import re

def update_file(file_path, data_updates):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    updated_count = 0
    for poi_id, ro_desc, ro_facts in data_updates:
        id_search = f'id: "{poi_id}"'
        id_pos = content.find(id_search)
        if id_pos == -1:
            continue
            
        # Find the end of this POI
        next_poi_pos = content.find('  {', id_pos + len(id_search))
        if next_poi_pos == -1:
            next_poi_pos = content.find('];', id_pos)
            
        poi_block = content[id_pos:next_poi_pos]
        new_poi_block = poi_block
        changed = False
        
        # Update descriptionAdvanced.ro
        da_start = new_poi_block.find("descriptionAdvanced:")
        if da_start != -1:
            da_end = new_poi_block.find("}", da_start) + 1
            da_block = new_poi_block[da_start:da_end]
            if 'ro: ""' in da_block:
                new_da_block = da_block.replace('ro: ""', f'ro: "{ro_desc}"')
                new_poi_block = new_poi_block.replace(da_block, new_da_block)
                changed = True

        # Update factsAdvanced.ro
        fa_start = new_poi_block.find("factsAdvanced:")
        if fa_start != -1:
            brace_count = 0
            fa_end = -1
            for i in range(fa_start, len(new_poi_block)):
                if new_poi_block[i] == '{':
                    brace_count += 1
                elif new_poi_block[i] == '}':
                    brace_count -= 1
                    if brace_count == 0:
                        fa_end = i + 1
                        break
            if fa_end != -1:
                fa_block = new_poi_block[fa_start:fa_end]
                if 'ro: []' in fa_block:
                    facts_list_str = ", ".join([f'"{f}"' for f in ro_facts])
                    new_fa_block = fa_block.replace('ro: []', f'ro: [{facts_list_str}]')
                    new_poi_block = new_poi_block.replace(fa_block, new_fa_block)
                    changed = True
        
        if changed:
            content = content.replace(poi_block, new_poi_block)
            updated_count += 1
                
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return updated_count

data = [
    ("cristo-concordia-landmarks-v2", "Statuia Cristo de la Concordia din Cochabamba este un monument impresionant și unul dintre cele mai cunoscute repere ale Boliviei. Situată pe vârful dealului San Pedro, aceasta oferă o vedere panoramică uluitoare de 360 de grade asupra orașului și a văii înconjurătoare. Cu o înălțime totală de peste 40 de metri, este una dintre cele mai mari statui ale lui Iisus din lume, depășind chiar și faimoasa statuie din Rio de Janeiro. Vizitatorii pot ajunge în vârf fie urcând cele peste 1.300 de trepte, fie folosind telecabina modernă. Monumentul nu este doar un simbol religios, ci și un punct de întâlnire esențial pentru turiști și localnici.", ["Statuia are o înălțime de 34,20 metri, plus un soclu de 6,24 metri.", "În anumite zile, vizitatorii pot urca în interiorul statuii până la brațele acesteia.", "Proiectul a fost realizat de sculptorii bolivieni César și Wálter Terrazas Pardo.", "Construcția a durat șapte ani și a fost finanțată prin donații publice.", "Statuia cântărește aproximativ 2.200 de tone și este realizată din beton armat."]),
    ("basilica-san-francisco-landmarks-v2", "Basilica San Francisco este una dintre cele mai importante bijuterii arhitecturale din La Paz și un exemplu remarcabil al stilului baroc andin. Fațada bisericii este bogat decorată cu sculpturi în piatră care prezintă un amestec fascinant de simbolism creștin și motive indigene, cum ar fi măști și plante locale. Mănăstirea adiacentă găzduiește astăzi un muzeu care oferă perspective asupra istoriei religioase și artei din Bolivia. Un punct de atracție special este accesul pe acoperiș, de unde se poate admira o vedere spectaculoasă asupra pieței aglomerate și a piețelor de vrăjitoare din apropiere. Biserica a fost timp de secole un centru vital pentru adunările religioase și sociale ale orașului.", ["Structura actuală a fost construită între 1743 și 1784 pe ruinele unei capele din 1548.", "Fațada integrează discret reprezentări ale 'Pachamama' (Mama Pământ) în simbolistica creștină.", "Turnul cu ceas al basilicii este un punct de reper distinctiv în panorama centrului istoric.", "Biserica a fost construită din blocuri masive de piatră rezistente la clima aspră a Anzilor.", "Interiorul adăpostește un altar principal magnific, bogat decorat cu foiță de aur."]),
    ("catedral-metropolitana-sucre-landmarks-v2", "Catedrala din Sucre, cunoscută și sub numele de Basilica Maicii Domnului din Guadalupe, este un monument emblematic al „Orașului Alb”. Construcția sa s-a întins pe parcursul mai multor secole, rezultând o combinație unică de stiluri renascentist, baroc și neoclasic. Catedrala adăpostește o colecție valoroasă de artă sacră, inclusiv celebra „Virgen de Guadalupe”, împodobită cu nenumărate bijuterii și perle. Turnul cu ceas este deosebit de proeminent, definind peisajul urban și fiind vizibil de la mare distanță. Ca centru spiritual al orașului, catedrala joacă un rol central în toate sărbătorile religioase importante din Sucre.", ["Capela Fecioarei de Guadalupe din interior este considerată unul dintre cele mai valoroase locuri din Bolivia.", "Muzeul de Artă Sacră al catedralei expune relicve rare și picturi coloniale.", "Construcția catedralei a durat aproape 150 de ani până la atingerea formei actuale.", "Zidurile albe reflectă lumina intensă a soarelui andin, contribuind la farmecul orașului Sucre.", "Clopotele catedralei cheamă locuitorii la rugăciune și festivități de sute de ani."]),
    ("plaza-murillo-landmarks-v2", "Plaza Murillo reprezintă inima politică și istorică a orașului La Paz și a întregii Bolivii. Înconjurată de Palatul Guvernului (Palacio Quemado), clădirea Parlamentului și catedrala impunătoare, această piață a fost scena multor revoluții și proclamații politice semnificative. În centru se află un monument dedicat lui Pedro Domingo Murillo, un erou al luptei pentru independență împotriva Spaniei. Astăzi, piața este un loc plin de viață unde localnicii se întâlnesc, turiștii admiră arhitectura și mii de porumbei sunt hrăniți. O vizită aici este esențială pentru a înțelege istoria vibrantă și atmosfera politică actuală a țării.", ["Piața se numea inițial Plaza de Armas și a fost redenumită ulterior în onoarea lui Murillo.", "Pe clădirea Parlamentului se află un ceas ale cărui cifre și ace se mișcă „invers” (în sens invers acelor de ceasornic).", "Plaza Murillo este situată la o altitudine de aproximativ 3.640 de metri deasupra nivelului mării.", "Palacio Quemado își datorează numele unui incendiu izbucnit în timpul unei revolte din 1875.", "Garda prezidențială în uniforme istorice este o prezență obișnuită și un motiv foto popular."]),
    ("convento-santa-teresa-landmarks-v2", "Mănăstirea Santa Teresa din Cochabamba este o relicvă fascinantă din perioada colonială și un loc de liniște în mijlocul orașului modern. Fondată în anul 1760, aceasta a adăpostit timp de secole călugărițe din ordinul Carmelitelor Desculțe, care trăiau în izolare strictă. Arhitectura mănăstirii, cu zidurile sale groase de chirpici și mănăstirile răcoroase, este perfect adaptată la climă și la nevoile spirituale. Astăzi, mănăstirea funcționează ca muzeu și centru cultural, permițând vizitatorilor să vadă chiliile călugărițelor, capela și opere de artă sacră valoroase. Este un loc care menține vie istoria devotamentului și a vieții monahale din Bolivia.", ["Mănăstirea a fost recent restaurată integral pentru a-i păstra splendoarea arhitecturală.", "Complexul include mai multe curți interioare superbe cu grădini tradiționale.", "În biserica mănăstirii se găsesc altare baroce impresionante realizate din lemn aurit.", "Călugărițele comunicau anterior cu lumea exterioară doar printr-un disc de lemn rotativ.", "Este considerată una dintre cele mai bine conservate mănăstiri coloniale de femei din toată Bolivia."]),
    ("catedral-nuestra-senora-la-paz-landmarks-v2", "Catedrala din La Paz, oficial Basilica Maicii Domnului din La Paz, se înalță maiestuos în Plaza Murillo, centrul politic al Boliviei. Construcția sa a început în anul 1835 și s-a întins pe aproape un secol, fiind sfințită în cele din urmă în 1925. Arhitectura neoclasică, cu zidurile sale masive și cupola elegantă de sticlă, conferă clădirii o prezență impunătoare. În interior, catedrala impresionează prin bolțile înalte, vitraliile artistice și un altar realizat din marmură italiană. De asemenea, adăpostește mausoleul lui Andrés de Santa Cruz, unul dintre părinții fondatori ai țării, fiind un loc central pentru ceremonii de stat și religioase.", ["Catedrala a fost construită pe un teren care a găzduit anterior una dintre primele biserici ale orașului.", "Vitraliile au fost fabricate în Europa și prezintă scene biblice de o înaltă calitate artistică.", "Datorită locației în pantă a orașului, fundația a fost construită deosebit de adâncă și stabilă.", "Mausoleul mareșalului Andrés de Santa Cruz este păzit permanent de o gardă de onoare.", "În zilele de sărbătoare, cupola catedralei este iluminată deasupra centrului istoric al orașului."]),
    ("estadio-hernando-siles-landmarks-v2", "Stadionul Hernando Siles din La Paz este mult mai mult decât un simplu stadion de fotbal; este o fortăreață în nori. Situat în cartierul Miraflores, la peste 3.600 de metri altitudine, este faimos pentru aerul rarefiat care pune adesea la încercare limitele fizice ale echipelor vizitatoare. Stadionul este casa echipei naționale a Boliviei și locul unde se desfășoară cele mai aprinse derby-uri locale între cluburile de top Bolívar și The Strongest. Atmosfera la meciurile internaționale este electrizantă, cu zeci de mii de fani care își susțin cu pasiune echipa. Pentru mulți pasionați de fotbal, o vizită la acest loc plin de istorie este obligatorie într-o călătorie în Bolivia.", ["Brazilia și Argentina au pierdut aici meciuri importante de calificare împotriva Boliviei.", "FIFA a încercat de mai multe ori să interzică meciurile la această altitudine din motive de siguranță.", "Stadionul a fost deschis în 1930 și modernizat ulterior pentru competiții internaționale.", "Pe lângă fotbal, aici au loc competiții mari de atletism și concerte în aer liber.", "Din tribunele superioare se poate admira o vedere fantastică asupra munților Anzi înconjurători."]),
    ("estacion-central-mi-teleferico-landmarks-v2", "Gara Centrală Mi Teleférico este un exemplu fascinant de îmbinare între istorie și infrastructură modernă. Clădirea istorică a fost odată cea mai importantă gară din La Paz și a fost restaurată cu grijă pentru a servi astăzi ca nod central pentru sistemul inovator de telecabine. De aici pornește Linia Roșie (Línea Roja), care leagă părțile joase ale orașului de platoul înalt din El Alto. Stația nu este doar un mijloc de transport, ci și un loc de întâlnire cultural, cu cafenele mici și zone de expoziție. O călătorie de aici oferă una dintre cele mai spectaculoase vederi asupra mării de case din La Paz și a vârfurilor înzăpezite din jur.", ["Mi Teleférico deține recordul mondial Guinness pentru cea mai lungă rețea urbană de telecabine.", "Stația păstrează multe elemente originale ale arhitecturii feroviare de la începutul secolului XX.", "Călătoria de la stația centrală la El Alto durează doar 10 minute și urcă sute de metri în altitudine.", "Sistemul de telecabine a revoluționat naveta între orașe și a redus impactul asupra mediului.", "Noaptea, stațiile și cabinele sunt iluminate, formând o rețea strălucitoare deasupra orașului."]),
    ("puente-de-las-americas-landmarks-v2", "Podul Americilor este una dintre cele mai distinctive structuri de inginerie din La Paz și o parte esențială a fluxului de trafic urban. Acest pod elegant suspendat traversează un defileu adânc, conectând zona aglomerată Miraflores cu cartierul la modă Sopocachi. De la inaugurarea sa, a redus considerabil timpul de deplasare și a devenit un simbol al modernizării orașului. Pentru pietoni, podul oferă o priveliște uluitoare, deși ușor amețitoare, asupra caselor de dedesubt și a topografiei dramatice a orașului. În special noaptea, podul este o priveliște atractivă, structura sa fiind puternic iluminată.", ["Podul a fost construit în anii '90 pentru a decongestiona străzile centrale supraaglomerate.", "Cu vopseaua sa portocalie distinctivă, este ușor de recunoscut din multe părți ale orașului.", "Este un loc preferat de fotografi pentru contrastul dintre arhitectura modernă și pantele abrupte.", "Podul necesită întreținere regulată pentru a rezista variațiilor extreme de temperatură la această altitudine.", "Numele său onorează statele americane și simbolizează legătura regională."]),
    ("iglesia-curahuara-carangas-landmarks-v2", "Biserica din Curahuara de Carangas este o bijuterie ascunsă pe vastul Altiplano bolivian. În ciuda exteriorului său modest, adăpostește în interior unele dintre cele mai magnifice picturi murale coloniale din America de Sud, ceea ce i-a adus supranumele de „Capela Sixtină a Anzilor”. Frescele acoperă aproape fiecare suprafață a interiorului și prezintă scene biblice adaptate de artiștii indigeni cu detalii locale. Aceste opere de artă au servit odată la transmiterea vizuală a doctrinei creștine către populația locală. Biserica este situată într-un peisaj arid, dar frumos, nu departe de maiestuosul vulcan Sajama.", ["Frescele datează de la începutul secolului al XVII-lea și au fost pictate cu pigmenți naturali.", "În picturi pot fi observate adesea animale locale, cum ar fi lamele, integrate în poveștile biblice.", "Biserica este construită din materiale simple, cum ar fi piatra și lutul, în contrast cu interiorul prețios.", "A fost declarată Monument Național al Boliviei pentru a proteja picturile sale unice.", "Curahuara de Carangas a fost un punct important pe ruta comercială colonială dintre Potosí și Pacific."]),
    ("santuario-virgen-socavon-landmarks-v2", "Sanctuarul Fecioarei din Socavón este inima spirituală a orașului Oruro și este strâns legat de istoria minieră a regiunii. Biserica a fost construită chiar deasupra intrării unei vechi mine de argint și adăpostește imaginea venerată a „Fecioarei din Gura Minei”. În fiecare an, în timpul carnavalului, sanctuarul devine scena unei procesiuni impresionante, unde mii de dansatori în costume colorate îi aduc omagiu Fecioarei. Sub biserică se află un muzeu minier care oferă o perspectivă autentică asupra condițiilor grele de muncă ale minerilor din secolele trecute. Pentru oamenii din Oruro, acest loc este un simbol al protecției, speranței și identității culturale.", ["'Diablada', dansul diavolilor, este cea mai cunoscută parte a carnavalului și se termină aici.", "Minerii vin aici pentru a se ruga pentru siguranță în timpul muncii periculoase din subteran.", "În mina de sub biserică poate fi văzută o statuie a lui 'Tio' (Unchiul), stăpânul lumii subterane.", "Sărbătoarea a fost recunoscută de UNESCO ca capodoperă a patrimoniului oral și imaterial al umanității.", "Din piața din fața sanctuarului se poate admira o vedere largă asupra acoperișurilor orașului minier."]),
    ("catedral-san-lorenzo-landmarks-v2", "Catedrala San Lorenzo este cea mai proeminentă clădire din centrul orașului Santa Cruz de la Sierra și o mărturie a arhitecturii coloniale tropicale. Cu fațada sa din cărămidă roșie strălucitoare, se distinge clar de catedralele din zonele muntoase mai reci. Interiorul bisericii este surprinzător de simplu, dar impresionează prin bolțile superbe de lemn și detaliile realizate manual. Catedrala este situată chiar în Plaza 24 de Septiembre, centrul vibrant al vieții urbane. O experiență specială este urcarea în unul dintre turnurile cu clopote, de unde se poate admira o vedere panoramică superbă asupra palmierilor din piață și a mării de case a orașului.", ["Structura actuală a fost finalizată la sfârșitul secolului al XIX-lea, după mai multe încercări.", "Altarul principal este decorat cu argintărie fină provenită de la misiunile iezuite din împrejurimi.", "În interior se află un mic muzeu cu obiecte religioase și veșminte istorice.", "Catedrala este un refugiu popular împotriva căldurii tropicale pentru localnici și vizitatori.", "Arhitectura sa prezintă influențe din diferite epoci, oferindu-i un aspect eclectic și unic."]),
    ("monumento-virgen-socavon-landmarks-v2", "Monumentul Fecioarei din Socavón este o dovadă impresionantă a credinței și a ingineriei din Oruro. Cu o înălțime de 45 de metri, depășește chiar și faimoasa statuie a lui Hristos din Rio de Janeiro și domină orizontul orașului de pe vârful dealului Santa Bárbara. Statuia o reprezintă pe sfânta patroană a minerilor și este recunoscută de departe ca un simbol alb strălucitor al speranței. Vizitatorii pot urca în interiorul statuii, unde se află capele și săli de expoziție. Punctul culminant al vizitei este vederea de pe platforma de observație situată în capul Fecioarei, care oferă o perspectivă inegalabilă asupra Altiplano și a minelor de exploatare.", ["Monumentul a fost inaugurat în 2013, la timp pentru celebrul carnaval din Oruro.", "Are opt etaje și este construit pentru a rezista vânturilor puternice de pe deal.", "Statuia ține un sceptru și un prunc Iisus în brațe, ambele realizate cu mare detaliu.", "Noaptea, statuia este iluminată cu proiectoare puternice și este vizibilă de la kilometri distanță.", "Proiectul a fost realizat printr-o colaborare strânsă între artiști, ingineri și municipalitate."]),
    ("iglesia-recoleta-landmarks-v2", "Biserica La Recoleta se află maiestuos la poalele dealului Churuquella și este unul dintre cele mai idilice locuri din Sucre. Fondată în anul 1601, mănăstirea franciscană este cunoscută pentru chiliile sale liniștite și piața superbă din față, mărginită de un rând elegant de arcade. Vizitatorii vin aici în special pentru a se bucura de apusul spectaculos, când soarele scaldă „Orașul Alb” într-o lumină caldă și aurie. Muzeul adiacent păstrează comori prețioase de artă sacră și oferă perspective asupra vieții călugărilor de-a lungul secolelor. O plimbare la Recoleta este obligatorie pentru orice vizitator al orașului Sucre care caută liniște și frumusețe.", ["În mijlocul pieței din fața bisericii se află un cedru vechi de secole, simbol local.", "Biserica găzduiește strane de cor impresionante realizate din lemn sculptat manual.", "Sub mănăstire se află catacombe care pot fi vizitate parțial.", "Punctul de observație (Mirador) de la Recoleta este un loc preferat de întâlnire pentru artiști.", "Mănăstirea a fost un centru important pentru activitățile misionare în regiune în timpul colonizării."]),
    ("torre-compania-jesus-landmarks-v2", "Turnul Companiei lui Iisus este un vestigiu iconic al puterii de odinioară a ordinului iezuit în Potosí. În timp ce biserica aferentă a fost distrusă de un cutremur în secolul al XVIII-lea, clopotnița magnifică a supraviețuit ca monument de sine stătător. Fațada sa este o capodoperă a stilului baroc mestizo, decorată cu sculpturi fine în piatră care îmbină artistic motive religioase și andine. Astăzi, turnul servește ca punct de informare turistică și oferă vizitatorilor posibilitatea de a urca pe platforma de observație printr-o scară îngustă. De sus se deschide o vedere spectaculoasă asupra centrului istoric, a Casei de la Moneda și a omniprezentului Cerro Rico.", ["Turnul a fost construit la începutul secolului XVIII, când Potosí era printre cele mai bogate orașe.", "Sculpturile includ îngeri cu trăsături indigene și fructe locale.", "Întreaga construcție a fost realizată din piatra roșiatică locală specifică regiunii.", "În perioada Crăciunului, turnul este centrul unor iluminări și evenimente festive.", "Este considerat unul dintre cele mai bune exemple de combinare a arhitecturii europene cu arta indigenă."]),
    ("mision-san-javier-landmarks-v2", "Misiunea San Javier este poarta de intrare în lumea fascinantă a misiunilor Chiquitos și cea mai veche de acest fel din Bolivia. Fondată în anul 1691, aceasta îmbină în mod unic arhitectura barocă europeană cu tradițiile meșteșugărești indigene. Biserica este construită aproape în întregime din lemn, cu coloane masive sculptate care susțin acoperișul uriaș. În interior domnește o atmosferă caldă, marcată de picturi artistice și o acustică excepțională. Sub conducerea părintelui elvețian Martin Schmid, misiunea a devenit un centru pentru muzică și artizanat. Astăzi, face parte din Patrimoniul Mondial UNESCO și este un monument viu al unei fuziuni culturale reușite.", ["Biserica a fost restaurată cu grijă de Hans Roth în secolul XX pentru a salva structura originală.", "În San Javier a fost descoperită o colecție importantă de partituri de muzică barocă.", "Sculpturile de pe altare au fost realizate de artiști locali Chiquitano cu o precizie uimitoare.", "Clădirea este proiectată să reziste căldurii și umidității tropicale.", "În fiecare an are loc aici un festival internațional de muzică barocă ce atrage vizitatori din toată lumea."]),
    ("mision-concepcion-landmarks-v2", "Misiunea Concepción este considerată bijuteria culturală a regiunii Chiquitania și este renumită pentru arhitectura sa magnifică și bogata moștenire muzicală. Biserica, a cărei formă actuală a fost finalizată în secolul al XVIII-lea sub îndrumarea părintelui Martin Schmid, impresionează prin sculpturile filigrane în lemn și picturile colorate ale fațadei. În arhiva adiacentă sunt păstrate sute de partituri originale din perioada barocă, mărturie a înaltei educații muzicale din misiune. Atmosfera liniștită a satului și aspectul impunător al bisericii fac din Concepción una dintre cele mai populare destinații pentru turismul cultural. Misiunea nu este doar un muzeu, ci rămâne un loc viu de cult și viață comunitară.", ["Concepción este sediul principal al ansamblului de muzică barocă al misiunilor Chiquitos.", "Altarul principal este o capodoperă a tehnicii poleirii cu aur, radiind splendoare în interiorul bisericii.", "Restaurarea bisericii în anii '70 a fost unul dintre cele mai ambițioase proiecte din Bolivia.", "Biserica are o colecție impresionantă de statui de sfinți realizate în tradiția artistică locală.", "Satul își păstrează dispunerea tradițională în jurul unei piețe mari, acoperite cu iarbă."]),
    ("obelisco-la-paz-landmarks-v2", "Obeliscul din La Paz este un punct de reper inconfundabil în inima centrului aglomerat al orașului. Ridicat în anii 1930 la intersecția unor artere principale importante, acesta marchează tranziția între cartierul istoric și centrele comerciale moderne. Turnul subțire de piatră se află pe o piață mică care, în ciuda traficului din jur, este un loc de întâlnire popular pentru localnici și protestatari. În imediata sa vecinătate se află bănci, clădiri guvernamentale și numeroase magazine care reflectă viața pulsantă a metropolei. Pentru vizitatori, obeliscul este adesea punctul de plecare pentru explorări prin străzile abrupte ale centrului orașului.", ["Obeliscul are o înălțime de aproximativ 18 metri și a fost realizat din piatra masivă.", "Comemorează fondarea republicii și spiritul de libertate al Boliviei.", "În ciuda locației centrale, piața din jurul obeliscului pare o mică insulă în haosul traficului.", "Este un punct strategic pentru multe marșuri de protest care se opresc aici înainte de a merge spre Plaza Murillo.", "De aici se poate ajunge pe jos în doar câteva minute la celebra Basilica de San Francisco."]),
    ("mercado-brujas-landmarks-v2", "Mercado de las Brujas, sau Piața Vrăjitoarelor, este unul dintre cele mai fascinante și neobișnuite locuri din La Paz. Situată pe străzile înguste cu piatră cubică de lângă strada Sagarnaga, oferă o perspectivă profundă asupra mitologiei andine și a medicinei populare. Aici, „vrăjitoarele” și herboriștii vând de la plante medicinale și amulete până la pachete rituale pentru ofrande aduse zeiței pământului, Pachamama. Deosebit de faimoși sunt fetușii de lama uscați, care sunt îngropați sub fundațiile caselor noi pentru a aduce noroc și protecție. Piața este un amestec viu de tradiții vechi și turism modern care captivează fiecare vizitator.", ["'Yatiris' (ghicitorii) pot fi recunoscuți după pălăriile lor închise la culoare și sacii cu frunze de coca.", "Piața este deschisă zilnic, dar consultările rituale au loc de obicei la primele ore ale dimineții.", "Pe lângă articole spirituale, se găsesc și textile superbe realizate manual din lână de alpaca.", "Fotografiatul ar trebui făcut doar cu permisiune, deoarece mulți vânzători consideră marfa sacră.", "Numele de 'Piața Vrăjitoarelor' este mai degrabă turistic; pentru localnici este un loc serios de medicină."]),
    ("convento-san-felipe-neri-landmarks-v2", "Mănăstirea San Felipe Neri din Sucre este o bijuterie arhitecturală a perioadei coloniale, cunoscută pentru fațada sa albă strălucitoare. Fosta mănăstire impresionează prin curțile sale neoclasice vaste și atmosfera liniștită a curților sale interioare. Un punct culminant absolut pentru vizitatori este urcarea pe acoperișul extins din teracotă. De acolo se deschide o vedere panoramică inegalabilă asupra „Orașului Alb”, cu nenumăratele sale turnuri de biserici și acoperișuri roșii. Clădirea este folosită astăzi parțial ca școală, dar își păstrează farmecul istoric și este o destinație obligatorie pentru fotografi și pasionații de arhitectură.", ["Mănăstirea a fost construită cu piatră roșiatică locală, vopsită ulterior în alb pentru estetica orașului.", "În zilele senine, de pe acoperiș se poate vedea până la vârfurile îndepărtate ale munților Anzi.", "Turnurile cu clopote ale mănăstirii sunt decorate cu fragmente de porțelan spaniol antic.", "În interior se află picturi religioase importante din secolele XVIII și XIX.", "Accesul pe acoperiș se face printr-o scară de piatră îngustă, încărcată de istorie."]),
    ("iglesia-san-lorenzo-landmarks-v2", "Biserica San Lorenzo de Carangas din Potosí este faimoasă pentru portalul său excepțional, considerat unul dintre cele mai bune exemple de baroc mestizo din lume. Sculpturile în piatră ale fațadei sunt de o detaliere incredibilă și prezintă o fuziune fascinantă între motivele creștine și cosmologia indigenă andină. Se pot găsi acolo simboluri precum soarele, luna și stelele alături de sfinți creștini și îngeri. Biserica a fost ridicată inițial în secolul al XVI-lea pentru comunitatea indigenă a populației Carangas care lucra în minele de argint. Astăzi este inclusă în Patrimoniul Mondial UNESCO și atrage istorici de artă și turiști pentru a admira această mărturie în piatră a istoriei coloniale.", ["Actuala fațadă barocă a fost adăugată între anii 1728 și 1744.", "Pe părțile laterale ale portalului pot fi văzute două sirene care cântă la instrumente locale (charangos).", "În interior, biserica impresionează printr-o cupolă superbă de lemn în stil mudéjar.", "Sculpturile fine au fost realizate din gresia roșiatică locală, ușor de modelat.", "Biserica a făcut parte odată dintr-un complex monahal mai mare, care astăzi a dispărut în mare parte."]),
    ("cementerio-de-trenes-landmarks-v2", "Cementerio de Trenes, sau Cimitirul Trenurilor, de la marginea orașului Uyuni, este unul dintre cele mai suprarealiste locuri din Bolivia. Aici se odihnesc rămășițele a zeci de locomotive cu aburi și vagoane britanice care au fost folosite la sfârșitul secolului XIX și începutul secolului XX pentru transportul mineralelor către porturile de la Pacific. După prăbușirea industriei miniere în anii 1940, trenurile au fost pur și simplu abandonate în deșert. Vântul sărat și aerul uscat au corodat metalul de-a lungul deceniilor, transformându-l în schelete ruginite. Astăzi, locul este un muzeu fascinant în aer liber și o primă oprire populară pentru orice tur în celebrul Salar de Uyuni.", ["Majoritatea locomotivelor au fost importate din Marea Britanie și erau avansate pentru acea vreme.", "Cimitirul de trenuri se află la doar aproximativ 3 kilometri de centrul orașului Uyuni.", "Vizitatorii se pot urca pe trenurile ruginite și pot privi în interiorul vechilor cabine de conducere.", "Locul a servit deja ca scenă spectaculoasă pentru numeroase filme și videoclipuri muzicale.", "Liniștea deșertului și giganții ruginiți creează o atmosferă melancolică, aproape post-apocaliptică."]),
    ("catedral-potosi-landmarks-v2", "Catedrala din Potosí este unul dintre cele mai magnifice exemple de arhitectură neoclasică din Bolivia. Construită la începutul secolului XIX pe ruinele unei biserici anterioare prăbușite, aceasta reflectă bogăția inimaginabilă de odinioară a orașului argintului. Fațada monumentală de piatră, cu coloanele sale corintice, domină Plaza 10 de Noviembre. În interior, catedrala impresionează prin bolțile înalte și luminoase, picturi valoroase ale școlii Potosí și un altar bogat decorat cu foiță de aur. Ca sediu al episcopiei de Potosí, rămâne până astăzi centrul vieții religioase și un simbol mândru al istoriei orașului.", ["Actuala catedrală a fost construită după planurile arhitectului spaniol Manuel de Sanahuja.", "Turnurile sale oferă o vedere panoramică fantastică asupra centrului istoric și a dealului Cerro Rico.", "În cripta catedralei se află mormintele unor personalități importante și ale unor înalți prelați.", "Construcția a durat aproape 30 de ani, fiind o realizare tehnică enormă pentru acea perioadă.", "Clădirea a fost restaurată de mai multe ori pentru a repara daunele cauzate de clima aspră andină."]),
    ("plaza-24-septiembre-landmarks-v2", "Plaza 24 de Septiembre este inima vibrantă a orașului Santa Cruz de la Sierra și un exemplu perfect al unui centru urban sud-american plin de viață. Sub palmierii uriași și copacii care oferă umbră, localnicii se întâlnesc pentru a juca șah, a discuta sau pur și simplu pentru a se bucura de atmosfera tropicală. Piața este mărginită de clădiri impresionante precum Catedrala San Lorenzo, Primăria și Centrul Cultural, toate emanând un farmec colonial. Aici tradiția se îmbină cu modernitatea, în timp ce muzicienii stradali cântă și turiștii se relaxează în cafenelele din jur. Este locul perfect pentru a cunoaște ritmul relaxat al culturii „Camba”.", ["Anterior piața era cunoscută sub numele de Plaza de Armas, înainte de a fi redenumită în cinstea revoltei din 1810.", "La colțurile pieței se găsesc adesea vânzători tradiționali de 'Somó', o băutură tipică din porumb.", "În copacii din piață pot fi observați, cu puțin noroc, leneși care trăiesc acolo în liniște.", "Piața este animată aproape la orice oră din zi și din noapte, fiind considerată foarte sigură.", "Băncile și aleile au fost renovate recent, păstrându-se însă caracterul istoric."]),
    ("puente-trillizos-landmarks-v2", "Podurile Trillizos (Podurile Tripleți) sunt un exemplu impresionant de inginerie modernă în topografia provocatoare a orașului La Paz. Sistemul constă în trei poduri hobanate consecutive – Kantutani, Choqueyapu și Orkojahuira – care traversează defileuri adânci și conectează cartiere importante ale orașului. De la inaugurarea lor în anul 2010, au îmbunătățit considerabil fluxul de trafic și au redus timpii de deplasare pentru mii de navetiști. Podurile nu sunt doar funcționale, ci și plăcute estetic, fiind adesea iluminate colorat pe timp de noapte. Pentru vizitatori, ele oferă o nouă perspectivă asupra pantelor abrupte și a mării de case a orașului.", ["Fiecare dintre cele trei poduri are un nume propriu care se referă la râul sau valea pe care o traversează.", "Construcția a fost unul dintre cele mai ambițioase proiecte de infrastructură din istoria recentă a La Paz.", "În total, podurile au o lungime de aproape doi kilometri, inclusiv drumurile de acces.", "Pilonii podurilor sunt proiectați să amortizeze activitățile seismice din regiune.", "De pe podul Orkojahuira se poate admira o vedere fantastică spre vârful înzăpezit al muntelui Illimani."]),
    ("mirador-killi-killi-landmarks-v2", "Mirador Killi Killi este fără îndoială unul dintre cele mai spectaculoase puncte de observație din La Paz. Situat pe un deal din cartierul Villa Pabón, oferă o vedere panoramică de 360 de grade de neegalat asupra întregului oraș, care se întinde ca un cazan uriaș sub picioarele tale. De aici se poate admira silueta distinctivă a muntelui Illimani, care veghează asupra orașului cu vârfurile sale înzăpezite. Punctul de observație este frumos amenajat, cu grădini terasate, bănci și mici locuri de joacă pentru copii. Este popular atât în rândul turiștilor pentru fotografii, cât și al localnicilor pentru un moment relaxant de liniște, în timp ce sub ei pulsează haosul metropolei.", ["Numele 'Killi Killi' provine de la un mic șoim care era foarte comun în această regiune.", "În timpul asediului indigen asupra La Paz din 1781, acest deal a servit ca punct strategic de observație.", "Punctul de observație este accesibil pe jos din centrul orașului, dar necesită o urcare abruptă.", "La amurg, locul oferă o atmosferă magică pe măsură ce luminile orașului se aprind treptat.", "În zilele senine, de aici se poate vedea aproape întregul sistem de telecabine urbane în acțiune."]),
    ("mercado-la-cancha-landmarks-v2", "Mercado La Cancha din Cochabamba nu este o piață obișnuită; este un oraș în interiorul orașului și o experiență pentru toate simțurile. Este considerată una dintre cele mai mari piețe în aer liber din America de Sud, întinzându-se pe numeroase cvartale de case în sudul orașului. Aici se poate găsi absolut orice: de la fructe exotice și condimente parfumate până la haine lucrate manual, electronice și remedii tradiționale. Labirintul de pasaje înguste și tarabe colorate este inima economică a regiunii și un creuzet al culturilor. O vizită la La Cancha este o lecție despre viața de zi cu zi boliviană și oferă ocazia de a gusta gastronomia locală autentică la nenumăratele tarabe de mâncare.", ["Piața este deschisă șapte zile pe săptămână, dar atinge punctul maxim miercurea și sâmbăta.", "Există sectoare specializate, cum ar fi „piața vrăjitoarelor” din interiorul La Cancha pentru articole spirituale.", "Navigarea necesită simț al orientării, deoarece este ușor să te pierzi pe aleile similare.", "Negocierea prețului face parte din experiența de cumpărare și este o practică obișnuită.", "Se recomandă măsuri de precauție, deoarece aglomerația densă poate atrage hoții de buzunare."]),
    ("monumento-eduardo-abaroa-landmarks-v2", "Monumentul dedicat lui Eduardo Abaroa se află în centrul pieței cu același nume din elegantul cartier Sopocachi din La Paz. Acesta îl onorează pe eroul național bolivian care a căzut în 1879, în timpul Războiului Salpetrului (Guerra del Pacífico), apărând podul Topáter. Abaroa este un simbol al curajului neclintit și al dorinței profund înrădăcinate a Boliviei de a avea acces suveran la mare. Monumentul îl înfățișează într-o poză eroică și este locul unor ceremonii naționale de comemorare importante, în special de „Ziua Mării”. Piața înconjurătoare este o oază de verdeață, utilizată de studenți, familii și artiști pentru pauze și întâlniri.", ["Ultimele cuvinte celebre ale lui Abaroa, prin care a refuzat să se predea, sunt legendare în Bolivia.", "Monumentul devine anual, pe 23 martie, centrul unor mari parade militare și civile.", "Statuia a fost creată de un sculptor renumit și surprinde spiritul hotărât al eroului.", "Plaza Abaroa este înconjurată de unele dintre cele mai bune cafenele și restaurante din cartierul Sopocachi.", "Pentru mulți bolivieni, acest loc este un sanctuar al patriotismului și al speranței de a recupera coasta."]),
    ("mirador-laikakota-landmarks-v2", "Mirador Laikakota este un loc preferat al locuitorilor din La Paz și oferă una dintre cele mai frumoase și relaxante vederi ale orașului. Situat în Parque Urbano Central pe o creastă montană, acesta permite o privire panoramică asupra bazinului jos al orașului La Paz, de la zgârie-norii moderni din centru până la pantele abrupte din El Alto. Punctul de observație este integrat într-o zonă de parc deosebit de atractivă pentru familii, deoarece oferă zone de joacă vaste și alei bine întreținute. Este un loc ideal pentru a scăpa de agitația orașului pentru un moment și pentru a admira în liniște geografia unică a acestui „cazan” din munții Anzi.", ["Din mirador se vede direct spre spectaculoasele 'Puentes Trillizos' (Podurile Tripleți).", "Parcul este cunoscut pentru echipamentele de joacă proiectate creativ, adesea bazate pe legende locale.", "Accesul la mirador se face printr-o rampă modernă care este potrivită și pentru scaune cu rotile.", "În serile senine, se poate vedea cum marea de lumini din El Alto se revarsă pe munte.", "Numele 'Laikakota' provine din limba Aymara și este tradus adesea prin 'Lacul Vrăjitorilor'."]),
    ("basilica-copacabana-landmarks-v2", "Basilica Maicii Domnului din Copacabana este unul dintre cele mai importante locuri spirituale din America de Sud și este situată pitoresc pe malul lacului Titicaca. Clădirea de un alb strălucitor impresionează prin cupolele sale maure și plăcile ceramice colorate care strălucesc în lumina intensă andină. În interior adăpostește imaginea venerată din lemn a Fecioarei din Copacabana, sfânta patroană a Boliviei. Credincioși din toată țara și din Peru vin în pelerinaj aici pentru a cere binecuvântarea, în special în timpul ceremoniilor zilnice de sfințire a vehiculelor din fața bisericii. Basilica îmbină în mod unic credința catolică cu tradițiile indigene străvechi, fiind un loc de o importanță emoțională profundă.", ["Celebra statuie a 'Fecioarei Negre' a fost creată de artistul indigen Francisco Tito Yupanqui în secolul XVI.", "Biserica a fost ridicată peste un fost sanctuar incaș, subliniind continuitatea religioasă a locului.", "Sărbătoarea Fecioarei de pe 5 august este unul dintre cele mai mari și mai colorate evenimente religioase din Bolivia.", "Altarul basilicii este o capodoperă a artei baroce a poleirii cu aur.", "Zidurile albe ale basilicii formează un contrast spectaculos cu apa albastru închis a lacului Titicaca."])
]

cnt = update_file('/mnt/c/Users/User/plizio-repo/lib/visualLab/data/poiExtraBoliviaLandmarksV2.ts', data)
print(f"Updated {cnt} POIs in poiExtraBoliviaLandmarksV2.ts")
