
import json

pois = []

def add_poi(id, name_en, name_de, name_hu, name_ro, desc_en, desc_de, desc_hu, desc_ro, facts_en, facts_de, facts_hu, facts_ro):
    pois.append({
        "id": id,
        "translations": {
            "en": {"name": name_en, "descriptionAdvanced": desc_en, "factsAdvanced": facts_en},
            "de": {"name": name_de, "descriptionAdvanced": desc_de, "factsAdvanced": facts_de},
            "hu": {"name": name_hu, "descriptionAdvanced": desc_hu, "factsAdvanced": facts_hu},
            "ro": {"name": name_ro, "descriptionAdvanced": desc_ro, "factsAdvanced": facts_ro}
        }
    })

# POI 1: Sintra
add_poi(
    "cult-sintra", "Sintra", "Sintra", "Sintra", "Sintra",
    "The Cultural Landscape of Sintra, located on the Portuguese Riviera, represents a pioneering ensemble of European Romanticism. In the 19th century, King Ferdinand II transformed a ruined monastery into a palace, merging Gothic, Egyptian, Moorish, and Renaissance elements into a cohesive aesthetic. This mountain range, known as the Serra de Sintra, is dotted with historic villas, parks, and gardens that blend seamlessly with the lush natural environment. Notable sites include the Castle of the Moors, crowning a high peak since the 8th century, and the Quinta da Regaleira with its mystical initiation wells. The town's unique microclimate has long attracted the Portuguese royalty and elite, resulting in a dense concentration of architectural masterpieces. In 1995, UNESCO recognized Sintra as a World Heritage site, specifically highlighting the harmonious integration of human-made structures and the wild landscape.",
    "Die Kulturlandschaft von Sintra an der portugiesischen Riviera ist ein wegweisendes Ensemble der europäischen Romantik des 19. Jahrhunderts. König Ferdinand II. verwandelte hier ein verfallenes Kloster in einen prächtigen Palast und kombinierte dabei gotische, ägyptische, maurische und Renaissance-Elemente. Das Gebirge Serra de Sintra ist übersät mit historischen Villen, Parks und Gärten, die harmonisch in die üppige Vegetation eingebettet sind. Zu den bedeutendsten Sehenswürdigkeiten zählen das Castelo dos Mouros aus dem 8. Jahrhundert und die mystische Quinta da Regaleira mit ihren berühmten Einweihungsbrunnen. Dank des besonderen Mikroklimas war der Ort über Jahrhunderte die bevorzugte Sommerresidenz der portugiesischen Könige und des Adels. 1995 wurde Sintra von der UNESCO zum Weltkulturerbe erklärt, wobei besonders die Verbindung von Architektur und Natur gewürdigt wurde.",
    "Sintra kultúrtája a portugál Riviérán az európai romantika egyik úttörő együttese, amely a 19. században nyerte el mai formáját. II. Ferdinánd király egy romos kolostort alakított át palotává, ötvözve a gótikus, egyiptomi, mór és reneszánsz stílusjegyeket egy egyedülálló esztétikai egységbe. A Serra de Sintra hegység vonulatait történelmi villák, parkok és kertek tarkítják, amelyek szervesen illeszkednek a buja természeti környezetbe. A terület nevezetes látnivalói közé tartozik a 8. századból származó Mór vár, valamint a misztikus Quinta da Regaleira a híres beavatási kútjaival. A város különleges mikroklímája régóta vonzotta a portugál királyi családot és az elitet, ami az építészeti remekművek sűrű koncentrációját eredményezte. 1995-ben az UNESCO a világörökség részévé nyilvánította Sintra vidékét.",
    "Peisajul cultural din Sintra, situat pe Riviera Portugheză, reprezintă un ansamblu de pionierat al romantismului european din secolul al XIX-lea. Regele Ferdinand al II-lea a transformat o mănăstire ruinată într-un palat spectaculos, îmbinând elemente gotice, egiptene, maure și renascentiste. Munții Serra de Sintra sunt presărați cu vile istorice, parcuri și grădini care se integrează perfect în mediul natural luxuriant. Printre siturile notabile se numără Castelul Maurilor, care domină un vârf înalt încă din secolul al VIII-lea, și Quinta da Regaleira cu fântânile sale mistice de inițiere. Microclimatul unic al orașului a atras de mult timp regalitatea și elita portugheză, rezultând o concentrație densă de capodopere arhitecturale. În 1995, UNESCO a recunoscut Sintra ca sit al Patrimoniului Mondial, evidențiind integrarea armonioasă a structurilor umane în peisajul sălbatic.",
    ["Sintra was the first center of European Romantic architecture starting in the 1840s.", "The Moorish Castle dates back to the 8th and 9th centuries during the Muslim occupation.", "UNESCO inscribed the site in 1995 as the first Cultural Landscape in Europe.", "The National Palace of Sintra features two iconic 33-meter high conical chimneys.", "The Quinta da Regaleira contains a 27-meter deep initiation well with a spiral staircase.", "The Serra de Sintra mountain range rises to a maximum altitude of 528 meters."],
    ["Sintra war ab den 1840er Jahren das erste Zentrum der romantischen Architektur in Europa.", "Das maurische Schloss stammt aus dem 8. und 9. Jahrhundert aus der Zeit der muslimischen Herrschaft.", "Die UNESCO ernannte Sintra 1995 zur ersten Kulturlandschaft Europas auf der Welterbeliste.", "Der Nationalpalast von Sintra besitzt zwei markante, 33 Meter hohe konische Schornsteine.", "Die Quinta da Regaleira beherbergt einen 27 Meter tiefen Einweihungsbrunnen mit Wendeltreppe.", "Das Gebirge der Serra de Sintra erreicht eine maximale Höhe von 528 Metern über dem Meer."],
    ["Sintra volt az európai romantikus építészet első központja az 1840-es évektől kezdődően.", "A Mór vár a 8. és 9. századból, a muszlim megszállás idejéből származik.", "Az UNESCO 1995-ben Sintra vidékét Európa első kultúrtájaként vette fel a listára.", "A Sintra Nemzeti Palota két ikonikus, 33 méter magas kúpos kéménnyel rendelkezik.", "A Quinta da Regaleira egy 27 méter mély beavatási kutat rejt spirális lépcsősorral.", "A Serra de Sintra hegylánc legmagasabb pontja 528 méterrel magasodik a tengerszint fölé."],
    ["Sintra a fost primul centru al arhitecturii romantice europene, începând cu anii 1840.", "Castelul Maurilor datează din secolele VIII și IX, din timpul ocupației musulmane.", "UNESCO a înscris situl în 1995 ca fiind primul peisaj cultural din Europa.", "Palatul Național din Sintra are două coșuri de fum conice emblematice, înalte de 33 de metri.", "Quinta da Regaleira conține o fântână de inițiere adâncă de 27 de metri, cu o scară în spirală.", "Lanțul muntos Serra de Sintra atinge o altitudine maximă de 528 de metri."]
)

# POI 2: Jerónimos Monastery
add_poi(
    "cult-jeronimos", "Jerónimos Monastery", "Hieronymus-Kloster", "Jeromos-kolostor", "Mănăstirea Jerónimos",
    "The Jerónimos Monastery in Lisbon is a supreme example of the Manueline style, a uniquely Portuguese transition from Gothic to Renaissance. Commissioned by King Manuel I in 1501, it was funded by the immense wealth generated from Portugal's maritime discoveries in Africa and the East. The monastery was built on the site where Vasco da Gama and his crew spent their last night in prayer before departing for India in 1497. Its intricate stonework features maritime motifs such as coral, ropes, and armillary spheres, reflecting the era's global explorations. The complex survived the devastating 1755 earthquake with minimal damage, preserving its grand cloister and the Church of Santa Maria. Today, it serves as the final resting place for both Vasco da Gama and the great epic poet Luís de Camões.",
    "Das Hieronymus-Kloster in Lissabon ist ein herausragendes Beispiel der Manuelinik, eines einzigartigen portugiesischen Baustils am Übergang von der Gotik zur Renaissance. König Manuel I. gab den Bau im Jahr 1501 in Auftrag, finanziert durch den Reichtum aus den Entdeckungsreisen nach Afrika und Fernost. Es wurde an jener Stelle errichtet, an der Vasco da Gama und seine Mannschaft 1497 ihre letzte Nacht vor der Abreise nach Indien im Gebet verbrachten. Die detailreichen Steinmetzarbeiten zeigen maritime Motive wie Korallen, Taue und Armillarsphären, welche die Ära der großen Entdeckungen symbolisieren. Das Bauwerk überstand das verheerende Erdbeben von 1755 fast unbeschadet, wodurch der prächtige Kreuzgang und die Kirche Santa Maria erhalten blieben. In der Anlage befinden sich heute die Grabmäler von Vasco da Gama und dem Nationaldichter Luís de Camões.",
    "A lisszaboni Jeromos-kolostor a mánuel stílus legnagyszerűbb példája, amely a gótikából a reneszánszba való átmenet sajátos portugál változata. I. Mánuel király 1501-ben rendelte el az építését, amelyet a Portugália afrikai és keleti tengeri felfedezéseiből származó hatalmas vagyonból finanszíroztak. A kolostor azon a helyen épült, ahol Vasco da Gama és legénysége az utolsó éjszakáját imádsággal töltötte 1497-es indiai indulása előtt. A bonyolult kőfaragványok tengeri motívumokat, például korallokat, köteleket és armilláris gömböket ábrázolnak, tükrözve a korszak világméretű felfedezéseit. Az épületegyüttes minimális károkkal élte túl az 1755-ös pusztító földrengést, megőrizve grandiózus kerengőjét és a Szűz Mária-templomot. Ma itt található Vasco da Gama és a nagy epikus költő, Luís de Camões végső nyughelye is.",
    "Mănăstirea Jerónimos din Lisabona este un exemplu suprem al stilului manuelin, o tranziție unică portugheză de la gotic la renaștere. Comandată de regele Manuel I în 1501, construcția a fost finanțată din bogățiile imense generate de descoperirile maritime ale Portugaliei în Africa și Orient. Mănăstirea a fost ridicată pe locul unde Vasco da Gama și echipajul său și-au petrecut ultima noapte în rugăciune înainte de a pleca spre India în 1497. Sculptura sa complexă în piatră prezintă motive maritime, cum ar fi corali, frânghii și sfere armilare, reflectând explorările globale ale epocii. Complexul a supraviețuit devastatorului cutremur din 1755 cu daune minime, păstrându-și claustrul grandios și Biserica Santa Maria. Astăzi, servește ca loc de odihnă final atât pentru Vasco da Gama, cât și pentru marele poet epic Luís de Camões.",
    ["Construction of the monastery began in 1501 and took over 100 years to complete.", "The site was designated a UNESCO World Heritage site in 1983.", "It was funded by a 5% tax on spices brought back from India and Africa.", "The double-storey cloister is considered one of the most beautiful in the world.", "Vasco da Gama was buried here in a neo-Manueline tomb in the 19th century.", "The 1755 earthquake destroyed much of Lisbon but left the monastery largely intact."],
    ["Der Bau des Klosters begann 1501 und dauerte insgesamt über 100 Jahre.", "Die Anlage wurde im Jahr 1983 zum UNESCO-Weltkulturerbe erklärt.", "Finanziert wurde der Bau durch eine fünfprozentige Steuer auf Gewürze aus Indien.", "Der zweistöckige Kreuzgang gilt als einer der kunstvollsten weltweit.", "Vasco da Gama wurde hier im 19. Jahrhundert in einem manuelinischen Grab beigesetzt.", "Das Erdbeben von 1755 zerstörte weite Teile Lissabons, verschonte aber das Kloster."],
    ["A kolostor építése 1501-ben kezdődött és több mint 100 évig tartott.", "A helyszínt 1983-ban az UNESCO Világörökség részévé nyilvánították.", "Az építkezést az Indiából és Afrikából származó fűszerekre kivetett 5%-os adóból fizették.", "A kétszintes kerengőt a világ egyik legszebbjeként tartják számon.", "Vasco da Gamát a 19. században temették ide egy neománuel stílusú síremlékbe.", "Az 1755-ös földrengés Lisszabon nagy részét romba döntötte, de a kolostort épségben hagyta."],
    ["Construcția mănăstirii a început în 1501 și a durat peste 100 de ani.", "Situl a fost desemnat Patrimoniu Mondial UNESCO în anul 1983.", "A fost finanțată printr-o taxă de 5% pe condimentele aduse din India și Africa.", "Claustrul cu două etaje este considerat unul dintre cele mai frumoase din lume.", "Vasco da Gama a fost înmormântat aici într-un mormânt neo-manuelin în secolul al XIX-lea.", "Cutremurul din 1755 a distrus o mare parte din Lisabona, dar a lăsat mănăstirea intactă."]
)

# POI 3: Batalha Monastery
add_poi(
    "cult-batalha", "Batalha Monastery", "Kloster von Batalha", "Batalha-kolostor", "Mănăstirea Batalha",
    "The Monastery of Batalha, officially known as the Monastery of Saint Mary of the Victory, was built to commemorate the Portuguese victory over the Castilians at the Battle of Aljubarrota in 1385. This victory secured Portugal's independence and established the Aviz dynasty. The construction spanned seven reigns and about 130 years, resulting in a masterpiece of Late Gothic and Manueline architecture. One of its most striking features is the Founder's Chapel, where King John I and Queen Philippa of Lancaster are buried in a joint tomb. The Unfinished Chapels, left roofless since the 16th century, showcase the most exuberant Manueline ornamentation with their massive pillars and detailed stonework. This UNESCO World Heritage site stands as a monumental symbol of national identity and architectural innovation.",
    "Das Kloster von Batalha, offiziell Kloster Maria vom Siege, wurde zum Gedenken an den Sieg Portugals über Kastilien in der Schlacht von Aljubarrota im Jahr 1385 errichtet. Dieser militärische Erfolg sicherte die Unabhängigkeit Portugals und begründete die Dynastie von Avis. Die Bauzeit erstreckte sich über sieben Regierungsperioden und etwa 130 Jahre, was zu einem Meisterwerk der Spätgotik und Manuelinik führte. Ein besonderes Highlight ist die Kapelle des Gründers, in der König Johann I. und Königin Philippa von Lancaster in einem gemeinsamen Grab ruhen. Die unvollendeten Kapellen, die seit dem 16. Jahrhundert ohne Dach geblieben sind, zeigen mit ihren massiven Pfeilern die prächtigsten Verzierungen des manuelinischen Stils. Als UNESCO-Welterbestätte ist das Kloster ein bedeutendes Symbol für die portugiesische Geschichte.",
    "A Batalha-kolostor, hivatalos nevén Győzelmes Szűz Mária-kolostor, a portugálok kasztíliaiak felett aratott 1385-ös aljubarrotai győzelmének emlékére épült. Ez a diadal biztosította Portugália függetlenségét és alapozta meg az Avis-házat. Az építkezés hét uralkodón keresztül, körülbelül 130 éven át tartott, aminek eredményeként a késő gótikus és a mánuel építészet remekműve jött létre. Egyik leglátványosabb része az Alapító-kápolna, ahol I. János király és Lancasteri Filippa királyné közös sírban nyugszik. A Befejezetlen kápolnák, amelyek a 16. század óta tető nélkül állnak, a mánuel stílus legburjánzóbb díszítését mutatják be hatalmas pilléreikkel és részletgazdag kőfaragványaikkal. Ez az UNESCO világörökségi helyszín a nemzeti identitás és az építészeti innováció monumentális jelképe.",
    "Mănăstirea Batalha, cunoscută oficial sub numele de Mănăstirea Sfânta Maria a Victoriei, a fost construită pentru a comemora victoria portugheză asupra castilienilor în bătălia de la Aljubarrota din 1385. Această victorie a asigurat independența Portugaliei și a stabilit dinastia de Aviz. Construcția s-a întins pe parcursul a șapte domnii și aproximativ 130 de ani, rezultând o capodoperă a arhitecturii gotice târzii și manueline. Una dintre cele mai izbitoare trăsături ale sale este Capela Fondatorului, unde regele Ioan I și regina Philippa de Lancaster sunt înmormântați într-un mormânt comun. Capelele Neterminate, lăsate fără acoperiș din secolul al XVI-lea, prezintă cea mai exuberantă ornamentație manuelină, cu pilonii lor masivi și sculpturile detaliate. Acest sit UNESCO este un simbol monumental al identității naționale.",
    ["The Battle of Aljubarrota took place on August 14, 1385.", "Construction of the monastery began in 1386 under architect Afonso Domingues.", "The site was inscribed on the UNESCO World Heritage list in 1983.", "The Unfinished Chapels consist of seven chapels arranged around an octagonal space.", "The main nave of the church is over 32 meters high.", "The Founder's Chapel was the first royal pantheon built in Portugal."],
    ["Die Schlacht von Aljubarrota fand am 14. August 1385 statt.", "Der Bau des Klosters begann 1386 unter dem Architekten Afonso Domingues.", "Das Kloster wurde im Jahr 1983 in die UNESCO-Welterbeliste aufgenommen.", "Die unvollendeten Kapellen umfassen sieben Kapellen um einen achteckigen Raum.", "Das Hauptschiff der Kirche ist über 32 Meter hoch.", "Die Kapelle des Gründers war das erste königliche Pantheon in Portugal."],
    ["Az aljubarrotai csata 1385. augusztus 14-én zajlott le.", "A kolostor építése 1386-ban kezdődött Afonso Domingues építész vezetésével.", "A helyszín 1983-ban került fel az UNESCO Világörökség listájára.", "A Befejezetlen kápolnák hét kápolnából állnak egy nyolcszögletű tér körül.", "A templom főhajója több mint 32 méter magas.", "Az Alapító-kápolna volt az első Portugáliában épült királyi panteon."],
    ["Bătălia de la Aljubarrota a avut loc la 14 august 1385.", "Construcția mănăstirii a început în 1386 sub conducerea arhitectului Afonso Domingues.", "Situl a fost înscris pe lista Patrimoniului Mondial UNESCO în 1983.", "Capelele Neterminate constau în șapte capele dispuse în jurul unui spațiu octogonal.", "Nava principală a bisericii are o înălțime de peste 32 de metri.", "Capela Fondatorului a fost primul panteon regal construit în Portugalia."]
)

# POI 4: Guimarães Old Town
add_poi(
    "cult-guimaraes", "Guimarães Old Town", "Altstadt von Guimarães", "Guimarães óvárosa", "Centrul Vechi din Guimarães",
    "Guimarães is often called the 'cradle of Portuguese nationality' because it is widely believed that the country's first king, Afonso Henriques, was born here in the early 12th century. The historic center is an exceptionally well-preserved example of the evolution of a medieval settlement into a modern town. Its architecture is characterized by a specific technique involving granite and half-timbering, which was exported to Portuguese colonies across the world. The skyline is dominated by the medieval Guimarães Castle, which defended the young kingdom, and the Palace of the Dukes of Braganza, inspired by French manor houses. Strolling through the narrow streets of the Oliveira and Santiago squares reveals centuries of history carved into stone facades. In 2001, UNESCO recognized the historical center for its authenticity and architectural significance.",
    "Guimarães wird oft als die Wiege der portugiesischen Nation bezeichnet, da hier im frühen 12. Jahrhundert der erste König des Landes, Afonso Henriques, geboren wurde. Das historische Zentrum ist ein außergewöhnlich gut erhaltenes Beispiel für die Entwicklung einer mittelalterlichen Siedlung zu einer modernen Stadt. Die Architektur ist geprägt von einer speziellen Kombination aus Granit und Fachwerkbauweise, die später in die weltweiten portugiesischen Kolonien exportiert wurde. Beherrscht wird das Stadtbild von der mittelalterlichen Burg von Guimarães und dem Palast der Herzöge von Braganza, der von französischen Herrenhäusern inspiriert wurde. Bei einem Spaziergang durch die engen Gassen der Plätze Oliveira und Santiago lässt sich die jahrhundertealte Geschichte an den Steinfassaden ablesen. 2001 wurde das Zentrum aufgrund seiner Authentizität zum UNESCO-Weltkulturerbe ernannt.",
    "Guimarãest gyakran a 'portugál nemzet bölcsőjeként' emlegetik, mivel úgy tartják, hogy itt született az ország első királya, Afonso Henriques a 12. század elején. A történelmi városközpont kivételesen jól megőrzött példája annak, hogyan fejlődött egy középkori település modern várossá. Építészetére jellemző a gránit és a fagerendás szerkezet sajátos ötvözete, amelyet később a világ számos portugál gyarmatára is elvittek. A városkép meghatározó eleme a középkori Guimarães vára, amely az ifjú királyságot védte, valamint a Braganza hercegek palotája, amelyet francia udvarházak ihlettek. Az Oliveira és a Santiago terek szűk utcáin sétálva a kőhomlokzatokba vésett évszázados történelem tárul elénk. 2001-ben az UNESCO elismerte a történelmi központ hitelességét és építészeti jelentőségét.",
    "Guimarães este adesea numit 'leagănul naționalității portugheze', deoarece se crede că primul rege al țării, Afonso Henriques, s-a născut aici la începutul secolului al XII-lea. Centrul istoric este un exemplu excepțional de bine conservat al evoluției unei așezări medievale într-un oraș modern. Arhitectura sa este caracterizată printr-o tehnică specifică ce implică granitul și structurile pe jumătate din lemn, tehnici exportate ulterior în coloniile portugheze din întreaga lume. Orizontul este dominat de castelul medieval Guimarães, care a apărat tânărul regat, și de Palatul Ducilor de Braganza, inspirat de conacele franceze. O plimbare pe străzile înguste ale piețelor Oliveira și Santiago dezvăluie secole de istorie sculptate în fațadele de piatră. În 2001, UNESCO a recunoscut centrul istoric pentru autenticitatea sa.",
    ["The Battle of São Mamede, won by Afonso Henriques in 1128, took place nearby.", "The Palace of the Dukes of Braganza features 39 distinctive brick chimneys.", "Guimarães was the European Capital of Culture in the year 2012.", "The castle of Guimarães was built in the 10th century to protect against Vikings.", "The Church of Nossa Senhora da Oliveira was founded in the 10th century.", "Much of the old town wall, built in the 14th century, is still standing."],
    ["Die Schlacht von São Mamede im Jahr 1128, die Afonso Henriques gewann, fand hier statt.", "Der Palast der Herzöge von Braganza besitzt 39 charakteristische Ziegelschornsteine.", "Guimarães war im Jahr 2012 die Kulturhauptstadt Europas.", "Die Burg von Guimarães wurde im 10. Jahrhundert zum Schutz vor Wikingern erbaut.", "Die Kirche Nossa Senhora da Oliveira wurde bereits im 10. Jahrhundert gegründet.", "Große Teile der im 14. Jahrhundert errichteten Stadtmauer sind noch erhalten."],
    ["A São Mamede-i csata, amelyet Afonso Henriques nyert meg 1128-ban, a közelben zajlott.", "A Braganza hercegek palotája 39 jellegzetes tégla kéménnyel rendelkezik.", "Guimarães 2012-ben Európa Kulturális Fővárosa volt.", "Guimarães várát a 10. században építették a vikingek elleni védekezésül.", "A Nossa Senhora da Oliveira-templomot a 10. században alapították.", "A 14. században épült óvárosi fal nagy része még ma is áll."],
    ["Bătălia de la São Mamede, câștigată de Afonso Henriques în 1128, a avut loc în apropiere.", "Palatul Ducilor de Braganza are 39 de coșuri de fum din cărămidă distincte.", "Guimarães a fost Capitala Europeană a Culturii în anul 2012.", "Castelul din Guimarães a fost construit în secolul al X-lea pentru apărare contra vikingilor.", "Biserica Nossa Senhora da Oliveira a fost fondată în secolul al X-lea.", "O mare parte din zidul vechi al orașului, construit în secolul al XIV-lea, este încă în picioare."]
)

# POI 5: Pena Palace (General/Historical)
add_poi(
    "cult-pena", "Pena Palace", "Palácio Nacional da Pena", "Pena-palota", "Palatul Național Pena",
    "Perched on a high peak of the Sintra Mountains, the Pena Palace is a 19th-century masterpiece that serves as one of the finest expressions of Romanticism in the world. King Ferdinand II, a man of great artistic sensitivity, acquired the ruins of a 16th-century Hieronymite monastery in 1838 and decided to build a summer residence for the royal family. The result is a vibrant, eclectic structure that incorporates elements of Gothic, Manueline, Moorish, and Renaissance styles. The palace is surrounded by the vast Pena Park, which contains over 500 species of trees from all corners of the globe, reflecting the era's fascination with exoticism. Standing at an elevation of 450 meters, the palace is visible from Lisbon on a clear day, appearing as a colorful crown over the forest. It remains a national monument and a cornerstone of Portugal's cultural heritage.",
    "Auf einem hohen Gipfel des Sintra-Gebirges thront der Pena-Palast, ein Meisterwerk des 19. Jahrhunderts und einer der bedeutendsten Ausdrücke der Romantik weltweit. König Ferdinand II., ein Mann mit großem künstlerischem Gespür, erwarb 1838 die Ruinen eines Hieronymiten-Klosters aus dem 16. Jahrhundert, um dort eine Sommerresidenz für die königliche Familie zu errichten. Das Ergebnis ist ein farbenfrohes, eklektisches Bauwerk, das Elemente der Gotik, Manuelinik, maurischen Kunst und Renaissance vereint. Der Palast ist vom weitläufigen Pena-Park umgeben, in dem über 500 Baumarten aus aller Welt wachsen, was die damalige Faszination für das Exotische widerspiegelt. Auf einer Höhe von 450 Metern gelegen, ist der Palast an klaren Tagen sogar von Lissabon aus sichtbar. Er ist ein Nationaldenkmal und ein zentraler Bestandteil des kulturellen Erbes Portugals.",
    "A Sintra-hegység egyik magas csúcsán trónoló Pena-palota a 19. századi romantika egyik legkiválóbb világméretű példája. II. Ferdinánd király, aki nagy művészeti érzékenységgel rendelkezett, 1838-ban szerezte meg egy 16. századi jeromos kolostor romjait, és elhatározta, hogy nyári rezidenciát épít rajta a királyi család számára. Az eredmény egy vibráló, eklektikus építmény lett, amely gótikus, mánuel, mór és reneszánsz stílusjegyeket ötvöz. A palotát a hatalmas Pena Park veszi körül, amely a világ minden tájáról származó több mint 500 fafajtát tartalmaz, tükrözve a korszak egzotikum iránti rajongását. A 450 méteres tengerszint feletti magasságban fekvő palota tiszta időben Lisszabonból is látható, és színes koronaként emelkedik az erdő fölé. Portugália kulturális örökségének egyik legfontosabb sarokköve.",
    "Cocoțat pe un vârf înalt al munților Sintra, Palatul Pena este o capodoperă din secolul al XIX-lea, fiind una dintre cele mai bune expresii ale romantismului din lume. Regele Ferdinand al II-lea, un om de o mare sensibilitate artistică, a achiziționat ruinele unei mănăstiri hieronimite din secolul al XVI-lea în 1838 și a decis să construiască o reședință de vară pentru familia regală. Rezultatul este o structură vibrantă, eclectică, ce încorporează elemente din stilurile gotic, manuelin, maur și renascentist. Palatul este înconjurat de vastul Parc Pena, care conține peste 500 de specii de copaci din toate colțurile lumii, reflectând fascinația epocii pentru exotism. Situat la o altitudine de 450 de metri, palatul este vizibil din Lisabona într-o zi senină. Rămâne un monument național și o piatră de temelie a patrimoniului portughez.",
    ["King Ferdinand II acquired the site in 1838 to build a royal summer home.", "The palace sits at an altitude of approximately 450 meters above sea level.", "It was officially classified as a National Monument in 1910.", "The Pena Park covers an area of 85 hectares of diverse forest.", "The last Queen of Portugal, Amélie, spent her last night at the palace in 1910.", "UNESCO added the palace to the World Heritage list in 1995."],
    ["König Ferdinand II. erwarb das Gelände im Jahr 1838 für die Sommerresidenz.", "Der Palast liegt auf einer Höhe von etwa 450 Metern über dem Meeresspiegel.", "Das Bauwerk wurde im Jahr 1910 offiziell als Nationaldenkmal klassifiziert.", "Der Pena-Park erstreckt sich über eine Fläche von insgesamt 85 Hektar Wald.", "Die letzte Königin Portugals, Amélie, verbrachte hier 1910 ihre letzte Nacht.", "Die UNESCO nahm den Palast 1995 in die Liste des Weltkulturerbes auf."],
    ["II. Ferdinánd király 1838-ban szerezte meg a területet a királyi nyaralóhoz.", "A palota körülbelül 450 méteres tengerszint feletti magasságban fekszik.", "Az épületet 1910-ben hivatalosan Nemzeti Műemlékké nyilvánították.", "A Pena Park 85 hektárnyi területet foglal el változatos erdővel.", "Portugália utolsó királynéja, Amélia, 1910-ben itt töltötte utolsó éjszakáját.", "Az UNESCO 1995-ben vette fel a palotát a Világörökség listájára."],
    ["Regele Ferdinand al II-lea a achiziționat situl în 1838 pentru reședința de vară.", "Palatul se află la o altitudine de aproximativ 450 de metri deasupra mării.", "A fost clasificat oficial ca Monument Național în anul 1910.", "Parcul Pena acoperă o suprafață de 85 de hectare de pădure diversă.", "Ultima regină a Portugaliei, Amélie, și-a petrecut ultima noapte aici în 1910.", "UNESCO a adăugat palatul pe lista Patrimoniului Mondial în 1995."]
)

# POI 6: Alcobaça Monastery
add_poi(
    "cult-alcobaca", "Alcobaça Monastery", "Kloster von Alcobaça", "Alcobaça-kolostor", "Mănăstirea Alcobaça",
    "The Monastery of Santa Maria d'Alcobaça, founded in the 12th century by King Afonso Henriques, is a masterpiece of Cistercian Gothic architecture. Its scale and purity of design reflect the Cistercian Order's ideal of austerity and spiritual focus. The church was the first purely Gothic building in Portugal, featuring an impressively high and narrow nave. Central to the monastery's history are the tombs of King Pedro I and his lover Inês de Castro, who was murdered on the orders of Pedro's father. Their ornate 14th-century sarcophagi are placed face to face, so that upon their resurrection, the first thing they see is each other. The monastery's massive kitchen and the refectory speak to the wealth and influence the monks held during the Middle Ages. In 1989, it was inscribed on the UNESCO World Heritage list for its artistic and historical value.",
    "Das Kloster Santa Maria von Alcobaça, im 12. Jahrhundert von König Afonso Henriques gegründet, ist ein Meisterwerk der zisterziensischen Gotik. Seine Größe und die Reinheit des Entwurfs spiegeln das Ideal der Entsagung und spirituellen Konzentration des Zisterzienserordens wider. Die Kirche war das erste rein gotische Gebäude in Portugal und besticht durch ihr beeindruckend hohes und schmales Mittelschiff. Ein zentraler Punkt der Klostergeschichte sind die Grabmäler von König Pedro I. und seiner Geliebten Inês de Castro, die auf Befehl von Pedros Vater ermordet wurde. Ihre kunstvollen Sarkophage aus dem 14. Jahrhundert stehen sich gegenüber, damit sie sich bei ihrer Auferstehung sofort wiedersehen können. Die riesige Küche und das Refektorium zeugen vom einstigen Reichtum und Einfluss der Mönche im Mittelalter. 1989 wurde das Kloster von der UNESCO zum Weltkulturerbe erklärt.",
    "Az Alcobaça-i Szent Mária-kolostor, amelyet a 12. században alapított Afonso Henriques király, a ciszterci gótikus építészet remekműve. Méretei és letisztult formavilága a ciszterci rend puritánságát és szellemi összpontosítását tükrözi. A templom volt az első tisztán gótikus épület Portugáliában, lenyűgözően magas és keskeny főhajóval. A kolostor történetének központi eleme I. Péter király és szerelme, Inês de Castro sírhelye, akit Péter apjának parancsára gyilkoltak meg. Díszes, 14. századi szarkofágjaik egymással szemben helyezkednek el, hogy feltámadásukkor az első dolog, amit meglátnak, egymás legyen. A kolostor hatalmas konyhája és ebédlője a szerzetesek középkori gazdagságáról és befolyásáról árulkodik. 1989-ben művészeti és történelmi értékei miatt felkerült az UNESCO Világörökség listájára.",
    "Mănăstirea Santa Maria din Alcobaça, fondată în secolul al XII-lea de regele Afonso Henriques, este o capodoperă a arhitecturii gotice cisterciene. Scara și puritatea designului său reflectă idealul de austeritate și concentrare spirituală al Ordinului Cistercian. Biserica a fost prima clădire pur gotică din Portugalia, având o navă impresionant de înaltă și îngustă. Centrale în istoria mănăstirii sunt mormintele regelui Pedro I și al iubitei sale Inês de Castro, care a fost ucisă la ordinul tatălui lui Pedro. Sarcofagele lor ornamentate din secolul al XIV-lea sunt așezate față în față, astfel încât, la învierea lor, primul lucru pe care îl văd să fie celălalt. Bucătăria masivă a mănăstirii și refectoriul vorbesc despre bogăția și influența călugărilor în Evul Mediu. În 1989, a fost înscrisă pe lista UNESCO.",
    ["The monastery was founded in 1153 by the first Portuguese king.", "The church is 106 meters long and was inspired by Clairvaux Abbey.", "King Pedro and Inês de Castro were buried here in the year 1361.", "The monastery's kitchen features a chimney covered in tiles from 1766.", "The Cloister of Silence was built during the reign of King Dinis I.", "UNESCO inscribed the monastery as a World Heritage site in 1989."],
    ["Das Kloster wurde 1153 vom ersten portugiesischen König gegründet.", "Die Kirche ist 106 Meter lang und wurde nach dem Vorbild von Clairvaux erbaut.", "König Pedro und Inês de Castro wurden hier im Jahr 1361 beigesetzt.", "Die Klosterküche besitzt einen mit Kacheln aus dem Jahr 1766 verzierten Schornstein.", "Der Kreuzgang des Schweigens wurde unter König Dinis I. errichtet.", "Die UNESCO erklärte das Kloster im Jahr 1989 zum Weltkulturerbe."],
    ["A kolostort 1153-ban alapította az első portugál király.", "A templom 106 méter hosszú, és a Clairvaux-i apátság mintájára épült.", "I. Péter királyt és Inês de Castrót 1361-ben temették ide.", "A kolostor konyhája 1766-ból származó csempékkel díszített kéménnyel rendelkezik.", "A Csend-kerengőt I. Dénes király uralkodása alatt építették.", "Az UNESCO 1989-ben nyilvánította a kolostort a Világörökség részévé."],
    ["Mănăstirea a fost fondată în 1153 de primul rege portughez.", "Biserica are 106 metri lungime și a fost inspirată de Abația Clairvaux.", "Regele Pedro și Inês de Castro au fost înmormântați aici în anul 1361.", "Bucătăria mănăstirii are un coș de fum acoperit cu plăci din 1766.", "Claustrul Tăcerii a fost construit în timpul domniei regelui Dinis I.", "UNESCO a înscris mănăstirea ca sit al Patrimoniului Mondial în 1989."]
)

# POI 7: Tomar Templar Castle
add_poi(
    "cult-tomar", "Tomar Templar Castle", "Burg von Tomar", "Tomari templomos vár", "Castelul Templierilor din Tomar",
    "The Convent of Christ in Tomar was originally a 12th-century Templar stronghold, serving as the headquarters of the Order of the Knights Templar in Portugal. After the order was dissolved in the 14th century, it became the seat of the Order of Christ, which played a crucial role in the Portuguese maritime discoveries. The complex is a palimpsest of architectural styles, most notably the unique 12th-century 'charola' or round church, modeled after the Holy Sepulchre in Jerusalem. Another world-famous feature is the Chapter House window, a supreme masterpiece of Manueline decoration featuring corals, ropes, and seaweed carved into stone. This window, created by Diogo de Arruda between 1510 and 1513, symbolizes Portugal's link to the sea. The vast complex includes seven cloisters and reflects the wealth and spiritual power of the military orders. UNESCO added it to the World Heritage list in 1983.",
    "Das Christuskloster in Tomar war ursprünglich eine Templerfestung aus dem 12. Jahrhundert und diente als Hauptquartier des Ordens in Portugal. Nach der Auflösung des Templerordens im 14. Jahrhundert wurde es zum Sitz des Christusordens, der eine entscheidende Rolle bei den portugiesischen Entdeckungsreisen spielte. Die Anlage vereint verschiedene Baustile, wobei die Charola, eine Rundkirche aus dem 12. Jahrhundert nach dem Vorbild des Heiligen Grabes in Jerusalem, besonders hervorsticht. Ein weiteres weltberühmtes Detail ist das Fenster des Kapitelsaals, ein Meisterwerk der Manuelinik mit detailreichen Steinmetzarbeiten von Korallen und Tauen. Dieses Fenster wurde zwischen 1510 und 1513 von Diogo de Arruda geschaffen und symbolisiert die tiefe Verbindung Portugals zum Meer. Der weitläufige Komplex umfasst sieben Kreuzgänge und wurde 1983 zum UNESCO-Weltkulturerbe erklärt.",
    "A tomari Krisztus-kolostor eredetileg egy 12. századi templomos erődítmény volt, amely a portugáliai templomos lovagrend székhelyeként szolgált. A rend 14. századi feloszlatása után a Krisztus-rend székhelye lett, amely kulcsszerepet játszott a portugál tengeri felfedezésekben. Az épületegyüttes stílusok tárháza, leginkább a 12. századi 'charola' vagy körtemplom emelkedik ki, amelyet a jeruzsálemi Szent Sír-templom mintájára építettek. Egy másik világhírű részlete a káptalani terem ablaka, a mánuel díszítőművészet remekműve, amely kőbe faragott korallokat, köteleket és tengeri moszatokat ábrázol. Ezt az ablakot Diogo de Arruda készítette 1510 és 1513 között, jelképezve Portugália tengeri kapcsolatait. A hatalmas komplexum hét kerengőt foglal magában, és 1983-ban került fel az UNESCO Világörökség listájára.",
    "Conventul lui Cristos din Tomar a fost inițial o cetate templieră din secolul al XII-lea, servind drept sediu al Ordinului Cavalerilor Templieri în Portugalia. După dizolvarea ordinului în secolul al XIV-lea, a devenit sediul Ordinului lui Cristos, care a jucat un rol crucial în descoperirile maritime portugheze. Complexul este un palimpsest de stiluri arhitecturale, în special 'charola' sau biserica rotundă din secolul al XII-lea, modelată după Sfântul Mormânt din Ierusalim. O altă caracteristică faimoasă este fereastra Casei Capitolului, o capodoperă a decorațiunilor manueline cu corali, frânghii și alge sculptate în piatră. Această fereastră, creată de Diogo de Arruda între 1510 și 1513, simbolizează legătura Portugaliei cu marea. Complexul include șapte claustre și a fost adăugat pe lista UNESCO în 1983.",
    ["The Templar Castle of Tomar was founded by Gualdim Pais in 1160.", "The 'charola' is an 16-sided polygonal round church from the 12th century.", "The Chapter House window was carved by Diogo de Arruda around 1510.", "The main cloister, or Great Cloister, was completed in the 16th century.", "The complex was designated a UNESCO World Heritage site in 1983.", "Tomar was the last headquarters of the Knights Templar in Portugal."],
    ["Die Burg der Templer in Tomar wurde 1160 von Gualdim Pais gegründet.", "Die 'Charola' ist eine 16-eckige Rundkirche aus dem 12. Jahrhundert.", "Das Fenster des Kapitelsaals wurde um 1510 von Diogo de Arruda gestaltet.", "Der Hauptkreuzgang der Anlage wurde im 16. Jahrhundert fertiggestellt.", "Das Christuskloster wurde im Jahr 1983 zum UNESCO-Weltkulturerbe erklärt.", "Tomar war das letzte Hauptquartier der Tempelritter in ganz Portugal."],
    ["A tomari templomos várat Gualdim Pais alapította 1160-ban.", "A 'charola' egy 16 oldalú sokszögletű körtemplom a 12. századból.", "A káptalani terem ablakát Diogo de Arruda faragta 1510 körül.", "A főkerengő, vagy Nagykerengő a 16. században készült el.", "Az épületegyüttest 1983-ban nyilvánították az UNESCO Világörökség részévé.", "Tomar volt a templomos lovagok utolsó székhelye Portugáliában."],
    ["Castelul Templierilor din Tomar a fost fondat de Gualdim Pais în 1160.", "Charola este o biserică rotundă poligonală cu 16 laturi din secolul XII.", "Fereastra Casei Capitolului a fost sculptată de Diogo de Arruda în jurul anului 1510.", "Claustrul principal, sau Marele Claustru, a fost finalizat în secolul al XVI-lea.", "Complexul a fost desemnat sit al Patrimoniului Mondial UNESCO în 1983.", "Tomar a fost ultimul sediu al Cavalerilor Templieri din Portugalia."]
)

# POI 8: Pena Palace (Architectural details)
add_poi(
    "cult-pena-palace", "Pena Palace Architecture", "Architektur des Pena-Palastes", "A Pena-palota építészete", "Arhitectura Palatului Pena",
    "The architecture of the Pena Palace is a spectacular display of 19th-century eclecticism, reflecting the personal vision of King Ferdinand II. Built by the German architect Baron Wilhelm Ludwig von Eschwege, it consciously combines Neo-Gothic, Neo-Manueline, Neo-Moorish, and Neo-Renaissance elements. The 'New Palace' section features bright yellow and red walls, which serve to distinguish different historical styles and construction phases. One of its most impressive features is the Triton Gateway, an allegorical arch depicting a half-man, half-fish creature that symbolizes the creation of the world. The interior is equally ornate, with trompe-l'œil paintings, intricate stucco work, and a collection of 19th-century tiles. The palace's structure was designed to incorporate the existing 16th-century monastery cloister and chapel, resulting in a complex verticality that follows the rugged terrain. This architectural fantasy was intended to evoke the spirit of German Romanticism while celebrating Portuguese history.",
    "Die Architektur des Pena-Palastes ist ein spektakuläres Zeugnis des Eklektizismus des 19. Jahrhunderts und spiegelt die persönliche Vision von König Ferdinand II. wider. Entworfen vom deutschen Architekten Wilhelm Ludwig von Eschwege, kombiniert das Bauwerk Neogotik, Neomanuelinik, neomaurische Elemente und Neorenaissance. Der Bereich des 'Neuen Palastes' ist durch leuchtend gelbe und rote Wände gekennzeichnet, die die verschiedenen Baustile optisch voneinander abgrenzen. Zu den beeindruckendsten Merkmalen gehört das Triton-Tor, ein allegorischer Bogen mit einer Meereskreatur, die die Entstehung der Welt symbolisiert. Die Innenräume sind ebenso prächtig gestaltet, mit Trompe-l'œil-Malereien, feinen Stuckarbeiten und einer Sammlung von Kacheln aus dem 19. Jahrhundert. Der Palast wurde so konzipiert, dass er den bestehenden Kreuzgang und die Kapelle des Klosters aus dem 16. Jahrhundert integriert, was zu einer komplexen, vertikalen Struktur führt. Diese architektonische Fantasie sollte den Geist der deutschen Romantik mit der portugiesischen Identität verbinden.",
    "A Pena-palota építészete a 19. századi eklektika látványos megnyilvánulása, amely II. Ferdinánd király személyes vízióját tükrözi. A német építész, Wilhelm Ludwig von Eschwege báró által tervezett épület tudatosan ötvözi a neogótikus, neománuel, neomór és neoreneszánsz elemeket. Az 'Új palota' részleg élénksárga és vörös falai segítenek megkülönböztetni a különböző történelmi stílusokat és építési fázisokat. Egyik leglenyűgözőbb eleme a Triton-kapu, egy allegorikus boltív, amely egy félig ember, félig hal lényt ábrázol, a világ teremtését jelképezve. A belső tér hasonlóan díszes, trompe-l'œil festményekkel, bonyolult stukkómunkákkal és 19. századi csempékkel. A palota szerkezetét úgy alakították ki, hogy magában foglalja a meglévő 16. századi kolostori kerengőt és kápolnát, ami a terepviszonyokat követő összetett vertikalitást eredményezett. Ez az építészeti fantázia a német romantika szellemét kívánta felidézni a portugál történelem dicsőítésével.",
    "Arhitectura Palatului Pena este o demonstrație spectaculoasă a eclectismului din secolul al XIX-lea, reflectând viziunea personală a regelui Ferdinand al II-lea. Construit de arhitectul german baronul Wilhelm Ludwig von Eschwege, acesta combină conștient elemente neo-gotice, neo-manueline, neo-maure și neo-renascentiste. Secțiunea 'Noul Palat' are pereți galbeni și roșii strălucitori, care servesc la distingerea diferitelor stiluri istorice. Una dintre cele mai impresionante caracteristici este Poarta Triton, un arc alegoric care înfățișează o creatură jumătate om, jumătate pește, simbolizând crearea lumii. Interiorul este la fel de bogat decorat, cu picturi trompe-l'œil, stucaturi complexe și o colecție de plăci ceramice din secolul al XIX-lea. Structura palatului a fost proiectată să încorporeze claustrul și capela mănăstirii din secolul al XVI-lea, rezultând o verticalitate complexă ce urmărește terenul accidentat. Această fantezie arhitecturală evocă spiritul romantismului german.",
    ["The palace was designed by the German architect Baron von Eschwege.", "The Triton Gateway features a relief of a sea monster symbolizing the elements.", "Construction of the romantic palace took place between 1842 and 1854.", "The distinct red and yellow colors were restored in the late 20th century.", "The palace chapel retains its original 16th-century alabaster altarpiece.", "The ballroom features a collection of Meissen porcelain from the 19th century."],
    ["Der Palast wurde vom deutschen Architekten Baron von Eschwege entworfen.", "Das Triton-Tor zeigt das Relief eines Ungeheuers, das die Elemente symbolisiert.", "Der Bau des romantischen Palastes erfolgte zwischen 1842 und 1854.", "Die markanten Farben Rot und Gelb wurden Ende des 20. Jahrhunderts restauriert.", "Die Palastkapelle besitzt noch ein originales Alabaster-Retabel aus dem 16. Jahrhundert.", "Der Ballsaal beherbergt eine Sammlung von Meissener Porzellan aus dem 19. Jahrhundert."],
    ["A palotát a német építész, Wilhelm Ludwig von Eschwege báró tervezte.", "A Triton-kapu egy tengeri szörnyet ábrázol, amely az őselemeket szimbolizálja.", "A romantikus palota építése 1842 és 1854 között zajlott.", "A jellegzetes piros és sárga színeket a 20. század végén állították helyre.", "A palotakápolna megőrizte eredeti, 16. századi alabástrom oltárképét.", "A bálteremben 19. századi meisseni porcelánok gyűjteménye látható."],
    ["Palatul a fost proiectat de arhitectul german baronul von Eschwege.", "Poarta Triton prezintă un relief al unui monstru marin simbolizând elementele.", "Construcția palatului romantic a avut loc între 1842 și 1854.", "Culorile distincte roșu și galben au fost restaurate la sfârșitul secolului XX.", "Capela palatului păstrează altarul original din alabastru din secolul al XVI-lea.", "Sala de bal are o colecție de porțelan de Meissen din secolul al XIX-lea."]
)

# POI 9: Livraria Lello
add_poi(
    "cult-livraria-lello", "Livraria Lello", "Buchhandlung Lello", "Lello könyvesbolt", "Librăria Lello",
    "Livraria Lello, located in the heart of Porto, is frequently cited as one of the most beautiful bookstores in the world. Opened in 1906 by brothers José and António Lello, the building features a stunning Neo-Gothic facade with Art Nouveau flourishes. The interior is dominated by a majestic, forked red staircase that twists through the center of the shop, leading to the second floor. A large stained-glass window in the ceiling, measuring eight by three meters, bears the brothers' motto 'Decus in Labore' (Dignity in Work). The wooden shelves are intricately carved with busts of famous Portuguese writers, creating an atmosphere of intellectual grandeur. In recent decades, the bookstore gained worldwide fame for its supposed influence on J.K. Rowling during her time in Porto, particularly regarding the aesthetics of the Harry Potter universe. Despite its status as a major tourist attraction, it remains a fully functioning bookstore and a landmark of Porto's cultural life.",
    "Die Buchhandlung Lello im Herzen von Porto wird regelmäßig als eine der schönsten Buchhandlungen der Welt bezeichnet. Eröffnet im Jahr 1906 von den Brüdern José und António Lello, besticht das Gebäude durch eine prachtvolle neogotische Fassade mit Jugendstil-Elementen. Das Innere wird von einer majestätischen, verzweigten roten Treppe beherrscht, die sich durch die Mitte des Ladens windet. Ein großes Bleiglasfenster in der Decke mit den Maßen acht mal drei Meter trägt das Motto der Brüder: 'Decus in Labore' (Würde in der Arbeit). Die Holzregale sind kunstvoll mit Büsten berühmter portugiesischer Schriftsteller verziert, was eine Atmosphäre intellektueller Erhabenheit schafft. In den letzten Jahrzehnten erlangte die Buchhandlung weltweite Bekanntheit, da sie J.K. Rowling während ihrer Zeit in Porto inspiriert haben soll, insbesondere in Bezug auf die Harry-Potter-Romane. Trotz des massiven Touristenandrangs ist sie weiterhin eine funktionierende Buchhandlung und ein Wahrzeichen der Stadt.",
    "A Porto szívében található Lello könyvesbolt (Livraria Lello) rendszeresen a világ legszebb könyvesboltjai között szerepel. Az 1906-ban José és António Lello testvérek által megnyitott épület lenyűgöző neogótikus homlokzattal rendelkezik, szecessziós díszítéssel. A belső teret egy fenséges, kettéágazó vörös lépcsőház uralja, amely a bolt közepén kanyarog felfelé. A mennyezeten egy hatalmas, nyolcszor három méteres ólomüveg ablak látható, amely a testvérek mottóját viseli: 'Decus in Labore' (Tisztesség a munkában). A fapolcokat híres portugál írók mellszobrai díszítik, megteremtve az intellektuális nagyszerűség légkörét. Az elmúlt évtizedekben a könyvesbolt világhírnevet szerzett, mivel állítólag ihletet adott J.K. Rowlingnak portói tartózkodása alatt, különösen a Harry Potter-világ esztétikájához. A turisztikai vonzereje ellenére ma is működő könyvesbolt és Porto kulturális életének meghatározó helyszíne.",
    "Livraria Lello, situată în inima orașului Porto, este frecvent citată ca fiind una dintre cele mai frumoase librării din lume. Deschisă în 1906 de frații José și António Lello, clădirea are o fațadă neo-gotică uluitoare cu elemente Art Nouveau. Interiorul este dominat de o scară roșie maiestuoasă, care se răsucește prin centrul magazinului, ducând la etajul al doilea. O fereastră mare cu vitralii în tavan, de opt pe trei metri, poartă motto-ul fraților 'Decus in Labore' (Demnitate în muncă). Rafturile de lemn sunt sculptate complex cu busturi de scriitori portughezi celebri, creând o atmosferă de grandoare intelectuală. În ultimele decenii, librăria a câștigat faimă mondială pentru presupusa influență asupra lui J.K. Rowling în timpul șederii sale în Porto, în special în ceea ce privește estetica universului Harry Potter. Rămâne un punct de reper al vieții culturale din Porto.",
    ["The bookstore was inaugurated on January 13, 1906.", "The building was designed by the engineer Francisco Xavier Esteves.", "The central staircase is made of reinforced concrete but painted to look like wood.", "The stained-glass ceiling window measures 8 meters in length.", "J.K. Rowling lived in Porto for two years in the early 1990s.", "Lello was one of the first buildings in Porto to use reinforced concrete."],
    ["Die Buchhandlung wurde am 13. Januar 1906 offiziell eingeweiht.", "Das Gebäude wurde vom Ingenieur Francisco Xavier Esteves entworfen.", "Die zentrale Treppe besteht aus Stahlbeton, ist aber in Holzoptik bemalt.", "Das Bleiglasfenster an der Decke ist genau 8 Meter lang.", "J.K. Rowling lebte Anfang der 1990er Jahre für zwei Jahre in Porto.", "Lello war eines der ersten Gebäude in Porto, das Stahlbeton verwendete."],
    ["A könyvesboltot 1906. január 13-án avatták fel.", "Az épületet Francisco Xavier Esteves mérnök tervezte.", "A központi lépcsőház vasbetonból készült, de fának látszó festést kapott.", "A mennyezeti ólomüveg ablak 8 méter hosszú.", "J.K. Rowling az 1990-es évek elején két évig élt Portóban.", "A Lello volt az egyik első épület Portóban, amelynél vasbetont alkalmaztak."],
    ["Librăria a fost inaugurată pe 13 ianuarie 1906.", "Clădirea a fost proiectată de inginerul Francisco Xavier Esteves.", "Scara centrală este realizată din beton armat, dar vopsită să arate ca lemnul.", "Vitraliul din tavan are o lungime de 8 metri.", "J.K. Rowling a locuit în Porto timp de doi ani la începutul anilor 1990.", "Lello a fost una dintre primele clădiri din Porto care a folosit beton armat."]
)

# POI 10: Chapel of Bones
add_poi(
    "cult-capela-ossos", "Chapel of Bones", "Knochenkapelle", "Csontkápolna", "Capela Oaselor",
    "The Chapel of Bones (Capela dos Ossos) in Évora is a 16th-century ossuary that serves as a profound reflection on the transience of human life. Built by Franciscan monks, the chapel was a creative solution to the overcrowding of the city's cemeteries, which were occupying valuable land. The walls and pillars of the small chapel are meticulously lined with the skulls and bones of approximately 5,000 monks and citizens. Above the entrance, a famous inscription warns visitors: 'We bones that are here, for yours we wait.' The dim lighting and the skeletal decorations create a somber atmosphere, intended to encourage meditation and spiritual awareness during the Counter-Reformation. Two desiccated corpses, one of an adult and one of a child, were historically displayed in the chapel, adding to its macabre reputation. Today, it is part of the larger Church of St. Francis and remains one of Évora's most visited and thought-provoking sites.",
    "Die Knochenkapelle (Capela dos Ossos) in Évora ist ein Beinhaus aus dem 16. Jahrhundert, das als tiefgründige Reflexion über die Vergänglichkeit des menschlichen Lebens dient. Von Franziskanermönchen erbaut, war die Kapelle eine kreative Lösung für den Platzmangel auf den Friedhöfen der Stadt, die wertvolles Bauland beanspruchten. Die Wände und Pfeiler der kleinen Kapelle sind akribisch mit den Schädeln und Knochen von schätzungsweise 5.000 Mönchen und Bürgern ausgekleidet. Über dem Eingang warnt eine berühmte Inschrift die Besucher: 'Wir Knochen, die hier sind, warten auf die euren.' Die dämmrige Beleuchtung und die skelettartigen Dekorationen schaffen eine ernste Atmosphäre, die während der Gegenreformation zur Meditation und geistigen Einkehr anregen sollte. Zwei vertrocknete Leichen, eine von einem Erwachsenen und eine von einem Kind, wurden dort historisch ausgestellt. Heute ist sie Teil der Franziskuskirche und eine der meistbesuchten Stätten in Évora.",
    "Az évora-i Csontkápolna (Capela dos Ossos) egy 16. századi osszárium, amely az emberi élet mulandóságára való mély elmélkedés helyszíne. A ferences szerzetesek által épített kápolna kreatív megoldás volt a város temetőinek túlzsúfoltságára, amelyek értékes földterületeket foglaltak el. A kis kápolna falait és pilléreit aprólékosan kirakták körülbelül 5000 szerzetes és polgár koponyájával és csontjaival. A bejárat felett egy híres felirat figyelmezteti a látogatókat: 'Mi, az itt lévő csontok, a tiéitekre várunk.' A homályos világítás és a csontváz-díszítés komor hangulatot áraszt, amelynek célja az ellenreformáció idején a meditáció és a lelki tudatosság ösztönzése volt. Két kiszáradt holttestet, egy felnőttét és egy gyermekét is közszemlére tettek itt. Ma a Szent Ferenc-templom része, és Évora egyik leglátogatottabb és legelgondolkodtatóbb látnivalója.",
    "Capela Oaselor (Capela dos Ossos) din Évora este un osuar din secolul al XVI-lea care servește ca o reflecție profundă asupra efemerității vieții umane. Construită de călugări franciscani, capela a fost o soluție creativă la supraaglomerarea cimitirelor orașului. Pereții și stâlpii micuței capele sunt căptușiți meticulos cu craniile și oasele a aproximativ 5.000 de călugări și cetățeni. Deasupra intrării, o inscripție faimoasă avertizează vizitatorii: 'Noi, oasele care suntem aici, le așteptăm pe ale voastre.' Iluminarea slabă și decorațiunile scheletice creează o atmosferă sumbră, menită să încurajeze meditația și conștientizarea spirituală în timpul Contrareformei. Două cadavre uscate, unul de adult și unul de copil, au fost expuse istoric în capelă. Astăzi, face parte din Biserica Sfântul Francisc și rămâne unul dintre cele mai vizitate locuri din Évora.",
    ["The chapel was built in the late 16th century by three Franciscan monks.", "Approximately 5,000 human skeletons were used to decorate the interior.", "The inscription above the entrance was written in the 16th century.", "The bones were collected from 42 different monastic cemeteries in the area.", "The chapel is 18.7 meters long and 11 meters wide.", "The ceiling features murals dating from the year 1810 with motifs related to death."],
    ["Die Kapelle wurde Ende des 16. Jahrhunderts von drei Franziskanermönchen erbaut.", "Schätzungsweise 5.000 menschliche Skelette wurden für die Dekoration verwendet.", "Die Inschrift über dem Eingang stammt aus dem 16. Jahrhundert.", "Die Knochen wurden von 42 verschiedenen Klosterfriedhöfen der Umgebung gesammelt.", "Die Kapelle ist 18,7 Meter lang und 11 Meter breit.", "Die Decke zeigt Wandmalereien aus dem Jahr 1810 mit Todesmotiven."],
    ["A kápolnát a 16. század végén építette három ferences szerzetes.", "Körülbelül 5000 emberi csontvázat használtak fel a belső tér díszítéséhez.", "A bejárat feletti felirat a 16. században készült.", "A csontokat a környék 42 különböző kolostori temetőjéből gyűjtötték össze.", "A kápolna 18,7 méter hosszú és 11 méter széle.", "A mennyezeten 1810-ből származó, halállal kapcsolatos motívumokat ábrázoló freskók láthatók."],
    ["Capela a fost construită la sfârșitul secolului XVI de trei călugări franciscani.", "Aproximativ 5.000 de schelete umane au fost folosite pentru a decora interiorul.", "Inscripția de deasupra intrării a fost scrisă în secolul al XVI-lea.", "Oasele au fost colectate din 42 de cimitire monahale diferite din zonă.", "Capela are 18,7 metri lungime și 11 metri lățime.", "Tavanul prezintă picturi murale din anul 1810 cu motive legate de moarte."]
)

print(json.dumps(pois, indent=2, ensure_ascii=False))
