import json
import os

cities = [
    ("gaborone", "state-capital", "BW-SE", 25.9231, -24.6282, "Gaborone", "Capital of Botswana, known for the Gaborone Game Reserve and its rapid modern development."),
    ("francistown", "city", "BW-NE", 27.5076, -21.1711, "Francistown", "One of the oldest towns in Botswana and a former center of southern Africa's first gold rush."),
    ("molepolole", "city", "BW-KW", 25.5204, -24.4079, "Molepolole", "Gateway to the Kalahari Desert and the largest traditional village in Botswana."),
    ("maun", "city", "BW-NW", 23.4162, -19.9796, "Maun", "The tourism capital of Botswana and the primary gateway to the Okavango Delta."),
    ("mogoditshane", "city", "BW-KW", 25.8643, -24.6191, "Mogoditshane", "A rapidly growing town near Gaborone, functioning largely as a sprawling suburb."),
    ("serowe", "city", "BW-CE", 26.7144, -22.3831, "Serowe", "A historic village known as the birthplace of several of Botswana's presidents."),
    ("kanye", "city", "BW-SO", 25.3283, -24.9789, "Kanye", "Located in mountainous terrain, it is the traditional capital of the Bangwaketse tribe."),
    ("mahalapye", "city", "BW-CE", 26.8335, -23.1044, "Mahalapye", "Positioned on the edge of the Kalahari Desert, it serves as a major railway junction."),
    ("mochudi", "city", "BW-KL", 26.1557, -24.4170, "Mochudi", "Home to the Bakgatla people, known for its traditional painted houses and cultural heritage."),
    ("palapye", "city", "BW-CE", 27.1245, -22.5447, "Palapye", "A rapidly growing industrial hub driven by the nearby Morupule Colliery and power station."),
    ("tlokweng", "city", "BW-SE", 25.9620, -24.6657, "Tlokweng", "A major town adjacent to Gaborone, situated close to the South African border."),
    ("ramotswa", "city", "BW-SE", 25.8702, -24.8715, "Ramotswa", "A bustling town serving as the tribal capital of the Balete people."),
    ("letlhakane", "city", "BW-CE", 25.5802, -21.4137, "Letlhakane", "A significant mining town surrounded by several major diamond mines."),
    ("tonota", "city", "BW-CE", 27.3871, -21.4793, "Tonota", "An agricultural and educational center located along the Shashe River."),
    ("moshupa", "city", "BW-SO", 25.4194, -24.7770, "Moshupa", "Characterized by its unique rocky outcrops and strong agricultural roots."),
    ("thamaga", "city", "BW-KW", 25.5395, -24.6738, "Thamaga", "Renowned for its traditional pottery and situated among scenic granite boulders."),
    ("jwaneng", "city", "BW-SO", 24.7297, -24.6033, "Jwaneng", "A closed mining town built around the Jwaneng diamond mine, one of the richest in the world."),
    ("bobonong", "city", "BW-CE", 28.4316, -21.9686, "Bobonong", "The administrative center of the Bobirwa sub-district, known for its semi-precious stones."),
    ("orapa", "city", "BW-CE", 25.3670, -21.2831, "Orapa", "A heavily secured mining town that hosts one of the world's largest open-pit diamond mines."),
    ("ghanzi", "city", "BW-GH", 21.6508, -21.7001, "Ghanzi", "Known as the capital of the Kalahari, serving as a hub for the local cattle farming industry."),
    ("kasane", "city", "BW-CH", 25.1504, -17.8173, "Kasane", "A crucial gateway to Chobe National Park and the meeting point of four African countries."),
    ("letlhakeng", "city", "BW-KW", 25.0315, -24.1030, "Letlhakeng", "A rural town located on the eastern fringes of the Kalahari Desert."),
    ("tutume", "city", "BW-CE", 27.0519, -20.5053, "Tutume", "A large village in the Central District with strong ties to regional educational institutions."),
    ("gabane", "city", "BW-KW", 25.7766, -24.6510, "Gabane", "A village near Gaborone that has increasingly become a residential commuter area."),
    ("kopong", "city", "BW-KW", 25.8920, -24.4776, "Kopong", "A peaceful settlement experiencing growth due to its proximity to the capital."),
    ("tsabong", "city", "BW-KG", 22.3995, -26.0186, "Tsabong", "An important administrative center located in the arid southern Kalahari."),
    ("gumare", "city", "BW-NW", 22.1502, -19.0435, "Gumare", "A key settlement in the North-West District, acting as a gateway to the Okavango Panhandle."),
    ("shoshong", "city", "BW-CE", 26.6853, -22.9567, "Shoshong", "A place of immense historical significance that served as a capital for the Bamangwato people."),
    ("lentsweletau", "city", "BW-KW", 25.8569, -24.2372, "Lentsweletau", "An agricultural village surrounded by rocky landscapes in the Kweneng District."),
    ("mmopane", "city", "BW-KW", 25.8596, -24.5823, "Mmopane", "A rapidly expanding village that has merged into the greater Gaborone urban area."),
    ("metsimotlhabe", "city", "BW-KW", 25.8115, -24.5772, "Metsimotlhabe", "A growing residential village named after the nearby Metsimotlhabe River."),
    ("mmadinare", "city", "BW-CE", 27.7601, -21.8744, "Mmadinare", "An ancient settlement positioned close to the Letsibogo Dam, an important water source."),
    ("shakawe", "city", "BW-NW", 21.8483, -18.3644, "Shakawe", "Located on the Okavango River, it is famous for excellent tiger fishing and rich birdlife."),
    ("rakops", "city", "BW-CE", 24.4082, -21.0374, "Rakops", "A gateway town to the Central Kalahari Game Reserve, situated along the Boteti River."),
    ("radisele", "city", "BW-CE", 26.8315, -22.8052, "Radisele", "A small agricultural village along the main A1 highway between Mahalapye and Palapye."),
    ("nata", "city", "BW-CE", 26.1772, -19.2223, "Nata", "A vital crossroads town and the primary entry point to the spectacular Makgadikgadi Pans."),
    ("lerala", "city", "BW-CE", 27.7561, -22.7667, "Lerala", "Located near the Tswapong Hills, known for the ephemeral Lerala diamond mine."),
    ("machaneng", "city", "BW-CE", 27.4833, -23.1833, "Machaneng", "A village near the Limpopo River, marking the border between Botswana and South Africa."),
    ("sefhare", "city", "BW-CE", 27.3833, -22.9500, "Sefhare", "A scenic village set against the foothills of the beautiful Tswapong range."),
    ("mathangwane", "city", "BW-CE", 27.3500, -21.0167, "Mathangwane", "A culturally diverse village located along the Shashe River northwest of Francistown."),
    ("sebina", "city", "BW-CE", 27.1833, -20.7333, "Sebina", "An important junction village providing routes to the northern tourist districts."),
    ("marapong", "city", "BW-CE", 27.1333, -20.6167, "Marapong", "An agricultural settlement known for its strong community and cattle farming traditions."),
    ("nokaneng", "city", "BW-NW", 22.1833, -19.6667, "Nokaneng", "A remote village on the western edge of the Okavango Delta."),
    ("charles_hill", "city", "BW-GH", 22.0167, -22.1167, "Charles Hill", "A border town providing a critical transport link between Botswana and Namibia."),
    ("kang", "city", "BW-KG", 22.7500, -23.6667, "Kang", "A vital rest stop along the Trans-Kalahari Highway connecting to Namibia."),
    ("hukuntsi", "city", "BW-KG", 21.7667, -23.9667, "Hukuntsi", "One of the major villages in the northern Kgalagadi district, surrounded by salt pans."),
    ("sefhophe", "city", "BW-CE", 27.9500, -22.1833, "Sefhophe", "An agricultural crossroads in the Central District with a growing local economy."),
    ("mmathethe", "city", "BW-SO", 25.1333, -25.2667, "Mmathethe", "A traditional rural village featuring rolling plains suited for cattle ranching."),
    ("goodhope", "city", "BW-SO", 25.4333, -25.4500, "Goodhope", "The administrative center of the Barolong farms area, a significant grain-producing region."),
    ("mabutsane", "city", "BW-SO", 23.9500, -24.4500, "Mabutsane", "A central hub for rural communities in the western part of the Southern District."),
    ("otse", "city", "BW-SE", 25.7500, -25.0167, "Otse", "Nestled between hills, it is famously home to the breeding colony of Cape Vultures."),
    ("pitsane", "city", "BW-SO", 25.5833, -25.5167, "Pitsane", "A settlement known for its railway station facilitating cross-border trade."),
    ("ramatlabama", "city", "BW-SO", 25.5667, -25.6500, "Ramatlabama", "The southernmost village in Botswana and a major border crossing post into South Africa."),
    ("tati_siding", "city", "BW-NE", 27.4833, -21.3167, "Tati Siding", "A rapidly developing suburb situated just south of the city of Francistown."),
    ("masunga", "city", "BW-NE", 27.2667, -20.6167, "Masunga", "The administrative capital of the North-East District and the heart of the Kalanga culture."),
    ("ntlhantlhe", "city", "BW-SO", 25.6833, -25.0167, "Ntlhantlhe", "A quiet, traditional village situated among small hills in the Southern District."),
    ("gweta", "city", "BW-CE", 25.2333, -20.1833, "Gweta", "A village acting as a primary starting point for excursions into the Makgadikgadi Pans."),
    ("odi", "city", "BW-KL", 26.0333, -24.5167, "Odi", "Famous for its local weaver cooperative which produces stunning traditional tapestries."),
    ("bokaa", "city", "BW-KL", 26.0167, -24.4500, "Bokaa", "Located near the Bokaa Dam, it serves as a tranquil residential and agricultural community."),
    ("morwa", "city", "BW-KL", 26.0667, -24.4333, "Morwa", "A village along the A1 highway that forms part of the culturally rich Kgatleng District.")
]

descriptions_de = [
    "Hauptstadt von Botswana, bekannt für das Gaborone Game Reserve und ihre schnelle moderne Entwicklung.",
    "Eine der ältesten Städte in Botswana und ehemaliges Zentrum des ersten Goldrausches im südlichen Afrika.",
    "Tor zur Kalahari-Wüste und das größte traditionelle Dorf in Botswana.",
    "Die Tourismushauptstadt Botswanas und das Haupttor zum Okavango-Delta.",
    "Eine schnell wachsende Stadt nahe Gaborone, die hauptsächlich als ausgedehnter Vorort fungiert.",
    "Ein historisches Dorf, das als Geburtsort mehrerer botswanischer Präsidenten bekannt ist.",
    "In bergigem Gelände gelegen, ist es die traditionelle Hauptstadt des Bangwaketse-Stammes.",
    "Am Rande der Kalahari-Wüste gelegen, dient es als wichtiger Eisenbahnknotenpunkt.",
    "Heimat des Bakgatla-Volkes, bekannt für seine traditionell bemalten Häuser und sein kulturelles Erbe.",
    "Ein schnell wachsendes Industriezentrum, angetrieben von der nahegelegenen Morupule-Kohlenmine und dem Kraftwerk.",
    "Eine bedeutende Stadt neben Gaborone, nahe der südafrikanischen Grenze gelegen.",
    "Eine geschäftige Stadt, die als Stammeshauptstadt des Balete-Volkes dient.",
    "Eine bedeutende Bergbaustadt, umgeben von mehreren großen Diamantenminen.",
    "Ein landwirtschaftliches und schulisches Zentrum am Fluss Shashe.",
    "Gekennzeichnet durch seine einzigartigen Felsvorsprünge und starken landwirtschaftlichen Wurzeln.",
    "Bekannt für seine traditionelle Töpferei und inmitten malerischer Granitblöcke gelegen.",
    "Eine geschlossene Bergbaustadt, die um die Jwaneng-Diamantenmine, eine der reichsten der Welt, gebaut wurde.",
    "Das Verwaltungszentrum des Bobirwa-Subdistrikts, bekannt für seine Halbedelsteine.",
    "Eine streng gesicherte Bergbaustadt, die eine der größten offenen Diamantenminen der Welt beherbergt.",
    "Bekannt als die Hauptstadt der Kalahari, dient sie als Zentrum für die lokale Rinderzucht.",
    "Ein entscheidendes Tor zum Chobe-Nationalpark und der Treffpunkt von vier afrikanischen Ländern.",
    "Eine ländliche Stadt am östlichen Rand der Kalahari-Wüste.",
    "Ein großes Dorf im Central District mit starken Bindungen zu regionalen Bildungseinrichtungen.",
    "Ein Dorf in der Nähe von Gaborone, das zunehmend zu einer Wohnpendlerzone geworden ist.",
    "Eine friedliche Siedlung, die aufgrund ihrer Nähe zur Hauptstadt wächst.",
    "Ein wichtiges Verwaltungszentrum in der trockenen südlichen Kalahari.",
    "Eine wichtige Siedlung im North-West District, die als Tor zum Okavango-Panhandle fungiert.",
    "Ein Ort von immenser historischer Bedeutung, der als Hauptstadt für das Bamangwato-Volk diente.",
    "Ein landwirtschaftliches Dorf inmitten felsiger Landschaften im Kweneng District.",
    "Ein schnell expandierendes Dorf, das mit dem Großraum Gaborone verschmolzen ist.",
    "Ein wachsendes Wohndorf, das nach dem nahegelegenen Fluss Metsimotlhabe benannt ist.",
    "Eine alte Siedlung in der Nähe des Letsibogo-Damms, einer wichtigen Wasserquelle.",
    "Am Okavango-Fluss gelegen, berühmt für exzellentes Tigerfischen und reiche Vogelwelt.",
    "Eine Torstadt zum Central Kalahari Game Reserve, am Boteti-Fluss gelegen.",
    "Ein kleines landwirtschaftliches Dorf entlang der A1-Autobahn zwischen Mahalapye und Palapye.",
    "Eine wichtige Kreuzungsstadt und der Haupteingang zu den spektakulären Makgadikgadi-Pfannen.",
    "In der Nähe der Tswapong Hills gelegen, bekannt für die kurzlebige Lerala-Diamantenmine.",
    "Ein Dorf nahe dem Limpopo-Fluss, das die Grenze zwischen Botswana und Südafrika markiert.",
    "Ein malerisches Dorf an den Ausläufern der wunderschönen Tswapong-Bergkette.",
    "Ein kulturell vielfältiges Dorf am Fluss Shashe nordwestlich von Francistown.",
    "Ein wichtiges Kreuzungsdorf, das Verbindungen zu den nördlichen Touristenbezirken bietet.",
    "Eine landwirtschaftliche Siedlung, bekannt für ihre starke Gemeinschaft und traditionelle Rinderzucht.",
    "Ein abgelegenes Dorf am westlichen Rand des Okavango-Deltas.",
    "Eine Grenzstadt, die eine wichtige Verkehrsverbindung zwischen Botswana und Namibia bietet.",
    "Ein wichtiger Rastplatz entlang des Trans-Kalahari-Highways, der nach Namibia führt.",
    "Eines der Hauptdörfer im nördlichen Kgalagadi-Distrikt, umgeben von Salzpfannen.",
    "Ein landwirtschaftlicher Knotenpunkt im Central District mit einer wachsenden lokalen Wirtschaft.",
    "Ein traditionelles ländliches Dorf mit sanften Ebenen, die sich für die Rinderzucht eignen.",
    "Das Verwaltungszentrum der Barolong-Farmen, einer bedeutenden getreideproduzierenden Region.",
    "Ein zentraler Knotenpunkt für ländliche Gemeinden im westlichen Teil des Southern District.",
    "Zwischen Hügeln eingebettet, ist es berühmt als Heimat einer Brutkolonie von Kapgeiern.",
    "Eine Siedlung, die für ihren Bahnhof bekannt ist, der den grenzüberschreitenden Handel erleichtert.",
    "Das südlichste Dorf in Botswana und ein wichtiger Grenzübergang nach Südafrika.",
    "Ein schnell entwickelnder Vorort, der südlich der Stadt Francistown liegt.",
    "Die Verwaltungshauptstadt des North-East District und das Herz der Kalanga-Kultur.",
    "Ein ruhiges, traditionelles Dorf zwischen kleinen Hügeln im Southern District.",
    "Ein Dorf, das als primärer Ausgangspunkt für Ausflüge in die Makgadikgadi-Pfannen dient.",
    "Berühmt für seine lokale Weberkooperative, die atemberaubende traditionelle Wandteppiche herstellt.",
    "In der Nähe des Bokaa-Damms gelegen, dient es als ruhige Wohn- und landwirtschaftliche Gemeinde.",
    "Ein Dorf entlang der A1-Autobahn, das Teil des kulturell reichen Kgatleng-Distrikts ist."
]

descriptions_hu = [
    "Botswana fővárosa, amely a Gaborone Vadrezervátumról és gyors modern fejlődéséről ismert.",
    "Botswana egyik legrégebbi városa, amely egykor Dél-Afrika első aranylázának központja volt.",
    "A Kalahári-sivatag kapuja, egyben Botswana legnagyobb hagyományos falva.",
    "Botswana turisztikai fővárosa és az Okavango-delta elsődleges kapuja.",
    "Gyorsan növekvő város Gaborone közelében, amely nagyrészt hatalmas külvárosként működik.",
    "Történelmi falu, amely több botswanai elnök szülőhelyeként ismert.",
    "Hegyvidéki terepen fekszik, és a Bangwaketse törzs hagyományos fővárosa.",
    "A Kalahári-sivatag szélén található város jelentős vasúti csomópontként szolgál.",
    "A Bakgatla nép otthona, hagyományosan festett házairól és kulturális örökségéről ismert.",
    "Gyorsan növekvő ipari központ, amelyet a közeli Morupule szénbánya és erőmű hajt.",
    "Jelentős település Gaborone szomszédságában, közel a dél-afrikai határhoz.",
    "Nyüzsgő város, amely a Balete nép törzsi fővárosaként szolgál.",
    "Jelentős bányaváros, amelyet számos nagy gyémántbánya vesz körül.",
    "Mezőgazdasági és oktatási központ a Shashe folyó mentén.",
    "Egyedülálló sziklás kiemelkedéseiről és erős mezőgazdasági gyökereiről ismert település.",
    "Hagyományos fazekasságáról híres, festői gránittömbök között elhelyezkedő település.",
    "Zárt bányaváros a Jwaneng gyémántbánya körül, amely a világ egyik leggazdagabb lelőhelye.",
    "A Bobirwa alkörzet közigazgatási központja, amely féldrágaköveiről ismert.",
    "Szigorúan őrzött bányaváros, amely a világ egyik legnagyobb külszíni gyémántbányájának ad otthont.",
    "A Kalahári fővárosaként ismert város, amely a helyi szarvasmarha-tenyésztés központja.",
    "Kritikus kapu a Chobe Nemzeti Parkhoz, egyben négy afrikai ország találkozási pontja.",
    "Vidéki város a Kalahári-sivatag keleti peremén.",
    "Nagy falu a Central District-ben, amely szorosan kötődik a regionális oktatási intézményekhez.",
    "Gaborone közeli falu, amely egyre inkább ingázó lakóövezetté válik.",
    "Békés település, amely a főváros közelsége miatt gyorsan növekszik.",
    "Fontos közigazgatási központ a száraz déli Kalaháriban.",
    "Kulcsfontosságú település az északnyugati kerületben, amely az Okavango Serpenyő kapujaként szolgál.",
    "Hatalmas történelmi jelentőségű hely, amely egykor a Bamangwato nép fővárosa volt.",
    "Sziklás tájakkal körülvett mezőgazdasági falu a Kweneng kerületben.",
    "Gyorsan terjeszkedő falu, amely lassan egybeolvad a nagyobb Gaborone városi területtel.",
    "Növekvő lakófalu, amely a közeli Metsimotlhabe folyóról kapta a nevét.",
    "Ősi település, amely az egyik fontos vízforrás, a Letsibogo-gát közelében helyezkedik el.",
    "Az Okavango folyón található város, amely kiváló tigris-halászatáról és gazdag madárvilágáról híres.",
    "A Közép-Kalahári Vadrezervátum kapuja, amely a Boteti folyó mentén fekszik.",
    "Kis mezőgazdasági falu a Mahalapye és Palapye közötti A1-es főút mentén.",
    "Fontos útkereszteződés és az elsődleges belépési pont a látványos Makgadikgadi-sósikságokra.",
    "A Tswapong-hegység közelében található, az efemer Lerala gyémántbányáról ismert település.",
    "A Limpopo folyó melletti falu, amely a Botswana és Dél-Afrika közötti határt jelöli.",
    "Festői falu, amely a gyönyörű Tswapong-hegység lábánál fekszik.",
    "Kulturálisan sokszínű falu, amely Francistowntól északnyugatra, a Shashe folyó mentén található.",
    "Fontos csomóponti falu, amely az északi turisztikai negyedek felé biztosít útvonalakat.",
    "Erős közösségéről és hagyományos szarvasmarha-tenyésztéséről ismert mezőgazdasági település.",
    "Félreeső falu az Okavango-delta nyugati szélén.",
    "Határváros, amely kritikus közlekedési kapcsolatot biztosít Botswana és Namíbia között.",
    "Fontos pihenőhely a Namíbiát összekötő Transz-Kalahári autópálya mentén.",
    "Az északi Kgalagadi kerület egyik fő falva, amelyet hatalmas sópáncélok vesznek körül.",
    "Mezőgazdasági kereszteződés a Central District-ben, növekvő helyi gazdasággal.",
    "Hagyományos vidéki falu, amelyet szarvasmarha-tenyésztésre alkalmas dombos síkságok jellemeznek.",
    "A Barolong farmok, egy jelentős gabonatermelő régió közigazgatási központja.",
    "A Southern District nyugati részének vidéki közösségeinek központi csomópontja.",
    "Hegyek között megbúvó település, amely híres a fokföldi keselyűk költőtelepéről.",
    "Vasútállomásáról ismert település, amely megkönnyíti a határon átnyúló kereskedelmet.",
    "Botswana legdélibb falva és jelentős határátkelőhely Dél-Afrika felé.",
    "Gyorsan fejlődő külváros, amely Francistown városától délre fekszik.",
    "Az Északkeleti kerület közigazgatási fővárosa és a Kalanga kultúra szíve.",
    "Csendes, hagyományos falu, amely kis dombok között terül el a Southern District-ben.",
    "Falu, amely elsődleges kiindulópontként szolgál a Makgadikgadi-sósikságokra induló túrákhoz.",
    "Helyi takács-szövetkezetéről híres, amely lenyűgöző hagyományos kárpitokat készít.",
    "A Bokaa-gát közelében található, nyugodt lakó- és mezőgazdasági közösségként szolgál.",
    "Az A1-es autópálya mentén fekvő falu, amely a kulturálisan gazdag Kgatleng kerület része."
]

descriptions_ro = [
    "Capitala Botswanei, cunoscută pentru Rezervația Gaborone Game și dezvoltarea sa modernă rapidă.",
    "Unul dintre cele mai vechi orașe din Botswana și fost centru al primei goane după aur din sudul Africii.",
    "Poarta de intrare în Deșertul Kalahari și cel mai mare sat tradițional din Botswana.",
    "Capitala turistică a Botswanei și principala poartă de acces către Delta Okavango.",
    "Un oraș cu o creștere rapidă în apropiere de Gaborone, funcționând în mare parte ca o suburbie extinsă.",
    "Un sat istoric cunoscut ca locul de naștere al mai multor președinți botswanezi.",
    "Situat pe un teren muntos, este capitala tradițională a tribului Bangwaketse.",
    "Poziționat la marginea Deșertului Kalahari, servește ca un nod feroviar major.",
    "Căminul poporului Bakgatla, cunoscut pentru casele sale tradiționale pictate și patrimoniul cultural.",
    "Un centru industrial cu o creștere rapidă condus de mina de cărbune și centrala electrică Morupule.",
    "Un oraș major adiacent la Gaborone, situat aproape de granița cu Africa de Sud.",
    "Un oraș plin de viață care servește drept capitală tribală a poporului Balete.",
    "Un important oraș minier înconjurat de mai multe mine majore de diamante.",
    "Un centru agricol și educațional situat de-a lungul râului Shashe.",
    "Caracterizat prin formațiunile sale stâncoase unice și rădăcini agricole puternice.",
    "Renumit pentru ceramica sa tradițională și situat printre bolovani pitorești de granit.",
    "Un oraș minier închis construit în jurul minei de diamante Jwaneng, una dintre cele mai bogate din lume.",
    "Centrul administrativ al subdistrictului Bobirwa, cunoscut pentru pietrele sale semiprețioase.",
    "Un oraș minier puternic securizat care găzduiește una dintre cele mai mari mine de diamante în aer liber.",
    "Cunoscut sub numele de capitala regiunii Kalahari, servind ca centru pentru fermierii locali de vite.",
    "O poartă crucială către Parcul Național Chobe și punctul de întâlnire al patru țări africane.",
    "Un oraș rural situat la marginile estice ale Deșertului Kalahari.",
    "Un sat mare din Districtul Central cu legături puternice cu instituțiile de învățământ regionale.",
    "Un sat din apropierea Gaboronei care a devenit din ce în ce mai mult o zonă rezidențială pentru navetiști.",
    "O așezare pașnică care cunoaște o creștere datorită apropierii sale de capitală.",
    "Un important centru administrativ situat în sudul arid al deșertului Kalahari.",
    "O așezare cheie în Districtul de Nord-Vest, acționând ca o poartă către coada regiunii Okavango.",
    "Un loc cu o imensă semnificație istorică care a servit drept capitală pentru poporul Bamangwato.",
    "Un sat agricol înconjurat de peisaje stâncoase în Districtul Kweneng.",
    "Un sat în expansiune rapidă care s-a contopit cu zona urbană extinsă Gaborone.",
    "Un sat rezidențial în creștere, numit după râul din apropiere Metsimotlhabe.",
    "O așezare antică poziționată aproape de barajul Letsibogo, o importantă sursă de apă.",
    "Situat pe râul Okavango, este renumit pentru pescuitul excelent și o viață bogată a păsărilor.",
    "Un oraș poartă către Rezervația de Vânătoare Kalahari Central, situat de-a lungul râului Boteti.",
    "Un mic sat agricol de-a lungul autostrăzii principale A1 între Mahalapye și Palapye.",
    "Un oraș crucial la o răscruce și punctul principal de intrare în spectaculoasele salinări Makgadikgadi.",
    "Situat lângă dealurile Tswapong, cunoscut pentru mina de diamante Lerala.",
    "Un sat aproape de râul Limpopo, marcând granița dintre Botswana și Africa de Sud.",
    "Un sat pitoresc așezat la poalele frumosului lanț muntos Tswapong.",
    "Un sat divers din punct de vedere cultural situat de-a lungul râului Shashe la nord-vest de Francistown.",
    "Un important sat de legătură care oferă rute către districtele turistice din nord.",
    "O așezare agricolă cunoscută pentru comunitatea sa puternică și tradițiile de creștere a vitelor.",
    "Un sat izolat la marginea vestică a Deltei Okavango.",
    "Un oraș de graniță care oferă o legătură de transport critică între Botswana și Namibia.",
    "Un popas vital de-a lungul autostrăzii Trans-Kalahari care face legătura cu Namibia.",
    "Unul dintre cele mai importante sate din districtul nordic Kgalagadi, înconjurat de salinări.",
    "O răscruce agricolă în Districtul Central, cu o economie locală în creștere.",
    "Un sat rural tradițional având câmpii întinse potrivite pentru creșterea vitelor.",
    "Centrul administrativ al fermelor Barolong, o regiune semnificativă producătoare de cereale.",
    "Un centru pentru comunitățile rurale din partea de vest a Districtului de Sud.",
    "Ascuns între dealuri, este faimos ca adăpost al coloniei de vulturi pelereni.",
    "O așezare cunoscută pentru gara sa feroviară care facilitează comerțul transfrontalier.",
    "Cel mai sudic sat din Botswana și un punct major de trecere a frontierei în Africa de Sud.",
    "O suburbie cu o dezvoltare rapidă situată chiar la sud de orașul Francistown.",
    "Capitala administrativă a Districtului de Nord-Est și inima culturii Kalanga.",
    "Un sat tradițional și liniștit, situat printre dealuri mici în Districtul de Sud.",
    "Un sat ce acționează ca un punct de plecare principal pentru excursii în zona Makgadikgadi.",
    "Faimos pentru cooperativa locală de țesători care produce tapițerii tradiționale uimitoare.",
    "Situat în apropierea barajului Bokaa, servește ca o comunitate rezidențială și agricolă liniștită.",
    "Un sat de-a lungul autostrăzii A1 care face parte din Districtul Kgatleng, bogat cultural."
]

descriptions_en = [
    "Capital of Botswana, known for the Gaborone Game Reserve and its rapid modern development.",
    "One of the oldest towns in Botswana and a former center of southern Africa's first gold rush.",
    "Gateway to the Kalahari Desert and the largest traditional village in Botswana.",
    "The tourism capital of Botswana and the primary gateway to the Okavango Delta.",
    "A rapidly growing town near Gaborone, functioning largely as a sprawling suburb.",
    "A historic village known as the birthplace of several of Botswana's presidents.",
    "Located in mountainous terrain, it is the traditional capital of the Bangwaketse tribe.",
    "Positioned on the edge of the Kalahari Desert, it serves as a major railway junction.",
    "Home to the Bakgatla people, known for its traditional painted houses and cultural heritage.",
    "A rapidly growing industrial hub driven by the nearby Morupule Colliery and power station.",
    "A major town adjacent to Gaborone, situated close to the South African border.",
    "A bustling town serving as the tribal capital of the Balete people.",
    "A significant mining town surrounded by several major diamond mines.",
    "An agricultural and educational center located along the Shashe River.",
    "Characterized by its unique rocky outcrops and strong agricultural roots.",
    "Renowned for its traditional pottery and situated among scenic granite boulders.",
    "A closed mining town built around the Jwaneng diamond mine, one of the richest in the world.",
    "The administrative center of the Bobirwa sub-district, known for its semi-precious stones.",
    "A heavily secured mining town that hosts one of the world's largest open-pit diamond mines.",
    "Known as the capital of the Kalahari, serving as a hub for the local cattle farming industry.",
    "A crucial gateway to Chobe National Park and the meeting point of four African countries.",
    "A rural town located on the eastern fringes of the Kalahari Desert.",
    "A large village in the Central District with strong ties to regional educational institutions.",
    "A village near Gaborone that has increasingly become a residential commuter area.",
    "A peaceful settlement experiencing growth due to its proximity to the capital.",
    "An important administrative center located in the arid southern Kalahari.",
    "A key settlement in the North-West District, acting as a gateway to the Okavango Panhandle.",
    "A place of immense historical significance that served as a capital for the Bamangwato people.",
    "An agricultural village surrounded by rocky landscapes in the Kweneng District.",
    "A rapidly expanding village that has merged into the greater Gaborone urban area.",
    "A growing residential village named after the nearby Metsimotlhabe River.",
    "An ancient settlement positioned close to the Letsibogo Dam, an important water source.",
    "Located on the Okavango River, it is famous for excellent tiger fishing and rich birdlife.",
    "A gateway town to the Central Kalahari Game Reserve, situated along the Boteti River.",
    "A small agricultural village along the main A1 highway between Mahalapye and Palapye.",
    "A vital crossroads town and the primary entry point to the spectacular Makgadikgadi Pans.",
    "Located near the Tswapong Hills, known for the ephemeral Lerala diamond mine.",
    "A village near the Limpopo River, marking the border between Botswana and South Africa.",
    "A scenic village set against the foothills of the beautiful Tswapong range.",
    "A culturally diverse village located along the Shashe River northwest of Francistown.",
    "An important junction village providing routes to the northern tourist districts.",
    "An agricultural settlement known for its strong community and cattle farming traditions.",
    "A remote village on the western edge of the Okavango Delta.",
    "A border town providing a critical transport link between Botswana and Namibia.",
    "A vital rest stop along the Trans-Kalahari Highway connecting to Namibia.",
    "One of the major villages in the northern Kgalagadi district, surrounded by salt pans.",
    "An agricultural crossroads in the Central District with a growing local economy.",
    "A traditional rural village featuring rolling plains suited for cattle ranching.",
    "The administrative center of the Barolong farms area, a significant grain-producing region.",
    "A central hub for rural communities in the western part of the Southern District.",
    "Nestled between hills, it is famously home to the breeding colony of Cape Vultures.",
    "A settlement known for its railway station facilitating cross-border trade.",
    "The southernmost village in Botswana and a major border crossing post into South Africa.",
    "A rapidly developing suburb situated just south of the city of Francistown.",
    "The administrative capital of the North-East District and the heart of the Kalanga culture.",
    "A quiet, traditional village situated among small hills in the Southern District.",
    "A village acting as a primary starting point for excursions into the Makgadikgadi Pans.",
    "Famous for its local weaver cooperative which produces stunning traditional tapestries.",
    "Located near the Bokaa Dam, it serves as a tranquil residential and agricultural community.",
    "A village along the A1 highway that forms part of the culturally rich Kgatleng District."
]

facts_de = [
    ["Gegründet im Jahr 1964, um Mafikeng als Hauptstadt zu ersetzen.", "Die Stadt beheimatet die Universität von Botswana."],
    ["Benannt nach dem Goldgräber Daniel Francis.", "Besitzt den internationalen Flughafen Francistown."],
    ["Bevölkerung liegt bei über 70.000 Menschen.", "Die Scottish Livingstone Hospital befindet sich hier."],
    ["Maun wurde 1915 als Hauptstadt des Batawana-Volkes gegründet.", "Der Flughafen bietet viele Flüge ins Delta an."],
    ["Wurde früher als unabhängiges Dorf betrachtet.", "Jetzt in die urbane Ausbreitung von Gaborone integriert."],
    ["Viele der Khama-Herrscher liegen in Serowe begraben.", "Beherbergt das Khama III Memorial Museum."],
    ["Die Siedlung liegt hoch auf einer Klippe.", "Die landwirtschaftliche Produktion in der Umgebung ist sehr hoch."],
    ["Zentrum für Züge, die zwischen Gaborone und Francistown verkehren.", "Es liegt auf dem südlichen Wendekreis."],
    ["Gegründet von den Bakgatla, als sie 1871 aus Südafrika flohen.", "Das Phuthadikobo Museum befindet sich auf dem Hügel."],
    ["Nahe der Khama Rhino Sanctuary gelegen.", "Besitzt eine große Morupule-Kohlenmine."],
    ["Nur wenige Kilometer vom südafrikanischen Grenzübergang entfernt.", "Eine wichtige Vorstadtgemeinde der Hauptstadt."],
    ["Befindet sich südlich der Hauptstadt in der Nähe des Notwane-Flusses.", "Herstellung lokaler Töpferwaren ist traditionell erhalten."],
    ["Das Orapa-Bergbaugebiet ist nur wenige Kilometer entfernt.", "Die Stadt entwickelte sich wegen des Diamantenabbaus."],
    ["Die Stadt liegt nahe dem Shashe-Damm.", "Viele der Einwohner arbeiten im landwirtschaftlichen Sektor."],
    ["Bekannt für riesige Granitsteine, die die Landschaft prägen.", "Die Gemeinschaft widmet sich stark der Landwirtschaft."],
    ["Die Thamaga Pottery ist im ganzen Land berühmt.", "Liegt in der Nähe des Metsemotlhaba-Flusses."],
    ["Die Jwaneng-Mine begann 1982 mit der Produktion.", "Wird wegen des Reichtums 'Prinz der Minen' genannt."],
    ["Die Gegend ist bekannt für wunderschöne Halbedelsteine.", "Der Motloutse-Fluss durchquert dieses Gebiet."],
    ["Die Mine wurde 1971 eröffnet.", "Sie bleibt wegen der Minensicherheit eine streng bewachte Stadt."],
    ["Rinderzucht ist die Hauptstütze der Wirtschaft.", "Viele Buschleute leben in der Umgebung der Stadt."],
    ["Grenzt an den Chobe-Fluss und den Nationalpark.", "Es gibt keine Grenzkontrollen zu den freilaufenden Wildtieren."],
    ["Dient als Ausgangspunkt für Ausflüge tief in die Kalahari.", "Der Khutse Game Reserve liegt in der Nähe."],
    ["Verfügt über ein wichtiges Krankenhaus und ein Lehrerausbildungsinstitut.", "Liegt am Rande des Makgadikgadi-Beckens."],
    ["Liegt auf felsigen Hügeln etwa 15 km von Gaborone entfernt.", "Ein bedeutendes Wohngebiet für Hauptstadt-Arbeiter."],
    ["Das Dorf hat in den letzten zehn Jahren einen Immobilienboom erlebt.", "Die Straßenverbindungen nach Gaborone wurden verbessert."],
    ["Ein abgelegener Vorposten nahe der südafrikanischen Grenze.", "Dient als Zentrum für die Kamelpatrouillen der Polizei."],
    ["Die Bevölkerung verlässt sich hauptsächlich auf Fischfang und Viehzucht.", "Ein Knotenpunkt für Reisen zum Okavango-Delta."],
    ["War im 19. Jahrhundert eine der größten Siedlungen im südlichen Afrika.", "Die Ruinen von alten Kirchen sind heute noch sichtbar."],
    ["Der Name bedeutet 'Berg der Löwen'.", "Die Region war früher für wilde Tiere bekannt."],
    ["Es hat eine schnelle Transformation vom Dorf zur Stadt erlebt.", "Eines der am dichtesten besiedelten Gebiete des Distrikts."],
    ["Die Bevölkerung wächst aufgrund der städtischen Abwanderung.", "Der Fluss Metsimotlhabe bietet eine Wasserquelle."],
    ["Liegt wenige Kilometer nördlich der Bergbaustadt Selebi-Phikwe.", "Der Letsibogo-Damm bietet Freizeitaktivitäten."],
    ["Ein Paradies für Vogelbeobachter.", "Einer der besten Orte, um nach dem afrikanischen Tigerfisch zu angeln."],
    ["Die Bewohner sind traditionell Viehhirten.", "Der Boteti-Fluss fließt nach starken Regenfällen."],
    ["Eine wichtige Anlaufstelle für Bauern in der Region.", "Verfügt über eine primäre Gesundheitsklinik."],
    ["Das nahegelegene Nata-Vogelschutzgebiet beherbergt Tausende von Flamingos.", "Die Stadt lebt vom durchgehenden Tourismus."],
    ["Das Dorf liegt malerisch an den Tswapong-Hügeln.", "Landwirtschaft und Rinderzucht sind die Lebensgrundlage."],
    ["Liegt im Osten in der Nähe der südafrikanischen Grenze.", "Ein ruhiger Ort mit Schwerpunkt auf Landwirtschaft."],
    ["Die Region ist reich an localer Stammesgeschichte.", "Die Tswapong-Hügel bieten eine atemberaubende Kulisse."],
    ["Ein lokales Zentrum, das nach dem Shashe-Fluss strukturiert ist.", "Liegt an der Hauptstraße nach Maun."],
    ["Befindet sich in einer Kreuzungszone zu nördlichen Regionen.", "Traditionelle Häuser sind immer noch weit verbreitet."],
    ["Ein wichtiges Zentrum für Viehzucht in der Gegend.", "Das Klima ist semiarid und heiß im Sommer."],
    ["Ein wichtiges Zentrum für die Versorgung abgelegener Delta-Gemeinschaften.", "Oft nur mit Geländewagen erreichbar."],
    ["Ein wichtiger Grenzposten zu Namibia (Mamuno).", "Dient dem wachsenden grenzüberschreitenden Lkw-Verkehr."],
    ["Die Stadt ist eine Oase auf dem langen Trans-Kalahari-Highway.", "Bietet wichtige Tankstellen und Rastplätze."],
    ["Wird häufig von Reisenden auf dem Weg zum Kgalagadi Transfrontier Park passiert.", "Von weiten Salzpfannen umgeben."],
    ["Bietet Anschlussstraßen zu den Bergbaugebieten in Selebi-Phikwe.", "Die Bevölkerung ist im letzten Jahrzehnt gewachsen."],
    ["Es finden lokale Viehauktionen statt.", "Eine der beständigsten ländlichen Siedlungen im Distrikt."],
    ["Ein politisches und administratives Zentrum für die Rolong-Leute.", "Gilt als die Kornkammer des Südens."],
    ["Hat ein Wüstenklima mit spärlichen Niederschlägen.", "Viele Buschmann-Gemeinschaften leben in den Außenbezirken."],
    ["Der nahegelegene Mannyelanong Hill schützt eine Kolonie von Kapgeiern.", "Ein beliebtes Ziel für Wanderer."],
    ["Besitzt eine Station an der Hauptbahnlinie.", "Handel und Viehzucht stützen die lokale Wirtschaft."],
    ["Ein geschäftiger Zollposten für die Ein- und Ausreise.", "Ein wichtiges Tor für den Handel."],
    ["Ursprünglich ein kleiner Vorort, heute eine wachsende Stadt.", "Profitierte enorm von der Nähe zu Francistown."],
    ["Hier leben viele Kalanga-sprechende Einwohner.", "Es ist der Verwaltungssitz des North-East District."],
    ["Es hat starke Verbindungen zu den benachbarten ländlichen Gemeinschaften.", "Die Viehzucht ist der wichtigste Wirtschaftszweig."],
    ["Tausende von Makgadikgadi-Baobabs befinden sich in der Nähe.", "Ein Stopp für Expeditionen zu den Nxai Pans."],
    ["Die Odi Weavers sind seit den 1970er Jahren eine Institution.", "Die Stadt bietet malerische Ausblicke auf umliegende Hügel."],
    ["Der Bokaa-Damm zieht oft Vogelbeobachter an.", "Eine schnell wachsende ländliche Siedlung."],
    ["Bildet eine kontinuierliche Siedlungslinie mit Mochudi.", "Die Bewohner pendeln oft zur Arbeit in die Hauptstadt."]
]

facts_hu = [
    ["1964-ben alapították, hogy átvegye Mafikengtől a fővárosi rangot.", "A város ad otthont a Botswanai Egyetemnek."],
    ["Daniel Francis aranyásóról kapta a nevét.", "Nemzetközi repülőtérrel rendelkezik."],
    ["Lakossága meghaladja a 70 000 főt.", "Itt található a Scottish Livingstone Kórház."],
    ["Maunt 1915-ben alapították a Batawana nép fővárosaként.", "A repülőtér számos járatot indít a deltába."],
    ["Korábban független falunak tekintették.", "Mára beolvadt Gaborone városi övezetébe."],
    ["Számos Khama uralkodó nyugszik Serowében.", "Itt található a Khama III Emlékmúzeum."],
    ["A település egy sziklás fennsíkon fekszik.", "A környék mezőgazdasági termelése nagyon magas."],
    ["A Gaborone és Francistown közötti vonatok központja.", "Közvetlenül a Baktérítőn helyezkedik el."],
    ["A Bakgatla nép alapította, amikor 1871-ben Dél-Afrikából menekültek.", "A Phuthadikobo Múzeum a hegyen található."],
    ["A Khama Orrszarvú Menedékhely közelében fekszik.", "Nagy szénbányával rendelkezik Morupule-ban."],
    ["Csak néhány kilométerre a dél-afrikai határátkelőtől.", "A főváros fontos elővárosi közössége."],
    ["A fővárostól délre, a Notwane folyó közelében található.", "A helyi fazekasság hagyománya még ma is él."],
    ["Az Orapa bányaterület csak néhány kilométerre van.", "A város a gyémántbányászat miatt fejlődött ki."],
    ["A város a Shashe-gát közelében fekszik.", "A lakosok nagy része a mezőgazdasági szektorban dolgozik."],
    ["A tájat uraló hatalmas gránitszikláiról ismert.", "A közösség erősen elkötelezett a mezőgazdaság iránt."],
    ["A Thamaga Pottery (fazekasság) országszerte híres.", "A Metsemotlhaba folyó közelében helyezkedik el."],
    ["A Jwaneng bánya 1982-ben kezdte meg a termelést.", "Gazdagsága miatt a 'Bányák Hercegének' is nevezik."],
    ["A terület gyönyörű féldrágaköveiről ismert.", "A Motloutse folyó keresztezi ezt a területet."],
    ["A bányát 1971-ben nyitották meg.", "A bányabiztonság miatt továbbra is szigorúan őrzött város."],
    ["A szarvasmarha-tenyésztés a gazdaság alappillére.", "Sok busman él a város környékén."],
    ["A Chobe folyóval és a nemzeti parkkal határos.", "Nincsenek kerítések, a vadállatok szabadon kószálhatnak."],
    ["Kiindulópontként szolgál a Kalaháriba irányuló mélyebb túrákhoz.", "A Khutse Vadrezervátum a közelben található."],
    ["Fontos kórházzal és tanárképző intézettel rendelkezik.", "A Makgadikgadi-medence szélén fekszik."],
    ["Sziklás dombokon fekszik, mintegy 15 km-re Gaborone-tól.", "Jelentős lakóövezet a fővárosban dolgozók számára."],
    ["A falu ingatlanbummot élt át az elmúlt évtizedben.", "A Gaborone-ba vezető közúti kapcsolatok jelentősen javultak."],
    ["Távoli előőrs a dél-afrikai határ közelében.", "A rendőrség teve-őrjárataiknak központjaként szolgál."],
    ["A lakosság főként halászatra és állattenyésztésre támaszkodik.", "Fontos csomópont az Okavango-delta felé tartó utazásokhoz."],
    ["A 19. században Dél-Afrika egyik legnagyobb települése volt.", "Az ősi templomok romjai ma is láthatók."],
    ["A név jelentése: 'Oroszlánok hegye'.", "A régió egykor vadállatairól volt híres."],
    ["Gyors átalakuláson ment keresztül, faluból várossá vált.", "A kerület egyik legsűrűbben lakott területe."],
    ["A lakosság a városi elvándorlás miatt növekszik.", "A Metsimotlhabe folyó vízellátást biztosít a településnek."],
    ["Néhány kilométerre északra fekszik a bányaváros Selebi-Phikwétől.", "A Letsibogo-gát népszerű rekreációs lehetőségeket kínál."],
    ["A madármegfigyelők paradicsoma.", "Az egyik legjobb hely az afrikai tigrishal horgászatára."],
    ["A lakosok hagyományosan szarvasmarha-pásztorok.", "A Boteti folyó a heves esőzések után megtelik vízzel."],
    ["Fontos találkozóhely a régió gazdái számára.", "Alapfokú egészségügyi klinikával rendelkezik."],
    ["A közeli Nata madármenedék flamingók ezreinek ad otthont.", "A város nagymértékben függ az átutazó turizmustól."],
    ["A falu festői környezetben, a Tswapong-hegyeknél fekszik.", "A mezőgazdaság és az állattenyésztés a megélhetés alapja."],
    ["Keleten, a dél-afrikai határ közelében helyezkedik el.", "Csendes település, a mezőgazdaságra összpontosítva."],
    ["A régió gazdag a helyi törzsi történelemben.", "A Tswapong-hegyek lenyűgöző hátteret biztosítanak."],
    ["A Shashe folyó mentén felépült helyi központ.", "A Maun felé vezető főútvonal mentén található."],
    ["Fontos csomóponti zónában helyezkedik el az északi régiók felé.", "A hagyományos házak még mindig széles körben elterjedtek."],
    ["Az állattenyésztés fontos központja a környéken.", "Az éghajlat félszáraz, a nyár pedig forró."],
    ["Kulcsfontosságú központ a távoli delta-közösségek ellátásához.", "Gyakran csak terepjáróval közelíthető meg."],
    ["Fontos határállomás Namíbia felé (Mamuno).", "Kiszolgálja a növekvő határon átnyúló teherforgalmat."],
    ["A város oázisként szolgál a hosszú Transz-Kalahári autópályán.", "Fontos benzinkutakat és pihenőhelyeket kínál."],
    ["A Kgalagadi Transfrontier Park felé tartó utazók gyakran áthaladnak rajta.", "Hatalmas sósikságok veszik körül."],
    ["Csatlakozó utakat kínál a Selebi-Phikwe bányaterületekhez.", "A lakosság száma az elmúlt évtizedben megnőtt."],
    ["Rendszeresen tartanak helyi szarvasmarha-árveréseket.", "A kerület egyik legkitartóbb vidéki települése."],
    ["A Rolong nép politikai és közigazgatási központja.", "Dél éléstáraként tartják számon."],
    ["Sivatagi éghajlattal rendelkezik, gyér csapadékkal.", "Számos busman közösség él a külvárosokban."],
    ["A közeli Mannyelanong-hegy a fokföldi keselyűk kolóniáját védi.", "A hegymászók körében is népszerű célpont."],
    ["Állomással rendelkezik a fő vasútvonalon.", "A kereskedelem és az állattenyésztés támogatja a helyi gazdaságot."],
    ["Forgalmas vámhivatal a belépéshez és kilépéshez.", "Fontos kereskedelmi kapu Dél-Afrika felé."],
    ["Eredetileg egy kis külváros, ma növekvő város.", "Nagyon sokat profitált Francistown közelségéből."],
    ["Sok kalanga nyelvű lakos él itt.", "Ez az Északkeleti kerület közigazgatási központja."],
    ["Erős kapcsolatokat ápol a szomszédos vidéki közösségekkel.", "A szarvasmarha-tenyésztés a legfontosabb gazdasági ágazat."],
    ["Makgadikgadi majomkenyérfák ezrei találhatók a közelben.", "Népszerű megálló a Nxai-tavakhoz induló expedíciók számára."],
    ["Az Odi Weavers (takácsok) az 1970-es évek óta létező intézmény.", "A város festői kilátást nyújt a környező dombokra."],
    ["A Bokaa-gát gyakran vonzza a madármegfigyelőket.", "Gyorsan növekvő vidéki település."],
    ["Folyamatos települési vonalat alkot Mochudi városával.", "A lakosok gyakran ingáznak a fővárosba dolgozni."]
]

facts_ro = [
    ["Fondată în 1964 pentru a înlocui Mafikeng ca și capitală a națiunii.", "Orașul găzduiește Universitatea din Botswana."],
    ["Numit după prospectorul de aur Daniel Francis.", "Deține Aeroportul Internațional Francistown."],
    ["Populația sa depășește 70.000 de locuitori.", "Spitalul Scottish Livingstone este situat aici."],
    ["Maun a fost fondat în 1915 ca reședință a poporului Batawana.", "Aeroportul are numeroase zboruri către deltă."],
    ["A fost considerat anterior un sat independent.", "Acum integrat în extinderea urbană a capitalei Gaborone."],
    ["Mulți dintre conducătorii Khama sunt îngropați în Serowe.", "Găzduiește Muzeul Memorial Khama III."],
    ["Așezarea se află la înălțime, pe o stâncă.", "Producția agricolă în zonele înconjurătoare este foarte mare."],
    ["Centru pentru trenurile care călătoresc între Gaborone și Francistown.", "Este situat direct pe Tropicul Capricornului."],
    ["Fondat de poporul Bakgatla când au fugit din Africa de Sud în 1871.", "Muzeul Phuthadikobo se află pe deal."],
    ["Situat în apropiere de Khama Rhino Sanctuary.", "Deține o mare mină de cărbune în Morupule."],
    ["La doar câțiva kilometri de punctul de trecere a frontierei cu Africa de Sud.", "O comunitate suburbană cheie pentru capitală."],
    ["Situat la sud de capitală, lângă râul Notwane.", "Tradiția ceramicii locale s-a păstrat până în prezent."],
    ["Zona minieră Orapa este la doar câțiva kilometri distanță.", "Orașul s-a dezvoltat datorită exploatării diamantelor."],
    ["Orașul se află în apropierea barajului Shashe.", "Multe dintre persoanele din oraș lucrează în sectorul agricol."],
    ["Cunoscut pentru bolovanii uriași de granit care presară peisajul.", "Comunitatea este puternic dedicată agriculturii."],
    ["Thamaga Pottery (Ceramica) este faimoasă în toată țara.", "Situat aproape de râul Metsemotlhaba."],
    ["Mina Jwaneng a început producția în anul 1982.", "Este numit 'Prințul Minelor' datorită bogăției sale uriașe."],
    ["Zona este renumită pentru pietrele semiprețioase frumoase.", "Râul Motloutse traversează această zonă a regiunii."],
    ["Mina a fost deschisă oficial în 1971.", "Rămâne un oraș strict păzit din cauza securității miniere."],
    ["Creșterea bovinelor este pilonul principal al economiei.", "Multe grupuri de boșimani locuiesc în apropierea orașului."],
    ["Se învecinează cu râul Chobe și cu parcul național.", "Nu există granițe îngrădite pentru fauna sălbatică."],
    ["Servește drept punct de lansare pentru drumeții adânci în Kalahari.", "Rezervația de Vânătoare Khutse este situată în apropiere."],
    ["Dispune de un spital important și un institut de formare a profesorilor.", "Este situat pe marginea bazinului Makgadikgadi."],
    ["Situat pe dealuri stâncoase la aproximativ 15 km de Gaborone.", "O zonă rezidențială importantă pentru lucrătorii din capitală."],
    ["Satul a cunoscut un boom imobiliar în ultimul deceniu.", "Legăturile rutiere cu Gaborone au fost mult îmbunătățite."],
    ["Un avanpost îndepărtat aproape de granița sud-africană.", "Servește drept centru pentru patrulele de poliție pe cămile."],
    ["Populația se bazează masiv pe pescuit și creșterea animalelor.", "Un nod crucial pentru călătoriile către Delta Okavango."],
    ["În secolul al 19-lea, a fost una dintre cele mai mari așezări din Africa de Sud.", "Ruinele bisericilor antice sunt încă vizibile."],
    ["Numele său înseamnă 'Muntele Leilor'.", "Regiunea era cunoscută în trecut pentru fauna sălbatică."],
    ["A cunoscut o transformare rapidă dintr-un sat în oraș.", "Este una dintre cele mai dens populate zone din district."],
    ["Populația crește datorită migrației către zonele urbane.", "Râul Metsimotlhabe asigură o sursă importantă de apă."],
    ["Situat la câțiva kilometri nord de orașul minier Selebi-Phikwe.", "Barajul Letsibogo oferă posibilități excelente de recreere."],
    ["Un adevărat paradis pentru observatorii de păsări.", "Unul dintre cele mai bune locuri pentru a pescui peștele tigru african."],
    ["Locuitorii sunt în mod tradițional crescători de vite.", "Râul Boteti curge de obicei după ploi abundente."],
    ["O piatră de temelie pentru fermierii din regiunea extinsă.", "Dispune de o clinică de asistență medicală primară."],
    ["Sanctuarul de Păsări Nata din apropiere găzduiește mii de flamingo.", "Orașul depinde în mare măsură de turismul de tranzit."],
    ["Satul este situat pitoresc pe dealurile Tswapong.", "Agricultura și creșterea animalelor sunt baza existenței."],
    ["Așezat în est, în apropiere de granița sud-africană.", "O locație liniștită, cu un accent puternic pe agricultură."],
    ["Regiunea este bogată în istoria triburilor locale.", "Dealurile Tswapong oferă un fundal peisagistic impresionant."],
    ["Un centru local structurat după râul Shashe.", "Se află pe ruta principală spre Maun."],
    ["Situat într-o zonă de intersecție către regiunile turistice din nord.", "Casele tradiționale sunt încă răspândite pe scară largă."],
    ["Un centru important pentru creșterea vitelor în zonă.", "Clima este semi-aridă și foarte caldă în timpul verii."],
    ["Un centru cheie pentru aprovizionarea comunităților îndepărtate din deltă.", "Adesea accesibil doar cu vehicule de teren."],
    ["Un post de frontieră major cu Namibia (Mamuno).", "Deservește traficul de camioane transfrontalier în creștere."],
    ["Orașul este o oază pe lunga autostradă Trans-Kalahari.", "Oferă stații de alimentare și spații de odihnă esențiale."],
    ["Adesea traversat de călătorii spre Parcul Transfrontalier Kgalagadi.", "Este înconjurat de vaste întinderi de sare."],
    ["Oferă drumuri de legătură către zonele miniere din Selebi-Phikwe.", "Populația a înregistrat o creștere în ultimul deceniu."],
    ["Aici se organizează în mod regulat licitații locale de vite.", "Una dintre cele mai durabile așezări rurale din district."],
    ["Un centru politic și administrativ pentru poporul Rolong.", "Este considerat a fi grânarul regiunii de sud."],
    ["Are o climă deșertică, cu precipitații rare și scăzute.", "Multe comunități de boșimani trăiesc la periferia orașului."],
    ["Dealul Mannyelanong din apropiere protejează o colonie de vulturi.", "O destinație de asemenea populară pentru excursioniști."],
    ["Are o stație pe linia feroviară principală a țării.", "Comerțul și creșterea animalelor susțin economia locală."],
    ["Un post vamal aglomerat pentru intrare și ieșire.", "O poartă comercială de importanță majoră."],
    ["La origine o mică suburbie, astăzi un oraș în plină dezvoltare.", "A beneficiat masiv de pe urma apropierii de Francistown."],
    ["Aici locuiesc mulți rezidenți vorbitori de limba Kalanga.", "Este sediul administrativ al Districtului Nord-Est."],
    ["Are legături strânse cu comunitățile rurale învecinate.", "Creșterea animalelor rămâne cea mai importantă industrie."],
    ["Mii de baobabi Makgadikgadi pot fi găsiți în apropiere.", "O oprire populară pentru expedițiile spre Platourile Nxai."],
    ["Cooperativa Odi Weavers este o instituție din anii 1970.", "Orașul oferă vederi pitorești la dealurile din jur."],
    ["Barajul Bokaa atrage adesea mulți observatori de păsări.", "O așezare rurală cu o rată de creștere foarte rapidă."],
    ["Formează o linie continuă de așezări alături de orașul Mochudi.", "Locuitorii fac adesea naveta pentru a lucra în capitală."]
]

descriptions_en = [
    "Capital of Botswana, known for the Gaborone Game Reserve and its rapid modern development.",
    "One of the oldest towns in Botswana and a former center of southern Africa's first gold rush.",
    "Gateway to the Kalahari Desert and the largest traditional village in Botswana.",
    "The tourism capital of Botswana and the primary gateway to the Okavango Delta.",
    "A rapidly growing town near Gaborone, functioning largely as a sprawling suburb.",
    "A historic village known as the birthplace of several of Botswana's presidents.",
    "Located in mountainous terrain, it is the traditional capital of the Bangwaketse tribe.",
    "Positioned on the edge of the Kalahari Desert, it serves as a major railway junction.",
    "Home to the Bakgatla people, known for its traditional painted houses and cultural heritage.",
    "A rapidly growing industrial hub driven by the nearby Morupule Colliery and power station.",
    "A major town adjacent to Gaborone, situated close to the South African border.",
    "A bustling town serving as the tribal capital of the Balete people.",
    "A significant mining town surrounded by several major diamond mines.",
    "An agricultural and educational center located along the Shashe River.",
    "Characterized by its unique rocky outcrops and strong agricultural roots.",
    "Renowned for its traditional pottery and situated among scenic granite boulders.",
    "A closed mining town built around the Jwaneng diamond mine, one of the richest in the world.",
    "The administrative center of the Bobirwa sub-district, known for its semi-precious stones.",
    "A heavily secured mining town that hosts one of the world's largest open-pit diamond mines.",
    "Known as the capital of the Kalahari, serving as a hub for the local cattle farming industry.",
    "A crucial gateway to Chobe National Park and the meeting point of four African countries.",
    "A rural town located on the eastern fringes of the Kalahari Desert.",
    "A large village in the Central District with strong ties to regional educational institutions.",
    "A village near Gaborone that has increasingly become a residential commuter area.",
    "A peaceful settlement experiencing growth due to its proximity to the capital.",
    "An important administrative center located in the arid southern Kalahari.",
    "A key settlement in the North-West District, acting as a gateway to the Okavango Panhandle.",
    "A place of immense historical significance that served as a capital for the Bamangwato people.",
    "An agricultural village surrounded by rocky landscapes in the Kweneng District.",
    "A rapidly expanding village that has merged into the greater Gaborone urban area.",
    "A growing residential village named after the nearby Metsimotlhabe River.",
    "An ancient settlement positioned close to the Letsibogo Dam, an important water source.",
    "Located on the Okavango River, it is famous for excellent tiger fishing and rich birdlife.",
    "A gateway town to the Central Kalahari Game Reserve, situated along the Boteti River.",
    "A small agricultural village along the main A1 highway between Mahalapye and Palapye.",
    "A vital crossroads town and the primary entry point to the spectacular Makgadikgadi Pans.",
    "Located near the Tswapong Hills, known for the ephemeral Lerala diamond mine.",
    "A village near the Limpopo River, marking the border between Botswana and South Africa.",
    "A scenic village set against the foothills of the beautiful Tswapong range.",
    "A culturally diverse village located along the Shashe River northwest of Francistown.",
    "An important junction village providing routes to the northern tourist districts.",
    "An agricultural settlement known for its strong community and cattle farming traditions.",
    "A remote village on the western edge of the Okavango Delta.",
    "A border town providing a critical transport link between Botswana and Namibia.",
    "A vital rest stop along the Trans-Kalahari Highway connecting to Namibia.",
    "One of the major villages in the northern Kgalagadi district, surrounded by salt pans.",
    "An agricultural crossroads in the Central District with a growing local economy.",
    "A traditional rural village featuring rolling plains suited for cattle ranching.",
    "The administrative center of the Barolong farms area, a significant grain-producing region.",
    "A central hub for rural communities in the western part of the Southern District.",
    "Nestled between hills, it is famously home to the breeding colony of Cape Vultures.",
    "A settlement known for its railway station facilitating cross-border trade.",
    "The southernmost village in Botswana and a major border crossing post into South Africa.",
    "A rapidly developing suburb situated just south of the city of Francistown.",
    "The administrative capital of the North-East District and the heart of the Kalanga culture.",
    "A quiet, traditional village situated among small hills in the Southern District.",
    "A village acting as a primary starting point for excursions into the Makgadikgadi Pans.",
    "Famous for its local weaver cooperative which produces stunning traditional tapestries.",
    "Located near the Bokaa Dam, it serves as a tranquil residential and agricultural community.",
    "A village along the A1 highway that forms part of the culturally rich Kgatleng District."
]

facts_en = [
    ["Founded in 1964 to replace Mafikeng as the national capital.", "The city is home to the University of Botswana."],
    ["Named after gold prospector Daniel Francis.", "Possesses the Francistown International Airport."],
    ["Population is well over 70,000 people.", "The Scottish Livingstone Hospital is located here."],
    ["Maun was founded in 1915 as the capital for the Batawana people.", "The airport has numerous flights straight into the Delta."],
    ["Was formerly considered an independent village.", "Now merged into the urban sprawl of Gaborone."],
    ["Many of the Khama rulers are buried in Serowe.", "Houses the Khama III Memorial Museum."],
    ["The settlement is situated high up on a cliff.", "Agricultural production in the surrounding areas is very high."],
    ["Hub for trains travelling between Gaborone and Francistown.", "It is situated directly on the Tropic of Capricorn."],
    ["Founded by the Bakgatla people when they fled South Africa in 1871.", "The Phuthadikobo Museum is located on the hill."],
    ["Situated near the Khama Rhino Sanctuary.", "Hosts a large Morupule Coal Mine."],
    ["Just a few kilometers from the South African border crossing.", "A key suburban community of the capital city."],
    ["Located south of the capital near the Notwane River.", "Making of local pottery has been traditionally preserved."],
    ["The Orapa mining area is only a few kilometers away.", "The town developed due to the diamond mining."],
    ["The town is near the Shashe Dam.", "A lot of people here work in the agricultural sector."],
    ["Known for huge granite boulders that dot the landscape.", "The community is strongly dedicated to farming."],
    ["The Thamaga Pottery is famous throughout the country.", "Situated near the Metsemotlhaba River."],
    ["The Jwaneng mine began production in 1982.", "It is called the 'Prince of Mines' due to its huge wealth."],
    ["The area is known for beautiful semi-precious stones.", "The Motloutse River crosses this area of the region."],
    ["The mine was officially opened in 1971.", "Remains a strictly guarded town because of mining security."],
    ["Cattle farming is the mainstay of the economy.", "Many Bushmen groups live in the outskirts of the town."],
    ["Borders the Chobe River and the national park.", "There are no fenced boundaries for the wandering wildlife."],
    ["Serves as a launch pad for treks deep into the Kalahari.", "The Khutse Game Reserve is located nearby."],
    ["Features an important hospital and a teacher training institute.", "Positioned on the edge of the Makgadikgadi Basin."],
    ["Located on rocky hills about 15km from Gaborone.", "A major residential area for workers from the capital."],
    ["The village has experienced a real estate boom in the last decade.", "Road links to Gaborone have been greatly improved."],
    ["A remote outpost near the South African border.", "Serves as a center for the camel police patrols."],
    ["The population relies heavily on fishing and livestock farming.", "A crucial node for travel to the Okavango Delta."],
    ["During the 19th century, it was one of the largest settlements in Southern Africa.", "Ruins of ancient churches are still visible."],
    ["Its name translates to 'Mountain of Lions'.", "The region was formerly known for its wild animals."],
    ["Has seen rapid transformation from village to town.", "One of the most densely populated areas of the district."],
    ["The population is growing due to urban migration.", "The Metsimotlhabe River provides a water source."],
    ["Located a few kilometers north of the mining town Selebi-Phikwe.", "The Letsibogo Dam offers recreational activities."],
    ["A haven for birdwatchers.", "One of the best places to fish for the African tigerfish."],
    ["The residents are traditionally cattle herders.", "The Boteti River flows after heavy rains."],
    ["An important touchstone for farmers in the wider region.", "Has a primary health care clinic."],
    ["The nearby Nata Bird Sanctuary is home to thousands of flamingos.", "The town thrives on transient tourism."],
    ["The village is picturesquely situated by the Tswapong Hills.", "Agriculture and cattle rearing are the livelihood."],
    ["Situated in the east near the South African border.", "A quiet location with a strong focus on farming."],
    ["The region is rich in local tribal history.", "The Tswapong Hills offer a stunning scenic backdrop."],
    ["A local hub structured after the Shashe River.", "Located along the main route to Maun."],
    ["Located in a junction zone providing access to northern tourist regions.", "Traditional homes are still widespread in the area."],
    ["An important center for cattle rearing in the area.", "The climate is semi-arid and very hot in the summer."],
    ["A key hub for supplying remote delta communities.", "Often only accessible using 4x4 vehicles."],
    ["A major border post with Namibia (Mamuno).", "Caters to growing cross-border trucking traffic."],
    ["The town is an oasis on the long Trans-Kalahari Highway.", "Offers essential filling stations and resting spots."],
    ["Frequently passed by travelers heading to the Kgalagadi Transfrontier Park.", "Surrounded by vast salt pans."],
    ["Offers connecting roads to the mining areas in Selebi-Phikwe.", "The population has grown in the last decade."],
    ["Local cattle auctions are regularly held here.", "One of the most enduring rural settlements in the district."],
    ["A political and administrative center for the Rolong people.", "Considered to be the granary of the south."],
    ["Has a desert climate with sparse rainfall.", "Many Bushmen communities live on the town outskirts."],
    ["The nearby Mannyelanong Hill protects a colony of Cape Vultures.", "A popular destination for hikers as well."],
    ["Has a station on the main railway line.", "Trade and livestock farming support the local economy."],
    ["A busy customs post for entry and exit.", "A major trade gateway into South Africa."],
    ["Originally a small suburb, today a growing town.", "Benefitted massively from its proximity to Francistown."],
    ["Many Kalanga-speaking residents live here.", "It is the administrative headquarters of the North-East District."],
    ["Has strong ties with the neighboring rural communities.", "Cattle farming remains the most important industry."],
    ["Thousands of Makgadikgadi baobab trees are found nearby.", "A stop for expeditions to the Nxai Pans."],
    ["The Odi Weavers cooperative is an institution since the 1970s.", "The town offers picturesque views of surrounding hills."],
    ["The Bokaa Dam often attracts many birdwatchers.", "A fast-growing rural settlement."],
    ["Forms a continuous settlement line with Mochudi.", "Residents often commute to work in the capital city."]
]

output_path = "lib/visualLab/data/poiExtraBotswanaCitiesV2.ts"

content = []
content.append('import type { POI } from "./poi";')
content.append('')
content.append('export const poiExtraBotswanaCitiesV2: POI[] = [')

for i, city in enumerate(cities):
    id_name, ptype, parent, lon, lat, eng_name, eng_desc = city
    poi_id = f"{id_name.replace('_', '-')}-cities-v2"
    
    de_desc = descriptions_de[i]
    hu_desc = descriptions_hu[i]
    ro_desc = descriptions_ro[i]
    en_desc = descriptions_en[i]
    
    de_fact = facts_de[i]
    hu_fact = facts_hu[i]
    ro_fact = facts_ro[i]
    en_fact = facts_en[i]
    
    name_obj = {
        "de": eng_name,
        "hu": eng_name,
        "ro": eng_name,
        "en": eng_name
    }
    
    comma = "," if i < len(cities) - 1 else ""
    
    poi_str = f"""  {{
    id: "{poi_id}",
    type: "{ptype}",
    parent: "{parent}",
    coords: [{lon}, {lat}],
    name: {json.dumps(name_obj, ensure_ascii=False)},
    description: {{
      de: {json.dumps(de_desc, ensure_ascii=False)},
      hu: {json.dumps(hu_desc, ensure_ascii=False)},
      ro: {json.dumps(ro_desc, ensure_ascii=False)},
      en: {json.dumps(en_desc, ensure_ascii=False)}
    }},
    facts: {{
      de: {json.dumps(de_fact, ensure_ascii=False)},
      hu: {json.dumps(hu_fact, ensure_ascii=False)},
      ro: {json.dumps(ro_fact, ensure_ascii=False)},
      en: {json.dumps(en_fact, ensure_ascii=False)}
    }}
  }}{comma}"""
    content.append(poi_str)

content.append('];')
content.append('')

with open(output_path, "w", encoding="utf-8") as f:
    f.write("\\n".join(content))

print(f"Generated {len(cities)} POIs.")
print(f"File size: {os.path.getsize(output_path)} bytes.")
