import json

data = {}

def add_poi(poi_id, faqs):
    data[poi_id] = {"faq": faqs}

# Block 1: 1-10
add_poi("city-dinant", [
    {"question": {"en": "What is Dinant famous for?", "de": "Wofür ist Dinant bekannt?", "hu": "Miről híres Dinant?", "ro": "Pentru ce este faimos Dinant?"}, "answer": {"en": "Dinant is famous for its Citadel, the Collegiate Church of Notre Dame, and as the birthplace of Adolphe Sax, the inventor of the saxophone.", "de": "Dinant ist bekannt für seine Zitadelle, die Stiftskirche Notre Dame und als Geburtsort von Adolphe Sax, dem Erfinder des Saxophons.", "hu": "Dinant híres a citadellájáról, a Notre Dame-társszékesegyházról és Adolphe Sax, a szaxofon feltalálójának szülőhelyeként.", "ro": "Dinant este faimos pentru Cetatea sa, Biserica Colegiată Notre Dame și ca loc de naștere al lui Adolphe Sax, inventatorul saxofonului."}},
    {"question": {"en": "Where is Dinant located?", "de": "Wo liegt Dinant?", "hu": "Hol található Dinant?", "ro": "Unde se află Dinant?"}, "answer": {"en": "It is located in the province of Namur, along the Meuse river.", "de": "Es liegt in der Provinz Namur, an der Maas.", "hu": "Namur tartományban található, a Maas-folyó mentén.", "ro": "Este situat în provincia Namur, de-a lungul râului Meuse."}},
    {"question": {"en": "What can you do at the Citadel of Dinant?", "de": "Was kann man in der Zitadelle von Dinant machen?", "hu": "Mit lehet csinálni a dinanti citadellában?", "ro": "Ce poți face la Cetatea din Dinant?"}, "answer": {"en": "You can visit the history museum and enjoy a panoramic view of the city.", "de": "Sie können das Geschichtsmuseum besuchen und einen Panoramablick auf die Stadt genießen.", "hu": "Meglátogathatja a történelmi múzeumot, és élvezheti a városra nyíló panorámát.", "ro": "Puteți vizita muzeul de istorie și vă puteți bucura de o vedere panoramică a orașului."}},
    {"question": {"en": "Who invented the saxophone in Dinant?", "de": "Wer erfand das Saxophon in Dinant?", "hu": "Ki találta fel a szaxofont Dinantban?", "ro": "Cine a inventat saxofonul în Dinant?"}, "answer": {"en": "Adolphe Sax invented the saxophone in the 1840s.", "de": "Adolphe Sax erfand das Saxophon in den 1840er Jahren.", "hu": "Adolphe Sax találta fel a szaxofont az 1840-es években.", "ro": "Adolphe Sax a inventat saxofonul în anii 1840."}}
])

add_poi("city-huy", [
    {"question": {"en": "What is the main attraction in Huy?", "de": "Was ist die Hauptattraktion in Huy?", "hu": "Mi Huy fő látványossága?", "ro": "Care este principala atracție din Huy?"}, "answer": {"en": "The main attraction is the Fort of Huy, a former citadel overlooking the Meuse river.", "de": "Die Hauptattraktion ist das Fort von Huy, eine ehemalige Zitadelle mit Blick auf die Maas.", "hu": "A fő látványosság a Huy-i erőd, egy korábbi citadella, amely a Maas-folyóra néz.", "ro": "Principala atracție este Fortul Huy, o fostă cetate care domină râul Meuse."}},
    {"question": {"en": "What is the 'Mur de Huy'?", "de": "Was ist die 'Mur de Huy'?", "hu": "Mi az a 'Mur de Huy'?", "ro": "Ce este 'Mur de Huy'?"}, "answer": {"en": "It is a famous steep climb in the city, well-known from the Flèche Wallonne cycling race.", "de": "Es ist ein berühmter steiler Anstieg in der Stadt, bekannt durch das Radrennen Flèche Wallonne.", "hu": "Ez egy híres meredek emelkedő a városban, amely a Flèche Wallonne kerékpárversenyről ismert.", "ro": "Este o faimoasă urcare abruptă din oraș, bine cunoscută de la cursa de ciclism Flèche Wallonne."}},
    {"question": {"en": "Which river flows through Huy?", "de": "Welcher Fluss fließt durch Huy?", "hu": "Melyik folyó folyik át Huy-n?", "ro": "Ce râu curge prin Huy?"}, "answer": {"en": "The Meuse river flows through the heart of Huy.", "de": "Die Maas fließt durch das Herz von Huy.", "hu": "A Maas-folyó folyik át Huy szívén.", "ro": "Râul Meuse curge prin inima orașului Huy."}},
    {"question": {"en": "Is there a cathedral in Huy?", "de": "Gibt es eine Kathedrale in Huy?", "hu": "Van katedrális Huy-ban?", "ro": "Există o catedrală în Huy?"}, "answer": {"en": "Yes, the Collegiate Church of Notre-Dame is a major Gothic landmark in the city.", "de": "Ja, die Stiftskirche Notre-Dame ist ein bedeutendes gotisches Wahrzeichen der Stadt.", "hu": "Igen, a Notre-Dame-társszékesegyház a város egyik jelentős gótikus emléke.", "ro": "Da, Biserica Colegiată Notre-Dame este un punct de reper gotic major din oraș."}}
])

add_poi("city-rochefort", [
    {"question": {"en": "What is Rochefort famous for?", "de": "Wofür ist Rochefort bekannt?", "hu": "Miről híres Rochefort?", "ro": "Pentru ce este faimos Rochefort?"}, "answer": {"en": "Rochefort is famous for its Trappist brewery and the caves of Lorette.", "de": "Rochefort ist bekannt für seine Trappistenbrauerei und die Höhlen von Lorette.", "hu": "Rochefort híres a trappista sörfőzdéjéről és a Lorette-barlangokról.", "ro": "Rochefort este faimos pentru berăria sa trapistă și peșterile din Lorette."}},
    {"question": {"en": "What can you visit in Rochefort?", "de": "Was kann man in Rochefort besuchen?", "hu": "Mit lehet meglátogatni Rochefortban?", "ro": "Ce poți vizita în Rochefort?"}, "answer": {"en": "You can visit the ruins of the Counts' Castle and the Caves of Rochefort.", "de": "Sie können die Ruinen der Grafenburg und die Grotten von Rochefort besuchen.", "hu": "Meglátogathatja a Grófi vár romjait és a Rochefort-i barlangokat.", "ro": "Puteți vizita ruinele Castelului Conților și Peșterile din Rochefort."}},
    {"question": {"en": "Is there a Trappist monastery in Rochefort?", "de": "Gibt es ein Trappistenkloster in Rochefort?", "hu": "Van trappista kolostor Rochefortban?", "ro": "Există o mănăstire trapistă în Rochefort?"}, "answer": {"en": "Yes, Saint-Remy Abbey is home to a community of Trappist monks.", "de": "Ja, die Abtei Saint-Remy beherbergt eine Gemeinschaft von Trappistenmönchen.", "hu": "Igen, a Saint-Remy apátság trappista szerzetesek közösségének ad otthont.", "ro": "Da, Abația Saint-Remy găzduiește o comunitate de călugări trapiști."}},
    {"question": {"en": "What type of cheese is Rochefort known for?", "de": "Für welche Käsesorte ist Rochefort bekannt?", "hu": "Milyen sajtról ismert Rochefort?", "ro": "Ce tip de brânză este cunoscut sub numele de Rochefort?"}, "answer": {"en": "Rochefort is known for its Rochefort cheese, often produced by the abbey.", "de": "Rochefort ist bekannt für seinen Rochefort-Käse, der oft von der Abtei hergestellt wird.", "hu": "Rochefort a Rochefort sajtról ismert, amelyet gyakran az apátság készít.", "ro": "Rochefort este cunoscut pentru brânza sa Rochefort, produsă adesea de abație."}}
])

add_poi("city-damme", [
    {"question": {"en": "What is Damme known for?", "de": "Wofür ist Damme bekannt?", "hu": "Miről nevezetes Damme?", "ro": "Pentru ce este cunoscut Damme?"}, "answer": {"en": "Damme is known as a picturesque 'book town' near Bruges, famous for its medieval architecture.", "de": "Damme ist bekannt als malerische 'Bücherstadt' bei Brügge, berühmt für seine mittelalterliche Architektur.", "hu": "Damme egy festői 'könyvvárosként' ismert Brugge közelében, amely középkori építészetéről híres.", "ro": "Damme este cunoscut ca un 'oraș al cărților' pitoresc lângă Bruges, renumit pentru arhitectura sa medievală."}},
    {"question": {"en": "Who is the famous literary figure associated with Damme?", "de": "Welche berühmte literarische Figur wird mit Damme in Verbindung gebracht?", "hu": "Melyik híres irodalmi alak kapcsolódik Damme-hoz?", "ro": "Care este faimoasa figură literară asociată cu Damme?"}, "answer": {"en": "Tijl Uilenspiegel is a legendary figure closely associated with the town of Damme.", "de": "Tijl Uilenspiegel ist eine legendäre Figur, die eng mit der Stadt Damme verbunden ist.", "hu": "Tijl Uilenspiegel egy legendás alak, aki szorosan kapcsolódik Damme városához.", "ro": "Tijl Uilenspiegel este o figură legendară strâns asociată cu orașul Damme."}},
    {"question": {"en": "How can you get to Damme from Bruges?", "de": "Wie kommt man von Brügge nach Damme?", "hu": "Hogyan juthatunk el Damme-ba Brugge-ből?", "ro": "Cum poți ajunge la Damme din Bruges?"}, "answer": {"en": "You can take a scenic boat trip along the Damme Canal (Damse Vaart).", "de": "Sie können eine malerische Bootsfahrt auf dem Damme-Kanal (Damse Vaart) unternehmen.", "hu": "Festői hajókirándulást tehet a Damme-csatornán (Damse Vaart).", "ro": "Puteți face o plimbare pitorească cu barca de-a lungul Canalului Damme (Damse Vaart)."}},
    {"question": {"en": "What is the main church in Damme?", "de": "Was ist die Hauptkirche in Damme?", "hu": "Melyik Damme főtemploma?", "ro": "Care este biserica principală din Damme?"}, "answer": {"en": "The Church of Our Lady (Onze-Lieve-Vrouw-Hemelvaartkerk) with its flat tower is the main church.", "de": "Die Frauenkirche (Onze-Lieve-Vrouw-Hemelvaartkerk) mit ihrem flachen Turm ist die Hauptkirche.", "hu": "A Miasszonyunk-templom (Onze-Lieve-Vrouw-Hemelvaartkerk) a lapos tornyával a főtemplom.", "ro": "Biserica Maicii Domnului (Onze-Lieve-Vrouw-Hemelvaartkerk) cu turnul său plat este biserica principală."}}
])

add_poi("city-aalst", [
    {"question": {"en": "What is Aalst most famous for?", "de": "Wofür ist Aalst am bekanntesten?", "hu": "Miről a leghíresebb Aalst?", "ro": "Pentru ce este cel mai faimos Aalst?"}, "answer": {"en": "Aalst is most famous for its annual Carnival, which is recognized by UNESCO.", "de": "Aalst ist am bekanntesten für seinen jährlichen Karneval, der von der UNESCO anerkannt ist.", "hu": "Aalst a leghíresebb az éves karneváljáról, amelyet az UNESCO is elismert.", "ro": "Aalst este cel mai faimos pentru Carnavalul său anual, care este recunoscut de UNESCO."}},
    {"question": {"en": "Where is Aalst located?", "de": "Wo liegt Aalst?", "hu": "Hol található Aalst?", "ro": "Unde se află Aalst?"}, "answer": {"en": "Aalst is located in the province of East Flanders, on the river Dender.", "de": "Aalst liegt in der Provinz Ostflandern, am Fluss Dender.", "hu": "Aalst Kelet-Flandria tartományban található, a Dender-folyó mentén.", "ro": "Aalst este situat în provincia Flandra de Est, pe râul Dender."}},
    {"question": {"en": "What is a major landmark in the Grote Markt of Aalst?", "de": "Was ist ein wichtiges Wahrzeichen am Grote Markt von Aalst?", "hu": "Mi az egyik fő látnivaló Aalst főterén (Grote Markt)?", "ro": "Care este un punct de reper major în Grote Markt din Aalst?"}, "answer": {"en": "The Belfry of Aalst, which is part of the UNESCO World Heritage list.", "de": "Der Belfried von Aalst, der zum UNESCO-Welterbe gehört.", "hu": "Az aalsti harangtorony (Belfry), amely az UNESCO Világörökség része.", "ro": "Beffroi-ul din Aalst, care face parte din lista Patrimoniului Mondial UNESCO."}},
    {"question": {"en": "Who was Dirk Martens?", "de": "Wer war Dirk Martens?", "hu": "Ki volt Dirk Martens?", "ro": "Cine a fost Dirk Martens?"}, "answer": {"en": "Dirk Martens was a native of Aalst who introduced printing to the Southern Netherlands.", "de": "Dirk Martens war ein aus Aalst stammender Drucker, der die Buchdruckerkunst in den südlichen Niederlanden einführte.", "hu": "Dirk Martens aalsti születésű volt, aki bevezette a könyvnyomtatást a Dél-Németalföldön.", "ro": "Dirk Martens a fost un originar din Aalst care a introdus tiparul în Țările de Jos de Sud."}}
])

add_poi("city-oudenaarde", [
    {"question": {"en": "What is Oudenaarde famous for historically?", "de": "Wofür ist Oudenaarde historisch bekannt?", "hu": "Miről nevezetes történelmileg Oudenaarde?", "ro": "Pentru ce este faimos istoric Oudenaarde?"}, "answer": {"en": "Oudenaarde is famous for its tapestry production and the Battle of Oudenaarde in 1708.", "de": "Oudenaarde ist bekannt für seine Tapisserieherstellung und die Schlacht von Oudenaarde im Jahr 1708.", "hu": "Oudenaarde híres faliszőnyeg-gyártásáról és az 1708-as oudenaarde-i csatáról.", "ro": "Oudenaarde este faimos pentru producția de tapiserie și Bătălia de la Oudenaarde din 1708."}},
    {"question": {"en": "What is the architectural style of Oudenaarde Town Hall?", "de": "Welchen Architekturstil hat das Rathaus von Oudenaarde?", "hu": "Milyen építészeti stílusú az oudenaarde-i városháza?", "ro": "Care este stilul arhitectural al primăriei din Oudenaarde?"}, "answer": {"en": "The Town Hall is a masterpiece of the Brabantine Gothic style.", "de": "Das Rathaus ist ein Meisterwerk des brabantischen Gotikstils.", "hu": "A városháza a brabanti gótikus stílus remekműve.", "ro": "Primăria este o capodoperă a stilului gotic brabantin."}},
    {"question": {"en": "Which major cycling race is associated with Oudenaarde?", "de": "Welches große Radrennen wird mit Oudenaarde in Verbindung gebracht?", "hu": "Melyik jelentős kerékpárverseny kapcsolódik Oudenaarde-hoz?", "ro": "Ce cursă majoră de ciclism este asociată cu Oudenaarde?"}, "answer": {"en": "Oudenaarde is the finishing point of the Tour of Flanders (Ronde van Vlaanderen).", "de": "Oudenaarde ist der Zielort der Flandern-Rundfahrt (Ronde van Vlaanderen).", "hu": "Oudenaarde a Flandriai körverseny (Ronde van Vlaanderen) célállomása.", "ro": "Oudenaarde este punctul de sosire al Turului Flandrei (Ronde van Vlaanderen)."}},
    {"question": {"en": "Where can you see tapestries in Oudenaarde?", "de": "Wo kann man in Oudenaarde Tapisserien sehen?", "hu": "Hol láthatók faliszőnyegek Oudenaarde-ban?", "ro": "Unde poți vedea tapiserii în Oudenaarde?"}, "answer": {"en": "The MOU Museum in the Town Hall houses an impressive collection of tapestries.", "de": "Das MOU-Museum im Rathaus beherbergt eine beeindruckende Sammlung von Tapisserien.", "hu": "A városházán található MOU Múzeum lenyűgöző faliszőnyeg-gyűjteménynek ad otthont.", "ro": "Muzeul MOU din Primărie găzduiește o colecție impresionantă de tapiserii."}}
])

add_poi("city-roeselare", [
    {"question": {"en": "What is Roeselare known for in terms of industry?", "de": "Wofür ist Roeselare industriell bekannt?", "hu": "Miről ismert Roeselare az ipar szempontjából?", "ro": "Pentru ce este cunoscut Roeselare în ceea ce privește industria?"}, "answer": {"en": "Roeselare is known as a commercial center and for its food processing industry.", "de": "Roeselare ist bekannt als Handelszentrum und für seine Lebensmittelindustrie.", "hu": "Roeselare kereskedelmi központként és élelmiszeriparáról ismert.", "ro": "Roeselare este cunoscut ca un centru comercial și pentru industria sa de procesare a alimentelor."}},
    {"question": {"en": "Which famous brewery is located near Roeselare?", "de": "Welche berühmte Brauerei befindet sich in der Nähe von Roeselare?", "hu": "Melyik híres sörfőzde található Roeselare közelében?", "ro": "Ce berărie celebră se află lângă Roeselare?"}, "answer": {"en": "The Rodenbach Brewery, famous for its Flemish red ale, is located in Roeselare.", "de": "Die Brauerei Rodenbach, bekannt für ihr flämisches Rotbier, befindet sich in Roeselare.", "hu": "A Rodenbach sörfőzde, amely híres flamand vörös söréről, Roeselare-ban található.", "ro": "Berăria Rodenbach, faimoasă pentru berea sa roșie flamandă, este situată în Roeselare."}},
    {"question": {"en": "What is the 'KOERS' museum in Roeselare?", "de": "Was ist das 'KOERS'-Museum in Roeselare?", "hu": "Mi az a 'KOERS' múzeum Roeselare-ban?", "ro": "Ce este muzeul 'KOERS' din Roeselare?"}, "answer": {"en": "KOERS is the Museum of Cycle Racing, showcasing the history of cycling.", "de": "KOERS ist das Museum für den Radrennsport, das die Geschichte des Radsports zeigt.", "hu": "A KOERS a Kerékpárversenyek Múzeuma, amely a kerékpározás történetét mutatja be.", "ro": "KOERS este Muzeul Curselor de Ciclism, care prezintă istoria ciclismului."}},
    {"question": {"en": "Where is Roeselare located?", "de": "Wo liegt Roeselare?", "hu": "Hol található Roeselare?", "ro": "Unde se află Roeselare?"}, "answer": {"en": "Roeselare is located in the province of West Flanders.", "de": "Roeselare liegt in der Provinz Westflandern.", "hu": "Roeselare Nyugat-Flandria tartományban található.", "ro": "Roeselare este situat în provincia Flandra de Vest."}}
])

add_poi("city-turnhout", [
    {"question": {"en": "What is Turnhout famous for producing?", "de": "Wofür ist Turnhout als Produktionsstandort bekannt?", "hu": "Milyen termék gyártásáról híres Turnhout?", "ro": "Ce este faimos Turnhout pentru producție?"}, "answer": {"en": "Turnhout is known as the world center for the production of playing cards.", "de": "Turnhout ist als Weltzentrum für die Herstellung von Spielkarten bekannt.", "hu": "Turnhout a játékkártya-gyártás világközpontjaként ismert.", "ro": "Turnhout este cunoscut ca centrul mondial pentru producția de cărți de joc."}},
    {"question": {"en": "Where is the Playing Card Museum located?", "de": "Wo befindet sich das Spielkartenmuseum?", "hu": "Hol található a Játékkártya Múzeum?", "ro": "Unde se află Muzeul Cărților de Joc?"}, "answer": {"en": "The National Museum of the Playing Card is located in Turnhout.", "de": "Das Nationale Spielkartenmuseum befindet sich in Turnhout.", "hu": "A Nemzeti Játékkártya Múzeum Turnhoutban található.", "ro": "Muzeul Național al Cărților de Joc este situat în Turnhout."}},
    {"question": {"en": "What historical building can you visit in Turnhout?", "de": "Welches historische Gebäude kann man in Turnhout besuchen?", "hu": "Milyen történelmi épület látogatható Turnhoutban?", "ro": "Ce clădire istorică poți vizita în Turnhout?"}, "answer": {"en": "The Castle of the Dukes of Brabant is a major historical landmark in Turnhout.", "de": "Das Schloss der Herzöge von Brabant ist ein wichtiges historisches Wahrzeichen in Turnhout.", "hu": "A Brabanti hercegek kastélya Turnhout egyik fő történelmi emléke.", "ro": "Castelul Ducilor de Brabant este un punct de reper istoric major în Turnhout."}},
    {"question": {"en": "What is the Beguinage of Turnhout?", "de": "Was ist der Begijnhof von Turnhout?", "hu": "Mi az a turnhouti beginázs?", "ro": "Ce este Beguinajul din Turnhout?"}, "answer": {"en": "It is a UNESCO-listed beguinage, a tranquil historic complex.", "de": "Es ist ein UNESCO-gelisteter Begijnhof, ein ruhiger historischer Komplex.", "hu": "Ez egy UNESCO-listás beginázs, egy nyugodt történelmi épületegyüttes.", "ro": "Este un beguinaj inclus în lista UNESCO, un complex istoric liniștit."}}
])

add_poi("city-hasselt", [
    {"question": {"en": "What is Hasselt famous for?", "de": "Wofür ist Hasselt bekannt?", "hu": "Miről híres Hasselt?", "ro": "Pentru ce este faimos Hasselt?"}, "answer": {"en": "Hasselt is famous for its Jenever production and the Japanese Garden.", "de": "Hasselt ist bekannt für seine Jenever-Produktion und den Japanischen Garten.", "hu": "Hasselt a Jenever-gyártásról és a Japánkertről híres.", "ro": "Hasselt este faimos pentru producția sa de Jenever și Grădina Japoneză."}},
    {"question": {"en": "What is the Japanese Garden in Hasselt?", "de": "Was ist der Japanische Garten in Hasselt?", "hu": "Mi az a hasselti Japánkert?", "ro": "Ce este Grădina Japoneză din Hasselt?"}, "answer": {"en": "It is the largest Japanese garden in Europe, symbolizing the friendship between Hasselt and Itami.", "de": "Es ist der größte japanische Garten in Europa und symbolisiert die Freundschaft zwischen Hasselt und Itami.", "hu": "Ez Európa legnagyobb japánkertje, amely a Hasselt és Itami közötti barátságot jelképezi.", "ro": "Este cea mai mare grădină japoneză din Europa, simbolizând prietenia dintre Hasselt și Itami."}},
    {"question": {"en": "What can you learn at the Jenever Museum?", "de": "Was kann man im Jenever-Museum lernen?", "hu": "Mit tudhatunk meg a Jenever Múzeumban?", "ro": "Ce poți învăța la Muzeul Jenever?"}, "answer": {"en": "You can learn about the history and production process of Jenever, a traditional gin-like spirit.", "de": "Sie können etwas über die Geschichte und den Herstellungsprozess von Jenever erfahren, einer traditionellen, gin-ähnlichen Spirituose.", "hu": "Megismerheti a Jenever, egy hagyományos, gin-szerű szeszes ital történetét és gyártási folyamatát.", "ro": "Puteți afla despre istoria și procesul de producție al Jenever, un spirit tradițional asemănător ginului."}},
    {"question": {"en": "Is Hasselt a shopping destination?", "de": "Ist Hasselt ein Ziel zum Einkaufen?", "hu": "Hasselt vásárlási célpont?", "ro": "Este Hasselt o destinație de cumpărături?"}, "answer": {"en": "Yes, Hasselt is known as a major fashion and shopping city in Belgium.", "de": "Ja, Hasselt ist als bedeutende Mode- und Einkaufsstadt in Belgien bekannt.", "hu": "Igen, Hasselt jelentős divat- és bevásárlóvárosként ismert Belgiumban.", "ro": "Da, Hasselt este cunoscut ca un oraș major de modă și cumpărături din Belgia."}}
])

add_poi("city-tongeren", [
    {"question": {"en": "What is the historical significance of Tongeren?", "de": "Was ist die historische Bedeutung von Tongeren?", "hu": "Mi Tongeren történelmi jelentősége?", "ro": "Care este semnificația istorică a orașului Tongeren?"}, "answer": {"en": "Tongeren is the oldest town in Belgium, founded by the Romans.", "de": "Tongeren ist die älteste Stadt Belgiens, die von den Römern gegründet wurde.", "hu": "Tongeren Belgium legrégebbi városa, amelyet a rómaiak alapítottak.", "ro": "Tongeren este cel mai vechi oraș din Belgia, fondat de romani."}},
    {"question": {"en": "Who is Ambiorix?", "de": "Wer ist Ambiorix?", "hu": "Ki az az Ambiorix?", "ro": "Cine este Ambiorix?"}, "answer": {"en": "Ambiorix was a leader of the Eburones who defeated Caesar's legions; a statue of him stands in Tongeren.", "de": "Ambiorix war ein Anführer der Eburonen, der Cäsars Legionen besiegte; in Tongeren steht eine Statue von ihm.", "hu": "Ambiorix az eburonok vezére volt, aki legyőzte Caesar légióit; szobra Tongerenben áll.", "ro": "Ambiorix a fost un lider al eburonilor care a învins legiunile lui Cezar; o statuie a sa se află în Tongeren."}},
    {"question": {"en": "What museum showcases the Roman past of Tongeren?", "de": "Welches Museum zeigt die römische Vergangenheit von Tongeren?", "hu": "Melyik múzeum mutatja be Tongeren római múltját?", "ro": "Ce muzeu prezintă trecutul roman al orașului Tongeren?"}, "answer": {"en": "The Gallo-Roman Museum houses artifacts from the Roman and prehistoric periods.", "de": "Das Gallo-Römische Museum beherbergt Artefakte aus der römischen und prähistorischen Zeit.", "hu": "A Gallo-Római Múzeum római és őskori leleteket őriz.", "ro": "Muzeul Gallo-Roman găzduiește artefacte din perioadele romană și preistorică."}},
    {"question": {"en": "What famous market takes place in Tongeren every Sunday?", "de": "Welcher berühmte Markt findet jeden Sonntag in Tongeren statt?", "hu": "Milyen híres vásárt tartanak Tongerenben minden vasárnap?", "ro": "Ce piață celebră are loc în Tongeren în fiecare duminică?"}, "answer": {"en": "The Tongeren Antique Market is the largest of its kind in the Benelux.", "de": "Der Antiquitätenmarkt von Tongeren ist der größte seiner Art in den Benelux-Ländern.", "hu": "A tongereni antikpiac a legnagyobb a maga nemében a Benelux-államokban.", "ro": "Piața de antichități din Tongeren este cea mai mare de acest gen din Benelux."}}
])

with open('bel_faq_2_part1.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
