import json

cities = [
    ("lima", "city", "PE-LMA", -77.0428, -12.0464, "Lima", "Die Hauptstadt und größte Stadt Perus.", "Peru fővárosa és legnagyobb városa.", "Capitala și cel mai mare oraș din Peru.", "The capital and largest city of Peru.", "Gegründet 1535 von Francisco Pizarro.", "Francisco Pizarro alapította 1535-ben.", "Fondat în 1535 de Francisco Pizarro.", "Founded in 1535 by Francisco Pizarro.", "Über 9 Millionen Einwohner.", "Több mint 9 millió lakosa van.", "Are peste 9 milioane de locuitori.", "Has over 9 million inhabitants."),
    ("arequipa", "city", "PE-ARE", -71.5369, -16.4090, "Arequipa", "Bekannt als die 'Weiße Stadt'.", "A 'Fehér Város' néven ismert.", "Cunoscut ca 'Orașul Alb'.", "Known as the 'White City'.", "Umgeben von Vulkanen wie dem Misti.", "Olyan vulkánok veszik körül, mint a Misti.", "Înconjurat de vulcani precum Misti.", "Surrounded by volcanoes like El Misti.", "Zweitgrößte Stadt in Peru.", "Peru második legnagyobb városa.", "Al doilea cel mai mare oraș din Peru.", "Second largest city in Peru."),
    ("trujillo", "city", "PE-LAL", -79.0299, -8.1159, "Trujillo", "Zentrum der Chimú-Kultur in Nordperu.", "A Chimú kultúra központja Észak-Peruban.", "Centrul culturii Chimú din nordul statului Peru.", "Center of the Chimú culture in northern Peru.", "Die Ruinen von Chan Chan liegen nahe.", "Chan Chan romjai a közelben találhatók.", "Ruinele de la Chan Chan sunt aproape.", "The ruins of Chan Chan are nearby.", "Bekannt für den Frühlingsfest.", "Híres a tavaszi fesztiváljáról.", "Cunoscut pentru festivalul primăverii.", "Known for its spring festival."),
    ("chiclayo", "city", "PE-LAM", -79.8390, -6.7713, "Chiclayo", "Hauptstadt der Region Lambayeque.", "Lambayeque régió fővárosa.", "Capitala regiunii Lambayeque.", "Capital of the Lambayeque region.", "Nahe dem Grab des Herrn von Sipán.", "Sipán urának sírja közelében.", "Aproape de mormântul Domnului de Sipán.", "Near the tomb of the Lord of Sipán.", "Wichtiger Handelsknotenpunkt.", "Fontos kereskedelmi csomópont.", "Un important nod comercial.", "An important commercial hub."),
    ("piura", "city", "PE-PIU", -80.6328, -5.1944, "Piura", "Eine der ältesten spanischen Städte Südamerikas.", "Dél-Amerika egyik legrégebbi spanyol városa.", "Unul dintre cele mai vechi orașe spaniole din America de Sud.", "One of the oldest Spanish cities in South America.", "Bekannt für warmes Klima und Strände.", "Meleg éghajlatáról és strandjairól ismert.", "Cunoscut pentru clima caldă și plaje.", "Known for warm climate and beaches.", "Wichtige landwirtschaftliche Region.", "Fontos mezőgazdasági régió.", "O regiune agricolă importantă.", "Important agricultural region."),
    ("iquitos", "city", "PE-LOR", -73.2538, -3.7491, "Iquitos", "Die größte Stadt im peruanischen Amazonasgebiet.", "A perui Amazonas legnagyobb városa.", "Cel mai mare oraș din Amazonia peruană.", "The largest city in the Peruvian Amazon.", "Nur per Boot oder Flugzeug erreichbar.", "Csak hajóval vagy repülővel közelíthető meg.", "Accesibil doar cu barca sau avionul.", "Accessible only by boat or airplane.", "Wichtiges Zentrum für Ökotourismus.", "Az ökoturizmus fontos központja.", "Un centru important pentru ecoturism.", "Important ecotourism center."),
    ("cusco", "state-capital", "PE-CUS", -71.9674, -13.5226, "Cusco", "Ehemalige Hauptstadt des Inkareiches.", "Az Inka Birodalom egykori fővárosa.", "Fosta capitală a Imperiului Inca.", "Former capital of the Inca Empire.", "UNESCO-Weltkulturerbe seit 1983.", "1983 óta UNESCO Világörökség.", "Patrimoniul Mondial UNESCO din 1983.", "UNESCO World Heritage site since 1983.", "Ausgangspunkt nach Machu Picchu.", "Kiindulópont Machu Picchu felé.", "Punct de plecare spre Machu Picchu.", "Starting point for Machu Picchu."),
    ("chimbote", "city", "PE-ANC", -78.5910, -9.0768, "Chimbote", "Wichtiger Fischereihafen in Peru.", "Fontos halászkikötő Peruban.", "Un important port de pescuit în Peru.", "Major fishing port in Peru.", "Hauptzentrum der peruanischen Stahlindustrie.", "A perui acélipar fő központja.", "Centrul principal al industriei siderurgice peruane.", "Main center of the Peruvian steel industry.", "Liegt in der Region Ancash.", "Ancash régióban található.", "Situat în regiunea Ancash.", "Located in the Ancash region."),
    ("huancayo", "state-capital", "PE-JUN", -75.2048, -12.0651, "Huancayo", "Kulturelles Zentrum im zentralen Hochland.", "Kulturális központ a központi hegyvidéken.", "Centru cultural în zona muntoasă centrală.", "Cultural center in the central highlands.", "Bekannt für den Sonntagsmarkt.", "Híres a vasárnapi piacáról.", "Cunoscut pentru piața de duminică.", "Known for its Sunday market.", "Liegt auf über 3.200 Metern Höhe.", "Több mint 3200 méter magasan fekszik.", "Situat la peste 3.200 de metri altitudine.", "Located over 3,200 meters above sea level."),
    ("tacna", "state-capital", "PE-TAC", -70.2527, -18.0146, "Tacna", "Grenzstadt zu Chile im Süden Perus.", "Határváros Chilével Peru déli részén.", "Oraș de graniță cu Chile în sudul statului Peru.", "Border city with Chile in southern Peru.", "Gilt als die 'Heldenstadt' Perus.", "Peru 'Hősvárosa' néven ismert.", "Cunoscut ca 'Orașul Erou' din Peru.", "Considered the 'Heroic City' of Peru.", "Wichtige Freihandelszone.", "Fontos szabadkereskedelmi övezet.", "O importantă zonă de liber schimb.", "Important free trade zone."),
    ("ica", "state-capital", "PE-ICA", -75.7277, -14.0677, "Ica", "Zentrum der peruanischen Weinproduktion.", "A perui bortermelés központja.", "Centrul producției de vin peruan.", "Center of Peruvian wine production.", "Die Oase Huacachina liegt in der Nähe.", "A Huacachina oázis a közelben található.", "Oaza Huacachina se află în apropiere.", "The Huacachina oasis is nearby.", "Berühmt für Pisco, ein Traubenschnaps.", "Híres a Pisco nevű szőlőpárlatról.", "Faimos pentru Pisco, un rachiu de struguri.", "Famous for Pisco, a grape brandy."),
    ("juliaca", "city", "PE-PUN", -70.1336, -15.4939, "Juliaca", "Handelszentrum in der Region Puno.", "Puno régió kereskedelmi központja.", "Centru comercial în regiunea Puno.", "Commercial center in the Puno region.", "Bekannt als 'Stadt der Winde'.", "A 'Szelek Városaként' is ismert.", "Cunoscut ca 'Orașul Vânturilor'.", "Known as the 'City of Winds'.", "Wichtiger Verkehrsknotenpunkt im Süden.", "Fontos közlekedési csomópont délen.", "Un important nod de transport în sud.", "Important transport hub in the south."),
    ("pucallpa", "state-capital", "PE-UCA", -74.5262, -8.3791, "Pucallpa", "Hauptstadt der Region Ucayali am Fluss Ucayali.", "Ucayali régió fővárosa az Ucayali folyó mentén.", "Capitala regiunii Ucayali pe râul Ucayali.", "Capital of the Ucayali region on the Ucayali River.", "Wichtiger Hafen im Amazonasgebiet.", "Fontos kikötő az Amazonas régióban.", "Port important în regiunea amazoniană.", "Important port in the Amazon region.", "Wirtschaftlich durch Holzeinschlag geprägt.", "Gazdaságát a fakitermelés határozza meg.", "Economia este dominată de exploatarea forestieră.", "Economy characterized by logging."),
    ("sullana", "city", "PE-PIU", -80.6852, -4.9038, "Sullana", "Stadt im Tal des Río Chira in Nordperu.", "Város a Chira folyó völgyében, Észak-Peruban.", "Oraș din valea râului Chira, în nordul statului Peru.", "City in the Chira River valley in northern Peru.", "Wichtiges Zentrum für Landwirtschaft.", "A mezőgazdaság fontos központja.", "Un centru important pentru agricultură.", "Important center for agriculture.", "Bekannt für sein warmes Klima.", "Meleg éghajlatáról ismert.", "Cunoscut pentru clima sa caldă.", "Known for its warm climate."),
    ("cajamarca", "state-capital", "PE-CAJ", -78.5135, -7.1637, "Cajamarca", "Historische Stadt im nördlichen Hochland Perus.", "Történelmi város Peru északi hegyvidékén.", "Oraș istoric din nordul muntos al statului Peru.", "Historical city in the northern highlands of Peru.", "Ort der Gefangennahme des Inkas Atahualpa.", "Atahualpa inka uralkodó elfogásának helyszíne.", "Locul unde a fost capturat incașul Atahualpa.", "Site of the capture of the Inca Atahualpa.", "Bekannt für Karneval und Milchprodukte.", "Híres a karneválról és a tejtermékekről.", "Cunoscut pentru carnaval și produse lactate.", "Known for carnival and dairy products."),
    ("chincha_alta", "city", "PE-ICA", -76.1309, -13.4098, "Chincha Alta", "Zentrum der afro-peruanischen Kultur.", "Az afro-perui kultúra központja.", "Centrul culturii afro-peruane.", "Center of Afro-Peruvian culture.", "Liegt in der Region Ica.", "Az Ica régióban található.", "Situat în regiunea Ica.", "Located in the Ica region.", "Bekannt für den traditionellen Cajón-Trommel.", "A hagyományos cajón dobról ismert.", "Cunoscut pentru toba tradițională cajón.", "Known for the traditional cajón drum."),
    ("ayacucho", "state-capital", "PE-AYA", -74.2235, -13.1587, "Ayacucho", "Bekannt für seine zahlreichen Kirchen.", "Számos templomáról ismert.", "Cunoscut pentru numeroasele sale biserici.", "Known for its numerous churches.", "Ort der entscheidenden Schlacht von Ayacucho 1824.", "Az 1824-es ayacuchói csata helyszíne.", "Locul bătăliei decisive de la Ayacucho din 1824.", "Site of the decisive Battle of Ayacucho in 1824.", "Zentrum des peruanischen Kunsthandwerks.", "A perui kézművesség központja.", "Centrul meșteșugurilor peruane.", "Center of Peruvian handicrafts."),
    ("huanuco", "state-capital", "PE-HUC", -76.2411, -9.9306, "Huánuco", "Liegt am Huallaga-Fluss im zentralen Hochland.", "A Huallaga folyó mentén található a központi hegyvidéken.", "Situat pe râul Huallaga în zonele muntoase centrale.", "Located on the Huallaga River in the central highlands.", "Gilt als Tor zum Amazonas.", "Az Amazonas kapujaként tartják számon.", "Considerat o poartă de acces către Amazon.", "Considered a gateway to the Amazon.", "Bekannt für den Tanz 'Los Negritos'.", "Híres a 'Los Negritos' táncról.", "Cunoscut pentru dansul 'Los Negritos'.", "Known for the 'Los Negritos' dance."),
    ("puno", "state-capital", "PE-PUN", -70.0267, -15.8402, "Puno", "Stadt am Ufer des Titicacasees.", "Város a Titicaca-tó partján.", "Oraș pe malul lacului Titicaca.", "City on the shores of Lake Titicaca.", "Folklore-Hauptstadt Perus.", "Peru folklór fővárosa.", "Capitala folclorică a statului Peru.", "Folklore capital of Peru.", "Ausgangspunkt zu den Uros-Inseln.", "Kiindulópont az Uros-szigetekhez.", "Punct de plecare către insulele Uros.", "Starting point to the Uros Islands."),
    ("tarapoto", "city", "PE-SAM", -76.3667, -6.4833, "Tarapoto", "Größte Stadt in der Region San Martín.", "San Martín régió legnagyobb városa.", "Cel mai mare oraș din regiunea San Martín.", "Largest city in the San Martín region.", "Wichtiges Tourismuszentrum für den Regenwald.", "Fontos turisztikai központ az esőerdőben.", "Centru turistic important pentru pădurea tropicală.", "Important tourism center for the rainforest.", "Bekannt für nahegelegene Wasserfälle.", "A közeli vízesésekről ismert.", "Cunoscut pentru cascadele din apropiere.", "Known for nearby waterfalls."),
    ("huaraz", "state-capital", "PE-ANC", -77.5287, -9.5290, "Huaraz", "Hauptstadt der Region Ancash.", "Ancash régió fővárosa.", "Capitala regiunii Ancash.", "Capital of the Ancash region.", "Zentrum für Alpinismus und Trekking.", "A hegymászás és túrázás központja.", "Centru pentru alpinism și trekking.", "Center for mountaineering and trekking.", "Liegt im Tal Callejón de Huaylas.", "A Callejón de Huaylas völgyben fekszik.", "Situat în valea Callejón de Huaylas.", "Located in the Callejón de Huaylas valley."),
    ("tumbes", "state-capital", "PE-TUM", -80.4515, -3.5669, "Tumbes", "Grenzstadt zu Ecuador im Norden Perus.", "Határváros Ecuadorral Peru északi részén.", "Oraș de graniță cu Ecuador în nordul statului Peru.", "Border city with Ecuador in northern Peru.", "Umgeben von Mangrovenwäldern.", "Mangroveerdők veszik körül.", "Înconjurat de păduri de mangrove.", "Surrounded by mangrove forests.", "Bekannt für Strände wie Punta Sal.", "Híres a strandjairól, mint Punta Sal.", "Cunoscut pentru plaje precum Punta Sal.", "Known for beaches like Punta Sal."),
    ("talara", "city", "PE-PIU", -81.2719, -4.5772, "Talara", "Wichtiges Zentrum der peruanischen Erdölindustrie.", "A perui olajipar fontos központja.", "Un important centru al industriei petroliere peruane.", "Important center of the Peruvian oil industry.", "Liegt an der Nordküste Perus.", "Peru északi partján található.", "Situat pe coasta de nord a statului Peru.", "Located on the northern coast of Peru.", "Bekannt für den Surfer-Strand Cabo Blanco.", "Híres a Cabo Blanco nevű szörfös strandról.", "Cunoscut pentru plaja de surf Cabo Blanco.", "Known for the Cabo Blanco surfer beach."),
    ("huaral", "city", "PE-LMA", -77.2081, -11.4936, "Huaral", "Stadt nördlich von Lima in einem fruchtbaren Tal.", "Limától északra fekvő város egy termékeny völgyben.", "Oraș situat la nord de Lima într-o vale fertilă.", "City north of Lima in a fertile valley.", "Bekannt für den Schweinebraten 'Chancho al Palo'.", "Híres a 'Chancho al Palo' nevű malacsültről.", "Cunoscut pentru friptura de porc 'Chancho al Palo'.", "Known for the 'Chancho al Palo' roast pork.", "Wichtige landwirtschaftliche Region.", "Fontos mezőgazdasági régió.", "O regiune agricolă importantă.", "Important agricultural region."),
    ("paita", "city", "PE-PIU", -81.1147, -5.0783, "Paita", "Wichtiger Seehafen in Nordperu.", "Fontos tengeri kikötő Észak-Peruban.", "Un important port maritim în nordul statului Peru.", "Major seaport in northern Peru.", "Historisch oft von Piraten angegriffen.", "A történelem során gyakran támadták kalózok.", "Din punct de vedere istoric, atacat adesea de pirați.", "Historically often attacked by pirates.", "Bekannt für traditionelle Ceviche.", "Híres a hagyományos ceviche-ről.", "Cunoscut pentru ceviche-ul tradițional.", "Known for traditional ceviche."),
    ("jaen", "city", "PE-CAJ", -78.8049, -5.7089, "Jaén", "Stadt in der nördlichen Region Cajamarca.", "Város az északi Cajamarca régióban.", "Oraș în regiunea nordică Cajamarca.", "City in the northern Cajamarca region.", "Wichtiges Zentrum für Kaffeeproduktion.", "A kávétermelés fontos központja.", "Un centru important pentru producția de cafea.", "Important center for coffee production.", "Tor zum peruanischen Amazonasgebiet.", "Kapu a perui Amazonas régióhoz.", "Poarta de acces către Amazonul peruan.", "Gateway to the Peruvian Amazon."),
    ("cerro_de_pasco", "state-capital", "PE-PAS", -76.2673, -10.6678, "Cerro de Pasco", "Eine der höchstgelegenen Städte der Welt.", "A világ egyik legmagasabban fekvő városa.", "Unul dintre orașele aflate la cea mai mare altitudine din lume.", "One of the highest cities in the world.", "Liegt auf 4.330 Metern über dem Meeresspiegel.", "4330 méterrel a tengerszint felett található.", "Situat la 4.330 de metri deasupra nivelului mării.", "Located 4,330 meters above sea level.", "Zentrum des Bergbaus in Peru.", "A perui bányászat központja.", "Centrul mineritului din Peru.", "Center of mining in Peru."),
    ("ilo", "city", "PE-MOQ", -71.3375, -17.6394, "Ilo", "Küstenstadt in der Region Moquegua.", "Tengerparti város a Moquegua régióban.", "Oraș de coastă în regiunea Moquegua.", "Coastal city in the Moquegua region.", "Wichtiger Hafen und Kupferhütte.", "Fontos kikötő és rézkohó.", "Port important și topitorie de cupru.", "Important port and copper smelter.", "Beliebte Strände in der Umgebung.", "Népszerű strandok a környéken.", "Plaje populare în împrejurimi.", "Popular beaches in the area."),
    ("puerto_maldonado", "state-capital", "PE-MDD", -69.1828, -12.5933, "Puerto Maldonado", "Hauptstadt der Region Madre de Dios.", "Madre de Dios régió fővárosa.", "Capitala regiunii Madre de Dios.", "Capital of the Madre de Dios region.", "Zentrum der Biodiversität im Amazonas.", "Az amazóniai biodiverzitás központja.", "Centru al biodiversității în Amazon.", "Center of biodiversity in the Amazon.", "Tor zum Tambopata-Nationalreservat.", "Kapu a Tambopata Nemzeti Rezervátumhoz.", "Poartă de acces către Rezervația Națională Tambopata.", "Gateway to the Tambopata National Reserve."),
    ("chulucanas", "city", "PE-PIU", -80.1625, -5.0931, "Chulucanas", "Stadt in der Region Piura.", "Város a Piura régióban.", "Oraș în regiunea Piura.", "City in the Piura region.", "Weltweit bekannt für ihre Keramik.", "Kerámiáiról világszerte ismert.", "Cunoscut în întreaga lume pentru ceramica sa.", "Known worldwide for its pottery.", "Produktion von Mango und Zitrone.", "Mangó és citrom termesztése.", "Producția de mango și lămâie.", "Production of mango and lemon."),
    ("sicuani", "city", "PE-CUS", -71.2261, -14.2694, "Sicuani", "Wichtige Stadt in der Region Cusco.", "Fontos város a Cusco régióban.", "Un oraș important din regiunea Cusco.", "Important city in the Cusco region.", "Ein zentrales Handelskreuz für Wolle.", "A gyapjú központi kereskedelmi csomópontja.", "O intersecție comercială centrală pentru lână.", "A central commercial crossroad for wool.", "Nahe den Inka-Ruinen von Raqchi.", "Raqchi inka romjai közelében.", "Aproape de ruinele incașe de la Raqchi.", "Near the Inca ruins of Raqchi."),
    ("abancay", "state-capital", "PE-APU", -72.8814, -13.6339, "Abancay", "Hauptstadt der Region Apurímac.", "Apurímac régió fővárosa.", "Capitala regiunii Apurímac.", "Capital of the Apurímac region.", "Umgeben von tiefen Canyons.", "Mély kanyonok veszik körül.", "Înconjurat de canioane adânci.", "Surrounded by deep canyons.", "Wichtiger landwirtschaftlicher Markt.", "Fontos mezőgazdasági piac.", "Piață agricolă importantă.", "Important agricultural market."),
    ("moquegua", "state-capital", "PE-MOQ", -70.9356, -17.1983, "Moquegua", "Hauptstadt der Region Moquegua im Süden.", "Moquegua régió fővárosa délen.", "Capitala regiunii Moquegua în sud.", "Capital of the Moquegua region in the south.", "Bekannt für traditionelle Architektur mit Satteldächern.", "Hagyományos nyeregtetős építészetéről ismert.", "Cunoscut pentru arhitectura tradițională cu acoperișuri în două ape.", "Known for traditional architecture with gabled roofs.", "Zentrum der peruanischen Pisco-Routen.", "A perui Pisco útvonalak központja.", "Centrul rutelor peruane Pisco.", "Center of the Peruvian Pisco routes."),
    ("yurimaguas", "city", "PE-LOR", -76.1039, -5.9030, "Yurimaguas", "Wichtiger Flusshafen in der Region Loreto.", "Fontos folyami kikötő a Loreto régióban.", "Un port fluvial important în regiunea Loreto.", "Important river port in the Loreto region.", "Bekannt als die 'Perle des Huallaga'.", "A 'Huallaga gyöngye' néven ismert.", "Cunoscut sub numele de „Perla de Huallaga”.", "Known as the 'Pearl of the Huallaga'.", "Liegt am Zusammenfluss von Huallaga und Paranapura.", "A Huallaga és a Paranapura összefolyásánál fekszik.", "Situat la confluența râurilor Huallaga și Paranapura.", "Located at the confluence of the Huallaga and Paranapura rivers."),
    ("chancay", "city", "PE-LMA", -77.2681, -11.5622, "Chancay", "Küstenstadt in der Region Lima.", "Tengerparti város a Lima régióban.", "Oraș de coastă în regiunea Lima.", "Coastal city in the Lima region.", "Heimat des Castillo de Chancay.", "A Chancay-kastély otthona.", "Casa Castelului Chancay.", "Home of the Castillo de Chancay.", "Baut einen großen neuen Hafen (Megaport).", "Egy hatalmas új kikötőt (Megaport) építenek.", "Construiește un port mare nou (Megaport).", "Building a large new port (Megaport)."),
    ("andahuaylas", "city", "PE-APU", -73.3853, -13.6556, "Andahuaylas", "Stadt in der Region Apurímac.", "Város az Apurímac régióban.", "Oraș în regiunea Apurímac.", "City in the Apurímac region.", "Bekannt für das Sondor Raymi Festival.", "A Sondor Raymi fesztiválról ismert.", "Cunoscut pentru festivalul Sondor Raymi.", "Known for the Sondor Raymi festival.", "Wichtiges Zentrum für Kartoffelanbau.", "A burgonyatermesztés fontos központja.", "Un centru important pentru cultivarea cartofilor.", "Important center for potato cultivation."),
    ("moyobamba", "state-capital", "PE-SAM", -76.9745, -6.0355, "Moyobamba", "Hauptstadt der Region San Martín.", "San Martín régió fővárosa.", "Capitala regiunii San Martín.", "Capital of the San Martín region.", "Die 'Stadt der Orchideen' in Peru.", "Az 'Orchideák Városa' Peruban.", "„Orașul orhideelor” din Peru.", "The 'City of Orchids' in Peru.", "Älteste spanische Stadt im Amazonas.", "A legrégebbi spanyol város az Amazonasban.", "Cel mai vechi oraș spaniol din Amazon.", "Oldest Spanish city in the Amazon."),
    ("huaura", "city", "PE-LMA", -77.5994, -11.0700, "Huaura", "Historische Stadt in der Region Lima.", "Történelmi város a Lima régióban.", "Oraș istoric în regiunea Lima.", "Historical city in the Lima region.", "Ort der ersten Unabhängigkeitserklärung Perus.", "Peru első függetlenségi nyilatkozatának helyszíne.", "Locul primei declarații de independență a statului Peru.", "Site of the first declaration of independence of Peru.", "José de San Martín sprach hier 1820 vom Balkon.", "José de San Martín 1820-ban itt beszélt az erkélyről.", "José de San Martín a vorbit aici de la balcon în 1820.", "José de San Martín spoke here from the balcony in 1820."),
    ("ferrenafe", "city", "PE-LAM", -79.7911, -6.6375, "Ferreñafe", "Stadt in der Region Lambayeque.", "Város a Lambayeque régióban.", "Oraș în regiunea Lambayeque.", "City in the Lambayeque region.", "Bekannt als die 'Stadt der doppelten Treue'.", "A 'Kettős Hűség Városa' néven ismert.", "Cunoscut ca „Orașul Dublei Loialități”.", "Known as the 'City of Double Loyalty'.", "Nahe dem Sicán-Nationalmuseum.", "A Sicán Nemzeti Múzeum közelében.", "Aproape de Muzeul Național Sicán.", "Near the Sicán National Museum."),
    ("quillabamba", "city", "PE-CUS", -72.6953, -12.8633, "Quillabamba", "Hauptstadt der Provinz La Convención in Cusco.", "La Convención tartomány fővárosa Cuscóban.", "Capitala provinciei La Convención din Cusco.", "Capital of the La Convención province in Cusco.", "Wichtiger Produzent von Kaffee und Kakao.", "Fontos kávé- és kakaótermelő.", "Un important producător de cafea și cacao.", "Important producer of coffee and cocoa.", "Liegt in einem warmen, subtropischen Tal.", "Egy meleg, szubtrópusi völgyben fekszik.", "Situat într-o vale caldă, subtropicală.", "Located in a warm, subtropical valley."),
    ("tingo_maria", "city", "PE-HUC", -76.0028, -9.2975, "Tingo María", "Stadt in der Region Huánuco am Huallaga-Fluss.", "Város a Huánuco régióban, a Huallaga folyó mentén.", "Oraș din regiunea Huánuco, pe râul Huallaga.", "City in the Huánuco region on the Huallaga River.", "Bekannt für den Nationalpark Tingo María.", "A Tingo María Nemzeti Parkról ismert.", "Cunoscut pentru Parcul Național Tingo María.", "Known for the Tingo María National Park.", "Die Bergkette 'Dornröschen' prägt das Landschaftsbild.", "A 'Csipkerózsika' hegyvonulat uralja a tájat.", "Lanțul muntos 'Frumoasa din Pădurea Adormită' domină peisajul.", "The 'Sleeping Beauty' mountain range dominates the landscape."),
    ("barranca", "city", "PE-LMA", -77.7656, -10.7519, "Barranca", "Küstenstadt in der Region Lima.", "Tengerparti város a Lima régióban.", "Oraș de coastă în regiunea Lima.", "Coastal city in the Lima region.", "Nahe der archäologischen Stätte Caral.", "Caral régészeti lelőhelyének közelében.", "Aproape de situl arheologic Caral.", "Near the archaeological site of Caral.", "Beliebte Strände und Gastronomie.", "Népszerű strandok és gasztronómia.", "Plaje populare și gastronomie.", "Popular beaches and gastronomy."),
    ("lambayeque", "city", "PE-LAM", -79.9075, -6.7022, "Lambayeque", "Stadt nahe Chiclayo, bekannt für Archäologie.", "Chiclayo melletti város, régészetéről ismert.", "Oraș lângă Chiclayo, cunoscut pentru arheologie.", "City near Chiclayo, known for archaeology.", "Heimat des Bruning-Museums und der Königsgäber von Sipán.", "A Bruning Múzeum és a Sipán királyi sírok otthona.", "Sediul Muzeului Bruning și al Mormintelor Regale din Sipán.", "Home to the Bruning Museum and Royal Tombs of Sipán.", "Wichtiges koloniales Erbe.", "Jelentős gyarmati örökség.", "Moștenire colonială importantă.", "Important colonial heritage."),
    ("chepen", "city", "PE-LAL", -79.4317, -7.2272, "Chepén", "Stadt in der Region La Libertad.", "Város a La Libertad régióban.", "Oraș în regiunea La Libertad.", "City in the La Libertad region.", "Bekannt für den Cerro Chepén und seinen Kreuzweg.", "A Cerro Chepénről és annak keresztútjáról ismert.", "Cunoscut pentru Cerro Chepén și Drumul Crucii sale.", "Known for the Cerro Chepén and its Way of the Cross.", "Wichtiges landwirtschaftliches und kommerzielles Zentrum.", "Fontos mezőgazdasági és kereskedelmi központ.", "Centru agricol și comercial important.", "Important agricultural and commercial center."),
    ("tarma", "city", "PE-JUN", -75.6883, -11.4189, "Tarma", "Die 'Perle der Anden' in der Region Junín.", "Az 'Andok gyöngye' a Junín régióban.", "„Perla Anzilor” din regiunea Junín.", "The 'Pearl of the Andes' in the Junín region.", "Bekannt für Blumenteppiche zu Ostern.", "Híres a húsvéti virágszőnyegeiről.", "Cunoscut pentru covoarele sale de flori de Paște.", "Known for flower carpets at Easter.", "Wichtiger Produzent von Blumen und Kräutern.", "Fontos virág- és gyógynövénytermelő.", "Un important producător de flori și ierburi.", "Important producer of flowers and herbs."),
    ("huacho", "city", "PE-LMA", -77.6075, -11.1064, "Huacho", "Küstenstadt und Hauptstadt der Provinz Huaura.", "Tengerparti város és Huaura tartomány fővárosa.", "Oraș de coastă și capitală a provinciei Huaura.", "Coastal city and capital of the Huaura province.", "Bekannt für die typische Wurst 'Salchicha Huachana'.", "A jellegzetes 'Salchicha Huachana' kolbászról ismert.", "Cunoscut pentru cârnații tipici 'Salchicha Huachana'.", "Known for the typical 'Salchicha Huachana' sausage.", "Nahe der Ausgrabungsstätte Bandurria.", "Bandurria ásatási területének közelében.", "Aproape de situl de excavare Bandurria.", "Near the Bandurria excavation site."),
    ("sechura", "city", "PE-PIU", -80.8228, -5.5569, "Sechura", "Stadt in der Region Piura an der Wüste Sechura.", "Város a Piura régióban a Sechura-sivatag mentén.", "Oraș din regiunea Piura de-a lungul deșertului Sechura.", "City in the Piura region along the Sechura Desert.", "Wichtiges Zentrum der peruanischen Phosphatförderung.", "A perui foszfátbányászat fontos központja.", "Centrul important al exploatării fosfaților din Peru.", "Important center of Peruvian phosphate mining.", "Die Bucht von Sechura ist reich an Meeresfrüchten.", "A Sechura-öböl gazdag tenger gyümölcseiben.", "Golful Sechura este bogat în fructe de mare.", "The Bay of Sechura is rich in seafood."),
    ("chota", "city", "PE-CAJ", -78.6517, -6.5606, "Chota", "Stadt im nördlichen Hochland von Cajamarca.", "Város Cajamarca északi hegyvidékén.", "Oraș în ținuturile muntoase de nord din Cajamarca.", "City in the northern highlands of Cajamarca.", "Bekannt für Rinderzucht und traditionelle Feste.", "Szarvasmarha-tenyésztésről és hagyományos fesztiválokról ismert.", "Cunoscut pentru creșterea vitelor și festivaluri tradiționale.", "Known for cattle breeding and traditional festivals.", "Die Provinz ist berühmt für die 'Rondas Campesinas'.", "A tartomány híres a 'Rondas Campesinas' paraszti őrségeiről.", "Provincia este renumită pentru 'Rondas Campesinas'.", "The province is famous for the 'Rondas Campesinas' peasant patrols."),
    ("pisco", "city", "PE-ICA", -76.2022, -13.7114, "Pisco", "Küstenstadt in der Region Ica.", "Tengerparti város a Ica régióban.", "Oraș de coastă în regiunea Ica.", "Coastal city in the Ica region.", "Namensgeber für den peruanischen Traubenschnaps.", "A perui szőlőpárlat névadója.", "Omonim pentru rachiul de struguri peruan.", "Namesake for the Peruvian grape brandy.", "Wichtiges Tor zu den Paracas-Inseln.", "Fontos kapu a Paracas-szigetekhez.", "O poartă importantă către Insulele Paracas.", "Important gateway to the Paracas Islands."),
    ("pacasmayo", "city", "PE-LAL", -79.5714, -7.4019, "Pacasmayo", "Hafenstadt in der Region La Libertad.", "Kikötőváros a La Libertad régióban.", "Oraș-port în regiunea La Libertad.", "Port city in the La Libertad region.", "Beliebt bei Surfern wegen der langen Wellen.", "Hosszú hullámai miatt népszerű a szörfösök körében.", "Popular printre surferi pentru valurile sale lungi.", "Popular with surfers because of its long waves.", "Bewahrt schöne koloniale Architektur.", "Megőrizte gyönyörű gyarmati építészetét.", "Păstrează o frumoasă arhitectură colonială.", "Preserves beautiful colonial architecture."),
    ("viru", "city", "PE-LAL", -78.7511, -8.4161, "Virú", "Stadt und Provinz in der Region La Libertad.", "Város és tartomány a La Libertad régióban.", "Oraș și provincie în regiunea La Libertad.", "City and province in the La Libertad region.", "Wichtiges Zentrum des Spargel- und Avocadoanbaus.", "A spárga és az avokádó termesztésének fontos központja.", "Centrul important al cultivării sparanghelului și avocado.", "Important center for asparagus and avocado cultivation.", "Reich an präkolumbianischen archäologischen Stätten.", "Gazdag prekolumbián régészeti lelőhelyekben.", "Bogat în situri arheologice precolumbiene.", "Rich in pre-Columbian archaeological sites."),
    ("requena", "city", "PE-LOR", -73.8517, -5.0608, "Requena", "Stadt am Fluss Ucayali in der Region Loreto.", "Város az Ucayali folyó partján a Loreto régióban.", "Oraș pe râul Ucayali în regiunea Loreto.", "City on the Ucayali River in the Loreto region.", "Bekannt als das 'Athen des Ucayali'.", "Az 'Ucayali Athénjaként' ismert.", "Cunoscut sub numele de „Atena din Ucayali”.", "Known as the 'Athens of the Ucayali'.", "Wichtiges Bildungszentrum im peruanischen Dschungel.", "Fontos oktatási központ a perui dzsungelben.", "Un important centru educațional în jungla peruană.", "Important educational center in the Peruvian jungle."),
    ("contamana", "city", "PE-LOR", -75.0119, -7.3486, "Contamana", "Hauptstadt der Provinz Ucayali in der Region Loreto.", "Ucayali tartomány fővárosa a Loreto régióban.", "Capitala provinciei Ucayali din regiunea Loreto.", "Capital of the Ucayali province in the Loreto region.", "Liegt an den Ufern des Flusses Ucayali.", "Az Ucayali folyó partján fekszik.", "Situat pe malul râului Ucayali.", "Located on the banks of the Ucayali River.", "Bekannt für das nahegelegene Thermalbad Aguas Calientes.", "A közeli Aguas Calientes termálfürdőről ismert.", "Cunoscut pentru băile termale din apropiere de la Aguas Calientes.", "Known for the nearby Aguas Calientes thermal baths."),
    ("juanjui", "city", "PE-SAM", -76.7294, -7.1775, "Juanjuí", "Stadt in der Region San Martín.", "Város a San Martín régióban.", "Oraș în regiunea San Martín.", "City in the San Martín region.", "Wichtiges Zentrum der Kakaoproduktion.", "A kakaótermelés fontos központja.", "Un centru important pentru producția de cacao.", "Important center for cocoa production.", "Ausgangspunkt für den Abiseo-Fluss-Nationalpark.", "Kiindulópont az Abiseo-folyó Nemzeti Parkhoz.", "Punct de plecare pentru Parcul Național Râul Abiseo.", "Starting point for the Abiseo River National Park."),
    ("bagua", "city", "PE-AMA", -78.5303, -5.6397, "Bagua", "Wichtige Stadt in der Region Amazonas.", "Fontos város az Amazonas régióban.", "Oraș important din regiunea Amazon.", "Important city in the Amazonas region.", "Zentrum des Handels für den peruanischen Dschungel.", "A perui dzsungel kereskedelmi központja.", "Centru de comerț pentru jungla peruană.", "Center of commerce for the Peruvian jungle.", "Umgeben von Kaffeebohnen- und Reisfeldern.", "Kávé- és rizsföldek veszik körül.", "Înconjurat de boabe de cafea și câmpuri de orez.", "Surrounded by coffee bean and rice fields."),
    ("chachapoyas", "state-capital", "PE-AMA", -77.8728, -6.2294, "Chachapoyas", "Hauptstadt der Region Amazonas in Nordperu.", "Amazonas régió fővárosa Észak-Peruban.", "Capitala regiunii Amazonas din nordul statului Peru.", "Capital of the Amazonas region in northern Peru.", "Zentrum der historischen Chachapoya-Kultur.", "A történelmi Chachapoya kultúra központja.", "Centrul culturii istorice Chachapoya.", "Center of the historical Chachapoya culture.", "Nahe der Festung Kuélap und dem Gocta-Wasserfall.", "A Kuélap erőd és a Gocta-vízesés közelében.", "Aproape de fortăreața Kuélap și cascada Gocta.", "Near the Kuélap fortress and the Gocta waterfall."),
    ("rioja", "city", "PE-SAM", -77.1667, -6.0614, "Rioja", "Die 'Stadt der Hüte' in der Region San Martín.", "A 'Kalapok Városa' a San Martín régióban.", "„Orașul pălăriilor” din regiunea San Martín.", "The 'City of Hats' in the San Martín region.", "Bekannt für den traditionellen Karneval.", "Híres a hagyományos karneválról.", "Cunoscut pentru carnavalul tradițional.", "Known for its traditional carnival.", "Wichtiges ökologisches Tourismusziel.", "Fontos ökológiai turisztikai célpont.", "Destinație importantă pentru turism ecologic.", "Important ecological tourism destination."),
    ("ilave", "city", "PE-PUN", -69.6381, -16.0825, "Ilave", "Wichtige Handelsstadt in der Region Puno.", "Fontos kereskedőváros a Puno régióban.", "Oraș comercial important în regiunea Puno.", "Important commercial city in the Puno region.", "Zentrum der Aymara-Kultur in Peru.", "Az aymara kultúra központja Peruban.", "Centrul culturii Aymara din Peru.", "Center of the Aymara culture in Peru.", "Großer Markt für landwirtschaftliche Produkte.", "Nagy piac a mezőgazdasági termékek számára.", "Piață mare pentru produse agricole.", "Large market for agricultural products."),
    ("huamachuco", "city", "PE-LAL", -78.0489, -7.8144, "Huamachuco", "Historische Stadt in der Region La Libertad.", "Történelmi város a La Libertad régióban.", "Oraș istoric în regiunea La Libertad.", "Historical city in the La Libertad region.", "Nahe der bedeutenden archäologischen Stätte Marcahuamachuco.", "Marcahuamachuco jelentős régészeti lelőhelyének közelében.", "Aproape de situl arheologic important de la Marcahuamachuco.", "Near the important archaeological site of Marcahuamachuco.", "Schauplatz der Schlacht von Huamachuco (1883).", "A huamachucói csata (1883) helyszíne.", "Scena bătăliei de la Huamachuco (1883).", "Scene of the Battle of Huamachuco (1883)."),
    ("nazca", "city", "PE-ICA", -74.9392, -14.8288, "Nazca", "Stadt in der Region Ica, im südlichen Peru.", "Város az Ica régióban, Dél-Peruban.", "Oraș în regiunea Ica, din sudul statului Peru.", "City in the Ica region, in southern Peru.", "Weltberühmt für die Nazca-Linien in der Wüste.", "Világhírű a sivatagban található Nazca-vonalakról.", "Cunoscut în întreaga lume pentru liniile Nazca din deșert.", "World-famous for the Nazca Lines in the desert.", "Wichtiger Touristenort wegen archäologischer Funde.", "Fontos turisztikai célpont a régészeti leletek miatt.", "Destinație turistică importantă datorită descoperirilor arheologice.", "Important tourist resort because of archaeological finds."),
    ("cutervo", "city", "PE-CAJ", -78.8169, -6.3764, "Cutervo", "Stadt im Hochland von Cajamarca.", "Város Cajamarca hegyvidékén.", "Oraș de munte din Cajamarca.", "City in the highlands of Cajamarca.", "Heimat des ersten Nationalparks Perus (1961).", "Peru első nemzeti parkjának (1961) otthona.", "Sediul primului parc național din Peru (1961).", "Home of the first national park of Peru (1961).", "Bekannt für Viehzucht und Landwirtschaft.", "Állattenyésztésről és mezőgazdaságról ismert.", "Cunoscut pentru creșterea vitelor și agricultură.", "Known for cattle breeding and agriculture."),
    ("catacaos", "city", "PE-PIU", -80.6761, -5.2678, "Catacaos", "Kleine Stadt in der Region Piura.", "Kisváros a Piura régióban.", "Orășel din regiunea Piura.", "Small town in the Piura region.", "Berühmt für Silber- und Goldfiligranarbeiten.", "Híres az ezüst- és arany filigrán munkákról.", "Renumit pentru munca cu filigran de argint și aur.", "Famous for silver and gold filigree work.", "Zentrum der peruanischen Picanterías (Restaurants).", "A perui picanteríák (éttermek) központja.", "Centrul picanteriilor (restaurantelor) peruane.", "Center of the Peruvian picanterías (restaurants)."),
    ("zarumilla", "city", "PE-TUM", -80.2742, -3.5019, "Zarumilla", "Grenzstadt in der nördlichen Region Tumbes.", "Határváros az északi Tumbes régióban.", "Oraș de graniță în regiunea de nord Tumbes.", "Border city in the northern Tumbes region.", "Schauplatz des ecuadorianisch-peruanischen Krieges (1941).", "Az ecuadori-perui háború (1941) helyszíne.", "Teatrul războiului ecuadorian-peruan (1941).", "Scene of the Ecuadorian-Peruvian War (1941).", "Nahe an Mangroven-Schutzgebieten.", "Közel a mangrove védett területekhez.", "Aproape de arii protejate cu mangrove.", "Close to mangrove protected areas."),
    ("lircay", "city", "PE-HUV", -74.7214, -12.9867, "Lircay", "Stadt und Hauptstadt der Provinz Angaraes.", "Város és Angaraes tartomány fővárosa.", "Oraș și capitală a provinciei Angaraes.", "City and capital of the Angaraes province.", "Liegt in der Region Huancavelica.", "A Huancavelica régióban található.", "Situat în regiunea Huancavelica.", "Located in the Huancavelica region.", "Bekannt als das 'Kleine Europa' wegen seines Mikroklimas.", "Mikroklímája miatt 'Kis Európaként' ismert.", "Cunoscută drept „Mica Europă” datorită microclimatului său.", "Known as 'Little Europe' due to its microclimate."),
    ("huancavelica", "state-capital", "PE-HUV", -74.9722, -12.7867, "Huancavelica", "Hauptstadt der Region Huancavelica.", "Huancavelica régió fővárosa.", "Capitala regiunii Huancavelica.", "Capital of the Huancavelica region.", "Wichtiges historisches Bergbauzentrum für Quecksilber.", "Fontos történelmi higanybányászati központ.", "Un important centru istoric minier de mercur.", "Important historical mining center for mercury.", "Liegt im tiefen Tal des Flusses Ichu.", "Az Ichu folyó mély völgyében fekszik.", "Situat în valea adâncă a râului Ichu.", "Located in the deep valley of the Ichu River."),
    ("satipo", "city", "PE-JUN", -74.6386, -11.2522, "Satipo", "Größte Provinz der Region Junín.", "A Junín régió legnagyobb tartománya.", "Cea mai mare provincie din regiunea Junín.", "Largest province in the Junín region.", "Wichtiges landwirtschaftliches Zentrum im Dschungel.", "Fontos mezőgazdasági központ a dzsungelben.", "Un centru agricol important în junglă.", "Important agricultural center in the jungle.", "Reich an indigenen Kulturen (Asháninka).", "Gazdag az őslakos kultúrákban (Asháninka).", "Bogat în culturi indigene (Asháninka).", "Rich in indigenous cultures (Asháninka)."),
    ("casma", "city", "PE-ANC", -78.3125, -9.4753, "Casma", "Stadt in der Region Ancash am Fluss Casma.", "Város az Ancash régióban, a Casma folyó partján.", "Oraș în regiunea Ancash pe râul Casma.", "City in the Ancash region on the Casma River.", "Nahe der archäologischen Stätte Sechín.", "Sechín régészeti lelőhelyének közelében.", "Aproape de situl arheologic Sechín.", "Near the archaeological site of Sechín.", "Gilt als die 'Stadt des ewigen Sonnenscheins'.", "Az 'Örök Napsütés Városaként' ismert.", "Considerat „Orașul Soarelui Etern”.", "Considered the 'City of Eternal Sunshine'."),
    ("yungay", "city", "PE-ANC", -77.7436, -9.1389, "Yungay", "Stadt im Callejón de Huaylas in der Region Ancash.", "Város a Callejón de Huaylas-ban, az Ancash régióban.", "Oraș din Callejón de Huaylas în regiunea Ancash.", "City in the Callejón de Huaylas in the Ancash region.", "Die alte Stadt wurde 1970 durch eine Lawine zerstört.", "A régi várost 1970-ben elpusztította egy lavina.", "Orașul vechi a fost distrus de o avalanșă în 1970.", "The old city was destroyed by an avalanche in 1970.", "Wichtiger Ausgangspunkt zum Huascarán-Nationalpark.", "Fontos kiindulópont a Huascarán Nemzeti Parkhoz.", "Punct de plecare important pentru Parcul Național Huascarán.", "Important starting point to the Huascarán National Park."),
    ("azangaro", "city", "PE-PUN", -70.1983, -14.9083, "Azángaro", "Historische Stadt in der Region Puno.", "Történelmi város a Puno régióban.", "Oraș istoric în regiunea Puno.", "Historical city in the Puno region.", "Bekannt als die 'Revolutionäre Stadt' im Kolonialismus.", "A gyarmati időkben 'Forradalmi Városként' ismert.", "Cunoscut ca „Orașul revoluționar” în perioada colonială.", "Known as the 'Revolutionary City' in colonial times.", "Zentrum der Viehzucht (Alpakas und Schafe).", "Az állattenyésztés központja (alpakák és juhok).", "Centrul creșterii vitelor (alpacas și oi).", "Center of cattle breeding (alpacas and sheep)."),
    ("macusani", "city", "PE-PUN", -70.4319, -14.0722, "Macusani", "Hauptstadt der Provinz Carabaya in der Region Puno.", "Carabaya tartomány fővárosa a Puno régióban.", "Capitala provinciei Carabaya din regiunea Puno.", "Capital of the Carabaya province in the Puno region.", "Ein bedeutendes Zentrum für Alpakazucht.", "Az alpakatenyésztés jelentős központja.", "Un centru major pentru creșterea alpaca.", "A major center for alpaca breeding.", "Liegt auf einer Höhe von über 4.300 Metern.", "Több mint 4300 méteres magasságban található.", "Situat la o altitudine de peste 4.300 de metri.", "Located at an altitude of over 4,300 meters."),
    ("putina", "city", "PE-PUN", -69.6631, -14.9133, "Putina", "Stadt in der Region Puno in den südlichen Anden.", "Város a Puno régióban a déli Andokban.", "Oraș din regiunea Puno din sudul Anzilor.", "City in the Puno region in the southern Andes.", "Berühmt für ihre Thermalquellen (Baños Termales).", "Híres hőforrásairól (Baños Termales).", "Renumit pentru izvoarele sale termale (Baños Termales).", "Famous for its thermal springs (Baños Termales).", "Umgeben von atemberaubenden Berglandschaften.", "Lélegzetelállító hegyi tájak veszik körül.", "Înconjurat de peisaje montane uluitoare.", "Surrounded by breathtaking mountain landscapes."),
    ("juli", "city", "PE-PUN", -69.4589, -16.2131, "Juli", "Eine der ältesten Städte in der Puno Region.", "A Puno régió egyik legrégebbi városa.", "Unul dintre cele mai vechi orașe din regiunea Puno.", "One of the oldest cities in the Puno region.", "Bekannt als das 'Rom der Anden' wegen seiner Kirchen.", "Templomai miatt az 'Andok Rómájaként' is ismert.", "Cunoscut ca 'Roma Anzilor' datorită bisericilor sale.", "Known as the 'Rome of the Andes' due to its churches.", "Liegt nahe dem Titicacasee.", "A Titicaca-tó közelében található.", "Situat în apropiere de lacul Titicaca.", "Located near Lake Titicaca."),
    ("ayaviri", "city", "PE-PUN", -70.5886, -14.8814, "Ayaviri", "Hauptstadt der Provinz Melgar in der Region Puno.", "Melgar tartomány fővárosa a Puno régióban.", "Capitala provinciei Melgar din regiunea Puno.", "Capital of the Melgar province in the Puno region.", "Wichtiges Zentrum der peruanischen Schaf- und Alpakazucht.", "A perui juh- és alpakatenyésztés fontos központja.", "Un centru important al creșterii de oi și alpaca din Peru.", "Important center of Peruvian sheep and alpaca breeding.", "Bekannt für das traditionelle Gericht 'Kankacho'.", "Híres a hagyományos 'Kankacho' nevű ételről.", "Cunoscut pentru preparatul tradițional 'Kankacho'.", "Known for the traditional dish 'Kankacho'."),
    ("tocache", "city", "PE-SAM", -76.5125, -8.1883, "Tocache", "Stadt in der Region San Martín im Huallaga-Tal.", "Város a San Martín régióban a Huallaga-völgyben.", "Oraș din regiunea San Martín, în Valea Huallaga.", "City in the San Martín region in the Huallaga Valley.", "Bekannt für den großflächigen Anbau von Kakao und Ölpalmen.", "Nagyüzemi kakaó- és olajpálma-termesztéséről ismert.", "Cunoscut pentru cultivarea pe scară largă a boabelor de cacao și a palmierilor de ulei.", "Known for large-scale cultivation of cocoa and oil palms.", "Verbindet den Regenwald mit der Zentralandenregion.", "Összeköti az esőerdőt a Középső-Andok régióval.", "Conectează pădurea tropicală cu regiunea Anzilor Centrale.", "Connects the rainforest with the central Andes region."),
    ("saposoa", "city", "PE-SAM", -76.7722, -6.9367, "Saposoa", "Stadt in der peruanischen Region San Martín.", "Város a perui San Martín régióban.", "Oraș în regiunea peruană San Martín.", "City in the Peruvian San Martín region.", "Nahe am Nationalpark Rio Abiseo, einem UNESCO-Weltkulturerbe.", "Közel a Rio Abiseo Nemzeti Parkhoz, amely UNESCO Világörökség.", "Aproape de Parcul Național Rio Abiseo, inclus în Patrimoniul Mondial UNESCO.", "Close to the Rio Abiseo National Park, a UNESCO World Heritage site.", "Eine der ältesten Städte im Amazonas-Gebiet Perus.", "Peru amazóniai régiójának egyik legrégebbi városa.", "Unul dintre cele mai vechi orașe din regiunea amazoniană din Peru.", "One of the oldest cities in the Amazon region of Peru."),
    ("amaszonas", "city", "PE-AMA", -77.8653, -6.2231, "Utcubamba", "Provinzstadt in der Region Amazonas.", "Tartományi város az Amazonas régióban.", "Oraș de provincie din regiunea Amazon.", "Provincial city in the Amazonas region.", "Verfügt über ein heißes, tropisches Klima.", "Forró, trópusi éghajlattal rendelkezik.", "Are un climat cald, tropical.", "Features a hot, tropical climate.", "Zentrum des regionalen Handels mit Reis und Kaffee.", "A regionális rizs- és kávékereskedelem központja.", "Centrul comerțului regional cu orez și cafea.", "Center of regional trade in rice and coffee."),
    ("otuzco", "city", "PE-LAL", -78.5667, -7.9017, "Otuzco", "Stadt in der Region La Libertad in Nordperu.", "Város a La Libertad régióban, Észak-Peruban.", "Oraș din regiunea La Libertad, în nordul statului Peru.", "City in the La Libertad region in northern Peru.", "Die Hauptstadt des 'Glaubens' wegen der Virgen de la Puerta.", "A 'hit' fővárosa a Virgen de la Puerta (A Kapu Szűze) miatt.", "Capitala 'credinței' datorită Virgen de la Puerta (Fecioara de la Poartă).", "The capital of 'faith' due to the Virgen de la Puerta (Virgin of the Gate).", "Wichtiger Ort für Wallfahrten im Dezember.", "Fontos zarándokhely decemberben.", "Un loc important de pelerinaj în decembrie.", "Important pilgrimage site in December."),
    ("santiago_de_chuco", "city", "PE-LAL", -78.1728, -8.1436, "Santiago de Chuco", "Stadt in der Region La Libertad.", "Város a La Libertad régióban.", "Oraș în regiunea La Libertad.", "City in the La Libertad region.", "Geburtsort des berühmten peruanischen Dichters César Vallejo.", "César Vallejo híres perui költő szülőhelye.", "Locul de naștere al faimosului poet peruan César Vallejo.", "Birthplace of the famous Peruvian poet César Vallejo.", "Bewahrt seine andine und koloniale Identität.", "Megőrizte andoki és gyarmati identitását.", "Își păstrează identitatea andină și colonială.", "Preserves its Andean and colonial identity."),
    ("chucuito", "city", "PE-PUN", -69.8892, -15.8953, "Chucuito", "Historische Stadt in der Region Puno nahe dem Titicacasee.", "Történelmi város a Puno régióban a Titicaca-tó közelében.", "Oraș istoric din regiunea Puno lângă Lacul Titicaca.", "Historical city in the Puno region near Lake Titicaca.", "Bekannt als die Stadt der königlichen Kassen der Inkas.", "Az inkák királyi kincstárainak városaként ismert.", "Cunoscut ca orașul cufere regale incașe.", "Known as the city of the royal coffers of the Incas.", "Beherbergt den Inka-Tempel der Fruchtbarkeit 'Inca Uyo'.", "Az 'Inca Uyo' inka termékenységi templomnak ad otthont.", "Găzduiește templul incaș al fertilității „Inca Uyo”.", "Houses the Inca temple of fertility 'Inca Uyo'."),
    ("acobamba", "city", "PE-HUV", -74.5683, -12.8419, "Acobamba", "Provinzhauptstadt in der Region Huancavelica.", "Tartományi főváros a Huancavelica régióban.", "Capitală de provincie din regiunea Huancavelica.", "Provincial capital in the Huancavelica region.", "Wirtschaft basiert auf Landwirtschaft, vor allem Kartoffeln und Mais.", "Gazdasága a mezőgazdaságon, főleg burgonyán és kukoricán alapul.", "Economia bazată pe agricultură, în special cartofi și porumb.", "Economy based on agriculture, especially potatoes and corn.", "Verfügt über tiefe andine Täler und steile Hänge.", "Mély andoki völgyekkel és meredek lejtőkkel rendelkezik.", "Prezintă văi andine adânci și versanți abrupți.", "Features deep Andean valleys and steep slopes."),
    ("pampas", "city", "PE-HUV", -74.8692, -12.3969, "Pampas", "Hauptstadt der Provinz Tayacaja in der Region Huancavelica.", "Tayacaja tartomány fővárosa a Huancavelica régióban.", "Capitala provinciei Tayacaja din regiunea Huancavelica.", "Capital of the Tayacaja province in the Huancavelica region.", "Bekannt für das Wasserkraftwerk 'Santiago Antúnez de Mayolo'.", "A 'Santiago Antúnez de Mayolo' vízerőműről ismert.", "Cunoscut pentru hidrocentrala 'Santiago Antúnez de Mayolo'.", "Known for the 'Santiago Antúnez de Mayolo' hydroelectric power plant.", "Fruchtbares Tal in einer rauen Berglandschaft.", "Termékeny völgy zord hegyvidéki tájon.", "O vale fertilă într-un peisaj montan accidentat.", "Fertile valley in a harsh mountain landscape."),
    ("castrovirreyna", "city", "PE-HUV", -75.3189, -13.2792, "Castrovirreyna", "Hochgelegene Stadt in der Region Huancavelica.", "Magasan fekvő város a Huancavelica régióban.", "Oraș la mare altitudine în regiunea Huancavelica.", "High-altitude city in the Huancavelica region.", "Benannt nach dem Vizekönig von Peru aus dem 16. Jahrhundert.", "A 16. századi perui alkirályról kapta a nevét.", "Numit după viceregele statului Peru din secolul al XVI-lea.", "Named after the Viceroy of Peru from the 16th century.", "Historisch sehr bedeutend für den Silberabbau.", "Történelmileg nagyon fontos az ezüstbányászat szempontjából.", "Istoric foarte important pentru extracția argintului.", "Historically very important for silver mining."),
    ("churcampa", "city", "PE-HUV", -74.3886, -12.7381, "Churcampa", "Stadt in der nordöstlichen Region von Huancavelica.", "Város Huancavelica északkeleti részén.", "Oraș din regiunea de nord-est a orașului Huancavelica.", "City in the northeastern region of Huancavelica.", "Stark von der andinen Kultur und der indigenen Gemeinschaft geprägt.", "Az andoki kultúra és az őslakos közösség erősen meghatározza.", "Puternic influențat de cultura andină și de comunitatea indigenă.", "Strongly influenced by the Andean culture and the indigenous community.", "Agrarzentrum für die lokale Bevölkerung.", "A helyi lakosság agráközpontja.", "Centru agricol pentru populația locală.", "Agricultural center for the local population."),
    ("caballo_cocha", "city", "PE-LOR", -70.5264, -3.9056, "Caballococha", "Stadt am Amazonas-Fluss nahe der Grenze zu Kolumbien und Brasilien.", "Város az Amazonas folyónál, Kolumbia és Brazília határának közelében.", "Oraș pe râul Amazon, la granița cu Columbia și Brazilia.", "City on the Amazon River near the border with Colombia and Brazil.", "Wichtig für den Grenzübergang (Tres Fronteras).", "Fontos határátkelőhely (Tres Fronteras).", "Punct de trecere a frontierei important (Tres Fronteras).", "Important for the border crossing (Tres Fronteras).", "Hauptstadt der Provinz Mariscal Ramón Castilla.", "Mariscal Ramón Castilla tartomány fővárosa.", "Capitala provinciei Mariscal Ramón Castilla.", "Capital of the Mariscal Ramón Castilla province."),
    ("nauta", "city", "PE-LOR", -73.5806, -4.5061, "Nauta", "Eine der ältesten Städte in der Region Loreto.", "A Loreto régió egyik legrégebbi városa.", "Unul dintre cele mai vechi orașe din regiunea Loreto.", "One of the oldest cities in the Loreto region.", "Liegt nahe dem Zusammenfluss von Marañón und Ucayali.", "A Marañón és az Ucayali összefolyásának közelében található.", "Situat aproape de confluența râurilor Marañón și Ucayali.", "Located near the confluence of the Marañón and Ucayali rivers.", "Ausgangspunkt für Reisen ins Pacaya-Samiria-Nationalreservat.", "Kiindulópont a Pacaya-Samiria Nemzeti Rezervátumba induló utazásokhoz.", "Punct de plecare pentru excursiile în Rezervația Națională Pacaya-Samiria.", "Starting point for trips to the Pacaya-Samiria National Reserve."),
    ("requena_dos", "city", "PE-LOR", -73.8517, -5.0608, "Requena", "Stadt am Fluss Ucayali in der Region Loreto.", "Város az Ucayali folyó partján a Loreto régióban.", "Oraș pe râul Ucayali în regiunea Loreto.", "City on the Ucayali River in the Loreto region.", "Bekannt als das 'Athen des Ucayali'.", "Az 'Ucayali Athénjaként' ismert.", "Cunoscut sub numele de „Atena din Ucayali”.", "Known as the 'Athens of the Ucayali'.", "Wichtiges Bildungszentrum im peruanischen Dschungel.", "Fontos oktatási központ a perui dzsungelben.", "Un important centru educațional în jungla peruană.", "Important educational center in the Peruvian jungle."),
    ("coracora", "city", "PE-AYA", -73.7844, -15.0211, "Coracora", "Hauptstadt der Provinz Parinacochas in der Region Ayacucho.", "Parinacochas tartomány fővárosa az Ayacucho régióban.", "Capitala provinciei Parinacochas din regiunea Ayacucho.", "Capital of the Parinacochas province in the Ayacucho region.", "Berühmt für das Fest der Virgen de las Nieves im August.", "Híres az augusztusi Virgen de las Nieves fesztiválról.", "Renumit pentru festivalul Virgen de las Nieves din august.", "Famous for the festival of the Virgen de las Nieves in August.", "Wichtiges Zentrum der Rinderzucht und Käseproduktion.", "A szarvasmarha-tenyésztés és sajtgyártás fontos központja.", "Un centru important pentru creșterea vitelor și producția de brânză.", "Important center of cattle breeding and cheese production.")
]


import glob
import sys

# find existing perl poi files to create blocklist
files = glob.glob("lib/visualLab/data/peruPoi.ts") + glob.glob("lib/visualLab/data/poiExtraPeru*.ts")
blocklist = set()
for f in files:
    with open(f, "r", encoding="utf-8") as file:
        lines = file.readlines()
        for i, line in enumerate(lines):
            if "name:" in line and "de:" in line:
                try:
                    # extract 'de: "Name"'
                    import re
                    match = re.search(r'de:\s*"([^"]+)"', line)
                    if not match:
                        match = re.search(r'de:\s*"([^"]+)"', lines[i+1])
                    if match:
                        blocklist.add(match.group(1).lower())
                except:
                    pass
            elif "de:" in line and "name" not in line:
                # might be name de inside a block
                try:
                    import re
                    match = re.search(r'de:\s*"([^"]+)"', line)
                    if match:
                        # only add if very short to avoid adding descriptions
                        val = match.group(1).strip()
                        if len(val) < 30:
                            blocklist.add(val.lower())
                except:
                    pass

print("Blocklist items:", len(blocklist))

valid_pois = []
for c in cities:
    (uid, ptype, parent, lon, lat, 
    n_de, d_de, d_hu, d_ro, d_en, 
    f1_de, f1_hu, f1_ro, f1_en, 
    f2_de, f2_hu, f2_ro, f2_en) = c
    
    if n_de.lower() in blocklist:
        continue
        
    # ensure no duplicates in the current list
    if any(p["id"] == f"{uid}-cities-v2" for p in valid_pois):
        continue
    if any(p["name_de"].lower() == n_de.lower() for p in valid_pois):
        continue
    
    valid_pois.append({
        "id": f"{uid}-cities-v2",
        "type": ptype,
        "parent": parent,
        "lon": lon,
        "lat": lat,
        "name_de": n_de, "name_hu": n_de, "name_ro": n_de, "name_en": n_de,
        "desc_de": d_de, "desc_hu": d_hu, "desc_ro": d_ro, "desc_en": d_en,
        "f1_de": f1_de, "f1_hu": f1_hu, "f1_ro": f1_ro, "f1_en": f1_en,
        "f2_de": f2_de, "f2_hu": f2_hu, "f2_ro": f2_ro, "f2_en": f2_en,
    })

if len(valid_pois) < 70:
    print(f"Warning: Only {len(valid_pois)} POIs generated.")
    # we need more to reach exactly 70
    # we have 70 in list, wait, let's see how many get accepted.
else:
    valid_pois = valid_pois[:70]


import math
import random

# we have 70 unique cities in the array, wait, there are 70 entries in my array? Let's check.
# I will output the file directly in python
with open("lib/visualLab/data/poiExtraPeruCitiesV2.ts", "w", encoding="utf-8") as out:
    out.write('import type { POI } from "./poi";\n\n')
    out.write('export const poiExtraPeruCitiesV2: POI[] = [\n')
    
    for i, p in enumerate(valid_pois):
        out.write('  {\n')
        out.write(f'    id: "{p["id"]}",\n')
        out.write(f'    type: "{p["type"]}",\n')
        out.write(f'    parent: "{p["parent"]}",\n')
        out.write(f'    coords: [{p["lon"]}, {p["lat"]}],\n')
        out.write('    name: {\n')
        out.write(f'      de: "{p["name_de"]}",\n')
        out.write(f'      hu: "{p["name_hu"]}",\n')
        out.write(f'      ro: "{p["name_ro"]}",\n')
        out.write(f'      en: "{p["name_en"]}"\n')
        out.write('    },\n')
        out.write('    description: {\n')
        out.write(f'      de: "{p["desc_de"]}",\n')
        out.write(f'      hu: "{p["desc_hu"]}",\n')
        out.write(f'      ro: "{p["desc_ro"]}",\n')
        out.write(f'      en: "{p["desc_en"]}"\n')
        out.write('    },\n')
        out.write('    facts: {\n')
        out.write(f'      de: ["{p["f1_de"]}", "{p["f2_de"]}"],\n')
        out.write(f'      hu: ["{p["f1_hu"]}", "{p["f2_hu"]}"],\n')
        out.write(f'      ro: ["{p["f1_ro"]}", "{p["f2_ro"]}"],\n')
        out.write(f'      en: ["{p["f1_en"]}", "{p["f2_en"]}"]\n')
        out.write('    }\n')
        if i == len(valid_pois) - 1:
            out.write('  }\n')
        else:
            out.write('  },\n')
            
    out.write('];\n')

print(f"Generated {len(valid_pois)} POIs.")
