/*

import type { POI } from "./poi";

export const poiExtraBelizeHistoryV2: POI[] = [
  {
    id: "battle-of-st-georges-caye-history-v2",
    type: "historical",
    parent: "BZ-BZ",
    coords: [-88.055, 17.561],
    name: {
      de: "Schlacht von St. George’s Caye",
      hu: "St. George’s Caye-i csata",
      ro: "Bătălia de la St. George's Caye",
      en: "Battle of St. George's Caye",
    },
    description: {
      de: "Ort der entscheidenden Seeschlacht von 1798 zwischen britischen Siedlern und Spanien, die die britische Kontrolle über das Gebiet sicherte.",
      hu: "Az 1798-as döntő tengeri csata helyszíne a brit telepesek és Spanyolország között, amely biztosította a brit fennhatóságot a területen.",
      ro: "Locul bătăliei navale decisive din 1798 dintre coloniștii britanici și Spania, care a asigurat controlul britanic asupra zonei.",
      en: "The site of the decisive 1798 naval battle between British settlers and Spain, which secured British control over the area.",
    },
    facts: {
      de: ["Fand im September 1798 statt.", "Nationalfeiertag am 10. September.", "Sicherte die Zukunft von Britisch-Honduras.", "Ein Wendepunkt in der Geschichte von Belize."],
      hu: ["1798 szeptemberében zajlott.", "Nemzeti ünnep szeptember 10-én.", "Biztosította Brit Honduras jövőjét.", "Fordulópont Belize történelmében."],
      ro: ["A avut loc în septembrie 1798.", "Sărbătoare națională pe 10 septembrie.", "A asigurat viitorul Hondurasului Britanic.", "Un punct de cotitură în istoria Belize."],
      en: ["Took place in September 1798.", "A national holiday is celebrated on September 10th.", "Secured the future of British Honduras.", "A turning point in Belizean history."],
    },
    descriptionAdvanced: {
      de: "",
      hu: "",
      ro: "",
      en: "St. George's Caye holds a legendary place in Belizean history as the site of the pivotal naval battle in September 1798. This engagement between British Baymen and the Spanish fleet from Mexico determined the future of the territory, ending centuries of Spanish claims and solidifying British influence. Today, the island remains a peaceful retreat, but the legacy of the battle is celebrated annually as a symbol of national resilience. Visitors can explore the historical markers and enjoy the pristine Caribbean waters that once witnessed this decisive moment. The victory at St. George's Caye is considered the birth of Belize as a distinct political entity in Central America."
    },
    factsAdvanced: {
      de: [],
      hu: [],
      ro: [],
      en: ["The battle occurred between September 3 and 10, 1798.", "September 10th is a public holiday in Belize known as St. George"s Caye Day.", "The Spanish fleet consisted of 32 vessels and 2,000 troops.", "British defenders used small sloops and flat-bottomed gunboats called "rafts".", "Not a single life was lost on the British side during the final engagement.", "The island served as the first capital of the British settlement until the 1800s.", "It is located approximately 8 miles northeast of Belize City."]
    },
  },
  {
    id: "santa-rita-corozal-history-v2",
    type: "historical",
    parent: "BZ-CZL",
    coords: [-88.4, 18.39],
    name: {
      de: "Maya-Stätte Santa Rita",
      hu: "Santa Rita maja romok",
      ro: "Situl arheologic Santa Rita",
      en: "Santa Rita Archaeological Site",
    },
    description: {
      de: "Eine antike Maya-Stätte in der Nähe von Corozal Town, die ein wichtiges Handelszentrum war.",
      hu: "Ősi maja lelőhely Corozal Town közelében, amely fontos kereskedelmi központ volt.",
      ro: "Un sit mayaș antic lângă Corozal Town, care a fost un important centru comercial.",
      en: "An ancient Maya site near Corozal Town that was an important trading center.",
    },
    facts: {
      de: ["Früheste Siedlung um 1200 v. Chr.", "Kontrollierte den Handel mit Jade und Obsidian.", "War bei Ankunft der Spanier noch bewohnt.", "Historischer Name war Chetumal."],
      hu: ["A legkorábbi település i.e. 1200 körül.", "Ellenőrizte a jáde és obszidián kereskedelmét.", "A spanyolok érkezésekor még lakott volt.", "Történelmi neve Chetumal volt."],
      ro: ["Cea mai veche așezare în jurul anului 1200 î.Hr.", "Controla comerțul cu jad și obsidian.", "Era încă locuit la sosirea spaniolilor.", "Numele istoric a fost Chetumal."],
      en: ["Earliest settlement around 1200 BC.", "Controlled trade in jade and obsidian.", "Was still occupied upon Spanish arrival.", "Historic name was Chetumal."],
    },
  },
  {
    id: "el-pilar-ruins-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.16, 17.17],
    name: {
      de: "El Pilar Ruinen",
      hu: "El Pilar romok",
      ro: "Ruinele El Pilar",
      en: "El Pilar Ruins",
    },
    description: {
      de: "Eine große Maya-Stätte an der Grenze zu Guatemala, bekannt für ihre Garten-Städtebauweise.",
      hu: "Nagy maja lelőhely a guatemalai határon, kertvárosi jellegű várostervezéséről ismert.",
      ro: "Un mare sit mayaș la granița cu Guatemala, cunoscut pentru urbanismul său de tip oraș-grădină.",
      en: "A large Maya site on the border with Guatemala, known for its garden-city urbanism.",
    },
    facts: {
      de: ["Bedeutet 'Wasserbecken'.", "Über 25 Plätze und hunderte von Bauten.", "Fokus auf nachhaltige Landwirtschaft.", "Wird gemeinsam von Belize und Guatemala verwaltet."],
      hu: ["Jelentése 'vízgyűjtő medence'.", "Több mint 25 tér és több száz épület.", "A fenntartható mezőgazdaságra összpontosít.", "Belize és Guatemala közösen kezeli."],
      ro: ["Înseamnă 'bazin de apă'.", "Peste 25 de piețe și sute de structuri.", "Accent pe agricultura durabilă.", "Gestionat în comun de Belize și Guatemala."],
      en: ["Means 'watering basin'.", "Over 25 plazas and hundreds of structures.", "Focus on sustainable agriculture.", "Co-managed by Belize and Guatemala."],
    },
  },
  {
    id: "poustinia-land-art-park-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-88.9, 17.4],
    name: {
      de: "Poustinia Land Art Park",
      hu: "Poustinia Land Art Park",
      ro: "Parcul de artă Poustinia",
      en: "Poustinia Land Art Park",
    },
    description: {
      de: "Ein Skulpturenpark, der moderne Kunst mit der Geschichte und Natur von Belize verbindet.",
      hu: "Szoborpark, amely a modern művészetet ötvözi Belize történelmével és természetével.",
      ro: "Un parc de sculptură care combină arta modernă cu istoria și natura din Belize.",
      en: "A sculpture park that combines modern art with the history and nature of Belize.",
    },
    facts: {
      de: ["Gegründet vom Künstler Daniel Popper.", "Installationen reflektieren die Maya-Kultur.", "Befindet sich im Dschungel.", "Spiritueller und künstlerischer Ort."],
      hu: ["Daniel Popper művész alapította.", "Az installációk a maja kultúrát tükrözik.", "A dzsungelben található.", "Spirituális és művészeti hely."],
      ro: ["Fondat de artistul Daniel Popper.", "Instalațiile reflectă cultura mayașă.", "Situat în junglă.", "Loc spiritual și artistic."],
      en: ["Founded by artist Daniel Popper.", "Installations reflect Maya culture.", "Located in the jungle.", "A spiritual and artistic place."],
    },
  },
  {
    id: "marco-gonzalez-site-history-v2",
    type: "historical",
    parent: "BZ-BZ",
    coords: [-87.98, 17.85],
    name: {
      de: "Marco Gonzalez Maya-Stätte",
      hu: "Marco Gonzalez maja lelőhely",
      ro: "Situl mayaș Marco Gonzalez",
      en: "Marco Gonzalez Maya Site",
    },
    description: {
      de: "Eine Maya-Handelsstation an der Südspitze von Ambergris Caye.",
      hu: "Maja kereskedelmi állomás az Ambergris Caye déli csücskén.",
      ro: "Un post comercial mayaș la capătul sudic al Ambergris Caye.",
      en: "A Maya trading outpost on the southern tip of Ambergris Caye.",
    },
    facts: {
      de: ["Küstenhandelszentrum.", "Wurde durch einen Hurrikan teilweise freigelegt.", "Fokus auf Salzproduktion und -handel.", "Jetzt ein geschütztes Reservat."],
      hu: ["Parti kereskedelmi központ.", "Egy hurrikán részben feltárta.", "A sótermelésre és -kereskedelemre összpontosított.", "Ma védett rezervátum."],
      ro: ["Centru comercial de coastă.", "Parțial expus de un uragan.", "Concentrat pe producția și comerțul cu sare.", "Acum o rezervație protejată."],
      en: ["Coastal trading center.", "Partially exposed by a hurricane.", "Focused on salt production and trade.", "Now a protected reserve."],
    },
  },
  {
    id: "old-belize-city-prison-history-v2",
    type: "historical",
    parent: "BZ-BZ",
    coords: [-88.19, 17.495],
    name: {
      de: "Altes Gefängnis von Belize City",
      hu: "Régi Belize City-i börtön",
      ro: "Vechea închisoare din Belize City",
      en: "Old Belize City Prison",
    },
    description: {
      de: "Ein historisches Gefängnis aus der Kolonialzeit, das heute das Museum von Belize beherbergt.",
      hu: "Történelmi gyarmati kori börtön, amely ma a Belize Múzeumnak ad otthont.",
      ro: "O închisoare istorică din epoca colonială, care acum găzduiește Muzeul din Belize.",
      en: "A historic colonial-era prison that now houses the Museum of Belize.",
    },
    facts: {
      de: ["Erbaut 1857.", "Diente bis 1993 als Gefängnis.", "Wurde in ein Nationalmuseum umgewandelt.", "Zeigt die Geschichte und Kultur von Belize."],
      hu: ["1857-ben épült.", "1993-ig börtönként szolgált.", "Nemzeti múzeummá alakították át.", "Belize történelmét és kultúráját mutatja be."],
      ro: ["Construită în 1857.", "A servit ca închisoare până în 1993.", "Transformata întrun muzeu național.", "Prezintă istoria și cultura din Belize."],
      en: ["Built in 1857.", "Served as a prison until 1993.", "Was converted into a national museum.", "Showcases the history and culture of Belize."],
    },
  },
  {
    id: "serpon-sugar-mill-history-v2",
    type: "historical",
    parent: "BZ-SC",
    coords: [-88.35, 16.9],
    name: {
      de: "Serpon Zuckerfabrik",
      hu: "Serpon cukorgyár",
      ro: "Fabrica de zahăr Serpon",
      en: "Serpon Sugar Mill",
    },
    description: {
      de: "Die Ruinen der ersten dampfbetriebenen Zuckerfabrik in Belize aus dem 19. Jahrhundert.",
      hu: "Belize első, 19. századi gőzzel hajtott cukorgyárának romjai.",
      ro: "Ruinele primei fabrici de zahăr cu aburi din Belize, din secolul al XIX-lea.",
      en: "The ruins of the first steam-powered sugar mill in Belize, dating to the 19th century.",
    },
    facts: {
      de: ["Gegründet 1862.", "Ein Pionier der industriellen Revolution in Belize.", "Heute ein archäologisches Reservat.", "Zeigt die Maschinerie aus dieser Zeit."],
      hu: ["1862-ben alapították.", "Az ipari forradalom úttörője Belize-ben.", "Ma régészeti rezervátum.", "Bemutatja az akkori gépeket."],
      ro: ["Fondată în 1862.", "Un pionier al revoluției industriale din Belize.", "Acum o rezervație arheologică.", "Prezintă mașinăriile din acea perioadă."],
      en: ["Established in 1862.", "A pioneer of the industrial revolution in Belize.", "Now an archaeological reserve.", "Displays the machinery from the era."],
    },
  },
  {
    id: "yarborough-cemetery-history-v2",
    type: "historical",
    parent: "BZ-BZ",
    coords: [-88.19, 17.48],
    name: {
      de: "Yarborough-Friedhof",
      hu: "Yarborough temető",
      ro: "Cimitirul Yarborough",
      en: "Yarborough Cemetery",
    },
    description: {
      de: "Der älteste europäische Friedhof in Belize, der bis ins 18. Jahrhundert zurückreicht.",
      hu: "Belize legrégebbi európai temetője, amely a 18. századig nyúlik vissza.",
      ro: "Cel mai vechi cimitir european din Belize, datând din secolul al XVIII-lea.",
      en: "The oldest European cemetery in Belize, dating back to the 18th century.",
    },
    facts: {
      de: ["Gräber von frühen Siedlern.", "Einige Gräber wurden aus England verschifft.", "Historische Grabsteine.", "Befindet sich in Belize City."],
      hu: ["Korai telepesek sírjai.", "Néhány sírkövet Angliából szállítottak.", "Történelmi sírkövek.", "Belize Cityben található."],
      ro: ["Mormintele primilor coloniști.", "Unele morminte au fost expediate din Anglia.", "Pietre funerare istorice.", "Situat în Belize City."],
      en: ["Graves of early settlers.", "Some graves were shipped from England.", "Historic tombstones.", "Located in Belize City."],
    },
  },
  {
    id: "cuello-ruins-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-88.58, 18.08],
    name: {
      de: "Cuello Ruinen",
      hu: "Cuello romok",
      ro: "Ruinele Cuello",
      en: "Cuello Ruins",
    },
    description: {
      de: "Eine der ältesten bekannten Maya-Stätten, mit einer Besiedlungsgeschichte bis 2600 v. Chr.",
      hu: "Az egyik legrégebbi ismert maja lelőhely, amelynek településtörténete i.e. 2600-ig nyúlik vissza.",
      ro: "Unul dintre cele mai vechi situri mayașe cunoscute, cu o istorie de locuire datând din 2600 î.Hr.",
      en: "One of the earliest known Maya sites, with a settlement history dating back to 2600 BC.",
    },
    facts: {
      de: ["Eine der ältesten Maya-Siedlungen.", "Auf Privatgelände gelegen (Cuello Rum Distillery).", "Wichtige Erkenntnisse über die frühe Maya-Kultur.", "Besuch nur mit Erlaubnis möglich."],
      hu: ["Az egyik legrégebbi maja település.", "Magánterületen található (Cuello Rum szeszfőzde).", "Fontos betekintést nyújt a korai maja kultúrába.", "Látogatás csak engedéllyel."],
      ro: ["Una dintre cele mai vechi așezări mayașe.", "Situat pe proprietate privată (Distileria de rom Cuello).", "Informații importante despre cultura mayașă timpurie.", "Vizitarea este posibilă numai cu permisiune."],
      en: ["One of the oldest Maya settlements.", "Located on private land (Cuello Rum Distillery).", "Provided key insights into early Maya culture.", "Permission required for visits."],
    },
  },
  {
    id: "buena-vista-cayo-ruin-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.0, 17.18],
    name: {
      de: "Buena Vista del Cayo Ruine",
      hu: "Buena Vista del Cayo rom",
      ro: "Ruina Buena Vista del Cayo",
      en: "Buena Vista del Cayo Ruin",
    },
    description: {
      de: "Eine kleinere, aber bedeutende Maya-Stätte nahe San Ignacio.",
      hu: "Kisebb, de jelentős maja lelőhely San Ignacio közelében.",
      ro: "Un sit mayaș mai mic, dar important, lângă San Ignacio.",
      en: "A smaller but significant Maya site near San Ignacio.",
    },
    facts: {
      de: ["Diente als sekundäres Zentrum zu Cahal Pech.", "Strategische Lage am Mopan River.", "Wichtige archäologische Funde.", "Umgangssprachlich als 'Gute Aussicht' bekannt."],
      hu: ["Cahal Pech másodlagos központjaként szolgált.", "Stratégiai fekvés a Mopan-folyó mentén.", "Fontos régészeti leletek.", "Köznyelvben 'Jó kilátás'-ként ismert."],
      ro: ["A servit ca centru secundar pentru Cahal Pech.", "Locație strategică pe râul Mopan.", "Descoperiri arheologice importante.", "Cunoscut colocvial ca 'Vedere Bună'."],
      en: ["Served as a secondary center to Cahal Pech.", "Strategic location on the Mopan River.", "Important archaeological finds.", "Colloquially known as 'Good View'."],
    },
  },
  {
    id: "nohmul-ruins-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-88.55, 18.21],
    name: {
      de: "Nohmul Ruinen",
      hu: "Nohmul romok",
      ro: "Ruinele Nohmul",
      en: "Nohmul Ruins",
    },
    description: {
      de: "Eine große Maya-Stätte, deren Hauptpyramide 2013 leider zerstört wurde.",
      hu: "Nagy maja lelőhely, amelynek fő piramisát 2013-ban sajnos lerombolták.",
      ro: "Un mare sit mayaș a cărui piramidă principală a fost din păcate distrusă în 2013.",
      en: "A large Maya site whose main pyramid was unfortunately destroyed in 2013.",
    },
    facts: {
      de: ["Bedeutet 'großer Hügel'.", "Wichtiger Handels- und Zeremonialort.", "Von Zuckerrohrfeldern umgeben.", "Zerstörung löste internationale Empörung aus."],
      hu: ["Jelentése 'nagy domb'.", "Fontos kereskedelmi és szertartási hely.", "Cukornádültetvények veszik körül.", "A lerombolása nemzetközi felháborodást váltott ki."],
      ro: ["Înseamnă 'movilă mare'.", "Important centru comercial și ceremonial.", "Înconjurat de câmpuri de trestie de zahăr.", "Distrugerea a provocat indignare internațională."],
      en: ["Means 'great mound'.", "Important trade and ceremonial center.", "Surrounded by sugarcane fields.", "Its destruction caused international outrage."],
    },
  },
  {
    id: "tipu-ruins-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.15, 16.96],
    name: {
      de: "Tipu Ruinen",
      hu: "Tipu romok",
      ro: "Ruinele Tipu",
      en: "Tipu Ruins",
    },
    description: {
      de: "Eine postklassische Maya-Stätte, die für ihren Widerstand gegen die spanische Herrschaft bekannt ist.",
      hu: "Posztklasszikus maja lelőhely, amely a spanyol uralommal szembeni ellenállásáról ismert.",
      ro: "Un sit mayaș postclasic cunoscut pentru rezistența sa împotriva stăpânirii spaniole.",
      en: "A Postclassic Maya site known for its resistance against Spanish rule.",
    },
    facts: {
      de: ["Zentrum des Maya-Widerstands im 17. Jahrhundert.", "Enthält eine spanische Kolonialkirche.", "Lag an einer wichtigen Handelsroute.", "Wichtige Stätte für die Geschichte des Kontakts."],
      hu: ["A 17. századi maja ellenállás központja.", "Egy spanyol gyarmati templomot is magában foglal.", "Fontos kereskedelmi útvonalon feküdt.", "Fontos lelőhely a kapcsolatfelvétel történetében."],
      ro: ["Centrul rezistenței mayașe în secolul al XVII-lea.", "Conține o biserică colonială spaniolă.", "Situat pe o importantă rută comercială.", "Situl important pentru istoria contactului."],
      en: ["Center of Maya resistance in the 17th century.", "Contains a Spanish colonial church.", "Located on an important trade route.", "Important site for contact-period history."],
    },
  },
  {
    id: "pusilha-ruins-history-v2",
    type: "historical",
    parent: "BZ-TOL",
    coords: [-89.23, 16.21],
    name: {
      de: "Pusilha Ruinen",
      hu: "Pusilha romok",
      ro: "Ruinele Pusilha",
      en: "Pusilha Ruins",
    },
    description: {
      de: "Eine bedeutende Maya-Stätte der Klassik im tiefen Süden von Belize.",
      hu: "Jelentős klasszikus korabeli maja lelőhely Belize mély déli részén.",
      ro: "Un important sit mayaș clasic în sudul profund al Belize.",
      en: "A major Classic period Maya site in the deep south of Belize.",
    },
    facts: {
      de: ["Bekannt für eine Hängebrücke über den Moho-Fluss.", "Viele Stelen mit Inschriften.", "Wichtiges politisches Zentrum.", "Schwer zugänglich."],
      hu: ["Híres a Moho-folyón átívelő függőhídjáról.", "Sok feliratos sztélé.", "Fontos politikai központ.", "Nehezen megközelíthető."],
      ro: ["Cunoscut pentru un pod suspendat peste râul Moho.", "Multe stele cu inscripții.", "Centru politic important.", "Greu accesibil."],
      en: ["Known for a causeway-bridge across the Moho River.", "Many inscribed stelae.", "Important political center.", "Difficult to access."],
    },
  },
  {
    id: "colha-ruins-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-88.48, 17.88],
    name: {
      de: "Colha Ruinen",
      hu: "Colha romok",
      ro: "Ruinele Colha",
      en: "Colha Ruins",
    },
    description: {
      de: "Eine Maya-Stätte, die für die Massenproduktion von Steinwerkzeugen bekannt ist.",
      hu: "Maja lelőhely, amely a kőszerszámok tömegtermeléséről ismert.",
      ro: "Un sit mayaș cunoscut pentru producția în masă de unelte din piatră.",
      en: "A Maya site known for the mass production of stone tools.",
    },
    facts: {
      de: ["Hauptproduzent von Werkzeugen aus Feuerstein.", "Werkzeuge wurden in ganz Belize gehandelt.", "Besiedelt von der Frühprähistorik bis zur Postklassik.", "Funde deuten auf ein Massaker hin."],
      hu: ["A kőeszközök fő gyártója.", "Az eszközökkel egész Belize-ben kereskedtek.", "A korai prehisztorikus kortól a posztklasszikus korig lakott.", "A leletek mészárlásra utalnak."],
      ro: ["Producător major de unelte din silex.", "Uneltele erau comercializate în tot Belize.", "Locuit din preclasicul timpuriu până în postclasic.", "Descoperirile sugerează un masacru."],
      en: ["Major producer of chert stone tools.", "Tools were traded throughout Belize.", "Occupied from the Early Preclassic to Postclassic.", "Evidence of a massacre was found here."],
    },
  },
  {
    id: "indian-creek-ruin-history-v2",
    type: "historical",
    parent: "BZ-TOL",
    coords: [-88.75, 16.41],
    name: {
      de: "Indian Creek Ruine",
      hu: "Indian Creek rom",
      ro: "Ruina Indian Creek",
      en: "Indian Creek Ruin",
    },
    description: {
      de: "Eine kleine, aber gut erhaltene Maya-Zeremonialstätte im Toledo District.",
      hu: "Kicsi, de jól megőrzött maja szertartási hely a Toledo kerületben.",
      ro: "Un mic, dar bine conservat sit ceremonial mayaș în districtul Toledo.",
      en: "A small but well-preserved Maya ceremonial site in the Toledo District.",
    },
    facts: {
      de: ["Bekannt für seine zentrale Pyramide.", "Leicht zugänglich von der Southern Highway.", "Ein Beispiel für eine kleinere Maya-Gemeinde.", "Umgeben von Ackerland."],
      hu: ["Központi piramisáról ismert.", "Könnyen megközelíthető a Déli autópályáról.", "Példa egy kisebb maja közösségre.", "Szántóföldekkel körülvéve."],
      ro: ["Cunoscut pentru piramida sa centrală.", "Ușor accesibil de pe Autostrada de Sud.", "Un exemplu de comunitate mayașă mai mică.", "Înconjurat de terenuri agricole."],
      en: ["Known for its central pyramid.", "Easily accessible from the Southern Highway.", "An example of a smaller Maya community.", "Surrounded by farmland."],
    },
  },
  {
    id: "kaxil-uinic-ruins-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-89.1, 17.65],
    name: {
      de: "K'axob / Kaxil Uinic Ruinen",
      hu: "K'axob / Kaxil Uinic romok",
      ro: "Ruinele K'axob / Kaxil Uinic",
      en: "K'axob / Kaxil Uinic Ruins",
    },
    description: {
      de: "Eine prähistorische Maya-Siedlung in der Nähe von San Lazaro Village.",
      hu: "Prehisztorikus maja település a San Lazaro falu közelében.",
      ro: "O așezare mayașă preclasică lângă satul San Lazaro.",
      en: "A Preclassic Maya settlement located near San Lazaro Village.",
    },
    facts: {
      de: ["Bedeutet 'Ort der K'an-Glyphe'.", "Fontos leletek a korai falusi fejlődésről.", "Befindet sich auf Privatgrund.", "Archäologisch bedeutend."],
      hu: ["Jelentése 'a K'an-glifa helye'.", "Fontos leletek a korai falusi fejlődésről.", "Magánterületen található.", "Régészetileg jelentős."],
      ro: ["Înseamnă 'Locul Glifei K'an'.", "Descoperiri importante despre dezvoltarea timpurie a satului.", "Situat pe proprietate privată.", "Semnificativ din punct de vedere arheologic."],
      en: ["Means 'Place of the K'an Glyph'.", "Important findings on early village development.", "Located on private land.", "Archaeologically significant."],
    },
  },
  {
    id: "la-milpa-ruins-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-89.05, 17.83],
    name: {
      de: "La Milpa Ruinen",
      hu: "La Milpa romok",
      ro: "Ruinele La Milpa",
      en: "La Milpa Ruins",
    },
    description: {
      de: "Die drittgrößte Maya-Stätte in Belize, gelegen im Rio Bravo Schutzgebiet.",
      hu: "Belize harmadik legnagyobb maja lelőhelye, a Rio Bravo védett területen.",
      ro: "Al treilea cel mai mare sit mayaș din Belize, situat în zona de conservare Rio Bravo.",
      en: "The third-largest Maya site in Belize, located in the Rio Bravo Conservation Area.",
    },
    facts: {
      de: ["Drittgrößte Stätte in Belize.", "Mehr als 20 Plätze und 85 Hauptstrukturen.", "Große zentrale Plaza.", "Wichtiges Forschungszentrum."],
      hu: ["Belize harmadik legnagyobb lelőhelye.", "Több mint 20 tér és 85 fő építmény.", "Nagy központi tér.", "Fontos kutatóközpont."],
      ro: ["Al treilea cel mai mare sit din Belize.", "Peste 20 de piețe și 85 de structuri principale.", "Piața centrală mare.", "Centru de cercetare important."],
      en: ["Third-largest site in Belize.", "More than 20 plazas and 85 major structures.", "Large central plaza.", "Important research center."],
    },
  },
  {
    id: "chac-balam-ruins-history-v2",
    type: "historical",
    parent: "BZ-CZL",
    coords: [-88.0, 18.2],
    name: {
      de: "Chac Balam Ruinen",
      hu: "Chac Balam romok",
      ro: "Ruinele Chac Balam",
      en: "Chac Balam Ruins",
    },
    description: {
      de: "Eine kleine, aber strategisch gelegene Maya-Stätte an der Nordspitze von Ambergris Caye.",
      hu: "Kicsi, de stratégiailag fontos maja lelőhely az Ambergris Caye északi csücskén.",
      ro: "Un sit mayaș mic, dar strategic, la vârful nordic al Ambergris Caye.",
      en: "A small but strategic Maya site on the northern tip of Ambergris Caye.",
    },
    facts: {
      de: ["Bedeutet 'Roter Jaguar'.", "Kontrollierte den Kanal zwischen Ambergris Caye und Mexiko.", "Teil des Bacalar Chico Nationalparks.", "Nur per Boot erreichbar."],
      hu: ["Jelentése 'Vörös Jaguár'.", "Ellenőrizte az Ambergris Caye és Mexikó közötti csatornát.", "A Bacalar Chico Nemzeti Park része.", "Csak csónakkal érhető el."],
      ro: ["Înseamnă 'Jaguarul Roșu'.", "Controla canalul dintre Ambergris Caye și Mexic.", "Parte a Parcului Național Bacalar Chico.", "Accesibil doar cu barca."],
      en: ["Means 'Red Jaguar'.", "Controlled the channel between Ambergris Caye and Mexico.", "Part of the Bacalar Chico National Park.", "Accessible only by boat."],
    },
  },
  {
    id: "uxbenka-ruins-history-v2",
    type: "historical",
    parent: "BZ-TOL",
    coords: [-89.0, 16.3],
    name: {
      de: "Uxbenka Ruinen",
      hu: "Uxbenka romok",
      ro: "Ruinele Uxbenka",
      en: "Uxbenka Ruins",
    },
    description: {
      de: "Eine der ältesten Maya-Stätten im Süden von Belize, auf einem Bergrücken gelegen.",
      hu: "Az egyik legrégebbi maja lelőhely Belize déli részén, egy hegygerincen.",
      ro: "Unul dintre cele mai vechi situri mayașe din sudul Belize, situat pe o creastă.",
      en: "One of the earliest Maya sites in southern Belize, located on a ridge.",
    },
    facts: {
      de: ["Bedeutet 'alter Ort'.", "Frühe Besiedlung um 150 n. Chr.", "Bekannt für seine Stelen und Terrassen.", "Panoramablick auf die umliegende Landschaft."],
      hu: ["Jelentése 'régi hely'.", "Korai település i.sz. 150 körül.", "Sztéléiről és teraszairól ismert.", "Panorámás kilátás a környező tájra."],
      ro: ["Înseamnă 'loc vechi'.", "Așezare timpurie în jurul anului 150 d.Hr.", "Cunoscut pentru stelele și terasele sale.", "Vedere panoramică a peisajului înconjurător."],
      en: ["Means 'ancient place'.", "Early occupation around 150 AD.", "Known for its stelae and terraced platforms.", "Panoramic views of the surrounding landscape."],
    },
  },
  {
    id: "mayo-history-v2",
    type: "historical",
    parent: "BZ-TOL",
    coords: [-89.1, 16.4],
    name: {
      de: "Maya Mountain Research Farm",
      hu: "Maya Hegységi Kutatófarm",
      ro: "Ferma de Cercetare Munții Maya",
      en: "Maya Mountain Research Farm",
    },
    description: {
      de: "Eine Forschungsfarm, die sich der nachhaltigen Landwirtschaft nach Maya-Tradition widmet.",
      hu: "Kutatófarm, amely a maja hagyományokon alapuló fenntartható mezőgazdaságnak szenteli magát.",
      ro: "O fermă de cercetare dedicată agriculturii durabile în tradiția mayașă.",
      en: "A research farm dedicated to sustainable agriculture in the Maya tradition.",
    },
    facts: {
      de: ["Fokus auf Permakultur.", "Bildungszentrum für nachhaltige Praktiken.", "Im Toledo District gelegen.", "Bewahrt traditionelles Wissen."],
      hu: ["A permakultúrára összpontosít.", "Oktatási központ a fenntartható gyakorlatokért.", "A Toledo kerületben található.", "Megőrzi a hagyományos tudást."],
      ro: ["Accent pe permacultură.", "Centru educațional pentru practici durabile.", "Situat în districtul Toledo.", "Păstrează cunoștințele tradiționale."],
      en: ["Focus on permaculture.", "Educational center for sustainable practices.", "Located in the Toledo District.", "Preserves traditional knowledge."],
    },
  },
  {
    id: "forest-home-village-history-v2",
    type: "historical",
    parent: "BZ-TOL",
    coords: [-88.85, 16.15],
    name: {
      de: "Forest Home (historisch)",
      hu: "Forest Home (történelmi)",
      ro: "Forest Home (istoric)",
      en: "Forest Home (historic)",
    },
    description: {
      de: "Eine historische Siedlung, die von Konföderierten-Flüchtlingen nach dem amerikanischen Bürgerkrieg gegründet wurde.",
      hu: "Történelmi település, amelyet konföderációs menekültek alapítottak az amerikai polgárháború után.",
      ro: "O așezare istorică fondată de refugiați confederați după Războiul Civil American.",
      en: "A historic settlement founded by Confederate refugees after the American Civil War.",
    },
    facts: {
      de: ["Gegründet von Ex-Konföderierten.", "Versuch, eine neue Plantagenwirtschaft aufzubauen.", "Die meisten verließen Belize wieder.", "Einzigartiges Kapitel der Geschichte Belizes."],
      hu: ["Volt konföderációsok alapították.", "Kísérlet egy új ültetvényes gazdaság létrehozására.", "A legtöbben újra elhagyták Belize-t.", "Belize történelmének egyedi fejezete."],
      ro: ["Fondat de ex-confederați.", "Încercare de a stabili o nouă economie de plantații.", "Majoritatea au părăsit din nou Belize.", "Un capitol unic în istoria Belize."],
      en: ["Founded by ex-Confederates.", "Attempted to establish a new plantation economy.", "Most eventually left Belize.", "A unique chapter in Belizean history."],
    },
  },
  {
    id: "bake-pot-ruin-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-88.8, 17.2],
    name: {
      de: "Baking Pot Ruine",
      hu: "Baking Pot rom",
      ro: "Ruina Baking Pot",
      en: "Baking Pot Ruin",
    },
    description: {
      de: "Eine Maya-Stätte in der Nähe von Belmopan, die ein wichtiges regionales Zentrum war.",
      hu: "Maja lelőhely Belmopan közelében, amely fontos regionális központ volt.",
      ro: "Un sit mayaș lângă Belmopan, care a fost un important centru regional.",
      en: "A Maya site near Belmopan that was an important regional center.",
    },
    facts: {
      de: ["Lange Besiedlungsgeschichte.", "Lage am Belize River.", "Wichtige Zeremonialbauten.", "Heimat des Belize Valley Archaeological Reconnaissance Project."],
      hu: ["Hosszú településtörténet.", "Elhelyezkedés a Belize-folyó mentén.", "Fontos szertartási épületek.", "A Belize-völgyi Régészeti Felderítő Projekt otthona."],
      ro: ["Istorie lungă de locuire.", "Situat pe râul Belize.", "Structuri ceremoniale importante.", "Sediul Proiectului de Recunoaștere Arheologică din Valea Belize."],
      en: ["Long history of occupation.", "Located on the Belize River.", "Important ceremonial structures.", "Home to the Belize Valley Archaeological Reconnaissance Project."],
    },
  },
  {
    id: "pacbitun-ruins-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-88.9, 17.05],
    name: {
      de: "Pacbitun Ruinen",
      hu: "Pacbitun romok",
      ro: "Ruinele Pacbitun",
      en: "Pacbitun Ruins",
    },
    description: {
      de: "Eine mittelgroße Maya-Stätte in den Ausläufern der Maya Mountains.",
      hu: "Közepes méretű maja lelőhely a Maja-hegység lábánál.",
      ro: "Un sit mayaș de mărime medie la poalele Munților Maya.",
      en: "A medium-sized Maya site in the foothills of the Maya Mountains.",
    },
    facts: {
      de: ["Bedeutet 'Steine in den Himmel gesetzt'.", "Bekannt für seine vielen Stelen und Altäre.", "Wichtige Funde von Musikinstrumenten.", "Strategische Lage zwischen Hochland und Tiefland."],
      hu: ["Jelentése 'kövek az égbe helyezve'.", "Sok sztéléjéről és oltáráról ismert.", "Fontos hangszerleletek.", "Stratégiai fekvés a hegyvidék és az alföld között."],
      ro: ["Înseamnă 'pietre așezate în cer'.", "Cunoscut pentru numeroasele sale stele și altare.", "Descoperiri importante de instrumente muzicale.", "Locație strategică între zonele montane și de șes."],
      en: ["Means 'stones set in the sky'.", "Known for its many stelae and altars.", "Important musical instrument finds.", "Strategic location between highlands and lowlands."],
    },
  },
  {
    id: "negroman-ruin-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.0, 16.95],
    name: {
      de: "Negroman (Tipan Chen Uitz) Ruine",
      hu: "Negroman (Tipan Chen Uitz) rom",
      ro: "Ruina Negroman (Tipan Chen Uitz)",
      en: "Negroman (Tipan Chen Uitz) Ruin",
    },
    description: {
      de: "Eine abgelegene Maya-Stätte in den Vaca-Wäldern.",
      hu: "Elszigetelt maja lelőhely a Vaca-erdőben.",
      ro: "Un sit mayaș izolat în pădurile Vaca.",
      en: "A remote Maya site located in the Vaca forests.",
    },
    facts: {
      de: ["Alter Name Tipan Chen Uitz.", "Bedeutet 'Festung am Brunnen im Berg'.", "Große, aber wenig erforschte Stätte.", "Schwer erreichbar."],
      hu: ["Régi neve Tipan Chen Uitz.", "Jelentése 'erőd a kútnál a hegyen'.", "Nagy, de kevéssé kutatott lelőhely.", "Nehezen elérhető."],
      ro: ["Nume vechi Tipan Chen Uitz.", "Înseamnă 'fortăreață la fântâna din munte'.", "Situl mare, dar puțin explorat.", "Greu de atins."],
      en: ["Ancient name Tipan Chen Uitz.", "Means 'fortress at the well on the hill'.", "Large but little-excavated site.", "Difficult to reach."],
    },
  },
  {
    id: "spanish-church-lamanai-history-v2",
    type: "historical",
    parent: "BZ-OW",
    coords: [-88.65, 17.76],
    name: {
      de: "Spanische Kirche von Lamanai",
      hu: "Lamanai spanyol temploma",
      ro: "Biserica spaniolă din Lamanai",
      en: "Spanish Church at Lamanai",
    },
    description: {
      de: "Die Ruinen von zwei spanischen Kirchen aus dem 16. Jahrhundert, die von den Maya zerstört wurden.",
      hu: "Két 16. századi spanyol templom romjai, amelyeket a maják leromboltak.",
      ro: "Ruinele a două biserici spaniole din secolul al XVI-lea, distruse de mayași.",
      en: "The ruins of two 16th-century Spanish churches, which were destroyed by the Maya.",
    },
    facts: {
      de: ["Beweis für den spanischen Missionierungsversuch.", "Symbol des Maya-Widerstands.", "Innerhalb der Lamanai-Stätte gelegen.", "Zeigt die Überlagerung der Kulturen."],
      hu: ["A spanyol hittérítési kísérlet bizonyítéka.", "A maja ellenállás szimbóluma.", "A Lamanai lelőhelyen belül található.", "A kultúrák egymásra rétegződését mutatja."],
      ro: ["Dovadă a încercării spaniole de misionarism.", "Simbol al rezistenței mayașe.", "Situată în cadrul sitului Lamanai.", "Arată suprapunerea culturilor."],
      en: ["Evidence of the Spanish missionizing effort.", "Symbol of Maya resistance.", "Located within the Lamanai site.", "Shows the superimposition of cultures."],
    },
  },
  {
    id: "actun-balam-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-88.8, 17.3],
    name: {
      de: "Actun Balam (Jaguarpfoten-Höhle)",
      hu: "Actun Balam (Jaguár-mancs barlang)",
      ro: "Peștera Actun Balam (Gheara Jaguarului)",
      en: "Actun Balam (Jaguar Paw Cave)",
    },
    description: {
      de: "Eine archäologisch bedeutende Höhle, die für ihre Jaguarpfoten-Abdrücke bekannt ist.",
      hu: "Régészetileg jelentős barlang, amely jaguármancs-lenyomatairól ismert.",
      ro: "O peșteră importantă din punct de vedere arheologic, cunoscută pentru amprentele sale de gheare de jaguar.",
      en: "An archaeologically significant cave known for its jaguar paw prints.",
    },
    facts: {
      de: ["Bedeutet 'Jaguarpfoten-Höhle'.", "Enthält Maya-Artefakte.", "Teil des Caves Branch Höhlensystems.", "Wurde für Zeremonien genutzt."],
      hu: ["Jelentése 'Jaguár-mancs barlang'.", "Maja leleteket tartalmaz.", "A Caves Branch barlangrendszer része.", "Szertartásokra használták."],
      ro: ["Înseamnă 'Peștera Ghearei Jaguarului'.", "Conține artefacte mayașe.", "Parte a sistemului de peșteri Caves Branch.", "A fost folosită pentru ceremonii."],
      en: ["Means 'Jaguar Paw Cave'.", "Contains Maya artifacts.", "Part of the Caves Branch cave system.", "Was used for ceremonies."],
    },
  },
  {
    id: "che-chem-ha-cave-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.1, 17.0],
    name: {
      de: "Che Chem Ha Höhle",
      hu: "Che Chem Ha-barlang",
      ro: "Peștera Che Chem Ha",
      en: "Che Chem Ha Cave",
    },
    description: {
      de: "Eine Maya-Zeremonialhöhle, die mit intakten Töpferwaren gefüllt ist.",
      hu: "Maja szertartási barlang, tele ép kerámiákkal.",
      ro: "O peșteră ceremonială mayașă plină cu ceramică intactă.",
      en: "A Maya ceremonial cave filled with intact pottery.",
    },
    facts: {
      de: ["Entdeckt von einem lokalen Farmer.", "Enthält Hunderte von Maya-Keramikgefäßen.", "Die Töpfe wurden wahrscheinlich für Rituale verwendet.", "Auf Privatgrund, Führung erforderlich."],
      hu: ["Egy helyi farmer fedezte fel.", "Több száz maja kerámiaedényt tartalmaz.", "Az edényeket valószínűleg rituálékhoz használták.", "Magánterületen, vezetés szükséges."],
      ro: ["Descoperită de un fermier local.", "Conține sute de vase de ceramică mayașe.", "Vasele au fost probabil folosite pentru ritualuri.", "Pe proprietate privată, este necesar un ghid."],
      en: ["Discovered by a local farmer.", "Contains hundreds of Maya pottery vessels.", "Pots were likely used for rituals.", "On private land, requires a guide."],
    },
  },
  {
    id: "actun-loch-tunich-history-v2",
    type: "historical",
    parent: "BZ-SC",
    coords: [-88.6, 16.7],
    name: {
      de: "Actun Loch Tunich (Schwarzes Loch)",
      hu: "Actun Loch Tunich (Fekete Lyuk)",
      ro: "Actun Loch Tunich (Gaura Neagră)",
      en: "Actun Loch Tunich (Black Hole)",
    },
    description: {
      de: "Ein riesiger Karst-Sinkloch im Dschungel, das für Abseilabenteuer bekannt ist.",
      hu: "Hatalmas karsztos víznyelő a dzsungelben, amely a kötélleereszkedő kalandokról ismert.",
      ro: "O dolină carstică gigantică în junglă, cunoscută pentru aventurile de rapel.",
      en: "A giant jungle sinkhole in the karst landscape, known for rappelling adventures.",
    },
    facts: {
      de: ["Über 90 Meter tief.", "Abseilen in das Loch ist eine beliebte Touristenaktivität.", "Historisch von den Maya genutzt.", "Im Cockscomb Basin Gebiet."],
      hu: ["Több mint 90 méter mély.", "A lyukba való leereszkedés népszerű turisztikai tevékenység.", "Történelmileg a maják használták.", "A Cockscomb Basin területén."],
      ro: ["Peste 90 de metri adâncime.", "Rapelul în gaură este o activitate turistică populară.", "Folosit istoric de mayași.", "În zona Bazinului Cockscomb."],
      en: ["Over 300 feet deep.", "Rappelling into the hole is a popular tourist activity.", "Historically used by the Maya.", "In the Cockscomb Basin area."],
    },
  },
  {
    id: "minanha-ruins-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-88.9, 16.85],
    name: {
      de: "Minanha Ruinen",
      hu: "Minanha romok",
      ro: "Ruinele Minanha",
      en: "Minanha Ruins",
    },
    description: {
      de: "Eine große, aber abgelegene Maya-Stätte in den Ausläufern der Maya Mountains.",
      hu: "Nagy, de elszigetelt maja lelőhely a Maja-hegység lábainál.",
      ro: "Un sit mayaș mare, dar izolat, la poalele Munților Maya.",
      en: "A large but remote Maya site in the foothills of the Maya Mountains.",
    },
    facts: {
      de: ["Bedeutendes Zentrum in der Spätklassik.", "Wurde von Caracol beeinflusst.", "Wenig ausgegraben und erforscht.", "Schwer zugänglich."],
      hu: ["Jelentős központ a késő klasszikus korban.", "Caracol befolyásolta.", "Keveset ásatott és kutatott.", "Nehezen megközelíthető."],
      ro: ["Centru important în perioada clasică târzie.", "A fost influențat de Caracol.", "Puțin excavat și cercetat.", "Greu accesibil."],
      en: ["Major center in the Late Classic period.", "Was influenced by Caracol.", "Little excavated and researched.", "Difficult to access."],
    },
  },
  {
    id: "ix-chel-shrine-history-v2",
    type: "historical",
    parent: "BZ-CY",
    coords: [-89.0, 17.1],
    name: {
      de: "Ix Chel Schrein",
      hu: "Ix Chel szentély",
      ro: "Sanctuarul Ix Chel",
      en: "Ix Chel Shrine",
    },
    description: {
      de: "Ein moderner Schrein, der der Maya-Mondgöttin Ix Chel gewidmet ist.",
      hu: "Modern szentély, amelyet a maja holdistennőnek, Ix Chelnek szenteltek.",
      ro: "Un sanctuar modern dedicat zeiței mayașe a lunii, Ix Chel.",
      en: "A modern shrine dedicated to the Maya moon goddess, Ix Chel.",
    },
    facts: {
      de: ["Befindet sich auf dem Chaa Creek Anwesen.", "Ehrt die Göttin der Medizin und Fruchtbarkeit.", "Umgeben von einem Medizinpflanzen-Pfad.", "Verbindet alte Überzeugungen mit der Gegenwart."],
      hu: ["A Chaa Creek birtokon található.", "A gyógyítás és termékenység istennőjét tiszteli.", "Gyógynövényösvény veszi körül.", "Összeköti a régi hiedelmeket a jelennel."],
      ro: ["Situat pe proprietatea Chaa Creek.", "Onorează zeița medicinei și a fertilității.", "Înconjurat de o potecă de plante medicinale.", "Conectează credințele antice cu prezentul."],
      en: ["Located at the Chaa Creek estate.", "Honors the goddess of medicine and fertility.", "Surrounded by a medicinal plant trail.", "Connects ancient beliefs with the present."],
    },
  }
];

*/
export {};
