import fs from 'fs';

function updateFile(filePath, updates) {
  let content = fs.readFileSync(filePath, 'utf8');
  for (const [id, data] of Object.entries(updates)) {
    const idRegex = new RegExp(`id:\\s*"${id}"`);
    const match = content.match(idRegex);
    if (!match) continue;
    
    const startIdx = match.index;
    let endIdx = content.indexOf('  },', startIdx);
    if (endIdx === -1) endIdx = content.indexOf('  }', startIdx);
    if (endIdx === -1) continue;
    
    let block = content.substring(startIdx, endIdx + 4);
    
    if (data.desc) {
      block = block.replace(/ro:\s*""/, `ro: "${data.desc}"`);
    }
    
    if (data.facts) {
      // Find the factsAdvanced block within this POI block
      const faMatch = block.match(/factsAdvanced:\s*{[\s\S]*?}/);
      if (faMatch) {
        const faBlock = faMatch[0];
        const newFaBlock = faBlock.replace(/ro:\s*\[\s*\]/, `ro: [\n        "${data.facts.join('",\n        "')}"\n      ]`);
        block = block.replace(faBlock, newFaBlock);
      } else {
        // If factsAdvanced is completely missing, add it
        block = block.replace(/facts:\s*{[\s\S]*?},/, (m) => {
          return m + `\n    factsAdvanced: {\n      de: [],\n      hu: [],\n      ro: [\n        "${data.facts.join('",\n        "')}"\n      ],\n      en: []\n    },`;
        });
      }
    }
    
    content = content.substring(0, startIdx) + block + content.substring(startIdx + block.length);
  }
  fs.writeFileSync(filePath, content);
}

const hu1 = {
  "geo-kiskunsagi-nemzeti-park-extra": { facts: ["Parcul Național Kiskunság a fost înființat în 1975 și este situat între fluviile Dunărea și Tisa.", "Acesta protejează peisaje variate, de la dune de nisip mișcătoare până la zone umede și saline.", "Parcul este renumit pentru 'puszta' (stepa) maghiară, un ecosistem unic în Europa.", "Aici pot fi observate specii rare de păsări, cum ar fi dropia, cea mai mare pasăre zburătoare din regiune.", "Vizitatorii pot asista la spectacole de echitație tradițională oferite de 'csikós' (păstori de cai).", "Rezervația Biosferei UNESCO include zonele de la Bugac și Fülöpháza.", "Canalele și lacurile saline adăpostesc colonii importante de păsări migratoare în timpul primăverii.", "Centrul de vizitare din Kecskemét oferă informații detaliate despre conservarea naturii în regiune."] },
  "geschichte-cifrapalota-extra": { facts: ["Cifrapalota (Palatul Cifrat) din Kecskemét este un exemplu remarcabil al stilului Secession maghiar.", "Construită în 1902, clădirea impresionează prin fațada sa decorată cu ceramică colorată Zsolnay.", "Motivele ornamentale sunt inspirate din folclorul maghiar, reprezentând flori și păuni.", "Inițial, clădirea a servit drept sediu administrativ și locuințe pentru oficialii orașului.", "Astăzi, palatul găzduiește Galeria de Artă din Kecskemét, cu o colecție valoroasă de pictură.", "Acoperișul este decorat cu elemente de ceramică smălțuită care strălucesc în soare.", "Interiorul păstrează detalii arhitecturale originale, inclusiv vitralii și tâmplărie sculptată.", "Este considerat unul dintre cele mai frumoase și fotografiate monumente din centrul orașului."] },
  "geschichte-kiskun-muzeum-extra": { facts: ["Muzeul Kiskun din Kiskunfélegyháza prezintă istoria și cultura regiunii Cumania Mică.", "Clădirea muzeului este un fost sediu al căpităniei cumane, construit în secolul al XVIII-lea.", "Curtea muzeului adăpostește o moară de vânt istorică, mutată aici pentru a fi conservată.", "Colecția de etnografie cuprinde obiecte de uz casnic și unelte folosite de păstorii din puszta.", "Muzeul deține o expoziție unică despre viața și faptele haiducilor locali celebri.", "O secțiune specială este dedicată arheologiei, cu descoperiri din epoca migrațiilor.", "Instituția poartă numele de 'Kiskun' în onoarea populației cumane care s-a stabilit aici în evul mediu.", "Grădina muzeului este un spațiu liniștit unde se organizează evenimente culturale în aer liber."] },
  "city-gyomaendrod-extra": { facts: ["Gyomaendrőd este un oraș situat pe malul Crișului Triplu, renumit pentru apele sale termale.", "Orașul s-a format prin unirea localităților Gyoma și Endrőd în anul 1982.", "Este o destinație populară pentru pescuit, datorită numeroaselor brațe moarte ale râului.", "Băile Termale Liget oferă ape curative recomandate pentru afecțiuni reumatice.", "Muzeul Imprimeriei Kner prezintă tradiția tipografică de peste un secol a familiei Kner.", "Podurile de peste Criș oferă vederi pitorești și sunt locuri preferate de plimbare.", "Orașul găzduiește anual Festivalul Internațional de Gastronomie din Gyomaendrőd.", "Regiunea este bogată în păduri inundabile și arii naturale protejate, ideale pentru ecoturism."] },
  "geschichte-wenckheim-kastely-extra": { facts: ["Castelul Wenckheim din Szabadkígyós este unul dintre cele mai frumoase edificii neorenascentiste din Ungaria.", "Proiectat de celebrul arhitect Miklós Ybl, castelul a fost finalizat în anul 1879.", "Clădirea are 365 de ferestre, 52 de camere și 12 intrări, simbolizând zilele, săptămânile și lunile anului.", "Parcul castelului este un monument peisagistic deosebit, cu un lac și arbori rari.", "Interiorul a fost recent restaurat și găzduiește o expoziție interactivă despre viața familiei nobiliare.", "Castelul dispune de o scară monumentală și de o bibliotecă ce păstrează atmosfera de epocă.", "În timpul verii, curtea castelului este scena unor concerte și evenimente de înaltă ținută.", "Fundația castelului este situată într-o zonă naturală protejată, oferind liniște și aer curat."] },
  "geschichte-geotermikus-kozpont-extra": { facts: ["Centrul Geotermic din județul Békés utilizează resursele naturale bogate de apă caldă din subsol.", "Ungaria deține una dintre cele mai mari rezerve de energie geotermală din Europa Centrală.", "Sistemul este folosit pentru încălzirea locuințelor și a serelor agricole din regiune.", "Utilizarea energiei geotermale reduce semnificativ emisiile de carbon ale comunităților locale.", "Centrul oferă și posibilități de cercetare pentru studenții din domeniul energiei regenerabile.", "Apa geotermală este extrasă de la adâncimi de peste 2.000 de metri, având temperaturi ridicate.", "Investițiile recente au modernizat rețeaua de distribuție pentru o eficiență maximă.", "Regiunea este un exemplu de bune practici în tranziția către o economie sustenabilă."] },
  "geschichte-edelenyi-kastelysziget-extra": { facts: ["Insula Castelului din Edelény este un complex baroc unic situat pe malul râului Bódva.", "Castelul L'Huillier-Coburg este al șaptelea ca mărime din Ungaria și impresionează prin frescele sale.", "Frescele din interior, realizate de pictorul Lieb Ferenc, sunt considerate cele mai frumoase picturi baroce laice.", "După o restaurare masivă, complexul a devenit un centru cultural și turistic major în nordul țării.", "Grădinile castelului au fost reamenajate pentru a reflecta designul peisagistic original.", "Insula oferă un cadru pitoresc pentru plimbări și activități de recreere în natură.", "Muzeul interactiv prezintă istoria castelului prin intermediul tehnologiilor digitale moderne.", "Este o destinație populară pentru evenimente corporate și nunți, datorită atmosferei sale elegante."] },
  "city-szentes-extra": { facts: ["Szentes este cunoscut drept 'orașul apelor și al legumelor', fiind renumit pentru agricultura în sere.", "Este unul dintre cele mai importante centre de utilizare a energiei geotermale în agricultură.", "Muzeul Koszta József deține o colecție valoroasă de pictură maghiară și piese de etnografie.", "Pârâul Kurca șerpuiește prin oraș, oferind locuri ideale pentru plimbări cu barca.", "Băile Termale din Szentes oferă o piscină acoperită de o cupolă de lemn unică în țară.", "Orașul are o tradiție lungă în polo pe apă, echipa locală fiind recunoscută la nivel național.", "Biserica Reformată din centrul orașului este una dintre cele mai mari clădiri de acest tip din regiune.", "Anual se organizează festivalul 'Zilele Szentes', celebrând tradițiile locale și gastronomia."] },
  "geo-maros-folyo-extra": { facts: ["Râul Mureș (Maros) izvorăște din munții Hășmașu Mare din România și se varsă în Tisa, lângă Szeged.", "Este unul dintre cele mai importante cursuri de apă din bazinul Carpatic, având o lungime de 761 km.", "Râul a fost folosit din antichitate pentru transportul sării și al lemnului din Transilvania.", "În Ungaria, Mureșul formează granița naturală pe o scurtă porțiune între județele Csongrád și Békés.", "Lunca Mureșului este o arie protejată, adăpostind specii rare de amfibieni și păsări de apă.", "Râul este renumit pentru nisipul său fin, colectat în trecut pentru diverse scopuri industriale.", "În timpul verii, nivelul apei permite practicarea canotajului și a altor sporturi nautice ușoare.", "Delta Mureșului de la vărsarea în Tisa este un punct critic pentru biodiversitatea regională."] },
  "geschichte-opusztaszer-extra": { facts: ["Parcul Național de Istorie din Ópusztaszer comemorează așezarea maghiarilor în bazinul Carpatic.", "Principala atracție este panorama Feszty, o pictură circulară monumentală ce înfățișează sosirea maghiarilor.", "Situl este considerat locul primei adunări legislative a maghiarilor, condusă de Árpád.", "Skanzenul (muzeul satului) din incintă prezintă viața rurală din regiunea Tisei de la sfârșitul secolului XIX.", "În parc se află numeroase monumente sculptate, inclusiv statuia monumentală a lui Árpád.", "Vizitatorii pot vedea prezentări de tir cu arcul călare și alte demonstrații de abilități nomade.", "Mănăstirea medievală excavată oferă indicii prețioase despre istoria religioasă timpurie a țării.", "Evenimentele organizate aici, precum Ziua de Rusalii, atrag zeci de mii de turiști în fiecare an."] },
  "city-bicske-extra": { facts: ["Bicske este situat în bazinul Zámoly, fiind un important nod de transport între Budapesta și Viena.", "Castelul Batthyány din oraș este un edificiu baroc superb, înconjurat de un parc dendrologic.", "Observatorul astronomic fondat de contele Károly Batthyány a fost unul dintre primele din țară.", "Orașul are o istorie bogată care datează încă din epoca romană, fiind situat pe ruta 'Via Magna'.", "Bicske este renumit pentru producția sa de vinuri în microregiunea înconjurătoare.", "Biserica romano-catolică Sfânta Treime este un monument baroc valoros din centrul localității.", "În apropiere se află dealurile Vértes, oferind numeroase trasee pentru drumeții și ciclism.", "Orașul joacă un rol activ în regiunea economică a Budapestei, găzduind centre logistice moderne."] },
  "geo-velencei-hegyseg-extra": { facts: ["Munții Velence sunt printre cei mai vechi munți din Ungaria, fiind formați din roci magmatice (granit).", "Cel mai înalt vârf este Meleg-hegy, având o altitudine de 352 de metri.", "Munții sunt celebri pentru 'pietrele mișcătoare' (ingókövek), formațiuni de granit modelate de eroziune.", "Regiunea este ideală pentru drumeții ușoare și oferă panorame superbe asupra lacului Velence.", "Solul de granit favorizează viticultura, vinurile locale fiind recunoscute pentru mineralitatea lor.", "Flora este diversă, incluzând specii rare care preferă solurile acide și însorite.", "Zona este bogată în cariere de piatră istorice, unele dintre ele fiind astăzi monumente naturale.", "Pâraiele care izvorăsc din acești munți alimentează lacul Velence situat la poale."] },
  "geschichte-pazmand-vizimalom-extra": { facts: ["Moara de apă din Pázmánd este un monument tehnic restaurat, situat pe malul pârâului Vereb.", "Aceasta reflectă tradiția morăritului în județul Fejér, fiind una dintre puținele mori rămase.", "Clădirea morii a fost consolidată și transformată într-un spațiu de expoziție și evenimente.", "Vizitatorii pot observa mecanismul original al morii și pot învăța despre tehnica măcinării tradiționale.", "Pázmánd este situat la poalele munților Velence, oferind un cadru natural pitoresc.", "Moara servește ca punct de oprire pentru turiștii care explorează regiunea viticolă locală.", "În incintă se organizează ateliere de coacere a pâinii, folosind metode străvechi.", "Este un simbol al conservării patrimoniului industrial rural din Ungaria."] },
  "geschichte-taci-gorsium-extra": { facts: ["Gorsium (Tác) este cea mai mare așezare romană excavată din Ungaria, situată în județul Fejér.", "Orașul a fost un important centru religios și administrativ al provinciei Pannonia.", "Parcul arheologic se întinde pe 200 de hectare, prezentând temple, bazilici și forumuri.", "Anual, aici se organizează festivalul 'Ludi Romani', care readuce la viață atmosfera antichității.", "Grădina de statui expune replici și piese originale de sculptură romană găsite la fața locului.", "Zidurile de incintă și porțile orașului au fost parțial reconstruite pentru a arăta grandoarea de odinioară.", "Gorsium a servit și ca centru pentru cultul imperial al provinciei în secolele II-III d.Hr.", "Teatrul în aer liber din incintă găzduiește spectacole de dramă antică în fiecare vară."] },
  "city-csorna-extra": { facts: ["Csorna este situat în inima regiunii Rábaköz, fiind un nod feroviar și rutier strategic.", "Abația Premonstratensă din oraș este un reper spiritual și arhitectural major al regiunii.", "Muzeul Csornai prezintă bogata cultură populară a regiunii Rábaköz, renumită pentru broderiile sale.", "În centrul orașului se află o piață spațioasă, dominată de clădiri istorice și monumente.", "Csorna este poarta de intrare către Parcul Național Fertő-Hanság dinspre sud.", "Industria locală include prelucrarea alimentelor și producția de utilaje agricole.", "Orașul găzduiește evenimente folclorice periodice unde se poartă costumele tradiționale locale.", "Tradiția cavalerească este celebrată anual prin concursuri de echitație și parade."] },
  "geschichte-eszterhazy-kastely-extra": { facts: ["Castelul Esterházy din Fertőd este supranumit 'Versailles-ul Ungariei' datorită grandorii sale baroce.", "Aici a locuit și a compus celebrul compozitor Joseph Haydn timp de aproape 30 de ani.", "Castelul are 126 de camere, fiind cel mai mare și mai fastuos palat baroc din țară.", "Sala de spectacole a castelului era renumită în secolul al XVIII-lea pentru acustica și decorul său.", "Grădinile castelului includ o rozărie spectaculoasă și alei mărginite de statui mitologice.", "După restaurări recente, castelul și-a recăpătat strălucirea de pe vremea prințului Miklós 'cel Strălucitor'.", "Muzeul castelului prezintă obiecte de artă, mobilier original și istoria faimoasei familii Esterházy.", "Anual se organizează festivalul internațional 'Zilele Muzicale Haydn' în sălile palatului."] },
  "geo-nagyerdo-extra": { facts: ["Nagyerdő (Pădurea Mare) din Debrecen a fost prima arie naturală protejată din Ungaria (1939).", "Este un parc urban vast, oferind posibilități de recreere, sport și contact cu natura.", "Pădurea adăpostește stejari seculari și o biodiversitate bogată, chiar în interiorul orașului.", "În incinta Nagyerdő se află Universitatea din Debrecen, Grădina Zoologică și Grădina Botanică.", "Turnul de Apă din Nagyerdő este un monument industrial transformat în centru de vizitare și belvedere.", "Stadionul Nagyerdei, unul dintre cele mai moderne din țară, este integrat armonios în peisajul pădurii.", "Lacul Békás este un loc preferat pentru plimbări și picnicuri în familie.", "Parcul găzduiește numeroase festivaluri, inclusiv celebrul Carnaval al Florilor din august."] },
  "geschichte-debreceni-reformatus-nagytemplom-extra": { facts: ["Marea Biserică Reformată din Debrecen este simbolul orașului și al protestantismului maghiar.", "În anul 1849, Lajos Kossuth a proclamat aici Declarația de Independență a Ungariei față de Austria.", "Clădirea neoclasică actuală a fost construită la începutul secolului al XIX-lea, având două turnuri masive.", "Biserica are o capacitate de 3.000 de locuri, fiind cea mai mare biserică protestantă din țară.", "Orga bisericii este celebră pentru sunetul său și este folosită des în concerte de muzică sacră.", "Vizitatorii pot urca în turnul vestic pentru o vedere panoramică asupra întregului oraș.", "Muzeul din interior prezintă istoria bisericii și Biblia de la Vizsoly, prima traducere integrală în maghiară.", "Este un monument istoric de importanță națională, fiind nucleul spiritual al 'Romei Calvine'."] },
  "geschichte-hortobagyi-kilenclyuku-hid-extra": { facts: ["Podul cu Nouă Găuri din Hortobágy este cel mai lung pod de piatră rutier din Ungaria.", "Finalizat în anul 1833, podul a înlocuit o structură mai veche de lemn afectată de inundații.", "Construcția din piatră de carieră și cărămidă are o lungime totală de 167 de metri.", "Podul a facilitat transportul animalelor către târgurile mari din centrul țării.", "Este simbolul cel mai cunoscut al Parcului Național Hortobágy și al peisajului de puszta.", "Anual, în jurul podului se organizează Târgul de la Pod, o tradiție care datează de secole.", "Arhitectura sa arcuită se reflectă în apele râului Hortobágy, creând imagini memorabile.", "În timpul celui de-al Doilea Război Mondial, podul a fost salvat de la distrugere prin minune."] },
  "city-fuzesabony-extra": { facts: ["Füzesabony este un important nod feroviar în nord-estul Ungariei, legând Budapesta de Miskolc și Eger.", "Gara orașului este o clădire istorică impunătoare, proiectată de celebrul arhitect Ferenc Pfaff.", "Orașul este situat într-o zonă cu bogate descoperiri arheologice din epoca bronzului.", "Numele localității provine de la arborii de salcie (füzes) care se găseau în abundență în zonă.", "În apropiere se află lacurile piscicole din regiunea Heves, ideale pentru observarea păsărilor.", "Füzesabony joacă un rol vital în logistica regională, găzduind centre de distribuție.", "Biserica catolică din oraș este un monument arhitectural semnificativ, ridicat în stil baroc.", "Orașul este o poartă de acces către stațiunile balneare din județul Heves."] },
  "geschichte-egri-bazilika-extra": { facts: ["Bazilica din Eger este a doua biserică ca mărime din Ungaria, după cea din Esztergom.", "Construită în stil neoclasic între 1831 și 1837, clădirea are o prezență monumentală.", "Fațada bisericii este decorată cu statui colosale ale sfinților Ștefan, Ladislau, Petru și Pavel.", "Interiorul impresionează prin frescele de pe cupolă și prin altarul sculptat cu măiestrie.", "Orga bazilicii, construită în secolul al XIX-lea, este una dintre cele mai mari din țară.", "Bazilica adăpostește sediul Arhiepiscopiei romano-catolice de Eger.", "Piața din fața bisericii este un spațiu vast, deschis, care pune în valoare arhitectura edificiului.", "Anual se organizează numeroase festivaluri de coruri și concerte de orgă internaționale."] },
  "geo-tisza-to-extra": { facts: ["Lacul Tisa este cel mai mare lac artificial din Ungaria, creat prin bararea râului Tisa în anii '70.", "Este o destinație majoră pentru ecoturism, având un labirint de canale, insule și stufărișuri.", "Ecucentrul Lacului Tisa din Poroszló găzduiește cel mai mare acvariu de apă dulce din Europa.", "Lacul face parte din Patrimoniul Mondial UNESCO datorită diversității sale biologice.", "Vizitatorii pot parcurge trasee educative pe poduri de lemn care traversează zonele de mlaștină.", "Lacul este ideal pentru canotaj, pescuit și observarea păsărilor rare precum egreta mare.", "Stațiunile din jurul lacului oferă plaje amenajate și facilități pentru sporturi nautice.", "Iarna, suprafața lacului îngheață adesea, oferind un peisaj alb spectaculos."] },
  "geschichte-szolnoki-muvesztelep-extra": { facts: ["Colonia de Artiști din Szolnok este cea mai veche și mai activă instituție de acest tip din Ungaria.", "Înființată în anul 1902, colonia a devenit un centru important al picturii realiste maghiare.", "Clădirea principală este situată pe malul Tisei, într-un parc plin de liniște și inspirație.", "Mari pictori maghiari, precum Adolf Fényes, au trăit și au lucrat între zidurile coloniei.", "Astăzi, colonia găzduiește expoziții de artă contemporană și oferă ateliere pentru tinerii artiști.", "Regiunea Tisei a oferit subiecte inepuizabile pentru pictura de peisaj locală.", "Instituția colaborează cu muzee de renume pentru promovarea artei plastice naționale.", "Fiecare an, colonia organizează simpozioane și cursuri deschise publicului pasionat de artă."] },
  "geschichte-tiszaderzs-romtemplom-extra": { facts: ["Ruinele bisericii din Tiszaderzs reprezintă o mărturie a arhitecturii religioase medievale din secolul al XIII-lea.", "Biserica a fost abandonată în timpul invaziei turcești, rămânând de atunci o ruină pitorească.", "Zidurile de piatră păstrează elemente specifice stilului romanic târziu și gotic timpuriu.", "Situl este un punct de atracție pentru turiștii care vizitează regiunea lacului Tisa.", "Excavațiile arheologice au scos la lumină morminte vechi și fragmente de decorațiuni interioare.", "Localitatea Tiszaderzs are o istorie lungă, fiind strâns legată de cursul râului Tisa.", "Ruina este un subiect preferat pentru fotografi, mai ales în lumina apusului.", "Comunitatea locală depune eforturi pentru conservarea acestui monument istoric rar."] },
  "city-dorog-extra": { facts: ["Dorog este un oraș cu o puternică tradiție minieră, situat la poalele munților Pilis.", "Timp de peste un secol, exploatarea cărbunelui a fost motorul principal al dezvoltării orașului.", "Muzeul Mineritului din localitate prezintă istoria industrială și tehnica extracției subterane.", "Dorog este renumit și pentru viața sa sportivă, în special pentru echipa locală de fotbal.", "Lacul Lupa, format într-o fostă carieră, este o zonă de agrement apreciată în apropiere.", "Orașul găzduiește numeroase monumente care amintesc de sacrificiul și munca minerilor.", "Poziția sa lângă Budapesta și Esztergom face din Dorog un nod de transport regional.", "Regiunea înconjurătoare oferă trasee montane superbe spre peșterile din Pilis."] },
  "city-orosz lany-extra": { facts: ["Oroszlány este un oraș industrial situat la vest de munții Vértes, faimos pentru minele sale.", "Numele orașului s-ar traduce prin 'Piatra Rusului', având rădăcini istorice slave.", "Turnul de răcire al vechii centrale electrice este un punct de reper vizual al orașului.", "Localitatea a cunoscut o expansiune rapidă în perioada socialistă, datorită industriei grele.", "În apropiere se află satul de mănăstiri kamaldulense de la Majk, un sit istoric de excepție.", "Lacul Bokod, aflat lângă oraș, este renumit pentru 'satul plutitor' de case de pescari.", "Oroszlány oferă acces rapid către zonele de drumeție ale Rezervației Naturale Vértes.", "Muzeul Mineritului din oraș prezintă o colecție impresionantă de utilaje grele folosite în trecut."] },
  "geo-gerecse-extra": { facts: ["Munții Gerecse sunt renumiți pentru zăcămintele lor de calcar roșu, folosit în arhitectura regală.", "Cel mai înalt punct al masivului este vârful Nagy-Gerecse, având 633 de metri.", "Munții adăpostesc numeroase peșteri spectaculoase, un paradis pentru speologi.", "Flora zonei include specii rare de orhidee și plante adaptate la solul calcaros.", "Regiunea este un punct critic pentru migrația păsărilor răpitoare în Europa Centrală.", "Zidurile stâncoase sunt căutate de alpiniști pentru traseele lor de cățărare tehnică.", "Numeroase situri preistorice au fost descoperite aici, inclusiv peștera de la Tata.", "Drumețiile în Gerecse oferă vederi spectaculoase asupra Dunării și a văii Dorog."] },
  "geschichte-turul-emlekmu-extra": { facts: ["Monumentul Turul din Tatabánya este cea mai mare statuie de pasăre din Europa Centrală.", "Statuia a fost ridicată în 1907 pentru a marca împlinirea a 1000 de ani de la venirea maghiarilor.", "Turul este pasărea mitologică a maghiarilor, simbol al puterii și al originii divine.", "Monumentul este situat pe marginea unui abrupt calcaros al munților Gerecse, vizibil de departe.", "Anvergura aripilor păsării de bronz este de aproape 15 metri.", "De la picioarele monumentului se deschide o panoramă uluitoare asupra orașului Tatabánya.", "Situl este legat de legende care vorbesc despre bătălii glorioase ale maghiarilor în această zonă.", "În apropiere se află Peștera Szelim, un alt punct de interes turistic major."] },
  "geschichte-tatai-var-extra": { facts: ["Cetatea din Tata este o fortificație superbă situată pe malul lacului Vechi (Öreg-tó).", "Construită în secolul al XIV-lea, cetatea a fost reședința preferată a regelui Sigismund de Luxemburg.", "Arhitectura actuală păstrează elemente gotice, renascentiste și baroce, fiind parțial restaurată.", "Cetatea a servit drept punct defensiv cheie împotriva otomanilor în secolul al XVI-lea.", "Muzeul Kuny Domokos din interior prezintă istoria orașului și a faimoasei ceramici de Tata.", "Sistemul de șanțuri cu apă care înconjoară cetatea este încă funcțional, fiind alimentat de lac.", "Terasa castelului oferă un loc romantic pentru plimbări cu vedere spre apele lacului.", "Anual, în curtea cetății se organizează festivaluri medievale și concerte de vară."] },
  "city-paszto-extra": { facts: ["Pásztó este un oraș istoric situat la poalele munților Mátra, în valea râului Zagyva.", "Localitatea a fost un important centru religios și administrativ în perioada medievală.", "Mănăstirea Cisterciană din Pásztó este un monument de o valoare inestimabilă.", "Centrul istoric păstrează clădiri medievale și baroce care emană o atmosferă arhaică.", "Muzeul orașului prezintă istoria morăritului și viața călugărilor cistercieni.", "Pásztó este o bază ideală pentru explorarea crestelor vestice ale masivului Mátra.", "Orașul este renumit pentru tradițiile sale viticole, fiind parte dintr-o regiune istorică.", "În apropiere se află lacul de acumulare Hasznos, un loc pitoresc pentru pescuit."] },
  "geo-karanc-extra": { facts: ["Muntele Karancs este supranumit 'Olimpul regiunii Palóc', situat la granița cu Slovacia.", "Vârful cel mai înalt atinge 729 de metri și oferă o panoramă vastă asupra Slovaciei Centrale.", "Masivul este acoperit de păduri de foioase dense, fiind o arie naturală protejată.", "Turnul de belvedere de pe vârf permite observarea munților Tatra în zilele foarte senine.", "Muntele este format din roci vulcanice (andezit), având o geologie complexă.", "Traseele de drumeție sunt abrupte și provocatoare, fiind apreciate de excursioniștii experimentați.", "În versanții muntelui se găsesc izvoare cu apă cristalină care alimentează pâraiele locale.", "Localitatea Salgótarján se află chiar la poalele acestui masiv impunător."] },
  "geschichte-somoskoi-var-extra": { facts: ["Cetatea Somoskő este o fortificație medievală situată spectaculos pe o stâncă de bazalt.", "Deși zidurile cetății se află pe teritoriul Slovaciei, localitatea Somoskő aparține Ungariei.", "Lângă cetate se află faimoasa cascadă de bazalt, un fenomen geologic rar cu coloane hexagonale.", "Cetatea a fost construită în secolul al XIII-lea pentru a supraveghea drumurile spre nord.", "În secolul al XVI-lea, cetatea a fost un punct de frontieră important în lupta cu turcii.", "Situl a fost locul de inspirație pentru numeroși poeți, inclusiv pentru Bálint Balassi.", "Turnurile cilindrice ale cetății au fost restaurate, oferind un aspect medieval autentic.", "Accesul la cetate se face printr-un drum pietruit ce pleacă din centrul satului Somoskő."] },
  "geschichte-szandavari-varrom-extra": { facts: ["Ruinele cetății Szandavár se află pe un vârf de andezit abrupt din munții Cserhát.", "Construită după invazia tătară, cetatea a avut o poziție strategică de control vizual.", "Istoria cetății este marcată de lupte eroice și de o explozie a depozitului de praf de pușcă în 1551.", "De pe platoul cetății se oferă una dintre cele mai frumoase vederi asupra dealurilor Nógrád.", "Traseul spre ruine trece prin zone naturale de o frumusețe sălbatică și liniște deplină.", "Săpăturile au scos la lumină fragmente de ziduri groase și baze de turnuri medievale.", "Szandavár este o destinație populară pentru Turul Albastru Național al Ungariei.", "Locul este învăluit în numeroase legende locale despre cavaleri și prințese captive."] },
  "city-rackeve-extra": { facts: ["Ráckeve este situat pe brațul Soroksár al Dunării, având o atmosferă venețiană.", "Biserica Ortodoxă Sârbă din oraș este singura biserică gotică sârbă din Ungaria.", "Castelul Savoyai este o bijuterie barocă, construit de celebrul general Eugeniu de Savoia.", "Orașul este un paradis pentru pescari și pentru amatorii de sporturi nautice pe brațul liniștit.", "Piața de miercuri și sâmbătă de pe malul apei este o tradiție colorată și foarte vizitată.", "Turnul primăriei oferă o panoramă superbă asupra meandrelor Dunării.", "Ráckeve are o istorie multietnică, fiind populat de-a lungul secolelor de sârbi, germani și maghiari.", "Băile termale din oraș oferă relaxare modernă într-un cadru natural de excepție."] },
  "city-nagymaros-extra": { facts: ["Nagymaros este un oraș pitoresc situat în Cotul Dunării, vizavi de cetatea Visegrád.", "Faleza Dunării din Nagymaros oferă una dintre cele mai iconice vederi panoramice din Ungaria.", "Orașul este un centru important pentru turismul activ: drumeții, ciclism și canotaj.", "Biserica romano-catolică Sfânta Cruce datează din secolul al XIV-lea, fiind un monument gotic.", "Anual, orașul găzduiește Festivalul de Muzică și Artă Populară de la malul Dunării.", "Nagymaros este o oprire obligatorie pe traseul internațional de ciclism EuroVelo 6.", "Pădurile muntoase de deasupra orașului fac parte din Parcul Național Dunăre-Ipoly.", "Piața locală de sâmbătă este renumită pentru produsele bio și atmosfera relaxată."] },
  "geo-duna-kanyar-extra": { facts: ["Cotul Dunării (Dunakanyar) este una dintre cele mai frumoase și turistice regiuni ale Ungariei.", "Fluviul își schimbă direcția de curgere cu aproape 90 de grade, străpungând munții Pilis și Visegrád.", "Regiunea cuprinde orașe istorice emblematice precum Esztergom, Visegrád și Szentendre.", "Peisajul oferă o combinație spectaculoasă de culmi muntoase, ape line și monumente istorice.", "Zona este protejată în cadrul Parcului Național Dunăre-Ipoly, fiind bogată în specii endemice.", "Numeroase cetăți și bastioane de observație sunt cocoțate pe înălțimile care domină fluviul.", "Transportul cu vaporașul de croazieră este modalitatea preferată a turiștilor pentru a vedea cotul.", "Iarna, ceața care se ridică deasupra apei creează peisaje mistice, căutate de pictori și fotografi."] },
  "geschichte-vac-dom-extra": { facts: ["Catedrala din Vác (Domul) este unul dintre cele mai importante monumente neoclasice din Ungaria.", "Ridicată în secolul al XVIII-lea, biserica impresionează prin fațada sa cu coloane corintice.", "Fresca uriașă de pe cupolă, operă a pictorului Franz Anton Maulbertsch, este o capodoperă barocă.", "Catedrala adăpostește relicve valoroase și este centrul Diecezei de Vác.", "În cripta domului se află mormintele episcopilor care au ctitorit clădiri importante în oraș.", "Piața Konstantin, unde se află catedrala, este una dintre cele mai armonioase piețe baroce din țară.", "Turnurile gemene ale domului domină silueta orașului de pe malul Dunării.", "Acustica interioară este deosebită, găzduind frecvent concerte de cor și muzică clasică."] },
  "geo-zselic-extra": { facts: ["Zselic este o regiune colinară pitorească situată în județul Somogy, renumită pentru pădurile sale.", "Zona a fost desemnată 'Parc de Cer Întunecat', având una dintre cele mai mici poluări luminoase.", "Pădurile de fag și carpen acoperă cea mai mare parte a teritoriului, oferind un aer curat.", "Observatorul Astronomic din Zselic este un punct de atracție pentru iubitorii de stele.", "Regiunea este bogată în vânat, fiind o destinație tradițională pentru vânătoarea responsabilă.", "Satele răsfirate printre dealuri păstrează o arhitectură rurală autentică și tradiții vechi.", "Solul și clima favorizează cultivarea pomilor fructiferi și a viței de vie pe versanții sudici.", "Traseele de drumeție din Zselic sunt liniștite și ideale pentru cei care caută solitudinea în natură."] },
  "geschichte-szantodpuszta-extra": { facts: ["Szantódpuszta este un complex muzeal în aer liber care păstrează atmosfera unei ferme nobiliare.", "Situat pe malul sudic al Balatonului, complexul cuprinde peste 30 de clădiri istorice.", "Conacul central și anexele gospodărești datează în mare parte din secolele XVIII-XIX.", "Vizitatorii pot vedea ateliere de fierărie, mori și grajduri restaurate cu grijă.", "Situl a fost distins cu premiul 'Europa Nostra' pentru calitatea conservării patrimoniului.", "Anual se organizează târguri de meșteșuguri și demonstrații de echitație tradițională.", "Capela barocă Sfântul Cristofor de pe deal oferă o vedere superbă asupra peninsulei Tihany.", "Este un loc ideal pentru a învăța despre istoria agriculturii și a vieții sociale din regiunea Balaton."] },
  "geschichte-somogyvar-extra": { facts: ["Somogyvár a fost un centru religios și administrativ major în perioada regatului maghiar timpuriu.", "Aici a fost fondată în 1091 de regele Ladislau cel Sfânt o abbație benedictină monumentală.", "Ruinele mănăstirii arată că aceasta era una dintre cele mai mari și moderne din Europa acelei vremi.", "Centrul de vizitare modern prezintă istoria abbației prin reconstituiri 3D și artefacte excavate.", "Situl este un loc memorial național, celebrând moștenirea spirituală a Sfântului Ladislau.", "Zidurile masive din piatră păstrate până astăzi demonstrează puterea economică a ordinului.", "De pe turnul de observație adiacent se pot vedea dealurile Somogy și lacul Balaton.", "Săpăturile arheologice continuă să scoată la lumină detalii despre viața monahală medievală."] },
  "city-fehergyarmat-extra": { facts: ["Fehérgyarmat este centrul cultural și economic al regiunii Szatmár, situat lângă râul Someș.", "Orașul este renumit pentru biserica sa reformată cu tavan pictat în stil popular.", "Regiunea înconjurătoare este celebră pentru livezile de prune și pentru palinca de Szatmár.", "Localitatea are o istorie de peste 700 de ani, fiind menționată prima dată în 1327.", "Fiecare an, orașul găzduiește festivalul 'Szatmári Fesztivál', celebrând tradițiile locale.", "Fehérgyarmat este o bază excelentă pentru explorarea bisericilor medievale de lemn din zonă.", "Economia locală se bazează pe prelucrarea alimentelor și pe industria textilă.", "În apropiere se află confluența râurilor Someș, Tisa și Tur, un ecosistem natural bogat."] },
  "city-ujfeherto-extra": { facts: ["Újfehértó este un oraș situat în inima regiunii Szabolcs, renumit pentru livezile sale de vișini.", "Soiul de vișine 'Újfehértói fürtös' este recunoscut la nivel internațional pentru calitatea sa.", "Orașul s-a dezvoltat ca un centru agricol important pe ruta istorică spre Transilvania.", "Biserica Reformată din oraș este un edificiu impunător cu un turn înalt, vizibil de departe.", "Muzeul local prezintă istoria agriculturii și a comunității evreiești care a trăit aici.", "Localitatea dispune de un lac de agrement apreciat de localnici pentru pescuit și relaxare.", "Újfehértó joacă un rol activ în regiunea economică a orașului Nyíregyháza.", "Anual se organizează festivalul 'Zilele Vișinelor', un eveniment gastronomic major."] },
  "geo-szatmari-siksag-extra": { facts: ["Câmpia Sătmarului (Szatmári-síkság) este o regiune istorică și geografică la granița cu România.", "Peisajul este marcat de râurile Tisa, Someș și Tur, având numeroase zone inundabile.", "Este una dintre cele mai tradiționale regiuni ale Ungariei, păstrând obiceiuri arhaice.", "Regiunea este celebră pentru 'drumul bisericilor medievale', mici bijuterii arhitecturale.", "Solul aluvionar este extrem de fertil, fiind ideal pentru cultivarea prunelor și a merelor.", "Flora include păduri de stejar și zone cu vegetație specifică malurilor de râu.", "Localitățile din câmpie au un farmec aparte, cu case vechi și porți sculptate din lemn.", "Este o destinație preferată pentru turismul rural și pentru observarea naturii neatinse."] },
  "historical-csaroda-templom-extra": { facts: ["Biserica din Csaroda este un monument gotic timpuriu de o frumusețe rară, datând din secolul al XIII-lea.", "Interiorul păstrează fresce originale cu sfinți zâmbitori, unice în arta medievală maghiară.", "Tavanul de lemn casetat și pictat manual datează din perioada barocă și este impecabil conservat.", "Turnul zvelt al bisericii este acoperit cu șindrilă, având o formă specifică regiunii Szatmár.", "Biserica este situată într-un cadru idilic, fiind înconjurată de un gard mic de piatră.", "Motivele florale care decorează pereții reflectă influența folclorului local asupra artei religioase.", "Csaroda este o oprire esențială pe traseul bisericilor medievale din bazinul Tisei superioare.", "În jurul bisericii se află un mic cimitir cu cruci vechi din lemn, specifice zonei."] },
  "landmark-tarpaiszarazmalom-extra": { facts: ["Moara uscată din Tarpa este una dintre ultimele mori cu cai (acționate de animale) din Europa.", "Construită în secolul al XIX-lea, moara este un monument tehnic de o valoare inestimabilă.", "Mecanismul uriaș de lemn era pus în mișcare de cai care mergeau în cerc într-o sală mare.", "Acoperișul imens din șindrilă are o formă circulară, fiind o capodoperă a dulgheriei populare.", "Moara este încă funcțională în scop demonstrativ, oferind o imagine clară a tehnicilor vechi.", "Tarpa este situată în județul Szabolcs-Szatmár-Bereg, o zonă bogată în patrimoniu rural.", "Lângă moară se află și o casă tradițională care completează imaginea gospodăriei de altădată.", "Localitatea este renumită și pentru renumita sa pălincă de prune cu denumire protejată."] },
  "city-tamasi-extra": { facts: ["Tamási este un oraș renumit la nivel internațional pentru băile sale termale și pentru vânătoare.", "Rezervația de vânătoare Gyulaj din apropiere adăpostește cea mai mare populație de cerbi lopătari.", "Băile Termale din Tamási au fost modernizate recent, oferind piscine cu ape bogate în fluor.", "Orașul este situat într-o zonă colinară superbă, la intersecția drumurilor spre Balaton și Pécs.", "Localitatea are o istorie lungă, fiind menționată ca posesiune regală în evul mediu.", "Anual se organizează festivalul 'Zilele Vânătorii', atrăgând specialiști din toată lumea.", "Biserica catolică din oraș este un monument baroc valoros, decorat cu picturi murale.", "Pista de biciclete legată de rețeaua regională face din Tamási un hub pentru turismul activ."] },
  "geo-siocsatorna-extra": { facts: ["Canalul Sió este principala cale de evacuare a surplusului de apă din lacul Balaton către Dunăre.", "Canalul are o lungime de peste 120 km, traversând județele Somogy, Tolna și Fejér.", "Sistemul de ecluze de la Siófok controlează cu precizie nivelul apei în 'Marea Ungariei'.", "Canalul a fost navigabil în trecut pentru navele care legau Balatonul de rețeaua fluvială europeană.", "Lunca canalului Sió este un coridor ecologic important pentru fauna acvatică.", "Malurile canalului sunt populare pentru pescuit și pentru drumeții lungi în natură.", "Recent, s-au realizat investiții majore pentru modernizarea ecluzelor și a digurilor de protecție.", "Canalul trece prin peisaje variate, de la câmpii agricole până la zone colinare împădurite."] },
  "historical-graboc-extra": { facts: ["Mănăstirea sârbă din Grábóc este un centru spiritual ortodox unic în județul Tolna.", "Fondată în secolul al XIV-lea de călugări veniți de la mănăstirea Dragović din Dalmația.", "Biserica actuală, ridicată în stil baroc în secolul al XVIII-lea, are un iconostas pictat superb.", "Este singura mănăstire ortodoxă din Ungaria unde viața monahală a fost aproape neîntreruptă.", "Situl este situat într-o vale ascunsă și liniștită, ideală pentru reculegere și rugăciune.", "Frescele interioare reflectă tradiția artistică bizantină adaptată stilului baroc central-european.", "Mănăstirea deține o colecție rară de manuscrise religioase și obiecte de cult vechi.", "Anual, de sărbătoarea hramului, numeroși pelerini sârbi și maghiari vizitează acest loc."] },
  "landmark-ozora-extra": { facts: ["Castelul Pipo din Ozora a fost construit în secolul al XV-lea de faimosul condotier Filippo Scolari.", "Clădirea este un exemplu rar de castel renascentist italian în inima Ungariei medievale.", "Spre deosebire de cetățile militare, castelul din Ozora a fost conceput ca o reședință luxoasă.", "Curtea interioară cu arcade este un spațiu de o eleganță deosebită, recent restaurat.", "Muzeul castelului prezintă viața lui Pipo de Ozora, un aliat de încredere al regelui Sigismund.", "Ozora este celebră astăzi și pentru festivalul de muzică psihedelică desfășurat anual în apropiere.", "Complexul include o grădină de plante aromatice și un mic teatru de curte.", "Castelul oferă și posibilități de cazare în camere mobilate în stil istoric, oferind o experiență unică."] },
  "city-vasvar-extra": { facts: ["Vasvár este unul dintre cele mai vechi orașe din vestul Ungariei, fiind fosta capitală a județului Vas.", "Pacea de la Vasvár din 1664 a fost un tratat istoric major semnat aici între austrieci și otomani.", "Mănăstirea Dominicană din oraș este un monument baroc impunător, găzduind un muzeu regional.", "Orașul se află pe 'Drumul Sfântului Martin', o rută de pelerinaj europeană importantă.", "În apropiere se află 'Zidul de Fier' (Vaskapu), un sistem defensiv antic din epoca migrațiilor.", "Vasvár găzduiește anual festivalul de teatru de stradă 'Hegyháti Napok'.", "Lacurile de la marginea orașului oferă condiții excelente pentru pescuit și relaxare în natură.", "Economia locală are rădăcini în meșteșugurile tradiționale și în prelucrarea lemnului."] },
  "city-janoshaza-extra": { facts: ["Jánosháza este situat la intersecția unor drumuri comerciale importante din județul Vas.", "Castelul Erdődy din oraș este o clădire istorică cu elemente renascentiste și baroce.", "Orașul s-a dezvoltat în jurul domeniului nobiliar, fiind un centru al vieții rurale din zonă.", "Biserica catolică din Jánosháza este un monument arhitectural valoros din secolul al XVIII-lea.", "Localitatea este cunoscută pentru ospitalitatea sa și pentru evenimentele culturale comunitare.", "Jánosháza joacă un rol de centru de servicii pentru satele mici din microregiunea Kemenesalja.", "În apropiere se află dealul Somló, renumit pentru vinurile sale vulcanice.", "Parcul castelului oferă un spațiu verde relaxant pentru locuitori și vizitatori."] },
  "geo-pinka-extra": { facts: ["Pârâul Pinka izvorăște din Austria și șerpuiește de-a lungul graniței maghiaro-austriece.", "Valea Pinkăi este renumită pentru peisajele sale sălbatice și pentru defileele adânci.", "Apa cristalină a Pinkăi adăpostește specii de pești care preferă apele curate de munte.", "Pârâul a alimentat în trecut numeroase mori de apă, ale căror urme se mai văd și astăzi.", "Regiunea Pinkamindszent este o arie protejată, importantă pentru biodiversitatea locală.", "Pârâul trece pe lângă podgorii celebre, unde se produce vinul roșu 'Eisenberg'.", "Traseele de drumeție de-a lungul apei sunt populare pentru liniștea și aerul lor curat.", "În timpul inundațiilor, pârâul poate deveni un râu vijelios, modelând constant relieful văii."] },
  "historical-sitke-extra": { facts: ["Localitatea Sitke este celebră pentru capela sa situată pe un deal, un monument romantic superb.", "Capela Calvarului a fost construită în secolul al XIX-lea de familia nobiliară Felsőbüki Nagy.", "Sitke este renumit în toată Ungaria pentru festivalul de rock caritabil organizat anual la capelă.", "Castelul din Sitke a fost transformat într-un hotel elegant, păstrând farmecul de epocă.", "În curtea castelului se află arbori seculari și statui care atestă trecutul nobiliar al locului.", "Satul este situat în apropierea stațiunii balneare Sárvár, fiind o destinație de excursie apreciată.", "Biserica satului păstrează elemente de arhitectură veche și obiecte de cult valoroase.", "Atmosfera liniștită și peisajul colinar fac din Sitke un loc ideal pentru relaxare."] },
  "landmark-pityerszer-extra": { facts: ["Pityerszer este un muzeu al satului autentic situat în regiunea Őrség, județul Vas.", "Muzeul păstrează case tradiționale 'înnădite' (kerített ház), specifice acestei zone de graniță.", "Construcțiile sunt realizate din lemn și lut, fiind adaptate la stilul de viață al grănicerilor.", "Pityerszer este singurul loc unde se pot vedea aceste tipuri de locuințe în locația lor originală.", "În incintă se pot degusta produse locale tradiționale, precum uleiul de dovleac presat la rece.", "Vizitatorii pot vedea unelte agricole vechi și pot învăța despre tehnica olăritului din Őrség.", "Zona este inclusă în Parcul Național Őrség, fiind înconjurată de păduri și fânețe bogate.", "Evenimentele 'Zilele Őrség' transformă Pityerszer într-un centru vibrant de cultură populară."] },
  "city-ajka-extra": { facts: ["Ajka este un oraș industrial situat în munții Bakony, renumit pentru producția de sticlă și alumină.", "Manufactura de sticlă Ajka Crystal produce obiecte de lux recunoscute la nivel mondial.", "Orașul s-a dezvoltat masiv în secolul XX, devenind un centru al mineritului de bauxită și cărbune.", "Muzeul Mineritului și al Industriei prezintă evoluția tehnologică a regiunii.", "Parcul orașului (Liget) oferă zone de relaxare, un lac și facilități sportive pentru locuitori.", "Ajka este o poartă de acces către frumusețile naturale ale masivului muntos Bakony.", "Localitatea pune un accent mare pe protecția mediului și pe ecologizarea fostelor situri industriale.", "Catedrala catolică modernă din oraș este un reper arhitectural semnificativ al noii localități."] },
  "city-berhida-extra": { facts: ["Berhida este situat în județul Veszprém, fiind o localitate cu o istorie industrială și agricolă.", "Biserica romano-catolică din Berhida datează din secolul al XIII-lea, având o structură rară de piatră.", "Orașul a fost afectat de un cutremur major în anul 1985, fiind ulterior reconstruit.", "Berhida joacă un rol important în economia locală prin unitățile sale de producție chimică.", "Cadrul natural este definit de pârâul Séd care trece prin apropiere.", "Orașul oferă acces rapid către stațiunile de pe malul estic al lacului Balaton.", "Tradițiile locale sunt celebrate prin festivaluri comunitare și evenimente folclorice.", "În apropiere se află zona industrială Pétfürdő, un hub major al industriei îngrășămintelor."] },
  "geo-csobanc-extra": { facts: ["Csobánc este un munte vulcanic sub formă de martor, situat în bazinul Tapolca.", "Pe vârful muntelui se află ruinele cetății Csobánc, care oferă o panoramă uluitoare.", "Versanții muntelui sunt acoperiți de podgorii celebre, unde se produc vinuri de bazalt.", "Muntele este un loc preferat pentru parapantiști datorită curenților de aer favorabili.", "Traseul spre vârf este abrupt, dar trece prin zone cu o floră rară și vederi spre Balaton.", "Cetatea Csobánc a fost una dintre puținele fortificații care nu a fost ocupată niciodată de turci.", "Anual se organizează concursuri de drumeție și evenimente dedicate istoriei cetății.", "Geologia muntelui este fascinantă, prezentând coloane de bazalt ascunse sub vegetație."] },
  "historical-csesznek-extra": { facts: ["Cetatea Csesznek este o fortificație gotică situată spectaculos pe o creastă din munții Bakony.", "Construită în secolul al XIII-lea, cetatea a fost deținută de familii nobiliare precum Cseszneky și Esterházy.", "Este una dintre cele mai romantice ruine din Ungaria, fiind o destinație populară pentru drumeții.", "Situl oferă prima rută de tip 'via ferrata' din Ungaria, amenajată pe pereții stâncoși de sub cetate.", "În secolul al XVIII-lea, cetatea a fost transformată într-un castel baroc, înainte de a fi abandonată.", "Anual, în satul de la poalele cetății au loc jocuri medievale și turniruri cavalerești.", "Vederea de pe bastioane cuprinde văile adânci și crestele împădurite ale masivului Bakony.", "Recent s-au realizat lucrări de consolidare care permit vizitarea în siguranță a zidurilor înalte."] },
  "landmark-osku-extra": { facts: ["Capela Rotundă din Öskü este una dintre cele mai neobișnuite clădiri medievale din Ungaria.", "Construită în secolul al XI-lea, capela are o formă circulară și un acoperiș bombat din piatră.", "Se crede că a fost ridicată pe fundația unui turn de pază roman sau a unui mormânt antic.", "Capela este situată pe un mic dâmb calcaros, oferind un peisaj pitoresc de tip mediteranean.", "Este unul dintre puținele monumente din epoca dinastiei Árpád care s-a păstrat aproape intact.", "Forma sa amintește de iurtele nomade ale maghiarilor timpurii, transformate în arhitectură de piatră.", "Öskü este o localitate situată între orașele Veszprém și Székesfehérvár.", "Interiorul capelei este simplu și auster, păstrând o atmosferă de o spiritualitate profundă."] },
  "city-letenye-extra": { facts: ["Letenye este un oraș situat la granița cu Croația, fiind un important punct de trecere a frontierei.", "Castelul Szapáry din oraș este înconjurat de un parc dendrologic renumit pentru arborii săi exotici.", "În parcul castelului se află un platan gigantic de peste 150 de ani, monument al naturii.", "Orașul este poarta de intrare către regiunea dalmată pentru turiștii care vin dinspre nord.", "Letenye are o tradiție viticolă bogată, dealurile din jur producând vinuri albe aromate.", "Pârâul Kerka trece prin apropierea orașului, oferind zone de agrement și pescuit.", "Anual se organizează festivalul transfrontalier 'Zilele Letenye', celebrând cultura regională.", "Piața locală este un punct de întâlnire pentru comercianții maghiari și croați din zonă."] },
  "city-zalalovo-extra": { facts: ["Zalalövő este situat pe valea râului Zala, având o istorie care urcă până în epoca romană.", "Aici se aflau ruinele orașului roman Salla, un punct important pe ruta 'Via Amber'.", "Muzeul local prezintă descoperiri arheologice valoroase și istoria transportului în zonă.", "Orașul este poarta de intrare în regiunea etnografică Őrség dinspre est.", "Zalalövő păstrează tradiții populare legate de olărit și de prelucrarea fibrelor naturale.", "Biserica satului este un monument arhitectural semnificativ, cu elemente de epocă.", "Traseele de drumeție de-a lungul râului Zala sunt apreciate pentru liniște și frumusețea peisajului.", "Localitatea joacă un rol activ în turismul ecologic și cultural din județul Zala."] },
  "geo-kisbalaton-extra": { facts: ["Kis-Balaton (Micul Balaton) este o rezervație naturală de importanță mondială, protejată prin Convenția Ramsar.", "Zona funcționează ca un filtru natural imens pentru apa care intră în lacul Balaton.", "Este un paradis al păsărilor, găzduind peste 250 de specii, inclusiv cormorani și stârci.", "Insula Kányavári este singura zonă a rezervației care poate fi vizitată fără ghid specializat.", "Podul de lemn curbat care duce spre insulă este un simbol arhitectural al regiunii.", "Centrul de vizitare 'Casa Micului Balaton' oferă expoziții interactive despre ecosistemul zonei.", "Rezervația adăpostește bivoli de apă maghiari în rezervația specială de la Kápolnapuszta.", "Accesul în zonele strict protejate se face doar cu bărci speciale și sub supraveghere științifică."] },
  "historical-egervar-extra": { facts: ["Castelul-cetate din Egervár este una dintre cele mai importante fortificații de câmpie din Ungaria.", "Construit în stil renascentist în secolul al XVI-lea, castelul a fost recent renovat complet.", "Curtea interioară cu arcade este un spațiu de o frumusețe clasică, folosit pentru spectacole.", "Muzeul castelului prezintă istoria familiei Nádasdy și evoluția arhitecturii defensive.", "Egervár este situat în județul Zala, într-un peisaj colinar liniștit.", "Castelul dispune de un centru de vizitare modern care folosește tehnologia hologramelor.", "În timpul verii, aici se organizează faimoasele 'Seri de Teatru de la Egervár'.", "Grădina castelului oferă un spațiu de promenadă relaxant mărginite de ziduri istorice."] },
  "landmark-gocsej-falumuzeum-extra": { facts: ["Muzeul Satului Göcsej din Zalaegerszeg a fost primul muzeu etnografic în aer liber din Ungaria.", "Situl prezintă arhitectura tradițională a microregiunii Göcsej, renumită pentru casele din bârne.", "Piesa centrală este o moară de apă funcțională de pe malul râului Zala.", "Vizitatorii pot vedea case cu acoperiș de paie, grajduri și biserici mici de lemn.", "Muzeul recreează atmosfera unui sat autentic din secolele XVIII-XIX.", "Göcsej este cunoscut pentru preparatele sale culinare pe bază de hrean și ciuperci de pădure.", "Anual se organizează festivaluri unde meșterii locali demonstrează tehnica olăritului și a țesutului.", "Complexul este situat chiar lângă centrul orașului Zalaegerszeg, fiind ușor accesibil."] }
};

updateFile('lib/visualLab/data/poiExtraHu1.ts', hu1);
console.log('Updated poiExtraHu1.ts');
