import fs from 'fs';

const file = 'lib/visualLab/data/poiExtraHu3.ts';
let content = fs.readFileSync(file, 'utf8');

const updates = {
  "historical-simontornyai-var-extra": {
    desc: "Cetatea Simontornya este un monument istoric fascinant care îmbină într-un mod unic fortificația medievală cu eleganța Renașterii. Numit după constructorul său, Simon Turul, complexul are o istorie de peste 700 de ani. De-a lungul secolelor, cetatea a servit ca reședință nobiliară, punct strategic de apărare și centru administrativ. Arhitectura sa actuală păstrează elemente valoroase din perioada gotică și renascentistă, fiind restaurată cu grijă pentru a reda vizitatorilor atmosfera de altădată. Muzeul amenajat în interior prezintă descoperiri arheologice locale și istoria familiilor care au stăpânit aceste ținuturi.",
    facts: ["Turnul de locuit original a fost ridicat în anul 1277 de către Simon Turul.", "Cetatea a fost modernizată la începutul secolului al XVI-lea după modelul curții regale din Buda.", "În timpul războaielor cu turcii, Simontornya a fost un oraș de garnizoană otoman timp de aproape 150 de ani.", "Săpăturile arheologice au scos la lumină un cuptor de ceramică renascentist unic în regiune.", "Bastionul porții oferă o perspectivă interesantă asupra sistemului defensiv medieval.", "Cetatea găzduiește expoziții periodice de artă contemporană și istorie locală."]
  },
  "historical-dunafoldvari-var-extra": {
    desc: "Cetatea din Dunaföldvár, cunoscută și sub numele de Turnul Csonka, este o fortificație emblematică situată pe malul drept al Dunării. Nucleul său este un turn de locuit masiv din secolul al XV-lea, care a supraviețuit multor asedii și perioade de abandon. Poziția sa strategică pe o înălțime deasupra fluviului a făcut din această cetate un punct cheie pentru controlul traficului naval și al trecerilor peste Dunăre. Astăzi, turnul restaurat găzduiește un muzeu local, unde sunt expuse obiecte ce atestă istoria milenară a așezării. Atmosfera istorică este completată de curtea cetății, unde se organizează diverse evenimente culturale și festivaluri în timpul verii.",
    facts: ["Turnul de locuit a fost construit în secolul al XV-lea, sub domnia regelui Sigismund.", "În perioada otomană, turnul a servit drept depozit de cereale și punct de apărare.", "De la ultimul etaj se oferă o vedere spectaculoasă asupra fluviului și a Câmpii Maghiare.", "Clădirea a fost dinamitată parțial de trupele austriece, de unde și denumirea de 'Turnul Csonka' (Trunchiat).", "Ansamblul include și o curte interioară unde se află un teatru în aer liber.", "Turnul are ziduri groase de peste doi metri, construite pentru a rezista loviturilor de tun."]
  },
  "kid-landmark-gemenci-kisvasut-extra": {
    desc: "Calea ferată cu ecartament îngust din Gemenc este un punct de atracție major pentru familii, oferind o modalitate unică de a explora cea mai mare luncă din Europa Centrală. Traseul șerpuiește prin păduri inundabile dense, trecând pe lângă brațe moarte ale Dunării și poieni unde pot fi observate animale sălbatice. Trenul pleacă din Pörböly, unde se află un centru de vizitare modern cu expoziții despre fauna și flora locală. Călătoria cu vagoanele deschise oferă o proximitate deosebită față de natură, fiind o experiență relaxantă pentru toate vârstele. Gemenc este renumit pentru populația sa de cerbi carpatini și barze negre, care pot fi zărite adesea din mersul trenului.",
    facts: ["Gemenc este cea mai mare pădure de luncă continuă din Europa Centrală.", "Traseul trece pe lângă numeroase brațe moarte ale Dunării, bogate în pești și păsări.", "În Pörböly se află o locomotivă cu aburi istorică numită 'Rezét'.", "Linia ferată are o lungime de aproximativ 30 de kilometri, traversând arii protejate.", "Trenul circulă zilnic în timpul sezonului turistic, având opriri în puncte cheie de observare.", "În timpul inundațiilor mari de pe Dunăre, porțiuni din traseu pot fi acoperite de apă.", "Centrul Pörböly oferă și facilități de închiriere de biciclete și canoe.", "Expoziția 'Comorile din Gemenc' prezintă ciclul de viață al pădurii inundabile."]
  },
  "industry-paksi-atomeromu-extra": {
    desc: "Centrala Nucleară de la Paks este cel mai important producător de energie electrică din Ungaria, asigurând aproximativ jumătate din necesarul de curent al țării. Situată pe malul Dunării, centrala utilizează apa fluviului pentru procesele de răcire, fiind un obiectiv strategic de securitate națională. Tehnologia utilizată este de tip VVER, recunoscută pentru fiabilitatea sa, iar managementul centralei pune un accent extrem pe siguranța nucleară și protecția mediului. Vizitatorii pot explora centrul de informare al centralei și Muzeul Energiei Nucleare, unde pot învăța despre funcționarea reactoarelor și despre rolul energiei atomice în combaterea schimbărilor climatice. Paks a devenit astfel nu doar un hub industrial, ci și un punct important pentru educația tehnologică a publicului larg.",
    facts: ["Cele patru reactoare produc anual peste 15.000 de gigawați-oră de energie electrică.", "Centrala utilizează apa Dunării pentru răcirea condensatoarelor, returnând-o cu câteva grade mai caldă.", "Sistemele de siguranță sunt verificate constant conform standardelor Agenției Internaționale pentru Energie Atomică.", "Muzeul Energiei Nucleare din Paks este singura instituție de acest tip din regiune.", "Primul bloc al centralei a fost conectat la rețeaua națională în anul 1982.", "Centrala asigură peste 40% din producția internă de energie electrică a Ungariei.", "Paks 2 este proiectul de extindere care vizează construcția a două noi reactoare moderne.", "Comunitatea locală beneficiază de numeroase investiții sociale susținute de centrală."]
  },
  "agriculture-szekszardi-bor-extra": {
    desc: "Regiunea viticolă Szekszárd este una dintre cele mai tradiționale zone pentru vinuri roșii din Ungaria, fiind celebră pentru cupajul 'Bikavér' (Sânge de Taur). Dealurile însorite din jurul orașului oferă condiții climatice ideale pentru soiurile de struguri negri, rezultând vinuri pline de caracter, catifelate și aromate. Tradiția vinificației în zonă datează încă din epoca romană, fiind perfecționată de-a lungul secolelor de meșteri locali. Vizitatorii pot explora cramele istorice săpate în loess și pot participa la degustări unde vor descoperi eleganța soiului Kadarka sau forța vinului Cabernet. Szekszárd nu este doar despre vin, ci și despre ospitalitatea autentică și peisajele idilice ale dealurilor Tolna.",
    facts: ["Szekszárd este una dintre cele mai vechi regiuni viticole din Ungaria, cu rădăcini romane.", "Regiunea are una dintre cele mai mari durate de însorire din întreaga țară.", "Soiul Kadarka este considerat cel mai reprezentativ și tradițional pentru acest areal.", "Cupajul 'Szekszárdi Bikavér' are reguli stricte de producție pentru a păstra calitatea.", "Cramele săpate în straturi de loess oferă o temperatură constantă naturală pentru maturare.", "Sărbătoarea Vinului de la Szekszárd atrage mii de vizitatori în fiecare lună septembrie.", "Regiunea cuprinde aproximativ 2.100 de hectare de viță de vie pe dealuri line.", "Producătorii locali pun un accent tot mai mare pe agricultura organică și sustenabilă."]
  },
  "historical-jurisics-var-extra": {
    desc: "Cetatea Jurisics din Kőszeg este un simbol al rezistenței eroice împotriva invaziei otomane, devenind faimoasă în 1532. Sub comanda căpitanului Miklós Jurisics, o mică garnizoană a reușit să oprească armata imensă a sultanului Suleiman Magnificul, care se îndrepta spre Viena. Cetatea îmbină stilurile gotic, renascentist și baroc, reflectând perioadele sale de reconstrucție. Vizitatorii pot explora curțile interioare, muzeul cetății care prezintă istoria locală și sistemul defensiv medieval. Atmosfera orașului Kőszeg, unul dintre cele mai pitorești orașe istorice din Ungaria, este întregită de prezența acestei fortărețe care veghează de peste șapte secole asupra comunității.",
    facts: ["Asediul din 1532 a durat 25 de zile, oprind înaintarea turcilor spre Viena.", "În fiecare zi, la ora 11:00, clopotele din Kőszeg bat pentru a comemora plecarea turcilor.", "Cetatea a aparținut mai multor familii nobiliare importante, inclusiv familiei Esterházy.", "Arhitectura cetății păstrează elemente din secolul al XIII-lea, fiind parțial înconjurată de un șanț de apă.", "Turnul porții oferă o vedere panoramică asupra pieței centrale a orașului Kőszeg.", "Muzeul găzduiește expoziția 'Secolele de aur din Kőszeg', prezentând bogăția istorică a zonei.", "Grădina cetății este un loc de relaxare apreciat, cu arbori seculari și statui istorice.", "Cetatea a fost complet renovată în ultimii ani, devenind un centru cultural modern."]
  },
  "historical-nadasdy-var-sarvar-extra": {
    desc: "Cetatea Nádasdy din Sárvár este una dintre cele mai bine conservate fortificații renascentiste din Ungaria, fiind celebră pentru frumusețea sălilor sale interioare. De-a lungul secolelor, familia Nádasdy a transformat fortăreața militară într-o reședință nobiliară luxoasă, un centru al culturii și al tipăritului maghiar. Sala Mare, decorată cu fresce monumentale ce înfățișează scene de bătălie, este considerată una dintre cele mai frumoase încăperi baroce din țară. Cetatea este înconjurată de un parc dendrologic superb, oferind un cadru ideal pentru plimbări relaxante. Astăzi, complexul găzduiește Muzeul Ferenc Nádasdy, care prezintă istoria husarilor, arte decorative și viața nobiliară din Transdanubia.",
    facts: ["Este una dintre puținele cetăți din Ungaria care nu a fost distrusă în timpul asediilor austriece.", "Prima carte în limba maghiară a fost tipărită aici, sub patronajul familiei Nádasdy.", "Sala Mare a fost pictată în secolul al XVIII-lea și este un exemplu remarcabil de baroc maghiar.", "Șanțul cetății este acum o grădină publică amenajată, plină de flori și vegetație.", "Muzeul husarilor din interior este unic în Europa, prezentând istoria acestui corp de elită.", "Turnul de poartă păstrează elemente de fortificație din secolul al XVI-lea.", "Cetatea a aparținut și casei regale de Bavaria în secolul al XIX-lea.", "Anual, în curtea cetății au loc festivaluri de muzică clasică și evenimente folclorice."]
  },
  "kid-landmark-jeli-arboretum-extra": {
    desc: "Arboretul Jeli este supranumit „Grădina Magică” a Ungariei, fiind renumit la nivel mondial pentru colecția sa spectaculoasă de rododendroni. Fondată de contele István Ambrózy-Migazzi la începutul secolului XX, grădina se întinde pe o suprafață mare, oferind un spectacol vizual incredibil în lunile mai și iunie, când mii de flori de culori variate înfloresc simultan. Vizitatorii se pot plimba pe alei șerpuite care trec prin „grădina de peisaj”, admirând specii rare de arbori aduși din Japonia, America și China. Aerul parfumat și culorile vibrante fac din acest arboret o destinație de vis pentru iubitorii de natură și fotografi. Recent, a fost inaugurat și un traseu prin coronamentul arborilor, permițând vizitatorilor să vadă grădina dintr-o perspectivă cu totul nouă.",
    facts: ["Rododendronii din Jeli înfloresc de obicei între mijlocul lunii mai și începutul lunii iunie.", "Grădina se întinde pe o suprafață de peste 100 de hectare, având numeroase microclimate.", "Contele Ambrózy-Migazzi a fost supranumit 'omul florilor' datorită pasiunii sale pentru botanică.", "Arboretul găzduiește și specii de conifere gigantice aduse de pe continentul nord-american.", "Există un traseu prin coroana arborilor, lung de câteva sute de metri, la 10 metri înălțime.", "Pârâul Kapuné șerpuiește prin grădină, creând zone umede ideale pentru plantele iubitoare de apă.", "Grădina este amenajată pe baza principiului 'grădinii veșnic verzi', având farmec în orice anotimp.", "Este considerat unul dintre cele mai valoroase parcuri dendrologice din Europa Centrală."]
  },
  "industry-opel-szentgotthard-extra": {
    desc: "Fabrica Opel din Szentgotthárd este un simbol al renașterii industriei auto maghiare după anul 1990, fiind prima mare investiție străină de acest tip din țară. Situată chiar la granița cu Austria, unitatea s-a specializat de-a lungul deceniilor în producția de motoare de înaltă tehnologie pentru diverse modele ale grupului. Fabrica utilizează procese de producție ultra-moderne și automatizate, fiind recunoscută pentru standardele sale ridicate de calitate. Dincolo de importanța sa economică directă, Opel Szentgotthárd a contribuit masiv la formarea unei baze solide de specialiști în inginerie auto în regiune. Astăzi, fabrica face parte din grupul Stellantis și continuă să fie un jucător cheie în rețeaua de producție auto europeană, adaptându-se constant cerințelor pentru motoare mai eficiente și mai ecologice.",
    facts: ["Primul autoturism Opel Astra fabricat în Ungaria a ieșit de pe linia de asamblare în 1992.", "Fabrica s-a transformat ulterior într-un centru global de producție a motoarelor.", "Unitatea produce sute de mii de motoare pe an pentru mărci precum Opel, Peugeot și Citroën.", "Szentgotthárd beneficiază de o locație strategică pentru logistică, fiind legată de marile autostrăzi europene.", "Fabrica a primit numeroase premii pentru eficiență și protecția muncii la nivel internațional.", "O mare parte din energia utilizată în fabrică provine din surse regenerabile.", "Colaborează intens cu școli tehnice locale pentru programe de învățământ dual.", "Producția de motoare include unități pe benzină de ultimă generație, extrem de eficiente."]
  },
  "industry-kormendi-gyogyszergyar-extra": {
    desc: "Fabrica de medicamente din Körmend, parte a grupului Egis, este unul dintre pilonii industriei farmaceutice maghiare, având o tradiție de cercetare și producție recunoscută internațional. Unitatea se concentrează pe fabricarea unor medicamente esențiale pentru tratarea bolilor cardiovasculare și ale sistemului nervos central. Fabrica utilizează tehnologii de sinteză chimică și ambalare la cele mai înalte standarde globale, exportând produse în peste 60 de țări. Körmendul a devenit astfel un punct central pe harta inovației medicale din regiune, oferind locuri de muncă pentru specialiști de înaltă calificare. Investițiile constante în noi linii de producție și în centre de logistică modernă asigură competitivitatea fabricii pe piața farmaceutică mondială, extrem de exigentă.",
    facts: ["Grupul Egis are o istorie de peste 100 de ani în industria farmaceutică ungară.", "Fabrica din Körmend produce anual milioane de cutii de medicamente pentru export.", "Investițiile recente au vizat crearea unor unități de producție pentru substanțe oncologice.", "Compania pune un accent major pe cercetare și dezvoltare, având sute de brevete proprii.", "Körmend este un centru logistic major pentru distribuția medicamentelor în toată Europa Centrală.", "Standardele de calitate sunt verificate periodic de autoritățile de reglementare din UE și SUA.", "Egis este un angajator strategic în județul Vas, sprijinind comunitatea locală.", "Procesele de producție sunt supravegheate prin sisteme digitale de înaltă precizie."]
  },
  "historical-sumegi-var-extra": {
    desc: "Cetatea Sümeg este una dintre cele mai spectaculoase și bine conservate fortificații medievale din Ungaria, tronând deasupra orașului pe un con vulcanic abrupt. Construită în secolul al XIII-lea, cetatea a fost o piesă cheie în sistemul defensiv al regiunii Balaton, reușind să reziste asediilor otomane de-a lungul istoriei. Vizitatorii pot urca pe drumul abrupt până la porțile grele pentru a descoperi o lume medievală vie: ateliere de meșteșugari, expoziții de arme și temnițe istorice. Curtea interioară este adesea scena unor turniruri cavalerești și banchete medievale care atrag turiști din toată lumea. Vederea de pe ziduri este pur și simplu uluitoare, oferind o panoramă completă asupra peisajului din Transdanubia.",
    facts: ["Cetatea a fost construită din ordinul regelui Béla al IV-lea după invazia tătară.", "Este singura cetate din regiunea Balaton care nu a fost ocupată niciodată de turci.", "Programul de spectacole medievale de la Sümeg este considerat cel mai bun din Ungaria.", "În interior se află o capelă veche și o expoziție dedicată istoriei torturii.", "Turnul de poartă și bastionul vechi păstrează zidăria originală din piatră de calcar.", "Anual, mii de turiști participă la 'Jocurile Istorice ale Cetății' în luna august.", "Cetatea a fost un centru important pentru episcopii de Veszprém în timpul dominației turcești.", "S-au realizat restaurări masive care permit vizitarea aproape integrală a complexului."]
  },
  "historical-tihanyi-apatsag-extra": {
    desc: "Abbația Benedictină din Tihany este un reper spiritual și istoric fundamental al Ungariei, situat pe peninsula omonimă ce înaintează în apele lacului Balaton. Fondată în 1055 de regele Andrei I, abbația deține un act de ctitorie ce conține primele cuvinte scrise în limba maghiară. Biserica barocă actuală, cu cele două turnuri emblematice, a fost ridicată în secolul al XVIII-lea pe locul vechii structuri romanice. Cripta regală, unde se află mormântul regelui Andrei I, este singurul loc de înhumare regală din Ungaria care a rămas intact pe locul său original. Tihany oferă nu doar o experiență spirituală, ci și una peisagistică de neuitat, cu vederi panoramice spectaculoase asupra 'Mării Ungariei' și câmpuri de lavandă ce parfumează aerul în fiecare vară.",
    facts: ["Actul de ctitorie al abbației (1055) este cel mai vechi document original păstrat în Ungaria.", "Cripta regală este o capodoperă a arhitecturii romanice timpurii din secolul al XI-lea.", "Turnurile abbației sunt simbolul oficial al peninsulei Tihany și al întregului lac Balaton.", "În interiorul bisericii se află sculpturi baroce superbe realizate de meșterul Sebestyén Stulhoff.", "Muzeul abbației prezintă istoria ordinului benedictin și viața comunității monahale.", "Tihany este faimos pentru 'ecoul' său, care se poate auzi cel mai bine de pe dealul de lângă biserică.", "Festivalul Lavandei din iunie transformă zona din jurul abbației într-un loc plin de culoare.", "Abbația este un punct de pelerinaj important pe ruta Sfântului Martin din Europa Centrală."]
  },
  "animal-habitat-veszpremi-allatkert-extra": {
    desc: "Grădina Zoologică din Veszprém, cunoscută și sub numele de Grădina Zoologică Kittenberger Kálmán, este una dintre cele mai frumoase și populare din Ungaria. Situată într-un cadru natural spectaculos, parțial într-o vale stâncoasă și parțial pe un platou, grădina oferă spații vaste și moderne pentru animalele sale. Vizitatorii pot admira o colecție impresionantă de specii, de la elefanți africani și rinoceri, până la pinguini și maimuțe exotice. Parcul pune un accent major pe conservarea speciilor și pe educația tinerilor, având numeroase zone interactive și un parc cu dinozauri care face deliciul copiilor. O plimbare prin acest zoo este o aventură completă în natură, oferind momente de relaxare și descoperire la doar câțiva pași de centrul istoric al orașului Veszprém.",
    facts: ["Grădina zoologică a fost deschisă în 1958 și poartă numele faimosului vânător și scriitor Kittenberger Kálmán.", "Este situată pe un teren accidentat de peste 15 hectare, oferind un peisaj variat.", "Parcul Dinozaurilor din incintă prezintă replici în mărime naturală ale creaturilor preistorice.", "Veszprém Zoo a fost prima din Ungaria care a găzduit cu succes o familie de elefanți africani.", "Există o pasarelă spectaculoasă la înălțime de unde pot fi observate girafele la nivelul ochilor.", "Grădina participă la peste 50 de programe internaționale de reproducere a speciilor periclitate.", "Pădurea de pinguini permite vizitatorilor să vadă păsările înotând printr-un perete de sticlă.", "Grădina este deschisă în fiecare zi a anului, oferind experiențe diferite în fiecare sezon."]
  },
  "industry-herendi-porcelan-extra": {
    desc: "Manufactura de Porțelan Herend este o legendă a meșteșugului maghiar, fiind recunoscută la nivel mondial ca unul dintre cei mai mari și importanți producători de porțelan pictat manual. Fondată în 1826, manufactura a devenit rapid furnizorul oficial al caselor regale din Europa, inclusiv al Reginei Victoria a Marii Britanii. Fiecare piesă de Herend este o operă de artă unică, modelată și decorată cu o precizie incredibilă de către artiști talentați. Vizitatorii centrului 'Porcelanium' pot vedea procesul de fabricație în atelierele demonstrative, unde pot observa cum lutul alb se transformă în obiecte delicate, decorate cu flori, păsări sau motive geometrice complexe. Herend este sinonim cu luxul, tradiția și perfecțiunea artistică, ducând faima artei maghiare în cele mai prestigioase saloane ale lumii.",
    facts: ["Modelul 'Victoria' a fost creat special pentru Regina Victoria după ce l-a admirat la Expoziția de la Londra din 1851.", "Fiecare obiect este marcat cu sigiliul oficial Herend, garantând autenticitatea și calitatea manuală.", "Manufactura utilizează mii de culori diferite și motive tradiționale păstrate de generații.", "Herend este membru al asociației Comité Colbert, care reunește cele mai prestigioase mărci de lux din lume.", "Cea mai mare piesă produsă vreodată la Herend este o vază monumentală de peste un metru înălțime.", "Muzeul Porțelanului din Herend adăpostește piese istorice de o valoare inestimabilă.", "Artiștii de la Herend au nevoie de ani de pregătire pentru a stăpâni tehnicile complexe de pictură pe porțelan.", "Produsele Herend sunt exportate în peste 60 de țări, fiind cadouri diplomatice oferite frecvent de statul maghiar."]
  },
  "industry-ajkai-timfoldgyar-extra": {
    desc: "Combinatul de alumină din Ajka a fost un punct central al industriei metalurgice maghiare, procesând bauxita extrasă din Munții Bakony. Istoria sa este marcată de decenii de producție intensivă care a susținut economia regiunii, dar și de tragedia ecologică din 2010. Astăzi, situl trece printr-un proces complex de transformare și ecologizare, fiind un studiu de caz important pentru managementul industrial modern și protecția mediului. Vizitatorii interesați de istoria tehnicii pot observa structurile industriale masive care definesc orizontul orașului Ajka. Regiunea din jur a fost revitalizată prin proiecte de împădurire și monitorizare strictă, demonstrând capacitatea de regenerare a naturii și a comunității după perioade de activitate industrială grea.",
    facts: ["Bauxita utilizată provenea din zăcămintele bogate ale munților Bakony din apropiere.", "Producția de alumină este prima etapă tehnologică în obținerea aluminiului metalic.", "Structura combinatului include furnale uriașe și silozuri de depozitare vizibile de la distanță.", "După evenimentele din 2010, au fost implementate cele mai stricte norme de siguranță industrială din Europa.", "Situl industrial este conectat la o rețea feroviară extinsă pentru transportul materiilor prime.", "În prezent, se pune un accent major pe recultivarea terenurilor și pe monitorizarea solului.", "Orașul Ajka s-a dezvoltat în jurul acestei industrii, devenind un centru urban important în județul Veszprém.", "Există planuri pentru transformarea unor părți din sit în parcuri tehnologice moderne."]
  },
  "historical-festetics-keszthely-extra": {
    desc: "Castelul Festetics din Keszthely este unul dintre cele mai splendide și vizitate castele baroce din Ungaria, fiind un simbol al bogăției culturale a aristocrației maghiare. Construit în secolul al XVIII-lea și extins ulterior, castelul impresionează prin fațada sa elegantă și prin interiorul deosebit de luxos, care a rămas în mare parte intact. Bijuteria coroanei este Biblioteca Helikon, singura bibliotecă nobiliară privată din Ungaria care s-a păstrat completă, adăpostind peste 80.000 de volume rare. Complexul include, de asemenea, un muzeu al trăsurilor, o seră tropicală și o expoziție cinegetică impresionantă. Parcul castelului, amenajat în stil englezesc, este un loc ideal pentru relaxare, fiind decorat cu fântâni arteziene și statui istorice. O vizită la castelul Festetics oferă o incursiune autentică în stilul de viață rafinat al uneia dintre cele mai progresiste familii nobiliare din istoria țării.",
    facts: ["Biblioteca Helikon conține cărți rare și manuscrise care au supraviețuit celui de-al Doilea Război Mondial.", "Familia Festetics a fondat Georgikon, prima universitate agricolă din Europa, la Keszthely.", "Castelul are 101 încăperi, dintre care cele mai importante sunt deschise publicului.", "Sala Oglinzilor din castel găzduiește periodic concerte de muzică clasică de înaltă calitate.", "Muzeul Trăsurilor din incintă prezintă peste 50 de vehicule istorice, inclusiv calești regale.", "Grădina cu palmieri a fost construită în 1880 și adăpostește plante exotice rare.", "Festetics a fost una dintre puținele familii nobiliare care a sprijinit activ cultura și știința în Ungaria.", "Anual, castelul atrage peste 200.000 de vizitatori, fiind un motor turistic pentru regiunea Balaton."]
  },
  "historical-rezi-var-extra": {
    desc: "Cetatea Rezi, situată pe o creastă stâncoasă la marginea munților Keszthely, este o ruină medievală plină de atmosferă care oferă una dintre cele mai frumoase priveliști asupra lacului Balaton. Construită probabil în secolul al XIII-lea, fortăreața a avut un rol defensiv important, supraveghind drumurile comerciale din regiune. Deși astăzi au rămas doar fragmente din zidurile groase și din turnurile sale, situl atrage numeroși turiști datorită peisajului sălbatic și liniștii absolute. Traseul de drumeție prin pădurea de fagi care duce la cetate este o plăcere pentru iubitorii de natură. Legendele locale vorbesc despre comori ascunse și tuneluri secrete sub stâncă, adăugând o notă de mister acestei fortărețe care pare să crească direct din munte.",
    facts: ["Cetatea a fost construită la o altitudine de 418 metri, pe un promontoriu calcaros.", "A servit drept punct de observație strategic împotriva incursiunilor tătare și otomane.", "Zidurile cetății au fost distruse parțial prin explozie în secolul al XVI-lea pentru a nu cădea în mâinile turcilor.", "De pe platforma cetății se pot vedea în zilele senine dealurile Somló și munții Bakony.", "Săpăturile arheologice au scos la lumină fragmente de ceramică medievală și vârfuri de săgeți.", "Este o destinație populară pentru Turul Albastru Național al Ungariei.", "În apropiere se află Stupa Budistă din Zalaszántó, un alt obiectiv turistic interesant.", "Restaurările recente au consolidat zidurile rămase pentru a preveni degradarea lor ulterioară."]
  },
  "kid-landmark-zalakaros-furdo-extra": {
    desc: "Băile Termale din Zalakaros sunt un paradis al relaxării și distracției pentru toate vârstele, fiind una dintre cele mai moderne stațiuni balneare din Ungaria. Apa termală de aici este unică, având un conținut bogat de minerale care o face ideală pentru tratamente terapeutice, dar și pentru relaxare pură. Pentru copii, parcul acvatic oferă o aventură fără sfârșit cu tobogane uriașe, piscine cu valuri și zone de joacă tematice pline de culoare. Stațiunea este înconjurată de parcuri îngrijite și trasee de plimbare, fiind locul perfect pentru o vacanță în familie. Facilitățile moderne de wellness, saunele și zonele de relaxare asigură o experiență regenerantă completă, transformând Zalakaros într-o destinație de top pe tot parcursul anului.",
    facts: ["Apa termală din Zalakaros a fost descoperită accidental în 1962 în timpul unor foraje petroliere.", "Temperatura apei la sursă este de aproximativ 96 de grade Celsius.", "Băile dispun de o suprafață de apă de peste 5.000 de metri pătrați în numeroase bazine.", "Complexul include o zonă specială numită 'Lumea Copiilor', cu peste 60 de elemente de atracție.", "Apa din Zalakaros este bogată în iod, brom și sulf, având proprietăți curative dovedite.", "Orașul este renumit pentru parcurile sale pline de flori și pentru curățenia exemplară.", "Există o piscină cu apă termală nefiltrată, păstrând toate mineralele naturale intacte.", "Zalakaros este a șasea cea mai vizitată localitate turistică din Ungaria."]
  },
  "industry-nagylengyeli-olaj-extra": {
    desc: "Câmpul petrolifer de la Nagylengyel este un sit istoric major al industriei energetice maghiare, reprezentând locul unde a fost descoperit unul dintre cele mai mari zăcăminte de țiței din țară. În anii '50, descoperirea petrolului aici a transformat regiunea Zala într-un hub industrial vital pentru economia națională. Astăzi, peisajul este marcat de pompele de extracție caracteristice ('capete de cal') care punctează dealurile verzi, oferind o imagine industrială nostalgică. Vizitatorii pot afla povestea 'aurului negru' maghiar în muzeele locale dedicate industriei petroliere. Nagylengyelul rămâne un simbol al eforturilor de explorare geologică și al importanței resurselor naturale în dezvoltarea infrastructurii moderne a Ungariei.",
    facts: ["Petrolul a fost descoperit la Nagylengyel în anul 1951, la adâncimi de peste 2.000 de metri.", "Zăcământul este cunoscut pentru petrolul său vâscos, bogat în bitum.", "Extracția a dus la construirea unor rețele de conducte ce legau regiunea de rafinăriile centrale.", "Muzeul Industriei Petroliere din apropiere (Zalaegerszeg) păstrează utilajele folosite la Nagylengyel.", "Descoperirea petrolului a dus la o creștere rapidă a populației și a infrastructurii în satele din zonă.", "Tehnologia de injecție cu dioxid de carbon a fost utilizată pionierat aici pentru a crește producția.", "Multe dintre sondele vechi sunt încă active, fiind monitorizate digital.", "Regiunea Zala este supranumită 'leagănul petrolului maghiar' datorită acestor descoperiri."]
  },
  "industry-zalaegerszegi-ruhagyar-extra": {
    desc: "Fabrica de confecții din Zalaegerszeg, cunoscută istoric sub numele de Zalaegerszegi Ruhagyár (ZARU), a fost timp de decenii un gigant al industriei textile maghiare. Recunoscută pentru calitatea croielii și a materialelor, fabrica producea îmbrăcăminte atât pentru piața internă, cât și pentru mari branduri internaționale de modă. Mii de femei din regiune au lucrat în atelierele sale, transformând orașul într-un centru important al modei și al designului vestimentar. Deși industria textilă a trecut prin transformări majore după 1990, tradiția croitoriei rămâne vie în Zalaegerszeg prin numeroasele ateliere mai mici și companii specializate care au preluat know-how-ul și rigoarea vechii fabrici. ZARU rămâne în memoria locală ca un simbol al stabilității economice și al măiestriei profesionale.",
    facts: ["Fabrica a fost înființată în 1951 și a devenit rapid unul dintre cei mai mari producători de haine din Europa Centrală.", "ZARU exporta peste 70% din producția sa către țări precum Germania, Franța și Italia.", "Compania a colaborat cu designeri renumiți pentru a crea colecții moderne de costume și paltoane.", "În perioada sa de glorie, fabrica oferea locuri de muncă pentru peste 3.000 de angajați.", "Tradiția calității din Zalaegerszeg este continuată astăzi de branduri locale care pun accent pe design sustenabil.", "Clădirea istorică a fabricii este un punct de reper industrial în structura urbană a orașului.", "Procesul de producție includea secții de creație, croitorie industrială și control riguros al calității.", "Orașul Zalaegerszeg găzduiește și alte industrii conexe, precum cea de prelucrare a pielii."]
  }
};

for (const [id, data] of Object.entries(updates)) {
  const poiRegex = new RegExp(`id:\\s*"${id}"[\\s\\S]*?descriptionAdvanced:\\s*{[\\s\\S]*?ro:\\s*""[\\s\\S]*?},[\\s\\S]*?factsAdvanced:\\s*{[\\s\\S]*?ro:\\s*\\[\\s*\\]`, 'g');
  
  content = content.replace(poiRegex, (match) => {
    let updatedMatch = match.replace(/ro:\s*""/, `ro: "${data.desc}"`);
    updatedMatch = updatedMatch.replace(/ro:\s*\[\s*\]/, `ro: [\n        "${data.facts.join('",\n        "')}"\n      ]`);
    return updatedMatch;
  });
}

fs.writeFileSync(file, content);
console.log('Updated remaining POIs in poiExtraHu3.ts');
