# -*- coding: utf-8 -*-
"""Insert German descriptionAdvanced text for 59 Mali cities V2."""
import re
import io

PATH = r"C:\Users\User\plizio-repo\lib\visualLab\data\poiExtraMaliCitiesV2.ts"

# Hand-written German texts (each >=600 chars, native, factual, SEO-rich)
DE = {
"mopti-cities-v2": "Mopti, oft als 'Venedig Malis' bezeichnet, liegt am Zusammenfluss von Niger und Bani und erstreckt sich über drei künstlich verbundene Inseln im Inneren Niger-Delta. Als wichtigster Flusshafen des Landes bildet die Stadt eine entscheidende Drehscheibe zwischen den nördlichen Wüstenregionen und dem fruchtbaren Süden. Das Stadtbild wird von der Großen Moschee von Mopti geprägt, einem 1933 errichteten Meisterwerk der sudano-sahelischen Lehmarchitektur. Im Hafen ankern täglich Hunderte traditioneller Pinassen, die Salz aus Taoudenni, Trockenfisch, Hirse und Reis transportieren. Mopti gilt als Tor zum Dogonland und vereint Bozo-Fischer, Fulani-Hirten und Bambara-Händler in einem lebendigen kulturellen Mosaik. Geografie K7 — afrikanische Flusshafenstädte.",
"koutiala-cities-v2": "Koutiala in der Region Sikasso ist als 'Hauptstadt des Weißen Goldes' bekannt und gilt als wichtigstes Zentrum der malischen Baumwollproduktion. Die Stadt beherbergt mehrere Verarbeitungsanlagen der staatlichen Compagnie Malienne pour le Développement du Textile (CMDT) und ist Knotenpunkt für Tausende Bauern aus dem Umland. Mit über 140.000 Einwohnern zählt Koutiala zu den am schnellsten wachsenden Städten Malis. Neben Baumwolle werden hier Hirse, Mais und Erdnüsse verarbeitet, und der Wochenmarkt zieht Händler aus Burkina Faso und der Elfenbeinküste an. Die Bevölkerung ist überwiegend Minianka und Bambara, was sich in der reichen Musik- und Webtradition widerspiegelt. Wirtschaftsgeografie K7 — westafrikanische Agrarzentren.",
"kayes-cities-v2": "Kayes liegt im äußersten Westen Malis am Senegal-Fluss und gilt als eine der heißesten Städte Afrikas mit Sommertemperaturen von regelmäßig über 45 °C. Die Stadt war einst ein wichtiger Stützpunkt der französischen Kolonialverwaltung und Endpunkt der Eisenbahnstrecke Dakar-Niger, die 1924 fertiggestellt wurde. Im 19. Jahrhundert war Kayes Hauptstadt des Französisch-Sudan, bevor diese Funktion nach Bamako verlegt wurde. Heute ist die Region für ihre Goldminen, Eisenerzvorkommen und die Wasserkraftwerke Manantali und Félou bekannt. Das prächtige koloniale Bahnhofsgebäude und die historische Festung erinnern an die strategische Bedeutung der Stadt im westafrikanischen Handel. Wirtschaftsgeografie K7 — Bergbauregionen Westafrikas.",
"segou-cities-v2": "Ségou am Niger ist die viertgrößte Stadt Malis und kulturelles Herz des Bambara-Volkes. Die Stadt war zwischen 1712 und 1861 die Hauptstadt des mächtigen Bambara-Königreichs Ségou unter Biton Coulibaly und seinen Nachfolgern. Heute ist Ségou berühmt für das jährliche Festival sur le Niger, eines der wichtigsten Kunst- und Musikfestivals Westafrikas. Die koloniale Architektur entlang des Flusses, die Bogolan-Stoffmanufakturen und die Töpfereien des nahegelegenen Dorfes Kalabougou machen die Stadt zu einem kulturellen Zentrum. Ségou ist auch das Verwaltungszentrum des Office du Niger, des größten Bewässerungsprojekts Westafrikas, das Zehntausende Hektar Reisanbaufläche speist. Kulturgeografie K7 — afrikanische Königreiche.",
"nioro-du-sahel-cities-v2": "Nioro du Sahel im Nordwesten Malis war historisch eine bedeutende Karawanenstadt am Übergang zwischen Sahel und Sahara. Die Stadt war im 19. Jahrhundert Hauptstadt des Reiches der Toucouleur unter El Hadj Omar Tall, eines wichtigen Akteurs des islamischen Dschihad in Westafrika. Heute lebt Nioro vom Viehhandel, insbesondere mit Rindern und Kamelen, die hier von nomadischen Fulani- und Maurenstämmen gehandelt werden. Die Stadt ist auch ein wichtiges Zentrum der Tijaniyya-Bruderschaft mit der berühmten Zaouia von Cheikh Hamahoullah. Geografisch markiert Nioro du Sahel den Übergang vom Trockensavannen-Klima zur Sahel-Steppe, was sie zu einem Schlüsselort für transhumanten Viehhandel macht. Geografie K7 — Sahelregionen.",
"niono-cities-v2": "Niono in der Region Ségou ist das Herzstück des Office du Niger, des größten Bewässerungsprojekts Westafrikas. Die Stadt liegt im fruchtbaren Inneren Niger-Delta und ist von einem dichten Netz aus Kanälen umgeben, die seit den 1930er Jahren von französischen Kolonialingenieuren angelegt wurden. Heute werden hier auf über 100.000 Hektar Reis, Zuckerrohr und Gemüse für den nationalen Markt produziert. Niono gilt als Reiskammer Malis und versorgt Bamako sowie die Nachbarländer mit Grundnahrungsmitteln. Die Bevölkerung ist eine Mischung aus Bambara-Bauern, Fulani-Hirten und sogenannten 'Coloniaux' — Nachfahren von Familien, die einst aus anderen Landesteilen zur Bewirtschaftung des Bewässerungssystems angesiedelt wurden. Agrargeografie K7 — Bewässerungslandwirtschaft.",
"markala-cities-v2": "Markala am Niger ist berühmt für sein 1947 fertiggestelltes Stauwehr, das Markala-Wehr, welches als technisches Herzstück des Office du Niger dient. Das fast 2,7 Kilometer lange Bauwerk reguliert den Wasserstand des Niger und ermöglicht die Bewässerung des riesigen Reis- und Zuckerrohranbaugebiets im Inneren Delta. Die Stadt wurde während der französischen Kolonialzeit gegründet, um Arbeiter für den Wehrbau zu beherbergen, und behielt ihren multikulturellen Charakter bis heute. Markala ist auch für seine traditionellen Fischer der Bozo-Volksgruppe bekannt, die mit großen Wurfnetzen Kapitäne und Welse fangen. Die Region ist landwirtschaftlich von zentraler Bedeutung für Mali und ein Schauplatz für Studien zur westafrikanischen Hydrologie. Wirtschaftsgeografie K7 — Wasserbauwerke Afrikas.",
"kolondieba-cities-v2": "Kolondiéba im Süden Malis liegt in einer waldreichen Savannenlandschaft nahe der Grenze zur Elfenbeinküste. Die Stadt ist Verwaltungszentrum eines gleichnamigen Kreises und gilt als wichtige Drehscheibe für den grenzüberschreitenden Handel mit Kaffee, Kakao und Holzprodukten. Die Bevölkerung ist überwiegend Bambara und Senufo, mit traditionellen Lehmhäusern und Hirsespeichern, die das Dorfbild prägen. Kolondiéba ist umgeben von Wäldern, in denen Karité-Bäume (Sheabutter) und Néré-Bäume wachsen, deren Früchte wichtige Einkommensquellen für die Frauen der Region sind. Die Region produziert auch Baumwolle und Mais. Bildungseinrichtungen und ein neues Krankenhaus haben den Ort zu einem regionalen Zentrum gemacht. Wirtschaftsgeografie K7 — westafrikanische Grenzhandelsstädte.",
"kati-cities-v2": "Kati liegt rund 15 Kilometer nordwestlich von Bamako und ist als wichtigste Garnisonsstadt Malis bekannt. Die historische Militärbasis wurde während der französischen Kolonialzeit gegründet und beherbergt bis heute den Hauptsitz der malischen Streitkräfte. Berühmt-berüchtigt wurde die Stadt durch die Militärputsche von 2012 und 2020, die beide vom Stützpunkt Kati ausgingen. Neben ihrer militärischen Bedeutung ist Kati ein bedeutendes Handelszentrum mit einem der größten Märkte Malis, der täglich Tausende Händler aus dem Umland anzieht. Die Stadt wächst rasant als Vorort von Bamako und beherbergt heute über 100.000 Einwohner. Die hügelige Landschaft und das relativ kühle Klima machen sie auch zu einem beliebten Wohnort für Pendler. Politische Geografie K7 — Hauptstadtregionen Afrikas.",
"gao-cities-v2": "Gao am Niger im Nordosten Malis war einst die Hauptstadt des mächtigen Songhai-Reiches, das im 15. und 16. Jahrhundert weite Teile Westafrikas beherrschte. Die Stadt erlebte unter Askia Mohammed I. (1493-1528) ihre Blütezeit als Zentrum islamischer Gelehrsamkeit und transsaharanischen Handels. Das Grab von Askia, eine pyramidenförmige Lehmkonstruktion aus dem Jahr 1495, gehört zum UNESCO-Weltkulturerbe. Heute ist Gao eine wichtige Hafenstadt mit etwa 90.000 Einwohnern, geprägt von Songhai, Tuareg und Fulani. Die Region war in den letzten Jahrzehnten Schauplatz politischer und sicherheitspolitischer Konflikte. Trotzdem bleibt Gao ein bedeutendes kulturelles Zentrum mit einem berühmten Wochenmarkt und einer reichen musikalischen Tradition. Geschichte K7 — afrikanische Reiche.",
"bougouni-cities-v2": "Bougouni im Süden Malis ist Hauptstadt der gleichnamigen Region und gilt als wichtiger Knotenpunkt zwischen Bamako und der Elfenbeinküste an der Nationalstraße RN7. Die Stadt mit etwa 60.000 Einwohnern liegt in einer waldreichen Region, die für ihre Goldminen, Baumwollproduktion und Sheabutter-Verarbeitung bekannt ist. Bougouni ist das Zentrum der Wassoulou-Region, einer kulturellen Landschaft, die für ihre einzigartige Musiktradition berühmt ist — Künstlerinnen wie Oumou Sangaré haben den Wassoulou-Stil weltweit populär gemacht. Die Bevölkerung ist überwiegend Bambara und Fulani, mit einer starken islamischen Tradition. Goldförderung im industriellen und handwerklichen Maßstab prägt zunehmend die regionale Wirtschaft. Wirtschaftsgeografie K7 — westafrikanische Goldregionen.",
"tombouctou-cities-v2": "Timbuktu, die legendäre 'Stadt der 333 Heiligen' am Südrand der Sahara, war vom 13. bis 16. Jahrhundert eines der bedeutendsten Zentren islamischer Gelehrsamkeit und transsaharanischen Handels weltweit. Unter dem Mali- und später Songhai-Reich beherbergte die Stadt die berühmte Sankoré-Universität mit angeblich 25.000 Studierenden und Bibliotheken mit Hunderttausenden von Manuskripten. Die drei großen Lehmmoscheen Djinguereber, Sankoré und Sidi Yahia gehören zum UNESCO-Weltkulturerbe. Heute hat Timbuktu rund 55.000 Einwohner und ist Symbol für Wissen und Ferne in der westlichen Vorstellung. Die Bevölkerung umfasst Songhai, Tuareg, Araber und Fulani. Klimawandel und politische Instabilität haben die Stadt zur gefährdeten UNESCO-Stätte gemacht. Geschichte K7 — Wissenschaftszentren der islamischen Welt.",
"banamba-cities-v2": "Banamba in der Region Koulikoro ist Hauptstadt eines gleichnamigen Kreises und ein wichtiges Handelszentrum nördlich von Bamako. Die Stadt war im 19. Jahrhundert Schauplatz heftiger Kämpfe zwischen den Bambara-Königreichen und dem Toucouleur-Reich von El Hadj Omar Tall. Heute lebt Banamba vom Viehhandel, der Hirse- und Erdnussproduktion sowie vom Handwerk, insbesondere von Schmieden und Webern. Der Wochenmarkt von Banamba ist einer der größten in der Region und zieht Händler aus dem ganzen Sahel an. Die Bevölkerung besteht überwiegend aus Bambara, Soninke und Fulani, mit einer starken islamischen Tradition. In der Umgebung wachsen Karité- und Néré-Bäume, deren Verarbeitung wichtige Einkommensquellen für lokale Frauenkooperativen darstellen. Wirtschaftsgeografie K7 — Sahelhandelsstädte.",
"san-cities-v2": "San in der Region Ségou liegt an der Kreuzung wichtiger Handelsstraßen zwischen Bamako, Mopti und Burkina Faso und gilt als eines der bedeutendsten kulturellen Zentren der Bambara-Bobo-Region. Die Stadt mit über 70.000 Einwohnern ist berühmt für ihr jährliches Janyé-Maskenfest, bei dem die Bobo ihre traditionellen Holzmasken und Tänze vorführen. San war historisch ein wichtiger Karawanenposten und ist heute ein Verkehrsknotenpunkt mit Anschluss an die Nationalstraße RN6. Wirtschaftlich dominiert die Landwirtschaft mit Hirse-, Mais- und Reisanbau sowie Viehzucht. Die Bobo-Bevölkerung praktiziert eine einzigartige Mischung aus Animismus und Islam. Die Architektur der Stadt zeigt die typische sudano-sahelische Lehmbauweise mit charakteristischen Speichern. Kulturgeografie K7 — afrikanische Maskentraditionen.",
"koulikoro-cities-v2": "Koulikoro liegt etwa 60 Kilometer nordöstlich von Bamako am Niger und ist Hauptstadt der gleichnamigen Region. Die Stadt war historisch der Endpunkt der schiffbaren Strecke des Niger ab Bamako während der Trockenzeit und entwickelte sich daher zu einem wichtigen Hafen und Eisenbahnknotenpunkt. Heute beherbergt Koulikoro große Industrieanlagen, darunter eine Ölmühle, eine Zementfabrik und Mühlen, sowie das größte Pflanzenölunternehmen Malis (Huicoma). In Koulikoro befindet sich auch die École de Maintien de la Paix Alioune Blondin Beye, ein international bedeutendes Friedensschulungszentrum der ECOWAS. Der Stein 'Soso Bala' (Dschunnnaga) gilt als heilig und ist mit der Soundjata-Keita-Legende des Mali-Reiches verbunden. Wirtschaftsgeografie K7 — afrikanische Industriezentren.",
"djenne-cities-v2": "Djenné im Inneren Niger-Delta ist eine der ältesten Städte Subsahara-Afrikas, deren Ursprünge bis ins 3. Jahrhundert v. Chr. zurückreichen (Djenné-Djeno). Die Große Moschee von Djenné, 1907 wieder aufgebaut, gilt als das größte Lehmziegelbauwerk der Welt und ist UNESCO-Weltkulturerbe. Jedes Jahr im Frühjahr findet das Crepissage-Festival statt, bei dem die gesamte Bevölkerung gemeinsam die Außenwände der Moschee mit frischem Lehmputz erneuert. Djenné war vom 13. bis 16. Jahrhundert ein bedeutendes Handels- und Gelehrtenzentrum, das mit Timbuktu verbunden war. Die historische Altstadt mit etwa 2.000 traditionellen Lehmhäusern in sudano-sahelischer Architektur ist ebenfalls UNESCO-geschützt. Heute leben rund 33.000 Menschen in der Stadt, überwiegend Songhai, Bozo und Fulani. Geschichte K7 — Lehmarchitektur Afrikas.",
"kidal-cities-v2": "Kidal liegt im äußersten Nordosten Malis am Rand der Sahara, am Fuße des Adrar des Ifoghas, eines zerklüfteten Sandsteingebirges. Die Stadt ist das traditionelle Zentrum der Tuareg-Konföderation der Ifoghas und Hauptstadt der gleichnamigen Region. Mit etwa 25.000 Einwohnern gehört Kidal zu den isoliertesten Städten Malis — die nächstgelegene asphaltierte Straße ist mehrere hundert Kilometer entfernt. Die Region wurde mehrfach Schauplatz von Tuareg-Aufständen, zuletzt 2012. Geografisch ist Kidal von Bedeutung als Übergangszone zwischen Sahel und echter Wüste, mit nomadischer Lebensweise, Kameltransport und einer einzigartigen Tuareg-Kultur, die sich in Sprache (Tamasheq), Musik und Schrift (Tifinagh) ausdrückt. Geografie K7 — Saharanrandregionen.",
"macina-cities-v2": "Macina in der Region Ségou liegt im Inneren Niger-Delta und war historisch das Zentrum des Macina-Reiches, das 1818 vom Fulani-Gelehrten Sékou Amadou Boubou gegründet wurde. Dieses theokratische islamische Reich, auch als Diina von Hamdullahi bekannt, prägte die Region kulturell und religiös bis zur Eroberung durch El Hadj Omar Tall im Jahr 1862. Heute ist Macina ein wichtiges Zentrum der Reisproduktion im Rahmen des Office du Niger und ein Knotenpunkt für Viehzucht der Fulani-Hirten. Die Bevölkerung lebt überwiegend von Landwirtschaft, Fischerei und transhumanter Viehhaltung. Die typische Lehmarchitektur und die jährlichen Wanderungen der Rinderherden durch die Auen des Niger machen die Region zu einem ethnografischen Schatz. Geschichte K7 — afrikanische Theokratien.",
"dire-cities-v2": "Diré in der Region Timbuktu liegt am Niger und ist ein wichtiger Flusshafen im Inneren Niger-Delta. Die Stadt mit rund 18.000 Einwohnern ist überwiegend von Songhai bewohnt und lebt von Reisanbau, Fischerei und Handel. Diré ist berühmt für seinen 'Floating Rice', eine Reissorte, die mit dem steigenden Wasserstand des Niger mitwächst und bis zu fünf Meter hohe Halme entwickeln kann. Die Stadt war historisch ein wichtiger Etappenort auf der Flussroute zwischen Timbuktu und Mopti. Im Hafen verkehren traditionelle Pinassen, die Salz, Hirse und Trockenfisch transportieren. Die Region hat in den letzten Jahrzehnten unter Dürren und Wüstenausbreitung gelitten, was die landwirtschaftliche Produktion herausfordert. Geografie K7 — afrikanische Flussdeltas.",
"bandiagara-cities-v2": "Bandiagara ist die Hauptstadt der gleichnamigen Region und das Tor zum berühmten Pays Dogon, einem UNESCO-geschützten Kultur- und Naturerbe. Die Stadt liegt am Rand der Falaise de Bandiagara, einer 200 Kilometer langen, bis zu 500 Meter hohen Sandsteinklippe, an deren Wänden die Dogon seit dem 14. Jahrhundert ihre einzigartigen Lehm-Dörfer errichtet haben. Bandiagara selbst hat etwa 18.000 Einwohner und ist Verwaltungs- und Handelszentrum für die rund 700 Dogon-Dörfer der Region. Die Dogon sind weltberühmt für ihre komplexe Kosmologie, ihre Maskentänze (Dama-Zeremonie) und ihre astronomischen Kenntnisse über den Sirius-Stern. Vor 2012 war die Region ein wichtiges Tourismusziel. Kulturgeografie K7 — UNESCO-Stätten Afrikas.",
"goundam-cities-v2": "Goundam in der Region Timbuktu liegt am Faguibine-See, einem der größten Seen Westafrikas. Die Stadt mit rund 14.000 Einwohnern ist ein wichtiges Verwaltungszentrum am Übergang zwischen Niger-Binnendelta und Sahara. Der Faguibine-See, der historisch eine wichtige Wasserquelle und ein bedeutendes Fischereigebiet war, ist seit den 1970er Jahren aufgrund von Dürren und Versandung weitgehend ausgetrocknet. Die Bevölkerung von Goundam besteht aus Songhai, Tuareg, Mauren und Fulani und lebt von Reisanbau, Viehzucht und Handel. Programme zur Renaturierung des Sees laufen seit Jahren mit internationaler Hilfe. Goundam war im 16. Jahrhundert Teil des Songhai-Reichs und ist auch heute kulturell und historisch eng mit Timbuktu verbunden. Geografie K7 — Sahelseen Afrikas.",
"kita-cities-v2": "Kita in der Region Kayes ist eine wichtige Stadt am Eisenbahnstrang Dakar-Niger, etwa 180 Kilometer westlich von Bamako. Die Stadt ist berühmt für den heiligen Berg Kita-Kourou, der eine wichtige Rolle in der Mande-Mythologie spielt und mit dem legendären Reichsgründer Soundjata Keïta verbunden ist. Jedes Jahr im Februar findet hier eine große katholische Wallfahrt zur Marienstatue auf dem Berg statt — ein einzigartiges Phänomen im überwiegend muslimischen Mali. Kita ist auch ein wichtiges Zentrum der Erdnussproduktion und des Baumwollhandels. Die Bevölkerung umfasst etwa 47.000 Einwohner, überwiegend Malinké und Fulani, mit einer reichen Musiktradition. Kita gilt als Wiege der Mande-Kultur und der westafrikanischen Griot-Tradition. Geschichte K7 — westafrikanische Kulturwiegen.",
"kenieba-cities-v2": "Kéniéba im äußersten Westen Malis ist Hauptstadt eines gleichnamigen Kreises in der Region Kayes und liegt im Goldgürtel von Bambouk, einem der ältesten Goldabbaugebiete der Welt. Bereits im Mittelalter lieferten die Goldminen dieser Region das Gold, das über transsaharanische Karawanen nach Nordafrika und Europa gelangte und das Mali-Reich zu legendärem Reichtum verhalf. Heute ist Kéniéba das Zentrum der industriellen Goldförderung Malis mit mehreren großen Minen wie Loulo-Gounkoto und Tabakoto. Die Stadt erlebt durch den Bergbau-Boom einen rasanten Wandel mit zuwandernden Arbeitern aus ganz Westafrika. Die ursprüngliche Bevölkerung der Malinké lebt von handwerklichem Goldschürfen, Landwirtschaft und Handel. Wirtschaftsgeografie K7 — Goldförderung Westafrikas.",
"bafoulabe-cities-v2": "Bafoulabé in der Region Kayes liegt am Zusammenfluss von Bafing und Bakoye, die hier den Senegal-Fluss bilden — daher der Name 'Bafoulabé', was in Malinké 'Treffen der zwei Flüsse' bedeutet. Die Stadt mit rund 10.000 Einwohnern war im 19. Jahrhundert ein wichtiger französischer Militärposten und Endpunkt der frühen Kolonisierungsbemühungen am Senegal. Heute lebt Bafoulabé von Landwirtschaft, Fischerei und vom nahegelegenen Manantali-Staudamm, der seit 1988 Wasserkraft für Mali, Senegal und Mauretanien liefert. Die Region ist landschaftlich beeindruckend mit Wasserfällen und Galeriewäldern entlang der Flüsse. Die Bevölkerung besteht überwiegend aus Khassonké und Malinké mit einer starken Tradition mündlicher Überlieferung. Geografie K7 — Flusszusammenflüsse Afrikas.",
"diema-cities-v2": "Diéma in der Region Kayes ist Hauptstadt eines gleichnamigen Kreises und ein wichtiger Knotenpunkt an der Nationalstraße RN3 zwischen Bamako und Kayes. Die Stadt liegt in der trockenen Sahelzone und ist Zentrum für die Soninké-Bevölkerung, eine der ältesten und kulturreichsten Volksgruppen Westafrikas. Die Soninké gelten als Gründer des Ghana-Reiches (8.-11. Jahrhundert) und haben eine ausgeprägte Migrationstradition — viele Familien haben Mitglieder, die als Arbeiter nach Frankreich oder in andere afrikanische Länder ausgewandert sind und durch Rücküberweisungen die lokale Wirtschaft prägen. Diéma lebt von Viehzucht, Hirse- und Erdnussanbau sowie von einem wichtigen Wochenmarkt. Die Region kämpft mit zunehmender Wüstenbildung und Wasserknappheit. Wirtschaftsgeografie K7 — Migration und Entwicklung in Afrika.",
"kolokani-cities-v2": "Kolokani in der Region Koulikoro liegt etwa 110 Kilometer nördlich von Bamako an der Straße nach Nara. Die Stadt mit rund 17.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und gilt als wichtiges Zentrum für die Bambara-Kultur. Kolokani ist umgeben von einer Trockensavannen-Landschaft mit Karité-, Néré- und Baobab-Bäumen, die wichtige Einkommensquellen für die lokale Bevölkerung darstellen. Die Wirtschaft basiert auf Hirse-, Erdnuss- und Baumwollanbau sowie auf Viehzucht. Kolokani hat in den letzten Jahren von Investitionen in Solarenergie und ländliche Elektrifizierung profitiert. Die Stadt ist auch bekannt für ihren Wochenmarkt, der Händler aus dem gesamten Sahel anzieht. Die Bevölkerung ist überwiegend Bambara und Fulani mit einer starken islamischen Tradition. Wirtschaftsgeografie K7 — Sahelzonen.",
"kangaba-cities-v2": "Kangaba am Niger ist eine kleine Stadt in der Region Koulikoro, die in der Geschichte Westafrikas eine zentrale Rolle spielte. Hier befindet sich der Kamablon, ein heiliges, mit Stroh gedecktes Haus, das alle sieben Jahre in einer feierlichen Zeremonie neu eingedeckt wird — ein UNESCO-anerkanntes immaterielles Kulturerbe. Kangaba gilt als Wiege des Mali-Reiches: Hier soll Soundjata Keïta um 1235 die berühmte Mande-Charta (Kurukan Fuga) verkündet haben, eine der ältesten Verfassungen der Welt mit Bestimmungen zu Menschenrechten. Die Stadt liegt nahe der Grenze zu Guinea und ist eng mit der Malinké-Kultur und der Griot-Tradition verbunden. Kangaba ist umgeben von Goldminen, die seit Jahrhunderten ausgebeutet werden. Geschichte K7 — afrikanische Verfassungstraditionen.",
"fana-cities-v2": "Fana in der Region Koulikoro ist eine wichtige Marktstadt an der Nationalstraße RN6 zwischen Bamako und Ségou, etwa 130 Kilometer östlich der Hauptstadt. Mit rund 20.000 Einwohnern ist Fana ein blühendes Handelszentrum, dessen Wochenmarkt zu den bedeutendsten der Region gehört und wöchentlich Tausende Händler aus dem Umland anzieht. Die Wirtschaft basiert auf Landwirtschaft, insbesondere Hirse, Mais, Erdnüssen und Baumwolle, sowie auf Viehzucht und Handwerk. Die Bevölkerung ist überwiegend Bambara, mit einer starken Tradition von Schmieden und Webern. Fana ist auch bekannt für seine traditionellen Musik- und Tanzgruppen, die bei großen Festlichkeiten in der Region auftreten. Die Stadt entwickelt sich zunehmend zu einem regionalen Bildungs- und Gesundheitszentrum. Wirtschaftsgeografie K7 — westafrikanische Marktstädte.",
"kadiolo-cities-v2": "Kadiolo im äußersten Süden Malis ist Hauptstadt eines gleichnamigen Kreises in der Region Sikasso, direkt an der Grenze zur Elfenbeinküste. Die Stadt mit rund 12.000 Einwohnern ist ein wichtiger Grenzübergang und Handelsposten für den Warenverkehr zwischen Mali und der Elfenbeinküste. Die Region ist eine der fruchtbarsten Malis mit hohen Niederschlägen und einem subtropischen Klima, was den Anbau von Mais, Reis, Yams und Kakao ermöglicht. Kadiolo ist auch ein Zentrum der Senufo-Kultur, einer Volksgruppe, die für ihre kunstvollen Holzschnitzereien, Masken und Webarbeiten weltberühmt ist. Die berühmte Poro-Initiationsgesellschaft der Senufo hat hier ihre traditionellen Heiligtümer. Goldförderung im handwerklichen Maßstab spielt ebenfalls eine wichtige Rolle. Kulturgeografie K7 — Senufo-Kunsttraditionen.",
"yanfolila-cities-v2": "Yanfolila in der Region Sikasso liegt im Süden Malis, nahe der Grenze zu Guinea, im kulturellen Herzen der Wassoulou-Region. Die Stadt mit etwa 12.000 Einwohnern ist Verwaltungssitz eines gleichnamigen Kreises und ein wichtiges Zentrum für die handwerkliche und industrielle Goldförderung. Yanfolila beherbergt seit 2017 eine moderne Goldmine, die von ausländischen Investoren betrieben wird und einer der größten Arbeitgeber der Region ist. Die Wassoulou-Kultur ist berühmt für ihre einzigartige Musiktradition mit dem Kamale Ngoni (Jungen-Harfe), die international durch Künstlerinnen wie Oumou Sangaré bekannt wurde. Die Bevölkerung ist überwiegend Fulani-Wassoulounké und lebt traditionell von Viehzucht, Goldwäsche und Landwirtschaft. Wirtschaftsgeografie K7 — Wassoulou-Region.",
"yorosso-cities-v2": "Yorosso in der Region Sikasso ist Hauptstadt eines gleichnamigen Kreises und liegt im Osten der Region nahe der Grenze zu Burkina Faso. Die Stadt mit rund 9.000 Einwohnern ist Zentrum eines wichtigen Baumwollanbaugebiets und Drehscheibe für den Handel mit landwirtschaftlichen Erzeugnissen. Die Bevölkerung ist überwiegend Minianka, eine Volksgruppe, die für ihre traditionelle Animisten-Religion und ihre kunstvollen Masken bekannt ist. Die Minianka praktizieren eine einzigartige Form der traditionellen Heilkunde und Initiation. Yorosso liegt in einer waldreichen Savannenlandschaft mit Karité- und Néré-Bäumen, deren Verarbeitung wichtige Einkommensquellen für die lokalen Frauenkooperativen darstellen. Die Region kämpft mit Herausforderungen wie Wüstenbildung und unzureichender Infrastruktur. Wirtschaftsgeografie K7 — Baumwollregionen.",
"bla-cities-v2": "Bla in der Region Ségou ist eine wichtige Marktstadt an der Nationalstraße RN6 zwischen Ségou und San. Die Stadt mit rund 35.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein bedeutendes Handelszentrum für Hirse, Mais und Erdnüsse. Bla ist berühmt für seinen Wochenmarkt, der zu den größten in Zentralmali gehört, sowie für seine traditionellen Lehmziegelarchitektur. Die Bevölkerung ist eine Mischung aus Bambara, Bobo und Fulani, was sich in der reichen kulturellen Tradition der Stadt widerspiegelt. Bla liegt in einer Savannenlandschaft mit zahlreichen Baobab-Bäumen, die in der lokalen Mythologie eine wichtige Rolle spielen. Die Stadt entwickelt sich zunehmend zu einem regionalen Bildungs- und Gesundheitszentrum mit neuen Schulen und einem ausgebauten Krankenhaus. Wirtschaftsgeografie K7 — westafrikanische Handelsstädte.",
"tominian-cities-v2": "Tominian in der Region Ségou liegt im Osten Malis nahe der Grenze zu Burkina Faso. Die Stadt mit rund 12.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und kulturelles Zentrum der Bobo-Bevölkerung. Die Bobo sind eine alte westafrikanische Volksgruppe, die für ihre traditionelle Religion, ihre kunstvollen Holzmasken und ihre einzigartige Architektur mit fortifizierten Lehmgehöften bekannt ist. Tominian ist ein wichtiger Standort katholischer Mission seit der Kolonialzeit, mit einer beeindruckenden Kathedrale aus den 1950er Jahren. Die Wirtschaft basiert auf Hirse-, Mais- und Erdnussanbau sowie auf der Verarbeitung von Sheabutter und Néré-Früchten. Die Stadt ist auch bekannt für ihre Bobo-Maskenfeste, die wichtige rituelle Funktionen erfüllen. Kulturgeografie K7 — Bobo-Kultur.",
"bankass-cities-v2": "Bankass in der Region Mopti liegt am südlichen Rand der Falaise de Bandiagara und gilt als zweites wichtiges Tor zum Pays Dogon. Die Stadt mit rund 13.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein bedeutendes Handelszentrum zwischen Dogon-Hochland und Burkina Faso. Bankass ist umgeben von Dogon-Dörfern in der typischen Lehmziegelarchitektur und beherbergt einen der bekanntesten Wochenmärkte des Pays Dogon. Die Bevölkerung umfasst Dogon, Fulani und Bambara, deren Zusammenleben in den letzten Jahren von Konflikten um Weide- und Ackerland geprägt war. Die Region ist landschaftlich beeindruckend mit Sandsteinklippen, traditionellen Speichern (Toguna) und heiligen Wasserstellen. Bankass ist auch Ausgangspunkt für Wanderungen entlang der Falaise. Kulturgeografie K7 — Dogon-Land.",
"koro-cities-v2": "Koro in der Region Mopti liegt im äußersten Osten Malis nahe der Grenze zu Burkina Faso, am südöstlichen Rand des Pays Dogon. Die Stadt mit rund 14.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein wichtiger Grenzübergang. Koro ist Zentrum einer landwirtschaftlich geprägten Region, in der Hirse, Erdnüsse und Zwiebeln angebaut werden. Die Bevölkerung ist eine Mischung aus Dogon, Fulani und Mossi, wobei letztere durch ihre Nähe zu Burkina Faso besonders präsent sind. Die Region war in den letzten Jahren leider Schauplatz interethnischer Konflikte zwischen sesshaften Dogon-Bauern und nomadischen Fulani-Hirten. Trotz der Herausforderungen bleibt Koro ein wichtiges Handels- und Kulturzentrum mit einem lebhaften Wochenmarkt. Geografie K7 — westafrikanische Grenzregionen.",
"douentza-cities-v2": "Douentza in der Region Mopti liegt am Fuße der Hombori-Berge an der Nationalstraße RN16 zwischen Mopti und Gao. Die Stadt mit rund 18.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein wichtiger Verkehrsknotenpunkt zwischen Zentral- und Nordmali. In der Nähe befindet sich der berühmte Hand of Fatima (Main de Fatima), eine Gruppe spektakulärer Sandsteintürme, die zu den geologischen Wahrzeichen Westafrikas zählen — der höchste Turm misst 600 Meter. Douentza ist auch Tor zum Gourma-Reservat, einem der wichtigsten Schutzgebiete für die letzten westafrikanischen Wüstenelefanten. Die Bevölkerung umfasst Fulani, Songhai, Tuareg und Dogon. Die Region war in den letzten Jahren von Sicherheitsproblemen betroffen. Geografie K7 — Sandsteinformationen Afrikas.",
"tenenkou-cities-v2": "Tenenkou in der Region Mopti liegt im Inneren Niger-Delta und ist Hauptstadt eines gleichnamigen Kreises. Die Stadt mit rund 10.000 Einwohnern lebt vom Reisanbau, von der Fischerei und vor allem von der Viehzucht. Tenenkou ist Zentrum der Fulani-Pastoralisten, die jedes Jahr im Dezember beim spektakulären Dégal-Fest ihre Rinderherden über den Niger schwimmen lassen, um die fruchtbaren Burgu-Weiden des Inneren Deltas zu erreichen. Diese Transhumanz ist ein UNESCO-anerkanntes immaterielles Kulturerbe. Die Region war historisch Teil des Macina-Reiches und prägt bis heute die islamische Kultur Westafrikas. In jüngerer Zeit war Tenenkou leider Schauplatz von Konflikten zwischen Fulani-Hirten und sesshaften Bauern. Geografie K7 — Niger-Binnendelta.",
"youwarou-cities-v2": "Youwarou in der Region Mopti liegt am Lac Débo, dem größten See im Inneren Niger-Delta, und ist Hauptstadt eines gleichnamigen Kreises. Die Stadt mit rund 6.000 Einwohnern ist ein wichtiges Zentrum für Fischerei und Viehzucht. Der Lac Débo ist ein bedeutendes Vogelschutzgebiet und Teil des Ramsar-Feuchtgebiets, in dem jährlich Hunderttausende Zugvögel aus Europa überwintern, darunter Pelikane, Reiher und Spateneulen. Die Bozo-Fischer von Youwarou nutzen seit Jahrhunderten traditionelle Fangtechniken mit großen Wurfnetzen aus Pinassen. Im Dezember findet das spektakuläre kollektive Fischfest 'Tondé' statt. Die Region kämpft mit den Folgen des Klimawandels und einem schwankenden Wasserstand des Niger. Naturgeografie K7 — afrikanische Feuchtgebiete.",
"niafunke-cities-v2": "Niafunké in der Region Timbuktu liegt am Niger und ist Hauptstadt eines gleichnamigen Kreises. Die Stadt mit rund 14.000 Einwohnern ist weltberühmt durch den großen Bluesmusiker Ali Farka Touré (1939-2006), der hier lebte und nach seinem internationalen Erfolg Bürgermeister wurde. Touré gilt als einer der einflussreichsten afrikanischen Musiker und gewann mehrere Grammy Awards. Niafunké lebt vom Reisanbau und der Fischerei im fruchtbaren Niger-Binnendelta. Die Bevölkerung besteht überwiegend aus Songhai mit einer starken kulturellen Tradition. Touré investierte einen Großteil seiner Einnahmen in die Stadt — er finanzierte Brunnen, Schulen und eine Mühle. Heute pflegt seine Familie sein musikalisches Erbe und ein Festival in Niafunké. Kulturgeografie K7 — afrikanische Musiklegenden.",
"gourma-rharous-cities-v2": "Gourma-Rharous in der Region Timbuktu liegt am Niger und ist Hauptstadt eines gleichnamigen Kreises. Die Stadt mit rund 8.000 Einwohnern ist ein wichtiges Zentrum für die Songhai- und Tuareg-Bevölkerung. Die Region Gourma am Südufer des Niger ist berühmt für ihre seltenen Wüstenelefanten, die letzten ihrer Art in Westafrika — eine Population von rund 350 Tieren wandert jährlich auf einer der längsten bekannten Elefantenwanderrouten der Welt. Das Gourma-Reservat ist ein wichtiges Naturschutzgebiet und Heimat von Giraffen, Antilopen und vielen Vogelarten. Die Bevölkerung lebt von Reisanbau, Fischerei und nomadischer Viehzucht. Die Region war in den letzten Jahren leider Schauplatz von Sicherheitsproblemen. Naturgeografie K7 — afrikanische Wildtiere.",
"bourem-cities-v2": "Bourem in der Region Gao liegt am Niger nördlich von Gao, dort wo der Fluss seine markante Schleife nach Westen vollzieht — ein Phänomen, das als Niger-Buckel bekannt ist. Die Stadt mit rund 6.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein wichtiger strategischer Punkt am Übergang zwischen Sahel und Sahara. Historisch war Bourem ein bedeutender Karawanenposten an der Route zwischen Timbuktu und den Salzminen von Taoudenni. Die Bevölkerung besteht aus Songhai, Tuareg und Arabern und lebt von Viehzucht, Fischerei und kleinem Handel. Die Region ist landschaftlich beeindruckend mit Dünen am Flussufer und einer einzigartigen Tier- und Pflanzenwelt am Übergang zur Wüste. Geografie K7 — Niger-Knie und Saharaübergang.",
"ansongo-cities-v2": "Ansongo in der Region Gao liegt am Niger südöstlich von Gao und ist Hauptstadt eines gleichnamigen Kreises. Die Stadt mit rund 12.000 Einwohnern ist ein wichtiges Verwaltungs- und Handelszentrum am Übergang zwischen dem Niger-Tal und der Sahel-Region. In der Nähe von Ansongo befindet sich das gleichnamige Naturschutzgebiet, das Heimat der seltenen West-Giraffen und der letzten westafrikanischen Wüstenelefanten ist. Die Bevölkerung besteht überwiegend aus Songhai, Fulani und Tuareg, die traditionell von Reisanbau, Fischerei und Viehzucht leben. Ansongo war historisch Teil des Songhai-Reiches und ein wichtiger Etappenort auf den transsaharanischen Karawanenrouten. Die Region war in den letzten Jahren von Sicherheitsproblemen geprägt. Naturgeografie K7 — Sahel-Wildtiere.",
"menaka-cities-v2": "Ménaka im äußersten Osten Malis ist Hauptstadt der gleichnamigen Region und Verwaltungszentrum eines weitläufigen, dünn besiedelten Sahel-Gebiets. Die Stadt mit rund 11.000 Einwohnern liegt nahe der Grenze zu Niger und ist traditionell ein Zentrum der Tuareg- und Daoussak-Bevölkerung. Ménaka war historisch ein wichtiger Karawanenposten am Übergang zwischen West- und Zentralafrika und ist heute ein Zentrum für nomadische Viehzucht. In der Region wandern jährlich riesige Rinder-, Kamel- und Ziegenherden zwischen den Sahelweiden. Die Region war in den letzten Jahren leider Schauplatz heftiger Konflikte und beherbergt mehrere Vertriebenenlager. Trotz aller Herausforderungen bleibt Ménaka ein wichtiges kulturelles Zentrum mit reicher Tuareg-Musiktradition. Geografie K7 — Sahel-Nomadenkulturen.",
"tessalit-cities-v2": "Tessalit liegt im äußersten Norden Malis im Adrar des Ifoghas, einem zerklüfteten Sandsteingebirge in der Sahara, nahe der Grenze zu Algerien. Die kleine Stadt mit rund 4.000 Einwohnern ist von strategischer Bedeutung als nördlichster größerer Ort Malis und beherbergt einen wichtigen Militärflughafen. Tessalit ist traditionelles Zentrum der Tuareg-Konföderation der Ifoghas und liegt an alten Karawanenrouten zwischen Mali und Algerien. Das umliegende Adrar-Gebirge mit seinen Felsmalereien und Tuareg-Heiligtümern zählt zu den archäologisch bedeutendsten Regionen der Sahara. Die Bevölkerung lebt traditionell von Kamelzucht und kleinem Handel. Tessalit war in den letzten Jahrzehnten mehrfach Schauplatz von Tuareg-Aufständen und ist seitdem militärisch stark präsent. Geografie K7 — Sahararegionen Afrikas.",
"aguelhok-cities-v2": "Aguelhok liegt im äußersten Norden Malis in der Region Kidal, im Adrar des Ifoghas. Die kleine Stadt mit rund 3.000 Einwohnern liegt an der historischen Karawanenroute zwischen Kidal und der algerischen Grenze. Aguelhok ist traditionell ein Zentrum der Tuareg-Bevölkerung und lebt von Kamelzucht, kleinem Handel und vom Verkauf handwerklich gefertigter Tuareg-Schmuckstücke aus Silber. Die umliegende Wüstenlandschaft mit ihren markanten Sandsteinformationen ist Heimat seltener Wüstenflora und -fauna, darunter Mendes-Antilopen und Wüstenfüchse. Die Stadt war 2012 leider Schauplatz tragischer Ereignisse während der Tuareg-Rebellion. Trotz der Herausforderungen bewahrt die Tuareg-Gemeinschaft ihre einzigartige Kultur mit Tamasheq-Sprache, Tifinagh-Schrift und der berühmten 'Wüstenmusik' (Tishoumaren). Geografie K7 — Saharaoasen.",
"araouane-cities-v2": "Araouane ist eine winzige Wüstenoase rund 270 Kilometer nördlich von Timbuktu, mitten in der Sahara. Die Siedlung mit weniger als 300 Einwohnern liegt an der historischen Salzkarawanenroute zwischen Taoudenni und Timbuktu, die seit dem Mittelalter befahren wird. Araouane war im 15. und 16. Jahrhundert ein blühendes Handels- und Gelehrtenzentrum mit eigenen Koranschulen und Bibliotheken. Heute leben hier nur noch wenige Familien, die hauptsächlich von der Viehzucht und der Versorgung der Salzkarawanen leben, die zweimal jährlich aus Taoudenni vorbeiziehen. Diese Karawanen, Azalai genannt, transportieren Salzbarren auf Hunderten von Kamelen und gelten als eine der letzten lebendigen Karawanentraditionen Afrikas. Geografie K7 — Wüstenoasen Afrikas.",
"taoudenni-cities-v2": "Taoudenni ist eine Salzminensiedlung im äußersten Norden Malis, etwa 700 Kilometer nordnordwestlich von Timbuktu, mitten in der Sahara. Hier wird seit dem 16. Jahrhundert auf einem ausgetrockneten Salzsee Steinsalz im Tiefbau abgebaut. Die Salzbarren werden in traditionellen, mehrwöchigen Kamelkarawanen (Azalai) nach Timbuktu transportiert — eine der letzten lebendigen Karawanentraditionen der Welt. Die Bedingungen in Taoudenni sind extrem: Temperaturen von über 50 °C im Sommer, kein Trinkwasser, keine Vegetation. Die Arbeiter, meist saisonale Migranten aus Timbuktu und Umgebung, leben in einfachen Salzziegel-Hütten. Historisch war das Taoudenni-Salz ein zentraler Handelsgut der transsaharanischen Wirtschaft. Wirtschaftsgeografie K7 — Salzhandel der Sahara.",
"yelimane-cities-v2": "Yélimané in der Region Kayes ist Hauptstadt eines gleichnamigen Kreises und liegt im äußersten Westen Malis nahe der Grenze zu Mauretanien. Die Stadt mit rund 12.000 Einwohnern ist ein wichtiges Zentrum der Soninké-Bevölkerung. Yélimané ist als 'Stadt der Auswanderung' bekannt — viele Familien haben Mitglieder, die als Arbeiter nach Frankreich migriert sind, was die lokale Wirtschaft durch Rücküberweisungen prägt. Diese 'navetane'-Tradition reicht bis in die 1950er Jahre zurück. Die Wirtschaft basiert auf Hirse-, Erdnuss- und Sorghum-Anbau sowie auf Viehzucht. Die Region ist von zunehmender Wüstenbildung betroffen, was Anpassungsprojekte erforderlich macht. Yélimané ist auch bekannt für seine traditionelle Soninké-Musik mit dem typischen Saiteninstrument Soron. Wirtschaftsgeografie K7 — Migration und Entwicklung.",
"dioila-cities-v2": "Dioïla in der Region Koulikoro ist Hauptstadt eines gleichnamigen Kreises und liegt am Baoulé-Fluss, einem Nebenfluss des Niger. Die Stadt mit rund 21.000 Einwohnern ist ein wichtiges Handelszentrum zwischen Bamako und der Region Sikasso, etwa 160 Kilometer südöstlich der Hauptstadt. Dioïla ist Zentrum eines wichtigen Baumwoll- und Hirseanbaugebiets und beherbergt mehrere Verarbeitungsanlagen für landwirtschaftliche Produkte. Die Bevölkerung ist überwiegend Bambara mit einer reichen Tradition von Schmieden, Webern und Töpfern. Der Baoulé-Fluss bietet Wasser für die Bewässerungslandwirtschaft und ist auch ein wichtiges Fischereigebiet. Dioïla hat in den letzten Jahren von Investitionen in Infrastruktur und ländliche Elektrifizierung profitiert und entwickelt sich zu einem regionalen Bildungszentrum. Wirtschaftsgeografie K7 — Baumwollanbau Westafrikas.",
"baroueli-cities-v2": "Barouéli in der Region Ségou ist Hauptstadt eines gleichnamigen Kreises und liegt etwa 60 Kilometer westlich von Ségou. Die Stadt mit rund 15.000 Einwohnern ist Teil des Office du Niger-Bewässerungsgebiets und ein wichtiges Zentrum des Reisanbaus. Barouéli ist umgeben von einem dichten Netz aus Bewässerungskanälen, die seit den 1930er Jahren ausgebaut werden. Die Bevölkerung ist überwiegend Bambara mit einer starken landwirtschaftlichen Tradition. Neben Reis werden hier Hirse, Mais, Erdnüsse und Gemüse angebaut, und Geflügel- sowie Fischzucht sind wichtige Einkommensquellen. Die Stadt verfügt über mehrere Schulen, ein Krankenhaus und einen lebhaften Wochenmarkt. Barouéli ist ein typisches Beispiel für die landwirtschaftliche Transformation Malis durch koloniale und postkoloniale Bewässerungsprojekte. Agrargeografie K7 — Reisanbau Afrikas.",
"ouelessebougou-cities-v2": "Ouelessebougou in der Region Koulikoro liegt etwa 80 Kilometer südlich von Bamako an der Nationalstraße RN7 in Richtung Sikasso. Die Stadt mit rund 16.000 Einwohnern ist Hauptstadt eines gleichnamigen Kreises und ein wichtiger Verkehrsknotenpunkt am Übergang zwischen den Trockensavannen des Sahel und den feuchteren südlichen Regionen Malis. Ouelessebougou ist Zentrum einer landwirtschaftlich geprägten Region mit Hirse-, Mais-, Erdnuss- und Baumwollanbau. Die Bevölkerung ist überwiegend Bambara und Fulani mit einer reichen kulturellen Tradition. Die Stadt ist auch bekannt für ihre Schmiedekunst und Töpferei. In den letzten Jahren hat Ouelessebougou von zahlreichen NGO-Projekten in den Bereichen Bildung, Gesundheit und Wasserversorgung profitiert. Wirtschaftsgeografie K7 — westafrikanische Klimazonen.",
"nampala-cities-v2": "Nampala in der Region Ségou liegt im Norden des Office du Niger-Gebiets nahe der Grenze zu Mauretanien. Die Stadt mit rund 5.000 Einwohnern ist ein wichtiges Zentrum für Reisanbau und Viehzucht im Sahel. Nampala liegt an der nördlichen Grenze des Bewässerungsgebiets und markiert den Übergang zur Halbwüste. Die Bevölkerung besteht aus Fulani, Bambara und Mauren, die traditionell von transhumanter Viehzucht leben. Die Region war in den letzten Jahren leider Schauplatz von Sicherheitsproblemen und beherbergt mehrere Vertriebenenlager. Trotz der Herausforderungen bleibt Nampala ein wichtiges landwirtschaftliches Zentrum mit Reisanbau und Viehmärkten. Die Stadt ist auch ein wichtiger Etappenort auf den nomadischen Wanderrouten zwischen Sahel und Niger-Binnendelta. Geografie K7 — Sahelübergangszonen.",
"dialakoroba-cities-v2": "Dialakoroba in der Region Koulikoro liegt etwa 65 Kilometer südöstlich von Bamako an der Straße in Richtung Bougouni. Die Stadt mit rund 13.000 Einwohnern ist ein aufstrebendes Zentrum am Rande des Hauptstadtballungsraums und Handelsknotenpunkt für die umliegenden Dörfer. Dialakoroba liegt in einer fruchtbaren Region mit Hirse-, Mais-, Erdnuss- und Mangoanbau. Die Bevölkerung ist überwiegend Bambara und Fulani mit einer reichen kulturellen Tradition. Die Stadt ist bekannt für ihre Wochenmärkte, die Händler aus dem ganzen Umland anziehen, sowie für ihre traditionelle Schmiedekunst. In den letzten Jahren hat Dialakoroba durch die Nähe zur Hauptstadt und neue Verkehrsverbindungen ein rasantes Wachstum erlebt und entwickelt sich zu einem wichtigen Vorortzentrum von Bamako. Wirtschaftsgeografie K7 — afrikanische Hauptstadtregionen.",
"diabaly-cities-v2": "Diabaly in der Region Ségou liegt im Norden des Office du Niger-Bewässerungsgebiets, etwa 90 Kilometer nördlich von Niono. Die Stadt mit rund 10.000 Einwohnern ist ein wichtiges Zentrum für Reisanbau und Viehzucht. Diabaly markiert den nördlichen Rand der intensiven Bewässerungslandwirtschaft und den Übergang zur Sahel-Steppe. Die Bevölkerung ist eine Mischung aus Bambara, Fulani und Soninké, die von Reisanbau, Hirse, Erdnüssen und Viehzucht leben. Diabaly geriet 2013 in die internationalen Schlagzeilen, als die Stadt vorübergehend von bewaffneten Gruppen besetzt wurde, was die französische Operation Serval auslöste. Heute hat sich die Stadt erholt und entwickelt sich wieder zu einem regionalen Handelszentrum. Wirtschaftsgeografie K7 — Bewässerungsgrenzen.",
"sofara-cities-v2": "Sofara in der Region Mopti liegt im Inneren Niger-Delta südlich von Mopti am Bani-Fluss. Die Stadt mit rund 18.000 Einwohnern ist ein wichtiges Zentrum für die Bambara- und Marka-Bevölkerung. Sofara war historisch ein bedeutender Handelsposten an der Verbindung zwischen Djenné und Mopti und ist bis heute für ihren großen Markt bekannt, der alle fünf Tage Tausende Händler aus dem Umland anzieht. Die Stadt ist berühmt für ihre traditionelle sudano-sahelische Lehmziegelarchitektur, die der von Djenné ähnelt. Die Wirtschaft basiert auf Reisanbau, Fischerei und Handel. Sofara verfügt über eine bemerkenswerte Lehmmoschee, die als kleinere Schwester der Großen Moschee von Djenné gilt. Die Bevölkerung praktiziert eine reiche Tradition islamischer Gelehrsamkeit. Kulturgeografie K7 — Lehmziegelarchitektur.",
"beleko-cities-v2": "Béléko in der Region Koulikoro liegt etwa 100 Kilometer südöstlich von Bamako an der Nationalstraße in Richtung Bougouni. Die Stadt mit rund 12.000 Einwohnern ist ein wichtiges Zentrum für Landwirtschaft und Handel im südlichen Mali. Béléko liegt in einer fruchtbaren Savannenlandschaft mit Karité-, Néré- und Mangobäumen, die wichtige Einkommensquellen für die lokale Bevölkerung darstellen. Die Wirtschaft basiert auf Mais-, Hirse-, Erdnuss- und Baumwollanbau sowie auf Sheabutter-Verarbeitung durch Frauenkooperativen. Die Bevölkerung ist überwiegend Bambara und Malinké mit einer reichen Tradition mündlicher Überlieferung und Griot-Musik. Béléko ist bekannt für seine Wochenmärkte und entwickelt sich zunehmend zu einem regionalen Bildungszentrum mit neuen Schulen und einem ausgebauten Krankenhaus. Wirtschaftsgeografie K7 — Sheabutter-Produktion.",
"kignan-cities-v2": "Kignan in der Region Sikasso liegt etwa 30 Kilometer nördlich der Stadt Sikasso. Die kleine Stadt mit rund 9.000 Einwohnern ist ein wichtiges Zentrum für Landwirtschaft und Handel in einer der fruchtbarsten Regionen Malis. Kignan liegt in einer waldreichen Savannenlandschaft, die für ihren Mangoanbau weltbekannt ist — die Region produziert hochwertige Mangos, die nach Europa und in die Nachbarländer exportiert werden. Neben Mango werden hier Mais, Hirse, Erdnüsse und Baumwolle angebaut. Die Bevölkerung ist überwiegend Senufo und Bambara mit einer reichen Tradition von Maskentänzen und Holzschnitzereien. Die berühmte Senufo-Initiationsgesellschaft Poro hat hier ihre traditionellen Heiligtümer in heiligen Wäldern. Kignan ist auch bekannt für seine Töpfereien und kunstvollen Webarbeiten. Kulturgeografie K7 — Senufo-Kunsttraditionen.",
"zegoua-cities-v2": "Zégoua im äußersten Süden Malis liegt direkt an der Grenze zur Elfenbeinküste in der Region Sikasso. Die Stadt mit rund 8.000 Einwohnern ist einer der wichtigsten Grenzübergänge Malis und ein blühendes Handelszentrum für den Warenverkehr zwischen den beiden Ländern. Über Zégoua laufen erhebliche Mengen importierter Güter, die im Hafen von Abidjan ankommen, in Richtung Bamako. Die Stadt ist bekannt für ihre lebhaften Märkte und das ausgeprägte transnationale Handelsleben. Die Bevölkerung ist überwiegend Senufo und Bambara mit ausgeprägten kulturellen Verbindungen zur Elfenbeinküste. Die Wirtschaft basiert auf Handel, Mango-, Mais- und Reisanbau. Zégoua ist auch ein wichtiger Standort für die Verarbeitung tropischer Früchte. Wirtschaftsgeografie K7 — westafrikanische Grenzhandel.",
"niena-cities-v2": "Niéna in der Region Sikasso liegt zwischen Bougouni und Sikasso an der Nationalstraße RN7. Die Stadt mit rund 11.000 Einwohnern ist ein wichtiges Handelszentrum und ein Zentrum für die Senufo- und Minianka-Bevölkerung. Niéna ist umgeben von einer der waldreichsten Regionen Malis mit Karité-, Néré- und Iroko-Bäumen. Die Wirtschaft basiert auf Baumwoll-, Mais-, Hirse- und Mangoanbau sowie auf der Verarbeitung von Sheabutter durch lokale Frauenkooperativen. Die Senufo-Bevölkerung ist berühmt für ihre kunstvollen Holzmasken und Statuen, die in den Initiationsriten der Poro-Gesellschaft verwendet werden — diese Senufo-Kunst gehört zu den geschätztesten in westafrikanischen und internationalen Museumssammlungen. Niéna verfügt auch über eine reiche Tradition von Schmieden und Webern. Kulturgeografie K7 — Senufo-Skulpturen.",
}

# Verify all >= 600
for k,v in DE.items():
    n = len(v)
    if n < 600:
        print(f"WARN: {k} only {n} chars")

with open(PATH, encoding="utf-8") as f:
    src = f.read()

# Strategy: For each id in DE dict, find its descriptionAdvanced block,
# and either replace empty/short de field, or add a de field if absent.
id_re = re.compile(r'id:\s*"([^"]+)"')
ids = [(m.group(1), m.start()) for m in id_re.finditer(src)]

# Build segments
out = []
last = 0
modified = 0
for i, (poi_id, start) in enumerate(ids):
    end = ids[i+1][1] if i+1 < len(ids) else len(src)
    if poi_id not in DE:
        continue
    de_text = DE[poi_id]
    # find descriptionAdvanced block within [start, end)
    block = src[start:end]
    m = re.search(r'descriptionAdvanced:\s*\{', block)
    if not m:
        print(f"SKIP no descAdv: {poi_id}")
        continue
    inner_start = start + m.end()
    # find matching close
    depth = 1
    j = inner_start
    while j < len(src) and depth > 0:
        c = src[j]
        if c == '{': depth += 1
        elif c == '}': depth -= 1
        j += 1
    inner_end = j - 1  # before final }
    inner = src[inner_start:inner_end]

    # Look for `de:` field in inner
    de_field_re = re.compile(r'(\bde:\s*)"((?:[^"\\]|\\.)*)"')
    mm = de_field_re.search(inner)
    new_inner = None
    if mm:
        existing_len = len(mm.group(2))
        if existing_len >= 50:
            continue  # skip
        # replace
        new_inner = inner[:mm.start()] + f'{mm.group(1)}"{de_text}"' + inner[mm.end():]
    else:
        # need to insert de: at the start of inner
        # Find the first lang field to know indentation
        first_field = re.search(r'\n(\s*)(hu|ro|en):\s*"', inner)
        if first_field:
            indent = first_field.group(1)
            insertion = f'\n{indent}de: "{de_text}",'
            # insert after the opening (before first field)
            # inner starts right after "descriptionAdvanced: {" - the newline is part of inner
            # find the first newline+indent
            new_inner = insertion + inner
        else:
            new_inner = f'\n      de: "{de_text}",' + inner
    # Apply replacement to src by reconstructing
    src = src[:inner_start] + new_inner + src[inner_end:]
    modified += 1
    # adjust ids list positions: re-scan because src changed length
    ids = [(m.group(1), m.start()) for m in id_re.finditer(src)]

print(f"Modified: {modified}")

with open(PATH, "w", encoding="utf-8", newline="") as f:
    f.write(src)
print("Written.")
