"use client";
// MentalMathExplorer — Mental arithmetic with tens for Grade 2 (island i2)
// Modernized with centralized SVG library

import { memo } from "react";
import ExplorerEngine from "@/app/astro-biologie/games/ExplorerEngine";
import type { ExplorerDef, TopicDef } from "@/app/astro-biologie/games/ExplorerEngine";

// ─── Labels ───────────────────────────────────────────────────────────────────

const LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Mental Math Explorer",
    t1_title: "Adding Tens in Your Head",
    t1_text: "Adding tens is easy — just add the tens digits! 40 + 20: four tens + two tens = six tens = 60. No need to count by ones!",
    t1_b1: "40 + 20 = 4 tens + 2 tens = 6 tens = 60",
    t1_b2: "Tens numbers always end in 0",
    t1_b3: "Ask: how many tens in total?",
    t1_inst: "Start at 40 and add 20 — jump 2 tens forward!",
    t1_h1: "40 = 4 tens. Add 2 more: 4 + 2 = 6",
    t1_h2: "6 tens = 60 — tap 60!",
    t1_q: "What is 30 + 50?",
    t1_q_80: "80", t1_q_35: "35", t1_q_53: "53", t1_q_8: "8",
    t2_title: "Counting by Tens",
    t2_text: "When we count by tens, each next number is exactly 10 more: 20, 30, 40, 50 … The ones digit stays the SAME! Only the tens digit changes by 1.",
    t2_b1: "Each step forward = +10",
    t2_b2: "Ones digit stays the same",
    t2_b3: "Tens digit goes up by 1",
    t2_inst: "What comes after 60 when counting by tens?",
    t2_h1: "60, then one more ten...",
    t2_h2: "60 + 10 = 70 — tap 70!",
    t2_q: "What number comes next? 45, 55, 65, __",
    t2_q_75: "75", t2_q_66: "66", t2_q_70: "70", t2_q_56: "56",
    t3_title: "Subtracting Tens in Your Head",
    t3_text: "Subtracting tens works the same way — subtract the tens digits! 80 − 30: eight tens − three tens = five tens = 50. Easy!",
    t3_b1: "80 − 30 = 8 tens − 3 tens = 5 tens = 50",
    t3_b2: "Jump LEFT on the number line",
    t3_b3: "Ask: how many tens are left?",
    t3_inst: "Start at 70 and subtract 20 — jump 2 tens back!",
    t3_h1: "70 = 7 tens. Take away 2: 7 − 2 = 5",
    t3_h2: "5 tens = 50 — tap 50!",
    t3_q: "What is 90 − 40?",
    t3_q_50: "50", t3_q_94: "94", t3_q_40: "40", t3_q_5: "5",
  },
  de: {
    explorer_title: "Kopfrechnen entdecken",
    t1_title: "Zehner im Kopf addieren",
    t1_text: "Zehner addieren ist leicht — addiere einfach die Zehnerziffern! 40 + 20: vier Zehner + zwei Zehner = sechs Zehner = 60. Kein Einzelzählen nötig!",
    t1_b1: "40 + 20 = 4 Zehner + 2 Zehner = 6 Zehner = 60",
    t1_b2: "Zehnerzahlen enden immer auf 0",
    t1_b3: "Frage: wie viele Zehner insgesamt?",
    t1_inst: "Starte bei 40 und addiere 20 — springe 2 Zehner vorwärts!",
    t1_h1: "40 = 4 Zehner. Noch 2 dazu: 4 + 2 = 6",
    t1_h2: "6 Zehner = 60 — tippe auf 60!",
    t1_q: "Was ist 30 + 50?",
    t1_q_80: "80", t1_q_35: "35", t1_q_53: "53", t1_q_8: "8",
    t2_title: "In Zehnern zählen",
    t2_text: "Beim Zählen in Zehnern ist jede nächste Zahl genau 10 mehr: 20, 30, 40, 50 … Die Einerziffer bleibt GLEICH! Nur die Zehnerziffer ändert sich um 1.",
    t2_b1: "Jeder Schritt = +10",
    t2_b2: "Einerziffer bleibt gleich",
    t2_b3: "Zehnerziffer steigt um 1",
    t2_inst: "Was kommt nach 60, wenn man in Zehnern zählt?",
    t2_h1: "60, dann noch ein Zehner...",
    t2_h2: "60 + 10 = 70 — tippe auf 70!",
    t2_q: "Welche Zahl fehlt? 45, 55, 65, __",
    t2_q_75: "75", t2_q_66: "66", t2_q_70: "70", t2_q_56: "56",
    t3_title: "Zehner im Kopf subtrahieren",
    t3_text: "Zehner subtrahieren funktioniert genauso — subtrahiere die Zehnerziffern! 80 − 30: acht Zehner − drei Zehner = fünf Zehner = 50. Ganz einfach!",
    t3_b1: "80 − 30 = 8 Zehner − 3 Zehner = 5 Zehner = 50",
    t3_b2: "Nach links springen auf dem Zahlenstrahl",
    t3_b3: "Frage: wie viele Zehner bleiben?",
    t3_inst: "Starte bei 70 und subtrahiere 20 — springe 2 Zehner zurück!",
    t3_h1: "70 = 7 Zehner. Minus 2: 7 − 2 = 5",
    t3_h2: "5 Zehner = 50 — tippe auf 50!",
    t3_q: "Was ist 90 − 40?",
    t3_q_50: "50", t3_q_94: "94", t3_q_40: "40", t3_q_5: "5",
  },
  hu: {
    explorer_title: "Fejszámolás felfedezés",
    t1_title: "Tízesek összeadása fejben",
    t1_text: "A tízeseket könnyű összeadni — csak a tízes számjegyeket add össze! 40 + 20: négy tízes + két tízes = hat tízes = 60. Nem kell egyesenként számolni!",
    t1_b1: "40 + 20 = 4 tízes + 2 tízes = 6 tízes = 60",
    t1_b2: "Tízes számok mindig 0-ra végződnek",
    t1_b3: "Kérdezd: összesen hány tízes?",
    t1_inst: "Indulj a 40-ről és add hozzá a 20-at — ugorj 2 tízest előre!",
    t1_h1: "40 = 4 tízes. Még 2 tízes: 4 + 2 = 6",
    t1_h2: "6 tízes = 60 — koppints a 60-ra!",
    t1_q: "Mennyi 30 + 50?",
    t1_q_80: "80", t1_q_35: "35", t1_q_53: "53", t1_q_8: "8",
    t2_title: "Tízenként számolás",
    t2_text: "Tízenként számolva minden következő szám pontosan 10-zel több: 20, 30, 40, 50 … Az egyes számjegy UGYANAZ marad! Csak a tízes változik 1-gyel.",
    t2_b1: "Minden lépés = +10",
    t2_b2: "Egyes számjegy marad ugyanaz",
    t2_b3: "Tízes számjegy 1-gyel nő",
    t2_inst: "Mi jön a 60 után, ha tízenként számolunk?",
    t2_h1: "60, majd még egy tízes...",
    t2_h2: "60 + 10 = 70 — koppints a 70-re!",
    t2_q: "Melyik szám hiányzik? 45, 55, 65, __",
    t2_q_75: "75", t2_q_66: "66", t2_q_70: "70", t2_q_56: "56",
    t3_title: "Tízesek kivonása fejben",
    t3_text: "A tízesek kivonása ugyanúgy működik — von ki a tízes számjegyeket! 80 − 30: nyolc tízes − három tízes = öt tízes = 50. Egyszerű!",
    t3_b1: "80 − 30 = 8 tízes − 3 tízes = 5 tízes = 50",
    t3_b2: "A számegyenesen balra ugrás",
    t3_b3: "Kérdezd: hány tízes marad?",
    t3_inst: "Indulj a 70-ről és von ki 20-at — ugorj 2 tízest vissza!",
    t3_h1: "70 = 7 tízes. Minus 2: 7 − 2 = 5",
    t3_h2: "5 tízes = 50 — koppints az 50-re!",
    t3_q: "Mennyi 90 − 40?",
    t3_q_50: "50", t3_q_94: "94", t3_q_40: "40", t3_q_5: "5",
  },
  ro: {
    explorer_title: "Calcul mental",
    t1_title: "Adunarea zecilor în minte",
    t1_text: "Adunarea zecilor este ușoară — aduni doar cifrele zecilor! 40 + 20: patru zeci + două zeci = șase zeci = 60. Nu trebuie să numeri unu câte unu!",
    t1_b1: "40 + 20 = 4 zeci + 2 zeci = 6 zeci = 60",
    t1_b2: "Numerele de zeci se termină în 0",
    t1_b3: "Întreabă: câte zeci în total?",
    t1_inst: "Pornește de la 40 și adaugă 20 — sari 2 zeci înainte!",
    t1_h1: "40 = 4 zeci. Încă 2 zeci: 4 + 2 = 6",
    t1_h2: "6 zeci = 60 — atinge 60!",
    t1_q: "Cât este 30 + 50?",
    t1_q_80: "80", t1_q_35: "35", t1_q_53: "53", t1_q_8: "8",
    t2_title: "Numărare din 10 în 10",
    t2_text: "Când numărăm din 10 în 10, fiecare următor este cu 10 mai mare: 20, 30, 40, 50 … Cifra unităților rămâne ACEEAȘI! Doar cifra zecilor crește cu 1.",
    t2_b1: "Fiecare pas = +10",
    t2_b2: "Cifra unităților rămâne aceeași",
    t2_b3: "Cifra zecilor crește cu 1",
    t2_inst: "Ce vine după 60 când numărăm din 10 în 10?",
    t2_h1: "60, apoi încă o zece...",
    t2_h2: "60 + 10 = 70 — atinge 70!",
    t2_q: "Ce număr lipsește? 45, 55, 65, __",
    t2_q_75: "75", t2_q_66: "66", t2_q_70: "70", t2_q_56: "56",
    t3_title: "Scăderea zecilor în minte",
    t3_text: "Scăderea zecilor funcționează la fel — scazi cifrele zecilor! 80 − 30: opt zeci − drei zeci = cinci zeci = 50. Simplu!",
    t3_b1: "80 − 30 = 8 zeci − 3 zeci = 5 zeci = 50",
    t3_b2: "Salt la stânga pe dreapta numerelor",
    t3_b3: "Întreabă: câte zeci rămân?",
    t3_inst: "Pornește de la 70 și scade 20 — sari 2 zeci înapoi!",
    t3_h1: "70 = 7 zeci. Minus 2: 7 − 2 = 5",
    t3_h2: "5 zeci = 50 — atinge 50!",
    t3_q: "Cât este 90 − 40?",
    t3_q_50: "50", t3_q_94: "94", t3_q_40: "40", t3_q_5: "5",
  },
};

// ─── Topic definitions ────────────────────────────────────────────────────────

const TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 100,
      step: 10,
      start: 40,
      target: 60,
      showJumps: true,
      jumpCount: 2,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_35", "t1_q_8", "t1_q_53", "t1_q_80"],
      answer: "t1_q_80",
    },
    quizSvg: () => null,
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 50,
      max: 80,
      step: 10,
      start: 60,
      target: 70,
      showJumps: true,
      jumpCount: 1,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_66", "t2_q_70", "t2_q_56", "t2_q_75"],
      answer: "t2_q_75",
    },
    quizSvg: () => null,
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 40,
      max: 80,
      step: 10,
      start: 70,
      target: 50,
      showJumps: true,
      jumpCount: 2,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_94", "t3_q_40", "t3_q_5", "t3_q_50"],
      answer: "t3_q_50",
    },
    quizSvg: () => null,
  },
];

// ─── Explorer definition ──────────────────────────────────────────────────────

const DEF: ExplorerDef = {
  labels: LABELS,
  title: "explorer_title",
  icon: "🧠",
  topics: TOPICS,
  rounds: [],
};

// ─── Export ───────────────────────────────────────────────────────────────────

const MentalMathExplorer = memo(function MentalMathExplorer({
  color = "#00D4FF",
  onDone,
  lang = "en",
}: {
  color?: string;
  onDone: (s: number, t: number) => void;
  lang?: string;
}) {
  return <ExplorerEngine def={DEF} grade={2} explorerId="math_g2_mentalmath" color={color} lang={lang} onDone={onDone} />;
});

export default MentalMathExplorer;
