"use client";
// PlaceValueExplorer4 — Large numbers & Place Value for Grade 4 (island i4)

import { memo } from "react";
import ExplorerEngine from "@/app/astro-biologie/games/ExplorerEngine";
import type { ExplorerDef, TopicDef } from "@/app/astro-biologie/games/ExplorerEngine";

// ─── SVG ILLUSZTRÁCIÓK ──────────────────────────────────────────────

// ─── LABELS ──────────────────────────────────────────────────────────

const LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Large Numbers Explorer",
    t1_title: "The World of Ten Thousands",
    t1_text: "When we have ten groups of 1,000, we get 10,000. These large numbers follow the same patterns you already know!",
    t1_b1: "10 x 1,000 = 10,000",
    t1_b2: "Comma or space separates thousands",
    t1_b3: "The fifth digit is the Ten Thousands",
    t1_inst: "Combine the blocks to create 30,000!",
    t1_h1: "Each block represents 10,000.",
    t1_h2: "You need exactly three 10,000 blocks.",
    t1_q: "Which number has a 5 in the ten thousands place?",
    t1_q_a: "15,200",
    t1_q_b: "52,000",
    t1_q_c: "5,200",
    t1_q_d: "10,005",
    t2_title: "Place Value Columns",
    t2_text: "In the number 43,250, every digit has a specific value. The 4 means four 10,000s, and the 3 means three 1,000s.",
    t2_b1: "Positions determine the actual value",
    t2_b2: "Zero acts as a placeholder",
    t2_b3: "Read from left to right",
    t2_inst: "Find 45,000 on the number line!",
    t2_h1: "It is exactly halfway between 40k and 50k.",
    t2_h2: "Look for the middle mark between 40,000 and 50,000.",
    t2_q: "What is the value of 7 in 74,300?",
    t2_q_a: "700",
    t2_q_b: "70,000",
    t2_q_c: "7,000",
    t2_q_d: "70",
    t3_title: "Comparing Large Numbers",
    t3_text: "To compare large numbers, always look at the highest place value first. 50,000 is always greater than 49,999!",
    t3_b1: "Compare the leftmost digits first",
    t3_b2: "More digits usually means a bigger number",
    t3_b3: "Equal digits? Move to the next place",
    t3_inst: "Move 10,000 blocks to reach the sum of 20,000 + 40,000!",
    t3_h1: "2 + 4 = 6, so you need 60,000.",
    t3_h2: "Drag six 10k blocks into the area.",
    t3_q: "Which number is the largest?",
    t3_q_a: "88,999",
    t3_q_b: "91,000",
    t3_q_c: "9,999",
    t3_q_d: "89,999",
  },
  de: {
    explorer_title: "Große Zahlen Entdecker",
    t1_title: "Die Welt der Zehntausender",
    t1_text: "Zehn Gruppen von 1.000 ergeben 10.000. Diese großen Zahlen folgen den gleichen Mustern, die du bereits kennst!",
    t1_b1: "10 x 1.000 = 10.000",
    t1_b2: "Punkte trennen die Tausender",
    t1_b3: "Die fünfte Stelle ist der Zehntausender",
    t1_inst: "Kombiniere die Blöcke, um 30.000 zu bilden!",
    t1_h1: "Jeder Block steht für 10.000.",
    t1_h2: "Du brauchst genau drei 10.000er Blöcke.",
    t1_q: "Welche Zahl hat eine 5 an der Zehntausenderstelle?",
    t1_q_a: "15.200",
    t1_q_b: "52.000",
    t1_q_c: "5.200",
    t1_q_d: "10.005",
    t2_title: "Stellenwert-Spalten",
    t2_text: "In der Zahl 43.250 hat jede Ziffer einen bestimmten Wert. Die 4 bedeutet vier 10.000er, die 3 bedeutet drei 1.000er.",
    t2_b1: "Positionen bestimmen den Wert",
    t2_b2: "Null dient als Platzhalter",
    t2_b3: "Lies von links nach rechts",
    t2_inst: "Finde 45.000 auf dem Zahlenstrahl!",
    t2_h1: "Es liegt genau in der Mitte zwischen 40k und 50k.",
    t2_h2: "Suche die Markierung zwischen 40.000 und 50.000.",
    t2_q: "Was ist der Wert der 7 in 74.300?",
    t2_q_a: "700",
    t2_q_b: "70.000",
    t2_q_c: "7.000",
    t2_q_d: "70",
    t3_title: "Große Zahlen vergleichen",
    t3_text: "Vergleiche immer zuerst den höchsten Stellenwert. 50.000 ist immer größer als 49.999!",
    t3_b1: "Vergleiche zuerst die linke Ziffer",
    t3_b2: "Mehr Stellen bedeuten meist größere Zahlen",
    t3_b3: "Gleiche Ziffer? Prüfe die nächste Stelle",
    t3_inst: "Bewege 10.000er Blöcke, um 20.000 + 40.000 zu bilden!",
    t3_h1: "2 + 4 = 6, also brauchst du 60.000.",
    t3_h2: "Ziehe sechs 10k-Blöcke in den Bereich.",
    t3_q: "Welche Zahl ist am größten?",
    t3_q_a: "88.999",
    t3_q_b: "91.000",
    t3_q_c: "9.999",
    t3_q_d: "89.999",
  },
  hu: {
    explorer_title: "Nagy számok felfedezése",
    t1_title: "A tízezresek világa",
    t1_text: "Ha tíz darab 1000-es csoportunk van, az 10 000-et alkot. Ezek a nagy számok ugyanazt a mintát követik, amit már ismersz!",
    t1_b1: "10 x 1000 = 10 000",
    t1_b2: "A szóköz elválasztja az ezreseket",
    t1_b3: "Az ötödik számjegy a tízezres",
    t1_inst: "Vond össze a blokkokat, hogy 30 000-et kapj!",
    t1_h1: "Minden blokk 10 000-et ér.",
    t1_h2: "Pontosan három darab 10 000-es blokkra van szükséged.",
    t1_q: "Melyik számban áll 5-ös a tízezres helyiértéken?",
    t1_q_a: "15 200",
    t1_q_b: "52 000",
    t1_q_c: "5200",
    t1_q_d: "10 005",
    t2_title: "Helyiérték oszlopok",
    t2_text: "A 43 250-es számban minden számjegynek saját értéke van. A 4-es négy darab 10 000-est, a 3-as három darab 1000-est jelent.",
    t2_b1: "A pozíció határozza meg az értéket",
    t2_b2: "A nulla helyiérték-tartó szerepű",
    t2_b3: "Balról jobbra olvasunk",
    t2_inst: "Keresd meg a 45 000-et a számegyenesen!",
    t2_h1: "Pontosan félúton van 40e és 50e között.",
    t2_h2: "Keresd a középső jelölést 40 000 és 50 000 között.",
    t2_q: "Mi a 7-es értéke a 74 300-as számban?",
    t2_q_a: "700",
    t2_q_b: "70 000",
    t2_q_c: "7000",
    t2_q_d: "70",
    t3_title: "Nagy számok összehasonlítása",
    t3_text: "Mindig a legmagasabb helyiértéket nézd először. Az 50 000 mindig nagyobb, mint a 49 999!",
    t3_b1: "A bal szélső számjeggyel kezdj",
    t3_b2: "A több számjegy általában nagyobb számot jelent",
    t3_b3: "Egyező számjegyek? Nézd a következőt",
    t3_inst: "Húzz be blokkokat a 20 000 + 40 000 összeghez!",
    t3_h1: "2 + 4 = 6, tehát 60 000 kell.",
    t3_h2: "Húzz hat darab 10e-es blokkot a területre.",
    t3_q: "Melyik szám a legnagyobb?",
    t3_q_a: "88 999",
    t3_q_b: "91 000",
    t3_q_c: "9999",
    t3_q_d: "89 999",
  },
  ro: {
    explorer_title: "Explorator numere mari",
    t1_title: "Lumea zecilor de mii",
    t1_text: "Când avem zece grupuri de 1.000, obținem 10.000. Aceste numere mari urmează aceleași reguli pe care le știi deja!",
    t1_b1: "10 x 1.000 = 10.000",
    t1_b2: "Punctul sau spațiul separă miile",
    t1_b3: "A cincea cifră este cea a zecilor de mii",
    t1_inst: "Combină blocurile pentru a crea 30.000!",
    t1_h1: "Fiecare bloc reprezintă 10.000.",
    t1_h2: "Ai nevoie de exact trei blocuri de 10.000.",
    t1_q: "Care număr are cifra 5 la poziția zecilor de mii?",
    t1_q_a: "15.200",
    t1_q_b: "52.000",
    t1_q_c: "5.200",
    t1_q_d: "10.005",
    t2_title: "Coloanele ordinelor",
    t2_text: "În numărul 43.250, fiecare cifră are o valoare specifică. 4 înseamnă patru de 10.000, iar 3 înseamnă trei de 1.000.",
    t2_b1: "Poziția determină valoarea reală",
    t2_b2: "Zero este un substitut pentru poziție",
    t2_b3: "Citește de la stânga la dreapta",
    t2_inst: "Găsește 45.000 pe linia numerelor!",
    t2_h1: "Este exact la jumătate între 40k și 50k.",
    t2_h2: "Caută marcajul din mijloc între 40.000 și 50.000.",
    t2_q: "Care este valoarea cifrei 7 în 74.300?",
    t2_q_a: "700",
    t2_q_b: "70.000",
    t2_q_c: "7.000",
    t2_q_d: "70",
    t3_title: "Compararea numerelor mari",
    t3_text: "Compară întotdeauna mai întâi cea mai mare poziție. 50.000 este întotdeauna mai mare decât 49.999!",
    t3_b1: "Compară prima cifră din stânga",
    t3_b2: "Mai multe cifre înseamnă de obicei un număr mai mare",
    t3_b3: "Cifre egale? Treci la următoarea poziție",
    t3_inst: "Mută blocurile pentru a obține suma 20.000 + 40.000!",
    t3_h1: "2 + 4 = 6, deci ai nevoie de 60.000.",
    t3_h2: "Trage șase blocuri de 10k în zonă.",
    t3_q: "Care număr este cel mai mare?",
    t3_q_a: "88.999",
    t3_q_b: "91.000",
    t3_q_c: "9.999",
    t3_q_d: "89.999",
  },
};

// ─── TOPIC DEFINÍCIÓK ────────────────────────────────────────────────

const TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [1, 1, 1], // three separate 10k blocks
      answer: 3,
      blockIcon: "📦",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_a", "t1_q_b", "t1_q_c", "t1_q_d"],
      answer: "t1_q_b",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 40000,
      max: 50000,
      start: 40000,
      target: 45000,
      step: 1000,
      showJumps: true,
      jumpCount: 5,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_a", "t2_q_b", "t2_q_c", "t2_q_d"],
      answer: "t2_q_b",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [2, 4], // 20k + 40k
      answer: 6,
      blockIcon: "📦",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_a", "t3_q_b", "t3_q_c", "t3_q_d"],
      answer: "t3_q_b",
    },
  },
];

// ─── EXPLORER DEFINÍCIÓ ──────────────────────────────────────────────

const DEF: ExplorerDef = {
  labels: LABELS,
  title: "explorer_title",
  icon: "🔢",
  topics: TOPICS,
  rounds: [],
};

// ─── EXPORT ──────────────────────────────────────────────────────────

const PlaceValueExplorer4 = memo(function PlaceValueExplorer4({
  color = "#8B5CF6",
  onDone,
  lang = "en",
}: {
  color?: string;
  onDone: (s: number, t: number) => void;
  lang?: string;
}) {
  return <ExplorerEngine def={DEF} grade={4} explorerId="math_g4_placevalue" color={color} lang={lang} onDone={onDone} />;
});

export default PlaceValueExplorer4;
