import type { PoolTopicDef } from "./types";

export const GEO_K7_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Asien & Naturgewalten",
    t1_title: "Kontinent der Superlative",
    t1_text: "Asien ist so groß, dass es fast alle Klimazonen der Erde vereint. Hier stehen die höchsten Giganten der Welt neben den tiefsten Senken.",
    t1_h1: "Dach der Welt = Himalaya",
    t1_h2: "Größtes Binnenmeer = Kaspisches Meer",
    t1_h3: "Tiefster See = Baikalsee",
    t1_inst: "Welcher Ort hält welchen Rekord?",
    t1_l1: "Mount Everest", t1_r1: "Höchster Gipfel",
    t1_l2: "Baikalsee", t1_r2: "Tiefster See",
    t1_l3: "Gobi", t1_r3: "Kalte Wüste",
    t1_q: "Wo befindet sich der Mount Everest?",
    t1_qa: "Im Himalaya-Gebirge", t1_qb: "In den Alpen", t1_qc: "In den Anden", t1_qd: "Am Äquator",

    t2_title: "Unruhige Erde",
    t2_text: "In Asien treffen gigantische Erdplatten aufeinander. Wenn sie sich verhaken und ruckartig lösen, zittert die Erde oder das Meer schlägt hohe Wellen.",
    t2_h1: "Platten schieben sich",
    t2_h2: "Spannung entlädt sich",
    t2_h3: "Energie wandert als Welle",
    t2_inst: "Beschrifte das Zentrum des Bebens!",
    t2_area_epi: "Epizentrum (oben)",
    t2_area_hypo: "Hypozentrum (unten)",
    t2_area_fault: "Bruchstelle",
    t2_area_wave: "Erdbebenwellen",
    t2_q: "Wie nennt man eine Riesenwelle nach einem Seebeben?",
    t2_qa: "Tsunami", t2_qb: "Ebbe", t2_qc: "Monsun", t2_qd: "Strömung",

    t3_title: "Chips und Reisfelder",
    t3_text: "Asiens Wirtschaft hat zwei Gesichter: In den Megastädten entstehen Mikrochips und Roboter, während auf dem Land Millionen Menschen vom Reisanbau leben.",
    t3_h1: "High-Tech Zentren",
    t3_h2: "Traditioneller Reisanbau",
    t3_h3: "Weltweiter Export",
    t3_inst: "Was passt in welche Welt?",
    t3_bucket_tech: "Moderne Industrie",
    t3_bucket_agri: "Traditionelle Landwirtschaft",
    t3_item_robot: "Industrieroboter",
    t3_item_chip: "Smartphone-Prozessor",
    t3_item_rice: "Handgepflückter Reis",
    t3_item_tea: "Teeplantage",
    t3_q: "In welchem Land hat High-Tech eine riesige Bedeutung?",
    t3_qa: "Japan", t3_qb: "Mongolei", t3_qc: "Nepal", t3_qd: "Laos",

    t4_title: "Atemzug des Kontinents",
    t4_text: "Der Monsun ist wie ein riesiger Atemzug. Im Sommer saugt das heiße Land feuchte Meeresluft an und bringt den lebenswichtigen Regen.",
    t4_h1: "Sommer = Regenzeit",
    t4_h2: "Winter = Trockenzeit",
    t4_h3: "Wichtig für die Bauern",
    t4_inst: "Wie entsteht der Sommermonsun?",
    t4_w1: "Land heizhet sich stark auf",
    t4_w2: "Warme Luft steigt auf",
    t4_w3: "Feuchte Luft strömt nach",
    t4_w4: "Wolken regnen ab",
    t4_q: "Wann bringt der Monsun in Indien meist den meisten Regen?",
    t4_qa: "Im Sommer", t4_qb: "Im Winter", t4_qc: "Nachts", t4_qd: "Gar nicht",

    t5_title: "Der Feuerring",
    t5_text: "Rund um den Pazifik brodelt es. Hunderte Vulkane stehen hier Wache. Sie sind gefährlich, aber ihre Asche macht den Boden auch fruchtbar.",
    t5_h1: "Vulkane am Ozeanrand",
    t5_h2: "Magma wird zu Lava",
    t5_h3: "Fruchtbare Vulkanerde",
    t5_inst: "Suche 5 aktive Vulkane in Ostasien!",
    t5_q: "Warum leben Menschen trotz Gefahr oft nah an Vulkanen?",
    t5_qa: "Wegen des fruchtbaren Bodens", t5_qb: "Wegen der Aussicht", t5_qc: "Weil es dort regnet", t5_qd: "Wegen des Eises",
  },
  en: {
    explorer_title: "Asia & Natural Forces",
    t1_title: "Continent of Superlatives",
    t1_text: "Asia is so vast that it combines almost all of Earth's climate zones. Here, the world's highest giants stand next to the deepest depressions.",
    t1_h1: "Roof of the World = Himalayas",
    t1_h2: "Largest inland sea = Caspian Sea",
    t1_h3: "Deepest lake = Lake Baikal",
    t1_inst: "Which place holds which record?",
    t1_l1: "Mount Everest", t1_r1: "Highest peak",
    t1_l2: "Lake Baikal", t1_r2: "Deepest lake",
    t1_l3: "Gobi", t1_r3: "Cold desert",
    t1_q: "Where is Mount Everest located?",
    t1_qa: "In the Himalayas", t1_qb: "In the Alps", t1_qc: "In the Andes", t1_qd: "At the Equator",

    t2_title: "Restless Earth",
    t2_text: "Gigantic tectonic plates collide in Asia. When they snag and suddenly release, the earth trembles or the sea throws up giant waves.",
    t2_h1: "Plates pushing each other",
    t2_h2: "Tension is released",
    t2_h3: "Energy travels as a wave",
    t2_inst: "Label the center of the quake!",
    t2_area_epi: "Epicenter (above)",
    t2_area_hypo: "Hypocenter (below)",
    t2_area_fault: "Fault line",
    t2_area_wave: "Seismic waves",
    t2_q: "What do you call a giant wave after an undersea earthquake?",
    t2_qa: "Tsunami", t2_qb: "Ebb", t2_qc: "Monsoon", t2_qd: "Current",

    t3_title: "Chips and Rice Fields",
    t3_text: "Asia's economy has two faces: microchips and robots are created in the megacities, while in the countryside millions live from rice farming.",
    t3_h1: "High-Tech Centers",
    t3_h2: "Traditional rice farming",
    t3_h3: "Global export",
    t3_inst: "What belongs to which world?",
    t3_bucket_tech: "Modern Industry",
    t3_bucket_agri: "Traditional Agriculture",
    t3_item_robot: "Industrial robot",
    t3_item_chip: "Smartphone processor",
    t3_item_rice: "Hand-picked rice",
    t3_item_tea: "Tea plantation",
    t3_q: "In which country is high-tech of huge importance?",
    t3_qa: "Japan", t3_qb: "Mongolia", t3_qc: "Nepal", t3_qd: "Laos",

    t4_title: "Breath of the Continent",
    t4_text: "The monsoon is like a giant breath. In summer, the hot land sucks in moist sea air and brings life-giving rain.",
    t4_h1: "Summer = Rainy season",
    t4_h2: "Winter = Dry season",
    t4_h3: "Vital for the harvest",
    t4_inst: "How does the summer monsoon form?",
    t4_w1: "Land heats up strongly",
    t4_w2: "Warm air rises",
    t4_w3: "Moist air flows in",
    t4_w4: "Clouds drop rain",
    t4_q: "When does the monsoon in India usually bring the most rain?",
    t4_qa: "In Summer", t4_qb: "In Winter", t4_qc: "At Night", t4_qd: "Never",

    t5_title: "The Ring of Fire",
    t5_text: "All around the Pacific, things are bubbling. Hundreds of volcanoes stand guard here. They are dangerous, but their ash makes the soil fertile.",
    t5_h1: "Volcanoes on ocean edge",
    t5_h2: "Magma becomes lava",
    t5_h3: "Fertile volcanic soil",
    t5_inst: "Find 5 active volcanoes in East Asia!",
    t5_q: "Why do people often live near volcanoes despite the danger?",
    t5_qa: "Because of fertile soil", t5_qb: "Because of the view", t5_qc: "Because it rains there", t5_qd: "Because of the ice",
  },
  hu: {
    explorer_title: "Ázsia és Természeti Erők",
    t1_title: "Alegek kontinense",
    t1_text: "Ázsia olyan hatalmas, hogy szinte a Föld összes éghajlati övezete megtalálható rajta. Itt a világ legmagasabb csúcsai mellett a legmélyebb medencék sorakoznak.",
    t1_h1: "A világ teteje = Himalája",
    t1_h2: "Legnagyobb beltenger = Kaszpi-tenger",
    t1_h3: "Legmélyebb tó = Bajkál-tó",
    t1_inst: "Melyik hely melyik rekordot tartja?",
    t1_l1: "Mount Everest", t1_r1: "Legmagasabb csúcs",
    t1_l2: "Bajkál-tó", t1_r2: "Legmélyebb tó",
    t1_l3: "Góbi", t1_r3: "Hideg sivatag",
    t1_q: "Hol található a Mount Everest?",
    t1_qa: "A Himalájában", t1_qb: "Az Alpokban", t1_qc: "Az Andokban", t1_qd: "Az Egyenlítőnél",

    t2_title: "Nyugtalan föld",
    t2_text: "Ázsiában hatalmas kőzetlemezek ütköznek össze. Amikor összeakadnak, majd hirtelen elmozdulnak, megremeg a föld, vagy óriási hullámokat vet a tenger.",
    t2_h1: "Egymást toló lemezek",
    t2_h2: "Feszültség felszabadulása",
    t2_h3: "Energia hullámként terjed",
    t2_inst: "Nevezd meg a rengés központját!",
    t2_area_epi: "Epizentrum (fent)",
    t2_area_hypo: "Hipocentrum (lent)",
    t2_area_fault: "Törésvonal",
    t2_area_wave: "Szeizmikus hullámok",
    t2_q: "Hogy hívják a tenger alatti földrengés utáni óriáshullámot?",
    t2_qa: "Cunami", t2_qb: "Apály", t2_qc: "Monsun", t2_qd: "Áramlat",

    t3_title: "Chipek és rizsföldek",
    t3_text: "Ázsia gazdasága kétarcú: a megavárosokban mikrochipek és robotok készülnek, míg vidéken milliók élnek rizstermesztésből.",
    t3_h1: "High-tech központok",
    t3_h2: "Hagyományos rizstermesztés",
    t3_h3: "Világszintű export",
    t3_inst: "Mi hova tartozik?",
    t3_bucket_tech: "Modern ipar",
    t3_bucket_agri: "Hagyományos mezőgazdaság",
    t3_item_robot: "Ipari robot",
    t3_item_chip: "Okostelefon processzor",
    t3_item_rice: "Kézzel aratott rizs",
    t3_item_tea: "Teaültetvény",
    t3_q: "Melyik országban kiemelten fontos a csúcstechnológia?",
    t3_qa: "Japán", t3_qb: "Mongólia", t3_qc: "Nepál", t3_qd: "Laosz",

    t4_title: "A kontinens lélegzetvétele",
    t4_text: "A monszun olyan, mint egy óriási lélegzetvétel. Nyáron a forró szárazföld beszippantja a tenger felőli párás levegőt, ami meghozza az életet adó esőt.",
    t4_h1: "Nyár = Esős évszak",
    t4_h2: "Tél = Száraz évszak",
    t4_h3: "Létfontosságú a termésnek",
    t4_inst: "Hogyan alakul ki a nyári monszun?",
    t4_w1: "A szárazföld felmelegszik",
    t4_w2: "A meleg levegő felszáll",
    t4_w3: "Párás levegő áramlik be",
    t4_w4: "A felhőkből eső esik",
    t4_q: "Mikor hozza a monszun Indiában a legtöbb esőt?",
    t4_qa: "Nyáron", t4_qb: "Télen", t4_qc: "Éjszaka", t4_qd: "Soha",

    t5_title: "A tűzgyűrű",
    t5_text: "A Csendes-óceán peremén állandóan forr a mély. Vulkánok százai állnak itt őrt. Veszélyesek, de hamujuk termékennyé teszi a földet.",
    t5_h1: "Vulkánok az óceán partján",
    t5_h2: "Magmából láva lesz",
    t5_h3: "Termékeny vulkáni talaj",
    t5_inst: "Keress 5 aktív vulkánt Kelet-Ázsiában!",
    t5_q: "Miért laknak az emberek a veszély ellenére vulkánok közelében?",
    t5_qa: "A termékeny talaj miatt", t5_qb: "A kilátás miatt", t5_qc: "Mert ott többet esik", t5_qd: "A jég miatt",
  },
  ro: {
    explorer_title: "Asia și Forțele Naturii",
    t1_title: "Continentul superlativelor",
    t1_text: "Asia este atât de mare încât reunește aproape toate zonele climatice ale Pământului. Aici, cei mai înalți giganți ai lumii stau lângă cele mai adânci depresiuni.",
    t1_h1: "Acoperișul lumii = Himalaya",
    t1_h2: "Cea mai mare mare interioară = Marea Caspică",
    t1_h3: "Cel mai adânc lac = Lacul Baikal",
    t1_inst: "Care loc deține ce record?",
    t1_l1: "Mount Everest", t1_r1: "Cel mai înalt vârf",
    t1_l2: "Lacul Baikal", t1_r2: "Cel mai adânc lac",
    t1_l3: "Gobi", t1_r3: "Deșert rece",
    t1_q: "Unde se află muntele Everest?",
    t1_qa: "În munții Himalaya", t1_qb: "În Alpi", t1_qc: "În Anzi", t1_qd: "La Ecuator",

    t2_title: "Pământ neliniștit",
    t2_text: "În Asia se ciocnesc plăci tectonice gigantice. Când se agață și se eliberează brusc, pământul tremură sau marea aruncă valuri uriașe.",
    t2_h1: "Plăci care se împing",
    t2_h2: "Tensiunea se eliberează",
    t2_h3: "Energia circulă ca o undă",
    t2_inst: "Etichetează centrul cutremurului!",
    t2_area_epi: "Epicentru (sus)",
    t2_area_hypo: "Hipocentru (jos)",
    t2_area_fault: "Linie de falie",
    t2_area_wave: "Unde seismice",
    t2_q: "Cum se numește un val uriaș după un cutremur submarin?",
    t2_qa: "Tsunami", t2_qb: "Reflux", t2_qc: "Muson", t2_qd: "Curent",

    t3_title: "Cipuri și orezării",
    t3_text: "Economia Asiei are două fețe: în mega-orașe se nasc microcipuri și roboți, în timp ce la țară milioane de oameni trăiesc din cultivarea orezului.",
    t3_h1: "Centre High-Tech",
    t3_h2: "Cultivarea tradițională a orezului",
    t3_h3: "Export mondial",
    t3_inst: "Ce aparține fiecărei lumi?",
    t3_bucket_tech: "Industrie modernă",
    t3_bucket_agri: "Agricultură tradițională",
    t3_item_robot: "Robot industrial",
    t3_item_chip: "Procesor de smartphone",
    t3_item_rice: "Orez cules manual",
    t3_item_tea: "Plantație de ceai",
    t3_q: "În care țară tehnologia are o importanță uriașă?",
    t3_qa: "Japonia", t3_qb: "Mongolia", t3_qc: "Nepal", t3_qd: "Laos",

    t4_title: "Respirația continentului",
    t4_text: "Musonul este ca o respirație gigantică. Vara, pământul fierbinte absoarbe aerul umed al mării și aduce ploaia vitală.",
    t4_h1: "Vară = Sezon ploios",
    t4_h2: "Iarnă = Sezon secetos",
    t4_h3: "Vital pentru recoltă",
    t4_inst: "Cum se formează musonul de vară?",
    t4_w1: "Pământul se încălzește puternic",
    t4_w2: "Aerul cald se ridică",
    t4_w3: "Aerul umed pătrunde în interior",
    t4_w4: "Norii aduc ploaia",
    t4_q: "Când aduce musonul în India cele mai multe ploi?",
    t4_qa: "Vara", t4_qb: "Iarna", t4_qc: "Noaptea", t4_qd: "Niciodată",

    t5_title: "Inelul de Foc",
    t5_text: "De jur împrejurul Pacificului, pământul fierbe. Sute de vulcani stau de veghe aici. Sunt periculoși, dar cenușa lor face solul fertil.",
    t5_h1: "Vulcani la marginea oceanului",
    t5_h2: "Magma devine lavă",
    t5_h3: "Sol vulcanic fertil",
    t5_inst: "Caută 5 vulcani activi în Asia de Est!",
    t5_q: "De ce trăiesc oamenii adesea lângă vulcani în ciuda pericolului?",
    t5_qa: "Datorită solului fertil", t5_qb: "Datorită priveliștii", t5_qc: "Pentru că plouă mai mult", t5_qd: "Datorită gheții",
  },
};

export const GEO_K7_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🏔️", title: "Asia", bg: "#F1F5F9" },
    bulletKeys: ["t1_h1", "t1_h2", "t1_h3"],
    interactive: {
      type: "match-pairs",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h3",
      pairs: [
        { left: "t1_l1", right: "t1_r1" },
        { left: "t1_l2", right: "t1_r2" },
        { left: "t1_l3", right: "t1_r3" },
      ],
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "💥", title: "Quake", bg: "#FFF7ED" },
    bulletKeys: ["t2_h1", "t2_h2", "t2_h3"],
    interactive: {
      type: "label-diagram",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h3",
      areas: [
        { id: "epi", x: 50, y: 15, label: "t2_area_epi" },
        { id: "hypo", x: 50, y: 80, label: "t2_area_hypo" },
        { id: "fault", x: 20, y: 50, label: "t2_area_fault" },
        { id: "wave", x: 80, y: 50, label: "t2_area_wave" },
      ],
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: {
      type: "two-groups",
      left: { items: ["🤖", "📱"], bg: "#EFF6FF", border: "#3B82F6" },
      right: { items: ["🍚", "🍵"], bg: "#F0FDF4", border: "#22C55E" },
      bg: "#F8FAFC",
    },
    bulletKeys: ["t3_h1", "t3_h2", "t3_h3"],
    interactive: {
      type: "drag-to-bucket",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
      buckets: [
        { id: "tech", label: "t3_bucket_tech" },
        { id: "agri", label: "t3_bucket_agri" },
      ],
      items: [
        { text: "t3_item_robot", bucketId: "tech" },
        { text: "t3_item_chip", bucketId: "tech" },
        { text: "t3_item_rice", bucketId: "agri" },
        { text: "t3_item_tea", bucketId: "agri" },
      ],
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🌬️", title: "Monsoon", bg: "#FDF4FF" },
    bulletKeys: ["t4_h1", "t4_h2", "t4_h3"],
    interactive: {
      type: "word-order",
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h3",
      words: ["t4_w1", "t4_w2", "t4_w3", "t4_w4"],
      correctOrder: [0, 1, 2, 3],
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "icon-grid", items: [{ emoji: "🌋" }, { emoji: "🌊" }, { emoji: "🗾" }], bg: "#FEF2F2" },
    bulletKeys: ["t5_h1", "t5_h2", "t5_h3"],
    interactive: {
      type: "tap-count",
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
      tapCount: { emoji: "🌋", count: 5 },
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
];
