import type { PoolTopicDef } from "./types";

export const GEO_K6_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Erde & Klima",
    t1_title: "Nordsee bis Alpen",
    t1_text: "Deutschland ist ein Land der Kontraste. Im Norden peitscht der Wind an die Küsten, während im Süden die hohen Gipfel der Alpen in den Himmel ragen.",
    t1_h1: "Küste im Norden",
    t1_h2: "Gebirge im Süden",
    t1_h3: "Dazwischen weite Ebenen",
    t1_inst: "Ordne die Städte ihrer Region zu!",
    t1_l1: "Hamburg", t1_r1: "Nahe der Küste",
    t1_l2: "München", t1_r2: "Nahe der Alpen",
    t1_l3: "Berlin", t1_r3: "In der Tiefebene",
    t1_q: "Welches Gebirge bildet die südliche Grenze Deutschlands?",
    t1_qa: "Die Alpen", t1_qb: "Der Harz", t1_qc: "Der Schwarzwald", t1_qd: "Die Anden",

    t2_title: "Reise zum Erdkern",
    t2_text: "Stell dir die Erde wie einen Pfirsich vor. Die Kruste ist die dünne Haut, das Fruchtfleisch der Mantel und der Stein in der Mitte ist der extrem heiße Kern.",
    t2_h1: "Kruste = Unsere Heimat",
    t2_h2: "Mantel = Heißes Gestein",
    t2_h3: "Kern = Eisen und Hitze",
    t2_inst: "Wo befinden wir uns? Beschrifte die Erdschichten!",
    t2_area_crust: "Erdkruste (fest)",
    t2_area_mantle: "Erdmantel (zäh)",
    t2_area_outer_core: "Äußerer Kern (flüssig)",
    t2_area_inner_core: "Innerer Kern (fest)",
    t2_q: "Welche Schicht ist am dünnsten?",
    t2_qa: "Die Erdkruste", t2_qb: "Der Erdmantel", t2_qc: "Der Erdkern", t2_qd: "Der Ozean",

    t3_title: "Vom Eis zum Dschungel",
    t3_text: "Klimazonen sind wie Gürtel um die Erde. Nahe der Sonne am Äquator wächst der Regenwald, an den Enden herrscht ewiges Eis.",
    t3_h1: "Äquator = Heiß & Nass",
    t3_h2: "Pole = Kalt & Trocken",
    t3_h3: "Wir leben mittendrin",
    t3_inst: "Sortiere die typischen Merkmale!",
    t3_bucket_tropic: "Tropischer Regenwald",
    t3_bucket_polar: "Polareiszone",
    t3_item_palm: "Riesige Farne",
    t3_item_jungle: "Bunte Papageien",
    t3_item_ice: "Eisbären",
    t3_item_penguin: "Schneestürme",
    t3_q: "Wo ist es das ganze Jahr über fast gleich warm und regnerisch?",
    t3_qa: "In den Tropen", t3_qb: "Am Nordpol", t3_qc: "In Deutschland", t3_qd: "In der Wüste Gobi",

    t4_title: "Der ewige Kreislauf",
    t4_text: "Kein Tropfen Wasser geht verloren. Das Wasser, das du heute trinkst, war vielleicht schon einmal Teil einer Wolke über dem Meer.",
    t4_h1: "Sonne treibt alles an",
    t4_h2: "Dampf wird zu Wolken",
    t4_h3: "Flüsse fließen zurück",
    t4_inst: "Folge dem Weg eines Wassertropfens!",
    t4_w1: "Verdunstung aus dem Meer",
    t4_w2: "Abkühlung in der Höhe",
    t4_w3: "Regen über dem Land",
    t4_w4: "Rückfluss im Fluss",
    t4_q: "Was liefert die Energie für den Wasserkreislauf?",
    t4_qa: "Die Sonne", t4_qb: "Der Wind", t4_qc: "Die Gezeiten", t4_qd: "Die Fische",

    t5_title: "Gedächtnis der Erde",
    t5_text: "Steine erzählen Geschichten. Manche entstehen aus glühendem Magma, andere werden über Millionen Jahre am Meeresgrund zusammengepresst.",
    t5_h1: "Magmatit = Erstarrtes Feuer",
    t5_h2: "Sedimentit = Abgelagerter Sand",
    t5_h3: "Metamorphit = Umgewandelt",
    t5_inst: "Sammle 5 Basalt-Steine (vulkanisch) für unser Labor!",
    t5_q: "Welches Gestein entsteht durch Ablagerung von Sand und Muscheln?",
    t5_qa: "Sedimentgestein", t5_qb: "Vulkangestein", t5_qc: "Edelsteine", t5_qd: "Weltraumschrott",
  },
  en: {
    explorer_title: "Earth & Climate",
    t1_title: "North Sea to Alps",
    t1_text: "Germany is a land of contrasts. In the north, winds whip the coasts, while in the south, the high peaks of the Alps reach for the sky.",
    t1_h1: "Coast in the North",
    t1_h2: "Mountains in the South",
    t1_h3: "Wide plains in between",
    t1_inst: "Assign the cities to their region!",
    t1_l1: "Hamburg", t1_r1: "Near the coast",
    t1_l2: "Munich", t1_r2: "Near the Alps",
    t1_l3: "Berlin", t1_r3: "In the plains",
    t1_q: "Which mountain range forms the southern border of Germany?",
    t1_qa: "The Alps", t1_qb: "The Harz", t1_qc: "The Black Forest", t1_qd: "The Andes",

    t2_title: "Journey to the Core",
    t2_text: "Imagine Earth like a peach. The crust is the thin skin, the flesh is the mantle, and the pit in the middle is the extremely hot core.",
    t2_h1: "Crust = Our home",
    t2_h2: "Mantle = Hot rock",
    t2_h3: "Core = Iron and heat",
    t2_inst: "Where are we? Label the Earth's layers!",
    t2_area_crust: "Crust (solid)",
    t2_area_mantle: "Mantle (viscous)",
    t2_area_outer_core: "Outer Core (liquid)",
    t2_area_inner_core: "Inner Core (solid)",
    t2_q: "Which layer is the thinnest?",
    t2_qa: "The Crust", t2_qb: "The Mantle", t2_qc: "The Core", t2_qd: "The Ocean",

    t3_title: "Ice to Jungle",
    t3_text: "Climate zones are like belts around the Earth. Near the sun at the Equator, rainforests grow; at the ends, eternal ice rules.",
    t3_h1: "Equator = Hot & Wet",
    t3_h2: "Poles = Cold & Dry",
    t3_h3: "We live in the middle",
    t3_inst: "Sort the typical features!",
    t3_bucket_tropic: "Tropical Rainforest",
    t3_bucket_polar: "Polar Ice Zone",
    t3_item_palm: "Giant ferns",
    t3_item_jungle: "Colorful parrots",
    t3_item_ice: "Polar bears",
    t3_item_penguin: "Snowstorms",
    t3_q: "Where is it almost equally warm and rainy all year round?",
    t3_qa: "In the Tropics", t3_qb: "At the North Pole", t3_qc: "In Germany", t3_qd: "In the Gobi Desert",

    t4_title: "The Eternal Cycle",
    t4_text: "Not a single drop of water is lost. The water you drink today might have once been part of a cloud over the ocean.",
    t4_h1: "Sun powers everything",
    t4_h2: "Steam becomes clouds",
    t4_h3: "Rivers flow back",
    t4_inst: "Follow the path of a water drop!",
    t4_w1: "Evaporation from sea",
    t4_w2: "Cooling up high",
    t4_w3: "Rain over land",
    t4_w4: "Return flow in river",
    t4_q: "What provides the energy for the water cycle?",
    t4_qa: "The Sun", t4_qb: "The Wind", t4_qc: "The Tides", t4_qd: "The Fish",

    t5_title: "Earth's Memory",
    t5_text: "Rocks tell stories. Some form from glowing magma, others are pressed together over millions of years on the seabed.",
    t5_h1: "Igneous = Frozen fire",
    t5_h2: "Sedimentary = Layered sand",
    t5_h3: "Metamorphic = Transformed",
    t5_inst: "Collect 5 basalt rocks (volcanic) for our lab!",
    t5_q: "Which rock is formed by the accumulation of sand and shells?",
    t5_qa: "Sedimentary rock", t5_qb: "Volcanic rock", t5_qc: "Gems", t5_qd: "Space junk",
  },
  hu: {
    explorer_title: "Föld és Éghajlat",
    t1_title: "Az Alpoktól a tengerig",
    t1_text: "Németország az ellentétek földje. Északon a szél korbácsolja a partokat, délen pedig az Alpok magas csúcsai nyúlnak az ég felé.",
    t1_h1: "Partvidék északon",
    t1_h2: "Hegységek délen",
    t1_h3: "Közöttük nagy alföldek",
    t1_inst: "Rendeld a városokat a régiójukhoz!",
    t1_l1: "Hamburg", t1_r1: "Közel a parthoz",
    t1_l2: "München", t1_r2: "Közel az Alpokhoz",
    t1_l3: "Berlin", t1_r3: "Az alföldön",
    t1_q: "Melyik hegység alkotja Németország déli határát?",
    t1_qa: "Az Alpok", t1_qb: "A Harz", t1_qc: "A Fekete-erdő", t1_qd: "Az Andok",

    t2_title: "Utazás a Föld középpontja felé",
    t2_text: "Képzeld el a Földet, mint egy őszibarackot. A héja a kéreg, a húsa a köpeny, a magja pedig a forró belső mag.",
    t2_h1: "Kéreg = Itt élünk mi",
    t2_h2: "Köpeny = Forró kőzet",
    t2_h3: "Mag = Vas és hőség",
    t2_inst: "Hol járunk? Nevezd meg a rétegeket!",
    t2_area_crust: "Földkéreg (szilárd)",
    t2_area_mantle: "Földköpeny (képlékeny)",
    t2_area_outer_core: "Külső mag (folyékony)",
    t2_area_inner_core: "Belső mag (szilárd)",
    t2_q: "Melyik a legvékonyabb réteg?",
    t2_qa: "Földkéreg", t2_qb: "Földköpeny", t2_qc: "Földmag", t2_qd: "Óceán",

    t3_title: "A jégtől a dzsungelig",
    t3_text: "Az éghajlati övezetek olyanok, mint az övek a Föld körül. Az Egyenlítőnél esőerdők nőnek, a sarkokon örök jég uralkodik.",
    t3_h1: "Egyenlítő = Forró és párás",
    t3_h2: "Sarkok = Hideg és száraz",
    t3_h3: "Mi középen lakunk",
    t3_inst: "Válogasd szét a jellemzőket!",
    t3_bucket_tropic: "Trópusi esőerdő",
    t3_bucket_polar: "Sarkvidéki jégmező",
    t3_item_palm: "Óriási páfrányok",
    t3_item_jungle: "Színes papagájok",
    t3_item_ice: "Jegesmedvék",
    t3_item_penguin: "Hóviharok",
    t3_q: "Hol van egész évben majdnem ugyanolyan meleg és esős idő?",
    t3_qa: "A trópusokon", t3_qb: "Az Északi-sarkon", t3_qc: "Magyarországon", t3_qd: "A Góbi sivatagban",

    t4_title: "Az örök körforgás",
    t4_text: "Egyetlen csepp víz sem vész el. A víz, amit ma iszol, lehet, hogy régen egy felhő része volt az óceán felett.",
    t4_h1: "A Nap hajt mindent",
    t4_h2: "A gőz felhővé válik",
    t4_h3: "A folyók visszatérnek",
    t4_inst: "Kövesd egy vízcsepp útját!",
    t4_w1: "Párolgás a tengerből",
    t4_w2: "Lehűlés a magasban",
    t4_w3: "Eső a szárazföld felett",
    t4_w4: "Visszafolyás a folyóban",
    t4_q: "Mi adja az energiát a víz körforgásához?",
    t4_qa: "A Nap", t4_qb: "A szél", t4_qc: "Az árapály", t4_qd: "A halak",

    t5_title: "A Föld emlékezete",
    t5_text: "A kövek történeteket mesélnek. Van, amelyik izzó magmából születik, mások millió évek alatt préselődnek össze a tengerfenéken.",
    t5_h1: "Magmás = Megfagyott tűz",
    t5_h2: "Üledékes = Réteges homok",
    t5_h3: "Átalakult = Megváltozott",
    t5_inst: "Gyűjts össze 5 bazaltkövet (vulkáni) a laborunkhoz!",
    t5_q: "Melyik kőzet keletkezik homok és kagylók lerakódásából?",
    t5_qa: "Üledékes kőzet", t5_qb: "Vulkáni kőzet", t5_qc: "Drágakövek", t5_qd: "Űrszemét",
  },
  ro: {
    explorer_title: "Pământ și Climă",
    t1_title: "De la Marea Nordului la Alpi",
    t1_text: "Germania este o țară a contrastelor. În nord, vântul biciuiește coastele, în timp ce în sud, vârfurile înalte ale Alpilor ating cerul.",
    t1_h1: "Coasta în Nord",
    t1_h2: "Munții în Sud",
    t1_h3: "Câmpii întinse între ele",
    t1_inst: "Atribuie orașele regiunii lor!",
    t1_l1: "Hamburg", t1_r1: "Lângă coastă",
    t1_l2: "München", t1_r2: "Lângă Alpi",
    t1_l3: "Berlin", t1_r3: "În câmpie",
    t1_q: "Ce lanț muntos formează granița de sud a Germaniei?",
    t1_qa: "Alpii", t1_qb: "Harz", t1_qc: "Pădurea Neagră", t1_qd: "Anzii",

    t2_title: "Călătorie spre nucleu",
    t2_text: "Imaginează-ți Pământul ca pe o piersică. Crusta este coaja subțire, pulpa este mantaua, iar sâmburele din mijloc este nucleul extrem de fierbinte.",
    t2_h1: "Crusta = Casa noastră",
    t2_h2: "Mantaua = Rocă fierbinte",
    t2_h3: "Nucleul = Fier și căldură",
    t2_inst: "Unde ne aflăm? Etichetează straturile Pământului!",
    t2_area_crust: "Crusta (solidă)",
    t2_area_mantle: "Mantaua (vâscoasă)",
    t2_area_outer_core: "Nucleul extern (lichid)",
    t2_area_inner_core: "Nucleul intern (solid)",
    t2_q: "Care strat este cel mai subțire?",
    t2_qa: "Crusta", t2_qb: "Mantaua", t2_qc: "Nucleul", t2_qd: "Oceanul",

    t3_title: "De la gheață la junglă",
    t3_text: "Zonele climatice sunt ca niște centuri în jurul Pământului. Lângă soare la Ecuator crește jungla, la capete stăpânește gheața veșnică.",
    t3_h1: "Ecuator = Cald și Umed",
    t3_h2: "Poli = Frig și Uscat",
    t3_h3: "Locuim la mijloc",
    t3_inst: "Sortează caracteristicile tipice!",
    t3_bucket_tropic: "Pădurea tropicală",
    t3_bucket_polar: "Zona de gheață polară",
    t3_item_palm: "Ferigi uriașe",
    t3_item_jungle: "Papagali colorați",
    t3_item_ice: "Urși polari",
    t3_item_penguin: "Furtuni de zăpadă",
    t3_q: "Unde este aproape la fel de cald și ploios tot anul?",
    t3_qa: "În tropice", t3_qb: "La Polul Nord", t3_qc: "În România", t3_qd: "În deșertul Gobi",

    t4_title: "Circuitul etern",
    t4_text: "Nicio picătură de apă nu se pierde. Apa pe care o bei astăzi a fost poate cândva parte dintr-un nor deasupra oceanului.",
    t4_h1: "Soarele conduce totul",
    t4_h2: "Aburul devine nori",
    t4_h3: "Râurile curg înapoi",
    t4_inst: "Urmează traseul unei picături de apă!",
    t4_w1: "Evaporare din mare",
    t4_w2: "Răcire la înălțime",
    t4_w3: "Ploaie peste pământ",
    t4_w4: "Retur prin râu",
    t4_q: "Ce furnizează energia pentru circuitul apei?",
    t4_qa: "Soarele", t4_qb: "Vântul", t4_qc: "Mareele", t4_qd: "Peștii",

    t5_title: "Memoria Pământului",
    t5_text: "Pietrele spun povești. Unele se nasc din magmă încinsă, altele sunt presate timp de milioane de ani pe fundul mării.",
    t5_h1: "Magmatice = Foc înghețat",
    t5_h2: "Sedimentare = Nisip stratificat",
    t5_h3: "Metamorfice = Transformate",
    t5_inst: "Colectează 5 roci de bazalt (vulcanice) pentru laborator!",
    t5_q: "Ce rocă se formează prin acumularea de nisip și scoici?",
    t5_qa: "Roca sedimentară", t5_qb: "Roca vulcanică", t5_qc: "Pietre prețioase", t5_qd: "Deșeuri spațiale",
  },
};

export const GEO_K6_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🏔️", title: "Landscapes", bg: "#F8FAFC" },
    bulletKeys: ["t1_h1", "t1_h2", "t1_h3"],
    interactive: {
      type: "match-pairs",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h3",
      pairs: [
        { left: "t1_l1", right: "t1_r1" },
        { left: "t1_l2", right: "t1_r2" },
        { left: "t1_l3", right: "t1_r3" },
      ],
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🌋", title: "Layers", bg: "#FEF2F2" },
    bulletKeys: ["t2_h1", "t2_h2", "t2_h3"],
    interactive: {
      type: "label-diagram",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h3",
      areas: [
        { id: "crust", x: 50, y: 10, label: "t2_area_crust" },
        { id: "mantle", x: 50, y: 35, label: "t2_area_mantle" },
        { id: "outer", x: 50, y: 65, label: "t2_area_outer_core" },
        { id: "inner", x: 50, y: 85, label: "t2_area_inner_core" },
      ],
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: {
      type: "two-groups",
      left: { items: ["🌴", "🦜"], bg: "#DCFCE7", border: "#22C55E" },
      right: { items: ["❄️", "🧊"], bg: "#EFF6FF", border: "#3B82F6" },
      bg: "#F8FAFC",
    },
    bulletKeys: ["t3_h1", "t3_h2", "t3_h3"],
    interactive: {
      type: "drag-to-bucket",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
      buckets: [
        { id: "tropic", label: "t3_bucket_tropic" },
        { id: "polar", label: "t3_bucket_polar" },
      ],
      items: [
        { text: "t3_item_palm", bucketId: "tropic" },
        { text: "t3_item_jungle", bucketId: "tropic" },
        { text: "t3_item_ice", bucketId: "polar" },
        { text: "t3_item_penguin", bucketId: "polar" },
      ],
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "💧", title: "Cycle", bg: "#F0F9FF" },
    bulletKeys: ["t4_h1", "t4_h2", "t4_h3"],
    interactive: {
      type: "word-order",
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h3",
      words: ["t4_w1", "t4_w2", "t4_w3", "t4_w4"],
      correctOrder: [0, 1, 2, 3],
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "icon-grid", items: [{ emoji: "🪨" }, { emoji: "🌋" }, { emoji: "🐚" }], bg: "#F1F5F9" },
    bulletKeys: ["t5_h1", "t5_h2", "t5_h3"],
    interactive: {
      type: "tap-count",
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
      tapCount: { emoji: "🪨", count: 5 },
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
];
