// @ts-nocheck
// lib/explorerPools/informatikaK4_i1.ts
import type { PoolTopicDef } from "./types";

export const INFO_K4_I1_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Python für Anfänger",
    t1_title: "Variable", t1_text: "Eine Variable speichert einen Wert, den du später nutzen kannst.", t1_inst: "Verbinde die Paare:", t1_h1: "Werte speichern.", t1_h2: "Wie eine Box.", t1_q: "Was macht x = 5?", t1_qa: "Speichert 5 in x", t1_qb: "Rechnet 5+x", t1_qc: "Löscht x", t1_qd: "Druckt x",
    t1_l1: "Variable", t1_r1: "Wert", t1_l2: "=", t1_r2: "Zuweisung", t1_l3: "x", t1_r3: "Name",
    t2_title: "Print", t2_text: "Mit print() kannst du Text oder Zahlen auf dem Bildschirm anzeigen.", t2_inst: "Verbinde die Paare:", t2_h1: "Text ausgeben.", t2_h2: "Hallo Welt!", t2_q: "Was macht print('Hallo')?", t2_qa: "Zeigt Hallo an", t2_qb: "Löscht den Text", t2_qc: "Speichert Hallo", t2_qd: "Fragt nach Hallo",
    t2_l1: "print", t2_r1: "Ausgabe", t2_l2: "Klammern", t2_r2: "Funktion", t2_l3: "Anführungszeichen", t2_r3: "Text",
    t3_title: "Input", t3_text: "Mit input() kann der Benutzer dem Programm etwas mitteilen.", t3_inst: "Verbinde die Paare:", t3_h1: "Daten eingeben.", t3_h2: "Tastatur nutzen.", t3_q: "Wofür ist input()?", t3_qa: "Benutzereingabe", t3_qb: "Bildschirm löschen", t3_qc: "Programm beenden", t3_qd: "Musik abspielen",
    t3_l1: "input", t3_r1: "Eingabe", t3_l2: "Tastatur", t3_r2: "Schreiben", t3_l3: "Frage", t3_r3: "Antwort",
    t4_title: "Zahlen", t4_text: "Python kennt ganze Zahlen (int) und Kommazahlen (float).", t4_inst: "Verbinde die Paare:", t4_h1: "Rechnen mit Python.", t4_h2: "Mathe-Power.", t4_q: "Was ist 5.5 in Python?", t4_qa: "Ein float", t4_qb: "Ein int", t4_qc: "Ein Text", t4_qd: "Ein Fehler",
    t4_l1: "int", t4_r1: "Ganze Zahl", t4_l2: "float", t4_r2: "Kommazahl", t4_l3: "5", t4_r3: "Zahl",
    t5_title: "Strings", t5_text: "Text wird in Python 'String' genannt und steht in Anführungszeichen.", t5_inst: "Verbinde die Paare:", t5_h1: "Wörter und Sätze.", t5_h2: "Text-Ketten.", t5_q: "Wie schreibt man Text?", t5_qa: "'Hallo'", t5_qb: "Hallo", t5_qc: "(Hallo)", t5_qd: "[Hallo]",
    t5_l1: "String", t5_r1: "Text", t5_l2: "Quotes", t5_r2: "Anführungszeichen", t5_l3: "Buchstabe", t5_r3: "Zeichen",
    t6_title: "Listen", t6_text: "In einer Liste kannst du viele Dinge zusammen speichern.", t6_inst: "Verbinde die Paare:", t6_h1: "Sachen sammeln.", t6_h2: "Einkaufsliste.", t6_q: "Wie sieht eine Liste aus?", t6_qa: "[1, 2, 3]", t6_qb: "(1, 2, 3)", t6_qc: "{1, 2, 3}", t6_qd: "<1, 2, 3>",
    t6_l1: "Liste", t6_r1: "Sammlung", t6_l2: "Klammern []", t6_r2: "Eckig", t6_l3: "Komma", t6_r3: "Trennen",
    t7_title: "If-Abfrage", t7_text: "Mit 'if' kann das Programm Entscheidungen treffen.", t7_inst: "Verbinde die Paare:", t7_h1: "Wenn-Dann.", t7_h2: "Entscheidungen.", t7_q: "Was macht 'if x > 5:'?", t7_qa: "Prüft ob x größer 5 ist", t7_qb: "Macht x zu 5", t7_qc: "Löscht x", t7_qd: "Druckt x",
    t7_l1: "if", t7_r1: "Wenn", t7_l2: "else", t7_r2: "Sonst", t7_l3: "Doppelpunkt", t7_r3: "Start",
    t8_title: "For-Schleife", t8_text: "Eine Schleife wiederholt Aufgaben mehrmals.", t8_inst: "Verbinde die Paare:", t8_h1: "Wiederholung.", t8_h2: "Immer wieder.", t8_q: "Was macht eine Schleife?", t8_qa: "Wiederholt Code", t8_qb: "Beendet das Programm", t8_qc: "Löscht alles", t8_qd: "Nichts",
    t8_l1: "for", t8_r1: "Schleife", t8_l2: "range", t8_r2: "Bereich", t8_l3: "i", t8_r3: "Zähler",
    t9_title: "Funktionen", t9_text: "Funktionen sind kleine Programme im Programm, die Aufgaben lösen.", t9_inst: "Verbinde die Paare:", t9_h1: "Code-Bausteine.", t9_h2: "Wiederverwendbar.", t9_q: "Wie startet man eine Funktion?", t9_qa: "def name():", t9_qb: "start name:", t9_qc: "function name:", t9_qd: "make name:",
    t9_l1: "def", t9_r1: "Definieren", t9_l2: "Funktion", t9_r2: "Aufgabe", t9_l3: "Aufruf", t9_r3: "Starten",
    t10_title: "Return", t10_text: "Mit return gibt eine Funktion ein Ergebnis zurück.", t10_inst: "Verbinde die Paare:", t10_h1: "Ergebnis liefern.", t10_h2: "Zurückgeben.", t10_q: "Was macht return?", t10_qa: "Gibt Wert zurück", t10_qb: "Beendet Computer", t10_qc: "Löscht Funktion", t10_qd: "Druckt Text",
    t10_l1: "return", t10_r1: "Zurückgeben", t10_l2: "Ergebnis", t10_r2: "Antwort", t10_l3: "Ende", t10_r3: "Stopp",
    t11_title: "Kommentare", t11_text: "Kommentare helfen Menschen, den Code zu verstehen.", t11_inst: "Verbinde die Paare:", t11_h1: "Notizen machen.", t11_h2: "Wird ignoriert.", t11_q: "Wie beginnt ein Kommentar?", t11_qa: "Mit #", t11_qb: "Mit //", t11_qc: "Mit --", t11_qd: "Mit !!",
    t11_l1: "#", t11_r1: "Kommentar", t11_l2: "Notiz", t11_r2: "Erklärung", t11_l3: "Code", t11_r3: "Programm",
    t12_title: "Operatoren", t12_text: "Mit Operatoren kannst du rechnen: +, -, *, /.", t12_inst: "Verbinde die Paare:", t12_h1: "Mathe-Zeichen.", t12_h2: "Rechnen.", t12_q: "Was ist das Zeichen für Mal?", t12_qa: "*", t12_qb: "x", t12_qc: "•", t12_qd: "#",
    t12_l1: "+", t12_r1: "Plus", t12_l2: "*", t12_r2: "Mal", t12_l3: "/", t12_r3: "Geteilt",
    t13_title: "Vergleiche", t13_text: "Du kannst Werte vergleichen, z.B. ob sie gleich sind.", t13_inst: "Verbinde die Paare:", t13_h1: "Größer oder kleiner.", t13_h2: "Checken.", t13_q: "Wie prüft man auf Gleichheit?", t13_qa: "==", t13_qb: "=", t13_qc: "===", t13_qd: "!=",
    t13_l1: "==", t13_r1: "Gleich", t13_l2: ">", t13_r2: "Größer", t13_l3: "<", t13_r3: "Kleiner",
    t14_title: "Logik", t14_text: "Mit and, or und not kannst du Bedingungen verknüpfen.", t14_inst: "Verbinde die Paare:", t14_h1: "Und / Oder.", t14_h2: "Logisches Denken.", t14_q: "Was bedeutet 'and'?", t14_qa: "Beides muss stimmen", t14_qb: "Eins reicht", t14_qc: "Nichts stimmt", t14_qd: "Vielleicht",
    t14_l1: "and", t14_r1: "Und", t14_l2: "or", t14_r2: "Oder", t14_l3: "not", t14_r3: "Nicht",
    t15_title: "Python-Profi", t15_text: "Du kennst jetzt die Grundlagen von Python!", t15_inst: "Verbinde die Paare:", t15_h1: "Super gemacht.", t15_h2: "Fertig!", t15_q: "Was ist Python?", t15_qa: "Eine Programmiersprache", t15_qb: "Nur eine Schlange", t15_qc: "Ein Spielzeug", t15_qd: "Ein Essen",
    t15_l1: "Python", t15_r1: "Sprache", t15_l2: "Code", t15_r2: "Programm", t15_l3: "Profi", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "Python for Beginners",
    t1_title: "Variable", t1_text: "A variable stores a value you can use later.", t1_inst: "Match the pairs:", t1_h1: "Store values.", t1_h2: "Like a box.", t1_q: "What does x = 5 do?", t1_qa: "Stores 5 in x", t1_qb: "Calculates 5+x", t1_qc: "Deletes x", t1_qd: "Prints x",
    t1_l1: "Variable", t1_r1: "Value", t1_l2: "=", t1_r2: "Assignment", t1_l3: "x", t1_r3: "Name",
    t2_title: "Print", t2_text: "Use print() to show text or numbers on the screen.", t2_inst: "Match the pairs:", t2_h1: "Output text.", t2_h2: "Hello World!", t2_q: "What does print('Hello') do?", t2_qa: "Shows Hello", t2_qb: "Deletes text", t2_qc: "Saves Hello", t2_qd: "Asks for Hello",
    t2_l1: "print", t2_r1: "Output", t2_l2: "Parentheses", t2_r2: "Function", t2_l3: "Quotes", t2_r3: "Text",
    t3_title: "Input", t3_text: "With input(), the user can tell something to the program.", t3_inst: "Match the pairs:", t3_h1: "Enter data.", t3_h2: "Use keyboard.", t3_q: "What is input() for?", t3_qa: "User input", t3_qb: "Clear screen", t3_qc: "End program", t3_qd: "Play music",
    t3_l1: "input", t3_r1: "Input", t3_l2: "Keyboard", t3_r2: "Type", t3_l3: "Question", t3_r3: "Answer",
    t4_title: "Numbers", t4_text: "Python knows whole numbers (int) and decimal numbers (float).", t4_inst: "Match the pairs:", t4_h1: "Math with Python.", t4_h2: "Math power.", t4_q: "What is 5.5 in Python?", t4_qa: "A float", t4_qb: "An int", t4_qc: "A text", t4_qd: "An error",
    t4_l1: "int", t4_r1: "Integer", t4_l2: "float", t4_r2: "Decimal", t4_l3: "5", t4_r3: "Number",
    t5_title: "Strings", t5_text: "Text in Python is called a 'String' and is put in quotes.", t5_inst: "Match the pairs:", t5_h1: "Words and sentences.", t5_h2: "Text chains.", t5_q: "How do you write text?", t5_qa: "'Hello'", t5_qb: "Hello", t5_qc: "(Hello)", t5_qd: "[Hello]",
    t5_l1: "String", t5_r1: "Text", t5_l2: "Quotes", t5_r2: "Quotation marks", t5_l3: "Letter", t5_r3: "Character",
    t6_title: "Lists", t6_text: "In a list, you can store many things together.", t6_inst: "Match the pairs:", t6_h1: "Collect things.", t6_h2: "Shopping list.", t6_q: "What does a list look like?", t6_qa: "[1, 2, 3]", t6_qb: "(1, 2, 3)", t6_qc: "{1, 2, 3}", t6_qd: "<1, 2, 3>",
    t6_l1: "List", t6_r1: "Collection", t6_l2: "Brackets []", t6_r2: "Square", t6_l3: "Comma", t6_r3: "Separate",
    t7_title: "If Statement", t7_text: "With 'if', the program can make decisions.", t7_inst: "Match the pairs:", t7_h1: "If-Then.", t7_h2: "Decisions.", t7_q: "What does 'if x > 5:' do?", t7_qa: "Checks if x is > 5", t7_qb: "Makes x equal 5", t7_qc: "Deletes x", t7_qd: "Prints x",
    t7_l1: "if", t7_r1: "If", t7_l2: "else", t7_r2: "Else", t7_l3: "Colon", t7_r3: "Start",
    t8_title: "For Loop", t8_text: "A loop repeats tasks multiple times.", t8_inst: "Match the pairs:", t8_h1: "Repetition.", t8_h2: "Again and again.", t8_q: "What does a loop do?", t8_qa: "Repeats code", t8_qb: "Ends program", t8_qc: "Deletes everything", t8_qd: "Nothing",
    t8_l1: "for", t8_r1: "Loop", t8_l2: "range", t8_r2: "Range", t8_l3: "i", t8_r3: "Counter",
    t9_title: "Functions", t9_text: "Functions are small programs within the program that solve tasks.", t9_inst: "Match the pairs:", t9_h1: "Code blocks.", t9_h2: "Reusable.", t9_q: "How do you start a function?", t9_qa: "def name():", t9_qb: "start name:", t9_qc: "function name:", t9_qd: "make name:",
    t9_l1: "def", t9_r1: "Define", t9_l2: "Function", t9_r2: "Task", t9_l3: "Call", t9_r3: "Start",
    t10_title: "Return", t10_text: "With return, a function gives back a result.", t10_inst: "Match the pairs:", t10_h1: "Provide result.", t10_h2: "Give back.", t10_q: "What does return do?", t10_qa: "Returns value", t10_qb: "Ends computer", t10_qc: "Deletes function", t10_qd: "Prints text",
    t10_l1: "return", t10_r1: "Return", t10_l2: "Result", t10_r2: "Answer", t10_l3: "End", t10_r3: "Stop",
    t11_title: "Comments", t11_text: "Comments help people understand the code.", t11_inst: "Match the pairs:", t11_h1: "Make notes.", t11_h2: "Ignored by computer.", t11_q: "How does a comment start?", t11_qa: "With #", t11_qb: "With //", t11_qc: "With --", t11_qd: "With !!",
    t11_l1: "#", t11_r1: "Comment", t11_l2: "Note", t11_r2: "Explanation", t11_l3: "Code", t11_r3: "Program",
    t12_title: "Operators", t12_text: "With operators you can calculate: +, -, *, /.", t12_inst: "Match the pairs:", t12_h1: "Math symbols.", t12_h2: "Calculating.", t12_q: "What is the symbol for multiply?", t12_qa: "*", t12_qb: "x", t12_qc: "•", t12_qd: "#",
    t12_l1: "+", t12_r1: "Plus", t12_l2: "*", t12_r2: "Times", t12_l3: "/", t12_r3: "Divide",
    t13_title: "Comparisons", t13_text: "You can compare values, e.g., if they are equal.", t13_inst: "Match the pairs:", t13_h1: "Greater or smaller.", t13_h2: "Checking.", t13_q: "How to check for equality?", t13_qa: "==", t13_qb: "=", t13_qc: "===", t13_qd: "!=",
    t13_l1: "==", t13_r1: "Equal", t13_l2: ">", t13_r2: "Greater", t13_l3: "<", t13_r3: "Smaller",
    t14_title: "Logic", t14_text: "With and, or, and not, you can combine conditions.", t14_inst: "Match the pairs:", t14_h1: "And / Or.", t14_h2: "Logical thinking.", t14_q: "What does 'and' mean?", t14_qa: "Both must be true", t14_qb: "One is enough", t14_qc: "None are true", t14_qd: "Maybe",
    t14_l1: "and", t14_r1: "And", t14_l2: "or", t14_r2: "Or", t14_l3: "not", t14_r3: "Not",
    t15_title: "Python Pro", t15_text: "You now know the basics of Python!", t15_inst: "Match the pairs:", t15_h1: "Great job.", t15_h2: "Finished!", t15_q: "What is Python?", t15_qa: "A programming language", t15_qb: "Just a snake", t15_qc: "A toy", t15_qd: "A food",
    t15_l1: "Python", t15_r1: "Language", t15_l2: "Code", t15_r2: "Program", t15_l3: "Pro", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "Python kezdőknek",
    t1_title: "Változó", t1_text: "A változó eltárol egy értéket, amit később használhatsz.", t1_inst: "Párosítsd össze:", t1_h1: "Értékek tárolása.", t1_h2: "Mint egy doboz.", t1_q: "Mit csinál az x = 5?", t1_qa: "Eltárolja az 5-öt x-ben", t1_qb: "Kiszámolja az 5+x-et", t1_qc: "Törli az x-et", t1_qd: "Kiírja az x-et",
    t1_l1: "Változó", t1_r1: "Érték", t1_l2: "=", t1_r2: "Hozzárendelés", t1_l3: "x", t1_r3: "Név",
    t2_title: "Print", t2_text: "A print() függvénnyel szöveget vagy számokat írathatsz ki a képernyőre.", t2_inst: "Párosítsd össze:", t2_h1: "Szöveg kiírása.", t2_h2: "Helló Világ!", t2_q: "Mit csinál a print('Szia')?", t2_qa: "Kiírja, hogy Szia", t2_qb: "Törli a szöveget", t2_qc: "Elmenti a Sziát", t2_qd: "Megkérdezi a Sziát",
    t2_l1: "print", t2_r1: "Kimenet", t2_l2: "Zárójelek", t2_r2: "Függvény", t2_l3: "Idézőjelek", t2_r3: "Szöveg",
    t3_title: "Input", t3_text: "Az input() segítségével a felhasználó üzenhet a programnak.", t3_inst: "Párosítsd össze:", t3_h1: "Adatbevitel.", t3_h2: "Használd a billentyűzetet.", t3_q: "Mire jó az input()?", t3_qa: "Felhasználói bevitel", t3_qb: "Képernyő törlése", t3_qc: "Program leállítása", t3_qd: "Zenelejátszás",
    t3_l1: "input", t3_r1: "Bevitel", t3_l2: "Billentyűzet", t3_r2: "Gépelés", t3_l3: "Kérdés", t3_r3: "Válasz",
    t4_title: "Számok", t4_text: "A Python ismeri az egész számokat (int) és a tizedes törteket (float).", t4_inst: "Párosítsd össze:", t4_h1: "Matek Pythonnal.", t4_h2: "Számolási erő.", t4_q: "Mi az 5.5 a Pythonban?", t4_qa: "Egy float", t4_qb: "Egy int", t4_qc: "Egy szöveg", t4_qd: "Egy hiba",
    t4_l1: "int", t4_r1: "Egész szám", t4_l2: "float", t4_r2: "Tizedes tört", t4_l3: "5", t4_r3: "Szám",
    t5_title: "Szövegek", t5_text: "A szöveget a Pythonban 'String'-nek hívjuk, és idézőjelbe tesszük.", t5_inst: "Párosítsd össze:", t5_h1: "Szavak és mondatok.", t5_h2: "Szövegláncok.", t5_q: "Hogyan írunk szöveget?", t5_qa: "'Szia'", t5_qb: "Szia", t5_qc: "(Szia)", t5_qd: "[Szia]",
    t5_l1: "String", t5_r1: "Szöveg", t5_l2: "Idézőjelek", t5_r2: "Karakterek", t5_l3: "Betű", t5_r3: "Jel",
    t6_title: "Listák", t6_text: "Egy listában sok dolgot tudsz egyszerre tárolni.", t6_inst: "Párosítsd össze:", t6_h1: "Dolgok gyűjtése.", t6_h2: "Bevásárlólista.", t6_q: "Hogy néz ki egy lista?", t6_qa: "[1, 2, 3]", t6_qb: "(1, 2, 3)", t6_qc: "{1, 2, 3}", t6_qd: "<1, 2, 3>",
    t6_l1: "Lista", t6_r1: "Gyűjtemény", t6_l2: "Zárójelek []", t6_r2: "Szögletes", t6_l3: "Vessző", t6_r3: "Elválasztás",
    t7_title: "If elágazás", t7_text: "Az 'if' segítségével a program döntéseket tud hozni.", t7_inst: "Párosítsd össze:", t7_h1: "Ha-Akkor.", t7_h2: "Döntések.", t7_q: "Mit csinál az 'if x > 5:'?", t7_qa: "Megnézi, nagyobb-e x mint 5", t7_qb: "x-et 5-re állítja", t7_qc: "Törli az x-et", t7_qd: "Kiírja az x-et",
    t7_l1: "if", t7_r1: "Ha", t7_l2: "else", t7_r2: "Különben", t7_l3: "Kettőspont", t7_r3: "Kezdet",
    t8_title: "For ciklus", t8_text: "A ciklus többször megismétel feladatokat.", t8_inst: "Párosítsd össze:", t8_h1: "Ismétlés.", t8_h2: "Újra és újra.", t8_q: "Mit csinál a ciklus?", t8_qa: "Kódot ismétel", t8_qb: "Leállítja a gépet", t8_qc: "Mindent töröl", t8_qd: "Semmit",
    t8_l1: "for", t8_r1: "Ciklus", t8_l2: "range", t8_r2: "Tartomány", t8_l3: "i", t8_r3: "Számláló",
    t9_title: "Függvények", t9_text: "A függvények kis programok a programban, amik feladatokat oldanak meg.", t9_inst: "Párosítsd össze:", t9_h1: "Kód-építőelemek.", t9_h2: "Újrafelhasználható.", t9_q: "Hogy kezdünk egy függvényt?", t9_qa: "def név():", t9_qb: "start név:", t9_qc: "function név:", t9_qd: "make név:",
    t9_l1: "def", t9_r1: "Definiálás", t9_l2: "Függvény", t9_r2: "Feladat", t9_l3: "Hívás", t9_r3: "Indítás",
    t10_title: "Return", t10_text: "A return segítségével a függvény visszaad egy eredményt.", t10_inst: "Párosítsd össze:", t10_h1: "Eredmény küldése.", t10_h2: "Visszaadás.", t10_q: "Mit csinál a return?", t10_qa: "Értéket ad vissza", t10_qb: "Kikapcsolja a gépet", t10_qc: "Törli a függvényt", t10_qd: "Szöveget ír",
    t10_l1: "return", t10_r1: "Visszaadás", t10_l2: "Eredmény", t10_r2: "Válasz", t10_l3: "Vége", t10_r3: "Stop",
    t11_title: "Kommentek", t11_text: "A kommentek segítenek az embereknek megérteni a kódot.", t11_inst: "Párosítsd össze:", t11_h1: "Jegyzetelés.", t11_h2: "A gép kihagyja.", t11_q: "Mivel kezdődik a komment?", t11_qa: "# jellel", t11_qb: "// jellel", t11_qc: "-- jellel", t11_qd: "!! jellel",
    t11_l1: "#", t11_r1: "Komment", t11_l2: "Jegyzet", t11_r2: "Magyarázat", t11_l3: "Kód", t11_r3: "Program",
    t12_title: "Operátorok", t12_text: "Az operátorokkal tudsz számolni: +, -, *, /.", t12_inst: "Párosítsd össze:", t12_h1: "Matek jelek.", t12_h2: "Számolás.", t12_q: "Mi a szorzás jele?", t12_qa: "*", t12_qb: "x", t12_qc: "•", t12_qd: "#",
    t12_l1: "+", t12_r1: "Plusz", t12_l2: "*", t12_r2: "Szorzás", t12_l3: "/", t12_r3: "Osztás",
    t13_title: "Összehasonlítás", t13_text: "Össze tudsz hasonlítani értékeket, pl. hogy egyenlőek-e.", t13_inst: "Párosítsd össze:", t13_h1: "Nagyobb vagy kisebb.", t13_h2: "Ellenőrzés.", t13_q: "Hogy nézzük meg az egyenlőséget?", t13_qa: "==", t13_qb: "=", t13_qc: "===", t13_qd: "!=",
    t13_l1: "==", t13_r1: "Egyenlő", t13_l2: ">", t13_r2: "Nagyobb", t13_l3: "<", t13_r3: "Kisebb",
    t14_title: "Logika", t14_text: "Az and, or és not segítségével feltételeket kapcsolhatsz össze.", t14_inst: "Párosítsd össze:", t14_h1: "És / Vagy.", t14_h2: "Logikus gondolkodás.", t14_q: "Mit jelent az 'and'?", t14_qa: "Mindkettő igaz", t14_qb: "Az egyik elég", t14_qc: "Egyik sem igaz", t14_qd: "Talán",
    t14_l1: "and", t14_r1: "És", t14_l2: "or", t14_r2: "Vagy", t14_l3: "not", t14_r3: "Nem",
    t15_title: "Python profi", t15_text: "Most már ismered a Python alapjait!", t15_inst: "Párosítsd össze:", t15_h1: "Szép munka.", t15_h2: "Kész!", t15_q: "Mi a Python?", t15_qa: "Egy programozási nyelv", t15_qb: "Csak egy kígyó", t15_qc: "Egy játék", t15_qd: "Egy étel",
    t15_l1: "Python", t15_r1: "Nyelv", t15_l2: "Kód", t15_r2: "Program", t15_l3: "Profi", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Python pentru începători",
    t1_title: "Variabilă", t1_text: "O variabilă stochează o valoare pe care o poți folosi mai târziu.", t1_inst: "Potrivește perechile:", t1_h1: "Stocare valori.", t1_h2: "Ca o cutie.", t1_q: "Ce face x = 5?", t1_qa: "Stochează 5 în x", t1_qb: "Calculează 5+x", t1_qc: "Șterge x", t1_qd: "Afișează x",
    t1_l1: "Variabilă", t1_r1: "Valoare", t1_l2: "=", t1_r2: "Atribuire", t1_l3: "x", t1_r3: "Nume",
    t2_title: "Print", t2_text: "Cu print() poți afișa text sau numere pe ecran.", t2_inst: "Potrivește perechile:", t2_h1: "Afișare text.", t2_h2: "Salut Lume!", t2_q: "Ce face print('Salut')?", t2_qa: "Afișează Salut", t2_qb: "Șterge textul", t2_qc: "Salvează Salut", t2_qd: "Întreabă Salut",
    t2_l1: "print", t2_r1: "Ieșire", t2_l2: "Paranteze", t2_r2: "Funcție", t2_l3: "Ghilimele", t2_r3: "Text",
    t3_title: "Input", t3_text: "Cu input(), utilizatorul poate comunica ceva programului.", t3_inst: "Potrivește perechile:", t3_h1: "Introducere date.", t3_h2: "Folosește tastatura.", t3_q: "Pentru ce este input()?", t3_qa: "Introducere utilizator", t3_qb: "Șterge ecranul", t3_qc: "Oprește programul", t3_qd: "Redă muzică",
    t3_l1: "input", t3_r1: "Intrare", t3_l2: "Tastatură", t3_r2: "Scriere", t3_l3: "Întrebare", t3_r3: "Răspuns",
    t4_title: "Numere", t4_text: "Python cunoaște numere întregi (int) și numere cu virgulă (float).", t4_inst: "Potrivește perechile:", t4_h1: "Mate cu Python.", t4_h2: "Putere matematică.", t4_q: "Ce este 5.5 în Python?", t4_qa: "Un float", t4_qb: "Un int", t4_qc: "Un text", t4_qd: "O eroare",
    t4_l1: "int", t4_r1: "Întreg", t4_l2: "float", t4_r2: "Zecimal", t4_l3: "5", t4_r3: "Număr",
    t5_title: "Stringuri", t5_text: "Textul în Python se numește 'String' și se pune între ghilimele.", t5_inst: "Potrivește perechile:", t5_h1: "Cuvinte și propoziții.", t5_h2: "Lanțuri de text.", t5_q: "Cum se scrie textul?", t5_qa: "'Salut'", t5_qb: "Salut", t5_qc: "(Salut)", t5_qd: "[Salut]",
    t5_l1: "String", t5_r1: "Text", t5_l2: "Ghilimele", t5_r2: "Semne", t5_l3: "Literă", t5_r3: "Caracter",
    t6_title: "Liste", t6_text: "Într-o listă poți stoca mai multe lucruri împreună.", t6_inst: "Potrivește perechile:", t6_h1: "Colectare lucruri.", t6_h2: "Listă de cumpărături.", t6_q: "Cum arată o listă?", t6_qa: "[1, 2, 3]", t6_qb: "(1, 2, 3)", t6_qc: "{1, 2, 3}", t6_qd: "<1, 2, 3>",
    t6_l1: "Listă", t6_r1: "Colecție", t6_l2: "Paranteze []", t6_r2: "Pătrate", t6_l3: "Virgulă", t6_r3: "Separare",
    t7_title: "Instrucțiunea If", t7_text: "Cu 'if', programul poate lua decizii.", t7_inst: "Potrivește perechile:", t7_h1: "Dacă-Atunci.", t7_h2: "Decizii.", t7_q: "Ce face 'if x > 5:'?", t7_qa: "Verifică dacă x > 5", t7_qb: "Îl face pe x egal cu 5", t7_qc: "Șterge x", t7_qd: "Afișează x",
    t7_l1: "if", t7_r1: "Dacă", t7_l2: "else", t7_r2: "Altfel", t7_l3: "Două puncte", t7_r3: "Start",
    t8_title: "Bucla For", t8_text: "O buclă repetă sarcini de mai multe ori.", t8_inst: "Potrivește perechile:", t8_h1: "Repetiție.", t8_h2: "Iarăși și iarăși.", t8_q: "Ce face o buclă?", t8_qa: "Repetă codul", t8_qb: "Oprește programul", t8_qc: "Șterge tot", t8_qd: "Nimic",
    t8_l1: "for", t8_r1: "Buclă", t8_l2: "range", t8_r2: "Interval", t8_l3: "i", t8_r3: "Contor",
    t9_title: "Funcții", t9_text: "Funcțiile sunt mici programe în program care rezolvă sarcini.", t9_inst: "Potrivește perechile:", t9_h1: "Blocuri de cod.", t9_h2: "Reutilizabil.", t9_q: "Cum începi o funcție?", t9_qa: "def nume():", t9_qb: "start nume:", t9_qc: "function nume:", t9_qd: "make nume:",
    t9_l1: "def", t9_r1: "Definire", t9_l2: "Funcție", t9_r2: "Sarcină", t9_l3: "Apel", t9_r3: "Pornire",
    t10_title: "Return", t10_text: "Cu return, o funcție returnează un rezultat.", t10_inst: "Potrivește perechile:", t10_h1: "Oferă rezultat.", t10_h2: "Dă înapoi.", t10_q: "Ce face return?", t10_qa: "Returnează valoarea", t10_qb: "Oprește calculatorul", t10_qc: "Șterge funcția", t10_qd: "Afișează text",
    t10_l1: "return", t10_r1: "Returnare", t10_l2: "Rezultat", t10_r2: "Răspuns", t10_l3: "Sfârșit", t10_r3: "Stop",
    t11_title: "Comentarii", t11_text: "Comentariile ajută oamenii să înțeleagă codul.", t11_inst: "Potrivește perechile:", t11_h1: "Notează.", t11_h2: "Ignorat de calculator.", t11_q: "Cum începe un comentariu?", t11_qa: "Cu #", t11_qb: "Cu //", t11_qc: "Cu --", t11_qd: "Cu !!",
    t11_l1: "#", t11_r1: "Comentariu", t11_l2: "Notă", t11_r2: "Explicație", t11_l3: "Cod", t11_r3: "Program",
    t12_title: "Operatori", t12_text: "Cu operatori poți calcula: +, -, *, /.", t12_inst: "Potrivește perechile:", t12_h1: "Semne mate.", t12_h2: "Calculare.", t12_q: "Care este semnul pentru înmulțire?", t12_qa: "*", t12_qb: "x", t12_qc: "•", t12_qd: "#",
    t12_l1: "+", t12_r1: "Plus", t12_l2: "*", t12_r2: "Ori", t12_l3: "/", t12_r3: "Împărțit",
    t13_title: "Comparații", t13_text: "Poți compara valori, de exemplu dacă sunt egale.", t13_inst: "Potrivește perechile:", t13_h1: "Mai mare sau mic.", t13_h2: "Verificare.", t13_q: "Cum verifici egalitatea?", t13_qa: "==", t13_qb: "=", t13_qc: "===", t13_qd: "!=",
    t13_l1: "==", t13_r1: "Egal", t13_l2: ">", t13_r2: "Mai mare", t13_l3: "<", t13_r3: "Mai mic",
    t14_title: "Logică", t14_text: "Cu and, or și not poți combina condiții.", t14_inst: "Potrivește perechile:", t14_h1: "Și / Sau.", t14_h2: "Gândire logică.", t14_q: "Ce înseamnă 'and'?", t14_qa: "Ambele trebuie să fie adevărate", t14_qb: "Una e de ajuns", t14_qc: "Niciuna nu e adevărată", t14_qd: "Poate",
    t14_l1: "and", t14_r1: "Și", t14_l2: "or", t14_r2: "Sau", t14_l3: "not", t14_r3: "Nu",
    t15_title: "Pro Python", t15_text: "Acum cunoști bazele Python!", t15_inst: "Potrivește perechile:", t15_h1: "Bravo.", t15_h2: "Gata!", t15_q: "Ce este Python?", t15_qa: "Un limbaj de programare", t15_qb: "Doar un șarpe", t15_qc: "O jucărie", t15_qd: "Mâncare",
    t15_l1: "Python", t15_r1: "Limbaj", t15_l2: "Cod", t15_r2: "Program", t15_l3: "Pro", t15_r3: "Victorie"
  }
};

export const INFO_K4_I1_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["📦", "🖨️", "⌨️", "🔢", "📝", "📋", "🔀", "🔁", "⚙️", "↩️", "💬", "➗", "⚖️", "🔗", "🐍"];
  const colors = ["#4CAF50", "#2196F3", "#FF9800", "#9C27B0", "#E91E63", "#00BCD4", "#FFC107", "#8BC34A", "#3F51B5", "#795548", "#607D8B", "#F44336", "#9E9E9E", "#673AB7", "#FFD700"];
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { type: "match-pairs", instruction: `t${t}_inst`, hint1: `t${t}_h1`, hint2: `t${t}_h2`,
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

