// lib/explorerPools/informatikaK4_i4.ts
import type { PoolTopicDef } from "./types";

export const INFO_K4_I4_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "HTML & CSS Grundlagen",
    t1_title: "HTML", t1_text: "HTML ist die Sprache der Webseiten — damit sagst du dem Browser, was er anzeigen soll.", t1_inst: "Verbinde die Paare:", t1_h1: "Webseiten-Sprache.", t1_h2: "Struktur der Seite.", t1_q: "Was ist HTML?", t1_qa: "Webseiten-Beschreibungssprache", t1_qb: "Ein Spiel", t1_qc: "Ein Bild", t1_qd: "Eine Zahl",
    t1_l1: "HTML", t1_r1: "Webseite", t1_l2: "Browser", t1_r2: "Anzeige", t1_l3: "Code", t1_r3: "Text",
    t2_title: "Tag", t2_text: "Ein Tag ist ein HTML-Befehl, wie <p> für einen Absatz oder <h1> für eine Überschrift.", t2_inst: "Verbinde die Paare:", t2_h1: "HTML-Befehl.", t2_h2: "In spitzen Klammern.", t2_q: "Wie schreibt man einen Tag?", t2_qa: "In spitzen Klammern < >", t2_qb: "Mit Zahlen", t2_qc: "Mit Farben", t2_qd: "Gar nicht",
    t2_l1: "Tag", t2_r1: "Befehl", t2_l2: "<h1>", t2_r2: "Überschrift", t2_l3: "<p>", t2_r3: "Absatz",
    t3_title: "Attribut", t3_text: "Attribute geben Tags zusätzliche Infos, wie 'href' für einen Link oder 'src' für ein Bild.", t3_inst: "Verbinde die Paare:", t3_h1: "Zusatzinfo.", t3_h2: "Eigenschaften.", t3_q: "Was macht ein Attribut?", t3_qa: "Gibt Zusatzinfos", t3_qb: "Löscht den Tag", t3_qc: "Macht Musik", t3_qd: "Nichts",
    t3_l1: "Attribut", t3_r1: "Eigenschaft", t3_l2: "href", t3_r2: "Link-Ziel", t3_l3: "src", t3_r3: "Bild-Quelle",
    t4_title: "Überschrift", t4_text: "Mit h1 bis h6 kannst du Überschriften in verschiedenen Größen erstellen.", t4_inst: "Verbinde die Paare:", t4_h1: "Wichtiger Text.", t4_h2: "h1 ist am größten.", t4_q: "Welcher Tag ist die größte Überschrift?", t4_qa: "<h1>", t4_qb: "<h6>", t4_qc: "<p>", t4_qd: "<a>",
    t4_l1: "h1", t4_r1: "Größte", t4_l2: "h6", t4_r2: "Kleinste", t4_l3: "Heading", t4_r3: "Überschrift",
    t5_title: "Absatz", t5_text: "Der <p> Tag wird für normalen Text und Absätze verwendet.", t5_inst: "Verbinde die Paare:", t5_h1: "Normaler Text.", t5_h2: "Paragraph.", t5_q: "Wofür steht das 'p' in <p>?", t5_qa: "Paragraph (Absatz)", t5_qb: "Picture (Bild)", t5_qc: "Play (Spielen)", t5_qd: "Power",
    t5_l1: "<p>", t5_r1: "Absatz", t5_l2: "Text", t5_r2: "Inhalt", t5_l3: "Ende", t5_r3: "</p>",
    t6_title: "Link", t6_text: "Benutze <a href='...'>, um einen anklickbaren Link zu einer anderen Seite zu erstellen.", t6_inst: "Verbinde die Paare:", t6_h1: "Verbindung.", t6_h2: "Anklickbar.", t6_q: "Welcher Tag erstellt einen Link?", t6_qa: "<a>", t6_qb: "<img>", t6_qc: "<li>", t6_qd: "<div>",
    t6_l1: "<a>", t6_r1: "Anker/Link", t6_l2: "href", t6_r2: "Adresse", t6_l3: "Klick", t6_r3: "Ziel",
    t7_title: "Bild", t7_text: "Mit <img src='...'> fügst du Bilder in deine Webseite ein.", t7_inst: "Verbinde die Paare:", t7_h1: "Visueller Inhalt.", t7_h2: "Image.", t7_q: "Was braucht ein <img> Tag unbedingt?", t7_qa: "src Attribut", t7_qb: "Einen Text", t7_qc: "Eine Zahl", t7_qd: "Nichts",
    t7_l1: "<img>", t7_r1: "Bild", t7_l2: "src", t7_r2: "Quelle", t7_l3: "alt", t7_r3: "Ersatztext",
    t8_title: "Liste", t8_text: "Mit <ul> und <li> kannst du Aufzählungslisten erstellen.", t8_inst: "Verbinde die Paare:", t8_h1: "Aufzählung.", t8_h2: "Listenpunkte.", t8_q: "Was bedeutet 'ul'?", t8_qa: "Unordered List", t8_qb: "Under Line", t8_qc: "Ultra Link", t8_qd: "User List",
    t8_l1: "<ul>", t8_r1: "Liste", t8_l2: "<li>", t8_r2: "Listenpunkt", t8_l3: "<ol>", t8_r3: "Nummeriert",
    t9_title: "Div", t9_text: "Ein <div> ist ein Container, um verschiedene Elemente zu gruppieren.", t9_inst: "Verbinde die Paare:", t9_h1: "Container.", t9_h2: "Box.", t9_q: "Was ist ein <div>?", t9_qa: "Ein Container-Element", t9_qb: "Ein Bild", t9_qc: "Ein Link", t9_qd: "Eine Liste",
    t9_l1: "<div>", t9_r1: "Box", t9_l2: "Container", t9_r2: "Gruppe", t9_l3: "Layout", t9_r3: "Struktur",
    t10_title: "CSS", t10_text: "CSS ist die Sprache, die bestimmt, wie die Seite aussieht — Farben, Größen, Abstände.", t10_inst: "Verbinde die Paare:", t10_h1: "Design.", t10_h2: "Style.", t10_q: "Wofür nutzt man CSS?", t10_qa: "Für das Design", t10_qb: "Für den Text", t10_qc: "Für Berechnungen", t10_qd: "Für Datenbanken",
    t10_l1: "CSS", t10_r1: "Design", t10_l2: "Style", t10_r2: "Aussehen", t10_l3: "Farbe", t10_r3: "Bunt",
    t11_title: "Farbe", t11_text: "Mit CSS kannst du die Textfarbe (color) oder Hintergrundfarbe (background-color) ändern.", t11_inst: "Verbinde die Paare:", t11_h1: "Bunte Webseite.", t11_h2: "Farbnamen.", t11_q: "Wie ändert man die Textfarbe in CSS?", t11_qa: "color", t11_qb: "text-paint", t11_qc: "font-color", t11_qd: "ink",
    t11_l1: "color", t11_r1: "Textfarbe", t11_l2: "background", t11_r2: "Hintergrund", t11_l3: "blue", t11_r3: "Blau",
    t12_title: "Schrift", t12_text: "Du kannst die Schriftart (font-family) und die Größe (font-size) anpassen.", t12_inst: "Verbinde die Paare:", t12_h1: "Text-Stil.", t12_h2: "Größe.", t12_q: "Was ändert 'font-size'?", t12_qa: "Die Schriftgröße", t12_qb: "Die Farbe", t12_qc: "Den Text", t12_qd: "Das Bild",
    t12_l1: "font-size", t12_r1: "Größe", t12_l2: "font-family", t12_r2: "Schriftart", t12_l3: "bold", t12_r3: "Fett",
    t13_title: "Rahmen", t13_text: "Mit 'border' kannst du einen Rahmen um deine Elemente ziehen.", t13_inst: "Verbinde die Paare:", t13_h1: "Umrandung.", t13_h2: "Border.", t13_q: "Was bedeutet 'border'?", t13_qa: "Rahmen / Rand", t13_qb: "Mitte", t13_qc: "Unten", t13_qd: "Oben",
    t13_l1: "border", t13_r1: "Rahmen", t13_l2: "solid", t13_r2: "Durchgehend", t13_l3: "width", t13_r3: "Breite",
    t14_title: "Klasse", t14_text: "Eine Klasse (.name) gibt mehreren Elementen den gleichen Stil.", t14_inst: "Verbinde die Paare:", t14_h1: "Wiederverwendbar.", t14_h2: "Punkt davor.", t14_q: "Wie beginnt eine Klasse im CSS?", t14_qa: "Mit einem Punkt .", t14_qb: "Mit einem #", t14_qc: "Mit einem !", t14_qd: "Mit einem ?",
    t14_l1: "class", t14_r1: "Klasse", t14_l2: ".rot", t14_r2: "CSS-Selektor", t14_l3: "id", t14_r3: "Einzigartig",
    t15_title: "Webentwickler", t15_text: "Du kannst jetzt einfache Webseiten mit HTML und CSS bauen!", t15_inst: "Verbinde die Paare:", t15_h1: "Super gemacht.", t15_h2: "Web-Profi.", t15_q: "Was hast du gelernt?", t15_qa: "Webseiten bauen", t15_qb: "Auto fahren", t15_qc: "Kochen", t15_qd: "Fliegen",
    t15_l1: "Web", t15_r1: "Internet", t15_l2: "Entwickler", t15_r2: "Bauen", t15_l3: "Fertig", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "HTML & CSS Basics",
    t1_title: "HTML", t1_text: "HTML is the language of web pages — it tells the browser what to show.", t1_inst: "Match the pairs:", t1_h1: "Web language.", t1_h2: "Page structure.", t1_q: "What is HTML?", t1_qa: "Web page description language", t1_qb: "A game", t1_qc: "An image", t1_qd: "A number",
    t1_l1: "HTML", t1_r1: "Web page", t1_l2: "Browser", t1_r2: "Display", t1_l3: "Code", t1_r3: "Text",
    t2_title: "Tag", t2_text: "A tag is an HTML command, like <p> for a paragraph or <h1> for a heading.", t2_inst: "Match the pairs:", t2_h1: "HTML command.", t2_h2: "In angle brackets.", t2_q: "How do you write a tag?", t2_qa: "In angle brackets < >", t2_qb: "With numbers", t2_qc: "With colors", t2_qd: "Not at all",
    t2_l1: "Tag", t2_r1: "Command", t2_l2: "<h1>", t2_r2: "Heading", t2_l3: "<p>", t2_r3: "Paragraph",
    t3_title: "Attribute", t3_text: "Attributes give tags extra info, like 'href' for a link or 'src' for an image.", t3_inst: "Match the pairs:", t3_h1: "Extra info.", t3_h2: "Properties.", t3_q: "What does an attribute do?", t3_qa: "Gives extra info", t3_qb: "Deletes the tag", t3_qc: "Makes music", t3_qd: "Nothing",
    t3_l1: "Attribute", t3_r1: "Property", t3_l2: "href", t3_r2: "Link target", t3_l3: "src", t3_r3: "Image source",
    t4_title: "Heading", t4_text: "Use h1 to h6 to create headings of different sizes.", t4_inst: "Match the pairs:", t4_h1: "Important text.", t4_h2: "h1 is the largest.", t4_q: "Which tag is the largest heading?", t4_qa: "<h1>", t4_qb: "<h6>", t4_qc: "<p>", t4_qd: "<a>",
    t4_l1: "h1", t4_r1: "Largest", t4_l2: "h6", t4_r2: "Smallest", t4_l3: "Heading", t4_r3: "Title",
    t5_title: "Paragraph", t5_text: "The <p> tag is used for regular text and paragraphs.", t5_inst: "Match the pairs:", t5_h1: "Regular text.", t5_h2: "Paragraph.", t5_q: "What does 'p' stand for in <p>?", t5_qa: "Paragraph", t5_qb: "Picture", t5_qc: "Play", t5_qd: "Power",
    t5_l1: "<p>", t5_r1: "Paragraph", t5_l2: "Text", t5_r2: "Content", t5_l3: "End", t5_r3: "</p>",
    t6_title: "Link", t6_text: "Use <a href='...'> to make a clickable link to another page.", t6_inst: "Match the pairs:", t6_h1: "Connection.", t6_h2: "Clickable.", t6_q: "Which tag creates a link?", t6_qa: "<a>", t6_qb: "<img>", t6_qc: "<li>", t6_qd: "<div>",
    t6_l1: "<a>", t6_r1: "Anchor/Link", t6_l2: "href", t6_r2: "Address", t6_l3: "Click", t6_r3: "Target",
    t7_title: "Image", t7_text: "Use <img src='...'> to insert images into your web page.", t7_inst: "Match the pairs:", t7_h1: "Visual content.", t7_h2: "Image.", t7_q: "What does an <img> tag definitely need?", t7_qa: "src attribute", t7_qb: "A text", t7_qc: "A number", t7_qd: "Nothing",
    t7_l1: "<img>", t7_r1: "Image", t7_l2: "src", t7_r2: "Source", t7_l3: "alt", t7_r3: "Alt text",
    t8_title: "List", t8_text: "Use <ul> and <li> to create bulleted lists.", t8_inst: "Match the pairs:", t8_h1: "Enumeration.", t8_h2: "List items.", t8_q: "What does 'ul' mean?", t8_qa: "Unordered List", t8_qb: "Under Line", t8_qc: "Ultra Link", t8_qd: "User List",
    t8_l1: "<ul>", t8_r1: "List", t8_l2: "<li>", t8_r2: "List item", t8_l3: "<ol>", t8_r3: "Ordered",
    t9_title: "Div", t9_text: "A <div> is a container used to group different elements together.", t9_inst: "Match the pairs:", t9_h1: "Container.", t9_h2: "Box.", t9_q: "What is a <div>?", t9_qa: "A container element", t9_qb: "An image", t9_qc: "A link", t9_qd: "A list",
    t9_l1: "<div>", t9_r1: "Box", t9_l2: "Container", t9_r2: "Group", t9_l3: "Layout", t9_r3: "Structure",
    t10_title: "CSS", t10_text: "CSS is the language that sets how the page looks — colors, sizes, spacing.", t10_inst: "Match the pairs:", t10_h1: "Design.", t10_h2: "Style.", t10_q: "What is CSS used for?", t10_qa: "For design", t10_qb: "For text", t10_qc: "For math", t10_qd: "For databases",
    t10_l1: "CSS", t10_r1: "Design", t10_l2: "Style", t10_r2: "Appearance", t10_l3: "Color", t10_r3: "Colorful",
    t11_title: "Color", t11_text: "With CSS you can change the text color (color) or background color (background-color).", t11_inst: "Match the pairs:", t11_h1: "Colorful web page.", t11_h2: "Color names.", t11_q: "How do you change text color in CSS?", t11_qa: "color", t11_qb: "text-paint", t11_qc: "font-color", t11_qd: "ink",
    t11_l1: "color", t11_r1: "Text color", t11_l2: "background", t11_r2: "Background", t11_l3: "blue", t11_r3: "Blue",
    t12_title: "Font", t12_text: "You can adjust the font type (font-family) and size (font-size).", t12_inst: "Match the pairs:", t12_h1: "Text style.", t12_h2: "Size.", t12_q: "What does 'font-size' change?", t12_qa: "The font size", t12_qb: "The color", t12_qc: "The text", t12_qd: "The image",
    t12_l1: "font-size", t12_r1: "Size", t12_l2: "font-family", t12_r2: "Font family", t12_l3: "bold", t12_r3: "Bold",
    t13_title: "Border", t13_text: "Use 'border' to draw a frame around your elements.", t13_inst: "Match the pairs:", t13_h1: "Outline.", t13_h2: "Border.", t13_q: "What does 'border' mean?", t13_qa: "Frame / Edge", t13_qb: "Middle", t13_qc: "Bottom", t13_qd: "Top",
    t13_l1: "border", t13_r1: "Frame", t13_l2: "solid", t13_r2: "Solid", t13_l3: "width", t13_r3: "Width",
    t14_title: "Class", t14_text: "A class (.name) gives the same style to multiple elements.", t14_inst: "Match the pairs:", t14_h1: "Reusable.", t14_h2: "Dot before.", t14_q: "How does a class start in CSS?", t14_qa: "With a dot .", t14_qb: "With a #", t14_qc: "With a !", t14_qd: "With a ?",
    t14_l1: "class", t14_r1: "Class", t14_l2: ".red", t14_r2: "CSS selector", t14_l3: "id", t14_r3: "Unique",
    t15_title: "Web Developer", t15_text: "You can now build simple web pages with HTML and CSS!", t15_inst: "Match the pairs:", t15_h1: "Great job.", t15_h2: "Web pro.", t15_q: "What did you learn?", t15_qa: "Building web pages", t15_qb: "Driving a car", t15_qc: "Cooking", t15_qd: "Flying",
    t15_l1: "Web", t15_r1: "Internet", t15_l2: "Developer", t15_r2: "Build", t15_l3: "Done", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "HTML és CSS alapok",
    t1_title: "HTML", t1_text: "A HTML a weboldalak leíró nyelve — ezzel mondod meg, mit mutasson a böngésző.", t1_inst: "Párosítsd össze:", t1_h1: "Weboldal nyelve.", t1_h2: "Oldal szerkezete.", t1_q: "Mi az a HTML?", t1_qa: "Weboldal-leíró nyelv", t1_qb: "Egy játék", t1_qc: "Egy kép", t1_qd: "Egy szám",
    t1_l1: "HTML", t1_r1: "Weboldal", t1_l2: "Böngésző", t1_r2: "Megjelenítés", t1_l3: "Kód", t1_r3: "Szöveg",
    t2_title: "Tag", t2_text: "A tag egy HTML parancs, mint a <p> a bekezdéshez vagy a <h1> a címsorhoz.", t2_inst: "Párosítsd össze:", t2_h1: "HTML parancs.", t2_h2: "Kacsacsőrök között.", t2_q: "Hogyan írunk egy tag-et?", t2_qa: "Kacsacsőrök között < >", t2_qb: "Számokkal", t2_qc: "Színekkel", t2_qd: "Sehogy",
    t2_l1: "Tag", t2_r1: "Parancs", t2_l2: "<h1>", t2_r2: "Címsor", t2_l3: "<p>", t2_r3: "Bekezdés",
    t3_title: "Attribútum", t3_text: "Az attribútumok plusz infót adnak a tag-eknek, mint a 'href' a linknek vagy a 'src' a képnek.", t3_inst: "Párosítsd össze:", t3_h1: "Plusz infó.", t3_h2: "Tulajdonságok.", t3_q: "Mit csinál az attribútum?", t3_qa: "Plusz infót ad", t3_qb: "Törli a tag-et", t3_qc: "Zenél", t3_qd: "Semmit",
    t3_l1: "Attribútum", t3_r1: "Tulajdonság", t3_l2: "href", t3_r2: "Link célja", t3_l3: "src", t3_r3: "Kép forrása",
    t4_title: "Heading", t4_text: "A h1-től h6-ig terjedő tag-ekkel különböző méretű címsorokat készíthetsz.", t4_inst: "Párosítsd össze:", t4_h1: "Fontos szöveg.", t4_h2: "h1 a legnagyobb.", t4_q: "Melyik tag a legnagyobb címsor?", t4_qa: "<h1>", t4_qb: "<h6>", t4_qc: "<p>", t4_qd: "<a>",
    t4_l1: "h1", t4_r1: "Legnagyobb", t4_l2: "h6", t4_r2: "Legkisebb", t4_l3: "Heading", t4_r3: "Címsor",
    t5_title: "Paragraph", t5_text: "A <p> tag-et a sima szövegekhez és bekezdésekhez használjuk.", t5_inst: "Párosítsd össze:", t5_h1: "Sima szöveg.", t5_h2: "Bekezdés.", t5_q: "Mit jelent a 'p' a <p> tag-ben?", t5_qa: "Paragraph (bekezdés)", t5_qb: "Picture (kép)", t5_qc: "Play (játék)", t5_qd: "Power",
    t5_l1: "<p>", t5_r1: "Bekezdés", t5_l2: "Szöveg", t5_r2: "Tartalom", t5_l3: "Vége", t5_r3: "</p>",
    t6_title: "Link", t6_text: "Használd az <a href='...'> tag-et, hogy kattintható linket készíts egy másik oldalra.", t6_inst: "Párosítsd össze:", t6_h1: "Kapcsolat.", t6_h2: "Kattintható.", t6_q: "Melyik tag készít linket?", t6_qa: "<a>", t6_qb: "<img>", t6_qc: "<li>", t6_qd: "<div>",
    t6_l1: "<a>", t6_r1: "Link", t6_l2: "href", t6_r2: "Cím", t6_l3: "Kattintás", t6_r3: "Cél",
    t7_title: "Image", t7_text: "Az <img src='...'> tag-gel képeket szúrhatsz be a weboldaladra.", t7_inst: "Párosítsd össze:", t7_h1: "Vizuális tartalom.", t7_h2: "Kép.", t7_q: "Mire van szüksége mindenképp egy <img> tag-nek?", t7_qa: "src attribútum", t7_qb: "Egy szöveg", t7_qc: "Egy szám", t7_qd: "Semmi",
    t7_l1: "<img>", t7_r1: "Kép", t7_l2: "src", t7_r2: "Forrás", t7_l3: "alt", t7_r3: "Leírás",
    t8_title: "List", t8_text: "Az <ul> és <li> tag-ekkel felsorolásokat készíthetsz.", t8_inst: "Párosítsd össze:", t8_h1: "Felsorolás.", t8_h2: "Listaelemek.", t8_q: "Mit jelent az 'ul'?", t8_qa: "Unordered List (rendezetlen lista)", t8_qb: "Under Line", t8_qc: "Ultra Link", t8_qd: "User List",
    t8_l1: "<ul>", t8_r1: "Lista", t8_l2: "<li>", t8_r2: "Listaelem", t8_l3: "<ol>", t8_r3: "Számozott",
    t9_title: "Div", t9_text: "A <div> egy konténer, amivel különböző elemeket csoportosíthatsz.", t9_inst: "Párosítsd össze:", t9_h1: "Konténer.", t9_h2: "Doboz.", t9_q: "Mi az a <div>?", t9_qa: "Egy konténer elem", t9_qb: "Egy kép", t9_qc: "Egy link", t9_qd: "Egy lista",
    t9_l1: "<div>", t9_r1: "Doboz", t9_l2: "Konténer", t9_r2: "Csoport", t9_l3: "Layout", t9_r3: "Szerkezet",
    t10_title: "CSS", t10_text: "A CSS az a nyelv, ami meghatározza, hogyan nézzen ki az oldal — színek, méretek, közök.", t10_inst: "Párosítsd össze:", t10_h1: "Dizájn.", t10_h2: "Stílus.", t10_q: "Mire használjuk a CSS-t?", t10_qa: "A kinézethez", t10_qb: "A szöveghez", t10_qc: "Számoláshoz", t10_qd: "Adatbázishoz",
    t10_l1: "CSS", t10_r1: "Dizájn", t10_l2: "Stílus", t10_r2: "Kinézet", t10_l3: "Szín", t10_r3: "Színes",
    t11_title: "Color", t11_text: "CSS-sel megváltoztathatod a szöveg színét (color) vagy a háttérszínt (background-color).", t11_inst: "Párosítsd össze:", t11_h1: "Színes weboldal.", t11_h2: "Színnevek.", t11_q: "Hogyan változtatod meg a szöveg színét CSS-ben?", t11_qa: "color", t11_qb: "text-paint", t11_qc: "font-color", t11_qd: "ink",
    t11_l1: "color", t11_r1: "Szövegszín", t11_l2: "background", t11_r2: "Háttér", t11_l3: "blue", t11_r3: "Kék",
    t12_title: "Font", t12_text: "Beállíthatod a betűtípust (font-family) és a méretet (font-size) is.", t12_inst: "Párosítsd össze:", t12_h1: "Szövegstílus.", t12_h2: "Méret.", t12_q: "Mit változtat meg a 'font-size'?", t12_qa: "A betűméretet", t12_qb: "A színt", t12_qc: "A szöveget", t12_qd: "A képet",
    t12_l1: "font-size", t12_r1: "Méret", t12_l2: "font-family", t12_r2: "Betűtípus", t12_l3: "bold", t12_r3: "Félkövér",
    t13_title: "Border", t13_text: "A 'border' segítségével szegélyt húzhatsz az elemeid köré.", t13_inst: "Párosítsd össze:", t13_h1: "Körvonal.", t13_h2: "Szegély.", t13_q: "Mit jelent a 'border'?", t13_qa: "Keret / Szegély", t13_qb: "Közép", t13_qc: "Alja", t13_qd: "Teteje",
    t13_l1: "border", t13_r1: "Szegély", t13_l2: "solid", t13_r2: "Folytonos", t13_l3: "width", t13_r3: "Szélesség",
    t14_title: "Class", t14_text: "Egy osztály (.nev) több elemnek is adhat ugyanolyan stílust.", t14_inst: "Párosítsd össze:", t14_h1: "Újrafelhasználható.", t14_h2: "Pont az elején.", t14_q: "Mivel kezdődik egy osztály a CSS-ben?", t14_qa: "Egy ponttal .", t14_qb: "Egy #-tel", t14_qc: "Egy !-lel", t14_qd: "Egy ?-tel",
    t14_l1: "class", t14_r1: "Osztály", t14_l2: ".piros", t14_r2: "CSS szelektor", t14_l3: "id", t14_r3: "Egyedi",
    t15_title: "Webfejlesztő", t15_text: "Most már tudsz egyszerű weboldalakat készíteni HTML és CSS segítségével!", t15_inst: "Párosítsd össze:", t15_h1: "Szép munka.", t15_h2: "Web profi.", t15_q: "Mit tanultál meg?", t15_qa: "Weboldalt építeni", t15_qb: "Autót vezetni", t15_qc: "Főzni", t15_qd: "Repülni",
    t15_l1: "Web", t15_r1: "Internet", t15_l2: "Fejlesztő", t15_r2: "Építés", t15_l3: "Kész", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Bazele HTML și CSS",
    t1_title: "HTML", t1_text: "HTML este limbajul paginilor web — prin el îi spui browserului ce să afișeze.", t1_inst: "Potrivește perechile:", t1_h1: "Limbaj web.", t1_h2: "Structura paginii.", t1_q: "Ce este HTML?", t1_qa: "Limbaj de descriere a paginilor web", t1_qb: "Un joc", t1_qc: "O imagine", t1_qd: "Un număr",
    t1_l1: "HTML", t1_r1: "Pagină web", t1_l2: "Browser", t1_r2: "Afișare", t1_l3: "Cod", t1_r3: "Text",
    t2_title: "Tag", t2_text: "Un tag este o comandă HTML, cum ar fi <p> pentru un paragraf sau <h1> pentru un titlu.", t2_inst: "Potrivește perechile:", t2_h1: "Comandă HTML.", t2_h2: "Între paranteze unghiulare.", t2_q: "Cum se scrie un tag?", t2_qa: "Între paranteze unghiulare < >", t2_qb: "Cu numere", t2_qc: "Cu culori", t2_qd: "Deloc",
    t2_l1: "Tag", t2_r1: "Comandă", t2_l2: "<h1>", t2_r2: "Titlu", t2_l3: "<p>", t2_r3: "Paragraf",
    t3_title: "Atribut", t3_text: "Atributele oferă tag-urilor informații suplimentare, cum ar fi 'href' pentru un link sau 'src' pentru o imagine.", t3_inst: "Potrivește perechile:", t3_h1: "Info extra.", t3_h2: "Proprietăți.", t3_q: "Ce face un atribut?", t3_qa: "Oferă info extra", t3_qb: "Șterge tag-ul", t3_qc: "Face muzică", t3_qd: "Nimic",
    t3_l1: "Atribut", t3_r1: "Proprietate", t3_l2: "href", t3_r2: "Țintă link", t3_l3: "src", t3_r3: "Sursă imagine",
    t4_title: "Heading", t4_text: "Folosește h1 până la h6 pentru a crea titluri de diferite dimensiuni.", t4_inst: "Potrivește perechile:", t4_h1: "Text important.", t4_h2: "h1 este cel mai mare.", t4_q: "Care tag este cel mai mare titlu?", t4_qa: "<h1>", t4_qb: "<h6>", t4_qc: "<p>", t4_qd: "<a>",
    t4_l1: "h1", t4_r1: "Cel mai mare", t4_l2: "h6", t4_r2: "Cel mai mic", t4_l3: "Heading", t4_r3: "Titlu",
    t5_title: "Paragraf", t5_text: "Tag-ul <p> este folosit pentru text normal și paragrafe.", t5_inst: "Potrivește perechile:", t5_h1: "Text normal.", t5_h2: "Paragraf.", t5_q: "De la ce vine 'p' în <p>?", t5_qa: "Paragraph (paragraf)", t5_qb: "Picture (imagine)", t5_qc: "Play (joc)", t5_qd: "Power",
    t5_l1: "<p>", t5_r1: "Paragraf", t5_l2: "Text", t5_r2: "Conținut", t5_l3: "Sfârșit", t5_r3: "</p>",
    t6_title: "Link", t6_text: "Folosește <a href='...'> pentru a crea un link pe care se poate da clic către o altă pagină.", t6_inst: "Potrivește perechile:", t6_h1: "Conexiune.", t6_h2: "Clicabil.", t6_q: "Care tag creează un link?", t6_qa: "<a>", t6_qb: "<img>", t6_qc: "<li>", t6_qd: "<div>",
    t6_l1: "<a>", t6_r1: "Link", t6_l2: "href", t6_r2: "Adresă", t6_l3: "Clic", t6_r3: "Țintă",
    t7_title: "Imagine", t7_text: "Cu <img src='...'> inserezi imagini în pagina ta web.", t7_inst: "Potrivește perechile:", t7_h1: "Conținut vizual.", t7_h2: "Imagine.", t7_q: "De ce are nevoie neapărat un tag <img>?", t7_qa: "Atributul src", t7_qb: "Un text", t7_qc: "Un număr", t7_qd: "Nimic",
    t7_l1: "<img>", t7_r1: "Imagine", t7_l2: "src", t7_r2: "Sursă", t7_l3: "alt", t7_r3: "Text alternativ",
    t8_title: "Listă", t8_text: "Cu <ul> și <li> poți crea liste cu puncte.", t8_inst: "Potrivește perechile:", t8_h1: "Enumerare.", t8_h2: "Elemente listă.", t8_q: "Ce înseamnă 'ul'?", t8_qa: "Unordered List (listă neordonată)", t8_qb: "Under Line", t8_qc: "Ultra Link", t8_qd: "User List",
    t8_l1: "<ul>", t8_r1: "Listă", t8_l2: "<li>", t8_r2: "Element listă", t8_l3: "<ol>", t8_r3: "Numerotată",
    t9_title: "Div", t9_text: "Un <div> este un container pentru a grupa diferite elemente.", t9_inst: "Potrivește perechile:", t9_h1: "Container.", t9_h2: "Casetă.", t9_q: "Ce este un <div>?", t9_qa: "Un element container", t9_qb: "O imagine", t9_qc: "Un link", t9_qd: "O listă",
    t9_l1: "<div>", t9_r1: "Casetă", t9_l2: "Container", t9_r2: "Grup", t9_l3: "Layout", t9_r3: "Structură",
    t10_title: "CSS", t10_text: "CSS este limbajul care stabilește cum arată pagina — culori, dimensiuni, spații.", t10_inst: "Potrivește perechile:", t10_h1: "Design.", t10_h2: "Stil.", t10_q: "Pentru ce se folosește CSS?", t10_qa: "Pentru design", t10_qb: "Pentru text", t10_qc: "Pentru calcule", t10_qd: "Pentru baze de date",
    t10_l1: "CSS", t10_r1: "Design", t10_l2: "Stil", t10_r2: "Aspect", t10_l3: "Culoare", t10_r3: "Colorat",
    t11_title: "Culoare", t11_text: "Cu CSS poți schimba culoarea textului (color) sau culoarea de fundal (background-color).", t11_inst: "Potrivește perechile:", t11_h1: "Pagină colorată.", t11_h2: "Nume culori.", t11_q: "Cum schimbi culoarea textului în CSS?", t11_qa: "color", t11_qb: "text-paint", t11_qc: "font-color", t11_qd: "ink",
    t11_l1: "color", t11_r1: "Culoare text", t11_l2: "background", t11_r2: "Fundal", t11_l3: "blue", t11_r3: "Albastru",
    t12_title: "Font", t12_text: "Poți ajusta tipul fontului (font-family) și dimensiunea (font-size).", t12_inst: "Potrivește perechile:", t12_h1: "Stil text.", t12_h2: "Dimensiune.", t12_q: "Ce schimbă 'font-size'?", t12_qa: "Dimensiunea fontului", t12_qb: "Culoarea", t12_qc: "Textul", t12_qd: "Imaginea",
    t12_l1: "font-size", t12_r1: "Dimensiune", t12_l2: "font-family", t12_r2: "Tip font", t12_l3: "bold", t12_r3: "Aldin",
    t13_title: "Border", t13_text: "Cu 'border' poți trasa un chenar în jurul elementelor tale.", t13_inst: "Potrivește perechile:", t13_h1: "Contur.", t13_h2: "Chenar.", t13_q: "Ce înseamnă 'border'?", t13_qa: "Chenar / Margine", t13_qb: "Mijloc", t13_qc: "Jos", t13_qd: "Sus",
    t13_l1: "border", t13_r1: "Chenar", t13_l2: "solid", t13_r2: "Continuu", t13_l3: "width", t13_r3: "Lățime",
    t14_title: "Clasă", t14_text: "O clasă (.nume) oferă același stil mai multor elemente.", t14_inst: "Potrivește perechile:", t14_h1: "Reutilizabil.", t14_h2: "Punct înainte.", t14_q: "Cum începe o clasă în CSS?", t14_qa: "Cu un punct .", t14_qb: "Cu un #", t14_qc: "Cu un !", t14_qd: "Cu un ?",
    t14_l1: "class", t14_r1: "Clasă", t14_l2: ".rosu", t14_r2: "Selector CSS", t14_l3: "id", t14_r3: "Unic",
    t15_title: "Dezvoltator Web", t15_text: "Acum poți construi pagini web simple cu HTML și CSS!", t15_inst: "Potrivește perechile:", t15_h1: "Bravo.", t15_h2: "Web pro.", t15_q: "Ce ai învățat?", t15_qa: "Să construiești pagini web", t15_qb: "Să conduci mașina", t15_qc: "Să gătești", t15_qd: "Să zbori",
    t15_l1: "Web", t15_r1: "Internet", t15_l2: "Dezvoltator", t15_r2: "Construcție", t15_l3: "Gata", t15_r3: "Victorie"
  }
};

export const INFO_K4_I4_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["🌐","🏷️","⚙️","📰","📄","🔗","🖼️","📋","📦","🎨","🌈","🔤","🟦","🏷️","💻"];
  const colors = ["#FF5722","#2196F3","#9C27B0","#FFC107","#8BC34A","#00BCD4","#E91E63","#607D8B","#795548","#F06292","#F44336","#3F51B5","#673AB7","#FF9800","#FFD700"];
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { type: "match-pairs", instruction: `t${t}_inst`, hint1: `t${t}_h1`, hint2: `t${t}_h2`,
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});
