// @ts-nocheck
// lib/explorerPools/informatikaK1_i7.ts
import type { PoolTopicDef } from "./types";

export const INFO_K1_I7_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Smarte Geräte",
    t1_title: "Das Smartphone", t1_text: "Ein Smartphone ist ein kleiner Computer für die Hosentasche.", t1_inst: "Verbinde die Paare:", t1_h1: "Telefon und mehr.", t1_h2: "Überall dabei.", t1_q: "Was ist ein Smartphone?", t1_qa: "Ein kleiner Computer", t1_qb: "Ein großer Stein", t1_qc: "Ein Stück Brot", t1_qd: "Ein Baum",
    t1_l1: "Smart", t1_r1: "Schlau", t1_l2: "Phone", t1_r2: "Telefon", t1_l3: "Tasche", t1_r3: "Tragen",
    t2_title: "Das Tablet", t2_text: "Ein Tablet ist flach und hat einen großen Touchscreen zum Spielen.", t2_inst: "Verbinde die Paare:", t2_h1: "Großer Bildschirm.", t2_h2: "Mit Fingern tippen.", t2_q: "Wie bedient man ein Tablet?", t2_qa: "Mit dem Finger", t2_qb: "Mit dem Fuß", t2_qc: "Mit der Nase", t2_qd: "Gar nicht",
    t2_l1: "Tablet", t2_r1: "Flach", t2_l2: "Touch", t2_r2: "Berühren", t2_l3: "Spiel", t2_r3: "Spaß",
    t3_title: "Die Smartwatch", t3_text: "Eine schlaue Uhr am Handgelenk kann Schritte zählen und Nachrichten zeigen.", t3_inst: "Verbinde die Paare:", t3_h1: "Uhr am Arm.", t3_h2: "Zählt Schritte.", t3_q: "Wo trägt man eine Smartwatch?", t3_qa: "Am Handgelenk", t3_qb: "Am Knie", t3_qc: "Auf dem Kopf", t3_qd: "Im Schuh",
    t3_l1: "Watch", t3_r1: "Uhr", t3_l2: "Arm", t3_r2: "Tragen", t3_l3: "Schritt", t3_r3: "Zählen",
    t4_title: "Fernbedienung", t4_text: "Mit der Fernbedienung steuerst du Geräte aus der Ferne.", t4_inst: "Verbinde die Paare:", t4_h1: "Drücken und umschalten.", t4_h2: "Nicht aufstehen.", t4_q: "Was macht eine Fernbedienung?", t4_qa: "Geräte steuern", t4_qb: "Essen kochen", t4_qc: "Haare waschen", t4_qd: "Schlafen",
    t4_l1: "Fern", t4_r1: "Weit weg", t4_l2: "Knopf", t4_r2: "Drücken", t4_l3: "TV", t4_r3: "Umschalten",
    t5_title: "Spielzeug-Robot", t5_text: "Kleine Roboter können fahren, blinken und manchmal sogar sprechen.", t5_inst: "Verbinde die Paare:", t5_h1: "Maschine zum Spielen.", t5_h2: "Blinkt und fährt.", t5_q: "Was ist ein Roboter?", t5_qa: "Eine schlaue Maschine", t5_qb: "Ein echtes Tier", t5_qc: "Eine Pflanze", t5_qd: "Ein Berg",
    t5_l1: "Robot", t5_r1: "Maschine", t5_l2: "Batterie", t5_r2: "Strom", t5_l3: "Spielzeug", t5_r3: "Fahren",
    t6_title: "Sprachassistent", t6_text: "Alexa oder Siri hören dir zu und beantworten deine Fragen.", t6_inst: "Verbinde die Paare:", t6_h1: "Sprechen mit der Maschine.", t6_h2: "Hört zu.", t6_q: "Wie redet man mit Alexa?", t6_qa: "Mit der Stimme", t6_qb: "Mit den Füßen", t6_qc: "Mit den Augen", t6_qd: "Gar nicht",
    t6_l1: "Stimme", t6_r1: "Sprechen", t6_l2: "Frage", t6_r2: "Antwort", t6_l3: "Name", t6_r3: "Rufen",
    t7_title: "Smart TV", t7_text: "Ein moderner Fernseher kann auch Filme aus dem Internet zeigen.", t7_inst: "Verbinde die Paare:", t7_h1: "Großes Kino.", t7_h2: "Internet im Wohnzimmer.", t7_q: "Was kann ein Smart TV?", t7_qa: "Internet-Filme zeigen", t7_qb: "Wäsche waschen", t7_qc: "Brot backen", t7_qd: "Fliegen",
    t7_l1: "TV", t7_r1: "Fernseher", t7_l2: "Film", t7_r2: "Schauen", t7_l3: "Netz", t7_r3: "Internet",
    t8_title: "Smarte Lautsprecher", t8_text: "Diese Boxen spielen Musik, wenn du es ihnen sagst.", t8_inst: "Verbinde die Paare:", t8_h1: "Musik auf Zuruf.", t8_h2: "Hört aufs Wort.", t8_q: "Was macht ein smarter Lautsprecher?", t8_qa: "Musik spielen", t8_qb: "Licht ausschalten", t8_qc: "Kaffee kochen", t8_qd: "Tanzen",
    t8_l1: "Box", t8_r1: "Lautsprecher", t8_l2: "Musik", t8_r2: "Hören", t8_l3: "Wort", t8_r3: "Befehl",
    t9_title: "Elektroauto", t9_text: "Elektroautos fahren mit Strom statt mit Benzin und sind sehr leise.", t9_inst: "Verbinde die Paare:", t9_h1: "Fahren mit Strom.", t9_h2: "Ganz leise.", t9_q: "Was braucht ein Elektroauto?", t9_qa: "Strom", t9_qb: "Saft", t9_qc: "Suppe", t9_qd: "Holz",
    t9_l1: "Auto", t9_r1: "Fahren", t9_l2: "Strom", t9_r2: "Batterie", t9_l3: "Leise", t9_r3: "Motor",
    t10_title: "Smartes Heim", t10_text: "Im smarten Haus geht das Licht von alleine an oder die Heizung wird warm.", t10_inst: "Verbinde die Paare:", t10_h1: "Schlaues Haus.", t10_h2: "Alles automatisch.", t10_q: "Was ist ein smartes Heim?", t10_qa: "Ein Haus mit Technik", t10_qb: "Ein Haus aus Pappe", t10_qc: "Ein Zelt", t10_qd: "Ein Baumhaus",
    t10_l1: "Haus", t10_r1: "Wohnen", t10_l2: "Licht", t10_r2: "An", t10_l3: "App", t10_r3: "Steuern",
    t11_title: "Google Assistent", t11_text: "Google hilft dir, Dinge im Internet schnell zu finden.", t11_inst: "Verbinde die Paare:", t11_h1: "Suchen und finden.", t11_h2: "Schlaue Hilfe.", t11_q: "Was macht ein Assistent?", t11_qa: "Helfen", t11_qb: "Stören", t11_qc: "Weglaufen", t11_qd: "Schlafen",
    t11_l1: "Google", t11_r1: "Suche", t11_l2: "Hilfe", t11_r2: "Assistent", t11_l3: "Wissen", t11_r3: "Finden",
    t12_title: "Frag die Maschine", t12_text: "Du kannst Computer fragen, wie das Wetter wird oder wie spät es ist.", t12_inst: "Verbinde die Paare:", t12_h1: "Wissen wollen.", t12_h2: "Antwort bekommen.", t12_q: "Was kann man den Computer fragen?", t12_qa: "Nach dem Wetter", t12_qb: "Nach dem Geschmack von Luft", t12_qc: "Nichts", t12_qd: "Ob er schläft",
    t12_l1: "Frage", t12_r1: "Wetter", t12_l2: "Zeit", t12_r2: "Uhr", t12_l3: "Wissen", t12_r3: "Computer",
    t13_title: "Sprachsteuerung", t13_text: "Manche Geräte verstehen, was du sagst, ohne dass du drücken musst.", t13_inst: "Verbinde die Paare:", t13_h1: "Nur sprechen.", t13_h2: "Keine Knöpfe.", t13_q: "Was bedeutet Sprachsteuerung?", t13_qa: "Mit Worten steuern", t13_qb: "Mit den Händen fuchteln", t13_qc: "Laut schreien", t13_qd: "Singen",
    t13_l1: "Mund", t13_r1: "Sprechen", t13_l2: "Ohr", t13_r2: "Hören", t13_l3: "Befehl", t13_r3: "Steuern",
    t14_title: "Strom macht's möglich", t14_text: "Alle smarten Geräte brauchen Strom aus der Steckdose oder Batterie.", t14_inst: "Verbinde die Paare:", t14_h1: "Energie tanken.", t14_h2: "Ohne Saft geht nichts.", t14_q: "Was brauchen smarte Geräte?", t14_qa: "Strom", t14_qb: "Wasser", t14_qc: "Sand", t14_qd: "Luft",
    t14_l1: "Akku", t14_r1: "Laden", t14_l2: "Kabel", t14_r2: "Stecker", t14_l3: "Blitz", t14_r3: "Energie",
    t15_title: "Smart-Meister", t15_text: "Du kennst dich jetzt super mit modernen Geräten aus!", t15_inst: "Verbinde die Paare:", t15_h1: "Alles verstanden.", t15_h2: "Du bist schlau.", t15_q: "Was bist du jetzt?", t15_qa: "Ein Technik-Profi", t15_qb: "Ein Toaster", t15_qc: "Ein Fahrrad", t15_qd: "Ein Stein",
    t15_l1: "Meister", t15_r1: "Wissen", t15_l2: "Gerät", t15_r2: "Smart", t15_l3: "Sieg", t15_r3: "Pokal"
  },
  en: {
    explorer_title: "Smart Devices",
    t1_title: "The Smartphone", t1_text: "A smartphone is a small computer for your pocket.", t1_inst: "Match the pairs:", t1_h1: "Phone and more.", t1_h2: "Always with you.", t1_q: "What is a smartphone?", t1_qa: "A small computer", t1_qb: "A big stone", t1_qc: "A piece of bread", t1_qd: "A tree",
    t1_l1: "Smart", t1_r1: "Clever", t1_l2: "Phone", t1_r2: "Telephone", t1_l3: "Pocket", t1_r3: "Carry",
    t2_title: "The Tablet", t2_text: "A tablet is flat and has a large touchscreen for playing.", t2_inst: "Match the pairs:", t2_h1: "Large screen.", t2_h2: "Tap with fingers.", t2_q: "How do you use a tablet?", t2_qa: "With your finger", t2_qb: "With your foot", t2_qc: "With your nose", t2_qd: "Not at all",
    t2_l1: "Tablet", t2_r1: "Flat", t2_l2: "Touch", t2_r2: "Touch", t2_l3: "Game", t2_r3: "Fun",
    t3_title: "The Smartwatch", t3_text: "A smart watch on your wrist can count steps and show messages.", t3_inst: "Match the pairs:", t3_h1: "Watch on arm.", t3_h2: "Counts steps.", t3_q: "Where do you wear a smartwatch?", t3_qa: "On the wrist", t3_qb: "On the knee", t3_qc: "On the head", t3_qd: "In the shoe",
    t3_l1: "Watch", t3_r1: "Clock", t3_l2: "Arm", t3_r2: "Wear", t3_l3: "Step", t3_r3: "Count",
    t4_title: "Remote Control", t4_text: "With the remote control, you control devices from a distance.", t4_inst: "Match the pairs:", t4_h1: "Press and switch.", t4_h2: "Don't get up.", t4_q: "What does a remote control do?", t4_qa: "Control devices", t4_qb: "Cook food", t4_qc: "Wash hair", t4_qd: "Sleep",
    t4_l1: "Remote", t4_r1: "Far away", t4_l2: "Button", t4_r2: "Press", t4_l3: "TV", t4_r3: "Switch",
    t5_title: "Toy Robot", t5_text: "Small robots can drive, blink, and sometimes even speak.", t5_inst: "Match the pairs:", t5_h1: "Machine for playing.", t5_h2: "Blinks and drives.", t5_q: "What is a robot?", t5_qa: "A smart machine", t5_qb: "A real animal", t5_qc: "A plant", t5_qd: "A mountain",
    t5_l1: "Robot", t5_r1: "Machine", t5_l2: "Battery", t5_r2: "Power", t5_l3: "Toy", t5_r3: "Drive",
    t6_title: "Voice Assistant", t6_text: "Alexa or Siri listen to you and answer your questions.", t6_inst: "Match the pairs:", t6_h1: "Talking to the machine.", t6_h2: "Listens.", t6_q: "How do you talk to Alexa?", t6_qa: "With your voice", t6_qb: "With your feet", t6_qc: "With your eyes", t6_qd: "Not at all",
    t6_l1: "Voice", t6_r1: "Speak", t6_l2: "Question", t6_r2: "Answer", t6_l3: "Name", t6_r3: "Call",
    t7_title: "Smart TV", t7_text: "A modern TV can also show movies from the internet.", t7_inst: "Match the pairs:", t7_h1: "Big cinema.", t7_h2: "Internet in the living room.", t7_q: "What can a smart TV do?", t7_qa: "Show internet movies", t7_qb: "Wash clothes", t7_qc: "Bake bread", t7_qd: "Fly",
    t7_l1: "TV", t7_r1: "Television", t7_l2: "Movie", t7_r2: "Watch", t7_l3: "Web", t7_r3: "Internet",
    t8_title: "Smart Speakers", t8_text: "These boxes play music when you tell them to.", t8_inst: "Match the pairs:", t8_h1: "Music on demand.", t8_h2: "Listens to words.", t8_q: "What does a smart speaker do?", t8_qa: "Play music", t8_qb: "Turn off light", t8_qc: "Make coffee", t8_qd: "Dance",
    t8_l1: "Box", t8_r1: "Speaker", t8_l2: "Music", t8_r2: "Listen", t8_l3: "Word", t8_r3: "Command",
    t9_title: "Electric Car", t9_text: "Electric cars run on electricity instead of gas and are very quiet.", t9_inst: "Match the pairs:", t9_h1: "Driving with power.", t9_h2: "Very quiet.", t9_q: "What does an electric car need?", t9_qa: "Electricity", t9_qb: "Juice", t9_qc: "Soup", t9_qd: "Wood",
    t9_l1: "Car", t9_r1: "Drive", t9_l2: "Power", t9_r2: "Battery", t9_l3: "Quiet", t9_r3: "Motor",
    t10_title: "Smart Home", t10_text: "In a smart home, the light turns on by itself or the heating gets warm.", t10_inst: "Match the pairs:", t10_h1: "Clever house.", t10_h2: "All automatic.", t10_q: "What is a smart home?", t10_qa: "A house with tech", t10_qb: "A cardboard house", t10_qc: "A tent", t10_qd: "A treehouse",
    t10_l1: "House", t10_r1: "Living", t10_l2: "Light", t10_r2: "On", t10_l3: "App", t10_r3: "Control",
    t11_title: "Google Assistant", t11_text: "Google helps you find things on the internet quickly.", t11_inst: "Match the pairs:", t11_h1: "Search and find.", t11_h2: "Smart help.", t11_q: "What does an assistant do?", t11_qa: "Help", t11_qb: "Disturb", t11_qc: "Run away", t11_qd: "Sleep",
    t11_l1: "Google", t11_r1: "Search", t11_l2: "Help", t11_r2: "Assistant", t11_l3: "Knowledge", t11_r3: "Find",
    t12_title: "Ask the Machine", t12_text: "You can ask computers what the weather will be like or what time it is.", t12_inst: "Match the pairs:", t12_h1: "Want to know.", t12_h2: "Get answer.", t12_q: "What can you ask the computer?", t12_qa: "About weather", t12_qb: "About taste of air", t12_qc: "Nothing", t12_qd: "If it sleeps",
    t12_l1: "Question", t12_r1: "Weather", t12_l2: "Time", t12_r2: "Clock", t12_l3: "Knowledge", t12_r3: "Computer",
    t13_title: "Voice Control", t13_text: "Some devices understand what you say without you having to press anything.", t13_inst: "Match the pairs:", t13_h1: "Just speak.", t13_h2: "No buttons.", t13_q: "What does voice control mean?", t13_qa: "Control with words", t13_qb: "Wave hands", t13_qc: "Scream loud", t13_qd: "Sing",
    t13_l1: "Mouth", t13_r1: "Speak", t13_l2: "Ear", t13_r2: "Listen", t13_l3: "Command", t13_r3: "Control",
    t14_title: "Powered by Electricity", t14_text: "All smart devices need power from a socket or battery.", t14_inst: "Match the pairs:", t14_h1: "Get energy.", t14_h2: "Nothing works without power.", t14_q: "What do smart devices need?", t14_qa: "Electricity", t14_qb: "Water", t14_qc: "Sand", t14_qd: "Air",
    t14_l1: "Battery", t14_r1: "Charge", t14_l2: "Cable", t14_r2: "Plug", t14_l3: "Bolt", t14_r3: "Energy",
    t15_title: "Smart Master", t15_text: "You now know a lot about modern devices!", t15_inst: "Match the pairs:", t15_h1: "Understood everything.", t15_h2: "You are smart.", t15_q: "What are you now?", t15_qa: "A tech pro", t15_qb: "A toaster", t15_qc: "A bicycle", t15_qd: "A stone",
    t15_l1: "Master", t15_r1: "Knowledge", t15_l2: "Device", t15_r2: "Smart", t15_l3: "Victory", t15_r3: "Trophy"
  },
  hu: {
    explorer_title: "Okos eszközök",
    t1_title: "Mi az okostelefon?", t1_text: "Az okostelefon egy apró számítógép, ami elfér a zsebedben.", t1_inst: "Párosítsd össze:", t1_h1: "Telefon és több.", t1_h2: "Mindig nálad van.", t1_q: "Mi az az okostelefon?", t1_qa: "Egy kis számítógép", t1_qb: "Egy nagy kő", t1_qc: "Egy darab kenyér", t1_qd: "Egy fa",
    t1_l1: "Okos", t1_r1: "Ügyes", t1_l2: "Telefon", t1_r2: "Hívás", t1_l3: "Zseb", t1_r3: "Hordozás",
    t2_title: "Mi a tablet?", t2_text: "A tablet lapos, és nagy érintőképernyője van a játékhoz.", t2_inst: "Párosítsd össze:", t2_h1: "Nagy kijelző.", t2_h2: "Ujjal nyomjuk.", t2_q: "Hogyan használjuk a tabletet?", t2_qa: "Az ujjunkkal", t2_qb: "A lábunkkal", t2_qc: "Az orrunkkal", t2_qd: "Sehogy",
    t2_l1: "Tablet", t2_r1: "Lapos", t2_l2: "Érintés", t2_r2: "Touch", t2_l3: "Játék", t2_r3: "Móka",
    t3_title: "Okosóra", t3_text: "A csuklódon lévő okosóra méri a lépteidet és mutatja az üzeneteket.", t3_inst: "Párosítsd össze:", t3_h1: "Óra a karon.", t3_h2: "Lépést számlál.", t3_q: "Hol hordjuk az okosórát?", t3_qa: "A csuklónkon", t3_qb: "A térdünkön", t3_qc: "A fejünkön", t3_qd: "A cipőben",
    t3_l1: "Óra", t3_r1: "Idő", t3_l2: "Kar", t3_r2: "Viselet", t3_l3: "Lépés", t3_r3: "Számolás",
    t4_title: "Távirányító", t4_text: "A távirányítóval messziről is tudod irányítani a gépeket.", t4_inst: "Párosítsd össze:", t4_h1: "Nyomás és váltás.", t4_h2: "Ne állj fel.", t4_q: "Mit csinál a távirányító?", t4_qa: "Gépet irányít", t4_qb: "Ebédet főz", t4_qc: "Hajat mos", t4_qd: "Alszik",
    t4_l1: "Táv", t4_r1: "Messze", t4_l2: "Gomb", t4_r2: "Nyomás", t4_l3: "TV", t4_r3: "Kapcsolás",
    t5_title: "Robot (játék)", t5_text: "A kis robotok tudnak gurulni, villogni és néha beszélni is.", t5_inst: "Párosítsd össze:", t5_h1: "Gép a játékhoz.", t5_h2: "Villog és megy.", t5_q: "Mi az a robot?", t5_qa: "Egy okos gép", t5_qb: "Egy igazi állat", t5_qc: "Egy növény", t5_qd: "Egy hegy",
    t5_l1: "Robot", t5_r1: "Gép", t5_l2: "Elem", t5_r2: "Áram", t5_l3: "Játék", t5_r3: "Gurulás",
    t6_title: "Alexa / Siri", t6_text: "Ők a hangasszisztensek, akik figyelnek rád és válaszolnak.", t6_inst: "Párosítsd össze:", t6_h1: "Beszéd a géphez.", t6_h2: "Figyel rád.", t6_q: "Hogyan beszélünk Alexával?", t6_qa: "A hangunkkal", t6_qb: "A lábunkkal", t6_qc: "A szemünkkel", t6_qd: "Sehogy",
    t6_l1: "Hang", t6_r1: "Beszéd", t6_l2: "Kérdés", t6_r2: "Válasz", t6_l3: "Név", t6_r3: "Hívás",
    t7_title: "Okos TV", t7_text: "A modern tévével már az internetről is nézhetsz filmeket.", t7_inst: "Párosítsd össze:", t7_h1: "Nagy mozi.", t7_h2: "Internet a szobában.", t7_q: "Mit tud az okos TV?", t7_qa: "Internetes filmek", t7_qb: "Ruhát mos", t7_qc: "Kenyeret süt", t7_qd: "Repül",
    t7_l1: "TV", t7_r1: "Tévé", t7_l2: "Film", t7_r2: "Nézés", t7_l3: "Háló", t7_r3: "Internet",
    t8_title: "Okoshangszóró", t8_text: "Ezek a dobozok zenét játszanak, ha megkéred őket.", t8_inst: "Párosítsd össze:", t8_h1: "Zene kérésre.", t8_h2: "Szóra fogad.", t8_q: "Mit csinál az okoshangszóró?", t8_qa: "Zenét játszik", t8_qb: "Lámpát olt", t8_qc: "Kávét főz", t8_qd: "Táncol",
    t8_l1: "Doboz", t8_r1: "Hangszóró", t8_l2: "Zene", t8_r2: "Hallgatás", t8_l3: "Szó", t8_r3: "Parancs",
    t9_title: "Elektromos autó", t9_text: "Az elektromos autók árammal mennek benzin helyett, és nagyon halkak.", t9_inst: "Párosítsd össze:", t9_h1: "Árammal megy.", t9_h2: "Nagyon halk.", t9_q: "Mi kell az elektromos autónak?", t9_qa: "Áram", t9_qb: "Szörp", t9_qc: "Leves", t9_qd: "Fa",
    t9_l1: "Autó", t9_r1: "Vezetés", t9_l2: "Áram", t9_r2: "Akku", t9_l3: "Halk", t9_r3: "Motor",
    t10_title: "Okos háztartás", t10_text: "Az okos házban magától felgyullad a lámpa vagy meleg lesz a fűtés.", t10_inst: "Párosítsd össze:", t10_h1: "Ügyes ház.", t10_h2: "Minden automata.", t10_q: "Mi az az okos otthon?", t10_qa: "Gépiesített ház", t10_qb: "Papírház", t10_qc: "Sátor", t10_qd: "Faház",
    t10_l1: "Ház", t10_r1: "Lakás", t10_l2: "Lámpa", t10_r2: "Fény", t10_l3: "App", t10_r3: "Irányítás",
    t11_title: "Google asszisztens", t11_text: "A Google segít neked gyorsan megtalálni dolgokat az interneten.", t11_inst: "Párosítsd össze:", t11_h1: "Keresés és lelet.", t11_h2: "Okos segítség.", t11_q: "Mit csinál egy asszisztens?", t11_qa: "Segít", t11_qb: "Zavar", t11_qc: "Elszalad", t11_qd: "Alszik",
    t11_l1: "Google", t11_r1: "Keresés", t11_l2: "Segítő", t11_r2: "Asszisztens", t11_l3: "Tudás", t11_r3: "Találat",
    t12_title: "Kérdezz a gépet!", t12_text: "Megkérdezheted a géptől, milyen idő lesz vagy hány óra van.", t12_inst: "Párosítsd össze:", t12_h1: "Tudni akarom.", t12_h2: "Választ kapok.", t12_q: "Mit kérdezhetsz a géptől?", t12_qa: "Az időjárást", t12_qb: "A levegő ízét", t12_qc: "Semmit", t12_qd: "Hogy alszik-e",
    t12_l1: "Kérdés", t12_r1: "Időjárás", t12_l2: "Idő", t12_r2: "Óra", t12_l3: "Tudás", t12_r3: "Gép",
    t13_title: "Hangvezérlés", t13_text: "Néhány gép megérti, amit mondasz, anélkül hogy megnyomnád.", t13_inst: "Párosítsd össze:", t13_h1: "Csak beszélj.", t13_h2: "Nincs gomb.", t13_q: "Mit jelent a hangvezérlés?", t13_qa: "Szavakkal irányít", t13_qb: "Kézzel hadonász", t13_qc: "Kiabál", t13_qd: "Énekel",
    t13_l1: "Száj", t13_r1: "Beszéd", t13_l2: "Fül", t13_r2: "Hallás", t13_l3: "Parancs", t13_r3: "Vezérlés",
    t14_title: "Hajtja az áram", t14_text: "Minden okos eszköznek áramra van szüksége a konnektorból vagy elemből.", t14_inst: "Párosítsd össze:", t14_h1: "Energia kell.", t14_h2: "Áram nélkül nem megy.", t14_q: "Mi kell az okos gépeknek?", t14_qa: "Áram", t14_qb: "Víz", t14_qc: "Homok", t14_qd: "Levegő",
    t14_l1: "Akku", t14_r1: "Töltés", t14_l2: "Kábel", t14_r2: "Dugó", t14_l3: "Villám", t14_r3: "Energia",
    t15_title: "Okos-mester", t15_text: "Már szuperül kiismered magad a modern eszközök között!", t15_inst: "Párosítsd össze:", t15_h1: "Mindent értesz.", t15_h2: "Ügyes vagy.", t15_q: "Mi vagy te most?", t15_qa: "Technikai profi", t15_qb: "Egy kenyérpirító", t15_qc: "Egy bicikli", t15_qd: "Egy kő",
    t15_l1: "Mester", t15_r1: "Tudás", t15_l2: "Eszköz", t15_r2: "Okos", t15_l3: "Siker", t15_r3: "Kupa"
  },
  ro: {
    explorer_title: "Dispozitive inteligente",
    t1_title: "Smartphone-ul", t1_text: "Un smartphone este un calculator mic care încape în buzunar.", t1_inst: "Potrivește perechile:", t1_h1: "Telefon și mai mult.", t1_h2: "Mereu la tine.", t1_q: "Ce este un smartphone?", t1_qa: "Un calculator mic", t1_qb: "O piatră mare", t1_qc: "O bucată de pâine", t1_qd: "Un copac",
    t1_l1: "Smart", t1_r1: "Isteț", t1_l2: "Phone", t1_r2: "Apel", t1_l3: "Buzunar", t1_r3: "Transport",
    t2_title: "Tableta", t2_text: "Tableta este plată și are un ecran tactil mare pentru joacă.", t2_inst: "Potrivește perechile:", t2_h1: "Ecran mare.", t2_h2: "Apăsăm cu degetul.", t2_q: "Cum folosim tableta?", t2_qa: "Cu degetul", t2_qb: "Cu piciorul", t2_qc: "Cu nasul", t2_qd: "Deloc",
    t2_l1: "Tabletă", t2_r1: "Plată", t2_l2: "Atingere", t2_r2: "Touch", t2_l3: "Joc", t2_r3: "Distracție",
    t3_title: "Ceasul inteligent", t3_text: "Ceasul de la încheietură îți măsoară pașii și arată mesajele.", t3_inst: "Potrivește perechile:", t3_h1: "Ceas la mână.", t3_h2: "Numără pașii.", t3_q: "Unde purtăm ceasul inteligent?", t3_qa: "La încheietură", t3_qb: "La genunchi", t3_qc: "Pe cap", t3_qd: "În pantof",
    t3_l1: "Ceas", t3_r1: "Timp", t3_l2: "Mână", t3_r2: "Purtare", t3_l3: "Pas", t3_r3: "Numărare",
    t4_title: "Telecomanda", t4_text: "Cu telecomanda poți controla aparatele de la distanță.", t4_inst: "Potrivește perechile:", t4_h1: "Apăsare și schimbare.", t4_h2: "Nu te ridica.", t4_q: "Ce face telecomanda?", t4_qa: "Controlează aparate", t4_qb: "Gătește prânzul", t4_qc: "Spală părul", t4_qd: "Doarme",
    t4_l1: "Tele", t4_r1: "Departe", t4_l2: "Buton", t4_r2: "Apăsare", t4_l3: "TV", t4_r3: "Comutare",
    t5_title: "Robot (jucărie)", t5_text: "Roboții mici se pot rostogoli, pot clipi și uneori chiar vorbi.", t5_inst: "Potrivește perechile:", t5_h1: "Mașină pentru joacă.", t5_h2: "Clipește și merge.", t5_q: "Ce este un robot?", t5_qa: "O mașină deșteaptă", t5_qb: "Un animal real", t5_qc: "O plantă", t5_qd: "Un munte",
    t5_l1: "Robot", t5_r1: "Mașină", t5_l2: "Baterie", t5_r2: "Curent", t5_l3: "Jucărie", t5_r3: "Rostogolire",
    t6_title: "Alexa / Siri", t6_text: "Ei sunt asistenții vocali care te ascultă și îți răspund.", t6_inst: "Potrivește perechile:", t6_h1: "Vorbirea cu mașina.", t6_h2: "Te ascultă.", t6_q: "Cum vorbim cu Alexa?", t6_qa: "Cu vocea", t6_qb: "Cu picioarele", t6_qc: "Cu ochii", t6_qd: "Deloc",
    t6_l1: "Voce", t6_r1: "Vorbire", t6_l2: "Întrebare", t6_r2: "Răspuns", t6_l3: "Nume", t6_r3: "Apel",
    t7_title: "Smart TV", t7_text: "Cu un televizor modern poți viziona filme chiar și de pe internet.", t7_inst: "Potrivește perechile:", t7_h1: "Cinema mare.", t7_h2: "Internet în cameră.", t7_q: "Ce poate face un Smart TV?", t7_qa: "Filme de pe internet", t7_qb: "Spală haine", t7_qc: "Coace pâine", t7_qd: "Zboară",
    t7_l1: "TV", t7_r1: "Televizor", t7_l2: "Film", t7_r2: "Vizionare", t7_l3: "Rețea", t7_r3: "Internet",
    t8_title: "Boxă inteligentă", t8_text: "Aceste cutii redau muzică dacă le rogi.", t8_inst: "Potrivește perechile:", t8_h1: "Muzică la cerere.", t8_h2: "Ascultă cuvântul.", t8_q: "Ce face o boxă inteligentă?", t8_qa: "Redă muzică", t8_qb: "Stinge lumina", t8_qc: "Face cafea", t8_qd: "Dansează",
    t8_l1: "Cutie", t8_r1: "Boxă", t8_l2: "Muzică", t8_r2: "Ascultare", t8_l3: "Cuvânt", t8_r3: "Comandă",
    t9_title: "Mașină electrică", t9_text: "Mașinile electrice merg cu curent în loc de benzină și sunt foarte silențioase.", t9_inst: "Potrivește perechile:", t9_h1: "Merge cu curent.", t9_h2: "Foarte silențioasă.", t9_q: "De ce are nevoie o mașină electrică?", t9_qa: "Curent", t9_qb: "Sirop", t9_qc: "Supă", t9_qd: "Lemn",
    t9_l1: "Mașină", t9_r1: "Condus", t9_l2: "Curent", t9_r2: "Acumulator", t9_l3: "Silențios", t9_r3: "Motor",
    t10_title: "Casă inteligentă", t10_text: "Într-o casă inteligentă lumina se aprinde singură sau căldura pornește.", t10_inst: "Potrivește perechile:", t10_h1: "Casă isteață.", t10_h2: "Totul automat.", t10_q: "Ce este o casă inteligentă?", t10_qa: "Casă tehnologizată", t10_qb: "Casă de carton", t10_qc: "Cort", t10_qd: "Casă în copac",
    t10_l1: "Casă", t10_r1: "Locuință", t10_l2: "Lumină", t10_r2: "Foc", t10_l3: "App", t10_r3: "Control",
    t11_title: "Google Assistant", t11_text: "Google te ajută să găsești rapid lucruri pe internet.", t11_inst: "Potrivește perechile:", t11_h1: "Căutare și găsire.", t11_h2: "Ajutor isteț.", t11_q: "Ce face un asistent?", t11_qa: "Ajută", t11_qb: "Deranjează", t11_qc: "Fuge", t11_qd: "Doarme",
    t11_l1: "Google", t11_r1: "Căutare", t11_l2: "Ajutor", t11_r2: "Asistent", t11_l3: "Cunoștințe", t11_r3: "Rezultat",
    t12_title: "Întreabă mașina!", t12_text: "Poți întreba mașina cum va fi vremea sau cât e ceasul.", t12_inst: "Potrivește perechile:", t12_h1: "Vreau să știu.", t12_h2: "Primesc răspuns.", t12_q: "Ce poți întreba mașina?", t12_qa: "Vremea", t12_qb: "Gustul aerului", t12_qc: "Nimic", t12_qd: "Dacă doarme",
    t12_l1: "Întrebare", t12_r1: "Vreme", t12_l2: "Timp", t12_r2: "Ceas", t12_l3: "Cunoștințe", t12_r3: "Mașină",
    t13_title: "Control vocal", t13_text: "Unele mașini înțeleg ce spui fără să apeși pe nimic.", t13_inst: "Potrivește perechile:", t13_h1: "Doar vorbește.", t13_h2: "Fără butoane.", t13_q: "Ce înseamnă control vocal?", t13_qa: "Control prin cuvinte", t13_qb: "Dat din mâini", t13_qc: "Țipat", t13_qd: "Cântat",
    t13_l1: "Gură", t13_r1: "Vorbire", t13_l2: "Ureche", t13_r2: "Ascultare", t13_l3: "Comandă", t13_r3: "Control",
    t14_title: "Pus în mișcare de curent", t14_text: "Toate dispozitivele inteligente au nevoie de curent de la priză sau baterie.", t14_inst: "Potrivește perechile:", t14_h1: "E nevoie de energie.", t14_h2: "Fără curent nu merge.", t14_q: "De ce au nevoie dispozitivele inteligente?", t14_qa: "Curent", t14_qb: "Apă", t14_qc: "Nisip", t14_qd: "Aer",
    t14_l1: "Acumulator", t14_r1: "Încărcare", t14_l2: "Cablu", t14_r2: "Ștecher", t14_l3: "Fulger", t14_r3: "Energie",
    t15_title: "Maestru Smart", t15_text: "Acum te pricepi de minune la dispozitivele moderne!", t15_inst: "Potrivește perechile:", t15_h1: "Înțelegi totul.", t15_h2: "Ești dibaci.", t15_q: "Ce ești acum?", t15_qa: "Profi în tehnică", t15_qb: "Un prăjitor de pâine", t15_qc: "O bicicletă", t15_qd: "O piatră",
    t15_l1: "Maestru", t15_r1: "Cunoștințe", t15_l2: "Dispozitiv", t15_r2: "Smart", t15_l3: "Succes", t15_r3: "Cupă"
  }
};

export const INFO_K1_I7_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["📱", "📟", "⌚", "🎮", "🤖", "🗣️", "📺", "🔊", "🚗", "🏠", "🎙️", "❓", "🎤", "⚡", "🏆"];
  const colors = ["#00BCD4", "#009688", "#4CAF50", "#8BC34A", "#CDDC39", "#FFEB3B", "#FFC107", "#FF9800", "#FF5722", "#F44336", "#E91E63", "#9C27B0", "#673AB7", "#3F51B5", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

