// @ts-nocheck
// lib/explorerPools/informatikaK1_i8.ts
import type { PoolTopicDef } from "./types";

export const INFO_K1_I8_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Hilfe & Lernen",
    t1_title: "Lernen am Computer", t1_text: "Der Computer hilft dir beim Lernen von neuen und spannenden Dingen.", t1_inst: "Verbinde die Paare:", t1_h1: "Schlauer werden.", t1_h2: "Wissen sammeln.", t1_q: "Was kann man am Computer machen?", t1_qa: "Lernen und spielen", t1_qb: "Nur schlafen", t1_qc: "Nichts", t1_qd: "Suppe kochen",
    t1_l1: "Lernen", t1_r1: "Wissen", t1_l2: "Schule", t1_r2: "Aufgabe", t1_l3: "Spaß", t1_r3: "Spiel",
    t2_title: "Zahlen-Spiel", t2_text: "Mit lustigen Spielen lernst du ganz einfach zählen und rechnen.", t2_inst: "Verbinde die Paare:", t2_h1: "Eins, zwei, drei.", t2_h2: "Rechnen macht Spaß.", t2_q: "Was lernst du im Zahlen-Spiel?", t2_qa: "Zählen", t2_qb: "Tanzen", t2_qc: "Essen", t2_qd: "Baden",
    t2_l1: "Zahl", t2_r1: "Mathe", t2_l2: "Plus", t2_r2: "Rechnen", t2_l3: "Eins", t2_r3: "Zählen",
    t3_title: "Buchstaben-Spiel", t3_text: "Finde die richtigen Buchstaben und lerne, wie man Wörter schreibt.", t3_inst: "Verbinde die Paare:", t3_h1: "A, B, C.", t3_h2: "Wörter bauen.", t3_q: "Was sind Buchstaben?", t3_qa: "Teile von Wörtern", t3_qb: "Teile von Autos", t3_qc: "Essen", t3_qd: "Steine",
    t3_l1: "A B C", t3_r1: "Alphabet", t3_l2: "Wort", t3_r2: "Schreiben", t3_l3: "Lesen", t3_r3: "Buch",
    t4_title: "Malen lernen", t4_text: "Lerne, wie man am Bildschirm tolle Bilder und Formen zeichnet.", t4_inst: "Verbinde die Paare:", t4_h1: "Bunte Kunst.", t4_h2: "Kreativ sein.", t4_q: "Womit malen wir am Computer?", t4_qa: "Mit der Maus", t4_qb: "Mit dem Löffel", t4_qc: "Mit dem Schuh", t4_qd: "Mit dem Kamm",
    t4_l1: "Farbe", t4_r1: "Bunt", t4_l2: "Form", t4_r2: "Kreis", t4_l3: "Malen", t4_r3: "Bild",
    t5_title: "Musik lernen", t5_text: "Höre Töne und lerne, wie man am Computer Musik macht.", t5_inst: "Verbinde die Paare:", t5_h1: "Töne hören.", t5_h2: "Lieder machen.", t5_q: "Was macht Musik?", t5_qa: "Töne und Lieder", t5_qb: "Lärm und Krach", t5_qc: "Stille", t5_qd: "Essen",
    t5_l1: "Ton", t5_r1: "Musik", t5_l2: "Lied", t5_r2: "Singen", t5_l3: "Hören", t5_r3: "Ohr",
    t6_title: "Lese-Programm", t6_text: "Der Computer liest dir Geschichten vor oder hilft dir beim Selberlesen.", t6_inst: "Verbinde die Paare:", t6_h1: "Geschichten hören.", t6_h2: "Wörter erkennen.", t6_q: "Was macht ein Lese-Programm?", t6_qa: "Beim Lesen helfen", t6_qb: "Licht ausmachen", t6_qc: "Weglaufen", t6_qd: "Schlafen",
    t6_l1: "Lesen", t6_r1: "Buch", t6_l2: "Text", t6_r2: "Wort", t6_l3: "Auge", t6_r3: "Sehen",
    t7_title: "Frage und Antwort", t7_text: "Beantworte Fragen und zeige, was du schon alles weißt.", t7_inst: "Verbinde die Paare:", t7_h1: "Gut aufpassen.", t7_h2: "Die Lösung finden.", t7_q: "Was kommt nach einer Frage?", t7_qa: "Die Antwort", t7_qb: "Ein Lied", t7_qc: "Ein Tanz", t7_qd: "Nichts",
    t7_l1: "Frage", t7_r1: "Antwort", t7_l2: "Richtig", t7_r2: "Häkchen", t7_l3: "Falsch", t7_r3: "Kreuz",
    t8_title: "Üben macht Spaß", t8_text: "Wiederhole Aufgaben, um immer besser und schneller zu werden.", t8_inst: "Verbinde die Paare:", t8_h1: "Nochmal machen.", t8_h2: "Besser werden.", t8_q: "Warum üben wir?", t8_qa: "Um zu lernen", t8_qb: "Um zu vergessen", t8_qc: "Um zu schlafen", t8_qd: "Um zu essen",
    t8_l1: "Üben", t8_r1: "Lernen", t8_l2: "Fleiß", t8_r2: "Stern", t8_l3: "Ziel", t8_r3: "Können",
    t9_title: "Wiederholung", t9_text: "Wenn du etwas oft machst, kannst du es dir besonders gut merken.", t9_inst: "Verbinde die Paare:", t9_h1: "Immer wieder.", t9_h2: "Nicht vergessen.", t9_q: "Was hilft beim Merken?", t9_qa: "Wiederholen", t9_qb: "Wegwerfen", t9_qc: "Verstecken", t9_qd: "Schreien",
    t9_l1: "Wieder", t9_r1: "Nochmal", t9_l2: "Merk", t9_r2: "Kopf", t9_l3: "Wissen", t9_r3: "Behalten",
    t10_title: "Belohnung", t10_text: "Für jede gelöste Aufgabe bekommst du tolle digitale Sticker.", t10_inst: "Verbinde die Paare:", t10_h1: "Gut gemacht.", t10_h2: "Sammle Sticker.", t10_q: "Was bekommst du für Fleiß?", t10_qa: "Einen Sticker", t10_qb: "Eine Hausaufgabe", t10_qc: "Nichts", t10_qd: "Einen Stein",
    t10_l1: "Sticker", t10_r1: "Bildchen", t10_l2: "Sammeln", t10_r2: "Album", t10_l3: "Super", t10_r3: "Lob",
    t11_title: "Richtig oder Falsch", t11_text: "Überlege genau: Stimmt die Aussage oder ist sie Quatsch?", t11_inst: "Verbinde die Paare:", t11_h1: "Ja oder Nein.", t11_h2: "Genau prüfen.", t11_q: "Was ist das Gegenteil von Richtig?", t11_qa: "Falsch", t11_qb: "Gut", t11_qc: "Schön", t11_qd: "Groß",
    t11_l1: "Ja", t11_r1: "Richtig", t11_l2: "Nein", t11_r2: "Falsch", t11_l3: "Check", t11_r3: "Prüfen",
    t12_title: "Quiz-Spiel", t12_text: "Ein Quiz ist ein Spiel, bei dem man viele Fragen beantworten muss.", t12_inst: "Verbinde die Paare:", t12_h1: "Raten und wissen.", t12_h2: "Punkte sammeln.", t12_q: "Was macht man im Quiz?", t12_qa: "Fragen beantworten", t12_qb: "Auto fahren", t12_qc: "Suppe essen", t12_qd: "Schlafen",
    t12_l1: "Quiz", t12_r1: "Fragen", t12_l2: "Punkte", t12_r2: "Gewinn", t12_l3: "Wahl", t12_r3: "Klick",
    t13_title: "Level und Stufen", t13_text: "Wenn du ein Level schaffst, wird die nächste Aufgabe ein bisschen schwerer.", t13_inst: "Verbinde die Paare:", t13_h1: "Immer weiter.", t13_h2: "Höher kommen.", t13_q: "Was kommt nach Level 1?", t13_qa: "Level 2", t13_qb: "Level 0", t13_qc: "Ende", t13_qd: "Pause",
    t13_l1: "Level", t13_r1: "Stufe", t13_l2: "Aufstieg", t13_r2: "Höher", t13_l3: "Schwer", t13_r3: "Herausforderung",
    t14_title: "Fortschritt speichern", t14_text: "Der Computer merkt sich, was du schon alles gelernt hast.", t14_inst: "Verbinde die Paare:", t14_h1: "Nichts verlieren.", t14_h2: "Morgen weitermachen.", t14_q: "Was macht der Computer mit deinem Erfolg?", t14_qa: "Er merkt ihn sich", t14_qb: "Er löscht ihn", t14_qc: "Er lacht", t14_qd: "Nichts",
    t14_l1: "Speichern", t14_r1: "Behalten", t14_l2: "Morgen", t14_r2: "Weiter", t14_l3: "Weg", t14_r3: "Ziel",
    t15_title: "Lern-Meister", t15_text: "Du bist jetzt ein echter Profi im Lernen am Computer!", t15_inst: "Verbinde die Paare:", t15_h1: "Du bist schlau.", t15_h2: "Alles geschafft.", t15_q: "Was hast du heute gemacht?", t15_qa: "Viel gelernt", t15_qb: "Nur geschlafen", t15_qc: "Nichts", t15_qd: "Geweint",
    t15_l1: "Meister", t15_r1: "Schlau", t15_l2: "Lernen", t15_r2: "Erfolg", t15_l3: "Sieg", t15_r3: "Pokal"
  },
  en: {
    explorer_title: "Help & Learning",
    t1_title: "Learning on Computer", t1_text: "The computer helps you learn new and exciting things.", t1_inst: "Match the pairs:", t1_h1: "Get smarter.", t1_h2: "Collect knowledge.", t1_q: "What can you do on the computer?", t1_qa: "Learn and play", t1_qb: "Only sleep", t1_qc: "Nothing", t1_qd: "Cook soup",
    t1_l1: "Learn", t1_r1: "Knowledge", t1_l2: "School", t1_r2: "Task", t1_l3: "Fun", t1_r3: "Game",
    t2_title: "Number Game", t2_text: "With fun games, you easily learn to count and do math.", t2_inst: "Match the pairs:", t2_h1: "One, two, three.", t2_h2: "Math is fun.", t2_q: "What do you learn in the number game?", t2_qa: "Counting", t2_qb: "Dancing", t2_qc: "Eating", t2_qd: "Bathing",
    t2_l1: "Number", t2_r1: "Math", t2_l2: "Plus", t2_r2: "Calculate", t2_l3: "One", t2_r3: "Count",
    t3_title: "Letter Game", t3_text: "Find the right letters and learn how to write words.", t3_inst: "Match the pairs:", t3_h1: "A, B, C.", t3_h2: "Build words.", t3_q: "What are letters?", t3_qa: "Parts of words", t3_qb: "Parts of cars", t3_qc: "Food", t3_qd: "Stones",
    t3_l1: "A B C", t3_r1: "Alphabet", t3_l2: "Word", t3_r2: "Write", t3_l3: "Read", t3_r3: "Book",
    t4_title: "Learn to Paint", t4_text: "Learn how to draw great pictures and shapes on the screen.", t4_inst: "Match the pairs:", t4_h1: "Colorful art.", t4_h2: "Be creative.", t4_q: "What do we paint with on the computer?", t4_qa: "With the mouse", t4_qb: "With a spoon", t4_qc: "With a shoe", t4_qd: "With a comb",
    t4_l1: "Color", t4_r1: "Colorful", t4_l2: "Shape", t4_r2: "Circle", t4_l3: "Paint", t4_r3: "Picture",
    t5_title: "Learn Music", t5_text: "Listen to sounds and learn how to make music on the computer.", t5_inst: "Match the pairs:", t5_h1: "Hear sounds.", t5_h2: "Make songs.", t5_q: "What makes music?", t5_qa: "Sounds and songs", t5_qb: "Noise and din", t5_qc: "Silence", t5_qd: "Food",
    t5_l1: "Sound", t5_r1: "Music", t5_l2: "Song", t5_r2: "Sing", t5_l3: "Hear", t5_r3: "Ear",
    t6_title: "Reading Program", t6_text: "The computer reads stories to you or helps you read yourself.", t6_inst: "Match the pairs:", t6_h1: "Hear stories.", t6_h2: "Recognize words.", t6_q: "What does a reading program do?", t6_qa: "Help with reading", t6_qb: "Turn off light", t6_qc: "Run away", t6_qd: "Sleep",
    t6_l1: "Read", t6_r1: "Book", t6_l2: "Text", t6_r2: "Word", t6_l3: "Eye", t6_r3: "See",
    t7_title: "Question and Answer", t7_text: "Answer questions and show what you already know.", t7_inst: "Match the pairs:", t7_h1: "Pay attention.", t7_h2: "Find the solution.", t7_q: "What comes after a question?", t7_qa: "The answer", t7_qb: "A song", t7_qc: "A dance", t7_qd: "Nothing",
    t7_l1: "Question", t7_r1: "Answer", t7_l2: "Right", t7_r2: "Checkmark", t7_l3: "Wrong", t7_r3: "Cross",
    t8_title: "Practice is Fun", t8_text: "Repeat tasks to get better and faster.", t8_inst: "Match the pairs:", t8_h1: "Do it again.", t8_h2: "Get better.", t8_q: "Why do we practice?", t8_qa: "To learn", t8_qb: "To forget", t8_qc: "To sleep", t8_qd: "To eat",
    t8_l1: "Practice", t8_r1: "Learn", t8_l2: "Diligence", t8_r2: "Star", t8_l3: "Goal", t8_r3: "Skill",
    t9_title: "Repetition", t9_text: "If you do something often, you can remember it particularly well.", t9_inst: "Match the pairs:", t9_h1: "Again and again.", t9_h2: "Don't forget.", t9_q: "What helps with remembering?", t9_qa: "Repeating", t9_qb: "Throwing away", t9_qc: "Hiding", t9_qd: "Screaming",
    t9_l1: "Again", t9_r1: "Once more", t9_l2: "Memory", t9_r2: "Head", t9_l3: "Knowledge", t9_r3: "Keep",
    t10_title: "Reward", t10_text: "For every solved task, you get great digital stickers.", t10_inst: "Match the pairs:", t10_h1: "Well done.", t10_h2: "Collect stickers.", t10_q: "What do you get for diligence?", t10_qa: "A sticker", t10_qb: "Homework", t10_qc: "Nothing", t10_qd: "A stone",
    t10_l1: "Sticker", t10_r1: "Picture", t10_l2: "Collect", t10_r2: "Album", t10_l3: "Super", t10_r3: "Praise",
    t11_title: "True or False", t11_text: "Think carefully: Is the statement correct or is it nonsense?", t11_inst: "Match the pairs:", t11_h1: "Yes or No.", t11_h2: "Check carefully.", t11_q: "What is the opposite of right?", t11_qa: "Wrong", t11_qb: "Good", t11_qc: "Nice", t11_qd: "Big",
    t11_l1: "Yes", t11_r1: "Right", t11_l2: "No", t11_r2: "Wrong", t11_l3: "Check", t11_r3: "Verify",
    t12_title: "Quiz Game", t12_text: "A quiz is a game where you have to answer many questions.", t12_inst: "Match the pairs:", t12_h1: "Guess and know.", t12_h2: "Collect points.", t12_q: "What do you do in a quiz?", t12_qa: "Answer questions", t12_qb: "Drive a car", t12_qc: "Eat soup", t12_qd: "Sleep",
    t12_l1: "Quiz", t12_r1: "Questions", t12_l2: "Points", t12_r2: "Win", t12_l3: "Choice", t12_r3: "Click",
    t13_title: "Levels and Stages", t13_text: "If you pass a level, the next task will be a bit harder.", t13_inst: "Match the pairs:", t13_h1: "Keep going.", t13_h2: "Get higher.", t13_q: "What comes after Level 1?", t13_qa: "Level 2", t13_qb: "Level 0", t13_qc: "End", t13_qd: "Pause",
    t13_l1: "Level", t13_r1: "Stage", t13_l2: "Rise", t13_r2: "Higher", t13_l3: "Hard", t13_r3: "Challenge",
    t14_title: "Save Progress", t14_text: "The computer remembers everything you have already learned.", t14_inst: "Match the pairs:", t14_h1: "Don't lose anything.", t14_h2: "Continue tomorrow.", t14_q: "What does the computer do with your success?", t14_qa: "It remembers it", t14_qb: "It deletes it", t14_qc: "It laughs", t14_qd: "Nothing",
    t14_l1: "Save", t14_r1: "Keep", t14_l2: "Tomorrow", t14_r2: "Continue", t14_l3: "Path", t14_r3: "Goal",
    t15_title: "Learning Master", t15_text: "You are now a real pro at learning on the computer!", t15_inst: "Match the pairs:", t15_h1: "You are smart.", t15_h2: "Finished everything.", t15_q: "What did you do today?", t15_qa: "Learned a lot", t15_qb: "Only slept", t15_qc: "Nothing", t15_qd: "Cried",
    t15_l1: "Master", t15_r1: "Smart", t15_l2: "Learn", t15_r2: "Success", t15_l3: "Victory", t15_r3: "Trophy"
  },
  hu: {
    explorer_title: "Segítség és tanulás",
    t1_title: "Mit tanulunk gépen?", t1_text: "A számítógép segít neked új és izgalmas dolgokat megtanulni.", t1_inst: "Párosítsd össze:", t1_h1: "Legyél okosabb.", t1_h2: "Gyűjtsd a tudást.", t1_q: "Mit lehet csinálni a gépen?", t1_qa: "Tanulni és játszani", t1_qb: "Csak aludni", t1_qc: "Semmit", t1_qd: "Levest főzni",
    t1_l1: "Tanulás", t1_r1: "Tudás", t1_l2: "Iskola", t1_r2: "Feladat", t1_l3: "Móka", t1_r3: "Játék",
    t2_title: "Számolós játék", t2_text: "Vidám játékokkal könnyen megtanulhatsz számolni és matekozni.", t2_inst: "Párosítsd össze:", t2_h1: "Egy, kettő, három.", t2_h2: "A matek jó.", t2_q: "Mit tanulsz a számolós játékban?", t2_qa: "Számolást", t2_qb: "Táncolást", t2_qc: "Evést", t2_qd: "Fürdést",
    t2_l1: "Szám", t2_r1: "Matek", t2_l2: "Plusz", t2_r2: "Számolás", t2_l3: "Egy", t2_r3: "Számlálás",
    t3_title: "Betű-játék", t3_text: "Keresd meg a helyes betűket, és tanuld meg, hogyan írjuk a szavakat.", t3_inst: "Párosítsd össze:", t3_h1: "A, B, C.", t3_h2: "Szavak építése.", t3_q: "Mik azok a betűk?", t3_qa: "Szavak részei", t3_qb: "Autók részei", t3_qc: "Ételek", t3_qd: "Kövek",
    t3_l1: "A B C", t3_r1: "Ábécé", t3_l2: "Szó", t3_r2: "Írás", t3_l3: "Olvasás", t3_r3: "Könyv",
    t4_title: "Rajzolós tanuló", t4_text: "Tanuld meg, hogyan rajzolhatsz szép képeket és formákat a képernyőn.", t4_inst: "Párosítsd össze:", t4_h1: "Színes művészet.", t4_h2: "Légy ügyes.", t4_q: "Mivel rajzolunk a gépen?", t4_qa: "Egérrel", t4_qb: "Kanállal", t4_qc: "Cipővel", t4_qd: "Fésűvel",
    t4_l1: "Szín", t4_r1: "Színes", t4_l2: "Forma", t4_r2: "Kör", t4_l3: "Rajzolás", t4_r3: "Kép",
    t5_title: "Zenés tanuló", t5_text: "Hallgass hangokat, és tanuld meg, hogyan készül a zene a gépen.", t5_inst: "Párosítsd össze:", t5_h1: "Hangok hallása.", t5_h2: "Dalok készítése.", t5_q: "Mi alkotja a zenét?", t5_qa: "Hangok és dalok", t5_qb: "Zaj és lárma", t5_qc: "Csend", t5_qd: "Ebéd",
    t5_l1: "Hang", t5_r1: "Zene", t5_l2: "Dal", t5_r2: "Éneklés", t5_l3: "Hallás", t5_r3: "Fül",
    t6_title: "Olvasós program", t6_text: "A gép felolvassa neked a meséket, vagy segít neked az olvasásban.", t6_inst: "Párosítsd össze:", t6_h1: "Mesék hallgatása.", t6_h2: "Szavak felismerése.", t6_q: "Mit csinál az olvasós program?", t6_qa: "Segít olvasni", t6_qb: "Lámpát olt", t6_qc: "Elszalad", t6_qd: "Alszik",
    t6_l1: "Olvasás", t6_r1: "Könyv", t6_l2: "Szöveg", t6_r2: "Szó", t6_l3: "Szem", t6_r3: "Látás",
    t7_title: "Kérdés-válasz", t7_text: "Válaszolj a kérdésekre, és mutasd meg, mi mindent tudsz már.", t7_inst: "Párosítsd össze:", t7_h1: "Figyelj jól.", t7_h2: "Találd meg a választ.", t7_q: "Mi jön a kérdés után?", t7_qa: "A válasz", t7_qb: "Egy dal", t7_qc: "Egy tánc", t7_qd: "Semmi",
    t7_l1: "Kérdés", t7_r1: "Válasz", t7_l2: "Helyes", t7_r2: "Pipa", t7_l3: "Rossz", t7_r3: "X",
    t8_title: "Gyakorlás", t8_text: "Ismételd meg a feladatokat, hogy egyre ügyesebb és gyorsabb legyél.", t8_inst: "Párosítsd össze:", t8_h1: "Csináld újra.", t8_h2: "Legyél jobb.", t8_q: "Miért gyakorolunk?", t8_qa: "Hogy tanuljunk", t8_qb: "Hogy elfelejtsük", t8_qc: "Hogy aludjunk", t8_qd: "Hogy együnk",
    t8_l1: "Gyakorlás", t8_r1: "Tanulás", t8_l2: "Szorgalom", t8_r2: "Csillag", t8_l3: "Cél", t8_r3: "Tudás",
    t9_title: "Ismétlés", t9_text: "Ha valamit sokszor csinálsz, azt nagyon jól meg tudod jegyezni.", t9_inst: "Párosítsd össze:", t9_h1: "Újra és újra.", t9_h2: "Ne felejtsd el.", t9_q: "Mi segít a megjegyzésben?", t9_qa: "Az ismétlés", t9_qb: "A kidobás", t9_qc: "Az elrejtés", t9_qd: "A kiabálás",
    t9_l1: "Újra", t9_r1: "Ismét", t9_l2: "Emlék", t9_r2: "Fej", t9_l3: "Tudás", t9_r3: "Megtartás",
    t10_title: "Jutalom matrica", t10_text: "Minden megoldott feladatért szép digitális matricákat kapsz.", t10_inst: "Párosítsd össze:", t10_h1: "Szép munka.", t10_h2: "Gyűjtsd a matricát.", t10_q: "Mit kapsz a szorgalomért?", t10_qa: "Egy matricát", t10_qb: "Házi feladatot", t10_qc: "Semmit", t10_qd: "Egy követ",
    t10_l1: "Matrica", t10_r1: "Kép", t10_l2: "Gyűjtés", t10_r2: "Album", t10_l3: "Szuper", t10_r3: "Dicséret",
    t11_title: "Igaz-hamis", t11_text: "Gondold át jól: igaz, amit hallasz, vagy csak butaság?", t11_inst: "Párosítsd össze:", t11_h1: "Igen vagy nem.", t11_h2: "Ellenőrizd.", t11_q: "Mi az ellentéte az igaznak?", t11_qa: "Hamis", t11_qb: "Jó", t11_qc: "Szép", t11_qd: "Nagy",
    t11_l1: "Igen", t11_r1: "Igaz", t11_l2: "Nem", t11_r2: "Hamis", t11_l3: "Pipa", t11_r3: "Ellenőrzés",
    t12_title: "Kvíz játék", t12_text: "A kvíz egy olyan játék, ahol sok kérdésre kell válaszolni.", t12_inst: "Párosítsd össze:", t12_h1: "Találd ki.", t12_h2: "Gyűjts pontot.", t12_q: "Mit csinálunk a kvízben?", t12_qa: "Kérdésekre válaszolunk", t12_qb: "Autót vezetünk", t12_qc: "Levest eszünk", t12_qd: "Alszunk",
    t12_l1: "Kvíz", t12_r1: "Kérdések", t12_l2: "Pontok", t12_r2: "Nyeremény", t12_l3: "Választás", t12_r3: "Kattintás",
    t13_title: "Szintek", t13_text: "Ha sikerül egy szint, a következő feladat egy kicsit nehezebb lesz.", t13_inst: "Párosítsd össze:", t13_h1: "Csak előre.", t13_h2: "Juss magasabbra.", t13_q: "Mi jön az 1. szint után?", t13_qa: "A 2. szint", t13_qb: "A 0. szint", t13_qc: "Vége", t13_qd: "Szünet",
    t13_l1: "Szint", t13_r1: "Fokozat", t13_l2: "Fejlődés", t13_r2: "Magasabb", t13_l3: "Nehéz", t13_r3: "Kihívás",
    t14_title: "Haladás mentése", t14_text: "A számítógép megjegyzi, mi mindent tanultál már meg.", t14_inst: "Párosítsd össze:", t14_h1: "Ne vesszen el.", t14_h2: "Holnap folytatjuk.", t14_q: "Mit csinál a gép a sikereiddel?", t14_qa: "Megjegyzi őket", t14_qb: "Kitörli őket", t14_qc: "Nevet", t14_qd: "Semmit",
    t14_l1: "Mentés", t14_r1: "Megtartás", t14_l2: "Holnap", t14_r2: "Folytatás", t14_l3: "Út", t14_r3: "Cél",
    t15_title: "Tanuló-mester", t15_text: "Már igazi profi vagy a számítógépes tanulásban!", t15_inst: "Párosítsd össze:", t15_h1: "Okos vagy.", t15_h2: "Mindent sikerült.", t15_q: "Mit csináltál ma?", t15_qa: "Sokat tanultam", t15_qb: "Csak aludtam", t15_qc: "Semmit", t15_qd: "Sírtam",
    t15_l1: "Mester", t15_r1: "Okos", t15_l2: "Tanulás", t15_r2: "Siker", t15_l3: "Győzelem", t15_r3: "Kupa"
  },
  ro: {
    explorer_title: "Ajutor & Învățare",
    t1_title: "Învățarea pe calculator", t1_text: "Calculatorul te ajută să înveți lucruri noi și interesante.", t1_inst: "Potrivește perechile:", t1_h1: "Fii mai deștept.", t1_h2: "Adună cunoștințe.", t1_q: "Ce poți face pe calculator?", t1_qa: "Să înveți și să te joci", t1_qb: "Doar să dormi", t1_qc: "Nimic", t1_qd: "Să gătești supă",
    t1_l1: "Învățare", t1_r1: "Cunoștințe", t1_l2: "Școală", t1_r2: "Sarcină", t1_l3: "Distracție", t1_r3: "Joc",
    t2_title: "Joc cu numere", t2_text: "Cu jocuri vesele înveți ușor să numeri și să faci matematică.", t2_inst: "Potrivește perechile:", t2_h1: "Unu, doi, trei.", t2_h2: "Mate e bună.", t2_q: "Ce înveți în jocul cu numere?", t2_qa: "Să numeri", t2_qb: "Să dansezi", t2_qc: "Să mănânci", t2_qd: "Să faci baie",
    t2_l1: "Număr", t2_r1: "Mate", t2_l2: "Plus", t2_r2: "Calcul", t2_l3: "Unu", t2_r3: "Numărare",
    t3_title: "Joc cu litere", t3_text: "Caută literele corecte și învață cum se scriu cuvintele.", t3_inst: "Potrivește perechile:", t3_h1: "A, B, C.", t3_h2: "Construirea cuvintelor.", t3_q: "Ce sunt literele?", t3_qa: "Părți din cuvinte", t3_qb: "Părți din mașini", t3_qc: "Mâncare", t3_qd: "Pietre",
    t3_l1: "A B C", t3_r1: "Alfabet", t3_l2: "Cuvânt", t3_r2: "Scriere", t3_l3: "Citire", t3_r3: "Carte",
    t4_title: "Învățarea desenului", t4_text: "Învață cum poți desena imagini și forme frumoase pe ecran.", t4_inst: "Potrivește perechile:", t4_h1: "Artă colorată.", t4_h2: "Fii dibaci.", t4_q: "Cu ce desenăm pe calculator?", t4_qa: "Cu mouse-ul", t4_qb: "Cu lingura", t4_qc: "Cu pantoful", t4_qd: "Cu pieptenele",
    t4_l1: "Culoare", t4_r1: "Colorat", t4_l2: "Formă", t4_r2: "Cerc", t4_l3: "Desen", t4_r3: "Imagine",
    t5_title: "Învățarea muzicii", t5_text: "Ascultă sunete și învață cum se face muzica pe calculator.", t5_inst: "Potrivește perechile:", t5_h1: "Auzirea sunetelor.", t5_h2: "Crearea cântecelor.", t5_q: "Ce formează muzica?", t5_qa: "Sunete și cântece", t5_qb: "Zgomot și larmă", t5_qc: "Liniște", t5_qd: "Prânz",
    t5_l1: "Sunet", t5_r1: "Muzică", t5_l2: "Cântec", t5_r2: "Cântat", t5_l3: "Auz", t5_r3: "Ureche",
    t6_title: "Program de citire", t6_text: "Calculatorul îți citește povești sau te ajută la citit.", t6_inst: "Potrivește perechile:", t6_h1: "Ascultarea poveștilor.", t6_h2: "Recunoașterea cuvintelor.", t6_q: "Ce face programul de citire?", t6_qa: "Ajută la citit", t6_qb: "Stinge lumina", t6_qc: "Fuge", t6_qd: "Doarme",
    t6_l1: "Citire", t6_r1: "Carte", t6_l2: "Text", t6_r2: "Cuvânt", t6_l3: "Ochi", t6_r3: "Vedere",
    t7_title: "Întrebare-răspuns", t7_text: "Răspunde la întrebări și arată tot ce știi deja.", t7_inst: "Potrivește perechile:", t7_h1: "Fii atent.", t7_h2: "Găsește răspunsul.", t7_q: "Ce vine după o întrebare?", t7_qa: "Răspunsul", t7_qb: "Un cântec", t7_qc: "Un dans", t7_qd: "Nimic",
    t7_l1: "Întrebare", t7_r1: "Răspuns", t7_l2: "Corect", t7_r2: "Bifă", t7_l3: "Greșit", t7_r3: "X",
    t8_title: "Exersare", t8_text: "Repetă sarcinile pentru a deveni tot mai dibaci și mai rapid.", t8_inst: "Potrivește perechile:", t8_h1: "Fă din nou.", t8_h2: "Fii mai bun.", t8_q: "De ce exersăm?", t8_qa: "Ca să învățăm", t8_qb: "Ca să uităm", t8_qc: "Ca să dormim", t8_qd: "Ca să mâncăm",
    t8_l1: "Exersare", t8_r1: "Învățare", t8_l2: "Hărnicie", t8_r2: "Stea", t8_l3: "Scop", t8_r3: "Cunoștințe",
    t9_title: "Repetare", t9_text: "Dacă faci ceva de multe ori, vei putea reține foarte bine.", t9_inst: "Potrivește perechile:", t9_h1: "Din nou și din nou.", t9_h2: "Nu uita.", t9_q: "Ce ajută la memorare?", t9_qa: "Repetarea", t9_qb: "Aruncarea", t9_qc: "Ascunderea", t9_qd: "Țipatul",
    t9_l1: "Din nou", t9_r1: "Repetă", t9_l2: "Amintire", t9_r2: "Cap", t9_l3: "Cunoștințe", t9_r3: "Păstrare",
    t10_title: "Abțibild recompensă", t10_text: "Pentru fiecare sarcină rezolvată primești abțibilduri digitale frumoase.", t10_inst: "Potrivește perechile:", t10_h1: "Bună treabă.", t10_h2: "Adună abțibildul.", t10_q: "Ce primești pentru hărnicie?", t10_qa: "Un abțibild", t10_qb: "Temă pentru acasă", t10_qc: "Nimic", t10_qd: "O piatră",
    t10_l1: "Abțibild", t10_r1: "Imagine", t10_l2: "Colectare", t10_r2: "Album", t10_l3: "Super", t10_r3: "Laudă",
    t11_title: "Adevărat-fals", t11_text: "Gândește-te bine: e adevărat ce auzi sau e doar o prostie?", t11_inst: "Potrivește perechile:", t11_h1: "Da sau nu.", t11_h2: "Verifică.", t11_q: "Care este opusul adevărului?", t11_qa: "Fals", t11_qb: "Bine", t11_qc: "Frumos", t11_qd: "Mare",
    t11_l1: "Da", t11_r1: "Adevărat", t11_l2: "Nu", t11_r2: "Fals", t11_l3: "Bifă", t11_r3: "Verificare",
    t12_title: "Joc Quiz", t12_text: "Quiz-ul este un joc unde trebuie să răspunzi la multe întrebări.", t12_inst: "Potrivește perechile:", t12_h1: "Ghicește.", t12_h2: "Adună puncte.", t12_q: "Ce facem în quiz?", t12_qa: "Răspundem la întrebări", t12_qb: "Conducem mașina", t12_qc: "Mâncăm supă", t12_qd: "Dormim",
    t12_l1: "Quiz", t12_r1: "Întrebări", t12_l2: "Puncte", t12_r2: "Premiu", t12_l3: "Alegere", t12_r3: "Clic",
    t13_title: "Niveluri", t13_text: "Dacă reușești un nivel, următoarea sarcină va fi puțin mai grea.", t13_inst: "Potrivește perechile:", t13_h1: "Doar înainte.", t13_h2: "Ajungi mai sus.", t13_q: "Ce vine după nivelul 1?", t13_qa: "Nivelul 2", t13_qb: "Nivelul 0", t13_qc: "Sfârșit", t13_qd: "Pauză",
    t13_l1: "Nivel", t13_r1: "Treaptă", t13_l2: "Evoluție", t13_r2: "Mai sus", t13_l3: "Greu", t13_r3: "Provocare",
    t14_title: "Salvarea progresului", t14_text: "Calculatorul reține tot ce ai învățat deja.", t14_inst: "Potrivește perechile:", t14_h1: "Să nu se piardă.", t14_h2: "Continuăm mâine.", t14_q: "Ce face mașina cu succesele tale?", t14_qa: "Le reține", t14_qb: "Le șterge", t14_qc: "Râde", t14_qd: "Nimic",
    t14_l1: "Salvare", t14_r1: "Păstrare", t14_l2: "Mâine", t14_r2: "Continuare", t14_l3: "Drum", t14_r3: "Scop",
    t15_title: "Maestru învățăcel", t15_text: "Ești deja un adevărat profi la învățarea pe calculator!", t15_inst: "Potrivește perechile:", t15_h1: "Ești deștept.", t15_h2: "Ai reușit totul.", t15_q: "Ce ai făcut azi?", t15_qa: "Am învățat mult", t15_qb: "Doar am dormit", t15_qc: "Nimic", t15_qd: "Am plâns",
    t15_l1: "Maestru", t15_r1: "Isteț", t15_l2: "Învățare", t15_r2: "Succes", t15_l3: "Victorie", t15_r3: "Cupă"
  }
};

export const INFO_K1_I8_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["🎓", "🔢", "🔤", "🎨", "🎵", "📖", "💬", "✍️", "🔁", "🌟", "✅", "❓", "📈", "💾", "🏆"];
  const colors = ["#3F51B5", "#2196F3", "#03A9F4", "#00BCD4", "#009688", "#4CAF50", "#8BC34A", "#CDDC39", "#FFEB3B", "#FFC107", "#FF9800", "#FF5722", "#F44336", "#E91E63", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

