// lib/explorerPools/informatikaK7_i8.ts
import type { PoolTopicDef } from "./types";

export const INFO_K7_I8_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Informatik Entdecker K7-8",
    t1_title: "SELECT (SQL)", t1_text: "Mit SELECT wählst du aus, welche Spalten einer Tabelle du sehen möchtest.", t1_inst: "Ordne die Paare zu:", t1_h1: "SELECT = Auswählen.", t1_h2: "* bedeutet alles.", t1_q: "Was macht der SELECT-Befehl in SQL?", t1_qa: "Wählt Spalten aus", t1_qb: "Löscht Daten", t1_qc: "Erstellt eine Tabelle", t1_qd: "Ändert Passwörter",
    t1_l1: "SELECT", t1_r1: "Spalten auswählen", t1_l2: "*", t1_r2: "Alle Spalten", t1_l3: "SELECT Name", t1_r3: "Nur Name zeigen", t1_l4: "SQL", t1_r4: "Datenbanksprache",
    t2_title: "FROM (SQL)", t2_text: "FROM gibt an, aus welcher Tabelle die Daten geholt werden sollen.", t2_inst: "Fülle die Lücke aus:", t2_h1: "SELECT ... FROM Tabelle.", t2_h2: "Woher kommen die Daten?", t2_q: "Wofür steht FROM in einer SQL-Abfrage?", t2_qa: "Gibt die Tabelle an", t2_qb: "Gibt die Spalte an", t2_qc: "Sortiert die Daten", t2_qd: "Löscht die Tabelle",
    t2_sent: "SELECT * ___ Kunden;", t2_c1: "FROM", t2_c2: "IN", t2_c3: "TO", t2_c4: "AT",
    t3_title: "WHERE (SQL)", t3_text: "Mit WHERE filterst du die Daten nach bestimmten Bedingungen (z.B. WHERE Alter > 18).", t3_inst: "Sortiere in die Eimer:", t3_h1: "Bedingung oder Befehl?", t3_h2: "WHERE filtert.", t3_q: "Was macht die WHERE-Klausel?", t3_qa: "Filtert Datensätze nach Bedingungen", t3_qb: "Wählt alle Daten aus", t3_qc: "Löscht die Datenbank", t3_qd: "Erstellt eine neue Spalte",
    t3_bl1: "Befehl", t3_bl2: "Bedingung", t3_i1: "SELECT", t3_i2: "Alter > 18", t3_i3: "FROM", t3_i4: "Name = 'Anna'",
    t4_title: "INSERT INTO (SQL)", t4_text: "Mit INSERT INTO fügst du neue Datensätze (Zeilen) in eine Tabelle ein.", t4_inst: "Bringe die Wörter in Ordnung:", t4_h1: "Einfügen in Tabelle.", t4_h2: "INSERT INTO.", t4_q: "Wie fügt man neue Daten in SQL ein?", t4_qa: "Mit INSERT INTO", t4_qb: "Mit ADD DATA", t4_qc: "Mit NEW ROW", t4_qd: "Mit CREATE",
    t4_w1: "INSERT", t4_w2: "INTO", t4_w3: "Kunden", t4_w4: "VALUES",
    t5_title: "UPDATE (SQL)", t5_text: "Mit UPDATE änderst du bestehende Daten in einer Tabelle. Wichtig: WHERE nicht vergessen!", t5_inst: "Markiere das richtige Wort:", t5_h1: "Daten aktualisieren.", t5_h2: "UPDATE ändert.", t5_q: "Was passiert, wenn man bei UPDATE das WHERE vergisst?", t5_qa: "Alle Datensätze werden geändert", t5_qb: "Nichts passiert", t5_qc: "Die Tabelle wird gelöscht", t5_qd: "Es gibt einen Syntaxfehler",
    t5_tk1: "Mit", t5_tk2: "UPDATE", t5_tk3: "ändert man", t5_tk4: "Daten.",
    t6_title: "DELETE (SQL)", t6_text: "Mit DELETE löschst du Datensätze aus einer Tabelle. Auch hier: WHERE nicht vergessen!", t6_inst: "Ordne die Paare zu:", t6_h1: "Löschen von Daten.", t6_h2: "Vorsicht mit DELETE!", t6_q: "Welcher Befehl löscht Zeilen in SQL?", t6_qa: "DELETE", t6_qb: "REMOVE", t6_qc: "DROP", t6_qd: "CLEAR",
    t6_l1: "DELETE", t6_r1: "Zeilen löschen", t6_l2: "UPDATE", t6_r2: "Zeilen ändern", t6_l3: "INSERT", t6_r3: "Zeilen hinzufügen", t6_l4: "SELECT", t6_r4: "Zeilen lesen",
    t7_title: "ORDER BY (SQL)", t7_text: "Mit ORDER BY sortierst du die Ergebnisse (ASC für aufsteigend, DESC für absteigend).", t7_inst: "Fülle die Lücke aus:", t7_h1: "Sortieren nach...", t7_h2: "ORDER BY.", t7_q: "Wie sortiert man Ergebnisse in SQL absteigend?", t7_qa: "ORDER BY Spalte DESC", t7_qb: "ORDER BY Spalte ASC", t7_qc: "SORT BY Spalte DOWN", t7_qd: "ORDER DOWN",
    t7_sent: "SELECT * FROM Kunden ___ Name;", t7_c1: "ORDER BY", t7_c2: "SORT BY", t7_c3: "GROUP BY", t7_c4: "FILTER BY",
    t8_title: "GROUP BY (SQL)", t8_text: "Mit GROUP BY fasst du Zeilen mit gleichen Werten zusammen, oft genutzt mit COUNT oder SUM.", t8_inst: "Bringe die Wörter in Ordnung:", t8_h1: "Gruppieren nach...", t8_h2: "GROUP BY.", t8_q: "Wofür nutzt man GROUP BY?", t8_qa: "Um gleiche Werte zusammenzufassen", t8_qb: "Um Daten zu löschen", t8_qc: "Um Tabellen zu verbinden", t8_qd: "Um nach Alphabet zu sortieren",
    t8_w1: "Fasst", t8_w2: "gleiche", t8_w3: "Werte", t8_w4: "zusammen",
    t9_title: "JOIN (SQL)", t9_text: "Mit JOIN (z.B. INNER JOIN) verbindest du Daten aus zwei oder mehr Tabellen anhand eines Schlüssels.", t9_inst: "Sortiere in die Eimer:", t9_h1: "Verbinden oder Filtern?", t9_h2: "JOIN verbindet.", t9_q: "Was macht ein JOIN in SQL?", t9_qa: "Verbindet Tabellen", t9_qb: "Trennt Tabellen", t9_qc: "Löscht Tabellen", t9_qd: "Kopiert Tabellen",
    t9_bl1: "Verbinden", t9_bl2: "Filtern", t9_i1: "INNER JOIN", t9_i2: "WHERE", t9_i3: "ON (Bedingung)", t9_i4: "LIKE",
    t10_title: "COUNT()", t10_text: "COUNT() ist eine Funktion, die zählt, wie viele Datensätze gefunden wurden.", t10_inst: "Markiere das richtige Wort:", t10_h1: "Zählen von Zeilen.", t10_h2: "COUNT = zählen.", t10_q: "Was macht COUNT(*) in SQL?", t10_qa: "Zählt alle Zeilen", t10_qb: "Addiert alle Zahlen", t10_qc: "Sucht nach Text", t10_qd: "Löscht alle Zeilen",
    t10_tk1: "COUNT()", t10_tk2: "zählt", t10_tk3: "die", t10_tk4: "Datensätze.",
    t11_title: "SUM()", t11_text: "SUM() addiert die Werte einer Zahlenspalte (z.B. SUM(Preis) für den Gesamtpreis).", t11_inst: "Fülle die Lücke aus:", t11_h1: "Summe berechnen.", t11_h2: "SUM = Summe.", t11_q: "Welche Funktion berechnet die Gesamtsumme einer Spalte?", t11_qa: "SUM()", t11_qb: "COUNT()", t11_qc: "MAX()", t11_qd: "ADD()",
    t11_sent: "SELECT ___(Preis) FROM Bestellungen;", t11_c1: "SUM", t11_c2: "COUNT", t11_c3: "TOTAL", t11_c4: "ALL",
    t12_title: "LIKE (SQL)", t12_text: "Mit LIKE suchst du nach Textmustern. Das %-Zeichen steht für beliebige Zeichen (z.B. LIKE 'A%').", t12_inst: "Ordne die Paare zu:", t12_h1: "Mustererkennung.", t12_h2: "% ist ein Platzhalter.", t12_q: "Was findet WHERE Name LIKE 'M%'?", t12_qa: "Alle Namen, die mit M beginnen", t12_qb: "Alle Namen, die mit M enden", t12_qc: "Nur den Namen 'M'", t12_qd: "Alle Namen ohne M",
    t12_l1: "'A%'", t12_r1: "Beginnt mit A", t12_l2: "'%A'", t12_r2: "Endet mit A", t12_l3: "'%A%'", t12_r3: "Enthält A", t12_l4: "LIKE", t12_r4: "Muster-Suche",
    t13_title: "AND / OR", t13_text: "Mit AND und OR verknüpfst du mehrere Bedingungen im WHERE-Teil.", t13_inst: "Bringe die Wörter in Ordnung:", t13_h1: "Bedingungen verknüpfen.", t13_h2: "AND = beides, OR = eins.", t13_q: "Wann ist (Alter > 18 AND Stadt = 'Berlin') wahr?", t13_qa: "Wenn beides zutrifft", t13_qb: "Wenn nur das Alter stimmt", t13_qc: "Wenn nur die Stadt stimmt", t13_qd: "Wenn keines zutrifft",
    t13_w1: "AND", t13_w2: "verlangt", t13_w3: "beide", t13_w4: "Bedingungen",
    t14_title: "LIMIT", t14_text: "Mit LIMIT beschränkst du die Anzahl der angezeigten Ergebnisse (z.B. LIMIT 5 zeigt nur 5 Zeilen).", t14_inst: "Sortiere in die Eimer:", t14_h1: "Begrenzen oder Sortieren?", t14_h2: "LIMIT = Grenze.", t14_q: "Was macht LIMIT 10 in SQL?", t14_qa: "Zeigt maximal 10 Ergebnisse", t14_qb: "Löscht 10 Ergebnisse", t14_qc: "Sortiert 10 Ergebnisse", t14_qd: "Fügt 10 Ergebnisse hinzu",
    t14_bl1: "Begrenzen", t14_bl2: "Sortieren", t14_i1: "LIMIT 5", t14_i2: "ORDER BY", t14_i3: "Maximal 10", t14_i4: "ASC / DESC",
    t15_title: "CREATE TABLE", t15_text: "Mit CREATE TABLE erstellst du eine neue, leere Tabelle in der Datenbank.", t15_inst: "Markiere das richtige Wort:", t15_h1: "Tabelle erstellen.", t15_h2: "CREATE = erschaffen.", t15_q: "Welcher Befehl erstellt eine neue Tabelle?", t15_qa: "CREATE TABLE", t15_qb: "NEW TABLE", t15_qc: "ADD TABLE", t15_qd: "MAKE TABLE",
    t15_tk1: "CREATE", t15_tk2: "TABLE", t15_tk3: "erstellt", t15_tk4: "Tabellen."
  },
  en: {
    explorer_title: "Informatics Explorer K7-8",
    t1_title: "SELECT (SQL)", t1_text: "With SELECT you choose which columns of a table you want to see.", t1_inst: "Match the pairs:", t1_h1: "SELECT = choose.", t1_h2: "* means everything.", t1_q: "What does the SELECT command do in SQL?", t1_qa: "Selects columns", t1_qb: "Deletes data", t1_qc: "Creates a table", t1_qd: "Changes passwords",
    t1_l1: "SELECT", t1_r1: "Select columns", t1_l2: "*", t1_r2: "All columns", t1_l3: "SELECT Name", t1_r3: "Show only Name", t1_l4: "SQL", t1_r4: "Database language",
    t2_title: "FROM (SQL)", t2_text: "FROM specifies from which table the data should be fetched.", t2_inst: "Fill in the blank:", t2_h1: "SELECT ... FROM table.", t2_h2: "Where does the data come from?", t2_q: "What does FROM stand for in an SQL query?", t2_qa: "Specifies the table", t2_qb: "Specifies the column", t2_qc: "Sorts the data", t2_qd: "Deletes the table",
    t2_sent: "SELECT * ___ Customers;", t2_c1: "FROM", t2_c2: "IN", t2_c3: "TO", t2_c4: "AT",
    t3_title: "WHERE (SQL)", t3_text: "With WHERE you filter the data according to specific conditions (e.g. WHERE Age > 18).", t3_inst: "Sort into buckets:", t3_h1: "Condition or command?", t3_h2: "WHERE filters.", t3_q: "What does the WHERE clause do?", t3_qa: "Filters records by conditions", t3_qb: "Selects all data", t3_qc: "Deletes the database", t3_qd: "Creates a new column",
    t3_bl1: "Command", t3_bl2: "Condition", t3_i1: "SELECT", t3_i2: "Age > 18", t3_i3: "FROM", t3_i4: "Name = 'Anna'",
    t4_title: "INSERT INTO (SQL)", t4_text: "With INSERT INTO you add new records (rows) into a table.", t4_inst: "Put the words in order:", t4_h1: "Insert into table.", t4_h2: "INSERT INTO.", t4_q: "How do you insert new data in SQL?", t4_qa: "With INSERT INTO", t4_qb: "With ADD DATA", t4_qc: "With NEW ROW", t4_qd: "With CREATE",
    t4_w1: "INSERT", t4_w2: "INTO", t4_w3: "Customers", t4_w4: "VALUES",
    t5_title: "UPDATE (SQL)", t5_text: "With UPDATE you change existing data in a table. Important: don't forget WHERE!", t5_inst: "Highlight the correct word:", t5_h1: "Update data.", t5_h2: "UPDATE changes.", t5_q: "What happens if you forget WHERE in an UPDATE?", t5_qa: "All records are changed", t5_qb: "Nothing happens", t5_qc: "The table is deleted", t5_qd: "There is a syntax error",
    t5_tk1: "With", t5_tk2: "UPDATE", t5_tk3: "you change", t5_tk4: "data.",
    t6_title: "DELETE (SQL)", t6_text: "With DELETE you remove records from a table. Again: don't forget WHERE!", t6_inst: "Match the pairs:", t6_h1: "Deleting data.", t6_h2: "Careful with DELETE!", t6_q: "Which command deletes rows in SQL?", t6_qa: "DELETE", t6_qb: "REMOVE", t6_qc: "DROP", t6_qd: "CLEAR",
    t6_l1: "DELETE", t6_r1: "Delete rows", t6_l2: "UPDATE", t6_r2: "Change rows", t6_l3: "INSERT", t6_r3: "Add rows", t6_l4: "SELECT", t6_r4: "Read rows",
    t7_title: "ORDER BY (SQL)", t7_text: "With ORDER BY you sort the results (ASC for ascending, DESC for descending).", t7_inst: "Fill in the blank:", t7_h1: "Sort by...", t7_h2: "ORDER BY.", t7_q: "How do you sort results descending in SQL?", t7_qa: "ORDER BY column DESC", t7_qb: "ORDER BY column ASC", t7_qc: "SORT BY column DOWN", t7_qd: "ORDER DOWN",
    t7_sent: "SELECT * FROM Customers ___ Name;", t7_c1: "ORDER BY", t7_c2: "SORT BY", t7_c3: "GROUP BY", t7_c4: "FILTER BY",
    t8_title: "GROUP BY (SQL)", t8_text: "With GROUP BY you group rows with the same values, often used with COUNT or SUM.", t8_inst: "Put the words in order:", t8_h1: "Group by...", t8_h2: "GROUP BY.", t8_q: "What is GROUP BY used for?", t8_qa: "To group identical values", t8_qb: "To delete data", t8_qc: "To join tables", t8_qd: "To sort alphabetically",
    t8_w1: "Groups", t8_w2: "identical", t8_w3: "values", t8_w4: "together",
    t9_title: "JOIN (SQL)", t9_text: "With JOIN (e.g. INNER JOIN) you connect data from two or more tables using a key.", t9_inst: "Sort into buckets:", t9_h1: "Connect or filter?", t9_h2: "JOIN connects.", t9_q: "What does a JOIN do in SQL?", t9_qa: "Connects tables", t9_qb: "Separates tables", t9_qc: "Deletes tables", t9_qd: "Copies tables",
    t9_bl1: "Connect", t9_bl2: "Filter", t9_i1: "INNER JOIN", t9_i2: "WHERE", t9_i3: "ON (Condition)", t9_i4: "LIKE",
    t10_title: "COUNT()", t10_text: "COUNT() is a function that counts how many records were found.", t10_inst: "Highlight the correct word:", t10_h1: "Counting rows.", t10_h2: "COUNT = count.", t10_q: "What does COUNT(*) do in SQL?", t10_qa: "Counts all rows", t10_qb: "Adds all numbers", t10_qc: "Searches for text", t10_qd: "Deletes all rows",
    t10_tk1: "COUNT()", t10_tk2: "counts", t10_tk3: "the", t10_tk4: "records.",
    t11_title: "SUM()", t11_text: "SUM() adds the values of a number column (e.g. SUM(Price) for the total price).", t11_inst: "Fill in the blank:", t11_h1: "Calculate sum.", t11_h2: "SUM = sum.", t11_q: "Which function calculates the total sum of a column?", t11_qa: "SUM()", t11_qb: "COUNT()", t11_qc: "MAX()", t11_qd: "ADD()",
    t11_sent: "SELECT ___(Price) FROM Orders;", t11_c1: "SUM", t11_c2: "COUNT", t11_c3: "TOTAL", t11_c4: "ALL",
    t12_title: "LIKE (SQL)", t12_text: "With LIKE you search for text patterns. The % sign stands for any characters (e.g. LIKE 'A%').", t12_inst: "Match the pairs:", t12_h1: "Pattern recognition.", t12_h2: "% is a placeholder.", t12_q: "What does WHERE Name LIKE 'M%' find?", t12_qa: "All names starting with M", t12_qb: "All names ending with M", t12_qc: "Only the name 'M'", t12_qd: "All names without M",
    t12_l1: "'A%'", t12_r1: "Starts with A", t12_l2: "'%A'", t12_r2: "Ends with A", t12_l3: "'%A%'", t12_r3: "Contains A", t12_l4: "LIKE", t12_r4: "Pattern search",
    t13_title: "AND / OR", t13_text: "With AND and OR you combine multiple conditions in the WHERE part.", t13_inst: "Put the words in order:", t13_h1: "Combine conditions.", t13_h2: "AND = both, OR = one.", t13_q: "When is (Age > 18 AND City = 'Berlin') true?", t13_qa: "When both apply", t13_qb: "When only the age is right", t13_qc: "When only the city is right", t13_qd: "When neither applies",
    t13_w1: "AND", t13_w2: "requires", t13_w3: "both", t13_w4: "conditions",
    t14_title: "LIMIT", t14_text: "With LIMIT you restrict the number of displayed results (e.g. LIMIT 5 shows only 5 rows).", t14_inst: "Sort into buckets:", t14_h1: "Limit or sort?", t14_h2: "LIMIT = boundary.", t14_q: "What does LIMIT 10 do in SQL?", t14_qa: "Shows a maximum of 10 results", t14_qb: "Deletes 10 results", t14_qc: "Sorts 10 results", t14_qd: "Adds 10 results",
    t14_bl1: "Limit", t14_bl2: "Sort", t14_i1: "LIMIT 5", t14_i2: "ORDER BY", t14_i3: "Maximum 10", t14_i4: "ASC / DESC",
    t15_title: "CREATE TABLE", t15_text: "With CREATE TABLE you create a new, empty table in the database.", t15_inst: "Highlight the correct word:", t15_h1: "Create table.", t15_h2: "CREATE = make.", t15_q: "Which command creates a new table?", t15_qa: "CREATE TABLE", t15_qb: "NEW TABLE", t15_qc: "ADD TABLE", t15_qd: "MAKE TABLE",
    t15_tk1: "CREATE", t15_tk2: "TABLE", t15_tk3: "creates", t15_tk4: "tables."
  },
  hu: {
    explorer_title: "Informatika Felfedező K7-8",
    t1_title: "SELECT (SQL)", t1_text: "A SELECT paranccsal kiválasztod, hogy a tábla mely oszlopait szeretnéd látni.", t1_inst: "Párosítsd össze:", t1_h1: "SELECT = kiválasztás.", t1_h2: "A * mindent jelent.", t1_q: "Mit csinál a SELECT parancs az SQL-ben?", t1_qa: "Oszlopokat választ ki", t1_qb: "Adatokat töröl", t1_qc: "Táblát hoz létre", t1_qd: "Jelszavakat módosít",
    t1_l1: "SELECT", t1_r1: "Oszlopok kiválasztása", t1_l2: "*", t1_r2: "Minden oszlop", t1_l3: "SELECT Nev", t1_r3: "Csak a Név mutatása", t1_l4: "SQL", t1_r4: "Adatbázis nyelv",
    t2_title: "FROM (SQL)", t2_text: "A FROM megadja, hogy melyik táblából kell lekérni az adatokat.", t2_inst: "Töltsd ki a hiányt:", t2_h1: "SELECT ... FROM tábla.", t2_h2: "Honnan jönnek az adatok?", t2_q: "Mit jelent a FROM egy SQL lekérdezésben?", t2_qa: "Megadja a táblát", t2_qb: "Megadja az oszlopot", t2_qc: "Rendezi az adatokat", t2_qd: "Törli a táblát",
    t2_sent: "SELECT * ___ Ugyfelek;", t2_c1: "FROM", t2_c2: "IN", t2_c3: "TO", t2_c4: "AT",
    t3_title: "WHERE (SQL)", t3_text: "A WHERE paranccsal bizonyos feltételek alapján szűröd az adatokat (pl. WHERE Kor > 18).", t3_inst: "Válogasd szét:", t3_h1: "Feltétel vagy parancs?", t3_h2: "A WHERE szűr.", t3_q: "Mit csinál a WHERE záradék?", t3_qa: "Feltételek alapján szűri a rekordokat", t3_qb: "Kiválasztja az összes adatot", t3_qc: "Törli az adatbázist", t3_qd: "Új oszlopot hoz létre",
    t3_bl1: "Parancs", t3_bl2: "Feltétel", t3_i1: "SELECT", t3_i2: "Kor > 18", t3_i3: "FROM", t3_i4: "Nev = 'Anna'",
    t4_title: "INSERT INTO (SQL)", t4_text: "Az INSERT INTO paranccsal új rekordokat (sorokat) adhatsz egy táblához.", t4_inst: "Tedd sorrendbe a szavakat:", t4_h1: "Beszúrás a táblába.", t4_h2: "INSERT INTO.", t4_q: "Hogyan szúrunk be új adatokat SQL-ben?", t4_qa: "INSERT INTO paranccsal", t4_qb: "ADD DATA paranccsal", t4_qc: "NEW ROW paranccsal", t4_qd: "CREATE paranccsal",
    t4_w1: "INSERT", t4_w2: "INTO", t4_w3: "Ugyfelek", t4_w4: "VALUES",
    t5_title: "UPDATE (SQL)", t5_text: "Az UPDATE paranccsal meglévő adatokat módosíthatsz. Fontos: ne felejtsd el a WHERE-t!", t5_inst: "Jelöld meg a helyes szót:", t5_h1: "Adatok frissítése.", t5_h2: "Az UPDATE módosít.", t5_q: "Mi történik, ha kifelejted a WHERE-t egy UPDATE-ből?", t5_qa: "Minden rekord módosul", t5_qb: "Nem történik semmi", t5_qc: "A tábla törlődik", t5_qd: "Szintaktikai hiba lesz",
    t5_tk1: "Az", t5_tk2: "UPDATE", t5_tk3: "adatokat", t5_tk4: "módosít.",
    t6_title: "DELETE (SQL)", t6_text: "A DELETE paranccsal rekordokat törölhetsz egy táblából. Itt is: ne felejtsd el a WHERE-t!", t6_inst: "Párosítsd össze:", t6_h1: "Adatok törlése.", t6_h2: "Óvatosan a DELETE-tel!", t6_q: "Melyik parancs töröl sorokat SQL-ben?", t6_qa: "DELETE", t6_qb: "REMOVE", t6_qc: "DROP", t6_qd: "CLEAR",
    t6_l1: "DELETE", t6_r1: "Sorok törlése", t6_l2: "UPDATE", t6_r2: "Sorok módosítása", t6_l3: "INSERT", t6_r3: "Sorok hozzáadása", t6_l4: "SELECT", t6_r4: "Sorok olvasása",
    t7_title: "ORDER BY (SQL)", t7_text: "Az ORDER BY paranccsal rendezheted az eredményeket (ASC növekvő, DESC csökkenő).", t7_inst: "Töltsd ki a hiányt:", t7_h1: "Rendezés valami szerint...", t7_h2: "ORDER BY.", t7_q: "Hogyan rendezzük az eredményeket csökkenő sorrendbe SQL-ben?", t7_qa: "ORDER BY oszlop DESC", t7_qb: "ORDER BY oszlop ASC", t7_qc: "SORT BY oszlop DOWN", t7_qd: "ORDER DOWN",
    t7_sent: "SELECT * FROM Ugyfelek ___ Nev;", t7_c1: "ORDER BY", t7_c2: "SORT BY", t7_c3: "GROUP BY", t7_c4: "FILTER BY",
    t8_title: "GROUP BY (SQL)", t8_text: "A GROUP BY paranccsal az azonos értékű sorokat csoportosíthatod, gyakran COUNT vagy SUM mellett.", t8_inst: "Tedd sorrendbe a szavakat:", t8_h1: "Csoportosítás valami szerint...", t8_h2: "GROUP BY.", t8_q: "Mire használjuk a GROUP BY-t?", t8_qa: "Azonos értékek csoportosítására", t8_qb: "Adatok törlésére", t8_qc: "Táblák összekapcsolására", t8_qd: "Betűrendes sorba rendezésre",
    t8_w1: "Azonos", t8_w2: "értékeket", t8_w3: "fog", t8_w4: "össze",
    t9_title: "JOIN (SQL)", t9_text: "A JOIN (pl. INNER JOIN) segítségével két vagy több tábla adatait kapcsolhatod össze egy kulcs alapján.", t9_inst: "Válogasd szét:", t9_h1: "Összekapcsolás vagy szűrés?", t9_h2: "A JOIN összekapcsol.", t9_q: "Mit csinál a JOIN az SQL-ben?", t9_qa: "Táblákat kapcsol össze", t9_qb: "Táblákat választ szét", t9_qc: "Táblákat töröl", t9_qd: "Táblákat másol",
    t9_bl1: "Összekapcsolás", t9_bl2: "Szűrés", t9_i1: "INNER JOIN", t9_i2: "WHERE", t9_i3: "ON (Feltétel)", t9_i4: "LIKE",
    t10_title: "COUNT()", t10_text: "A COUNT() egy függvény, amely megszámolja, hány rekordot talált.", t10_inst: "Jelöld meg a helyes szót:", t10_h1: "Sorok számolása.", t10_h2: "COUNT = számolás.", t10_q: "Mit csinál a COUNT(*) az SQL-ben?", t10_qa: "Megszámolja az összes sort", t10_qb: "Összeadja a számokat", t10_qc: "Szöveget keres", t10_qd: "Törli az összes sort",
    t10_tk1: "A COUNT()", t10_tk2: "megszámolja", t10_tk3: "a", t10_tk4: "rekordokat.",
    t11_title: "SUM()", t11_text: "A SUM() összeadja egy számoszlop értékeit (pl. SUM(Ar) a végösszeghez).", t11_inst: "Töltsd ki a hiányt:", t11_h1: "Összeg számítása.", t11_h2: "SUM = összeg.", t11_q: "Melyik függvény számítja ki egy oszlop végösszegét?", t11_qa: "SUM()", t11_qb: "COUNT()", t11_qc: "MAX()", t11_qd: "ADD()",
    t11_sent: "SELECT ___(Ar) FROM Rendelesek;", t11_c1: "SUM", t11_c2: "COUNT", t11_c3: "TOTAL", t11_c4: "ALL",
    t12_title: "LIKE (SQL)", t12_text: "A LIKE paranccsal szövegmintákat kereshetsz. A % jel bármilyen karaktert helyettesít (pl. LIKE 'A%').", t12_inst: "Párosítsd össze:", t12_h1: "Minta felismerése.", t12_h2: "A % egy helykitöltő.", t12_q: "Mit talál meg a WHERE Nev LIKE 'M%'?", t12_qa: "Minden M-mel kezdődő nevet", t12_qb: "Minden M-re végződő nevet", t12_qc: "Csak az 'M' nevet", t12_qd: "Minden nevet M nélkül",
    t12_l1: "'A%'", t12_r1: "A-val kezdődik", t12_l2: "'%A'", t12_r2: "A-ra végződik", t12_l3: "'%A%'", t12_r3: "Tartalmazza az A-t", t12_l4: "LIKE", t12_r4: "Mintakeresés",
    t13_title: "AND / OR", t13_text: "Az AND és OR szavakkal több feltételt kapcsolhatsz össze a WHERE részben.", t13_inst: "Tedd sorrendbe a szavakat:", t13_h1: "Feltételek összekapcsolása.", t13_h2: "AND = mindkettő, OR = egyik.", t13_q: "Mikor igaz a (Kor > 18 AND Varos = 'Budapest')?", t13_qa: "Ha mindkettő teljesül", t13_qb: "Ha csak a kor stimmel", t13_qc: "Ha csak a város stimmel", t13_qd: "Ha egyik sem teljesül",
    t13_w1: "Az AND", t13_w2: "mindkét", t13_w3: "feltételt", t13_w4: "megköveteli",
    t14_title: "LIMIT", t14_text: "A LIMIT paranccsal korlátozhatod a megjelenített eredmények számát (pl. LIMIT 5 csak 5 sort mutat).", t14_inst: "Válogasd szét:", t14_h1: "Korlátozás vagy rendezés?", t14_h2: "LIMIT = határ.", t14_q: "Mit csinál a LIMIT 10 az SQL-ben?", t14_qa: "Maximum 10 eredményt mutat", t14_qb: "Töröl 10 eredményt", t14_qc: "Rendez 10 eredményt", t14_qd: "Hozzáad 10 eredményt",
    t14_bl1: "Korlátozás", t14_bl2: "Rendezés", t14_i1: "LIMIT 5", t14_i2: "ORDER BY", t14_i3: "Maximum 10", t14_i4: "ASC / DESC",
    t15_title: "CREATE TABLE", t15_text: "A CREATE TABLE paranccsal új, üres táblát hozhatsz létre az adatbázisban.", t15_inst: "Jelöld meg a helyes szót:", t15_h1: "Tábla létrehozása.", t15_h2: "CREATE = létrehoz.", t15_q: "Melyik parancs hoz létre új táblát?", t15_qa: "CREATE TABLE", t15_qb: "NEW TABLE", t15_qc: "ADD TABLE", t15_qd: "MAKE TABLE",
    t15_tk1: "A CREATE", t15_tk2: "TABLE", t15_tk3: "táblákat", t15_tk4: "hoz létre."
  },
  ro: {
    explorer_title: "Explorator Informatică K7-8",
    t1_title: "SELECT (SQL)", t1_text: "Cu SELECT alegi ce coloane ale unei tabele vrei să vezi.", t1_inst: "Potrivește perechile:", t1_h1: "SELECT = alege.", t1_h2: "* înseamnă totul.", t1_q: "Ce face comanda SELECT în SQL?", t1_qa: "Selectează coloane", t1_qb: "Șterge date", t1_qc: "Creează o tabelă", t1_qd: "Schimbă parole",
    t1_l1: "SELECT", t1_r1: "Selectează coloane", t1_l2: "*", t1_r2: "Toate coloanele", t1_l3: "SELECT Nume", t1_r3: "Arată doar Nume", t1_l4: "SQL", t1_r4: "Limbaj de baze de date",
    t2_title: "FROM (SQL)", t2_text: "FROM specifică din ce tabelă trebuie preluate datele.", t2_inst: "Completează spațiul liber:", t2_h1: "SELECT ... FROM tabelă.", t2_h2: "De unde vin datele?", t2_q: "Ce înseamnă FROM într-o interogare SQL?", t2_qa: "Specifică tabela", t2_qb: "Specifică coloana", t2_qc: "Sortează datele", t2_qd: "Șterge tabela",
    t2_sent: "SELECT * ___ Clienti;", t2_c1: "FROM", t2_c2: "IN", t2_c3: "TO", t2_c4: "AT",
    t3_title: "WHERE (SQL)", t3_text: "Cu WHERE filtrezi datele conform unor condiții specifice (de ex. WHERE Varsta > 18).", t3_inst: "Sortează în găleți:", t3_h1: "Condiție sau comandă?", t3_h2: "WHERE filtrează.", t3_q: "Ce face clauza WHERE?", t3_qa: "Filtrează înregistrările după condiții", t3_qb: "Selectează toate datele", t3_qc: "Șterge baza de date", t3_qd: "Creează o coloană nouă",
    t3_bl1: "Comandă", t3_bl2: "Condiție", t3_i1: "SELECT", t3_i2: "Varsta > 18", t3_i3: "FROM", t3_i4: "Nume = 'Anna'",
    t4_title: "INSERT INTO (SQL)", t4_text: "Cu INSERT INTO adaugi înregistrări noi (rânduri) într-o tabelă.", t4_inst: "Pune cuvintele în ordine:", t4_h1: "Inserează în tabelă.", t4_h2: "INSERT INTO.", t4_q: "Cum inserezi date noi în SQL?", t4_qa: "Cu INSERT INTO", t4_qb: "Cu ADD DATA", t4_qc: "Cu NEW ROW", t4_qd: "Cu CREATE",
    t4_w1: "INSERT", t4_w2: "INTO", t4_w3: "Clienti", t4_w4: "VALUES",
    t5_title: "UPDATE (SQL)", t5_text: "Cu UPDATE modifici datele existente într-o tabelă. Important: nu uita de WHERE!", t5_inst: "Evidențiază cuvântul corect:", t5_h1: "Actualizează date.", t5_h2: "UPDATE modifică.", t5_q: "Ce se întâmplă dacă uiți WHERE într-un UPDATE?", t5_qa: "Toate înregistrările sunt modificate", t5_qb: "Nu se întâmplă nimic", t5_qc: "Tabela este ștearsă", t5_qd: "Apare o eroare de sintaxă",
    t5_tk1: "Cu", t5_tk2: "UPDATE", t5_tk3: "modifici", t5_tk4: "datele.",
    t6_title: "DELETE (SQL)", t6_text: "Cu DELETE ștergi înregistrări dintr-o tabelă. Din nou: nu uita de WHERE!", t6_inst: "Potrivește perechile:", t6_h1: "Ștergerea datelor.", t6_h2: "Atenție cu DELETE!", t6_q: "Care comandă șterge rânduri în SQL?", t6_qa: "DELETE", t6_qb: "REMOVE", t6_qc: "DROP", t6_qd: "CLEAR",
    t6_l1: "DELETE", t6_r1: "Șterge rânduri", t6_l2: "UPDATE", t6_r2: "Modifică rânduri", t6_l3: "INSERT", t6_r3: "Adaugă rânduri", t6_l4: "SELECT", t6_r4: "Citește rânduri",
    t7_title: "ORDER BY (SQL)", t7_text: "Cu ORDER BY sortezi rezultatele (ASC pentru crescător, DESC pentru descrescător).", t7_inst: "Completează spațiul liber:", t7_h1: "Sortează după...", t7_h2: "ORDER BY.", t7_q: "Cum sortezi rezultatele descrescător în SQL?", t7_qa: "ORDER BY coloana DESC", t7_qb: "ORDER BY coloana ASC", t7_qc: "SORT BY coloana DOWN", t7_qd: "ORDER DOWN",
    t7_sent: "SELECT * FROM Clienti ___ Nume;", t7_c1: "ORDER BY", t7_c2: "SORT BY", t7_c3: "GROUP BY", t7_c4: "FILTER BY",
    t8_title: "GROUP BY (SQL)", t8_text: "Cu GROUP BY grupezi rândurile cu aceleași valori, adesea folosit cu COUNT sau SUM.", t8_inst: "Pune cuvintele în ordine:", t8_h1: "Grupează după...", t8_h2: "GROUP BY.", t8_q: "Pentru ce este folosit GROUP BY?", t8_qa: "Pentru a grupa valori identice", t8_qb: "Pentru a șterge date", t8_qc: "Pentru a uni tabele", t8_qd: "Pentru a sorta alfabetic",
    t8_w1: "Grupează", t8_w2: "valorile", t8_w3: "identice", t8_w4: "împreună",
    t9_title: "JOIN (SQL)", t9_text: "Cu JOIN (de ex. INNER JOIN) conectezi date din două sau mai multe tabele folosind o cheie.", t9_inst: "Sortează în găleți:", t9_h1: "Conectează sau filtrează?", t9_h2: "JOIN conectează.", t9_q: "Ce face un JOIN în SQL?", t9_qa: "Conectează tabele", t9_qb: "Separă tabele", t9_qc: "Șterge tabele", t9_qd: "Copiază tabele",
    t9_bl1: "Conectează", t9_bl2: "Filtrează", t9_i1: "INNER JOIN", t9_i2: "WHERE", t9_i3: "ON (Condiție)", t9_i4: "LIKE",
    t10_title: "COUNT()", t10_text: "COUNT() este o funcție care numără câte înregistrări au fost găsite.", t10_inst: "Evidențiază cuvântul corect:", t10_h1: "Numărarea rândurilor.", t10_h2: "COUNT = numără.", t10_q: "Ce face COUNT(*) în SQL?", t10_qa: "Numără toate rândurile", t10_qb: "Adună toate numerele", t10_qc: "Caută text", t10_qd: "Șterge toate rândurile",
    t10_tk1: "COUNT()", t10_tk2: "numără", t10_tk3: "toate", t10_tk4: "înregistrările.",
    t11_title: "SUM()", t11_text: "SUM() adună valorile unei coloane de numere (de ex. SUM(Pret) pentru prețul total).", t11_inst: "Completează spațiul liber:", t11_h1: "Calculează suma.", t11_h2: "SUM = sumă.", t11_q: "Care funcție calculează suma totală a unei coloane?", t11_qa: "SUM()", t11_qb: "COUNT()", t11_qc: "MAX()", t11_qd: "ADD()",
    t11_sent: "SELECT ___(Pret) FROM Comenzi;", t11_c1: "SUM", t11_c2: "COUNT", t11_c3: "TOTAL", t11_c4: "ALL",
    t12_title: "LIKE (SQL)", t12_text: "Cu LIKE cauți modele de text. Semnul % reprezintă orice caractere (de ex. LIKE 'A%').", t12_inst: "Potrivește perechile:", t12_h1: "Recunoașterea modelelor.", t12_h2: "% este un substituent.", t12_q: "Ce găsește WHERE Nume LIKE 'M%'?", t12_qa: "Toate numele care încep cu M", t12_qb: "Toate numele care se termină cu M", t12_qc: "Doar numele 'M'", t12_qd: "Toate numele fără M",
    t12_l1: "'A%'", t12_r1: "Începe cu A", t12_l2: "'%A'", t12_r2: "Se termină cu A", t12_l3: "'%A%'", t12_r3: "Conține A", t12_l4: "LIKE", t12_r4: "Căutare model",
    t13_title: "AND / OR", t13_text: "Cu AND și OR combini mai multe condiții în partea WHERE.", t13_inst: "Pune cuvintele în ordine:", t13_h1: "Combină condiții.", t13_h2: "AND = ambele, OR = una.", t13_q: "Când este (Varsta > 18 AND Oras = 'Bucuresti') adevărat?", t13_qa: "Când ambele se aplică", t13_qb: "Când doar vârsta este corectă", t13_qc: "Când doar orașul este corect", t13_qd: "Când niciuna nu se aplică",
    t13_w1: "AND", t13_w2: "necesită", t13_w3: "ambele", t13_w4: "condiții",
    t14_title: "LIMIT", t14_text: "Cu LIMIT restricționezi numărul de rezultate afișate (de ex. LIMIT 5 arată doar 5 rânduri).", t14_inst: "Sortează în găleți:", t14_h1: "Limitează sau sortează?", t14_h2: "LIMIT = limită.", t14_q: "Ce face LIMIT 10 în SQL?", t14_qa: "Arată maxim 10 rezultate", t14_qb: "Șterge 10 rezultate", t14_qc: "Sortează 10 rezultate", t14_qd: "Adaugă 10 rezultate",
    t14_bl1: "Limitează", t14_bl2: "Sortează", t14_i1: "LIMIT 5", t14_i2: "ORDER BY", t14_i3: "Maxim 10", t14_i4: "ASC / DESC",
    t15_title: "CREATE TABLE", t15_text: "Cu CREATE TABLE creezi o tabelă nouă, goală, în baza de date.", t15_inst: "Evidențiază cuvântul corect:", t15_h1: "Creează tabelă.", t15_h2: "CREATE = a crea.", t15_q: "Care comandă creează o tabelă nouă?", t15_qa: "CREATE TABLE", t15_qb: "NEW TABLE", t15_qc: "ADD TABLE", t15_qd: "MAKE TABLE",
    t15_tk1: "CREATE", t15_tk2: "TABLE", t15_tk3: "creează", t15_tk4: "tabele."
  }
};

export const INFO_K7_I8_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🔍", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "match-pairs", instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2", pairs: [{left:"t1_l1",right:"t1_r1"},{left:"t1_l2",right:"t1_r2"},{left:"t1_l3",right:"t1_r3"},{left:"t1_l4",right:"t1_r4"}] },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "📂", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "gap-fill", instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2", sentence: "t2_sent", choices: ["t2_c1", "t2_c2", "t2_c3", "t2_c4"], correctIndex: 0 },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🎯", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "drag-to-bucket", instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2", buckets: [{id:"b1",label:"t3_bl1"},{id:"b2",label:"t3_bl2"}], items: [{text:"t3_i1",bucketId:"b1"},{text:"t3_i2",bucketId:"b2"},{text:"t3_i3",bucketId:"b1"},{text:"t3_i4",bucketId:"b2"}] },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "➕", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "physics-stacker", instruction: "t4_inst", hint1: "t4_h1", hint2: "t4_h2", words: ["t4_w1", "t4_w2", "t4_w3", "t4_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "✏️", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t5_inst", hint1: "t5_h1", hint2: "t5_h2", tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4"], correctIndices: [1] },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t6_title", infoText: "t6_text",
    svg: { type: "simple-icon", icon: "🗑️", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "match-pairs", instruction: "t6_inst", hint1: "t6_h1", hint2: "t6_h2", pairs: [{left:"t6_l1",right:"t6_r1"},{left:"t6_l2",right:"t6_r2"},{left:"t6_l3",right:"t6_r3"},{left:"t6_l4",right:"t6_r4"}] },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title", infoText: "t7_text",
    svg: { type: "simple-icon", icon: "⬇️", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "gap-fill", instruction: "t7_inst", hint1: "t7_h1", hint2: "t7_h2", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3", "t7_c4"], correctIndex: 0 },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title", infoText: "t8_text",
    svg: { type: "simple-icon", icon: "👥", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "physics-stacker", instruction: "t8_inst", hint1: "t8_h1", hint2: "t8_h2", words: ["t8_w1", "t8_w2", "t8_w3", "t8_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t9_title", infoText: "t9_text",
    svg: { type: "simple-icon", icon: "🔗", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "drag-to-bucket", instruction: "t9_inst", hint1: "t9_h1", hint2: "t9_h2", buckets: [{id:"b1",label:"t9_bl1"},{id:"b2",label:"t9_bl2"}], items: [{text:"t9_i1",bucketId:"b1"},{text:"t9_i2",bucketId:"b2"},{text:"t9_i3",bucketId:"b1"},{text:"t9_i4",bucketId:"b2"}] },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t10_title", infoText: "t10_text",
    svg: { type: "simple-icon", icon: "🔢", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t10_inst", hint1: "t10_h1", hint2: "t10_h2", tokens: ["t10_tk1", "t10_tk2", "t10_tk3", "t10_tk4"], correctIndices: [0] },
    quiz: { question: "t10_q", choices: ["t10_qa", "t10_qb", "t10_qc", "t10_qd"], answer: "t10_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t11_title", infoText: "t11_text",
    svg: { type: "simple-icon", icon: "➕", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "gap-fill", instruction: "t11_inst", hint1: "t11_h1", hint2: "t11_h2", sentence: "t11_sent", choices: ["t11_c1", "t11_c2", "t11_c3", "t11_c4"], correctIndex: 0 },
    quiz: { question: "t11_q", choices: ["t11_qa", "t11_qb", "t11_qc", "t11_qd"], answer: "t11_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t12_title", infoText: "t12_text",
    svg: { type: "simple-icon", icon: "🎭", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "match-pairs", instruction: "t12_inst", hint1: "t12_h1", hint2: "t12_h2", pairs: [{left:"t12_l1",right:"t12_r1"},{left:"t12_l2",right:"t12_r2"},{left:"t12_l3",right:"t12_r3"},{left:"t12_l4",right:"t12_r4"}] },
    quiz: { question: "t12_q", choices: ["t12_qa", "t12_qb", "t12_qc", "t12_qd"], answer: "t12_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t13_title", infoText: "t13_text",
    svg: { type: "simple-icon", icon: "⚖️", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "physics-stacker", instruction: "t13_inst", hint1: "t13_h1", hint2: "t13_h2", words: ["t13_w1", "t13_w2", "t13_w3", "t13_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t13_q", choices: ["t13_qa", "t13_qb", "t13_qc", "t13_qd"], answer: "t13_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t14_title", infoText: "t14_text",
    svg: { type: "simple-icon", icon: "🚧", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "drag-to-bucket", instruction: "t14_inst", hint1: "t14_h1", hint2: "t14_h2", buckets: [{id:"b1",label:"t14_bl1"},{id:"b2",label:"t14_bl2"}], items: [{text:"t14_i1",bucketId:"b1"},{text:"t14_i2",bucketId:"b2"},{text:"t14_i3",bucketId:"b1"},{text:"t14_i4",bucketId:"b2"}] },
    quiz: { question: "t14_q", choices: ["t14_qa", "t14_qb", "t14_qc", "t14_qd"], answer: "t14_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t15_title", infoText: "t15_text",
    svg: { type: "simple-icon", icon: "🏗️", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t15_inst", hint1: "t15_h1", hint2: "t15_h2", tokens: ["t15_tk1", "t15_tk2", "t15_tk3", "t15_tk4"], correctIndices: [0] },
    quiz: { question: "t15_q", choices: ["t15_qa", "t15_qb", "t15_qc", "t15_qd"], answer: "t15_qa" }
  }
];
