// @ts-nocheck
// lib/explorerPools/informatikaK7_i2.ts
import type { PoolTopicDef } from "./types";

export const INFO_K7_I2_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Hardware & Daten Labor",
    t16_title: "Binärsystem", t16_text: "Computer nutzen das Binärsystem mit nur zwei Ziffern: 0 und 1. Diese heißen 'Bits'.", t16_inst: "Welche dieser Zahlen ist binär geschrieben?", t16_h1: "Binär nutzt nur 0 und 1.", t16_h2: "Wenn du eine 2, 3 oder andere Ziffer siehst, ist es nicht binär.", t16_q: "Binary Check:", t16_t1: "10110", t16_t2: "10210", t16_t3: "12345", t16_t4: "88", t16_quiz_q: "Wie viele Ziffern hat das Binärsystem?", t16_qa: "2", t16_qb: "1", t16_qc: "10", t16_qd: "16",
    t17_title: "Hexadezimal", t17_text: "Das Hexadezimalsystem nutzt 16 Symbole (0-9 und A-F). Es wird oft für Farben auf Webseiten genutzt.", t17_inst: "Vervollständige die Hexadezimal-Folge.", t17_h1: "Nach 9 folgen die Symbole A, B, C, D, E, F.", t17_h2: "'C' steht für die Dezimalzahl 12.", t17_sent: "9, A, B, ___ , D, E, F", t17_c1: "C", t17_c2: "10", t17_c3: "X", t17_c4: "G", t17_quiz_q: "Welcher Buchstabe steht für 10 in Hexadezimal?", t17_qa: "A", t17_qb: "B", t17_qc: "C", t17_qd: "F",
    t18_title: "Umrechnung", t18_text: "Das Umrechnen von Zahlen zwischen Systemen (binär zu dezimal) hilft Computern und Menschen, sich zu verstehen.", t18_inst: "Ordne die Binärzahl ihrem Dezimalwert zu.", t18_h1: "0001 ist 1.", t18_h2: "1010 ist 10.", t18_l1: "0001", t18_r1: "1", t18_l2: "0010", t18_r2: "2", t18_l3: "0100", t18_r3: "4", t18_l4: "1000", t18_r4: "8", t18_q: "Was ist der Dezimalwert von binär '11'?", t18_qa: "3", t18_qb: "2", t18_qc: "4", t18_qd: "1",
    t19_title: "CPU-Funktionsweise", t19_text: "Die CPU ist das Gehirn des Computers. Sie macht drei Schritte: Abrufen (Fetch), Dekodieren (Decode) und Ausführen (Execute).", t19_inst: "Bringe den CPU-Befehlszyklus in die richtige Reihenfolge.", t19_h1: "Zuerst holt die CPU den Befehl (Fetch).", t19_h2: "Zuletzt führt die CPU die Aufgabe aus (Execute).", t19_w1: "Fetch (Befehl holen)", t19_w2: "Decode (Verstehen)", t19_w3: "Execute (Ausführen)", t19_q: "Welcher Teil des Computers ist das 'Gehirn'?", t19_qa: "CPU", t19_qb: "RAM", t19_qc: "Monitor", t19_qd: "Tastatur",
    t20_title: "RAM & ROM", t20_text: "RAM ist temporärer Speicher (gelöscht beim Ausschalten). ROM ist permanenter Speicher (behält Daten wie Start-Anweisungen).", t20_inst: "Sortiere die Eigenschaften: RAM oder ROM.", t20_h1: "RAM wird beim Neustart geleert.", t20_h2: "ROM enthält die BIOS-Startbefehle.", t20_b1: "RAM", t20_b2: "ROM", t20_i1: "Temporärer Speicher", t20_i2: "Schnellerer Zugriff", t20_i3: "Permanenter Speicher", t20_i4: "Nur Lese-Zugriff", t20_q: "Was passiert mit dem RAM, wenn der Strom ausgeht?", t20_qa: "Er wird geleert", t20_qb: "Nichts", t20_qc: "Es explodiert", t20_qd: "Es speichert alles",
    t21_title: "GPU", t21_text: "Die GPU (Grafikprozessor) ist spezialisiert auf das Rendern von Bildern und Videos durch viele gleichzeitige Aufgaben.", t21_inst: "Vervollständige den Satz zur GPU-Nutzung.", t21_h1: "GPUs sind wichtig für moderne Spiele.", t21_h2: "Sie verarbeitet hochauflösende Grafiken.", t21_sent: "Die GPU wird meist für das Rendern von ___ genutzt.", t21_c1: "Grafik", t21_c2: "Sound", t21_c3: "Tastatur", t21_c4: "Drucker", t21_q: "Kann eine GPU viele Dinge gleichzeitig tun?", t21_qa: "Ja", t21_qb: "Nein", t21_qc: "Nur im Wasser", t21_qd: "Manchmal",
    t22_title: "Betriebssysteme (BS)", t22_text: "Das Betriebssystem (BS) verwaltet Software und Hardware. Beispiele sind Windows, macOS und Linux.", t22_inst: "Ordne den Teil des BS seiner Funktion zu.", t22_h1: "Der Kernel ist der Kern des BS.", t22_h2: "Die GUI ist das, was Nutzer sehen und klicken.", t22_l1: "Kernel", t22_r1: "Kern-Funktionen", t22_l2: "GUI", t22_r2: "Visuelle Oberfläche", t22_l3: "Treiber", t22_r3: "Steuert Hardware", t22_l4: "Dateisystem", t22_r4: "Organisiert Daten", t22_q: "Ist Linux ein Betriebssystem?", t22_qa: "Ja", t22_qb: "Nein", t22_qc: "Nur auf Macs", t22_qd: "Es ist Hardware",
    t23_title: "Prozesse & Threads", t23_text: "Ein Prozess ist ein laufendes Programm. Ein Thread ist ein kleiner Teil eines Prozesses, der unabhängig laufen kann.", t23_inst: "Was ist ein Teil eines Prozesses?", t23_h1: "Ein Prozess kann viele Threads haben.", t23_h2: "Threads helfen dem Computer, schneller zu arbeiten.", t23_q: "Finde den kleineren Teil:", t23_t1: "Thread", t23_t2: "Hauptprogramm", t23_t3: "Festplatte", t23_t4: "USB", t23_quiz_q: "Kann ein Prozess mehrere Threads haben?", t23_qa: "Ja", t23_qb: "Nein", t23_qc: "Nur in Linux", t23_qd: "Vielleicht",
    t24_title: "Virtualisierung", t24_text: "Virtualisierung erlaubt es, mehrere virtuelle Computer (VMs) gleichzeitig auf einem echten zu nutzen.", t24_inst: "Vervollständige den Satz über virtuelle Maschinen.", t24_h1: "Eine VM verhält sich wie ein echter Computer.", t24_h2: "Sie nutzt Software, um Hardware zu simulieren.", t24_sent: "Linux unter Windows laufen zu lassen, nutzt eine ___ Maschine.", t24_c1: "virtuelle", t24_c2: "schwere", t24_c3: "kaputte", t24_c4: "fliegende", t24_q: "Warum nutzt man Virtualisierung?", t24_qa: "Viele BS nutzen", t24_qb: "Strom sparen", t24_qc: "Weil es blau ist", t24_qd: "Keines",
    t25_title: "SQL-Grundlagen", t25_text: "SQL ist eine Sprache für Datenbanken. Man kann Daten wählen (SELECT), einfügen (INSERT) oder löschen (DELETE).", t25_inst: "Vervollständige die SQL-Abfrage, um alle Nutzer zu laden.", t25_h1: "SELECT wird genutzt, um Daten zu wählen.", t25_h2: "FROM gibt den Tabellennamen an.", t25_sent: "SELECT * ___ users", t25_c1: "FROM", t25_c2: "IN", t25_c3: "WITH", t25_c4: "GET", t25_q: "Welcher SQL-Befehl fügt neue Daten hinzu?", t25_qa: "INSERT", t25_qb: "SELECT", t25_qc: "DELETE", t25_qd: "UPDATE",
    t26_title: "Tabellen & Datensätze", t26_text: "Daten liegen in Tabellen. Jede Zeile ist ein Datensatz, jede Spalte ein Feld (wie Name oder Alter).", t26_inst: "Ordne den Datenbank-Begriff seiner Rolle zu.", t26_h1: "Eine Zeile steht für ein einzelnes Element (z.B. Nutzer).", t26_h2: "Ein Primary Key identifiziert jede Zeile eindeutig.", t26_l1: "Zeile", t26_r1: "Ein Datensatz", t26_l2: "Spalte", t26_r2: "Datenkategorie", t26_l3: "Primary Key", t26_r3: "Eindeutige ID", t26_l4: "Tabelle", t26_r4: "Datensammlung", t26_q: "Wie nennt man eine einzelne Zeile in einer Tabelle?", t26_qa: "Datensatz", t26_qb: "Feld", t26_qc: "Tabelle", t26_qd: "Abfrage",
    t27_title: "Datenbeziehungen", t27_text: "Tabellen können verknüpft sein. Zum Beispiel ist eine 'Bestellungen'-Tabelle mit einer 'Nutzer'-Tabelle über eine User-ID verknüpft.", t27_inst: "Wie verknüpfen wir zwei Tabellen?", t27_h1: "Nutze eine gemeinsame ID in beiden Tabellen.", t27_h2: "Das nennt man Foreign Key (Fremdschlüssel).", t27_q: "Was verbindet Tabellen?", t27_t1: "Foreign Key", t27_t2: "Tabellenfarbe", t27_t3: "Maus", t27_t4: "Bildschirm", t27_quiz_q: "Hilft ein 'Foreign Key' beim Verknüpfen?", t27_qa: "Ja", t27_qb: "Nein", t27_qc: "Nur in Excel", t27_qd: "Vielleicht",
    t28_title: "Protokolle", t28_text: "Protokolle sind Kommunikationsregeln. HTTP ist für Webseiten, SMTP für E-Mails.", t28_inst: "Ordne das Protokoll seiner Aufgabe zu.", t28_h1: "HTTP/HTTPS ist zum Surfen im Web.", t28_h2: "IP kümmert sich um die Adressierung von Geräten.", t28_l1: "HTTP", t28_r1: "Webseiten", t28_l2: "SMTP", t28_r2: "E-Mail-Versand", t28_l3: "FTP", t28_r3: "Dateiübertragung", t28_l4: "IP", t28_r4: "Geräte-Adressierung", t28_q: "Welches Protokoll wird für sichere Webseiten genutzt?", t28_qa: "HTTPS", t28_qb: "HTTP", t28_qc: "FTP", t28_qd: "SMTP",
    t29_title: "Cybersicherheit", t29_text: "Cybersicherheit schützt Systeme vor Angriffen. Nutze starke Passwörter und sei vorsichtig mit unbekannten Links.", t29_inst: "Sortiere die Verhaltensweisen: Sicher oder Unsicher.", t29_h1: "Passwörter regelmäßig zu ändern ist sicher.", t29_h2: "Auf zufällige Pop-up-Werbung zu klicken ist unsicher.", t29_b1: "Sicher", t29_b2: "Unsicher", t29_i1: "Komplexe Passwörter", t29_i2: "Zwei-Faktor-Login", t29_i3: "Passwörter teilen", t29_i4: "Seltsame Links öffnen", t29_q: "Solltest du überall dasselbe Passwort nutzen?", t29_qa: "Nein", t29_qb: "Ja", t29_qc: "Nur wenn kurz", t29_qd: "Vielleicht",
    t30_title: "Verschlüsselung", t30_text: "Verschlüsselung macht Daten unleserlich für Unbefugte. Es ist der Schlüssel zur Privatsphäre online.", t30_inst: "Vervollständige den Satz über Verschlüsselung.", t30_h1: "Der Originaltext heißt 'Klartext'.", t30_h2: "Verschlüsselung macht daraus 'Geheimtext'.", t30_sent: "Verschlüsselung wandelt lesbaren Text in ___ Text um.", t30_c1: "Geheimtext", t30_c2: "leichten", t30_c3: "hellen", t30_c4: "kaputten", t30_q: "Welcher Code ist eine einfache historische Verschlüsselung?", t30_qa: "Caesar-Code", t30_qb: "Binär-Code", t30_qc: "HTML", t30_qd: "SQL"
  },
  en: {
    explorer_title: "Hardware & Data Lab",
    t16_title: "Binary System", t16_text: "Computers use the binary system, which only has two digits: 0 and 1. These are called 'bits'.", t16_inst: "Which of these numbers is written in binary?", t16_h1: "Binary only uses 0 and 1.", t16_h2: "If you see a 2, 3, or any other digit, it's not binary.", t16_q: "Binary Check:", t16_t1: "10110", t16_t2: "10210", t16_t3: "12345", t16_t4: "88", t16_quiz_q: "How many digits are in the binary system?", t16_qa: "2", t16_qb: "1", t16_qc: "10", t16_qd: "16",
    t17_title: "Hexadecimal", t17_text: "The hexadecimal system uses 16 symbols (0-9 and A-F). It is often used for colors on websites.", t17_inst: "Complete the hexadecimal sequence.", t17_h1: "After 9, the symbols are A, B, C, D, E, F.", t17_h2: "'C' represents the decimal number 12.", t17_sent: "9, A, B, ___ , D, E, F", t17_c1: "C", t17_c2: "10", t17_c3: "X", t17_c4: "G", t17_quiz_q: "Which letter represents 10 in hexadecimal?", t17_qa: "A", t17_qb: "B", t17_qc: "C", t17_qd: "F",
    t18_title: "Conversion", t18_text: "Converting numbers between systems (binary to decimal) helps computers and humans understand each other.", t18_inst: "Match the binary number with its decimal value.", t18_h1: "0001 is 1.", t18_h2: "1010 is 10.", t18_l1: "0001", t18_r1: "1", t18_l2: "0010", t18_r2: "2", t18_l3: "0100", t18_r3: "4", t18_l4: "1000", t18_r4: "8", t18_q: "What is the decimal value of binary '11'?", t18_qa: "3", t18_qb: "2", t18_qc: "4", t18_qd: "1",
    t19_title: "CPU Functioning", t19_text: "The Central Processing Unit (CPU) is the brain of the computer. It follows three steps: Fetch, Decode, and Execute.", t19_inst: "Put the CPU instruction cycle in order.", t19_h1: "First, the CPU gets the instruction (Fetch).", t19_h2: "Last, the CPU carries out the task (Execute).", t19_w1: "Fetch (Get data)", t19_w2: "Decode (Understand)", t19_w3: "Execute (Do task)", t19_q: "Which part of the computer is the 'brain'?", t19_qa: "CPU", t19_qb: "RAM", t19_qc: "Monitor", t19_qd: "Keyboard",
    t20_title: "RAM & ROM", t20_text: "RAM is temporary storage (deleted when off). ROM is permanent storage (keeps data like start-up instructions).", t20_inst: "Sort the characteristics: RAM or ROM.", t20_h1: "RAM is cleared when you restart.", t20_h2: "ROM contains the BIOS start instructions.", t20_b1: "RAM", t20_b2: "ROM", t20_i1: "Temporary memory", t20_i2: "Faster access", t20_i3: "Permanent storage", t20_i4: "Read-Only", t20_q: "What happens to RAM when the power goes off?", t20_qa: "It is cleared", t20_qb: "Nothing", t20_qc: "It explodes", t20_qd: "It saves everything",
    t21_title: "GPU", t21_text: "The Graphics Processing Unit (GPU) is specialized for rendering images and video by doing many small tasks at once.", t21_inst: "Complete the sentence about GPU use.", t21_h1: "GPU is essential for modern games.", t21_h2: "It handles high-resolution graphics.", t21_sent: "The GPU is mainly used for ___ rendering.", t21_c1: "graphics", t21_c2: "sound", t21_c3: "keyboard", t21_c4: "printer", t21_q: "Can a GPU do many things at once?", t21_qa: "Yes", t21_qb: "No", t21_qc: "Only in water", t21_qd: "Sometimes",
    t22_title: "OS In-depth", t22_text: "The Operating System (OS) manages software and hardware. Examples are Windows, macOS, and Linux.", t22_inst: "Match the OS part with its function.", t22_h1: "The Kernel is the core of the OS.", t22_h2: "The GUI is what users see and click.", t22_l1: "Kernel", t22_r1: "core functions", t22_l2: "GUI", t22_r2: "visual interface", t22_l3: "Driver", t22_r3: "controls hardware", t22_l4: "File System", t22_r4: "organizes data", t22_q: "Is Linux an Operating System?", t22_qa: "Yes", t22_qb: "No", t22_qc: "Only on Macs", t22_qd: "It's hardware",
    t23_title: "Processes & Threads", t23_text: "A process is a running program. A thread is a smaller part of a process that can run independently.", t23_inst: "Which one is a part of a process?", t23_h1: "One process can have many threads.", t23_h2: "Threads help the computer do things faster.", t23_q: "Find the smaller part:", t23_t1: "Thread", t23_t2: "Main Program", t23_t3: "Hard Drive", t23_t4: "USB", t23_quiz_q: "Can one process have multiple threads?", t23_qa: "Yes", t23_qb: "No", t23_qc: "Only in Linux", t23_qd: "Maybe",
    t24_title: "Virtualization", t24_text: "Virtualization allows one physical computer to run multiple virtual computers (VMs) at the same time.", t24_inst: "Complete the sentence about Virtual Machines.", t24_h1: "A VM behaves like a real computer.", t24_h2: "It uses software to simulate hardware.", t24_sent: "Running Linux inside Windows is done using a ___ machine.", t24_c1: "virtual", t24_c2: "heavy", t24_c3: "broken", t24_c4: "flying", t24_q: "Why use virtualization?", t24_qa: "Run many OS", t24_qb: "Save power", t24_qc: "Because it's blue", t24_qd: "None",
    t25_title: "SQL Basics", t25_text: "SQL is a language used to talk to databases. You can SELECT data, INSERT new items, or DELETE them.", t25_inst: "Complete the SQL query to get all users.", t25_h1: "SELECT is used to pick data.", t25_h2: "FROM specifies the table name.", t25_sent: "SELECT * ___ users", t25_c1: "FROM", t25_c2: "IN", t25_c3: "WITH", t25_c4: "GET", t25_q: "Which SQL command adds new data?", t25_qa: "INSERT", t25_qb: "SELECT", t25_qc: "DELETE", t25_qd: "UPDATE",
    t26_title: "Tables & Records", t26_text: "Data is stored in Tables. Each row is a Record, and each column is a Field (like Name or Age).", t26_inst: "Match the database term with its role.", t26_h1: "A Row represents one single item (like a user).", t26_h2: "A Primary Key uniquely identifies each row.", t26_l1: "Row", t26_r1: "One record", t26_l2: "Column", t26_r2: "Data category", t26_l3: "Primary Key", t26_r3: "Unique ID", t26_l4: "Table", t26_r4: "Collection of data", t26_q: "What is a single row in a table called?", t26_qa: "Record", t26_qb: "Field", t26_qc: "Table", t26_qd: "Query",
    t27_title: "Data Relations", t27_text: "Tables can be linked. For example, an 'Orders' table is linked to a 'Users' table by a User ID.", t27_inst: "How do we link two tables?", t27_h1: "Use a common ID in both tables.", t27_h2: "This is called a Foreign Key.", t27_q: "Which connects tables?", t27_t1: "Foreign Key", t27_t2: "Color of table", t27_t3: "Mouse", t27_t4: "Screen", t27_quiz_q: "Does a 'Foreign Key' help link tables?", t27_qa: "Yes", t27_qb: "No", t27_qc: "Only in Excel", t27_qd: "Maybe",
    t28_title: "Protocols", t28_text: "Protocols are rules for communication. HTTP is for websites, and SMTP is for sending emails.", t28_inst: "Match the protocol with its job.", t28_h1: "HTTP/HTTPS is for web browsing.", t28_h2: "IP handles the addressing of devices.", t28_l1: "HTTP", t28_r1: "Websites", t28_l2: "SMTP", t28_r2: "Email sending", t28_l3: "FTP", t28_r3: "File transfer", t28_l4: "IP", t28_r4: "Device addressing", t28_q: "Which protocol is used for secure websites?", t28_qa: "HTTPS", t28_qb: "HTTP", t28_qc: "FTP", t28_qd: "SMTP",
    t29_title: "Cybersecurity", t29_text: "Cybersecurity protects systems from attacks. Use strong passwords and be careful with unknown links.", t29_inst: "Sort the behaviors: Safe or Unsafe.", t29_h1: "Changing passwords regularly is safe.", t29_h2: "Clicking random pop-up ads is unsafe.", t29_b1: "Safe", t29_b2: "Unsafe", t29_i1: "Complex passwords", t29_i2: "Two-factor login", t29_i3: "Sharing passwords", t29_i4: "Opening weird links", t29_q: "Should you use the same password for everything?", t29_qa: "No", t29_qb: "Yes", t29_qc: "Only if short", t29_qd: "Maybe",
    t30_title: "Encryption", t30_text: "Encryption scrambles data so only authorized people can read it. It's the key to privacy online.", t30_inst: "Complete the sentence about encryption.", t30_h1: "The original text is called 'plain text'.", t30_h2: "Encryption turns it into 'cipher text'.", t30_sent: "Encryption changes readable text into ___ text.", t30_c1: "cipher", t30_c2: "easy", t30_c3: "bright", t30_c4: "broken", t30_q: "Which code is a simple historical encryption?", t30_qa: "Caesar code", t30_qb: "Binary code", t30_qc: "HTML", t30_qd: "SQL"
  },
  hu: {
    explorer_title: "Hardver és adat labor",
    t16_title: "Bináris rendszer", t16_text: "A számítógépek a bináris rendszert használják, amely csak két számjegyet tartalmaz: 0 és 1. Ezeket 'bit'-eknek hívjuk.", t16_inst: "Melyik szám van bináris formában?", t16_h1: "A bináris csak 0-t és 1-et használ.", t16_h2: "Ha 2-est, 3-ast vagy más számjegyet látsz, az nem bináris.", t16_q: "Binary Check:", t16_t1: "10110", t16_t2: "10210", t16_t3: "12345", t16_t4: "88", t16_quiz_q: "Hány számjegy van a bináris rendszerben?", t16_qa: "2", t16_qb: "1", t16_qc: "10", t16_qd: "16",
    t17_title: "Hexadecimális", t17_text: "A hexadecimális rendszer 16 szimbólumot használ (0-9 és A-F). Gyakran használják színek megadására.", t17_inst: "Egészítsd ki a hexadecimális sorozatot!", t17_h1: "9 után a szimbólumok: A, B, C, D, E, F.", t17_h2: "A 'C' a 12-es számot jelöli.", t17_sent: "9, A, B, ___ , D, E, F", t17_c1: "C", t17_c2: "10", t17_c3: "X", t17_c4: "G", t17_quiz_q: "Melyik betű jelöli a 10-et hexadecimális rendszerben?", t17_qa: "A", t17_qb: "B", t17_qc: "C", t17_qd: "F",
    t18_title: "Átváltás", t18_text: "A számrendszerek közötti átváltás segít a gépeknek és az embereknek megérteni egymást.", t18_inst: "Párosítsd a bináris számot a tizedes értékével!", t18_h1: "A 0001 az 1-es.", t18_h2: "Az 1010 a 10-es.", t18_l1: "0001", t18_r1: "1", t18_l2: "0010", t18_r2: "2", t18_l3: "0100", t18_r3: "4", t18_l4: "1000", t18_r4: "8", t18_q: "Mennyi a bináris '11' tizedes értéke?", t18_qa: "3", t18_qb: "2", t18_qc: "4", t18_qd: "1",
    t19_title: "CPU működése", t19_text: "A CPU a számítógép agya. Három lépést követ: lehívás (Fetch), dekódolás (Decode) és végrehajtás (Execute).", t19_inst: "Tedd sorrendbe a CPU utasítás ciklusát!", t19_h1: "Először a CPU lekéri az utasítást (Fetch).", t19_h2: "Végül a CPU végrehajtja a feladatot (Execute).", t19_w1: "Fetch (Lekérés)", t19_w2: "Decode (Értelmezés)", t19_w3: "Execute (Végrehajtás)", t19_q: "A számítógép melyik része az 'agy'?", t19_qa: "CPU", t19_qb: "RAM", t19_qc: "Monitor", t19_qd: "Billentyűzet",
    t20_title: "RAM és ROM", t20_text: "A RAM ideiglenes tároló (törlődik kikapcsoláskor). A ROM állandó (megőrzi az indítási adatokat).", t20_inst: "Rendezd a tulajdonságokat: RAM vagy ROM!", t20_h1: "A RAM tartalma törlődik újraindításkor.", t20_h2: "A ROM tartalmazza a BIOS indítási utasításokat.", t20_b1: "RAM", t20_b2: "ROM", t20_i1: "Ideiglenes memória", t20_i2: "Gyorsabb hozzáférés", t20_i3: "Állandó tároló", t20_i4: "Csak olvasható", t20_q: "Mi történik a RAM-mal, ha elmegy az áram?", t20_qa: "Törlődik", t20_qb: "Semmi", t20_qc: "Felrobban", t20_qd: "Mindent elment",
    t21_title: "GPU", t21_text: "A GPU (Grafikus processzor) speciálisan képek és videók megjelenítésére szolgál, sok apró feladatot végezve egyszerre.", t21_inst: "Egészítsd ki a GPU használatáról szóló mondatot!", t21_h1: "A GPU elengedhetetlen a modern játékokhoz.", t21_h2: "A nagyfelbontású grafikát kezeli.", t21_sent: "A GPU-t főleg ___ megjelenítésére használják.", t21_c1: "grafika", t21_c2: "hang", t21_c3: "billentyűzet", t21_c4: "nyomtató", t21_q: "Képes a GPU sok dolgot egyszerre végezni?", t21_qa: "Igen", t21_qb: "Nem", t21_qc: "Csak vízben", t21_qd: "Néha",
    t22_title: "Operációs rendszerek", t22_text: "Az operációs rendszer (OS) kezeli a szoftvereket és a hardvert. Például: Windows, macOS, Linux.", t22_inst: "Párosítsd az operációs rendszer részét a funkciójával!", t22_h1: "A Kernel (rendszermag) az OS központja.", t22_h2: "A GUI (grafikus felület) az, amit a felhasználó lát.", t22_l1: "Kernel", t22_r1: "Központi funkciók", t22_l2: "GUI", t22_r2: "Vizuális felület", t22_l3: "Illesztőprogram", t22_r3: "Hardver vezérlése", t22_l4: "Fájlrendszer", t22_r4: "Adatok rendszerezése", t22_q: "A Linux egy operációs rendszer?", t22_qa: "Igen", t22_qb: "Nem", t22_qc: "Csak Mac-en", t22_qd: "Ez hardver",
    t23_title: "Folyamatok és szálak", t23_text: "A folyamat egy futó program. A szál (thread) a folyamat egy kisebb része, ami önállóan futhat.", t23_inst: "Melyik egy folyamat része?", t23_h1: "Egy folyamatnak sok szála lehet.", t23_h2: "A szálak segítenek a számítógépnek gyorsabban dolgozni.", t23_q: "Keresd a kisebb részt:", t23_t1: "Szál", t23_t2: "Főprogram", t23_t3: "Merevlemez", t23_t4: "USB", t23_quiz_q: "Lehet-e egy folyamatnak több szála?", t23_qa: "Igen", t23_qb: "Nem", t23_qc: "Csak Linux-ban", t23_qd: "Talán",
    t24_title: "Virtualizáció", t24_text: "A virtualizáció lehetővé teszi, hogy egy fizikai gépen több virtuális gép (VM) fusson egyszerre.", t24_inst: "Egészítsd ki a virtuális gépekről szóló mondatot!", t24_h1: "A VM úgy viselkedik, mint egy valódi gép.", t24_h2: "Szoftvert használ a hardver szimulálására.", t24_sent: "A Linux futtatása Windows-on egy ___ géppel történik.", t24_c1: "virtuális", t24_c2: "nehéz", t24_c3: "törött", t24_c4: "repülő", t24_q: "Miért használnak virtualizációt?", t24_qa: "Több OS futtatása", t24_qb: "Árammegtakarítás", t24_qc: "Mert kék", t24_qd: "Egyik sem",
    t25_title: "SQL alapok", t25_text: "Az SQL egy nyelv az adatbázisokkal való kommunikációhoz. Lehet adatokat lekérni (SELECT), beszúrni (INSERT) vagy törölni (DELETE).", t25_inst: "Egészítsd ki az SQL lekérdezést az összes felhasználóhoz!", t25_h1: "A SELECT-et használjuk adatok lekérésére.", t25_h2: "A FROM határozza meg a tábla nevét.", t25_sent: "SELECT * ___ users", t25_c1: "FROM", t25_c2: "IN", t25_c3: "WITH", t25_c4: "GET", t25_q: "Melyik SQL parancs ad hozzá új adatot?", t25_qa: "INSERT", t25_qb: "SELECT", t25_qc: "DELETE", t25_qd: "UPDATE",
    t26_title: "Táblák és rekordok", t26_text: "Az adatokat táblákban tároljuk. Minden sor egy rekord, minden oszlop pedig egy mező (pl. név vagy kor).", t26_inst: "Párosítsd az adatbázis fogalmat a szerepével!", t26_h1: "Egy sor egyetlen elemet (pl. egy felhasználót) jelent.", t26_h2: "A Primary Key (elsődleges kulcs) egyedileg azonosít minden sort.", t26_l1: "Sor", t26_r1: "Egy rekord", t26_l2: "Oszlop", t26_r2: "Adatkategória", t26_l3: "Primary Key", t26_r3: "Egyedi azonosító", t26_l4: "Tábla", t26_r4: "Adatgyűjtemény", t26_q: "Hogy hívják a táblázat egyetlen sorát?", t26_qa: "Rekord", t26_qb: "Mező", t26_qc: "Tábla", t26_qd: "Lekérdezés",
    t27_title: "Adatkapcsolatok", t27_text: "A táblák összekapcsolhatók. Például a 'Rendelések' tábla a felhasználói azonosítóval kapcsolódik a 'Felhasználók' táblához.", t27_inst: "Hogyan kapcsolunk össze két táblát?", t27_h1: "Használjunk közös azonosítót mindkét táblában!", t27_h2: "Ezt idegen kulcsnak (Foreign Key) hívják.", t27_q: "Mi kapcsolja össze a táblákat?", t27_t1: "Foreign Key", t27_t2: "Tábla színe", t27_t3: "Egér", t27_t4: "Képernyő", t27_quiz_q: "Segít-e a 'Foreign Key' a táblák összekapcsolásában?", t27_qa: "Igen", t27_qb: "Nem", t27_qc: "Csak Excel-ben", t27_qd: "Talán",
    t28_title: "Protokollok", t28_text: "A protokollok a kommunikáció szabályai. A HTTP weboldalakhoz, az SMTP e-mailekhez használatos.", t28_inst: "Párosítsd a protokollt a feladatával!", t28_h1: "A HTTP/HTTPS a webböngészéshez van.", t28_h2: "Az IP kezeli az eszközök címzését.", t28_l1: "HTTP", t28_r1: "Weboldalak", t28_l2: "SMTP", t28_r2: "E-mail küldés", t28_l3: "FTP", t28_r3: "Fájlátvitel", t28_l4: "IP", t28_r4: "Eszközcímzés", t28_q: "Melyik protokollt használják a biztonságos weboldalakhoz?", t28_qa: "HTTPS", t28_qb: "HTTP", t28_qc: "FTP", t28_qd: "SMTP",
    t29_title: "Kiberbiztonság", t29_text: "A kiberbiztonság megvédi a rendszereket a támadásoktól. Használj erős jelszavakat!", t29_inst: "Rendezd a viselkedéseket: Biztonságos vagy Nem biztonságos!", t29_h1: "A jelszavak rendszeres cseréje biztonságos.", t29_h2: "A felugró hirdetésekre való kattintás nem biztonságos.", t29_b1: "Biztonságos", t29_b2: "Nem biztonságos", t29_i1: "Bonyolult jelszavak", t29_i2: "Kétlépcsős azonosítás", t29_i3: "Jelszavak megosztása", t29_i4: "Gyanús linkek megnyitása", t29_q: "Szabad-e ugyanazt a jelszót használni mindenhol?", t29_qa: "Nem", t29_qb: "Igen", t29_qc: "Csak ha rövid", t29_qd: "Talán",
    t30_title: "Titkosítás", t30_text: "A titkosítás olvashatatlanná teszi az adatokat az illetéktelenek számára. Ez az online magánélet kulcsa.", t30_inst: "Egészítsd ki a titkosításról szóló mondatot!", t30_h1: "Az eredeti szöveget 'plain text'-nek hívjuk.", t30_h2: "A titkosítás 'cipher text'-té alakítja.", t30_sent: "A titkosítás az olvasható szöveget ___ szöveggé alakítja.", t30_c1: "titkos", t30_c2: "könnyű", t30_c3: "világos", t30_c4: "törött", t30_q: "Melyik egy egyszerű történelmi titkosítás?", t30_qa: "Caesar-kód", t30_qb: "Bináris kód", t30_qc: "HTML", t30_qd: "SQL"
  },
  ro: {
    explorer_title: "Laborator Hardware și Date",
    t16_title: "Sistemul binar", t16_text: "Calculatoarele folosesc sistemul binar, care are doar două cifre: 0 și 1. Acestea se numesc „biți”.", t16_inst: "Care dintre aceste numere este scris în binar?", t16_h1: "Binarul folosește doar 0 și 1.", t16_h2: "Dacă vezi un 2, 3 sau orice altă cifră, nu este binar.", t16_q: "Binary Check:", t16_t1: "10110", t16_t2: "10210", t16_t3: "12345", t16_t4: "88", t16_quiz_q: "Câte cifre sunt în sistemul binar?", t16_qa: "2", t16_qb: "1", t16_qc: "10", t16_qd: "16",
    t17_title: "Hexazecimal", t17_text: "Sistemul hexazecimal folosește 16 simboluri (0-9 și A-F). Este adesea folosit pentru culori pe site-uri web.", t17_inst: "Completează secvența hexazecimală.", t17_h1: "După 9, simbolurile sunt A, B, C, D, E, F.", t17_h2: "„C” reprezintă numărul zecimal 12.", t17_sent: "9, A, B, ___ , D, E, F", t17_c1: "C", t17_c2: "10", t17_c3: "X", t17_c4: "G", t17_quiz_q: "Ce literă reprezintă 10 în hexazecimal?", t17_qa: "A", t17_qb: "B", t17_qc: "C", t17_qd: "F",
    t18_title: "Conversie", t18_text: "Convertirea numerelor între sisteme (binar în zecimal) ajută calculatoarele și oamenii să se înțeleagă.", t18_inst: "Potrivește numărul binar cu valoarea sa zecimală.", t18_h1: "0001 este 1.", t18_h2: "1010 este 10.", t18_l1: "0001", t18_r1: "1", t18_l2: "0010", t18_r2: "2", t18_l3: "0100", t18_r3: "4", t18_l4: "1000", t18_r4: "8", t18_q: "Care este valoarea zecimală a binarului „11”?", t18_qa: "3", t18_qb: "2", t18_qc: "4", t18_qd: "1",
    t19_title: "Funcționarea procesorului", t19_text: "Unitatea centrală de procesare (CPU) este creierul computerului. Urmează trei pași: Fetch, Decode și Execute.", t19_inst: "Pune ciclul de instrucțiuni al procesorului în ordine.", t19_h1: "Mai întâi, procesorul primește instrucțiunea (Fetch).", t19_h2: "În cele din urmă, procesorul îndeplinește sarcina (Execute).", t19_w1: "Fetch (Obține date)", t19_w2: "Decode (Înțelege)", t19_w3: "Execute (Execută sarcina)", t19_q: "Care parte a computerului este „creierul”?", t19_qa: "CPU", t19_qb: "RAM", t19_qc: "Monitor", t19_qd: "Tastatură",
    t20_title: "RAM și ROM", t20_text: "RAM este stocare temporară (ștearsă când este oprit). ROM este stocare permanentă (păstrează date precum instrucțiunile de pornire).", t20_inst: "Sortează caracteristicile: RAM sau ROM.", t20_h1: "RAM este șters când repornești.", t20_h2: "ROM conține instrucțiunile de pornire BIOS.", t20_b1: "RAM", t20_b2: "ROM", t20_i1: "Memorie temporară", t20_i2: "Acces mai rapid", t20_i3: "Stocare permanentă", t20_i4: "Doar citire", t20_q: "Ce se întâmplă cu RAM când se oprește curentul?", t20_qa: "Este șters", t20_qb: "Nimic", t20_qc: "Explodează", t20_qd: "Salvează totul",
    t21_title: "GPU", t21_text: "Unitatea de procesare grafică (GPU) este specializată pentru redarea imaginilor și a videoclipurilor prin îndeplinirea simultană a multor sarcini mici.", t21_inst: "Completează propoziția despre utilizarea GPU.", t21_h1: "GPU este esențial pentru jocurile moderne.", t21_h2: "Gestionează grafice de înaltă rezoluție.", t21_sent: "GPU este utilizat în principal pentru randarea ___.", t21_c1: "grafice", t21_c2: "sunet", t21_c3: "tastatură", t21_c4: "imprimantă", t21_q: "Poate un GPU să facă multe lucruri deodată?", t21_qa: "Da", t21_qb: "Nu", t21_qc: "Doar în apă", t21_qd: "Uneori",
    t22_title: "Sisteme de operare", t22_text: "Sistemul de operare (OS) gestionează software-ul și hardware-ul. Exemple sunt Windows, macOS și Linux.", t22_inst: "Potrivește partea sistemului de operare cu funcția sa.", t22_h1: "Kernelul este nucleul sistemului de operare.", t22_h2: "GUI este ceea ce utilizatorii văd și pe ce fac clic.", t22_l1: "Kernel", t22_r1: "Funcții de bază", t22_l2: "GUI", t22_r2: "Interfață vizuală", t22_l3: "Driver", t22_r3: "Controlează hardware-ul", t22_l4: "Sistem de fișiere", t22_r4: "Organizează datele", t22_q: "Este Linux un sistem de operare?", t22_qa: "Da", t22_qb: "Nu", t22_qc: "Doar pe Mac-uri", t22_qd: "Este hardware",
    t23_title: "Procese și fire", t23_text: "Un proces este un program care rulează. Un fir (thread) este o parte mai mică a unui proces care poate rula independent.", t23_inst: "Care dintre acestea este o parte a unui proces?", t23_h1: "Un proces poate avea mai multe fire.", t23_h2: "Firele ajută computerul să facă lucrurile mai repede.", t23_q: "Găsește partea mai mică:", t23_t1: "Fir (Thread)", t23_t2: "Program principal", t23_t3: "Hard disk", t23_t4: "USB", t23_quiz_q: "Poate un proces să aibă mai multe fire?", t23_qa: "Da", t23_qb: "Nu", t23_qc: "Doar în Linux", t23_qd: "Poate",
    t24_title: "Virtualizarea", t24_text: "Virtualizarea permite unui computer fizic să ruleze mai multe computere virtuale (VM) în același timp.", t24_inst: "Completează propoziția despre mașinile virtuale.", t24_h1: "Un VM se comportă ca un computer real.", t24_h2: "Folosește software pentru a simula hardware-ul.", t24_sent: "Rularea Linux în Windows se face folosind o mașină ___.", t24_c1: "virtuală", t24_c2: "grea", t24_c3: "stricată", t24_c4: "zburătoare", t24_q: "De ce se folosește virtualizarea?", t24_qa: "Rularea mai multor OS", t24_qb: "Economisirea energiei", t24_qc: "Pentru că e albastru", t24_qd: "Niciunul",
    t25_title: "Bazele SQL", t25_text: "SQL este un limbaj folosit pentru a comunica cu bazele de date. Poți SELECTA date, INSERA elemente noi sau le poți ȘTERGE.", t25_inst: "Completează interogarea SQL pentru a obține toți utilizatorii.", t25_h1: "SELECT este folosit pentru a alege date.", t25_h2: "FROM specifică numele tabelului.", t25_sent: "SELECT * ___ users", t25_c1: "FROM", t25_c2: "IN", t25_c3: "WITH", t25_c4: "GET", t25_q: "Care comandă SQL adaugă date noi?", t25_qa: "INSERT", t25_qb: "SELECT", t25_qc: "DELETE", t25_qd: "UPDATE",
    t26_title: "Tabele și înregistrări", t26_text: "Datele sunt stocate în Tabele. Fiecare rând este o Înregistrare, iar fiecare coloană este un Câmp (cum ar fi Nume sau Vârstă).", t26_inst: "Potrivește termenul bazei de date cu rolul său.", t26_h1: "Un rând reprezintă un singur element (cum ar fi un utilizator).", t26_h2: "O cheie primară identifică în mod unic fiecare rând.", t26_l1: "Rând", t26_r1: "O înregistrare", t26_l2: "Coloană", t26_r2: "Categorie de date", t26_l3: "Cheie primară", t26_r3: "ID unic", t26_l4: "Tabel", t26_r4: "Colecție de date", t26_q: "Cum se numește un singur rând dintr-un tabel?", t26_qa: "Înregistrare", t26_qb: "Câmp", t26_qc: "Tabel", t26_qd: "Interogare",
    t27_title: "Relații de date", t27_text: "Tabelele pot fi legate. De exemplu, un tabel „Comenzi” este legat de un tabel „Utilizatori” printr-un ID de utilizator.", t27_inst: "Cum legăm două tabele?", t27_h1: "Folosește un ID comun în ambele tabele.", t27_h2: "Aceasta se numește cheie străină.", t27_q: "Ce conectează tabelele?", t27_t1: "Cheie străină", t27_t2: "Culoarea tabelului", t27_t3: "Mouse", t27_t4: "Ecran", t27_quiz_q: "Ajută o „cheie străină” la legarea tabelelor?", t27_qa: "Da", t27_qb: "Nu", t27_qc: "Doar în Excel", t27_qd: "Poate",
    t28_title: "Protocoale", t28_text: "Protocoalele sunt reguli de comunicare. HTTP este pentru site-uri web, iar SMTP este pentru trimiterea de e-mailuri.", t28_inst: "Potrivește protocolul cu sarcina sa.", t28_h1: "HTTP/HTTPS este pentru navigarea pe web.", t28_h2: "IP gestionează adresarea dispozitivelor.", t28_l1: "HTTP", t28_r1: "Site-uri web", t28_l2: "SMTP", t28_r2: "Trimitere e-mail", t28_l3: "FTP", t28_r3: "Transfer de fișiere", t28_l4: "IP", t28_r4: "Adresarea dispozitivului", t28_q: "Care protocol este utilizat pentru site-uri web securizate?", t28_qa: "HTTPS", t28_qb: "HTTP", t28_qc: "FTP", t28_qd: "SMTP",
    t29_title: "Securitate cibernetică", t29_text: "Securitatea cibernetică protejează sistemele de atacuri. Folosește parole puternice și ai grijă la linkurile necunoscute.", t29_inst: "Sortează comportamentele: Sigure sau Nesigure.", t29_h1: "Schimbarea regulată a parolelor este sigură.", t29_h2: "Dând clic pe reclame pop-up aleatorii este nesigur.", t29_b1: "Sigur", t29_b2: "Nesigur", t29_i1: "Parole complexe", t29_i2: "Autentificare cu doi factori", t29_i3: "Partajarea parolelor", t29_i4: "Deschiderea link-urilor ciudate", t29_q: "Ar trebui să folosești aceeași parolă pentru toate?", t29_qa: "Nu", t29_qb: "Da", t29_qc: "Doar dacă e scurtă", t29_qd: "Poate",
    t30_title: "Criptarea", t30_text: "Criptarea amestecă datele, astfel încât numai persoanele autorizate să le poată citi. Este cheia confidențialității online.", t30_inst: "Completează propoziția despre criptare.", t30_h1: "Textul original se numește „text simplu”.", t30_h2: "Criptarea îl transformă în „text cifrat”.", t30_sent: "Criptarea schimbă textul lizibil în text ___.", t30_c1: "cifrat", t30_c2: "ușor", t30_c3: "luminos", t30_c4: "stricat", t30_q: "Care cod este o criptare istorică simplă?", t30_qa: "Codul Caesar", t30_qb: "Cod binar", t30_qc: "HTML", t30_qd: "SQL"
  }
};

export const INFO_K7_I2_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t16_title", infoText: "t16_text",
    svg: { type: "simple-icon", icon: "🔢", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "physics-slingshot", instruction: "t16_inst", hint1: "t16_h1", hint2: "t16_h2", question: "t16_q", targets: [{id:"1",text:"t16_t1",isCorrect:true},{id:"2",text:"t16_t2",isCorrect:false},{id:"3",text:"t16_t3",isCorrect:false},{id:"4",text:"t16_t4",isCorrect:false}] },
    quiz: { question: "t16_quiz_q", choices: ["t16_qa", "t16_qb", "t16_qc", "t16_qd"], answer: "t16_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t17_title", infoText: "t17_text",
    svg: { type: "simple-icon", icon: "🎨", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "gap-fill", instruction: "t17_inst", hint1: "t17_h1", hint2: "t17_h2", sentence: "t17_sent", choices: ["t17_c1", "t17_c2", "t17_c3", "t17_c4"], correctIndex: 0 },
    quiz: { question: "t17_quiz_q", choices: ["t17_qa", "t17_qb", "t17_qc", "t17_qd"], answer: "t17_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t18_title", infoText: "t18_text",
    svg: { type: "simple-icon", icon: "🔄", bg: "#ECFDF5", color: "#059669" },
    interactive: { type: "match-pairs", instruction: "t18_inst", hint1: "t18_h1", hint2: "t18_h2", pairs: [{left:"t18_l1",right:"t18_r1"},{left:"t18_l2",right:"t18_r2"},{left:"t18_l3",right:"t18_r3"},{left:"t18_l4",right:"t18_r4"}] },
    quiz: { question: "t18_q", choices: ["t18_qa", "t18_qb", "t18_qc", "t18_qd"], answer: "t18_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t19_title", infoText: "t19_text",
    svg: { type: "simple-icon", icon: "🧠", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: { type: "physics-stacker", instruction: "t19_inst", hint1: "t19_h1", hint2: "t19_h2", words: ["t19_w1", "t19_w2", "t19_w3"], correctOrder: [0, 1, 2] },
    quiz: { question: "t19_q", choices: ["t19_qa", "t19_qb", "t19_qc", "t19_qd"], answer: "t19_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t20_title", infoText: "t20_text",
    svg: { type: "simple-icon", icon: "💾", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "physics-bucket", instruction: "t20_inst", hint1: "t20_h1", hint2: "t20_h2", buckets: [{id:"ram",label:"t20_b1"},{id:"rom",label:"t20_b2"}], items: [{text:"t20_i1",bucketId:"ram"},{text:"t20_i2",bucketId:"ram"},{text:"t20_i3",bucketId:"rom"},{text:"t20_i4",bucketId:"rom"}] },
    quiz: { question: "t20_q", choices: ["t20_qa", "t20_qb", "t20_qc", "t20_qd"], answer: "t20_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t21_title", infoText: "t21_text",
    svg: { type: "simple-icon", icon: "🎮", bg: "#F0FDF4", color: "#16A34A" },
    interactive: { type: "gap-fill", instruction: "t21_inst", hint1: "t21_h1", hint2: "t21_h2", sentence: "t21_sent", choices: ["t21_c1", "t21_c2", "t21_c3", "t21_c4"], correctIndex: 0 },
    quiz: { question: "t21_q", choices: ["t21_qa", "t21_qb", "t21_qc", "t21_qd"], answer: "t21_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t22_title", infoText: "t22_text",
    svg: { type: "simple-icon", icon: "🖥️", bg: "#FFF7ED", color: "#C2410C" },
    interactive: { type: "match-pairs", instruction: "t22_inst", hint1: "t22_h1", hint2: "t22_h2", pairs: [{left:"t22_l1",right:"t22_r1"},{left:"t22_l2",right:"t22_r2"},{left:"t22_l3",right:"t22_r3"},{left:"t22_l4",right:"t22_r4"}] },
    quiz: { question: "t22_q", choices: ["t22_qa", "t22_qb", "t22_qc", "t22_qd"], answer: "t22_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t23_title", infoText: "t23_text",
    svg: { type: "simple-icon", icon: "🧵", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: { type: "physics-slingshot", instruction: "t23_inst", hint1: "t23_h1", hint2: "t23_h2", question: "t23_q", targets: [{id:"1",text:"t23_t1",isCorrect:true},{id:"2",text:"t23_t2",isCorrect:false},{id:"3",text:"t23_t3",isCorrect:false},{id:"4",text:"t23_t4",isCorrect:false}] },
    quiz: { question: "t23_quiz_q", choices: ["t23_qa", "t23_qb", "t23_qc", "t23_qd"], answer: "t23_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t24_title", infoText: "t24_text",
    svg: { type: "simple-icon", icon: "☁️", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "gap-fill", instruction: "t24_inst", hint1: "t24_h1", hint2: "t24_h2", sentence: "t24_sent", choices: ["t24_c1", "t24_c2", "t24_c3", "t24_c4"], correctIndex: 0 },
    quiz: { question: "t24_q", choices: ["t24_qa", "t24_qb", "t24_qc", "t24_qd"], answer: "t24_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t25_title", infoText: "t25_text",
    svg: { type: "simple-icon", icon: "📊", bg: "#F0FDF4", color: "#16A34A" },
    interactive: { type: "gap-fill", instruction: "t25_inst", hint1: "t25_h1", hint2: "t25_h2", sentence: "t25_sent", choices: ["t25_c1", "t25_c2", "t25_c3", "t25_c4"], correctIndex: 0 },
    quiz: { question: "t25_q", choices: ["t25_qa", "t25_qb", "t25_qc", "t25_qd"], answer: "t25_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t26_title", infoText: "t26_text",
    svg: { type: "simple-icon", icon: "📅", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "match-pairs", instruction: "t26_inst", hint1: "t26_h1", hint2: "t26_h2", pairs: [{left:"t26_l1",right:"t26_r1"},{left:"t26_l2",right:"t26_r2"},{left:"t26_l3",right:"t26_r3"},{left:"t26_l4",right:"t26_r4"}] },
    quiz: { question: "t26_q", choices: ["t26_qa", "t26_qb", "t26_qc", "t26_qd"], answer: "t26_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t27_title", infoText: "t27_text",
    svg: { type: "simple-icon", icon: "🔗", bg: "#FFF7ED", color: "#C2410C" },
    interactive: { type: "physics-slingshot", instruction: "t27_inst", hint1: "t27_h1", hint2: "t27_h2", question: "t27_q", targets: [{id:"1",text:"t27_t1",isCorrect:true},{id:"2",text:"t27_t2",isCorrect:false},{id:"3",text:"t27_t3",isCorrect:false},{id:"4",text:"t27_t4",isCorrect:false}] },
    quiz: { question: "t27_quiz_q", choices: ["t27_qa", "t27_qb", "t27_qc", "t27_qd"], answer: "t27_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t28_title", infoText: "t28_text",
    svg: { type: "simple-icon", icon: "📡", bg: "#ECFDF5", color: "#059669" },
    interactive: { type: "match-pairs", instruction: "t28_inst", hint1: "t28_h1", hint2: "t28_h2", pairs: [{left:"t28_l1",right:"t28_r1"},{left:"t28_l2",right:"t28_r2"},{left:"t28_l3",right:"t28_r3"},{left:"t28_l4",right:"t28_r4"}] },
    quiz: { question: "t28_q", choices: ["t28_qa", "t28_qb", "t28_qc", "t28_qd"], answer: "t28_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t29_title", infoText: "t29_text",
    svg: { type: "simple-icon", icon: "🛡️", bg: "#FEFCE8", color: "#A16207" },
    interactive: { type: "physics-bucket", instruction: "t29_inst", hint1: "t29_h1", hint2: "t29_h2", buckets: [{id:"safe",label:"t29_b1"},{id:"unsafe",label:"t29_b2"}], items: [{text:"t29_i1",bucketId:"safe"},{text:"t29_i2",bucketId:"safe"},{text:"t29_i3",bucketId:"unsafe"},{text:"t29_i4",bucketId:"unsafe"}] },
    quiz: { question: "t29_q", choices: ["t29_qa", "t29_qb", "t29_qc", "t29_qd"], answer: "t29_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t30_title", infoText: "t30_text",
    svg: { type: "simple-icon", icon: "🔐", bg: "#F0FDF4", color: "#16A34A" },
    interactive: { type: "gap-fill", instruction: "t30_inst", hint1: "t30_h1", hint2: "t30_h2", sentence: "t30_sent", choices: ["t30_c1", "t30_c2", "t30_c3", "t30_c4"], correctIndex: 0 },
    quiz: { question: "t30_q", choices: ["t30_qa", "t30_qb", "t30_qc", "t30_qd"], answer: "t30_qa" }
  }
];

