// @ts-nocheck
// lib/explorerPools/informatikaK2_i5.ts
import type { PoolTopicDef } from "./types";

export const INFO_K2_I5_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Bildbearbeitung Grundlagen",
    t1_title: "Bild öffnen", t1_text: "Wähle ein Foto von deinem Computer aus, um es zu bearbeiten.", t1_inst: "Verbinde die Paare:", t1_h1: "Datei laden.", t1_h2: "Starten.", t1_q: "Was machst du zuerst?", t1_qa: "Bild öffnen", t1_qb: "Computer löschen", t1_qc: "Licht ausmachen", t1_qd: "Schlafen",
    t1_l1: "Öffnen", t1_r1: "Start", t1_l2: "Datei", t1_r2: "Bild", t1_l3: "Ordner", t1_r3: "Suchen",
    t2_title: "Zuschneiden (Crop)", t2_text: "Schneide die Ränder weg, damit nur das Wichtige zu sehen ist.", t2_inst: "Verbinde die Paare:", t2_h1: "Ränder weg.", t2_h2: "Fokus setzen.", t2_q: "Was macht 'Zuschneiden'?", t2_qa: "Teile vom Rand entfernen", t2_qb: "Das Bild malen", t2_qc: "Musik abspielen", t2_qd: "Text schreiben",
    t2_l1: "Zuschneiden", t2_r1: "Rand weg", t2_l2: "Schere", t2_r2: "Symbol", t2_l3: "Fokus", t2_r3: "Mitte",
    t3_title: "Größe ändern", t3_text: "Mache dein Bild größer oder kleiner.", t3_inst: "Verbinde die Paare:", t3_h1: "Größe anpassen.", t3_h2: "Pixel ändern.", t3_q: "Was bedeutet 'Resize'?", t3_qa: "Größe ändern", t3_qb: "Farbe ändern", t3_qc: "Bild löschen", t3_qd: "Namen ändern",
    t3_l1: "Größe", t3_r1: "Pixel", t3_l2: "Klein", t3_r2: "E-Mail", t3_l3: "Groß", t3_r3: "Poster",
    t4_title: "Drehen (Rotate)", t4_text: "Drehe dein Bild, wenn es auf der Seite liegt.", t4_inst: "Verbinde die Paare:", t4_h1: "Karussell.", t4_h2: "Richtung ändern.", t4_q: "Was macht man beim Drehen?", t4_qa: "Das Bild wenden", t4_qb: "Das Bild löschen", t4_qc: "Das Bild dunkler machen", t4_qd: "Nichts",
    t4_l1: "Drehen", t4_r1: "Wenden", t4_l2: "Pfeil", t4_r2: "Kreis", t4_l3: "Grad", t4_r3: "Winkel",
    t5_title: "Aufhellen", t5_text: "Mache ein zu dunkles Foto heller, damit man alles sieht.", t5_inst: "Verbinde die Paare:", t5_h1: "Mehr Licht.", t5_h2: "Sonne an.", t5_q: "Wann benutzt du 'Aufhellen'?", t5_qa: "Wenn das Bild zu dunkel ist", t5_qb: "Wenn das Bild zu hell ist", t5_qc: "Wenn das Bild weg ist", t5_qd: "Immer",
    t5_l1: "Heller", t5_r1: "Licht", t5_l2: "Sonne", t5_r2: "Symbol", t5_l3: "Dunkel", t5_r3: "Vorher",
    t6_title: "Abdunkeln", t6_text: "Mache ein zu helles Bild etwas dunkler.", t6_inst: "Verbinde die Paare:", t6_h1: "Weniger Licht.", t6_h2: "Schatten.", t6_q: "Was passiert beim Abdunkeln?", t6_qa: "Das Bild wird dunkler", t6_qb: "Das Bild wird weiß", t6_qc: "Das Bild verschwindet", t6_qd: "Es wird bunt",
    t6_l1: "Dunkler", t6_r1: "Schatten", t6_l2: "Mond", t6_r2: "Symbol", t6_l3: "Hell", t6_r3: "Vorher",
    t7_title: "Farben anpassen", t7_text: "Mache die Farben kräftiger oder ändere sie ganz.", t1_inst: "Verbinde die Paare:", t7_h1: "Bunter machen.", t7_h2: "Sättigung.", t7_q: "Was änderst du hier?", t7_qa: "Die Farben", t7_qb: "Die Größe", t7_qc: "Den Namen", t7_qd: "Das Datum",
    t7_l1: "Farbe", t7_r1: "Bunt", t7_l2: "Grau", t7_r2: "Farblos", t7_l3: "Palette", t7_r3: "Auswahl",
    t8_title: "Filter benutzen", t8_text: "Mit Filtern kannst du dein Bild schnell verändern, z.B. in Schwarz-Weiß.", t8_inst: "Verbinde die Paare:", t8_h1: "Schneller Effekt.", t8_h2: "Zauberei.", t8_q: "Was ist ein Filter?", t8_qa: "Ein fertiger Effekt", t8_qb: "Ein Putzmittel", t8_qc: "Ein neues Bild", t8_qd: "Eine Kamera",
    t8_l1: "Filter", t8_r1: "Effekt", t8_l2: "Sepia", t8_r2: "Alt", t8_l3: "S/W", t8_r3: "Grau",
    t9_title: "Text hinzufügen", t9_text: "Schreibe etwas direkt auf dein Bild.", t9_inst: "Verbinde die Paare:", t9_h1: "Wörter schreiben.", t9_h2: "T-Symbol.", t9_q: "Welches Symbol steht oft für Text?", t9_qa: "Das T", t9_qb: "Ein Kreis", t9_qc: "Ein Auto", t9_qd: "Ein Baum",
    t9_l1: "Text", t9_r1: "Schreiben", t9_l2: "T", t9_r2: "Symbol", t9_l3: "Schrift", t9_r3: "Art",
    t10_title: "Rahmen (Border)", t10_text: "Setze einen schönen Rahmen um dein Bild.", t10_inst: "Verbinde die Paare:", t10_h1: "Einfassen.", t10_h2: "Dekoration.", t10_q: "Was ist ein 'Border'?", t10_qa: "Ein Rahmen", t10_qb: "Ein Loch", t10_qc: "Ein Fleck", t10_qd: "Ein Fehler",
    t10_l1: "Rahmen", t10_r1: "Außen", t10_l2: "Linie", t10_r2: "Rand", t10_l3: "Deko", t10_r3: "Schön",
    t11_title: "Element kopieren", t11_text: "Du kannst Teile vom Bild kopieren und woanders einfügen.", t11_inst: "Verbinde die Paare:", t11_h1: "Verdoppeln.", t11_h2: "Stempel.", t11_q: "Was macht man beim Kopieren?", t11_qa: "Einen Teil verdoppeln", t11_qb: "Alles löschen", t11_qc: "Das Bild drehen", t11_qd: "Singen",
    t11_l1: "Kopie", t11_r1: "Zwei", t11_l2: "Stempel", t11_r2: "Werkzeug", t11_l3: "Quelle", t11_r3: "Start",
    t12_title: "Retusche", t12_text: "Entferne kleine Fehler oder Flecken im Bild.", t12_inst: "Verbinde die Paare:", t12_h1: "Sauber machen.", t12_h2: "Pflaster-Symbol.", t12_q: "Was macht Retusche?", t12_qa: "Kleine Fehler korrigieren", t12_qb: "Das Bild zerstören", t12_qc: "Essen kochen", t12_qd: "Laufen",
    t12_l1: "Retusche", t12_r1: "Heilen", t12_l2: "Pflaster", t12_r2: "Symbol", t12_l3: "Fleck", t12_r3: "Weg",
    t13_title: "Ebenen (Layers)", t13_text: "Arbeite mit mehreren Schichten übereinander.", t13_inst: "Verbinde die Paare:", t13_h1: "Stapel.", t13_h2: "Übereinander.", t13_q: "Was sind Ebenen?", t13_qa: "Schichten im Bild", t13_qb: "Treppen", t13_qc: "Farben", t13_qd: "Pinsel",
    t13_l1: "Ebene", t13_r1: "Schicht", t13_l2: "Stapel", t13_r2: "Oben/Unten", t13_l3: "Sichtbar", t13_r3: "Auge",
    t14_title: "Speichern (JPG/PNG)", t14_text: "Speichere dein fertiges Werk als JPG oder PNG Datei.", t14_inst: "Verbinde die Paare:", t14_h1: "Fertigstellen.", t14_h2: "Format wählen.", t14_q: "Was sind JPG und PNG?", t14_qa: "Bildformate", t14_qb: "Eissorten", t14_qc: "Automarken", t14_qd: "Ländernamen",
    t14_l1: "JPG", t14_r1: "Foto", t14_l2: "PNG", t14_r2: "Grafik", t14_l3: "Speichern", t14_r3: "Behalten",
    t15_title: "Editor-Meister", t15_text: "Du kannst jetzt Bilder wie ein Profi bearbeiten!", t15_inst: "Verbinde die Paare:", t15_h1: "Super gemacht!", t15_h2: "Alles gelernt.", t15_q: "Was bist du jetzt?", t15_qa: "Bild-Experte", t15_qb: "Ein Drucker", t15_qc: "Ein Rahmen", t15_qd: "Ein Papier",
    t15_l1: "Meister", t15_r1: "Experte", t15_l2: "Bild", t15_r2: "Design", t15_l3: "Fertig", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "Image Editing Basics",
    t1_title: "Open Image", t1_text: "Choose a photo from your computer to edit it.", t1_inst: "Match the pairs:", t1_h1: "Load file.", t1_h2: "Start.", t1_q: "What do you do first?", t1_qa: "Open image", t1_qb: "Delete computer", t1_qc: "Turn off light", t1_qd: "Sleep",
    t1_l1: "Open", t1_r1: "Start", t1_l2: "File", t1_r2: "Image", t1_l3: "Folder", t1_r3: "Search",
    t2_title: "Crop", t2_text: "Cut away the edges so only the important part is visible.", t2_inst: "Match the pairs:", t2_h1: "Edges away.", t2_h2: "Set focus.", t2_q: "What does 'Crop' do?", t2_qa: "Remove parts of the edge", t2_qb: "Paint the image", t2_qc: "Play music", t2_qd: "Write text",
    t2_l1: "Crop", t2_r1: "Edge away", t2_l2: "Scissors", t2_r2: "Symbol", t2_l3: "Focus", t2_r3: "Middle",
    t3_title: "Resize", t3_text: "Make your image larger or smaller.", t3_inst: "Match the pairs:", t3_h1: "Adjust size.", t3_h2: "Change pixels.", t3_q: "What does 'Resize' mean?", t3_qa: "Change size", t3_qb: "Change color", t3_qc: "Delete image", t3_qd: "Change name",
    t3_l1: "Size", t3_r1: "Pixels", t3_l2: "Small", t3_r2: "Email", t3_l3: "Large", t3_r3: "Poster",
    t4_title: "Rotate", t4_text: "Rotate your image if it's on its side.", t4_inst: "Match the pairs:", t4_h1: "Carousel.", t4_h2: "Change direction.", t4_q: "What do you do when rotating?", t4_qa: "Turn the image", t4_qb: "Delete the image", t4_qc: "Make the image darker", t4_qd: "Nothing",
    t4_l1: "Rotate", t4_r1: "Turn", t4_l2: "Arrow", t4_r2: "Circle", t4_l3: "Degrees", t4_r3: "Angle",
    t5_title: "Brighten", t5_text: "Make a photo that is too dark brighter so you can see everything.", t5_inst: "Match the pairs:", t5_h1: "More light.", t5_h2: "Sun on.", t5_q: "When do you use 'Brighten'?", t5_qa: "When the image is too dark", t5_qb: "When the image is too bright", t5_qc: "When the image is gone", t5_qd: "Always",
    t5_l1: "Brighter", t5_r1: "Light", t5_l2: "Sun", t5_r2: "Symbol", t5_l3: "Dark", t5_r3: "Before",
    t6_title: "Darken", t6_text: "Make an image that is too bright a bit darker.", t6_inst: "Match the pairs:", t6_h1: "Less light.", t6_h2: "Shadow.", t6_q: "What happens when darkening?", t6_qa: "The image gets darker", t6_qb: "The image turns white", t6_qc: "The image disappears", t6_qd: "It gets colorful",
    t6_l1: "Darker", t6_r1: "Shadow", t6_l2: "Moon", t6_r2: "Symbol", t6_l3: "Bright", t6_r3: "Before",
    t7_title: "Adjust Colors", t7_text: "Make the colors stronger or change them completely.", t7_inst: "Match the pairs:", t7_h1: "Make more colorful.", t7_h2: "Saturation.", t7_q: "What do you change here?", t7_qa: "The colors", t7_qb: "The size", t7_qc: "The name", t7_qd: "The date",
    t7_l1: "Color", t7_r1: "Colorful", t7_l2: "Gray", t7_r2: "Colorless", t7_l3: "Palette", t7_r3: "Selection",
    t8_title: "Use Filters", t8_text: "With filters, you can quickly change your image, e.g., to black and white.", t8_inst: "Match the pairs:", t8_h1: "Quick effect.", t8_h2: "Magic.", t8_q: "What is a filter?", t8_qa: "A ready-made effect", t8_qb: "A cleaning agent", t8_qc: "A new image", t8_qd: "A camera",
    t8_l1: "Filter", t8_r1: "Effect", t8_l2: "Sepia", t8_r2: "Old", t8_l3: "B/W", t8_r3: "Gray",
    t9_title: "Add Text", t9_text: "Write something directly on your image.", t9_inst: "Match the pairs:", t9_h1: "Write words.", t9_h2: "T symbol.", t9_q: "Which symbol often stands for text?", t9_qa: "The T", t9_qb: "A circle", t9_qc: "A car", t9_qd: "A tree",
    t9_l1: "Text", t9_r1: "Write", t9_l2: "T", t9_r2: "Symbol", t9_l3: "Font", t9_r3: "Style",
    t10_title: "Border", t10_text: "Put a nice frame around your image.", t10_inst: "Match the pairs:", t10_h1: "Enclose.", t10_h2: "Decoration.", t10_q: "What is a 'Border'?", t10_qa: "A frame", t10_qb: "A hole", t10_qc: "A spot", t10_qd: "A mistake",
    t10_l1: "Border", t10_r1: "Outside", t10_l2: "Line", t10_r2: "Edge", t10_l3: "Deko", t10_r3: "Nice",
    t11_title: "Copy Element", t11_text: "You can copy parts of the image and paste them elsewhere.", t11_inst: "Match the pairs:", t11_h1: "Double.", t11_h2: "Stamp.", t11_q: "What do you do when copying?", t11_qa: "Double a part", t11_qb: "Delete everything", t11_qc: "Rotate the image", t11_qd: "Sing",
    t11_l1: "Copy", t11_r1: "Two", t11_l2: "Stamp", t11_r2: "Tool", t11_l3: "Source", t11_r3: "Start",
    t12_title: "Retouch", t12_text: "Remove small mistakes or spots in the image.", t12_inst: "Match the pairs:", t12_h1: "Clean up.", t12_h2: "Band-aid symbol.", t12_q: "What does retouching do?", t12_qa: "Correct small mistakes", t12_qb: "Destroy the image", t12_qc: "Cook food", t12_qd: "Run",
    t12_l1: "Retouch", t12_r1: "Heal", t12_l2: "Band-aid", t12_r2: "Symbol", t12_l3: "Spot", t12_r3: "Gone",
    t13_title: "Layers", t13_text: "Work with several layers on top of each other.", t13_inst: "Match the pairs:", t13_h1: "Stack.", t13_h2: "On top of each other.", t13_q: "What are layers?", t13_qa: "Layers in the image", t13_qb: "Stairs", t13_qc: "Colors", t13_qd: "Brushes",
    t13_l1: "Layer", t13_r1: "Level", t13_l2: "Stack", t13_r2: "Top/Bottom", t13_l3: "Visible", t13_r3: "Eye",
    t14_title: "Save (JPG/PNG)", t14_text: "Save your finished work as a JPG or PNG file.", t14_inst: "Match the pairs:", t14_h1: "Finish.", t14_h2: "Choose format.", t14_q: "What are JPG and PNG?", t14_qa: "Image formats", t14_qb: "Ice cream flavors", t14_qc: "Car brands", t14_qd: "Country names",
    t14_l1: "JPG", t14_r1: "Photo", t14_l2: "PNG", t14_r2: "Graphic", t14_l3: "Save", t14_r3: "Keep",
    t15_title: "Editor Master", t15_text: "You can now edit images like a pro!", t15_inst: "Match the pairs:", t15_h1: "Great job!", t15_h2: "Learned everything.", t15_q: "What are you now?", t15_qa: "Image expert", t15_qb: "A printer", t15_qc: "A frame", t15_qd: "A paper",
    t15_l1: "Master", t15_r1: "Expert", t15_l2: "Image", t15_r2: "Design", t15_l3: "Done", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "Képszerkesztés Alapok",
    t1_title: "Kép megnyitása", t1_text: "Válassz ki egy fotót a gépedről, hogy szerkeszteni tudd.", t1_inst: "Párosítsd össze:", t1_h1: "Fájl betöltése.", t1_h2: "Indítás.", t1_q: "Mit csinálsz legelőször?", t1_qa: "Megnyitom a képet", t1_qb: "Letörlöm a gépet", t1_qc: "Lekapcsolom a lámpát", t1_qd: "Alszom",
    t1_l1: "Megnyitás", t1_r1: "Start", t1_l2: "Fájl", t1_r2: "Kép", t1_l3: "Mappa", t1_r3: "Keresés",
    t2_title: "Kivágás (Crop)", t2_text: "Vágd le a széleket, hogy csak a fontos rész maradjon.", t2_inst: "Párosítsd össze:", t2_h1: "Szélek le.", t2_h2: "Fókuszálás.", t2_q: "Mit csinál a 'Kivágás'?", t2_qa: "Levágja a kép széleit", t2_qb: "Kifesti a képet", t2_qc: "Zenét játszik", t2_qd: "Szöveget ír",
    t2_l1: "Kivágás", t2_r1: "Szélek le", t2_l2: "Olló", t2_r2: "Ikon", t2_l3: "Fókusz", t2_r3: "Közép",
    t3_title: "Méretezés", t3_text: "Tedd a képedet nagyobbá vagy kisebbé.", t3_inst: "Párosítsd össze:", t3_h1: "Méret állítás.", t3_h2: "Pixelek.", t3_q: "Mit jelent a 'Resize'?", t3_qa: "Méret megváltoztatása", t3_qb: "Szín megváltoztatása", t3_qc: "Kép törlése", t3_qd: "Név megváltoztatása",
    t3_l1: "Méret", t3_r1: "Pixelek", t3_l2: "Kicsi", t3_r2: "Email", t3_l3: "Nagy", t3_r3: "Poszter",
    t4_title: "Forgatás (Rotate)", t4_text: "Forgasd el a képet, ha az az oldalán fekszik.", t4_inst: "Párosítsd össze:", t4_h1: "Körhinta.", t4_h2: "Irányváltás.", t4_q: "Mit csinálsz forgatáskor?", t4_qa: "Megfordítom a képet", t4_qb: "Letörlöm a képet", t4_qc: "Sötétítem a képet", t4_qd: "Semmit",
    t4_l1: "Forgatás", t4_r1: "Fordítás", t4_l2: "Nyíl", t4_r2: "Kör", t4_l3: "Fok", t4_r3: "Szög",
    t5_title: "Világosítás", t5_text: "Tedd világosabbá a sötét fotót, hogy minden látsszon.", t5_inst: "Párosítsd össze:", t5_h1: "Több fény.", t5_h2: "Napocska be.", t5_q: "Mikor használsz világosítást?", t5_qa: "Ha túl sötét a kép", t5_qb: "Ha túl világos a kép", t5_qc: "Ha eltűnt a kép", t5_qd: "Mindig",
    t5_l1: "Világosabb", t5_r1: "Fény", t5_l2: "Nap", t5_r2: "Ikon", t5_l3: "Sötét", t5_r3: "Előtte",
    t6_title: "Sötétítés", t6_text: "Tedd egy kicsit sötétebbé a túl világos képet.", t6_inst: "Párosítsd össze:", t6_h1: "Kevesebb fény.", t6_h2: "Árnyék.", t6_q: "Mi történik sötétítéskor?", t6_qa: "Sötétebb lesz a kép", t6_qb: "Fehér lesz a kép", t6_qc: "Eltűnik a kép", t6_qd: "Színes lesz",
    t6_l1: "Sötétebb", t6_r1: "Árnyék", t6_l2: "Hold", t6_r2: "Ikon", t6_l3: "Világos", t6_r3: "Előtte",
    t7_title: "Színek állítása", t7_text: "Tedd élénkebbé a színeket vagy változtasd meg őket.", t7_inst: "Párosítsd össze:", t7_h1: "Színesebb legyen.", t7_h2: "Telítettség.", t7_q: "Mit változtatsz itt?", t7_qa: "A színeket", t7_qb: "A méretet", t7_qc: "A nevet", t7_qd: "A dátumot",
    t7_l1: "Szín", t7_r1: "Színes", t7_l2: "Szürke", t7_r2: "Színtelen", t7_l3: "Paletta", t7_r3: "Választék",
    t8_title: "Szűrők használata", t8_text: "A szűrőkkel gyorsan megváltoztathatod a képet, pl. fekete-fehérre.", t8_inst: "Párosítsd össze:", t8_h1: "Gyors effekt.", t8_h2: "Varázslat.", t8_q: "Mi az a szűrő?", t8_qa: "Egy kész effekt", t8_qb: "Egy tisztítószer", t8_qc: "Egy új kép", t8_qd: "Egy kamera",
    t8_l1: "Szűrő", t8_r1: "Effekt", t8_l2: "Szépia", t8_r2: "Régi", t8_l3: "F/F", t8_r3: "Szürke",
    t9_title: "Szöveg a képen", t9_text: "Írj valamit közvetlenül a képedre.", t9_inst: "Párosítsd össze:", t9_h1: "Szavak írása.", t9_h2: "T ikon.", t9_q: "Melyik ikon jelzi a szöveget?", t9_qa: "A T betű", t9_qb: "Egy kör", t9_qc: "Egy autó", t9_qd: "Egy fa",
    t9_l1: "Szöveg", t9_r1: "Írás", t9_l2: "T", t9_r2: "Ikon", t9_l3: "Betű", t9_r3: "Stílus",
    t10_title: "Keret (Border)", t10_text: "Tegyél egy szép keretet a képed köré.", t10_inst: "Párosítsd össze:", t10_h1: "Körbezárás.", t10_h2: "Díszítés.", t10_q: "Mi az a 'Border'?", t10_qa: "Egy keret", t10_qb: "Egy lyuk", t10_qc: "Egy folt", t10_qd: "Egy hiba",
    t10_l1: "Keret", t10_r1: "Kívül", t10_l2: "Vonal", t10_r2: "Szél", t10_l3: "Dísz", t10_r3: "Szép",
    t11_title: "Elem másolása", t11_text: "Másolhatsz részeket a képből és máshova teheted őket.", t11_inst: "Párosítsd össze:", t11_h1: "Duplázás.", t11_h2: "Pecsét.", t11_q: "Mit csinálsz másoláskor?", t11_qa: "Megduplázok egy részt", t11_qb: "Mindent törlök", t11_qc: "Elforgatom a képet", t11_qd: "Énekelek",
    t11_l1: "Másolás", t11_r1: "Kettő", t11_l2: "Pecsét", t11_r2: "Eszköz", t11_l3: "Forrás", t11_r3: "Start",
    t12_title: "Retusálás", t12_text: "Tüntesd el az apró hibákat vagy foltokat a képről.", t12_inst: "Párosítsd össze:", t12_h1: "Takarítás.", t12_h2: "Tapasz ikon.", t12_q: "Mit csinál a retusálás?", t12_qa: "Apró hibákat javít", t12_qb: "Tönkreteszi a képet", t12_qc: "Főz", t12_qd: "Fut",
    t12_l1: "Retus", t12_r1: "Javítás", t12_l2: "Tapasz", t12_r2: "Ikon", t12_l3: "Folt", t12_r3: "Eltűnik",
    t13_title: "Rétegek (Layers)", t13_text: "Dolgozz több réteggel egymás felett.", t13_inst: "Párosítsd össze:", t13_h1: "Torony.", t13_h2: "Egymáson.", t13_q: "Mik azok a rétegek?", t13_qa: "Szintek a képen", t13_qb: "Lépcsők", t13_qc: "Színek", t13_qd: "Ecsetek",
    t13_l1: "Réteg", t13_r1: "Szint", t13_l2: "Torony", t13_r2: "Alul/Felül", t13_l3: "Látható", t13_r3: "Szem",
    t14_title: "Mentés (JPG/PNG)", t14_text: "Mentsd el a kész művedet JPG vagy PNG fájlként.", t14_inst: "Párosítsd össze:", t14_h1: "Befejezés.", t14_h2: "Formátum.", t14_q: "Mi az a JPG és PNG?", t14_qa: "Képformátumok", t14_qb: "Fagyi ízek", t14_qc: "Autómárkák", t14_qd: "Országnevek",
    t14_l1: "JPG", t14_r1: "Fotó", t14_l2: "PNG", t14_r2: "Grafika", t14_l3: "Mentés", t14_r3: "Megtartás",
    t15_title: "Szerkesztő Mester", t15_text: "Most már profi módon tudsz képeket szerkeszteni!", t15_inst: "Párosítsd össze:", t15_h1: "Szuper munka!", t15_h2: "Mindent megtanultál.", t15_q: "Mi vagy te most?", t15_qa: "Képszakértő", t15_qb: "Egy nyomtató", t15_qc: "Egy keret", t15_qd: "Egy papír",
    t15_l1: "Mester", t15_r1: "Szakértő", t15_l2: "Kép", t15_r2: "Dizájn", t15_l3: "Kész", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Editare Imagine Baze",
    t1_title: "Deschide imaginea", t1_text: "Alege o fotografie din calculatorul tău pentru a o edita.", t1_inst: "Potrivește perechile:", t1_h1: "Încarcă fișier.", t1_h2: "Start.", t1_q: "Ce faci mai întâi?", t1_qa: "Deschid imaginea", t1_qb: "Șterg calculatorul", t1_qc: "Sting lumina", t1_qd: "Dorm",
    t1_l1: "Deschide", t1_r1: "Start", t1_l2: "Fișier", t1_r2: "Imagine", t1_l3: "Dosar", t1_r3: "Căutare",
    t2_title: "Decupare (Crop)", t2_text: "Taie marginile pentru a rămâne doar partea importantă.", t2_inst: "Potrivește perechile:", t2_h1: "Margini jos.", t2_h2: "Focalizare.", t2_q: "Ce face 'Decuparea'?", t2_qa: "Taie marginile imaginii", t2_qb: "Pictează imaginea", t2_qc: "Pune muzică", t2_qd: "Scrie text",
    t2_l1: "Decupare", t2_r1: "Margini", t2_l2: "Foarfecă", t2_r2: "Simbol", t2_l3: "Focus", t2_r3: "Mijloc",
    t3_title: "Redimensionare", t3_text: "Fă imaginea ta mai mare sau mai mică.", t3_inst: "Potrivește perechile:", t3_h1: "Reglare mărime.", t3_h2: "Pixeli.", t3_q: "Ce înseamnă 'Resize'?", t3_qa: "Schimbarea mărimii", t3_qb: "Schimbarea culorii", t3_qc: "Ștergerea imaginii", t3_qd: "Schimbarea numelui",
    t3_l1: "Mărime", t3_r1: "Pixeli", t3_l2: "Mic", t3_r2: "Email", t3_l3: "Mare", t3_r3: "Poster",
    t4_title: "Rotire (Rotate)", t4_text: "Rotește imaginea dacă este culcată pe o parte.", t4_inst: "Potrivește perechile:", t4_h1: "Carusel.", t4_h2: "Schimbare direcție.", t4_q: "Ce faci la rotire?", t4_qa: "Întorc imaginea", t4_qb: "Șterg imaginea", t4_qc: "Întunec imaginea", t4_qd: "Nimic",
    t4_l1: "Rotire", t4_r1: "Întoarcere", t4_l2: "Săgeată", t4_r2: "Cerc", t4_l3: "Grade", t4_r3: "Unghi",
    t5_title: "Luminare", t5_text: "Fă o fotografie prea întunecată mai luminoasă.", t5_inst: "Potrivește perechile:", t5_h1: "Mai multă lumină.", t5_h2: "Soare pornit.", t5_q: "Când folosești luminarea?", t5_qa: "Când imaginea e prea întunecată", t5_qb: "Când imaginea e prea luminoasă", t5_qc: "Când a dispărut imaginea", t5_qd: "Întotdeauna",
    t5_l1: "Luminos", t5_r1: "Lumină", t5_l2: "Soare", t5_r2: "Simbol", t5_l3: "Întunecat", t5_r3: "Înainte",
    t6_title: "Întunecare", t6_text: "Fă o imagine prea luminoasă puțin mai întunecată.", t6_inst: "Potrivește perechile:", t6_h1: "Mai puțină lumină.", t6_h2: "Umbră.", t6_q: "Ce se întâmplă la întunecare?", t6_qa: "Imaginea devine mai întunecată", t6_qb: "Imaginea devine albă", t6_qc: "Imaginea dispare", t6_qd: "Devine colorată",
    t6_l1: "Întunecat", t6_r1: "Umbră", t6_l2: "Lună", t6_r2: "Simbol", t6_l3: "Luminos", t6_r3: "Înainte",
    t7_title: "Reglare culori", t7_text: "Fă culorile mai vii sau schimbă-le de tot.", t7_inst: "Potrivește perechile:", t7_h1: "Mai colorat.", t7_h2: "Saturație.", t7_q: "Ce schimbi aici?", t7_qa: "Culorile", t7_qb: "Mărimea", t7_qc: "Numele", t7_qd: "Data",
    t7_l1: "Culoare", t7_r1: "Colorat", t7_l2: "Gri", t7_r2: "Fără culoare", t7_l3: "Paletă", t7_r3: "Selecție",
    t8_title: "Folosire filtre", t8_text: "Cu filtre poți schimba rapid imaginea, de ex. în alb-negru.", t8_inst: "Potrivește perechile:", t8_h1: "Efect rapid.", t8_h2: "Magie.", t8_q: "Ce este un filtru?", t8_qa: "Un efect gata făcut", t8_qb: "Un detergent", t8_qc: "O imagine nouă", t8_qd: "O cameră",
    t8_l1: "Filtru", t8_r1: "Efect", t8_l2: "Sepia", t8_r2: "Vechi", t8_l3: "A/N", t8_r3: "Gri",
    t9_title: "Text pe imagine", t9_text: "Scrie ceva direct pe imaginea ta.", t9_inst: "Potrivește perechile:", t9_h1: "Scriere cuvinte.", t9_h2: "Simbol T.", t9_q: "Ce simbol indică textul?", t9_qa: "Litera T", t9_qb: "Un cerc", t9_qc: "O mașină", t9_qd: "Un copac",
    t9_l1: "Text", t9_r1: "Scriere", t9_l2: "T", t9_r2: "Simbol", t9_l3: "Font", t9_r3: "Stil",
    t10_title: "Ramă (Border)", t10_text: "Pune o ramă frumoasă în jurul imaginii tale.", t10_inst: "Potrivește perechile:", t10_h1: "Încadrare.", t10_h2: "Decorare.", t10_q: "Ce este un 'Border'?", t10_qa: "O ramă", t10_qb: "O gaură", t10_qc: "O pată", t10_qd: "O greșeală",
    t10_l1: "Ramă", t10_r1: "Exterior", t10_l2: "Linie", t10_r2: "Margine", t10_l3: "Decor", t10_r3: "Frumos",
    t11_title: "Copiere element", t11_text: "Poți copia părți din imagine și să le pui în altă parte.", t11_inst: "Potrivește perechile:", t11_h1: "Dublare.", t11_h2: "Ștampilă.", t11_q: "Ce faci la copiere?", t11_qa: "Dublez o parte", t11_qb: "Șterg tot", t11_qc: "Rotesc imaginea", t11_qd: "Cânt",
    t11_l1: "Copiere", t11_r1: "Doi", t11_l2: "Ștampilă", t11_r2: "Unealtă", t11_l3: "Sursă", t11_r3: "Start",
    t12_title: "Retușare", t12_text: "Elimină micile greșeli sau pete din imagine.", t12_inst: "Potrivește perechile:", t12_h1: "Curățenie.", t12_h2: "Simbol plasture.", t12_q: "Ce face retușarea?", t12_qa: "Repară mici greșeli", t12_qb: "Distruge imaginea", t12_qc: "Gătește", t12_qd: "Fuge",
    t12_l1: "Retuș", t12_r1: "Reparare", t12_l2: "Plasture", t12_r2: "Simbol", t12_l3: "Pată", t12_r3: "Dispare",
    t13_title: "Straturi (Layers)", t13_text: "Lucrează cu mai multe straturi unul peste altul.", t13_inst: "Potrivește perechile:", t13_h1: "Turn.", t13_h2: "Unul peste altul.", t13_q: "Ce sunt straturile?", t13_qa: "Niveluri în imagine", t13_qb: "Scări", t13_qc: "Culori", t13_qd: "Pensule",
    t13_l1: "Strat", t13_r1: "Nivel", t13_l2: "Turn", t13_r2: "Jos/Sus", t13_l3: "Vizibil", t13_r3: "Ochi",
    t14_title: "Salvare (JPG/PNG)", t14_text: "Salvează lucrarea terminată ca fișier JPG sau PNG.", t14_inst: "Potrivește perechile:", t14_h1: "Finalizare.", t14_h2: "Format.", t14_q: "Ce sunt JPG și PNG?", t14_qa: "Formate de imagine", t14_qb: "Arome de înghețată", t14_qc: "Mărci de mașini", t14_qd: "Nume de țări",
    t14_l1: "JPG", t14_r1: "Foto", t14_l2: "PNG", t14_r2: "Grafică", t14_l3: "Salvare", t14_r3: "Păstrare",
    t15_title: "Maestru Editor", t15_text: "Acum poți edita imagini ca un profesionist!", t15_inst: "Potrivește perechile:", t15_h1: "Bravo!", t15_h2: "Ai învățat totul.", t15_q: "Ce ești acum?", t15_qa: "Expert imagini", t15_qb: "O imprimantă", t15_qc: "O ramă", t15_qd: "O hârtie",
    t15_l1: "Maestru", t15_r1: "Expert", t15_l2: "Imagine", t15_r2: "Design", t15_l3: "Gata", t15_r3: "Victorie"
  }
};

export const INFO_K2_I5_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["📂", "✂️", "📏", "🔄", "☀️", "🌑", "🌈", "🪄", "font", "🖼️", "👯", "🩹", "🥞", "💾", "🏆"];
  const colors = ["#FFC107", "#F44336", "#2196F3", "#4CAF50", "#FFEB3B", "#37474F", "#E91E63", "#9C27B0", "#607D8B", "#795548", "#00BCD4", "#8BC34A", "#673AB7", "#FF5722", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

