import type { PoolTopicDef } from "./types";

export const INFO_K4_I9_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Abschlussprojekt — Code Kids Meister",
    t1_title: "Projektplanung", t1_text: "Bevor du programmierst, plane dein Projekt: Was willst du erreichen und welche Teile brauchst du?", t1_inst: "Verbinde die Paare:", t1_h1: "Vorbereitung.", t1_h2: "Schritt für Schritt.", t1_q: "Was macht man bei der Projektplanung?", t1_qa: "Ziele und Schritte festlegen", t1_qb: "Sofort alles löschen", t1_qc: "Nur schlafen", t1_qd: "Eis essen",
    t1_l1: "Planung", t1_r1: "Vorbereitung", t1_l2: "Ziel", t1_r2: "Ergebnis", t1_l3: "Schritte", t1_r3: "Ablauf",
    t2_title: "Python Mini-Projekt", t2_text: "Erstelle ein kleines Programm in Python, zum Beispiel ein Quiz oder einen Taschenrechner.", t2_inst: "Verbinde die Paare:", t2_h1: "Eigener Code.", t2_h2: "Python-Power.", t2_q: "Was ist ein gutes Python-Projekt?", t2_qa: "Ein Quiz-Spiel", t2_qb: "Ein Papierflieger", t2_qc: "Ein Apfel", t2_qd: "Ein Schuh",
    t2_l1: "Python", t2_r1: "Code", t2_l2: "Quiz", t2_r2: "Fragen", t2_l3: "Logik", t2_r3: "Ablauf",
    t3_title: "Webseiten-Projekt", t3_text: "Kombiniere HTML, CSS und JavaScript, um deine eigene Webseite zu bauen.", t3_inst: "Verbinde die Paare:", t3_h1: "Web-Entwicklung.", t3_h2: "Online-Präsenz.", t3_q: "Welche Sprachen braucht eine Webseite?", t3_qa: "HTML, CSS, JS", t3_qb: "Deutsch und Englisch", t3_qc: "Nur Bilder", t3_qd: "Keine",
    t3_l1: "HTML", t3_r1: "Struktur", t3_l2: "CSS", t3_r2: "Design", t3_l3: "JS", t3_r3: "Funktion",
    t4_title: "Spiele-Projekt", t4_text: "Entwickle ein kleines Spiel in Scratch oder Python, bei dem man Punkte sammeln kann.", t4_inst: "Verbinde the Paare:", t4_h1: "Game Design.", t4_h2: "Spielspaß.", t4_q: "Was braucht jedes Spiel?", t4_qa: "Regeln und Ziele", t4_qb: "Einen echten Ball", t4_qc: "Viel Wasser", t4_qd: "Einen Fernseher",
    t4_l1: "Spiel", t4_r1: "Game", t4_l2: "Score", t4_r2: "Punkte", t4_l3: "Level", t4_r3: "Abschnitt",
    t5_title: "Teamarbeit", t5_text: "Große Projekte entstehen oft im Team, wo jeder eine bestimmte Aufgabe übernimmt.", t5_inst: "Verbinde die Paare:", t5_h1: "Zusammenarbeit.", t5_h2: "Gemeinsam stark.", t5_q: "Was ist wichtig im Team?", t5_qa: "Gute Kommunikation", t5_qb: "Dass einer alles macht", t5_qc: "Dass niemand redet", t5_qd: "Streiten",
    t5_l1: "Team", t5_r1: "Gruppe", t5_l2: "Rolle", t5_r2: "Aufgabe", t5_l3: "Hilfe", t5_r3: "Support",
    t6_title: "Versionskontrolle", t6_text: "Mit Git kannst du verschiedene Versionen deines Codes speichern und zurückspringen.", t6_inst: "Verbinde die Paare:", t6_h1: "Code-Verwaltung.", t6_h2: "Sicherung.", t6_q: "Was macht Git?", t6_qa: "Speichert Code-Änderungen", t6_qb: "Löscht den Computer", t6_qc: "Macht Fotos", t6_qd: "Spielt Musik",
    t6_l1: "Git", t6_r1: "Versionen", t6_l2: "Branch", t6_r2: "Zweig", t6_l3: "Merge", t6_r3: "Zusammenführen",
    t7_title: "Commit", t7_text: "Ein Commit ist ein Speicherpunkt in deinem Projekt mit einer kurzen Nachricht.", t7_inst: "Verbinde die Paare:", t7_h1: "Speichern.", t7_h2: "Meilenstein.", t7_q: "Was gehört zu einem Commit?", t7_qa: "Code und Nachricht", t7_qb: "Ein Video", t7_qc: "Ein Lied", t7_qd: "Ein Keks",
    t7_l1: "Commit", t7_r1: "Speichern", t7_l2: "Message", t7_r2: "Nachricht", t7_l3: "History", t7_r3: "Verlauf",
    t8_title: "GitHub", t8_text: "GitHub ist eine Online-Plattform, auf der du deinen Code speichern und teilen kannst.", t8_inst: "Verbinde die Paare:", t8_h1: "Code-Cloud.", t8_h2: "Open Source.", t8_q: "Was ist GitHub?", t8_qa: "Online-Speicher für Code", t8_qb: "Ein soziales Netzwerk für Hunde", t8_qc: "Ein Kochbuch", t8_qd: "Ein Spielzeugladen",
    t8_l1: "GitHub", t8_r1: "Plattform", t8_l2: "Repo", t8_r2: "Lager", t8_l3: "Public", t8_r3: "Öffentlich",
    t9_title: "Deployment", t9_text: "Deployment bedeutet, dein Projekt zu veröffentlichen, damit andere es nutzen können.", t9_inst: "Verbinde die Paare:", t9_h1: "Veröffentlichen.", t9_h2: "Live gehen.", t9_q: "Was bedeutet 'Deploy'?", t9_qa: "Projekt online stellen", t9_qb: "Projekt löschen", t9_qc: "Code verstecken", t9_qd: "Computer ausschalten",
    t9_l1: "Deploy", t9_r1: "Veröffentlichen", t9_l2: "Live", t9_r2: "Online", t9_l3: "User", t9_r3: "Nutzer",
    t10_title: "Dokumentation", t10_text: "In der README-Datei erklärst du, was dein Projekt macht und wie man es startet.", t10_inst: "Verbinde die Paare:", t10_h1: "Beschreibung.", t10_h2: "Anleitung.", t10_q: "Wofür ist die README-Datei?", t10_qa: "Erklärung des Projekts", t10_qb: "Zum Malen", t10_qc: "Für Passwörter", t10_qd: "Zum Löschen",
    t10_l1: "README", t10_r1: "Info", t10_l2: "Doku", t10_r2: "Anleitung", t10_l3: "Text", t10_r3: "Inhalt",
    t11_title: "Präsentation", t11_text: "Stelle dein fertiges Projekt anderen vor und erkläre, wie du es gebaut hast.", t11_inst: "Verbinde die Paare:", t11_h1: "Vorstellen.", t11_h2: "Demo.", t11_q: "Was macht man bei einer Präsentation?", t11_qa: "Das Projekt zeigen", t11_qb: "Sich verstecken", t11_qc: "Nichts sagen", t11_qd: "Weglaufen",
    t11_l1: "Demo", t11_r1: "Vorführung", t11_l2: "Slides", t11_r2: "Folien", t11_l3: "Speech", t11_r3: "Vortrag",
    t12_title: "Portfolio", t12_text: "Ein Portfolio ist eine Sammlung deiner besten Arbeiten, die du zeigen kannst.", t12_inst: "Verbinde die Paare:", t12_h1: "Arbeitsproben.", t12_h2: "Erfolge.", t12_q: "Was gehört in ein Portfolio?", t12_qa: "Deine besten Projekte", t12_qb: "Deine Hausaufgaben", t12_qc: "Alte Socken", t12_qd: "Müll",
    t12_l1: "Portfolio", t12_r1: "Sammlung", t12_l2: "Showcase", t12_r2: "Ausstellung", t12_l3: "Skills", t12_r3: "Fähigkeiten",
    t13_title: "Feedback", t13_text: "Hole dir Rückmeldungen von anderen ein, um dein Projekt noch besser zu machen.", t13_inst: "Verbinde die Paare:", t13_h1: "Rückmeldung.", t13_h2: "Verbesserung.", t13_q: "Warum ist Feedback wichtig?", t13_qa: "Um zu lernen", t13_qb: "Um traurig zu sein", t13_qc: "Um aufzuhören", t13_qd: "Ist egal",
    t13_l1: "Feedback", t13_r1: "Meinung", t13_l2: "Review", t13_r2: "Prüfung", t13_l3: "Fix", t13_r3: "Verbesserung",
    t14_title: "Zukunft", t14_text: "Programmieren ist eine Superkraft – lerne immer weiter und entdecke Neues!", t14_inst: "Verbinde die Paare:", t14_h1: "Weiterlernen.", t14_h2: "Ausblick.", t14_q: "Was kannst du jetzt tun?", t14_qa: "Weiter programmieren", t14_qb: "Alles vergessen", t14_qc: "Den Computer wegwerfen", t14_qd: "Nichts",
    t14_l1: "Zukunft", t14_r1: "Lernen", t14_l2: "Karriere", t14_r2: "Beruf", t14_l3: "Spaß", t14_r3: "Freude",
    t15_title: "Code Kids Meister", t15_text: "Herzlichen Glückwunsch! Du hast den Code Kids Kurs erfolgreich abgeschlossen!", t15_inst: "Verbinde die Paare:", t15_h1: "Sieg.", t15_h2: "Abschluss.", t15_q: "Was bist du jetzt?", t15_qa: "Code Kids Meister", t15_qb: "Ein Anfänger", t15_qc: "Ein Roboter", t15_qd: "Ein Baum",
    t15_l1: "Meister", t15_r1: "Profi", t15_l2: "Diplom", t15_r2: "Zertifikat", t15_l3: "Sieg", t15_r3: "Erfolg"
  },
  en: {
    explorer_title: "Final Project — Code Kids Master",
    t1_title: "Project Planning", t1_text: "Before you code, plan your project: What do you want to achieve and what parts do you need?", t1_inst: "Match the pairs:", t1_h1: "Preparation.", t1_h2: "Step by step.", t1_q: "What do you do in project planning?", t1_qa: "Set goals and steps", t1_qb: "Delete everything immediately", t1_qc: "Just sleep", t1_qd: "Eat ice cream",
    t1_l1: "Planning", t1_r1: "Preparation", t1_l2: "Goal", t1_r2: "Result", t1_l3: "Steps", t1_r3: "Process",
    t2_title: "Python Mini-Project", t2_text: "Create a small program in Python, for example, a quiz or a calculator.", t2_inst: "Match the pairs:", t2_h1: "Own code.", t2_h2: "Python power.", t2_q: "What is a good Python project?", t2_qa: "A quiz game", t2_qb: "A paper plane", t2_qc: "An apple", t2_qd: "A shoe",
    t2_l1: "Python", t2_r1: "Code", t2_l2: "Quiz", t2_r2: "Questions", t2_l3: "Logic", t2_r3: "Flow",
    t3_title: "Website Project", t3_text: "Combine HTML, CSS, and JavaScript to build your own website.", t3_inst: "Match the pairs:", t3_h1: "Web development.", t3_h2: "Online presence.", t3_q: "Which languages does a website need?", t3_qa: "HTML, CSS, JS", t3_qb: "German and English", t3_qc: "Only images", t3_qd: "None",
    t3_l1: "HTML", t3_r1: "Structure", t3_l2: "CSS", t3_r2: "Design", t3_l3: "JS", t3_r3: "Function",
    t4_title: "Game Project", t4_text: "Develop a small game in Scratch or Python where you can collect points.", t4_inst: "Match the pairs:", t4_h1: "Game design.", t4_h2: "Fun.", t4_q: "What does every game need?", t4_qa: "Rules and goals", t4_qb: "A real ball", t4_qc: "Lots of water", t4_qd: "A TV",
    t4_l1: "Game", t4_r1: "Play", t4_l2: "Score", t4_r2: "Points", t4_l3: "Level", t4_r3: "Stage",
    t5_title: "Teamwork", t5_text: "Large projects are often created in teams, where everyone takes on a specific task.", t5_inst: "Match the pairs:", t5_h1: "Collaboration.", t5_h2: "Stronger together.", t5_q: "What is important in a team?", t5_qa: "Good communication", t5_qb: "One person doing everything", t5_qc: "Nobody talking", t5_qd: "Fighting",
    t5_l1: "Team", t5_r1: "Group", t5_l2: "Role", t5_r2: "Task", t5_l3: "Help", t5_r3: "Support",
    t6_title: "Version Control", t6_text: "With Git, you can save different versions of your code and jump back.", t6_inst: "Match the pairs:", t6_h1: "Code management.", t6_h2: "Backup.", t6_q: "What does Git do?", t6_qa: "Saves code changes", t6_qb: "Deletes the computer", t6_qc: "Takes photos", t6_qd: "Plays music",
    t6_l1: "Git", t6_r1: "Versions", t6_l2: "Branch", t6_r2: "Branch", t6_l3: "Merge", t6_r3: "Combine",
    t7_title: "Commit", t7_text: "A commit is a save point in your project with a short message.", t7_inst: "Match the pairs:", t7_h1: "Saving.", t7_h2: "Milestone.", t7_q: "What belongs to a commit?", t7_qa: "Code and message", t7_qb: "A video", t7_qc: "A song", t7_qd: "A cookie",
    t7_l1: "Commit", t7_r1: "Save", t7_l2: "Message", t7_r2: "Note", t7_l3: "History", t7_r3: "Log",
    t8_title: "GitHub", t8_text: "GitHub is an online platform where you can store and share your code.", t8_inst: "Match the pairs:", t8_h1: "Code cloud.", t8_h2: "Open source.", t8_q: "What is GitHub?", t8_qa: "Online storage for code", t8_qb: "A social network for dogs", t8_qc: "A cookbook", t8_qd: "A toy store",
    t8_l1: "GitHub", t8_r1: "Platform", t8_l2: "Repo", t8_r2: "Storage", t8_l3: "Public", t8_r3: "Open",
    t9_title: "Deployment", t9_text: "Deployment means publishing your project so others can use it.", t9_inst: "Match the pairs:", t9_h1: "Publishing.", t9_h2: "Going live.", t9_q: "What does 'deploy' mean?", t9_qa: "Putting project online", t9_qb: "Deleting project", t9_qc: "Hiding code", t9_qd: "Turning off computer",
    t9_l1: "Deploy", t9_r1: "Publish", t9_l2: "Live", t9_r2: "Online", t9_l3: "User", t9_r3: "User",
    t10_title: "Documentation", t10_text: "In the README file, you explain what your project does and how to start it.", t10_inst: "Match the pairs:", t10_h1: "Description.", t10_h2: "Instructions.", t10_q: "What is the README file for?", t10_qa: "Explaining the project", t10_qb: "For painting", t10_qc: "For passwords", t10_qd: "For deleting",
    t10_l1: "README", t10_r1: "Info", t10_l2: "Docs", t10_r2: "Guide", t10_l3: "Text", t10_r3: "Content",
    t11_title: "Presentation", t11_text: "Present your finished project to others and explain how you built it.", t11_inst: "Match the pairs:", t11_h1: "Introducing.", t11_h2: "Demo.", t11_q: "What do you do in a presentation?", t11_qa: "Show the project", t11_qb: "Hide yourself", t11_qc: "Say nothing", t11_qd: "Run away",
    t11_l1: "Demo", t11_r1: "Show", t11_l2: "Slides", t11_r2: "Pages", t11_l3: "Speech", t11_r3: "Talk",
    t12_title: "Portfolio", t12_text: "A portfolio is a collection of your best work that you can show.", t12_inst: "Match the pairs:", t12_h1: "Work samples.", t12_h2: "Successes.", t12_q: "What goes into a portfolio?", t12_qa: "Your best projects", t12_qb: "Your homework", t12_qc: "Old socks", t12_qd: "Trash",
    t12_l1: "Portfolio", t12_r1: "Collection", t12_l2: "Showcase", t12_r2: "Exhibition", t12_l3: "Skills", t12_r3: "Abilities",
    t13_title: "Feedback", t13_text: "Get feedback from others to make your project even better.", t13_inst: "Match the pairs:", t13_h1: "Response.", t13_h2: "Improvement.", t13_q: "Why is feedback important?", t13_qa: "To learn", t13_qb: "To be sad", t13_qc: "To quit", t13_qd: "It doesn't matter",
    t13_l1: "Feedback", t13_r1: "Opinion", t13_l2: "Review", t13_r2: "Check", t13_l3: "Fix", t13_r3: "Improvement",
    t14_title: "Future", t14_text: "Programming is a superpower – keep learning and discover new things!", t14_inst: "Match the pairs:", t14_h1: "Keep learning.", t14_h2: "Outlook.", t14_q: "What can you do now?", t14_qa: "Keep programming", t14_qb: "Forget everything", t14_qc: "Throw away computer", t14_qd: "Nothing",
    t14_l1: "Future", t14_r1: "Learning", t14_l2: "Career", t14_r2: "Job", t14_l3: "Fun", t14_r3: "Joy",
    t15_title: "Code Kids Master", t15_text: "Congratulations! You have successfully completed the Code Kids course!", t15_inst: "Match the pairs:", t15_h1: "Victory.", t15_h2: "Completion.", t15_q: "What are you now?", t15_qa: "Code Kids Master", t15_qb: "A beginner", t15_qc: "A robot", t15_qd: "A tree",
    t15_l1: "Master", t15_r1: "Pro", t15_l2: "Diploma", t15_r2: "Certificate", t15_l3: "Victory", t15_r3: "Success"
  },
  hu: {
    explorer_title: "Záró projekt — Code Kids mester",
    t1_title: "Projekt tervezés", t1_text: "Mielőtt kódolnál, tervezd meg: mit akarsz elérni, milyen részekből áll.", t1_inst: "Párosítsd össze:", t1_h1: "Előkészület.", t1_h2: "Lépésről lépésre.", t1_q: "Mit csinálunk a projekt tervezéskor?", t1_qa: "Célokat és lépéseket határozunk meg", t1_qb: "Azonnal törlünk mindent", t1_qc: "Csak alszunk", t1_qd: "Fagyizunk",
    t1_l1: "Tervezés", t1_r1: "Előkészítés", t1_l2: "Cél", t1_r2: "Eredmény", t1_l3: "Lépések", t1_r3: "Folyamat",
    t2_title: "Python mini-projekt", t2_text: "Készíts egy mini programot: kvíz, számológép vagy véletlen-vicc generátor.", t2_inst: "Párosítsd össze:", t2_h1: "Saját kód.", t2_h2: "Python erő.", t2_q: "Mi egy jó Python projekt?", t2_qa: "Egy kvíz játék", t2_qb: "Egy papírrepülő", t2_qc: "Egy alma", t2_qd: "Egy cipő",
    t2_l1: "Python", t2_r1: "Kód", t2_l2: "Kvíz", t2_r2: "Kérdések", t2_l3: "Logika", t2_r3: "Menet",
    t3_title: "Webhely projekt", t3_text: "HTML+CSS+JS együtt: készítsd el a saját weboldaladat.", t3_inst: "Párosítsd össze:", t3_h1: "Webfejlesztés.", t3_h2: "Online jelenlét.", t3_q: "Milyen nyelvek kellenek egy weboldalhoz?", t3_qa: "HTML, CSS, JS", t3_qb: "Magyar és angol", t3_qc: "Csak képek", t3_qd: "Semmilyen",
    t3_l1: "HTML", t3_r1: "Szerkezet", t3_l2: "CSS", t3_r2: "Dizájn", t3_l3: "JS", t3_r3: "Működés",
    t4_title: "Játék projekt", t4_text: "Készíts egy kis játékot Scratch-ben vagy Pythonban, ahol pontokat lehet gyűjteni.", t4_inst: "Párosítsd össze:", t4_h1: "Játéktervezés.", t4_h2: "Szórakozás.", t4_q: "Mi kell minden játékhoz?", t4_qa: "Szabályok és célok", t4_qb: "Egy igazi labda", t4_qc: "Sok víz", t4_qd: "Egy tévé",
    t4_l1: "Játék", t4_r1: "Game", t4_l2: "Pontszám", t4_r2: "Score", t4_l3: "Szint", t4_r3: "Level",
    t5_title: "Csapatmunka", t5_text: "A nagy projektek gyakran csapatban készülnek, ahol mindenkinek megvan a feladata.", t5_inst: "Párosítsd össze:", t5_h1: "Együttműködés.", t5_h2: "Együtt erősebbek vagyunk.", t5_q: "Mi fontos a csapatban?", t5_qa: "Jó kommunikáció", t5_qb: "Hogy egyvalaki csináljon mindent", t5_qc: "Hogy senki ne beszéljen", t5_qd: "Veszekedés",
    t5_l1: "Csapat", t5_r1: "Csoport", t5_l2: "Szerep", t5_r2: "Feladat", t5_l3: "Segítség", t5_r3: "Támogatás",
    t6_title: "Verziókezelés", t6_text: "A git egy verziókezelő — minden változtatásodat elmenti, visszaléphetsz.", t6_inst: "Párosítsd össze:", t6_h1: "Kódkezelés.", t1_h2: "Mentés.", t6_q: "Mit csinál a git?", t6_qa: "Menti a kód változásait", t6_qb: "Törli a számítógépet", t6_qc: "Fotókat készít", t6_qd: "Zenét játszik",
    t6_l1: "Git", t6_r1: "Verziók", t6_l2: "Branch", t6_r2: "Ág", t6_l3: "Merge", t6_r3: "Összevonás",
    t7_title: "Commit", t7_text: "A commit egy mentési pont a kódodban — névvel és üzenettel.", t7_inst: "Párosítsd össze:", t7_h1: "Mentés.", t7_h2: "Mérföldkő.", t7_q: "Mi tartozik egy commit-hoz?", t7_qa: "Kód és üzenet", t7_qb: "Egy videó", t7_qc: "Egy dal", t7_qd: "Egy süti",
    t7_l1: "Commit", t7_r1: "Mentés", t7_l2: "Üzenet", t7_r2: "Message", t7_l3: "History", t7_r3: "Történet",
    t8_title: "GitHub", t8_text: "A GitHub online tárhely a kódodnak — mások is megnézhetik, segíthetnek.", t8_inst: "Párosítsd össze:", t8_h1: "Kód-felhő.", t8_h2: "Nyílt forráskód.", t8_q: "Mi az a GitHub?", t8_qa: "Online tárhely kódoknak", t8_qb: "Közösségi oldal kutyáknak", t8_qc: "Egy szakácskönyv", t8_qd: "Egy játékbolt",
    t8_l1: "GitHub", t8_r1: "Platform", t8_l2: "Repo", t8_r2: "Raktár", t8_l3: "Public", t8_r3: "Nyilvános",
    t9_title: "Közzététel", t9_text: "A deploy azt jelenti, hogy közzéteszed a projektedet, hogy mások is használhassák.", t9_inst: "Párosítsd össze:", t9_h1: "Publikálás.", t9_h2: "Élesítés.", t9_q: "Mit jelent a 'deploy'?", t9_qa: "Projekt online tétele", t9_qb: "Projekt törlése", t9_qc: "Kód elrejtése", t9_qd: "Gép kikapcsolása",
    t9_l1: "Deploy", t9_r1: "Közzététel", t9_l2: "Live", t9_r2: "Éles", t9_l3: "User", t9_r3: "Felhasználó",
    t10_title: "Dokumentáció", t10_text: "A README fájl leírja a projektedet — mit csinál, hogyan futtasd.", t10_inst: "Párosítsd össze:", t10_h1: "Leírás.", t10_h2: "Útmutató.", t10_q: "Mire jó a README fájl?", t10_qa: "A projekt leírására", t10_qb: "Rajzolásra", t10_qc: "Jelszavaknak", t10_qd: "Törlésre",
    t10_l1: "README", t10_r1: "Infó", t10_l2: "Doku", t10_r2: "Leírás", t10_l3: "Szöveg", t10_r3: "Tartalom",
    t11_title: "Prezentáció", t11_text: "Mutasd be a kész projektedet másoknak, és magyarázd el, hogyan készült.", t11_inst: "Párosítsd össze:", t11_h1: "Bemutatás.", t11_h2: "Demó.", t11_q: "Mit csinálunk prezentációkor?", t11_qa: "Megmutatjuk a projektet", t11_qb: "Elbújunk", t11_qc: "Nem mondunk semmit", t11_qd: "Elszaladunk",
    t11_l1: "Demó", t11_r1: "Bemutató", t11_l2: "Diák", t11_r2: "Slides", t11_l3: "Beszéd", t11_r3: "Előadás",
    t12_title: "Portfolio", t12_text: "A portfolio munkáid gyűjteménye — amit megmutathatsz másoknak.", t12_inst: "Párosítsd össze:", t12_h1: "Munkák gyűjteménye.", t12_h2: "Sikerek.", t12_q: "Mi kerül a portfólióba?", t12_qa: "A legjobb projektjeid", t12_qb: "A házi feladataid", t12_qc: "Régi zoknik", t12_qd: "Szemét",
    t12_l1: "Portfolio", t12_r1: "Gyűjtemény", t12_l2: "Showcase", t12_r2: "Bemutató", t12_l3: "Skills", t12_r3: "Képességek",
    t13_title: "Visszajelzés", t13_text: "Kérj véleményt másoktól, hogy még jobbá tudd tenni a projektedet.", t13_inst: "Párosítsd össze:", t13_h1: "Vélemény.", t13_h2: "Fejlődés.", t13_q: "Miért fontos a visszajelzés?", t13_qa: "Hogy tanuljunk belőle", t13_qb: "Hogy szomorúak legyünk", t13_qc: "Hogy abbahagyjuk", t13_qd: "Nem számít",
    t13_l1: "Feedback", t13_r1: "Vélemény", t13_l2: "Review", t13_r2: "Átnézés", t13_l3: "Fix", t13_r3: "Javítás",
    t14_title: "Jövő", t14_text: "A programozás egy szupererő — tanulj tovább és fedezz fel újdonságokat!", t14_inst: "Párosítsd össze:", t14_h1: "Tanulj tovább.", t14_h2: "Kilátások.", t14_q: "Mit tehetsz most?", t14_qa: "Tanulsz tovább programozni", t14_qb: "Mindent elfelejtesz", t14_qc: "Kidobod a gépet", t14_qd: "Semmit",
    t14_l1: "Jövő", t14_r1: "Tanulás", t14_l2: "Karrier", t14_r2: "Szakma", t14_l3: "Móka", t14_r3: "Öröm",
    t15_title: "Code Kids mester", t15_text: "Gratulálunk! Most már tudsz kódolni, weboldalt készíteni, robotokat vezérelni és MI-t érteni!", t15_inst: "Párosítsd össze:", t15_h1: "Győzelem.", t15_h2: "Befejezés.", t15_q: "Mi vagy te most?", t15_qa: "Code Kids mester", t15_qb: "Egy kezdő", t15_qc: "Egy robot", t15_qd: "Egy fa",
    t15_l1: "Mester", t15_r1: "Profi", t15_l2: "Diploma", t15_r2: "Oklevél", t15_l3: "Siker", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Proiect final — Code Kids maestru",
    t1_title: "Planificare proiect", t1_text: "Înainte de a coda, planifică proiectul: ce vrei să obții și de ce părți ai nevoie?", t1_inst: "Potrivește perechile:", t1_h1: "Pregătire.", t1_h2: "Pas cu pas.", t1_q: "Ce faci la planificarea proiectului?", t1_qa: "Stabilești scopuri și pași", t1_qb: "Ștergi tot imediat", t1_qc: "Doar dormi", t1_qd: "Mănânci înghețată",
    t1_l1: "Planificare", t1_r1: "Pregătire", t1_l2: "Scop", t1_r2: "Rezultat", t1_l3: "Pași", t1_r3: "Proces",
    t2_title: "Mini-proiect Python", t2_text: "Creează un mic program în Python, de exemplu un quiz sau un calculator.", t2_inst: "Potrivește perechile:", t2_h1: "Cod propriu.", t2_h2: "Putere Python.", t2_q: "Ce este un proiect Python bun?", t2_qa: "Un joc quiz", t2_qb: "Un avion de hârtie", t2_qc: "Un măr", t2_qd: "Un pantof",
    t2_l1: "Python", t2_r1: "Cod", t2_l2: "Quiz", t2_r2: "Întrebări", t2_l3: "Logică", t2_r3: "Flux",
    t3_title: "Proiect Website", t3_text: "Combină HTML, CSS și JS pentru a-ți construi propriul site web.", t3_inst: "Potrivește perechile:", t3_h1: "Dezvoltare web.", t3_h2: "Prezență online.", t3_q: "Ce limbaje are nevoie un site?", t3_qa: "HTML, CSS, JS", t3_qb: "Română și engleză", t3_qc: "Doar poze", t3_qd: "Niciunul",
    t3_l1: "HTML", t3_r1: "Structură", t3_l2: "CSS", t3_r2: "Design", t3_l3: "JS", t3_r3: "Funcție",
    t4_title: "Proiect Joc", t4_text: "Dezvoltă un mic joc în Scratch sau Python unde poți colecta puncte.", t4_inst: "Potrivește perechile:", t4_h1: "Design joc.", t4_h2: "Distracție.", t4_q: "Ce are nevoie orice joc?", t4_qa: "Reguli și scopuri", t4_qb: "O minge reală", t4_qc: "Multă apă", t4_qd: "Un TV",
    t4_l1: "Joc", t4_r1: "Game", t4_l2: "Scor", t4_r2: "Puncte", t4_l3: "Nivel", t4_r3: "Level",
    t5_title: "Muncă în echipă", t5_text: "Proiectele mari se fac des în echipă, unde fiecare are o sarcină specifică.", t5_inst: "Potrivește perechile:", t5_h1: "Colaborare.", t5_h2: "Mai buni împreună.", t5_q: "Ce este important în echipă?", t5_qa: "Comunicare bună", t5_qb: "Să facă unul totul", t5_qc: "Să nu vorbească nimeni", t5_qd: "Certuri",
    t5_l1: "Echipă", t5_r1: "Grup", t5_l2: "Rol", t5_r2: "Sarcină", t5_l3: "Ajutor", t5_r3: "Suport",
    t6_title: "Control versiuni", t6_text: "Cu git poți salva diferite versiuni ale codului tău și poți reveni.", t6_inst: "Potrivește perechile:", t6_h1: "Gestiune cod.", t6_h2: "Salvare.", t6_q: "Ce face git?", t6_qa: "Salvează schimbările codului", t6_qb: "Șterge calculatorul", t6_qc: "Face poze", t6_qd: "Redă muzică",
    t6_l1: "Git", t6_r1: "Versiuni", t6_l2: "Branch", t6_r2: "Ramură", t6_l3: "Merge", t6_r3: "Combinare",
    t7_title: "Commit", t7_text: "Un commit este un punct de salvare în codul tău — cu nume și mesaj.", t7_inst: "Potrivește perechile:", t7_h1: "Salvare.", t7_h2: "Etapă.", t7_q: "Ce aparține unui commit?", t7_qa: "Cod și mesaj", t7_qb: "Un video", t7_qc: "Un cântec", t7_qd: "Un biscuite",
    t7_l1: "Commit", t7_r1: "Salvare", t7_l2: "Mesaj", t7_r2: "Message", t7_l3: "Istoric", t7_r3: "History",
    t8_title: "GitHub", t8_text: "GitHub este un spațiu online pentru codul tău — alții pot vedea și ajuta.", t8_inst: "Potrivește perechile:", t8_h1: "Cloud cod.", t8_h2: "Open source.", t8_q: "Ce este GitHub?", t8_qa: "Stocare online pentru cod", t8_qb: "Rețea socială pentru câini", t8_qc: "O carte de bucate", t8_qd: "Un magazin de jucării",
    t8_l1: "GitHub", t8_r1: "Platformă", t8_l2: "Repo", t8_r2: "Depozit", t8_l3: "Public", t8_r3: "Public",
    t9_title: "Publicare", t9_text: "Deploy înseamnă să publici proiectul tău pentru ca alții să-l poată folosi.", t9_inst: "Potrivește perechile:", t9_h1: "Publicare.", t9_h2: "Lansare.", t9_q: "Ce înseamnă 'deploy'?", t9_qa: "Punerea proiectului online", t9_qb: "Ștergerea proiectului", t9_qc: "Ascunderea codului", t9_qd: "Închiderea PC-ului",
    t9_l1: "Deploy", t9_r1: "Publicare", t9_l2: "Live", t9_r2: "Activ", t9_l3: "User", t9_r3: "Utilizator",
    t10_title: "Documentație", t10_text: "Fișierul README descrie proiectul tău — ce face și cum se pornește.", t10_inst: "Potrivește perechile:", t10_h1: "Descriere.", t10_h2: "Ghid.", t10_q: "La ce e bun fișierul README?", t10_qa: "Descrierea proiectului", t10_qb: "Pentru desenat", t10_qc: "Pentru parole", t10_qd: "Pentru șters",
    t10_l1: "README", t10_r1: "Info", t10_l2: "Doc", t10_r2: "Ghid", t10_l3: "Text", t10_r3: "Conținut",
    t11_title: "Prezentare", t11_text: "Prezintă proiectul tău gata altora și explică cum l-ai construit.", t11_inst: "Potrivește perechile:", t11_h1: "Introducere.", t11_h2: "Demo.", t11_q: "Ce facem la o prezentare?", t11_qa: "Arătăm proiectul", t11_qb: "Ne ascundem", t11_qc: "Nu spunem nimic", t11_qd: "Fugim",
    t11_l1: "Demo", t11_r1: "Prezentare", t11_l2: "Slide-uri", t11_r2: "Pagini", t11_l3: "Discurs", t11_r3: "Vorbire",
    t12_title: "Portofoliu", t12_text: "Un portofoliu este o colecție cu cele mai bune lucrări ale tale.", t12_inst: "Potrivește perechile:", t12_h1: "Colecție lucrări.", t12_h2: "Succese.", t12_q: "Ce intră în portofoliu?", t12_qa: "Cele mai bune proiecte", t12_qb: "Temele tale", t12_qc: "Șosete vechi", t12_qd: "Gunoi",
    t12_l1: "Portfolio", t12_r1: "Colecție", t12_l2: "Showcase", t12_r2: "Prezentare", t12_l3: "Skills", t12_r3: "Abilități",
    t13_title: "Feedback", t13_text: "Cere părerea altora pentru a-ți face proiectul și mai bun.", t13_inst: "Potrivește perechile:", t13_h1: "Răspuns.", t13_h2: "Progres.", t13_q: "De ce e important feedback-ul?", t13_qa: "Să învățăm din el", t13_qb: "Să fim triști", t13_qc: "Să renunțăm", t13_qd: "Nu contează",
    t13_l1: "Feedback", t13_r1: "Opinie", t13_l2: "Review", t13_r2: "Verificare", t13_l3: "Fix", t13_r3: "Reparare",
    t14_title: "Viitor", t14_text: "Programarea este o superputere — învață mereu și descoperă noutăți!", t14_inst: "Potrivește perechile:", t14_h1: "Învață mai departe.", t14_h2: "Perspective.", t14_q: "Ce poți face acum?", t14_qa: "Înveți programare în continuare", t14_qb: "Uiti totul", t14_qc: "Arunci PC-ul", t14_qd: "Nimic",
    t14_l1: "Viitor", t14_r1: "Învățare", t14_l2: "Carieră", t14_r2: "Job", t14_l3: "Distracție", t14_r3: "Bucurie",
    t15_title: "Code Kids maestru", t15_text: "Felicitări! Acum știi să codezi, să faci site-uri, să conduci roboți și să înțelegi AI!", t15_inst: "Potrivește perechile:", t15_h1: "Victorie.", t15_h2: "Finalizare.", t15_q: "Ce ești acum?", t15_qa: "Code Kids maestru", t15_qb: "Un începător", t15_qc: "Un robot", t15_qd: "Un copac",
    t15_l1: "Maestru", t15_r1: "Profi", t15_l2: "Diplomă", t15_r2: "Certificat", t15_l3: "Succes", t15_r3: "Victorie"
  }
};

export const INFO_K4_I9_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["📝","🐍","🌐","🎮","👥","🌳","💾","🐙","🚀","📚","🎤","🎨","💬","🎓","🏆"];
  const colors = ["#4CAF50","#FFC107","#2196F3","#E91E63","#00BCD4","#F44336","#795548","#607D8B","#9C27B0","#3F51B5","#FF9800","#8BC34A","#00BCD4","#673AB7","#FFD700"];
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { type: "match-pairs", instruction: `t${t}_inst`, hint1: `t${t}_h1`, hint2: `t${t}_h2`,
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});
