// lib/explorerPools/informatikaK1_i4.ts
import type { PoolTopicDef } from "./types";

export const INFO_K1_I4_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Zahlen & Text",
    t1_title: "Zahlen finden", t1_text: "Suche die Zahlen 1, 2, 3 oben auf deiner Tastatur.", t1_inst: "Verbinde die Paare:", t1_h1: "Zahlen suchen.", t1_h2: "Wie alt bist du?", t1_q: "Wo sind die Zahlen meistens?", t1_qa: "Oben in einer Reihe", t1_qb: "Unter der Maus", t1_qc: "Im Bildschirm", t1_qd: "Hinter dem PC",
    t1_l1: "Eins", t1_r1: "1", t1_l2: "Zwei", t1_r2: "2", t1_l3: "Drei", t1_r3: "3",
    t2_title: "Kleine Buchstaben", t2_text: "Die meisten Buchstaben, die wir schreiben, sind klein.", t2_inst: "Verbinde die Paare:", t2_h1: "Kleine Buchstaben.", t2_h2: "abc...", t2_q: "Welcher Buchstabe ist klein?", t2_qa: "a", t2_qb: "A", t2_qc: "7", t2_qd: "!",
    t2_l1: "Klein a", t2_r1: "a", t2_l2: "Klein b", t2_r2: "b", t2_l3: "Klein c", t2_r3: "c",
    t3_title: "Große Buchstaben", t3_text: "Am Anfang eines Namens schreiben wir groß.", t3_inst: "Verbinde die Paare:", t3_h1: "Große Buchstaben.", t3_h2: "ABC...", t3_q: "Welcher Buchstabe ist groß?", t3_qa: "B", t3_qb: "b", t3_qc: "5", t3_qd: "?",
    t3_l1: "Groß A", t3_r1: "A", t3_l2: "Groß B", t3_r2: "B", t3_l3: "Groß C", t3_r3: "C",
    t4_title: "Die Leertaste", t4_text: "Die lange Taste macht eine Lücke zwischen den Wörtern.", t4_inst: "Verbinde die Paare:", t4_h1: "Abstand halten.", t4_h2: "Die längste Taste.", t4_q: "Was macht die Leertaste?", t4_qa: "Einen Abstand", t4_qb: "Alles löschen", t4_qc: "Den PC aus", t4_qd: "Ein Bild",
    t4_l1: "Leertaste", t4_r1: "Lücke", t4_l2: "Wort", t4_r2: "Abstand", t4_l3: "Lang", t4_r3: "Taste",
    t5_title: "Die Enter-Taste", t5_text: "Mit Enter springst du in eine neue Zeile.", t5_inst: "Verbinde die Paare:", t5_h1: "Neue Zeile.", t5_h2: "Nach unten hüpfen.", t5_q: "Was macht die Enter-Taste?", t5_qa: "Neue Zeile", t5_qb: "Buchstabe löschen", t5_qc: "Malen", t5_qd: "Singen",
    t5_l1: "Enter", t5_r1: "Neue Zeile", t5_l2: "Sprung", t5_r2: "Unten", t5_l3: "Fertig", t5_r3: "Bestätigen",
    t6_title: "Löschen", t6_text: "Mit Backspace löschst du den letzten Buchstaben links.", t6_inst: "Verbinde die Paare:", t6_h1: "Wegmachen.", t6_h2: "Nach links löschen.", t6_q: "Wie löscht man einen Fehler?", t6_qa: "Backspace-Taste", t6_qb: "Mit Wasser", t6_qc: "Mit der Maus", t6_qd: "Gar nicht",
    t6_l1: "Löschen", t6_r1: "Weg", t6_l2: "Fehler", t6_r2: "Korrigieren", t6_l3: "Links", t6_r3: "Richtung",
    t7_title: "Zahlen schreiben", t7_text: "Tippe dein Alter oder deine Hausnummer.", t7_inst: "Verbinde die Paare:", t7_h1: "Zahlen tippen.", t7_h2: "Wie viele?", t7_q: "Was ist eine Zahl?", t7_qa: "10", t7_qb: "Haus", t7_qc: "Baum", t7_qd: "Sonne",
    t7_l1: "Zahl", t7_r1: "Ziffer", t7_l2: "Alter", t7_r2: "Jahre", t7_l3: "Menge", t7_r3: "Viel",
    t8_title: "Wörter schreiben", t8_text: "Setze Buchstaben zusammen, um ein Wort zu bilden.", t8_inst: "Verbinde die Paare:", t8_h1: "Buchstaben-Kette.", t8_h2: "Ein Name.", t8_q: "Was braucht man für ein Wort?", t8_qa: "Buchstaben", t8_qb: "Eier", t8_qc: "Steine", t8_qd: "Wasser",
    t8_l1: "Wort", t8_r1: "Name", t8_l2: "Buchstabe", t8_r2: "Teil", t8_l3: "Lesen", t8_r3: "Buch",
    t9_title: "Sätze schreiben", t9_text: "Ein Satz besteht aus vielen Wörtern und einem Punkt.", t9_inst: "Verbinde die Paare:", t9_h1: "Ganze Sätze.", t9_h2: "Punkt am Ende.", t9_q: "Was kommt ans Ende eines Satzes?", t9_qa: "Ein Punkt", t9_qb: "Eine Nase", t9_qc: "Ein Schuh", t9_qd: "Ein Apfel",
    t9_l1: "Satz", t9_r1: "Punkt", t9_l2: "Anfang", t9_r2: "Groß", t9_l3: "Ende", t9_r3: "Stopp",
    t10_title: "Satzzeichen", t10_text: "Fragezeichen (?) und Ausrufezeichen (!) sind wichtig.", t10_inst: "Verbinde die Paare:", t10_h1: "Fragen oder rufen.", t10_h2: "Zeichen setzen.", t10_q: "Welches Zeichen ist für eine Frage?", t10_qa: "?", t10_qb: "!", t10_qc: "A", t10_qd: "1",
    t10_l1: "Frage", t10_r1: "?", t10_l2: "Rufen", t10_r2: "!", t10_l3: "Stopp", t10_r3: ".",
    t11_title: "Komma und Punkt", t11_text: "Kleine Pausen machen den Text besser lesbar.", t11_inst: "Verbinde die Paare:", t11_h1: "Pause machen.", t11_h2: "Satzende.", t11_q: "Wo ist der Punkt auf der Tastatur?", t11_qa: "Unten rechts", t11_qb: "Ganz oben", t11_qc: "An der Maus", t11_qd: "Im Kabel",
    t11_l1: "Punkt", t11_r1: "Ende", t11_l2: "Komma", t11_r2: "Pause", t11_l3: "Tippen", t11_r3: "Finger",
    t12_title: "Die Pfeiltasten", t12_text: "Mit den Pfeilen kannst du den Cursor bewegen.", t12_inst: "Verbinde die Paare:", t12_h1: "Hin und her.", t12_h2: "Oben, unten, links, rechts.", t12_q: "Was machen die Pfeiltasten?", t12_qa: "Bewegen", t12_qb: "Löschen", t12_qc: "Malen", t12_qd: "Speichern",
    t12_l1: "Hoch", t12_r1: "Oben", t12_l2: "Runter", t12_r2: "Unten", t12_l3: "Rechts", t12_r3: "Vor",
    t13_title: "Die Shift-Taste", t13_text: "Halte Shift gedrückt für einen großen Buchstaben.", t13_inst: "Verbinde die Paare:", t13_h1: "Groß machen.", t13_h2: "Umschalttaste.", t13_q: "Wie schreibt man ein großes 'A'?", t13_qa: "Shift + a", t13_qb: "Nur a", t13_qc: "Leertaste", t13_qd: "Enter",
    t13_l1: "Shift", t13_r1: "Groß", t13_l2: "Taste", t13_r2: "Drücken", t13_l3: "Halten", t13_r3: "Wichtig",
    t14_title: "Die Tab-Taste", t14_text: "Mit Tab springst du zum nächsten Feld.", t14_inst: "Verbinde die Paare:", t14_h1: "Weiter hüpfen.", t14_h2: "Großer Sprung.", t14_q: "Was macht Tab?", t14_qa: "Springen", t14_qb: "Löschen", t14_qc: "Malen", t14_qd: "Schlafen",
    t14_l1: "Tab", t14_r1: "Sprung", t14_l2: "Feld", t14_r2: "Nächstes", t14_l3: "Pfeil", t14_r3: "Symbol",
    t15_title: "Schreib-Meister", t15_text: "Du kannst jetzt super mit der Tastatur umgehen!", t15_inst: "Verbinde die Paare:", t15_h1: "Du bist klasse.", t15_h2: "Alles gelernt.", t15_q: "Was kannst du jetzt?", t15_qa: "Texte schreiben", t15_qb: "Fliegen", t15_qc: "Tauchen", t15_qd: "Zaubern",
    t15_l1: "Meister", t15_r1: "Schreiben", t15_l2: "Tastatur", t15_r2: "Profi", t15_l3: "Fertig", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "Numbers & Text",
    t1_title: "Finding Numbers", t1_text: "Look for the numbers 1, 2, 3 at the top of your keyboard.", t1_inst: "Match the pairs:", t1_h1: "Search for numbers.", t1_h2: "How old are you?", t1_q: "Where are the numbers usually?", t1_qa: "In a row at the top", t1_qb: "Under the mouse", t1_qc: "In the screen", t1_qd: "Behind the PC",
    t1_l1: "One", t1_r1: "1", t1_l2: "Two", t1_r2: "2", t1_l3: "Three", t1_r3: "3",
    t2_title: "Lowercase Letters", t2_text: "Most letters we write are small.", t2_inst: "Match the pairs:", t2_h1: "Small letters.", t2_h2: "abc...", t2_q: "Which letter is lowercase?", t2_qa: "a", t2_qb: "A", t2_qc: "7", t2_qd: "!",
    t2_l1: "Small a", t2_r1: "a", t2_l2: "Small b", t2_r2: "b", t2_l3: "Small c", t2_r3: "c",
    t3_title: "Uppercase Letters", t3_text: "We use big letters at the start of a name.", t3_inst: "Match the pairs:", t3_h1: "Big letters.", t3_h2: "ABC...", t3_q: "Which letter is uppercase?", t3_qa: "B", t3_qb: "b", t3_qc: "5", t3_qd: "?",
    t3_l1: "Big A", t3_r1: "A", t3_l2: "Big B", t3_r2: "B", t3_l3: "Big C", t3_r3: "C",
    t4_title: "The Space Bar", t4_text: "The long button makes a gap between words.", t4_inst: "Match the pairs:", t4_h1: "Keep a distance.", t4_h2: "The longest key.", t4_q: "What does the space bar do?", t4_qa: "A space", t4_qb: "Delete everything", t4_qc: "Turn off PC", t4_qd: "A picture",
    t4_l1: "Space bar", t4_r1: "Gap", t4_l2: "Word", t4_r2: "Space", t4_l3: "Long", t4_r3: "Key",
    t5_title: "The Enter Key", t5_text: "With Enter, you jump to a new line.", t5_inst: "Match the pairs:", t5_h1: "New line.", t5_h2: "Jump down.", t5_q: "What does the Enter key do?", t5_qa: "New line", t5_qb: "Delete letter", t5_qc: "Paint", t5_qd: "Sing",
    t5_l1: "Enter", t5_r1: "New line", t5_l2: "Jump", t5_r2: "Down", t5_l3: "Done", t5_r3: "Confirm",
    t6_title: "Deleting", t6_text: "Use Backspace to delete the last letter on the left.", t6_inst: "Match the pairs:", t6_h1: "Remove it.", t6_h2: "Delete to the left.", t6_q: "How do you fix a mistake?", t6_qa: "Backspace key", t6_qb: "With water", t6_qc: "With the mouse", t6_qd: "Not at all",
    t6_l1: "Delete", t6_r1: "Gone", t6_l2: "Mistake", t6_r2: "Fix", t6_l3: "Left", t6_r3: "Direction",
    t7_title: "Typing Numbers", t7_text: "Type your age or your house number.", t7_inst: "Match the pairs:", t7_h1: "Type numbers.", t7_h2: "How many?", t7_q: "What is a number?", t7_qa: "10", t7_qb: "House", t7_qc: "Tree", t7_qd: "Sun",
    t7_l1: "Number", t7_r1: "Digit", t7_l2: "Age", t7_r2: "Years", t7_l3: "Amount", t7_r3: "Many",
    t8_title: "Typing Words", t8_text: "Put letters together to form a word.", t8_inst: "Match the pairs:", t8_h1: "Letter chain.", t8_h2: "A name.", t8_q: "What do you need for a word?", t8_qa: "Letters", t8_qb: "Eggs", t8_qc: "Stones", t8_qd: "Water",
    t8_l1: "Word", t8_r1: "Name", t8_l2: "Letter", t8_r2: "Part", t8_l3: "Read", t8_r3: "Book",
    t9_title: "Typing Sentences", t9_text: "A sentence has many words and a period.", t9_inst: "Match the pairs:", t9_h1: "Full sentences.", t9_h2: "Period at the end.", t9_q: "What goes at the end of a sentence?", t9_qa: "A period", t9_qb: "A nose", t9_qc: "A shoe", t9_qd: "An apple",
    t9_l1: "Sentence", t9_r1: "Period", t9_l2: "Start", t9_r2: "Big", t9_l3: "End", t9_r3: "Stop",
    t10_title: "Punctuation", t10_text: "Question marks (?) and exclamation marks (!) are important.", t10_inst: "Match the pairs:", t10_h1: "Ask or shout.", t10_h2: "Set marks.", t10_q: "Which mark is for a question?", t10_qa: "?", t10_qb: "!", t10_qc: "A", t10_qd: "1",
    t10_l1: "Question", t10_r1: "?", t10_l2: "Shout", t10_r2: "!", t10_l3: "Stop", t10_r3: ".",
    t11_title: "Comma and Period", t11_text: "Small pauses make the text easier to read.", t11_inst: "Match the pairs:", t11_h1: "Take a pause.", t11_h2: "End of sentence.", t11_q: "Where is the period on the keyboard?", t11_qa: "Bottom right", t11_qb: "At the very top", t11_qc: "On the mouse", t11_qd: "In the cable",
    t11_l1: "Period", t11_r1: "End", t11_l2: "Comma", t11_r2: "Pause", t11_l3: "Typing", t11_r3: "Finger",
    t12_title: "The Arrow Keys", t12_text: "Use the arrows to move the cursor.", t12_inst: "Match the pairs:", t12_h1: "Back and forth.", t12_h2: "Up, down, left, right.", t12_q: "What do the arrow keys do?", t12_qa: "Move", t12_qb: "Delete", t12_qc: "Paint", t12_qd: "Save",
    t12_l1: "Up", t12_r1: "Top", t12_l2: "Down", t12_r2: "Bottom", t12_l3: "Right", t12_r3: "Forward",
    t13_title: "The Shift Key", t13_text: "Hold Shift for a capital letter.", t13_inst: "Match the pairs:", t13_h1: "Make it big.", t13_h2: "Shift key.", t13_q: "How do you type a big 'A'?", t13_qa: "Shift + a", t13_qb: "Just a", t13_qc: "Space bar", t13_qd: "Enter",
    t13_l1: "Shift", t13_r1: "Big", t13_l2: "Key", t13_r2: "Press", t13_l3: "Hold", t13_r3: "Important",
    t14_title: "The Tab Key", t14_text: "With Tab, you jump to the next field.", t14_inst: "Match the pairs:", t14_h1: "Jump forward.", t14_h2: "Big jump.", t14_q: "What does Tab do?", t14_qa: "Jump", t14_qb: "Delete", t14_qc: "Paint", t14_qd: "Sleep",
    t14_l1: "Tab", t14_r1: "Jump", t14_l2: "Field", t14_r2: "Next", t14_l3: "Arrow", t14_r3: "Symbol",
    t15_title: "Writing Master", t15_text: "You can now use the keyboard super well!", t15_inst: "Match the pairs:", t15_h1: "You are great.", t15_h2: "Learned everything.", t15_q: "What can you do now?", t15_qa: "Write texts", t15_qb: "Fly", t15_qc: "Dive", t15_qd: "Magic",
    t15_l1: "Master", t15_r1: "Writing", t15_l2: "Keyboard", t15_r2: "Pro", t15_l3: "Done", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "Számok & Szöveg",
    t1_title: "Számok keresése", t1_text: "Keresd az 1, 2, 3 számokat a billentyűzeted tetején.", t1_inst: "Párosítsd össze:", t1_h1: "Számok keresése.", t1_h2: "Hány éves vagy?", t1_q: "Hol vannak általában a számok?", t1_qa: "Fent egy sorban", t1_qb: "Az egér alatt", t1_qc: "A képernyőben", t1_qd: "A gép mögött",
    t1_l1: "Egy", t1_r1: "1", t1_l2: "Kettő", t1_r2: "2", t1_l3: "Három", t1_r3: "3",
    t2_title: "Kisbetűk", t2_text: "A legtöbb betű, amit írunk, kicsi.", t2_inst: "Párosítsd össze:", t2_h1: "Kisbetűk.", t2_h2: "abc...", t2_q: "Melyik betű kicsi?", t2_qa: "a", t2_qb: "A", t2_qc: "7", t2_qd: "!",
    t2_l1: "Kis a", t2_r1: "a", t2_l2: "Kis b", t2_r2: "b", t2_l3: "Kis c", t2_r3: "c",
    t3_title: "Nagybetűk", t3_text: "Nevek elején nagybetűt használunk.", t3_inst: "Párosítsd össze:", t3_h1: "Nagybetűk.", t3_h2: "ABC...", t3_q: "Melyik betű nagy?", t3_qa: "B", t3_qb: "b", t3_qc: "5", t3_qd: "?",
    t3_l1: "Nagy A", t3_r1: "A", t3_l2: "Nagy B", t3_r2: "B", t3_l3: "Nagy C", t3_r3: "C",
    t4_title: "A szóköz", t4_text: "A hosszú gombbal helyet hagyunk a szavak között.", t4_inst: "Párosítsd össze:", t4_h1: "Tarts távolságot.", t4_h2: "A leghosszabb gomb.", t4_q: "Mit csinál a szóköz?", t4_qa: "Helyet hagy", t4_qb: "Mindent töröl", t4_qc: "Kikapcsolja a gépet", t4_qd: "Képet rajzol",
    t4_l1: "Szóköz", t4_r1: "Hely", t4_l2: "Szó", t4_r2: "Távolság", t4_l3: "Hosszú", t4_r3: "Gomb",
    t5_title: "Az Enter gomb", t5_text: "Az Enterrel új sorba ugorhatsz.", t5_inst: "Párosítsd össze:", t5_h1: "Új sor.", t5_h2: "Ugorj lejjebb.", t5_q: "Mit csinál az Enter gomb?", t5_qa: "Új sor", t5_qb: "Betűt töröl", t5_qc: "Fest", t5_qd: "Énekel",
    t5_l1: "Enter", t5_r1: "Új sor", t5_l2: "Ugrás", t5_r2: "Le", t5_l3: "Kész", t5_r3: "Rendben",
    t6_title: "Törlés", t6_text: "A Backspace gombbal törölheted az utolsó betűt.", t6_inst: "Párosítsd össze:", t6_h1: "Tüntesd el.", t6_h2: "Balra töröl.", t6_q: "Hogyan javítod a hibát?", t6_qa: "Backspace gomb", t6_qb: "Vízzel", t6_qc: "Az egérrel", t6_qd: "Sehogy",
    t6_l1: "Törlés", t6_r1: "Eltűnt", t6_l2: "Hiba", t6_r2: "Javítás", t6_l3: "Balra", t6_r3: "Irány",
    t7_title: "Számok írása", t7_text: "Írd be a korodat vagy a házszámodat.", t7_inst: "Párosítsd össze:", t7_h1: "Számok gépelése.", t7_h2: "Mennyi?", t7_q: "Mi a szám?", t7_qa: "10", t7_qb: "Ház", t7_qc: "Fa", t7_qd: "Nap",
    t7_l1: "Szám", t7_r1: "Számjegy", t7_l2: "Kor", t7_r2: "Évek", t7_l3: "Mennyiség", t7_r3: "Sok",
    t8_title: "Szavak írása", t8_text: "Tedd egymás mellé a betűket, hogy szót kapj.", t8_inst: "Párosítsd össze:", t8_h1: "Betűlánc.", t8_h2: "Egy név.", t8_q: "Mi kell egy szóhoz?", t8_qa: "Betűk", t8_qb: "Tojás", t8_qc: "Kövek", t8_qd: "Víz",
    t8_l1: "Szó", t8_r1: "Név", t8_l2: "Betű", t8_r2: "Rész", t8_l3: "Olvasás", t8_r3: "Könyv",
    t9_title: "Mondatok írása", t9_text: "A mondat sok szóból és egy pontból áll.", t9_inst: "Párosítsd össze:", t9_h1: "Egész mondatok.", t9_h2: "Pont a végén.", t9_q: "Mi van a mondat végén?", t9_qa: "Egy pont", t9_qb: "Egy orr", t9_qc: "Egy cipő", t9_qd: "Egy alma",
    t9_l1: "Mondat", t9_r1: "Pont", t9_l2: "Eleje", t9_r2: "Nagy", t9_l3: "Vége", t9_r3: "Stopp",
    t10_title: "Írásjelek", t10_text: "A kérdőjel (?) és a felkiáltójel (!) fontosak.", t10_inst: "Párosítsd össze:", t10_h1: "Kérdezz vagy kiálts.", t10_h2: "Tegyél jelet.", t10_q: "Melyik jel való kérdéshez?", t10_qa: "?", t10_qb: "!", t10_qc: "A", t10_qd: "1",
    t10_l1: "Kérdés", t10_r1: "?", t10_l2: "Kiáltás", t10_r2: "!", t10_l3: "Stopp", t10_r3: ".",
    t11_title: "Vessző és pont", t11_text: "A kis szünetek segítik az olvasást.", t11_inst: "Párosítsd össze:", t11_h1: "Tarts szünetet.", t11_h2: "Mondat vége.", t11_q: "Hol van a pont a billentyűzeten?", t11_qa: "Lent jobbra", t11_qb: "Legfelül", t11_qc: "Az egéren", t11_qd: "A kábelben",
    t11_l1: "Pont", t11_r1: "Vége", t11_l2: "Vessző", t11_r2: "Szünet", t11_l3: "Gépelés", t11_r3: "Ujj",
    t12_title: "A nyíl billentyűk", t12_text: "A nyilakkal mozgathatod a kurzort.", t12_inst: "Párosítsd össze:", t12_h1: "Itt-ott.", t12_h2: "Fel, le, balra, jobbra.", t12_q: "Mit csinálnak a nyilak?", t12_qa: "Mozgatnak", t12_qb: "Törölnek", t12_qc: "Festenek", t12_qd: "Mentenek",
    t12_l1: "Fel", t12_r1: "Fent", t12_l2: "Le", t12_r2: "Lent", t12_l3: "Jobbra", t12_r3: "Előre",
    t13_title: "A Shift gomb", t13_text: "Tartsd nyomva a Shiftet a nagybetűhöz.", t13_inst: "Párosítsd össze:", t13_h1: "Legyen nagy.", t13_h2: "Váltó gomb.", t13_q: "Hogyan írsz nagy 'A'-t?", t13_qa: "Shift + a", t13_qb: "Csak a", t13_qc: "Szóköz", t13_qd: "Enter",
    t13_l1: "Shift", t13_r1: "Nagy", t13_l2: "Gomb", t13_r2: "Nyomás", t13_l3: "Tartás", t13_r3: "Fontos",
    t14_title: "A Tab gomb", t14_text: "A Tabbal a következő mezőre ugorhatsz.", t14_inst: "Párosítsd össze:", t14_h1: "Ugorj tovább.", t14_h2: "Nagy ugrás.", t14_q: "Mit csinál a Tab?", t14_qa: "Ugrás", t14_qb: "Törlés", t14_qc: "Festés", t14_qd: "Alvás",
    t14_l1: "Tab", t14_r1: "Ugrás", t14_l2: "Mező", t14_r2: "Következő", t14_l3: "Nyíl", t14_r3: "Ikon",
    t15_title: "Író-mester", t15_text: "Most már szuperül tudod használni a billentyűzetet!", t15_inst: "Párosítsd össze:", t15_h1: "Nagyszerű vagy.", t15_h2: "Mindent megtanultál.", t15_q: "Mit tudsz most már?", t15_qa: "Szöveget írni", t15_qb: "Repülni", t15_qc: "Búvárkodni", t15_qd: "Varázsolni",
    t15_l1: "Mester", t15_r1: "Írás", t15_l2: "Billentyűzet", t15_r2: "Profi", t15_l3: "Kész", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Cifre & Text",
    t1_title: "Găsirea cifrelor", t1_text: "Caută cifrele 1, 2, 3 în partea de sus a tastaturii.", t1_inst: "Potrivește perechile:", t1_h1: "Caută cifrele.", t1_h2: "Câți ani ai?", t1_q: "Unde sunt cifrele de obicei?", t1_qa: "Într-un rând sus", t1_qb: "Sub mouse", t1_qc: "În ecran", t1_qd: "În spatele PC-ului",
    t1_l1: "Unu", t1_r1: "1", t1_l2: "Doi", t1_r2: "2", t1_l3: "Trei", t1_r3: "3",
    t2_title: "Litere mici", t2_text: "Majoritatea literelor pe care le scriem sunt mici.", t2_inst: "Potrivește perechile:", t2_h1: "Litere mici.", t2_h2: "abc...", t2_q: "Care literă este mică?", t2_qa: "a", t2_qb: "A", t2_qc: "7", t2_qd: "!",
    t2_l1: "a mic", t2_r1: "a", t2_l2: "b mic", t2_r2: "b", t2_l3: "c mic", t2_r3: "c",
    t3_title: "Litere mari", t3_text: "Folosim litere mari la începutul unui nume.", t3_inst: "Potrivește perechile:", t3_h1: "Litere mari.", t3_h2: "ABC...", t3_q: "Care literă este mare?", t3_qa: "B", t3_qb: "b", t3_qc: "5", t3_qd: "?",
    t3_l1: "A mare", t3_r1: "A", t3_l2: "B mare", t3_r2: "B", t3_l3: "C mare", t3_r3: "C",
    t4_title: "Bara de spațiu", t4_text: "Butonul lung lasă un spațiu între cuvinte.", t4_inst: "Potrivește perechile:", t4_h1: "Lasă distanță.", t4_h2: "Cea mai lungă tastă.", t4_q: "Ce face bara de spațiu?", t4_qa: "Un spațiu", t4_qb: "Șterge tot", t4_qc: "Oprește PC-ul", t4_qd: "O imagine",
    t4_l1: "Spațiu", t4_r1: "Loc", t4_l2: "Cuvânt", t4_r2: "Distanță", t4_l3: "Lung", t4_r3: "Tastă",
    t5_title: "Tasta Enter", t5_text: "Cu Enter, sari la un rând nou.", t5_inst: "Potrivește perechile:", t5_h1: "Rând nou.", t5_h2: "Sari mai jos.", t5_q: "Ce face tasta Enter?", t5_qa: "Rând nou", t5_qb: "Șterge litera", t5_qc: "Pictează", t5_qd: "Cântă",
    t5_l1: "Enter", t5_r1: "Rând nou", t5_l2: "Săritură", t5_r2: "Jos", t5_l3: "Gata", t5_r3: "Confirmă",
    t6_title: "Ștergere", t6_text: "Folosește Backspace pentru a șterge ultima literă.", t6_inst: "Potrivește perechile:", t6_h1: "Elimină.", t6_h2: "Șterge la stânga.", t6_q: "Cum repari o greșeală?", t6_qa: "Tasta Backspace", t6_qb: "Cu apă", t6_qc: "Cu mouse-ul", t6_qd: "Deloc",
    t6_l1: "Ștergere", t6_r1: "Dispărut", t6_l2: "Greșeală", t6_r2: "Repară", t6_l3: "Stânga", t6_r3: "Direcție",
    t7_title: "Scrierea cifrelor", t7_text: "Scrie vârsta ta sau numărul casei.", t7_inst: "Potrivește perechile:", t7_h1: "Tastează cifre.", t7_h2: "Cât?", t7_q: "Ce este o cifră?", t7_qa: "10", t7_qb: "Casă", t7_qc: "Copac", t7_qd: "Soare",
    t7_l1: "Cifră", t7_r1: "Număr", t7_l2: "Vârstă", t7_r2: "Ani", t7_l3: "Cantitate", t7_r3: "Mult",
    t8_title: "Scrierea cuvintelor", t8_text: "Pune literele împreună pentru a forma un cuvânt.", t8_inst: "Potrivește perechile:", t8_h1: "Lanț de litere.", t8_h2: "Un nume.", t8_q: "De ce ai nevoie pentru un cuvânt?", t8_qa: "Litere", t8_qb: "Ouă", t8_qc: "Pietre", t8_qd: "Apă",
    t8_l1: "Cuvânt", t8_r1: "Nume", t8_l2: "Literă", t8_r2: "Parte", t8_l3: "Citit", t8_r3: "Carte",
    t9_title: "Scrierea propozițiilor", t9_text: "O propoziție are multe cuvinte și un punct.", t9_inst: "Potrivește perechile:", t9_h1: "Propoziții întregi.", t9_h2: "Punct la sfârșit.", t9_q: "Ce se pune la sfârșitul unei propoziții?", t9_qa: "Un punct", t9_qb: "Un nas", t9_qc: "Un pantof", t9_qd: "Un măr",
    t9_l1: "Propoziție", t9_r1: "Punct", t9_l2: "Început", t9_r2: "Mare", t9_l3: "Sfârșit", t9_r3: "Stop",
    t10_title: "Semne de punctuație", t10_text: "Semnul întrebării (?) și al exclamării (!) sunt importante.", t10_inst: "Potrivește perechile:", t10_h1: "Întreabă sau strigă.", t10_h2: "Pune semne.", t10_q: "Care semn este pentru întrebare?", t10_qa: "?", t10_qb: "!", t10_qc: "A", t10_qd: "1",
    t10_l1: "Întrebare", t10_r1: "?", t10_l2: "Strigăt", t10_r2: "!", t10_l3: "Stop", t10_r3: ".",
    t11_title: "Virgulă și punct", t11_text: "Pauzele mici fac textul mai ușor de citit.", t11_inst: "Potrivește perechile:", t11_h1: "Fă o pauză.", t11_h2: "Sfârșit de propoziție.", t11_q: "Unde este punctul pe tastatură?", t11_qa: "Jos dreapta", t11_qb: "Sus de tot", t11_qc: "Pe mouse", t11_qd: "În cablu",
    t11_l1: "Punct", t11_r1: "Sfârșit", t11_l2: "Virgulă", t11_r2: "Pauză", t11_l3: "Tastare", t11_r3: "Deget",
    t12_title: "Tastele săgeți", t12_text: "Folosește săgețile pentru a mișca cursorul.", t12_inst: "Potrivește perechile:", t12_h1: "Înainte și înapoi.", t12_h2: "Sus, jos, stânga, dreapta.", t12_q: "Ce fac tastele săgeți?", t12_qa: "Mișcă", t12_qb: "Șterg", t12_qc: "Pictează", t12_qd: "Salvează",
    t12_l1: "Sus", t12_r1: "Vârf", t12_l2: "Jos", t12_r2: "Bază", t12_l3: "Dreapta", t12_r3: "Înainte",
    t13_title: "Tasta Shift", t13_text: "Ține Shift apăsat pentru o literă mare.", t13_inst: "Potrivește perechile:", t13_h1: "Fă-o mare.", t13_h2: "Tasta Shift.", t13_q: "Cum scrii un 'A' mare?", t13_qa: "Shift + a", t13_qb: "Doar a", t13_qc: "Spațiu", t13_qd: "Enter",
    t13_l1: "Shift", t13_r1: "Mare", t13_l2: "Tastă", t13_r2: "Apăsare", t13_l3: "Ține", t13_r3: "Important",
    t14_title: "Tasta Tab", t14_text: "Cu Tab, sari la următorul câmp.", t14_inst: "Potrivește perechile:", t14_h1: "Sari înainte.", t14_h2: "Săritură mare.", t14_q: "Ce face Tab?", t14_qa: "Sari", t14_qb: "Șterge", t14_qc: "Pictează", t14_qd: "Doarme",
    t14_l1: "Tab", t14_r1: "Sari", t14_l2: "Câmp", t14_r2: "Următor", t14_l3: "Săgeată", t14_r3: "Simbol",
    t15_title: "Maestru la scris", t15_text: "Acum poți folosi tastatura foarte bine!", t15_inst: "Potrivește perechile:", t15_h1: "Ești grozav.", t15_h2: "Ai învățat totul.", t15_q: "Ce poți face acum?", t15_qa: "Scrii texte", t15_qb: "Zbori", t15_qc: "Te scufunzi", t15_qd: "Faci magie",
    t15_l1: "Maestru", t15_r1: "Scris", t15_l2: "Tastatură", t15_r2: "Pro", t15_l3: "Gata", t15_r3: "Victorie"
  }
};

export const INFO_K1_I4_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["🔢", "abc", "ABC", "⌨️", "⏎", "⌫", "7️⃣", "🔤", "📝", "❓", "🛑", "↕️", "⬆️", "⏭️", "🎓"];
  const colors = ["#4CAF50", "#2196F3", "#3F51B5", "#9E9E9E", "#607D8B", "#F44336", "#FF9800", "#9C27B0", "#673AB7", "#E91E63", "#795548", "#00BCD4", "#FFC107", "#009688", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});
