// @ts-nocheck
// lib/explorerPools/informatikaK8_i2.ts
import type { PoolTopicDef } from "./types";

export const INFO_K8_I2_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Zukunft der Informatik",
    t16_title: "Fortgeschrittene KI", t16_text: "Deep Learning und Generative KI verändern unsere Welt.",
    t16_inst: "Ordne den Satz:", t16_w1: "KI-Modelle", t16_w2: "lernen", t16_w3: "aus", t16_w4: "riesigen", t16_w5: "Datenmengen.",
    t16_q: "Was ist ein LLM?", t16_qa: "Large Language Model", t16_qb: "Little Logic Machine", t16_qc: "Long List Maker", t16_qd: "Local Link Manager",
    t17_title: "ML Grundlagen", t17_text: "Maschinelles Lernen ermöglicht Computern, ohne explizite Programmierung zu lernen.",
    t17_inst: "Verbinde:", t17_l1: "Supervised", t17_r1: "Mit Labels", t17_l2: "Unsupervised", t17_r2: "Muster finden", t17_l3: "Algorithm", t17_r3: "Regelwerk",
    t17_q: "Wofür steht ML?", t17_qa: "Machine Learning", t17_qb: "Mobile Logic", t17_qc: "Mega Laptop", t17_qd: "Multi Level",
    t18_title: "Neuronale Netze", t18_text: "Diese Netzwerke sind dem menschlichen Gehirn nachempfunden.",
    t18_inst: "Fülle die Lücke:", t18_sent: "Neuronale Netze bestehen aus künstlichen ___.", t18_qa18: "Neuronen", t18_qb18: "Kabeln", t18_qc18: "Schaltern", t18_qd18: "Batterien",
    t18_q: "Was ist die Inspiration für neuronale Netze?", t18_qa: "Das Gehirn", t18_qb: "Das Herz", t18_qc: "Der Magen", t18_qd: "Die Lunge",
    t19_title: "Datenanalyse", t19_text: "Daten reinigen, umwandeln und modellieren, um Erkenntnisse zu gewinnen.",
    t19_inst: "Markiere das Ziel:", t19_tk1: "Datenanalyse", t19_tk2: "dient", t19_tk3: "der Gewinnung", t19_tk4: "wertvoller Insights.",
    t19_q: "Was ist der erste Schritt?", t19_qa: "Datensammlung", t19_qb: "Löschen", t19_qc: "Drucken", t19_qd: "Verkaufen",
    t20_title: "Statistik", t20_text: "Mathematische Methoden zur Analyse von Datenmengen.",
    t20_inst: "Baue den Satz:", t20_f1: "Statistik hilft,", t20_f2: "Trends in", t20_f3: "großen Datenmengen", t20_f4: "zu erkennen.",
    t20_q: "Was ist der 'Mittelwert'?", t20_qa: "Durchschnitt", t20_qb: "Maximum", t20_qc: "Minimum", t20_qd: "Zufall",
    t21_title: "Visualisierung", t21_text: "Daten in grafische Formen bringen, um sie verständlich zu machen.",
    t21_inst: "Sortiere:", t21_bl1: "Diagramme", t21_bl2: "Keine Diagramme", t21_i1: "Balkendiagramm", t21_i2: "Textdatei", t21_i3: "Tortendiagramm", t21_i4: "Tastatur",
    t21_q: "Warum visualisieren wir?", t21_qa: "Um Muster schneller zu sehen", t21_qb: "Damit es bunt ist", t21_qc: "Um Platz zu sparen", t21_qd: "Gar nicht",
    t22_title: "Cloud Computing", t22_text: "Bereitstellung von IT-Infrastruktur über das Internet.",
    t22_inst: "Verbinde:", t22_l1: "SaaS", t22_r1: "Software", t22_l2: "IaaS", t22_r2: "Infrastruktur", t22_l3: "PaaS", t22_r3: "Plattform",
    t22_q: "Was ist AWS?", t22_qa: "Cloud-Anbieter", t22_qb: "Betriebssystem", t22_qc: "Programmiersprache", t22_qd: "Hardware",
    t23_title: "IoT", t23_text: "Vernetzung von physischen Objekten mit dem Internet.",
    t23_inst: "Fülle die Lücke:", t23_sent: "IoT verbindet Alltagsgeräte mit dem ___.", t23_qa23: "Internet", t23_qb23: "Telefonnetz", t23_qc23: "Stromnetz", t23_qd23: "Radio",
    t23_q: "Welches ist ein IoT-Gerät?", t23_qa: "Smarter Kühlschrank", t23_qb: "Mechanische Uhr", t23_qc: "Papiertüte", t23_qd: "Holztisch",
    t24_title: "Cyber-Ethik", t24_text: "Sicherheit und moralisches Handeln im digitalen Raum.",
    t24_inst: "Ordne den Satz:", t24_w1: "Sichere", t24_w2: "Passwörter", t24_w3: "schützen", t24_w4: "deine", t24_w5: "Privatsphäre.",
    t24_q: "Was ist Phishing?", t24_qa: "Betrugsversuch per E-Mail", t24_qb: "Angeln am See", t24_qc: "Ein Update", t24_qd: "Ein Spiel",
    t25_title: "Digitale Identität", t25_text: "Deine Präsenz und Spuren im Internet.",
    t25_inst: "Markiere:", t25_tk1: "Schütze", t25_tk2: "immer", t25_tk3: "deine persönlichen", t25_tk4: "Daten.",
    t25_q: "Was ist ein digitaler Fußabdruck?", t25_qa: "Hinterlassene Daten im Netz", t25_qb: "Ein Bild vom Fuß", t25_qc: "Ein Passwort", t25_qd: "Ein Browser",
    t26_title: "Blockchain", t26_text: "Dezentrale, fälschungssichere Datenbanktechnologie.",
    t26_inst: "Baue den Satz:", t26_f1: "Blockchain speichert", t26_f2: "Transaktionen in", t26_f3: "einer Kette", t26_f4: "von Blöcken.",
    t26_q: "Was war die erste Anwendung?", t26_qa: "Bitcoin", t26_qb: "Facebook", t26_qc: "YouTube", t26_qd: "Google",
    t27_title: "Quantencomputing", t27_text: "Computer, die auf den Gesetzen der Quantenmechanik basieren.",
    t27_inst: "Fülle die Lücke:", t27_sent: "Quantencomputer nutzen ___ statt Bits.", t27_qa27: "Qubits", t27_qb27: "Megabits", t27_qc27: "Licht", t27_qd27: "Atome",
    t27_q: "Was ist der Vorteil?", t27_qa: "Enorme Rechenleistung", t27_qb: "Sie sind billiger", t27_qc: "Sie brauchen keinen Strom", t27_qd: "Keiner",
    t28_title: "IT-Berufe", t28_text: "Vielfältige Karrieremöglichkeiten in der Welt der Technik.",
    t28_inst: "Verbinde:", t28_l1: "Entwickler", t28_r1: "Code", t28_l2: "Designer", t28_r2: "Aussehen", t28_l3: "Datenanalyst", t28_r3: "Erkenntnisse",
    t28_q: "Was macht ein UX-Designer?", t28_qa: "Nutzererfahrung gestalten", t28_qb: "Hardware bauen", t28_qc: "Server warten", t28_qd: "Bücher schreiben",
    t29_title: "Zukunft des Webs", t29_text: "Die Entwicklung hin zu einem dezentralen Web 3.0.",
    t29_inst: "Ordne:", t29_w1: "Das", t29_w2: "Web 3.0", t29_w3: "wird", t29_w4: "dezentral", t29_w5: "sein.",
    t29_q: "Was gehört zum Metaverse?", t29_qa: "Virtuelle Welten", t29_qb: "Echte Autos", t29_qc: "Alte Briefe", t29_qd: "Kabelfernsehen",
    t30_title: "Projektarbeit", t30_text: "Das Erlernte in einem eigenen Projekt anwenden.",
    t30_inst: "Fülle die Lücke:", t30_sent: "Gute ___ ist die Basis jedes Projekts.", t30_qa30: "Planung", t30_qb30: "Hardware", t30_qc30: "Kaffeemaschine", t30_qd30: "Tasche",
    t30_q: "Wie lernt man Informatik am besten?", t30_qa: "Durch Selbermachen", t30_qb: "Nur durch Lesen", t30_qc: "Gar nicht", t30_qd: "Durch Fernsehen",
  },
  en: {
    explorer_title: "Future of Informatics",
    t16_title: "Advanced AI", t16_text: "Deep Learning and Generative AI are changing our world.",
    t16_inst: "Order the sentence:", t16_w1: "AI models", t16_w2: "learn", t16_w3: "from", t16_w4: "huge", t16_w5: "amounts of data.",
    t16_q: "What is an LLM?", t16_qa: "Large Language Model", t16_qb: "Little Logic Machine", t16_qc: "Long List Maker", t16_qd: "Local Link Manager",
    t17_title: "ML Basics", t17_text: "Machine Learning allows computers to learn without explicit programming.",
    t17_inst: "Match:", t17_l1: "Supervised", t17_r1: "With labels", t17_l2: "Unsupervised", t17_r2: "Find patterns", t17_l3: "Algorithm", t17_r3: "Ruleset",
    t17_q: "What does ML stand for?", t17_qa: "Machine Learning", t17_qb: "Mobile Logic", t17_qc: "Mega Laptop", t17_qd: "Multi Level",
    t18_title: "Neural Networks", t18_text: "These networks are modeled after the human brain.",
    t18_inst: "Fill the gap:", t18_sent: "Neural networks consist of artificial ___.", t18_qa18: "neurons", t18_qb18: "cables", t18_qc18: "switches", t18_qd18: "batteries",
    t18_q: "What is the inspiration for neural networks?", t18_qa: "The brain", t18_qb: "The heart", t18_qc: "The stomach", t18_qd: "The lungs",
    t19_title: "Data Analysis", t19_text: "Cleaning, transforming, and modeling data to gain insights.",
    t19_inst: "Highlight the goal:", t19_tk1: "Data analysis", t19_tk2: "is used", t19_tk3: "to gain", t19_tk4: "valuable insights.",
    t19_q: "What is the first step?", t19_qa: "Data collection", t19_qb: "Deletion", t19_qc: "Printing", t19_qd: "Selling",
    t20_title: "Statistics", t20_text: "Mathematical methods for analyzing sets of data.",
    t20_inst: "Build the sentence:", t20_f1: "Statistics helps", t20_f2: "to recognize", t20_f3: "trends in", t20_f4: "large datasets.",
    t20_q: "What is the 'Mean'?", t20_qa: "Average", t20_qb: "Maximum", t20_qc: "Minimum", t20_qd: "Random",
    t21_title: "Visualization", t21_text: "Turning data into graphical forms to make it understandable.",
    t21_inst: "Sort:", t21_bl1: "Charts", t21_bl2: "Not Charts", t21_i1: "Bar chart", t21_i2: "Text file", t21_i3: "Pie chart", t21_i4: "Keyboard",
    t21_q: "Why do we visualize?", t21_qa: "To see patterns faster", t21_qb: "To make it colorful", t21_qc: "To save space", t21_qd: "Not at all",
    t22_title: "Cloud Computing", t22_text: "Providing IT infrastructure over the internet.",
    t22_inst: "Match:", t22_l1: "SaaS", t22_r1: "Software", t22_l2: "IaaS", t22_r2: "Infrastructure", t22_l3: "PaaS", t22_r3: "Platform",
    t22_q: "What is AWS?", t22_qa: "Cloud provider", t22_qb: "Operating system", t22_qc: "Programming language", t22_qd: "Hardware",
    t23_title: "IoT", t23_text: "Connecting physical objects to the internet.",
    t23_inst: "Fill the gap:", t23_sent: "IoT connects everyday devices to the ___.", t23_qa23: "Internet", t23_qb23: "Phone network", t23_qc23: "Power grid", t23_qd23: "Radio",
    t23_q: "Which is an IoT device?", t23_qa: "Smart fridge", t23_qb: "Mechanical watch", t23_qc: "Paper bag", t23_qd: "Wooden table",
    t24_title: "Cyber Ethics", t24_text: "Security and moral action in the digital space.",
    t24_inst: "Order the sentence:", t24_w1: "Secure", t24_w2: "passwords", t24_w3: "protect", t24_w4: "your", t24_w5: "privacy.",
    t24_q: "What is phishing?", t24_qa: "Fraudulent email attempt", t24_qb: "Fishing at the lake", t24_qc: "An update", t24_qd: "A game",
    t25_title: "Digital Identity", t25_text: "Your presence and traces on the internet.",
    t25_inst: "Highlight:", t25_tk1: "Always", t25_tk2: "protect", t25_tk3: "your personal", t25_tk4: "data.",
    t25_q: "What is a digital footprint?", t25_qa: "Data left behind online", t25_qb: "A picture of a foot", t25_qc: "A password", t25_qd: "A browser",
    t26_title: "Blockchain", t26_text: "Decentralized, tamper-proof database technology.",
    t26_inst: "Build the sentence:", t26_f1: "Blockchain stores", t26_f2: "transactions in", t26_f3: "a chain", t26_f4: "of blocks.",
    t26_q: "What was the first application?", t26_qa: "Bitcoin", t26_qb: "Facebook", t26_qc: "YouTube", t26_qd: "Google",
    t27_title: "Quantum Computing", t27_text: "Computers based on the laws of quantum mechanics.",
    t27_inst: "Fill the gap:", t27_sent: "Quantum computers use ___ instead of bits.", t27_qa27: "qubits", t27_qb27: "megabits", t27_qc27: "light", t27_qd27: "atoms",
    t27_q: "What is the advantage?", t27_qa: "Enormous power", t27_qb: "They are cheaper", t27_qc: "No electricity needed", t27_qd: "None",
    t28_title: "IT Careers", t28_text: "Diverse career opportunities in the world of technology.",
    t28_inst: "Match:", t28_l1: "Developer", t28_r1: "Code", t28_l2: "Designer", t28_r2: "Appearance", t28_l3: "Data analyst", t28_r3: "Insights",
    t28_q: "What does a UX designer do?", t28_qa: "Design user experience", t28_qb: "Build hardware", t28_qc: "Maintain servers", t28_qd: "Write books",
    t29_title: "Future of Web", t29_text: "The development towards a decentralized Web 3.0.",
    t29_inst: "Order:", t29_w1: "The", t29_w2: "Web 3.0", t29_w3: "will", t29_w4: "be", t29_w5: "decentralized.",
    t29_q: "What belongs to the Metaverse?", t29_qa: "Virtual worlds", t29_qb: "Real cars", t29_qc: "Old letters", t29_qd: "Cable TV",
    t30_title: "Project Work", t30_text: "Apply what you have learned in your own project.",
    t30_inst: "Fill the gap:", t30_sent: "Good ___ is the basis of every project.", t30_qa30: "planning", t30_qb30: "hardware", t30_qc30: "coffee machine", t30_qd30: "bag",
    t30_q: "What is the best way to learn informatics?", t30_qa: "By doing it yourself", t30_qb: "Just by reading", t30_qc: "Not at all", t30_qd: "By watching TV",
  },
  hu: {
    explorer_title: "Az informatika jövője",
    t16_title: "Haladó MI", t16_text: "A mélytanulás és a generatív MI megváltoztatják világunkat.",
    t16_inst: "Rendezd a mondatot:", t16_w1: "Az MI-modellek", t16_w2: "hatalmas", t16_w3: "adatmennyiségekből", t16_w4: "tanulnak", t16_w5: "mintákat.",
    t16_q: "Mi az az LLM?", t16_qa: "Large Language Model", t16_qb: "Little Logic Machine", t16_qc: "Long List Maker", t16_qd: "Local Link Manager",
    t17_title: "Gépi tanulás", t17_text: "A gépi tanulás lehetővé teszi, hogy a gépek tapasztalatból tanuljanak.",
    t17_inst: "Párosítsd:", t17_l1: "Felügyelt", t17_r1: "Címkékkel", t17_l2: "Felügyelet nélküli", t17_r2: "Mintakeresés", t17_l3: "Algoritmus", t17_r3: "Szabályrendszer",
    t17_q: "Mit jelent az ML?", t17_qa: "Machine Learning", t17_qb: "Mobile Logic", t17_qc: "Mega Laptop", t17_qd: "Multi Level",
    t18_title: "Neurális hálók", t18_text: "Ezeket a hálózatokat az emberi agy ihlette.",
    t18_inst: "Pótold:", t18_sent: "A neurális hálók mesterséges ___ épülnek fel.", t18_qa18: "neuronokból", t18_qb18: "kábelekből", t18_qc18: "kapcsolókból", t18_qd18: "elemekből",
    t18_q: "Mi az ihletforrás?", t18_qa: "Az agy", t18_qb: "A szív", t18_qc: "A gyomor", t18_qd: "A tüdő",
    t19_title: "Adatelemzés", t19_text: "Adatok tisztítása és modellezése hasznos információk kinyeréséhez.",
    t19_inst: "Jelöld a célt:", t19_tk1: "Az adatelemzés", t19_tk2: "célja az", t19_tk3: "értékes", t19_tk4: "összefüggések feltárása.",
    t19_q: "Mi az első lépés?", t19_qa: "Adatgyűjtés", t19_qb: "Törlés", t19_qc: "Nyomtatás", t19_qd: "Eladás",
    t20_title: "Statisztika", t20_text: "Matematikai módszerek nagy adatmennyiségek elemzésére.",
    t20_inst: "Építs mondatot:", t20_f1: "A statisztika segít", t20_f2: "felismerni a", t20_f3: "trendeket a", t20_f4: "nagy adathalmazokban.",
    t20_q: "Mi az 'átlag'?", t20_qa: "Számtani közép", t20_qb: "Maximum", t20_qc: "Minimum", t20_qd: "Véletlen",
    t21_title: "Vizualizáció", t21_text: "Adatok grafikus formába öntése a jobb érthetőségért.",
    t21_inst: "Válogasd szét:", t21_bl1: "Diagramok", t21_bl2: "Nem diagramok", t21_i1: "Oszlopdiagram", t21_i2: "Szöveges fájl", t21_i3: "Tortadiagram", t21_i4: "Billentyűzet",
    t21_q: "Miért vizualizálunk?", t21_qa: "Hogy gyorsabban lássuk a mintákat", t21_qb: "Hogy színes legyen", t21_qc: "Helytakarékosságból", t21_qd: "Egyáltalán nem",
    t22_title: "Cloud Computing", t22_text: "Informatikai erőforrások biztosítása az interneten keresztül.",
    t22_inst: "Párosítsd:", t22_l1: "SaaS", t22_r1: "Szoftver", t22_l2: "IaaS", t22_r2: "Infrastruktúra", t22_l3: "PaaS", t22_r3: "Platform",
    t22_q: "Mi az AWS?", t22_qa: "Felhőszolgáltató", t22_qb: "Operációs rendszer", t22_qc: "Programnyelv", t22_qd: "Hardver",
    t23_title: "IoT", t23_text: "Fizikai eszközök összekapcsolása az internettel.",
    t23_inst: "Pótold:", t23_sent: "Az IoT mindennapi eszközöket köt az ___.", t23_qa23: "internetre", t23_qb23: "távbeszélőhöz", t23_qc23: "áramhoz", t23_qd23: "rádióhoz",
    t23_q: "Melyik egy IoT eszköz?", t23_qa: "Okoshűtő", t23_qb: "Mechanikus óra", t23_qc: "Papírzacskó", t23_qd: "Asztal",
    t24_title: "Kiberetika", t24_text: "Biztonság és erkölcsös viselkedés a digitális térben.",
    t24_inst: "Rendezd a mondatot:", t24_w1: "A", t24_w2: "biztonságos", t24_w3: "jelszavak", t24_w4: "védik", t24_w5: "a magánszférát.",
    t24_q: "Mi az adathalászat?", t24_qa: "Csaló e-mailes próbálkozás", t24_qb: "Horgászat a tónál", t24_qc: "Frissítés", t24_qd: "Játék",
    t25_title: "Digitális lábnyomunk", t25_text: "Jelenléted és nyomaid az interneten.",
    t25_inst: "Jelöld:", t25_tk1: "Mindig", t25_tk2: "védd", t25_tk3: "a személyes", t25_tk4: "adataidat.",
    t25_q: "Mi a digitális lábnyom?", t25_qa: "Hátrahagyott adatok a neten", t25_qb: "Egy láb képe", t25_qc: "Jelszó", t25_qd: "Böngésző",
    t26_title: "Blokklánc", t26_text: "Decentralizált, hamisíthatatlan adatbázis technológia.",
    t26_inst: "Építs mondatot:", t26_f1: "A blokklánc", t26_f2: "tranzakciókat tárol", t26_f3: "blokkokból álló", t26_f4: "láncolatban.",
    t26_q: "Mi volt az első alkalmazás?", t26_qa: "Bitcoin", t26_qb: "Facebook", t26_qc: "YouTube", t26_qd: "Google",
    t27_title: "Kvantumgépek", t27_text: "A kvantummechanika törvényein alapuló számítógépek.",
    t27_inst: "Pótold:", t27_sent: "A kvantumszámítógépek bitek helyett ___ használnak.", t27_qa27: "qubiteket", t27_qb27: "megabiteket", t27_qc27: "fényt", t27_qd27: "atomokat",
    t27_q: "Mi az előnyük?", t27_qa: "Hatalmas számítási kapacitás", t27_qb: "Olcsóbbak", t27_qc: "Nem kell áram", t27_qd: "Nincs",
    t28_title: "IT karrier", t28_text: "Változatos lehetőségek a technológia világában.",
    t28_inst: "Párosítsd:", t28_l1: "Fejlesztő", t28_r1: "Kódolás", t28_l2: "Dizájner", t28_r2: "Megjelenés", t28_l3: "Adatelemző", t28_r3: "Összefüggések",
    t28_q: "Mit csinál egy UX dizájner?", t28_qa: "Felhasználói élményt tervez", t28_qb: "Gépalkatrészt gyárt", t28_qc: "Szervert javít", t28_qd: "Könyvet ír",
    t29_title: "Web jövője", t29_text: "Fejlődés a decentralizált Web 3.0 felé.",
    t29_inst: "Rendezd:", t29_w1: "A", t29_w2: "Web 3.0", t29_w3: "decentralizált", t29_w4: "módon", t29_w5: "működik.",
    t29_q: "Mi a metaverzum része?", t29_qa: "Virtuális világok", t29_qb: "Valódi autók", t29_qc: "Régi levelek", t29_qd: "Kábeltévé",
    t30_title: "Projektmunka", t30_text: "A tanultak alkalmazása egy saját projektben.",
    t30_inst: "Pótold:", t30_sent: "A jó ___ minden projekt alapja.", t30_qa30: "tervezés", t30_qb30: "hardver", t30_qc30: "kávéfőző", t30_qd30: "táska",
    t30_q: "Hogyan tanulhatsz legjobban?", t30_qa: "Gyakorlással", t30_qb: "Csak olvasással", t30_qc: "Sehogy", t30_qd: "Tévézéssel",
  },
  ro: {
    explorer_title: "Viitorul Informaticii",
    t16_title: "IA Avansată", t16_text: "Deep Learning și IA generativă ne schimbă lumea.",
    t16_inst: "Ordonează fraza:", t16_w1: "Modelele IA", t16_w2: "învață", t16_w3: "din", t16_w4: "cantități", t16_w5: "mari de date.",
    t16_q: "Ce este un LLM?", t16_qa: "Large Language Model", t16_qb: "Little Logic Machine", t16_qc: "Long List Maker", t16_qd: "Local Link Manager",
    t17_title: "Bazele ML", t17_text: "Machine Learning permite computerelor să învețe din experiență.",
    t17_inst: "Potrivește:", t17_l1: "Supravegheat", t17_r1: "Cu etichete", t17_l2: "Nesupravegheat", t17_r2: "Găsire tipare", t17_l3: "Algoritm", t17_r3: "Reguli",
    t17_q: "Ce înseamnă ML?", t17_qa: "Machine Learning", t17_qb: "Mobile Logic", t17_qc: "Mega Laptop", t17_qd: "Multi Level",
    t18_title: "Rețele Neuronale", t18_text: "Aceste rețele sunt modelate după creierul uman.",
    t18_inst: "Completează:", t18_sent: "Rețelele neuronale sunt formate din ___ artificiali.", t18_qa18: "neuroni", t18_qb18: "cabluri", t18_qc18: "întrerupătoare", t18_qd18: "baterii",
    t18_q: "Care este inspirația?", t18_qa: "Creierul", t18_qb: "Inima", t18_qc: "Stomacul", t18_qd: "Plămânii",
    t19_title: "Analiza Datelor", t19_text: "Curățarea și modelarea datelor pentru a obține informații utile.",
    t19_inst: "Evidențiază scopul:", t19_tk1: "Analiza datelor", t19_tk2: "servește", t19_tk3: "obținerii de", t19_tk4: "informații valoroase.",
    t19_q: "Care este primul pas?", t19_qa: "Colectarea datelor", t19_qb: "Ștergerea", t19_qc: "Imprimarea", t19_qd: "Vânzarea",
    t20_title: "Statistică", t20_text: "Metode matematice pentru analiza seturilor de date.",
    t20_inst: "Construiește fraza:", t20_f1: "Statistica ajută", t20_f2: "la recunoașterea", t20_f3: "tendințelor în", t20_f4: "seturi mari de date.",
    t20_q: "Ce este 'Media'?", t20_qa: "Media aritmetică", t20_qb: "Maximul", t20_qc: "Minimul", t20_qd: "Aleatoriu",
    t21_title: "Vizualizare", t21_text: "Transformarea datelor în forme grafice pentru a fi înțelese.",
    t21_inst: "Sortează:", t21_bl1: "Grafice", t21_bl2: "Nu grafice", t21_i1: "Grafic cu bare", t21_i2: "Fișier text", t21_i3: "Grafic circular", t21_i4: "Tastatură",
    t21_q: "De ce vizualizăm?", t21_qa: "Pentru a vedea tiparele rapid", t21_qb: "Să fie colorat", t21_qc: "Pentru a economisi spațiu", t21_qd: "Deloc",
    t22_title: "Cloud Computing", t22_text: "Furnizarea infrastructurii IT prin internet.",
    t22_inst: "Potrivește:", t22_l1: "SaaS", t22_r1: "Software", t22_l2: "IaaS", t22_r2: "Infrastructură", t22_l3: "PaaS", t22_r3: "Platformă",
    t22_q: "Ce este AWS?", t22_qa: "Furnizor cloud", t22_qb: "Sistem de operare", t22_qc: "Limbaj de programare", t22_qd: "Hardware",
    t23_title: "IoT", t23_text: "Conectarea obiectelor fizice la internet.",
    t23_inst: "Completează:", t23_sent: "IoT conectează dispozitivele de zi cu zi la ___.", t23_qa23: "internet", t23_qb23: "rețeaua telefonică", t23_qc23: "rețeaua electrică", t23_qd23: "radio",
    t23_q: "Care este un dispozitiv IoT?", t23_qa: "Frigider inteligent", t23_qb: "Ceas mecanic", t23_qc: "Pungă de hârtie", t23_qd: "Masă",
    t24_title: "Ciberetică", t24_text: "Securitate și comportament moral în spațiul digital.",
    t24_inst: "Ordonează fraza:", t24_w1: "Parolele", t24_w2: "sigure", t24_w3: "îți", t24_w4: "protejează", t24_w5: "intimitatea.",
    t24_q: "Ce este phishing-ul?", t24_qa: "Tentativă de fraudă prin email", t24_qb: "Pescuit la lac", t24_qc: "O actualizare", t24_qd: "Un joc",
    t25_title: "Identitate Digitală", t25_text: "Prezența și urmele tale pe internet.",
    t25_inst: "Evidențiază:", t25_tk1: "Protejează-ți", t25_tk2: "întotdeauna", t25_tk3: "datele", t25_tk4: "personale.",
    t25_q: "Ce este amprenta digitală?", t25_qa: "Date lăsate în urmă pe net", t25_qb: "O poză cu piciorul", t25_qc: "O parolă", t25_qd: "Un browser",
    t26_title: "Blockchain", t26_text: "Tehnologie de bază de date descentralizată și sigură.",
    t26_inst: "Construiește fraza:", t26_f1: "Blockchain stochează", t26_f2: "tranzacții într-un", t26_f3: "lanț de", t26_f4: "blocuri.",
    t26_q: "Care a fost prima aplicație?", t26_qa: "Bitcoin", t26_qb: "Facebook", t26_qc: "YouTube", t26_qd: "Google",
    t27_title: "Computere Cuantice", t27_text: "Computere bazate pe legile mecanicii cuantice.",
    t27_inst: "Completează:", t27_sent: "Computerele cuantice folosesc ___ în loc de biți.", t27_qa27: "qubiți", t27_qb27: "megabiți", t27_qc27: "lumină", t27_qd27: "atomi",
    t27_q: "Care este avantajul?", t27_qa: "Capacitate uriașă de calcul", t27_qb: "Sunt mai ieftine", t27_qc: "Nu consumă curent", t27_qd: "Niciunul",
    t28_title: "Cariere IT", t28_text: "Oportunități diverse în lumea tehnologiei.",
    t28_inst: "Potrivește:", t28_l1: "Programator", t28_r1: "Cod", t28_l2: "Designer", t28_r2: "Aspect", t28_l3: "Analist date", t28_r3: "Informații",
    t28_q: "Ce face un designer UX?", t28_qa: "Proiectează experiența utilizatorului", t28_qb: "Construiește hardware", t28_qc: "Repară servere", t28_qd: "Scrie cărți",
    t29_title: "Viitorul Web", t29_text: "Evoluția către un Web 3.0 descentralizat.",
    t29_inst: "Ordonează:", t29_w1: "Web 3.0", t29_w2: "va", t29_w3: "funcționa", t29_w4: "în mod", t29_w5: "descentralizat.",
    t29_q: "Ce face parte din Metaverse?", t29_qa: "Lumi virtuale", t29_qb: "Mașini reale", t29_qc: "Scrisori vechi", t29_qd: "Televiziune prin cablu",
    t30_title: "Proiect", t30_text: "Aplicarea celor învățate într-un proiect propriu.",
    t30_inst: "Completează:", t30_sent: "O bună ___ este baza oricărui proiect.", t30_qa30: "planificare", t30_qb30: "hardware", t30_qc30: "mașină de cafea", t30_qd30: "geantă",
    t30_q: "Cum înveți cel mai bine?", t30_qa: "Prin practică", t30_qb: "Doar citind", t30_qc: "Deloc", t30_qd: "Privind la TV",
  },
};

export const INFO_K8_I2_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t16_title", infoText: "t16_text",
    svg: { type: "simple-icon", icon: "🧠", title: "Advanced AI", color: "#FFD700" },
    interactive: { type: "word-order", instruction: "t16_inst", words: ["t16_w1", "t16_w2", "t16_w3", "t16_w4", "t16_w5"], correctOrder: [0,1,2,3,4] },
    quiz: { question: "t16_q", choices: ["t16_qa", "t16_qb", "t16_qc", "t16_qd"], answer: "t16_qa" }
  },
  {
    infoTitle: "t17_title", infoText: "t17_text",
    svg: { type: "icon-grid", items: [{ emoji: "🤖" }, { emoji: "📈" }, { emoji: "⚙️" }] },
    interactive: { type: "match-pairs", instruction: "t17_inst", pairs: [{ left: "t17_l1", right: "t17_r1" }, { left: "t17_l2", right: "t17_r2" }, { left: "t17_l3", right: "t17_r3" }] },
    quiz: { question: "t17_q", choices: ["t17_qa", "t17_qb", "t17_qc", "t17_qd"], answer: "t17_qa" }
  },
  {
    infoTitle: "t18_title", infoText: "t18_text",
    svg: { type: "simple-icon", icon: "🕸️", title: "Neural Net" },
    interactive: { type: "gap-fill", instruction: "t18_inst", sentence: "t18_sent", choices: ["t18_qa18", "t18_qb18", "t18_qc18", "t18_qd18"], correctIndex: 0 },
    quiz: { question: "t18_q", choices: ["t18_qa", "t18_qb", "t18_qc", "t18_qd"], answer: "t18_qa" }
  },
  {
    infoTitle: "t19_title", infoText: "t19_text",
    svg: { type: "simple-icon", icon: "🔍", title: "Analysis" },
    interactive: { type: "highlight-text", instruction: "t19_inst", tokens: ["t19_tk1", "t19_tk2", "t19_tk3", "t19_tk4"], correctIndices: [3] },
    quiz: { question: "t19_q", choices: ["t19_qa", "t19_qb", "t19_qc", "t19_qd"], answer: "t19_qa" }
  },
  {
    infoTitle: "t20_title", infoText: "t20_text",
    svg: { type: "word-display", word: "Σ x / n", color: "#4CAF50" },
    interactive: { type: "sentence-build", instruction: "t20_inst", fragments: ["t20_f1", "t20_f2", "t20_f3", "t20_f4"] },
    quiz: { question: "t20_q", choices: ["t20_qa", "t20_qb", "t20_qc", "t20_qd"], answer: "t20_qa" }
  },
  {
    infoTitle: "t21_title", infoText: "t21_text",
    svg: { type: "simple-icon", icon: "📊", title: "Visuals" },
    interactive: { type: "drag-to-bucket", instruction: "t21_inst", buckets: [{ id: "c", label: "t21_bl1" }, { id: "n", label: "t21_bl2" }], items: [{ text: "t21_i1", bucketId: "c" }, { text: "t21_i2", bucketId: "n" }, { text: "t21_i3", bucketId: "c" }, { text: "t21_i4", bucketId: "n" }] },
    quiz: { question: "t21_q", choices: ["t21_qa", "t21_qb", "t21_qc", "t21_qd"], answer: "t21_qa" }
  },
  {
    infoTitle: "t22_title", infoText: "t22_text",
    svg: { type: "simple-icon", icon: "☁️", title: "Cloud" },
    interactive: { type: "match-pairs", instruction: "t22_inst", pairs: [{ left: "t22_l1", right: "t22_r1" }, { left: "t22_l2", right: "t22_r2" }, { left: "t22_l3", right: "t22_r3" }] },
    quiz: { question: "t22_q", choices: ["t22_qa", "t22_qb", "t22_qc", "t22_qd"], answer: "t22_qa" }
  },
  {
    infoTitle: "t23_title", infoText: "t23_text",
    svg: { type: "simple-icon", icon: "🏠", title: "IoT" },
    interactive: { type: "gap-fill", instruction: "t23_inst", sentence: "t23_sent", choices: ["t23_qa23", "t23_qb23", "t23_qc23", "t23_qd23"], correctIndex: 0 },
    quiz: { question: "t23_q", choices: ["t23_qa", "t23_qb", "t23_qc", "t23_qd"], answer: "t23_qa" }
  },
  {
    infoTitle: "t24_title", infoText: "t24_text",
    svg: { type: "simple-icon", icon: "🔐", title: "Security" },
    interactive: { type: "word-order", instruction: "t24_inst", words: ["t24_w1", "t24_w2", "t24_w3", "t24_w4", "t24_w5"], correctOrder: [0,1,2,3,4] },
    quiz: { question: "t24_q", choices: ["t24_qa", "t24_qb", "t24_qc", "t24_qd"], answer: "t24_qa" }
  },
  {
    infoTitle: "t25_title", infoText: "t25_text",
    svg: { type: "simple-icon", icon: "👣", title: "Footprint" },
    interactive: { type: "highlight-text", instruction: "t25_inst", tokens: ["t25_tk1", "t25_tk2", "t25_tk3", "t25_tk4"], correctIndices: [2,3] },
    quiz: { question: "t25_q", choices: ["t25_qa", "t25_qb", "t25_qc", "t25_qd"], answer: "t25_qa" }
  },
  {
    infoTitle: "t26_title", infoText: "t26_text",
    svg: { type: "word-display", word: "⛓️ Block-Chain", color: "#607D8B" },
    interactive: { type: "sentence-build", instruction: "t26_inst", fragments: ["t26_f1", "t26_f2", "t26_f3", "t26_f4"] },
    quiz: { question: "t26_q", choices: ["t26_qa", "t26_qb", "t26_qc", "t26_qd"], answer: "t26_qa" }
  },
  {
    infoTitle: "t27_title", infoText: "t27_text",
    svg: { type: "simple-icon", icon: "⚛️", title: "Quantum" },
    interactive: { type: "gap-fill", instruction: "t27_inst", sentence: "t27_sent", choices: ["t27_qa27", "t27_qb27", "t27_qc27", "t27_qd27"], correctIndex: 0 },
    quiz: { question: "t27_q", choices: ["t27_qa", "t27_qb", "t27_qc", "t27_qd"], answer: "t27_qa" }
  },
  {
    infoTitle: "t28_title", infoText: "t28_text",
    svg: { type: "icon-grid", items: [{ emoji: "💻" }, { emoji: "🎨" }, { emoji: "📊" }] },
    interactive: { type: "match-pairs", instruction: "t28_inst", pairs: [{ left: "t28_l1", right: "t28_r1" }, { left: "t28_l2", right: "t28_r2" }, { left: "t28_l3", right: "t28_r3" }] },
    quiz: { question: "t28_q", choices: ["t28_qa", "t28_qb", "t28_qc", "t28_qd"], answer: "t28_qa" }
  },
  {
    infoTitle: "t29_title", infoText: "t29_text",
    svg: { type: "simple-icon", icon: "🌐", title: "Web 3.0" },
    interactive: { type: "word-order", instruction: "t29_inst", words: ["t29_w1", "t29_w2", "t29_w3", "t29_w4", "t29_w5"], correctOrder: [0,1,2,3,4] },
    quiz: { question: "t29_q", choices: ["t29_qa", "t29_qb", "t29_qc", "t29_qd"], answer: "t29_qa" }
  },
  {
    infoTitle: "t30_title", infoText: "t30_text",
    svg: { type: "simple-icon", icon: "🚀", title: "Project" },
    interactive: { type: "gap-fill", instruction: "t30_inst", sentence: "t30_sent", choices: ["t30_qa30", "t30_qb30", "t30_qc30", "t30_qd30"], correctIndex: 0 },
    quiz: { question: "t30_q", choices: ["t30_qa", "t30_qb", "t30_qc", "t30_qd"], answer: "t30_qa" }
  }
];

