// @ts-nocheck
// lib/explorerPools/informatikaK1_i9.ts
import type { PoolTopicDef } from "./types";

export const INFO_K1_I9_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Meister-Insel",
    t1_title: "Meine Punkte", t1_text: "Hier kannst du sehen, wie viele Punkte du gesammelt hast.", t1_inst: "Verbinde die Paare:", t1_h1: "Punkte zählen.", t1_h2: "Deine Belohnung.", t1_q: "Was zeigen die Punkte?", t1_qa: "Deinen Erfolg", t1_qb: "Das Wetter", t1_qc: "Die Uhrzeit", t1_qd: "Dein Alter",
    t1_l1: "Punkte", t1_r1: "Zahl", t1_l2: "Sammeln", t1_r2: "Fleiß", t1_l3: "Stern", t1_r3: "Glanz",
    t2_title: "Sticker-Belohnungen", t2_text: "Für tolle Arbeit bekommst du kleine digitale Sticker.", t2_inst: "Verbinde die Paare:", t2_h1: "Sammle sie alle.", t2_h2: "Schöne Bilder.", t2_q: "Was sind Sticker?", t2_qa: "Kleine Belohnungen", t2_qb: "Echte Äpfel", t2_qc: "Schwere Steine", t2_qd: "Kalte Luft",
    t2_l1: "Sticker", t2_r1: "Bild", t2_l2: "Album", t2_r2: "Platz", t2_l3: "Klebe", t2_r3: "Fest",
    t3_title: "Dein Avatar", t3_text: "Dein Avatar ist deine Spielfigur in der App.", t3_inst: "Verbinde die Paare:", t3_h1: "Das bist du.", t3_h2: "Wähle ein Aussehen.", t3_q: "Wer ist der Avatar?", t3_qa: "Deine Spielfigur", t3_qb: "Ein echter Hund", t3_qc: "Ein Baum", t3_qd: "Ein Auto",
    t3_l1: "Avatar", t3_r1: "Figur", t3_l2: "Kleidung", t3_r2: "Farbe", t3_l3: "Gesicht", t3_r3: "Lächeln",
    t4_title: "Dein Profil", t4_text: "Im Profil stehen dein Name und deine Erfolge.", t4_inst: "Verbinde die Paare:", t4_h1: "Alles über dich.", t4_h2: "Deine Seite.", t4_q: "Was steht im Profil?", t4_qa: "Dein Name", t4_qb: "Ein Kochrezept", t4_qc: "Die Einkaufsliste", t4_qd: "Hausaufgaben",
    t4_l1: "Profil", t4_r1: "Name", t4_l2: "Foto", t4_r2: "Bild", t4_l3: "Info", t4_r3: "Text",
    t5_title: "Einstellungen", t5_text: "Hier kannst du die App so einstellen, wie du sie magst.", t5_inst: "Verbinde die Paare:", t5_h1: "Anpassen.", t5_h2: "Zahnrad-Symbol.", t5_q: "Wo ändert man Dinge?", t5_qa: "In den Einstellungen", t5_qb: "In der Küche", t5_qc: "Im Garten", t5_qd: "Im Bett",
    t5_l1: "Zahnrad", t5_r1: "Symbol", t5_l2: "Ändern", t5_r2: "Wahl", t5_l3: "Menü", t5_r3: "Liste",
    t6_title: "Ton an/aus", t6_text: "Du kannst die Musik und Geräusche ein- oder ausschalten.", t6_inst: "Verbinde die Paare:", t6_h1: "Laut oder leise.", t6_h2: "Hör mal zu.", t6_q: "Was macht der Lautsprecher?", t6_qa: "Töne machen", t6_qb: "Licht machen", t6_qc: "Essen kochen", t6_qd: "Wäsche waschen",
    t6_l1: "Laut", t6_r1: "Musik", t6_l2: "Leise", t6_r2: "Stumm", t6_l3: "Hören", t6_r3: "Ohr",
    t7_title: "Farbe wählen", t7_text: "Wähle deine Lieblingsfarbe für das Aussehen der App.", t7_inst: "Verbinde die Paare:", t7_h1: "Alles bunt.", t7_h2: "Deine Wahl.", t7_q: "Was kann man wählen?", t7_qa: "Die Farbe", t7_qb: "Das Wetter", t7_qc: "Den Wochentag", t7_qd: "Die Schuhgröße",
    t7_l1: "Farbe", t7_r1: "Bunt", t7_l2: "Blau", t7_r2: "Himmel", t7_l3: "Rot", t7_r3: "Herz",
    t8_title: "Sprache wählen", t8_text: "Du kannst die App auf Deutsch oder in anderen Sprachen nutzen.", t8_inst: "Verbinde die Paare:", t8_h1: "Wie wir sprechen.", t8_h2: "Wähle ein Land.", t8_q: "Was ist Deutsch?", t8_qa: "Eine Sprache", t8_qb: "Ein Tier", t8_qc: "Ein Spielzeug", t8_qd: "Ein Obst",
    t8_l1: "Deutsch", t8_r1: "Hallo", t8_l2: "Englisch", t8_r2: "Hello", t8_l3: "Flagge", t8_r3: "Land",
    t9_title: "Hell oder Dunkel?", t9_text: "Wähle, ob die App hell oder dunkel aussehen soll.", t9_inst: "Verbinde die Paare:", t9_h1: "Tag oder Nacht.", t9_h2: "Für deine Augen.", t9_q: "Wann ist es dunkel?", t9_qa: "In der Nacht", t9_qb: "Am Mittag", t9_qc: "In der Sonne", t9_qd: "Beim Licht",
    t9_l1: "Hell", t9_r1: "Sonne", t9_l2: "Dunkel", t9_r2: "Mond", t9_l3: "Modus", t9_r3: "Wahl",
    t10_title: "Elternbereich", t10_text: "Einige Bereiche sind nur für deine Eltern gedacht.", t10_inst: "Verbinde die Paare:", t10_h1: "Für Erwachsene.", t10_h2: "Sicherheit.", t10_q: "Wer darf hier rein?", t10_qa: "Die Eltern", t10_qb: "Das Baby", t10_qc: "Die Katze", t10_qd: "Das Spielzeug",
    t10_l1: "Eltern", t10_r1: "Groß", t10_l2: "Kind", t10_r2: "Klein", t10_l3: "Schutz", t10_r3: "Sicher",
    t11_title: "Offline-Modus", t11_text: "Du kannst auch ohne Internet lernen und spielen.", t11_inst: "Verbinde die Paare:", t11_h1: "Ohne Netz.", t11_h2: "Überall spielen.", t11_q: "Was bedeutet Offline?", t11_qa: "Ohne Internet", t11_qb: "Mit viel Wasser", t11_qc: "Im Flugzeug", t11_qd: "Beim Schlafen",
    t11_l1: "Offline", t11_r1: "Kein Netz", t11_l2: "Online", t11_r2: "Internet", t11_l3: "Spielen", t11_r3: "Immer",
    t12_title: "Fortschritt speichern", t12_text: "Die App merkt sich automatisch, was du schon gelernt hast.", t12_inst: "Verbinde die Paare:", t12_h1: "Nicht vergessen.", t12_h2: "Alles sicher.", t12_q: "Was macht das Speichern?", t12_qa: "Es merkt sich alles", t12_qb: "Es löscht alles", t12_qc: "Es macht Musik", t12_qd: "Es schläft",
    t12_l1: "Speichern", t12_r1: "Behalten", t12_l2: "Lernen", t12_r2: "Wissen", t12_l3: "Fertig", t12_r3: "Häkchen",
    t13_title: "Cloud-Sicherung", t13_text: "Deine Daten können sicher im Internet gespeichert werden.", t13_inst: "Verbinde die Paare:", t13_h1: "In der Wolke.", t13_h2: "Sicherheitskopie.", t13_q: "Was ist die Cloud?", t13_qa: "Ein Speicher im Netz", t13_qb: "Eine echte Wolke", t13_qc: "Ein Regenschirm", t13_qd: "Ein Vogel",
    t13_l1: "Cloud", t13_r1: "Wolke", t13_l2: "Backup", t13_r2: "Sicherung", t13_l3: "Daten", t13_r3: "Infos",
    t14_title: "Lernstufe", t14_text: "Hier siehst du, wie weit du schon gekommen bist.", t14_inst: "Verbinde die Paare:", t14_h1: "Dein Level.", t14_h2: "Immer besser.", t14_q: "Was ist eine Lernstufe?", t14_qa: "Dein Fortschritt", t14_qb: "Eine Treppe", t14_qc: "Ein Berg", t14_qd: "Ein Haus",
    t14_l1: "Stufe", t14_r1: "Level", t14_l2: "Lernen", t14_r2: "Besser", t14_l3: "Ziel", t14_r3: "Ende",
    t15_title: "Meister!", t15_text: "Herzlichen Glückwunsch! Du weißt jetzt alles über die App.", t15_inst: "Verbinde die Paare:", t15_h1: "Du bist der Beste.", t15_h2: "Alles geschafft.", t15_q: "Was bist du jetzt?", t15_qa: "Ein Meister", t15_qb: "Ein Anfänger", t15_qc: "Ein Baum", t15_qd: "Ein Stein",
    t15_l1: "Meister", t15_r1: "Pokal", t15_l2: "Wissen", t15_r2: "Kopf", t15_l3: "Sieg", t15_r3: "Feier"
  },
  en: {
    explorer_title: "Master Island",
    t1_title: "My Points", t1_text: "Here you can see how many points you have collected.", t1_inst: "Match the pairs:", t1_h1: "Count points.", t1_h2: "Your reward.", t1_q: "What do the points show?", t1_qa: "Your success", t1_qb: "The weather", t1_qc: "The time", t1_qd: "Your age",
    t1_l1: "Points", t1_r1: "Number", t1_l2: "Collect", t1_r2: "Effort", t1_l3: "Star", t1_r3: "Shine",
    t2_title: "Sticker Rewards", t2_text: "You get small digital stickers for great work.", t2_inst: "Match the pairs:", t2_h1: "Collect them all.", t2_h2: "Nice pictures.", t2_q: "What are stickers?", t2_qa: "Small rewards", t2_qb: "Real apples", t2_qc: "Heavy stones", t2_qd: "Cold air",
    t2_l1: "Sticker", t2_r1: "Picture", t2_l2: "Album", t2_r2: "Space", t2_l3: "Glue", t2_r3: "Stick",
    t3_title: "Your Avatar", t3_text: "Your avatar is your character in the app.", t3_inst: "Match the pairs:", t3_h1: "This is you.", t3_h2: "Choose a look.", t3_q: "Who is the avatar?", t3_qa: "Your character", t3_qb: "A real dog", t3_qc: "A tree", t3_qd: "A car",
    t3_l1: "Avatar", t3_r1: "Figure", t3_l2: "Clothes", t3_r2: "Color", t3_l3: "Face", t3_r3: "Smile",
    t4_title: "Your Profile", t4_text: "Your profile shows your name and achievements.", t4_inst: "Match the pairs:", t4_h1: "All about you.", t4_h2: "Your page.", t4_q: "What is in the profile?", t4_qa: "Your name", t4_qb: "A recipe", t4_qc: "Shopping list", t4_qd: "Homework",
    t4_l1: "Profile", t4_r1: "Name", t4_l2: "Photo", t4_r2: "Picture", t4_l3: "Info", t4_r3: "Text",
    t5_title: "Settings", t5_text: "Here you can set up the app just the way you like it.", t5_inst: "Match the pairs:", t5_h1: "Customize.", t5_h2: "Gear icon.", t5_q: "Where do you change things?", t5_qa: "In settings", t5_qb: "In the kitchen", t5_qc: "In the garden", t5_qd: "In bed",
    t5_l1: "Gear", t5_r1: "Icon", t5_l2: "Change", t5_r2: "Choice", t5_l3: "Menu", t5_r3: "List",
    t6_title: "Sound On/Off", t6_text: "You can turn the music and sounds on or off.", t6_inst: "Match the pairs:", t6_h1: "Loud or quiet.", t6_h2: "Listen up.", t6_q: "What does the speaker do?", t6_qa: "Make sounds", t6_qb: "Make light", t6_qc: "Cook food", t6_qd: "Wash clothes",
    t6_l1: "Loud", t6_r1: "Music", t6_l2: "Quiet", t6_r2: "Mute", t6_l3: "Hear", t6_r3: "Ear",
    t7_title: "Choose Color", t7_text: "Pick your favorite color for the app's look.", t7_inst: "Match the pairs:", t7_h1: "All colorful.", t7_h2: "Your choice.", t7_q: "What can you choose?", t7_qa: "The color", t7_qb: "The weather", t7_qc: "The day", t7_qd: "Shoe size",
    t7_l1: "Color", t7_r1: "Bright", t7_l2: "Blue", t7_r2: "Sky", t7_l3: "Red", t7_r3: "Heart",
    t8_title: "Choose Language", t8_text: "You can use the app in English or other languages.", t8_inst: "Match the pairs:", t8_h1: "How we speak.", t8_h2: "Pick a country.", t8_q: "What is English?", t8_qa: "A language", t8_qb: "An animal", t8_qc: "A toy", t8_qd: "A fruit",
    t8_l1: "English", t8_r1: "Hello", t8_l2: "German", t8_r2: "Hallo", t8_l3: "Flag", t8_r3: "Country",
    t9_title: "Light or Dark?", t9_text: "Choose if the app should look light or dark.", t9_inst: "Match the pairs:", t9_h1: "Day or night.", t9_h2: "For your eyes.", t9_q: "When is it dark?", t9_qa: "At night", t9_qb: "At noon", t9_qc: "In the sun", t9_qd: "With light",
    t9_l1: "Light", t9_r1: "Sun", t9_l2: "Dark", t9_r2: "Moon", t9_l3: "Mode", t9_r3: "Choice",
    t10_title: "Parental Control", t10_text: "Some areas are meant only for your parents.", t10_inst: "Match the pairs:", t10_h1: "For adults.", t10_h2: "Safety.", t10_q: "Who can enter here?", t10_qa: "Parents", t10_qb: "The baby", t10_qc: "The cat", t10_qd: "The toy",
    t10_l1: "Parents", t10_r1: "Big", t10_l2: "Child", t10_r2: "Small", t10_l3: "Guard", t10_r3: "Safe",
    t11_title: "Offline Mode", t11_text: "You can learn and play even without internet.", t11_inst: "Match the pairs:", t11_h1: "No network.", t11_h2: "Play anywhere.", t11_q: "What does offline mean?", t11_qa: "No internet", t11_qb: "With water", t11_qc: "On a plane", t11_qd: "While sleeping",
    t11_l1: "Offline", t11_r1: "No net", t11_l2: "Online", t11_r2: "Internet", t11_l3: "Play", t11_r3: "Always",
    t12_title: "Save Progress", t12_text: "The app automatically remembers what you have learned.", t12_inst: "Match the pairs:", t12_h1: "Don't forget.", t12_h2: "All safe.", t12_q: "What does saving do?", t12_qa: "Remembers all", t12_qb: "Deletes all", t12_qc: "Makes music", t12_qd: "Sleeps",
    t12_l1: "Save", t12_r1: "Keep", t12_l2: "Learn", t12_r2: "Know", t12_l3: "Done", t12_r3: "Check",
    t13_title: "Cloud Backup", t13_text: "Your data can be safely stored on the internet.", t13_inst: "Match the pairs:", t13_h1: "In the cloud.", t13_h2: "Safety copy.", t13_q: "What is the cloud?", t13_qa: "Online storage", t13_qb: "A real cloud", t13_qc: "Umbrella", t13_qd: "A bird",
    t13_l1: "Cloud", t13_r1: "Sky", t13_l2: "Backup", t13_r2: "Safety", t13_l3: "Data", t13_r3: "Info",
    t14_title: "Learning Level", t14_text: "Here you can see how far you have come.", t14_inst: "Match the pairs:", t14_h1: "Your level.", t14_h2: "Getting better.", t14_q: "What is a learning level?", t14_qa: "Your progress", t14_qb: "A staircase", t14_qc: "A mountain", t14_qd: "A house",
    t14_l1: "Level", t14_r1: "Step", t14_l2: "Learn", t14_r2: "Better", t14_l3: "Goal", t14_r3: "End",
    t15_title: "Master!", t15_text: "Congratulations! You now know everything about the app.", t15_inst: "Match the pairs:", t15_h1: "You are the best.", t15_h2: "All done.", t15_q: "What are you now?", t15_qa: "A Master", t15_qb: "A beginner", t15_qc: "A tree", t15_qd: "A stone",
    t15_l1: "Master", t15_r1: "Cup", t15_l2: "Knowledge", t15_r2: "Head", t15_l3: "Win", t15_r3: "Party"
  },
  hu: {
    explorer_title: "Mester sziget",
    t1_title: "Mi a pontom?", t1_text: "Itt láthatod, hogy mennyi pontot gyűjtöttél össze.", t1_inst: "Párosítsd össze:", t1_h1: "Pontok száma.", t1_h2: "A jutalmad.", t1_q: "Mit mutatnak a pontok?", t1_qa: "A sikeredet", t1_qb: "Az időjárást", t1_qc: "Az időt", t1_qd: "Az életkorod",
    t1_l1: "Pontok", t1_r1: "Szám", t1_l2: "Gyűjtés", t1_r2: "Szorgalom", t1_l3: "Csillag", t1_r3: "Fény",
    t2_title: "Kis matrica jutalmak", t2_text: "A szép munkáért apró digitális matricákat kapsz.", t2_inst: "Párosítsd össze:", t2_h1: "Gyűjtsd össze mind.", t2_h2: "Szép képek.", t2_q: "Mik azok a matricák?", t2_qa: "Apró jutalmak", t2_qb: "Igazi almák", t2_qc: "Nehéz kövek", t2_qd: "Hideg levegő",
    t2_l1: "Matrica", t2_r1: "Kép", t2_l2: "Album", t2_r2: "Hely", t2_l3: "Ragacs", t2_r3: "Tapadás",
    t3_title: "Avatár / karaktered", t3_text: "Az avatár a te saját figurád az alkalmazásban.", t3_inst: "Párosítsd össze:", t3_h1: "Ez vagy te.", t3_h2: "Válassz kinézetet.", t3_q: "Ki az az avatár?", t3_qa: "A te figurád", t3_qb: "Egy igazi kutya", t3_qc: "Egy fa", t3_qd: "Egy autó",
    t3_l1: "Avatár", t3_r1: "Figura", t3_l2: "Ruha", t3_r2: "Szín", t3_l3: "Arc", t3_r3: "Mosoly",
    t4_title: "Profilod", t4_text: "A profilodban szerepel a neved és az eredményeid.", t4_inst: "Párosítsd össze:", t4_h1: "Minden rólad.", t4_h2: "A te oldalad.", t4_q: "Mi van a profilban?", t4_qa: "A neved", t4_qb: "Egy recept", t4_qc: "Bevásárlólista", t4_qd: "Házi feladat",
    t4_l1: "Profil", t4_r1: "Név", t4_l2: "Fotó", t4_r2: "Kép", t4_l3: "Infó", t4_r3: "Szöveg",
    t5_title: "Beállítások", t5_text: "Itt tudod úgy beállítani a gépet, ahogy neked tetszik.", t5_inst: "Párosítsd össze:", t5_h1: "Alakítsd át.", t5_h2: "Fogaskerék ikon.", t5_q: "Hol változtathatsz dolgokat?", t5_qa: "A beállításokban", t5_qb: "A konyhában", t5_qc: "A kertben", t5_qd: "Az ágyban",
    t5_l1: "Fogaskerék", t5_r1: "Ikon", t5_l2: "Váltás", t5_r2: "Választás", t5_l3: "Menü", t5_r3: "Lista",
    t6_title: "Hang be/ki", t6_text: "Ki- és bekapcsolhatod a zenét és a hangokat.", t6_inst: "Párosítsd össze:", t6_h1: "Hangos vagy halk.", t6_h2: "Figyelj csak.", t6_q: "Mit csinál a hangszóró?", t6_qa: "Hangot ad", t6_qb: "Világít", t6_qc: "Főz", t6_qd: "Mos",
    t6_l1: "Hangos", t6_r1: "Zene", t6_l2: "Halk", t6_r2: "Néma", t6_l3: "Hallás", t6_r3: "Fül",
    t7_title: "Színtéma választás", t7_text: "Válaszd ki a kedvenc színedet az alkalmazáshoz.", t7_inst: "Párosítsd össze:", t7_h1: "Legyen színes.", t7_h2: "A te döntésed.", t7_q: "Mit választhatsz ki?", t7_qa: "A színt", t7_qb: "Az időjárást", t7_qc: "A napot", t7_qd: "A cipőméretet",
    t7_l1: "Szín", t7_r1: "Színes", t7_l2: "Kék", t7_r2: "Égbolt", t7_l3: "Piros", t7_r3: "Szív",
    t8_title: "Nyelv beállítása", t8_text: "Használhatod a gépet magyarul vagy más nyelveken is.", t8_inst: "Párosítsd össze:", t8_h1: "Ahogy beszélünk.", t8_h2: "Válassz országot.", t8_q: "Mi a magyar?", t8_qa: "Egy nyelv", t8_qb: "Egy állat", t8_qc: "Egy játék", t8_qd: "Egy gyümölcs",
    t8_l1: "Magyar", t8_r1: "Szia", t8_l2: "Angol", t8_r2: "Hello", t8_l3: "Zászló", t8_r3: "Ország",
    t9_title: "Sötét vagy világos?", t9_text: "Válaszd ki, hogy sötét vagy világos legyen a képernyő.", t9_inst: "Párosítsd össze:", t9_h1: "Nappal vagy éjjel.", t9_h2: "A szemednek.", t9_q: "Mikor van sötét?", t9_qa: "Éjszaka", t9_qb: "Délben", t9_qc: "A napon", t9_qd: "Lámpánál",
    t9_l1: "Világos", t9_r1: "Nap", t9_l2: "Sötét", t9_r2: "Hold", t9_l3: "Mód", t9_r3: "Választás",
    t10_title: "Szülői kontroll", t10_text: "Vannak részek, amik csak a szüleidnek szólnak.", t10_inst: "Párosítsd össze:", t10_h1: "Felnőtteknek.", t10_h2: "Biztonság.", t10_q: "Ki léphet be ide?", t10_qa: "A szülők", t10_qb: "A kisbaba", t10_qc: "A macska", t10_qd: "A játék",
    t10_l1: "Szülő", t10_r1: "Nagy", t10_l2: "Gyerek", t10_r2: "Kicsi", t10_l3: "Védő", t10_r3: "Biztonság",
    t11_title: "Offline mód", t11_text: "Internet nélkül is tudsz tanulni és játszani.", t11_inst: "Párosítsd össze:", t11_h1: "Nincs hálózat.", t11_h2: "Bárhol játszhatsz.", t11_q: "Mit jelent az offline?", t11_qa: "Nincs internet", t11_qb: "Sok víz van", t11_qc: "Repülőn vagy", t11_qd: "Alvás közben",
    t11_l1: "Offline", t11_r1: "Nincs net", t11_l2: "Online", t11_r2: "Internet", t11_l3: "Játék", t11_r3: "Mindig",
    t12_title: "Haladás mentése", t12_text: "A gép automatikusan megjegyzi, hol tartasz a tanulásban.", t12_inst: "Párosítsd össze:", t12_h1: "Ne felejtsd el.", t12_h2: "Minden megvan.", t12_q: "Mit csinál a mentés?", t12_qa: "Megjegyzi a dolgokat", t12_qb: "Kitöröl mindent", t12_qc: "Zenél", t12_qd: "Alszik",
    t12_l1: "Mentés", t12_r1: "Megtartás", t12_l2: "Tanulás", t12_r2: "Tudás", t12_l3: "Kész", t12_r3: "Pipa",
    t13_title: "Biztonsági mentés", t13_text: "Az adataidat biztonságban tárolhatod az interneten.", t13_inst: "Párosítsd össze:", t13_h1: "A felhőben.", t13_h2: "Másolat készítése.", t13_q: "Mi az a felhő?", t13_qa: "Internet-tárhely", t13_qb: "Egy igazi felhő", t13_qc: "Esernyő", t13_qd: "Egy madár",
    t13_l1: "Felhő", t13_r1: "Égbolt", t13_l2: "Másolat", t13_r2: "Biztonság", t13_l3: "Adat", t13_r3: "Infó",
    t14_title: "Tanulmányi szint", t14_text: "Itt láthatod, hogy milyen ügyes vagy már.", t14_inst: "Párosítsd össze:", t14_h1: "A te szinted.", t14_h2: "Egyre jobb.", t14_q: "Mi a tanulmányi szint?", t14_qa: "A haladásod", t14_qb: "Egy lépcső", t14_qc: "Egy hegy", t14_qd: "Egy ház",
    t14_l1: "Szint", t14_r1: "Fokozat", t14_l2: "Tanulás", t14_r2: "Jobb", t14_l3: "Cél", t14_r3: "Vége",
    t15_title: "Mester!", t15_text: "Gratulálunk! Most már mindent tudsz a használatról.", t15_inst: "Párosítsd össze:", t15_h1: "Te vagy a legjobb.", t15_h2: "Mindent tudsz.", t15_q: "Mi vagy te most?", t15_qa: "Egy Mester", t15_qb: "Egy kezdő", t15_qc: "Egy fa", t15_qd: "Egy kő",
    t15_l1: "Mester", t15_r1: "Kupa", t15_l2: "Tudás", t15_r2: "Fej", t15_l3: "Győzelem", t15_r3: "Ünnep"
  },
  ro: {
    explorer_title: "Insula Maestrului",
    t1_title: "Punctele mele", t1_text: "Aici poți vedea câte puncte ai adunat.", t1_inst: "Potrivește perechile:", t1_h1: "Numără punctele.", t1_h2: "Recompensa ta.", t1_q: "Ce arată punctele?", t1_qa: "Succesul tău", t1_qb: "Vremea", t1_qc: "Ora", t1_qd: "Vârsta ta",
    t1_l1: "Puncte", t1_r1: "Număr", t1_l2: "Colectare", t1_r2: "Hărnicie", t1_l3: "Stea", t1_r3: "Strălucire",
    t2_title: "Stickere recompensă", t2_text: "Primești stickere digitale mici pentru munca depusă.", t2_inst: "Potrivește perechile:", t2_h1: "Adună-le pe toate.", t2_h2: "Imagini frumoase.", t2_q: "Ce sunt stickerele?", t2_qa: "Mici recompense", t2_qb: "Mere adevărate", t2_qc: "Pietre grele", t2_qd: "Aer rece",
    t2_l1: "Sticker", t2_r1: "Imagine", t2_l2: "Album", t2_r2: "Loc", t2_l3: "Lipici", t2_r3: "Fix",
    t3_title: "Avatarul tău", t3_text: "Avatarul este personajul tău în aplicație.", t3_inst: "Potrivește perechile:", t3_h1: "Acesta ești tu.", t3_h2: "Alege un aspect.", t3_q: "Cine este avatarul?", t3_qa: "Personajul tău", t3_qb: "Un câine real", t3_qc: "Un copac", t3_qd: "O mașină",
    t3_l1: "Avatar", t3_r1: "Figură", t3_l2: "Haine", t3_r2: "Culoare", t3_l3: "Față", t3_r3: "Zâmbet",
    t4_title: "Profilul tău", t4_text: "În profil apar numele și rezultatele tale.", t4_inst: "Potrivește perechile:", t4_h1: "Totul despre tine.", t4_h2: "Pagina ta.", t4_q: "Ce este în profil?", t4_qa: "Numele tău", t4_qb: "O rețetă", t4_qc: "Lista de cumpărături", t4_qd: "Teme",
    t4_l1: "Profil", t4_r1: "Nume", t4_l2: "Foto", t4_r2: "Imagine", t4_l3: "Info", t4_r3: "Text",
    t5_title: "Setări", t5_text: "Aici poți seta aplicația așa cum îți place.", t5_inst: "Potrivește perechile:", t5_h1: "Personalizează.", t5_h2: "Pictogramă rotiță.", t5_q: "Unde schimbi lucrurile?", t5_qa: "În setări", t5_qb: "În bucătărie", t5_qc: "În grădină", t5_qd: "În pat",
    t5_l1: "Rotiță", t5_r1: "Simbol", t5_l2: "Schimbare", t5_r2: "Alegere", t5_l3: "Meniu", t5_r3: "Listă",
    t6_title: "Sunet pornit/oprit", t6_text: "Poți porni sau opri muzica și sunetele.", t6_inst: "Potrivește perechile:", t6_h1: "Tare sau încet.", t6_h2: "Ascultă.", t6_q: "Ce face difuzorul?", t6_qa: "Scoate sunete", t6_qb: "Face lumină", t6_qc: "Gătește", t6_qd: "Spală",
    t6_l1: "Tare", t6_r1: "Muzică", t6_l2: "Încet", t6_r2: "Mut", t6_l3: "Auz", t6_r3: "Ureche",
    t7_title: "Alegere temă", t7_text: "Alege culoarea preferată pentru aplicație.", t7_inst: "Potrivește perechile:", t7_h1: "Să fie colorat.", t7_h2: "Decizia ta.", t7_q: "Ce poți alege?", t7_qa: "Culoarea", t7_qb: "Vremea", t7_qc: "Ziua", t7_qd: "Mărimea la pantofi",
    t7_l1: "Culoare", t7_r1: "Colorat", t7_l2: "Albastru", t7_r2: "Cer", t7_l3: "Roșu", t7_r3: "Inimă",
    t8_title: "Setare limbă", t8_text: "Poți folosi aplicația în română sau în alte limbi.", t8_inst: "Potrivește perechile:", t8_h1: "Cum vorbim.", t8_h2: "Alege o țară.", t8_q: "Ce este româna?", t8_qa: "O limbă", t8_qb: "Un animal", t8_qc: "O jucărie", t8_qd: "Un fruct",
    t8_l1: "Română", t8_r1: "Bună", t8_l2: "Engleză", t8_r2: "Hello", t8_l3: "Steag", t8_r3: "Țară",
    t9_title: "Întunecat sau luminos?", t9_text: "Alege dacă ecranul să fie luminos sau întunecat.", t9_inst: "Potrivește perechile:", t9_h1: "Zi sau noapte.", t9_h2: "Pentru ochi.", t9_q: "Când este întuneric?", t9_qa: "Noaptea", t9_qb: "La prânz", t9_qc: "La soare", t9_qd: "La lampă",
    t9_l1: "Luminos", t9_r1: "Soare", t9_l2: "Întunecat", t9_r2: "Lună", t9_l3: "Mod", t9_r3: "Alegere",
    t10_title: "Control parental", t10_text: "Există părți care sunt doar pentru părinții tăi.", t10_inst: "Potrivește perechile:", t10_h1: "Pentru adulți.", t10_h2: "Siguranță.", t10_q: "Cine poate intra aici?", t10_qa: "Părinții", t10_qb: "Bebelușul", t10_qc: "Pisica", t10_qd: "Jucăria",
    t10_l1: "Părinte", t10_r1: "Mare", t10_l2: "Copil", t10_r2: "Mic", t10_l3: "Protecție", t10_r3: "Sigur",
    t11_title: "Mod offline", t11_text: "Poți învăța și te poți juca și fără internet.", t11_inst: "Potrivește perechile:", t11_h1: "Fără rețea.", t11_h2: "Joacă-te oriunde.", t11_q: "Ce înseamnă offline?", t11_qa: "Fără internet", t11_qb: "Multă apă", t11_qc: "În avion", t11_qd: "În somn",
    t11_l1: "Offline", t11_r1: "Fără net", t11_l2: "Online", t11_r2: "Internet", t11_l3: "Joc", t11_r3: "Mereu",
    t12_title: "Salvare progres", t12_text: "Aplicația reține automat unde ai rămas cu învățatul.", t12_inst: "Potrivește perechile:", t12_h1: "Nu uita.", t12_h2: "Totul e salvat.", t12_q: "Ce face salvarea?", t12_qa: "Reține lucrurile", t12_qb: "Șterge tot", t12_qc: "Cântă", t12_qd: "Doarme",
    t12_l1: "Salvare", t12_r1: "Păstrare", t12_l2: "Învățare", t12_r2: "Cunoaștere", t12_l3: "Gata", t12_r3: "Bifă",
    t13_title: "Copie de siguranță", t13_text: "Datele tale pot fi păstrate în siguranță pe internet.", t13_inst: "Potrivește perechile:", t13_h1: "În cloud.", t13_h2: "Creare copie.", t13_q: "Ce este cloud-ul?", t13_qa: "Stocare internet", t13_qb: "Un nor real", t13_qc: "Umbrelă", t13_qd: "O pasăre",
    t13_l1: "Cloud", t13_r1: "Cer", t13_l2: "Copie", t13_r2: "Siguranță", t13_l3: "Date", t13_r3: "Info",
    t14_title: "Nivel de studiu", t14_text: "Aici poți vedea cât de priceput ești deja.", t14_inst: "Potrivește perechile:", t14_h1: "Nivelul tău.", t14_h2: "Tot mai bun.", t14_q: "Ce este nivelul de studiu?", t14_qa: "Progresul tău", t14_qb: "O scară", t14_qc: "Un munte", t14_qd: "O casă",
    t14_l1: "Nivel", t14_r1: "Treaptă", t14_l2: "Învățare", t14_r2: "Mai bun", t14_l3: "Scop", t14_r3: "Sfârșit",
    t15_title: "Maestru!", t15_text: "Felicitări! Acum știi totul despre utilizare.", t15_inst: "Potrivește perechile:", t15_h1: "Ești cel mai bun.", t15_h2: "Știi totul.", t15_q: "Ce ești acum?", t15_qa: "Un Maestru", t15_qb: "Un începător", t15_qc: "Un copac", t15_qd: "O piatră",
    t15_l1: "Maestru", t15_r1: "Cupă", t15_l2: "Cunoaștere", t15_r2: "Cap", t15_l3: "Victorie", t15_r3: "Sărbătoare"
  }
};

export const INFO_K1_I9_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["⭐", "🏷️", "👤", "🆔", "⚙️", "🔊", "🎨", "🌐", "🌗", "🔒", "✈️", "💾", "☁️", "📈", "🏆"];
  const colors = ["#FFD700", "#FF4081", "#2196F3", "#4CAF50", "#9E9E9E", "#FF9800", "#9C27B0", "#3F51B5", "#607D8B", "#F44336", "#00BCD4", "#795548", "#03A9F4", "#8BC34A", "#FFC107"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

