// lib/explorerPools/informatikaK2_i7.ts
import type { PoolTopicDef } from "./types";

export const INFO_K2_I7_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Präsentation",
    t1_title: "Was ist eine Präsentation?", t1_text: "Eine Präsentation hilft dir, deine Ideen mit Bildern und Text zu zeigen.", t1_inst: "Verbinde die Paare:", t1_h1: "Ideen zeigen.", t1_h2: "Bilder und Text.", t1_q: "Wofür ist eine Präsentation gut?", t1_qa: "Um Ideen zu zeigen", t1_qb: "Zum Suppe kochen", t1_qc: "Zum Schlafen", t1_qd: "Zum Zähneputzen",
    t1_l1: "Präsentation", t1_r1: "Vortrag", t1_l2: "Idee", t1_r2: "Zeigen", t1_l3: "Publikum", t1_r3: "Zuschauer",
    t2_title: "Neue Folie", t2_text: "Jede neue Seite in deiner Präsentation nennt man Folie.", t2_inst: "Verbinde die Paare:", t2_h1: "Eine neue Seite.", t2_h2: "Klick auf das Plus.", t2_q: "Wie nennt man eine Seite in PowerPoint?", t2_qa: "Folie", t2_qb: "Blatt Papier", t2_qc: "Fenster", t2_qd: "Tisch",
    t2_l1: "Neu", t2_r1: "Folie", t2_l2: "Plus", t2_r2: "Hinzufügen", t2_l3: "Seite", t2_r3: "Inhalt",
    t3_title: "Titel eingeben", t3_text: "Schreibe die Überschrift in das große Feld oben.", t3_inst: "Verbinde die Paare:", t3_h1: "Der Name vom Thema.", t3_h2: "Ganz oben.", t3_q: "Wo steht meistens der Titel?", t3_qa: "Ganz oben", t3_qb: "Unter dem Tisch", t3_qc: "Im Keller", t3_qd: "Ganz unten",
    t3_l1: "Titel", t3_r1: "Name", t3_l2: "Textfeld", t3_r2: "Schreiben", t3_l3: "Groß", t3_r3: "Wichtig",
    t4_title: "Inhalt schreiben", t4_text: "Schreibe kurze Sätze, damit die Zuschauer alles gut lesen können.", t4_inst: "Verbinde die Paare:", t4_h1: "Nicht zu viel Text.", t4_h2: "Wichtige Infos.", t4_q: "Was sollte man auf die Folie schreiben?", t4_qa: "Kurze Sätze", t4_qb: "Ein ganzes Buch", t4_qc: "Geheimnisse", t4_qd: "Nichts",
    t4_l1: "Inhalt", t4_r1: "Text", t4_l2: "Lesen", t4_r2: "Auge", t4_l3: "Kurz", t4_r3: "Einfach",
    t5_title: "Bilder einfügen", t5_text: "Bilder machen deine Präsentation viel schöner und spannender.", t5_inst: "Verbinde die Paare:", t5_h1: "Fotos benutzen.", t5_h2: "Einfügen Menü.", t5_q: "Was macht eine Folie spannender?", t5_qa: "Bilder", t5_qb: "Dunkelheit", t5_qc: "Leere", t5_qd: "Staub",
    t5_l1: "Bild", t5_r1: "Foto", t5_l2: "Einfügen", t5_r2: "Hinzufügen", t5_l3: "Schön", t5_r3: "Bunt",
    t6_title: "Hintergrund wählen", t6_text: "Wähle eine schöne Farbe oder ein Muster für deine Folien.", t6_inst: "Verbinde die Paare:", t6_h1: "Die Farbe hinten.", t6_h2: "Design wählen.", t6_q: "Was ist der Hintergrund?", t6_qa: "Die Farbe hinten", t6_qb: "Ein Vorhang", t6_qc: "Ein Teppich", t6_qd: "Der Himmel",
    t6_l1: "Hintergrund", t6_r1: "Hinten", t6_l2: "Farbe", t6_r2: "Bunt", t6_l3: "Design", t6_r3: "Muster",
    t7_title: "Übergänge", t7_text: "Ein Übergang ist eine Animation, wenn du zur nächsten Folie wechselst.", t7_inst: "Verbinde die Paare:", t7_h1: "Von Folie zu Folie.", t7_h2: "Bewegung beim Wechsel.", t7_q: "Was ist ein Übergang?", t7_qa: "Wechsel-Animation", t7_qb: "Eine Brücke", t7_qc: "Ein Tunnel", t7_qd: "Ein Sprung",
    t7_l1: "Übergang", t7_r1: "Wechsel", t7_l2: "Nächste", t7_r2: "Folie", t7_l3: "Effekt", t7_r3: "Bewegung",
    t8_title: "Animationen", t8_text: "Lasse Bilder oder Texte auf die Folie fliegen oder hüpfen.", t8_inst: "Verbinde die Paare:", t8_h1: "Dinge bewegen sich.", t8_h2: "Effekte für Text.", t8_q: "Was macht eine Animation?", t8_qa: "Bewegt Objekte", t8_qb: "Löscht alles", t8_qc: "Macht Musik", t8_qd: "Schaltet aus",
    t8_l1: "Animation", t8_r1: "Bewegung", t8_l2: "Einfliegen", t8_r2: "Effekt", t8_l3: "Klick", t8_r3: "Start",
    t9_title: "Folien-Reihenfolge", t9_text: "Du kannst die Folien verschieben, um die Reihenfolge zu ändern.", t9_inst: "Verbinde die Paare:", t9_h1: "Was kommt zuerst?", t9_h2: "Sortieren.", t9_q: "Kann man die Reihenfolge ändern?", t9_qa: "Ja, durch Verschieben", t9_qb: "Nein, nie", t9_qc: "Nur mit Schere", t9_qd: "Nur nachts",
    t9_l1: "Reihenfolge", t9_r1: "Sortieren", t9_l2: "Verschieben", t9_r2: "Maus", t9_l3: "Zuerst", t9_r3: "Start",
    t10_title: "Notizen", t10_text: "Schreibe dir Notizen auf, die nur du beim Vortrag sehen kannst.", t10_inst: "Verbinde die Paare:", t10_h1: "Hilfe für dich.", t10_h2: "Unter der Folie.", t10_q: "Wer sieht die Notizen?", t10_qa: "Nur der Sprecher", t10_qb: "Alle Zuschauer", t10_qc: "Niemand", t10_qd: "Der Hund",
    t10_l1: "Notiz", t10_r1: "Hilfe", t10_l2: "Sprecher", t10_r2: "Du", t10_l3: "Geheim", t10_r3: "Unsichtbar",
    t11_title: "Abspielen", t11_text: "Starte deine Präsentation, um sie in groß zu sehen.", t11_inst: "Verbinde die Paare:", t11_h1: "Ganz groß machen.", t11_h2: "F5 Taste drücken.", t11_q: "Wie sieht man die Präsentation groß?", t11_qa: "Präsentationsmodus", t11_qb: "Mit der Lupe", t11_qc: "Monitor drehen", t11_qd: "Licht aus",
    t11_l1: "Abspielen", t11_r1: "Start", t11_l2: "Vollbild", t11_r2: "Groß", t11_l3: "Taste", t11_r3: "F5",
    t12_title: "Vorführen", t12_text: "Benutze die Pfeiltasten, um zur nächsten Folie zu gehen.", t12_inst: "Verbinde die Paare:", t12_h1: "Weiter klicken.", t12_h2: "Pfeil nach rechts.", t12_q: "Wie geht man zur nächsten Folie?", t12_qa: "Pfeiltaste", t12_qb: "Laut schreien", t12_qc: "Warten", t12_qd: "Tastatur werfen",
    t12_l1: "Weiter", t12_r1: "Pfeil", t12_l2: "Tastatur", t12_r2: "Steuerung", t12_l3: "Vortrag", t12_r3: "Reden",
    t13_title: "Export als PDF", t13_text: "Speichere deine Präsentation als PDF, damit jeder sie lesen kann.", t13_inst: "Verbinde die Paare:", t13_h1: "Ein festes Format.", t13_h2: "Zum Verschicken.", t13_q: "Was ist ein PDF?", t13_qa: "Ein Dokument-Format", t13_qb: "Ein Spiel", t13_qc: "Ein Foto", t13_qd: "Ein Video",
    t13_l1: "Export", t13_r1: "Speichern", t13_l2: "PDF", t13_r2: "Format", t13_l3: "Teilen", t13_r3: "Senden",
    t14_title: "Speichern als PPTX", t14_text: "Speichere deine Arbeit, damit du sie später weiter bearbeiten kannst.", t14_inst: "Verbinde die Paare:", t14_h1: "PowerPoint Datei.", t14_h2: "Nicht vergessen.", t14_q: "Wie heißt die PowerPoint-Datei?", t14_qa: "PPTX", t14_qb: "DOCX", t14_qc: "MP3", t14_qd: "JPG",
    t14_l1: "Speichern", t14_r1: "Behalten", t14_l2: "PPTX", t14_r2: "Datei", t14_l3: "Arbeit", t14_r3: "Fertig",
    t15_title: "Präsentations-Meister", t15_text: "Du kannst jetzt tolle Shows am Computer erstellen!", t15_inst: "Verbinde die Paare:", t15_h1: "Super gemacht!", t15_h2: "Alles gelernt.", t15_q: "Was bist du jetzt?", t15_qa: "Präsentations-Profi", t15_qb: "Ein Koch", t15_qc: "Ein Pilot", t15_qd: "Ein Fisch",
    t15_l1: "Meister", t15_r1: "Profi", t15_l2: "Show", t15_r2: "Erfolg", t15_l3: "Ende", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "Presentation",
    t1_title: "What is a Presentation?", t1_text: "A presentation helps you show your ideas with pictures and text.", t1_inst: "Match the pairs:", t1_h1: "Showing ideas.", t1_h2: "Pictures and text.", t1_q: "What is a presentation good for?", t1_qa: "To show ideas", t1_qb: "To cook soup", t1_qc: "To sleep", t1_qd: "To brush teeth",
    t1_l1: "Presentation", t1_r1: "Talk", t1_l2: "Idea", t1_r2: "Show", t1_l3: "Audience", t1_r3: "Viewers",
    t2_title: "New Slide", t2_text: "Every new page in your presentation is called a slide.", t2_inst: "Match the pairs:", t2_h1: "A new page.", t2_h2: "Click the plus.", t2_q: "What is a page in PowerPoint called?", t2_qa: "Slide", t2_qb: "Sheet of paper", t2_qc: "Window", t2_qd: "Table",
    t2_l1: "New", t2_r1: "Slide", t2_l2: "Plus", t2_r2: "Add", t2_l3: "Page", t2_r3: "Content",
    t3_title: "Enter Title", t3_text: "Write the heading in the large box at the top.", t3_inst: "Match the pairs:", t3_h1: "The name of the topic.", t3_h2: "At the very top.", t3_q: "Where is the title usually located?", t3_qa: "At the top", t3_qb: "Under the table", t3_qc: "In the basement", t3_qd: "At the bottom",
    t3_l1: "Title", t3_r1: "Name", t3_l2: "Text box", t3_r2: "Write", t3_l3: "Large", t3_r3: "Important",
    t4_title: "Write Content", t4_text: "Write short sentences so the audience can read everything easily.", t4_inst: "Match the pairs:", t4_h1: "Not too much text.", t4_h2: "Important info.", t4_q: "What should you write on the slide?", t4_qa: "Short sentences", t4_qb: "A whole book", t4_qc: "Secrets", t4_qd: "Nothing",
    t4_l1: "Content", t4_r1: "Text", t4_l2: "Read", t4_r2: "Eye", t4_l3: "Short", t4_r3: "Simple",
    t5_title: "Insert Pictures", t5_text: "Pictures make your presentation much nicer and more exciting.", t5_inst: "Match the pairs:", t5_h1: "Use photos.", t5_h2: "Insert menu.", t5_q: "What makes a slide more exciting?", t5_qa: "Pictures", t5_qb: "Darkness", t5_qc: "Emptiness", t5_qd: "Dust",
    t5_l1: "Picture", t5_r1: "Photo", t5_l2: "Insert", t5_r2: "Add", t5_l3: "Nice", t5_r3: "Colorful",
    t6_title: "Choose Background", t6_text: "Choose a nice color or pattern for your slides.", t6_inst: "Match the pairs:", t6_h1: "The color in the back.", t6_h2: "Select design.", t6_q: "What is the background?", t6_qa: "The color in the back", t6_qb: "A curtain", t6_qc: "A carpet", t6_qd: "The sky",
    t6_l1: "Background", t6_r1: "Back", t6_l2: "Color", t6_r2: "Colorful", t6_l3: "Design", t6_r3: "Pattern",
    t7_title: "Transitions", t7_text: "A transition is an animation when you move to the next slide.", t7_inst: "Match the pairs:", t7_h1: "From slide to slide.", t7_h2: "Movement when changing.", t7_q: "What is a transition?", t7_qa: "Change animation", t7_qb: "A bridge", t7_qc: "A tunnel", t7_qd: "A jump",
    t7_l1: "Transition", t7_r1: "Change", t7_l2: "Next", t7_r2: "Slide", t7_l3: "Effect", t7_r3: "Movement",
    t8_title: "Animations", t8_text: "Make pictures or text fly or bounce onto the slide.", t8_inst: "Match the pairs:", t8_h1: "Things move.", t8_h2: "Effects for text.", t8_q: "What does an animation do?", t8_qa: "Moves objects", t8_qb: "Deletes everything", t8_qc: "Makes music", t8_qd: "Turns off",
    t8_l1: "Animation", t8_r1: "Movement", t8_l2: "Fly in", t8_r2: "Effect", t8_l3: "Click", t8_r3: "Start",
    t9_title: "Slide Order", t9_text: "You can move slides to change their order.", t9_inst: "Match the pairs:", t9_h1: "What comes first?", t9_h2: "Sorting.", t9_q: "Can you change the order?", t9_qa: "Yes, by moving", t9_qb: "No, never", t9_qc: "Only with scissors", t9_qd: "Only at night",
    t9_l1: "Order", t9_r1: "Sorting", t9_l2: "Move", t9_r2: "Mouse", t9_l3: "First", t9_r3: "Start",
    t10_title: "Notes", t10_text: "Write notes that only you can see during the presentation.", t10_inst: "Match the pairs:", t10_h1: "Help for you.", t10_h2: "Under the slide.", t10_q: "Who sees the notes?", t10_qa: "Only the speaker", t10_qb: "All viewers", t10_qc: "Nobody", t10_qd: "The dog",
    t10_l1: "Note", t10_r1: "Help", t10_l2: "Speaker", t10_r2: "You", t10_l3: "Secret", t10_r3: "Invisible",
    t11_title: "Play", t11_text: "Start your presentation to see it in full screen.", t11_inst: "Match the pairs:", t11_h1: "Make it large.", t11_h2: "Press F5 key.", t11_q: "How do you see the presentation large?", t11_qa: "Presentation mode", t11_qb: "With a magnifier", t11_qc: "Rotate monitor", t11_qd: "Lights out",
    t11_l1: "Play", t11_r1: "Start", t11_l2: "Full screen", t11_r2: "Large", t11_l3: "Key", t11_r3: "F5",
    t12_title: "Presenting", t12_text: "Use the arrow keys to go to the next slide.", t12_inst: "Match the pairs:", t12_h1: "Click next.", t12_h2: "Right arrow.", t12_q: "How do you go to the next slide?", t12_qa: "Arrow key", t12_qb: "Shout loudly", t12_qc: "Wait", t12_qd: "Throw keyboard",
    t12_l1: "Next", t12_r1: "Arrow", t12_l2: "Keyboard", t12_r2: "Control", t12_l3: "Talk", t12_r3: "Speaking",
    t13_title: "Export as PDF", t13_text: "Save your presentation as a PDF so everyone can read it.", t13_inst: "Match the pairs:", t13_h1: "A fixed format.", t13_h2: "For sending.", t13_q: "What is a PDF?", t13_qa: "A document format", t13_qb: "A game", t13_qc: "A photo", t13_qd: "A video",
    t13_l1: "Export", t13_r1: "Save", t13_l2: "PDF", t13_r2: "Format", t13_l3: "Share", t13_r3: "Send",
    t14_title: "Save as PPTX", t14_text: "Save your work so you can continue editing it later.", t14_inst: "Match the pairs:", t14_h1: "PowerPoint file.", t14_h2: "Don't forget.", t14_q: "What is the PowerPoint file called?", t14_qa: "PPTX", t14_qb: "DOCX", t14_qc: "MP3", t14_qd: "JPG",
    t14_l1: "Save", t14_r1: "Keep", t14_l2: "PPTX", t14_r2: "File", t14_l3: "Work", t14_r3: "Done",
    t15_title: "Presentation Master", t15_text: "You can now create great shows on the computer!", t15_inst: "Match the pairs:", t15_h1: "Great job!", t15_h2: "Learned everything.", t15_q: "What are you now?", t15_qa: "Presentation Pro", t15_qb: "A cook", t15_qc: "A pilot", t15_qd: "A fish",
    t15_l1: "Master", t15_r1: "Pro", t15_l2: "Show", t15_r2: "Success", t15_l3: "End", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "Prezentáció",
    t1_title: "Mi az a prezentáció?", t1_text: "A prezentáció segít bemutatni az ötleteidet képekkel és szöveggel.", t1_inst: "Párosítsd össze:", t1_h1: "Ötletek bemutatása.", t1_h2: "Képek és szöveg.", t1_q: "Mire jó a prezentáció?", t1_qa: "Ötletek bemutatására", t1_qb: "Levesfőzésre", t1_qc: "Alvásra", t1_qd: "Fogmosásra",
    t1_l1: "Prezentáció", t1_r1: "Előadás", t1_l2: "Ötlet", t1_r2: "Bemutatás", t1_l3: "Közönség", t1_r3: "Nézők",
    t2_title: "Új dia", t2_text: "A prezentáció minden új oldalát diának nevezzük.", t2_inst: "Párosítsd össze:", t2_h1: "Egy új oldal.", t2_h2: "Kattints a pluszra.", t2_q: "Hogy hívják az oldalt a PowerPointban?", t2_qa: "Dia", t2_qb: "Papírlap", t2_qc: "Ablak", t2_qd: "Asztal",
    t2_l1: "Új", t2_r1: "Dia", t2_l2: "Plusz", t2_r2: "Hozzáadás", t2_l3: "Oldal", t2_r3: "Tartalom",
    t3_title: "Cím beírása", t3_text: "Írd a címet a fenti nagy szövegdobozba.", t3_inst: "Párosítsd össze:", t3_h1: "A téma neve.", t3_h2: "Legfelül.", t3_q: "Hol található általában a cím?", t3_qa: "Legfelül", t3_qb: "Az asztal alatt", t3_qc: "A pincében", t3_qd: "Legalul",
    t3_l1: "Cím", t3_r1: "Név", t3_l2: "Szövegdoboz", t3_r2: "Írás", t3_l3: "Nagy", t3_r3: "Fontos",
    t4_title: "Tartalom írása", t4_text: "Írj rövid mondatokat, hogy a nézők könnyen elolvashassák.", t4_inst: "Párosítsd össze:", t4_h1: "Ne legyen túl sok szöveg.", t4_h2: "Fontos infók.", t4_q: "Mit érdemes a diára írni?", t4_qa: "Rövid mondatokat", t4_qb: "Egy egész könyvet", t4_qc: "Titkokat", t4_qd: "Semmit",
    t4_l1: "Tartalom", t4_r1: "Szöveg", t4_l2: "Olvasás", t4_r2: "Szem", t4_l3: "Rövid", t4_r3: "Egyszerű",
    t5_title: "Képek beillesztése", t5_text: "A képek sokkal szebbé és izgalmasabbá teszik az előadásodat.", t5_inst: "Párosítsd össze:", t5_h1: "Használj fotókat.", t5_h2: "Beillesztés menü.", t5_q: "Mi teszi izgalmasabbá a diát?", t5_qa: "Képek", t5_qb: "Sötétség", t5_qc: "Üresség", t5_qd: "Por",
    t5_l1: "Kép", t5_r1: "Fotó", t5_l2: "Beillesztés", t5_r2: "Hozzáadás", t5_l3: "Szép", t5_r3: "Színes",
    t6_title: "Háttér választás", t6_text: "Válassz egy szép színt vagy mintát a diák hátterének.", t6_inst: "Párosítsd össze:", t6_h1: "A hátsó szín.", t6_h2: "Tervezés választása.", t6_q: "Mi a háttér?", t6_qa: "A hátsó szín", t6_qb: "Egy függöny", t6_qc: "Egy szőnyeg", t6_qd: "Az égbolt",
    t6_l1: "Háttér", t6_r1: "Hátul", t6_l2: "Szín", t6_r2: "Színes", t6_l3: "Tervezés", t6_r3: "Minta",
    t7_title: "Átmenetek", t7_text: "Az átmenet egy animáció, amikor a következő diára lépsz.", t7_inst: "Párosítsd össze:", t7_h1: "Diáról diára.", t7_h2: "Mozgás váltáskor.", t7_q: "Mi az az átmenet?", t7_qa: "Váltási animáció", t7_qb: "Egy híd", t7_qc: "Egy alagút", t7_qd: "Egy ugrás",
    t7_l1: "Átmenet", t7_r1: "Váltás", t7_l2: "Következő", t7_r2: "Dia", t7_l3: "Effekt", t7_r3: "Mozgás",
    t8_title: "Animációk", t8_text: "Tedd mozgóvá a képeket vagy szövegeket a dián.", t8_inst: "Párosítsd össze:", t8_h1: "A dolgok mozognak.", t8_h2: "Effektek a szöveghez.", t8_q: "Mit csinál az animáció?", t8_qa: "Mozgatja a tárgyakat", t8_qb: "Mindent töröl", t8_qc: "Zenél", t8_qd: "Kikapcsol",
    t8_l1: "Animáció", t8_r1: "Mozgás", t8_l2: "Beúszás", t8_r2: "Effekt", t8_l3: "Kattintás", t8_r3: "Start",
    t9_title: "Dia sorrend", t9_text: "A diákat elmozgathatod, hogy megváltoztasd a sorrendjüket.", t9_inst: "Párosítsd össze:", t9_h1: "Mi jön először?", t9_h2: "Rendezés.", t9_q: "Meg lehet változtatni a sorrendet?", t9_qa: "Igen, mozgatással", t9_qb: "Nem, soha", t9_qc: "Csak ollóval", t9_qd: "Csak éjjel",
    t9_l1: "Sorrend", t9_r1: "Rendezés", t9_l2: "Mozgatás", t9_r2: "Egér", t9_l3: "Első", t9_r3: "Start",
    t10_title: "Jegyzetek", t10_text: "Írj jegyzeteket, amiket csak te látsz az előadás közben.", t10_inst: "Párosítsd össze:", t10_h1: "Segítség neked.", t10_h2: "A dia alatt.", t10_q: "Ki látja a jegyzeteket?", t10_qa: "Csak az előadó", t10_qb: "Minden néző", t10_qc: "Senki", t10_qd: "A kutya",
    t10_l1: "Jegyzet", t10_r1: "Segítség", t10_l2: "Előadó", t10_r2: "Te", t10_l3: "Titkos", t10_r3: "Láthatatlan",
    t11_title: "Lejátszás", t11_text: "Indítsd el a prezentációt, hogy nagyban lásd.", t11_inst: "Párosítsd össze:", t11_h1: "Legyen nagy.", t11_h2: "F5 billentyű.", t11_q: "Hogyan látod nagyban a prezentációt?", t11_qa: "Vetítési mód", t11_qb: "Nagyítóval", t11_qc: "Monitor forgatással", t11_qd: "Lámpaoltással",
    t11_l1: "Lejátszás", t11_r1: "Start", t11_l2: "Teljes képernyő", t11_r2: "Nagy", t11_l3: "Gomb", t11_r3: "F5",
    t12_title: "Vetítés", t12_text: "Használd a nyíl billentyűket a következő diára lépéshez.", t12_inst: "Párosítsd össze:", t12_h1: "Kattints tovább.", t12_h2: "Jobbra nyíl.", t12_q: "Hogyan lépsz a következő diára?", t12_qa: "Nyíl billentyű", t12_qb: "Hangos kiabálással", t12_qc: "Várakozással", t12_qd: "Billentyűzet dobással",
    t12_l1: "Tovább", t12_r1: "Nyíl", t12_l2: "Billentyűzet", t12_r2: "Vezérlés", t12_l3: "Előadás", t12_r3: "Beszéd",
    t13_title: "Exportálás PDF-be", t13_text: "Mentsd el PDF-ként, hogy bárki elolvashassa.", t13_inst: "Párosítsd össze:", t13_h1: "Fix formátum.", t13_h2: "Küldéshez.", t13_q: "Mi az a PDF?", t13_qa: "Egy dokumentum formátum", t13_qb: "Egy játék", t13_qc: "Egy fotó", t13_qd: "Egy videó",
    t13_l1: "Export", t13_r1: "Mentés", t13_l2: "PDF", t13_r2: "Formátum", t13_l3: "Megosztás", t13_r3: "Küldés",
    t14_title: "Mentés PPTX-ben", t14_text: "Mentsd el a munkádat, hogy később is tudd folytatni.", t14_inst: "Párosítsd össze:", t14_h1: "PowerPoint fájl.", t14_h2: "Ne felejtsd el.", t14_q: "Hogy hívják a PowerPoint fájlt?", t14_qa: "PPTX", t14_qb: "DOCX", t14_qc: "MP3", t14_qd: "JPG",
    t14_l1: "Mentés", t14_r1: "Megtartás", t14_l2: "PPTX", t14_r2: "Fájl", t14_l3: "Munka", t14_r3: "Kész",
    t15_title: "Prezentáció Mester", t15_text: "Most már szuper bemutatókat tudsz készíeni a gépen!", t15_inst: "Párosítsd össze:", t15_h1: "Szép munka!", t15_h2: "Mindent megtanultál.", t15_q: "Mi vagy te most?", t15_qa: "Prezentáció profi", t15_qb: "Egy szakács", t15_qc: "Egy pilóta", t15_qd: "Egy hal",
    t15_l1: "Mester", t15_r1: "Profi", t15_l2: "Show", t15_r2: "Siker", t15_l3: "Vége", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Prezentare",
    t1_title: "Ce este o prezentare?", t1_text: "O prezentare te ajută să-ți arăți ideile cu imagini și text.", t1_inst: "Potrivește perechile:", t1_h1: "Arătarea ideilor.", t1_h2: "Imagini și text.", t1_q: "La ce este bună o prezentare?", t1_qa: "Pentru a arăta idei", t1_qb: "Pentru a găti supă", t1_qc: "Pentru a dormi", t1_qd: "Pentru spălat pe dinți",
    t1_l1: "Prezentare", t1_r1: "Discurs", t1_l2: "Idee", t1_r2: "Arată", t1_l3: "Public", t1_r3: "Spectatori",
    t2_title: "Diapozitiv nou", t2_text: "Fiecare pagină nouă din prezentarea ta se numește diapozitiv (slide).", t2_inst: "Potrivește perechile:", t2_h1: "O pagină nouă.", t2_h2: "Clic pe plus.", t2_q: "Cum se numește o pagină în PowerPoint?", t2_qa: "Diapozitiv", t2_qb: "Foaie de hârtie", t2_qc: "Fereastră", t2_qd: "Masă",
    t2_l1: "Nou", t2_r1: "Diapozitiv", t2_l2: "Plus", t2_r2: "Adaugă", t2_l3: "Pagină", t2_r3: "Conținut",
    t3_title: "Introdu titlul", t3_text: "Scrie titlul în caseta mare de sus.", t3_inst: "Potrivește perechile:", t3_h1: "Numele temei.", t3_h2: "Chiar sus.", t3_q: "Unde se află de obicei titlul?", t3_qa: "Sus de tot", t3_qb: "Sub masă", t3_qc: "În pivniță", t3_qd: "Jos de tot",
    t3_l1: "Titlu", t3_r1: "Nume", t3_l2: "Casetă text", t3_r2: "Scrie", t3_l3: "Mare", t3_r3: "Important",
    t4_title: "Scrie conținutul", t4_text: "Scrie propoziții scurte pentru ca publicul să poată citi ușor.", t4_inst: "Potrivește perechile:", t4_h1: "Nu prea mult text.", t4_h2: "Info importante.", t4_q: "Ce ar trebui să scrii pe diapozitiv?", t4_qa: "Propoziții scurte", t4_qb: "O carte întreagă", t4_qc: "Secrete", t4_qd: "Nimic",
    t4_l1: "Conținut", t4_r1: "Text", t4_l2: "Citește", t4_r2: "Ochi", t4_l3: "Scurt", t4_r3: "Simplu",
    t5_title: "Inserează imagini", t5_text: "Imaginile fac prezentarea mult mai frumoasă și interesantă.", t5_inst: "Potrivește perechile:", t5_h1: "Folosește fotografii.", t5_h2: "Meniul Inserare.", t5_q: "Ce face un diapozitiv mai interesant?", t5_qa: "Imaginile", t5_qb: "Întunericul", t5_qc: "Goliul", t5_qd: "Praful",
    t5_l1: "Imagine", t5_r1: "Foto", t5_l2: "Inserează", t5_r2: "Adaugă", t5_l3: "Frumos", t5_r3: "Colorat",
    t6_title: "Alege fundalul", t6_text: "Alege o culoare frumoasă sau un model pentru fundalul diapozitivelor.", t6_inst: "Potrivește perechile:", t6_h1: "Culoarea din spate.", t6_h2: "Selectează design.", t6_q: "Ce este fundalul?", t6_qa: "Culoarea din spate", t6_qb: "O perdea", t6_qc: "Un covor", t6_qd: "Cerul",
    t6_l1: "Fundal", t6_r1: "Spate", t6_l2: "Culoare", t6_r2: "Colorat", t6_l3: "Design", t6_r3: "Model",
    t7_title: "Tranziții", t7_text: "O tranziție este o animație când treci la următorul diapozitiv.", t7_inst: "Potrivește perechile:", t7_h1: "De la slide la slide.", t7_h2: "Mișcare la schimbare.", t7_q: "Ce este o tranziție?", t7_qa: "Animație de schimbare", t7_qb: "Un pod", t7_qc: "Un tunel", t7_qd: "O săritură",
    t7_l1: "Tranziție", t7_r1: "Schimbare", t7_l2: "Următorul", t7_r2: "Slide", t7_l3: "Efect", t7_r3: "Mișcare",
    t8_title: "Animații", t8_text: "Fă imaginile sau textele să zboare sau să sară pe diapozitiv.", t8_inst: "Potrivește perechile:", t8_h1: "Lucrurile se mișcă.", t8_h2: "Efecte pentru text.", t8_q: "Ce face o animație?", t8_qa: "Mișcă obiectele", t8_qb: "Șterge tot", t8_qc: "Face muzică", t8_qd: "Oprește",
    t8_l1: "Animație", t8_r1: "Mișcare", t8_l2: "Zbor", t8_r2: "Efect", t8_l3: "Clic", t8_r3: "Start",
    t9_title: "Ordinea diapozitivelor", t9_text: "Poți muta diapozitivele pentru a le schimba ordinea.", t9_inst: "Potrivește perechile:", t9_h1: "Ce vine mai întâi?", t9_h2: "Sortare.", t9_q: "Poți schimba ordinea?", t9_qa: "Da, prin mutare", t9_qb: "Nu, niciodată", t9_qc: "Doar cu foarfeca", t9_qd: "Doar noaptea",
    t9_l1: "Ordine", t9_r1: "Sortare", t9_l2: "Mută", t9_r2: "Mouse", t9_l3: "Primul", t9_r3: "Start",
    t10_title: "Note", t10_text: "Scrie note pe care doar tu le poți vedea în timpul prezentării.", t10_inst: "Potrivește perechile:", t10_h1: "Ajutor pentru tine.", t10_h2: "Sub diapozitiv.", t10_q: "Cine vede notele?", t10_qa: "Doar vorbitorul", t10_qb: "Toți spectatorii", t10_qc: "Nimeni", t10_qd: "Câinele",
    t10_l1: "Notă", t10_r1: "Ajutor", t10_l2: "Vorbitor", t10_r2: "Tu", t10_l3: "Secret", t10_r3: "Invizibil",
    t11_title: "Redare", t11_text: "Pornește prezentarea pentru a o vedea pe tot ecranul.", t11_inst: "Potrivește perechile:", t11_h1: "Fă-o mare.", t11_h2: "Apasă tasta F5.", t11_q: "Cum vezi prezentarea mare?", t11_qa: "Mod prezentare", t11_qb: "Cu lupa", t11_qc: "Rotește monitorul", t11_qd: "Stinge lumina",
    t11_l1: "Redare", t11_r1: "Start", t11_l2: "Ecran complet", t11_r2: "Mare", t11_l3: "Tastă", t11_r3: "F5",
    t12_title: "Prezentarea", t12_text: "Folosește tastele săgeți pentru a trece la următorul diapozitiv.", t12_inst: "Potrivește perechile:", t12_h1: "Clic înainte.", t12_h2: "Săgeată dreapta.", t12_q: "Cum treci la următorul diapozitiv?", t12_qa: "Tasta săgeată", t12_qb: "Strigând tare", t12_qc: "Așteptând", t12_qd: "Aruncând tastatura",
    t12_l1: "Înainte", t12_r1: "Săgeată", t12_l2: "Tastatură", t12_r2: "Control", t12_l3: "Discurs", t12_r3: "Vorbire",
    t13_title: "Export ca PDF", t13_text: "Salvează prezentarea ca PDF pentru ca oricine să o poată citi.", t13_inst: "Potrivește perechile:", t13_h1: "Un format fix.", t13_h2: "Pentru trimitere.", t13_q: "Ce este un PDF?", t13_qa: "Un format de document", t13_qb: "Un joc", t13_qc: "O fotografie", t13_qd: "Un video",
    t13_l1: "Export", t13_r1: "Salvare", t13_l2: "PDF", t13_r2: "Format", t13_l3: "Partajare", t13_r3: "Trimite",
    t14_title: "Salvare ca PPTX", t14_text: "Salvează-ți munca pentru a o putea edita mai târziu.", t14_inst: "Potrivește perechile:", t14_h1: "Fișier PowerPoint.", t14_h2: "Nu uita.", t14_q: "Cum se numește fișierul PowerPoint?", t14_qa: "PPTX", t14_qb: "DOCX", t14_qc: "MP3", t14_qd: "JPG",
    t14_l1: "Salvare", t14_r1: "Păstrare", t14_l2: "PPTX", t14_r2: "Fișier", t14_l3: "Muncă", t14_r3: "Gata",
    t15_title: "Maestru în prezentări", t15_text: "Acum poți crea spectacole grozave la calculator!", t15_inst: "Potrivește perechile:", t15_h1: "Bravo!", t15_h2: "Ai învățat totul.", t15_q: "Ce ești acum?", t15_qa: "Expert în prezentări", t15_qb: "Un bucătar", t15_qc: "Un pilot", t15_qd: "Un pește",
    t15_l1: "Maestru", t15_r1: "Expert", t15_l2: "Spectacol", t15_r2: "Succes", t15_l3: "Sfârșit", t15_r3: "Victorie"
  }
};

export const INFO_K2_I7_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["💡", "➕", "🏷️", "📝", "🖼️", "🎨", "🎞️", "✨", "🔢", "🗒️", "▶️", "🗣️", "📄", "💾", "🏆"];
  const colors = ["#FFEB3B", "#4CAF50", "#2196F3", "#9E9E9E", "#E91E63", "#9C27B0", "#FF9800", "#00BCD4", "#795548", "#607D8B", "#F44336", "#3F51B5", "#FF5722", "#009688", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});
