// lib/explorerPools/informatikaK7_i4.ts
import type { PoolTopicDef } from "./types";

export const INFO_K7_I4_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Informatik Entdecker K7-4",
    t1_title: "Variablen in Python", t1_text: "Eine Variable speichert einen Wert. In Python: alter = 13 oder name = 'Anna'.", t1_inst: "Ordne die Paare zu:", t1_h1: "Welcher Datentyp ist was?", t1_h2: "Zahl, Text oder Wahrheitswert?", t1_q: "Was ist eine Variable?", t1_qa: "Ein benannter Speicherplatz für Werte", t1_qb: "Eine Schleife", t1_qc: "Eine Funktion", t1_qd: "Ein Kommentar",
    t1_l1: "alter = 13", t1_r1: "Integer", t1_l2: "name = 'Anna'", t1_r2: "String", t1_l3: "wahr = True", t1_r3: "Boolean", t1_l4: "preis = 1.5", t1_r4: "Float",
    t2_title: "print() Funktion", t2_text: "Mit print() geben wir Text oder Werte in Python auf dem Bildschirm aus.", t2_inst: "Fülle die Lücke aus:", t2_h1: "print() = Ausgabe.", t2_h2: "print('Hallo') zeigt Hallo.", t2_q: "Was macht print() in Python?", t2_qa: "Gibt Text oder Werte aus", t2_qb: "Liest Benutzereingaben", t2_qc: "Löscht Variablen", t2_qd: "Beendet das Programm",
    t2_sent: "Die Funktion ___ gibt Text auf dem Bildschirm aus.", t2_c1: "print()", t2_c2: "input()", t2_c3: "show()", t2_c4: "display()",
    t3_title: "input() Funktion", t3_text: "input() liest eine Eingabe des Benutzers ein und gibt sie als String zurück.", t3_inst: "Sortiere in die Eimer:", t3_h1: "Eingabe oder Ausgabe?", t3_h2: "input() liest, print() schreibt!", t3_q: "Was macht input() in Python?", t3_qa: "Liest eine Benutzereingabe", t3_qb: "Gibt Text aus", t3_qc: "Löscht eine Variable", t3_qd: "Beendet das Programm",
    t3_bl1: "Eingabe", t3_bl2: "Ausgabe", t3_i1: "input()", t3_i2: "print()", t3_i3: "Benutzer tippt", t3_i4: "Bildschirm zeigt",
    t4_title: "Strings (Zeichenketten)", t4_text: "Strings sind Texte in Python, in Anführungszeichen: 'Hallo' oder \"Welt\".", t4_inst: "Bringe die Wörter in Ordnung:", t4_h1: "Strings in Anführungszeichen.", t4_h2: "Einzel oder doppelt!", t4_q: "Wie schreibt man einen String in Python?", t4_qa: "In Anführungszeichen: 'Hallo'", t4_qb: "In spitzen Klammern: <Hallo>", t4_qc: "In eckigen Klammern: [Hallo]", t4_qd: "In runden Klammern: (Hallo)",
    t4_w1: "Strings", t4_w2: "stehen", t4_w3: "in", t4_w4: "Anführungszeichen",
    t5_title: "Integer (Ganzzahlen)", t5_text: "Integer sind ganze Zahlen in Python ohne Anführungszeichen: alter = 13.", t5_inst: "Markiere das richtige Wort:", t5_h1: "Integer = ganze Zahl, kein Text.", t5_h2: "13 ist ein Integer!", t5_q: "Was ist ein Integer in Python?", t5_qa: "Eine ganze Zahl", t5_qb: "Ein Text in Anführungszeichen", t5_qc: "Ein Wahrheitswert", t5_qd: "Eine Kommazahl",
    t5_tk1: "Ein Integer", t5_tk2: "ist", t5_tk3: "eine", t5_tk4: "Ganzzahl.",
    t6_title: "Float (Kommazahlen)", t6_text: "Floats sind Kommazahlen. In Python verwendet man einen Punkt statt eines Kommas: pi = 3.14.", t6_inst: "Ordne die Paare zu:", t6_h1: "Punkt statt Komma!", t6_h2: "Float = Fließkommazahl.", t6_q: "Wie schreibt man eine Kommazahl in Python?", t6_qa: "Mit einem Punkt (3.14)", t6_qb: "Mit einem Komma (3,14)", t6_qc: "In Anführungszeichen ('3.14')", t6_qd: "Mit einem Doppelpunkt (3:14)",
    t6_l1: "3.14", t6_r1: "Float", t6_l2: "42", t6_r2: "Integer", t6_l3: "'3.14'", t6_r3: "String", t6_l4: "True", t6_r4: "Boolean",
    t7_title: "Boolean (Wahrheitswerte)", t7_text: "Booleans haben nur zwei Werte: True (Wahr) oder False (Falsch). Sie sind wichtig für Bedingungen.", t7_inst: "Fülle die Lücke aus:", t7_h1: "True oder False.", t7_h2: "Großgeschrieben!", t7_q: "Welche Werte kann ein Boolean haben?", t7_qa: "True oder False", t7_qb: "1 bis 10", t7_qc: "Ja, Nein, Vielleicht", t7_qd: "Jeden Text",
    t7_sent: "Ein Boolean ist entweder True oder ___.", t7_c1: "False", t7_c2: "Falsch", t7_c3: "Null", t7_c4: "Nichts",
    t8_title: "Type Casting", t8_text: "Mit int(), float() oder str() kann man Datentypen umwandeln, z.B. int('5') wird zur Zahl 5.", t8_inst: "Bringe die Wörter in Ordnung:", t8_h1: "Umwandlung von Typen.", t8_h2: "Text zu Zahl.", t8_q: "Was macht int('5')?", t8_qa: "Wandelt den Text '5' in die Zahl 5 um", t8_qb: "Gibt '5' auf dem Bildschirm aus", t8_qc: "Löscht die Zahl 5", t8_qd: "Macht aus 5 eine Kommazahl",
    t8_w1: "int()", t8_w2: "wandelt", t8_w3: "Text", t8_w4: "in Zahlen",
    t9_title: "Arithmetische Operatoren", t9_text: "Python nutzt +, -, * (Mal) und / (Geteilt) zum Rechnen.", t9_inst: "Sortiere in die Eimer:", t9_h1: "Rechnen oder Text?", t9_h2: "* ist Mal, / ist Geteilt.", t9_q: "Welches Zeichen nutzt Python für die Multiplikation?", t9_qa: "* (Sternchen)", t9_qb: "x (Buchstabe)", t9_qc: ". (Punkt)", t9_qd: ": (Doppelpunkt)",
    t9_bl1: "Rechnen", t9_bl2: "Vergleich", t9_i1: "+ und -", t9_i2: "== und !=", t9_i3: "* und /", t9_i4: "< und >",
    t10_title: "Vergleichsoperatoren", t10_text: "Mit == (gleich), != (ungleich), < und > vergleicht man Werte. Das Ergebnis ist ein Boolean.", t10_inst: "Markiere das richtige Wort:", t10_h1: "== prüft auf Gleichheit.", t10_h2: "= ist Zuweisung.", t10_q: "Welcher Operator prüft, ob zwei Werte gleich sind?", t10_qa: "==", t10_qb: "=", t10_qc: "!=", t10_qd: "<>",
    t10_tk1: "Der Operator", t10_tk2: "==", t10_tk3: "prüft", t10_tk4: "Gleichheit.",
    t11_title: "Logische Operatoren", t11_text: "Mit and, or und not kann man Bedingungen verknüpfen. 'and' bedeutet: beides muss wahr sein.", t11_inst: "Fülle die Lücke aus:", t11_h1: "and = und.", t11_h2: "or = oder.", t11_q: "Wann ist (A and B) wahr?", t11_qa: "Wenn A und B wahr sind", t11_qb: "Wenn nur A wahr ist", t11_qc: "Wenn nur B wahr ist", t11_qd: "Wenn keines wahr ist",
    t11_sent: "Mit ___ müssen beide Bedingungen wahr sein.", t11_c1: "and", t11_c2: "or", t11_c3: "not", t11_c4: "if",
    t12_title: "Kommentare", t12_text: "Kommentare beginnen mit # und werden von Python ignoriert. Sie erklären den Code für Menschen.", t12_inst: "Ordne die Paare zu:", t12_h1: "# für Kommentare.", t12_h2: "Wird nicht ausgeführt.", t12_q: "Wie startet man einen Kommentar in Python?", t12_qa: "Mit #", t12_qb: "Mit //", t12_qc: "Mit <!--", t12_qd: "Mit /*",
    t12_l1: "#", t12_r1: "Kommentar", t12_l2: "print()", t12_r2: "Ausgabe", t12_l3: "input()", t12_r3: "Eingabe", t12_l4: "=", t12_r4: "Zuweisung",
    t13_title: "String Concatenation", t13_text: "Man kann Strings mit dem + Operator verbinden: 'Hallo ' + 'Welt' wird zu 'Hallo Welt'.", t13_inst: "Bringe die Wörter in Ordnung:", t13_h1: "Plus verbindet Text.", t13_h2: "Hallo + Welt.", t13_q: "Was ist das Ergebnis von 'A' + 'B'?", t13_qa: "'AB'", t13_qb: "'A B'", t13_qc: "Ein Fehler", t13_qd: "Nichts",
    t13_w1: "Das Plus", t13_w2: "verbindet", t13_w3: "zwei", t13_w4: "Strings",
    t14_title: "f-Strings", t14_text: "f-Strings formatieren Text einfach: f'Ich bin {alter} Jahre alt'. Variablen stehen in {}.", t14_inst: "Sortiere in die Eimer:", t14_h1: "f vor dem String.", t14_h2: "Variablen in {}.", t14_q: "Wie fügt man eine Variable in einen f-String ein?", t14_qa: "In geschweiften Klammern {}", t14_qb: "Mit einem Plus +", t14_qc: "In eckigen Klammern []", t14_qd: "Mit einem Komma ,",
    t14_bl1: "f-String", t14_bl2: "Normaler String", t14_i1: "f'Hallo {name}'", t14_i2: "'Hallo name'", t14_i3: "f'Alter: {x}'", t14_i4: "'Alter: x'",
    t15_title: "len() Funktion", t15_text: "Die Funktion len() gibt die Länge eines Strings oder einer Liste zurück: len('Python') ist 6.", t15_inst: "Markiere das richtige Wort:", t15_h1: "len = length (Länge).", t15_h2: "Zählt die Zeichen.", t15_q: "Was gibt len('Hallo') zurück?", t15_qa: "5", t15_qb: "4", t15_qc: "6", t15_qd: "Hallo",
    t15_tk1: "len()", t15_tk2: "gibt", t15_tk3: "die Länge", t15_tk4: "zurück."
  },
  en: {
    explorer_title: "Informatics Explorer K7-4",
    t1_title: "Variables in Python", t1_text: "A variable stores a value. In Python: age = 13 or name = 'Anna'.", t1_inst: "Match the pairs:", t1_h1: "Which data type is what?", t1_h2: "Number, text or boolean?", t1_q: "What is a variable?", t1_qa: "A named storage space for values", t1_qb: "A loop", t1_qc: "A function", t1_qd: "A comment",
    t1_l1: "age = 13", t1_r1: "Integer", t1_l2: "name = 'Anna'", t1_r2: "String", t1_l3: "true = True", t1_r3: "Boolean", t1_l4: "price = 1.5", t1_r4: "Float",
    t2_title: "print() Function", t2_text: "With print() we output text or values to the screen in Python.", t2_inst: "Fill in the blank:", t2_h1: "print() = output.", t2_h2: "print('Hello') shows Hello.", t2_q: "What does print() do in Python?", t2_qa: "Outputs text or values", t2_qb: "Reads user input", t2_qc: "Deletes variables", t2_qd: "Ends the program",
    t2_sent: "The function ___ outputs text on the screen.", t2_c1: "print()", t2_c2: "input()", t2_c3: "show()", t2_c4: "display()",
    t3_title: "input() Function", t3_text: "input() reads a user input and returns it as a string.", t3_inst: "Sort into buckets:", t3_h1: "Input or output?", t3_h2: "input() reads, print() writes!", t3_q: "What does input() do in Python?", t3_qa: "Reads a user input", t3_qb: "Outputs text", t3_qc: "Deletes a variable", t3_qd: "Ends the program",
    t3_bl1: "Input", t3_bl2: "Output", t3_i1: "input()", t3_i2: "print()", t3_i3: "User types", t3_i4: "Screen shows",
    t4_title: "Strings", t4_text: "Strings are texts in Python written in quotation marks: 'Hello' or \"World\".", t4_inst: "Put the words in order:", t4_h1: "Strings in quotation marks.", t4_h2: "Single or double quotes!", t4_q: "How do you write a string in Python?", t4_qa: "In quotation marks: 'Hello'", t4_qb: "In angle brackets: <Hello>", t4_qc: "In square brackets: [Hello]", t4_qd: "In round brackets: (Hello)",
    t4_w1: "Strings", t4_w2: "are", t4_w3: "in", t4_w4: "quotes",
    t5_title: "Integer (Whole Numbers)", t5_text: "Integers are whole numbers in Python without quotation marks: age = 13.", t5_inst: "Highlight the correct word:", t5_h1: "Integer = whole number, not text.", t5_h2: "13 is an integer!", t5_q: "What is an integer in Python?", t5_qa: "A whole number", t5_qb: "A text in quotation marks", t5_qc: "A boolean value", t5_qd: "A decimal number",
    t5_tk1: "An integer", t5_tk2: "is", t5_tk3: "a", t5_tk4: "whole number.",
    t6_title: "Float (Decimals)", t6_text: "Floats are decimal numbers. In Python, use a dot instead of a comma: pi = 3.14.", t6_inst: "Match the pairs:", t6_h1: "Dot instead of comma!", t6_h2: "Float = floating point number.", t6_q: "How do you write a decimal number in Python?", t6_qa: "With a dot (3.14)", t6_qb: "With a comma (3,14)", t6_qc: "In quotes ('3.14')", t6_qd: "With a colon (3:14)",
    t6_l1: "3.14", t6_r1: "Float", t6_l2: "42", t6_r2: "Integer", t6_l3: "'3.14'", t6_r3: "String", t6_l4: "True", t6_r4: "Boolean",
    t7_title: "Boolean (Truth Values)", t7_text: "Booleans have only two values: True or False. They are important for conditions.", t7_inst: "Fill in the blank:", t7_h1: "True or False.", t7_h2: "Capitalized!", t7_q: "What values can a Boolean have?", t7_qa: "True or False", t7_qb: "1 to 10", t7_qc: "Yes, No, Maybe", t7_qd: "Any text",
    t7_sent: "A Boolean is either True or ___.", t7_c1: "False", t7_c2: "Wrong", t7_c3: "Zero", t7_c4: "Nothing",
    t8_title: "Type Casting", t8_text: "With int(), float() or str() you can convert data types, e.g. int('5') becomes the number 5.", t8_inst: "Put the words in order:", t8_h1: "Converting types.", t8_h2: "Text to number.", t8_q: "What does int('5') do?", t8_qa: "Converts the text '5' to the number 5", t8_qb: "Prints '5' on the screen", t8_qc: "Deletes the number 5", t8_qd: "Makes 5 a decimal number",
    t8_w1: "int()", t8_w2: "converts", t8_w3: "text", t8_w4: "to numbers",
    t9_title: "Arithmetic Operators", t9_text: "Python uses +, -, * (multiply) and / (divide) for math.", t9_inst: "Sort into buckets:", t9_h1: "Math or text?", t9_h2: "* is multiply, / is divide.", t9_q: "Which symbol does Python use for multiplication?", t9_qa: "* (asterisk)", t9_qb: "x (letter)", t9_qc: ". (dot)", t9_qd: ": (colon)",
    t9_bl1: "Math", t9_bl2: "Comparison", t9_i1: "+ and -", t9_i2: "== and !=", t9_i3: "* and /", t9_i4: "< and >",
    t10_title: "Comparison Operators", t10_text: "With == (equal), != (not equal), < and > you compare values. The result is a Boolean.", t10_inst: "Highlight the correct word:", t10_h1: "== checks for equality.", t10_h2: "= is assignment.", t10_q: "Which operator checks if two values are equal?", t10_qa: "==", t10_qb: "=", t10_qc: "!=", t10_qd: "<>",
    t10_tk1: "The operator", t10_tk2: "==", t10_tk3: "checks", t10_tk4: "equality.",
    t11_title: "Logical Operators", t11_text: "With and, or and not you can combine conditions. 'and' means: both must be true.", t11_inst: "Fill in the blank:", t11_h1: "and = both.", t11_h2: "or = one of them.", t11_q: "When is (A and B) true?", t11_qa: "When A and B are true", t11_qb: "When only A is true", t11_qc: "When only B is true", t11_qd: "When neither is true",
    t11_sent: "With ___ both conditions must be true.", t11_c1: "and", t11_c2: "or", t11_c3: "not", t11_c4: "if",
    t12_title: "Comments", t12_text: "Comments start with # and are ignored by Python. They explain the code for humans.", t12_inst: "Match the pairs:", t12_h1: "# for comments.", t12_h2: "Not executed.", t12_q: "How do you start a comment in Python?", t12_qa: "With #", t12_qb: "With //", t12_qc: "With <!--", t12_qd: "With /*",
    t12_l1: "#", t12_r1: "Comment", t12_l2: "print()", t12_r2: "Output", t12_l3: "input()", t12_r3: "Input", t12_l4: "=", t12_r4: "Assignment",
    t13_title: "String Concatenation", t13_text: "You can join strings with the + operator: 'Hello ' + 'World' becomes 'Hello World'.", t13_inst: "Put the words in order:", t13_h1: "Plus joins text.", t13_h2: "Hello + World.", t13_q: "What is the result of 'A' + 'B'?", t13_qa: "'AB'", t13_qb: "'A B'", t13_qc: "An error", t13_qd: "Nothing",
    t13_w1: "The plus", t13_w2: "joins", t13_w3: "two", t13_w4: "strings",
    t14_title: "f-Strings", t14_text: "f-Strings format text easily: f'I am {age} years old'. Variables go in {}.", t14_inst: "Sort into buckets:", t14_h1: "f before the string.", t14_h2: "Variables in {}.", t14_q: "How do you insert a variable into an f-String?", t14_qa: "In curly braces {}", t14_qb: "With a plus +", t14_qc: "In square brackets []", t14_qd: "With a comma ,",
    t14_bl1: "f-String", t14_bl2: "Normal String", t14_i1: "f'Hello {name}'", t14_i2: "'Hello name'", t14_i3: "f'Age: {x}'", t14_i4: "'Age: x'",
    t15_title: "len() Function", t15_text: "The len() function returns the length of a string or list: len('Python') is 6.", t15_inst: "Highlight the correct word:", t15_h1: "len = length.", t15_h2: "Counts the characters.", t15_q: "What does len('Hello') return?", t15_qa: "5", t15_qb: "4", t15_qc: "6", t15_qd: "Hello",
    t15_tk1: "len()", t15_tk2: "returns", t15_tk3: "the", t15_tk4: "length."
  },
  hu: {
    explorer_title: "Informatika Felfedező K7-4",
    t1_title: "Változók Pythonban", t1_text: "A változó értékeket tárol. Pythonban: kor = 13 vagy nev = 'Anna'.", t1_inst: "Párosítsd össze:", t1_h1: "Melyik adattípus mi?", t1_h2: "Szám, szöveg vagy logikai?", t1_q: "Mi a változó?", t1_qa: "Értékek elnevezett tárolóhelye", t1_qb: "Egy ciklus", t1_qc: "Egy függvény", t1_qd: "Egy megjegyzés",
    t1_l1: "kor = 13", t1_r1: "Integer", t1_l2: "nev = 'Anna'", t1_r2: "String", t1_l3: "igaz = True", t1_r3: "Boolean", t1_l4: "ar = 1.5", t1_r4: "Float",
    t2_title: "print() függvény", t2_text: "A print() függvénnyel szöveget vagy értéket írunk ki a képernyőre Pythonban.", t2_inst: "Töltsd ki a hiányt:", t2_h1: "print() = kimenet.", t2_h2: "print('Helló') megjeleníti Helló.", t2_q: "Mit csinál a print() Pythonban?", t2_qa: "Szöveget vagy értéket ír ki", t2_qb: "Felhasználói bevitelt olvas", t2_qc: "Változókat töröl", t2_qd: "Befejezi a programot",
    t2_sent: "A ___ függvény szöveget ír ki a képernyőre.", t2_c1: "print()", t2_c2: "input()", t2_c3: "show()", t2_c4: "display()",
    t3_title: "input() függvény", t3_text: "Az input() beolvassa a felhasználó bevitelét és stringként adja vissza.", t3_inst: "Válogasd szét:", t3_h1: "Bevitel vagy kimenet?", t3_h2: "input() olvas, print() ír!", t3_q: "Mit csinál az input() Pythonban?", t3_qa: "Beolvassa a felhasználói bevitelt", t3_qb: "Szöveget ír ki", t3_qc: "Változót töröl", t3_qd: "Befejezi a programot",
    t3_bl1: "Bemenet", t3_bl2: "Kimenet", t3_i1: "input()", t3_i2: "print()", t3_i3: "Felhasználó gépel", t3_i4: "Képernyő mutatja",
    t4_title: "Stringek (szövegek)", t4_text: "A stringek szövegek Pythonban, idézőjel között: 'Helló' vagy \"Világ\".", t4_inst: "Tedd sorrendbe a szavakat:", t4_h1: "Stringek idézőjelben.", t4_h2: "Egyszeres vagy dupla!", t4_q: "Hogyan írunk stringet Pythonban?", t4_qa: "Idézőjelben: 'Helló'", t4_qb: "Csúcsos zárójelben: <Helló>", t4_qc: "Szögletes zárójelben: [Helló]", t4_qd: "Kerek zárójelben: (Helló)",
    t4_w1: "A stringek", t4_w2: "idézőjelben", t4_w3: "vannak", t4_w4: "írva",
    t5_title: "Integer (egész számok)", t5_text: "Az integer egész számok Pythonban, idézőjel nélkül: kor = 13.", t5_inst: "Jelöld meg a helyes szót:", t5_h1: "Integer = egész szám, nem szöveg.", t5_h2: "A 13 egy integer!", t5_q: "Mi az integer Pythonban?", t5_qa: "Egy egész szám", t5_qb: "Idézőjelben lévő szöveg", t5_qc: "Logikai érték", t5_qd: "Tizedes szám",
    t5_tk1: "Az integer", t5_tk2: "egy", t5_tk3: "egész", t5_tk4: "szám.",
    t6_title: "Float (tizedestörtek)", t6_text: "A float tizedestört. Pythonban pontot használunk vessző helyett: pi = 3.14.", t6_inst: "Párosítsd össze:", t6_h1: "Pont a vessző helyett!", t6_h2: "Float = lebegőpontos szám.", t6_q: "Hogyan írunk tizedestörtet Pythonban?", t6_qa: "Ponttal (3.14)", t6_qb: "Vesszővel (3,14)", t6_qc: "Idézőjelben ('3.14')", t6_qd: "Kettősponttal (3:14)",
    t6_l1: "3.14", t6_r1: "Float", t6_l2: "42", t6_r2: "Integer", t6_l3: "'3.14'", t6_r3: "String", t6_l4: "True", t6_r4: "Boolean",
    t7_title: "Boolean (logikai értékek)", t7_text: "A boolean csak két értéket vehet fel: True (Igaz) vagy False (Hamis).", t7_inst: "Töltsd ki a hiányt:", t7_h1: "True vagy False.", t7_h2: "Nagybetűvel kezdődik!", t7_q: "Milyen értékei lehetnek egy boolean-nak?", t7_qa: "True vagy False", t7_qb: "1-től 10-ig", t7_qc: "Igen, Nem, Talán", t7_qd: "Bármilyen szöveg",
    t7_sent: "A boolean értéke True vagy ___.", t7_c1: "False", t7_c2: "Hamis", t7_c3: "Nulla", t7_c4: "Semmi",
    t8_title: "Típuskonverzió", t8_text: "Az int(), float() vagy str() függvényekkel adattípusokat alakíthatunk át, pl. int('5') az 5-ös szám lesz.", t8_inst: "Tedd sorrendbe a szavakat:", t8_h1: "Típusok átalakítása.", t8_h2: "Szövegből szám.", t8_q: "Mit csinál az int('5')?", t8_qa: "Az '5' szöveget 5-ös számmá alakítja", t8_qb: "Kiírja az '5'-öt a képernyőre", t8_qc: "Törli az 5-ös számot", t8_qd: "Tizedestörtté alakítja az 5-öt",
    t8_w1: "Az int()", t8_w2: "szöveget", t8_w3: "számmá", t8_w4: "alakít",
    t9_title: "Aritmetikai operátorok", t9_text: "A Python a +, -, * (szorzás) és / (osztás) jeleket használja számoláshoz.", t9_inst: "Válogasd szét:", t9_h1: "Számolás vagy szöveg?", t9_h2: "A * a szorzás, a / az osztás.", t9_q: "Melyik jelet használja a Python szorzásra?", t9_qa: "* (csillag)", t9_qb: "x (betű)", t9_qc: ". (pont)", t9_qd: ": (kettőspont)",
    t9_bl1: "Számolás", t9_bl2: "Összehasonlítás", t9_i1: "+ és -", t9_i2: "== és !=", t9_i3: "* és /", t9_i4: "< és >",
    t10_title: "Összehasonlító operátorok", t10_text: "A == (egyenlő), != (nem egyenlő), < és > jelekkel értékeket hasonlítunk össze. Az eredmény egy boolean.", t10_inst: "Jelöld meg a helyes szót:", t10_h1: "A == az egyenlőséget vizsgálja.", t10_h2: "Az = értékadás.", t10_q: "Melyik operátor vizsgálja, hogy két érték egyenlő-e?", t10_qa: "==", t10_qb: "=", t10_qc: "!=", t10_qd: "<>",
    t10_tk1: "A ==", t10_tk2: "operátor", t10_tk3: "egyenlőséget", t10_tk4: "vizsgál.",
    t11_title: "Logikai operátorok", t11_text: "Az and, or és not szavakkal feltételeket kapcsolhatunk össze. Az 'and' jelentése: mindkettőnek igaznak kell lennie.", t11_inst: "Töltsd ki a hiányt:", t11_h1: "and = és.", t11_h2: "or = vagy.", t11_q: "Mikor igaz az (A and B)?", t11_qa: "Ha A és B is igaz", t11_qb: "Ha csak A igaz", t11_qc: "Ha csak B igaz", t11_qd: "Ha egyik sem igaz",
    t11_sent: "Az ___ operátornál mindkét feltételnek igaznak kell lennie.", t11_c1: "and", t11_c2: "or", t11_c3: "not", t11_c4: "if",
    t12_title: "Kommentek", t12_text: "A kommentek #-tel kezdődnek, és a Python figyelmen kívül hagyja őket. A kódot magyarázzák az embereknek.", t12_inst: "Párosítsd össze:", t12_h1: "# a kommentekhez.", t12_h2: "Nem hajtódik végre.", t12_q: "Hogyan kezdünk egy kommentet Pythonban?", t12_qa: "# jellel", t12_qb: "// jellel", t12_qc: "<!-- jellel", t12_qd: "/* jellel",
    t12_l1: "#", t12_r1: "Komment", t12_l2: "print()", t12_r2: "Kimenet", t12_l3: "input()", t12_r3: "Bemenet", t12_l4: "=", t12_r4: "Értékadás",
    t13_title: "Stringek összefűzése", t13_text: "Stringeket a + operátorral kapcsolhatunk össze: 'Helló ' + 'Világ' eredménye 'Helló Világ'.", t13_inst: "Tedd sorrendbe a szavakat:", t13_h1: "A plusz szöveget köt össze.", t13_h2: "Helló + Világ.", t13_q: "Mi az eredménye az 'A' + 'B' kifejezésnek?", t13_qa: "'AB'", t13_qb: "'A B'", t13_qc: "Hiba", t13_qd: "Semmi",
    t13_w1: "A plusz", t13_w2: "két", t13_w3: "stringet", t13_w4: "köt össze",
    t14_title: "f-Stringek", t14_text: "Az f-stringek egyszerűen formázzák a szöveget: f'Én {kor} éves vagyok'. A változók {}-be kerülnek.", t14_inst: "Válogasd szét:", t14_h1: "f a string előtt.", t14_h2: "Változók {}-ben.", t14_q: "Hogyan illesztünk be változót egy f-stringbe?", t14_qa: "Kapcsos zárójelek közé {}", t14_qb: "Plusz jellel +", t14_qc: "Szögletes zárójelek közé []", t14_qd: "Vesszővel ,",
    t14_bl1: "f-String", t14_bl2: "Normál String", t14_i1: "f'Helló {nev}'", t14_i2: "'Helló nev'", t14_i3: "f'Kor: {x}'", t14_i4: "'Kor: x'",
    t15_title: "len() függvény", t15_text: "A len() függvény visszaadja egy string vagy lista hosszát: len('Python') értéke 6.", t15_inst: "Jelöld meg a helyes szót:", t15_h1: "len = length (hossz).", t15_h2: "Megszámolja a karaktereket.", t15_q: "Mit ad vissza a len('Helló')?", t15_qa: "5", t15_qb: "4", t15_qc: "6", t15_qd: "Helló",
    t15_tk1: "A len()", t15_tk2: "visszaadja", t15_tk3: "a", t15_tk4: "hosszat."
  },
  ro: {
    explorer_title: "Explorator Informatică K7-4",
    t1_title: "Variabile în Python", t1_text: "O variabilă stochează o valoare. În Python: varsta = 13 sau nume = 'Anna'.", t1_inst: "Potrivește perechile:", t1_h1: "Ce tip de date este ce?", t1_h2: "Număr, text sau boolean?", t1_q: "Ce este o variabilă?", t1_qa: "Un spațiu de stocare cu nume pentru valori", t1_qb: "O buclă", t1_qc: "O funcție", t1_qd: "Un comentariu",
    t1_l1: "varsta = 13", t1_r1: "Integer", t1_l2: "nume = 'Anna'", t1_r2: "String", t1_l3: "adevarat = True", t1_r3: "Boolean", t1_l4: "pret = 1.5", t1_r4: "Float",
    t2_title: "Funcția print()", t2_text: "Cu print() afișăm text sau valori pe ecran în Python.", t2_inst: "Completează spațiul liber:", t2_h1: "print() = ieșire.", t2_h2: "print('Salut') arată Salut.", t2_q: "Ce face print() în Python?", t2_qa: "Afișează text sau valori", t2_qb: "Citește input-ul utilizatorului", t2_qc: "Șterge variabile", t2_qd: "Termină programul",
    t2_sent: "Funcția ___ afișează text pe ecran.", t2_c1: "print()", t2_c2: "input()", t2_c3: "show()", t2_c4: "display()",
    t3_title: "Funcția input()", t3_text: "input() citește introducerea unui utilizator și o returnează ca string.", t3_inst: "Sortează în găleți:", t3_h1: "Intrare sau ieșire?", t3_h2: "input() citește, print() scrie!", t3_q: "Ce face input() în Python?", t3_qa: "Citește introducerea utilizatorului", t3_qb: "Afișează text", t3_qc: "Șterge o variabilă", t3_qd: "Termină programul",
    t3_bl1: "Intrare", t3_bl2: "Ieșire", t3_i1: "input()", t3_i2: "print()", t3_i3: "Utilizatorul tastează", t3_i4: "Ecranul arată",
    t4_title: "Șiruri de caractere (Strings)", t4_text: "Șirurile sunt texte în Python scrise între ghilimele: 'Salut' sau \"Lume\".", t4_inst: "Pune cuvintele în ordine:", t4_h1: "Șiruri între ghilimele.", t4_h2: "Simple sau duble!", t4_q: "Cum scriem un string în Python?", t4_qa: "Între ghilimele: 'Salut'", t4_qb: "Între paranteze unghiulare: <Salut>", t4_qc: "Între paranteze drepte: [Salut]", t4_qd: "Între paranteze rotunde: (Salut)",
    t4_w1: "Șirurile", t4_w2: "sunt", t4_w3: "în", t4_w4: "ghilimele",
    t5_title: "Integer (numere întregi)", t5_text: "Întregii sunt numere întregi în Python fără ghilimele: varsta = 13.", t5_inst: "Evidențiază cuvântul corect:", t5_h1: "Integer = număr întreg, nu text.", t5_h2: "13 este un integer!", t5_q: "Ce este un integer în Python?", t5_qa: "Un număr întreg", t5_qb: "Text între ghilimele", t5_qc: "O valoare booleană", t5_qd: "Un număr zecimal",
    t5_tk1: "Un integer", t5_tk2: "este", t5_tk3: "un", t5_tk4: "număr întreg.",
    t6_title: "Float (Zecimale)", t6_text: "Floats sunt numere zecimale. În Python, folosești un punct în loc de virgulă: pi = 3.14.", t6_inst: "Potrivește perechile:", t6_h1: "Punct în loc de virgulă!", t6_h2: "Float = număr cu virgulă mobilă.", t6_q: "Cum scrii un număr zecimal în Python?", t6_qa: "Cu un punct (3.14)", t6_qb: "Cu o virgulă (3,14)", t6_qc: "Între ghilimele ('3.14')", t6_qd: "Cu două puncte (3:14)",
    t6_l1: "3.14", t6_r1: "Float", t6_l2: "42", t6_r2: "Integer", t6_l3: "'3.14'", t6_r3: "String", t6_l4: "True", t6_r4: "Boolean",
    t7_title: "Boolean (Valori de adevăr)", t7_text: "Booleenii au doar două valori: True (Adevărat) sau False (Fals). Sunt importanți pentru condiții.", t7_inst: "Completează spațiul liber:", t7_h1: "True sau False.", t7_h2: "Cu majusculă!", t7_q: "Ce valori poate avea un Boolean?", t7_qa: "True sau False", t7_qb: "1 la 10", t7_qc: "Da, Nu, Poate", t7_qd: "Orice text",
    t7_sent: "Un Boolean este fie True, fie ___.", t7_c1: "False", t7_c2: "Fals", t7_c3: "Zero", t7_c4: "Nimic",
    t8_title: "Conversia tipurilor", t8_text: "Cu int(), float() sau str() poți converti tipuri de date, de ex. int('5') devine numărul 5.", t8_inst: "Pune cuvintele în ordine:", t8_h1: "Conversia tipurilor.", t8_h2: "Text în număr.", t8_q: "Ce face int('5')?", t8_qa: "Convertește textul '5' în numărul 5", t8_qb: "Afișează '5' pe ecran", t8_qc: "Șterge numărul 5", t8_qd: "Face din 5 un număr zecimal",
    t8_w1: "int()", t8_w2: "convertește", t8_w3: "textul", t8_w4: "în numere",
    t9_title: "Operatori aritmetici", t9_text: "Python folosește +, -, * (înmulțire) și / (împărțire) pentru matematică.", t9_inst: "Sortează în găleți:", t9_h1: "Matematică sau text?", t9_h2: "* este înmulțire, / este împărțire.", t9_q: "Ce simbol folosește Python pentru înmulțire?", t9_qa: "* (asterisc)", t9_qb: "x (literă)", t9_qc: ". (punct)", t9_qd: ": (două puncte)",
    t9_bl1: "Matematică", t9_bl2: "Comparație", t9_i1: "+ și -", t9_i2: "== și !=", t9_i3: "* și /", t9_i4: "< și >",
    t10_title: "Operatori de comparație", t10_text: "Cu == (egal), != (diferit), < și > compari valori. Rezultatul este un Boolean.", t10_inst: "Evidențiază cuvântul corect:", t10_h1: "== verifică egalitatea.", t10_h2: "= este atribuire.", t10_q: "Care operator verifică dacă două valori sunt egale?", t10_qa: "==", t10_qb: "=", t10_qc: "!=", t10_qd: "<>",
    t10_tk1: "Operatorul", t10_tk2: "==", t10_tk3: "verifică", t10_tk4: "egalitatea.",
    t11_title: "Operatori logici", t11_text: "Cu and, or și not poți combina condiții. 'and' înseamnă: ambele trebuie să fie adevărate.", t11_inst: "Completează spațiul liber:", t11_h1: "and = ambele.", t11_h2: "or = unul dintre ele.", t11_q: "Când este (A and B) adevărat?", t11_qa: "Când A și B sunt adevărate", t11_qb: "Când doar A este adevărat", t11_qc: "Când doar B este adevărat", t11_qd: "Când niciunul nu este adevărat",
    t11_sent: "Cu ___ ambele condiții trebuie să fie adevărate.", t11_c1: "and", t11_c2: "or", t11_c3: "not", t11_c4: "if",
    t12_title: "Comentarii", t12_text: "Comentariile încep cu # și sunt ignorate de Python. Ele explică codul pentru oameni.", t12_inst: "Potrivește perechile:", t12_h1: "# pentru comentarii.", t12_h2: "Nu este executat.", t12_q: "Cum începi un comentariu în Python?", t12_qa: "Cu #", t12_qb: "Cu //", t12_qc: "Cu <!--", t12_qd: "Cu /*",
    t12_l1: "#", t12_r1: "Comentariu", t12_l2: "print()", t12_r2: "Ieșire", t12_l3: "input()", t12_r3: "Intrare", t12_l4: "=", t12_r4: "Atribuire",
    t13_title: "Concatenarea șirurilor", t13_text: "Poți uni șiruri cu operatorul +: 'Salut ' + 'Lume' devine 'Salut Lume'.", t13_inst: "Pune cuvintele în ordine:", t13_h1: "Plus unește textul.", t13_h2: "Salut + Lume.", t13_q: "Care este rezultatul lui 'A' + 'B'?", t13_qa: "'AB'", t13_qb: "'A B'", t13_qc: "O eroare", t13_qd: "Nimic",
    t13_w1: "Plusul", t13_w2: "unește", t13_w3: "două", t13_w4: "șiruri",
    t14_title: "f-Strings", t14_text: "f-Strings formatează textul ușor: f'Am {varsta} ani'. Variabilele merg în {}.", t14_inst: "Sortează în găleți:", t14_h1: "f înainte de șir.", t14_h2: "Variabile în {}.", t14_q: "Cum inserezi o variabilă într-un f-String?", t14_qa: "În acolade {}", t14_qb: "Cu un plus +", t14_qc: "În paranteze drepte []", t14_qd: "Cu o virgulă ,",
    t14_bl1: "f-String", t14_bl2: "Șir normal", t14_i1: "f'Salut {nume}'", t14_i2: "'Salut nume'", t14_i3: "f'Vârsta: {x}'", t14_i4: "'Vârsta: x'",
    t15_title: "Funcția len()", t15_text: "Funcția len() returnează lungimea unui șir sau a unei liste: len('Python') este 6.", t15_inst: "Evidențiază cuvântul corect:", t15_h1: "len = lungime.", t15_h2: "Numără caracterele.", t15_q: "Ce returnează len('Salut')?", t15_qa: "5", t15_qb: "4", t15_qc: "6", t15_qd: "Salut",
    t15_tk1: "len()", t15_tk2: "returnează", t15_tk3: "lungimea", t15_tk4: "șirului."
  }
};

export const INFO_K7_I4_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "📦", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "match-pairs", instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2", pairs: [{left:"t1_l1",right:"t1_r1"},{left:"t1_l2",right:"t1_r2"},{left:"t1_l3",right:"t1_r3"},{left:"t1_l4",right:"t1_r4"}] },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🖨️", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "gap-fill", instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2", sentence: "t2_sent", choices: ["t2_c1", "t2_c2", "t2_c3", "t2_c4"], correctIndex: 0 },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "⌨️", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "drag-to-bucket", instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2", buckets: [{id:"b1",label:"t3_bl1"},{id:"b2",label:"t3_bl2"}], items: [{text:"t3_i1",bucketId:"b1"},{text:"t3_i2",bucketId:"b2"},{text:"t3_i3",bucketId:"b1"},{text:"t3_i4",bucketId:"b2"}] },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🔤", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "physics-stacker", instruction: "t4_inst", hint1: "t4_h1", hint2: "t4_h2", words: ["t4_w1", "t4_w2", "t4_w3", "t4_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🔢", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t5_inst", hint1: "t5_h1", hint2: "t5_h2", tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4"], correctIndices: [3] },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t6_title", infoText: "t6_text",
    svg: { type: "simple-icon", icon: "📏", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "match-pairs", instruction: "t6_inst", hint1: "t6_h1", hint2: "t6_h2", pairs: [{left:"t6_l1",right:"t6_r1"},{left:"t6_l2",right:"t6_r2"},{left:"t6_l3",right:"t6_r3"},{left:"t6_l4",right:"t6_r4"}] },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title", infoText: "t7_text",
    svg: { type: "simple-icon", icon: "✅", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "gap-fill", instruction: "t7_inst", hint1: "t7_h1", hint2: "t7_h2", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3", "t7_c4"], correctIndex: 0 },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title", infoText: "t8_text",
    svg: { type: "simple-icon", icon: "🔄", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "physics-stacker", instruction: "t8_inst", hint1: "t8_h1", hint2: "t8_h2", words: ["t8_w1", "t8_w2", "t8_w3", "t8_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t9_title", infoText: "t9_text",
    svg: { type: "simple-icon", icon: "➕", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "drag-to-bucket", instruction: "t9_inst", hint1: "t9_h1", hint2: "t9_h2", buckets: [{id:"b1",label:"t9_bl1"},{id:"b2",label:"t9_bl2"}], items: [{text:"t9_i1",bucketId:"b1"},{text:"t9_i2",bucketId:"b2"},{text:"t9_i3",bucketId:"b1"},{text:"t9_i4",bucketId:"b2"}] },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t10_title", infoText: "t10_text",
    svg: { type: "simple-icon", icon: "⚖️", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t10_inst", hint1: "t10_h1", hint2: "t10_h2", tokens: ["t10_tk1", "t10_tk2", "t10_tk3", "t10_tk4"], correctIndices: [1] },
    quiz: { question: "t10_q", choices: ["t10_qa", "t10_qb", "t10_qc", "t10_qd"], answer: "t10_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t11_title", infoText: "t11_text",
    svg: { type: "simple-icon", icon: "🔗", bg: "#EFF6FF", color: "#2563EB" },
    interactive: { type: "gap-fill", instruction: "t11_inst", hint1: "t11_h1", hint2: "t11_h2", sentence: "t11_sent", choices: ["t11_c1", "t11_c2", "t11_c3", "t11_c4"], correctIndex: 0 },
    quiz: { question: "t11_q", choices: ["t11_qa", "t11_qb", "t11_qc", "t11_qd"], answer: "t11_qa" }
  },
  {
    difficulty: "easy",
    infoTitle: "t12_title", infoText: "t12_text",
    svg: { type: "simple-icon", icon: "💬", bg: "#FDF2F8", color: "#DB2777" },
    interactive: { type: "match-pairs", instruction: "t12_inst", hint1: "t12_h1", hint2: "t12_h2", pairs: [{left:"t12_l1",right:"t12_r1"},{left:"t12_l2",right:"t12_r2"},{left:"t12_l3",right:"t12_r3"},{left:"t12_l4",right:"t12_r4"}] },
    quiz: { question: "t12_q", choices: ["t12_qa", "t12_qb", "t12_qc", "t12_qd"], answer: "t12_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t13_title", infoText: "t13_text",
    svg: { type: "simple-icon", icon: "🖇️", bg: "#F0F9FF", color: "#0EA5E9" },
    interactive: { type: "physics-stacker", instruction: "t13_inst", hint1: "t13_h1", hint2: "t13_h2", words: ["t13_w1", "t13_w2", "t13_w3", "t13_w4"], correctOrder: [0, 1, 2, 3] },
    quiz: { question: "t13_q", choices: ["t13_qa", "t13_qb", "t13_qc", "t13_qd"], answer: "t13_qa" }
  },
  {
    difficulty: "medium",
    infoTitle: "t14_title", infoText: "t14_text",
    svg: { type: "simple-icon", icon: "✨", bg: "#FEF3C7", color: "#D97706" },
    interactive: { type: "drag-to-bucket", instruction: "t14_inst", hint1: "t14_h1", hint2: "t14_h2", buckets: [{id:"b1",label:"t14_bl1"},{id:"b2",label:"t14_bl2"}], items: [{text:"t14_i1",bucketId:"b1"},{text:"t14_i2",bucketId:"b2"},{text:"t14_i3",bucketId:"b1"},{text:"t14_i4",bucketId:"b2"}] },
    quiz: { question: "t14_q", choices: ["t14_qa", "t14_qb", "t14_qc", "t14_qd"], answer: "t14_qa" }
  },
  {
    difficulty: "hard",
    infoTitle: "t15_title", infoText: "t15_text",
    svg: { type: "simple-icon", icon: "📏", bg: "#F3E8FF", color: "#B45309" },
    interactive: { type: "highlight-text", instruction: "t15_inst", hint1: "t15_h1", hint2: "t15_h2", tokens: ["t15_tk1", "t15_tk2", "t15_tk3", "t15_tk4"], correctIndices: [0] },
    quiz: { question: "t15_q", choices: ["t15_qa", "t15_qb", "t15_qc", "t15_qd"], answer: "t15_qa" }
  }
];
