// @ts-nocheck
// lib/explorerPools/informatikaK1_i1.ts
import type { PoolTopicDef } from "./types";

export const INFO_K1_I1_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Code Kids Informatik 1",
    t1_title: "Der Computer", t1_text: "Der Computer hilft uns beim Lernen und Spielen.", t1_inst: "Verbinde die Paare:", t1_h1: "Lernen und Spielen.", t1_h2: "Ein kluger Helfer.", t1_q: "Was hilft uns beim Lernen?", t1_qa: "Computer", t1_qb: "Auto", t1_qc: "Ball", t1_qd: "Apfel",
    t1_l1: "Monitor", t1_r1: "Bild", t1_l2: "Maus", t1_r2: "Klick", t1_l3: "Tastatur", t1_r3: "Schreiben",
    t2_title: "Der Bildschirm", t2_text: "Auf dem Bildschirm sehen wir Bilder und Buchstaben.", t2_inst: "Verbinde die Paare:", t2_h1: "Bilder sehen.", t2_h2: "Bunt und hell.", t2_q: "Was sehen wir auf dem Bildschirm?", t2_qa: "Bilder", t2_qb: "Geräusche", t2_qc: "Gerüche", t2_qd: "Wasser",
    t2_l1: "Bild", t2_r1: "Anblick", t2_l2: "Buchstabe", t2_r2: "Lesen", t2_l3: "Farbe", t2_r3: "Schön",
    t3_title: "Die Maus", t3_text: "Mit der Maus können wir uns auf dem Bildschirm bewegen.", t3_inst: "Verbinde die Paare:", t3_h1: "Den Pfeil bewegen.", t3_h2: "Klick machen.", t3_q: "Womit bewegen wir den Pfeil?", t3_qa: "Maus", t3_qb: "Fuß", t3_qc: "Auge", t3_qd: "Nase",
    t3_l1: "Klick", t3_r1: "Taste", t3_l2: "Bewegen", t3_r2: "Pfeil", t3_l3: "Scrollen", t3_r3: "Rad",
    t4_title: "Die Tastatur", t4_text: "Mit der Tastatur können wir Buchstaben schreiben.", t4_inst: "Verbinde die Paare:", t4_h1: "Buchstaben tippen.", t4_h2: "Viele Tasten.", t4_q: "Womit können wir schreiben?", t4_qa: "Tastatur", t4_qb: "Bleistift", t4_qc: "Löffel", t4_qd: "Schuh",
    t4_l1: "Buchstabe", t4_r1: "Taste", t4_l2: "Leerzeichen", t4_r2: "Abstand", t4_l3: "Enter", t4_r3: "Neue Zeile",
    t5_title: "Ein- und Ausschalten", t5_text: "Mit dem Knopf können wir die Maschine starten.", t5_inst: "Verbinde die Paare:", t5_h1: "Start und Stopp.", t5_h2: "Drück den Knopf.", t5_q: "Wie starten wir die Maschine?", t5_qa: "Mit dem Knopf", t5_qb: "Durch Schreien", t5_qc: "Durch Schlafen", t5_qd: "Durch Laufen",
    t5_l1: "Ein", t5_r1: "Start", t5_l2: "Aus", t5_r2: "Stopp", t5_l3: "Knopf", t5_r3: "Drücken",
    t6_title: "Der Ton", t6_text: "Aus den Lautsprechern hören wir Musik und Stimmen.", t6_inst: "Verbinde die Paare:", t6_h1: "Musik hören.", t6_h2: "Lautsprecher.", t6_q: "Was macht der Lautsprecher?", t6_qa: "Töne", t6_qb: "Licht", t6_qc: "Bilder", t6_qd: "Essen",
    t6_l1: "Lautsprecher", t6_r1: "Ton", t6_l2: "Musik", t6_r2: "Hören", t6_l3: "Leise", t6_r3: "Stumm",
    t7_title: "Videos", t7_text: "Wir können Filme und kleine Videos am Computer ansehen.", t7_inst: "Verbinde die Paare:", t7_h1: "Bewegte Bilder.", t7_h2: "Film ab!", t7_q: "Was ist ein Video?", t7_qa: "Ein kleiner Film", t7_qb: "Ein Stein", t7_qc: "Ein Brot", t7_qd: "Ein Schuh",
    t7_l1: "Video", t7_r1: "Film", t7_l2: "Start", t7_r2: "Play", t7_l3: "Pause", t7_r3: "Warten",
    t8_title: "Drucken", t8_text: "Der Drucker bringt unsere Bilder auf echtes Papier.", t8_inst: "Verbinde die Paare:", t8_h1: "Papier und Tinte.", t8_h2: "Ausdrucken.", t8_q: "Was macht der Drucker?", t8_qa: "Bilder auf Papier", t8_qb: "Essen kochen", t8_qc: "Wäsche waschen", t8_qd: "Auto fahren",
    t8_l1: "Drucker", t8_r1: "Papier", t8_l2: "Farbe", t8_r2: "Tinte", t8_l3: "Fertig", t8_r3: "Blatt",
    t9_title: "Der Scanner", t9_text: "Ein Scanner liest Bilder ein und schickt sie in den Computer.", t9_inst: "Verbinde die Paare:", t9_h1: "Bilder einlesen.", t9_h2: "Digital machen.", t9_q: "Was macht ein Scanner?", t9_qa: "Bilder einlesen", t9_qb: "Löcher bohren", t9_qc: "Singen", t9_qd: "Tanzen",
    t9_l1: "Scanner", t9_r1: "Einlesen", t9_l2: "Foto", t9_r2: "Kopie", t9_l3: "Licht", t9_r3: "Abtasten",
    t10_title: "Wi-Fi", t10_text: "Wi-Fi verbindet den Computer ohne Kabel mit dem Internet.", t10_inst: "Verbinde die Paare:", t10_h1: "Ohne Kabel.", t10_h2: "Internet.", t10_q: "Was ist Wi-Fi?", t10_qa: "Funk-Internet", t10_qb: "Ein Haustier", t10_qc: "Ein Spielzeug", t10_qd: "Ein Apfel",
    t10_l1: "Wi-Fi", t10_r1: "Funk", t10_l2: "Internet", t10_r2: "Netz", t10_l3: "Wellen", t10_r3: "Signal",
    t11_title: "Update", t11_text: "Ein Update macht den Computer besser und sicherer.", t11_inst: "Verbinde die Paare:", t11_h1: "Neu machen.", t11_h2: "Besser werden.", t11_q: "Was macht ein Update?", t11_qa: "Programme erneuern", t11_qb: "Alles löschen", t11_qc: "Kaputt machen", t11_qd: "Schlafen",
    t11_l1: "Update", t11_r1: "Neu", t11_l2: "Warten", t11_r2: "Laden", t11_l3: "Fertig", t11_r3: "Besser",
    t12_title: "Hilfe bei Fehlern", t12_text: "Wenn etwas nicht geht, frag einen Erwachsenen um Hilfe.", t12_inst: "Verbinde die Paare:", t12_h1: "Nicht verzagen.", t12_h2: "Hilfe holen.", t12_q: "Was tun bei einem Fehler?", t12_qa: "Hilfe fragen", t12_qb: "Weinen", t12_qc: "Weglaufen", t12_qd: "Kaputt machen",
    t12_l1: "Fehler", t12_r1: "Problem", t12_l2: "Hilfe", t12_r2: "Fragen", t12_l3: "Lösung", t12_r3: "Gut",
    t13_title: "Neustart", t13_text: "Manchmal hilft es, den Computer einfach neu zu starten.", t13_inst: "Verbinde die Paare:", t13_h1: "Aus und an.", t13_h2: "Frisch beginnen.", t13_q: "Was ist ein Neustart?", t13_qa: "Neu beginnen", t13_qb: "Ganz löschen", t13_qc: "Wegwerfen", t13_qd: "Essen",
    t13_l1: "Neustart", t13_r1: "Reset", t13_l2: "Warten", t13_r2: "Laden", t13_l3: "Start", t13_r3: "Anfang",
    t14_title: "Programme", t14_text: "Wir können neue Spiele und Programme auf dem Computer installieren.", t14_inst: "Verbinde die Paare:", t14_h1: "Neue Spiele.", t14_h2: "Installieren.", t14_q: "Was ist ein Programm?", t14_qa: "Ein Werkzeug oder Spiel", t14_qb: "Ein Baum", t14_qc: "Ein Stein", t14_qd: "Ein Vogel",
    t14_l1: "Programm", t14_r1: "App", t14_l2: "Installieren", t14_r2: "Hinzufügen", t14_l3: "Icon", t14_r3: "Bildchen",
    t15_title: "Informatik-Meister", t15_text: "Du kennst dich jetzt super mit dem Computer aus!", t15_inst: "Verbinde die Paare:", t15_h1: "Du bist toll.", t15_h2: "Alles gelernt.", t15_q: "Was bist du jetzt?", t15_qa: "Ein Meister", t15_qb: "Ein Auto", t15_qc: "Ein Baum", t15_qd: "Ein Stein",
    t15_l1: "Meister", t15_r1: "Wissen", t15_l2: "Computer", t15_r2: "Profi", t15_l3: "Sieg", t15_r3: "Pokal"
  },
  en: {
    explorer_title: "Code Kids Informatics 1",
    t1_title: "The Computer", t1_text: "The computer helps us learn and play.", t1_inst: "Match the pairs:", t1_h1: "Learn and play.", t1_h2: "A smart helper.", t1_q: "What helps us learn?", t1_qa: "Computer", t1_qb: "Car", t1_qc: "Ball", t1_qd: "Apple",
    t1_l1: "Monitor", t1_r1: "Image", t1_l2: "Mouse", t1_r2: "Click", t1_l3: "Keyboard", t1_r3: "Writing",
    t2_title: "The Screen", t2_text: "We see images and letters on the screen.", t2_inst: "Match the pairs:", t2_h1: "See images.", t2_h2: "Bright and colorful.", t2_q: "What do we see on the screen?", t2_qa: "Images", t2_qb: "Sounds", t2_qc: "Smells", t2_qd: "Water",
    t2_l1: "Image", t2_r1: "Sight", t2_l2: "Letter", t2_r2: "Reading", t2_l3: "Color", t2_r3: "Beautiful",
    t3_title: "The Mouse", t3_text: "We can move on the screen with the mouse.", t3_inst: "Match the pairs:", t3_h1: "Move the arrow.", t3_h2: "Make a click.", t3_q: "What do we use to move the arrow?", t3_qa: "Mouse", t3_qb: "Foot", t3_qc: "Eye", t3_qd: "Nose",
    t3_l1: "Click", t3_r1: "Button", t3_l2: "Move", t3_r2: "Arrow", t3_l3: "Scroll", t3_r3: "Wheel",
    t4_title: "The Keyboard", t4_text: "We can write letters with the keyboard.", t4_inst: "Match the pairs:", t4_h1: "Type letters.", t4_h2: "Many keys.", t4_q: "What can we use to write?", t4_qa: "Keyboard", t4_qb: "Pencil", t4_qc: "Spoon", t4_qd: "Shoe",
    t4_l1: "Letter", t4_r1: "Key", t4_l2: "Space", t4_r2: "Gap", t4_l3: "Enter", t4_r3: "New line",
    t5_title: "Turning On and Off", t5_text: "We can start the machine with the button.", t5_inst: "Match the pairs:", t5_h1: "Start and stop.", t5_h2: "Press the button.", t5_q: "How do we start the machine?", t5_qa: "With the button", t5_qb: "By shouting", t5_qc: "By sleeping", t5_qd: "By running",
    t5_l1: "On", t5_r1: "Start", t5_l2: "Off", t5_r2: "Stop", t5_l3: "Button", t5_r3: "Press",
    t6_title: "The Sound", t6_text: "We hear music and voices from the speakers.", t6_inst: "Match the pairs:", t6_h1: "Hear music.", t6_h2: "Speakers.", t6_q: "What does the speaker do?", t6_qa: "Sounds", t6_qb: "Light", t6_qc: "Images", t6_qd: "Food",
    t6_l1: "Speaker", t6_r1: "Sound", t6_l2: "Music", t6_r2: "Hear", t6_l3: "Quiet", t6_r3: "Mute",
    t7_title: "Videos", t7_text: "We can watch movies and small videos on the computer.", t7_inst: "Match the pairs:", t7_h1: "Moving images.", t7_h2: "Play movie!", t7_q: "What is a video?", t7_qa: "A small movie", t7_qb: "A stone", t7_qc: "Bread", t7_qd: "A shoe",
    t7_l1: "Video", t7_r1: "Movie", t7_l2: "Start", t7_r2: "Play", t7_l3: "Pause", t7_r3: "Wait",
    t8_title: "Printing", t8_text: "The printer puts our pictures on real paper.", t8_inst: "Match the pairs:", t8_h1: "Paper and ink.", t8_h2: "Print out.", t8_q: "What does the printer do?", t8_qa: "Images on paper", t8_qb: "Cook food", t8_qc: "Wash clothes", t8_qd: "Drive car",
    t8_l1: "Printer", t8_r1: "Paper", t8_l2: "Color", t8_r2: "Ink", t8_l3: "Done", t8_r3: "Sheet",
    t9_title: "The Scanner", t9_text: "A scanner reads pictures and sends them to the computer.", t9_inst: "Match the pairs:", t9_h1: "Read images.", t9_h2: "Make digital.", t9_q: "What does a scanner do?", t9_qa: "Read images", t9_qb: "Drill holes", t9_qc: "Sing", t9_qd: "Dance",
    t9_l1: "Scanner", t9_r1: "Read", t9_l2: "Photo", t9_r2: "Copy", t9_l3: "Light", t9_r3: "Scan",
    t10_title: "Wi-Fi", t10_text: "Wi-Fi connects the computer to the internet without cables.", t10_inst: "Match the pairs:", t10_h1: "No cables.", t10_h2: "Internet.", t10_q: "What is Wi-Fi?", t10_qa: "Wireless internet", t10_qb: "A pet", t10_qc: "A toy", t10_qd: "An apple",
    t10_l1: "Wi-Fi", t10_r1: "Radio", t10_l2: "Internet", t10_r2: "Net", t10_l3: "Waves", t10_r3: "Signal",
    t11_title: "Update", t11_text: "An update makes the computer better and safer.", t11_inst: "Match the pairs:", t11_h1: "Make new.", t11_h2: "Get better.", t11_q: "What does an update do?", t11_qa: "Renew programs", t11_qb: "Delete all", t11_qc: "Break things", t11_qd: "Sleep",
    t11_l1: "Update", t11_r1: "New", t11_l2: "Wait", t11_r2: "Load", t11_l3: "Done", t11_r3: "Better",
    t12_title: "Help with Errors", t12_text: "If something doesn't work, ask an adult for help.", t12_inst: "Match the pairs:", t12_h1: "Don't worry.", t12_h2: "Get help.", t12_q: "What to do if there's an error?", t12_qa: "Ask for help", t12_qb: "Cry", t12_qc: "Run away", t12_qd: "Break it",
    t12_l1: "Error", t12_r1: "Problem", t12_l2: "Help", t12_r2: "Ask", t12_l3: "Solution", t12_r3: "Good",
    t13_title: "Restart", t13_text: "Sometimes it helps to just restart the computer.", t13_inst: "Match the pairs:", t13_h1: "Off and on.", t13_h2: "Start fresh.", t13_q: "What is a restart?", t13_qa: "Start over", t13_qb: "Delete all", t13_qc: "Throw away", t13_qd: "Eat",
    t13_l1: "Restart", t13_r1: "Reset", t13_l2: "Wait", t13_r2: "Load", t13_l3: "Start", t13_r3: "Beginning",
    t14_title: "Programs", t14_text: "We can install new games and programs on the computer.", t14_inst: "Match the pairs:", t14_h1: "New games.", t14_h2: "Install.", t14_q: "What is a program?", t14_qa: "A tool or game", t14_qb: "A tree", t14_qc: "A stone", t14_qd: "A bird",
    t14_l1: "Program", t14_r1: "App", t14_l2: "Install", t14_r2: "Add", t14_l3: "Icon", t14_r3: "Picture",
    t15_title: "Informatics Master", t15_text: "You now know a lot about the computer!", t15_inst: "Match the pairs:", t15_h1: "You are great.", t15_h2: "Learned all.", t15_q: "What are you now?", t15_qa: "A Master", t15_qb: "A car", t15_qc: "A tree", t15_qd: "A stone",
    t15_l1: "Master", t15_r1: "Knowledge", t15_l2: "Computer", t15_r2: "Pro", t15_l3: "Win", t15_r3: "Cup"
  },
  hu: {
    explorer_title: "Code Kids Informatika 1",
    t1_title: "A számítógép", t1_text: "A számítógép segít nekünk tanulni és játszani.", t1_inst: "Párosítsd össze:", t1_h1: "Tanulás és játék.", t1_h2: "Okos segítőtárs.", t1_q: "Mi segít nekünk a tanulásban?", t1_qa: "Számítógép", t1_qb: "Autó", t1_qc: "Labda", t1_qd: "Alma",
    t1_l1: "Monitor", t1_r1: "Kép", t1_l2: "Egér", t1_r2: "Kattintás", t1_l3: "Billentyűzet", t1_r3: "Írás",
    t2_title: "A képernyő", t2_text: "A képernyőn látjuk a képeket és a betűket.", t2_inst: "Párosítsd össze:", t2_h1: "Képek nézése.", t2_h2: "Színes és fényes.", t2_q: "Mit látunk a képernyőn?", t2_qa: "Képeket", t2_qb: "Hangokat", t2_qc: "Illatokat", t2_qd: "Vizet",
    t2_l1: "Kép", t2_r1: "Látvány", t2_l2: "Betű", t2_r2: "Olvasás", t2_l3: "Szín", t2_r3: "Szép",
    t3_title: "Az egér", t3_text: "Az egérrel tudunk mozogni a képernyőn.", t3_inst: "Párosítsd össze:", t3_h1: "A nyíl mozgatása.", t3_h2: "Kattints egyet.", t3_q: "Mivel mozgatjuk a nyilat?", t3_qa: "Egérrel", t3_qb: "Lábbal", t3_qc: "Szemmel", t3_qd: "Orral",
    t3_l1: "Kattintás", t3_r1: "Gomb", t3_l2: "Mozgatás", t3_r2: "Nyíl", t3_l3: "Görgetés", t3_r3: "Kerék",
    t4_title: "A billentyűzet", t4_text: "A billentyűzettel tudunk betűket írni.", t4_inst: "Párosítsd össze:", t4_h1: "Betűk gépelése.", t4_h2: "Sok gomb.", t4_q: "Mivel tudunk írni?", t4_qa: "Billentyűzettel", t4_qb: "Ceruzával", t4_qc: "Kanállal", t4_qd: "Cipővel",
    t4_l1: "Betű", t4_r1: "Gomb", t4_l2: "Szóköz", t4_r2: "Hely", t4_l3: "Enter", t4_r3: "Új sor",
    t5_title: "Be- és kikapcsolás", t5_text: "A gombbal tudjuk elindítani a gépet.", t5_inst: "Párosítsd össze:", t5_h1: "Start és stop.", t5_h2: "Nyomd meg a gombot.", t5_q: "Hogyan indítjuk el a gépet?", t5_qa: "Gombbal", t5_qb: "Kiabálással", t5_qc: "Alvással", t5_qd: "Futással",
    t5_l1: "Be", t5_r1: "Indítás", t5_l2: "Ki", t5_r2: "Leállítás", t5_l3: "Gomb", t5_r3: "Nyomás",
    t6_title: "A hang", t6_text: "A hangszórókból halljuk a zenét és a beszédet.", t6_inst: "Párosítsd össze:", t6_h1: "Zenehallgatás.", t6_h2: "Hangszórók.", t6_q: "Mit csinál a hangszóró?", t6_qa: "Hangot ad", t6_qb: "Világít", t6_qc: "Képet mutat", t6_qd: "Eszik",
    t6_l1: "Hangszóró", t6_r1: "Hang", t6_l2: "Zene", t6_r2: "Hallás", t6_l3: "Halk", t6_r3: "Néma",
    t7_title: "Videó", t7_text: "Filmeket és kis videókat is nézhetünk a gépen.", t7_inst: "Párosítsd össze:", t7_h1: "Mozgóképek.", t7_h2: "Indul a film!", t7_q: "Mi az a videó?", t7_qa: "Egy kisfilm", t7_qb: "Egy kő", t7_qc: "Egy kenyér", t7_qd: "Egy cipő",
    t7_l1: "Videó", t7_r1: "Film", t7_l2: "Indítás", t7_r2: "Lejátszás", t7_l3: "Szünet", t7_r3: "Várakozás",
    t8_title: "Nyomtatás", t8_text: "A nyomtató papírra teszi a rajzainkat.", t8_inst: "Párosítsd össze:", t8_h1: "Papír és festék.", t8_h2: "Kinyomtatás.", t8_q: "Mit csinál a nyomtató?", t8_qa: "Képet tesz papírra", t8_qb: "Főz", t8_qc: "Mos", t8_qd: "Autót vezet",
    t8_l1: "Nyomtató", t8_r1: "Papír", t8_l2: "Szín", t8_r2: "Tinta", t8_l3: "Kész", t8_r3: "Lap",
    t9_title: "Scanner", t9_text: "A scanner beolvassa a képeket a gépbe.", t9_inst: "Párosítsd össze:", t9_h1: "Képek beolvasása.", t9_h2: "Digitális lesz.", t9_q: "Mit csinál a scanner?", t9_qa: "Beolvassa a képet", t9_qb: "Lyukat fúr", t9_qc: "Énekel", t9_qd: "Táncol",
    t9_l1: "Scanner", t9_r1: "Beolvasás", t9_l2: "Fotó", t9_r2: "Másolat", t9_l3: "Fény", t9_r3: "Pásztázás",
    t10_title: "Wi-Fi", t10_text: "A Wi-Fi kábel nélkül köti össze a gépet az internettel.", t10_inst: "Párosítsd össze:", t10_h1: "Kábel nélkül.", t10_h2: "Internet.", t10_q: "Mi az a Wi-Fi?", t10_qa: "Vezeték nélküli net", t10_qb: "Egy kiskutya", t10_qc: "Egy játék", t10_qd: "Egy alma",
    t10_l1: "Wi-Fi", t10_r1: "Rádió", t10_l2: "Internet", t10_r2: "Hálózat", t10_l3: "Hullámok", t10_r3: "Jel",
    t11_title: "Frissítés", t11_text: "A frissítés jobbá és biztonságosabbá teszi a gépet.", t11_inst: "Párosítsd össze:", t11_h1: "Újjá tenni.", t11_h2: "Jobb lesz.", t11_q: "Mit csinál a frissítés?", t11_qa: "Megújítja a gépet", t11_qb: "Mindent töröl", t11_qc: "Elrontja", t11_qd: "Alszik",
    t11_l1: "Frissítés", t11_r1: "Új", t11_l2: "Várakozás", t11_r2: "Betöltés", t11_l3: "Kész", t11_r3: "Jobb",
    t12_title: "Ha hiba van", t12_text: "Ha valami nem működik, kérj segítséget egy felnőttől.", t12_inst: "Párosítsd össze:", t12_h1: "Ne aggódj.", t12_h2: "Kérj segítséget.", t12_q: "Mit tegyél, ha hiba van?", t12_qa: "Kérj segítséget", t12_qb: "Sírj", t12_qc: "Szaladj el", t12_qd: "Törd össze",
    t12_l1: "Hiba", t12_r1: "Probléma", t12_l2: "Segítség", t12_r2: "Kérdezés", t12_l3: "Megoldás", t12_r3: "Jó",
    t13_title: "Újraindítás", t13_text: "Néha segít, ha egyszerűen újraindítjuk a gépet.", t13_inst: "Párosítsd össze:", t13_h1: "Ki és be.", t13_h2: "Tiszta lap.", t13_q: "Mi az az újraindítás?", t13_qa: "Újrakezdés", t13_qb: "Törlés", t13_qc: "Kidobás", t13_qd: "Evés",
    t13_l1: "Újraindítás", t13_r1: "Reset", t13_l2: "Várás", t13_r2: "Töltés", t13_l3: "Start", t13_r3: "Kezdet",
    t14_title: "Programok", t14_text: "Új játékokat és programokat is tehetünk a gépre.", t14_inst: "Párosítsd össze:", t14_h1: "Új játékok.", t14_h2: "Telepítés.", t14_q: "Mi az a program?", t14_qa: "Egy eszköz vagy játék", t14_qb: "Egy fa", t14_qc: "Egy kő", t14_qd: "Egy madár",
    t14_l1: "Program", t14_r1: "App", t14_l2: "Telepítés", t14_r2: "Hozzáadás", t14_l3: "Ikon", t14_r3: "Kép",
    t15_title: "Informatika Mester", t15_text: "Most már nagyon sokat tudsz a számítógépről!", t15_inst: "Párosítsd össze:", t15_h1: "Ügyes vagy.", t15_h2: "Mindent tudsz.", t15_q: "Mi vagy te most?", t15_qa: "Egy Mester", t15_qb: "Egy autó", t15_qc: "Egy fa", t15_qd: "Egy kő",
    t15_l1: "Mester", t15_r1: "Tudás", t15_l2: "Gép", t15_r2: "Profi", t15_l3: "Győzelem", t15_r3: "Kupa"
  },
  ro: {
    explorer_title: "Code Kids Informatică 1",
    t1_title: "Calculatorul", t1_text: "Calculatorul ne ajută să învățăm și să ne jucăm.", t1_inst: "Potrivește perechile:", t1_h1: "Învățare și joc.", t1_h2: "Un ajutor deștept.", t1_q: "Ce ne ajută să învățăm?", t1_qa: "Calculatorul", t1_qb: "Mașina", t1_qc: "Mingea", t1_qd: "Mărul",
    t1_l1: "Monitor", t1_r1: "Imagine", t1_l2: "Mouse", t1_r2: "Click", t1_l3: "Tastatură", t1_r3: "Scriere",
    t2_title: "Ecranul", t2_text: "Pe ecran vedem imagini și litere.", t2_inst: "Potrivește perechile:", t2_h1: "Privim imagini.", t2_h2: "Luminos și colorat.", t2_q: "Ce vedem pe ecran?", t2_qa: "Imagini", t2_qb: "Sunete", t2_qc: "Mirosuri", t2_qd: "Apă",
    t2_l1: "Imagine", t2_r1: "Vedere", t2_l2: "Literă", t2_r2: "Citire", t2_l3: "Culoare", t2_r3: "Frumos",
    t3_title: "Mouse-ul", t3_text: "Cu mouse-ul ne putem mișca pe ecran.", t3_inst: "Potrivește perechile:", t3_h1: "Mișcăm săgeata.", t3_h2: "Dă un click.", t3_q: "Cu ce mișcăm săgeata?", t3_qa: "Cu mouse-ul", t3_qb: "Cu piciorul", t3_qc: "Cu ochiul", t3_qd: "Cu nasul",
    t3_l1: "Click", t3_r1: "Buton", t3_l2: "Mișcare", t3_r2: "Săgeată", t3_l3: "Scroll", t3_r3: "Rotiță",
    t4_title: "Tastatura", t4_text: "Cu tastatura putem scrie litere.", t4_inst: "Potrivește perechile:", t4_h1: "Scriem litere.", t4_h2: "Multe taste.", t4_q: "Cu ce putem scrie?", t4_qa: "Cu tastatura", t4_qb: "Cu creionul", t4_qc: "Cu lingura", t4_qd: "Cu pantoful",
    t4_l1: "Literă", t4_r1: "Tastă", t4_l2: "Spațiu", t4_r2: "Loc", t4_l3: "Enter", t4_r3: "Rând nou",
    t5_title: "Pornire și oprire", t5_text: "Cu butonul putem porni aparatul.", t5_inst: "Potrivește perechile:", t5_h1: "Start și stop.", t5_h2: "Apasă butonul.", t5_q: "Cum pornim aparatul?", t5_qa: "Cu butonul", t5_qb: "Prin strigăt", t5_qc: "Prin dormit", t5_qd: "Prin alergat",
    t5_l1: "Pornit", t5_r1: "Start", t5_l2: "Oprit", t5_r2: "Stop", t5_l3: "Buton", t5_r3: "Apăsare",
    t6_title: "Sunetul", t6_text: "Din difuzoare auzim muzică și voci.", t6_inst: "Potrivește perechile:", t6_h1: "Ascultăm muzică.", t6_h2: "Difuzoare.", t6_q: "Ce face difuzorul?", t6_qa: "Sunete", t6_qb: "Lumină", t6_qc: "Imagini", t6_qd: "Mâncare",
    t6_l1: "Difuzor", t6_r1: "Sunet", t6_l2: "Muzică", t6_r2: "Auz", t6_l3: "Încet", t6_r3: "Mut",
    t7_title: "Video", t7_text: "Putem viziona filme și videoclipuri pe calculator.", t7_inst: "Potrivește perechile:", t7_h1: "Imagini în mișcare.", t7_h2: "Începe filmul!", t7_q: "Ce este un video?", t7_qa: "Un filmuleț", t7_qb: "O piatră", t7_qc: "Pâine", t7_qd: "Un pantof",
    t7_l1: "Video", t7_r1: "Film", t7_l2: "Start", t7_r2: "Play", t7_l3: "Pauză", t7_r3: "Așteaptă",
    t8_title: "Tipărire", t8_text: "Imprimanta pune desenele noastre pe hârtie reală.", t8_inst: "Potrivește perechile:", t8_h1: "Hârtie și cerneală.", t8_h2: "Tipărire.", t8_q: "Ce face imprimanta?", t8_qa: "Imagini pe hârtie", t8_qb: "Gătește", t8_qc: "Spală haine", t8_qd: "Conduce mașina",
    t8_l1: "Imprimantă", t8_r1: "Hârtie", t8_l2: "Culoare", t8_r2: "Cerneală", t8_l3: "Gata", t8_r3: "Foaie",
    t9_title: "Scanner", t9_text: "Un scanner citește imaginile și le trimite în calculator.", t9_inst: "Potrivește perechile:", t9_h1: "Citire imagini.", t9_h2: "Devine digital.", t9_q: "Ce face un scanner?", t9_qa: "Citește imagini", t9_qb: "Face găuri", t9_qc: "Cântă", t9_qd: "Dansează",
    t9_l1: "Scanner", t9_r1: "Citire", t9_l2: "Foto", t9_r2: "Copie", t9_l3: "Lumină", t9_r3: "Scanare",
    t10_title: "Wi-Fi", t10_text: "Wi-Fi conectează calculatorul la internet fără cabluri.", t10_inst: "Potrivește perechile:", t10_h1: "Fără cabluri.", t10_h2: "Internet.", t10_q: "Ce este Wi-Fi?", t10_qa: "Internet fără fir", t10_qb: "Un animal", t10_qc: "O jucărie", t10_qd: "Un măr",
    t10_l1: "Wi-Fi", t10_r1: "Radio", t10_l2: "Internet", t10_r2: "Rețea", t10_l3: "Unde", t10_r3: "Semnal",
    t11_title: "Actualizare", t11_text: "O actualizare face calculatorul mai bun și mai sigur.", t11_inst: "Potrivește perechile:", t11_h1: "Înnoire.", t11_h2: "Devine mai bun.", t11_q: "Ce face o actualizare?", t11_qa: "Înnoiește programele", t11_qb: "Șterge tot", t11_qc: "Strică tot", t11_qd: "Doarme",
    t11_l1: "Update", t11_r1: "Nou", t11_l2: "Așteaptă", t11_r2: "Încarcă", t11_l3: "Gata", t11_r3: "Mai bun",
    t12_title: "Ajutor la erori", t12_text: "Dacă ceva nu merge, cere ajutorul unui adult.", t12_inst: "Potrivește perechile:", t12_h1: "Nu te îngrijora.", t12_h2: "Cere ajutor.", t12_q: "Ce faci dacă e o eroare?", t12_qa: "Cere ajutor", t12_qb: "Plângi", t12_qc: "Fugi", t12_qd: "Îl strici",
    t12_l1: "Eroare", t12_r1: "Problemă", t12_l2: "Ajutor", t12_r2: "Întreabă", t12_l3: "Soluție", t12_r3: "Bine",
    t13_title: "Repornire", t13_text: "Uneori ajută să repornești pur și simplu calculatorul.", t13_inst: "Potrivește perechile:", t13_h1: "Oprit și pornit.", t13_h2: "Început proaspăt.", t13_q: "Ce este o repornire?", t13_qa: "O ia de la capăt", t13_qb: "Șterge tot", t13_qc: "Îl arunci", t13_qd: "Mănânci",
    t13_l1: "Restart", t13_r1: "Reset", t13_l2: "Așteaptă", t13_r2: "Încarcă", t13_l3: "Start", t13_r3: "Început",
    t14_title: "Programe", t14_text: "Putem instala jocuri și programe noi pe calculator.", t14_inst: "Potrivește perechile:", t14_h1: "Jocuri noi.", t14_h2: "Instalare.", t14_q: "Ce este un program?", t14_qa: "O unealtă sau joc", t14_qb: "Un copac", t14_qc: "O piatră", t14_qd: "O pasăre",
    t14_l1: "Program", t14_r1: "App", t14_l2: "Instalare", t14_r2: "Adăugare", t14_l3: "Pictogramă", t14_r3: "Imagine",
    t15_title: "Maestru în informatică", t15_text: "Acum știi foarte multe despre calculator!", t15_inst: "Potrivește perechile:", t15_h1: "Ești grozav.", t15_h2: "Ai învățat tot.", t15_q: "Ce ești acum?", t15_qa: "Un Maestru", t15_qb: "O mașină", t15_qc: "Un copac", t15_qd: "O piatră",
    t15_l1: "Maestru", t15_r1: "Cunoștințe", t15_l2: "Calculator", t15_r2: "Pro", t15_l3: "Victorie", t15_r3: "Cupă"
  }
};

export const INFO_K1_I1_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["💻", "📺", "🖱️", "⌨️", "🔘", "🔊", "🎬", "🖨️", "📠", "📶", "🔄", "🆘", "🔁", "📦", "🏆"];
  const colors = ["#2196F3", "#4CAF50", "#FF9800", "#9C27B0", "#F44336", "#3F51B5", "#E91E63", "#795548", "#607D8B", "#00BCD4", "#8BC34A", "#FFC107", "#03A9F4", "#673AB7", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

