// @ts-nocheck
// lib/explorerPools/informatikaK8_i4.ts
import type { PoolTopicDef } from "./types";

export const INFO_K8_I4_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Internet & Netzwerke",
    t1_title: "TCP/IP-Protokoll", t1_text: "TCP/IP ist das grundlegende Protokoll des Internets. TCP stellt sicher, dass Datenpakete vollständig ankommen, IP kümmert sich um die Adressierung.",
    t1_inst: "Ordne die Protokollbegriffe zu.", t1_h1: "TCP = Übertragungssteuerung, IP = Adressierung", t1_h2: "IP-Adresse identifiziert jeden Computer im Netz",
    t1_l1: "TCP", t1_r1: "stellt vollständige Datenübertragung sicher", t1_l2: "IP", t1_r2: "Adressierung von Geräten im Netzwerk", t1_l3: "Datenpaket", t1_r3: "kleine Einheit der übertragenen Daten",
    t1_q: "Wofür ist TCP im TCP/IP-Protokoll zuständig?", t1_qa: "Für die vollständige und korrekte Datenübertragung", t1_qb: "Für die Adressierung der Geräte", t1_qc: "Für das Verschlüsseln der Daten", t1_qd: "Für die Anzeige von Webseiten",
    t2_title: "HTTP/HTTPS", t2_text: "HTTP (HyperText Transfer Protocol) überträgt Webseiten vom Server zum Browser. HTTPS ist die verschlüsselte Variante.",
    t2_inst: "Fülle die Lücke aus.", t2_h1: "HTTPS = HTTP + Verschlüsselung", t2_h2: "Das S steht für Secure (sicher)",
    t2_sent: "___ ist die verschlüsselte Version von HTTP.", t2_qa2: "HTTPS", t2_qb2: "FTP", t2_qc2: "DNS", t2_qd2: "SMTP",
    t2_q: "Was überträgt das HTTP-Protokoll?", t2_qa: "Webseiten vom Server zum Browser", t2_qb: "E-Mails zwischen Mailservern", t2_qc: "Dateien per FTP", t2_qd: "IP-Adressen",
    t3_title: "DNS (Domainnamensystem)", t3_text: "DNS wandelt Domainnamen (z. B. google.com) in IP-Adressen um. Es funktioniert wie ein Telefonbuch des Internets.",
    t3_inst: "Sortiere die Wörter in die richtige Reihenfolge.", t3_h1: "DNS wandelt Name → IP-Adresse um", t3_h2: "Ohne DNS müssten wir IP-Adressen eingeben",
    t3_w1: "DNS", t3_w2: "wandelt", t3_w3: "Domainnamen", t3_w4: "in IP-Adressen", t3_w5: "um.",
    t3_q: "Was ist die Hauptaufgabe des DNS?", t3_qa: "Domainnamen in IP-Adressen umwandeln", t3_qb: "Webseiten speichern", t3_qc: "E-Mails versenden", t3_qd: "Datenpakete verschlüsseln",
    t4_title: "FTP (Dateiübertragung)", t4_text: "FTP (File Transfer Protocol) dient zum Übertragen von Dateien zwischen Computern über ein Netzwerk. SFTP ist die sichere verschlüsselte Variante.",
    t4_inst: "Sortiere die Begriffe in die richtige Kategorie.", t4_h1: "FTP = Dateiübertragung, SMTP = E-Mail-Versand", t4_h2: "HTTP = Webseiten, DNS = Namensauflösung",
    t4_bl1: "Dateiübertragung", t4_bl2: "Webseiten / E-Mail", t4_i1: "FTP", t4_i2: "HTTP", t4_i3: "SFTP", t4_i4: "SMTP",
    t4_q: "Wozu dient das FTP-Protokoll?", t4_qa: "Zum Übertragen von Dateien zwischen Computern", t4_qb: "Zum Anzeigen von Webseiten", t4_qc: "Zum Versenden von E-Mails", t4_qd: "Zum Auflösen von Domainnamen",
    t5_title: "SMTP (E-Mail-Versand)", t5_text: "SMTP (Simple Mail Transfer Protocol) ist das Protokoll zum Versenden von E-Mails. POP3 und IMAP werden zum Empfangen verwendet.",
    t5_inst: "Markiere die Protokolle, die mit E-Mail zusammenhängen.", t5_h1: "SMTP = Senden, POP3/IMAP = Empfangen", t5_h2: "HTTP und FTP sind keine E-Mail-Protokolle",
    t5_tk1: "SMTP", t5_tk2: "HTTP", t5_tk3: "POP3", t5_tk4: "FTP", t5_tk5: "IMAP",
    t5_q: "Welches Protokoll wird zum Versenden von E-Mails verwendet?", t5_qa: "SMTP", t5_qb: "HTTP", t5_qc: "FTP", t5_qd: "DNS",
    t6_title: "Das Internet", t6_text: "Das Internet ist ein weltweites Netzwerk aus Computernetzwerken, das Daten über standardisierte Protokolle austauscht.",
    t6_inst: "Fülle die Lücke aus.", t6_sent: "Das Internet ist ein ___ von Netzwerken.", t6_qa6: "Netzwerk", t6_qb6: "Computer", t6_qc6: "Kabel", t6_qd6: "Programm",
    t6_q: "Was ist das Internet?", t6_qa: "Ein globales Computernetzwerk", t6_qb: "Eine Suchmaschine", t6_qc: "Ein Browser", t6_qd: "Ein Betriebssystem",
    t7_title: "Router", t7_text: "Ein Router leitet Datenpakete zwischen verschiedenen Netzwerken weiter und wählt den besten Weg.",
    t7_inst: "Verbinde die Geräte mit ihrer Funktion.",
    t7_l1: "Router", t7_r1: "Leitet Pakete weiter", t7_l2: "Modem", t7_r2: "Verbindet mit dem Internet", t7_l3: "Switch", t7_r3: "Verbindet lokale Geräte",
    t7_q: "Was ist die Hauptaufgabe eines Routers?", t7_qa: "Netzwerkverkehr leiten", t7_qb: "Viren abwehren", t7_qc: "Webseiten hosten", t7_qd: "Bildschirme steuern",
    t8_title: "Datenpakete", t8_text: "Daten werden in kleine Pakete zerlegt, um sie effizient über das Netzwerk zu senden. Jedes Paket hat einen Header (Kopf) und Payload (Nutzdaten).",
    t8_inst: "Sortiere:", t8_bl1: "Header", t8_bl2: "Payload", t8_i1: "Ziel-IP-Adresse", t8_i2: "Eigentliche Nachricht", t8_i3: "Quell-IP-Adresse", t8_i4: "Bilddaten",
    t8_q: "Warum werden Daten in Pakete zerlegt?", t8_qa: "Für effizientere und sicherere Übertragung", t8_qb: "Um Platz auf der Festplatte zu sparen", t8_qc: "Damit sie farbig werden", t8_qd: "Um den Computer zu verlangsamen",
    t9_title: "IPv4 vs IPv6", t9_text: "IPv4 nutzt 32-Bit-Adressen (z. B. 192.168.1.1). Weil diese knapp wurden, wurde IPv6 mit 128-Bit-Adressen entwickelt.",
    t9_inst: "Baue den Satz:", t9_f1: "IPv6", t9_f2: "bietet", t9_f3: "deutlich", t9_f4: "mehr Adressen.",
    t9_q: "Welcher Standard hat längere IP-Adressen?", t9_qa: "IPv6", t9_qb: "IPv4", t9_qc: "IPv2", t9_qd: "IPv8",
    t10_title: "MAC-Adresse", t10_text: "Eine MAC-Adresse ist eine Hardware-Adresse, die jeden Netzwerkadapter auf der Welt eindeutig identifiziert.",
    t10_inst: "Ordne:", t10_w1: "Die", t10_w2: "MAC-Adresse", t10_w3: "identifiziert", t10_w4: "die", t10_w5: "Netzwerkkarte.",
    t10_q: "Was identifiziert die MAC-Adresse?", t10_qa: "Die physische Hardware", t10_qb: "Den Standort im Internet", t10_qc: "Den Namen der Webseite", t10_qd: "Die Geschwindigkeit",
    t11_title: "Bandbreite", t11_text: "Bandbreite ist die maximale Datenmenge, die in einer bestimmten Zeit über eine Netzwerkverbindung übertragen werden kann (oft in Mbps).",
    t11_inst: "Markiere das Maß für Bandbreite:", t11_tk1: "Die Bandbreite", t11_tk2: "beträgt", t11_tk3: "100", t11_tk4: "Megabit", t11_tk5: "pro Sekunde.",
    t11_q: "Wie wird Bandbreite oft gemessen?", t11_qa: "In Megabit pro Sekunde (Mbps)", t11_qb: "In Kilogramm (kg)", t11_qc: "In Grad Celsius (°C)", t11_qd: "In Stunden (h)",
    t12_title: "Latenz (Ping)", t12_text: "Latenz ist die Zeitverzögerung, bis ein Datenpaket sein Ziel erreicht. Ein niedriger Ping ist gut für Online-Spiele.",
    t12_inst: "Fülle die Lücke:", t12_sent: "Ein niedriger ___ bedeutet schnelle Reaktionen.", t12_qa12: "Ping", t12_qb12: "Preis", t12_qc12: "Strom", t12_qd12: "Ton",
    t12_q: "Was ist besser für ein flüssiges Online-Spiel?", t12_qa: "Eine niedrige Latenz", t12_qb: "Eine hohe Latenz", t12_qc: "Kein Internet", t12_qd: "Viele Viren",
    t13_title: "WLAN (Wi-Fi)", t13_text: "WLAN (Wireless Local Area Network) verbindet Geräte drahtlos über Funkwellen mit einem lokalen Netzwerk.",
    t13_inst: "Verbinde:", t13_l1: "WLAN", t13_r1: "Drahtlos", t13_l2: "LAN-Kabel", t13_r2: "Verkabelt", t13_l3: "Funkwellen", t13_r3: "Signalübertragung",
    t13_q: "Wie überträgt WLAN Daten?", t13_qa: "Über Funkwellen", t13_qb: "Über dicke Kupferkabel", t13_qc: "Über Wasserleitungen", t13_qd: "Gar nicht",
    t14_title: "LAN vs WAN", t14_text: "Ein LAN (Local) ist ein kleines Netzwerk wie zu Hause. Ein WAN (Wide) ist ein riesiges Netzwerk, wie das Internet.",
    t14_inst: "Sortiere:", t14_bl1: "LAN", t14_bl2: "WAN", t14_i1: "Heimnetzwerk", t14_i2: "Das Internet", t14_i3: "Büro-Netzwerk", t14_i4: "Weltweites Netz",
    t14_q: "Was ist das größte WAN?", t14_qa: "Das Internet", t14_qb: "Das Heimnetzwerk", t14_qc: "Mein Smartphone", t14_qd: "Eine Festplatte",
    t15_title: "Firewall", t15_text: "Eine Firewall überwacht den Netzwerkverkehr und blockiert unerlaubte Zugriffe, um den Computer zu schützen.",
    t15_inst: "Ordne:", t15_w1: "Eine", t15_w2: "Firewall", t15_w3: "blockiert", t15_w4: "unerlaubte", t15_w5: "Zugriffe.",
    t15_q: "Welche Aufgabe hat eine Firewall?", t15_qa: "Unerwünschte Daten blockieren", t15_qb: "E-Mails schneller machen", t15_qc: "Den Bildschirm reinigen", t15_qd: "Das Internet löschen",
  },
  en: {
    explorer_title: "Internet & Networks",
    t1_title: "TCP/IP protocol", t1_text: "TCP/IP is the fundamental protocol of the internet. TCP ensures data packets arrive completely, IP handles addressing.",
    t1_inst: "Match the protocol terms.", t1_h1: "TCP = transmission control, IP = addressing", t1_h2: "IP address identifies every computer in the network",
    t1_l1: "TCP", t1_r1: "ensures complete data delivery", t1_l2: "IP", t1_r2: "addressing of devices in the network", t1_l3: "Data packet", t1_r3: "small unit of transmitted data",
    t1_q: "What is TCP responsible for in the TCP/IP protocol?", t1_qa: "For complete and correct data delivery", t1_qb: "For addressing the devices", t1_qc: "For encrypting the data", t1_qd: "For displaying web pages",
    t2_title: "HTTP/HTTPS", t2_text: "HTTP (HyperText Transfer Protocol) transfers web pages from server to browser. HTTPS is the encrypted version.",
    t2_inst: "Fill in the blank.", t2_h1: "HTTPS = HTTP + encryption", t2_h2: "The S stands for Secure",
    t2_sent: "___ is the encrypted version of HTTP.", t2_qa2: "HTTPS", t2_qb2: "FTP", t2_qc2: "DNS", t2_qd2: "SMTP",
    t2_q: "What does the HTTP protocol transfer?", t2_qa: "Web pages from server to browser", t2_qb: "Emails between mail servers", t2_qc: "Files via FTP", t2_qd: "IP addresses",
    t3_title: "DNS (Domain Name System)", t3_text: "DNS converts domain names (e.g. google.com) into IP addresses. It works like a phone book of the internet.",
    t3_inst: "Sort the words into the correct order.", t3_h1: "DNS converts name → IP address", t3_h2: "Without DNS we would have to type IP addresses",
    t3_w1: "DNS", t3_w2: "converts", t3_w3: "domain names", t3_w4: "into IP addresses", t3_w5: ".",
    t3_q: "What is the main task of DNS?", t3_qa: "Converting domain names into IP addresses", t3_qb: "Storing web pages", t3_qc: "Sending emails", t3_qd: "Encrypting data packets",
    t4_title: "FTP (File Transfer)", t4_text: "FTP (File Transfer Protocol) is used to transfer files between computers over a network. SFTP is the secure encrypted variant.",
    t4_inst: "Sort the terms into the correct category.", t4_h1: "FTP = file transfer, SMTP = email sending", t4_h2: "HTTP = web pages, DNS = name resolution",
    t4_bl1: "File transfer", t4_bl2: "Web / Email", t4_i1: "FTP", t4_i2: "HTTP", t4_i3: "SFTP", t4_i4: "SMTP",
    t4_q: "What is the FTP protocol used for?", t4_qa: "For transferring files between computers", t4_qb: "For displaying web pages", t4_qc: "For sending emails", t4_qd: "For resolving domain names",
    t5_title: "SMTP (Email sending)", t5_text: "SMTP (Simple Mail Transfer Protocol) is the protocol for sending emails. POP3 and IMAP are used for receiving.",
    t5_inst: "Highlight the protocols related to email.", t5_h1: "SMTP = sending, POP3/IMAP = receiving", t5_h2: "HTTP and FTP are not email protocols",
    t5_tk1: "SMTP", t5_tk2: "HTTP", t5_tk3: "POP3", t5_tk4: "FTP", t5_tk5: "IMAP",
    t5_q: "Which protocol is used for sending emails?", t5_qa: "SMTP", t5_qb: "HTTP", t5_qc: "FTP", t5_qd: "DNS",
    t6_title: "The Internet", t6_text: "The internet is a global network of computer networks that exchanges data using standardized protocols.",
    t6_inst: "Fill in the blank.", t6_sent: "The internet is a ___ of networks.", t6_qa6: "network", t6_qb6: "computer", t6_qc6: "cable", t6_qd6: "program",
    t6_q: "What is the internet?", t6_qa: "A global computer network", t6_qb: "A search engine", t6_qc: "A browser", t6_qd: "An operating system",
    t7_title: "Router", t7_text: "A router forwards data packets between different networks and chooses the best path.",
    t7_inst: "Match the devices with their function.",
    t7_l1: "Router", t7_r1: "Forwards packets", t7_l2: "Modem", t7_r2: "Connects to the internet", t7_l3: "Switch", t7_r3: "Connects local devices",
    t7_q: "What is the main task of a router?", t7_qa: "Directing network traffic", t7_qb: "Blocking viruses", t7_qc: "Hosting websites", t7_qd: "Controlling screens",
    t8_title: "Data Packets", t8_text: "Data is split into small packets to send them efficiently over the network. Each packet has a header and payload.",
    t8_inst: "Sort:", t8_bl1: "Header", t8_bl2: "Payload", t8_i1: "Destination IP", t8_i2: "Actual message", t8_i3: "Source IP", t8_i4: "Image data",
    t8_q: "Why is data split into packets?", t8_qa: "For more efficient and reliable transmission", t8_qb: "To save hard drive space", t8_qc: "To make them colorful", t8_qd: "To slow down the computer",
    t9_title: "IPv4 vs IPv6", t9_text: "IPv4 uses 32-bit addresses (e.g. 192.168.1.1). Because we ran out of them, IPv6 was developed with 128-bit addresses.",
    t9_inst: "Build the sentence:", t9_f1: "IPv6", t9_f2: "provides", t9_f3: "significantly", t9_f4: "more addresses.",
    t9_q: "Which standard has longer IP addresses?", t9_qa: "IPv6", t9_qb: "IPv4", t9_qc: "IPv2", t9_qd: "IPv8",
    t10_title: "MAC Address", t10_text: "A MAC address is a hardware address that uniquely identifies every network adapter in the world.",
    t10_inst: "Order:", t10_w1: "The", t10_w2: "MAC address", t10_w3: "identifies", t10_w4: "the", t10_w5: "network card.",
    t10_q: "What does the MAC address identify?", t10_qa: "The physical hardware", t10_qb: "The location on the internet", t10_qc: "The website name", t10_qd: "The speed",
    t11_title: "Bandwidth", t11_text: "Bandwidth is the maximum amount of data that can be transferred over a network connection in a given time (often in Mbps).",
    t11_inst: "Highlight the measure for bandwidth:", t11_tk1: "The bandwidth", t11_tk2: "is", t11_tk3: "100", t11_tk4: "Megabits", t11_tk5: "per second.",
    t11_q: "How is bandwidth often measured?", t11_qa: "In Megabits per second (Mbps)", t11_qb: "In Kilograms (kg)", t11_qc: "In Celsius (°C)", t11_qd: "In hours (h)",
    t12_title: "Latency (Ping)", t12_text: "Latency is the time delay for a data packet to reach its destination. A low ping is good for online gaming.",
    t12_inst: "Fill the gap:", t12_sent: "A low ___ means fast reactions.", t12_qa12: "ping", t12_qb12: "price", t12_qc12: "power", t12_qd12: "sound",
    t12_q: "What is better for smooth online gaming?", t12_qa: "A low latency", t12_qb: "A high latency", t12_qc: "No internet", t12_qd: "Many viruses",
    t13_title: "Wi-Fi (WLAN)", t13_text: "Wi-Fi (Wireless Local Area Network) connects devices wirelessly to a local network using radio waves.",
    t13_inst: "Match:", t13_l1: "Wi-Fi", t13_r1: "Wireless", t13_l2: "LAN Cable", t13_r2: "Wired", t13_l3: "Radio waves", t13_r3: "Signal transmission",
    t13_q: "How does Wi-Fi transmit data?", t13_qa: "Via radio waves", t13_qb: "Via thick copper cables", t13_qc: "Via water pipes", t13_qd: "Not at all",
    t14_title: "LAN vs WAN", t14_text: "A LAN (Local) is a small network like at home. A WAN (Wide) is a massive network, like the internet.",
    t14_inst: "Sort:", t14_bl1: "LAN", t14_bl2: "WAN", t14_i1: "Home network", t14_i2: "The Internet", t14_i3: "Office network", t14_i4: "Global web",
    t14_q: "What is the largest WAN?", t14_qa: "The Internet", t14_qb: "The home network", t14_qc: "My smartphone", t14_qd: "A hard drive",
    t15_title: "Firewall", t15_text: "A firewall monitors network traffic and blocks unauthorized access to protect the computer.",
    t15_inst: "Order:", t15_w1: "A", t15_w2: "firewall", t15_w3: "blocks", t15_w4: "unauthorized", t15_w5: "access.",
    t15_q: "What is the task of a firewall?", t15_qa: "To block unwanted data", t15_qb: "To make emails faster", t15_qc: "To clean the screen", t15_qd: "To delete the internet",
  },
  hu: {
    explorer_title: "Internet és Hálózatok",
    t1_title: "TCP/IP protokoll", t1_text: "A TCP/IP az internet alapprotokolljai. A TCP gondoskodik arról, hogy az adatcsomagok hiánytalanul megérkezzenek, az IP a címzést kezeli.",
    t1_inst: "Párosítsd a protokollfogalmakat.", t1_h1: "TCP = átvitelvezérlés, IP = címzés", t1_h2: "az IP-cím azonosítja a hálózat minden számítógépét",
    t1_l1: "TCP", t1_r1: "biztosítja a hiánytalan adatátvitelt", t1_l2: "IP", t1_r2: "eszközök hálózati címzése", t1_l3: "Adatcsomag", t1_r3: "az átvitt adatok kis egysége",
    t1_q: "Miért felelős a TCP a TCP/IP protokollban?", t1_qa: "A hiánytalan és helyes adatátvitelért", t1_qb: "Az eszközök címzéséért", t1_qc: "Az adatok titkosításáért", t1_qd: "A weboldalak megjelenítéséért",
    t2_title: "HTTP/HTTPS", t2_text: "A HTTP (HyperText Transfer Protocol) weboldalakat továbbít a szerverről a böngészőbe. A HTTPS a titkosított változat.",
    t2_inst: "Töltsd ki a hiányzó részt.", t2_h1: "HTTPS = HTTP + titkosítás", t2_h2: "az S a Secure-t jelenti",
    t2_sent: "A ___ a HTTP titkosított változata.", t2_qa2: "HTTPS", t2_qb2: "FTP", t2_qc2: "DNS", t2_qd2: "SMTP",
    t2_q: "Mit továbbít a HTTP protokoll?", t2_qa: "Weboldalakat a szerverről a böngészőbe", t2_qb: "E-maileket levelezőszerverek között", t2_qc: "Fájlokat FTP-n keresztül", t2_qd: "IP-címeket",
    t3_title: "DNS (tartománynévrendszer)", t3_text: "A DNS a tartományneveket (pl. google.com) IP-címekké alakítja. Az internet telefonkönyveként működik.",
    t3_inst: "Rendezd a szavakat helyes sorrendbe.", t3_h1: "a DNS nevet → IP-címmé alakít", t3_h2: "DNS nélkül IP-címeket kellene begépelni",
    t3_w1: "A DNS", t3_w2: "a domainnevet", t3_w3: "IP-címmé", t3_w4: "alakítja", t3_w5: "át.",
    t3_q: "Mi a DNS fő feladata?", t3_qa: "Tartománynevek IP-címekké alakítása", t3_qb: "Weboldalak tárolása", t3_qc: "E-mailek küldése", t3_qd: "Adatcsomagok titkosítása",
    t4_title: "FTP (fájlátvitel)", t4_text: "Az FTP (File Transfer Protocol) fájlok átvitelére szolgál számítógépek között hálózaton keresztül. Az SFTP a biztonságos, titkosított változat.",
    t4_inst: "Rendezd a fogalmakat a megfelelő kategóriába.", t4_h1: "FTP = fájlátvitel, SMTP = e-mail küldés", t4_h2: "HTTP = weboldalak, DNS = névfeloldás",
    t4_bl1: "Fájlátvitel", t4_bl2: "Web / E-mail", t4_i1: "FTP", t4_i2: "HTTP", t4_i3: "SFTP", t4_i4: "SMTP",
    t4_q: "Mire szolgál az FTP protokoll?", t4_qa: "Fájlok átvitelére számítógépek között", t4_qb: "Weboldalak megjelenítésére", t4_qc: "E-mailek küldésére", t4_qd: "Tartománynevek feloldására",
    t5_title: "SMTP (e-mail küldés)", t5_text: "Az SMTP (Simple Mail Transfer Protocol) az e-mailek küldésére szolgáló protokoll. A POP3 és az IMAP a fogadásra szolgál.",
    t5_inst: "Emeld ki az e-mailhez kapcsolódó protokollokat.", t5_h1: "SMTP = küldés, POP3/IMAP = fogadás", t5_h2: "a HTTP és FTP nem e-mail protokollok",
    t5_tk1: "SMTP", t5_tk2: "HTTP", t5_tk3: "POP3", t5_tk4: "FTP", t5_tk5: "IMAP",
    t5_q: "Melyik protokollt használják az e-mailek küldésére?", t5_qa: "SMTP", t5_qb: "HTTP", t5_qc: "FTP", t5_qd: "DNS",
    t6_title: "Az Internet", t6_text: "Az internet számítógép-hálózatok globális hálózata, amely szabványosított protokollokon keresztül cserél adatokat.",
    t6_inst: "Töltsd ki a hiányzó részt.", t6_sent: "Az internet a hálózatok ___.", t6_qa6: "hálózata", t6_qb6: "számítógépe", t6_qc6: "kábele", t6_qd6: "programja",
    t6_q: "Mi az internet?", t6_qa: "Egy globális számítógép-hálózat", t6_qb: "Egy keresőmotor", t6_qc: "Egy böngésző", t6_qd: "Egy operációs rendszer",
    t7_title: "Router", t7_text: "A router adatcsomagokat továbbít különböző hálózatok között, és kiválasztja a legjobb útvonalat.",
    t7_inst: "Párosítsd az eszközöket a funkciójukkal.",
    t7_l1: "Router", t7_r1: "Csomagokat továbbít", t7_l2: "Modem", t7_r2: "Csatlakoztat az internethez", t7_l3: "Switch", t7_r3: "Helyi eszközöket köt össze",
    t7_q: "Mi a router fő feladata?", t7_qa: "Hálózati forgalom irányítása", t7_qb: "Vírusok kivédése", t7_qc: "Weboldalak tárolása", t7_qd: "Képernyők vezérlése",
    t8_title: "Adatcsomagok", t8_text: "Az adatokat kis csomagokra bontják, hogy hatékonyan küldhessék át a hálózaton. Minden csomagnak van fejléce (header) és hasznos terhe (payload).",
    t8_inst: "Válogasd szét:", t8_bl1: "Fejléc", t8_bl2: "Hasznos teher", t8_i1: "Cél IP-címe", t8_i2: "Tényleges üzenet", t8_i3: "Forrás IP-címe", t8_i4: "Képadatok",
    t8_q: "Miért bontják az adatokat csomagokra?", t8_qa: "A hatékonyabb és megbízhatóbb átvitelért", t8_qb: "Hogy helyet spóroljanak a merevlemezen", t8_qc: "Hogy színesek legyenek", t8_qd: "Hogy lelassítsák a gépet",
    t9_title: "IPv4 és IPv6", t9_text: "Az IPv4 32 bites címeket használ (pl. 192.168.1.1). Mivel ezek elfogytak, kifejlesztették az IPv6-ot 128 bites címekkel.",
    t9_inst: "Építs mondatot:", t9_f1: "Az IPv6", t9_f2: "sokkal", t9_f3: "több címet", t9_f4: "biztosít.",
    t9_q: "Melyik szabványnak vannak hosszabb IP-címei?", t9_qa: "IPv6", t9_qb: "IPv4", t9_qc: "IPv2", t9_qd: "IPv8",
    t10_title: "MAC-cím", t10_text: "A MAC-cím egy hardvercím, amely egyedileg azonosít minden hálózati adaptert a világon.",
    t10_inst: "Rendezd:", t10_w1: "A", t10_w2: "MAC-cím", t10_w3: "azonosítja", t10_w4: "a", t10_w5: "hálózati kártyát.",
    t10_q: "Mit azonosít a MAC-cím?", t10_qa: "A fizikai hardvert", t10_qb: "Az internetes tartózkodási helyet", t10_qc: "A weboldal nevét", t10_qd: "A sebességet",
    t11_title: "Sávszélesség", t11_text: "A sávszélesség a maximális adatmennyiség, amely egy hálózati kapcsolaton keresztül adott idő alatt átvihető (gyakran Mbps).",
    t11_inst: "Jelöld a sávszélesség mértékegységét:", t11_tk1: "A sávszélesség", t11_tk2: "értéke", t11_tk3: "100", t11_tk4: "Megabit", t11_tk5: "másodpercenként.",
    t11_q: "Miben mérik gyakran a sávszélességet?", t11_qa: "Megabit per másodpercben (Mbps)", t11_qb: "Kilogrammban (kg)", t11_qc: "Celsius fokban (°C)", t11_qd: "Órában (h)",
    t12_title: "Késleltetés (Ping)", t12_text: "A késleltetés az az idő, ami alatt egy adatcsomag eléri a célját. Az alacsony ping jó az online játékokhoz.",
    t12_inst: "Pótold:", t12_sent: "Az alacsony ___ gyors reakciókat jelent.", t12_qa12: "ping", t12_qb12: "ár", t12_qc12: "áram", t12_qd12: "hang",
    t12_q: "Mi a jobb a folyamatos online játékhoz?", t12_qa: "Az alacsony késleltetés", t12_qb: "A magas késleltetés", t12_qc: "Ha nincs internet", t12_qd: "A sok vírus",
    t13_title: "WLAN (Wi-Fi)", t13_text: "A WLAN (Vezeték nélküli helyi hálózat) rádióhullámokon keresztül, vezeték nélkül köti össze az eszközöket.",
    t13_inst: "Párosítsd:", t13_l1: "Wi-Fi", t13_r1: "Vezeték nélküli", t13_l2: "LAN kábel", t13_r2: "Vezetékes", t13_l3: "Rádióhullámok", t13_r3: "Jeltovábbítás",
    t13_q: "Hogyan továbbít adatokat a Wi-Fi?", t13_qa: "Rádióhullámokon keresztül", t13_qb: "Vastag rézkábeleken", t13_qc: "Vízcsöveken keresztül", t13_qd: "Sehogy",
    t14_title: "LAN és WAN", t14_text: "A LAN (Helyi) egy kis hálózat, mint például otthon. A WAN (Kiterjedt) egy hatalmas hálózat, mint az internet.",
    t14_inst: "Válogasd szét:", t14_bl1: "LAN", t14_bl2: "WAN", t14_i1: "Otthoni hálózat", t14_i2: "Az Internet", t14_i3: "Irodai hálózat", t14_i4: "Világháló",
    t14_q: "Mi a legnagyobb WAN?", t14_qa: "Az internet", t14_qb: "Az otthoni hálózat", t14_qc: "Az okostelefonom", t14_qd: "Egy merevlemez",
    t15_title: "Tűzfal", t15_text: "A tűzfal figyeli a hálózati forgalmat, és blokkolja a jogosulatlan hozzáféréseket, hogy megvédje a számítógépet.",
    t15_inst: "Rendezd:", t15_w1: "A", t15_w2: "tűzfal", t15_w3: "blokkolja", t15_w4: "a jogosulatlan", t15_w5: "hozzáférést.",
    t15_q: "Mi a tűzfal feladata?", t15_qa: "Nemkívánatos adatok blokkolása", t15_qb: "E-mailek gyorsítása", t15_qc: "A képernyő tisztítása", t15_qd: "Az internet törlése",
  },
  ro: {
    explorer_title: "Internet & Rețele",
    t1_title: "Protocolul TCP/IP", t1_text: "TCP/IP este protocolul fundamental al internetului. TCP asigură că pachetele de date ajung complet, IP se ocupă de adresare.",
    t1_inst: "Potrivește termenii de protocol.", t1_h1: "TCP = control transmisie, IP = adresare", t1_h2: "Adresa IP identifică fiecare computer din rețea",
    t1_l1: "TCP", t1_r1: "asigură livrarea completă a datelor", t1_l2: "IP", t1_r2: "adresarea dispozitivelor în rețea", t1_l3: "Pachet de date", t1_r3: "unitate mică de date transmise",
    t1_q: "De ce este responsabil TCP în protocolul TCP/IP?", t1_qa: "Pentru livrarea completă și corectă a datelor", t1_qb: "Pentru adresarea dispozitivelor", t1_qc: "Pentru criptarea datelor", t1_qd: "Pentru afișarea paginilor web",
    t2_title: "HTTP/HTTPS", t2_text: "HTTP (HyperText Transfer Protocol) transferă pagini web de la server la browser. HTTPS este varianta criptată.",
    t2_inst: "Completează spațiul liber.", t2_h1: "HTTPS = HTTP + criptare", t2_h2: "S înseamnă Secure",
    t2_sent: "___ este versiunea criptată a HTTP.", t2_qa2: "HTTPS", t2_qb2: "FTP", t2_qc2: "DNS", t2_qd2: "SMTP",
    t2_q: "Ce transferă protocolul HTTP?", t2_qa: "Pagini web de la server la browser", t2_qb: "Emailuri între servere de mail", t2_qc: "Fișiere prin FTP", t2_qd: "Adrese IP",
    t3_title: "DNS (Domain Name System)", t3_text: "DNS convertește numele de domeniu (ex. google.com) în adrese IP. Funcționează ca o carte de telefon a internetului.",
    t3_inst: "Sortează cuvintele în ordinea corectă.", t3_h1: "DNS convertește nume → adresă IP", t3_h2: "Fără DNS ar trebui să introducem adrese IP",
    t3_w1: "DNS", t3_w2: "convertește", t3_w3: "numele de domeniu", t3_w4: "în adrese IP", t3_w5: ".",
    t3_q: "Care este sarcina principală a DNS?", t3_qa: "Convertirea numelor de domeniu în adrese IP", t3_qb: "Stocarea paginilor web", t3_qc: "Trimiterea emailurilor", t3_qd: "Criptarea pachetelor de date",
    t4_title: "FTP (transfer fișiere)", t4_text: "FTP (File Transfer Protocol) este folosit pentru a transfera fișiere între computere printr-o rețea. SFTP este varianta securizată criptată.",
    t4_inst: "Sortează termenii în categoria corectă.", t4_h1: "FTP = transfer fișiere, SMTP = trimitere email", t4_h2: "HTTP = pagini web, DNS = rezoluție nume",
    t4_bl1: "Transfer fișiere", t4_bl2: "Web / Email", t4_i1: "FTP", t4_i2: "HTTP", t4_i3: "SFTP", t4_i4: "SMTP",
    t4_q: "La ce servește protocolul FTP?", t4_qa: "Pentru transferul fișierelor între computere", t4_qb: "Pentru afișarea paginilor web", t4_qc: "Pentru trimiterea emailurilor", t4_qd: "Pentru rezolvarea numelor de domeniu",
    t5_title: "SMTP (trimitere email)", t5_text: "SMTP (Simple Mail Transfer Protocol) este protocolul pentru trimiterea emailurilor. POP3 și IMAP sunt folosite pentru primire.",
    t5_inst: "Evidențiază protocoalele legate de email.", t5_h1: "SMTP = trimitere, POP3/IMAP = primire", t5_h2: "HTTP și FTP nu sunt protocoale de email",
    t5_tk1: "SMTP", t5_tk2: "HTTP", t5_tk3: "POP3", t5_tk4: "FTP", t5_tk5: "IMAP",
    t5_q: "Ce protocol este folosit pentru trimiterea emailurilor?", t5_qa: "SMTP", t5_qb: "HTTP", t5_qc: "FTP", t5_qd: "DNS",
    t6_title: "Internetul", t6_text: "Internetul este o rețea globală de rețele de computere care face schimb de date folosind protocoale standardizate.",
    t6_inst: "Completează spațiul liber.", t6_sent: "Internetul este o ___ de rețele.", t6_qa6: "rețea", t6_qb6: "computer", t6_qc6: "cablu", t6_qd6: "program",
    t6_q: "Ce este internetul?", t6_qa: "O rețea globală de computere", t6_qb: "Un motor de căutare", t6_qc: "Un browser", t6_qd: "Un sistem de operare",
    t7_title: "Router", t7_text: "Un router redirecționează pachetele de date între diferite rețele și alege cea mai bună rută.",
    t7_inst: "Potrivește dispozitivele cu funcția lor.",
    t7_l1: "Router", t7_r1: "Redirecționează pachete", t7_l2: "Modem", t7_r2: "Se conectează la internet", t7_l3: "Switch", t7_r3: "Conectează dispozitive locale",
    t7_q: "Care este sarcina principală a unui router?", t7_qa: "Direcționarea traficului de rețea", t7_qb: "Blocarea virușilor", t7_qc: "Găzduirea site-urilor", t7_qd: "Controlul ecranelor",
    t8_title: "Pachete de Date", t8_text: "Datele sunt împărțite în pachete mici pentru a fi trimise eficient prin rețea. Fiecare pachet are un antet (header) și date utile (payload).",
    t8_inst: "Sortează:", t8_bl1: "Antet", t8_bl2: "Date utile", t8_i1: "IP destinație", t8_i2: "Mesajul real", t8_i3: "IP sursă", t8_i4: "Date imagine",
    t8_q: "De ce sunt datele împărțite în pachete?", t8_qa: "Pentru o transmisie mai eficientă și fiabilă", t8_qb: "Pentru a economisi spațiu pe disc", t8_qc: "Pentru a le face colorate", t8_qd: "Pentru a încetini computerul",
    t9_title: "IPv4 vs IPv6", t9_text: "IPv4 folosește adrese pe 32 de biți (ex. 192.168.1.1). Deoarece s-au epuizat, a fost dezvoltat IPv6 cu adrese pe 128 de biți.",
    t9_inst: "Construiește fraza:", t9_f1: "IPv6", t9_f2: "oferă", t9_f3: "semnificativ", t9_f4: "mai multe adrese.",
    t9_q: "Care standard are adrese IP mai lungi?", t9_qa: "IPv6", t9_qb: "IPv4", t9_qc: "IPv2", t9_qd: "IPv8",
    t10_title: "Adresa MAC", t10_text: "O adresă MAC este o adresă hardware care identifică unic fiecare adaptor de rețea din lume.",
    t10_inst: "Ordonează:", t10_w1: "Adresa", t10_w2: "MAC", t10_w3: "identifică", t10_w4: "placa de", t10_w5: "rețea.",
    t10_q: "Ce identifică adresa MAC?", t10_qa: "Hardware-ul fizic", t10_qb: "Locația pe internet", t10_qc: "Numele site-ului", t10_qd: "Viteza",
    t11_title: "Lățime de bandă", t11_text: "Lățimea de bandă este cantitatea maximă de date care poate fi transferată printr-o conexiune de rețea într-un timp dat (deseori în Mbps).",
    t11_inst: "Evidențiază unitatea pentru lățimea de bandă:", t11_tk1: "Lățimea de bandă", t11_tk2: "este de", t11_tk3: "100", t11_tk4: "Megabiți", t11_tk5: "pe secundă.",
    t11_q: "Cum se măsoară adesea lățimea de bandă?", t11_qa: "În Megabiți pe secundă (Mbps)", t11_qb: "În Kilograme (kg)", t11_qc: "În Celsius (°C)", t11_qd: "În ore (h)",
    t12_title: "Latență (Ping)", t12_text: "Latența este întârzierea până când un pachet de date ajunge la destinație. Un ping scăzut este bun pentru jocurile online.",
    t12_inst: "Completează:", t12_sent: "Un ___ scăzut înseamnă reacții rapide.", t12_qa12: "ping", t12_qb12: "preț", t12_qc12: "curent", t12_qd12: "sunet",
    t12_q: "Ce este mai bine pentru un joc online fluid?", t12_qa: "O latență scăzută", t12_qb: "O latență ridicată", t12_qc: "Fără internet", t12_qd: "Mulți viruși",
    t13_title: "Wi-Fi (WLAN)", t13_text: "Wi-Fi (Wireless Local Area Network) conectează dispozitivele wireless la o rețea locală folosind unde radio.",
    t13_inst: "Potrivește:", t13_l1: "Wi-Fi", t13_r1: "Fără fir", t13_l2: "Cablu LAN", t13_r2: "Cu fir", t13_l3: "Unde radio", t13_r3: "Transmisie semnal",
    t13_q: "Cum transmite Wi-Fi datele?", t13_qa: "Prin unde radio", t13_qb: "Prin cabluri groase de cupru", t13_qc: "Prin conducte de apă", t13_qd: "Deloc",
    t14_title: "LAN vs WAN", t14_text: "Un LAN (Local) este o rețea mică, cum ar fi acasă. Un WAN (Wide) este o rețea masivă, cum ar fi internetul.",
    t14_inst: "Sortează:", t14_bl1: "LAN", t14_bl2: "WAN", t14_i1: "Rețea de acasă", t14_i2: "Internetul", t14_i3: "Rețea de birou", t14_i4: "Rețea globală",
    t14_q: "Care este cel mai mare WAN?", t14_qa: "Internetul", t14_qb: "Rețeaua de acasă", t14_qc: "Smartphone-ul meu", t14_qd: "Un hard disk",
    t15_title: "Firewall", t15_text: "Un firewall monitorizează traficul de rețea și blochează accesul neautorizat pentru a proteja computerul.",
    t15_inst: "Ordonează:", t15_w1: "Un", t15_w2: "firewall", t15_w3: "blochează", t15_w4: "accesul", t15_w5: "neautorizat.",
    t15_q: "Care este sarcina unui firewall?", t15_qa: "Să blocheze datele nedorite", t15_qb: "Să facă emailurile mai rapide", t15_qc: "Să curețe ecranul", t15_qd: "Să șteargă internetul",
  },
};

export const INFO_K8_I4_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🌐", color: "#0D47A1" },
    interactive: { type: "match-pairs", instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2", pairs: [{ left: "t1_l1", right: "t1_r1" }, { left: "t1_l2", right: "t1_r2" }, { left: "t1_l3", right: "t1_r3" }] },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" }
  },
  {
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🔒", color: "#1B5E20" },
    interactive: { type: "gap-fill", instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2", sentence: "t2_sent", choices: ["t2_qa2", "t2_qb2", "t2_qc2", "t2_qd2"], correctIndex: 0 },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" }
  },
  {
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "📖", color: "#4A148C" },
    interactive: { type: "word-order", instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2", words: ["t3_w1", "t3_w2", "t3_w3", "t3_w4", "t3_w5"], correctOrder: [0, 1, 2, 3, 4] },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" }
  },
  {
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "📁", color: "#E65100" },
    interactive: { type: "drag-to-bucket", instruction: "t4_inst", hint1: "t4_h1", hint2: "t4_h2", buckets: [{ id: "file", label: "t4_bl1" }, { id: "web", label: "t4_bl2" }], items: [{ text: "t4_i1", bucketId: "file" }, { text: "t4_i2", bucketId: "web" }, { text: "t4_i3", bucketId: "file" }, { text: "t4_i4", bucketId: "web" }] },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" }
  },
  {
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "📧", color: "#880E4F" },
    interactive: { type: "highlight-text", instruction: "t5_inst", hint1: "t5_h1", hint2: "t5_h2", tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4", "t5_tk5"], correctIndices: [0, 2, 4] },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" }
  },
  {
    infoTitle: "t6_title", infoText: "t6_text",
    svg: { type: "simple-icon", icon: "🌍", color: "#1976D2" },
    interactive: { type: "gap-fill", instruction: "t6_inst", sentence: "t6_sent", choices: ["t6_qa6", "t6_qb6", "t6_qc6", "t6_qd6"], correctIndex: 0 },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qa" }
  },
  {
    infoTitle: "t7_title", infoText: "t7_text",
    svg: { type: "simple-icon", icon: "🖧", color: "#F57C00" },
    interactive: { type: "match-pairs", instruction: "t7_inst", pairs: [{ left: "t7_l1", right: "t7_r1" }, { left: "t7_l2", right: "t7_r2" }, { left: "t7_l3", right: "t7_r3" }] },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qa" }
  },
  {
    infoTitle: "t8_title", infoText: "t8_text",
    svg: { type: "simple-icon", icon: "📦", color: "#388E3C" },
    interactive: { type: "drag-to-bucket", instruction: "t8_inst", buckets: [{ id: "h", label: "t8_bl1" }, { id: "p", label: "t8_bl2" }], items: [{ text: "t8_i1", bucketId: "h" }, { text: "t8_i2", bucketId: "p" }, { text: "t8_i3", bucketId: "h" }, { text: "t8_i4", bucketId: "p" }] },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" }
  },
  {
    infoTitle: "t9_title", infoText: "t9_text",
    svg: { type: "word-display", word: "IPv6", color: "#7B1FA2" },
    interactive: { type: "sentence-build", instruction: "t9_inst", fragments: ["t9_f1", "t9_f2", "t9_f3", "t9_f4"] },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" }
  },
  {
    infoTitle: "t10_title", infoText: "t10_text",
    svg: { type: "simple-icon", icon: "🔖", color: "#D32F2F" },
    interactive: { type: "word-order", instruction: "t10_inst", words: ["t10_w1", "t10_w2", "t10_w3", "t10_w4", "t10_w5"], correctOrder: [0, 1, 2, 3, 4] },
    quiz: { question: "t10_q", choices: ["t10_qa", "t10_qb", "t10_qc", "t10_qd"], answer: "t10_qa" }
  },
  {
    infoTitle: "t11_title", infoText: "t11_text",
    svg: { type: "simple-icon", icon: "⚡", color: "#FBC02D" },
    interactive: { type: "highlight-text", instruction: "t11_inst", tokens: ["t11_tk1", "t11_tk2", "t11_tk3", "t11_tk4", "t11_tk5"], correctIndices: [3, 4] },
    quiz: { question: "t11_q", choices: ["t11_qa", "t11_qb", "t11_qc", "t11_qd"], answer: "t11_qa" }
  },
  {
    infoTitle: "t12_title", infoText: "t12_text",
    svg: { type: "simple-icon", icon: "⏱️", color: "#C2185B" },
    interactive: { type: "gap-fill", instruction: "t12_inst", sentence: "t12_sent", choices: ["t12_qa12", "t12_qb12", "t12_qc12", "t12_qd12"], correctIndex: 0 },
    quiz: { question: "t12_q", choices: ["t12_qa", "t12_qb", "t12_qc", "t12_qd"], answer: "t12_qa" }
  },
  {
    infoTitle: "t13_title", infoText: "t13_text",
    svg: { type: "simple-icon", icon: "📶", color: "#0097A7" },
    interactive: { type: "match-pairs", instruction: "t13_inst", pairs: [{ left: "t13_l1", right: "t13_r1" }, { left: "t13_l2", right: "t13_r2" }, { left: "t13_l3", right: "t13_r3" }] },
    quiz: { question: "t13_q", choices: ["t13_qa", "t13_qb", "t13_qc", "t13_qd"], answer: "t13_qa" }
  },
  {
    infoTitle: "t14_title", infoText: "t14_text",
    svg: { type: "simple-icon", icon: "🏙️", color: "#5D4037" },
    interactive: { type: "drag-to-bucket", instruction: "t14_inst", buckets: [{ id: "l", label: "t14_bl1" }, { id: "w", label: "t14_bl2" }], items: [{ text: "t14_i1", bucketId: "l" }, { text: "t14_i2", bucketId: "w" }, { text: "t14_i3", bucketId: "l" }, { text: "t14_i4", bucketId: "w" }] },
    quiz: { question: "t14_q", choices: ["t14_qa", "t14_qb", "t14_qc", "t14_qd"], answer: "t14_qa" }
  },
  {
    infoTitle: "t15_title", infoText: "t15_text",
    svg: { type: "simple-icon", icon: "🧱", color: "#E64A19" },
    interactive: { type: "word-order", instruction: "t15_inst", words: ["t15_w1", "t15_w2", "t15_w3", "t15_w4", "t15_w5"], correctOrder: [0, 1, 2, 3, 4] },
    quiz: { question: "t15_q", choices: ["t15_qa", "t15_qb", "t15_qc", "t15_qd"], answer: "t15_qa" }
  }
];

