// lib/explorerPools/informatikaK7_i9.ts
import type { PoolTopicDef } from "./types";

export const INFO_K7_I9_LABELS: Record<string, Record<string, string>> = {
  // Topic 1 – HTML
  t1_title: { de: "HTML (Webseiten-Struktur)", en: "HTML (web page structure)", hu: "HTML (weboldal-szerkezet)", ro: "HTML (structura paginii web)" },
  t1_text: { de: "HTML (HyperText Markup Language) beschreibt die Struktur einer Webseite mit Tags wie <h1>, <p> oder <a>.", en: "HTML (HyperText Markup Language) describes the structure of a web page with tags like <h1>, <p> or <a>.", hu: "A HTML (HyperText Markup Language) egy weboldal szerkezetét írja le olyan tagekkel, mint a h1, p vagy a.", ro: "HTML (HyperText Markup Language) descrie structura unei pagini web cu etichete ca h1, p sau a." },
  t1_inst: { de: "Ordne die HTML-Begriffe zu.", en: "Match the HTML terms.", hu: "Párosítsd a HTML fogalmakat.", ro: "Potrivește termenii HTML." },
  t1_h1: { de: "Tags stehen in spitzen Klammern", en: "Tags are in angle brackets", hu: "a tagek csúcsos zárójelben vannak", ro: "Tagurile sunt între paranteze unghiulare" },
  t1_h2: { de: "Jedes öffnende Tag hat ein schließendes Tag", en: "Every opening tag has a closing tag", hu: "minden nyitó tagnek van záró tagje", ro: "Fiecare tag de deschidere are un tag de închidere" },
  t1_l1: { de: "h1", en: "h1", hu: "h1", ro: "h1" },
  t1_r1: { de: "Hauptüberschrift", en: "main heading", hu: "főcím", ro: "titlu principal" },
  t1_l2: { de: "p", en: "p", hu: "p", ro: "p" },
  t1_r2: { de: "Absatz / Textblock", en: "paragraph / text block", hu: "bekezdés / szövegblokk", ro: "paragraf / bloc de text" },
  t1_l3: { de: "a href", en: "a href", hu: "a href", ro: "a href" },
  t1_r3: { de: "Hyperlink zu einer URL", en: "hyperlink to a URL", hu: "hiperhivatkozás egy URL-re", ro: "hyperlink către un URL" },
  t1_q: { de: "Wofür steht die Abkürzung HTML?", en: "What does HTML stand for?", hu: "Mit jelent a HTML rövidítés?", ro: "Ce înseamnă abrevierea HTML?" },
  t1_qa: { de: "HyperText Markup Language", en: "HyperText Markup Language", hu: "HyperText Markup Language", ro: "HyperText Markup Language" },
  t1_qb: { de: "High Transfer Machine Language", en: "High Transfer Machine Language", hu: "High Transfer Machine Language", ro: "High Transfer Machine Language" },
  t1_qc: { de: "Hyper Tool Making Loop", en: "Hyper Tool Making Loop", hu: "Hyper Tool Making Loop", ro: "Hyper Tool Making Loop" },
  t1_qd: { de: "Home Text Markup Layout", en: "Home Text Markup Layout", hu: "Home Text Markup Layout", ro: "Home Text Markup Layout" },

  // Topic 2 – CSS
  t2_title: { de: "CSS (Gestaltung)", en: "CSS (Styling)", hu: "CSS (megjelenés)", ro: "CSS (stilizare)" },
  t2_text: { de: "CSS (Cascading Style Sheets) legt das Aussehen von HTML-Elementen fest: Farbe, Schriftgröße, Abstände usw.", en: "CSS (Cascading Style Sheets) defines the appearance of HTML elements: color, font size, spacing, etc.", hu: "A CSS (Cascading Style Sheets) határozza meg a HTML-elemek megjelenését: szín, betűméret, margó stb.", ro: "CSS (Cascading Style Sheets) definește aspectul elementelor HTML: culoare, dimensiune font, spațiere etc." },
  t2_inst: { de: "Fülle die Lücke aus.", en: "Fill in the blank.", hu: "Töltsd ki a hiányzó részt.", ro: "Completează spațiul liber." },
  t2_h1: { de: "color setzt die Textfarbe", en: "color sets the text color", hu: "a color tulajdonság adja meg a szöveg színét", ro: "color setează culoarea textului" },
  t2_h2: { de: "CSS-Eigenschaft: Wert;", en: "CSS property: value;", hu: "CSS tulajdonság: érték;", ro: "proprietate CSS: valoare;" },
  t2_sent: { de: "p { ___: red; } macht den Absatztext rot.", en: "p { ___: red; } makes the paragraph text red.", hu: "p { ___: red; } pirossá teszi a bekezdés szövegét.", ro: "p { ___: red; } face textul paragrafului roșu." },
  t2_qa2: { de: "color", en: "color", hu: "color", ro: "color" },
  t2_qb2: { de: "font", en: "font", hu: "font", ro: "font" },
  t2_qc2: { de: "background", en: "background", hu: "background", ro: "background" },
  t2_qd2: { de: "border", en: "border", hu: "border", ro: "border" },
  t2_q: { de: "Wofür wird CSS in der Webentwicklung verwendet?", en: "What is CSS used for in web development?", hu: "Mire használják a CSS-t a webfejlesztésben?", ro: "La ce este folosit CSS în dezvoltarea web?" },
  t2_qa: { de: "Zum Gestalten des Aussehens von HTML-Elementen", en: "To style the appearance of HTML elements", hu: "A HTML-elemek megjelenésének formázásához", ro: "Pentru stilizarea aspectului elementelor HTML" },
  t2_qb: { de: "Zum Speichern von Benutzerdaten", en: "To store user data", hu: "Felhasználói adatok tárolásához", ro: "Pentru stocarea datelor utilizatorilor" },
  t2_qc: { de: "Zum Abfragen von Datenbanken", en: "To query databases", hu: "Adatbázisok lekérdezéséhez", ro: "Pentru interogarea bazelor de date" },
  t2_qd: { de: "Zum Erstellen von Algorithmen", en: "To create algorithms", hu: "Algoritmusok létrehozásához", ro: "Pentru crearea algoritmilor" },

  // Topic 3 – JavaScript
  t3_title: { de: "JavaScript (Interaktivität)", en: "JavaScript (Interactivity)", hu: "JavaScript (interaktivitás)", ro: "JavaScript (interactivitate)" },
  t3_text: { de: "JavaScript macht Webseiten interaktiv. Es kann auf Klicks reagieren, Inhalte ändern oder Berechnungen ausführen.", en: "JavaScript makes web pages interactive. It can react to clicks, change content, or run calculations.", hu: "A JavaScript interaktívvá teszi a weboldalakat. Reagálhat kattintásokra, módosíthatja a tartalmat vagy számításokat végezhet.", ro: "JavaScript face paginile web interactive. Poate reacționa la clicuri, schimba conținutul sau efectua calcule." },
  t3_inst: { de: "Sortiere die Wörter in die richtige Reihenfolge.", en: "Sort the words into the correct order.", hu: "Rendezd a szavakat helyes sorrendbe.", ro: "Sortează cuvintele în ordinea corectă." },
  t3_h1: { de: "alert() zeigt ein Popup-Fenster", en: "alert() shows a popup window", hu: "az alert() egy felugró ablakot jelenít meg", ro: "alert() afișează o fereastră popup" },
  t3_h2: { de: "document.getElementById() wählt ein HTML-Element", en: "document.getElementById() selects an HTML element", hu: "a document.getElementById() egy HTML-elemet választ ki", ro: "document.getElementById() selectează un element HTML" },
  t3_w1: { de: "document", en: "document", hu: "document", ro: "document" },
  t3_w2: { de: ".getElementById(", en: ".getElementById(", hu: ".getElementById(", ro: ".getElementById(" },
  t3_w3: { de: "'cim'", en: "'title'", hu: "'cim'", ro: "'titlu'" },
  t3_w4: { de: ")", en: ")", hu: ")", ro: ")" },
  t3_w5: { de: ".innerHTML = 'Hallo!'", en: ".innerHTML = 'Hello!'", hu: ".innerHTML = 'Szia!'", ro: ".innerHTML = 'Bună!'" },
  t3_q: { de: "Was ist die Hauptaufgabe von JavaScript auf einer Webseite?", en: "What is the main purpose of JavaScript on a web page?", hu: "Mi a JavaScript fő feladata egy weboldalon?", ro: "Care este scopul principal al JavaScript pe o pagină web?" },
  t3_qa: { de: "Interaktivität und dynamische Inhalte", en: "Interactivity and dynamic content", hu: "Interaktivitás és dinamikus tartalom", ro: "Interactivitate și conținut dinamic" },
  t3_qb: { de: "Die Struktur der Seite definieren", en: "Define the structure of the page", hu: "Az oldal szerkezetének meghatározása", ro: "Definirea structurii paginii" },
  t3_qc: { de: "Das Aussehen der Seite festlegen", en: "Set the appearance of the page", hu: "Az oldal megjelenésének meghatározása", ro: "Stabilirea aspectului paginii" },
  t3_qd: { de: "Daten in einer Datenbank speichern", en: "Store data in a database", hu: "Adatok tárolása adatbázisban", ro: "Stocarea datelor într-o bază de date" },

  // Topic 4 – DOM
  t4_title: { de: "DOM (Document Object Model)", en: "DOM (Document Object Model)", hu: "DOM (Document Object Model)", ro: "DOM (Document Object Model)" },
  t4_text: { de: "Das DOM ist die Baumstruktur, die der Browser aus dem HTML erstellt. JavaScript kann über das DOM Elemente lesen und ändern.", en: "The DOM is the tree structure the browser creates from HTML. JavaScript can read and change elements via the DOM.", hu: "A DOM az a fastruktúra, amelyet a böngésző a HTML-ből hoz létre. A JavaScript a DOM-on keresztül olvashatja és módosíthatja az elemeket.", ro: "DOM-ul este structura de arbore pe care browserul o creează din HTML. JavaScript poate citi și modifica elemente prin DOM." },
  t4_inst: { de: "Sortiere die Begriffe in die richtige Kategorie.", en: "Sort the terms into the correct category.", hu: "Rendezd a fogalmakat a megfelelő kategóriába.", ro: "Sortează termenii în categoria corectă." },
  t4_h1: { de: "HTML = Struktur, CSS = Stil, JS = Verhalten", en: "HTML = structure, CSS = style, JS = behavior", hu: "HTML = szerkezet, CSS = stílus, JS = viselkedés", ro: "HTML = structură, CSS = stil, JS = comportament" },
  t4_h2: { de: "DOM ist die Brücke zwischen HTML und JS", en: "DOM is the bridge between HTML and JS", hu: "a DOM az összekötő kapocs HTML és JS között", ro: "DOM-ul este puntea dintre HTML și JS" },
  t4_bl1: { de: "HTML-Aufgabe", en: "HTML task", hu: "HTML feladata", ro: "Sarcina HTML" },
  t4_bl2: { de: "JavaScript-Aufgabe", en: "JavaScript task", hu: "JavaScript feladata", ro: "Sarcina JavaScript" },
  t4_i1: { de: "Seite strukturieren", en: "structure the page", hu: "az oldal felépítése", ro: "structurarea paginii" },
  t4_i2: { de: "auf Klick reagieren", en: "react to a click", hu: "kattintásra reagálás", ro: "reacționarea la clic" },
  t4_i3: { de: "Überschriften definieren", en: "define headings", hu: "fejlécek meghatározása", ro: "definirea titlurilor" },
  t4_i4: { de: "Text dynamisch ändern", en: "dynamically change text", hu: "szöveg dinamikus módosítása", ro: "modificarea dinamică a textului" },
  t4_q: { de: "Was ist das DOM?", en: "What is the DOM?", hu: "Mi a DOM?", ro: "Ce este DOM-ul?" },
  t4_qa: { de: "Die Baumstruktur des HTML-Dokuments im Browser", en: "The tree structure of the HTML document in the browser", hu: "A HTML-dokumentum fastruktúrája a böngészőben", ro: "Structura de arbore a documentului HTML în browser" },
  t4_qb: { de: "Ein Datenbankformat", en: "A database format", hu: "Egy adatbázis-formátum", ro: "Un format de baze de date" },
  t4_qc: { de: "Eine Programmiersprache", en: "A programming language", hu: "Egy programozási nyelv", ro: "Un limbaj de programare" },
  t4_qd: { de: "Ein Webserver-Protokoll", en: "A web server protocol", hu: "Egy webszerver-protokoll", ro: "Un protocol de server web" },

  // Topic 5 – Reszponzív design
  t5_title: { de: "Responsives Design", en: "Responsive design", hu: "Reszponzív design", ro: "Design responsiv" },
  t5_text: { de: "Responsives Design bedeutet, dass eine Webseite auf verschiedenen Bildschirmgrößen (Handy, Tablet, PC) gut aussieht.", en: "Responsive design means a web page looks good on different screen sizes (phone, tablet, PC).", hu: "A reszponzív design azt jelenti, hogy egy weboldal jól néz ki különböző képernyőméreteken (telefon, tablet, PC).", ro: "Design-ul responsiv înseamnă că o pagină web arată bine pe diferite dimensiuni de ecran (telefon, tabletă, PC)." },
  t5_inst: { de: "Markiere die Teile, die zu Responsivem Design gehören.", en: "Highlight the parts that belong to responsive design.", hu: "Emeld ki a reszponzív designhoz tartozó részeket.", ro: "Evidențiază părțile care aparțin design-ului responsiv." },
  t5_h1: { de: "Media Queries passen das Layout an", en: "Media queries adapt the layout", hu: "a media query-k igazítják az elrendezést", ro: "Interogările media adaptează aspectul" },
  t5_h2: { de: "Flexbox und Grid helfen bei flexiblen Layouts", en: "Flexbox and Grid help with flexible layouts", hu: "a Flexbox és Grid segíti a rugalmas elrendezést", ro: "Flexbox și Grid ajută la aspecte flexibile" },
  t5_tk1: { de: "@media (max-width: 600px)", en: "@media (max-width: 600px)", hu: "@media (max-width: 600px)", ro: "@media (max-width: 600px)" },
  t5_tk2: { de: "font-size: 24px;", en: "font-size: 24px;", hu: "font-size: 24px;", ro: "font-size: 24px;" },
  t5_tk3: { de: "display: flex;", en: "display: flex;", hu: "display: flex;", ro: "display: flex;" },
  t5_tk4: { de: "color: blue;", en: "color: blue;", hu: "color: blue;", ro: "color: blue;" },
  t5_tk5: { de: "viewport meta tag", en: "viewport meta tag", hu: "viewport meta tag", ro: "viewport meta tag" },
  t5_q: { de: "Was bedeutet responsives Webdesign?", en: "What does responsive web design mean?", hu: "Mit jelent a reszponzív webdesign?", ro: "Ce înseamnă design-ul web responsiv?" },
  t5_qa: { de: "Das Layout passt sich verschiedenen Bildschirmgrößen an", en: "The layout adapts to different screen sizes", hu: "Az elrendezés alkalmazkodik a különböző képernyőméretekhez", ro: "Aspectul se adaptează la diferite dimensiuni de ecran" },
  t5_qb: { de: "Die Webseite lädt sehr schnell", en: "The web page loads very quickly", hu: "A weboldal nagyon gyorsan tölt be", ro: "Pagina web se încarcă foarte repede" },
  t5_qc: { de: "Die Webseite hat viele Animationen", en: "The web page has many animations", hu: "A weboldal sok animációt tartalmaz", ro: "Pagina web are multe animații" },
  t5_qd: { de: "Die Webseite ist auf Englisch verfügbar", en: "The web page is available in English", hu: "A weboldal angolul érhető el", ro: "Pagina web este disponibilă în engleză" },
};

export const INFO_K7_I9_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🌐", color: "#E65100" },
    interactive: {
      type: "match-pairs",
      instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2",
      pairs: [
        { left: "t1_l1", right: "t1_r1" },
        { left: "t1_l2", right: "t1_r2" },
        { left: "t1_l3", right: "t1_r3" },
      ],
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🎨", color: "#1565C0" },
    interactive: {
      type: "gap-fill",
      instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2",
      sentence: "t2_sent",
      choices: ["t2_qa2", "t2_qb2", "t2_qc2", "t2_qd2"],
      correctIndex: 0,
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "⚡", color: "#F9A825" },
    interactive: {
      type: "word-order",
      instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2",
      words: ["t3_w1", "t3_w2", "t3_w3", "t3_w4", "t3_w5"],
      correctOrder: [0, 1, 2, 3, 4],
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🌲", color: "#558B2F" },
    interactive: {
      type: "drag-to-bucket",
      instruction: "t4_inst", hint1: "t4_h1", hint2: "t4_h2",
      buckets: [
        { id: "html", label: "t4_bl1" },
        { id: "js", label: "t4_bl2" },
      ],
      items: [
        { text: "t4_i1", bucketId: "html" },
        { text: "t4_i2", bucketId: "js" },
        { text: "t4_i3", bucketId: "html" },
        { text: "t4_i4", bucketId: "js" },
      ],
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "📱", color: "#6A1B9A" },
    interactive: {
      type: "highlight-text",
      instruction: "t5_inst", hint1: "t5_h1", hint2: "t5_h2",
      tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4", "t5_tk5"],
      correctIndices: [0, 2, 4],
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
];
