// lib/explorerPools/informatikaK8_i9.ts
import type { PoolTopicDef } from "./types";

export const INFO_K8_I9_LABELS: Record<string, Record<string, string>> = {
  // Topic 1 – Szoftverfejlesztő
  t1_title: { de: "Softwareentwickler", en: "Software developer", hu: "Szoftverfejlesztő", ro: "Dezvoltator software" },
  t1_text: { de: "Ein Softwareentwickler schreibt, testet und wartet Programme. Er nutzt Programmiersprachen wie Python, Java oder JavaScript.", en: "A software developer writes, tests and maintains programs. They use programming languages such as Python, Java or JavaScript.", hu: "A szoftverfejlesztő programokat ír, tesztel és karbantart. Python, Java vagy JavaScript programozási nyelveket használ.", ro: "Un dezvoltator software scrie, testează și întreține programe. Folosește limbaje de programare precum Python, Java sau JavaScript." },
  t1_inst: { de: "Ordne die IT-Berufe ihren Aufgaben zu.", en: "Match the IT careers to their tasks.", hu: "Párosítsd az IT-szakmákat a feladataikhoz.", ro: "Potrivește carierele IT cu sarcinile lor." },
  t1_h1: { de: "Entwickler schreibt Code, Analyst wertet Daten aus", en: "Developer writes code, analyst evaluates data", hu: "fejlesztő kódot ír, elemző adatokat értékel", ro: "Dezvoltatorul scrie cod, analistul evaluează date" },
  t1_h2: { de: "Jedes IT-Beruf hat eigene Spezialisierung", en: "Each IT career has its own specialization", hu: "minden IT-szakmának saját specializációja van", ro: "Fiecare carieră IT are propria specializare" },
  t1_l1: { de: "Softwareentwickler", en: "Software developer", hu: "Szoftverfejlesztő", ro: "Dezvoltator software" },
  t1_r1: { de: "schreibt und wartet Programme", en: "writes and maintains programs", hu: "programokat ír és karbantart", ro: "scrie și întrețin programe" },
  t1_l2: { de: "Datenanalyst", en: "Data analyst", hu: "Adatelemző", ro: "Analist de date" },
  t1_r2: { de: "wertet Daten aus und erstellt Berichte", en: "evaluates data and creates reports", hu: "adatokat értékel és jelentéseket készít", ro: "evaluează date și creează rapoarte" },
  t1_l3: { de: "Cybersecurity-Experte", en: "Cybersecurity expert", hu: "Kiberbiztonság-szakértő", ro: "Expert în securitate cibernetică" },
  t1_r3: { de: "schützt Systeme vor Cyberangriffen", en: "protects systems from cyberattacks", hu: "rendszereket véd kibertámadásoktól", ro: "protejează sistemele de atacuri cibernetice" },
  t1_q: { de: "Was macht ein Softwareentwickler hauptsächlich?", en: "What does a software developer mainly do?", hu: "Mit csinál főleg a szoftverfejlesztő?", ro: "Ce face în principal un dezvoltator software?" },
  t1_qa: { de: "Er schreibt, testet und wartet Programme", en: "They write, test and maintain programs", hu: "Programokat ír, tesztel és karbantart", ro: "Scrie, testează și întreține programe" },
  t1_qb: { de: "Er verwaltet Netzwerke", en: "They manage networks", hu: "Hálózatokat kezel", ro: "Gestionează rețele" },
  t1_qc: { de: "Er gestaltet Benutzeroberflächen", en: "They design user interfaces", hu: "Felhasználói felületeket tervez", ro: "Proiectează interfețe utilizator" },
  t1_qd: { de: "Er analysiert Daten", en: "They analyze data", hu: "Adatokat elemez", ro: "Analizează date" },

  // Topic 2 – Adatelemző
  t2_title: { de: "Datenanalyst", en: "Data analyst", hu: "Adatelemző", ro: "Analist de date" },
  t2_text: { de: "Ein Datenanalyst sammelt, bereinigt und analysiert große Datenmengen, um Erkenntnisse für Entscheidungen zu gewinnen. Er nutzt Tools wie Excel, SQL und Python.", en: "A data analyst collects, cleans and analyzes large amounts of data to gain insights for decisions. They use tools like Excel, SQL and Python.", hu: "Az adatelemző nagy mennyiségű adatot gyűjt, tisztít és elemez, hogy döntésekhez nyerjen ki felismeréseket. Excel, SQL és Python eszközöket használ.", ro: "Un analist de date colectează, curăță și analizează cantități mari de date pentru a obține informații pentru decizii. Folosește instrumente precum Excel, SQL și Python." },
  t2_inst: { de: "Fülle die Lücke aus.", en: "Fill in the blank.", hu: "Töltsd ki a hiányzó részt.", ro: "Completează spațiul liber." },
  t2_h1: { de: "Datenanalyst = Daten auswerten und visualisieren", en: "Data analyst = evaluate and visualize data", hu: "adatelemző = adatokat értékel és vizualizál", ro: "Analist de date = evaluează și vizualizează date" },
  t2_h2: { de: "SQL und Python sind typische Analysetools", en: "SQL and Python are typical analysis tools", hu: "az SQL és Python tipikus elemzőeszközök", ro: "SQL și Python sunt instrumente tipice de analiză" },
  t2_sent: { de: "Ein Datenanalyst verwendet häufig ___ , um Daten abzufragen.", en: "A data analyst often uses ___ to query data.", hu: "Az adatelemző gyakran ___ használ az adatok lekérdezéséhez.", ro: "Un analist de date folosește adesea ___ pentru a interoga date." },
  t2_qa2: { de: "SQL", en: "SQL", hu: "SQL-t", ro: "SQL" },
  t2_qb2: { de: "Photoshop", en: "Photoshop", hu: "Photoshopot", ro: "Photoshop" },
  t2_qc2: { de: "Word", en: "Word", hu: "Wordöt", ro: "Word" },
  t2_qd2: { de: "PowerPoint", en: "PowerPoint", hu: "PowerPointot", ro: "PowerPoint" },
  t2_q: { de: "Was ist die Hauptaufgabe eines Datenanalysten?", en: "What is the main task of a data analyst?", hu: "Mi az adatelemző fő feladata?", ro: "Care este sarcina principală a unui analist de date?" },
  t2_qa: { de: "Daten sammeln, bereinigen und analysieren", en: "Collecting, cleaning and analyzing data", hu: "Adatok gyűjtése, tisztítása és elemzése", ro: "Colectarea, curățarea și analizarea datelor" },
  t2_qb: { de: "Programme schreiben und testen", en: "Writing and testing programs", hu: "Programok írása és tesztelése", ro: "Scrierea și testarea programelor" },
  t2_qc: { de: "Netzwerke verwalten", en: "Managing networks", hu: "Hálózatok kezelése", ro: "Gestionarea rețelelor" },
  t2_qd: { de: "Webseiten gestalten", en: "Designing web pages", hu: "Weboldalak tervezése", ro: "Proiectarea paginilor web" },

  // Topic 3 – Kiberbiztonság-szakértő
  t3_title: { de: "Cybersecurity-Experte", en: "Cybersecurity expert", hu: "Kiberbiztonság-szakértő", ro: "Expert în securitate cibernetică" },
  t3_text: { de: "Ein Cybersecurity-Experte schützt Computersysteme und Netzwerke vor Angriffen und Datenverlust. Er analysiert Bedrohungen und entwickelt Sicherheitslösungen.", en: "A cybersecurity expert protects computer systems and networks from attacks and data loss. They analyze threats and develop security solutions.", hu: "A kiberbiztonság-szakértő számítógépes rendszereket és hálózatokat véd támadásoktól és adatvesztéstől. Fenyegetéseket elemez és biztonsági megoldásokat fejleszt.", ro: "Un expert în securitate cibernetică protejează sistemele informatice și rețelele de atacuri și pierderi de date. Analizează amenințările și dezvoltă soluții de securitate." },
  t3_inst: { de: "Sortiere die Wörter in die richtige Reihenfolge.", en: "Sort the words into the correct order.", hu: "Rendezd a szavakat helyes sorrendbe.", ro: "Sortează cuvintele în ordinea corectă." },
  t3_h1: { de: "Cybersecurity = Schutz vor digitalen Angriffen", en: "Cybersecurity = protection from digital attacks", hu: "kiberbiztonság = védelem a digitális támadásoktól", ro: "Securitate cibernetică = protecție față de atacuri digitale" },
  t3_h2: { de: "Penetrationstest = geplanter Angriff zur Sicherheitsprüfung", en: "Penetration test = planned attack to test security", hu: "penetrációs teszt = tervezett támadás a biztonság ellenőrzéséhez", ro: "Test de penetrare = atac planificat pentru verificarea securității" },
  t3_w1: { de: "Ein Cybersecurity-Experte", en: "A cybersecurity expert", hu: "A kiberbiztonság-szakértő", ro: "Un expert în securitate cibernetică" },
  t3_w2: { de: "schützt Systeme", en: "protects systems", hu: "rendszereket véd", ro: "protejează sistemele" },
  t3_w3: { de: "vor Cyberangriffen", en: "from cyberattacks", hu: "kibertámadásoktól", ro: "de atacuri cibernetice" },
  t3_w4: { de: "und analysiert", en: "and analyzes", hu: "és biztonsági", ro: "și analizează" },
  t3_w5: { de: "Sicherheitsbedrohungen.", en: "security threats.", hu: "fenyegetéseket elemez.", ro: "amenințările de securitate." },
  t3_q: { de: "Was schützt ein Cybersecurity-Experte?", en: "What does a cybersecurity expert protect?", hu: "Mit véd a kiberbiztonság-szakértő?", ro: "Ce protejează un expert în securitate cibernetică?" },
  t3_qa: { de: "Computersysteme und Netzwerke vor Angriffen", en: "Computer systems and networks from attacks", hu: "Számítógépes rendszereket és hálózatokat támadásoktól", ro: "Sisteme informatice și rețele de atacuri" },
  t3_qb: { de: "Daten in Excel-Tabellen", en: "Data in Excel tables", hu: "Adatokat Excel-táblázatokban", ro: "Date în tabele Excel" },
  t3_qc: { de: "Webseiten-Design", en: "Web page design", hu: "Weboldal-designt", ro: "Design de pagini web" },
  t3_qd: { de: "Serverräume vor Feuer", en: "Server rooms from fire", hu: "Szerverszobákat tűztől", ro: "Camere de servere de incendiu" },

  // Topic 4 – UX tervező
  t4_title: { de: "UX-Designer", en: "UX designer", hu: "UX tervező", ro: "Designer UX" },
  t4_text: { de: "Ein UX-Designer (User Experience) gestaltet Benutzeroberflächen so, dass sie einfach, intuitiv und angenehm zu bedienen sind.", en: "A UX designer creates user interfaces that are easy, intuitive and pleasant to use.", hu: "A UX-tervező (User Experience) olyan felhasználói felületeket tervez, amelyek egyszerűek, intuitívak és kellemesek.", ro: "Un designer UX (User Experience) creează interfețe utilizator care sunt simple, intuitive și plăcute de folosit." },
  t4_inst: { de: "Sortiere die Begriffe in die richtige Kategorie.", en: "Sort the terms into the correct category.", hu: "Rendezd a fogalmakat a megfelelő kategóriába.", ro: "Sortează termenii în categoria corectă." },
  t4_h1: { de: "UX = wie das Produkt sich anfühlt, UI = wie es aussieht", en: "UX = how the product feels, UI = how it looks", hu: "UX = hogyan érzi magát a felhasználó, UI = hogyan néz ki", ro: "UX = cum se simte produsul, UI = cum arată" },
  t4_h2: { de: "Gutes UX: einfach zu lernen, schnell zu bedienen", en: "Good UX: easy to learn, quick to use", hu: "jó UX: könnyen tanulható, gyorsan kezelhető", ro: "UX bun: ușor de învățat, rapid de utilizat" },
  t4_bl1: { de: "UX-Aufgaben", en: "UX tasks", hu: "UX feladatok", ro: "Sarcini UX" },
  t4_bl2: { de: "Entwickler-Aufgaben", en: "Developer tasks", hu: "Fejlesztői feladatok", ro: "Sarcini dezvoltator" },
  t4_i1: { de: "Benutzerfreundlichkeit testen", en: "testing usability", hu: "használhatóság tesztelése", ro: "testarea ușurinței de utilizare" },
  t4_i2: { de: "Code schreiben und debuggen", en: "writing and debugging code", hu: "kód írása és debuggolása", ro: "scrierea și depanarea codului" },
  t4_i3: { de: "Wireframes und Prototypen erstellen", en: "creating wireframes and prototypes", hu: "vázlatok és prototípusok készítése", ro: "crearea wireframe-urilor și prototipurilor" },
  t4_i4: { de: "Algorithmen implementieren", en: "implementing algorithms", hu: "algoritmusok implementálása", ro: "implementarea algoritmilor" },
  t4_q: { de: "Was ist die Hauptaufgabe eines UX-Designers?", en: "What is the main task of a UX designer?", hu: "Mi a UX-tervező fő feladata?", ro: "Care este sarcina principală a unui designer UX?" },
  t4_qa: { de: "Benutzeroberflächen intuitiv und angenehm zu gestalten", en: "Making user interfaces intuitive and pleasant", hu: "Intuitív és kellemes felhasználói felületek tervezése", ro: "Crearea interfețelor utilizator intuitive și plăcute" },
  t4_qb: { de: "Netzwerke zu verwalten", en: "Managing networks", hu: "Hálózatok kezelése", ro: "Gestionarea rețelelor" },
  t4_qc: { de: "Sicherheitslücken zu finden", en: "Finding security vulnerabilities", hu: "Biztonsági rések megtalálása", ro: "Găsirea vulnerabilităților de securitate" },
  t4_qd: { de: "Datenbanken zu verwalten", en: "Managing databases", hu: "Adatbázisok kezelése", ro: "Gestionarea bazelor de date" },

  // Topic 5 – IT sertifikátok
  t5_title: { de: "IT-Zertifikate", en: "IT certifications", hu: "IT-tanúsítványok", ro: "Certificări IT" },
  t5_text: { de: "IT-Zertifikate sind anerkannte Nachweise für bestimmte Kenntnisse und Fähigkeiten, z. B. CompTIA A+, Cisco CCNA oder Google Cloud-Zertifikate.", en: "IT certifications are recognized proofs of specific knowledge and skills, e.g. CompTIA A+, Cisco CCNA or Google Cloud certifications.", hu: "Az IT-tanúsítványok elismert igazolások meghatározott tudásról és készségekről, például CompTIA A+, Cisco CCNA vagy Google Cloud tanúsítványok.", ro: "Certificările IT sunt dovezi recunoscute de cunoștințe și abilități specifice, ex. CompTIA A+, Cisco CCNA sau certificări Google Cloud." },
  t5_inst: { de: "Markiere die anerkannten IT-Zertifikate.", en: "Highlight the recognized IT certifications.", hu: "Emeld ki az elismert IT-tanúsítványokat.", ro: "Evidențiază certificările IT recunoscute." },
  t5_h1: { de: "CompTIA, Cisco, Microsoft, Google sind bekannte Anbieter", en: "CompTIA, Cisco, Microsoft, Google are well-known providers", hu: "a CompTIA, Cisco, Microsoft, Google ismert tanúsítványkiadók", ro: "CompTIA, Cisco, Microsoft, Google sunt furnizori cunoscuți" },
  t5_h2: { de: "Zertifikate zeigen Arbeitgebern nachgewiesene Fähigkeiten", en: "Certifications show employers proven skills", hu: "a tanúsítványok igazolt készségeket mutatnak a munkáltatóknak", ro: "Certificările arată angajatorilor abilități dovedite" },
  t5_tk1: { de: "CompTIA A+", en: "CompTIA A+", hu: "CompTIA A+", ro: "CompTIA A+" },
  t5_tk2: { de: "Führerschein Klasse B", en: "Driver's license class B", hu: "B-kategóriás jogosítvány", ro: "Permis de conducere clasa B" },
  t5_tk3: { de: "Cisco CCNA", en: "Cisco CCNA", hu: "Cisco CCNA", ro: "Cisco CCNA" },
  t5_tk4: { de: "Schwimmabzeichen", en: "Swimming badge", hu: "Úszójelvény", ro: "Insignă de înot" },
  t5_tk5: { de: "Google Cloud Professional", en: "Google Cloud Professional", hu: "Google Cloud Professional", ro: "Google Cloud Professional" },
  t5_q: { de: "Wozu dienen IT-Zertifikate im Beruf?", en: "What are IT certifications used for in a career?", hu: "Mire valók az IT-tanúsítványok a munkában?", ro: "La ce servesc certificările IT în carieră?" },
  t5_qa: { de: "Sie beweisen anerkannte Kenntnisse und Fähigkeiten", en: "They prove recognized knowledge and skills", hu: "Elismert tudást és készségeket igazolnak", ro: "Dovedesc cunoștințe și abilități recunoscute" },
  t5_qb: { de: "Sie ersetzen das Schulzeugnis", en: "They replace the school report", hu: "Helyettesítik az iskolai bizonyítványt", ro: "Înlocuiesc diploma școlară" },
  t5_qc: { de: "Sie sind nur in Deutschland gültig", en: "They are only valid in Germany", hu: "Csak Németországban érvényesek", ro: "Sunt valabile doar în Germania" },
  t5_qd: { de: "Sie werden von Schulen ausgestellt", en: "They are issued by schools", hu: "Iskolák adják ki őket", ro: "Sunt emise de școli" },
};

export const INFO_K8_I9_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "💻", color: "#1565C0" },
    interactive: {
      type: "match-pairs",
      instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2",
      pairs: [
        { left: "t1_l1", right: "t1_r1" },
        { left: "t1_l2", right: "t1_r2" },
        { left: "t1_l3", right: "t1_r3" },
      ],
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "📊", color: "#006064" },
    interactive: {
      type: "gap-fill",
      instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2",
      sentence: "t2_sent",
      choices: ["t2_qa2", "t2_qb2", "t2_qc2", "t2_qd2"],
      correctIndex: 0,
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🛡️", color: "#B71C1C" },
    interactive: {
      type: "word-order",
      instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2",
      words: ["t3_w1", "t3_w2", "t3_w3", "t3_w4", "t3_w5"],
      correctOrder: [0, 1, 2, 3, 4],
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🎨", color: "#E65100" },
    interactive: {
      type: "drag-to-bucket",
      instruction: "t4_inst", hint1: "t4_h1", hint2: "t4_h2",
      buckets: [
        { id: "ux", label: "t4_bl1" },
        { id: "dev", label: "t4_bl2" },
      ],
      items: [
        { text: "t4_i1", bucketId: "ux" },
        { text: "t4_i2", bucketId: "dev" },
        { text: "t4_i3", bucketId: "ux" },
        { text: "t4_i4", bucketId: "dev" },
      ],
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🏅", color: "#4A148C" },
    interactive: {
      type: "highlight-text",
      instruction: "t5_inst", hint1: "t5_h1", hint2: "t5_h2",
      tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4", "t5_tk5"],
      correctIndices: [0, 2, 4],
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
];
