// @ts-nocheck
// lib/explorerPools/informatikaK3_i2.ts
import type { PoolTopicDef } from "./types";

export const INFO_K3_I2_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "HTML-Grundlagen",
    t1_title: "Was ist HTML?", t1_text: "HTML ist die Sprache, mit der man Webseiten baut. Es sagt dem Browser, was er anzeigen soll.", t1_inst: "Verbinde die Paare:", t1_h1: "Webseiten-Sprache.", t1_h2: "Struktur bauen.", t1_q: "Wofür steht HTML?", t1_qa: "Webseiten bauen", t1_qb: "Bilder malen", t1_qc: "Musik hören", t1_qd: "Spiele spielen",
    t1_l1: "HTML", t1_r1: "Sprache", t1_l2: "Browser", t1_r2: "Anzeigen", t1_l3: "Webseite", t1_r3: "Internet",
    t2_title: "Tags (<p>, <h1>)", t2_text: "Tags sind wie Klammern, die dem Computer sagen: Hier fängt ein Text an und hier hört er auf.", t2_inst: "Verbinde die Paare:", t2_h1: "Befehle in Klammern.", t2_h2: "Start und Ende.", t2_q: "Wie sehen HTML-Tags aus?", t2_qa: "In spitzen Klammern", t2_qb: "In runden Klammern", t2_qc: "In eckigen Klammern", t2_qd: "Ohne Klammern",
    t2_l1: "Tag", t2_r1: "Befehl", t2_l2: "<h1>", t2_r2: "Überschrift", t2_l3: "<p>", t2_r3: "Text",
    t3_title: "Attribute (src, href)", t3_text: "Attribute geben zusätzliche Informationen, wie zum Beispiel, wo ein Bild zu finden ist.", t3_inst: "Verbinde die Paare:", t3_h1: "Zusatz-Info.", t3_h2: "Eigenschaften.", t3_q: "Was macht ein Attribut?", t3_qa: "Gibt Infos", t3_qb: "Löscht Text", t3_qc: "Macht Musik", t3_qd: "Schaltet aus",
    t3_l1: "src", t3_r1: "Bildquelle", t3_l2: "href", t3_r2: "Link-Ziel", t3_l3: "Attribut", t3_r3: "Eigenschaft",
    t4_title: "Webseiten-Struktur", t4_text: "Eine Webseite hat einen Kopf (head) für Infos und einen Körper (body) für den Inhalt.", t4_inst: "Verbinde die Paare:", t4_h1: "Oben und unten.", t4_h2: "Der Aufbau.", t4_q: "Wo steht der sichtbare Inhalt einer Webseite?", t4_qa: "Im Body", t4_qb: "Im Head", t4_qc: "Im Keller", t4_qd: "In der Tasche",
    t4_l1: "Head", t4_r1: "Informationen", t4_l2: "Body", t4_r2: "Inhalt", t4_l3: "HTML", t4_r3: "Ganzes Dokument",
    t5_title: "Überschriften (h1-h6)", t5_text: "Es gibt verschiedene Größen für Überschriften, von h1 (ganz groß) bis h6 (ganz klein).", t5_inst: "Verbinde die Paare:", t5_h1: "Groß bis klein.", t5_h2: "Wichtigkeit.", t5_q: "Welche Überschrift ist am größten?", t5_qa: "h1", t5_qb: "h6", t5_qc: "h3", t5_qd: "h10",
    t5_l1: "h1", t5_r1: "Größte", t5_l2: "h6", t5_r2: "Kleinste", t5_l3: "Überschrift", t5_r3: "Titel",
    t6_title: "Absatz (<p>)", t6_text: "Mit dem p-Tag erstellt man einen normalen Textabsatz.", t6_inst: "Verbinde die Paare:", t6_h1: "Normaler Text.", t6_h2: "Schreiben.", t6_q: "Was bedeutet das 'p' in <p>?", t6_qa: "Paragraph (Absatz)", t6_qb: "Pinsel", t6_qc: "Pause", t6_qd: "Punkt",
    t6_l1: "<p>", t6_r1: "Absatz", t6_l2: "Text", t6_r2: "Lesen", t6_l3: "Inhalt", t6_r3: "Schreiben",
    t7_title: "Listen (ul, ol)", t7_text: "Listen helfen, Dinge untereinander aufzuzählen, mit Punkten oder Zahlen.", t7_inst: "Verbinde die Paare:", t7_h1: "Aufzählung.", t7_h2: "Punkte oder Zahlen.", t7_q: "Welche Liste hat Zahlen?", t7_qa: "ol (ordered list)", t7_qb: "ul (unordered list)", t7_qc: "li (list item)", t7_qd: "p (paragraph)",
    t7_l1: "ul", t7_r1: "Punkte", t7_l2: "ol", t7_r2: "Zahlen", t7_l3: "li", t7_r3: "Listenpunkt",
    t8_title: "Links (<a>)", t8_text: "Links verbinden Webseiten miteinander. Wenn man draufklickt, kommt man woanders hin.", t8_inst: "Verbinde die Paare:", t8_h1: "Verbindung.", t8_h2: "Klicken.", t8_q: "Welches Tag benutzt man für einen Link?", t8_qa: "<a>", t8_qb: "<img>", t8_qc: "<li>", t8_qd: "<div>",
    t8_l1: "<a>", t8_r1: "Link", t8_l2: "href", t3_r2: "Ziel", t8_l3: "Klick", t8_r3: "Besuchen",
    t9_title: "Bilder (<img>)", t9_text: "Mit dem img-Tag kannst du Fotos und Bilder auf deine Webseite bringen.", t9_inst: "Verbinde die Paare:", t9_h1: "Fotos zeigen.", t9_h2: "Bunt machen.", t9_q: "Was braucht ein Bild-Tag unbedingt?", t9_qa: "src (Quelle)", t9_qb: "href (Link)", t9_qc: "p (Text)", t9_qd: "h1 (Titel)",
    t9_l1: "<img>", t9_r1: "Bild", t9_l2: "src", t9_r2: "Quelle", t9_l3: "alt", t9_r3: "Beschreibung",
    t10_title: "Boxen (<div>)", t10_text: "Ein div ist wie eine unsichtbare Box, in der man andere Dinge sammeln kann.", t10_inst: "Verbinde die Paare:", t10_h1: "Container.", t10_h2: "Gruppieren.", t10_q: "Was macht ein <div>?", t10_qa: "Inhalte gruppieren", t10_qb: "Text löschen", t10_qc: "Bilder malen", t10_qd: "Musik abspielen",
    t10_l1: "<div>", t10_r1: "Box", t10_l2: "Gruppe", t10_r2: "Sammeln", t10_l3: "Layout", t10_r3: "Struktur",
    t11_title: "Formulare", t11_text: "Formulare benutzt man, um Informationen von Benutzern zu sammeln (z.B. Name).", t11_inst: "Verbinde die Paare:", t11_h1: "Eingabe.", t11_h2: "Fragen stellen.", t11_q: "Was kann man in ein Formular eingeben?", t11_qa: "Daten", t11_qb: "Essen", t11_qc: "Wasser", t11_qd: "Luft",
    t11_l1: "<form>", t11_r1: "Formular", t11_l2: "Input", t11_r2: "Eingabe", t11_l3: "Senden", t11_r3: "Button",
    t12_title: "Buttons (<button>)", t12_text: "Buttons sind Knöpfe, auf die man klicken kann, um etwas auszulösen.", t12_inst: "Verbinde die Paare:", t12_h1: "Drücken.", t12_h2: "Aktion.", t12_q: "Was passiert meistens bei einem Button?", t12_qa: "Eine Aktion startet", t12_qb: "Der Computer geht aus", t12_qc: "Es regnet", t12_qd: "Nichts",
    t12_l1: "<button>", t12_r1: "Knopf", t12_l2: "Klick", t12_r2: "Drücken", t12_l3: "Aktion", t12_r3: "Start",
    t13_title: "Input-Felder", t13_text: "In ein Input-Feld kann man Text mit der Tastatur hineinschreiben.", t13_inst: "Verbinde die Paare:", t13_h1: "Schreiben.", t13_h2: "Tippen.", t13_q: "Wo schreibt man seinen Namen in einer Webseite?", t13_qa: "In ein Input-Feld", t13_qb: "Auf den Monitor", t13_qc: "In ein Bild", t13_qd: "In einen Link",
    t13_l1: "<input>", t13_r1: "Eingabefeld", t13_l2: "Typ", t13_r2: "Art", t13_l3: "Text", t13_r3: "Schreiben",
    t14_title: "CSS-Hauch (Farbe)", t14_text: "Mit CSS macht man die Webseite hübsch, zum Beispiel mit Farben und Größen.", t14_inst: "Verbinde die Paare:", t14_h1: "Design.", t14_h2: "Schön machen.", t14_q: "Was macht CSS?", t14_qa: "Das Aussehen ändern", t14_qb: "Den Text schreiben", t14_qc: "Den Computer reparieren", t14_qd: "Das Internet löschen",
    t14_l1: "CSS", t14_r1: "Design", t14_l2: "Farbe", t14_r2: "Bunt", t14_l3: "Größe", t14_r3: "Format",
    t15_title: "Web-Meister", t15_text: "Du weißt jetzt, wie man die Grundbausteine für eine eigene Webseite setzt!", t15_inst: "Verbinde die Paare:", t15_h1: "Super gemacht.", t15_h2: "Alles gelernt.", t15_q: "Was kannst du jetzt bauen?", t15_qa: "Eine Webseite", t15_qb: "Ein Auto", t15_qc: "Ein Haus", t15_qd: "Einen Baum",
    t15_l1: "Meister", t15_r1: "Web-Profi", t15_l2: "Code", t15_r2: "Schreiben", t15_l3: "Fertig", t15_r3: "Sieg"
  },
  en: {
    explorer_title: "HTML Basics",
    t1_title: "What is HTML?", t1_text: "HTML is the language used to build websites. It tells the browser what to display.", t1_inst: "Match the pairs:", t1_h1: "Website language.", t1_h2: "Build structure.", t1_q: "What is HTML used for?", t1_qa: "Building websites", t1_qb: "Painting pictures", t1_qc: "Listening to music", t1_qd: "Playing games",
    t1_l1: "HTML", t1_r1: "Language", t1_l2: "Browser", t1_r2: "Display", t1_l3: "Website", t1_r3: "Internet",
    t2_title: "Tags (<p>, <h1>)", t2_text: "Tags are like brackets that tell the computer: here a text starts and here it ends.", t2_inst: "Match the pairs:", t2_h1: "Commands in brackets.", t2_h2: "Start and end.", t2_q: "What do HTML tags look like?", t2_qa: "In angle brackets", t2_qb: "In round brackets", t2_qc: "In square brackets", t2_qd: "Without brackets",
    t2_l1: "Tag", t2_r1: "Command", t2_l2: "<h1>", t2_r2: "Heading", t2_l3: "<p>", t2_r3: "Text",
    t3_title: "Attributes (src, href)", t3_text: "Attributes provide extra information, like where to find an image.", t3_inst: "Match the pairs:", t3_h1: "Extra info.", t3_h2: "Properties.", t3_q: "What does an attribute do?", t3_qa: "Gives info", t3_qb: "Deletes text", t3_qc: "Makes music", t3_qd: "Turns off",
    t3_l1: "src", t3_r1: "Image source", t3_l2: "href", t3_r2: "Link target", t3_l3: "Attribute", t3_r3: "Property",
    t4_title: "Website Structure", t4_text: "A website has a head for info and a body for the content.", t4_inst: "Match the pairs:", t4_h1: "Top and bottom.", t4_h2: "The layout.", t4_q: "Where is the visible content of a website located?", t4_qa: "In the body", t4_qb: "In the head", t4_qc: "In the basement", t4_qd: "In the pocket",
    t4_l1: "Head", t4_r1: "Information", t4_l2: "Body", t4_r2: "Content", t4_l3: "HTML", t4_r3: "Whole document",
    t5_title: "Headings (h1-h6)", t5_text: "There are different sizes for headings, from h1 (very large) to h6 (very small).", t5_inst: "Match the pairs:", t5_h1: "Large to small.", t5_h2: "Importance.", t5_q: "Which heading is the largest?", t5_qa: "h1", t5_qb: "h6", t5_qc: "h3", t5_qd: "h10",
    t5_l1: "h1", t5_r1: "Largest", t5_l2: "h6", t5_r2: "Smallest", t5_l3: "Heading", t5_r3: "Title",
    t6_title: "Paragraph (<p>)", t6_text: "The p tag is used to create a normal text paragraph.", t6_inst: "Match the pairs:", t6_h1: "Normal text.", t6_h2: "Writing.", t6_q: "What does the 'p' in <p> stand for?", t6_qa: "Paragraph", t6_qb: "Paint", t6_qc: "Pause", t6_qd: "Point",
    t6_l1: "<p>", t6_r1: "Paragraph", t6_l2: "Text", t6_r2: "Read", t6_l3: "Content", t6_r3: "Write",
    t7_title: "Lists (ul, ol)", t7_text: "Lists help to list things one below the other, with dots or numbers.", t7_inst: "Match the pairs:", t7_h1: "Enumeration.", t7_h2: "Dots or numbers.", t7_q: "Which list has numbers?", t7_qa: "ol (ordered list)", t7_qb: "ul (unordered list)", t7_qc: "li (list item)", t7_qd: "p (paragraph)",
    t7_l1: "ul", t7_r1: "Dots", t7_l2: "ol", t7_r2: "Numbers", t7_l3: "li", t7_r3: "List item",
    t8_title: "Links (<a>)", t8_text: "Links connect websites together. When you click on them, you go somewhere else.", t8_inst: "Match the pairs:", t8_h1: "Connection.", t8_h2: "Clicking.", t8_q: "Which tag is used for a link?", t8_qa: "<a>", t8_qb: "<img>", t8_qc: "<li>", t8_qd: "<div>",
    t8_l1: "<a>", t8_r1: "Link", t8_l2: "href", t3_r2: "Target", t8_l3: "Click", t8_r3: "Visit",
    t9_title: "Images (<img>)", t9_text: "With the img tag, you can bring photos and pictures to your website.", t9_inst: "Match the pairs:", t9_h1: "Show photos.", t9_h2: "Make it colorful.", t9_q: "What does an image tag absolutely need?", t9_qa: "src (source)", t9_qb: "href (link)", t9_qc: "p (text)", t9_qd: "h1 (title)",
    t9_l1: "<img>", t9_r1: "Image", t9_l2: "src", t9_r2: "Source", t9_l3: "alt", t9_r3: "Description",
    t10_title: "Boxes (<div>)", t10_text: "A div is like an invisible box where you can collect other things.", t10_inst: "Match the pairs:", t10_h1: "Container.", t10_h2: "Group.", t10_q: "What does a <div> do?", t10_qa: "Group content", t10_qb: "Delete text", t10_qc: "Paint pictures", t10_qd: "Play music",
    t10_l1: "<div>", t10_r1: "Box", t10_l2: "Group", t10_r2: "Collect", t10_l3: "Layout", t10_r3: "Structure",
    t11_title: "Forms", t11_text: "Forms are used to collect information from users (e.g., name).", t11_inst: "Match the pairs:", t11_h1: "Input.", t11_h2: "Ask questions.", t11_q: "What can you enter into a form?", t11_qa: "Data", t11_qb: "Food", t11_qc: "Water", t11_qd: "Air",
    t11_l1: "<form>", t11_r1: "Form", t11_l2: "Input", t11_r2: "Entry", t11_l3: "Submit", t11_r3: "Button",
    t12_title: "Buttons (<button>)", t12_text: "Buttons are things you can click on to trigger something.", t12_inst: "Match the pairs:", t12_h1: "Press.", t12_h2: "Action.", t12_q: "What usually happens with a button?", t12_qa: "An action starts", t12_qb: "Computer turns off", t12_qc: "It rains", t12_qd: "Nothing",
    t12_l1: "<button>", t12_r1: "Button", t12_l2: "Click", t12_r2: "Press", t12_l3: "Action", t12_r3: "Start",
    t13_title: "Input Fields", t13_text: "In an input field, you can write text with the keyboard.", t13_inst: "Match the pairs:", t13_h1: "Write.", t13_h2: "Type.", t13_q: "Where do you write your name on a website?", t13_qa: "In an input field", t13_qb: "On the monitor", t13_qc: "In a picture", t13_qd: "In a link",
    t13_l1: "<input>", t13_r1: "Input field", t13_l2: "Type", t13_r2: "Kind", t13_l3: "Text", t13_r3: "Write",
    t14_title: "CSS Touch (Color)", t14_text: "With CSS, you make the website pretty, for example with colors and sizes.", t14_inst: "Match the pairs:", t14_h1: "Design.", t14_h2: "Make it nice.", t14_q: "What does CSS do?", t14_qa: "Change appearance", t14_qb: "Write the text", t14_qc: "Fix the computer", t14_qd: "Delete the internet",
    t14_l1: "CSS", t14_r1: "Design", t14_l2: "Color", t14_r2: "Colorful", t14_l3: "Size", t14_r3: "Format",
    t15_title: "Web Master", t15_text: "You now know how to set the basic building blocks for your own website!", t15_inst: "Match the pairs:", t15_h1: "Great job.", t15_h2: "Learned everything.", t15_q: "What can you build now?", t15_qa: "A website", t15_qb: "A car", t15_qc: "A house", t15_qd: "A tree",
    t15_l1: "Master", t15_r1: "Web Pro", t15_l2: "Code", t15_r2: "Write", t15_l3: "Done", t15_r3: "Victory"
  },
  hu: {
    explorer_title: "HTML alapok",
    t1_title: "Mi az HTML?", t1_text: "A HTML az a nyelv, amivel weboldalakat építünk. Megmondja a böngészőnek, mit mutasson.", t1_inst: "Párosítsd össze:", t1_h1: "Weboldal nyelv.", t1_h2: "Szerkezet építés.", t1_q: "Mire való a HTML?", t1_qa: "Weboldalak készítésére", t1_qb: "Képek festésére", t1_qc: "Zenehallgatásra", t1_qd: "Játékra",
    t1_l1: "HTML", t1_r1: "Nyelv", t1_l2: "Böngésző", t1_r2: "Megjelenítés", t1_l3: "Weboldal", t1_r3: "Internet",
    t2_title: "Tagek (<p>, <h1>)", t2_text: "A tagek olyanok, mint a zárójelek, amik megmondják a gépnek: itt kezdődik egy szöveg és itt ér véget.", t2_inst: "Párosítsd össze:", t2_h1: "Parancsok zárójelben.", t2_h2: "Kezdet és vég.", t2_q: "Hogy néznek ki a HTML tagek?", t2_qa: "Kacsacsőrök között", t2_qb: "Sima zárójelben", t2_qc: "Szögletes zárójelben", t2_qd: "Zárójel nélkül",
    t2_l1: "Tag", t2_r1: "Parancs", t2_l2: "<h1>", t2_r2: "Címsor", t2_l3: "<p>", t2_r3: "Szöveg",
    t3_title: "Attribútumok (src, href)", t3_text: "Az attribútumok plusz információt adnak, például hogy hol található egy kép.", t3_inst: "Párosítsd össze:", t3_h1: "Plusz infó.", t3_h2: "Tulajdonságok.", t3_q: "Mit csinál egy attribútum?", t3_qa: "Infót ad", t3_qb: "Törli a szöveget", t3_qc: "Zenél", t3_qd: "Kikapcsol",
    t3_l1: "src", t3_r1: "Kép forrása", t3_l2: "href", t3_r2: "Link célja", t3_l3: "Attribútum", t3_r3: "Tulajdonság",
    t4_title: "Weboldal szerkezete", t4_text: "Egy weboldalnak van feje (head) az infóknak és teste (body) a tartalomnak.", t4_inst: "Párosítsd össze:", t4_h1: "Fent és lent.", t4_h2: "A felépítés.", t4_q: "Hol van a weboldal látható tartalma?", t4_qa: "A body-ban", t4_qb: "A head-ben", t4_qc: "A pincében", t4_qd: "A zsebben",
    t4_l1: "Head", t4_r1: "Információk", t4_l2: "Body", t4_r2: "Tartalom", t4_l3: "HTML", t4_r3: "Egész dokumentum",
    t5_title: "Címsorok (h1-h6)", t5_text: "Különböző méretű címsorok vannak, a h1-től (legnagyobb) a h6-ig (legkisebb).", t5_inst: "Párosítsd össze:", t5_h1: "Nagy és kicsi.", t5_h2: "Fontosság.", t5_q: "Melyik címsor a legnagyobb?", t5_qa: "h1", t5_qb: "h6", t5_qc: "h3", t5_qd: "h10",
    t5_l1: "h1", t5_r1: "Legnagyobb", t5_l2: "h6", t5_r2: "Legkisebb", t5_l3: "Címsor", t5_r3: "Cím",
    t6_title: "Bekezdés (<p>)", t6_text: "A p taggel hozunk létre egy sima szöveges bekezdést.", t6_inst: "Párosítsd össze:", t6_h1: "Sima szöveg.", t6_h2: "Írás.", t6_q: "Mit jelent a 'p' a <p>-ben?", t6_qa: "Paragraph (bekezdés)", t6_qb: "Pecsenye", t6_qc: "Pipa", t6_qd: "Pont",
    t6_l1: "<p>", t6_r1: "Bekezdés", t6_l2: "Szöveg", t6_r2: "Olvasás", t6_l3: "Tartalom", t6_r3: "Írás",
    t7_title: "Listák (ul, ol)", t7_text: "A listák segítenek felsorolni dolgokat egymás alatt, pontokkal vagy számokkal.", t7_inst: "Párosítsd össze:", t7_h1: "Felsorolás.", t7_h2: "Pontok vagy számok.", t7_q: "Melyik listában vannak számok?", t7_qa: "ol (ordered list)", t7_qb: "ul (unordered list)", t7_qc: "li (list item)", t7_qd: "p (paragraph)",
    t7_l1: "ul", t7_r1: "Pontok", t7_l2: "ol", t7_r2: "Számok", t7_l3: "li", t7_r3: "Listaelem",
    t8_title: "Linkek (<a>)", t8_text: "A linkek összekötik a weboldalakat. Ha rákattintasz, máshová jutsz.", t8_inst: "Párosítsd össze:", t8_h1: "Kapcsolat.", t8_h2: "Kattintás.", t8_q: "Melyik taget használjuk linkhez?", t8_qa: "<a>", t8_qb: "<img>", t8_qc: "<li>", t8_qd: "<div>",
    t8_l1: "<a>", t8_r1: "Link", t8_l2: "href", t3_r2: "Cél", t8_l3: "Kattintás", t8_r3: "Látogatás",
    t9_title: "Képek (<img>)", t9_text: "Az img taggel tudsz fotókat és képeket tenni a weboldaladra.", t9_inst: "Párosítsd össze:", t9_h1: "Fotók mutatása.", t9_h2: "Legyen színes.", t9_q: "Mire van szüksége egy képnek?", t9_qa: "src (forrás)", t9_qb: "href (link)", t9_qc: "p (szöveg)", t9_qd: "h1 (cím)",
    t9_l1: "<img>", t9_r1: "Kép", t9_l2: "src", t9_r2: "Forrás", t9_l3: "alt", t9_r3: "Leírás",
    t10_title: "Dobozok (<div>)", t10_text: "A div olyan, mint egy láthatatlan doboz, amibe más dolgokat gyűjthetsz.", t10_inst: "Párosítsd össze:", t10_h1: "Tároló.", t10_h2: "Csoportosítás.", t10_q: "Mit csinál a <div>?", t10_qa: "Csoportosítja a tartalmat", t10_qb: "Törli a szöveget", t10_qc: "Képet fest", t10_qd: "Zenét játszik",
    t10_l1: "<div>", t10_r1: "Doboz", t10_l2: "Csoport", t10_r2: "Gyűjtés", t10_l3: "Elrendezés", t10_r3: "Szerkezet",
    t11_title: "Űrlapok", t11_text: "Az űrlapokat arra használjuk, hogy infókat gyűjtsünk a felhasználóktól (pl. név).", t11_inst: "Párosítsd össze:", t11_h1: "Bevitel.", t11_h2: "Kérdések.", t11_q: "Mit lehet beírni egy űrlapba?", t11_qa: "Adatokat", t11_qb: "Ételt", t11_qc: "Vizet", t11_qd: "Levegőt",
    t11_l1: "<form>", t11_r1: "Űrlap", t11_l2: "Input", t11_r2: "Bevitel", t11_l3: "Küldés", t11_r3: "Gomb",
    t12_title: "Gombok (<button>)", t12_text: "A gombok olyan dolgok, amikre kattintva elindul valami.", t12_inst: "Párosítsd össze:", t12_h1: "Megnyomás.", t12_h2: "Akció.", t12_q: "Mi történik általában egy gombbal?", t12_qa: "Elindul egy művelet", t12_qb: "Kikapcsol a gép", t12_qc: "Esik az eső", t12_qd: "Semmi",
    t12_l1: "<button>", t12_r1: "Gomb", t12_l2: "Kattintás", t12_r2: "Nyomás", t12_l3: "Akció", t12_r3: "Indítás",
    t13_title: "Input mezők", t13_text: "Az input mezőbe szöveget tudsz írni a billentyűzettel.", t13_inst: "Párosítsd össze:", t13_h1: "Írás.", t13_h2: "Gépelés.", t13_q: "Hova írod a neved egy weboldalon?", t13_qa: "Egy input mezőbe", t13_qb: "A monitorra", t13_qc: "Egy képbe", t13_qd: "Egy linkbe",
    t13_l1: "<input>", t13_r1: "Beviteli mező", t13_l2: "Típus", t13_r2: "Fajta", t13_l3: "Szöveg", t13_r3: "Írás",
    t14_title: "CSS csepp (Szín)", t14_text: "A CSS-sel teszed széppé a weboldalt, például színekkel és méretekkel.", t14_inst: "Párosítsd össze:", t14_h1: "Dizájn.", t14_h2: "Szépítés.", t14_q: "Mit csinál a CSS?", t14_qa: "Megváltoztatja a kinézetet", t14_qb: "Megírja a szöveget", t14_qc: "Megjavítja a gépet", t14_qd: "Törli az internetet",
    t14_l1: "CSS", t14_r1: "Dizájn", t14_l2: "Szín", t14_r2: "Színes", t14_l3: "Méret", t14_r3: "Formátum",
    t15_title: "Web mester", t15_text: "Most már tudod, hogyan rakd le a saját weboldalad alapköveit!", t15_inst: "Párosítsd össze:", t15_h1: "Szuper munka.", t15_h2: "Mindent megtanultál.", t15_q: "Mit tudsz most már építeni?", t15_qa: "Weboldalt", t15_qb: "Autót", t15_qc: "Házat", t15_qd: "Fát",
    t15_l1: "Mester", t15_r1: "Web profi", t15_l2: "Kód", t15_r2: "Írás", t15_l3: "Kész", t15_r3: "Győzelem"
  },
  ro: {
    explorer_title: "Bazele HTML",
    t1_title: "Ce este HTML?", t1_text: "HTML este limbajul cu care se construiesc paginile web. Îi spune browserului ce să afișeze.", t1_inst: "Potrivește perechile:", t1_h1: "Limbaj web.", t1_h2: "Construcție structură.", t1_q: "La ce servește HTML?", t1_qa: "Construirea paginilor web", t1_qb: "Pictarea imaginilor", t1_qc: "Ascultarea muzicii", t1_qd: "Jocuri",
    t1_l1: "HTML", t1_r1: "Limbaj", t1_l2: "Browser", t1_r2: "Afișare", t1_l3: "Pagină web", t1_r3: "Internet",
    t2_title: "Tag-uri (<p>, <h1>)", t2_text: "Tag-urile sunt ca niște paranteze care îi spun calculatorului: aici începe un text și aici se termină.", t2_inst: "Potrivește perechile:", t2_h1: "Comenzi în paranteze.", t2_h2: "Început și sfârșit.", t2_q: "Cum arată tag-urile HTML?", t2_qa: "Între paranteze ascuțite", t2_qb: "Între paranteze rotunde", t2_qc: "Între paranteze pătrate", t2_qd: "Fără paranteze",
    t2_l1: "Tag", t2_r1: "Comandă", t2_l2: "<h1>", t2_r2: "Titlu", t2_l3: "<p>", t2_r3: "Text",
    t3_title: "Atribute (src, href)", t3_text: "Atributele oferă informații suplimentare, cum ar fi unde se găsește o imagine.", t3_inst: "Potrivește perechile:", t3_h1: "Info în plus.", t3_h2: "Proprietăți.", t3_q: "Ce face un atribut?", t3_qa: "Oferă info", t3_qb: "Șterge textul", t3_qc: "Face muzică", t3_qd: "Oprește",
    t3_l1: "src", t3_r1: "Sursă imagine", t3_l2: "href", t3_r2: "Țintă link", t3_l3: "Atribut", t3_r3: "Proprietate",
    t4_title: "Structura paginii web", t4_text: "O pagină web are un cap (head) pentru info și un corp (body) pentru conținut.", t4_inst: "Potrivește perechile:", t4_h1: "Sus și jos.", t4_h2: "Construcția.", t4_q: "Unde se află conținutul vizibil al unei pagini web?", t4_qa: "În body", t4_qb: "În head", t4_qc: "În pivniță", t4_qd: "În buzunar",
    t4_l1: "Head", t4_r1: "Informații", t4_l2: "Body", t4_r2: "Conținut", t4_l3: "HTML", t4_r3: "Tot documentul",
    t5_title: "Titluri (h1-h6)", t5_text: "Există diferite mărimi pentru titluri, de la h1 (cel mai mare) la h6 (cel mai mic).", t5_inst: "Potrivește perechile:", t5_h1: "Mare și mic.", t5_h2: "Importanță.", t5_q: "Care titlu este cel mai mare?", t5_qa: "h1", t5_qb: "h6", t5_qc: "h3", t5_qd: "h10",
    t5_l1: "h1", t5_r1: "Cel mai mare", t5_l2: "h6", t5_r2: "Cel mai mic", t5_l3: "Titlu", t5_r3: "Nume",
    t6_title: "Paragraf (<p>)", t6_text: "Cu tag-ul p creăm un paragraf de text normal.", t6_inst: "Potrivește perechile:", t6_h1: "Text normal.", t6_h2: "Scriere.", t6_q: "Ce înseamnă 'p' în <p>?", t6_qa: "Paragraph (paragraf)", t6_qb: "Pensulă", t6_qc: "Pipă", t6_qd: "Punct",
    t6_l1: "<p>", t6_r1: "Paragraf", t6_l2: "Text", t6_r2: "Citire", t6_l3: "Conținut", t6_r3: "Scriere",
    t7_title: "Liste (ul, ol)", t7_text: "Listele ajută la enumerarea lucrurilor unul sub altul, cu puncte sau numere.", t7_inst: "Potrivește perechile:", t7_h1: "Enumerare.", t7_h2: "Puncte sau numere.", t7_q: "Care listă are numere?", t7_qa: "ol (ordered list)", t7_qb: "ul (unordered list)", t7_qc: "li (list item)", t7_qd: "p (paragraph)",
    t7_l1: "ul", t7_r1: "Puncte", t7_l2: "ol", t7_r2: "Numere", t7_l3: "li", t7_r3: "Element listă",
    t8_title: "Link-uri (<a>)", t8_text: "Link-urile conectează paginile web între ele. Dacă dai clic, ajungi în altă parte.", t8_inst: "Potrivește perechile:", t8_h1: "Conexiune.", t8_h2: "Clic.", t8_q: "Ce tag folosim pentru link?", t8_qa: "<a>", t8_qb: "<img>", t8_qc: "<li>", t8_qd: "<div>",
    t8_l1: "<a>", t8_r1: "Link", t8_l2: "href", t3_r2: "Țintă", t8_l3: "Clic", t8_r3: "Vizită",
    t9_title: "Imagini (<img>)", t9_text: "Cu tag-ul img poți pune fotografii și imagini pe pagina ta web.", t9_inst: "Potrivește perechile:", t9_h1: "Arată poze.", t9_h2: "Să fie colorat.", t9_q: "De ce are nevoie o imagine?", t9_qa: "src (sursă)", t9_qb: "href (link)", t9_qc: "p (text)", t9_qd: "h1 (titlu)",
    t9_l1: "<img>", t9_r1: "Imagine", t9_l2: "src", t9_r2: "Sursă", t9_l3: "alt", t9_r3: "Descriere",
    t10_title: "Cutii (<div>)", t10_text: "Un div este ca o cutie invizibilă în care poți aduna alte lucruri.", t10_inst: "Potrivește perechile:", t10_h1: "Container.", t10_h2: "Grupare.", t10_q: "Ce face un <div>?", t10_qa: "Grupează conținutul", t10_qb: "Șterge textul", t10_qc: "Pictează", t10_qd: "Redă muzică",
    t10_l1: "<div>", t10_r1: "Cutie", t10_l2: "Grup", t10_r2: "Colectare", t10_l3: "Aranjare", t10_r3: "Structură",
    t11_title: "Formulare", t11_text: "Formularele sunt folosite pentru a colecta info de la utilizatori (ex. nume).", t11_inst: "Potrivește perechile:", t11_h1: "Introducere.", t11_h2: "Întrebări.", t11_q: "Ce se poate scrie într-un formular?", t11_qa: "Date", t11_qb: "Mâncare", t11_qc: "Apă", t11_qd: "Aer",
    t11_l1: "<form>", t11_r1: "Formular", t11_l2: "Input", t11_r2: "Introducere", t11_l3: "Trimitere", t11_r3: "Buton",
    t12_title: "Butoane (<button>)", t12_text: "Butoanele sunt lucruri pe care dai clic pentru a porni ceva.", t12_inst: "Potrivește perechile:", t12_h1: "Apăsare.", t12_h2: "Acțiune.", t12_q: "Ce se întâmplă de obicei cu un buton?", t12_qa: "Pornește o acțiune", t12_qb: "Se oprește calculatorul", t12_qc: "Plouă", t12_qd: "Nimic",
    t12_l1: "<button>", t12_r1: "Buton", t12_l2: "Clic", t12_r2: "Apăsare", t12_l3: "Acțiune", t12_r3: "Pornire",
    t13_title: "Câmpuri input", t13_text: "În câmpul input poți scrie text cu tastatura.", t13_inst: "Potrivește perechile:", t13_h1: "Scriere.", t13_h2: "Tastare.", t13_q: "Unde îți scrii numele pe o pagină web?", t13_qa: "Într-un câmp input", t13_qb: "Pe monitor", t13_qc: "Într-o imagine", t13_qd: "Într-un link",
    t13_l1: "<input>", t13_r1: "Câmp introducere", t13_l2: "Tip", t13_r2: "Fel", t13_l3: "Text", t13_r3: "Scriere",
    t14_title: "CSS (Culoare)", t14_text: "Cu CSS faci pagina web frumoasă, de exemplu cu culori și mărimi.", t14_inst: "Potrivește perechile:", t14_h1: "Design.", t14_h2: "Înfrumusețare.", t14_q: "Ce face CSS?", t14_qa: "Schimbă aspectul", t14_qb: "Scrie textul", t14_qc: "Repară calculatorul", t14_qd: "Șterge internetul",
    t14_l1: "CSS", t14_r1: "Design", t14_l2: "Culoare", t14_r2: "Colorat", t14_l3: "Mărime", t14_r3: "Format",
    t15_title: "Maestru Web", t15_text: "Acum știi cum să pui bazele propriei tale pagini web!", t15_inst: "Potrivește perechile:", t15_h1: "Bravo.", t15_h2: "Ai învățat totul.", t15_q: "Ce poți construi acum?", t15_qa: "O pagină web", t15_qb: "O mașină", t15_qc: "O casă", t15_qd: "Un copac",
    t15_l1: "Maestru", t15_r1: "Web profi", t15_l2: "Cod", t15_r2: "Scriere", t15_l3: "Gata", t15_r3: "Victorie"
  }
};

export const INFO_K3_I2_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["🌐", "🏷️", "⚙️", "🏗️", "🔝", "📄", "📜", "🔗", "🖼️", "📦", "📝", "🔘", "⌨️", "🎨", "🏆"];
  const colors = ["#E44D26", "#F16529", "#2965F1", "#333333", "#61DAFB", "#4CAF50", "#FF9800", "#2196F3", "#9C27B0", "#795548", "#607D8B", "#E91E63", "#009688", "#FFC107", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});

