// lib/explorerPools/informatikaK3_i8.ts
import type { PoolTopicDef } from "./types";

export const INFO_K3_I8_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Datenbank Grundlagen",
    t1_title: "Was ist eine Datenbank?", t1_text: "Eine Datenbank ist ein System zur elektronischen Verwaltung von großen Datenmengen.", t1_inst: "Verbinde die Paare:", t1_h1: "Daten ordnen.", t1_h2: "Digitales Archiv.", t1_q: "Wofür nutzt man eine Datenbank?", t1_qa: "Zum Speichern großer Datenmengen", t1_qb: "Zum Haare schneiden", t1_qc: "Zum Kochen", t1_qd: "Zum Schlafen",
    t1_l1: "Datenbank", t1_r1: "Speichersystem", t1_l2: "Daten", t1_r2: "Informationen", t1_l3: "Struktur", t1_r3: "Ordnung",
    t2_title: "Die Tabelle", t2_text: "In einer Datenbank werden Daten in Tabellen organisiert, ähnlich wie in Excel.", t2_inst: "Verbinde die Paare:", t2_h1: "Zeilen und Spalten.", t2_h2: "Grundbaustein.", t2_q: "Wie nennt man die Struktur in einer Datenbank?", t2_qa: "Tabelle", t2_qb: "Kreis", t2_qc: "Wolke", t2_qd: "Punkt",
    t2_l1: "Tabelle", t2_r1: "Table", t2_l2: "Raster", t2_r2: "Gitter", t2_l3: "Name", t2_r3: "Bezeichnung",
    t3_title: "Der Datensatz (Zeile)", t3_text: "Eine Zeile in einer Tabelle enthält alle Informationen zu einem bestimmten Objekt.", t3_inst: "Verbinde die Paare:", t3_h1: "Ein Objekt.", t3_h2: "Waagerecht.", t3_q: "Was ist ein Datensatz?", t3_qa: "Eine Zeile in der Tabelle", t3_qb: "Eine ganze Datenbank", t3_qc: "Ein Computer", t3_qd: "Ein Kabel",
    t3_l1: "Datensatz", t3_r1: "Zeile", t3_l2: "Eintrag", t3_r2: "Row", t3_l3: "Objekt", t3_r3: "Einheit",
    t4_title: "Das Feld (Spalte)", t4_text: "Eine Spalte definiert eine bestimmte Eigenschaft, wie zum Beispiel 'Name' oder 'Alter'.", t4_inst: "Verbinde die Paare:", t4_h1: "Eigenschaft.", t4_h2: "Senkrecht.", t4_q: "Was beschreibt eine Spalte?", t4_qa: "Eine bestimmte Eigenschaft", t4_qb: "Das ganze Wetter", t4_qc: "Die Farbe des PCs", t4_qd: "Nichts",
    t4_l1: "Feld", t4_r1: "Spalte", t4_l2: "Attribut", t4_r2: "Column", t4_l3: "Typ", t4_r3: "Art",
    t5_title: "Primärschlüssel", t5_text: "Ein Primärschlüssel ist ein eindeutiger Wert, der jeden Datensatz kennzeichnet (z.B. ID).", t5_inst: "Verbinde die Paare:", t5_h1: "Eindeutig.", t5_h2: "Identifikation.", t5_q: "Was macht ein Primärschlüssel?", t5_qa: "Identifiziert Datensätze eindeutig", t5_qb: "Schließt die Tür ab", t5_qc: "Macht Musik", t5_qd: "Löscht alles",
    t5_l1: "Primärschlüssel", t5_r1: "ID", t5_l2: "Eindeutig", t5_r2: "Unique", t5_l3: "Schlüssel", t5_r3: "Key",
    t6_title: "Die Abfrage", t6_text: "Mit einer Abfrage (Query) suchst du gezielt nach Informationen in der Datenbank.", t6_inst: "Verbinde die Paare:", t6_h1: "Frage stellen.", t6_h2: "Suchen.", t6_q: "Was ist eine Abfrage?", t6_qa: "Eine gezielte Suche", t6_qb: "Ein Fehler", t6_qc: "Ein Bild", t6_qd: "Ein Spiel",
    t6_l1: "Abfrage", t6_r1: "Query", t6_l2: "Suche", t6_r2: "Finden", t6_l3: "Ergebnis", t6_r3: "Liste",
    t7_title: "SELECT Basis", t7_text: "Mit dem Befehl SELECT wählst du aus, welche Spalten du sehen möchtest.", t7_inst: "Verbinde die Paare:", t7_h1: "Auswählen.", t7_h2: "Anzeigen.", t7_q: "Was macht SELECT?", t7_qa: "Wählt Daten aus", t7_qb: "Löscht Daten", t7_qc: "Ändert das Passwort", t7_qd: "Druckt Papier",
    t7_l1: "SELECT", t7_r1: "Wähle", t7_l2: "FROM", t7_r2: "Von", t7_l3: "Stern (*)", t7_r3: "Alles",
    t8_title: "WHERE Bedingung", t8_text: "Mit WHERE kannst du die Ergebnisse filtern (z.B. nur Personen über 18).", t8_inst: "Verbinde die Paare:", t8_h1: "Filtern.", t8_h2: "Bedingung.", t8_q: "Wofür nutzt man WHERE?", t8_qa: "Zum Filtern von Daten", t8_qb: "Zum Malen", t8_qc: "Zum Rechnen", t8_qd: "Zum Beenden",
    t8_l1: "WHERE", t8_r1: "Wo", t8_l2: "Filter", t8_r2: "Einschränkung", t8_l3: "Bedingung", t8_r3: "Condition",
    t9_title: "ORDER BY", t9_text: "Mit ORDER BY sortierst du deine Ergebnisse (z.B. alphabetisch).", t9_inst: "Verbinde die Paare:", t9_h1: "Sortieren.", t9_h2: "Reihenfolge.", t9_q: "Was macht ORDER BY?", t9_qa: "Sortiert die Ergebnisse", t9_qb: "Löscht die Tabelle", t9_qc: "Macht ein Foto", t9_qd: "Spielt ein Video",
    t9_l1: "ORDER BY", t9_r1: "Sortiere", t9_l2: "ASC", t9_r2: "Aufsteigend", t9_l3: "DESC", t9_r3: "Absteigend",
    t10_title: "LIMIT", t10_text: "Mit LIMIT begrenzt du die Anzahl der angezeigten Ergebnisse.", t10_inst: "Verbinde die Paare:", t10_h1: "Begrenzen.", t10_h2: "Anzahl.", t10_q: "Was bewirkt LIMIT 5?", t10_qa: "Zeigt nur 5 Ergebnisse", t10_qb: "Zeigt 500 Ergebnisse", t10_qc: "Löscht 5 Zeilen", t10_qd: "Wartet 5 Minuten",
    t10_l1: "LIMIT", t10_r1: "Grenze", t10_l2: "Anzahl", t10_r2: "Menge", t10_l3: "Stopp", t10_r3: "Ende",
    t11_title: "JOIN (Verknüpfung)", t11_text: "Mit JOIN kannst du Daten aus zwei verschiedenen Tabellen kombinieren.", t11_inst: "Verbinde die Paare:", t11_h1: "Verbinden.", t11_h2: "Zusammenführen.", t11_q: "Was macht ein JOIN?", t11_qa: "Verknüpft Tabellen", t11_qb: "Trennt Tabellen", t11_qc: "Löscht die Datenbank", t11_qd: "Ändert die Farbe",
    t11_l1: "JOIN", t11_r1: "Verbinden", t11_l2: "Relation", t11_r2: "Beziehung", t11_l3: "Fremdschlüssel", t11_r3: "Link",
    t12_title: "INSERT (Einfügen)", t12_text: "Mit INSERT fügst du einen neuen Datensatz in eine Tabelle ein.", t12_inst: "Verbinde die Paare:", t12_h1: "Hinzufügen.", t12_h2: "Neu erstellen.", t12_q: "Was macht INSERT?", t12_qa: "Fügt neue Daten ein", t12_qb: "Löscht alte Daten", t12_qc: "Sucht Daten", t12_qd: "Sortiert Daten",
    t12_l1: "INSERT", t12_r1: "Einfügen", t12_l2: "INTO", t12_r2: "In", t12_l3: "VALUES", t12_r3: "Werte",
    t13_title: "UPDATE (Ändern)", t13_text: "Mit UPDATE kannst du bestehende Informationen in der Datenbank ändern.", t13_inst: "Verbinde die Paare:", t13_h1: "Aktualisieren.", t13_h2: "Korrigieren.", t13_q: "Was macht UPDATE?", t13_qa: "Ändert vorhandene Daten", t13_qb: "Löscht die Datenbank", t13_qc: "Erstellt eine Tabelle", t13_qd: "Nichts",
    t13_l1: "UPDATE", t13_r1: "Ändern", t13_l2: "SET", t13_r2: "Setze", t13_l3: "Neu", t13_r3: "Aktuell",
    t14_title: "DELETE (Löschen)", t14_text: "Mit DELETE entfernst du Datensätze aus einer Tabelle.", t14_inst: "Verbinde die Paare:", t14_h1: "Entfernen.", t14_h2: "Vorsicht!", t14_q: "Was macht DELETE?", t14_qa: "Löscht Datensätze", t14_qb: "Kopiert Datensätze", t14_qc: "Sichert Daten", t14_qd: "Macht alles bunt",
    t14_l1: "DELETE", t14_r1: "Löschen", t14_l2: "FROM", t14_r2: "Von", t14_l3: "Weg", t14_r3: "Entfernt",
    t15_title: "Datenbank-Meister", t15_text: "Du verstehst jetzt, wie Computer große Mengen an Informationen verwalten!", t15_inst: "Verbinde die Paare:", t15_h1: "Daten-Experte.", t15_h2: "Alles gelernt.", t15_q: "Was ist das Herz vieler Apps?", t15_qa: "Die Datenbank", t15_qb: "Die Maus", t15_qc: "Das Gehäuse", t15_qd: "Das Stromkabel",
    t15_l1: "Meister", t15_r1: "Experte", t15_l2: "SQL", t15_r2: "Sprache", t15_l3: "Daten", t15_r3: "Wissen"
  },
  en: {
    explorer_title: "Database Basics",
    t1_title: "What is a Database?", t1_text: "A database is a system for electronically managing large amounts of data.", t1_inst: "Match the pairs:", t1_h1: "Organize data.", t1_h2: "Digital archive.", t1_q: "What is a database used for?", t1_qa: "Storing large amounts of data", t1_qb: "Cutting hair", t1_qc: "Cooking", t1_qd: "Sleeping",
    t1_l1: "Database", t1_r1: "Storage system", t1_l2: "Data", t1_r2: "Information", t1_l3: "Structure", t1_r3: "Order",
    t2_title: "The Table", t2_text: "In a database, data is organized into tables, similar to Excel.", t2_inst: "Match the pairs:", t2_h1: "Rows and columns.", t2_h2: "Basic building block.", t2_q: "What is the structure in a database called?", t2_qa: "Table", t2_qb: "Circle", t2_qc: "Cloud", t2_qd: "Dot",
    t2_l1: "Table", t2_r1: "Grid", t2_l2: "Raster", t2_r2: "Matrix", t2_l3: "Name", t2_r3: "Label",
    t3_title: "The Record (Row)", t3_text: "A row in a table contains all information about a specific object.", t3_inst: "Match the pairs:", t3_h1: "One object.", t3_h2: "Horizontal.", t3_q: "What is a record?", t3_qa: "A row in the table", t3_qb: "A whole database", t3_qc: "A computer", t3_qd: "A cable",
    t3_l1: "Record", t3_r1: "Row", t3_l2: "Entry", t3_r2: "Item", t3_l3: "Object", t3_r3: "Unit",
    t4_title: "The Field (Column)", t4_text: "A column defines a specific property, such as 'Name' or 'Age'.", t4_inst: "Match the pairs:", t4_h1: "Property.", t4_h2: "Vertical.", t4_q: "What does a column describe?", t4_qa: "A specific property", t4_qb: "The whole weather", t4_qc: "PC color", t4_qd: "Nothing",
    t4_l1: "Field", t4_r1: "Column", t4_l2: "Attribute", t4_r2: "Property", t4_l3: "Type", t4_r3: "Kind",
    t5_title: "Primary Key", t5_text: "A primary key is a unique value that identifies each record (e.g., ID).", t5_inst: "Match the pairs:", t5_h1: "Unique.", t5_h2: "Identification.", t5_q: "What does a primary key do?", t5_qa: "Uniquely identifies records", t5_qb: "Locks the door", t5_qc: "Makes music", t5_qd: "Deletes everything",
    t5_l1: "Primary Key", t5_r1: "ID", t5_l2: "Unique", t5_r2: "Single", t5_l3: "Key", t5_r3: "Identifier",
    t6_title: "The Query", t6_text: "With a query, you search for specific information in the database.", t6_inst: "Match the pairs:", t6_h1: "Ask a question.", t6_h2: "Search.", t6_q: "What is a query?", t6_qa: "A targeted search", t6_qb: "An error", t6_qc: "An image", t6_qd: "A game",
    t6_l1: "Query", t6_r1: "Search", t6_l2: "Ask", t6_r2: "Find", t6_l3: "Result", t6_r3: "List",
    t7_title: "SELECT Basic", t7_text: "Use the SELECT command to choose which columns you want to see.", t7_inst: "Match the pairs:", t7_h1: "Select.", t7_h2: "Display.", t7_q: "What does SELECT do?", t7_qa: "Selects data", t7_qb: "Deletes data", t7_qc: "Changes password", t7_qd: "Prints paper",
    t7_l1: "SELECT", t7_r1: "Choose", t7_l2: "FROM", t7_r2: "Source", t7_l3: "Asterisk (*)", t7_r3: "All",
    t8_title: "WHERE Condition", t8_text: "Use WHERE to filter results (e.g., only people over 18).", t8_inst: "Match the pairs:", t8_h1: "Filter.", t8_h2: "Condition.", t8_q: "What is WHERE used for?", t8_qa: "Filtering data", t8_qb: "Painting", t8_qc: "Calculating", t8_qd: "Exiting",
    t8_l1: "WHERE", t8_r1: "Condition", t8_l2: "Filter", t8_r2: "Limit", t8_l3: "Criteria", t8_r3: "Rule",
    t9_title: "ORDER BY", t9_text: "Use ORDER BY to sort your results (e.g., alphabetically).", t9_inst: "Match the pairs:", t9_h1: "Sort.", t9_h2: "Sequence.", t9_q: "What does ORDER BY do?", t9_qa: "Sorts the results", t9_qb: "Deletes the table", t9_qc: "Takes a photo", t9_qd: "Plays a video",
    t9_l1: "ORDER BY", t9_r1: "Sort", t9_l2: "ASC", t9_r2: "Ascending", t9_l3: "DESC", t9_r3: "Descending",
    t10_title: "LIMIT", t10_text: "Use LIMIT to restrict the number of results displayed.", t10_inst: "Match the pairs:", t10_h1: "Restrict.", t10_h2: "Amount.", t10_q: "What does LIMIT 5 do?", t10_qa: "Shows only 5 results", t10_qb: "Shows 500 results", t10_qc: "Deletes 5 rows", t10_qd: "Waits 5 minutes",
    t10_l1: "LIMIT", t10_r1: "Bound", t10_l2: "Count", t10_r2: "Quantity", t10_l3: "Stop", t10_r3: "End",
    t11_title: "JOIN (Link)", t11_text: "Use JOIN to combine data from two different tables.", t11_inst: "Match the pairs:", t11_h1: "Connect.", t11_h2: "Merge.", t11_q: "What does a JOIN do?", t11_qa: "Links tables", t11_qb: "Separates tables", t11_qc: "Deletes database", t11_qd: "Changes color",
    t11_l1: "JOIN", t11_r1: "Connect", t11_l2: "Relation", t11_r2: "Link", t11_l3: "Foreign Key", t11_r3: "Reference",
    t12_title: "INSERT", t12_text: "Use INSERT to add a new record to a table.", t12_inst: "Match the pairs:", t12_h1: "Add.", t12_h2: "Create new.", t12_q: "What does INSERT do?", t12_qa: "Adds new data", t12_qb: "Deletes old data", t12_qc: "Searches data", t12_qd: "Sorts data",
    t12_l1: "INSERT", t12_r1: "Add", t12_l2: "INTO", t12_r2: "Target", t12_l3: "VALUES", t12_r3: "Data",
    t13_title: "UPDATE", t13_text: "Use UPDATE to change existing information in the database.", t13_inst: "Match the pairs:", t13_h1: "Update.", t13_h2: "Correct.", t13_q: "What does UPDATE do?", t13_qa: "Changes existing data", t13_qb: "Deletes database", t13_qc: "Creates table", t13_qd: "Nothing",
    t13_l1: "UPDATE", t13_r1: "Change", t13_l2: "SET", t13_r2: "Assign", t13_l3: "New", t13_r3: "Current",
    t14_title: "DELETE", t14_text: "Use DELETE to remove records from a table.", t14_inst: "Match the pairs:", t14_h1: "Remove.", t14_h2: "Be careful!", t14_q: "What does DELETE do?", t14_qa: "Deletes records", t14_qb: "Copies records", t14_qc: "Backs up data", t14_qd: "Makes it colorful",
    t14_l1: "DELETE", t14_r1: "Remove", t14_l2: "FROM", t14_r2: "Source", t14_l3: "Gone", t14_r3: "Deleted",
    t15_title: "Database Master", t15_text: "You now understand how computers manage large amounts of information!", t15_inst: "Match the pairs:", t15_h1: "Data expert.", t15_h2: "Learned everything.", t15_q: "What is the heart of many apps?", t15_qa: "The database", t15_qb: "The mouse", t15_qc: "The case", t15_qd: "The power cable",
    t15_l1: "Master", t15_r1: "Expert", t15_l2: "SQL", t15_r2: "Language", t15_l3: "Data", t15_r3: "Knowledge"
  },
  hu: {
    explorer_title: "Adatbázis alapok",
    t1_title: "Mi az az adatbázis?", t1_text: "Az adatbázis nagy mennyiségű adat elektronikus tárolására és kezelésére szolgáló rendszer.", t1_inst: "Párosítsd össze:", t1_h1: "Adatok rendszerezése.", t1_h2: "Digitális archívum.", t1_q: "Mire használjuk az adatbázist?", t1_qa: "Nagy mennyiségű adat tárolására", t1_qb: "Hajvágásra", t1_qc: "Főzésre", t1_qd: "Alvásra",
    t1_l1: "Adatbázis", t1_r1: "Tárolórendszer", t1_l2: "Adat", t1_r2: "Információ", t1_l3: "Struktúra", t1_r3: "Rend",
    t2_title: "A tábla", t2_text: "Az adatbázisban az adatokat táblákba szervezzük, hasonlóan az Excelhez.", t2_inst: "Párosítsd össze:", t2_h1: "Sorok és oszlopok.", t2_h2: "Alapegység.", t2_q: "Hogy hívják az adatbázis szerkezetét?", t2_qa: "Tábla", t2_qb: "Kör", t2_qc: "Felhő", t2_qd: "Pont",
    t2_l1: "Tábla", t2_r1: "Rács", t2_l2: "Négyzetháló", t2_r2: "Mátrix", t2_l3: "Név", t2_r3: "Címke",
    t3_title: "A rekord (sor)", t3_text: "A tábla egy sora egy adott dologról (pl. egy személyről) tartalmaz minden adatot.", t3_inst: "Párosítsd össze:", t3_h1: "Egy objektum.", t3_h2: "Vízszintes.", t3_q: "Mi az a rekord?", t3_qa: "Egy sor a táblában", t3_qb: "Egy egész adatbázis", t3_qc: "Egy számítógép", t3_qd: "Egy kábel",
    t3_l1: "Rekord", t3_r1: "Sor", t3_l2: "Bejegyzés", t3_r2: "Elem", t3_l3: "Objektum", t3_r3: "Egység",
    t4_title: "A mező (oszlop)", t4_text: "Az oszlop egy adott tulajdonságot határoz meg, például 'Név' vagy 'Életkor'.", t4_inst: "Párosítsd össze:", t4_h1: "Tulajdonság.", t4_h2: "Függőleges.", t4_q: "Mit ír le egy oszlop?", t4_qa: "Egy adott tulajdonságot", t4_qb: "Az egész időjárást", t4_qc: "A gép színét", t4_qd: "Semmit",
    t4_l1: "Mező", t4_r1: "Oszlop", t4_l2: "Attribútum", t4_r2: "Tulajdonság", t4_l3: "Típus", t4_r3: "Fajta",
    t5_title: "Elsődleges kulcs", t5_text: "Az elsődleges kulcs egy egyedi érték, ami azonosít minden rekordot (pl. ID).", t5_inst: "Párosítsd össze:", t5_h1: "Egyedi.", t5_h2: "Azonosítás.", t5_q: "Mit csinál az elsődleges kulcs?", t5_qa: "Egyedileg azonosítja a sorokat", t5_qb: "Bezárja az ajtót", t5_qc: "Zenél", t5_qd: "Mindent töröl",
    t5_l1: "Elsődleges kulcs", t5_r1: "ID", t5_l2: "Egyedi", t5_r2: "Unique", t5_l3: "Kulcs", t5_r3: "Azonosító",
    t6_title: "A lekérdezés", t6_text: "A lekérdezéssel (query) célzottan kereshetsz információkat az adatbázisban.", t6_inst: "Párosítsd össze:", t6_h1: "Kérdés feltevése.", t6_h2: "Keresés.", t6_q: "Mi az a lekérdezés?", t6_qa: "Egy célzott keresés", t6_qb: "Egy hiba", t6_qc: "Egy kép", t6_qd: "Egy játék",
    t6_l1: "Lekérdezés", t6_r1: "Query", t6_l2: "Keresés", t6_r2: "Találat", t6_l3: "Eredmény", t6_r3: "Lista",
    t7_title: "SELECT alap", t7_text: "A SELECT paranccsal választod ki, melyik oszlopokat szeretnéd látni.", t7_inst: "Párosítsd össze:", t7_h1: "Kiválasztás.", t7_h2: "Megjelenítés.", t7_q: "Mit csinál a SELECT?", t7_qa: "Adatokat választ ki", t7_qb: "Adatokat töröl", t7_qc: "Jelszót vált", t7_qd: "Papírt nyomtat",
    t7_l1: "SELECT", t7_r1: "Válaszd ki", t7_l2: "FROM", t7_r2: "Honnan", t7_l3: "Csillag (*)", t7_r3: "Mindent",
    t8_title: "WHERE feltétel", t8_text: "A WHERE segítségével szűrheted a találatokat (pl. csak a 18 év felettiek).", t8_inst: "Párosítsd össze:", t8_h1: "Szűrés.", t8_h2: "Feltétel.", t8_q: "Mire jó a WHERE?", t8_qa: "Adatok szűrésére", t8_qb: "Festésre", t8_qc: "Számolásra", t8_qd: "Kilépésre",
    t8_l1: "WHERE", t8_r1: "Feltétel", t8_l2: "Szűrő", t8_r2: "Korlátozás", t8_l3: "Szabály", t8_r3: "Kritérium",
    t9_title: "ORDER BY", t9_text: "Az ORDER BY paranccsal sorba rendezheted a találatokat (pl. ABC rendben).", t9_inst: "Párosítsd össze:", t9_h1: "Rendezés.", t9_h2: "Sorrend.", t9_q: "Mit csinál az ORDER BY?", t9_qa: "Sorba rendezi az adatokat", t9_qb: "Törli a táblát", t9_qc: "Fotót készít", t9_qd: "Videót játszik",
    t9_l1: "ORDER BY", t9_r1: "Rendezés", t9_l2: "ASC", t9_r2: "Növekvő", t9_l3: "DESC", t9_r3: "Csökkenő",
    t10_title: "LIMIT", t10_text: "A LIMIT segítségével korlátozhatod a megjelenített találatok számát.", t10_inst: "Párosítsd össze:", t10_h1: "Korlátozás.", t10_h2: "Mennyiség.", t10_q: "Mit csinál a LIMIT 5?", t10_qa: "Csak 5 találatot mutat", t10_qb: "500 találatot mutat", t10_qc: "Töröl 5 sort", t10_qd: "Vár 5 percet",
    t10_l1: "LIMIT", t10_r1: "Határ", t10_l2: "Szám", t10_r2: "Mennyiség", t10_l3: "Stop", t10_r3: "Vége",
    t11_title: "JOIN (Összekapcsolás)", t11_text: "A JOIN segítségével két különböző tábla adatait kapcsolhatod össze.", t11_inst: "Párosítsd össze:", t11_h1: "Összekötés.", t11_h2: "Egyesítés.", t11_q: "Mit csinál a JOIN?", t11_qa: "Táblákat kapcsol össze", t11_qb: "Táblákat választ szét", t11_qc: "Törli az adatbázist", t11_qd: "Színt vált",
    t11_l1: "JOIN", t11_r1: "Összekapcsolás", t11_l2: "Reláció", t11_r2: "Kapcsolat", t11_l3: "Idegen kulcs", t11_r3: "Link",
    t12_title: "INSERT (Beszúrás)", t12_text: "Az INSERT paranccsal új rekordot (sort) adhatsz a táblához.", t12_inst: "Párosítsd össze:", t12_h1: "Hozzáadás.", t12_h2: "Új létrehozása.", t12_q: "Mit csinál az INSERT?", t12_qa: "Új adatot ad hozzá", t12_qb: "Régi adatot töröl", t12_qc: "Adatot keres", t12_qd: "Adatot rendez",
    t12_l1: "INSERT", t12_r1: "Beszúrás", t12_l2: "INTO", t12_r2: "Hova", t12_l3: "VALUES", t12_r3: "Értékek",
    t13_title: "UPDATE (Módosítás)", t13_text: "Az UPDATE paranccsal megváltoztathatod a már meglévő adatokat.", t13_inst: "Párosítsd össze:", t13_h1: "Frissítés.", t13_h2: "Javítás.", t13_q: "Mit csinál az UPDATE?", t13_qa: "Módosítja az adatokat", t13_qb: "Törli az adatbázist", t13_qc: "Táblát készít", t13_qd: "Semmit",
    t13_l1: "UPDATE", t13_r1: "Módosítás", t13_l2: "SET", t13_r2: "Beállítás", t13_l3: "Új", t13_r3: "Aktuális",
    t14_title: "DELETE (Törlés)", t14_text: "A DELETE paranccsal rekordokat törölhetsz a táblából.", t14_inst: "Párosítsd össze:", t14_h1: "Eltávolítás.", t14_h2: "Vigyázz!", t14_q: "Mit csinál a DELETE?", t14_qa: "Sorokat töröl", t14_qb: "Sorokat másol", t14_qc: "Adatot ment", t14_qd: "Színessé tesz",
    t14_l1: "DELETE", t14_r1: "Törlés", t14_l2: "FROM", t14_r2: "Honnan", t14_l3: "Eltűnik", t14_r3: "Törölve",
    t15_title: "Adatbázis mester", t15_text: "Most már érted, hogyan kezelik a gépek az óriási információhalmazokat!", t15_inst: "Párosítsd össze:", t15_h1: "Adat-szakértő.", t15_h2: "Mindent megtanultál.", t15_q: "Mi a legtöbb applikáció szíve?", t15_qa: "Az adatbázis", t15_qb: "Az egér", t15_qc: "A gépház", t15_qd: "A tápkábel",
    t15_l1: "Mester", t15_r1: "Szakértő", t15_l2: "SQL", t15_r2: "Nyelv", t15_l3: "Adat", t15_r3: "Tudás"
  },
  ro: {
    explorer_title: "Baze de Date",
    t1_title: "Ce este o Bază de Date?", t1_text: "O bază de date este un sistem pentru gestionarea electronică a unor cantități mari de date.", t1_inst: "Potrivește perechile:", t1_h1: "Organizează datele.", t1_h2: "Arhivă digitală.", t1_q: "La ce se folosește o bază de date?", t1_qa: "Stocarea cantităților mari de date", t1_qb: "Tunsul părului", t1_qc: "Gătit", t1_qd: "Dormit",
    t1_l1: "Bază de date", t1_r1: "Sistem stocare", t1_l2: "Date", t1_r2: "Informații", t1_l3: "Structură", t1_r3: "Ordine",
    t2_title: "Tabelul", t2_text: "Într-o bază de date, datele sunt organizate în tabele, similar cu Excel.", t2_inst: "Potrivește perechile:", t2_h1: "Rânduri și coloane.", t2_h2: "Unitate de bază.", t2_q: "Cum se numește structura dintr-o bază de date?", t2_qa: "Tabel", t2_qb: "Cerc", t2_qc: "Nor", t2_qd: "Punct",
    t2_l1: "Tabel", t2_r1: "Grilă", t2_l2: "Caroiaj", t2_r2: "Matrice", t2_l3: "Nume", t2_r3: "Etichetă",
    t3_title: "Înregistrarea (Rândul)", t3_text: "Un rând dintr-un tabel conține toate informațiile despre un anumit obiect.", t3_inst: "Potrivește perechile:", t3_h1: "Un obiect.", t3_h2: "Orizontal.", t3_q: "Ce este o înregistrare?", t3_qa: "Un rând în tabel", t3_qb: "O bază de date întreagă", t3_qc: "Un computer", t3_qd: "Un cablu",
    t3_l1: "Înregistrare", t3_r1: "Rând", t3_l2: "Intrare", t3_r2: "Element", t3_l3: "Obiect", t3_r3: "Unitate",
    t4_title: "Câmpul (Coloana)", t4_text: "O coloană definește o anumită proprietate, cum ar fi 'Nume' sau 'Vârstă'.", t4_inst: "Potrivește perechile:", t4_h1: "Proprietate.", t4_h2: "Vertical.", t4_q: "Ce descrie o coloană?", t4_qa: "O anumită proprietate", t4_qb: "Toată vremea", t4_qc: "Culoarea PC", t4_qd: "Nimic",
    t4_l1: "Câmp", t4_r1: "Coloană", t4_l2: "Atribut", t4_r2: "Proprietate", t4_l3: "Tip", t4_r3: "Fel",
    t5_title: "Cheie Primară", t5_text: "O cheie primară este o valoare unică ce identifică fiecare înregistrare (ex. ID).", t5_inst: "Potrivește perechile:", t5_h1: "Unic.", t5_h2: "Identificare.", t5_q: "Ce face o cheie primară?", t5_qa: "Identifică unic rândurile", t5_qb: "Încuie ușa", t5_qc: "Face muzică", t5_qd: "Șterge tot",
    t5_l1: "Cheie primară", t5_r1: "ID", t5_l2: "Unic", t5_r2: "Singular", t5_l3: "Cheie", t5_r3: "Identificator",
    t6_title: "Interogarea", t6_text: "Cu o interogare (query), cauți informații specifice în baza de date.", t6_inst: "Potrivește perechile:", t6_h1: "Pune o întrebare.", t6_h2: "Caută.", t6_q: "Ce este o interogare?", t6_qa: "O căutare țintită", t6_qb: "O eroare", t6_qc: "O imagine", t6_qd: "Un joc",
    t6_l1: "Interogare", t6_r1: "Query", t6_l2: "Căutare", t6_r2: "Găsire", t6_l3: "Rezultat", t6_r3: "Listă",
    t7_title: "SELECT de bază", t7_text: "Cu comanda SELECT alegi ce coloane vrei să vezi.", t7_inst: "Potrivește perechile:", t7_h1: "Selectează.", t7_h2: "Afișează.", t7_q: "Ce face SELECT?", t7_qa: "Selectează date", t7_qb: "Șterge date", t7_qc: "Schimbă parola", t7_qd: "Tipărește hârtie",
    t7_l1: "SELECT", t7_r1: "Alege", t7_l2: "FROM", t7_r2: "Sursă", t7_l3: "Asterisc (*)", t7_r3: "Tot",
    t8_title: "Condiția WHERE", t8_text: "Cu WHERE poți filtra rezultatele (ex. doar persoanele peste 18 ani).", t8_inst: "Potrivește perechile:", t8_h1: "Filtrare.", t8_h2: "Condiție.", t8_q: "La ce folosește WHERE?", t8_qa: "Filtrarea datelor", t8_qb: "Pictat", t8_qc: "Calculat", t8_qd: "Ieșire",
    t8_l1: "WHERE", t8_r1: "Condiție", t8_l2: "Filtru", t8_r2: "Limită", t8_l3: "Criteriu", t8_r3: "Regulă",
    t9_title: "ORDER BY", t9_text: "Cu ORDER BY sortezi rezultatele (ex. alfabetic).", t9_inst: "Potrivește perechile:", t9_h1: "Sortare.", t9_h2: "Secvență.", t9_q: "Ce face ORDER BY?", t9_qa: "Sortează rezultatele", t9_qb: "Șterge tabelul", t9_qc: "Face o poză", t9_qd: "Redă un video",
    t9_l1: "ORDER BY", t9_r1: "Sortează", t9_l2: "ASC", t9_r2: "Ascendent", t9_l3: "DESC", t9_r3: "Descendent",
    t10_title: "LIMIT", t10_text: "Cu LIMIT restricționezi numărul de rezultate afișate.", t10_inst: "Potrivește perechile:", t10_h1: "Restricție.", t10_h2: "Cantitate.", t10_q: "Ce face LIMIT 5?", t10_qa: "Arată doar 5 rezultate", t10_qb: "Arată 500 rezultate", t10_qc: "Șterge 5 rânduri", t10_qd: "Așteaptă 5 minute",
    t10_l1: "LIMIT", t10_r1: "Limită", t10_l2: "Număr", t10_r2: "Cantitate", t10_l3: "Stop", t10_r3: "Final",
    t11_title: "JOIN (Legătură)", t11_text: "Cu JOIN poți combina date din două tabele diferite.", t11_inst: "Potrivește perechile:", t11_h1: "Conectare.", t11_h2: "Fuziune.", t11_q: "Ce face un JOIN?", t11_qa: "Leagă tabele", t11_qb: "Separă tabele", t11_qc: "Șterge baza de date", t11_qd: "Schimbă culoarea",
    t11_l1: "JOIN", t11_r1: "Conectare", t11_l2: "Relație", t11_r2: "Legătură", t11_l3: "Cheie externă", t11_r3: "Referință",
    t12_title: "INSERT", t12_text: "Cu INSERT adaugi o înregistrare nouă în tabel.", t12_inst: "Potrivește perechile:", t12_h1: "Adăugare.", t12_h2: "Creare nouă.", t12_q: "Ce face INSERT?", t12_qa: "Adaugă date noi", t12_qb: "Șterge date vechi", t12_qc: "Caută date", t12_qd: "Sortează date",
    t12_l1: "INSERT", t12_r1: "Adaugă", t12_l2: "INTO", t12_r2: "În", t12_l3: "VALUES", t12_r3: "Valori",
    t13_title: "UPDATE", t13_text: "Cu UPDATE poți modifica informațiile existente în baza de date.", t13_inst: "Potrivește perechile:", t13_h1: "Actualizare.", t13_h2: "Corectare.", t13_q: "Ce face UPDATE?", t13_qa: "Modifică datele existente", t13_qb: "Șterge baza de date", t13_qc: "Creează tabel", t13_qd: "Nimic",
    t13_l1: "UPDATE", t13_r1: "Modifică", t13_l2: "SET", t13_r2: "Setează", t13_l3: "Nou", t13_r3: "Actual",
    t14_title: "DELETE", t14_text: "Cu DELETE elimini înregistrări dintr-un tabel.", t14_inst: "Potrivește perechile:", t14_h1: "Eliminare.", t14_h2: "Atenție!", t14_q: "Ce face DELETE?", t14_qa: "Șterge înregistrări", t14_qb: "Copiază înregistrări", t14_qc: "Salvează date", t14_qd: "Face totul colorat",
    t14_l1: "DELETE", t14_r1: "Șterge", t14_l2: "FROM", t14_r2: "Din", t14_l3: "Dispărut", t14_r3: "Eliminat",
    t15_title: "Maestru Baze de Date", t15_text: "Acum înțelegi cum gestionează computerele cantități uriașe de informații!", t15_inst: "Potrivește perechile:", t15_h1: "Expert date.", t15_h2: "Ai învățat totul.", t15_q: "Ce este inima multor aplicații?", t15_qa: "Baza de date", t15_qb: "Mouse-ul", t15_qc: "Carcasa", t15_qd: "Cablul de curent",
    t15_l1: "Maestru", t15_r1: "Expert", t15_l2: "SQL", t15_r2: "Limbaj", t15_l3: "Date", t15_r3: "Cunoaștere"
  }
};

export const INFO_K3_I8_POOL: PoolTopicDef[] = Array.from({ length: 15 }, (_, i) => {
  const t = i + 1;
  const icons = ["🗄️", "📊", "➖", "📋", "🔑", "🔍", "✅", "⏳", "↕️", "🛑", "🔗", "➕", "📝", "❌", "🏆"];
  const colors = ["#607D8B", "#3F51B5", "#9E9E9E", "#2196F3", "#FFC107", "#00BCD4", "#4CAF50", "#FF9800", "#9C27B0", "#F44336", "#009688", "#E91E63", "#FF5722", "#795548", "#FFD700"];
  
  return {
    infoTitle: `t${t}_title`, infoText: `t${t}_text`,
    svg: { type: "simple-icon", icon: icons[i], color: colors[i] },
    interactive: { 
      type: "match-pairs", 
      instruction: `t${t}_inst`, 
      hint1: `t${t}_h1`, 
      hint2: `t${t}_h2`, 
      pairs: [{left:`t${t}_l1`,right:`t${t}_r1`},{left:`t${t}_l2`,right:`t${t}_r2`},{left:`t${t}_l3`,right:`t${t}_r3`}] 
    },
    quiz: { question: `t${t}_q`, choices: [`t${t}_qa`, `t${t}_qb`, `t${t}_qc`, `t${t}_qd`], answer: `t${t}_qa` }
  };
});
