// lib/explorerPools/informatikaK8_i8.ts
import type { PoolTopicDef } from "./types";

export const INFO_K8_I8_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Maschinelles Lernen",
    t1_title: "Überwachtes Lernen", t1_text: "Beim überwachten Lernen werden dem Modell Beispiele mit bekannten Ergebnissen (Labels) gegeben. Es lernt, Muster zu erkennen und Vorhersagen zu machen.",
    t1_inst: "Ordne die Lernarten zu:", t1_l1: "Überwacht", t1_r1: "mit bekannten Labels", t1_l2: "Unüberwacht", t1_r2: "Muster ohne Labels", t1_l3: "Bestärkend", t1_r3: "Belohnung und Strafe",
    t1_q: "Was ist das Merkmal des überwachten Lernens?", t1_qa: "Lernen aus gelabelten Daten", t1_qb: "Lernen ohne jegliche Daten", t1_qc: "Manuelle Programmierung", t1_qd: "Zufällige Entscheidungen",
    t2_title: "Klassifikation", t2_text: "Klassifikation ist eine ML-Aufgabe, bei der das Modell Eingaben einer Kategorie zuordnet, z.B. E-Mail als Spam oder kein Spam.",
    t2_inst: "Fülle die Lücke aus:", t2_sent: "Beim Filter ordnet das Modell eine E-Mail als ___ oder Nicht-Spam ein.", t2_qa2: "Spam", t2_qb2: "Zahl", t2_qc2: "Bild", t2_qd2: "Video",
    t2_q: "Was ist das Ziel der Klassifikation?", t2_qa: "Eingaben einer Kategorie zuordnen", t2_qb: "Einen Zahlenwert vorhersagen", t2_qc: "Daten komprimieren", t2_qd: "Webseiten übersetzen",
    t3_title: "Regression", t3_text: "Regression ist eine Aufgabe, bei der das Modell einen kontinuierlichen Zahlenwert vorhersagt, z.B. den Preis eines Hauses.",
    t3_inst: "Sortiere den Satz:", t3_w1: "Regression", t3_w2: "sagt", t3_w3: "einen", t3_w4: "Zahlenwert", t3_w5: "voraus.",
    t3_q: "Was sagt ein Regressionsmodell voraus?", t3_qa: "Einen kontinuierlichen Zahlenwert", t3_qb: "Eine von mehreren Kategorien", t3_qc: "Einen Dateinamen", t3_qd: "Eine IP-Adresse",
    t4_title: "Datensatz (Dataset)", t4_text: "Ein Datensatz ist eine Sammlung strukturierter Daten für das Training. Qualität und Menge sind entscheidend.",
    t4_inst: "Sortiere:", t4_bl1: "Gut für ML", t4_bl2: "Schlecht für ML", t4_i1: "Qualitative Daten", t4_i2: "Ausgewogene Daten", t4_i3: "Fehlerhafte Daten", t4_i4: "Verzerrte Daten",
    t4_q: "Warum ist die Qualität des Datensatzes wichtig?", t4_qa: "Bessere Daten = genauere Modelle", t4_qb: "Mehr Daten = langsameres Modell", t4_qc: "Daten müssen manuell sein", t4_qd: "Weniger Daten sind besser",
    t5_title: "Overfitting", t5_text: "Overfitting tritt auf, wenn ein Modell Trainingsdaten zu gut auswendig lernt und bei neuen Daten schlecht ist.",
    t5_inst: "Markiere das Problem:", t5_tk1: "Das Modell", t5_tk2: "lernt", t5_tk3: "die Trainingsdaten", t5_tk4: "auswendig.",
    t5_q: "Was passiert bei Overfitting?", t5_qa: "Schlechte Generalisierung auf neue Daten", t5_qb: "Das Modell lernt gar nichts", t5_qc: "Es wird unendlich schnell", t5_qd: "Es löscht den Datensatz",
    t6_title: "Trainings- vs Testdaten", t6_text: "Trainingsdaten werden zum Lernen verwendet, Testdaten zur Bewertung des Modells mit unbekannten Daten.",
    t6_inst: "Verbinde:", t6_l1: "Trainingsdaten", t6_r1: "Zum Lernen", t6_l2: "Testdaten", t6_r2: "Zur Bewertung", t6_l3: "Validierungsdaten", t6_r3: "Zur Optimierung",
    t6_q: "Wofür sind Testdaten?", t6_qa: "Zur Bewertung der Modellleistung", t6_qb: "Zum Auswendiglernen", t6_qc: "Um das Modell zu verlangsamen", t6_qd: "Für die Benutzeroberfläche",
    t7_title: "Underfitting", t7_text: "Underfitting bedeutet, das Modell ist zu einfach und kann die Muster in den Trainingsdaten nicht richtig erfassen.",
    t7_inst: "Baue den Satz:", t7_f1: "Ein", t7_f2: "zu einfaches Modell", t7_f3: "führt zu", t7_f4: "Underfitting.",
    t7_q: "Was ist Underfitting?", t7_qa: "Modell ist zu simpel für die Daten", t7_qb: "Modell lernt die Daten auswendig", t7_qc: "Modell hat zu viele Parameter", t7_qd: "Modell stürzt ab",
    t8_title: "Entscheidungsbäume", t8_text: "Entscheidungsbäume fällen Entscheidungen durch eine Reihe von Ja/Nein-Fragen, ähnlich wie ein Flussdiagramm.",
    t8_inst: "Fülle die Lücke:", t8_sent: "Ein Entscheidungsbaum nutzt ___ zur Klassifikation.", t8_qa8: "Ja/Nein-Fragen", t8_qb8: "Zufallszahlen", t8_qc8: "Bilder", t8_qd8: "Neutrinos",
    t8_q: "Wie funktioniert ein Entscheidungsbaum?", t8_qa: "Mit verschachtelten Wenn-Dann-Regeln", t8_qb: "Mit komplexen Differentialgleichungen", t8_qc: "Durch reines Raten", t8_qd: "Mit unüberwachtem Lernen",
    t9_title: "Klassifikation vs Regression", t9_text: "Klassifikation sagt Kategorien (z.B. Hund/Katze) voraus, Regression sagt numerische Werte (z.B. Preis) voraus.",
    t9_inst: "Sortiere:", t9_bl1: "Klassifikation", t9_bl2: "Regression", t9_i1: "Spam-Filter", t9_i2: "Hundeart erkennen", t9_i3: "Hauspreis schätzen", t9_i4: "Aktienkurs vorhersagen",
    t9_q: "Welches ist ein Regressionsproblem?", t9_qa: "Den Preis eines Autos vorhersagen", t9_qb: "Ein Bild als Katze oder Hund erkennen", t9_qc: "Eine E-Mail als Spam markieren", t9_qd: "Die Sprache eines Textes erkennen",
    t10_title: "Clustering", t10_text: "Clustering gruppiert ähnliche Datenpunkte ohne vorherige Labels. Es gehört zum unüberwachten Lernen.",
    t10_inst: "Ordne:", t10_w1: "Clustering", t10_w2: "gruppiert", t10_w3: "ähnliche", t10_w4: "Datenpunkte", t10_w5: "zusammen.",
    t10_q: "Zu welcher Lernart gehört Clustering?", t10_qa: "Unüberwachtes Lernen", t10_qb: "Überwachtes Lernen", t10_qc: "Bestärkendes Lernen", t10_qd: "Manuelles Lernen",
    t11_title: "Künstliche Neuronen", t11_text: "Künstliche Neuronen sind die Bausteine neuronaler Netze. Sie empfangen Eingaben, gewichten diese und erzeugen eine Ausgabe.",
    t11_inst: "Verbinde:", t11_l1: "Eingabe", t11_r1: "Daten", t11_l2: "Gewicht", t11_r2: "Bedeutung", t11_l3: "Aktivierung", t11_r3: "Ausgabe",
    t11_q: "Was simulieren künstliche Neuronen grob?", t11_qa: "Biologische Nervenzellen", t11_qb: "Computermonitore", t11_qc: "Datenbanken", t11_qd: "Tastaturen",
    t12_title: "Epochen & Iterationen", t12_text: "Eine Epoche ist ein kompletter Durchlauf aller Trainingsdaten. Eine Iteration verarbeitet einen kleinen Teil (Batch) der Daten.",
    t12_inst: "Markiere:", t12_tk1: "Eine", t12_tk2: "Epoche", t12_tk3: "nutzt", t12_tk4: "alle", t12_tk5: "Trainingsdaten.",
    t12_q: "Was ist eine Epoche beim Training?", t12_qa: "Ein voller Durchlauf der Trainingsdaten", t12_qb: "Ein einzelner Datenpunkt", t12_qc: "Eine Fehlermeldung", t12_qd: "Ein neues Modell",
    t13_title: "Gradientenabstieg", t13_text: "Ein Optimierungsalgorithmus, der versucht, den Fehler des Modells zu minimieren, indem er Gewichte schrittweise anpasst.",
    t13_inst: "Baue den Satz:", t13_f1: "Der", t13_f2: "Gradientenabstieg", t13_f3: "minimiert den", t13_f4: "Fehler.",
    t13_q: "Was ist das Ziel des Gradientenabstiegs?", t13_qa: "Den Fehler minimieren", t13_qb: "Den Datensatz vergrößern", t13_qc: "Die Geschwindigkeit drosseln", t13_qd: "Das Modell löschen",
    t14_title: "Datasets (Datenmengen)", t14_text: "Riesige, unstrukturierte Datenmengen (Big Data) bilden das Fundament vieler moderner KI-Modelle wie ChatGPT.",
    t14_inst: "Fülle die Lücke:", t14_sent: "Große KI-Modelle benötigen riesige ___.", t14_qa14: "Datenmengen", t14_qb14: "Bildschirme", t14_qc14: "Tastaturen", t14_qd14: "Mäuse",
    t14_q: "Warum brauchen moderne KI-Modelle Big Data?", t14_qa: "Um komplexe Muster in Sprache und Bild zu lernen", t14_qb: "Um Festplattenplatz zu verschwenden", t14_qc: "Damit sie langsamer werden", t14_qd: "Nur für Marketingzwecke",
    t15_title: "Feature Engineering", t15_text: "Der Prozess, rohe Daten in nützliche Merkmale (Features) umzuwandeln, um dem ML-Modell das Lernen zu erleichtern.",
    t15_inst: "Sortiere:", t15_bl1: "Rohe Daten", t15_bl2: "Features", t15_i1: "Datum", t15_i2: "Rohtext", t15_i3: "Wortanzahl", t15_i4: "Wochentag",
    t15_q: "Was ist das Ziel von Feature Engineering?", t15_qa: "Daten in nützlichere Formen für das Modell zu bringen", t15_qb: "Das Modell komplett zu programmieren", t15_qc: "Alle Daten zu löschen", t15_qd: "Fehler in den Daten zu erzeugen",
  },
  en: {
    explorer_title: "Machine Learning",
    t1_title: "Supervised Learning", t1_text: "In supervised learning, the model is given examples with known outcomes (labels). It learns to recognize patterns and make predictions.",
    t1_inst: "Match the learning types:", t1_l1: "Supervised", t1_r1: "known labels", t1_l2: "Unsupervised", t1_r2: "no labels", t1_l3: "Reinforcement", t1_r3: "reward & punishment",
    t1_q: "What characterizes supervised learning?", t1_qa: "Learning from labeled data", t1_qb: "Learning without any data", t1_qc: "Manual programming", t1_qd: "Random guessing",
    t2_title: "Classification", t2_text: "Classification is an ML task where the model assigns inputs to a category, e.g., an email as spam or not spam.",
    t2_inst: "Fill the gap:", t2_sent: "The filter classifies an email as ___ or not spam.", t2_qa2: "spam", t2_qb2: "number", t2_qc2: "image", t2_qd2: "video",
    t2_q: "What is the goal of classification?", t2_qa: "Assign inputs to a category", t2_qb: "Predict a numerical value", t2_qc: "Compress data", t2_qd: "Translate websites",
    t3_title: "Regression", t3_text: "Regression is a task where the model predicts a continuous numerical value, such as the price of a house.",
    t3_inst: "Order the sentence:", t3_w1: "Regression", t3_w2: "predicts", t3_w3: "a", t3_w4: "continuous", t3_w5: "value.",
    t3_q: "What does a regression model predict?", t3_qa: "A continuous numerical value", t3_qb: "One of several categories", t3_qc: "A file name", t3_qd: "An IP address",
    t4_title: "Dataset", t4_text: "A dataset is a collection of structured data for training. Quality and quantity are crucial.",
    t4_inst: "Sort:", t4_bl1: "Good for ML", t4_bl2: "Bad for ML", t4_i1: "High quality data", t4_i2: "Balanced data", t4_i3: "Erroneous data", t4_i4: "Biased data",
    t4_q: "Why is dataset quality important?", t4_qa: "Better data = more accurate models", t4_qb: "More data = slower models", t4_qc: "Data must be manual", t4_qd: "Fewer data is better",
    t5_title: "Overfitting", t5_text: "Overfitting occurs when a model memorizes the training data too well and performs poorly on new data.",
    t5_inst: "Highlight the issue:", t5_tk1: "The model", t5_tk2: "memorizes", t5_tk3: "the", t5_tk4: "training data.",
    t5_q: "What happens during overfitting?", t5_qa: "Poor generalization to new data", t5_qb: "The model learns nothing", t5_qc: "It becomes infinitely fast", t5_qd: "It deletes the dataset",
    t6_title: "Training vs Test Data", t6_text: "Training data is used for learning, test data is used to evaluate the model on unseen data.",
    t6_inst: "Match:", t6_l1: "Training data", t6_r1: "For learning", t6_l2: "Test data", t6_r2: "For evaluation", t6_l3: "Validation data", t6_r3: "For tuning",
    t6_q: "What is test data for?", t6_qa: "To evaluate model performance", t6_qb: "For memorization", t6_qc: "To slow down the model", t6_qd: "For the user interface",
    t7_title: "Underfitting", t7_text: "Underfitting means the model is too simple and cannot properly capture the patterns in the training data.",
    t7_inst: "Build the sentence:", t7_f1: "A", t7_f2: "too simple model", t7_f3: "leads to", t7_f4: "underfitting.",
    t7_q: "What is underfitting?", t7_qa: "Model is too simple for the data", t7_qb: "Model memorizes the data", t7_qc: "Model has too many parameters", t7_qd: "Model crashes",
    t8_title: "Decision Trees", t8_text: "Decision trees make choices through a series of yes/no questions, similar to a flowchart.",
    t8_inst: "Fill the gap:", t8_sent: "A decision tree uses ___ to classify data.", t8_qa8: "yes/no questions", t8_qb8: "random numbers", t8_qc8: "images", t8_qd8: "neutrinos",
    t8_q: "How does a decision tree work?", t8_qa: "With nested if-then rules", t8_qb: "With complex differential equations", t8_qc: "By pure guessing", t8_qd: "With unsupervised learning",
    t9_title: "Classification vs Regression", t9_text: "Classification predicts categories (e.g. dog/cat), regression predicts numerical values (e.g. price).",
    t9_inst: "Sort:", t9_bl1: "Classification", t9_bl2: "Regression", t9_i1: "Spam filter", t9_i2: "Identify dog breed", t9_i3: "Estimate house price", t9_i4: "Predict stock price",
    t9_q: "Which of these is a regression problem?", t9_qa: "Predicting the price of a car", t9_qb: "Recognizing an image as a cat or dog", t9_qc: "Marking an email as spam", t9_qd: "Detecting the language of a text",
    t10_title: "Clustering", t10_text: "Clustering groups similar data points together without prior labels. It is part of unsupervised learning.",
    t10_inst: "Order:", t10_w1: "Clustering", t10_w2: "groups", t10_w3: "similar", t10_w4: "data", t10_w5: "together.",
    t10_q: "Which learning type includes clustering?", t10_qa: "Unsupervised learning", t10_qb: "Supervised learning", t10_qc: "Reinforcement learning", t10_qd: "Manual learning",
    t11_title: "Artificial Neurons", t11_text: "Artificial neurons are the building blocks of neural networks. They receive inputs, weigh them, and produce an output.",
    t11_inst: "Match:", t11_l1: "Input", t11_r1: "Data", t11_l2: "Weight", t11_r2: "Importance", t11_l3: "Activation", t11_r3: "Output",
    t11_q: "What do artificial neurons roughly simulate?", t11_qa: "Biological nerve cells", t11_qb: "Computer monitors", t11_qc: "Databases", t11_qd: "Keyboards",
    t12_title: "Epochs & Iterations", t12_text: "An epoch is one complete pass through all training data. An iteration processes a small batch of data.",
    t12_inst: "Highlight:", t12_tk1: "An", t12_tk2: "epoch", t12_tk3: "uses", t12_tk4: "all", t12_tk5: "training data.",
    t12_q: "What is an epoch during training?", t12_qa: "A full pass through the training data", t12_qb: "A single data point", t12_qc: "An error message", t12_qd: "A new model",
    t13_title: "Gradient Descent", t13_text: "An optimization algorithm that tries to minimize the model's error by adjusting weights step by step.",
    t13_inst: "Build the sentence:", t13_f1: "Gradient", t13_f2: "descent", t13_f3: "minimizes", t13_f4: "the error.",
    t13_q: "What is the goal of gradient descent?", t13_qa: "To minimize the error", t13_qb: "To expand the dataset", t13_qc: "To reduce speed", t13_qd: "To delete the model",
    t14_title: "Datasets (Big Data)", t14_text: "Huge amounts of unstructured data form the foundation of many modern AI models like ChatGPT.",
    t14_inst: "Fill the gap:", t14_sent: "Large AI models require massive ___.", t14_qa14: "datasets", t14_qb14: "screens", t14_qc14: "keyboards", t14_qd14: "mice",
    t14_q: "Why do modern AI models need big data?", t14_qa: "To learn complex patterns in text and images", t14_qb: "To waste storage space", t14_qc: "To slow them down", t14_qd: "Only for marketing purposes",
    t15_title: "Feature Engineering", t15_text: "The process of transforming raw data into useful features to make learning easier for the ML model.",
    t15_inst: "Sort:", t15_bl1: "Raw Data", t15_bl2: "Features", t15_i1: "Date", t15_i2: "Raw text", t15_i3: "Word count", t15_i4: "Day of week",
    t15_q: "What is the goal of feature engineering?", t15_qa: "To transform data into more useful formats for the model", t15_qb: "To program the model entirely", t15_qc: "To delete all data", t15_qd: "To introduce errors in the data",
  },
  hu: {
    explorer_title: "Gépi Tanulás",
    t1_title: "Felügyelt tanulás", t1_text: "A felügyelt tanulás során a modellnek ismert eredményű (címkézett) példákat adunk. Mintákat tanul felismerni és jósolni.",
    t1_inst: "Párosítsd a típusokat:", t1_l1: "Felügyelt", t1_r1: "címkézett adatok", t1_l2: "Felügyelet nélküli", t1_r2: "címke nélkül", t1_l3: "Megerősítéses", t1_r3: "jutalom és büntetés",
    t1_q: "Mi jellemzi a felügyelt tanulást?", t1_qa: "Tanulás címkézett adatokból", t1_qb: "Tanulás adatok nélkül", t1_qc: "Kézi programozás", t1_qd: "Véletlenszerű tippelés",
    t2_title: "Osztályozás", t2_text: "Az osztályozás egy feladat, ahol a modell egy kategóriába sorolja a bemenetet, pl. spam vagy nem spam e-mail.",
    t2_inst: "Pótold a hiányzót:", t2_sent: "A szűrő egy e-mailt ___ vagy nem spam kategóriába sorol.", t2_qa2: "spam", t2_qb2: "szám", t2_qc2: "kép", t2_qd2: "videó",
    t2_q: "Mi az osztályozás célja?", t2_qa: "Bemenetek kategóriába sorolása", t2_qb: "Számérték előrejelzése", t2_qc: "Adattömörítés", t2_qd: "Weboldalak fordítása",
    t3_title: "Regresszió", t3_text: "A regresszió során a modell egy folytonos számértéket jósol meg, például egy ház árát.",
    t3_inst: "Rendezd a mondatot:", t3_w1: "A regresszió", t3_w2: "folytonos", t3_w3: "számértéket", t3_w4: "jósol", t3_w5: "meg.",
    t3_q: "Mit jósol meg egy regressziós modell?", t3_qa: "Folytonos számértéket", t3_qb: "Egyet a több kategória közül", t3_qc: "Egy fájlnevet", t3_qd: "Egy IP-címet",
    t4_title: "Adathalmaz", t4_text: "Az adathalmaz strukturált adatok gyűjteménye a tanításhoz. A minőség és a mennyiség kulcsfontosságú.",
    t4_inst: "Válogasd szét:", t4_bl1: "Jó az ML-hez", t4_bl2: "Rossz az ML-hez", t4_i1: "Kiváló minőség", t4_i2: "Kiegyensúlyozott", t4_i3: "Hibás adatok", t4_i4: "Torzított adatok",
    t4_q: "Miért fontos az adathalmaz minősége?", t4_qa: "Jobb adatok = pontosabb modellek", t4_qb: "Több adat = lassabb modellek", t4_qc: "Az adatokat kézzel kell bevinni", t4_qd: "Kevesebb adat mindig jobb",
    t5_title: "Túltanulás (Overfitting)", t5_text: "Túltanulás akkor lép fel, ha a modell túl jól bemagolja a tanítási adatokat, és új adatokon rosszul teljesít.",
    t5_inst: "Jelöld ki a problémát:", t5_tk1: "A modell", t5_tk2: "bemagolja", t5_tk3: "a", t5_tk4: "tanítási adatokat.",
    t5_q: "Mi történik túltanuláskor?", t5_qa: "Gyenge általánosítás új adatokra", t5_qb: "A modell semmit sem tanul", t5_qc: "Végtelenül gyors lesz", t5_qd: "Törli az adathalmazt",
    t6_title: "Tanítási vs Tesztadatok", t6_text: "A tanítási adatokból tanul a modell, a tesztadatokkal pedig az új adatokon nyújtott teljesítményt mérjük.",
    t6_inst: "Párosítsd:", t6_l1: "Tanítási adatok", t6_r1: "Tanuláshoz", t6_l2: "Tesztadatok", t6_r2: "Értékeléshez", t6_l3: "Validációs adatok", t6_r3: "Finomhangoláshoz",
    t6_q: "Mire valók a tesztadatok?", t6_qa: "A modell teljesítményének mérésére", t6_qb: "Bemagolásra", t6_qc: "A modell lelassítására", t6_qd: "A felhasználói felülethez",
    t7_title: "Alultanulás (Underfitting)", t7_text: "Alultanulás jelentése: a modell túl egyszerű, és nem tudja megfelelően megragadni a mintákat az adatokban.",
    t7_inst: "Építs mondatot:", t7_f1: "Egy", t7_f2: "túl egyszerű modell", t7_f3: "alultanuláshoz", t7_f4: "vezet.",
    t7_q: "Mi az alultanulás?", t7_qa: "A modell túl egyszerű az adatokhoz", t7_qb: "A modell bemagolja az adatokat", t7_qc: "Túl sok paramétere van", t7_qd: "A modell összeomlik",
    t8_title: "Döntési fák", t8_text: "A döntési fák igen/nem kérdések sorozatán keresztül hoznak döntéseket, hasonlóan egy folyamatábrához.",
    t8_inst: "Pótold a hiányzót:", t8_sent: "Egy döntési fa ___ segítségével osztályoz.", t8_qa8: "igen/nem kérdések", t8_qb8: "véletlenszámok", t8_qc8: "képek", t8_qd8: "neutrínók",
    t8_q: "Hogyan működik egy döntési fa?", t8_qa: "Egymásba ágyazott ha-akkor szabályokkal", t8_qb: "Komplex differenciálegyenletekkel", t8_qc: "Puszta találgatással", t8_qd: "Felügyelet nélküli tanulással",
    t9_title: "Osztályozás vs Regresszió", t9_text: "Az osztályozás kategóriákat (pl. kutya/macska), a regresszió számértékeket (pl. ár) jósol.",
    t9_inst: "Válogasd szét:", t9_bl1: "Osztályozás", t9_bl2: "Regresszió", t9_i1: "Spamszűrő", t9_i2: "Kutyafajta", t9_i3: "Házár becslés", t9_i4: "Részvényárfolyam",
    t9_q: "Melyik egy regressziós probléma?", t9_qa: "Egy autó árának megjóslása", t9_qb: "Kép felismerése kutyaként", t9_qc: "E-mail spamnek jelölése", t9_qd: "Egy szöveg nyelvének felismerése",
    t10_title: "Klaszterezés", t10_text: "A klaszterezés hasonló adatpontokat csoportosít előzetes címkék nélkül. Ez felügyelet nélküli tanulás.",
    t10_inst: "Rendezd:", t10_w1: "A klaszterezés", t10_w2: "hasonló", t10_w3: "adatokat", t10_w4: "csoportosít", t10_w5: "egybe.",
    t10_q: "Milyen típusú tanulás a klaszterezés?", t10_qa: "Felügyelet nélküli tanulás", t10_qb: "Felügyelt tanulás", t10_qc: "Megerősítéses tanulás", t10_qd: "Kézi tanulás",
    t11_title: "Mesterséges Neuronok", t11_text: "A mesterséges neuronok a neurális hálózatok építőkövei. Bemenetet kapnak, súlyozzák, majd kimenetet adnak.",
    t11_inst: "Párosítsd:", t11_l1: "Bemenet", t11_r1: "Adat", t11_l2: "Súly", t11_r2: "Fontosság", t11_l3: "Aktiváció", t11_r3: "Kimenet",
    t11_q: "Mit szimulálnak nagyjából a mesterséges neuronok?", t11_qa: "Biológiai idegsejteket", t11_qb: "Számítógép monitorokat", t11_qc: "Adatbázisokat", t11_qd: "Billentyűzeteket",
    t12_title: "Epokák és Iterációk", t12_text: "Egy epoka a teljes tanítási adathalmaz egy bejárása. Egy iteráció csak egy kis adag (batch) feldolgozása.",
    t12_inst: "Jelöld ki:", t12_tk1: "Egy epoka", t12_tk2: "alatt", t12_tk3: "minden", t12_tk4: "tanítási", t12_tk5: "adatot felhasználunk.",
    t12_q: "Mi az az epoka a tanítás során?", t12_qa: "A tanítási adatok teljes bejárása", t12_qb: "Egyetlen adatpont", t12_qc: "Hibaüzenet", t12_qd: "Új modell",
    t13_title: "Gradiens ereszkedés", t13_text: "Optimalizáló algoritmus, amely lépésről lépésre próbálja minimalizálni a modell hibáját a súlyok módosításával.",
    t13_inst: "Építs mondatot:", t13_f1: "A", t13_f2: "gradiens ereszkedés", t13_f3: "minimalizálja", t13_f4: "a hibát.",
    t13_q: "Mi a gradiens ereszkedés célja?", t13_qa: "A hiba minimalizálása", t13_qb: "Az adathalmaz növelése", t13_qc: "A sebesség csökkentése", t13_qd: "A modell törlése",
    t14_title: "Adathalmazok (Big Data)", t14_text: "Hatalmas, strukturálatlan adatmennyiségek képezik a modern AI modellek, pl. a ChatGPT alapját.",
    t14_inst: "Pótold:", t14_sent: "A nagy AI modellek hatalmas ___ igényelnek.", t14_qa14: "adatmennyiséget", t14_qb14: "képernyőt", t14_qc14: "billentyűzetet", t14_qd14: "egeret",
    t14_q: "Miért kell a modern AI modelleknek Big Data?", t14_qa: "Hogy komplex mintákat tanuljanak", t14_qb: "Tárhely pazarolásához", t14_qc: "Lassításhoz", t14_qd: "Marketing célokra",
    t15_title: "Jellemzőtervezés (Feature Engineering)", t15_text: "A nyers adatok hasznos jellemzőkké (features) alakítása, ami megkönnyíti a modell tanulását.",
    t15_inst: "Válogasd szét:", t15_bl1: "Nyers adat", t15_bl2: "Jellemző", t15_i1: "Dátum", t15_i2: "Nyers szöveg", t15_i3: "Szavak száma", t15_i4: "A hét napja",
    t15_q: "Mi a jellemzőtervezés célja?", t15_qa: "Hasznosabb formába hozni az adatokat a modellnek", t15_qb: "A modell teljes újraírása", t15_qc: "Minden adat törlése", t15_qd: "Hibák generálása az adatokban",
  },
  ro: {
    explorer_title: "Învățare Automată",
    t1_title: "Învățare Supravegheată", t1_text: "În învățarea supravegheată, modelul primește exemple cu rezultate cunoscute (etichete). Învață să recunoască tipare.",
    t1_inst: "Potrivește tipurile:", t1_l1: "Supravegheată", t1_r1: "etichete cunoscute", t1_l2: "Nesupravegheată", t1_r2: "fără etichete", t1_l3: "Prin recompensă", t1_r3: "recompensă și pedeapsă",
    t1_q: "Ce caracterizează învățarea supravegheată?", t1_qa: "Învățarea din date etichetate", t1_qb: "Învățarea fără date", t1_qc: "Programarea manuală", t1_qd: "Ghiticitul aleatoriu",
    t2_title: "Clasificare", t2_text: "Clasificarea este o sarcină unde modelul atribuie intrările unei categorii, de exemplu, un email ca spam sau nu.",
    t2_inst: "Completează:", t2_sent: "Filtrul clasifică un email ca ___ sau nu.", t2_qa2: "spam", t2_qb2: "număr", t2_qc2: "imagine", t2_qd2: "video",
    t2_q: "Care este scopul clasificării?", t2_qa: "Atribuirea intrărilor unei categorii", t2_qb: "Prezicerea unei valori numerice", t2_qc: "Comprimarea datelor", t2_qd: "Traducerea site-urilor",
    t3_title: "Regresie", t3_text: "Regresia este o sarcină în care modelul prezice o valoare numerică continuă, cum ar fi prețul unei case.",
    t3_inst: "Ordonează propoziția:", t3_w1: "Regresia", t3_w2: "prezice", t3_w3: "o valoare", t3_w4: "numerică", t3_w5: "continuă.",
    t3_q: "Ce prezice un model de regresie?", t3_qa: "O valoare numerică continuă", t3_qb: "Una din mai multe categorii", t3_qc: "Un nume de fișier", t3_qd: "O adresă IP",
    t4_title: "Set de date", t4_text: "Un set de date este o colecție de date structurate pentru antrenament. Calitatea și cantitatea sunt cruciale.",
    t4_inst: "Sortează:", t4_bl1: "Bun pt ML", t4_bl2: "Rău pt ML", t4_i1: "Date de calitate", t4_i2: "Date echilibrate", t4_i3: "Date cu erori", t4_i4: "Date distorsionate",
    t4_q: "De ce e importantă calitatea setului de date?", t4_qa: "Date mai bune = modele mai precise", t4_qb: "Mai multe date = modele mai lente", t4_qc: "Datele trebuie introduse manual", t4_qd: "Mai puține date înseamnă mai bine",
    t5_title: "Overfitting", t5_text: "Overfitting-ul apare când un model memorează prea bine datele de antrenament și performează slab pe date noi.",
    t5_inst: "Evidențiază problema:", t5_tk1: "Modelul", t5_tk2: "memorează", t5_tk3: "datele", t5_tk4: "de antrenament.",
    t5_q: "Ce se întâmplă la overfitting?", t5_qa: "Generalizare slabă pe date noi", t5_qb: "Modelul nu învață nimic", t5_qc: "Devine infinit de rapid", t5_qd: "Șterge setul de date",
    t6_title: "Date de Antrenament vs Test", t6_text: "Datele de antrenament sunt folosite pentru învățare, iar cele de test pentru a evalua modelul pe date nevăzute.",
    t6_inst: "Potrivește:", t6_l1: "Date antrenament", t6_r1: "Pentru învățare", t6_l2: "Date test", t6_r2: "Pentru evaluare", t6_l3: "Date validare", t6_r3: "Pentru ajustare",
    t6_q: "La ce folosesc datele de test?", t6_qa: "Pentru a evalua performanța modelului", t6_qb: "Pentru memorare", t6_qc: "Pentru a încetini modelul", t6_qd: "Pentru interfața utilizatorului",
    t7_title: "Underfitting", t7_text: "Underfitting înseamnă că modelul este prea simplu și nu poate capta corect tiparele din datele de antrenament.",
    t7_inst: "Construiește fraza:", t7_f1: "Un model", t7_f2: "prea simplu", t7_f3: "duce la", t7_f4: "underfitting.",
    t7_q: "Ce este underfitting-ul?", t7_qa: "Modelul e prea simplu pentru date", t7_qb: "Modelul memorează datele", t7_qc: "Modelul are prea mulți parametri", t7_qd: "Modelul se prăbușește",
    t8_title: "Arbori de Decizie", t8_text: "Arborii de decizie iau decizii printr-o serie de întrebări da/nu, similar cu o schemă logică.",
    t8_inst: "Completează:", t8_sent: "Un arbore de decizie folosește ___.", t8_qa8: "întrebări da/nu", t8_qb8: "numere aleatoare", t8_qc8: "imagini", t8_qd8: "neutrini",
    t8_q: "Cum funcționează un arbore de decizie?", t8_qa: "Cu reguli imbricate de tip dacă-atunci", t8_qb: "Cu ecuații diferențiale complexe", t8_qc: "Doar ghicind", t8_qd: "Prin învățare nesupravegheată",
    t9_title: "Clasificare vs Regresie", t9_text: "Clasificarea prezice categorii (ex. câine/pisică), regresia prezice valori numerice (ex. preț).",
    t9_inst: "Sortează:", t9_bl1: "Clasificare", t9_bl2: "Regresie", t9_i1: "Filtru de spam", t9_i2: "Rasă de câine", t9_i3: "Estimare preț casă", t9_i4: "Predicție preț acțiuni",
    t9_q: "Care este o problemă de regresie?", t9_qa: "Prezicerea prețului unei mașini", t9_qb: "Recunoașterea unei imagini ca pisică/câine", t9_qc: "Marcarea unui email ca spam", t9_qd: "Detectarea limbii unui text",
    t10_title: "Clustering", t10_text: "Clustering-ul grupează date similare fără etichete anterioare. Face parte din învățarea nesupravegheată.",
    t10_inst: "Ordonează:", t10_w1: "Clustering-ul", t10_w2: "grupează", t10_w3: "datele", t10_w4: "similare", t10_w5: "la un loc.",
    t10_q: "Din ce tip de învățare face parte clustering-ul?", t10_qa: "Învățare nesupravegheată", t10_qb: "Învățare supravegheată", t10_qc: "Învățare prin recompensă", t10_qd: "Învățare manuală",
    t11_title: "Neuroni Artificiali", t11_text: "Neuronii artificiali sunt blocurile de bază ale rețelelor neurale. Primesc date, le ponderează și dau un rezultat.",
    t11_inst: "Potrivește:", t11_l1: "Intrare", t11_r1: "Date", t11_l2: "Pondere", t11_r2: "Importanță", t11_l3: "Activare", t11_r3: "Rezultat",
    t11_q: "Ce simulează neuronii artificiali?", t11_qa: "Celule nervoase biologice", t11_qb: "Monitoare de calculator", t11_qc: "Baze de date", t11_qd: "Tastaturi",
    t12_title: "Epoci și Iterații", t12_text: "O epocă este o trecere completă prin toate datele. O iterație procesează doar un lot mic de date.",
    t12_inst: "Evidențiază:", t12_tk1: "O", t12_tk2: "epocă", t12_tk3: "folosește", t12_tk4: "toate", t12_tk5: "datele.",
    t12_q: "Ce este o epocă în antrenament?", t12_qa: "O trecere completă prin datele de antrenament", t12_qb: "Un singur punct de date", t12_qc: "Un mesaj de eroare", t12_qd: "Un nou model",
    t13_title: "Gradient Descent", t13_text: "Un algoritm de optimizare care încearcă să minimizeze eroarea modelului ajustând ponderile pas cu pas.",
    t13_inst: "Construiește fraza:", t13_f1: "Gradient", t13_f2: "descent", t13_f3: "minimizează", t13_f4: "eroarea.",
    t13_q: "Care este scopul gradient descent?", t13_qa: "Să minimizeze eroarea", t13_qb: "Să extindă setul de date", t13_qc: "Să reducă viteza", t13_qd: "Să șteargă modelul",
    t14_title: "Big Data", t14_text: "Cantități uriașe de date nestructurate reprezintă baza multor modele moderne de IA, cum ar fi ChatGPT.",
    t14_inst: "Completează:", t14_sent: "Modelele mari necesită mult ___.", t14_qa14: "set de date", t14_qb14: "ecran", t14_qc14: "tastatură", t14_qd14: "mouse",
    t14_q: "De ce modelele moderne au nevoie de Big Data?", t14_qa: "Pentru a învăța tipare complexe", t14_qb: "Pentru a irosi spațiu", t14_qc: "Pentru a fi mai încete", t14_qd: "Doar pentru marketing",
    t15_title: "Feature Engineering", t15_text: "Procesul de transformare a datelor brute în caracteristici utile pentru a ușura învățarea modelului ML.",
    t15_inst: "Sortează:", t15_bl1: "Date brute", t15_bl2: "Caracteristici", t15_i1: "Data", t15_i2: "Text brut", t15_i3: "Număr de cuvinte", t15_i4: "Zi a săptămânii",
    t15_q: "Care este scopul feature engineering?", t15_qa: "Să transforme datele într-un format util", t15_qb: "Să programeze modelul complet", t15_qc: "Să șteargă toate datele", t15_qd: "Să introducă erori în date",
  },
};

export const INFO_K8_I8_POOL: PoolTopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🎓", color: "#1A237E" },
    interactive: { type: "match-pairs", instruction: "t1_inst", pairs: [{ left: "t1_l1", right: "t1_r1" }, { left: "t1_l2", right: "t1_r2" }, { left: "t1_l3", right: "t1_r3" }] },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" }
  },
  {
    infoTitle: "t2_title", infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🗂️", color: "#B71C1C" },
    interactive: { type: "gap-fill", instruction: "t2_inst", sentence: "t2_sent", choices: ["t2_qa2", "t2_qb2", "t2_qc2", "t2_qd2"], correctIndex: 0 },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" }
  },
  {
    infoTitle: "t3_title", infoText: "t3_text",
    svg: { type: "simple-icon", icon: "📈", color: "#1B5E20" },
    interactive: { type: "word-order", instruction: "t3_inst", words: ["t3_w1", "t3_w2", "t3_w3", "t3_w4", "t3_w5"], correctOrder: [0, 1, 2, 3, 4] },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" }
  },
  {
    infoTitle: "t4_title", infoText: "t4_text",
    svg: { type: "simple-icon", icon: "💾", color: "#E65100" },
    interactive: { type: "drag-to-bucket", instruction: "t4_inst", buckets: [{ id: "good", label: "t4_bl1" }, { id: "bad", label: "t4_bl2" }], items: [{ text: "t4_i1", bucketId: "good" }, { text: "t4_i2", bucketId: "bad" }, { text: "t4_i3", bucketId: "good" }, { text: "t4_i4", bucketId: "bad" }] },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" }
  },
  {
    infoTitle: "t5_title", infoText: "t5_text",
    svg: { type: "simple-icon", icon: "⚠️", color: "#4A148C" },
    interactive: { type: "highlight-text", instruction: "t5_inst", tokens: ["t5_tk1", "t5_tk2", "t5_tk3", "t5_tk4"], correctIndices: [1] },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" }
  },
  {
    infoTitle: "t6_title", infoText: "t6_text",
    svg: { type: "simple-icon", icon: "🧪", color: "#3F51B5" },
    interactive: { type: "match-pairs", instruction: "t6_inst", pairs: [{ left: "t6_l1", right: "t6_r1" }, { left: "t6_l2", right: "t6_r2" }, { left: "t6_l3", right: "t6_r3" }] },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qa" }
  },
  {
    infoTitle: "t7_title", infoText: "t7_text",
    svg: { type: "simple-icon", icon: "📉", color: "#009688" },
    interactive: { type: "sentence-build", instruction: "t7_inst", fragments: ["t7_f1", "t7_f2", "t7_f3", "t7_f4"] },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qa" }
  },
  {
    infoTitle: "t8_title", infoText: "t8_text",
    svg: { type: "simple-icon", icon: "🌳", color: "#4CAF50" },
    interactive: { type: "gap-fill", instruction: "t8_inst", sentence: "t8_sent", choices: ["t8_qa8", "t8_qb8", "t8_qc8", "t8_qd8"], correctIndex: 0 },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" }
  },
  {
    infoTitle: "t9_title", infoText: "t9_text",
    svg: { type: "simple-icon", icon: "⚖️", color: "#9C27B0" },
    interactive: { type: "drag-to-bucket", instruction: "t9_inst", buckets: [{ id: "c", label: "t9_bl1" }, { id: "r", label: "t9_bl2" }], items: [{ text: "t9_i1", bucketId: "c" }, { text: "t9_i2", bucketId: "c" }, { text: "t9_i3", bucketId: "r" }, { text: "t9_i4", bucketId: "r" }] },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" }
  },
  {
    infoTitle: "t10_title", infoText: "t10_text",
    svg: { type: "simple-icon", icon: "🍇", color: "#E91E63" },
    interactive: { type: "word-order", instruction: "t10_inst", words: ["t10_w1", "t10_w2", "t10_w3", "t10_w4", "t10_w5"], correctOrder: [0, 1, 2, 3, 4] },
    quiz: { question: "t10_q", choices: ["t10_qa", "t10_qb", "t10_qc", "t10_qd"], answer: "t10_qa" }
  },
  {
    infoTitle: "t11_title", infoText: "t11_text",
    svg: { type: "simple-icon", icon: "🧠", color: "#F44336" },
    interactive: { type: "match-pairs", instruction: "t11_inst", pairs: [{ left: "t11_l1", right: "t11_r1" }, { left: "t11_l2", right: "t11_r2" }, { left: "t11_l3", right: "t11_r3" }] },
    quiz: { question: "t11_q", choices: ["t11_qa", "t11_qb", "t11_qc", "t11_qd"], answer: "t11_qa" }
  },
  {
    infoTitle: "t12_title", infoText: "t12_text",
    svg: { type: "simple-icon", icon: "🔁", color: "#03A9F4" },
    interactive: { type: "highlight-text", instruction: "t12_inst", tokens: ["t12_tk1", "t12_tk2", "t12_tk3", "t12_tk4", "t12_tk5"], correctIndices: [1] },
    quiz: { question: "t12_q", choices: ["t12_qa", "t12_qb", "t12_qc", "t12_qd"], answer: "t12_qa" }
  },
  {
    infoTitle: "t13_title", infoText: "t13_text",
    svg: { type: "simple-icon", icon: "🎢", color: "#FF9800" },
    interactive: { type: "sentence-build", instruction: "t13_inst", fragments: ["t13_f1", "t13_f2", "t13_f3", "t13_f4"] },
    quiz: { question: "t13_q", choices: ["t13_qa", "t13_qb", "t13_qc", "t13_qd"], answer: "t13_qa" }
  },
  {
    infoTitle: "t14_title", infoText: "t14_text",
    svg: { type: "simple-icon", icon: "🐘", color: "#607D8B" },
    interactive: { type: "gap-fill", instruction: "t14_inst", sentence: "t14_sent", choices: ["t14_qa14", "t14_qb14", "t14_qc14", "t14_qd14"], correctIndex: 0 },
    quiz: { question: "t14_q", choices: ["t14_qa", "t14_qb", "t14_qc", "t14_qd"], answer: "t14_qa" }
  },
  {
    infoTitle: "t15_title", infoText: "t15_text",
    svg: { type: "simple-icon", icon: "🔧", color: "#795548" },
    interactive: { type: "drag-to-bucket", instruction: "t15_inst", buckets: [{ id: "raw", label: "t15_bl1" }, { id: "feat", label: "t15_bl2" }], items: [{ text: "t15_i1", bucketId: "raw" }, { text: "t15_i2", bucketId: "raw" }, { text: "t15_i3", bucketId: "feat" }, { text: "t15_i4", bucketId: "feat" }] },
    quiz: { question: "t15_q", choices: ["t15_qa", "t15_qb", "t15_qc", "t15_qd"], answer: "t15_qa" }
  }
];
