import type { PoolTopicDef, SvgConfig } from "./types";

type Lang = "de" | "en" | "hu" | "ro";
type T = Record<Lang, string>;

const L = (en: string, de: string, hu: string, ro: string): T => ({ en, de, hu, ro });

const SORT_INST = L("Sort the examples.", "Ordne die Beispiele.", "Rendezd a példákat.", "Grupează exemplele.");
const MATCH_INST = L("Match the pairs.", "Ordne die Paare zu.", "Párosítsd az elemeket.", "Potrivește perechile.");
const ORDER_INST = L("Put the steps in order.", "Bringe die Schritte in die richtige Reihenfolge.", "Tedd sorrendbe a lépéseket.", "Pune pașii în ordine.");
const GAP_INST = L("Choose the missing word.", "Wähle das fehlende Wort.", "Válaszd ki a hiányzó szót.", "Alege cuvântul lipsă.");
const HIGHLIGHT_INST = L("Find the key idea.", "Finde die wichtigste Idee.", "Találd meg a lényegi részt.", "Găsește ideea-cheie.");
const DIAGRAM_INST = L("Label the diagram.", "Beschrifte die Grafik.", "Jelöld meg az ábrát.", "Etichetează diagrama.");

interface ChemTopic {
  id: string;
  difficulty: "easy" | "medium" | "hard";
  labels: Record<string, T>;
  svg: SvgConfig;
  interactive: PoolTopicDef["interactive"];
  quiz: PoolTopicDef["quiz"];
}

const makeIslandLabels = (topics: ChemTopic[]): Record<string, Record<string, string>> => {
  const labels: Record<Lang, Record<string, string>> = { de: {}, en: {}, hu: {}, ro: {} };

  topics.forEach((topic) => {
    Object.entries(topic.labels).forEach(([key, value]) => {
      (Object.keys(labels) as Lang[]).forEach((lang) => {
        labels[lang][`${topic.id}_${key}`] = value[lang];
      });
    });
  });

  return labels;
};

const makePool = (topics: ChemTopic[]): PoolTopicDef[] =>
  topics.map((topic) => ({
    difficulty: topic.difficulty,
    infoTitle: `${topic.id}_title`,
    infoText: `${topic.id}_text`,
    svg: topic.svg,
    hintKey: `${topic.id}_h1`,
    interactive: topic.interactive,
    quiz: topic.quiz,
  }));

const simpleIcon = (icon: string, title: string, bg: string, color: string): SvgConfig => ({
  type: "simple-icon",
  icon,
  title,
  bg,
  color,
});

const twoGroups = (left: string[], right: string[], leftBg: string, rightBg: string, borderA: string, borderB: string, bg?: string): SvgConfig => ({
  type: "two-groups",
  left: { items: left, bg: leftBg, border: borderA },
  right: { items: right, bg: rightBg, border: borderB },
  bg,
});

const iconGrid = (items: { emoji: string; label?: string }[], bg?: string): SvgConfig => ({
  type: "icon-grid",
  items,
  bg,
});

const sentence = (words: string[], highlightIndices: number[], color: string): SvgConfig => ({
  type: "sentence-display",
  words,
  highlightIndices,
  color,
});

const word = (word: string, color: string, subtitle?: string): SvgConfig => ({
  type: "word-display",
  word,
  color,
  subtitle,
});

const bubbles = (items: { text: string; emoji?: string; color: string; bg: string }[]): SvgConfig => ({
  type: "text-bubbles",
  items,
});

const diagram = (name: string, color?: string, bg?: string): SvgConfig => ({
  type: "biologie-diagram",
  name,
  color,
  bg,
});

const I1: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Matter Around Us", "Stoffe im Alltag", "Anyagok körülöttünk", "Substanțe din jur"),
      text: L("Everyday materials can be solid, liquid, or gas.", "Alltagsstoffe sind fest, flüssig oder gasförmig.", "A mindennapi anyagok szilárdak, folyékonyak vagy gázok lehetnek.", "Substanțele cotidiene pot fi solide, lichide sau gazoase."),
      inst: SORT_INST,
      h1: L("Look at the examples.", "Schau dir die Beispiele an.", "Nézd meg a példákat.", "Privește exemplele."),
      h2: L("Choose the right group.", "Wähle die richtige Gruppe.", "Válaszd a megfelelő csoportot.", "Alege grupul potrivit."),
      b1: L("solids", "Feststoffe", "szilárd", "solide"),
      b2: L("liquids", "Flüssigkeiten", "folyadék", "lichide"),
      b3: L("gases", "Gase", "gázok", "gaze"),
      i1: L("stone", "Stein", "kő", "piatră"),
      i2: L("water", "Wasser", "víz", "apă"),
      i3: L("air", "Luft", "levegő", "aer"),
      i4: L("steam", "Dampf", "gőz", "abur"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "solid", label: "b1" }, { id: "liquid", label: "b2" }, { id: "gas", label: "b3" }],
      items: [
        { text: "i1", bucketId: "solid" },
        { text: "i2", bucketId: "liquid" },
        { text: "i3", bucketId: "gas" },
        { text: "i4", bucketId: "gas" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "materials_daily_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("States of Matter", "Aggregatzustände", "Halmazállapotok", "Stările de agregare"),
      text: L("Solid, liquid, and gas behave differently.", "Fest, flüssig und gasförmig verhalten sich unterschiedlich.", "A szilárd, folyékony és gáz halmazállapot másképp viselkedik.", "Solidul, lichidul și gazul se comportă diferit."),
      inst: MATCH_INST,
      h1: L("Think about shape and flow.", "Denk an Form und Fließen.", "Gondolj az alakra és az áramlásra.", "Gândește-te la formă și curgere."),
      h2: L("Match each state.", "Ordne jeden Zustand zu.", "Párosítsd az állapotokat.", "Potrivește fiecare stare."),
      l1: L("solid", "fest", "szilárd", "solid"),
      r1: L("keeps its shape", "behält die Form", "megtartja az alakját", "își păstrează forma"),
      l2: L("liquid", "flüssig", "folyékony", "lichid"),
      r2: L("flows", "fließt", "folyik", "curge"),
      l3: L("gas", "gasförmig", "gáz", "gaz"),
      r3: L("spreads out", "breitet sich aus", "szétterül", "se împrăștie"),
      l4: L("water", "Wasser", "víz", "apă"),
      r4: L("fills the container", "füllt den Behälter", "kitölti az edényt", "umple recipientul"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "solids_liquids_gases_mcq" },
  },
  {
    id: "t3",
    difficulty: "medium",
    labels: {
      title: L("State Changes", "Zustandsänderungen", "Halmazállapot-változás", "Schimbări de stare"),
      text: L("Heating or cooling can change matter.", "Erwärmen oder Abkühlen kann Stoffe verändern.", "A melegítés vagy hűtés megváltoztathatja az anyagot.", "Încălzirea sau răcirea poate schimba materia."),
      inst: ORDER_INST,
      h1: L("Start with heat.", "Beginne mit Wärme.", "Kezdd a melegítéssel.", "Începe cu căldura."),
      h2: L("Then think of cooling.", "Dann an das Abkühlen denken.", "Utána gondolj a hűtésre.", "Apoi gândește-te la răcire."),
      w1: L("melting", "schmelzen", "olvadás", "topire"),
      w2: L("evaporation", "verdampfen", "párolgás", "evaporare"),
      w3: L("freezing", "gefrieren", "fagyás", "înghețare"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "state_changes_basic_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Hard, Soft, Elastic", "Hart, weich, elastisch", "Kemény, puha, rugalmas", "Dur, moale, elastic"),
      text: L("Some materials are hard, some are soft, and some stretch back.", "Manche Stoffe sind hart, weich oder elastisch.", "Vannak kemény, puha és rugalmas anyagok.", "Unele materiale sunt dure, moi sau elastice."),
      inst: SORT_INST,
      h1: L("Feel the surface.", "Fühle die Oberfläche.", "Érezd a felületet.", "Simte suprafața."),
      h2: L("Decide how it changes.", "Entscheide, wie es sich verändert.", "Döntsd el, hogyan viselkedik.", "Decide cum se comportă."),
      b1: L("hard", "hart", "kemény", "dur"),
      b2: L("soft", "weich", "puha", "moale"),
      b3: L("elastic", "elastisch", "rugalmas", "elastic"),
      i1: L("glass", "Glas", "üveg", "sticlă"),
      i2: L("sponge", "Schwamm", "szivacs", "burete"),
      i3: L("rubber band", "Gummiband", "gumiszalag", "elastic"),
      i4: L("wood", "Holz", "fa", "lemn"),
    },
    svg: bubbles([
      { text: "hard", emoji: "🪵", color: "#92400E", bg: "#FEF3C7" },
      { text: "soft", emoji: "🧽", color: "#0F766E", bg: "#CCFBF1" },
      { text: "elastic", emoji: "🪢", color: "#7C3AED", bg: "#EDE9FE" },
    ]),
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "hard", label: "b1" }, { id: "soft", label: "b2" }, { id: "elastic", label: "b3" }],
      items: [
        { text: "i1", bucketId: "hard" },
        { text: "i2", bucketId: "soft" },
        { text: "i3", bucketId: "elastic" },
        { text: "i4", bucketId: "hard" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "properties_hard_soft_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Waterproof?", "Wasserdicht?", "Vízálló?", "Impermeabil?"),
      text: L("Some things let water in, others keep water out.", "Manche Dinge lassen Wasser durch, andere nicht.", "Egyes anyagok átengedik a vizet, mások nem.", "Unele lucruri lasă apa să treacă, altele nu."),
      inst: GAP_INST,
      h1: L("Think about rainwear.", "Denk an Regenkleidung.", "Gondolj az esőkabátra.", "Gândește-te la haine de ploaie."),
      h2: L("Choose what keeps water out.", "Wähle, was Wasser abhält.", "Válaszd azt, ami kint tartja a vizet.", "Alege ce ține apa afară."),
      sent: L("A raincoat is ___.", "Ein Regenmantel ist ___.", "Egy esőkabát ___.", "O haină de ploaie este ___."),
      c1: L("waterproof", "wasserdicht", "vízálló", "impermeabil"),
      c2: L("absorbent", "saugfähig", "nedvszívó", "absorbant"),
      c3: L("heavy", "schwer", "nehéz", "greu"),
      c4: L("sticky", "klebrig", "ragadós", "lipicios"),
    },
    svg: simpleIcon("☔", "waterproof", "#ECFEFF", "#0F766E"),
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "properties_waterproof_mcq" },
  },
];

const I2: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Particles", "Teilchen", "Részecskék", "Particule"),
      text: L("Everything in chemistry is made of tiny particles.", "Alles in der Chemie besteht aus winzigen Teilchen.", "A kémiában minden apró részecskékből áll.", "Totul în chimie este alcătuit din particule mici."),
      inst: HIGHLIGHT_INST,
      h1: L("Tiny means very small.", "Winzig bedeutet sehr klein.", "Az apró nagyon kicsit jelent.", "Foarte mic înseamnă minuscul."),
      h2: L("Focus on the key word.", "Achte auf das Schlüsselwort.", "Figyelj a kulcsszóra.", "Fii atent la cuvântul-cheie."),
      w1: L("Everything", "Alles", "Minden", "Totul"),
      w2: L("is", "ist", "van", "este"),
      w3: L("made", "gemacht", "készül", "alcătuit"),
      w4: L("of particles", "aus Teilchen", "részecskékből", "din particule"),
    },
    svg: { type: "kemia-diagram", name: "AtomSvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [3],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "particle_idea_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Particle Spacing", "Teilchenabstand", "Részecsketávolság", "Distanța dintre particule"),
      text: L("Particles can be close together or far apart.", "Teilchen können dicht beieinander oder weit entfernt sein.", "A részecskék közel vagy távol lehetnek egymástól.", "Particulele pot fi apropiate sau depărtate."),
      inst: MATCH_INST,
      h1: L("Close means dense.", "Nah bedeutet dicht.", "A közel sűrűt jelent.", "Aproape înseamnă dens."),
      h2: L("Far apart means spread out.", "Weit auseinander bedeutet verteilt.", "A távol egymástól szétterülést jelent.", "Depărtate înseamnă răspândite."),
      l1: L("close together", "dicht zusammen", "közel egymáshoz", "apropiate"),
      r1: L("solid", "fest", "szilárd", "solid"),
      l2: L("some space", "etwas Abstand", "van hely köztük", "puțin spațiu"),
      r2: L("liquid", "flüssig", "folyékony", "lichid"),
      l3: L("far apart", "weit auseinander", "távol egymástól", "departe"),
      r3: L("gas", "gasförmig", "gáz", "gaz"),
      l4: L("packed", "gepackt", "összeszorulva", "înghesuit"),
      r4: L("cold solid", "kalter Feststoff", "hideg szilárd anyag", "solid rece"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "particle_spacing_mcq" },
  },
  {
    id: "t3",
    difficulty: "medium",
    labels: {
      title: L("Particle Motion", "Teilchenbewegung", "Részecskemozgás", "Mișcarea particulelor"),
      text: L("Particles move faster when they are warmer.", "Teilchen bewegen sich schneller, wenn es wärmer wird.", "A részecskék gyorsabban mozognak, ha melegebb van.", "Particulele se mișcă mai repede când este mai cald."),
      inst: ORDER_INST,
      h1: L("Start with slow motion.", "Beginne mit langsamer Bewegung.", "Kezdd a lassú mozgással.", "Începe cu mișcarea lentă."),
      h2: L("End with fast motion.", "Ende mit schneller Bewegung.", "Végül jön a gyors mozgás.", "Încheie cu mișcarea rapidă."),
      w1: L("slow", "langsam", "lassú", "lent"),
      w2: L("faster", "schneller", "gyorsabb", "mai repede"),
      w3: L("fastest", "am schnellsten", "leggyorsabb", "cel mai repede"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "particle_motion_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Heating", "Erwärmen", "Melegítés", "Încălzire"),
      text: L("Heating gives particles more energy.", "Beim Erwärmen bekommen Teilchen mehr Energie.", "A melegítés több energiát ad a részecskéknek.", "Încălzirea dă particulelor mai multă energie."),
      inst: SORT_INST,
      h1: L("Warmer means more movement.", "Wärmer bedeutet mehr Bewegung.", "A melegebb több mozgást jelent.", "Mai cald înseamnă mai multă mișcare."),
      h2: L("Put the faster ones together.", "Ordne die schnelleren zusammen.", "Tedd össze a gyorsabbakat.", "Pune la un loc cele mai rapide."),
      b1: L("slow", "langsam", "lassú", "lent"),
      b2: L("fast", "schnell", "gyors", "rapid"),
      i1: L("ice", "Eis", "jég", "gheață"),
      i2: L("water", "Wasser", "víz", "apă"),
      i3: L("steam", "Dampf", "gőz", "abur"),
      i4: L("warm liquid", "warme Flüssigkeit", "meleg folyadék", "lichid cald"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "slow", label: "b1" }, { id: "fast", label: "b2" }],
      items: [
        { text: "i1", bucketId: "slow" },
        { text: "i2", bucketId: "slow" },
        { text: "i3", bucketId: "fast" },
        { text: "i4", bucketId: "fast" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "heating_particles_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Cooling", "Abkühlen", "Hűtés", "Răcire"),
      text: L("Cooling makes particles move more slowly.", "Beim Abkühlen bewegen sich Teilchen langsamer.", "A hűtés lassítja a részecskéket.", "Răcirea încetinește particulele."),
      inst: GAP_INST,
      h1: L("Cold means slower particles.", "Kalt bedeutet langsamere Teilchen.", "A hideg lassabb részecskéket jelent.", "Rece înseamnă particule mai lente."),
      h2: L("Choose the slowing action.", "Wähle die verlangsamende Wirkung.", "Válaszd a lassító hatást.", "Alege efectul de încetinire."),
      sent: L("Cooling makes particles ___.", "Abkühlen macht Teilchen ___.", "A hűtés a részecskéket ___.", "Răcirea face particulele ___."),
      c1: L("slower", "langsamer", "lassabbá", "mai lente"),
      c2: L("louder", "lauter", "hangosabbá", "mai zgomotoase"),
      c3: L("heavier", "schwerer", "nehezebbé", "mai grele"),
      c4: L("heller", "heller", "világosabbá", "mai luminoase"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "cooling_particles_mcq" },
  },
];

const I3: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Pure or Mixture", "Reinstoff oder Gemisch", "Tiszta anyag vagy keverék", "Substanță pură sau amestec"),
      text: L("Some samples contain one substance, others contain several.", "Manche Proben bestehen aus einem Stoff, andere aus mehreren.", "Egyes minták egy anyagból állnak, mások többől.", "Unele probe conțin o singură substanță, altele mai multe."),
      inst: SORT_INST,
      h1: L("One kind or many kinds?", "Eine Sorte oder viele?", "Egyféle vagy többféle?", "Un singur fel sau mai multe?"),
      h2: L("Sort the samples.", "Sortiere die Proben.", "Rendezd a mintákat.", "Grupează probele."),
      b1: L("pure", "rein", "tiszta", "pur"),
      b2: L("mixture", "Gemisch", "keverék", "amestec"),
      i1: L("salt", "Salz", "só", "sare"),
      i2: L("air", "Luft", "levegő", "aer"),
      i3: L("salad", "Salat", "saláta", "salată"),
      i4: L("gold", "Gold", "arany", "aur"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "pure", label: "b1" }, { id: "mixture", label: "b2" }],
      items: [
        { text: "i1", bucketId: "pure" },
        { text: "i2", bucketId: "mixture" },
        { text: "i3", bucketId: "mixture" },
        { text: "i4", bucketId: "pure" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "pure_vs_mixture_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Solutions", "Lösungen", "Oldatok", "Soluții"),
      text: L("A solution is a mixture where one substance dissolves in another.", "Eine Lösung ist ein Gemisch, in dem sich ein Stoff in einem anderen löst.", "Az oldat olyan keverék, ahol az egyik anyag feloldódik a másikban.", "O soluție este un amestec în care o substanță se dizolvă în alta."),
      inst: MATCH_INST,
      h1: L("Think of sugar water.", "Denk an Zuckerwasser.", "Gondolj a cukros vízre.", "Gândește-te la apă cu zahăr."),
      h2: L("Which part dissolves?", "Welcher Teil löst sich?", "Melyik oldódik fel?", "Ce se dizolvă?"),
      l1: L("solute", "gelöster Stoff", "oldott anyag", "solut"),
      r1: L("the thing that dissolves", "der Stoff, der sich löst", "ami feloldódik", "substanța care se dizolvă"),
      l2: L("solvent", "Lösungsmittel", "oldószer", "solvent"),
      r2: L("the liquid", "die Flüssigkeit", "a folyadék", "lichidul"),
      l3: L("sugar", "Zucker", "cukor", "zahăr"),
      r3: L("dissolves in water", "löst sich in Wasser", "feloldódik vízben", "se dizolvă în apă"),
      l4: L("salt water", "Salzwasser", "sós víz", "apă sărată"),
      r4: L("a solution", "eine Lösung", "egy oldat", "o soluție"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "solutions_intro_mcq" },
  },
  {
    id: "t3",
    difficulty: "medium",
    labels: {
      title: L("Suspensions", "Suspensionen", "Szuszpenziók", "Suspensii"),
      text: L("In a suspension, tiny pieces are mixed in a liquid but do not fully dissolve.", "In einer Suspension sind kleine Teilchen in einer Flüssigkeit verteilt, lösen sich aber nicht ganz.", "A szuszpenzióban apró részecskék vannak a folyadékban, de nem oldódnak fel teljesen.", "Într-o suspensie, particulele sunt amestecate într-un lichid, dar nu se dizolvă complet."),
      inst: SORT_INST,
      h1: L("Look for cloudy mixtures.", "Achte auf trübe Gemische.", "Keress zavaros keverékeket.", "Caută amestecuri tulburi."),
      h2: L("Not everything disappears.", "Nicht alles verschwindet.", "Nem minden tűnik el.", "Nu totul dispare."),
      b1: L("solution", "Lösung", "oldat", "soluție"),
      b2: L("suspension", "Suspension", "szuszpenzió", "suspensie"),
      i1: L("salt water", "Salzwasser", "sós víz", "apă sărată"),
      i2: L("muddy water", "Schlammwasser", "sáros víz", "apă tulbure"),
      i3: L("orange juice with pulp", "Orangensaft mit Fruchtfleisch", "narancslé gyümölcshússal", "suc cu pulpă"),
      i4: L("clear sugar water", "klares Zuckerwasser", "tiszta cukros víz", "apă cu zahăr limpede"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "solution", label: "b1" }, { id: "suspension", label: "b2" }],
      items: [
        { text: "i1", bucketId: "solution" },
        { text: "i2", bucketId: "suspension" },
        { text: "i3", bucketId: "suspension" },
        { text: "i4", bucketId: "solution" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "suspensions_intro_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Filtration", "Filtration", "Szűrés", "Filtrare"),
      text: L("Filtration separates solid particles from a liquid.", "Filtration trennt feste Teilchen von einer Flüssigkeit.", "A szűrés elválasztja a szilárd részecskéket a folyadéktól.", "Filtrarea separă particulele solide dintr-un lichid."),
      inst: ORDER_INST,
      h1: L("Think: pour, catch, collect.", "Denk: gießen, auffangen, sammeln.", "Gondolj erre: öntés, felfogás, gyűjtés.", "Gândește: toarnă, oprește, colectează."),
      h2: L("Follow the filter steps.", "Folge den Filterschritten.", "Kövesd a szűrés lépéseit.", "Urmează pașii filtrării."),
      w1: L("pour", "gießen", "önt", "toarnă"),
      w2: L("filter", "filtern", "szűr", "filtrează"),
      w3: L("collect", "sammeln", "összegyűjt", "colectează"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "filtration_basic_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Evaporation", "Eindampfen", "Bepárlás", "Evaporare"),
      text: L("When water evaporates, the dissolved solid stays behind.", "Wenn Wasser verdampft, bleibt der gelöste Stoff zurück.", "Amikor a víz elpárolog, az oldott anyag visszamarad.", "Când apa se evaporă, solidul dizolvat rămâne."),
      inst: GAP_INST,
      h1: L("Water leaves, solid stays.", "Wasser geht weg, Feststoff bleibt.", "A víz eltűnik, a szilárd marad.", "Apa pleacă, solidul rămâne."),
      h2: L("Pick the process word.", "Wähle das Prozesswort.", "Válaszd ki a folyamat szavát.", "Alege cuvântul procesului."),
      sent: L("After evaporation, salt is ___.", "Nach dem Eindampfen ist Salz ___.", "A bepárlás után a só ___.", "După evaporare, sarea este ___."),
      c1: L("left behind", "zurückgeblieben", "visszamarad", "lăsată în urmă"),
      c2: L("melted", "geschmolzen", "megolvadt", "topită"),
      c3: L("frozen", "gefroren", "megfagyott", "înghețată"),
      c4: L("burned", "verbrannt", "elégett", "arsă"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "evaporation_basic_mcq" },
  },
];

const I4: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Water", "Wasser", "Víz", "Apă"),
      text: L("Water is special: it flows, dissolves many things, and matters for life.", "Wasser ist besonders: Es fließt, löst vieles und ist wichtig fürs Leben.", "A víz különleges: folyik, sok mindent old és fontos az élethez.", "Apa este specială: curge, dizolvă multe lucruri și este importantă pentru viață."),
      inst: MATCH_INST,
      h1: L("Think about water behavior.", "Denk an das Verhalten von Wasser.", "Gondolj a víz viselkedésére.", "Gândește-te la comportamentul apei."),
      h2: L("Match water with facts.", "Ordne Wasser den Fakten zu.", "Párosítsd a vizet a tényekkel.", "Potrivește apa cu faptele."),
      l1: L("water", "Wasser", "víz", "apă"),
      r1: L("flows", "fließt", "folyik", "curge"),
      l2: L("water", "Wasser", "víz", "apă"),
      r2: L("dissolves salt", "löst Salz", "feloldja a sót", "dizolvă sarea"),
      l3: L("water", "Wasser", "víz", "apă"),
      r3: L("can evaporate", "kann verdampfen", "elpárologhat", "poate evapora"),
      l4: L("water", "Wasser", "víz", "apă"),
      r4: L("is important", "ist wichtig", "fontos", "este importantă"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "water_properties_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Water Cycle", "Wasserkreislauf", "Víz körforgása", "Ciclul apei"),
      text: L("Water goes up, forms clouds, and falls back as rain.", "Wasser steigt auf, bildet Wolken und fällt als Regen zurück.", "A víz felszáll, felhőt alkot, majd esőként visszahullik.", "Apa urcă, formează nori și cade înapoi ca ploaie."),
      inst: ORDER_INST,
      h1: L("First heat, then clouds.", "Erst Wärme, dann Wolken.", "Először meleg, aztán felhő.", "Mai întâi căldură, apoi nori."),
      h2: L("Then rain returns.", "Dann kommt der Regen zurück.", "Aztán visszatér az eső.", "Apoi revine ploaia."),
      w1: L("evaporation", "Verdunstung", "elpárolgás", "evaporare"),
      w2: L("clouds", "Wolken", "felhők", "nori"),
      w3: L("rain", "Regen", "eső", "ploaie"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "water_cycle_chem_mcq" },
  },
  {
    id: "t3",
    difficulty: "easy",
    labels: {
      title: L("Air is a Mixture", "Luft ist ein Gemisch", "A levegő keverék", "Aerul este un amestec"),
      text: L("Air contains several gases, not just one substance.", "Luft enthält mehrere Gase, nicht nur einen Stoff.", "A levegő több gázból áll, nem csak egy anyagból.", "Aerul conține mai multe gaze, nu doar o singură substanță."),
      inst: SORT_INST,
      h1: L("Pick the gases that belong in air.", "Wähle die Gase, die zur Luft gehören.", "Válaszd ki a levegő gázait.", "Alege gazele care fac parte din aer."),
      h2: L("Air is mixed, not pure.", "Luft ist gemischt, nicht rein.", "A levegő kevert, nem tiszta.", "Aerul este amestecat, nu pur."),
      b1: L("air gases", "Luftgase", "levegőgázok", "gaze din aer"),
      b2: L("not in air", "nicht in Luft", "nincs a levegőben", "nu sunt în aer"),
      i1: L("oxygen", "Sauerstoff", "oxigén", "oxigen"),
      i2: L("nitrogen", "Stickstoff", "nitrogén", "azot"),
      i3: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      i4: L("gold", "Gold", "arany", "aur"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "air", label: "b1" }, { id: "notair", label: "b2" }],
      items: [
        { text: "i1", bucketId: "air" },
        { text: "i2", bucketId: "air" },
        { text: "i3", bucketId: "air" },
        { text: "i4", bucketId: "notair" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "air_is_mixture_mcq" },
  },
  {
    id: "t4",
    difficulty: "medium",
    labels: {
      title: L("Oxygen for Burning", "Sauerstoff fürs Brennen", "Oxigén az égéshez", "Oxigen pentru ardere"),
      text: L("Burning needs oxygen.", "Brennen braucht Sauerstoff.", "Az égéshez oxigén kell.", "Arderea are nevoie de oxigen."),
      inst: GAP_INST,
      h1: L("Fire uses oxygen.", "Feuer verbraucht Sauerstoff.", "A tűz oxigént használ.", "Focul folosește oxigen."),
      h2: L("Choose what is needed.", "Wähle, was gebraucht wird.", "Válaszd ki, mire van szükség.", "Alege ce este necesar."),
      sent: L("Burning needs ___.", "Brennen braucht ___.", "Az égéshez ___ kell.", "Arderea are nevoie de ___."),
      c1: L("oxygen", "Sauerstoff", "oxigén", "oxigen"),
      c2: L("salt", "Salz", "só", "sare"),
      c3: L("glass", "Glas", "üveg", "sticlă"),
      c4: L("paper", "Papier", "papír", "hârtie"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "oxygen_for_burning_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Carbon Dioxide", "Kohlenstoffdioxid", "Szén-dioxid", "Dioxid de carbon"),
      text: L("Carbon dioxide is a gas we breathe out and plants use.", "Kohlenstoffdioxid ist ein Gas, das wir ausatmen und das Pflanzen nutzen.", "A szén-dioxid egy gáz, amelyet kilélegzünk, és a növények használnak.", "Dioxidul de carbon este un gaz pe care îl expirăm și pe care plantele îl folosesc."),
      inst: MATCH_INST,
      h1: L("Think about breath and plants.", "Denk an Atmung und Pflanzen.", "Gondolj a légzésre és a növényekre.", "Gândește-te la respirație și plante."),
      h2: L("Match where it appears.", "Ordne zu, wo es vorkommt.", "Párosítsd, hol fordul elő.", "Potrivește unde apare."),
      l1: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      r1: L("in exhaled air", "in ausgeatmeter Luft", "kilélegzett levegőben", "în aerul expirat"),
      l2: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      r2: L("used by plants", "von Pflanzen genutzt", "a növények használják", "folosit de plante"),
      l3: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      r3: L("in burning", "beim Brennen", "égéskor", "la ardere"),
      l4: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      r4: L("a gas", "ein Gas", "egy gáz", "un gaz"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "carbon_dioxide_intro_mcq" },
  },
];

const I5: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Physical or Chemical?", "Physikalisch oder chemisch?", "Fizikai vagy kémiai?", "Fizic sau chimic?"),
      text: L("Some changes only change form, others make a new substance.", "Manche Veränderungen ändern nur die Form, andere bilden einen neuen Stoff.", "Van, ami csak alakot változtat, máskor új anyag jön létre.", "Unele schimbări modifică doar forma, altele creează o substanță nouă."),
      inst: SORT_INST,
      h1: L("Form change or new substance?", "Formänderung oder neuer Stoff?", "Alakváltozás vagy új anyag?", "Schimbare de formă sau substanță nouă?"),
      h2: L("Sort the examples.", "Sortiere die Beispiele.", "Rendezd a példákat.", "Grupează exemplele."),
      b1: L("physical", "physikalisch", "fizikai", "fizic"),
      b2: L("chemical", "chemisch", "kémiai", "chimic"),
      i1: L("melting ice", "Eis schmilzt", "jég olvad", "gheață topită"),
      i2: L("burning paper", "Papier brennt", "papír ég", "hârtie arde"),
      i3: L("tearing paper", "Papier reißt", "papír szakad", "hârtie ruptă"),
      i4: L("rusting nail", "Nagel rostet", "szög rozsdásodik", "cui ruginește"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "physical", label: "b1" }, { id: "chemical", label: "b2" }],
      items: [
        { text: "i1", bucketId: "physical" },
        { text: "i2", bucketId: "chemical" },
        { text: "i3", bucketId: "physical" },
        { text: "i4", bucketId: "chemical" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "physical_vs_chemical_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Burning", "Brennen", "Égés", "Ardere"),
      text: L("Burning is a chemical change with heat and light.", "Brennen ist eine chemische Veränderung mit Wärme und Licht.", "Az égés kémiai változás, hővel és fénnyel.", "Arderea este o schimbare chimică cu căldură și lumină."),
      inst: MATCH_INST,
      h1: L("What shows burning?", "Was zeigt Brennen?", "Mi mutatja az égést?", "Ce arată arderea?"),
      h2: L("Match the clues.", "Ordne die Hinweise zu.", "Párosítsd a jeleket.", "Potrivește indiciile."),
      l1: L("smoke", "Rauch", "füst", "fum"),
      r1: L("a burning sign", "ein Zeichen fürs Brennen", "az égés jele", "semn de ardere"),
      l2: L("heat", "Wärme", "hő", "căldură"),
      r2: L("comes from fire", "kommt vom Feuer", "a tűzből jön", "vine din foc"),
      l3: L("light", "Licht", "fény", "lumină"),
      r3: L("glows", "leuchtet", "világít", "strălucește"),
      l4: L("ash", "Asche", "hamu", "cenușă"),
      r4: L("left behind", "bleibt übrig", "visszamarad", "rămâne în urmă"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "burning_signs_mcq" },
  },
  {
    id: "t3",
    difficulty: "easy",
    labels: {
      title: L("Rusting", "Rosten", "Rozsdásodás", "Ruginire"),
      text: L("Iron rusts when it meets water and air.", "Eisen rostet, wenn es mit Wasser und Luft in Berührung kommt.", "A vas akkor rozsdásodik, ha vízzel és levegővel találkozik.", "Fierul ruginește când întâlnește apă și aer."),
      inst: HIGHLIGHT_INST,
      h1: L("Rust needs air and water.", "Rost braucht Luft und Wasser.", "A rozsda levegőt és vizet igényel.", "Rugina are nevoie de aer și apă."),
      h2: L("Find the key parts.", "Finde die wichtigen Teile.", "Találd meg a fontos részeket.", "Găsește părțile-cheie."),
      w1: L("iron", "Eisen", "vas", "fier"),
      w2: L("water", "Wasser", "víz", "apă"),
      w3: L("air", "Luft", "levegő", "aer"),
      w4: L("rust", "Rost", "rozsda", "rugină"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [0, 1, 2, 3],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "rusting_intro_mcq" },
  },
  {
    id: "t4",
    difficulty: "medium",
    labels: {
      title: L("Dissolve or React?", "Lösen oder reagieren?", "Oldódik vagy reagál?", "Se dizolvă sau reacționează?"),
      text: L("Sometimes a substance just dissolves. Sometimes a new substance appears.", "Manchmal löst sich ein Stoff nur. Manchmal entsteht ein neuer Stoff.", "Néha az anyag csak oldódik. Máskor új anyag keletkezik.", "Uneori o substanță doar se dizolvă. Alteori apare o substanță nouă."),
      inst: SORT_INST,
      h1: L("Look for new substance signs.", "Achte auf Zeichen eines neuen Stoffes.", "Keress új anyag jeleit.", "Caută semnele unei substanțe noi."),
      h2: L("Sort the processes.", "Sortiere die Vorgänge.", "Rendezd a folyamatokat.", "Grupează procesele."),
      b1: L("dissolve", "lösen", "oldódik", "se dizolvă"),
      b2: L("react", "reagieren", "reagál", "reacționează"),
      i1: L("sugar in water", "Zucker in Wasser", "cukor vízben", "zahăr în apă"),
      i2: L("vinegar + baking soda", "Essig + Natron", "ecet + szódabikarbóna", "oțet + bicarbonat"),
      i3: L("salt in water", "Salz in Wasser", "só vízben", "sare în apă"),
      i4: L("metal rusting", "Metall rostet", "fém rozsdásodik", "metal ruginește"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "dissolve", label: "b1" }, { id: "react", label: "b2" }],
      items: [
        { text: "i1", bucketId: "dissolve" },
        { text: "i2", bucketId: "react" },
        { text: "i3", bucketId: "dissolve" },
        { text: "i4", bucketId: "react" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "dissolving_vs_reacting_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Reaction Clues", "Reaktionszeichen", "Reakció jelei", "Indicii de reacție"),
      text: L("Gas, color change, heat, or a new solid can show a reaction.", "Gas, Farbänderung, Wärme oder ein neuer Feststoff können auf eine Reaktion hinweisen.", "Gáz, színváltozás, hő vagy új szilárd anyag mutathat reakciót.", "Gazul, schimbarea culorii, căldura sau un solid nou pot arăta o reacție."),
      inst: HIGHLIGHT_INST,
      h1: L("Look for changes.", "Achte auf Veränderungen.", "Figyelj a változásokra.", "Caută schimbările."),
      h2: L("Which clues matter?", "Welche Hinweise zählen?", "Mely jelek számítanak?", "Ce indicii contează?"),
      w1: L("gas", "Gas", "gáz", "gaz"),
      w2: L("color change", "Farbwechsel", "színváltozás", "schimbare de culoare"),
      w3: L("heat", "Wärme", "hő", "căldură"),
      w4: L("new solid", "neuer Feststoff", "új szilárd anyag", "solid nou"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [0, 1, 2, 3],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "reaction_clues_mcq" },
  },
];

const I6: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Lab Rules", "Laborregeln", "Labor szabályok", "Reguli de laborator"),
      text: L("Safety comes first in the lab.", "Sicherheit geht im Labor vor.", "A laborban a biztonság az első.", "Siguranța este pe primul loc în laborator."),
      inst: HIGHLIGHT_INST,
      h1: L("Find the safe actions.", "Finde die sicheren Handlungen.", "Találd meg a biztonságos tetteket.", "Găsește acțiunile sigure."),
      h2: L("Do not touch dangerous things.", "Berühre nichts Gefährliches.", "Ne érj veszélyes dolgokhoz.", "Nu atinge lucrurile periculoase."),
      w1: L("goggles", "Schutzbrille", "védőszemüveg", "ochelari de protecție"),
      w2: L("run", "rennen", "futni", "aleargă"),
      w3: L("taste", "kosten", "megkóstolni", "gusta"),
      w4: L("listen", "zuhören", "figyelni", "ascultă"),
    },
    svg: { type: "kemia-diagram", name: "LabSafetySvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [0, 3],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "lab_rules_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Hazard Symbols", "Gefahrensymbole", "Veszélyjelek", "Simboluri de pericol"),
      text: L("Hazard symbols warn us about danger.", "Gefahrensymbole warnen vor Gefahr.", "A veszélyjelek figyelmeztetnek a veszélyre.", "Simbolurile de pericol ne avertizează."),
      inst: MATCH_INST,
      h1: L("Every symbol has a meaning.", "Jedes Symbol hat eine Bedeutung.", "Minden jelnek van jelentése.", "Fiecare simbol are un sens."),
      h2: L("Match symbol and meaning.", "Ordne Symbol und Bedeutung zu.", "Párosítsd a jelet és a jelentést.", "Potrivește simbolul cu sensul."),
      l1: L("flame", "Flamme", "láng", "flacără"),
      r1: L("flammable", "entzündbar", "gyúlékony", "inflamabil"),
      l2: L("skull", "Totenkopf", "koponya", "craniu"),
      r2: L("toxic", "giftig", "mérgező", "toxic"),
      l3: L("corrosion", "Ätzwirkung", "maró hatás", "coroziv"),
      r3: L("can burn skin", "kann Haut verätzen", "bőrt marhat", "poate arde pielea"),
      l4: L("electric", "elektrisch", "elektromos", "electric"),
      r4: L("shock danger", "Stromschlaggefahr", "áramütés veszélye", "pericol de șoc"),
    },
    svg: { type: "kemia-diagram", name: "LabSafetySvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "hazard_symbols_basic_mcq" },
  },
  {
    id: "t3",
    difficulty: "easy",
    labels: {
      title: L("Measuring Volume", "Volumen messen", "Térfogat mérése", "Măsurarea volumului"),
      text: L("We measure liquid volume with a cylinder or cup.", "Das Volumen von Flüssigkeiten messen wir mit Zylinder oder Becher.", "A folyadék térfogatát hengerrel vagy pohárral mérjük.", "Volumul lichidelor se măsoară cu un cilindru sau pahar."),
      inst: DIAGRAM_INST,
      h1: L("Look at the container.", "Schau auf das Gefäß.", "Nézd meg az edényt.", "Privește recipientul."),
      h2: L("Label the measuring parts.", "Beschrifte die Mess-Teile.", "Jelöld a mérési részeket.", "Etichetează părțile de măsurare."),
      a1: L("scale", "Skala", "skála", "scară"),
      a2: L("liquid", "Flüssigkeit", "folyadék", "lichid"),
      a3: L("meniscus", "Meniskus", "meniszkusz", "menisc"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "label-diagram",
      areas: [
        { id: "a1", x: 50, y: 20, label: "a1" },
        { id: "a2", x: 50, y: 55, label: "a2" },
        { id: "a3", x: 50, y: 80, label: "a3" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "measuring_volume_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Measuring Mass", "Masse messen", "Tömeg mérése", "Măsurarea masei"),
      text: L("Mass is measured with a balance or scale.", "Masse misst man mit Waage oder Balkenwaage.", "A tömeget mérlegen mérjük.", "Masa se măsoară cu o balanță sau cântar."),
      inst: MATCH_INST,
      h1: L("Mass uses grams and kilograms.", "Masse benutzt Gramm und Kilogramm.", "A tömeg grammot és kilogrammot használ.", "Masa folosește grame și kilograme."),
      h2: L("Match object and unit.", "Ordne Objekt und Einheit zu.", "Párosítsd a tárgyat és az egységet.", "Potrivește obiectul și unitatea."),
      l1: L("small object", "kleiner Gegenstand", "kis tárgy", "obiect mic"),
      r1: L("grams", "Gramm", "gramm", "grame"),
      l2: L("big object", "großer Gegenstand", "nagy tárgy", "obiect mare"),
      r2: L("kilograms", "Kilogramm", "kilogramm", "kilograme"),
      l3: L("scale", "Waage", "mérleg", "cântar"),
      r3: L("measures mass", "misst Masse", "tömeget mér", "măsoară masa"),
      l4: L("balance", "Balkenwaage", "mérleg", "balanță"),
      r4: L("shows comparison", "zeigt Vergleich", "összehasonlít", "arată comparația"),
    },
    svg: simpleIcon("⚖️", "mass", "#F8FAFC", "#7C3AED"),
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "measuring_mass_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Simple Experiments", "Einfache Versuche", "Egyszerű kísérletek", "Experimente simple"),
      text: L("Good experiments need a clear question and careful observation.", "Gute Versuche brauchen eine klare Frage und genaue Beobachtung.", "A jó kísérlethez világos kérdés és pontos megfigyelés kell.", "Experimentele bune au nevoie de o întrebare clară și observație atentă."),
      inst: GAP_INST,
      h1: L("Think: observe, test, learn.", "Denk: beobachten, testen, lernen.", "Gondolj erre: megfigyelés, kipróbálás, tanulás.", "Gândește: observă, testează, învață."),
      h2: L("Choose the experiment word.", "Wähle das Versuchs-Wort.", "Válaszd a kísérlet szavát.", "Alege cuvântul experimentului."),
      sent: L("A good experiment needs ___.", "Ein guter Versuch braucht ___.", "Egy jó kísérlethez ___ kell.", "Un experiment bun are nevoie de ___."),
      c1: L("careful observation", "genaue Beobachtung", "pontos megfigyelés", "observație atentă"),
      c2: L("no question", "keine Frage", "nincs kérdés", "fără întrebare"),
      c3: L("random guessing", "raten", "vaktippelés", "ghicit la întâmplare"),
      c4: L("noise", "Lärm", "zaj", "zgomot"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "simple_experiments_mcq" },
  },
];

const I7: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Review: Materials", "Wiederholung: Stoffe", "Ismétlés: anyagok", "Recapitulare: materiale"),
      text: L("Let's review solids, liquids, gases, and simple properties.", "Wiederholen wir Feststoffe, Flüssigkeiten, Gase und einfache Eigenschaften.", "Ismételjük át a szilárd, folyékony, gáz és egyszerű tulajdonságokat.", "Să recapitulăm solidele, lichidele, gazele și proprietățile simple."),
      inst: SORT_INST,
      h1: L("Use what you learned.", "Nutze, was du gelernt hast.", "Használd, amit tanultál.", "Folosește ce ai învățat."),
      h2: L("Sort the review examples.", "Sortiere die Wiederholungsbeispiele.", "Rendezd az ismétlő példákat.", "Grupează exemplele de recapitulare."),
      b1: L("state", "Zustand", "állapot", "stare"),
      b2: L("property", "Eigenschaft", "tulajdonság", "proprietate"),
      i1: L("ice", "Eis", "jég", "gheață"),
      i2: L("water", "Wasser", "víz", "apă"),
      i3: L("air", "Luft", "levegő", "aer"),
      i4: L("soft sponge", "weicher Schwamm", "puha szivacs", "burete moale"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "state", label: "b1" }, { id: "property", label: "b2" }],
      items: [
        { text: "i1", bucketId: "state" },
        { text: "i2", bucketId: "state" },
        { text: "i3", bucketId: "state" },
        { text: "i4", bucketId: "property" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "materials_daily_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Review: Particles", "Wiederholung: Teilchen", "Ismétlés: részecskék", "Recapitulare: particule"),
      text: L("Particle ideas explain all substances.", "Teilchenideen erklären alle Stoffe.", "A részecske-tan minden anyagot megmagyaráz.", "Ideile despre particule explică toate substanțele."),
      inst: MATCH_INST,
      h1: L("Look for dense and spread-out patterns.", "Achte auf dichte und verteilte Muster.", "Keress sűrű és szétterülő mintákat.", "Caută modele dense și răspândite."),
      h2: L("Match particle ideas.", "Ordne Teilchenideen zu.", "Párosítsd a részecske-ötleteket.", "Potrivește ideile despre particule."),
      l1: L("close together", "dicht zusammen", "közel", "apropiate"),
      r1: L("solid", "fest", "szilárd", "solid"),
      l2: L("far apart", "weit auseinander", "távol", "departe"),
      r2: L("gas", "gasförmig", "gáz", "gaz"),
      l3: L("move faster", "bewegen sich schneller", "gyorsabban mozognak", "se mișcă mai repede"),
      r3: L("warm", "warm", "meleg", "cald"),
      l4: L("move slower", "bewegen sich langsamer", "lassabban mozognak", "se mișcă mai încet"),
      r4: L("cold", "kalt", "hideg", "rece"),
    },
    svg: { type: "kemia-diagram", name: "AtomSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "particle_idea_mcq" },
  },
  {
    id: "t3",
    difficulty: "medium",
    labels: {
      title: L("Review: Motion", "Wiederholung: Bewegung", "Ismétlés: mozgás", "Recapitulare: mișcare"),
      text: L("Particles move more when things are warmer.", "Teilchen bewegen sich mehr, wenn es wärmer ist.", "A részecskék többet mozognak, ha melegebb van.", "Particulele se mișcă mai mult când este mai cald."),
      inst: ORDER_INST,
      h1: L("Warm first, then faster.", "Erst warm, dann schneller.", "Először meleg, aztán gyorsabb.", "Mai întâi cald, apoi mai rapid."),
      h2: L("Put them in order.", "Bringe sie in Ordnung.", "Tedd sorrendbe.", "Pune-le în ordine."),
      w1: L("cold", "kalt", "hideg", "rece"),
      w2: L("warm", "warm", "meleg", "cald"),
      w3: L("hot", "heiß", "forró", "fierbinte"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "particle_motion_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Review: State Changes", "Wiederholung: Zustandsänderungen", "Ismétlés: állapotváltozások", "Recapitulare: schimbări de stare"),
      text: L("Heating and cooling can melt, freeze, or evaporate matter.", "Erwärmen und Abkühlen können Stoffe schmelzen, gefrieren oder verdampfen lassen.", "A melegítés és hűtés olvaszthat, fagyaszthat vagy párologtathat.", "Încălzirea și răcirea pot topi, îngheța sau evapora materia."),
      inst: GAP_INST,
      h1: L("Think of ice and steam.", "Denk an Eis und Dampf.", "Gondolj a jégre és a gőzre.", "Gândește-te la gheață și abur."),
      h2: L("Choose the right change.", "Wähle die richtige Veränderung.", "Válaszd a helyes változást.", "Alege schimbarea corectă."),
      sent: L("Heating can make ice ___.", "Erwärmen kann Eis ___.", "A melegítés a jeget ___.", "Încălzirea poate face gheața ___."),
      c1: L("melt", "schmelzen", "olvadni", "să se topească"),
      c2: L("rust", "rosten", "rozsdásodni", "să ruginească"),
      c3: L("freeze", "gefrieren", "fagyni", "să înghețe"),
      c4: L("burn", "brennen", "égni", "să ardă"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "state_changes_basic_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Review: Water & Air", "Wiederholung: Wasser & Luft", "Ismétlés: víz és levegő", "Recapitulare: apă și aer"),
      text: L("Water and air are everyday mixtures and materials we know well.", "Wasser und Luft sind alltägliche Gemische und Stoffe, die wir gut kennen.", "A víz és a levegő hétköznapi keverékek és anyagok.", "Apa és aerul sunt amestecuri și materiale cotidiene pe care le cunoaștem bine."),
      inst: MATCH_INST,
      h1: L("Think of gases and dissolving.", "Denk an Gase und Lösen.", "Gondolj a gázokra és oldódásra.", "Gândește-te la gaze și dizolvare."),
      h2: L("Match the review facts.", "Ordne die Wiederholungsfakten zu.", "Párosítsd az ismétlő tényeket.", "Potrivește faptele de recapitulare."),
      l1: L("air", "Luft", "levegő", "aer"),
      r1: L("mixture of gases", "Gemisch aus Gasen", "gázok keveréke", "amestec de gaze"),
      l2: L("water", "Wasser", "víz", "apă"),
      r2: L("flows and dissolves", "fließt und löst", "folyik és old", "curge și dizolvă"),
      l3: L("oxygen", "Sauerstoff", "oxigén", "oxigen"),
      r3: L("helps burning", "hilft beim Brennen", "segíti az égést", "ajută arderea"),
      l4: L("carbon dioxide", "Kohlenstoffdioxid", "szén-dioxid", "dioxid de carbon"),
      r4: L("used by plants", "von Pflanzen genutzt", "növények használják", "folosit de plante"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "water_properties_mcq" },
  },
];

const I8: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Review: Mixtures", "Wiederholung: Gemische", "Ismétlés: keverékek", "Recapitulare: amestecuri"),
      text: L("Mixtures can be pure or mixed, dissolved or filtered.", "Gemische können rein oder gemischt, gelöst oder gefiltert sein.", "A keverékek lehetnek tiszták vagy kevertek, oldottak vagy szűrtek.", "Amestecurile pot fi pure sau amestecate, dizolvate sau filtrate."),
      inst: SORT_INST,
      h1: L("Sort by mixture idea.", "Sortiere nach Gemisch-Idee.", "Rendezd keverék szerint.", "Grupează după ideea de amestec."),
      h2: L("Keep solutions together.", "Halte Lösungen zusammen.", "Tartsd együtt az oldatokat.", "Ține soluțiile împreună."),
      b1: L("solution", "Lösung", "oldat", "soluție"),
      b2: L("mixture", "Gemisch", "keverék", "amestec"),
      i1: L("salt water", "Salzwasser", "sós víz", "apă sărată"),
      i2: L("salad", "Salat", "saláta", "salată"),
      i3: L("muddy water", "Schlammwasser", "sáros víz", "apă tulbure"),
      i4: L("gold", "Gold", "arany", "aur"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "solution", label: "b1" }, { id: "mixture", label: "b2" }],
      items: [
        { text: "i1", bucketId: "solution" },
        { text: "i2", bucketId: "mixture" },
        { text: "i3", bucketId: "mixture" },
        { text: "i4", bucketId: "solution" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "pure_vs_mixture_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Review: Solutions", "Wiederholung: Lösungen", "Ismétlés: oldatok", "Recapitulare: soluții"),
      text: L("In a solution, one substance dissolves in another.", "In einer Lösung löst sich ein Stoff in einem anderen.", "Oldatban az egyik anyag a másikban oldódik.", "Într-o soluție, o substanță se dizolvă în alta."),
      inst: MATCH_INST,
      h1: L("Remember solute and solvent.", "Denke an gelösten Stoff und Lösungsmittel.", "Emlékezz az oldott anyagra és az oldószerre.", "Ține minte solutul și solventul."),
      h2: L("Match the solution facts.", "Ordne die Lösungs-Fakten zu.", "Párosítsd az oldat-tényeket.", "Potrivește faptele despre soluții."),
      l1: L("solute", "gelöster Stoff", "oldott anyag", "solut"),
      r1: L("dissolves", "löst sich", "feloldódik", "se dizolvă"),
      l2: L("solvent", "Lösungsmittel", "oldószer", "solvent"),
      r2: L("does the dissolving", "ermöglicht das Lösen", "segíti az oldódást", "permite dizolvarea"),
      l3: L("sugar water", "Zuckerwasser", "cukros víz", "apă cu zahăr"),
      r3: L("a solution", "eine Lösung", "egy oldat", "o soluție"),
      l4: L("salt water", "Salzwasser", "sós víz", "apă sărată"),
      r4: L("a solution", "eine Lösung", "egy oldat", "o soluție"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "solutions_intro_mcq" },
  },
  {
    id: "t3",
    difficulty: "easy",
    labels: {
      title: L("Review: Water Cycle", "Wiederholung: Wasserkreislauf", "Ismétlés: vízkörforgás", "Recapitulare: ciclul apei"),
      text: L("Evaporation, clouds, and rain keep water moving.", "Verdunstung, Wolken und Regen halten das Wasser in Bewegung.", "A párolgás, a felhő és az eső mozgatják a vizet.", "Evaporarea, norii și ploaia mențin apa în mișcare."),
      inst: ORDER_INST,
      h1: L("Start with vapor.", "Beginne mit Dampf.", "Kezdd a vízgőzzel.", "Începe cu vapori."),
      h2: L("End with rain.", "Ende mit Regen.", "Végül jön az eső.", "Încheie cu ploaia."),
      w1: L("evaporation", "Verdunstung", "elpárolgás", "evaporare"),
      w2: L("clouds", "Wolken", "felhők", "nori"),
      w3: L("rain", "Regen", "eső", "ploaie"),
    },
    svg: { type: "kemia-diagram", name: "StatesSvg" },
    interactive: {
      type: "word-order",
      words: ["w1", "w2", "w3"],
      correctOrder: [0, 1, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "water_cycle_chem_mcq" },
  },
  {
    id: "t4",
    difficulty: "medium",
    labels: {
      title: L("Review: Burning", "Wiederholung: Brennen", "Ismétlés: égés", "Recapitulare: ardere"),
      text: L("Burning needs oxygen and gives heat and light.", "Brennen braucht Sauerstoff und gibt Wärme und Licht.", "Az égéshez oxigén kell, és hőt valamint fényt ad.", "Arderea are nevoie de oxigen și dă căldură și lumină."),
      inst: GAP_INST,
      h1: L("Remember oxygen.", "Erinnere dich an Sauerstoff.", "Emlékezz az oxigénre.", "Ține minte oxigenul."),
      h2: L("Pick the burning word.", "Wähle das Brenn-Wort.", "Válaszd az égés szavát.", "Alege cuvântul arderii."),
      sent: L("Burning needs ___.", "Brennen braucht ___.", "Az égéshez ___ kell.", "Arderea are nevoie de ___."),
      c1: L("oxygen", "Sauerstoff", "oxigén", "oxigen"),
      c2: L("salt", "Salz", "só", "sare"),
      c3: L("paper", "Papier", "papír", "hârtie"),
      c4: L("glass", "Glas", "üveg", "sticlă"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "oxygen_for_burning_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Review: Burning Signs", "Wiederholung: Brennzeichen", "Ismétlés: égés jelei", "Recapitulare: semnele arderii"),
      text: L("Smoke, heat, light, and ash can show burning.", "Rauch, Wärme, Licht und Asche können Brennen zeigen.", "A füst, hő, fény és hamu az égést mutathatják.", "Fumul, căldura, lumina și cenușa pot arăta arderea."),
      inst: HIGHLIGHT_INST,
      h1: L("Find all clues.", "Finde alle Hinweise.", "Találd meg az összes jelet.", "Găsește toate indiciile."),
      h2: L("Choose the signs of burning.", "Wähle die Brennzeichen.", "Válaszd az égés jeleit.", "Alege semnele arderii."),
      w1: L("smoke", "Rauch", "füst", "fum"),
      w2: L("heat", "Wärme", "hő", "căldură"),
      w3: L("light", "Licht", "fény", "lumină"),
      w4: L("ash", "Asche", "hamu", "cenușă"),
    },
    svg: { type: "kemia-diagram", name: "ReactionSvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [0, 1, 2, 3],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "burning_signs_mcq" },
  },
];

const I9: ChemTopic[] = [
  {
    id: "t1",
    difficulty: "easy",
    labels: {
      title: L("Lab Review", "Labor-Wiederholung", "Labor ismétlés", "Recapitulare de laborator"),
      text: L("Safety rules help us work carefully in the lab.", "Laborregeln helfen uns, sorgfältig zu arbeiten.", "A labor szabályok segítenek óvatosan dolgozni.", "Regulile de laborator ne ajută să lucrăm atent."),
      inst: HIGHLIGHT_INST,
      h1: L("Pick safe actions.", "Wähle sichere Handlungen.", "Válaszd a biztonságos cselekvéseket.", "Alege acțiunile sigure."),
      h2: L("Stay careful.", "Bleib vorsichtig.", "Maradj óvatos.", "Rămâi atent."),
      w1: L("goggles", "Schutzbrille", "védőszemüveg", "ochelari de protecție"),
      w2: L("taste", "kosten", "megkóstolni", "a gusta"),
      w3: L("ask first", "zuerst fragen", "előbb megkérdezni", "întreabă întâi"),
      w4: L("run", "rennen", "futni", "alergă"),
    },
    svg: { type: "kemia-diagram", name: "LabSafetySvg" },
    interactive: {
      type: "highlight-text",
      tokens: ["w1", "w2", "w3", "w4"],
      correctIndices: [0, 2],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "lab_rules_mcq" },
  },
  {
    id: "t2",
    difficulty: "easy",
    labels: {
      title: L("Hazards Review", "Gefahren-Wiederholung", "Veszélyek ismétlés", "Recapitulare: pericole"),
      text: L("Hazard symbols warn us about flammable, toxic, or corrosive things.", "Gefahrensymbole warnen vor entzündbaren, giftigen oder ätzenden Stoffen.", "A veszélyjelek gyúlékony, mérgező vagy maró anyagokra figyelmeztetnek.", "Simbolurile de pericol avertizează despre substanțe inflamabile, toxice sau corozive."),
      inst: MATCH_INST,
      h1: L("Symbols have meanings.", "Symbole haben Bedeutungen.", "A jeleknek jelentése van.", "Simbolurile au sens."),
      h2: L("Review the meanings.", "Wiederhole die Bedeutungen.", "Ismételd át a jelentéseket.", "Recapitulează sensurile."),
      l1: L("flame", "Flamme", "láng", "flacără"),
      r1: L("flammable", "entzündbar", "gyúlékony", "inflamabil"),
      l2: L("skull", "Totenkopf", "koponya", "craniu"),
      r2: L("toxic", "giftig", "mérgező", "toxic"),
      l3: L("corrosion", "Ätzwirkung", "maró", "coroziv"),
      r3: L("dangerous to skin", "gefährlich für Haut", "veszélyes a bőrre", "periculos pentru piele"),
      l4: L("electric", "elektrisch", "elektromos", "electric"),
      r4: L("shock", "Stromschlag", "áramütés", "șoc"),
    },
    svg: { type: "kemia-diagram", name: "LabSafetySvg" },
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "hazard_symbols_basic_mcq" },
  },
  {
    id: "t3",
    difficulty: "easy",
    labels: {
      title: L("Mass Review", "Masse-Wiederholung", "Tömeg ismétlés", "Recapitulare: masă"),
      text: L("Mass is measured with a balance and shown in grams or kilograms.", "Masse misst man mit einer Waage und zeigt sie in Gramm oder Kilogramm an.", "A tömeget mérlegen mérjük, grammal vagy kilogrammal.", "Masa se măsoară cu o balanță și se arată în grame sau kilograme."),
      inst: MATCH_INST,
      h1: L("Match object and unit.", "Ordne Objekt und Einheit zu.", "Párosítsd a tárgyat és az egységet.", "Potrivește obiectul și unitatea."),
      h2: L("Use grams and kilograms.", "Nutze Gramm und Kilogramm.", "Használd a grammot és kilogrammot.", "Folosește grame și kilograme."),
      l1: L("small object", "kleiner Gegenstand", "kis tárgy", "obiect mic"),
      r1: L("grams", "Gramm", "gramm", "grame"),
      l2: L("big object", "großer Gegenstand", "nagy tárgy", "obiect mare"),
      r2: L("kilograms", "Kilogramm", "kilogramm", "kilograme"),
      l3: L("scale", "Waage", "mérleg", "cântar"),
      r3: L("measures mass", "misst Masse", "tömeget mér", "măsoară masa"),
      l4: L("balance", "Balkenwaage", "mérleg", "balanță"),
      r4: L("shows comparison", "zeigt Vergleich", "összehasonlít", "arată comparația"),
    },
    svg: simpleIcon("⚖️", "mass", "#F8FAFC", "#7C3AED"),
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "l1", right: "r1" },
        { left: "l2", right: "r2" },
        { left: "l3", right: "r3" },
        { left: "l4", right: "r4" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "measuring_mass_mcq" },
  },
  {
    id: "t4",
    difficulty: "easy",
    labels: {
      title: L("Volume Review", "Volumen-Wiederholung", "Térfogat ismétlés", "Recapitulare: volum"),
      text: L("We use a measuring cylinder or cup to read liquid volume.", "Wir nutzen Messzylinder oder Becher, um das Volumen von Flüssigkeiten zu lesen.", "A folyadék térfogatát mérőhengerrel vagy pohárral mérjük.", "Folosim cilindrul sau paharul gradat pentru a citi volumul lichidelor."),
      inst: DIAGRAM_INST,
      h1: L("Find the scale.", "Finde die Skala.", "Találd meg a skálát.", "Găsește scala."),
      h2: L("Label the parts.", "Beschrifte die Teile.", "Jelöld meg a részeket.", "Etichetează părțile."),
      a1: L("scale", "Skala", "skála", "scară"),
      a2: L("liquid", "Flüssigkeit", "folyadék", "lichid"),
      a3: L("meniscus", "Meniskus", "meniszkusz", "menisc"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "label-diagram",
      areas: [
        { id: "a1", x: 50, y: 20, label: "a1" },
        { id: "a2", x: 50, y: 55, label: "a2" },
        { id: "a3", x: 50, y: 82, label: "a3" },
      ],
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "measuring_volume_mcq" },
  },
  {
    id: "t5",
    difficulty: "medium",
    labels: {
      title: L("Simple Experiments Review", "Wiederholung: einfache Versuche", "Egyszerű kísérletek ismétlés", "Recapitulare: experimente simple"),
      text: L("A good experiment has a question, a test, and careful observation.", "Ein guter Versuch hat eine Frage, einen Test und genaue Beobachtung.", "Egy jó kísérletnek van kérdése, próbája és megfigyelése.", "Un experiment bun are întrebare, test și observație atentă."),
      inst: GAP_INST,
      h1: L("Think: question and observation.", "Denk an Frage und Beobachtung.", "Gondolj a kérdésre és a megfigyelésre.", "Gândește-te la întrebare și observație."),
      h2: L("Choose the experiment idea.", "Wähle die Versuchsidee.", "Válaszd a kísérlet ötletét.", "Alege ideea experimentului."),
      sent: L("A good experiment needs ___.", "Ein guter Versuch braucht ___.", "Egy jó kísérlethez ___ kell.", "Un experiment bun are nevoie de ___."),
      c1: L("careful observation", "genaue Beobachtung", "pontos megfigyelés", "observație atentă"),
      c2: L("no question", "keine Frage", "nincs kérdés", "fără întrebare"),
      c3: L("random guessing", "Raten", "vaktippelés", "ghicit"),
      c4: L("noise", "Lärm", "zaj", "zgomot"),
    },
    svg: { type: "kemia-diagram", name: "BeakerSvg" },
    interactive: {
      type: "gap-fill",
      sentence: "sent",
      choices: ["c1", "c2", "c3", "c4"],
      correctIndex: 0,
      instruction: "inst",
      hint1: "h1",
      hint2: "h2",
    },
    quiz: { generate: "simple_experiments_mcq" },
  },
];

export const KEMIA_K5_I1_LABELS = makeIslandLabels(I1);
export const KEMIA_K5_I1_POOL = makePool(I1);
export const KEMIA_K5_I2_LABELS = makeIslandLabels(I2);
export const KEMIA_K5_I2_POOL = makePool(I2);
export const KEMIA_K5_I3_LABELS = makeIslandLabels(I3);
export const KEMIA_K5_I3_POOL = makePool(I3);
export const KEMIA_K5_I4_LABELS = makeIslandLabels(I4);
export const KEMIA_K5_I4_POOL = makePool(I4);
export const KEMIA_K5_I5_LABELS = makeIslandLabels(I5);
export const KEMIA_K5_I5_POOL = makePool(I5);
export const KEMIA_K5_I6_LABELS = makeIslandLabels(I6);
export const KEMIA_K5_I6_POOL = makePool(I6);
export const KEMIA_K5_I7_LABELS = makeIslandLabels(I7);
export const KEMIA_K5_I7_POOL = makePool(I7);
export const KEMIA_K5_I8_LABELS = makeIslandLabels(I8);
export const KEMIA_K5_I8_POOL = makePool(I8);
export const KEMIA_K5_I9_LABELS = makeIslandLabels(I9);
export const KEMIA_K5_I9_POOL = makePool(I9);
