// lib/explorerPools/magyarO5.ts

import type { PoolTopicDef } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// LABELS (hu)
// ─────────────────────────────────────────────────────────────────────────────

export const MAGYAR_O5_I1_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Hangtan Szigete",
    t1_title: "Magánhangzók",
    t1_text: "A beszédhangok egyik csoportja. Lehetnek magasak vagy mélyek.",
    t1_b1: "Mély (a, o, u)", t1_b2: "Magas (e, i, ö, ü)",
    t1_i1: "a", t1_i2: "o", t1_i3: "u", t1_i4: "e", t1_i5: "i", t1_i6: "ö", t1_i7: "ü",
    t1_inst: "Válogasd szét a hangokat hangrend szerint!",
    t2_title: "Hangrend",
    t2_text: "A szavak lehetnek mély, magas vagy vegyes hangrendűek.",
    t2_b1: "Mély hangrendű", t2_b2: "Magas hangrendű",
    t2_i1: "autó", t2_i2: "ablak", t2_i3: "ház", t2_i4: "tenisz", t2_i5: "tükör", t2_i6: "felhő",
    t2_inst: "Csoportosítsd a szavakat!",
    t3_title: "Illeszkedés",
    t3_text: "A toldalék magánhangzója igazodik a szótő magánhangzóihoz.",
    t3_l1: "ház", t3_r1: "-ban", t3_l2: "kert", t3_r2: "-ben", t3_l3: "erdő", t3_r3: "-ben",
    t3_inst: "Párosítsd a tövet a helyes raggal!",
    t4_title: "Mássalhangzók",
    t4_text: "A hangok másik csoportja. Lehetnek zöngések vagy zöngétlenek.",
    t4_b1: "Zöngés", t4_b2: "Zöngétlen",
    t4_i1: "b", t4_i2: "d", t4_i3: "g", t4_i4: "p", t4_i5: "t", t4_i6: "k",
    t4_inst: "Válogasd szét a mássalhangzókat!",
    t5_title: "Rövid és hosszú hangok",
    t5_text: "A hangok időtartama megváltoztathatja a szó jelentését.",
    t5_l1: "áru", t5_r1: "árú", t5_l2: "kor", t5_r2: "kór",
    t5_inst: "Párosítsd az alakokat!",
    t6_title: "A betűrend",
    t6_text: "A szavak ábécé szerinti sorrendje.",
    t6_w1: "alma", t6_w2: "asztal", t6_w3: "autó",
    t6_inst: "Tedd ábécé-sorrendbe a szavakat!",
    t7_title: "Zöngésség szerinti részleges hasonulás",
    t7_text: "Két egymás mellé kerülő mássalhangzó közül az egyik megváltozik (pl. népdal [nébdal]).",
    t7_tok1: "nép", t7_tok2: "dal", t7_tok3: "vas", t7_tok4: "golyó",
    t7_inst: "Melyik szópárnál van hasonulás?",
    t8_title: "Teljes hasonulás",
    t8_text: "Amikor a két hang teljesen azonossá válik (pl. vízzel = víz + vel).",
    t8_sent: "Késsel vágja a kenyeret. (Kéz + ___)", t8_c1: "vel", t8_c2: "sel", t8_c3: "el",
    t8_inst: "Mi volt az eredeti rag?",
    t9_title: "Összeolvadás",
    t9_text: "Két hangból egy harmadik, hosszú hang lesz (pl. tudja [tuggya]).",
    t9_sent: "Péter jól ___ a leckét.", t9_c1: "tudja", t9_c2: "mondja", t9_c3: "látja",
    t9_inst: "Válaszd az összeolvadásra példát!",
    t10_title: "Hangtan mestere",
    t10_q: "Milyen hangrendű a 'kávé' szó?",
    t10_t1: "vegyes", t10_t2: "mély", t10_t3: "magas",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I2_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Szóelemzés Szigete",
    t1_title: "A szótő",
    t1_text: "A szó jelentést hordozó magva.",
    t1_b1: "Szótő", t1_b2: "Toldalék",
    t1_i1: "asztal", t1_i2: "ház", t1_i3: "könyv", t1_i4: "-ban", t1_i5: "-ság",
    t1_inst: "Válogasd szét a részeket!",
    t2_title: "A képző",
    t2_text: "Megváltoztatja a szó jelentését vagy szófaját (pl. kert → kertész).",
    t2_l1: "tanul", t2_r1: "-ás", t2_l2: "asztal", t2_r2: "-os", t2_l3: "szép", t2_r3: "-ség",
    t2_inst: "Párosítsd a tövet a képzővel!",
    t3_title: "A jel",
    t3_text: "Módosítja a jelentést, de nem csinál új szót (pl. többes szám jele: -k).",
    t3_tok1: "házak", t3_tok2: "szebb", t3_tok3: "írt", t3_tok4: "alma",
    t3_inst: "Kattints a JELET tartalmazó szavakra!",
    t4_title: "A rag",
    t4_text: "A szó mondatbeli szerepét jelöli ki. Mindig a szó legvégén áll.",
    t4_sent: "A fiú az erdő___ sétál.", t4_c1: "ben", t4_c2: "ság", t4_c3: "bb",
    t4_inst: "Melyik a megfelelő rag?",
    t5_title: "Szóelemzési sorrend",
    t5_text: "Tő + képző + jel + rag.",
    t5_w1: "ház", t5_w2: "-as", t5_w3: "-ok", t5_w4: "-at",
    t5_inst: "Tedd helyes sorrendbe a toldalékokat!",
    t6_title: "Származékszó",
    t6_text: "Képzővel ellátott szó.",
    t6_b1: "Származékszó", t6_b2: "Alapszó",
    t6_i1: "olvasás", t6_i2: "író", t6_i3: "asztal", t6_i4: "ház",
    t6_inst: "Válogasd szét!",
    t7_title: "Többes szám jele",
    t7_text: "Azt mutatja, hogy több dologról van szó. Jele: -k.",
    t7_sent: "A ___ a fán énekelnek.", t7_c1: "madarak", t7_c2: "madár", t7_c3: "madárral",
    t7_inst: "Válaszd a többes számú alakot!",
    t8_title: "Múlt idő jele",
    t8_text: "Azt fejezi ki, hogy a cselekvés már megtörtént. Jele: -t vagy -tt.",
    t8_tok1: "olvasott", t8_tok2: "ment", t8_tok3: "írt", t8_tok4: "vár",
    t8_inst: "Kattints a múlt idejű igékre!",
    t9_title: "Birtokjel",
    t9_text: "Azt mutatja, hogy valami valakié (pl. Péteré). Jele: -é.",
    t9_sent: "Ez a toll a ___.", t9_c1: "Petié", t9_c2: "Petit", t9_c3: "Petivel",
    t9_inst: "Kié a toll?",
    t10_title: "Szóelemzés mestere",
    t10_q: "Mi állhat a szó végén a rag után?",
    t10_t1: "semmi", t10_t2: "képző", t10_t3: "jel",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I3_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Szófajok Szigete",
    t1_title: "Főnév",
    t1_text: "Élőlények, tárgyak, gondolati dolgok neve.",
    t1_b1: "Köznév", t1_b2: "Tulajdonnév",
    t1_i1: "fiú", t1_i2: "város", t1_i3: "Kovács", t1_i4: "Pécs",
    t1_inst: "Válogasd szét a főneveket!",
    t2_title: "Melléknév",
    t2_text: "Tulajdonságot, minőséget fejez ki. Kérdése: Milyen?",
    t2_l1: "szép", t2_r1: "virág", t2_l2: "ügyes", t2_r2: "gyerek", t2_l3: "piros", t2_r3: "alma",
    t2_inst: "Párosítsd a melléknevet a főnévvel!",
    t3_title: "Számnév",
    t3_text: "Mennyiséget vagy sorrendet fejez ki.",
    t3_b1: "Határozott", t3_b2: "Határozatlan",
    t3_i1: "egy", t3_i2: "tíz", t3_i3: "sok", t3_i4: "kevés",
    t3_inst: "Csoportosítsd a számneveket!",
    t4_title: "Névmások",
    t4_text: "Névszókat helyettesítő szavak (pl. én, ez, mindenki).",
    t4_tok1: "ő", t4_tok2: "mi", t4_tok3: "az", t4_tok4: "olyan", t4_tok5: "szék",
    t4_inst: "Kattints a névmásokra!",
    t5_title: "Személyes névmás",
    t5_text: "A beszélőre vagy a hallgatóra utal.",
    t5_l1: "Én", t5_r1: "E/1", t5_l2: "Te", t5_r2: "E/2", t5_l3: "Mi", t5_r3: "T/1",
    t5_inst: "Párosítsd a személyeket!",
    t6_title: "Az Ige",
    t6_text: "Cselekvést, történést vagy állapotot fejez ki.",
    t6_q: "Melyik egy IGE?",
    t6_t1: "olvas", t6_t2: "olvasás", t6_t3: "olvasmány",
    t6_inst: "Válaszd az igét!",
    t7_title: "Igenevek: Főnévi igenév",
    t7_text: "Igei és főnévi tulajdonságai is vannak. Végződése: -ni.",
    t7_tok1: "futni", t7_tok2: "enni", t7_tok3: "aludni", t7_tok4: "szalad", t7_tok5: "ház",
    t7_inst: "Kattints a főnévi igenevekre!",
    t8_title: "Melléknévi igenév",
    t8_text: "Folyamatos (-ó/-ő), befejezett (-t/-tt) vagy beálló (-andó/-endő).",
    t8_l1: "olvasó", t8_r1: "folyamatos", t8_l2: "elolvasott", t8_r2: "befejezett", t8_l3: "olvasandó", t8_r3: "beálló",
    t8_inst: "Párosítsd az igenév fajtáját!",
    t9_title: "Határozószó",
    t9_text: "A cselekvés körülményeit (helyét, idejét) fejezi ki (pl. lent, ma, most).",
    t9_sent: "Péter ___ érkezett meg.", t9_c1: "most", t9_c2: "szép", t9_c3: "három",
    t9_inst: "Válaszd a határozószót!",
    t10_title: "Szófajok mestere",
    t10_q: "Melyik szófaj helyettesíthet bármilyen névszót?",
    t10_t1: "névmás", t10_t2: "ige", t10_t3: "számnév",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I4_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Mondattan Szigete",
    t1_title: "Az Állítmány",
    t1_text: "A mondat központi része, megmondja, mit állítunk az alanyról.",
    t1_tok1: "A", t1_tok2: "gyerek", t1_tok3: "almát", t1_tok4: "eszik", t1_tok5: ".",
    t1_inst: "Kattints az ÁLLÍTMÁNYRA!",
    t2_title: "Az Alany",
    t2_text: "Akiről vagy amiről állítunk valamit a mondatban.",
    t2_tok1: "A", t2_tok2: "kismadár", t2_tok3: "szépen", t2_tok4: "fütyül", t2_tok5: ".",
    t2_inst: "Kattints az ALANYRA!",
    t3_title: "Alany-állítmány egyezése",
    t3_text: "Számban és személyben meg kell egyezniük.",
    t3_sent: "Mi tegnap moziba ___.", t3_c1: "mentünk", t3_c2: "mentek", t3_c3: "mentem",
    t3_inst: "Válaszd a helyes alakot!",
    t4_title: "A Tárgy",
    t4_text: "Amire a cselekvés irányul. Ragja: -t. Kérdése: Mit? Kit?",
    t4_tok1: "Péter", t4_tok2: "könyvet", t4_tok3: "olvas", t4_tok4: ".",
    t4_inst: "Kattints a TÁRGYRA!",
    t5_title: "Helyhatározó",
    t5_text: "A cselekvés helyét mutatja meg. Ragjai: -ban, -ben, -ra, -re, -ból, -ből stb.",
    t5_sent: "A cica a ___ alszik.", t5_c1: "kosárban", t5_c2: "reggel", t5_c3: "gyorsan",
    t5_inst: "Melyik a helyhatározó?",
    t6_title: "Időhatározó",
    t6_text: "A cselekvés idejét mutatja meg. Kérdése: Mikor?",
    t6_sent: "___ elmegyünk kirándulni.", t6_c1: "Holnap", t6_c2: "Kertben", t6_c3: "Szépen",
    t6_inst: "Melyik az időhatározó?",
    t7_title: "Módhatározó",
    t7_text: "Azt mutatja, hogyan történik a cselekvés. Ragja gyakran: -an, -en.",
    t7_sent: "A kislány ___ énekel.", t7_c1: "szépen", t7_c2: "tegnap", t7_c3: "erdőben",
    t7_inst: "Válaszd a módhatározót!",
    t8_title: "Tőmondat és bővített mondat",
    t8_text: "A tőmondat csak alanyból és állítmányból áll.",
    t8_b1: "Tőmondat", t8_b2: "Bővített",
    t8_i1: "Péter tanul.", t8_i2: "Esik.", t8_i3: "Anna almát eszik.", t8_i4: "Kint fúj a szél.",
    t8_inst: "Válogasd szét a mondatokat!",
    t9_title: "Szószerkezetek",
    t9_text: "Két szó nyelvtani kapcsolata (pl. alanyos, tárgyas).",
    t9_l1: "kutya szalad", t9_r1: "alanyos", t9_l2: "almát eszik", t9_r2: "tárgyas",
    t9_inst: "Párosítsd a szerkezetet a típussal!",
    t10_title: "Mondattan mestere",
    t10_q: "Melyik kérdésre felel a tárgy?",
    t10_t1: "Mit?", t10_t2: "Ki?", t10_t3: "Mikor?",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I5_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Szövegtan Szigete",
    t1_title: "A szöveg felépítése",
    t1_text: "Mondatokból bekezdések, bekezdésekből fejezetek állnak össze.",
    t1_w1: "szó", t1_w2: "mondat", t1_w3: "bekezdés", t1_w4: "szöveg",
    t1_inst: "Tedd sorrendbe a méret szerint!",
    t2_title: "A cím szerepe",
    t2_text: "A cím megnevezi a témát és felkelti az érdeklődést.",
    t2_sent: "A 'Téli reggel' cím alapján a mű az ___ szól.", t2_c1: "időjárásról", t2_c2: "nyárról", t2_c3: "ételről",
    t2_inst: "Miről szólhat a szöveg?",
    t3_title: "Bekezdés és téma",
    t3_text: "Minden bekezdés egy új gondolati egységet tartalmaz.",
    t3_q: "Miért használunk bekezdéseket?",
    t3_t1: "Tagolásra", t3_t2: "Díszítésre", t3_t3: "Helykitöltésre",
    t3_inst: "Válaszd a jót!",
    t4_title: "Szövegösszetartó elemek",
    t4_text: "Kötőszók, névmások és ismétlések kapcsolják össze a mondatokat.",
    t4_tok1: "és", t4_tok2: "ezért", t4_tok3: "azonban", t4_tok4: "hogy", t4_tok5: "asztal",
    t4_inst: "Kattints a szövegkapcsoló szavakra!",
    t5_title: "Szövegtípusok",
    t5_text: "Leíró, elbeszélő vagy érvelő szövegek.",
    t5_b1: "Leíró (bemutat)", t5_b2: "Elbeszélő (mesél)",
    t5_i1: "A szoba tágas.", t5_i2: "Kék falak.", t5_i3: "Szaladt a fiú.", t5_i4: "Megállt a kapuban.",
    t5_inst: "Csoportosítsd a mondatokat!",
    t6_title: "Szóhasználat",
    t6_text: "A szöveg stílusához illő szavak megválasztása.",
    t6_l1: "baráti levél", t6_r1: "közvetlen", t6_l2: "hivatalos levél", t6_r2: "választékos",
    t6_inst: "Párosítsd a stílust!",
    t7_title: "Szövegértés alapjai",
    t7_text: "A lényeg kiemelése és az összefüggések megértése.",
    t7_sent: "A szöveg elolvasása után készítsünk ___.", t7_c1: "vázlatot", t7_c2: "rajzot", t7_c3: "szünetet",
    t7_inst: "Mi segít a megértésben?",
    t8_title: "Köznyelv és irodalmi nyelv",
    t8_text: "A hétköznapi beszéd és a művészi kifejezésmód közötti különbség.",
    t8_b1: "Köznyelv", t8_b2: "Irodalmi",
    t8_i1: "Szia!", t8_i2: "Mi újság?", t8_i3: "Hajnalpír", t8_i4: "Suhatag",
    t8_inst: "Válogasd szét a szavakat!",
    t9_title: "Vázlatírás",
    t9_text: "A szöveg pontokba szedett terve.",
    t9_w1: "Bevezetés", t9_w2: "Tárgyalás", t9_w3: "Befejezés",
    t9_inst: "Tedd sorrendbe a vázlat részeit!",
    t10_title: "Szövegtan mestere",
    t10_q: "Hogy hívjuk a szöveg fő gondolatát?",
    t10_t1: "téma", t10_t2: "cím", t10_t3: "bekezdés",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I6_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Helyesírás Szigete",
    t1_title: "Magánhangzó-törvények",
    t1_text: "Hangrendi illeszkedés (pl. ház-ban, kert-ben).",
    t1_l1: "ablak", t1_r1: "-on", t1_l2: "tükör", t1_r2: "-ön", t1_l3: "szék", t1_r3: "-en",
    t1_inst: "Párosítsd a ragokat!",
    t2_title: "Mássalhangzó-törvények",
    t2_text: "Zöngésség szerinti hasonulás (pl. vasban [vazban]).",
    t2_sent: "A 'népdal' szóban a 'p' hang ___ ejtjük.", t2_c1: "b-nek", t2_c2: "p-nek", t2_c3: "f-nek",
    t2_inst: "Hogy ejtjük valójában?",
    t3_title: "Írásmódok",
    t3_text: "Kiejtés elve, szóelemzés elve, hagyomány elve, egyszerűsítés elve.",
    t3_b1: "Kiejtés elve", t3_b2: "Hagyomány elve",
    t3_i1: "alma", t3_i2: "fut", t3_i3: "Kossuth", t3_i4: "Széchenyi",
    t3_inst: "Válogasd szét a szavakat!",
    t4_title: "J vagy LY?",
    t4_text: "Gyakorold a j és ly helyes használatát!",
    t4_sent: "A ___ mély az úton.", t4_c1: "lyuk", t4_c2: "juk", t4_c3: "iuk",
    t4_inst: "Melyik a helyes?",
    t5_title: "Tulajdonnevek helyesírása",
    t5_text: "Személynevek, állatnevek, helynevek.",
    t5_tok1: "Kovács", t5_tok2: "Bodri", t5_tok3: "Balaton", t5_tok4: "folyó", t5_tok5: "hegy",
    t5_inst: "Kattints a tulajdonnevekre!",
    t6_title: "Összetett szavak írása",
    t6_text: "Egybeírjuk az összetett szavakat (pl. ablaküveg).",
    t6_sent: "A 'házi' és 'feladat' szavakat ___ írjuk.", t6_c1: "külön", t6_c2: "egybe", t6_c3: "kötőjellel",
    t6_inst: "Hogy írjuk helyesen?",
    t7_title: "Vesszőhasználat",
    t7_text: "Felsorolásnál és tagmondatok között vesszőt teszünk.",
    t7_sent: "Tanultam___ de elfáradtam.", t7_c1: ",", t7_c2: ".", t7_c3: "!",
    t7_inst: "Pótold az írásjelet!",
    t8_title: "Elválasztás",
    t8_text: "A mássalhangzók találkozásakor az elválasztás szabályai szerint tagolunk.",
    t8_sent: "asz-___-ony", t8_c1: "szony", t8_c2: "zony", t8_c3: "ony",
    t8_inst: "Hogy választjuk el az 'asszony' szót?",
    t9_title: "Kettőzött többjegyű betűk",
    t9_text: "Csak az első jegyet kettőzzük meg (pl. asszony, gally).",
    t9_q: "Hogy írjuk helyesen?",
    t9_t1: "asszony", t9_t2: "aszszony", t9_t3: "aszony",
    t9_inst: "Válaszd a jót!",
    t10_title: "Helyesírás mestere",
    t10_q: "Melyik elv alapján írjuk a családneveket (pl. Ady)?",
    t10_t1: "hagyomány", t10_t2: "kiejtés", t10_t3: "szóelemzés",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I7_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Ismétlő Sziget 1",
    t1_title: "Hangrendi válogató",
    t1_b1: "Mély", t1_b2: "Magas",
    t1_i1: "autó", t1_i2: "kutya", t1_i3: "tükör", t1_i4: "szék",
    t1_inst: "Csoportosíts!",
    t2_title: "Tő és toldalék",
    t2_l1: "vár", t2_r1: "szótő", t2_l2: "-nak", t2_r2: "toldalék",
    t2_inst: "Párosíts!",
    t3_title: "Igeidők",
    t3_sent: "Tegnap nagyot ___.", t3_c1: "estem", t3_c2: "esek", t3_c3: "esni fogok",
    t3_inst: "Válaszd a múltat!",
    t4_title: "Szófaj kereső",
    t4_tok1: "én", t4_tok2: "te", t4_tok3: "ő", t4_tok4: "mi", t4_tok5: "ház",
    t4_inst: "Kattints a névmásokra!",
    t5_title: "Állítmány kereső",
    t5_tok1: "A", t5_tok2: "nap", t5_tok3: "fényesen", t5_tok4: "ragyog", t5_tok5: ".",
    t5_inst: "Melyik az állítmány?",
    t6_title: "J vagy LY? 2",
    t6_sent: "A ___ szép kék madár.", t6_c1: "jégmadár", t6_c2: "lyégmadár",
    t6_inst: "Válaszd a jót!",
    t7_title: "Szöveg sorrend",
    t7_w1: "Bevezetés", t7_w2: "Tárgyalás", t7_w3: "Befejezés",
    t7_inst: "Rendezd sorba!",
    t8_title: "Mondatvégi jelek",
    t8_sent: "Hű de jó ez a játék___", t8_c1: "!", t8_c2: "?", t8_c3: ".",
    t8_inst: "Tedd ki a jelet!",
    t9_title: "Tárgy kereső",
    t9_tok1: "Anna", t9_tok2: "almát", t9_tok3: "eszik", t9_tok4: ".",
    t9_inst: "Melyik a tárgy?",
    t10_title: "Kis mester",
    t10_q: "Hány szótő van egy egyszerű szóban?",
    t10_t1: "1", t10_t2: "2", t10_t3: "sok",
    t10_inst: "Válaszolj!",
  }
};

export const MAGYAR_O5_I8_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Ismétlő Sziget 2",
    t1_title: "Mássalhangzó válogató",
    t1_b1: "Zöngés", t1_b2: "Zöngétlen",
    t1_i1: "b", t1_i2: "d", t1_i3: "p", t1_i4: "t",
    t1_inst: "Csoportosíts!",
    t2_title: "Igenév kereső",
    t2_tok1: "tanulni", t2_tok2: "enni", t2_tok3: "főzni", t2_tok4: "szék",
    t2_inst: "Kattints az igenevekre!",
    t3_title: "Határozó párosító",
    t3_l1: "itt", t3_r1: "hely", t3_l2: "ma", t3_r2: "idő",
    t3_inst: "Párosíts!",
    t4_title: "Összetett szó bontó",
    t4_l1: "asztalláb", t4_r1: "asztal + láb", t4_l2: "vashíd", t4_r2: "vas + híd",
    t4_inst: "Bontsd szét a szavakat!",
    t5_title: "Nagybetűs nevek 2",
    t5_tok1: "Petőfi", t5_tok2: "Sándor", t5_tok3: "Magyarország", t5_tok4: "iskola",
    t5_inst: "Kattints a nevekre!",
    t6_title: "Vázlat sorrend",
    t6_w1: "1. Kezdés", t6_w2: "2. Alpont", t6_w3: "3. Zárás",
    t6_inst: "Rendezd sorba!",
    t7_title: "Alany kereső",
    t7_tok1: "A", t7_tok2: "tanár", t7_tok3: "magyaráz", t7_tok4: ".",
    t7_inst: "Melyik az alany?",
    t8_title: "Szín és melléknév",
    t8_sent: "A ___ fű nagyon puha.", t8_c1: "zöld", t8_c2: "szalad", t8_c3: "három",
    t8_inst: "Válaszd a melléknevet!",
    t9_title: "Illeszkedés 2",
    t9_l1: "tükör", t9_r1: "-ben", t9_l2: "doboz", t9_r2: "-ban",
    t9_inst: "Párosíts!",
    t10_title: "Nagy mester",
    t10_q: "Mi a mondat központi része?",
    t10_t1: "Állítmány", t10_t2: "Alany", t10_t3: "Tárgy",
    t10_inst: "Utolsó kérdés!",
  }
};

export const MAGYAR_O5_I9_LABELS: Record<string, Record<string, string>> = {
  hu: {
    explorer_title: "Végső Vizsga Szigete",
    t1_title: "Mindent a hangokról",
    t1_b1: "Magas", t1_b2: "Mély",
    t1_i1: "e", t1_i2: "i", t1_i3: "a", t1_i4: "o",
    t1_inst: "Csoportosíts!",
    t2_title: "Mindent a szavakról",
    t2_l1: "kert", t2_r1: "tő", t2_l2: "-ész", t2_r2: "képző",
    t2_inst: "Párosíts!",
    t3_title: "Mindent a szófajokról",
    t3_q: "Milyen szófaj az 'én'?",
    t3_t1: "névmás", t3_t2: "főnév", t3_t3: "ige",
    t3_inst: "Válaszolj!",
    t4_title: "Mindent a mondatról",
    t4_tok1: "Anna", t4_tok2: "almát", t4_tok3: "eszik", t4_tok4: ".",
    t4_inst: "Kattints az állítmányra!",
    t5_title: "Mindent a szövegről",
    t5_q: "Mi áll a szöveg elején?",
    t5_t1: "Bevezetés", t5_t2: "Befejezés", t5_t3: "Tárgyalás",
    t5_inst: "Válaszd a jót!",
    t6_title: "Helyesírási záróteszt",
    t6_sent: "A ___ magasan repül.", t6_c1: "gólya", t6_c2: "gójya",
    t6_inst: "Válaszd a jót!",
    t7_title: "Igeidők záróteszt",
    t7_sent: "Holnap biztosan ___.", t7_c1: "játszunk", t7_c2: "játszottunk",
    t7_inst: "Válaszd a jelent!",
    t8_title: "Szószerkezetek záróteszt",
    t8_l1: "Péter fut", t8_r1: "alanyos", t8_l2: "vizet iszik", t8_r2: "tárgyas",
    t8_inst: "Párosíts!",
    t9_title: "Mondatfajták záróteszt",
    t9_sent: "Bárcsak sikerülne___", t9_c1: "!", t9_c2: "?", t9_c3: ".",
    t9_inst: "Tedd ki a jelet!",
    t10_title: "Irány a 6. osztály!",
    t10_q: "Gratulálok! Készen állsz a folytatásra?",
    t10_t1: "Igen!", t10_t2: "Még gyakorlok.",
    t10_inst: "Az utolsó gomb!",
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POOLS
// ─────────────────────────────────────────────────────────────────────────────

export const MAGYAR_O5_I1_POOL: PoolTopicDef[] = [
  { difficulty: "easy", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "two-groups", left: { items: ["a", "o"], bg: "#FFF7ED", border: "#C2410C" }, right: { items: ["e", "i"], bg: "#F0FDF4", border: "#15803D" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4", "t1_i5", "t1_i6", "t1_i7"], instruction: "t1_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "medium", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "two-groups", left: { items: ["autó"], bg: "#FFF7ED", border: "#C2410C" }, right: { items: ["tükör"], bg: "#F0FDF4", border: "#15803D" } }, interactive: { type: "physics-bucket", bucket1: "t2_b1", bucket2: "t2_b2", items: ["t2_i1", "t2_i2", "t2_i3", "t2_i4", "t2_i5", "t2_i6"], instruction: "t2_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "easy", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "simple-icon", icon: "🤝", title: "Illeszkedés", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "match-pairs", pairs: [{ left: "t3_l1", right: "t3_r1" }, { left: "t3_l2", right: "t3_r2" }, { left: "t3_l3", right: "t3_r3" }], instruction: "t3_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "easy", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "two-groups", left: { items: ["b", "d"], bg: "#DBEAFE", border: "#2563EB" }, right: { items: ["p", "t"], bg: "#FEE2E2", border: "#EF4444" } }, interactive: { type: "physics-bucket", bucket1: "t4_b1", bucket2: "t4_b2", items: ["t4_i1", "t4_i2", "t4_i3", "t4_i4", "t4_i5", "t4_i6"], instruction: "t4_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "medium", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "simple-icon", icon: "📏", title: "Hossz", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "match-pairs", pairs: [{ left: "t5_l1", right: "t5_r1" }, { left: "t5_l2", right: "t5_r2" }], instruction: "t5_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "easy", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "simple-icon", icon: "🔢", title: "ABC", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t6_w1", "t6_w2", "t6_w3"], correctOrder: [0, 1, 2], instruction: "t6_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "hard", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: "⚡", title: "Hasonulás", bg: "#FEF2F2", color: "#B91C1C" }, interactive: { type: "highlight-text", tokens: ["t7_tok1", "t7_tok2", "t7_tok3", "t7_tok4"], correctIndices: [0, 1, 2], instruction: "t7_inst" }, quiz: { generate: "hasonulas" } },
  { difficulty: "medium", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "simple-icon", icon: "➕", title: "Teljes", bg: "#DCFCE7", color: "#16A34A" }, interactive: { type: "gap-fill", sentence: "t8_sent", choices: ["t8_c1", "t8_c2", "t8_c3"], correctIndex: 0, instruction: "t8_inst" }, quiz: { generate: "hasonulas" } },
  { difficulty: "medium", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "🤝", title: "Összeolvad", bg: "#E0F2FE", color: "#3B82F6" }, interactive: { type: "gap-fill", sentence: "t9_sent", choices: ["t9_c1", "t9_c2", "t9_c3"], correctIndex: 0, instruction: "t9_inst" }, quiz: { generate: "hasonulas" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "hangrendsz" } },
];

export const MAGYAR_O5_I2_POOL: PoolTopicDef[] = [
  { difficulty: "easy", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "two-groups", left: { items: ["ház"], bg: "#F3F4F6", border: "#D1D5DB" }, right: { items: ["-ban"], bg: "#DBEAFE", border: "#3B82F6" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4", "t1_i5"], instruction: "t1_inst" }, quiz: { generate: "to_toldalek" } },
  { difficulty: "medium", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "simple-icon", icon: "➕", title: "Képző", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "match-pairs", pairs: [{ left: "t2_l1", right: "t2_r1" }, { left: "t2_l2", right: "t2_r2" }, { left: "t2_l3", right: "t2_r3" }], instruction: "t2_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "medium", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "simple-icon", icon: "🔖", title: "Jel", bg: "#FEF3C7", color: "#D97706" }, interactive: { type: "highlight-text", tokens: ["t3_tok1", "t3_tok2", "t3_tok3", "t3_tok4"], correctIndices: [0, 1, 2], instruction: "t3_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "medium", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "simple-icon", icon: "📎", title: "Rag", bg: "#F0FDF4", color: "#15803D" }, interactive: { type: "gap-fill", sentence: "t4_sent", choices: ["t4_c1", "t4_c2", "t4_c3"], correctIndex: 0, instruction: "t4_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "hard", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "simple-icon", icon: "🔢", title: "Sorrend", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t5_w1", "t5_w2", "t5_w3", "t5_w4"], correctOrder: [0, 1, 2, 3], instruction: "t5_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "medium", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "two-groups", left: { items: ["ír-ás"], bg: "#FDF4FF", border: "#A21CAF" }, right: { items: ["ír"], bg: "#F3F4F6", border: "#D1D5DB" } }, interactive: { type: "physics-bucket", bucket1: "t6_b1", bucket2: "t6_b2", items: ["t6_i1", "t6_i2", "t6_i3", "t6_i4"], instruction: "t6_inst" }, quiz: { generate: "szoelemzés_melyi" } },
  { difficulty: "easy", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: "👥", title: "Többes", bg: "#E0F2FE", color: "#0284C7" }, interactive: { type: "gap-fill", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3"], correctIndex: 0, instruction: "t7_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "medium", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "simple-icon", icon: "⏳", title: "Múlt", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "highlight-text", tokens: ["t8_tok1", "t8_tok2", "t8_tok3", "t8_tok4"], correctIndices: [0, 1, 2], instruction: "t8_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "medium", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "👤", title: "Kié", bg: "#FEF2F2", color: "#B91C1C" }, interactive: { type: "gap-fill", sentence: "t9_sent", choices: ["t9_c1", "t9_c2", "t9_c3"], correctIndex: 0, instruction: "t9_inst" }, quiz: { generate: "kepzo_jel_rag" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "to_toldalek" } },
];

export const MAGYAR_O5_I3_POOL: PoolTopicDef[] = [
  { difficulty: "easy", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "two-groups", left: { items: ["fiú"], bg: "#F3F4F6", border: "#D1D5DB" }, right: { items: ["Pécs"], bg: "#FEF2F2", border: "#EF4444" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4"], instruction: "t1_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "easy", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "simple-icon", icon: "🌈", title: "Milyen", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "match-pairs", pairs: [{ left: "t2_l1", right: "t2_r1" }, { left: "t2_l2", right: "t2_r2" }, { left: "t2_l3", right: "t2_r3" }], instruction: "t2_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "medium", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "two-groups", left: { items: ["3"], bg: "#E0F2FE", border: "#3B82F6" }, right: { items: ["sok"], bg: "#FEF3C7", border: "#D97706" } }, interactive: { type: "physics-bucket", bucket1: "t3_b1", bucket2: "t3_b2", items: ["t3_i1", "t3_i2", "t3_i3", "t3_i4"], instruction: "t3_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "medium", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "simple-icon", icon: "👤", title: "Névmás", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "highlight-text", tokens: ["t4_tok1", "t4_tok2", "t4_tok3", "t4_tok4", "t4_tok5"], correctIndices: [0, 1, 2, 3], instruction: "t4_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "medium", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "simple-icon", icon: "👥", title: "Személy", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "match-pairs", pairs: [{ left: "t5_l1", right: "t5_r1" }, { left: "t5_l2", right: "t5_r2" }, { left: "t5_l3", right: "t5_r3" }], instruction: "t5_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "easy", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "simple-icon", icon: "🏃", title: "Ige", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "physics-slingshot", question: "t6_q", targets: [{ id: "v1", text: "t6_t1", isCorrect: true }, { id: "n1", text: "t6_t2", isCorrect: false }, { id: "n2", text: "t6_t3", isCorrect: false }], instruction: "t6_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "medium", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: "📜", title: "-ni", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "highlight-text", tokens: ["t7_tok1", "t7_tok2", "t7_tok3", "t7_tok4", "t7_tok5"], correctIndices: [0, 1, 2], instruction: "t7_inst" }, quiz: { generate: "igenev" } },
  { difficulty: "hard", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "simple-icon", icon: "🏷️", title: "Igenév", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "match-pairs", pairs: [{ left: "t8_l1", right: "t8_r1" }, { left: "t8_l2", right: "t8_r2" }, { left: "t8_l3", right: "t8_r3" }], instruction: "t8_inst" }, quiz: { generate: "igenev" } },
  { difficulty: "medium", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "📍", title: "Mikor", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "gap-fill", sentence: "t9_sent", choices: ["t9_c1", "t9_c2", "t9_c3"], correctIndex: 0, instruction: "t9_inst" }, quiz: { generate: "hatarozoSzo" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "hu_parts_of_speech" } },
];

export const MAGYAR_O5_I4_POOL: PoolTopicDef[] = [
  { difficulty: "medium", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "simple-icon", icon: "🎬", title: "Tesz", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "highlight-text", tokens: ["t1_tok1", "t1_tok2", "t1_tok3", "t1_tok4", "t1_tok5"], correctIndices: [3], instruction: "t1_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "medium", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "simple-icon", icon: "👤", title: "Ki", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "highlight-text", tokens: ["t2_tok1", "t2_tok2", "t2_tok3", "t2_tok4", "t2_tok5"], correctIndices: [1], instruction: "t2_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "medium", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "simple-icon", icon: "🤝", title: "Egyez", bg: "#F0FDF4", color: "#15803D" }, interactive: { type: "gap-fill", sentence: "t3_sent", choices: ["t3_c1", "t3_c2", "t3_c3"], correctIndex: 0, instruction: "t3_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "hard", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "simple-icon", icon: "📦", title: "Mit", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "highlight-text", tokens: ["t4_tok1", "t4_tok2", "t4_tok3", "t4_tok4"], correctIndices: [1], instruction: "t4_inst" }, quiz: { generate: "targy_hatarozo" } },
  { difficulty: "medium", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "simple-icon", icon: "📍", title: "Hol", bg: "#FEF3C7", color: "#D97706" }, interactive: { type: "gap-fill", sentence: "t5_sent", choices: ["t5_c1", "t5_c2", "t5_c3"], correctIndex: 0, instruction: "t5_inst" }, quiz: { generate: "targy_hatarozo" } },
  { difficulty: "medium", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "simple-icon", icon: "⏰", title: "Mikor", bg: "#F0F9FF", color: "#0369A1" }, interactive: { type: "gap-fill", sentence: "t6_sent", choices: ["t6_c1", "t6_c2", "t6_c3"], correctIndex: 0, instruction: "t6_inst" }, quiz: { generate: "targy_hatarozo" } },
  { difficulty: "medium", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: "⚙️", title: "Hogyan", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "gap-fill", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3"], correctIndex: 0, instruction: "t7_inst" }, quiz: { generate: "targy_hatarozo" } },
  { difficulty: "medium", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "two-groups", left: { items: ["Péter tanul."], bg: "#F3F4F6", border: "#D1D5DB" }, right: { items: ["Kint fúj."], bg: "#DBEAFE", border: "#3B82F6" } }, interactive: { type: "physics-bucket", bucket1: "t8_b1", bucket2: "t8_b2", items: ["t8_i1", "t8_i2", "t8_i3", "t8_i4"], instruction: "t8_inst" }, quiz: { generate: "hu_sentence_structure" } },
  { difficulty: "medium", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "🔗", title: "Kötés", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "match-pairs", pairs: [{ left: "t9_l1", right: "t9_r1" }, { left: "t9_l2", right: "t9_r2" }], instruction: "t9_inst" }, quiz: { generate: "szoszerkezet" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "alany_allitmany" } },
];

export const MAGYAR_O5_I5_POOL: PoolTopicDef[] = [
  { difficulty: "easy", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "simple-icon", icon: "🔢", title: "Mondat", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t1_w1", "t1_w2", "t1_w3", "t1_w4"], correctOrder: [0, 1, 2, 3], instruction: "t1_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "easy", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "simple-icon", icon: "📖", title: "Cím", bg: "#F0FDF4", color: "#15803D" }, interactive: { type: "gap-fill", sentence: "t2_sent", choices: ["t2_c1", "t2_c2", "t2_c3"], correctIndex: 0, instruction: "t2_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "medium", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "simple-icon", icon: "📑", title: "Bekezdés", bg: "#E0F2FE", color: "#0369A1" }, interactive: { type: "physics-slingshot", question: "t3_q", targets: [{ id: "v1", text: "t3_t1", isCorrect: true }, { id: "n1", text: "t3_t2", isCorrect: false }, { id: "n2", text: "t3_t3", isCorrect: false }], instruction: "t3_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "simple-icon", icon: "🔗", title: "Kötő", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "highlight-text", tokens: ["t4_tok1", "t4_tok2", "t4_tok3", "t4_tok4", "t4_tok5"], correctIndices: [0, 1, 2, 3], instruction: "t4_inst" }, quiz: { generate: "kohezio" } },
  { difficulty: "medium", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "two-groups", left: { items: ["Kék"], bg: "#DBEAFE", border: "#2563EB" }, right: { items: ["Szalad"], bg: "#FEE2E2", border: "#EF4444" } }, interactive: { type: "physics-bucket", bucket1: "t5_b1", bucket2: "t5_b2", items: ["t5_i1", "t5_i2", "t5_i3", "t5_i4"], instruction: "t5_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "simple-icon", icon: "🔍", title: "Miért", bg: "#F3F4F6", color: "#111827" }, interactive: { type: "physics-slingshot", question: "t6_q", targets: [{ id: "v1", text: "t6_t1", isCorrect: true }, { id: "n1", text: "t6_t2", isCorrect: false }, { id: "n2", text: "t6_t3", isCorrect: false }], instruction: "t6_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "medium", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: "📝", title: "Vázlat", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "gap-fill", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3"], correctIndex: 0, instruction: "t7_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "medium", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "two-groups", left: { items: ["Szia!"], bg: "#DCFCE7", border: "#16A34A" }, right: { items: ["Suhatag"], bg: "#FDF4FF", border: "#A21CAF" } }, interactive: { type: "physics-bucket", bucket1: "t8_b1", bucket2: "t8_b2", items: ["t8_i1", "t8_i2", "t8_i3", "t8_i4"], instruction: "t8_inst" }, quiz: { generate: "koznyelv_irodalmi" } },
  { difficulty: "medium", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "🔢", title: "Vázlat", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t9_w1", "t9_w2", "t9_w3"], correctOrder: [0, 1, 2], instruction: "t9_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "szovegtipusok" } },
];

export const MAGYAR_O5_I6_POOL: PoolTopicDef[] = [
  { difficulty: "easy", infoTitle: "t1_title", infoText: "t1_text", svg: { type: "simple-icon", icon: "🤝", title: "Illeszk", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "match-pairs", pairs: [{ left: "t1_l1", right: "t1_r1" }, { left: "t1_l2", right: "t1_r2" }, { left: "t1_l3", right: "t1_r3" }], instruction: "t1_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "medium", infoTitle: "t2_title", infoText: "t2_text", svg: { type: "simple-icon", icon: "🔄", title: "Hasonulás", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "gap-fill", sentence: "t2_sent", choices: ["t2_c1", "t2_c2", "t2_c3"], correctIndex: 0, instruction: "t2_inst" }, quiz: { generate: "hasonulas" } },
  { difficulty: "medium", infoTitle: "t3_title", infoText: "t3_text", svg: { type: "two-groups", left: { items: ["alma"], bg: "#DCFCE7", border: "#16A34A" }, right: { items: ["Ady"], bg: "#FEF2F2", border: "#B91C1C" } }, interactive: { type: "physics-bucket", bucket1: "t3_b1", bucket2: "t3_b2", items: ["t3_i1", "t3_i2", "t3_i3", "t3_i4"], instruction: "t3_inst" }, quiz: { generate: "helyesiras_5" } },
  { difficulty: "medium", infoTitle: "t4_title", infoText: "t4_text", svg: { type: "simple-icon", icon: "❓", title: "J-LY", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "gap-fill", sentence: "t4_sent", choices: ["t4_c1", "t4_c2", "t4_c3"], correctIndex: 0, instruction: "t4_inst" }, quiz: { generate: "hu_spelling" } },
  { difficulty: "medium", infoTitle: "t5_title", infoText: "t5_text", svg: { type: "simple-icon", icon: "🏙️", title: "Nagy", bg: "#FEF2F2", color: "#B91C1C" }, interactive: { type: "highlight-text", tokens: ["t5_tok1", "t5_tok2", "t5_tok3", "t5_tok4", "t5_tok5"], correctIndices: [0, 1, 2], instruction: "t5_inst" }, quiz: { generate: "helyesiras_5" } },
  { difficulty: "medium", infoTitle: "t6_title", infoText: "t6_text", svg: { type: "simple-icon", icon: "🔗", title: "Egybe", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "gap-fill", sentence: "t6_sent", choices: ["t6_c1", "t6_c2", "t6_c3"], correctIndex: 1, instruction: "t6_inst" }, quiz: { generate: "osszetetel_iras" } },
  { difficulty: "easy", infoTitle: "t7_title", infoText: "t7_text", svg: { type: "simple-icon", icon: ",", title: "Vessző", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "gap-fill", sentence: "t7_sent", choices: ["t7_c1", "t7_c2", "t7_c3"], correctIndex: 0, instruction: "t7_inst" }, quiz: { generate: "helyesiras_vesszö" } },
  { difficulty: "medium", infoTitle: "t8_title", infoText: "t8_text", svg: { type: "word-syllables", parts: ["asz", "szony"], color: "#DB2777" }, interactive: { type: "gap-fill", sentence: "t8_sent", choices: ["t8_c1", "t8_c2", "t8_c3"], correctIndex: 0, instruction: "t8_inst" }, quiz: { generate: "helyesiras_5" } },
  { difficulty: "hard", infoTitle: "t9_title", infoText: "t9_text", svg: { type: "simple-icon", icon: "✨", title: "Egysz", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "physics-slingshot", question: "t9_q", targets: [{ id: "v1", text: "t9_t1", isCorrect: true }, { id: "n1", text: "t9_t2", isCorrect: false }, { id: "n2", text: "t9_t3", isCorrect: false }], instruction: "t9_inst" }, quiz: { generate: "helyesiras_5" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "t10_text", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }, { id: "n2", text: "t10_t3", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "helyesiras_5" } },
];

export const MAGYAR_O5_I7_POOL: PoolTopicDef[] = [
  { difficulty: "hard", infoTitle: "t1_title", infoText: "", svg: { type: "two-groups", left: { items: ["a"], bg: "#FFF7ED", border: "#C2410C" }, right: { items: ["e"], bg: "#F0FDF4", border: "#15803D" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4"], instruction: "t1_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "hard", infoTitle: "t2_title", infoText: "", svg: { type: "simple-icon", icon: "🤝", title: "Tő", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "match-pairs", pairs: [{ left: "t2_l1", right: "t2_r1" }, { left: "t2_l2", right: "t2_r2" }], instruction: "t2_inst" }, quiz: { generate: "to_toldalek" } },
  { difficulty: "hard", infoTitle: "t3_title", infoText: "", svg: { type: "simple-icon", icon: "⏳", title: "Idő", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "gap-fill", sentence: "t3_sent", choices: ["t3_c1", "t3_c2", "t3_c3"], correctIndex: 0, instruction: "t3_inst" }, quiz: { generate: "ige_igeidok" } },
  { difficulty: "hard", infoTitle: "t4_title", infoText: "", svg: { type: "simple-icon", icon: "👤", title: "Ki", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "highlight-text", tokens: ["t4_tok1", "t4_tok2", "t4_tok3", "t4_tok4"], correctIndices: [0, 1, 2, 3], instruction: "t4_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "hard", infoTitle: "t5_title", infoText: "", svg: { type: "simple-icon", icon: "🎬", title: "Tesz", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "highlight-text", tokens: ["t5_tok1", "t5_tok2", "t5_tok3", "t5_tok4"], correctIndices: [3], instruction: "t5_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "hard", infoTitle: "t6_title", infoText: "", svg: { type: "simple-icon", icon: "❓", title: "J-LY", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "gap-fill", sentence: "t6_sent", choices: ["t6_c1", "t6_c2"], correctIndex: 0, instruction: "t6_inst" }, quiz: { generate: "hu_spelling" } },
  { difficulty: "hard", infoTitle: "t7_title", infoText: "", svg: { type: "simple-icon", icon: "🔢", title: "Váz", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t7_w1", "t7_w2", "t7_w3"], correctOrder: [0, 1, 2], instruction: "t7_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t8_title", infoText: "", svg: { type: "simple-icon", icon: "!", title: "Jel", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "gap-fill", sentence: "t8_sent", choices: ["t8_c1", "t8_c2", "t8_c3"], correctIndex: 0, instruction: "t8_inst" }, quiz: { generate: "mondatfajtak" } },
  { difficulty: "hard", infoTitle: "t9_title", infoText: "", svg: { type: "simple-icon", icon: "📦", title: "Mit", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "highlight-text", tokens: ["t9_tok1", "t9_tok2", "t9_tok3"], correctIndices: [1], instruction: "t9_inst" }, quiz: { generate: "targy_hatarozo" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "", svg: { type: "simple-icon", icon: "🎓", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "to_toldalek" } },
];

export const MAGYAR_O5_I8_POOL: PoolTopicDef[] = [
  { difficulty: "hard", infoTitle: "t1_title", infoText: "", svg: { type: "two-groups", left: { items: ["b"], bg: "#DBEAFE", border: "#2563EB" }, right: { items: ["p"], bg: "#FEE2E2", border: "#EF4444" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4"], instruction: "t1_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "hard", infoTitle: "t2_title", infoText: "", svg: { type: "simple-icon", icon: "📜", title: "Igenév", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "highlight-text", tokens: ["t2_tok1", "t2_tok2", "t2_tok3"], correctIndices: [0, 1, 2], instruction: "t2_inst" }, quiz: { generate: "igenev" } },
  { difficulty: "hard", infoTitle: "t3_title", infoText: "", svg: { type: "simple-icon", icon: "📍", title: "Hat", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "match-pairs", pairs: [{ left: "t3_l1", right: "t3_r1" }, { left: "t3_l2", right: "t3_r2" }], instruction: "t3_inst" }, quiz: { generate: "hatarozoSzo" } },
  { difficulty: "hard", infoTitle: "t4_title", infoText: "", svg: { type: "simple-icon", icon: "🔗", title: "Bont", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "match-pairs", pairs: [{ left: "t4_l1", right: "t4_r1" }, { left: "t4_l2", right: "t4_r2" }], instruction: "t4_inst" }, quiz: { generate: "osszetetel_iras" } },
  { difficulty: "hard", infoTitle: "t5_title", infoText: "", svg: { type: "simple-icon", icon: "🔠", title: "Nagy", bg: "#FEF2F2", color: "#B91C1C" }, interactive: { type: "highlight-text", tokens: ["t5_tok1", "t5_tok2", "t5_tok3"], correctIndices: [0, 1, 2], instruction: "t5_inst" }, quiz: { generate: "helyesiras_5" } },
  { difficulty: "hard", infoTitle: "t6_title", infoText: "", svg: { type: "simple-icon", icon: "🔢", title: "Váz", bg: "#F3F4F6", color: "#1F2937" }, interactive: { type: "physics-stacker", words: ["t6_w1", "t6_w2", "t6_w3"], correctOrder: [0, 1, 2], instruction: "t6_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t7_title", infoText: "", svg: { type: "simple-icon", icon: "👤", title: "Ki", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "highlight-text", tokens: ["t7_tok1", "t7_tok2", "t7_tok3"], correctIndices: [1], instruction: "t7_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "hard", infoTitle: "t8_title", infoText: "", svg: { type: "simple-icon", icon: "🎨", title: "Mell", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "gap-fill", sentence: "t8_sent", choices: ["t8_c1", "t8_c2"], correctIndex: 0, instruction: "t8_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "hard", infoTitle: "t9_title", infoText: "", svg: { type: "simple-icon", icon: "🤝", title: "Ill", bg: "#DCFCE7", color: "#16A34A" }, interactive: { type: "match-pairs", pairs: [{ left: "t9_l1", right: "t9_r1" }, { left: "t9_l2", right: "t9_r2" }], instruction: "t9_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "", svg: { type: "simple-icon", icon: "🏆", title: "Mester", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "alany_allitmany" } },
];

export const MAGYAR_O5_I9_POOL: PoolTopicDef[] = [
  { difficulty: "hard", infoTitle: "t1_title", infoText: "", svg: { type: "two-groups", left: { items: ["e"], bg: "#F0FDF4", border: "#15803D" }, right: { items: ["a"], bg: "#FFF7ED", border: "#C2410C" } }, interactive: { type: "physics-bucket", bucket1: "t1_b1", bucket2: "t1_b2", items: ["t1_i1", "t1_i2", "t1_i3", "t1_i4"], instruction: "t1_inst" }, quiz: { generate: "hangrendsz" } },
  { difficulty: "hard", infoTitle: "t2_title", infoText: "", svg: { type: "simple-icon", icon: "✂️", title: "Bont", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "match-pairs", pairs: [{ left: "t2_l1", right: "t2_r1" }, { left: "t2_l2", right: "t2_r2" }], instruction: "t2_inst" }, quiz: { generate: "to_toldalek" } },
  { difficulty: "hard", infoTitle: "t3_title", infoText: "", svg: { type: "simple-icon", icon: "👤", title: "Én", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t3_q", targets: [{ id: "v1", text: "t3_t1", isCorrect: true }, { id: "n1", text: "t3_t2", isCorrect: false }], instruction: "t3_inst" }, quiz: { generate: "hu_parts_of_speech" } },
  { difficulty: "hard", infoTitle: "t4_title", infoText: "", svg: { type: "simple-icon", icon: "🎬", title: "Tesz", bg: "#FEE2E2", color: "#DC2626" }, interactive: { type: "highlight-text", tokens: ["t4_tok1", "t4_tok2", "t4_tok3"], correctIndices: [2], instruction: "t4_inst" }, quiz: { generate: "alany_allitmany" } },
  { difficulty: "hard", infoTitle: "t5_title", infoText: "", svg: { type: "simple-icon", icon: "🏗️", title: "Szerk", bg: "#E0F2FE", color: "#0284C7" }, interactive: { type: "physics-slingshot", question: "t5_q", targets: [{ id: "v1", text: "t5_t1", isCorrect: true }, { id: "n1", text: "t5_t2", isCorrect: false }], instruction: "t5_inst" }, quiz: { generate: "szovegtipusok" } },
  { difficulty: "hard", infoTitle: "t6_title", infoText: "", svg: { type: "simple-icon", icon: "❓", title: "J-LY", bg: "#DBEAFE", color: "#2563EB" }, interactive: { type: "gap-fill", sentence: "t6_sent", choices: ["t6_c1", "t6_c2"], correctIndex: 0, instruction: "t6_inst" }, quiz: { generate: "hu_spelling" } },
  { difficulty: "hard", infoTitle: "t7_title", infoText: "", svg: { type: "simple-icon", icon: "🕒", title: "Idő", bg: "#F3F4F6", color: "#374151" }, interactive: { type: "gap-fill", sentence: "t7_sent", choices: ["t7_c1", "t7_c2"], correctIndex: 0, instruction: "t7_inst" }, quiz: { generate: "ige_igeidok" } },
  { difficulty: "hard", infoTitle: "t8_title", infoText: "", svg: { type: "simple-icon", icon: "🤝", title: "Szerk", bg: "#F0F9FF", color: "#0369A1" }, interactive: { type: "match-pairs", pairs: [{ left: "t8_l1", right: "t8_r1" }, { left: "t8_l2", right: "t8_r2" }], instruction: "t8_inst" }, quiz: { generate: "szoszerkezet" } },
  { difficulty: "hard", infoTitle: "t9_title", infoText: "", svg: { type: "simple-icon", icon: "🙏", title: "Bár", bg: "#FDF4FF", color: "#A21CAF" }, interactive: { type: "gap-fill", sentence: "t9_sent", choices: ["t9_c1", "t9_c2"], correctIndex: 0, instruction: "t9_inst" }, quiz: { generate: "mondatfajtak" } },
  { difficulty: "hard", infoTitle: "t10_title", infoText: "", svg: { type: "simple-icon", icon: "🎓", title: "Vége", bg: "#EDE9FE", color: "#7C3AED" }, interactive: { type: "physics-slingshot", question: "t10_q", targets: [{ id: "v1", text: "t10_t1", isCorrect: true }, { id: "n1", text: "t10_t2", isCorrect: false }], instruction: "t10_inst" }, quiz: { generate: "szovegtipusok" } },
];
