import type { PoolTopicDef } from "./types";

export const PHYSIK_K5_I1_LABELS: Record<string, Record<string, string>> = {
  de: {
    explorer_title: "Kräfte-Basislager",
    t1_title: "Drücken oder Ziehen",
    t1_text: "Eine Kraft ist oft ein Drücken oder Ziehen. Damit kannst du Dinge in Bewegung bringen oder stoppen.",
    t1_inst: "Sortiere die Beispiele in die richtige Gruppe.",
    t1_h1: "Ein Einkaufswagen wird meist geschoben.",
    t1_h2: "An einer Schublade ziehst du meistens.",
    t1_b1: "Drücken",
    t1_b2: "Ziehen",
    t1_i1: "Einkaufswagen schieben",
    t1_i2: "Schublade öffnen",
    t1_i3: "Tür zudrücken",
    t1_i4: "Schlitten ziehen",

    t2_title: "Was macht Reibung?",
    t2_text: "Reibung bremst Bewegungen. Auf rauen Flächen ist sie größer, auf glatten kleiner.",
    t2_inst: "Verbinde die Oberfläche mit ihrer Reibung.",
    t2_h1: "Sandpapier ist rau.",
    t2_h2: "Eis ist glatt und rutschig.",
    t2_l1: "Sandpapier",
    t2_r1: "viel Reibung",
    t2_l2: "Eis",
    t2_r2: "wenig Reibung",
    t2_l3: "Gummi",
    t2_r3: "starke Haftung",
    t2_l4: "Öl",
    t2_r4: "gleitet leicht",

    t3_title: "Kräfte ordnen",
    t3_text: "Manche Kräfte entstehen bei Berührung, andere wirken aus der Entfernung. Für diese Insel brauchst du vor allem Druck, Zug und Reibung sicher.",
    t3_inst: "Bringe die Kraftbeispiele in die Lernreihenfolge.",
    t3_h1: "Starte mit den einfachsten Alltagskräften.",
    t3_h2: "Drücken und Ziehen kommen vor Reibung als Vergleichskraft.",
    t3_w1: "Drücken",
    t3_w2: "Ziehen",
    t3_w3: "Reibung",

    t4_title: "Reibung erkennen",
    t4_text: "Nicht jede Bewegung ist gleich leicht. Reibung hilft beim Bremsen, kann aber auch das Rutschen schwerer machen.",
    t4_inst: "Triff alle Ziele, bei denen viel Reibung hilft.",
    t4_h1: "Bremsen und Grip brauchen Reibung.",
    t4_h2: "Rutschen auf Eis braucht eher wenig Reibung.",
    t4_q: "Wo ist viel Reibung nützlich?",
    t4_t1: "Fahrradbremse",
    t4_t2: "Schuhsohle auf Asphalt",
    t4_t3: "Schlitten auf Eis",
    t4_t4: "geöltes Lager",

    t5_title: "Push oder Pull?",
    t5_text: "Viele Bewegungen kannst du als Push oder Pull beschreiben. Wenn du das sicher erkennst, verstehst du die Aufgaben aus m2 und m3 schneller.",
    t5_inst: "Wähle die passende Aussage.",
    t5_h1: "Schieben ist meist von dir weg.",
    t5_h2: "Ziehen ist meist zu dir hin.",
    t5_sent: "Einen Bollerwagen bewegst du meistens durch...",
    t5_c1: "Ziehen",
    t5_c2: "Schweben",
    t5_c3: "Schmelzen",
    t5_c4: "Leuchten",
  },
  en: {
    explorer_title: "Force Base Camp",
    t1_title: "Push or Pull",
    t1_text: "A force is often a push or a pull. It can start movement or stop it.",
    t1_inst: "Sort the examples into the correct group.",
    t1_h1: "A shopping cart is usually pushed.",
    t1_h2: "A drawer is usually pulled open.",
    t1_b1: "Push",
    t1_b2: "Pull",
    t1_i1: "push a shopping cart",
    t1_i2: "open a drawer",
    t1_i3: "push a door shut",
    t1_i4: "pull a sled",

    t2_title: "What Does Friction Do?",
    t2_text: "Friction slows motion down. Rough surfaces create more friction, smooth ones less.",
    t2_inst: "Match the surface to its friction.",
    t2_h1: "Sandpaper is rough.",
    t2_h2: "Ice is smooth and slippery.",
    t2_l1: "sandpaper",
    t2_r1: "high friction",
    t2_l2: "ice",
    t2_r2: "low friction",
    t2_l3: "rubber",
    t2_r3: "strong grip",
    t2_l4: "oil",
    t2_r4: "slides easily",

    t3_title: "Order the Forces",
    t3_text: "Some forces need contact, others work at a distance. For this island, push, pull, and friction are the key ideas.",
    t3_inst: "Put the force examples into learning order.",
    t3_h1: "Start with the simplest daily forces.",
    t3_h2: "Push and pull come before friction as a comparison force.",
    t3_w1: "push",
    t3_w2: "pull",
    t3_w3: "friction",

    t4_title: "Spot Friction",
    t4_text: "Not every movement should be easy. Friction helps with braking and grip, but it can also make sliding harder.",
    t4_inst: "Hit all targets where strong friction helps.",
    t4_h1: "Brakes and grip need friction.",
    t4_h2: "Sliding on ice needs less friction.",
    t4_q: "Where is high friction useful?",
    t4_t1: "bike brake",
    t4_t2: "shoe sole on asphalt",
    t4_t3: "sled on ice",
    t4_t4: "oiled bearing",

    t5_title: "Push or Pull?",
    t5_text: "Many movements can be described as push or pull. If you know this well, m2 and m3 will feel much clearer.",
    t5_inst: "Choose the correct statement.",
    t5_h1: "Pushing is usually away from you.",
    t5_h2: "Pulling is usually toward you.",
    t5_sent: "You usually move a wagon by...",
    t5_c1: "pulling",
    t5_c2: "floating",
    t5_c3: "melting",
    t5_c4: "shining",
  },
  hu: {
    explorer_title: "Erő Alaptábor",
    t1_title: "Nyomás vagy húzás",
    t1_text: "Az erő sokszor nyomás vagy húzás. Ettől egy tárgy elindulhat vagy megállhat.",
    t1_inst: "Rendezd a példákat a megfelelő csoportba.",
    t1_h1: "A bevásárlókocsit általában tolod.",
    t1_h2: "A fiókot általában húzod.",
    t1_b1: "Nyomás",
    t1_b2: "Húzás",
    t1_i1: "bevásárlókocsi tolása",
    t1_i2: "fiók kihúzása",
    t1_i3: "ajtó betolása",
    t1_i4: "szán húzása",

    t2_title: "Mit csinál a súrlódás?",
    t2_text: "A súrlódás lassítja a mozgást. A durva felületeken nagyobb, a simákon kisebb.",
    t2_inst: "Párosítsd a felületet a súrlódásával.",
    t2_h1: "A csiszolópapír durva.",
    t2_h2: "A jég sima és csúszós.",
    t2_l1: "csiszolópapír",
    t2_r1: "nagy súrlódás",
    t2_l2: "jég",
    t2_r2: "kis súrlódás",
    t2_l3: "gumi",
    t2_r3: "erős tapadás",
    t2_l4: "olaj",
    t2_r4: "könnyen csúszik",

    t3_title: "Erők sorrendje",
    t3_text: "Vannak érintkezési és távolhatású erők. Ezen a szigeten a nyomás, húzás és súrlódás a legfontosabb.",
    t3_inst: "Tedd tanulási sorrendbe az erőpéldákat.",
    t3_h1: "Kezdd a legegyszerűbb hétköznapi erőkkel.",
    t3_h2: "A nyomás és a húzás megelőzi a súrlódást.",
    t3_w1: "nyomás",
    t3_w2: "húzás",
    t3_w3: "súrlódás",

    t4_title: "Súrlódás felismerése",
    t4_text: "Nem minden mozgás legyen könnyű. A súrlódás segít a fékezésben és a tapadásban is.",
    t4_inst: "Találd el azokat a célokat, ahol a nagy súrlódás segít.",
    t4_h1: "A fék és a tapadás súrlódást igényel.",
    t4_h2: "A jégen csúszás inkább kis súrlódást jelent.",
    t4_q: "Hol hasznos a nagy súrlódás?",
    t4_t1: "biciklifék",
    t4_t2: "cipőtalp aszfalton",
    t4_t3: "szán a jégen",
    t4_t4: "olajozott csapágy",

    t5_title: "Tolod vagy húzod?",
    t5_text: "Sok mozgást le lehet írni nyomásként vagy húzásként. Ha ezt biztosan felismered, az m2 és m3 is könnyebb lesz.",
    t5_inst: "Válaszd ki a helyes állítást.",
    t5_h1: "A tolás általában tőled elfelé megy.",
    t5_h2: "A húzás általában feléd jön.",
    t5_sent: "Egy kiskocsit általában így mozgatsz:",
    t5_c1: "húzással",
    t5_c2: "lebegéssel",
    t5_c3: "olvadással",
    t5_c4: "világítással",
  },
  ro: {
    explorer_title: "Tabăra Forțelor",
    t1_title: "Împingere sau tragere",
    t1_text: "O forță este adesea o împingere sau o tragere. Ea poate porni mișcarea sau o poate opri.",
    t1_inst: "Sortează exemplele în grupa corectă.",
    t1_h1: "Căruciorul de cumpărături este de obicei împins.",
    t1_h2: "Un sertar este de obicei tras.",
    t1_b1: "Împingere",
    t1_b2: "Tragere",
    t1_i1: "împingi un cărucior",
    t1_i2: "deschizi un sertar",
    t1_i3: "împingi o ușă",
    t1_i4: "tragi o sanie",

    t2_title: "Ce face frecarea?",
    t2_text: "Frecarea încetinește mișcarea. Pe suprafețe aspre este mai mare, pe cele netede mai mică.",
    t2_inst: "Potrivește suprafața cu frecarea ei.",
    t2_h1: "Hârtia abrazivă este aspră.",
    t2_h2: "Gheața este netedă și alunecoasă.",
    t2_l1: "hârtie abrazivă",
    t2_r1: "frecare mare",
    t2_l2: "gheață",
    t2_r2: "frecare mică",
    t2_l3: "cauciuc",
    t2_r3: "aderență puternică",
    t2_l4: "ulei",
    t2_r4: "alunecă ușor",

    t3_title: "Ordinea forțelor",
    t3_text: "Unele forțe apar prin contact, altele acționează de la distanță. Pe această insulă contează mai ales împingerea, tragerea și frecarea.",
    t3_inst: "Pune exemplele de forțe în ordinea învățării.",
    t3_h1: "Începe cu forțele simple din viața de zi cu zi.",
    t3_h2: "Împingerea și tragerea vin înaintea frecării.",
    t3_w1: "împingere",
    t3_w2: "tragere",
    t3_w3: "frecare",

    t4_title: "Recunoaște frecarea",
    t4_text: "Nu orice mișcare trebuie să fie ușoară. Frecarea ajută la frânare și la aderență.",
    t4_inst: "Lovește toate țintele unde frecarea mare ajută.",
    t4_h1: "Frânele și aderența au nevoie de frecare.",
    t4_h2: "Alunecarea pe gheață înseamnă mai puțină frecare.",
    t4_q: "Unde este utilă frecarea mare?",
    t4_t1: "frână de bicicletă",
    t4_t2: "talpă pe asfalt",
    t4_t3: "sanie pe gheață",
    t4_t4: "rulment uns",

    t5_title: "Împingi sau tragi?",
    t5_text: "Multe mișcări pot fi descrise ca împingere sau tragere. Dacă stăpânești asta, m2 și m3 vor fi mai clare.",
    t5_inst: "Alege afirmația corectă.",
    t5_h1: "Împingerea merge de obicei departe de tine.",
    t5_h2: "Tragerea vine de obicei spre tine.",
    t5_sent: "De obicei miști un cărucior prin...",
    t5_c1: "tragere",
    t5_c2: "plutire",
    t5_c3: "topire",
    t5_c4: "strălucire",
  },
};

export const PHYSIK_K5_I1_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "↔️", title: "Push / Pull", bg: "#EFF6FF", color: "#2563EB" },
    interactive: {
      type: "physics-bucket",
      buckets: [{ id: "push", label: "t1_b1" }, { id: "pull", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "push" },
        { text: "t1_i2", bucketId: "pull" },
        { text: "t1_i3", bucketId: "push" },
        { text: "t1_i4", bucketId: "pull" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "push_pull_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🛝", title: "Friction", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "friction_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🧭", title: "Force Order", bg: "#ECFDF5", color: "#059669" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "push_pull_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🛞", title: "Grip", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: false },
        { id: "4", text: "t4_t4", isCorrect: false },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "friction_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🚚", title: "Motion", bg: "#FEE2E2", color: "#DC2626" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "push_pull_mcq" },
  },
];

const PHYSIK_K5_I2_BASE = {
  explorer_title: "Gravity Camp",
  t1_title: "Fall or Orbit",
  t1_text: "Gravity pulls objects toward a planet. Some objects fall back, others keep orbiting.",
  t1_inst: "Sort the examples.",
  t1_h1: "Falling things go back down.",
  t1_h2: "Orbiting things keep moving around.",
  t1_b1: "falls back",
  t1_b2: "keeps orbiting",
  t1_i1: "apple",
  t1_i2: "stone",
  t1_i3: "moon",
  t1_i4: "satellite",

  t2_title: "Mass and Weight",
  t2_text: "Mass stays the same. Weight depends on gravity and is measured in newtons.",
  t2_inst: "Match the term to the unit or tool.",
  t2_h1: "Mass uses kilograms.",
  t2_h2: "Weight uses newtons.",
  t2_l1: "mass",
  t2_r1: "kilogram",
  t2_l2: "weight",
  t2_r2: "newton",
  t2_l3: "mass meter",
  t2_r3: "scale",
  t2_l4: "gravity",
  t2_r4: "pull",

  t3_title: "Gravity Strength",
  t3_text: "Gravity is strongest near a planet and weaker farther away.",
  t3_inst: "Put the places in order from strong to weak gravity.",
  t3_h1: "Start where gravity feels strongest.",
  t3_h2: "Deep space is the weakest.",
  t3_w1: "Earth",
  t3_w2: "Moon",
  t3_w3: "deep space",

  t4_title: "Gravity Acts",
  t4_text: "Gravity works everywhere around us, even in space.",
  t4_inst: "Hit all targets where gravity is acting.",
  t4_h1: "All planets and moons have gravity.",
  t4_h2: "Objects can still fall in space when they are near a planet.",
  t4_q: "Where does gravity act?",
  t4_t1: "Earth",
  t4_t2: "Moon",
  t4_t3: "apple",
  t4_t4: "satellite",

  t5_title: "Air Resistance",
  t5_text: "Air resistance slows moving objects down. Bigger surfaces usually meet more air resistance.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "A parachute creates lots of air resistance.",
  t5_h2: "A small ball moves through air more easily.",
  t5_sent: "Air resistance makes fast things ___.",
  t5_c1: "slower",
  t5_c2: "heavier",
  t5_c3: "brighter",
  t5_c4: "warmer",
} as const;

export const PHYSIK_K5_I2_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I2_BASE },
  de: { ...PHYSIK_K5_I2_BASE, explorer_title: "Gravitation" },
  hu: { ...PHYSIK_K5_I2_BASE, explorer_title: "Gravitáció" },
  ro: { ...PHYSIK_K5_I2_BASE, explorer_title: "Gravitație" },
};

export const PHYSIK_K5_I2_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🌍", title: "Orbit", bg: "#E0F2FE", color: "#0284C7" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "down", label: "t1_b1" }, { id: "orbit", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "down" },
        { text: "t1_i2", bucketId: "down" },
        { text: "t1_i3", bucketId: "orbit" },
        { text: "t1_i4", bucketId: "orbit" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "gravity_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "⚖️", title: "Mass vs Weight", bg: "#FEF9C3", color: "#CA8A04" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "weight_mass_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🛰️", title: "Gravity Strength", bg: "#ECFCCB", color: "#65A30D" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "gravity_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🪐", title: "Gravity Everywhere", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: true },
        { id: "4", text: "t4_t4", isCorrect: true },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "gravity_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🪂", title: "Air Resistance", bg: "#F0FDFA", color: "#0F766E" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "air_resistance_mcq" },
  },
];

const PHYSIK_K5_I3_BASE = {
  explorer_title: "Force Meter",
  t1_title: "What Measures Force?",
  t1_text: "A force meter shows how strong a push or pull is.",
  t1_inst: "Sort the things into tool or unit.",
  t1_h1: "A dynamometer is a tool.",
  t1_h2: "Newton is a unit.",
  t1_b1: "tool",
  t1_b2: "unit",
  t1_i1: "dynamometer",
  t1_i2: "newton",
  t1_i3: "scale",
  t1_i4: "N",

  t2_title: "Force Words",
  t2_text: "Force has a unit and a measuring tool.",
  t2_inst: "Match the force word to its partner.",
  t2_h1: "Unit and tool go together.",
  t2_h2: "Force is measured, not guessed.",
  t2_l1: "force",
  t2_r1: "newton",
  t2_l2: "measure",
  t2_r2: "dynamometer",
  t2_l3: "symbol",
  t2_r3: "N",
  t2_l4: "tool",
  t2_r4: "meter",

  t3_title: "Force Formula",
  t3_text: "The force formula connects mass, acceleration and force.",
  t3_inst: "Fill in the missing symbol.",
  t3_h1: "F = m × a",
  t3_h2: "Acceleration is the missing part.",
  t3_sent: "F = m × ___.",
  t3_c1: "a",
  t3_c2: "v",
  t3_c3: "t",
  t3_c4: "s",

  t4_title: "One Newton",
  t4_text: "One newton is a small force you can measure.",
  t4_inst: "Put the steps in order.",
  t4_h1: "First you measure.",
  t4_h2: "Then you read the number.",
  t4_w1: "dynamometer",
  t4_w2: "force",
  t4_w3: "newton",

  t5_title: "Choose the Tool",
  t5_text: "A force meter is the right tool for force measurement.",
  t5_inst: "Shoot the correct tool.",
  t5_h1: "Only one tool measures force directly.",
  t5_h2: "A ruler does not measure force.",
  t5_q: "Which tool measures force?",
  t5_t1: "dynamometer",
  t5_t2: "ruler",
  t5_t3: "thermometer",
  t5_t4: "stopwatch",
} as const;

export const PHYSIK_K5_I3_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I3_BASE },
  de: { ...PHYSIK_K5_I3_BASE, explorer_title: "Kraftmesser" },
  hu: { ...PHYSIK_K5_I3_BASE, explorer_title: "Erőmérő" },
  ro: { ...PHYSIK_K5_I3_BASE, explorer_title: "Măsurarea forței" },
};

export const PHYSIK_K5_I3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "📏", title: "Meter", bg: "#EEF2FF", color: "#4F46E5" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "tool", label: "t1_b1" }, { id: "unit", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "tool" },
        { text: "t1_i2", bucketId: "unit" },
        { text: "t1_i3", bucketId: "tool" },
        { text: "t1_i4", bucketId: "unit" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "force_measurement_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "N", title: "Symbols", bg: "#F0FDF4", color: "#16A34A" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "force_measurement_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🧮", title: "Formula", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "gap-fill",
      sentence: "t3_sent",
      choices: ["t3_c1", "t3_c2", "t3_c3", "t3_c4"],
      correctIndex: 0,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "force_measurement_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "⚙️", title: "Newton", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-stacker",
      words: ["t4_w1", "t4_w2", "t4_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "force_measurement_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🧰", title: "Tool check", bg: "#FEF2F2", color: "#DC2626" },
    interactive: {
      type: "physics-slingshot",
      question: "t5_q",
      targets: [
        { id: "1", text: "t5_t1", isCorrect: true },
        { id: "2", text: "t5_t2", isCorrect: false },
        { id: "3", text: "t5_t3", isCorrect: false },
        { id: "4", text: "t5_t4", isCorrect: false },
      ],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "force_measurement_mcq" },
  },
];

const PHYSIK_K5_I4_BASE = {
  explorer_title: "Energy Camp",
  t1_title: "Energy Forms",
  t1_text: "Energy can be motion, heat, light, sound, or stored energy.",
  t1_inst: "Sort the examples into moving or stored energy.",
  t1_h1: "Moving things have kinetic energy.",
  t1_h2: "Stored things keep energy inside.",
  t1_b1: "moving energy",
  t1_b2: "stored energy",
  t1_i1: "rolling ball",
  t1_i2: "running child",
  t1_i3: "battery",
  t1_i4: "raised book",

  t2_title: "Kinetic Energy",
  t2_text: "Kinetic energy belongs to moving objects.",
  t2_inst: "Match the movement to its energy idea.",
  t2_h1: "More movement means more kinetic energy.",
  t2_h2: "A moving car has kinetic energy.",
  t2_l1: "movement",
  t2_r1: "kinetic energy",
  t2_l2: "speed",
  t2_r2: "more energy",
  t2_l3: "car",
  t2_r3: "moves",
  t2_l4: "ball",
  t2_r4: "flies",

  t3_title: "Potential Energy",
  t3_text: "Potential energy is stored because of position or condition.",
  t3_inst: "Put the places from low to high potential energy.",
  t3_h1: "Higher places store more energy.",
  t3_h2: "A shelf is higher than the floor.",
  t3_w1: "floor",
  t3_w2: "table",
  t3_w3: "shelf",

  t4_title: "Energy Conversion",
  t4_text: "Energy can change from one form to another.",
  t4_inst: "Shoot the examples of energy conversion.",
  t4_h1: "A lamp changes electric energy to light.",
  t4_h2: "A toaster changes electric energy to heat.",
  t4_q: "Which examples show conversion?",
  t4_t1: "lamp lights up",
  t4_t2: "toaster heats",
  t4_t3: "book stays still",
  t4_t4: "bicycle moves",

  t5_title: "Energy Review",
  t5_text: "Energy can change form, but it does not disappear.",
  t5_inst: "Fill in the sentence.",
  t5_h1: "Energy is conserved.",
  t5_h2: "It changes form, not value.",
  t5_sent: "Energy can change from one form to another.",
  t5_c1: "forms",
  t5_c2: "forces",
  t5_c3: "shapes",
  t5_c4: "colors",
} as const;

export const PHYSIK_K5_I4_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I4_BASE },
  de: { ...PHYSIK_K5_I4_BASE, explorer_title: "Energie" },
  hu: { ...PHYSIK_K5_I4_BASE, explorer_title: "Energia" },
  ro: { ...PHYSIK_K5_I4_BASE, explorer_title: "Energie" },
};

export const PHYSIK_K5_I4_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "⚡", title: "Forms", bg: "#EEF2FF", color: "#4F46E5" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "move", label: "t1_b1" }, { id: "store", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "move" },
        { text: "t1_i2", bucketId: "move" },
        { text: "t1_i3", bucketId: "store" },
        { text: "t1_i4", bucketId: "store" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "energy_forms_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🏃", title: "Kinetic", bg: "#F0FDF4", color: "#16A34A" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "kinetic_energy_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "⬆️", title: "Potential", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "potential_energy_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🔄", title: "Conversion", bg: "#E0F2FE", color: "#0284C7" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: false },
        { id: "4", text: "t4_t4", isCorrect: true },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "energy_conversion_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "♻️", title: "Conservation", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "energy_conservation_mcq" },
  },
];

const PHYSIK_K5_I5_BASE = {
  explorer_title: "Energy Flow",
  t1_title: "From One Form to Another",
  t1_text: "Energy can travel and change form in devices and living things.",
  t1_inst: "Sort the examples into conversion and no conversion.",
  t1_h1: "A lamp changes energy.",
  t1_h2: "A stone sitting still does not.",
  t1_b1: "conversion",
  t1_b2: "no conversion",
  t1_i1: "lamp",
  t1_i2: "toaster",
  t1_i3: "stone",
  t1_i4: "bicycle",

  t2_title: "Energy Partners",
  t2_text: "Different things store different forms of energy.",
  t2_inst: "Match the source with the energy form.",
  t2_h1: "Food stores chemical energy.",
  t2_h2: "A battery stores electrical energy.",
  t2_l1: "sunlight",
  t2_r1: "light energy",
  t2_l2: "food",
  t2_r2: "chemical energy",
  t2_l3: "battery",
  t2_r3: "electric energy",
  t2_l4: "muscle",
  t2_r4: "movement",

  t3_title: "Energy Chain",
  t3_text: "Energy often moves from a source into a living thing and then into action.",
  t3_inst: "Put the chain in order.",
  t3_h1: "Sunlight starts the chain.",
  t3_h2: "Food becomes body energy.",
  t3_w1: "sun",
  t3_w2: "plant",
  t3_w3: "food",
  t3_w4: "body",

  t4_title: "Check Conversion",
  t4_text: "A change from one form to another is energy conversion.",
  t4_inst: "Shoot the real conversions.",
  t4_h1: "Some changes are real energy conversion.",
  t4_h2: "A stone staying still is not.",
  t4_q: "Which examples are conversions?",
  t4_t1: "lamp lights",
  t4_t2: "toaster heats",
  t4_t3: "stone stays still",
  t4_t4: "bicycle moves",

  t5_title: "Energy Is Conserved",
  t5_text: "Energy is not created or destroyed, only changed.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "Energy is not destroyed.",
  t5_h2: "It is transformed.",
  t5_sent: "Energy is not ___.",
  t5_c1: "destroyed",
  t5_c2: "created",
  t5_c3: "visible",
  t5_c4: "small",
} as const;

export const PHYSIK_K5_I5_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I5_BASE },
  de: { ...PHYSIK_K5_I5_BASE, explorer_title: "Energiefluss" },
  hu: { ...PHYSIK_K5_I5_BASE, explorer_title: "Energiaáramlás" },
  ro: { ...PHYSIK_K5_I5_BASE, explorer_title: "Fluxul energiei" },
};

export const PHYSIK_K5_I5_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🔋", title: "Change", bg: "#ECFEFF", color: "#0F766E" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "yes", label: "t1_b1" }, { id: "no", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "yes" },
        { text: "t1_i2", bucketId: "yes" },
        { text: "t1_i3", bucketId: "no" },
        { text: "t1_i4", bucketId: "yes" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "energy_conversion_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🔌", title: "Forms", bg: "#F0FDF4", color: "#16A34A" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "energy_forms_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "☀️", title: "Chain", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3", "t3_w4"],
      correctOrder: [0, 1, 2, 3],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "energy_conservation_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "⚙️", title: "Conversion Check", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: false },
        { id: "4", text: "t4_t4", isCorrect: true },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "energy_conversion_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "♻️", title: "Saved", bg: "#F1F5F9", color: "#334155" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "energy_conservation_mcq" },
  },
];

const PHYSIK_K5_I6_BASE = {
  explorer_title: "Heat Camp",
  t1_title: "Temperature",
  t1_text: "Temperature tells how warm or cold something is.",
  t1_inst: "Complete the sentence.",
  t1_h1: "Warm and cold are temperature words.",
  t1_h2: "The right answer is warm.",
  t1_sent: "Temperature tells how ___ or cold something is.",
  t1_c1: "warm",
  t1_c2: "heavy",
  t1_c3: "long",
  t1_c4: "wide",

  t2_title: "Heat Transfer",
  t2_text: "Heat moves by conduction, convection, or radiation.",
  t2_inst: "Match the heat move to the example.",
  t2_h1: "Metal usually conducts heat.",
  t2_h2: "Air and water can move heat by convection.",
  t2_l1: "metal spoon",
  t2_r1: "conduction",
  t2_l2: "hot air",
  t2_r2: "convection",
  t2_l3: "sunlight",
  t2_r3: "radiation",
  t2_l4: "hand on pot",
  t2_r4: "conduction",

  t3_title: "States of Matter",
  t3_text: "Solid, liquid, and gas are the main states of matter.",
  t3_inst: "Put the states in order from fixed to free moving.",
  t3_h1: "Solid keeps its shape.",
  t3_h2: "Gas spreads out the most.",
  t3_w1: "solid",
  t3_w2: "liquid",
  t3_w3: "gas",

  t4_title: "Melting and Boiling",
  t4_text: "Heat can change ice into water and water into steam.",
  t4_inst: "Shoot the change that is correct.",
  t4_h1: "Melting changes solid to liquid.",
  t4_h2: "Boiling changes liquid to gas.",
  t4_q: "Which change happens with heat?",
  t4_t1: "ice melts",
  t4_t2: "water boils",
  t4_t3: "stone stays still",
  t4_t4: "steam cools",

  t5_title: "Heat Review",
  t5_text: "Heat can move and change the state of matter.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "Hot things have more heat energy.",
  t5_h2: "The missing word is warm.",
  t5_sent: "Temperature tells how ___ or cold something is.",
  t5_c1: "warm",
  t5_c2: "fast",
  t5_c3: "round",
  t5_c4: "soft",
} as const;

export const PHYSIK_K5_I6_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I6_BASE },
  de: { ...PHYSIK_K5_I6_BASE, explorer_title: "Wärme" },
  hu: { ...PHYSIK_K5_I6_BASE, explorer_title: "Hő" },
  ro: { ...PHYSIK_K5_I6_BASE, explorer_title: "Căldură" },
};

export const PHYSIK_K5_I6_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🌡️", title: "Temperature", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "gap-fill",
      sentence: "t1_sent",
      choices: ["t1_c1", "t1_c2", "t1_c3", "t1_c4"],
      correctIndex: 0,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "temperature_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🔥", title: "Transfer", bg: "#FEE2E2", color: "#DC2626" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "heat_transfer_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🧊", title: "States", bg: "#EFF6FF", color: "#2563EB" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "states_of_matter_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "💧", title: "Change", bg: "#ECFCCB", color: "#65A30D" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: false },
        { id: "4", text: "t4_t4", isCorrect: true },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "melting_boiling_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "♨️", title: "Review", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "temperature_mcq" },
  },
];

const PHYSIK_K5_I7_BASE = {
  explorer_title: "Light Camp",
  t1_title: "Light Sources",
  t1_text: "Some light comes from nature, some from human-made devices.",
  t1_inst: "Sort the examples.",
  t1_h1: "Sun and stars are natural.",
  t1_h2: "Lamp and LED are artificial.",
  t1_b1: "natural",
  t1_b2: "artificial",
  t1_i1: "sun",
  t1_i2: "stars",
  t1_i3: "lamp",
  t1_i4: "LED",

  t2_title: "Shadows",
  t2_text: "A shadow appears when light is blocked.",
  t2_inst: "Match the shadow idea to the example.",
  t2_h1: "No light, no shadow shape.",
  t2_h2: "Blocking light creates darkness.",
  t2_l1: "light blocked",
  t2_r1: "shadow",
  t2_l2: "dark center",
  t2_r2: "umbra",
  t2_l3: "light edge",
  t2_r3: "penumbra",
  t2_l4: "sun",
  t2_r4: "shadow maker",

  t3_title: "Reflection",
  t3_text: "Light bounces off smooth surfaces like mirrors.",
  t3_inst: "Put the reflection steps in order.",
  t3_h1: "Incoming light hits the mirror.",
  t3_h2: "The light bounces away again.",
  t3_w1: "incoming light",
  t3_w2: "mirror",
  t3_w3: "reflected light",

  t4_title: "Refraction",
  t4_text: "Light bends when it moves from one material to another.",
  t4_inst: "Shoot the examples of refraction.",
  t4_h1: "A straw in water looks bent.",
  t4_h2: "A prism bends light too.",
  t4_q: "Which examples show refraction?",
  t4_t1: "straw in water",
  t4_t2: "prism",
  t4_t3: "ball on floor",
  t4_t4: "spoon in glass",

  t5_title: "Colors Spectrum",
  t5_text: "White light can split into the colors of the rainbow.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "A rainbow shows a spectrum.",
  t5_h2: "The missing word is spectrum.",
  t5_sent: "White light can be split into a ___.",
  t5_c1: "spectrum",
  t5_c2: "shadow",
  t5_c3: "sound",
  t5_c4: "circle",
} as const;

export const PHYSIK_K5_I7_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I7_BASE },
  de: { ...PHYSIK_K5_I7_BASE, explorer_title: "Licht" },
  hu: { ...PHYSIK_K5_I7_BASE, explorer_title: "Fény" },
  ro: { ...PHYSIK_K5_I7_BASE, explorer_title: "Lumină" },
};

export const PHYSIK_K5_I7_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "☀️", title: "Sources", bg: "#FFFBEB", color: "#D97706" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "nat", label: "t1_b1" }, { id: "art", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "nat" },
        { text: "t1_i2", bucketId: "nat" },
        { text: "t1_i3", bucketId: "art" },
        { text: "t1_i4", bucketId: "art" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "light_sources_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🌑", title: "Shadows", bg: "#E0E7FF", color: "#4338CA" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "shadows_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "🪞", title: "Reflection", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "reflection_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "💧", title: "Refraction", bg: "#DBEAFE", color: "#2563EB" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: false },
        { id: "4", text: "t4_t4", isCorrect: true },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "refraction_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🌈", title: "Spectrum", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "colors_spectrum_mcq" },
  },
];

const PHYSIK_K5_I8_BASE = {
  explorer_title: "Sound Camp",
  t1_title: "Sound Waves",
  t1_text: "Sound moves as waves through air, water, or solids.",
  t1_inst: "Sort the things into sound makers and quiet things.",
  t1_h1: "A bell makes sound.",
  t1_h2: "A stone is quiet.",
  t1_b1: "sound maker",
  t1_b2: "quiet",
  t1_i1: "bell",
  t1_i2: "speaker",
  t1_i3: "drum",
  t1_i4: "stone",

  t2_title: "Pitch and Volume",
  t2_text: "Pitch tells how high or low a sound is. Volume tells how loud it is.",
  t2_inst: "Match the sound idea to the example.",
  t2_h1: "High pitch uses fast vibration.",
  t2_h2: "Loud volume uses strong vibration.",
  t2_l1: "high pitch",
  t2_r1: "small vibration",
  t2_l2: "low pitch",
  t2_r2: "slow vibration",
  t2_l3: "loud",
  t2_r3: "strong",
  t2_l4: "quiet",
  t2_r4: "soft",

  t3_title: "Echo",
  t3_text: "An echo is sound that bounces back from a surface.",
  t3_inst: "Put the echo steps in order.",
  t3_h1: "Sound goes out first.",
  t3_h2: "Then it returns to your ear.",
  t3_w1: "sound goes out",
  t3_w2: "bounces back",
  t3_w3: "you hear echo",

  t4_title: "Speed of Sound",
  t4_text: "Sound travels fastest in solids and does not travel in a vacuum.",
  t4_inst: "Shoot the places where sound can travel.",
  t4_h1: "Sound needs a material to move through.",
  t4_h2: "Vacuum does not carry sound.",
  t4_q: "Where can sound travel?",
  t4_t1: "solid",
  t4_t2: "liquid",
  t4_t3: "gas",
  t4_t4: "vacuum",

  t5_title: "Sound Review",
  t5_text: "Sound needs a material to move through.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "Sound needs air, water, or solid material.",
  t5_h2: "The missing word is medium.",
  t5_sent: "Sound needs a ___.",
  t5_c1: "medium",
  t5_c2: "color",
  t5_c3: "spectrum",
  t5_c4: "circle",
} as const;

export const PHYSIK_K5_I8_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I8_BASE },
  de: { ...PHYSIK_K5_I8_BASE, explorer_title: "Schall" },
  hu: { ...PHYSIK_K5_I8_BASE, explorer_title: "Hang" },
  ro: { ...PHYSIK_K5_I8_BASE, explorer_title: "Sunet" },
};

export const PHYSIK_K5_I8_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🔊", title: "Sound", bg: "#ECFEFF", color: "#0891B2" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "make", label: "t1_b1" }, { id: "quiet", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "make" },
        { text: "t1_i2", bucketId: "make" },
        { text: "t1_i3", bucketId: "make" },
        { text: "t1_i4", bucketId: "quiet" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "sound_waves_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🎵", title: "Pitch", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "pitch_volume_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "📣", title: "Echo", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "echo_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "🌊", title: "Speed", bg: "#DBEAFE", color: "#2563EB" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: true },
        { id: "4", text: "t4_t4", isCorrect: false },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "speed_of_sound_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🫧", title: "Medium", bg: "#F0FDFA", color: "#0F766E" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "sound_waves_mcq" },
  },
];

const PHYSIK_K5_I9_BASE = {
  explorer_title: "Magnet Camp",
  t1_title: "Magnetic Materials",
  t1_text: "Some materials are attracted by magnets and others are not.",
  t1_inst: "Sort the examples.",
  t1_h1: "Iron and steel are magnetic.",
  t1_h2: "Wood and paper are not magnetic.",
  t1_b1: "magnetic",
  t1_b2: "not magnetic",
  t1_i1: "iron",
  t1_i2: "steel",
  t1_i3: "wood",
  t1_i4: "plastic",

  t2_title: "Magnetic Field",
  t2_text: "A magnetic field is the area around a magnet where it acts.",
  t2_inst: "Match the magnet idea to the result.",
  t2_h1: "Opposite poles attract.",
  t2_h2: "Same poles repel.",
  t2_l1: "north pole",
  t2_r1: "attracts south",
  t2_l2: "south pole",
  t2_r2: "attracts north",
  t2_l3: "same poles",
  t2_r3: "repel",
  t2_l4: "field",
  t2_r4: "area around magnet",

  t3_title: "Static Electricity",
  t3_text: "Rubbing can build up electric charge.",
  t3_inst: "Put the charge steps in order.",
  t3_h1: "Rubbing makes charge.",
  t3_h2: "The charge can jump as a spark.",
  t3_w1: "rubbing",
  t3_w2: "charge builds",
  t3_w3: "spark",

  t4_title: "Simple Circuits",
  t4_text: "A circuit needs a battery, wires, and a bulb or motor.",
  t4_inst: "Shoot the things that make a closed circuit.",
  t4_h1: "A closed circuit lets current flow.",
  t4_h2: "An open circuit does not work.",
  t4_q: "Which parts help make a simple circuit?",
  t4_t1: "battery",
  t4_t2: "wire",
  t4_t3: "bulb",
  t4_t4: "tape",

  t5_title: "Magnet Review",
  t5_text: "A closed circuit lets current flow.",
  t5_inst: "Fill in the missing word.",
  t5_h1: "A circuit must be closed.",
  t5_h2: "The missing word is closed.",
  t5_sent: "A closed circuit lets current ___.",
  t5_c1: "flow",
  t5_c2: "sleep",
  t5_c3: "freeze",
  t5_c4: "hide",
} as const;

export const PHYSIK_K5_I9_LABELS: Record<string, Record<string, string>> = {
  en: { ...PHYSIK_K5_I9_BASE },
  de: { ...PHYSIK_K5_I9_BASE, explorer_title: "Magnetismus" },
  hu: { ...PHYSIK_K5_I9_BASE, explorer_title: "Mágnesesség" },
  ro: { ...PHYSIK_K5_I9_BASE, explorer_title: "Magnetism" },
};

export const PHYSIK_K5_I9_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "simple-icon", icon: "🧲", title: "Materials", bg: "#FDF2F8", color: "#DB2777" },
    interactive: {
      type: "drag-to-bucket",
      buckets: [{ id: "mag", label: "t1_b1" }, { id: "not", label: "t1_b2" }],
      items: [
        { text: "t1_i1", bucketId: "mag" },
        { text: "t1_i2", bucketId: "mag" },
        { text: "t1_i3", bucketId: "not" },
        { text: "t1_i4", bucketId: "not" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { generate: "magnets_mcq" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "simple-icon", icon: "🧭", title: "Field", bg: "#EEF2FF", color: "#4F46E5" },
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { generate: "magnetic_field_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "simple-icon", icon: "⚡", title: "Charge", bg: "#FEF3C7", color: "#D97706" },
    interactive: {
      type: "physics-stacker",
      words: ["t3_w1", "t3_w2", "t3_w3"],
      correctOrder: [0, 1, 2],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { generate: "static_electricity_mcq" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "simple-icon", icon: "💡", title: "Circuit", bg: "#F0FDF4", color: "#16A34A" },
    interactive: {
      type: "physics-slingshot",
      question: "t4_q",
      targets: [
        { id: "1", text: "t4_t1", isCorrect: true },
        { id: "2", text: "t4_t2", isCorrect: true },
        { id: "3", text: "t4_t3", isCorrect: true },
        { id: "4", text: "t4_t4", isCorrect: false },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { generate: "simple_circuits_mcq" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "simple-icon", icon: "🔋", title: "Current", bg: "#F5F3FF", color: "#7C3AED" },
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { generate: "simple_circuits_mcq" },
  },
];
