// lib/explorerPools/romanaC3.ts — AstroRomână Clasa 3 pool stubs
import type { PoolTopicDef } from "./types";

function mkLabels(ro: string, en: string, hu: string, de: string) {
  return {
    en: { explorer_title: en, t1_title: en, t1_text: en, t1_q: en+"?", t1_qa: "A", t1_qb: "B", t1_qc: "C", t1_qd: "D", t1_inst: en, t1_h1: en, t1_h2: en, t1_l1: "1", t1_r1: "a", t1_l2: "2", t1_r2: "b", t1_l3: "3", t1_r3: "c" },
    hu: { explorer_title: hu, t1_title: hu, t1_text: hu, t1_q: hu+"?", t1_qa: "A", t1_qb: "B", t1_qc: "C", t1_qd: "D", t1_inst: hu, t1_h1: hu, t1_h2: hu, t1_l1: "1", t1_r1: "a", t1_l2: "2", t1_r2: "b", t1_l3: "3", t1_r3: "c" },
    de: { explorer_title: de, t1_title: de, t1_text: de, t1_q: de+"?", t1_qa: "A", t1_qb: "B", t1_qc: "C", t1_qd: "D", t1_inst: de, t1_h1: de, t1_h2: de, t1_l1: "1", t1_r1: "a", t1_l2: "2", t1_r2: "b", t1_l3: "3", t1_r3: "c" },
    ro: { explorer_title: ro, t1_title: ro, t1_text: ro, t1_q: ro+"?", t1_qa: "A", t1_qb: "B", t1_qc: "C", t1_qd: "D", t1_inst: ro, t1_h1: ro, t1_h2: ro, t1_l1: "1", t1_r1: "a", t1_l2: "2", t1_r2: "b", t1_l3: "3", t1_r3: "c" },
  };
}

function mkPool(color: string): PoolTopicDef[] {
  return [
    {
      infoTitle: "t1_title", infoText: "t1_text",
      svg: { type: "simple-icon", icon: "📖", color },
      hintKey: "t1_h1",
      interactive: { type: "match-pairs", pairs: [{ left: "t1_l1", right: "t1_r1" }, { left: "t1_l2", right: "t1_r2" }, { left: "t1_l3", right: "t1_r3" }], instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2" },
      quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
      difficulty: "medium",
    },
  ];
}

export const SUBST3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Substantivul — cazuri",

    t1_title: "Ce este substantivul?",
    t1_text: "Substantivul numește ființe, lucruri sau fenomene. El răspunde la întrebările „cine?” și „ce?”.",
    t1_inst: "Atinge doar substantivele din listă.",
    t1_h1: "Privește fiecare cuvânt.",
    t1_h2: "Substantivele denumesc ceva concret.",
    t1_w1: "copil",
    t1_w2: "alergă",
    t1_w3: "masă",
    t1_w4: "frumos",
    t1_w5: "ploaie",
    t1_w6: "scrie",
    t1_q: "Care cuvânt este substantiv?",
    t1_qa: "masă",
    t1_qb: "alergă",
    t1_qc: "frumos",
    t1_qd: "scrie",

    t2_title: "Ființe, lucruri sau fenomene",
    t2_text: "Substantivele pot reprezenta ființe, obiecte sau fenomene naturale. Grupăm pe baza sensului lor.",
    t2_inst: "Trage fiecare cuvânt în categorie.",
    t2_h1: "Întreabă-te: cine? ce? ce se întâmplă?",
    t2_h2: "Copil este ființă, carte este lucru, ploaia este fenomen.",
    t2_b1: "Ființe",
    t2_b2: "Lucruri",
    t2_b3: "Fenomene",
    t2_i1: "pisică",
    t2_i2: "ghiozdan",
    t2_i3: "ploiă",
    t2_i4: "copil",
    t2_i5: "carte",
    t2_i6: "ninsoare",
    t2_q: "Care substantiv este fenomen?",
    t2_qa: "carte",
    t2_qb: "copil",
    t2_qc: "ninsoare",
    t2_qd: "pisică",

    t3_title: "Substantive comune vs proprii",
    t3_text: "Substantivele proprii sunt nume (Ana, România). Cele comune numesc în general obiecte sau ființe.",
    t3_inst: "Potrivește cuvintele cu grupa potrivită.",
    t3_h1: "Observe că România se scrie cu majusculă.",
    t3_h2: "Copilul este substantiv comun.",
    t3_b1: "Comune",
    t3_b2: "Proprii",
    t3_i1: "copil",
    t3_i2: "Ana",
    t3_i3: "școală",
    t3_i4: "București",
    t3_i5: "pisică",
    t3_i6: "Maria",
    t3_q: "Care este substantiv propriu?",
    t3_qa: "copil",
    t3_qb: "București",
    t3_qc: "școală",
    t3_qd: "pisică",

    t4_title: "Singular și plural",
    t4_text: "Singularul arată un singur obiect; pluralul arată multe. Formele se pot recunoaște ușor.",
    t4_inst: "Perechează singularul cu pluralul.",
    t4_h1: "Copil crește în copii.",
    t4_h2: "Floare devine flori.",
    t4_l1: "copil",
    t4_r1: "copii",
    t4_l2: "floare",
    t4_r2: "flori",
    t4_l3: "carte",
    t4_r3: "cărți",
    t4_l4: "nor",
    t4_r4: "nori",
    t4_q: "Care este pluralul pentru „carte”?",
    t4_qa: "cărți",
    t4_qb: "carte",
    t4_qc: "cartiță",
    t4_qd: "cărțile",

    t5_title: "Substantivul din propoziție",
    t5_text: "Alegem substantivul care se potrivește în propoziție. El trebuie să denumească ceea ce vedem sau simțim.",
    t5_inst: "Completează propoziția cu substantivul potrivit.",
    t5_h1: "Propoziția descrie cerul plin de obiecte.",
    t5_h2: "Cuvântul „nori” se potrivește la sfârșit.",
    t5_sent: "Pe cer sunt mulți ___.",
    t5_c1: "nori",
    t5_c2: "alerg",
    t5_c3: "veseli",
    t5_c4: "scrie",
    t5_q: "Ce cuvânt completează corect propoziția?",
    t5_qa: "nori",
    t5_qb: "alerg",
    t5_qc: "scrie",
    t5_qd: "veseli",

    t6_title: "Găsim substantivele",
    t6_text: "Uneori substantivele stau printre alte părți de vorbire. Le recunoaștem după ceea ce denumesc.",
    t6_inst: "Lovește doar substantivele din listă.",
    t6_h1: "Soare, elev și minge sunt substantive.",
    t6_h2: "Verbele și adjectivele nu aparțin acestei grupe.",
    t6_qmain: "Care cuvinte sunt substantive?",
    t6_t1: "soare",
    t6_t2: "frumos",
    t6_t3: "minge",
    t6_t4: "citește",
    t6_t5: "elev",
    t6_t6: "repede",
    t6_q: "Care dintre acestea este substantiv?",
    t6_qa: "repede",
    t6_qb: "elev",
    t6_qc: "citește",
    t6_qd: "frumos",

    t7_title: "Câte substantive sunt?",
    t7_text: "Numărăm substantivele din propoziție pentru a observa câte denumiri apar.",
    t7_inst: "Atinge de două ori pentru cele două substantive.",
    t7_h1: "Propoziția „Ana are un caiet.” are două substantive.",
    t7_h2: "Ana și caiet sunt substantive.",
    t7_q: "Câte substantive sunt în propoziția „Ana are un caiet.”?",
    t7_qa: "1",
    t7_qb: "2",
    t7_qc: "3",
    t7_qd: "4",

    t8_title: "Singular sau plural 2",
    t8_text: "Unele substantive se pot pune în grupuri de singular vs plural. Le sortăm corect.",
    t8_inst: "Aruncă fiecare cuvânt în grupa potrivită.",
    t8_h1: "Mere și copii sunt plural.",
    t8_h2: "Masă și elev sunt singular.",
    t8_b1: "Singular",
    t8_b2: "Plural",
    t8_i1: "masă",
    t8_i2: "mere",
    t8_i3: "elev",
    t8_i4: "copii",
    t8_i5: "nor",
    t8_i6: "flori",
    t8_q: "Care substantiv este la plural?",
    t8_qa: "nor",
    t8_qb: "masă",
    t8_qc: "flori",
    t8_qd: "elev",

    t9_title: "Recapitulare substantive",
    t9_text: "Revizuim toate cunoștințele despre substantive: categorii, plural și funcția în propoziție.",
    t9_inst: "Potrivește substantivul cu grupa corectă.",
    t9_h1: "Gândește-te dacă este ființă, lucru sau fenomen.",
    t9_h2: "Ana este ființă, ploaie este fenomen.",
    t9_l1: "Ana",
    t9_r1: "ființă",
    t9_l2: "ploaie",
    t9_r2: "fenomen",
    t9_l3: "carte",
    t9_r3: "lucru",
    t9_l4: "Maria",
    t9_r4: "nume propriu",
    t9_q: "Ce fel de substantiv este „Maria”?",
    t9_qa: "lucru",
    t9_qb: "fenomen",
    t9_qc: "nume propriu",
    t9_qd: "acțiune",
  },
};

export const SUBST3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [{ text: "copil", color: "#1D4ED8", bg: "#DBEAFE" }, { text: "alergă", color: "#047857", bg: "#D1FAE5" }, { text: "masă", color: "#9333EA", bg: "#EDE9FE" }], bg: "#F3F4F6" },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_w1", "t1_w2", "t1_w3", "t1_w4", "t1_w5", "t1_w6"],
      correctIndices: [0, 2, 4],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "icon-grid", items: [
      { emoji: "👧", label: "pisică" }, { emoji: "🎒", label: "ghiozdan" },
      { emoji: "🌧️", label: "ploaie" }, { emoji: "📘", label: "carte" },
    ], bg: "#ECFEFF" },
    hintKey: "t2_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "fiinte", label: "t2_b1" },
        { id: "lucruri", label: "t2_b2" },
        { id: "fenomene", label: "t2_b3" },
      ],
      items: [
        { text: "t2_i1", bucketId: "fiinte" },
        { text: "t2_i2", bucketId: "lucruri" },
        { text: "t2_i3", bucketId: "fenomene" },
        { text: "t2_i4", bucketId: "fiinte" },
        { text: "t2_i5", bucketId: "lucruri" },
        { text: "t2_i6", bucketId: "fenomene" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qc" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "two-groups", left: { items: ["copil", "pisică", "școală"], bg: "#DBEAFE", border: "#2563EB" }, right: { items: ["Ana", "București", "Maria"], bg: "#FEF3C7", border: "#F97316" } },
    hintKey: "t3_h1",
    interactive: {
      type: "physics-bucket",
      buckets: [
        { id: "common", label: "t3_b1" },
        { id: "proper", label: "t3_b2" },
      ],
      items: [
        { text: "t3_i1", bucketId: "common" },
        { text: "t3_i2", bucketId: "proper" },
        { text: "t3_i3", bucketId: "common" },
        { text: "t3_i4", bucketId: "proper" },
        { text: "t3_i5", bucketId: "common" },
        { text: "t3_i6", bucketId: "proper" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qc" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "letter-pairs", pairs: [["copil","copii"], ["floare","flori"], ["carte","cărți"]], color: "#10B981", dimColor: "#86EFAC" },
    hintKey: "t4_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t4_l1", right: "t4_r1" },
        { left: "t4_l2", right: "t4_r2" },
        { left: "t4_l3", right: "t4_r3" },
        { left: "t4_l4", right: "t4_r4" },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "icon-grid", items: [{ emoji: "☁️", label: "nori" }, { emoji: "🌤️", label: "cer" }], bg: "#F0F9FF" },
    hintKey: "t5_h1",
    interactive: {
      type: "gap-fill",
      sentence: "t5_sent",
      choices: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      correctIndex: 0,
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t6_title",
    infoText: "t6_text",
    svg: { type: "text-bubbles", items: [{ text: "soare", emoji: "☀️", color: "#F59E0B", bg: "#FEF3C7" }, { text: "minge", emoji: "⚽", color: "#2563EB", bg: "#DBEAFE" }, { text: "elev", emoji: "🎒", color: "#047857", bg: "#D1FAE5" }], bg: "#F7F6FF" },
    hintKey: "t6_h1",
    interactive: {
      type: "physics-slingshot",
      question: "t6_qmain",
      targets: [
        { id: "sun", text: "t6_t1", isCorrect: true },
        { id: "perf", text: "t6_t2", isCorrect: false },
        { id: "ball", text: "t6_t3", isCorrect: true },
        { id: "reads", text: "t6_t4", isCorrect: false },
        { id: "student", text: "t6_t5", isCorrect: true },
        { id: "very", text: "t6_t6", isCorrect: false },
      ],
      instruction: "t6_inst",
      hint1: "t6_h1",
      hint2: "t6_h2",
    },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qb" },
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title",
    infoText: "t7_text",
    svg: { type: "sentence-display", words: ["Ana", "are", "un", "caiet"], highlightIndices: [0, 3], color: "#FF5782" },
    hintKey: "t7_h1",
    interactive: {
      type: "tap-count",
      tapCount: { emoji: "📦", count: 2 },
      instruction: "t7_inst",
      hint1: "t7_h1",
      hint2: "t7_h2",
    },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title",
    infoText: "t8_text",
    svg: { type: "text-bubbles", items: [{ text: "masă", color: "#2563EB", bg: "#E0F2FE" }, { text: "copii", color: "#0EA5E9", bg: "#DBEAFE" }, { text: "nor", color: "#E11D48", bg: "#FFE4E6" }], bg: "#F8FAFC" },
    hintKey: "t8_h1",
    interactive: {
      type: "physics-bucket",
      buckets: [
        { id: "sg", label: "t8_b1" },
        { id: "pl", label: "t8_b2" },
      ],
      items: [
        { text: "t8_i1", bucketId: "sg" },
        { text: "t8_i2", bucketId: "pl" },
        { text: "t8_i3", bucketId: "sg" },
        { text: "t8_i4", bucketId: "pl" },
        { text: "t8_i5", bucketId: "sg" },
        { text: "t8_i6", bucketId: "pl" },
      ],
      instruction: "t8_inst",
      hint1: "t8_h1",
      hint2: "t8_h2",
    },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qc" },
  },
  {
    difficulty: "hard",
    infoTitle: "t9_title",
    infoText: "t9_text",
    svg: { type: "text-bubbles", items: [
      { text: "Ana", color: "#1D4ED8", bg: "#E0F2FE" },
      { text: "ploaie", color: "#0EA5E9", bg: "#DBEAFE" },
      { text: "carte", color: "#BE185D", bg: "#FCE7F3" },
      { text: "Maria", color: "#9D174D", bg: "#FEE2E2" },
    ] },
    hintKey: "t9_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t9_l1", right: "t9_r1" },
        { left: "t9_l2", right: "t9_r2" },
        { left: "t9_l3", right: "t9_r3" },
        { left: "t9_l4", right: "t9_r4" },
      ],
      instruction: "t9_inst",
      hint1: "t9_h1",
      hint2: "t9_h2",
    },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qc" },
  },
];

export const VERB3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Verbul — timpuri",

    t1_title: "Ce este un verb?",
    t1_text: "Verbul arată ce face cineva sau ce se întâmplă. El răspunde la întrebarea „ce face?” sau „ce se întâmplă?”.",
    t1_inst: "Atinge doar verbele din listă.",
    t1_h1: "Privește acțiunea din cuvânt.",
    t1_h2: "Aleargă, scrie, citește sunt verbe.",
    t1_w1: "aleargă",
    t1_w2: "minge",
    t1_w3: "scrie",
    t1_w4: "copil",
    t1_w5: "cântă",
    t1_w6: "carte",
    t1_q: "Care cuvânt arată o acțiune?",
    t1_qa: "scrie",
    t1_qb: "copil",
    t1_qc: "carte",
    t1_qd: "minge",

    t2_title: "Persoanele verbului",
    t2_text: "Verbul se schimbă în funcție de persoana care face acțiunea: eu, tu, el/ea, noi, voi, ei/ele.",
    t2_inst: "Potrivește forma corectă cu persoana dată.",
    t2_h1: "Eu scriu, tu scrii, el scrie.",
    t2_h2: "Ascultă care persoană apare în propoziție.",
    t2_l1: "eu scriu",
    t2_r1: "scriu",
    t2_l2: "tu citești",
    t2_r2: "citești",
    t2_l3: "el aleargă",
    t2_r3: "aleargă",
    t2_l4: "noi citim",
    t2_r4: "cităm",
    t2_q: "Cum spune verbul „a scrie” la persoana a treia singular?",
    t2_qa: "scriu",
    t2_qb: "scriem",
    t2_qc: "scrie",
    t2_qd: "scrii",

    t3_title: "Timpuri: prezent vs trecut",
    t3_text: "În prezent spunem ce facem acum, iar în trecut spunem ce s-a întâmplat deja.",
    t3_inst: "Aruncă doar verbele care se potrivesc cu timpul cerut.",
    t3_h1: "Prezentul spune „acum”.",
    t3_h2: "Trecutul spune „ieri”.",
    t3_b1: "Prezent",
    t3_b2: "Trecut",
    t3_i1: "aleargă",
    t3_i2: "a alergat",
    t3_i3: "citește",
    t3_i4: "a citit",
    t3_i5: "scrie",
    t3_i6: "a scris",
    t3_q: "Care verb este la trecut?",
    t3_qa: "citește",
    t3_qb: "a citit",
    t3_qc: "scrie",
    t3_qd: "aleargă",

    t4_title: "Conjugare în persoana a doua",
    t4_text: "Persoana a doua arată ce face „tu”. Verbul se termină în -i sau -e, în funcție de verb.",
    t4_inst: "Atinge forma corectă pentru „tu”.",
    t4_h1: "Tu citești și tu scrii.",
    t4_h2: "Fii atent la terminație.",
    t4_sent: "Tu ___ o poveste.",
    t4_c1: "citești",
    t4_c2: "citește",
    t4_c3: "citeștii",
    t4_c4: "citeaște",
    t4_q: "Cum se spune „tu” + „a scrie”?",
    t4_qa: "scrii",
    t4_qb: "scrie",
    t4_qc: "scriem",
    t4_qd: "scrieți",

    t5_title: "Verbul în propoziție",
    t5_text: "Găsește verbul potrivit care descrie acțiunea din propoziție. Propozițiile sunt mici povești.",
    t5_inst: "Completează propoziția cu verbul corect.",
    t5_h1: "Propoziția spune ce face copilul.",
    t5_h2: "„Aleargă” descrie mișcarea.",
    t5_sent: "Copilul ___ prin parc.",
    t5_c1: "aleargă",
    t5_c2: "carte",
    t5_c3: "frumos",
    t5_c4: "vrea",
    t5_q: "Ce verb merge în propoziție?",
    t5_qa: "aleargă",
    t5_qb: "carte",
    t5_qc: "frumos",
    t5_qd: "copil",

    t6_title: "Conjugăm la plural",
    t6_text: "Când vorbim despre noi sau voi, folosim forme la plural. Alegem forma potrivită pentru „noi”.",
    t6_inst: "Potrivește pluralul cu persoana „noi”.",
    t6_h1: "Noi citim și noi scriem.",
    t6_h2: "Verbele se pun la plural.",
    t6_qmain: "Care forme sunt la plural?",
    t6_t1: "noi citim",
    t6_t2: "voi scrie",
    t6_t3: "ei citesc",
    t6_t4: "noi scriem",
    t6_t5: "tu citești",
    t6_t6: "noi alergăm",
    t6_q: "Care verb este la plural?",
    t6_qa: "tu citești",
    t6_qb: "noi alergăm",
    t6_qc: "voi scrie",
    t6_qd: "tu scrii",

    t7_title: "Numărăm acțiunile",
    t7_text: "Câte acțiuni face un verb? Uneori repetăm de mai multe ori o acțiune.",
    t7_inst: "Atinge de trei ori pentru cele trei verbe.",
    t7_h1: "Propoziția conține trei acțiuni.",
    t7_h2: "Fiecare verb se numără o dată.",
    t7_q: "Câte acțiuni apar?",
    t7_qa: "2",
    t7_qb: "3",
    t7_qc: "4",
    t7_qd: "1",

    t8_title: "Construim propoziția",
    t8_text: "Ordinea cuvintelor face propoziția corectă. Începem cu cine face acțiunea, apoi ce face.",
    t8_inst: "Așază fragmentele în ordinea corectă.",
    t8_h1: "Ana primește și apoi citește.",
    t8_h2: "Ordinea: Ana - primește - o - scrisoare.",
    t8_f1: "Ana",
    t8_f2: "primește",
    t8_f3: "o",
    t8_f4: "scrisoare",
    t8_q: "Care cuvânt arată acțiunea din propoziție?",
    t8_qa: "primește",
    t8_qb: "Ana",
    t8_qc: "scrisoare",
    t8_qd: "o",

    t9_title: "Recapitulare verbe",
    t9_text: "Revedem ce am învățat: ce este verbul, cum se schimbă și cum stă în propoziție.",
    t9_inst: "Potrivește forma cu regula corectă.",
    t9_h1: "Gândește-te dacă este prezent sau trecut.",
    t9_h2: "Verbele arată acțiuni și se acordă cu persoana.",
    t9_l1: "tu citești",
    t9_r1: "prezent",
    t9_l2: "a citit",
    t9_r2: "trecut",
    t9_l3: "noi alergăm",
    t9_r3: "plural",
    t9_l4: "Ana scrie",
    t9_r4: "singular",
    t9_q: "Ce fel de formă este „a citit”?",
    t9_qa: "prezent",
    t9_qb: "trecut",
    t9_qc: "plural",
    t9_qd: "singular",
  },
};

export const VERB3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [{ text: "aleargă", color: "#1D4ED8", bg: "#DBEAFE" }, { text: "copil", color: "#047857", bg: "#D1FAE5" }, { text: "scrie", color: "#9333EA", bg: "#EDE9FE" }], bg: "#F9FAFB" },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_w1", "t1_w2", "t1_w3", "t1_w4", "t1_w5", "t1_w6"],
      correctIndices: [0, 2, 4],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "sentence-display", words: ["eu", "scriu"], highlightIndices: [0, 1], color: "#34D399" },
    hintKey: "t2_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qc" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "two-groups", left: { items: ["aleargă","citește","scrie"], bg: "#DBEAFE", border: "#2563EB" }, right: { items: ["a alergat","a citit","a scris"], bg: "#FEF3C7", border: "#F97316" } },
    hintKey: "t3_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "prez", label: "t3_b1" },
        { id: "trecut", label: "t3_b2" },
      ],
      items: [
        { text: "t3_i1", bucketId: "prez" },
        { text: "t3_i2", bucketId: "trecut" },
        { text: "t3_i3", bucketId: "prez" },
        { text: "t3_i4", bucketId: "trecut" },
        { text: "t3_i5", bucketId: "prez" },
        { text: "t3_i6", bucketId: "trecut" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "text-bubbles", items: [{ text: "Tu", color: "#2563EB", bg: "#E0F2FE" }, { text: "citești", color: "#0EA5E9", bg: "#DBEAFE" }, { text: "o carte", color: "#E11D48", bg: "#FEE2E2"}], bg: "#F8FAFC" },
    hintKey: "t4_h1",
    interactive: {
      type: "gap-fill",
      sentence: "t4_sent",
      choices: ["t4_c1", "t4_c2", "t4_c3", "t4_c4"],
      correctIndex: 0,
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "word-display", word: "aleargă", highlightChars: ["a"], color: "#F97316", subtitle: "Cuvântul spune ce face copilul." },
    hintKey: "t5_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t6_title",
    infoText: "t6_text",
    svg: { type: "text-bubbles", items: [{ text: "noi", color: "#0369A1", bg: "#E0F2FE" }, { text: "citim", color: "#1D4ED8", bg: "#DBEAFE" }, { text: "scriem", color: "#059669", bg: "#D1FAE5" }], bg: "#F7F6FF" },
    hintKey: "t6_h1",
    interactive: {
      type: "physics-slingshot",
      question: "t6_qmain",
      targets: [
        { id: "noi", text: "t6_t1", isCorrect: true },
        { id: "voi", text: "t6_t2", isCorrect: true },
        { id: "ei", text: "t6_t3", isCorrect: true },
        { id: "tu", text: "t6_t4", isCorrect: false },
        { id: "el", text: "t6_t5", isCorrect: false },
        { id: "ea", text: "t6_t6", isCorrect: false },
      ],
      instruction: "t6_inst",
      hint1: "t6_h1",
      hint2: "t6_h2",
    },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t7_title",
    infoText: "t7_text",
    svg: { type: "sentence-display", words: ["Ana", "aleargă", "și", "tu", "alegi"], highlightIndices: [1], color: "#FB923C" },
    hintKey: "t7_h1",
    interactive: {
      type: "tap-count",
      tapCount: { emoji: "👣", count: 3 },
      instruction: "t7_inst",
      hint1: "t7_h1",
      hint2: "t7_h2",
    },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title",
    infoText: "t8_text",
    svg: { type: "text-bubbles", items: [{ text: "Ana", color: "#2563EB", bg: "#E0F2FE" }, { text: "primește", color: "#0EA5E9", bg: "#DBEAFE" }, { text: "scrisoare", color: "#E11D48", bg: "#FEE2E2" }], bg: "#F8FAFC" },
    hintKey: "t8_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t8_f1", "t8_f2", "t8_f3", "t8_f4"],
      instruction: "t8_inst",
      hint1: "t8_h1",
      hint2: "t8_h2",
    },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" },
  },
  {
    difficulty: "hard",
    infoTitle: "t9_title",
    infoText: "t9_text",
    svg: { type: "text-bubbles", items: [
      { text: "tu citești", color: "#2563EB", bg: "#E0F2FE" },
      { text: "a citit", color: "#0EA5E9", bg: "#DBEAFE" },
      { text: "Noi scriem", color: "#059669", bg: "#D1FAE5" },
    ], bg: "#F7F6FF" },
    hintKey: "t9_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t9_l1", right: "t9_r1" },
        { left: "t9_l2", right: "t9_r2" },
        { left: "t9_l3", right: "t9_r3" },
        { left: "t9_l4", right: "t9_r4" },
      ],
      instruction: "t9_inst",
      hint1: "t9_h1",
      hint2: "t9_h2",
    },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qb" },
  },
];

export const ADJ3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Adjectivul — acordul",

    t1_title: "Ce este adjectivul?",
    t1_text: "Adjectivul descrie cum este un substantiv: frumos, roșu sau mare, iar el se acordă în gen și număr cu substantivul.",
    t1_inst: "Alege doar adjectivele din listă.",
    t1_h1: "Privește cu atenție fiecare cuvânt.",
    t1_h2: "Adjectivele răspund la întrebarea \"cum\"?",
    t1_w1: "frumos",
    t1_w2: "copil",
    t1_w3: "mare",
    t1_w4: "masă",
    t1_w5: "mic",
    t1_w6: "flori",
    t1_q: "Care cuvânt este adjectiv?",
    t1_qa: "frumos",
    t1_qb: "copil",
    t1_qc: "masă",
    t1_qd: "flori",

    t2_title: "Adjectivul și substantivul",
    t2_text: "Adjectivul trebuie să aibă același gen și număr ca substantivul: fată frumoasă, băieți veseli.",
    t2_inst: "Potrivește perechile corecte.",
    t2_h1: "Observă forma fiecărui cuvânt.",
    t2_h2: "Ele trebuie să se potrivească între ele.",
    t2_l1: "fată",
    t2_r1: "frumoasă",
    t2_l2: "băieți",
    t2_r2: "veseli",
    t2_l3: "flori",
    t2_r3: "colorate",
    t2_l4: "masă",
    t2_r4: "mare",
    t2_q: "Care pereche este corectă?",
    t2_qa: "flori - colorate",
    t2_qb: "băieți - colorate",
    t2_qc: "masă - veseli",
    t2_qd: "fată - frumoasă",

    t3_title: "Genul adjectivelor",
    t3_text: "Formele adjective se schimbă la masculin și feminin; ele pot termina în -u sau -ă.",
    t3_inst: "Alege forma de feminin.",
    t3_h1: "Fata este frumoasă.",
    t3_h2: "Băiatul este frumos.",
    t3_w1: "frumoasă",
    t3_w2: "frumos",
    t3_w3: "mică",
    t3_w4: "mic",
    t3_w5: "mare",
    t3_w6: "mare",
    t3_q: "Care adjectiv e feminin?",
    t3_qa: "frumoasă",
    t3_qb: "frumos",
    t3_qc: "mic",
    t3_qd: "mare",

    t4_title: "Singular versus plural",
    t4_text: "Adjectivele se potrivesc cu pluralul: flori roșii, mese mari.",
    t4_inst: "Alege forma de plural corectă.",
    t4_h1: "Pluralul are terminații în -i/-e.",
    t4_h2: ""Roșii" merge cu flori.",
    t4_l1: "flori",
    t4_r1: "roșii",
    t4_l2: "mese",
    t4_r2: "mari",
    t4_l3: "fete",
    t4_r3: "colorate",
    t4_l4: "băieți",
    t4_r4: "veseli",
    t4_q: "Care adjectiv este plural?",
    t4_qa: "colorate",
    t4_qb: "mare",
    t4_qc: "veseli",
    t4_qd: "mic",

    t5_title: "Adjectivul potrivit",
    t5_text: "Alege adjectivul care se potrivește cu substantivul din propoziție.",
    t5_inst: "Completează propoziția cu forma corectă.",
    t5_h1: "Copilul este vesel.",
    t5_h2: "Forma trebuie să fie masculin, singular.",
    t5_sent: "Copilul este ___.",
    t5_c1: "vesel",
    t5_c2: "veseli",
    t5_c3: "veselă",
    t5_c4: "vesele",
    t5_q: "Ce adjectiv se potrivește?",
    t5_qa: "vesel",
    t5_qb: "vesele",
    t5_qc: "veseli",
    t5_qd: "veselă",

    t6_title: "Plural feminin",
    t6_text: "Substantivele feminine la plural cer adjective precum vesele, frumoase.",
    t6_inst: "Lovește doar adjectivele la plural feminin.",
    t6_h1: "Fetele sunt vesele.",
    t6_h2: "Mesele sunt mari.",
    t6_t1: "vesele",
    t6_t2: "veseli",
    t6_t3: "mari",
    t6_t4: "mare",
    t6_t5: "frumoase",
    t6_t6: "frumos",
    t6_q: "Care adjectiv e plural feminin?",
    t6_qa: "veseli",
    t6_qb: "vesele",
    t6_qc: "frumos",
    t6_qd: "mare",

    t7_title: "Perechi de adjective",
    t7_text: "Potrivește perechile care descriu același substantiv în gen diferit.",
    t7_inst: "Aruncă perechile potrivite.",
    t7_h1: "Frumos — frumoasă, mic — mică.",
    t7_h2: "Privește dacă genul se potrivește.",
    t7_l1: "frumos",
    t7_r1: "frumoasă",
    t7_l2: "mic",
    t7_r2: "mică",
    t7_l3: "mare",
    t7_r3: "mare",
    t7_l4: "colorat",
    t7_r4: "colorată",
    t7_q: "Care pereche e corectă?",
    t7_qa: "colorat - colorată",
    t7_qb: "mare - mare",
    t7_qc: "mic - mică",
    t7_qd: "frumos - frumos",

    t8_title: "Adjectivul corect",
    t8_text: "Verificăm dacă adjectivele se potrivesc cu propozițiile simple.",
    t8_inst: "Potrivește forma corectă cu propoziția.",
    t8_h1: "Privește genul și numărul.",
    t8_h2: "Fată frumoasă e feminin, singular.",
    t8_w1: "băiat frumos",
    t8_w2: "fată frumoasă",
    t8_w3: "flori colorate",
    t8_w4: "masa mare",
    t8_q: "Care propoziție e corectă?",
    t8_qa: "băiat frumos",
    t8_qb: "fată frumoasă",
    t8_qc: "flori colorate",
    t8_qd: "masa mare",

    t9_title: "Recapitulare",
    t9_text: "Revenim asupra regulilor și alegem perechile corecte.",
    t9_inst: "Lovește doar variantele corecte.",
    t9_h1: "Adjectivele se acordă cu substantivul.",
    t9_h2: "Genul și numărul contează.",
    t9_l1: "frumoasă",
    t9_r1: "fată",
    t9_l2: "colorat",
    t9_r2: "masă",
    t9_l3: "veseli",
    t9_r3: "băieți",
    t9_l4: "mari",
    t9_r4: "flori",
    t9_q: "Care alegere e corectă?",
    t9_qa: "frumoasă - fată",
    t9_qb: "colorat - masă",
    t9_qc: "veseli - fete",
    t9_qd: "mare - băieți",
  },
};

export const ADJ3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [{ text: "frumos", color: "#047857", bg: "#D1FAE5" }, { text: "copil", color: "#065F46", bg: "#DCFCE7" }, { text: "mare", color: "#059669", bg: "#D9F99D" }], bg: "#ECFDF3" },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_w1", "t1_w2", "t1_w3", "t1_w4", "t1_w5", "t1_w6"],
      correctIndices: [0, 2, 4],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "drag-to-bucket", buckets: [
      { id: "masc", label: "t2_b1" },
      { id: "fem", label: "t2_b2" },
      { id: "pl", label: "t2_b3" },
    ], items: [
      { text: "t2_i1", bucketId: "masc" },
      { text: "t2_i2", bucketId: "fem" },
      { text: "t2_i3", bucketId: "pl" },
      { text: "t2_i4", bucketId: "masc" },
      { text: "t2_i5", bucketId: "fem" },
      { text: "t2_i6", bucketId: "pl" },
    ], bg: "#ECFEFF" },
    hintKey: "t2_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "masc", label: "t2_b1" },
        { id: "fem", label: "t2_b2" },
        { id: "pl", label: "t2_b3" },
      ],
      items: [
        { text: "t2_i1", bucketId: "masc" },
        { text: "t2_i2", bucketId: "fem" },
        { text: "t2_i3", bucketId: "pl" },
        { text: "t2_i4", bucketId: "masc" },
        { text: "t2_i5", bucketId: "fem" },
        { text: "t2_i6", bucketId: "pl" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "match-pairs", pairs: [
      { left: "t3_l1", right: "t3_r1" },
      { left: "t3_l2", right: "t3_r2" },
      { left: "t3_l3", right: "t3_r3" },
      { left: "t3_l4", right: "t3_r4" },
    ] },
    hintKey: "t3_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t3_l1", right: "t3_r1" },
        { left: "t3_l2", right: "t3_r2" },
        { left: "t3_l3", right: "t3_r3" },
        { left: "t3_l4", right: "t3_r4" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "text-bubbles", items: [
      { text: "flori roșii", color: "#DC2626", bg: "#FEE2E2" },
      { text: "mese mari", color: "#0EA5E9", bg: "#DBEAFE" },
    ] },
    hintKey: "t4_h1",
    interactive: {
      type: "gap-fill",
      sentence: "t4_sent",
      choices: ["t4_c1", "t4_c2", "t4_c3", "t4_c4"],
      correctIndex: 0,
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "sentence-display", words: ["Copilul", "este", "vesel"], highlightIndices: [2], color: "#F97316" },
    hintKey: "t5_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t5_c1", "t5_c2", "t5_c3", "t5_c4"],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t6_title",
    infoText: "t6_text",
    svg: { type: "physics-slingshot", question: "t6_qmain", targets: [
      { id: "t1", text: "t6_t1", isCorrect: true },
      { id: "t2", text: "t6_t2", isCorrect: false },
      { id: "t3", text: "t6_t3", isCorrect: true },
      { id: "t4", text: "t6_t4", isCorrect: false },
      { id: "t5", text: "t6_t5", isCorrect: true },
      { id: "t6", text: "t6_t6", isCorrect: false },
    ] },
    hintKey: "t6_h1",
    interactive: {
      type: "physics-slingshot",
      question: "t6_qmain",
      targets: [
        { id: "t1", text: "t6_t1", isCorrect: true },
        { id: "t2", text: "t6_t2", isCorrect: false },
        { id: "t3", text: "t6_t3", isCorrect: true },
        { id: "t4", text: "t6_t4", isCorrect: false },
        { id: "t5", text: "t6_t5", isCorrect: true },
        { id: "t6", text: "t6_t6", isCorrect: false },
      ],
      instruction: "t6_inst",
      hint1: "t6_h1",
      hint2: "t6_h2",
    },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qb" },
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title",
    infoText: "t7_text",
    svg: { type: "tap-count", tapCount: { emoji: "🌟", count: 2 } },
    hintKey: "t7_h1",
    interactive: {
      type: "tap-count",
      tapCount: { emoji: "🌟", count: 2 },
      instruction: "t7_inst",
      hint1: "t7_h1",
      hint2: "t7_h2",
    },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title",
    infoText: "t8_text",
    svg: { type: "text-bubbles", items: [
      { text: "băiat frumos", color: "#2563EB", bg: "#DBEAFE" },
      { text: "fată frumoasă", color: "#BE185D", bg: "#FCE7F3" },
    ] },
    hintKey: "t8_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t8_w1", "t8_w2", "t8_w3", "t8_w4"],
      correctIndices: [1],
      instruction: "t8_inst",
      hint1: "t8_h1",
      hint2: "t8_h2",
    },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qb" },
  },
  {
    difficulty: "hard",
    infoTitle: "t9_title",
    infoText: "t9_text",
    svg: { type: "icon-grid", items: [
      { emoji: "🧑", label: "frumos - frumoasă" },
      { emoji: "🌼", label: "colorat - colorată" },
      { emoji: "📚", label: "mare - mare" },
      { emoji: "🎈", label: "veseli - vesele" },
    ], bg: "#F9FAFB" },
    hintKey: "t9_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t9_l1", right: "t9_r1" },
        { left: "t9_l2", right: "t9_r2" },
        { left: "t9_l3", right: "t9_r3" },
        { left: "t9_l4", right: "t9_r4" },
      ],
      instruction: "t9_inst",
      hint1: "t9_h1",
      hint2: "t9_h2",
    },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" },
  },
];

export const PRON3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Pronumele personale",

    t1_title: "Cine sunt pronumele?",
    t1_text: "Pronumele înlocuiește un substantiv: eu, tu, el, noi, voi, ei. Ele ne ajută să repetăm mai puține cuvinte.",
    t1_inst: "Atinge doar pronumele din listă.",
    t1_h1: "Privește cu ce înlocuiești un substantiv.",
    t1_h2: "Gândește-te „cine” sau „ce”.",
    t1_w1: "eu",
    t1_w2: "carte",
    t1_w3: "tu",
    t1_w4: "el",
    t1_w5: "noi",
    t1_w6: "masă",
    t1_q: "Care cuvânt este pronume?",
    t1_qa: "tu",
    t1_qb: "carte",
    t1_qc: "masă",
    t1_qd: "copil",

    t2_title: "Pronumele la persoana I",
    t2_text: "Pentru persoana I folosim „eu” când vorbim despre mine și „noi” când vorbim despre grupul din care fac parte.",
    t2_inst: "Potrivește pronumele cu descrierea.",
    t2_h1: "Eu vorbesc, noi învățăm.",
    t2_h2: "Ascultă dacă vorbim despre unul sau mai mulți.",
    t2_l1: "vorbesc",
    t2_r1: "eu",
    t2_l2: "învață",
    t2_r2: "el",
    t2_l3: "învațăm",
    t2_r3: "noi",
    t2_l4: "cântă",
    t2_r4: "voi",
    t2_q: "Care pronume este la persoana I plural?",
    t2_qa: "noi",
    t2_qb: "voi",
    t2_qc: "tu",
    t2_qd: "el",

    t3_title: "Pronumele la persoana a II-a",
    t3_text: "Tu ești persoana a doua. Când ne adresăm unuia, spunem tu.",
    t3_inst: "Lovește doar pronumele care spun „tu”.",
    t3_h1: "Ascultă când ți se spune „tu”.",
    t3_h2: "Tu ești cel căruia i se vorbește.",
    t3_qmain: "Care cuvânt se referă la persoana a doua?",
    t3_t1: "tu",
    t3_t2: "el",
    t3_t3: "voi",
    t3_t4: "mie",
    t3_t5: "ea",
    t3_t6: "noi",
    t3_q: "Care pronume este persoana a doua?",
    t3_qa: "tu",
    t3_qb: "voi",
    t3_qc: "eu",
    t3_qd: "el",

    t4_title: "Pronumele la persoana a III-a",
    t4_text: "„El” și „ea” arată despre cine vorbim când nu suntem noi sau tu.",
    t4_inst: "Potrivește pronumele cu exemplul corect.",
    t4_h1: "El și ea vorbesc despre altcineva.",
    t4_h2: "Ascultă dacă existăm în propoziție.",
    t4_l1: "El citește",
    t4_r1: "el",
    t4_l2: "Ea pleacă",
    t4_r2: "ea",
    t4_l3: "Noi cântăm",
    t4_r3: "noi",
    t4_l4: "Voi mergeți",
    t4_r4: "voi",
    t4_q: "Care este pronume la persoana a treia?",
    t4_qa: "el",
    t4_qb: "noi",
    t4_qc: "tu",
    t4_qd: "voi",

    t5_title: "Pronumele în propoziție",
    t5_text: "Uneori pronumele înlocuiește un substantiv deja spus, ca să nu repetăm.",
    t5_inst: "Completează propoziția cu pronumele cel mai potrivit.",
    t5_h1: "Am spus o poveste despre Ana.",
    t5_h2: "Apoi am spus că ea citește.",
    t5_sent: "Ana are un caiet. ___ citește acum.",
    t5_c1: "Ea",
    t5_c2: "Noi",
    t5_c3: "Tu",
    t5_c4: "El",
    t5_q: "Care pronume înlocuiește numele Ana?",
    t5_qa: "Ea",
    t5_qb: "Tu",
    t5_qc: "Noi",
    t5_qd: "El",

    t6_title: "Pronumele și numărul",
    t6_text: "Pronumele se schimbă dacă vorbim de unul (eu) sau de mai mulți (noi).",
    t6_inst: "Alege pronumele potrivit pentru context.",
    t6_h1: "Eu merg la școală.",
    t6_h2: "Noi mergem împreună.",
    t6_qmain: "Care pronume este la numărul plural?",
    t6_t1: "eu",
    t6_t2: "noi",
    t6_t3: "tu",
    t6_t4: "voi",
    t6_t5: "ei",
    t6_t6: "ea",
    t6_q: "Care pronume indică plural?",
    t6_qa: "eu",
    t6_qb: "noi",
    t6_qc: "tu",
    t6_qd: "el",

    t7_title: "Pronumele și genul",
    t7_text: "În limba română pronumele de persoana a treia sunt masculin (el) sau feminin (ea).",
    t7_inst: "Potrivește pronumele cu genul corespunzător.",
    t7_h1: "El este băiat, ea e fată.",
    t7_h2: "Gândim la cine se referă.",
    t7_l1: "băiat",
    t7_r1: "el",
    t7_l2: "fată",
    t7_r2: "ea",
    t7_l3: "soare",
    t7_r3: "el",
    t7_l4: "lună",
    t7_r4: "ea",
    t7_q: "Care pronume este feminin?",
    t7_qa: "el",
    t7_qb: "ea",
    t7_qc: "tu",
    t7_qd: "noi",

    t8_title: "Pronumele și poziția",
    t8_text: "Pronumele pot fi subiect (eu, tu) sau complement (pe mine, pe tine).",
    t8_inst: "Alege pronumele-subiect.",
    t8_h1: "Eu și tu suntem subiecte.",
    t8_h2: "Pe mine e complement.",
    t8_w1: "eu",
    t8_w2: "pe mine",
    t8_w3: "tu",
    t8_w4: "pe tine",
    t8_q: "Care pronume este subiect?",
    t8_qa: "eu",
    t8_qb: "pe tine",
    t8_qc: "pe mine",
    t8_qd: "el",

    t9_title: "Recapitulare pronume",
    t9_text: "Revizuim ce pronume folosim în fiecare persoană și număr.",
    t9_inst: "Potrivește pronumele cu persoana corectă.",
    t9_h1: "Eu e persoana I, tu persoana a II-a, el/ea persoana a III-a.",
    t9_h2: "Noi și voi sunt plural.",
    t9_l1: "persoana I singular",
    t9_r1: "eu",
    t9_l2: "persoana I plural",
    t9_r2: "noi",
    t9_l3: "persoana a II-a singular",
    t9_r3: "tu",
    t9_l4: "persoana a III-a singular",
    t9_r4: "el/ea",
    t9_q: "Care pronume este persoana I plural?",
    t9_qa: "voi",
    t9_qb: "noi",
    t9_qc: "tu",
    t9_qd: "el",
  },
};

export const PRON3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [
      { text: "eu", color: "#0369A1", bg: "#DBEAFE" },
      { text: "tu", color: "#0EA5E9", bg: "#BFDBFE" },
      { text: "el", color: "#2563EB", bg: "#E0F2FE" },
    ] },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_w1", "t1_w2", "t1_w3", "t1_w4", "t1_w5", "t1_w6"],
      correctIndices: [0, 2, 4],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "sentence-display", words: ["Noi", "cântăm"], color: "#14B8A6" },
    hintKey: "t2_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "icon-grid", items: [
      { emoji: "👩‍🎓", label: "tu" },
      { emoji: "🔊", label: "voi" },
      { emoji: "📖", label: "eu" },
      { emoji: "🌟", label: "el" },
    ] },
    hintKey: "t3_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t3_t1", right: "t3_t1" },
        { left: "t3_t2", right: "t3_t2" },
        { left: "t3_t3", right: "t3_t3" },
        { left: "t3_t4", right: "t3_t4" },
        { left: "t3_t5", right: "t3_t5" },
        { left: "t3_t6", right: "t3_t6" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa", "t3_qb", "t3_qc", "t3_qd"], answer: "t3_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "text-bubbles", items: [
      { text: "El", color: "#7C3AED", bg: "#EDE9FE" },
      { text: "Ea", color: "#C026D3", bg: "#F5D0FE" },
      { text: "Noi", color: "#14B8A6", bg: "#D1FAE5" },
    ] },
    hintKey: "t4_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "pers3", label: "t4_b1" },
        { id: "pers1", label: "t4_b2" },
      ],
      items: [
        { text: "t4_l1", bucketId: "pers3" },
        { text: "t4_l2", bucketId: "pers3" },
        { text: "t4_l3", bucketId: "pers1" },
        { text: "t4_l4", bucketId: "pers3" },
      ],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa", "t4_qb", "t4_qc", "t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "sentence-display", words: ["Ea", "vorbește", "frumos"], color: "#EC4899" },
    hintKey: "t5_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t5_c1", "t5_c2", "t5_c3"],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa", "t5_qb", "t5_qc", "t5_qd"], answer: "t5_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t6_title",
    infoText: "t6_text",
    svg: { type: "sentence-display", words: ["Noi", "mergem", "acasă"], color: "#0EA5E9" },
    hintKey: "t6_h1",
    interactive: {
      type: "physics-slingshot",
      question: "t6_qmain",
      targets: [
        { id: "noi", text: "t6_t2", isCorrect: true },
        { id: "eu", text: "t6_t1", isCorrect: false },
        { id: "voi", text: "t6_t4", isCorrect: true },
        { id: "tu", text: "t6_t3", isCorrect: false },
        { id: "ei", text: "t6_t5", isCorrect: true },
        { id: "ea", text: "t6_t6", isCorrect: false },
      ],
      instruction: "t6_inst",
      hint1: "t6_h1",
      hint2: "t6_h2",
    },
    quiz: { question: "t6_q", choices: ["t6_qa", "t6_qb", "t6_qc", "t6_qd"], answer: "t6_qb" },
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title",
    infoText: "t7_text",
    svg: { type: "icon-grid", items: [
      { emoji: "❤️", label: "tu" },
      { emoji: "💡", label: "el" },
      { emoji: "🎒", label: "noi" },
    ], bg: "#FEF3C7" },
    hintKey: "t7_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t7_l1", right: "t7_r1" },
        { left: "t7_l2", right: "t7_r2" },
        { left: "t7_l3", right: "t7_r3" },
      ],
      instruction: "t7_inst",
      hint1: "t7_h1",
      hint2: "t7_h2",
    },
    quiz: { question: "t7_q", choices: ["t7_qa", "t7_qb", "t7_qc", "t7_qd"], answer: "t7_qb" },
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title",
    infoText: "t8_text",
    svg: { type: "gap-fill", sentence: "t8_sent", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], correctIndex: 0 },
    hintKey: "t8_h1",
    interactive: {
      type: "gap-fill",
      sentence: "t8_sent",
      choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"],
      correctIndex: 0,
      instruction: "t8_inst",
      hint1: "t8_h1",
      hint2: "t8_h2",
    },
    quiz: { question: "t8_q", choices: ["t8_qa", "t8_qb", "t8_qc", "t8_qd"], answer: "t8_qa" },
  },
  {
    difficulty: "hard",
    infoTitle: "t9_title",
    infoText: "t9_text",
    svg: { type: "physics-magnet", pairs: [
      { left: "t9_l1", right: "t9_r1" },
      { left: "t9_l2", right: "t9_r2" },
      { left: "t9_l3", right: "t9_r3" },
      { left: "t9_l4", right: "t9_r4" },
    ] },
    hintKey: "t9_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t9_l1", right: "t9_r1" },
        { left: "t9_l2", right: "t9_r2" },
        { left: "t9_l3", right: "t9_r3" },
        { left: "t9_l4", right: "t9_r4" },
      ],
      instruction: "t9_inst",
      hint1: "t9_h1",
      hint2: "t9_h2",
    },
    quiz: { question: "t9_q", choices: ["t9_qa", "t9_qb", "t9_qc", "t9_qd"], answer: "t9_qa" },
  },
];

export const ORT3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Ortografia — cratima și literele duble",

    t1_title: "Ce este ortografia?",
    t1_text: "Ortografia înseamnă scrierea corectă: litere, cratimă, majusculă și diacritice.",
    t1_inst: "Alege doar cuvintele scrise corect.",
    t1_h1: "Gândește-te la litere.",
    t1_h2: "Ortografia respectă regulile.",
    t1_w1: "casă",
    t1_w2: "casaa",
    t1_w3: "corect",
    t1_w4: "creorct",
    t1_w5: "cratimă",
    t1_w6: "critima",
    t1_q: "Care cuvânt e corect?",
    t1_qa: "casă",
    t1_qb: "casaa",
    t1_qc: "critima",
    t1_qd: "creorct",

    t2_title: "Cratima și legăturile",
    t2_text: "Cratima leagă două cuvinte care formează un singur sens: „spicuiala” devine „spicuială”.",
    t2_inst: "Potrivește expresia corectă cu cratimă.",
    t2_h1: "Cratima unește verbe cu nume.",
    t2_h2: "Fiecare cuvânt are rostul lui.",
    t2_l1: "călători-vorbitori",
    t2_r1: "călătorii vorbitori",
    t2_l2: "copii-zâmbet",
    t2_r2: "copi-zâmbet",
    t2_l3: "omuleți-vorbăreți",
    t2_r3: "omuleți vorbăreți",
    t2_l4: "părinți-imaginați",
    t2_r4: "părinți imaginați",
    t2_q: "Care expresie trebuie să aibă cratimă?",
    t2_qa: "călători-vorbitori",
    t2_qb: "copii zâmbet",
    t2_qc: "omuleți vorbăreți",
    t2_qd: "părinți-imaginați",

    t3_title: "Litera dublă",
    t3_text: "Literele duble apar în cuvinte ca „mâine” sau „carte”. Ele se scriu cu două caractere la rând.",
    t3_inst: "Atinge cuvintele cu litera dublă.",
    t3_h1: "Observă când repetăm litera.",
    t3_h2: "Dublă înseamnă două la rând.",
    t3_l1: "mâine",
    t3_r1: "mâne",
    t3_l2: "carte",
    t3_r2: "caarte",
    t3_l3: "atât",
    t3_r3: "aât",
    t3_l4: "pas",
    t3_r4: "pass",
    t3_q: "Care cuvânt are literă dublă?",
    t3_qa: "mâine",
    t3_qb: "pas",
    t3_qc: "carte",
    t3_qd: "atât",

    t4_title: "Majusculele",
    t4_text: "La începutul propoziției scriem literă mare; e și cazul numelor proprii.",
    t4_inst: "Selectează propozițiile corecte.",
    t4_h1: "Vezi unde începe o propoziție.",
    t4_h2: "Numele se scriu cu majusculă.",
    t4_l1: "Ana pleacă.",
    t4_r1: "corect",
    t4_l2: "ana pleacă.",
    t4_r2: "gresit",
    t4_l3: "București este capitala.",
    t4_r3: "corect",
    t4_l4: "bucurești e mare.",
    t4_r4: "gresit",
    t4_q: "Care propoziție e corectă?",
    t4_qa: "Ana pleacă.",
    t4_qb: "ana pleacă.",
    t4_qc: "bucurești e mare.",
    t4_qd: "București este capitala.",

    t5_title: "Diacriticele",
    t5_text: "Diacriticele (Ă, Â, Î, Ș, Ț) schimbă sunetul cuvântului: `fata` și `fată` nu sunt același lucru.",
    t5_inst: "Potrivește cuvintele cu diacritice cu forma corectă.",
    t5_h1: "Ascultă sunetul.",
    t5_h2: "Diacriticele sunt importante.",
    t5_l1: "fată",
    t5_r1: "fata",
    t5_l2: "țară",
    t5_r2: "tara",
    t5_l3: "cărți",
    t5_r3: "carti",
    t5_l4: "știre",
    t5_r4: "stire",
    t5_q: "Care pereche arată forma corectă?",
    t5_qa: "fată - fata",
    t5_qb: "țară - tara",
    t5_qc: "cărți - carti",
    t5_qd: "știre - stire",

    t6_title: "Punctuația corectă",
    t6_text: "Punctul, semnul întrebării și virgula trebuie puse la locul lor.",
    t6_inst: "Alege semnul potrivit pentru propoziție.",
    t6_h1: "Gândește-te la sens.",
    t6_h2: "Semnul schimbă tonul propoziției.",
    t6_qmain: "Ce semn merge la final?",
    t6_t1: ".",
    t6_t2: "?",
    t6_t3: "!",
    t6_t4: ",",
    t6_t5: ".",
    t6_t6: "?",
    t6_q: "Ce semn e corect pentru „Vrei să mergem”?",
    t6_qa: ".",
    t6_qb: "?",
    t6_qc: "!",
    t6_qd: ",",

    t7_title: "Spațiile între cuvinte",
    t7_text: "Scriem spații între cuvinte, dar nu între literele unui cuvânt.",
    t7_inst: "Potrivește grupurile de cuvinte.",
    t7_h1: "Vorbim despre două cuvinte.",
    t7_h2: "Cuvintele separate primesc spațiu.",
    t7_l1: "a merge",
    t7_r1: "corect",
    t7_l2: "amerg e",
    t7_r2: "gresit",
    t7_l3: "frumoasă floare",
    t7_r3: "corect",
    t7_l4: "frumoasăfloare",
    t7_r4: "gresit",
    t7_q: "Care grup e scris corect?",
    t7_qa: "a merge",
    t7_qb: "amerg e",
    t7_qc: "frumoasăfloare",
    t7_qd: "frumoasă floare",

    t8_title: "Repetarea literelor",
    t8_text: "Unele cuvinte au litere repetate ca „fund” sau „muncă”. Le învățăm prin comparație.",
    t8_inst: "Alege cuvântul corect.",
    t8_h1: "Observă literele duble.",
    t8_h2: "Fii atent la pronunție.",
    t8_w1: "fund",
    t8_w2: "funt",
    t8_w3: "muncă",
    t8_w4: "muncaa",
    t8_q: "Care cuvânt e scris corect?",
    t8_qa: "fund",
    t8_qb: "funt",
    t8_qc: "muncaa",
    t8_qd: "muncă",

    t9_title: "Recapitulare ortografie",
    t9_text: "Revedem cratima, majuscula, diacriticele și literele duble într-o recapitulare finală.",
    t9_inst: "Lovește doar variantele corecte.",
    t9_h1: "Trecem tot ce am învățat.",
    t9_h2: "Fiecare alegere are sens.",
    t9_l1: "călători-vorbitori",
    t9_r1: "corect",
    t9_l2: "fată",
    t9_r2: "corect",
    t9_l3: "Roșii",
    t9_r3: "corect",
    t9_l4: "funt",
    t9_r4: "gresit",
    t9_q: "Care combinație e corectă?",
    t9_qa: "călători-vorbitori - corect",
    t9_qb: "funt - corect",
    t9_qc: "Roșii - greșit",
    t9_qd: "fată - greșit",
  },
};

export const ORT3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [
      { text: "casă", color: "#22C55E", bg: "#DCFCE7" },
      { text: "cris", color: "#047857", bg: "#D1FAE5" },
      { text: "cratimă", color: "#0F766E", bg: "#99F6E4" },
    ] },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_w1", "t1_w2", "t1_w3", "t1_w4", "t1_w5", "t1_w6"],
      correctIndices: [0, 2, 4],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa","t1_qb","t1_qc","t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "drag-to-bucket", buckets: [
      { id: "split", label: "t2_b1" },
      { id: "single", label: "t2_b2" },
    ], items: [
      { text: "t2_l1", bucketId: "split" },
      { text: "t2_l2", bucketId: "split" },
      { text: "t2_l3", bucketId: "split" },
      { text: "t2_l4", bucketId: "split" },
      { text: "t2_l1", bucketId: "split" },
      { text: "t2_l4", bucketId: "single" },
    ] },
    hintKey: "t2_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "split", label: "t2_b1" },
        { id: "single", label: "t2_b2" },
      ],
      items: [
        { text: "t2_l1", bucketId: "split" },
        { text: "t2_l2", bucketId: "split" },
        { text: "t2_l3", bucketId: "split" },
        { text: "t2_l4", bucketId: "split" },
        { text: "t2_l1", bucketId: "split" },
        { text: "t2_l4", bucketId: "single" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa","t2_qb","t2_qc","t2_qd"], answer: "t2_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "icon-grid", items: [
      { emoji: "✍️", label: "mâine" },
      { emoji: "📚", label: "carte" },
      { emoji: "🎩", label: "căpătat" },
    ] },
    hintKey: "t3_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t3_l1", right: "t3_r1" },
        { left: "t3_l2", right: "t3_r2" },
        { left: "t3_l3", right: "t3_r3" },
        { left: "t3_l4", right: "t3_r4" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa","t3_qb","t3_qc","t3_qd"], answer: "t3_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "text-bubbles", items: [
      { text: "Ana", color: "#BE185D", bg: "#FCE7F3" },
      { text: "pleacă", color: "#EA580C", bg: "#FED7AA" },
      { text: "acasă", color: "#059669", bg: "#DCfCE7" },
    ] },
    hintKey: "t4_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t4_l1", "t4_l2", "t4_l3", "t4_l4"],
      correctIndices: [0,2],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa","t4_qb","t4_qc","t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "sentence-display", words: ["Ea", "citește", "o", "carte"], highlightIndices: [1], color: "#0EA5E9" },
    hintKey: "t5_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t5_c1","t5_c2","t5_c3","t5_c4"],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa","t5_qb","t5_qc","t5_qd"], answer: "t5_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t6_title",
    infoText: "t6_text",
    svg: { type: "gap-fill", sentence: "t6_sent", choices: ["t6_qa","t6_qb","t6_qc","t6_qd"], correctIndex: 1 },
    hintKey: "t6_h1",
    interactive: {
      type: "gap-fill",
      sentence: "t6_sent",
      choices: ["t6_qa","t6_qb","t6_qc","t6_qd"],
      correctIndex: 1,
      instruction: "t6_inst",
      hint1: "t6_h1",
      hint2: "t6_h2",
    },
    quiz: { question: "t6_q", choices: ["t6_qa","t6_qb","t6_qc","t6_qd"], answer: "t6_qb" },
  },
  {
    difficulty: "easy",
    infoTitle: "t7_title",
    infoText: "t7_text",
    svg: { type: "sentence-display", words: ["Fetele", "sunt", "veseli"], highlightIndices: [0], color: "#14B8A6" },
    hintKey: "t7_h1",
    interactive: {
      type: "tap-count",
      tapCount: { emoji: "👏", count: 2 },
      instruction: "t7_inst",
      hint1: "t7_h1",
      hint2: "t7_h2",
    },
    quiz: { question: "t7_q", choices: ["t7_qa","t7_qb","t7_qc","t7_qd"], answer: "t7_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t8_title",
    infoText: "t8_text",
    svg: { type: "text-bubbles", items: [
      { text: "Roșii", color: "#DC2626", bg: "#FEE2E2" },
      { text: "roșii", color: "#EA580C", bg: "#FED7AA" },
      { text: "Roșie", color: "#BE185D", bg: "#FCE7F3" },
    ] },
    hintKey: "t8_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t8_w1","t8_w2","t8_w3","t8_w4"],
      correctIndices: [0,3],
      instruction: "t8_inst",
      hint1: "t8_h1",
      hint2: "t8_h2",
    },
    quiz: { question: "t8_q", choices: ["t8_qa","t8_qb","t8_qc","t8_qd"], answer: "t8_qa" },
  },
  {
    difficulty: "hard",
    infoTitle: "t9_title",
    infoText: "t9_text",
    svg: { type: "physics-magnet", pairs: [
      { left: "t9_l1", right: "t9_r1" },
      { left: "t9_l2", right: "t9_r2" },
      { left: "t9_l3", right: "t9_r3" },
      { left: "t9_l4", right: "t9_r4" },
    ] },
    hintKey: "t9_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t9_l1", right: "t9_r1" },
        { left: "t9_l2", right: "t9_r2" },
        { left: "t9_l3", right: "t9_r3" },
        { left: "t9_l4", right: "t9_r4" },
      ],
      instruction: "t9_inst",
      hint1: "t9_h1",
      hint2: "t9_h2",
    },
    quiz: { question: "t9_q", choices: ["t9_qa","t9_qb","t9_qc","t9_qd"], answer: "t9_qa" },
  },
];

export const PROP3_LABELS: Record<string, Record<string, string>> = {
  ro: {
    explorer_title: "Propoziția dezvoltată",

    t1_title: "Ce este propoziția?",
    t1_text: "Propoziția spune un gând complet: are subiect, predicat și, uneori, completări.",
    t1_inst: "Alege propozițiile complete.",
    t1_h1: "Caută subiect și predicat.",
    t1_h2: "Vezi dacă exprimă un gând întreg.",
    t1_l1: "Ana citește.",
    t1_r1: "corect",
    t1_l2: "Alergăm.",
    t1_r2: "corect",
    t1_l3: "Cartea mare.",
    t1_r3: "incomplet",
    t1_l4: "Sări.",
    t1_r4: "incomplet",
    t1_q: "Care propoziție are subiect și predicat?",
    t1_qa: "Ana citește.",
    t1_qb: "Cartea mare.",
    t1_qc: "Sări.",
    t1_qd: "Mere roșii",

    t2_title: "Subiectul și predicatul",
    t2_text: "Subiectul spune cine sau ce, predicatul spune ce face subiectul.",
    t2_inst: "Pune fiecare propoziție în categoria potrivită.",
    t2_h1: "Observă cine face acțiunea.",
    t2_h2: "Predicatul e verbul.",
    t2_b1: "Subiect",
    t2_b2: "Predicat",
    t2_i1: "Ana",
    t2_i2: "citește",
    t2_i3: "Mihai",
    t2_i4: "aleargă",
    t2_i5: "Cartea",
    t2_i6: "este",
    t2_q: "Ce este subiect?",
    t2_qa: "Ana",
    t2_qb: "citește",
    t2_qc: "aleargă",
    t2_qd: "este",

    t3_title: "Completarea",
    t3_text: "Completările adaugă detalii: locul, timpul sau motivul ",
    t3_inst: "Alege completarea potrivită.",
    t3_h1: "Întreabă „unde” sau „când”.",
    t3_h2: "Propoziția devine mai clară.",
    t3_sent: "Ana citește ___.",
    t3_c1: "o carte",
    t3_c2: "alergă",
    t3_c3: "frumos",
    t3_c4: "repede",
    t3_q: "Ce completează propoziția?",
    t3_qa: "o carte",
    t3_qb: "alergă",
    t3_qc: "frumos",
    t3_qd: "repede",

    t4_title: "Ordinea cuvintelor",
    t4_text: "Subiectul vine înainte și predicatul după el, dar completările pot fi la început sau sfârșit.",
    t4_inst: "Rearanjează fragmentele.",
    t4_h1: "Începe cu subiectul.",
    t4_h2: "Predicatul spune ce se întâmplă.",
    t4_f1: "Mara",
    t4_f2: "citește",
    t4_f3: "o poveste",
    t4_f4: "frumos",
    t4_q: "Care ordine e corectă?",
    t4_qa: "Mara citește o poveste frumos.",
    t4_qb: "citește Mara o poveste frumos.",
    t4_qc: "o poveste citește Mara frumos.",
    t4_qd: "frumos Mara citește o poveste.",

    t5_title: "Pronumele în propoziție",
    t5_text: "Pronumele pot înlocui subiectul: „Ana” devine „ea”.",
    t5_inst: "Potrivește pronumele cu propoziția.",
    t5_h1: "Fii atent la persoană.",
    t5_h2: "Pronumele înlocuiește subiectul deja spus.",
    t5_l1: "Ana merge",
    t5_r1: "ea",
    t5_l2: "Noi cântăm",
    t5_r2: "noi",
    t5_l3: "Tu citești",
    t5_r3: "tu",
    t5_l4: "El scrie",
    t5_r4: "el",
    t5_q: "Ce pronume înlocuiește „Ana”?",
    t5_qa: "ea",
    t5_qb: "noi",
    t5_qc: "tu",
    t5_qd: "el",

    t6_title: "Adjectivul în propoziție",
    t6_text: "Adjectivele descriu subiectul: „copil vesel”, „fată frumoasă”.",
    t6_inst: "Completează cu adjectivul potrivit.",
    t6_h1: "Adjectivul urmează subiectul.",
    t6_h2: "Se potrivește în gen și număr.",
    t6_sent: "Elevul ___ citește.",
    t6_c1: "vesel",
    t6_c2: "frumoasă",
    t6_c3: "veseli",
    t6_c4: "frumos",
    t6_q: "Ce adjectiv se potrivește?",
    t6_qa: "vesel",
    t6_qb: "frumoasă",
    t6_qc: "veseli",
    t6_qd: "frumos",

    t7_title: "Propoziția cu mai multe verburi",
    t7_text: "Unele propoziții au mai multe verbe: „Ana citește și scrie”.",
    t7_inst: "Alege propozițiile cu două verbe.",
    t7_h1: "Privește fiecare verb.",
    t7_h2: "Gândește-te dacă apar două acțiuni.",
    t7_w1: "citește",
    t7_w2: "scrie",
    t7_w3: "aleargă",
    t7_w4: "cântă",
    t7_q: "Care propoziție are două verbe?",
    t7_qa: "Ana citește și scrie.",
    t7_qb: "Ana citește.",
    t7_qc: "Cântă frumos.",
    t7_qd: "Alergă repede.",

    t8_title: "Propoziția dezvoltă detaliul",
    t8_text: "Adăugăm detalii despre loc, timp sau cum se desfășoară acțiunea.",
    t8_inst: "Potrivește detaliile cu propoziția corectă.",
    t8_h1: "Întreabă unde și când.",
    t8_h2: "Detaliile fac propoziția mai clară.",
    t8_l1: "Mâine, Ana pleacă la școală.",
    t8_r1: "corect",
    t8_l2: "Ana pleacă mâine, la școală.",
    t8_r2: "corect",
    t8_l3: "Ana pleacă la mâine școală.",
    t8_r3: "gresit",
    t8_q: "Care parte e detaliu de timp?",
    t8_qa: "Mâine",
    t8_qb: "Ana",
    t8_qc: "pleacă",
    t8_qd: "la școală",

    t9_title: "Recapitulare propoziție",
    t9_text: "Revedem subiectul, predicatul și detaliile în propoziția dezvoltată.",
    t9_inst: "Potrivește rolul fiecărui fragment.",
    t9_h1: "Caută subiectul și predicatul.",
    t9_h2: "Vezi unde e detaliul.",
    t9_l1: "Subiect",
    t9_r1: "Ana",
    t9_l2: "Predicat",
    t9_r2: "citește",
    t9_l3: "Detaliu timp",
    t9_r3: "mâine",
    t9_l4: "Detaliu loc",
    t9_r4: "la școală",
    t9_q: "Ce rol are cuvântul „mâine”?",
    t9_qa: "detaliu",
    t9_qb: "subiect",
    t9_qc: "predicat",
    t9_qd: "verbe",
  },
};

export const PROP3_POOL: PoolTopicDef[] = [
  {
    difficulty: "easy",
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: { type: "text-bubbles", items: [
      { text: "Ana", color: "#EC4899", bg: "#FCE7F3" },
      { text: "citește", color: "#0EA5E9", bg: "#BFDBFE" },
      { text: "o carte", color: "#047857", bg: "#D1FAE5" },
    ] },
    hintKey: "t1_h1",
    interactive: {
      type: "highlight-text",
      tokens: ["t1_l1", "t1_r1", "t1_l2", "t1_r2", "t1_l3", "t1_r3"],
      correctIndices: [0, 1, 2],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: { question: "t1_q", choices: ["t1_qa", "t1_qb", "t1_qc", "t1_qd"], answer: "t1_qa" },
  },
  {
    difficulty: "easy",
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: { type: "match-pairs", pairs: [
      { left: "t2_l1", right: "t2_r1" },
      { left: "t2_l2", right: "t2_r2" },
      { left: "t2_l3", right: "t2_r3" },
      { left: "t2_l4", right: "t2_r4" },
    ] },
    hintKey: "t2_h1",
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: { question: "t2_q", choices: ["t2_qa", "t2_qb", "t2_qc", "t2_qd"], answer: "t2_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: { type: "icon-grid", items: [
      { emoji: "🕒", label: "mâine" },
      { emoji: "📍", label: "la școală" },
      { emoji: "🛌", label: "acasă" },
    ] },
    hintKey: "t3_h1",
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "timp", label: "t3_b1" },
        { id: "loc", label: "t3_b2" },
      ],
      items: [
        { text: "t3_w1", bucketId: "timp" },
        { text: "t3_w2", bucketId: "loc" },
        { text: "t3_w3", bucketId: "timp" },
        { text: "t3_w4", bucketId: "loc" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: { question: "t3_q", choices: ["t3_qa","t3_qb","t3_qc","t3_qd"], answer: "t3_qa" },
  },
  {
    difficulty: "medium",
    infoTitle: "t4_title",
    infoText: "t4_text",
    svg: { type: "sentence-display", words: ["Ana", "citește", "o", "carte"], highlightIndices: [0,1], color: "#14B8A6" },
    hintKey: "t4_h1",
    interactive: {
      type: "sentence-build",
      fragments: ["t4_f1","t4_f2","t4_f3","t4_f4"],
      instruction: "t4_inst",
      hint1: "t4_h1",
      hint2: "t4_h2",
    },
    quiz: { question: "t4_q", choices: ["t4_qa","t4_qb","t4_qc","t4_qd"], answer: "t4_qa" },
  },
  {
    difficulty: "hard",
    infoTitle: "t5_title",
    infoText: "t5_text",
    svg: { type: "physics-magnet", pairs: [
      { left: "t5_l1", right: "t5_r1" },
      { left: "t5_l2", right: "t5_r2" },
      { left: "t5_l3", right: "t5_r3" },
      { left: "t5_l4", right: "t5_r4" },
    ] },
    hintKey: "t5_h1",
    interactive: {
      type: "physics-magnet",
      pairs: [
        { left: "t5_l1", right: "t5_r1" },
        { left: "t5_l2", right: "t5_r2" },
        { left: "t5_l3", right: "t5_r3" },
        { left: "t5_l4", right: "t5_r4" },
      ],
      instruction: "t5_inst",
      hint1: "t5_h1",
      hint2: "t5_h2",
    },
    quiz: { question: "t5_q", choices: ["t5_qa","t5_qb","t5_qc","t5_qd"], answer: "t5_qa" },
  },
];

export const TEXT3D_LABELS = mkLabels("Textul descriptiv", "Descriptive Text", "Leíró szöveg", "Beschreibender Text");
export const TEXT3D_POOL = mkPool("#10B981");

export const TEXT3N_LABELS = mkLabels("Textul narativ C3", "Narrative Text C3", "Elbeszélő szöveg C3", "Erzähltext K3");
export const TEXT3N_POOL = mkPool("#34D399");

export const RECAP3_LABELS = mkLabels("Recapitulare C3", "Review C3", "Összefoglalás C3", "Wiederholung C3");
export const RECAP3_POOL = mkPool("#10B981");
