// Registry of the per-country "Top 50 Sehenswürdigkeiten" SEO hub pages
// (static HTML under public/<localized-slug>/, generated by
// scripts/build-country-sights.mts). Used to WIRE the otherwise-orphan hubs
// into the crawl graph: the country page links here, the sitemap lists them,
// and (later) the listed POIs link back. A hub that nothing links to and that
// is absent from the sitemap cannot rank — discovery + internal links are as
// important as the content itself.
//
// countryId -> { lang: localized-root-slug }. Add an entry here the moment a
// new hub is generated so it gets linked + sitemapped automatically.

export type HubLang = "de" | "hu" | "ro" | "en";

export const SIGHTS_HUBS: Record<string, Partial<Record<HubLang, string>>> = {
  croatia: {
    de: "kroatien-sehenswuerdigkeiten",
    hu: "horvatorszag-latnivalok",
    ro: "croatia-obiective-turistice",
    en: "croatia-attractions",
  },
};

// Localized label for the inbound link rendered on the country page.
export const SIGHTS_HUB_LABEL: Record<HubLang, string> = {
  de: "Die Top 50 Sehenswürdigkeiten",
  hu: "A top 50 látnivaló",
  ro: "Top 50 obiective turistice",
  en: "The Top 50 Attractions",
};

export function sightsHubSlug(countryId: string, lang: string): string | null {
  return SIGHTS_HUBS[countryId]?.[lang as HubLang] ?? null;
}
