// AUTO-GENERATED by plizio_orch/_build_hub_wiring.py from public/data/_hub_manifest.json.
// Registry of the per-country "Top 50 Sehenswürdigkeiten" SEO hub pages (static HTML
// under public/<localized-slug>/). Wires the otherwise-orphan hubs into the crawl graph:
// the country page links here + the sitemap lists them. Re-run the wiring script after
// generating new hubs (scripts/build-country-sights.mts).

export type HubLang = "de" | "hu" | "ro" | "en";

export const SIGHTS_HUBS: Record<string, Partial<Record<HubLang, string>>> = {
  "croatia": { de: "kroatien-sehenswuerdigkeiten", hu: "horvatorszag-latnivalok", ro: "croatia-obiective-turistice", en: "croatia-attractions" },
  "germany": { de: "deutschland-sehenswuerdigkeiten", hu: "nemetorszag-latnivalok", ro: "germania-obiective-turistice", en: "germany-attractions" },
  "austria": { de: "oesterreich-sehenswuerdigkeiten", hu: "ausztria-latnivalok", ro: "austria-obiective-turistice", en: "austria-attractions" },
  "switzerland": { de: "schweiz-sehenswuerdigkeiten", hu: "svajc-latnivalok", ro: "elvetia-obiective-turistice", en: "switzerland-attractions" },
  "france": { de: "frankreich-sehenswuerdigkeiten", hu: "franciaorszag-latnivalok", ro: "franta-obiective-turistice", en: "france-attractions" },
  "italy": { de: "italien-sehenswuerdigkeiten", hu: "olaszorszag-latnivalok", ro: "italia-obiective-turistice", en: "italy-attractions" },
  "spain": { de: "spanien-sehenswuerdigkeiten", hu: "spanyolorszag-latnivalok", ro: "spania-obiective-turistice", en: "spain-attractions" },
  "portugal": { de: "portugal-sehenswuerdigkeiten", hu: "portugalia-latnivalok", ro: "portugalia-obiective-turistice", en: "portugal-attractions" },
  "netherlands": { de: "niederlande-sehenswuerdigkeiten", hu: "hollandia-latnivalok", ro: "tarile-de-jos-obiective-turistice", en: "netherlands-attractions" },
  "belgium": { de: "belgien-sehenswuerdigkeiten", hu: "belgium-latnivalok", ro: "belgia-obiective-turistice", en: "belgium-attractions" },
  "greece": { de: "griechenland-sehenswuerdigkeiten", hu: "goeroegorszag-latnivalok", ro: "grecia-obiective-turistice", en: "greece-attractions" },
  "poland": { de: "polen-sehenswuerdigkeiten", hu: "lengyelorszag-latnivalok", ro: "polonia-obiective-turistice", en: "poland-attractions" },
  "czech-republic": { de: "tschechien-sehenswuerdigkeiten", hu: "csehorszag-latnivalok", ro: "cehia-obiective-turistice", en: "czechia-attractions" },
  "hungary": { de: "ungarn-sehenswuerdigkeiten", hu: "magyarorszag-latnivalok", ro: "ungaria-obiective-turistice", en: "hungary-attractions" },
  "romania": { de: "rumaenien-sehenswuerdigkeiten", hu: "romania-latnivalok", ro: "romania-obiective-turistice", en: "romania-attractions" },
  "ireland": { de: "irland-sehenswuerdigkeiten", hu: "irorszag-latnivalok", ro: "irlanda-obiective-turistice", en: "ireland-attractions" },
  "slovenia": { de: "slowenien-sehenswuerdigkeiten", hu: "szlovenia-latnivalok", ro: "slovenia-obiective-turistice", en: "slovenia-attractions" },
  "slovakia": { de: "slowakei-sehenswuerdigkeiten", hu: "szlovakia-latnivalok", ro: "slovacia-obiective-turistice", en: "slovakia-attractions" },
};

export const SIGHTS_HUB_LABEL: Record<HubLang, string> = {
  de: "Die Top 50 Sehenswürdigkeiten",
  hu: "A top 50 látnivaló",
  ro: "Top 50 obiective turistice",
  en: "The Top 50 Attractions",
};

export function sightsHubSlug(countryId: string, lang: string): string | null {
  return SIGHTS_HUBS[countryId]?.[lang as HubLang] ?? null;
}
