import type { ExplorerDef } from "@/app/astro-biologie/games/ExplorerEngine";

export const G1_COUNTING_DEF: ExplorerDef = {
  labels: {}, // Data will be migrated here
  title: "explorer_title",
  icon: "🔢",
  topics: [], // Topics data
  rounds: []
};

export const G1_ADDSUB_DEF: ExplorerDef = {
  labels: {},
  title: "explorer_title",
  icon: "➕",
  topics: [],
  rounds: []
};

// ... other defs will go here
// ─── PATTERNEXPLORER CONFIG ───

const PATTERNEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    // Explorer meta
    explorer_title: "Data & Patterns Explorer",
    // Topic 1: Reading data (tally charts)
    t1_title: "Reading Data from Tables",
    t1_text: "A table or chart helps us count and organize information. We use tally marks (||||) to count objects. Then we add up all the tallies to find the total!",
    t1_b1: "Tally marks help us count in groups of 5",
    t1_b2: "Each group of 5 is marked with a line through 4",
    t1_b3: "Add up the groups to find the total",
    t1_inst: "Count the tallies and combine the groups!",
    t1_h1: "Count: 4 apples, 3 bananas, 2 grapes",
    t1_h2: "Total: 4 + 3 + 2 = 9 fruits",
    t1_q: "In the chart, which fruit is the favorite?",
    t1_q_apples: "Apples (4)",
    t1_q_bananas: "Bananas (3)",
    t1_q_grapes: "Grapes (2)",
    t1_q_all: "All equal",
    svg_tally_total: "Total: 4 + 3 + 2 = 9 fruits",
    svg_tally_fav: "The favorite is apples (4 tally marks)",
    // Topic 2: Number sequences & patterns
    t2_title: "Number Sequences & Patterns",
    t2_text: "A pattern is a sequence of numbers or objects that follows a rule. We can find the rule by looking at how numbers change: +2, -1, ×2, etc. Once we know the rule, we can find the next number!",
    t2_b1: "Look for what changes from one number to the next",
    t2_b2: "Apply the same rule again to find the next number",
    t2_b3: "Patterns help us predict what comes next",
    t2_inst: "Tap the number where the pattern 2, 4, 6, 8 lands next!",
    t2_h1: "The pattern adds 2 each time: 2→4→6→8→?",
    t2_h2: "8 + 2 = 10 — tap number 10!",
    t2_q: "What comes next: 5, 10, 15, __?",
    t2_q_18: "18",
    t2_q_20: "20",
    t2_q_25: "25",
    t2_q_16: "16",
    svg_seq_rule: "Pattern Rule: Add 2 each time",
    svg_seq_next: "What comes next after 8?",
    // Topic 3: Sorting & classifying
    t3_title: "Sorting and Classifying Objects",
    t3_text: "We can sort objects into groups by different properties: color, size, shape, or type. When we sort, we organize things to make counting easier. We can count each group separately, then add them together!",
    t3_b1: "Choose a property to sort by (color, size, shape)",
    t3_b2: "Count each group separately",
    t3_b3: "Add the groups together to find the total",
    t3_inst: "Count the circles and combine them by size!",
    t3_h1: "Count: 3 big circles, 4 small circles",
    t3_h2: "Total: 3 + 4 = 7 circles",
    t3_q: "Sort by shape: how many circles? 🔵🔵🟢🔵🟢🔵",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_2: "2",
    t3_q_5: "5",
    svg_sort_big: "Big",
    svg_sort_3big: "3 big",
    svg_sort_small: "Small",
    svg_sort_4small: "4 small",
    svg_sort_total: "Total: 3 + 4 = 7 circles",
  },
  de: {
    explorer_title: "Daten & Muster entdecken",
    t1_title: "Daten aus Tabellen lesen",
    t1_text: "Eine Tabelle oder ein Diagramm hilft uns, Informationen zu zählen und zu organisieren. Wir verwenden Strichmarkierungen (||||), um Gegenstände zu zählen. Dann addieren wir alle Markierungen, um die Gesamtzahl zu finden!",
    t1_b1: "Strichmarkierungen helfen uns in Gruppen von 5 zu zählen",
    t1_b2: "Jede Gruppe von 5 wird mit einer Linie durch 4 gekennzeichnet",
    t1_b3: "Addiere die Gruppen, um die Gesamtzahl zu finden",
    t1_inst: "Zähle die Markierungen und kombiniere die Gruppen!",
    t1_h1: "Zähle: 4 Äpfel, 3 Bananen, 2 Trauben",
    t1_h2: "Gesamt: 4 + 3 + 2 = 9 Früchte",
    t1_q: "Welche Frucht ist in der Tabelle das Lieblingsobst?",
    t1_q_apples: "Äpfel (4)",
    t1_q_bananas: "Bananen (3)",
    t1_q_grapes: "Trauben (2)",
    t1_q_all: "Alle gleich",
    svg_tally_total: "Gesamt: 4 + 3 + 2 = 9 Früchte",
    svg_tally_fav: "Der Favorit sind Äpfel (4 Striche)",
    t2_title: "Zahlenfolgen & Muster",
    t2_text: "Ein Muster ist eine Folge von Zahlen oder Objekten, die einer Regel folgt. Wir können die Regel finden, indem wir schauen, wie sich Zahlen ändern: +2, -1, ×2 usw. Wenn wir die Regel kennen, können wir die nächste Zahl finden!",
    t2_b1: "Schau, was sich von einer Zahl zur nächsten ändert",
    t2_b2: "Wende die gleiche Regel wieder an, um die nächste Zahl zu finden",
    t2_b3: "Muster helfen uns vorherzusagen, was kommt",
    t2_inst: "Tippe auf die Zahl, wo die Zahlenfolge 2, 4, 6, 8 weitergeht!",
    t2_h1: "Das Muster addiert jedes Mal 2: 2→4→6→8→?",
    t2_h2: "8 + 2 = 10 — tippe auf die 10!",
    t2_q: "Was kommt als nächstes: 5, 10, 15, __?",
    t2_q_18: "18",
    t2_q_20: "20",
    t2_q_25: "25",
    t2_q_16: "16",
    svg_seq_rule: "Musterregel: Jedes Mal +2",
    svg_seq_next: "Was kommt nach der 8?",
    t3_title: "Objekte sortieren und klassifizieren",
    t3_text: "Wir können Objekte nach verschiedenen Eigenschaften in Gruppen sortieren: Farbe, Größe, Form oder Typ. Wenn wir sortieren, organisieren wir Dinge, um das Zählen leichter zu machen. Wir können jede Gruppe einzeln zählen und dann addieren!",
    t3_b1: "Wähle eine Eigenschaft zum Sortieren (Farbe, Größe, Form)",
    t3_b2: "Zähle jede Gruppe einzeln",
    t3_b3: "Addiere die Gruppen, um die Gesamtzahl zu finden",
    t3_inst: "Zähle die Kreise und kombiniere sie nach Größe!",
    t3_h1: "Zähle: 3 große Kreise, 4 kleine Kreise",
    t3_h2: "Gesamt: 3 + 4 = 7 Kreise",
    t3_q: "Sortiere nach Form: wie viele Kreise? 🔵🔵🟢🔵🟢🔵",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_2: "2",
    t3_q_5: "5",
    svg_sort_big: "Groß",
    svg_sort_3big: "3 große",
    svg_sort_small: "Klein",
    svg_sort_4small: "4 kleine",
    svg_sort_total: "Gesamt: 3 + 4 = 7 Kreise",
  },
  hu: {
    explorer_title: "Adatok & Minták felfedezés",
    t1_title: "Adatok olvasása táblázatokból",
    t1_text: "Egy táblázat vagy grafikon segít számolni és információkat szervezni. A vonásjegyeket (||||) használjuk tárgyak számlálásához. Aztán összeadjuk az összes vonást, hogy megtaláljuk az összeget!",
    t1_b1: "A vonásjegyek 5-ös csoportokra segítik a számlálást",
    t1_b2: "Minden 5-ös csoport egy vonalon keresztül van megjelölve",
    t1_b3: "Add össze a csoportokat az összesen megtalálásához",
    t1_inst: "Számold a vonásokat és kombinálj csoportokat!",
    t1_h1: "Számolás: 4 alma, 3 banán, 2 szőlő",
    t1_h2: "Összesen: 4 + 3 + 2 = 9 gyümölcs",
    t1_q: "A táblázatban melyik gyümölcs a kedvenc?",
    t1_q_apples: "Alma (4)",
    t1_q_bananas: "Banán (3)",
    t1_q_grapes: "Szőlő (2)",
    t1_q_all: "Mindegyik egyenlő",
    svg_tally_total: "Összesen: 4 + 3 + 2 = 9 gyümölcs",
    svg_tally_fav: "A kedvenc az alma (4 vonás)",
    t2_title: "Számsorozatok & Minták",
    t2_text: "A minta egy olyan számsor vagy objektumsor, amely egy szabályt követi. Meg tudjuk találni a szabályt, ha megnézzük hogyan változnak a számok: +2, -1, ×2 stb. Amikor ismerjük a szabályt, meg tudjuk találni a következő számot!",
    t2_b1: "Nézd meg, mi változik egyik számról a másikra",
    t2_b2: "Alkalmaz ugyanezt a szabályt, hogy megtaláld a következő számot",
    t2_b3: "A minták segíteni fognak megjósolni, hogy mi jön",
    t2_inst: "Koppints arra a számra, ahol a 2, 4, 6, 8 minta folytatódik!",
    t2_h1: "A minta minden alkalommal 2-t ad: 2→4→6→8→?",
    t2_h2: "8 + 2 = 10 — koppints a 10-re!",
    t2_q: "Mi jön következő: 5, 10, 15, __?",
    t2_q_18: "18",
    t2_q_20: "20",
    t2_q_25: "25",
    t2_q_16: "16",
    svg_seq_rule: "Minta szabály: Minden alkalommal +2",
    svg_seq_next: "Mi jön a 8 után?",
    t3_title: "Tárgyak szortírozása és besorolása",
    t3_text: "Tárgyakat különféle tulajdonságok szerint csoportosíthatunk: szín, méret, forma vagy típus. Amikor szortírozunk, rendszereztük a dolgokat, hogy könnyebb legyen a számlálás. Minden csoportot külön számlálhatunk, majd összeadhatjuk!",
    t3_b1: "Válassz egy tulajdonságot szortírózáshoz (szín, méret, forma)",
    t3_b2: "Számold meg minden csoportot külön",
    t3_b3: "Add össze a csoportokat az összes megtalálásához",
    t3_inst: "Számold a köröket és kombinálj méret szerint!",
    t3_h1: "Számolás: 3 nagy kör, 4 kis kör",
    t3_h2: "Összesen: 3 + 4 = 7 kör",
    t3_q: "Szortírozz forma szerint: hány kör van? 🔵🔵🟢🔵🟢🔵",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_2: "2",
    t3_q_5: "5",
    svg_sort_big: "Nagy",
    svg_sort_3big: "3 nagy",
    svg_sort_small: "Kicsi",
    svg_sort_4small: "4 kicsi",
    svg_sort_total: "Összesen: 3 + 4 = 7 kör",
  },
  ro: {
    explorer_title: "Explorare date și modele",
    t1_title: "Citirea datelor din tabele",
    t1_text: "Un tabel sau o diagramă ne ajută să numărăm și să organizăm informații. Folosim semne de liniuță (||||) pentru a număra obiecte. Apoi adunăm toate liniuțele pentru a găsi totalul!",
    t1_b1: "Semnele de liniuță ne ajută să numărăm în grupuri de 5",
    t1_b2: "Fiecare grup de 5 este marcat cu o linie peste 4",
    t1_b3: "Adună grupurile pentru a găsi totalul",
    t1_inst: "Numără liniuțele și combină grupurile!",
    t1_h1: "Numărare: 4 mere, 3 banane, 2 struguri",
    t1_h2: "Total: 4 + 3 + 2 = 9 fructe",
    t1_q: "În tabel, ce fruct este preferat?",
    t1_q_apples: "Mere (4)",
    t1_q_bananas: "Banane (3)",
    t1_q_grapes: "Struguri (2)",
    t1_q_all: "Toate egale",
    svg_tally_total: "Total: 4 + 3 + 2 = 9 fructe",
    svg_tally_fav: "Preferatul sunt merele (4 liniuțe)",
    t2_title: "Secvențe de numere și modele",
    t2_text: "Un model este o secvență de numere sau obiecte care urmează o regulă. Putem găsi regula privind cum se schimbă numerele: +2, -1, ×2 etc. Odată ce știm regula, putem găsi următorul număr!",
    t2_b1: "Privește ce se schimbă de la un număr la altul",
    t2_b2: "Aplică aceeași regulă din nou pentru a găsi următorul număr",
    t2_b3: "Modelele ne ajută să prezicem ce vine",
    t2_inst: "Atinge numărul unde secvența 2, 4, 6, 8 continuă!",
    t2_h1: "Modelul adaugă 2 de fiecare dată: 2→4→6→8→?",
    t2_h2: "8 + 2 = 10 — atinge numărul 10!",
    t2_q: "Ce vine în continuare: 5, 10, 15, __?",
    t2_q_18: "18",
    t2_q_20: "20",
    t2_q_25: "25",
    t2_q_16: "16",
    svg_seq_rule: "Regula modelului: Adaugă 2 de fiecare dată",
    svg_seq_next: "Ce vine după 8?",
    t3_title: "Sortarea și clasificarea obiectelor",
    t3_text: "Putem sorta obiecte în grupuri după diferite proprietăți: culoare, mărime, formă sau tip. Când sortăm, organizăm lucrurile pentru a ușura numărarea. Putem număra fiecare grup separat, apoi le adunăm!",
    t3_b1: "Alege o proprietate după care să sortezi (culoare, mărime, formă)",
    t3_b2: "Numără fiecare grup separat",
    t3_b3: "Adună grupurile pentru a găsi totalul",
    t3_inst: "Numără cercurile și combină-le după mărime!",
    t3_h1: "Numărare: 3 cercuri mari, 4 cercuri mici",
    t3_h2: "Total: 3 + 4 = 7 cercuri",
    t3_q: "Sortează după formă: câte cercuri? 🔵🔵🟢🔵🟢🔵",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_2: "2",
    t3_q_5: "5",
    svg_sort_big: "Mare",
    svg_sort_3big: "3 mari",
    svg_sort_small: "Mic",
    svg_sort_4small: "4 mici",
    svg_sort_total: "Total: 3 + 4 = 7 cercuri",
  },
};

const PATTERNEXPLORER_TOPICS: TopicDef[] = [] = [
  // Topic 1: Reading data from tables (tally charts)
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: (lang) => <TallyChartSvg lang={lang} />,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [4, 3, 2],
      answer: 9,
      blockIcon: "🍎",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_apples", "t1_q_bananas", "t1_q_grapes", "t1_q_all"],
      answer: "t1_q_apples",
    },
  },

  // Topic 2: Number sequences & patterns
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: (lang) => <SequenceSvg lang={lang} />,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 20,
      start: 8,
      target: 10,
      showJumps: true,
      jumpCount: 1,
      step: 2,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_18", "t2_q_20", "t2_q_25", "t2_q_16"],
      answer: "t2_q_20",
    },
  },

  // Topic 3: Sorting & classifying
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: (lang) => <SortingClassSvg lang={lang} />,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [3, 4],
      answer: 7,
      blockIcon: "🔵",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_2", "t3_q_3", "t3_q_4", "t3_q_5"],
      answer: "t3_q_3",
    },
  },
];

export const PATTERNEXPLORER_DEF: ExplorerDef = {
  labels: PATTERNEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: PATTERNEXPLORER_TOPICS,
  rounds: [],
};

// ─── PLACEVALUE20EXPLORER CONFIG ───

const PLACEVALUE20EXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    // Explorer meta
    explorer_title: "Numbers 11-20",
    // SVG labels
    svg_1ten: "1 TEN",
    svg_ones: "ONES",
    svg_count_forward: "Count forward: 12, 13, 14, __, 16",
    // Topic 1: Numbers 11-20 intro
    t1_title: "Numbers 11-20",
    t1_text: "After 10 comes 11, 12, 13... up to 20! Each number from 11-20 is made of 1 TEN and some ONES. For example: 15 = 1 ten + 5 ones.",
    t1_b1: "All numbers 11-20 start with 1 ten",
    t1_b2: "The second digit shows how many ONES",
    t1_b3: "Count: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20",
    t1_inst: "Tap the number 15 on the number line!",
    t1_h1: "It comes after 14 and before 16",
    t1_h2: "15 is in the middle of the range 11-20",
    t1_q: "What number comes after 17?",
    t1_q_16: "16",
    t1_q_18: "18",
    t1_q_19: "19",
    t1_q_14: "14",
    // Topic 2: Place value (tens and ones)
    t2_title: "Tens and Ones",
    t2_text: "Numbers 11-20 are made of 1 TEN (= 10 dots) and ONES (= single dots). For example: 14 = 1 ten + 4 ones. When you see 16, it means 1 ten and 6 ones!",
    t2_b1: "1 ten = 10 single dots in a rod",
    t2_b2: "Ones = single dots placed separately",
    t2_b3: "Together: 1 ten + some ones = the number",
    t2_inst: "Build the number 14! Tap the dots to select.",
    t2_h1: "14 needs 1 ten + 4 ones",
    t2_h2: "Start by selecting the ten-rod, then 4 ones",
    t2_q: "How many tens in the number 16?",
    t2_q_0: "0",
    t2_q_1: "1",
    t2_q_6: "6",
    t2_q_16: "16",
    // Topic 3: Sequences and counting
    t3_title: "Counting Forward",
    t3_text: "Count numbers in order: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Each number is one more than the previous. When you count forward, you go: 12, 13, 14, 15 (and so on!).",
    t3_b1: "Each number is one more than before",
    t3_b2: "Count in order from 11 to 20",
    t3_b3: "Every gap in a sequence has ONE answer",
    t3_inst: "Find the missing number: 12, 13, 14, __, 16!",
    t3_h1: "The gap is between 14 and 16",
    t3_h2: "14 + 1 = 15 — tap number 15!",
    t3_q: "What comes next: 14, 15, 16, __?",
    t3_q_13: "13",
    t3_q_17: "17",
    t3_q_18: "18",
    t3_q_19: "19",
  },
  de: {
    explorer_title: "Zahlen 11-20",
    svg_1ten: "1 ZEHNER",
    svg_ones: "EINER",
    svg_count_forward: "Vorwärts zählen: 12, 13, 14, __, 16",
    t1_title: "Zahlen 11-20",
    t1_text: "Nach 10 kommt 11, 12, 13... bis 20! Jede Zahl von 11-20 besteht aus 1 ZEHNER und einigen EINERN. Zum Beispiel: 15 = 1 Zehner + 5 Einer.",
    t1_b1: "Alle Zahlen 11-20 beginnen mit 1 Zehner",
    t1_b2: "Die zweite Ziffer zeigt, wie viele EINER",
    t1_b3: "Zähle: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20",
    t1_inst: "Tippe auf die Zahl 15 auf dem Zahlenstrahl!",
    t1_h1: "Sie kommt nach 14 und vor 16",
    t1_h2: "15 ist in der Mitte des Bereichs 11-20",
    t1_q: "Welche Zahl kommt nach 17?",
    t1_q_16: "16",
    t1_q_18: "18",
    t1_q_19: "19",
    t1_q_14: "14",
    t2_title: "Zehner und Einer",
    t2_text: "Zahlen 11-20 bestehen aus 1 ZEHNER (= 10 Punkte) und EINERN (= einzelne Punkte). Zum Beispiel: 14 = 1 Zehner + 4 Einer. Wenn du 16 siehst, bedeutet es 1 Zehner und 6 Einer!",
    t2_b1: "1 Zehner = 10 einzelne Punkte in einem Stab",
    t2_b2: "Einer = einzelne Punkte separat angeordnet",
    t2_b3: "Zusammen: 1 Zehner + einige Einer = die Zahl",
    t2_inst: "Baue die Zahl 14! Tippe auf die Punkte.",
    t2_h1: "14 benötigt 1 Zehner + 4 Einer",
    t2_h2: "Beginne mit dem Zehnerstab, dann 4 Einer",
    t2_q: "Wie viele Zehner in der Zahl 16?",
    t2_q_0: "0",
    t2_q_1: "1",
    t2_q_6: "6",
    t2_q_16: "16",
    t3_title: "Vorwärts zählen",
    t3_text: "Zähle Zahlen der Reihe nach: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Jede Zahl ist eins mehr als die vorherige. Beim Vorwärtszählen geht es so: 12, 13, 14, 15 (und so weiter!).",
    t3_b1: "Jede Zahl ist eins mehr als vorher",
    t3_b2: "Zähle der Reihe nach von 11 bis 20",
    t3_b3: "Jede Lücke in einer Reihe hat EINE Antwort",
    t3_inst: "Finde die fehlende Zahl: 12, 13, 14, __, 16!",
    t3_h1: "Die Lücke ist zwischen 14 und 16",
    t3_h2: "14 + 1 = 15 — tippe auf 15!",
    t3_q: "Was kommt danach: 14, 15, 16, __?",
    t3_q_13: "13",
    t3_q_17: "17",
    t3_q_18: "18",
    t3_q_19: "19",
  },
  hu: {
    explorer_title: "Számok 11-20",
    svg_1ten: "1 TÍZES",
    svg_ones: "EGYES",
    svg_count_forward: "Számolj előre: 12, 13, 14, __, 16",
    t1_title: "Számok 11-20",
    t1_text: "A 10 után jön 11, 12, 13... 20-ig! A 11-20 közötti minden szám 1 TÍZESBŐL és néhány EGYESBŐL áll. Például: 15 = 1 tízes + 5 egyes.",
    t1_b1: "A 11-20 közötti számok mind 1 tízessel kezdődnek",
    t1_b2: "A második számjegy mutatja, hány EGYES",
    t1_b3: "Számolj: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20",
    t1_inst: "Koppints a számegyenesen a 15-re!",
    t1_h1: "A 14 után és a 16 előtt van",
    t1_h2: "A 15 a 11-20 tartomány közepén van",
    t1_q: "Melyik szám van a 17 után?",
    t1_q_16: "16",
    t1_q_18: "18",
    t1_q_19: "19",
    t1_q_14: "14",
    t2_title: "Tízesek és egyesek",
    t2_text: "A 11-20 közötti számok 1 TÍZESBŐL (= 10 pont) és EGYESEKBŐL (= egyetlen pontok) állnak. Például: 14 = 1 tízes + 4 egyes. Amikor látod a 16-ot, ez 1 tízes és 6 egyes!",
    t2_b1: "1 tízes = 10 egyedi pont egy rúdban",
    t2_b2: "Egyesek = egyedi pontok külön elhelyezve",
    t2_b3: "Együtt: 1 tízes + néhány egyes = a szám",
    t2_inst: "Építsd meg a 14-es számot! Koppints a pontokra.",
    t2_h1: "A 14-hez 1 tízes + 4 egyes kell",
    t2_h2: "Kezdd az ezerkiváló rúddal, majd 4 egyessel",
    t2_q: "Hány tízes van a 16-os számban?",
    t2_q_0: "0",
    t2_q_1: "1",
    t2_q_6: "6",
    t2_q_16: "16",
    t3_title: "Előre számolás",
    t3_text: "Számolj előre sorban: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Minden szám eggyel több az előzőnél. Az előre számoláskor így megy: 12, 13, 14, 15 (és így tovább!).",
    t3_b1: "Minden szám eggyel több az előzőnél",
    t3_b2: "Számolj sorban 11-től 20-ig",
    t3_b3: "Minden rés egy sorozatban EGY válasza van",
    t3_inst: "Találd meg a hiányzó számot: 12, 13, 14, __, 16!",
    t3_h1: "A rés 14 és 16 között van",
    t3_h2: "14 + 1 = 15 — koppints a 15-re!",
    t3_q: "Mi jön ezután: 14, 15, 16, __?",
    t3_q_13: "13",
    t3_q_17: "17",
    t3_q_18: "18",
    t3_q_19: "19",
  },
  ro: {
    explorer_title: "Numere 11-20",
    svg_1ten: "1 ZECE",
    svg_ones: "UNITĂȚI",
    svg_count_forward: "Numără înainte: 12, 13, 14, __, 16",
    t1_title: "Numere 11-20",
    t1_text: "După 10 vin 11, 12, 13... până la 20! Fiecare număr de la 11-20 este format din 1 ZECE și câteva UNITĂȚI. De exemplu: 15 = 1 zece + 5 unități.",
    t1_b1: "Toate numerele 11-20 încep cu 1 zece",
    t1_b2: "A doua cifră arată câte UNITĂȚI",
    t1_b3: "Numără: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20",
    t1_inst: "Atinge numărul 15 pe linia numerelor!",
    t1_h1: "Vine după 14 și înainte de 16",
    t1_h2: "15 este în mijlocul intervalului 11-20",
    t1_q: "Ce număr vine după 17?",
    t1_q_16: "16",
    t1_q_18: "18",
    t1_q_19: "19",
    t1_q_14: "14",
    t2_title: "Zeci și unități",
    t2_text: "Numerele 11-20 sunt formate din 1 ZECE (= 10 puncte) și UNITĂȚI (= puncte unice). De exemplu: 14 = 1 zece + 4 unități. Când vezi 16, înseamnă 1 zece și 6 unități!",
    t2_b1: "1 zece = 10 puncte unice într-o bară",
    t2_b2: "Unități = puncte unice plasate separat",
    t2_b3: "Împreună: 1 zece + câteva unități = numărul",
    t2_inst: "Construiește numărul 14! Atinge punctele.",
    t2_h1: "14 are nevoie de 1 zece + 4 unități",
    t2_h2: "Începe cu bara de zecimi, apoi 4 unități",
    t2_q: "Câte zeci în numărul 16?",
    t2_q_0: "0",
    t2_q_1: "1",
    t2_q_6: "6",
    t2_q_16: "16",
    t3_title: "Numărare înainte",
    t3_text: "Numără numerele în ordine: 11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Fiecare număr este cu unu mai mult decât cel anterior. Când numeri înainte, mergi: 12, 13, 14, 15 (și tot așa!).",
    t3_b1: "Fiecare număr este cu unu mai mult decât cel anterior",
    t3_b2: "Numără în ordine de la 11 la 20",
    t3_b3: "Fiecare gol în secvență are UN răspuns",
    t3_inst: "Găsește numărul lipsă: 12, 13, 14, __, 16!",
    t3_h1: "Golul este între 14 și 16",
    t3_h2: "14 + 1 = 15 — atinge 15!",
    t3_q: "Ce vine mai departe: 14, 15, 16, __?",
    t3_q_13: "13",
    t3_q_17: "17",
    t3_q_18: "18",
    t3_q_19: "19",
  },
};

const PLACEVALUE20EXPLORER_TOPICS: TopicDef[] = [] = [
  // Topic 1: Numbers 11-20
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <NumberLine1120Svg highlight={15} />,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "number-line",
      min: 10,
      max: 20,
      start: 10,
      target: 15,
      showJumps: true,
      jumpCount: 5,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_16", "t1_q_18", "t1_q_19", "t1_q_14"],
      answer: "t1_q_18",
    },
  },

  // Topic 2: Place value (tens and ones)
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: (lang) => <PlaceValueSvg ones={4} label="14" lang={lang} />,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "block-drag",
      mode: "place-value",
      groups: [],
      tens: 1,
      ones: 4,
      answer: 14,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_0", "t2_q_1", "t2_q_6", "t2_q_16"],
      answer: "t2_q_1",
    },
  },

  // Topic 3: Sequences and counting forward
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: (lang) => <SequenceSvg lang={lang} />,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 10,
      max: 20,
      start: 13,
      target: 15,
      showJumps: true,
      jumpCount: 2,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_13", "t3_q_17", "t3_q_18", "t3_q_19"],
      answer: "t3_q_17",
    },
  },
];

export const PLACEVALUE20EXPLORER_DEF: ExplorerDef = {
  labels: PLACEVALUE20EXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: PLACEVALUE20EXPLORER_TOPICS,
  rounds: [],
};

// ─── ADDSUBEXPLORER CONFIG ───

const ADDSUBEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Addition Explorer",
    t1_title: "Swap Groups",
    t1_text: "When we ADD, the order doesn't matter! 3 + 5 is the same as 5 + 3. The answer is always the same!",
    t1_b1: "Groups can swap places",
    t1_b2: "The answer stays the same",
    t1_b3: "Try: 4 + 3 and 3 + 4",
    t1_inst: "Drag the groups together — answer 7!",
    t1_h1: "4 stars here, 3 stars there",
    t1_h2: "Put them together = 7 total",
    t1_q: "4 + 3 = 3 + ?",
    t1_q_3: "3", t1_q_4: "4", t1_q_7: "7", t1_q_1: "1",
    t2_title: "Break Numbers Apart",
    t2_text: "Big numbers are made from smaller numbers! 7 can split into 3 and 4. 7 can also split into 5 and 2. Same number, different splits!",
    t2_b1: "One big number splits",
    t2_b2: "Into two smaller numbers",
    t2_b3: "Add them back = original",
    t2_inst: "Remove 3 from 8 — how many left?",
    t2_h1: "Start with 8, take away 3",
    t2_h2: "Count remaining = 5",
    t2_q: "8 = 3 + ?",
    t2_q_4: "4", t2_q_5: "5", t2_q_6: "6", t2_q_3: "3",
    t3_title: "Adding to 10",
    t3_text: "Use a number line to add! Start at 4, jump forward 3 steps. Where do you land? 4 + 3 = 7!",
    t3_b1: "Start at the first number",
    t3_b2: "Jump forward by the second",
    t3_b3: "Where you land = the answer",
    t3_inst: "Tap number 7 on the line!",
    t3_h1: "Start at 4, jump 3 times",
    t3_h2: "Count up: 5, 6, 7 — tap 7!",
    t3_q: "5 + 4 = ?",
    t3_q_8: "8", t3_q_9: "9", t3_q_10: "10", t3_q_7: "7",
  },
  de: {
    explorer_title: "Addition entdecken",
    t1_title: "Gruppen tauschen",
    t1_text: "Beim ADDIEREN ist die Reihenfolge egal! 3 + 5 ist dasselbe wie 5 + 3. Das Ergebnis bleibt gleich!",
    t1_b1: "Gruppen können Plätze tauschen",
    t1_b2: "Das Ergebnis bleibt gleich",
    t1_b3: "Versuche: 4 + 3 und 3 + 4",
    t1_inst: "Ziehe die Gruppen zusammen — Antwort 7!",
    t1_h1: "4 Sterne hier, 3 Sterne dort",
    t1_h2: "Zusammen = 7 insgesamt",
    t1_q: "4 + 3 = 3 + ?",
    t1_q_3: "3", t1_q_4: "4", t1_q_7: "7", t1_q_1: "1",
    t2_title: "Zahlen auseinander nehmen",
    t2_text: "Große Zahlen bestehen aus kleineren Zahlen! 7 teilt sich in 3 und 4. 7 kann sich auch in 5 und 2 teilen. Gleiche Zahl, unterschiedliche Aufteilungen!",
    t2_b1: "Eine große Zahl teilt sich auf",
    t2_b2: "In zwei kleinere Zahlen",
    t2_b3: "Zusammengezählt = Original",
    t2_inst: "Nimm 3 von 8 — wie viele bleiben?",
    t2_h1: "Starte mit 8, nimm 3 weg",
    t2_h2: "Zähle übrig = 5",
    t2_q: "8 = 3 + ?",
    t2_q_4: "4", t2_q_5: "5", t2_q_6: "6", t2_q_3: "3",
    t3_title: "Addition bis 10",
    t3_text: "Benutze eine Zahlenlinie zum Addieren! Starte bei 4, springe vorwärts 3 Schritte. Wo landest du? 4 + 3 = 7!",
    t3_b1: "Starte bei der ersten Zahl",
    t3_b2: "Springe vorwärts um die zweite",
    t3_b3: "Wo du landest = die Antwort",
    t3_inst: "Tippe auf 7 auf der Linie!",
    t3_h1: "Starte bei 4, springe 3 mal",
    t3_h2: "Zähle hoch: 5, 6, 7 — tippe 7!",
    t3_q: "5 + 4 = ?",
    t3_q_8: "8", t3_q_9: "9", t3_q_10: "10", t3_q_7: "7",
  },
  hu: {
    explorer_title: "Összeadás felfedezés",
    t1_title: "Csoportok cseréje",
    t1_text: "Az ÖSSZEADÁSNÁL a sorrend nem számít! 3 + 5 ugyanaz, mint 5 + 3. Az eredmény mindig ugyanaz!",
    t1_b1: "A csoportok helyet cserélhetnek",
    t1_b2: "Az eredmény ugyanaz marad",
    t1_b3: "Próbáld: 4 + 3 és 3 + 4",
    t1_inst: "Húzd össze a csoportokat — válasz 7!",
    t1_h1: "4 csillag itt, 3 csillag ott",
    t1_h2: "Együtt = 7 összesen",
    t1_q: "4 + 3 = 3 + ?",
    t1_q_3: "3", t1_q_4: "4", t1_q_7: "7", t1_q_1: "1",
    t2_title: "Számok szétszedése",
    t2_text: "A nagy számok kis számokból vannak! A 7 3-ra és 4-re bomlik. A 7 5-re és 2-re is bomlik. Ugyanaz a szám, más feldarabolás!",
    t2_b1: "Egy nagy szám felhasználódik",
    t2_b2: "Két kis számra",
    t2_b3: "Összeadva = az eredeti",
    t2_inst: "Vegyél 3-at az 8-ból — mennyi marad?",
    t2_h1: "Kezdj 8-tól, vegyél el 3-at",
    t2_h2: "Számold meg a maradékot = 5",
    t2_q: "8 = 3 + ?",
    t2_q_4: "4", t2_q_5: "5", t2_q_6: "6", t2_q_3: "3",
    t3_title: "Összeadás 10-ig",
    t3_text: "Használj számegyenest az összeadáshoz! Indulj a 4-ből, ugorj előre 3 lépést. Hol érsz? 4 + 3 = 7!",
    t3_b1: "Indulj az első számnál",
    t3_b2: "Ugorj előre a másodikkal",
    t3_b3: "Ahol érsz = a válasz",
    t3_inst: "Koppints a 7-re a soron!",
    t3_h1: "Indulj 4-ből, ugorj 3-szor",
    t3_h2: "Számolj fel: 5, 6, 7 — koppints 7-re!",
    t3_q: "5 + 4 = ?",
    t3_q_8: "8", t3_q_9: "9", t3_q_10: "10", t3_q_7: "7",
  },
  ro: {
    explorer_title: "Explorare adunare",
    t1_title: "Schimbă grupurile",
    t1_text: "La ADUNARE, ordinea nu contează! 3 + 5 este la fel ca 5 + 3. Răspunsul este întotdeauna același!",
    t1_b1: "Grupurile pot schimba locul",
    t1_b2: "Răspunsul rămâne același",
    t1_b3: "Încearcă: 4 + 3 și 3 + 4",
    t1_inst: "Trage grupurile împreună — răspuns 7!",
    t1_h1: "4 stele aici, 3 stele acolo",
    t1_h2: "Împreună = 7 total",
    t1_q: "4 + 3 = 3 + ?",
    t1_q_3: "3", t1_q_4: "4", t1_q_7: "7", t1_q_1: "1",
    t2_title: "Sparge numerele în bucăți",
    t2_text: "Numerele mari sunt făcute din numere mici! 7 se împarte în 3 și 4. 7 se poate și împărți în 5 și 2. Același număr, alte diviziuni!",
    t2_b1: "Un număr mare se descompune",
    t2_b2: "În două numere mici",
    t2_b3: "Adunate la loc = originalul",
    t2_inst: "Ia 3 din 8 — câte rămân?",
    t2_h1: "Începe cu 8, ia 3 deoparte",
    t2_h2: "Numără rămase = 5",
    t2_q: "8 = 3 + ?",
    t2_q_4: "4", t2_q_5: "5", t2_q_6: "6", t2_q_3: "3",
    t3_title: "Adunare până la 10",
    t3_text: "Folosește o linie numerică pentru adunare! Începe la 4, sari înainte 3 pași. Unde aterizezi? 4 + 3 = 7!",
    t3_b1: "Începe la primul număr",
    t3_b2: "Sari înainte cu al doilea",
    t3_b3: "Unde aterizezi = răspunsul",
    t3_inst: "Atingi 7 pe linie!",
    t3_h1: "Începe la 4, sari 3 ori",
    t3_h2: "Numără: 5, 6, 7 — atingi 7!",
    t3_q: "5 + 4 = ?",
    t3_q_8: "8", t3_q_9: "9", t3_q_10: "10", t3_q_7: "7",
  },
};

const ADDSUBEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [4, 3],
      answer: 7,
      blockIcon: "⭐",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_1", "t1_q_3", "t1_q_4", "t1_q_7"],
      answer: "t1_q_4",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "block-drag",
      mode: "split",
      groups: [8, 3],
      answer: 5,
      blockIcon: "🔵",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_3", "t2_q_4", "t2_q_5", "t2_q_6"],
      answer: "t2_q_5",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 4,
      target: 7,
      showJumps: true,
      jumpCount: 3,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_7", "t3_q_8", "t3_q_9", "t3_q_10"],
      answer: "t3_q_9",
    },
  },
];

export const ADDSUBEXPLORER_DEF: ExplorerDef = {
  labels: ADDSUBEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: ADDSUBEXPLORER_TOPICS,
  rounds: [],
};

// ─── CLOCKCOINSEXPLORER CONFIG ───

const CLOCKCOINSEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Time & Money Explorer",
    t1_title: "Reading the Clock",
    t1_text: "The SHORT hand shows the HOUR. When it points to a number, that's the hour! The LONG hand shows the minutes. When it points to 12, it's o'clock!",
    t1_b1: "Short hand = hour",
    t1_b2: "Long hand = minutes",
    t1_b3: "When both point up = o'clock",
    t1_inst: "Tap the number 3 on the number line — that's where 3 o'clock is!",
    t1_h1: "The short hand is pointing to which number?",
    t1_h2: "It's pointing to 3, so it's 3 o'clock!",
    t1_q: "What time is it when the short hand points to 7?",
    t1_q_3: "3 o'clock", t1_q_7: "7 o'clock", t1_q_11: "11 o'clock", t1_q_5: "5 o'clock",
    t2_title: "Counting Money",
    t2_text: "Euro coins have different values: 1¢, 2¢, 5¢, and 10¢. To count money, add up all the coin values. Start with the biggest coins first!",
    t2_b1: "Different coins have different values",
    t2_b2: "Add all the values together",
    t2_b3: "Start with the largest coins",
    t2_inst: "Combine 5¢ + 5¢ coins to make 10¢!",
    t2_h1: "How many 5¢ coins do you need?",
    t2_h2: "5 + 5 = 10 — combine them!",
    t2_q: "What is 5¢ + 2¢ + 1¢ + 1¢?",
    t2_q_8: "8¢", t2_q_9: "9¢", t2_q_10: "10¢", t2_q_7: "7¢",
    t3_title: "Comparing Lengths",
    t3_text: "Some objects are LONGER and some are SHORTER. We can measure with centimeters (cm). A pencil is usually longer than an eraser. Compare the numbers to see which is bigger!",
    t3_b1: "Longer = bigger number",
    t3_b2: "Shorter = smaller number",
    t3_b3: "Use numbers to compare",
    t3_inst: "Tap 15 on the number line — that's the pencil's length!",
    t3_h1: "Which is longer: 15 cm or 5 cm?",
    t3_h2: "15 is bigger, so the pencil is longer!",
    t3_q: "Which is longer: a pencil (15 cm) or an eraser (5 cm)?",
    t3_q_pencil: "Pencil", t3_q_eraser: "Eraser", t3_q_equal: "They are equal", t3_q_idk: "Can't tell",
  },
  de: {
    explorer_title: "Zeit & Geld Entdeckung",
    t1_title: "Uhr ablesen",
    t1_text: "Der KURZE Zeiger zeigt die STUNDE. Wenn er auf eine Zahl zeigt, ist das die Stunde! Der LANGE Zeiger zeigt die Minuten. Wenn er auf 12 zeigt, ist es Uhr!",
    t1_b1: "Kurzer Zeiger = Stunde",
    t1_b2: "Langer Zeiger = Minuten",
    t1_b3: "Beide oben = Uhr",
    t1_inst: "Tippe auf die Zahl 3 auf dem Zahlenstrahl — das ist 3 Uhr!",
    t1_h1: "Auf welche Zahl zeigt der kurze Zeiger?",
    t1_h2: "Er zeigt auf 3, also ist es 3 Uhr!",
    t1_q: "Wie spät ist es, wenn der kurze Zeiger auf 7 zeigt?",
    t1_q_3: "3 Uhr", t1_q_7: "7 Uhr", t1_q_11: "11 Uhr", t1_q_5: "5 Uhr",
    t2_title: "Geld zählen",
    t2_text: "Euro-Münzen haben verschiedene Werte: 1¢, 2¢, 5¢ und 10¢. Um Geld zu zählen, addiere alle Münzwerte. Beginne mit den größten Münzen!",
    t2_b1: "Verschiedene Münzen haben verschiedene Werte",
    t2_b2: "Addiere alle Werte zusammen",
    t2_b3: "Beginne mit den größten Münzen",
    t2_inst: "Kombiniere 5¢ + 5¢ Münzen zu 10¢!",
    t2_h1: "Wie viele 5¢-Münzen brauchst du?",
    t2_h2: "5 + 5 = 10 — kombiniere sie!",
    t2_q: "Was ist 5¢ + 2¢ + 1¢ + 1¢?",
    t2_q_8: "8¢", t2_q_9: "9¢", t2_q_10: "10¢", t2_q_7: "7¢",
    t3_title: "Längen vergleichen",
    t3_text: "Manche Gegenstände sind LÄNGER und manche KÜRZER. Wir können in Zentimetern (cm) messen. Ein Bleistift ist normalerweise länger als ein Radierer. Vergleiche die Zahlen!",
    t3_b1: "Länger = größere Zahl",
    t3_b2: "Kürzer = kleinere Zahl",
    t3_b3: "Nutze Zahlen zum Vergleichen",
    t3_inst: "Tippe auf 15 auf dem Zahlenstrahl — das ist die Länge des Bleistifts!",
    t3_h1: "Was ist länger: 15 cm oder 5 cm?",
    t3_h2: "15 ist größer, also ist der Bleistift länger!",
    t3_q: "Was ist länger: ein Bleistift (15 cm) oder ein Radierer (5 cm)?",
    t3_q_pencil: "Bleistift", t3_q_eraser: "Radierer", t3_q_equal: "Sie sind gleich lang", t3_q_idk: "Kann man nicht sagen",
  },
  hu: {
    explorer_title: "Idő & Pénz felfedezés",
    t1_title: "Az óra olvasása",
    t1_text: "A RÖVID mutató mutatja az ÓRÁT. Ha egy számra mutat, az a szám az óra! A HOSSZÚ mutató a perceket mutatja. Ha a 12-re mutat, egész óra van!",
    t1_b1: "Rövid mutató = óra",
    t1_b2: "Hosszú mutató = perc",
    t1_b3: "Mindkettő felfelé = egész óra",
    t1_inst: "Koppints a 3-as számra a számegyenesen — az 3 óra!",
    t1_h1: "Melyik számra mutat a rövid mutató?",
    t1_h2: "A 3-ra mutat, szóval 3 óra van!",
    t1_q: "Hány óra van, ha a rövid mutató a 7-re mutat?",
    t1_q_3: "3 óra", t1_q_7: "7 óra", t1_q_11: "11 óra", t1_q_5: "5 óra",
    t2_title: "Pénz számolása",
    t2_text: "Az euro érméinek különböző értéke van: 1¢, 2¢, 5¢ és 10¢. A pénz számolásához add össze az összes érme értékét. Kezdd a legnagyobb érméikkel!",
    t2_b1: "Különböző érméik különböző értékű",
    t2_b2: "Add össze az összes értéket",
    t2_b3: "Kezdd a legnagyobb érméikkel",
    t2_inst: "Kombinálj 5¢ + 5¢ érméket, hogy 10¢ legyen!",
    t2_h1: "Hány 5¢ érmére van szükséged?",
    t2_h2: "5 + 5 = 10 — kombináld őket!",
    t2_q: "Mennyi az 5¢ + 2¢ + 1¢ + 1¢?",
    t2_q_8: "8¢", t2_q_9: "9¢", t2_q_10: "10¢", t2_q_7: "7¢",
    t3_title: "Hosszúságok összehasonlítása",
    t3_text: "Egyes tárgyak HOSSZABBAK és némelyik RÖVIDEBB. Centiméterben (cm) tudjuk mérni. Egy ceruza általában hosszabb, mint egy radír. Hasonlítsd össze a számokat!",
    t3_b1: "Hosszabb = nagyobb szám",
    t3_b2: "Rövidebb = kisebb szám",
    t3_b3: "Használj számokat az összehasonlításhoz",
    t3_inst: "Koppints a 15-re a számegyenesen — az a ceruza hossza!",
    t3_h1: "Mi a hosszabb: 15 cm vagy 5 cm?",
    t3_h2: "15 nagyobb, szóval a ceruza hosszabb!",
    t3_q: "Mi a hosszabb: egy ceruza (15 cm) vagy egy radír (5 cm)?",
    t3_q_pencil: "Ceruza", t3_q_eraser: "Radír", t3_q_equal: "Egyforma hosszúak", t3_q_idk: "Nem tudom",
  },
  ro: {
    explorer_title: "Descoperire timp & bani",
    t1_title: "Citirea orei",
    t1_text: "Acul SCURT arată ORA. Când señalează o cifră, aceea este ora! Acul LUNG arată minutele. Când señalează 12, este exact ora!",
    t1_b1: "Ac scurt = oră",
    t1_b2: "Ac lung = minute",
    t1_b3: "Amândoi sus = exact pe oră",
    t1_inst: "Atinge cifra 3 pe linia numerelor — aceea este 3 ore!",
    t1_h1: "La ce cifră señalează acul scurt?",
    t1_h2: "Señalează la 3, deci sunt 3 ore!",
    t1_q: "Cât este ceasul când acul scurt señalează la 7?",
    t1_q_3: "3 ore", t1_q_7: "7 ore", t1_q_11: "11 ore", t1_q_5: "5 ore",
    t2_title: "Numărarea banilor",
    t2_text: "Monedele euro au valori diferite: 1¢, 2¢, 5¢ și 10¢. Pentru a număra bani, adună valorile tuturor monedelor. Începe cu monedele mai mari!",
    t2_b1: "Monede diferite au valori diferite",
    t2_b2: "Adună toate valorile",
    t2_b3: "Începe cu monedele mai mari",
    t2_inst: "Combină monede de 5¢ + 5¢ pentru a face 10¢!",
    t2_h1: "Câte monede de 5¢ ai nevoie?",
    t2_h2: "5 + 5 = 10 — combină-le!",
    t2_q: "Cât este 5¢ + 2¢ + 1¢ + 1¢?",
    t2_q_8: "8¢", t2_q_9: "9¢", t2_q_10: "10¢", t2_q_7: "7¢",
    t3_title: "Compararea lungimilor",
    t3_text: "Unele obiecte sunt MAI LUNGI și altele sunt MAI SCURTE. Putem măsura în centimetri (cm). O creionul este de obicei mai lung decât un radieră. Compară numerele!",
    t3_b1: "Mai lung = număr mai mare",
    t3_b2: "Mai scurt = număr mai mic",
    t3_b3: "Folosește numere pentru a compara",
    t3_inst: "Atinge 15 pe linia numerelor — aceea este lungimea creionului!",
    t3_h1: "Ce este mai lung: 15 cm sau 5 cm?",
    t3_h2: "15 este mai mare, deci creionul este mai lung!",
    t3_q: "Ce este mai lung: o creion (15 cm) sau o radieră (5 cm)?",
    t3_q_pencil: "Creion", t3_q_eraser: "Radieră", t3_q_equal: "Sunt egale", t3_q_idk: "Nu pot spune",
  },
};

const CLOCKCOINSEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "number-line",
      min: 1,
      max: 12,
      start: 1,
      target: 3,
      showJumps: true,
      jumpCount: 2,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_3", "t1_q_7", "t1_q_11", "t1_q_5"],
      answer: "t1_q_7",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [5, 5],
      answer: 10,
      blockIcon: "🪙",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_8", "t2_q_9", "t2_q_10", "t2_q_7"],
      answer: "t2_q_9",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 20,
      start: 0,
      target: 15,
      showJumps: false,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_pencil", "t3_q_eraser", "t3_q_equal", "t3_q_idk"],
      answer: "t3_q_pencil",
    },
  },
];

export const CLOCKCOINSEXPLORER_DEF: ExplorerDef = {
  labels: CLOCKCOINSEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: CLOCKCOINSEXPLORER_TOPICS,
  rounds: [],
};

// ─── COUNTINGEXPLORER CONFIG ───

const COUNTINGEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Counting Explorer",
    t1_title: "Counting Objects",
    t1_text: "To count objects, touch each one and say the number out loud: 1, 2, 3... The last number you say is how many there are!",
    t1_b1: "Always start from 1",
    t1_b2: "Count each object exactly once",
    t1_b3: "The last number is the total",
    t1_inst: "Move 5 apples into the basket!",
    t1_h1: "Count them one by one — how many do you need?",
    t1_h2: "You need exactly 5 apples in the basket",
    t1_q: "How many stars are in this picture?",
    t1_q_7: "7", t1_q_5: "5", t1_q_6: "6", t1_q_8: "8",
    t2_title: "Comparing Numbers",
    t2_text: "To compare two groups, count each group. The group with the bigger number has MORE. If both numbers are the same, they are EQUAL!",
    t2_b1: "Count each group separately",
    t2_b2: "The bigger number = more objects",
    t2_b3: "Same number = equal",
    t2_inst: "Tap the number where 3 + 4 lands on the number line!",
    t2_h1: "Start at 3 and jump 4 steps forward",
    t2_h2: "3 + 4 = 7 — tap number 7!",
    t2_q: "Which group has MORE: 6 cats or 4 dogs?",
    t2_q_cats: "6 cats", t2_q_dogs: "4 dogs", t2_q_equal: "They are equal", t2_q_idk: "Can't tell",
    t3_title: "Number Neighbors",
    t3_text: "Every number has neighbors! The number BEFORE is one less, the number AFTER is one more. For example: 4 is before 5, and 6 is after 5.",
    t3_b1: "The number before = one less",
    t3_b2: "The number after = one more",
    t3_b3: "Together: before – number – after",
    t3_inst: "Tap the number that comes AFTER 6 on the number line!",
    t3_h1: "What is one more than 6?",
    t3_h2: "6 + 1 = 7 — tap number 7!",
    t3_q: "What number comes BEFORE 8?",
    t3_q_7: "7", t3_q_9: "9", t3_q_6: "6", t3_q_8: "8",
  },
  de: {
    explorer_title: "Zählen entdecken",
    t1_title: "Gegenstände zählen",
    t1_text: "Um Gegenstände zu zählen, berühre jeden einzelnen und sage die Zahl laut: 1, 2, 3... Die letzte Zahl ist die Gesamtzahl!",
    t1_b1: "Fang immer bei 1 an",
    t1_b2: "Zähle jeden Gegenstand genau einmal",
    t1_b3: "Die letzte Zahl ist die Gesamtzahl",
    t1_inst: "Lege 5 Äpfel in den Korb!",
    t1_h1: "Zähle sie einzeln — wie viele brauchst du?",
    t1_h2: "Du brauchst genau 5 Äpfel im Korb",
    t1_q: "Wie viele Sterne sind auf dem Bild?",
    t1_q_7: "7", t1_q_5: "5", t1_q_6: "6", t1_q_8: "8",
    t2_title: "Zahlen vergleichen",
    t2_text: "Um zwei Gruppen zu vergleichen, zähle jede Gruppe. Die Gruppe mit der größeren Zahl hat MEHR. Wenn beide Zahlen gleich sind, sind sie GLEICH!",
    t2_b1: "Zähle jede Gruppe einzeln",
    t2_b2: "Die größere Zahl = mehr Gegenstände",
    t2_b3: "Gleiche Zahl = gleich viele",
    t2_inst: "Tippe auf die Zahl, wo 3 + 4 auf dem Zahlenstrahl landet!",
    t2_h1: "Starte bei 3 und springe 4 Schritte vorwärts",
    t2_h2: "3 + 4 = 7 — tippe auf die 7!",
    t2_q: "Welche Gruppe hat MEHR: 6 Katzen oder 4 Hunde?",
    t2_q_cats: "6 Katzen", t2_q_dogs: "4 Hunde", t2_q_equal: "Gleich viele", t2_q_idk: "Kann man nicht sagen",
    t3_title: "Zahlennachbarn",
    t3_text: "Jede Zahl hat Nachbarn! Die Zahl DAVOR ist eins weniger, die Zahl DANACH ist eins mehr. Zum Beispiel: 4 kommt vor 5, und 6 kommt nach 5.",
    t3_b1: "Die Zahl davor = eins weniger",
    t3_b2: "Die Zahl danach = eins mehr",
    t3_b3: "Zusammen: davor – Zahl – danach",
    t3_inst: "Tippe auf die Zahl, die NACH der 6 kommt!",
    t3_h1: "Was ist eins mehr als 6?",
    t3_h2: "6 + 1 = 7 — tippe auf die 7!",
    t3_q: "Welche Zahl kommt VOR der 8?",
    t3_q_7: "7", t3_q_9: "9", t3_q_6: "6", t3_q_8: "8",
  },
  hu: {
    explorer_title: "Számolás felfedezés",
    t1_title: "Tárgyak számolása",
    t1_text: "A tárgyak számolásához érintsd meg mindegyiket, és mondd hangosan a számot: 1, 2, 3... Az utolsó szám a tárgyak száma!",
    t1_b1: "Mindig 1-től kezdj",
    t1_b2: "Minden tárgyat pontosan egyszer számolj",
    t1_b3: "Az utolsó szám az összesen",
    t1_inst: "Tegyél 5 almát a kosárba!",
    t1_h1: "Számold meg egyenként — hányra van szükséged?",
    t1_h2: "Pontosan 5 alma kell a kosárba",
    t1_q: "Hány csillag van a képen?",
    t1_q_7: "7", t1_q_5: "5", t1_q_6: "6", t1_q_8: "8",
    t2_title: "Számok összehasonlítása",
    t2_text: "Két csoport összehasonlításához számold meg mindkettőt. A nagyobb számú csoportban van TÖBB. Ha mindkét szám ugyanaz, akkor EGYENLŐEK!",
    t2_b1: "Számold meg külön mindkét csoportot",
    t2_b2: "A nagyobb szám = több tárgy",
    t2_b3: "Ugyanaz a szám = egyenlő",
    t2_inst: "Koppints arra a számra, ahova a 3 + 4 esik a számegyenesen!",
    t2_h1: "Indulj a 3-tól és ugorj 4 lépést előre",
    t2_h2: "3 + 4 = 7 — koppints a 7-re!",
    t2_q: "Melyik csoportban van TÖBB: 6 macska vagy 4 kutya?",
    t2_q_cats: "6 macska", t2_q_dogs: "4 kutya", t2_q_equal: "Egyenlő", t2_q_idk: "Nem tudom",
    t3_title: "Számszomszédok",
    t3_text: "Minden számnak van szomszédja! Az ELŐTTE lévő szám eggyel kisebb, az UTÁNA lévő eggyel nagyobb. Például: 4 van az 5 előtt, 6 van az 5 után.",
    t3_b1: "Az előtte lévő szám = eggyel kisebb",
    t3_b2: "Az utána lévő szám = eggyel nagyobb",
    t3_b3: "Együtt: előtte – szám – utána",
    t3_inst: "Koppints arra a számra, ami a 6 UTÁN jön a számegyenesen!",
    t3_h1: "Mi az eggyel több mint 6?",
    t3_h2: "6 + 1 = 7 — koppints a 7-re!",
    t3_q: "Melyik szám van a 8 ELŐTT?",
    t3_q_7: "7", t3_q_9: "9", t3_q_6: "6", t3_q_8: "8",
  },
  ro: {
    explorer_title: "Explorare numărare",
    t1_title: "Numărarea obiectelor",
    t1_text: "Pentru a număra obiectele, atinge fiecare și spune numărul cu voce tare: 1, 2, 3... Ultimul număr este totalul!",
    t1_b1: "Începe întotdeauna de la 1",
    t1_b2: "Numără fiecare obiect o singură dată",
    t1_b3: "Ultimul număr este totalul",
    t1_inst: "Pune 5 mere în coș!",
    t1_h1: "Numără-le pe rând — câte ai nevoie?",
    t1_h2: "Ai nevoie de exact 5 mere în coș",
    t1_q: "Câte stele sunt în imagine?",
    t1_q_7: "7", t1_q_5: "5", t1_q_6: "6", t1_q_8: "8",
    t2_title: "Compararea numerelor",
    t2_text: "Pentru a compara două grupuri, numără fiecare. Grupul cu numărul mai mare are MAI MULTE. Dacă sunt egale, sunt EGALE!",
    t2_b1: "Numără fiecare grup separat",
    t2_b2: "Numărul mai mare = mai multe obiecte",
    t2_b3: "Același număr = egale",
    t2_inst: "Atinge numărul unde 3 + 4 ajunge pe linia numerelor!",
    t2_h1: "Începe de la 3 și sari 4 pași înainte",
    t2_h2: "3 + 4 = 7 — atinge numărul 7!",
    t2_q: "Care grup are MAI MULTE: 6 pisici sau 4 câini?",
    t2_q_cats: "6 pisici", t2_q_dogs: "4 câini", t2_q_equal: "Sunt egale", t2_q_idk: "Nu se poate spune",
    t3_title: "Vecinii numerelor",
    t3_text: "Fiecare număr are vecini! Numărul DINAINTEA este cu unu mai mic, numărul DE DUPĂ este cu unu mai mare. De exemplu: 4 vine înainte de 5, iar 6 vine după 5.",
    t3_b1: "Numărul dinaintea = cu unu mai mic",
    t3_b2: "Numărul de după = cu unu mai mare",
    t3_b3: "Împreună: înainte – număr – după",
    t3_inst: "Atinge numărul care vine DUPĂ 6!",
    t3_h1: "Ce este cu unu mai mult decât 6?",
    t3_h2: "6 + 1 = 7 — atinge numărul 7!",
    t3_q: "Ce număr vine ÎNAINTE de 8?",
    t3_q_7: "7", t3_q_9: "9", t3_q_6: "6", t3_q_8: "8",
  },
};

const COUNTINGEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [3, 2],
      answer: 5,
      blockIcon: "🍎",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_5", "t1_q_6", "t1_q_7", "t1_q_8"],
      answer: "t1_q_7",
    },
    quizSvg: () => null,
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 3,
      target: 7,
      showJumps: true,
      jumpCount: 4,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_cats", "t2_q_dogs", "t2_q_equal", "t2_q_idk"],
      answer: "t2_q_cats",
    },
    quizSvg: () => null,
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 6,
      target: 7,
      showJumps: true,
      jumpCount: 1,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_6", "t3_q_7", "t3_q_8", "t3_q_9"],
      answer: "t3_q_7",
    },
    quizSvg: () => null,
  },
];

export const COUNTINGEXPLORER_DEF: ExplorerDef = {
  labels: COUNTINGEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: COUNTINGEXPLORER_TOPICS,
  rounds: [],
};

// ─── DOUBLEHALFEXPLORER CONFIG ───

const DOUBLEHALFEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Double & Half Explorer",
    t1_title: "Doubling (×2)",
    t1_text: "Double means adding the same number twice. When you double, you make two equal groups and count them together: 4 + 4 = 8.",
    t1_b1: "Double = two equal groups",
    t1_b2: "Add them together",
    t1_b3: "2 × the number",
    t1_inst: "Combine 5 stars with 5 more stars — how many total?",
    t1_h1: "Count both groups together",
    t1_h2: "5 + 5 = 10 — double of 5!",
    t1_q: "What is the double of 6?",
    t1_q_10: "10", t1_q_12: "12", t1_q_11: "11", t1_q_14: "14",
    t2_title: "Halving (÷2)",
    t2_text: "Half means splitting into two equal parts. When you halve, you divide a number equally: 8 ÷ 2 = 4, so half of 8 is 4.",
    t2_b1: "Half = split into 2 equal parts",
    t2_b2: "Each part is the same size",
    t2_b3: "Half = ÷ by 2",
    t2_inst: "Split 8 cookies equally with a friend — how many does each get?",
    t2_h1: "Share them equally into 2 groups",
    t2_h2: "8 ÷ 2 = 4 — each gets 4 cookies!",
    t2_q: "What is half of 14?",
    t2_q_6: "6", t2_q_7: "7", t2_q_8: "8", t2_q_5: "5",
    t3_title: "Simple Fractions (1/2)",
    t3_text: "A fraction is a part of a whole. When you split something in half, you have two equal parts. One part is 1/2 (one half) of the whole.",
    t3_b1: "1/2 = one of two equal parts",
    t3_b2: "The top number tells the parts you have",
    t3_b3: "The bottom number tells the total parts",
    t3_inst: "Half of 6 candies = tap the candy on the right!",
    t3_h1: "Split 6 equally into 2 groups",
    t3_h2: "6 ÷ 2 = 3 in each group!",
    t3_q: "If you share 6 candies equally with a friend, how many does each get?",
    t3_q_2: "2", t3_q_3: "3", t3_q_4: "4", t3_q_5: "5",
  },
  de: {
    explorer_title: "Verdoppeln & Halbieren Entdeckung",
    t1_title: "Verdoppeln (×2)",
    t1_text: "Verdoppeln bedeutet, die gleiche Zahl zweimal hinzuzufügen. Wenn du verdoppelst, machst du zwei gleiche Gruppen und zählst sie zusammen: 4 + 4 = 8.",
    t1_b1: "Verdoppeln = zwei gleiche Gruppen",
    t1_b2: "Zähle sie zusammen",
    t1_b3: "2 × die Zahl",
    t1_inst: "Kombiniere 5 Sterne mit 5 weiteren Sternen — wie viele insgesamt?",
    t1_h1: "Zähle beide Gruppen zusammen",
    t1_h2: "5 + 5 = 10 — das Doppelte von 5!",
    t1_q: "Was ist das Doppelte von 6?",
    t1_q_10: "10", t1_q_12: "12", t1_q_11: "11", t1_q_14: "14",
    t2_title: "Halbieren (÷2)",
    t2_text: "Halbieren bedeutet, in zwei gleiche Teile zu teilen. Wenn du halbierst, teilst du eine Zahl gleichmäßig: 8 ÷ 2 = 4, also ist die Hälfte von 8 gleich 4.",
    t2_b1: "Halbieren = in 2 gleiche Teile teilen",
    t2_b2: "Jeder Teil ist gleich groß",
    t2_b3: "Hälfte = ÷ 2",
    t2_inst: "Teile 8 Kekse gleichmäßig mit einem Freund — wie viele bekommt jeder?",
    t2_h1: "Teile sie gleichermaßen in 2 Gruppen",
    t2_h2: "8 ÷ 2 = 4 — jeder bekommt 4 Kekse!",
    t2_q: "Was ist die Hälfte von 14?",
    t2_q_6: "6", t2_q_7: "7", t2_q_8: "8", t2_q_5: "5",
    t3_title: "Einfache Brüche (1/2)",
    t3_text: "Ein Bruch ist ein Teil eines Ganzen. Wenn du etwas in zwei Hälften teilst, hast du zwei gleiche Teile. Ein Teil ist 1/2 (ein Halb) des Ganzen.",
    t3_b1: "1/2 = einer von zwei gleichen Teilen",
    t3_b2: "Die obere Zahl zeigt die Teile, die du hast",
    t3_b3: "Die untere Zahl zeigt die Gesamtteile",
    t3_inst: "Hälfte von 6 Bonbons = tippe auf das Bonbon rechts!",
    t3_h1: "Teile 6 gleichmäßig in 2 Gruppen",
    t3_h2: "6 ÷ 2 = 3 in jeder Gruppe!",
    t3_q: "Wenn du 6 Bonbons gleichmäßig mit einem Freund teilst, wie viele bekommt jeder?",
    t3_q_2: "2", t3_q_3: "3", t3_q_4: "4", t3_q_5: "5",
  },
  hu: {
    explorer_title: "Dupla & Fele Felfedezés",
    t1_title: "Megduplázás (×2)",
    t1_text: "A megduplázás azt jelenti, hogy az ugyanazt a számot kétszer hozzáadod. Amikor megduplázol, két egyenlő csoportot készítesz és összeadod őket: 4 + 4 = 8.",
    t1_b1: "Megduplázás = két egyenlő csoport",
    t1_b2: "Összeadod őket",
    t1_b3: "2 × a szám",
    t1_inst: "Kombinálj 5 csillagot 5 másik csillaggal — összesen hány?",
    t1_h1: "Számold össze mindkét csoportot",
    t1_h2: "5 + 5 = 10 — az 5 duplája!",
    t1_q: "Mi az 6 duplája?",
    t1_q_10: "10", t1_q_12: "12", t1_q_11: "11", t1_q_14: "14",
    t2_title: "Felezés (÷2)",
    t2_text: "A felezés azt jelenti, hogy két egyenlő részre osztasz. Amikor felezol, egyenlően osztasz el egy számot: 8 ÷ 2 = 4, tehát a 8 fele 4.",
    t2_b1: "Felezés = 2 egyenlő részre osztás",
    t2_b2: "Minden rész egyforma",
    t2_b3: "Fele = ÷ 2",
    t2_inst: "Oszd meg 8 sütit egyenlően egy baráttal — hányan kapja meg?",
    t2_h1: "Oszd meg őket egyenlően 2 csoportra",
    t2_h2: "8 ÷ 2 = 4 — mindenki 4 sütit kap!",
    t2_q: "Mi a 14 fele?",
    t2_q_6: "6", t2_q_7: "7", t2_q_8: "8", t2_q_5: "5",
    t3_title: "Egyszerű Törtek (1/2)",
    t3_text: "A tört az egész egy része. Amikor valamit két felére osztasz, két egyenlő részed van. Egy rész az 1/2 (egy fél) az egésznek.",
    t3_b1: "1/2 = az egyik a két egyenlő részből",
    t3_b2: "A felső szám a részeket mutatja, amelyeid van",
    t3_b3: "Az alsó szám az összes részeket mutatja",
    t3_inst: "6 cukor fele = kattints a jobb oldali cukorra!",
    t3_h1: "Oszd meg a 6-ot egyenlően 2 csoportra",
    t3_h2: "6 ÷ 2 = 3 minden csoportban!",
    t3_q: "Ha 6 cukrot egyenlően osztasz meg egy baráttal, hányat kap mindenki?",
    t3_q_2: "2", t3_q_3: "3", t3_q_4: "4", t3_q_5: "5",
  },
  ro: {
    explorer_title: "Explorare Dublu & Jumătate",
    t1_title: "Dublare (×2)",
    t1_text: "Dublarea înseamnă adunarea aceluiași număr de două ori. Când dublezi, faci două grupuri egale și le numeri împreună: 4 + 4 = 8.",
    t1_b1: "Dublare = două grupuri egale",
    t1_b2: "Adună-le împreună",
    t1_b3: "2 × numărul",
    t1_inst: "Combină 5 stele cu 5 stele în plus — câte în total?",
    t1_h1: "Numără ambele grupuri împreună",
    t1_h2: "5 + 5 = 10 — dublul lui 5!",
    t1_q: "Care este dublul lui 6?",
    t1_q_10: "10", t1_q_12: "12", t1_q_11: "11", t1_q_14: "14",
    t2_title: "Înjumătățire (÷2)",
    t2_text: "Înjumătățirea înseamnă împărțirea în două părți egale. Când înjumătățești, împarți un număr egal: 8 ÷ 2 = 4, deci jumătatea lui 8 este 4.",
    t2_b1: "Înjumătățire = împărțire în 2 părți egale",
    t2_b2: "Fiecare parte este la fel de mare",
    t2_b3: "Jumătate = ÷ 2",
    t2_inst: "Împarte 8 biscuiți egal cu un prieten — câți primește fiecare?",
    t2_h1: "Împarte-i egal în 2 grupuri",
    t2_h2: "8 ÷ 2 = 4 — fiecare primește 4 biscuiți!",
    t2_q: "Care este jumătatea lui 14?",
    t2_q_6: "6", t2_q_7: "7", t2_q_8: "8", t2_q_5: "5",
    t3_title: "Fracții Simple (1/2)",
    t3_text: "O fracție este o parte a unui întreg. Când împarți ceva în jumătate, ai două părți egale. O parte este 1/2 (o jumătate) din întreg.",
    t3_b1: "1/2 = una din două părți egale",
    t3_b2: "Numărul de sus arată părțile pe care le ai",
    t3_b3: "Numărul de jos arată totalul de părți",
    t3_inst: "Jumătatea din 6 bomboane = atinge bomboana din dreapta!",
    t3_h1: "Împarte 6 egal în 2 grupuri",
    t3_h2: "6 ÷ 2 = 3 în fiecare grup!",
    t3_q: "Dacă împarți 6 bomboane egal cu un prieten, câte primește fiecare?",
    t3_q_2: "2", t3_q_3: "3", t3_q_4: "4", t3_q_5: "5",
  },
};

const DOUBLEHALFEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [5, 5],
      answer: 10,
      blockIcon: "⭐",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_10", "t1_q_12", "t1_q_11", "t1_q_14"],
      answer: "t1_q_12",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "block-drag",
      mode: "split",
      groups: [8, 4],
      answer: 4,
      blockIcon: "🍪",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_6", "t2_q_7", "t2_q_8", "t2_q_5"],
      answer: "t2_q_7",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 0,
      target: 3,
      showJumps: true,
      jumpCount: 3,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_2", "t3_q_3", "t3_q_4", "t3_q_5"],
      answer: "t3_q_3",
    },
  },
];

export const DOUBLEHALFEXPLORER_DEF: ExplorerDef = {
  labels: DOUBLEHALFEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: DOUBLEHALFEXPLORER_TOPICS,
  rounds: [],
};

// ─── SHAPESEXPLORER CONFIG ───

const SHAPESEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Shapes Explorer",
    t1_title: "Basic Shapes",
    t1_text: "There are four basic shapes: triangle (3 sides), square (4 equal sides), circle (round, no sides), and rectangle (4 sides, longer than wide). Each shape has special features!",
    t1_b1: "Triangle has 3 sides and 3 corners",
    t1_b2: "Square has 4 equal sides and 4 corners",
    t1_b3: "Circle is round with no sides or corners",
    t1_inst: "Count 3 triangles and 3 squares — how many shapes total?",
    t1_h1: "3 triangles + 3 squares = how many?",
    t1_h2: "Count them all together — the answer is 6!",
    t1_q: "How many corners does a triangle have?",
    t1_q_2: "2", t1_q_3: "3", t1_q_4: "4", t1_q_5: "5",
    t2_title: "Where Are Things?",
    t2_text: "Shapes can be in different places: ABOVE (up), BELOW (down), LEFT (left side), RIGHT (right side), and CENTER (middle). Learning positions helps us understand directions!",
    t2_b1: "Left = the left side",
    t2_b2: "Right = the right side",
    t2_b3: "Above = higher up; Below = lower down",
    t2_inst: "Tap position 3 on the line — the middle!",
    t2_h1: "Count from 1 to 5, find the middle",
    t2_h2: "1, 2, 3 (middle!) — tap number 3!",
    t2_q: "Which shape has 4 equal sides?",
    t2_q_triangle: "triangle", t2_q_square: "square", t2_q_circle: "circle", t2_q_rectangle: "rectangle",
    t3_title: "Patterns & Repetition",
    t3_text: "A pattern repeats the same shapes or colors in order: circle, square, circle, square... When you see a pattern, you can guess what comes next! Patterns are all around us.",
    t3_b1: "Patterns repeat in order",
    t3_b2: "Look for what repeats",
    t3_b3: "Guess the next shape in the pattern",
    t3_inst: "Move 4 blocks to complete the pattern!",
    t3_h1: "Circle-square-circle-square-?",
    t3_h2: "The next shape is a circle! Drag 4 circles!",
    t3_q: "What comes next: red square, blue circle, red square, blue circle, ?",
    t3_q_red_sq: "red square", t3_q_blue_circ: "blue circle", t3_q_red_circ: "red circle", t3_q_blue_sq: "blue square",
  },
  de: {
    explorer_title: "Formen entdecken",
    t1_title: "Grundformen",
    t1_text: "Es gibt vier Grundformen: Dreieck (3 Seiten), Quadrat (4 gleiche Seiten), Kreis (rund, keine Seiten) und Rechteck (4 Seiten, länger als breit). Jede Form hat besondere Merkmale!",
    t1_b1: "Dreieck hat 3 Seiten und 3 Ecken",
    t1_b2: "Quadrat hat 4 gleiche Seiten und 4 Ecken",
    t1_b3: "Kreis ist rund ohne Seiten oder Ecken",
    t1_inst: "Zähle 3 Dreiecke und 3 Quadrate — wie viele Formen insgesamt?",
    t1_h1: "3 Dreiecke + 3 Quadrate = wie viele?",
    t1_h2: "Zähle sie zusammen — die Antwort ist 6!",
    t1_q: "Wie viele Ecken hat ein Dreieck?",
    t1_q_2: "2", t1_q_3: "3", t1_q_4: "4", t1_q_5: "5",
    t2_title: "Wo sind die Formen?",
    t2_text: "Formen können an verschiedenen Stellen sein: OBEN (nach oben), UNTEN (nach unten), LINKS (linke Seite), RECHTS (rechte Seite) und MITTE (Mitte). Das Lernen von Positionen hilft uns, Richtungen zu verstehen!",
    t2_b1: "Links = die linke Seite",
    t2_b2: "Rechts = die rechte Seite",
    t2_b3: "Oben = höher oben; Unten = weiter unten",
    t2_inst: "Tippe auf Position 3 auf der Linie — die Mitte!",
    t2_h1: "Zähle von 1 bis 5, finde die Mitte",
    t2_h2: "1, 2, 3 (Mitte!) — tippe auf 3!",
    t2_q: "Welche Form hat 4 gleiche Seiten?",
    t2_q_triangle: "Dreieck", t2_q_square: "Quadrat", t2_q_circle: "Kreis", t2_q_rectangle: "Rechteck",
    t3_title: "Muster & Wiederholung",
    t3_text: "Ein Muster wiederholt die gleichen Formen oder Farben der Reihe nach: Kreis, Quadrat, Kreis, Quadrat... Wenn du ein Muster siehst, kannst du erraten, was als nächstes kommt! Muster sind überall um uns herum.",
    t3_b1: "Muster wiederholen sich in Reihenfolge",
    t3_b2: "Schau, was sich wiederholt",
    t3_b3: "Erraten Sie die nächste Form im Muster",
    t3_inst: "Verschiebe 4 Blöcke, um das Muster zu vervollständigen!",
    t3_h1: "Kreis-Quadrat-Kreis-Quadrat-?",
    t3_h2: "Die nächste Form ist ein Kreis! Verschiebe 4 Kreise!",
    t3_q: "Was kommt als nächstes: rotes Quadrat, blauer Kreis, rotes Quadrat, blauer Kreis, ?",
    t3_q_red_sq: "rotes Quadrat", t3_q_blue_circ: "blauer Kreis", t3_q_red_circ: "roter Kreis", t3_q_blue_sq: "blaues Quadrat",
  },
  hu: {
    explorer_title: "Alakzatok felfedezése",
    t1_title: "Alapalakzatok",
    t1_text: "Négy alapalakzat van: háromszög (3 oldal), négyzet (4 egyenlő oldal), kör (kerek, nincs oldala) és téglalap (4 oldal, hosszabb, mint széles). Minden alakzatnak különleges jellemzői vannak!",
    t1_b1: "Háromszögnek 3 oldala és 3 sarka van",
    t1_b2: "Négyzetnek 4 egyenlő oldala és 4 sarka van",
    t1_b3: "A kör kerek, nincs oldala vagy sarka",
    t1_inst: "Számold meg a 3 háromszöget és 3 négyzetet — összesen hány alakzat?",
    t1_h1: "3 háromszög + 3 négyzet = hány?",
    t1_h2: "Számold össze őket — a válasz 6!",
    t1_q: "Hány sarka van egy háromszögnek?",
    t1_q_2: "2", t1_q_3: "3", t1_q_4: "4", t1_q_5: "5",
    t2_title: "Hol vannak az alakzatok?",
    t2_text: "Az alakzatok különböző helyeken lehetnek: FELÜL (felül), ALUL (alul), BALRA (bal oldal), JOBBRA (jobb oldal) és KÖZÉPEN (közepén). A pozíciók tanulása segít megérteni az irányokat!",
    t2_b1: "Balra = a bal oldal",
    t2_b2: "Jobbra = a jobb oldal",
    t2_b3: "Felül = fentebb; Alul = lejjebb",
    t2_inst: "Koppints a 3. pozícióra a vonalon — a közepére!",
    t2_h1: "Számolj 1-től 5-ig, találd meg a közepét",
    t2_h2: "1, 2, 3 (közepén!) — koppints a 3-ra!",
    t2_q: "Melyik alakzatnak van 4 egyenlő oldala?",
    t2_q_triangle: "háromszög", t2_q_square: "négyzet", t2_q_circle: "kör", t2_q_rectangle: "téglalap",
    t3_title: "Minták & Ismétlés",
    t3_text: "A minta ugyanazt az alakzatot vagy színt ismétli: kör, négyzet, kör, négyzet... Ha meglátod a mintát, kitalálhatod, mi jön a következő! A minták mindenütt körülöttünk vannak.",
    t3_b1: "A minták sorrendben ismétlődnek",
    t3_b2: "Nézd meg, mi ismétlődik",
    t3_b3: "Találd meg a következő alakzatot a mintában",
    t3_inst: "Mozgass 4 blokkot a minta befejezéséhez!",
    t3_h1: "Kör-négyzet-kör-négyzet-?",
    t3_h2: "A következő alakzat egy kör! Mozgass 4 kört!",
    t3_q: "Mi jön a következő: piros négyzet, kék kör, piros négyzet, kék kör, ?",
    t3_q_red_sq: "piros négyzet", t3_q_blue_circ: "kék kör", t3_q_red_circ: "piros kör", t3_q_blue_sq: "kék négyzet",
  },
  ro: {
    explorer_title: "Explorarea formelor",
    t1_title: "Forme de bază",
    t1_text: "Există patru forme de bază: triunghi (3 laturi), pătrat (4 laturi egale), cerc (rotund, fără laturi) și dreptunghi (4 laturi, mai lung decât larg). Fiecare formă are caracteristici speciale!",
    t1_b1: "Triunghiul are 3 laturi și 3 colțuri",
    t1_b2: "Pătratul are 4 laturi egale și 4 colțuri",
    t1_b3: "Cercul este rotund, fără laturi sau colțuri",
    t1_inst: "Numără 3 triunghiuri și 3 pătrate — câte forme în total?",
    t1_h1: "3 triunghiuri + 3 pătrate = câte?",
    t1_h2: "Numără-le împreună — răspunsul este 6!",
    t1_q: "Câte colțuri are un triunghi?",
    t1_q_2: "2", t1_q_3: "3", t1_q_4: "4", t1_q_5: "5",
    t2_title: "Unde sunt formele?",
    t2_text: "Formele pot fi în locuri diferite: SUS (deasupra), JOS (dedesubt), STÂNGA (stânga), DREAPTA (dreapta) și CENTRU (în mijloc). Învățarea pozițiilor ne ajută să înțelegem direcțiile!",
    t2_b1: "Stânga = partea stângă",
    t2_b2: "Dreapta = partea dreaptă",
    t2_b3: "Sus = mai sus; Jos = mai jos",
    t2_inst: "Atinge poziția 3 pe linie — mijlocul!",
    t2_h1: "Numără de la 1 la 5, găsește mijlocul",
    t2_h2: "1, 2, 3 (mijloc!) — atinge 3!",
    t2_q: "Care formă are 4 laturi egale?",
    t2_q_triangle: "triunghi", t2_q_square: "pătrat", t2_q_circle: "cerc", t2_q_rectangle: "dreptunghi",
    t3_title: "Modele & Repetare",
    t3_text: "Un model repetă aceleași forme sau culori în ordine: cerc, pătrat, cerc, pătrat... Când vezi un model, poți ghici ce vine mai departe! Modelele sunt peste tot în jurul nostru.",
    t3_b1: "Modelele se repetă în ordine",
    t3_b2: "Uită-te la ceea ce se repetă",
    t3_b3: "Ghicește următoarea formă din model",
    t3_inst: "Mută 4 blocuri pentru a completa modelul!",
    t3_h1: "Cerc-pătrat-cerc-pătrat-?",
    t3_h2: "Următoarea formă este un cerc! Mută 4 cercuri!",
    t3_q: "Ce vine mai departe: pătrat roșu, cerc albastru, pătrat roșu, cerc albastru, ?",
    t3_q_red_sq: "pătrat roșu", t3_q_blue_circ: "cerc albastru", t3_q_red_circ: "cerc roșu", t3_q_blue_sq: "pătrat albastru",
  },
};

const SHAPESEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [3, 3],
      answer: 6,
      blockIcon: "🔷",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_2", "t1_q_3", "t1_q_4", "t1_q_5"],
      answer: "t1_q_3",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 1,
      max: 5,
      start: 1,
      target: 3,
      showJumps: true,
      jumpCount: 2,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_triangle", "t2_q_square", "t2_q_circle", "t2_q_rectangle"],
      answer: "t2_q_square",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [2, 2],
      answer: 4,
      blockIcon: "🔴",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_red_sq", "t3_q_blue_circ", "t3_q_red_circ", "t3_q_blue_sq"],
      answer: "t3_q_blue_circ",
    },
  },
];

export const SHAPESEXPLORER_DEF: ExplorerDef = {
  labels: SHAPESEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: SHAPESEXPLORER_TOPICS,
  rounds: [],
};

// ─── SUBTRACTIONEXPLORER CONFIG ───

const SUBTRACTIONEXPLORER_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Subtraction Explorer",
    t1_title: "Taking Away",
    t1_text: "To subtract, we jump BACKWARDS on the number line! Start at 8, jump back 3 steps. Where do you land? 8 − 3 = 5!",
    t1_b1: "Start at the bigger number",
    t1_b2: "Jump backwards to subtract",
    t1_b3: "Where you land = the answer",
    t1_inst: "Tap number 5 on the line!",
    t1_h1: "Start at 8, jump back 3 times",
    t1_h2: "Count down: 7, 6, 5 — tap 5!",
    t1_q: "9 − 4 = ?",
    t1_q_4: "4",
    t1_q_5: "5",
    t1_q_6: "6",
    t1_q_3: "3",
    t2_title: "Cross It Out",
    t2_text: "Subtraction means taking some away! You have 7 apples, you eat 3. Cross out 3 apples. Count what's left: 7 − 3 = 4!",
    t2_b1: "Start with all the items",
    t2_b2: "Cross out the ones removed",
    t2_b3: "Count what's left = answer",
    t2_inst: "Remove 3 from 8 — how many left?",
    t2_h1: "Start with 8, take away 3",
    t2_h2: "Count remaining = 5",
    t2_q: "10 − 4 = ?",
    t2_q_5: "5",
    t2_q_6: "6",
    t2_q_7: "7",
    t2_q_4: "4",
    t3_title: "What's Missing?",
    t3_text: "How many more do you need? You have 6 dots and need 10. Count the empty spots: 6 + ? = 10. You need 4 more!",
    t3_b1: "Look at how many you have",
    t3_b2: "Count the empty spots",
    t3_b3: "That's the missing number!",
    t3_inst: "Drag 4 dots to fill the frame!",
    t3_h1: "6 filled, 4 empty",
    t3_h2: "Add 4 to reach 10!",
    t3_q: "7 + ? = 10",
    t3_q_2: "2",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_5: "5",
  },
  de: {
    explorer_title: "Subtraktion entdecken",
    t1_title: "Wegnehmen",
    t1_text: "Zum Subtrahieren springen wir RÜCKWÄRTS auf der Zahlenlinie! Starte bei 8, springe 3 Schritte zurück. Wo landest du? 8 − 3 = 5!",
    t1_b1: "Starte bei der größeren Zahl",
    t1_b2: "Springe rückwärts zum Subtrahieren",
    t1_b3: "Wo du landest = die Antwort",
    t1_inst: "Tippe auf 5 auf der Linie!",
    t1_h1: "Starte bei 8, springe 3 mal zurück",
    t1_h2: "Zähle runter: 7, 6, 5 — tippe 5!",
    t1_q: "9 − 4 = ?",
    t1_q_4: "4",
    t1_q_5: "5",
    t1_q_6: "6",
    t1_q_3: "3",
    t2_title: "Durchstreichen",
    t2_text: "Subtraktion heißt etwas wegnehmen! Du hast 7 Äpfel, du isst 3. Streiche 3 Äpfel durch. Zähle was übrig bleibt: 7 − 3 = 4!",
    t2_b1: "Starte mit allen Gegenständen",
    t2_b2: "Streiche durch was weggenommen wird",
    t2_b3: "Zähle was übrig bleibt = Antwort",
    t2_inst: "Nimm 3 von 8 weg — wie viele bleiben?",
    t2_h1: "Starte mit 8, nimm 3 weg",
    t2_h2: "Zähle übrig = 5",
    t2_q: "10 − 4 = ?",
    t2_q_5: "5",
    t2_q_6: "6",
    t2_q_7: "7",
    t2_q_4: "4",
    t3_title: "Was fehlt? (Ergänzen)",
    t3_text: "Wie viele brauchst du noch? Du hast 6 Punkte und brauchst 10. Zähle die leeren Plätze: 6 + ? = 10. Du brauchst noch 4!",
    t3_b1: "Schau wie viele du hast",
    t3_b2: "Zähle die leeren Plätze",
    t3_b3: "Das ist die fehlende Zahl!",
    t3_inst: "Ziehe 4 Punkte in den Rahmen!",
    t3_h1: "6 gefüllt, 4 leer",
    t3_h2: "Füge 4 hinzu um 10 zu erreichen!",
    t3_q: "7 + ? = 10",
    t3_q_2: "2",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_5: "5",
  },
  hu: {
    explorer_title: "Kivonás felfedezés",
    t1_title: "Elvétel",
    t1_text: "A kivonáshoz HÁTRAFELÉ ugrunk a számegyenesen! Indulj 8-tól, ugorj hátra 3 lépést. Hol érsz? 8 − 3 = 5!",
    t1_b1: "Indulj a nagyobb számtól",
    t1_b2: "Ugorj hátrafelé a kivonáshoz",
    t1_b3: "Ahol érsz = a válasz",
    t1_inst: "Koppints az 5-re a soron!",
    t1_h1: "Indulj 8-ból, ugorj hátra 3-szor",
    t1_h2: "Számolj vissza: 7, 6, 5 — koppints 5-re!",
    t1_q: "9 − 4 = ?",
    t1_q_4: "4",
    t1_q_5: "5",
    t1_q_6: "6",
    t1_q_3: "3",
    t2_title: "Húzd át!",
    t2_text: "A kivonás azt jelenti, elveszünk belőle! Van 7 almád, megeszel 3-at. Húzd át a 3 almát. Számold, ami maradt: 7 − 3 = 4!",
    t2_b1: "Kezdj az összes tárggyal",
    t2_b2: "Húzd át az elvett darabokat",
    t2_b3: "Számold a maradékot = válasz",
    t2_inst: "Vegyél 3-at a 8-ból — mennyi marad?",
    t2_h1: "Kezdj 8-tól, vegyél el 3-at",
    t2_h2: "Számold meg a maradékot = 5",
    t2_q: "10 − 4 = ?",
    t2_q_5: "5",
    t2_q_6: "6",
    t2_q_7: "7",
    t2_q_4: "4",
    t3_title: "Mi hiányzik? (Kiegészítés)",
    t3_text: "Mennyi kell még? Van 6 pontod és 10 kell. Számold az üres helyeket: 6 + ? = 10. Még 4 kell!",
    t3_b1: "Nézd meg mennyid van",
    t3_b2: "Számold az üres helyeket",
    t3_b3: "Ez a hiányzó szám!",
    t3_inst: "Húzz 4 pontot a keretbe!",
    t3_h1: "6 kitöltve, 4 üres",
    t3_h2: "Adj hozzá 4-et, hogy 10 legyen!",
    t3_q: "7 + ? = 10",
    t3_q_2: "2",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_5: "5",
  },
  ro: {
    explorer_title: "Explorare scădere",
    t1_title: "Luăm înapoi",
    t1_text: "Pentru scădere, sărim ÎNAPOI pe linia numerică! Începe la 8, sari înapoi 3 pași. Unde aterizezi? 8 − 3 = 5!",
    t1_b1: "Începe la numărul mai mare",
    t1_b2: "Sari înapoi pentru a scădea",
    t1_b3: "Unde aterizezi = răspunsul",
    t1_inst: "Atingi 5 pe linie!",
    t1_h1: "Începe la 8, sari înapoi de 3 ori",
    t1_h2: "Numără înapoi: 7, 6, 5 — atingi 5!",
    t1_q: "9 − 4 = ?",
    t1_q_4: "4",
    t1_q_5: "5",
    t1_q_6: "6",
    t1_q_3: "3",
    t2_title: "Taie-le!",
    t2_text: "Scăderea înseamnă a lua din ele! Ai 7 mere, mănânci 3. Taie 3 mere. Numără ce a rămas: 7 − 3 = 4!",
    t2_b1: "Începe cu toate obiectele",
    t2_b2: "Taie-le pe cele scoase",
    t2_b3: "Numără ce a rămas = răspunsul",
    t2_inst: "Ia 3 din 8 — câte rămân?",
    t2_h1: "Începe cu 8, ia 3",
    t2_h2: "Numără rămase = 5",
    t2_q: "10 − 4 = ?",
    t2_q_5: "5",
    t2_q_6: "6",
    t2_q_7: "7",
    t2_q_4: "4",
    t3_title: "Ce lipsește? (Completare)",
    t3_text: "Câte mai trebuie? Ai 6 puncte și ai nevoie de 10. Numără locurile goale: 6 + ? = 10. Mai ai nevoie de 4!",
    t3_b1: "Uită-te câte ai",
    t3_b2: "Numără locurile goale",
    t3_b3: "Acesta este numărul lipsă!",
    t3_inst: "Trage 4 puncte în cadru!",
    t3_h1: "6 completate, 4 goale",
    t3_h2: "Adaugă 4 pentru a ajunge la 10!",
    t3_q: "7 + ? = 10",
    t3_q_2: "2",
    t3_q_3: "3",
    t3_q_4: "4",
    t3_q_5: "5",
  },
};

const SUBTRACTIONEXPLORER_TOPICS: TopicDef[] = [] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => null,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 8,
      target: 5,
      showJumps: true,
      jumpCount: 3,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_3", "t1_q_4", "t1_q_5", "t1_q_6"],
      answer: "t1_q_5",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => null,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "block-drag",
      mode: "split",
      groups: [8, 3],
      answer: 5,
      blockIcon: "🍎",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_4", "t2_q_5", "t2_q_6", "t2_q_7"],
      answer: "t2_q_6",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => null,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "block-drag",
      mode: "combine",
      groups: [6, 4],
      answer: 10,
      blockIcon: "🔴",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_2", "t3_q_3", "t3_q_4", "t3_q_5"],
      answer: "t3_q_3",
    },
  },
];

export const SUBTRACTIONEXPLORER_DEF: ExplorerDef = {
  labels: SUBTRACTIONEXPLORER_LABELS,
  title: "explorer_title",
  icon: "🚀",
  topics: SUBTRACTIONEXPLORER_TOPICS,
  rounds: [],
};

