import type {
  ExplorerDef,
  TopicDef,
} from "@/app/astro-biologie/games/ExplorerEngine";

const SqrtVisual = ({
  expression,
  result,
}: {
  expression: string;
  result?: string;
}) => (
  <svg
    viewBox="0 0 360 150"
    className="mx-auto h-auto w-full max-w-sm"
    role="img"
    aria-label={result ? `${expression} = ${result}` : expression}
  >
    <defs>
      <linearGradient id="sqrt-card" x1="0" y1="0" x2="1" y2="1">
        <stop stopColor="#A855F7" stopOpacity="0.35" />
        <stop offset="1" stopColor="#38BDF8" stopOpacity="0.18" />
      </linearGradient>
    </defs>
    <rect
      x="12"
      y="12"
      width="336"
      height="126"
      rx="28"
      fill="url(#sqrt-card)"
      stroke="#C084FC"
      strokeWidth="2"
    />
    <text
      x="180"
      y="91"
      textAnchor="middle"
      fill="white"
      fontSize="42"
      fontWeight="800"
    >
      {expression}
      {result ? ` = ${result}` : ""}
    </text>
  </svg>
);

const SQRTEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Discover square roots",
    t1_title: "Square numbers and roots",
    t1_text:
      "A square root reverses squaring. Because 7 x 7 = 49, the principal square root of 49 is 7.",
    t1_b1: "The symbol is √.",
    t1_b2: "√49 = 7 because 7² = 49.",
    t1_b3: "The principal square root is never negative.",
    t1_inst: "Match each square number with its square root.",
    t1_h1: "Think: which number multiplied by itself gives the value?",
    t1_h2: "For example, 6 x 6 = 36.",
    n16: "16",
    n25: "25",
    n36: "36",
    n64: "64",
    n4: "4",
    n5: "5",
    n6: "6",
    n8: "8",
    t1_q: "What is √81?",
    a9: "9",
    a8: "8",
    a18: "18",
    a40: "40",
    t2_title: "Estimating a square root",
    t2_text:
      "If a number is not a perfect square, locate it between two neighboring square numbers. Since 25 < 30 < 36, √30 lies between 5 and 6.",
    t2_b1: "5² = 25",
    t2_b2: "6² = 36",
    t2_b3: "Therefore 5 < √30 < 6.",
    t2_inst:
      "Tap the upper whole-number bound for √30 on the number line.",
    t2_h1: "Compare 30 with 25 and 36.",
    t2_h2: "√30 is greater than 5, so its upper whole-number bound is 6.",
    t2_q: "Between which whole numbers is √70?",
    a8_9: "8 and 9",
    a7_8: "7 and 8",
    a9_10: "9 and 10",
    a6_7: "6 and 7",
    t3_title: "Calculating with roots",
    t3_text:
      "Calculate square roots before addition or subtraction. For √64 - √16, first find 8 and 4, then subtract.",
    t3_b1: "√64 = 8",
    t3_b2: "√16 = 4",
    t3_b3: "So √64 - √16 = 4.",
    t3_inst: "Complete the expression: √81 + √25 = ___.",
    t3_sentence: "√81 + √25 = ___",
    t3_h1: "Find both roots first.",
    t3_h2: "9 + 5 = 14.",
    a14: "14",
    a12: "12",
    a16: "16",
    a20: "20",
    t3_q: "What is √100 - √36?",
    a4: "4",
    a6: "6",
    a8b: "8",
    a64: "64",
  },
  de: {
    explorer_title: "Quadratwurzeln entdecken",
    t1_title: "Quadratzahlen und Wurzeln",
    t1_text:
      "Die Quadratwurzel macht das Quadrieren rückgängig. Weil 7 x 7 = 49 gilt, ist die Hauptwurzel aus 49 gleich 7.",
    t1_b1: "Das Wurzelzeichen ist √.",
    t1_b2: "√49 = 7, weil 7² = 49.",
    t1_b3: "Die Hauptwurzel ist nie negativ.",
    t1_inst: "Ordne jeder Quadratzahl ihre Quadratwurzel zu.",
    t1_h1: "Welche Zahl ergibt mit sich selbst multipliziert den Wert?",
    t1_h2: "Zum Beispiel: 6 x 6 = 36.",
    n16: "16",
    n25: "25",
    n36: "36",
    n64: "64",
    n4: "4",
    n5: "5",
    n6: "6",
    n8: "8",
    t1_q: "Wie viel ist √81?",
    a9: "9",
    a8: "8",
    a18: "18",
    a40: "40",
    t2_title: "Eine Quadratwurzel abschätzen",
    t2_text:
      "Ist eine Zahl keine Quadratzahl, ordne sie zwischen zwei benachbarten Quadratzahlen ein. Weil 25 < 30 < 36 gilt, liegt √30 zwischen 5 und 6.",
    t2_b1: "5² = 25",
    t2_b2: "6² = 36",
    t2_b3: "Also gilt 5 < √30 < 6.",
    t2_inst:
      "Tippe auf die obere ganze Zahl als Schranke für √30 auf dem Zahlenstrahl.",
    t2_h1: "Vergleiche 30 mit 25 und 36.",
    t2_h2: "√30 ist größer als 5, also ist die obere ganze Schranke 6.",
    t2_q: "Zwischen welchen ganzen Zahlen liegt √70?",
    a8_9: "8 und 9",
    a7_8: "7 und 8",
    a9_10: "9 und 10",
    a6_7: "6 und 7",
    t3_title: "Mit Wurzeln rechnen",
    t3_text:
      "Berechne die Quadratwurzeln vor der Addition oder Subtraktion. Bei √64 - √16 bestimmst du zuerst 8 und 4 und subtrahierst dann.",
    t3_b1: "√64 = 8",
    t3_b2: "√16 = 4",
    t3_b3: "Also ist √64 - √16 = 4.",
    t3_inst: "Vervollständige den Ausdruck: √81 + √25 = ___.",
    t3_sentence: "√81 + √25 = ___",
    t3_h1: "Berechne zuerst beide Wurzeln.",
    t3_h2: "9 + 5 = 14.",
    a14: "14",
    a12: "12",
    a16: "16",
    a20: "20",
    t3_q: "Wie viel ist √100 - √36?",
    a4: "4",
    a6: "6",
    a8b: "8",
    a64: "64",
  },
  hu: {
    explorer_title: "Négyzetgyökök felfedezése",
    t1_title: "Négyzetszámok és gyökök",
    t1_text:
      "A négyzetgyökvonás a négyzetre emelés fordítottja. Mivel 7 x 7 = 49, ezért 49 fő négyzetgyöke 7.",
    t1_b1: "A négyzetgyök jele: √.",
    t1_b2: "√49 = 7, mert 7² = 49.",
    t1_b3: "A fő négyzetgyök soha nem negatív.",
    t1_inst: "Párosítsd a négyzetszámokat a négyzetgyökükkel.",
    t1_h1: "Melyik szám önmagával szorozva adja az értéket?",
    t1_h2: "Például: 6 x 6 = 36.",
    n16: "16",
    n25: "25",
    n36: "36",
    n64: "64",
    n4: "4",
    n5: "5",
    n6: "6",
    n8: "8",
    t1_q: "Mennyi √81?",
    a9: "9",
    a8: "8",
    a18: "18",
    a40: "40",
    t2_title: "Négyzetgyök becslése",
    t2_text:
      "Ha egy szám nem négyzetszám, keresd meg a két szomszédos négyzetszámot. Mivel 25 < 30 < 36, ezért √30 értéke 5 és 6 között van.",
    t2_b1: "5² = 25",
    t2_b2: "6² = 36",
    t2_b3: "Tehát 5 < √30 < 6.",
    t2_inst:
      "Koppints √30 felső egész korlátjára a számegyenesen.",
    t2_h1: "Hasonlítsd össze a 30-at a 25-tel és a 36-tal.",
    t2_h2: "√30 nagyobb 5-nél, ezért a felső egész korlát 6.",
    t2_q: "Mely egész számok között van √70?",
    a8_9: "8 és 9",
    a7_8: "7 és 8",
    a9_10: "9 és 10",
    a6_7: "6 és 7",
    t3_title: "Műveletek gyökökkel",
    t3_text:
      "Összeadás vagy kivonás előtt számítsd ki a négyzetgyököket. A √64 - √16 esetén előbb 8-at és 4-et kapsz, majd kivonsz.",
    t3_b1: "√64 = 8",
    t3_b2: "√16 = 4",
    t3_b3: "Ezért √64 - √16 = 4.",
    t3_inst: "Egészítsd ki: √81 + √25 = ___.",
    t3_sentence: "√81 + √25 = ___",
    t3_h1: "Először számítsd ki mindkét gyököt.",
    t3_h2: "9 + 5 = 14.",
    a14: "14",
    a12: "12",
    a16: "16",
    a20: "20",
    t3_q: "Mennyi √100 - √36?",
    a4: "4",
    a6: "6",
    a8b: "8",
    a64: "64",
  },
  ro: {
    explorer_title: "Descoperă rădăcinile pătrate",
    t1_title: "Pătrate perfecte și rădăcini",
    t1_text:
      "Rădăcina pătrată inversează ridicarea la pătrat. Deoarece 7 x 7 = 49, rădăcina pătrată principală a lui 49 este 7.",
    t1_b1: "Simbolul este √.",
    t1_b2: "√49 = 7, deoarece 7² = 49.",
    t1_b3: "Rădăcina pătrată principală nu este negativă.",
    t1_inst: "Asociază fiecare pătrat perfect cu rădăcina sa.",
    t1_h1: "Ce număr înmulțit cu el însuși dă valoarea?",
    t1_h2: "De exemplu: 6 x 6 = 36.",
    n16: "16",
    n25: "25",
    n36: "36",
    n64: "64",
    n4: "4",
    n5: "5",
    n6: "6",
    n8: "8",
    t1_q: "Cât este √81?",
    a9: "9",
    a8: "8",
    a18: "18",
    a40: "40",
    t2_title: "Estimarea unei rădăcini",
    t2_text:
      "Dacă numărul nu este pătrat perfect, așază-l între două pătrate vecine. Deoarece 25 < 30 < 36, √30 este între 5 și 6.",
    t2_b1: "5² = 25",
    t2_b2: "6² = 36",
    t2_b3: "Așadar 5 < √30 < 6.",
    t2_inst:
      "Atinge limita superioară întreagă pentru √30 pe axa numerelor.",
    t2_h1: "Compară 30 cu 25 și 36.",
    t2_h2: "√30 este mai mare decât 5, deci limita sa superioară întreagă este 6.",
    t2_q: "Între ce numere întregi se află √70?",
    a8_9: "8 și 9",
    a7_8: "7 și 8",
    a9_10: "9 și 10",
    a6_7: "6 și 7",
    t3_title: "Calcule cu rădăcini",
    t3_text:
      "Calculează rădăcinile înainte de adunare sau scădere. Pentru √64 - √16, găsești mai întâi 8 și 4, apoi scazi.",
    t3_b1: "√64 = 8",
    t3_b2: "√16 = 4",
    t3_b3: "Deci √64 - √16 = 4.",
    t3_inst: "Completează: √81 + √25 = ___.",
    t3_sentence: "√81 + √25 = ___",
    t3_h1: "Calculează mai întâi ambele rădăcini.",
    t3_h2: "9 + 5 = 14.",
    a14: "14",
    a12: "12",
    a16: "16",
    a20: "20",
    t3_q: "Cât este √100 - √36?",
    a4: "4",
    a6: "6",
    a8b: "8",
    a64: "64",
  },
};

const SQRTEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <SqrtVisual expression="√49" result="7" />,
    bulletKeys: ["t1_b1", "t1_b2", "t1_b3"],
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "n16", right: "n4" },
        { left: "n25", right: "n5" },
        { left: "n36", right: "n6" },
        { left: "n64", right: "n8" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["a9", "a8", "a18", "a40"],
      answer: "a9",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => <SqrtVisual expression="5 < √30 < 6" />,
    bulletKeys: ["t2_b1", "t2_b2", "t2_b3"],
    interactive: {
      type: "number-line",
      min: 0,
      max: 10,
      start: 0,
      target: 6,
      step: 1,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["a8_9", "a7_8", "a9_10", "a6_7"],
      answer: "a8_9",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => <SqrtVisual expression="√64 - √16" result="4" />,
    bulletKeys: ["t3_b1", "t3_b2", "t3_b3"],
    interactive: {
      type: "gap-fill",
      sentence: "t3_sentence",
      choices: ["a14", "a12", "a16", "a20"],
      correctIndex: 0,
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["a4", "a6", "a8b", "a64"],
      answer: "a4",
    },
  },
];

const LessonCard = ({
  accent,
  headline,
  lines,
}: {
  accent: string;
  headline: string;
  lines: string[];
}) => (
  <svg
    viewBox="0 0 360 180"
    className="mx-auto h-auto w-full max-w-sm"
    role="img"
    aria-label={headline}
  >
    <rect x="12" y="12" width="336" height="156" rx="24" fill="#0f172a" stroke={accent} strokeWidth="2" />
    <text x="180" y="48" textAnchor="middle" fill="white" fontSize="22" fontWeight="800">
      {headline}
    </text>
    {lines.map((line, index) => (
      <text
        key={`${headline}-${index}`}
        x="40"
        y={88 + index * 24}
        fill="white"
        fontSize="16"
        fontWeight="600"
      >
        {line}
      </text>
    ))}
  </svg>
);

const PlaneCard = ({
  accent,
  caption,
  points,
}: {
  accent: string;
  caption: string;
  points: { x: number; y: number; label: string }[];
}) => {
  const size = 320;
  const pad = 36;
  const range = 5;
  const plot = size - pad * 2;
  const step = plot / (range * 2);
  const origin = size / 2;
  const px = (value: number) => origin + value * step;
  const py = (value: number) => origin - value * step;

  return (
    <svg
      viewBox={`0 0 ${size} ${size}`}
      className="mx-auto h-auto w-full max-w-sm"
      role="img"
      aria-label={caption}
    >
      <rect x="10" y="10" width={size - 20} height={size - 20} rx="24" fill="#0f172a" stroke={accent} strokeWidth="2" />
      {Array.from({ length: range * 2 + 1 }).map((_, index) => {
        const pos = pad + index * step;
        const axis = index === range;
        return (
          <g key={index}>
            <line x1={pos} y1={pad} x2={pos} y2={size - pad} stroke={axis ? "#94a3b8" : "#334155"} strokeWidth={axis ? 1.6 : 0.7} />
            <line x1={pad} y1={pos} x2={size - pad} y2={pos} stroke={axis ? "#94a3b8" : "#334155"} strokeWidth={axis ? 1.6 : 0.7} />
          </g>
        );
      })}
      <text x={size / 2} y="28" textAnchor="middle" fill="white" fontSize="15" fontWeight="700">
        {caption}
      </text>
      {points.map((point) => (
        <g key={point.label}>
          <circle cx={px(point.x)} cy={py(point.y)} r="7" fill={accent} />
          <text x={px(point.x) + 10} y={py(point.y) - 10} fill="white" fontSize="13" fontWeight="700">
            {point.label}
          </text>
        </g>
      ))}
    </svg>
  );
};

function buildDef(
  labels: Record<string, Record<string, string>>,
  icon: string,
  topics: TopicDef[],
): ExplorerDef {
  return {
    labels,
    title: "explorer_title",
    icon,
    topics,
    rounds: [],
  };
}

const EQUATIONEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Equations and inequalities",
    t1_title: "One-step equations",
    t1_text: "Undo the operation around x. In x + 7 = 19, subtract 7 from both sides.",
    t1_b1: "Use inverse operations.",
    t1_b2: "Check by substitution.",
    t1_inst: "Complete: x + 7 = 19, so x = ___.",
    t1_h1: "Subtract 7 from 19.",
    t1_h2: "19 - 7 = 12.",
    t1_sentence: "x + 7 = 19, so x = ___",
    t1_a1: "12",
    t1_a2: "26",
    t1_a3: "11",
    t1_a4: "7",
    t1_q: "Which value solves x - 9 = 4?",
    t1_q_a1: "13",
    t1_q_a2: "5",
    t1_q_a3: "-5",
    t1_q_a4: "9",
    t2_title: "Equations on both sides",
    t2_text: "Collect x terms on one side and number terms on the other side.",
    t2_b1: "Keep the equation balanced.",
    t2_b2: "Solve the simpler equation at the end.",
    t2_inst: "Solve 3x + 2 = x + 10.",
    t2_step1: "Subtract x from both sides. What is 3x - x?",
    t2_step2: "Now solve 2x = 8. What is x?",
    t2_h1: "3x - x becomes 2x.",
    t2_h2: "Divide 8 by 2 to get 4.",
    t2_q: "Solve 5x - 3 = 2x + 12.",
    t2_q_a1: "5",
    t2_q_a2: "3",
    t2_q_a3: "15",
    t2_q_a4: "4",
    t3_title: "Fractions and inequalities",
    t3_text: "For fractional equations, clear the denominator. For inequalities, test which numbers make the statement true.",
    t3_b1: "x / 2 > 6 means x > 12.",
    t3_b2: "Only true values belong in the solution set.",
    t3_inst: "Sort the numbers for x / 2 > 6.",
    t3_h1: "Multiply both sides by 2.",
    t3_h2: "Only numbers greater than 12 work.",
    t3_yes: "solution",
    t3_no: "not solution",
    t3_i1: "9",
    t3_i2: "12",
    t3_i3: "13",
    t3_i4: "16",
    t3_q: "Solve x / 3 = 5.",
    t3_q_a1: "15",
    t3_q_a2: "8",
    t3_q_a3: "2",
    t3_q_a4: "20",
  },
  de: {
    explorer_title: "Gleichungen und Ungleichungen",
    t1_title: "Ein-Schritt-Gleichungen",
    t1_text: "Mache die Rechenoperation bei x rueckgaengig. Bei x + 7 = 19 ziehst du 7 ab.",
    t1_b1: "Nutze Umkehroperationen.",
    t1_b2: "Pruefe durch Einsetzen.",
    t1_inst: "Ergaenze: x + 7 = 19, also x = ___.",
    t1_h1: "Ziehe 7 von 19 ab.",
    t1_h2: "19 - 7 = 12.",
    t1_sentence: "x + 7 = 19, also x = ___",
    t1_a1: "12",
    t1_a2: "26",
    t1_a3: "11",
    t1_a4: "7",
    t1_q: "Welcher Wert loest x - 9 = 4?",
    t1_q_a1: "13",
    t1_q_a2: "5",
    t1_q_a3: "-5",
    t1_q_a4: "9",
    t2_title: "Gleichungen auf beiden Seiten",
    t2_text: "Bringe die x-Terme auf eine Seite und die Zahlen auf die andere Seite.",
    t2_b1: "Halte die Gleichung im Gleichgewicht.",
    t2_b2: "Loese am Ende die einfachere Gleichung.",
    t2_inst: "Loese 3x + 2 = x + 10.",
    t2_step1: "Subtrahiere x auf beiden Seiten. Was ist 3x - x?",
    t2_step2: "Loese nun 2x = 8. Was ist x?",
    t2_h1: "3x - x wird zu 2x.",
    t2_h2: "Teile 8 durch 2 und erhalte 4.",
    t2_q: "Loese 5x - 3 = 2x + 12.",
    t2_q_a1: "5",
    t2_q_a2: "3",
    t2_q_a3: "15",
    t2_q_a4: "4",
    t3_title: "Brueche und Ungleichungen",
    t3_text: "Bei Bruchgleichungen beseitigst du den Nenner. Bei Ungleichungen pruefst du passende Zahlen.",
    t3_b1: "x / 2 > 6 bedeutet x > 12.",
    t3_b2: "Nur wahre Werte gehoeren zur Loesungsmenge.",
    t3_inst: "Sortiere die Zahlen fuer x / 2 > 6.",
    t3_h1: "Multipliziere beide Seiten mit 2.",
    t3_h2: "Nur Zahlen groesser als 12 passen.",
    t3_yes: "Loesung",
    t3_no: "keine Loesung",
    t3_i1: "9",
    t3_i2: "12",
    t3_i3: "13",
    t3_i4: "16",
    t3_q: "Loese x / 3 = 5.",
    t3_q_a1: "15",
    t3_q_a2: "8",
    t3_q_a3: "2",
    t3_q_a4: "20",
  },
  hu: {
    explorer_title: "Egyenletek es egyenlotlensegek",
    t1_title: "Egy lepeses egyenletek",
    t1_text: "Forditsd vissza az x melletti muveletet. Az x + 7 = 19 egyenletben 7-et vonunk ki.",
    t1_b1: "Hasznalj ellentetes muveletet.",
    t1_b2: "Helyettesitessel ellenorizz.",
    t1_inst: "Egészitsd ki: x + 7 = 19, tehat x = ___.",
    t1_h1: "Vond ki a 7-et 19-bol.",
    t1_h2: "19 - 7 = 12.",
    t1_sentence: "x + 7 = 19, tehat x = ___",
    t1_a1: "12",
    t1_a2: "26",
    t1_a3: "11",
    t1_a4: "7",
    t1_q: "Melyik ertek oldja meg az x - 9 = 4 egyenletet?",
    t1_q_a1: "13",
    t1_q_a2: "5",
    t1_q_a3: "-5",
    t1_q_a4: "9",
    t2_title: "Ket oldalon szereplo egyenletek",
    t2_text: "Gyujtsd az x-es tagokat az egyik oldalra, a szamokat a masikra.",
    t2_b1: "Maradjon egyensulyban az egyenlet.",
    t2_b2: "A vegul kapott egyszerubb egyenletet oldd meg.",
    t2_inst: "Oldd meg: 3x + 2 = x + 10.",
    t2_step1: "Vond ki az x-et mindket oldalbol. Mennyi 3x - x?",
    t2_step2: "Most oldd meg a 2x = 8 egyenletet. Mennyi x?",
    t2_h1: "3x - x = 2x.",
    t2_h2: "8-at 2-vel osztva 4-et kapsz.",
    t2_q: "Oldd meg: 5x - 3 = 2x + 12.",
    t2_q_a1: "5",
    t2_q_a2: "3",
    t2_q_a3: "15",
    t2_q_a4: "4",
    t3_title: "Tortes egyenletek es egyenlotlensegek",
    t3_text: "Tuntesd el a nevezot, majd nezd meg, mely szamok teszik igazza az allitast.",
    t3_b1: "x / 2 > 6 ugyanaz, mint x > 12.",
    t3_b2: "Csak az igaz ertekek jo megoldasok.",
    t3_inst: "Rendezd a szamokat az x / 2 > 6 allitashoz.",
    t3_h1: "Szorozd meg mindket oldalt 2-vel.",
    t3_h2: "Csak a 12-nel nagyobb szamok jok.",
    t3_yes: "megoldas",
    t3_no: "nem megoldas",
    t3_i1: "9",
    t3_i2: "12",
    t3_i3: "13",
    t3_i4: "16",
    t3_q: "Oldd meg: x / 3 = 5.",
    t3_q_a1: "15",
    t3_q_a2: "8",
    t3_q_a3: "2",
    t3_q_a4: "20",
  },
  ro: {
    explorer_title: "Ecuatii si inegalitati",
    t1_title: "Ecuatii cu un pas",
    t1_text: "Anuleaza operatia din jurul lui x. In x + 7 = 19, scazi 7 din ambele parti.",
    t1_b1: "Foloseste operatii inverse.",
    t1_b2: "Verifica prin inlocuire.",
    t1_inst: "Completeaza: x + 7 = 19, deci x = ___.",
    t1_h1: "Scade 7 din 19.",
    t1_h2: "19 - 7 = 12.",
    t1_sentence: "x + 7 = 19, deci x = ___",
    t1_a1: "12",
    t1_a2: "26",
    t1_a3: "11",
    t1_a4: "7",
    t1_q: "Ce valoare rezolva x - 9 = 4?",
    t1_q_a1: "13",
    t1_q_a2: "5",
    t1_q_a3: "-5",
    t1_q_a4: "9",
    t2_title: "Ecuatii pe ambele parti",
    t2_text: "Strange termenii cu x pe o parte si numerele pe cealalta parte.",
    t2_b1: "Pastreaza egalitatea echilibrata.",
    t2_b2: "Rezolva ecuatia mai simpla de la final.",
    t2_inst: "Rezolva 3x + 2 = x + 10.",
    t2_step1: "Scade x din ambele parti. Cat este 3x - x?",
    t2_step2: "Acum rezolva 2x = 8. Cat este x?",
    t2_h1: "3x - x devine 2x.",
    t2_h2: "8 impartit la 2 da 4.",
    t2_q: "Rezolva 5x - 3 = 2x + 12.",
    t2_q_a1: "5",
    t2_q_a2: "3",
    t2_q_a3: "15",
    t2_q_a4: "4",
    t3_title: "Fractii si inegalitati",
    t3_text: "Elimina numitorul si apoi vezi ce numere fac adevarata afirmatia.",
    t3_b1: "x / 2 > 6 inseamna x > 12.",
    t3_b2: "Doar valorile adevarate sunt solutii.",
    t3_inst: "Sorteaza numerele pentru x / 2 > 6.",
    t3_h1: "Inmulteste ambele parti cu 2.",
    t3_h2: "Doar numerele mai mari decat 12 merg.",
    t3_yes: "solutie",
    t3_no: "nu este solutie",
    t3_i1: "9",
    t3_i2: "12",
    t3_i3: "13",
    t3_i4: "16",
    t3_q: "Rezolva x / 3 = 5.",
    t3_q_a1: "15",
    t3_q_a2: "8",
    t3_q_a3: "2",
    t3_q_a4: "20",
  },
};

const EQUATIONEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <LessonCard accent="#10B981" headline="x + 7 = 19" lines={["subtract 7", "x = 12"]} />,
    bulletKeys: ["t1_b1", "t1_b2"],
    interactive: {
      type: "gap-fill",
      sentence: "t1_sentence",
      choices: ["t1_a1", "t1_a2", "t1_a3", "t1_a4"],
      correctIndex: 0,
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"],
      answer: "t1_q_a1",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => <LessonCard accent="#10B981" headline="3x + 2 = x + 10" lines={["2x = 8", "x = 4"]} />,
    bulletKeys: ["t2_b1", "t2_b2"],
    interactive: {
      type: "equation-solver",
      equation: "3x + 2 = x + 10",
      steps: [
        { instruction: "t2_step1", choices: [1, 2, 3, 4], answer: 2, equation: "2x = 8" },
        { instruction: "t2_step2", choices: [2, 4, 6, 8], answer: 4, equation: "x = 4" },
      ],
      finalAnswer: 4,
      variable: "x",
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"],
      answer: "t2_q_a1",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => <LessonCard accent="#10B981" headline="x / 2 > 6" lines={["multiply by 2", "x > 12"]} />,
    bulletKeys: ["t3_b1", "t3_b2"],
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "yes", label: "t3_yes" },
        { id: "no", label: "t3_no" },
      ],
      items: [
        { text: "t3_i1", bucketId: "no" },
        { text: "t3_i2", bucketId: "no" },
        { text: "t3_i3", bucketId: "yes" },
        { text: "t3_i4", bucketId: "yes" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"],
      answer: "t3_q_a1",
    },
  },
];

export const EQUATIONEXPLORER8_DEF: ExplorerDef = buildDef(
  EQUATIONEXPLORER8_LABELS,
  "=",
  EQUATIONEXPLORER8_TOPICS,
);
const FUNCTIONEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Linear functions",
    t1_title: "Read values from a rule",
    t1_text: "For y = 2x + 1, double x and then add 1.",
    t1_b1: "Substitute the x-value into the rule.",
    t1_b2: "The graph of a linear function is a straight line.",
    t1_inst: "Use the graph of y = 2x + 1. Tap the y-value when x = 4.",
    t1_h1: "Double 4 first.",
    t1_h2: "2 * 4 + 1 = 9.",
    t1_q: "For f(x) = 2x + 1, what is f(-2)?",
    t1_q_a1: "-3",
    t1_q_a2: "-5",
    t1_q_a3: "3",
    t1_q_a4: "5",
    t2_title: "Slope means change",
    t2_text: "Slope tells how much y changes when x increases by 1.",
    t2_b1: "Positive slope rises to the right.",
    t2_b2: "Negative slope falls to the right.",
    t2_inst: "Match each change pattern with its slope.",
    t2_h1: "Rise means change in y and run means change in x.",
    t2_h2: "If the line goes down, the slope is negative.",
    t2_l1: "rise 2, run 1",
    t2_r1: "slope 2",
    t2_l2: "rise 1, run 2",
    t2_r2: "slope 1/2",
    t2_l3: "down 3, right 1",
    t2_r3: "slope -3",
    t2_l4: "horizontal line",
    t2_r4: "slope 0",
    t2_q: "Which slope means the line falls 2 units when x increases by 1?",
    t2_q_a1: "-2",
    t2_q_a2: "2",
    t2_q_a3: "1/2",
    t2_q_a4: "0",
    t3_title: "Slope-intercept form",
    t3_text: "In y = mx + b, m is the slope and b is the y-intercept.",
    t3_b1: "The coefficient of x is the slope.",
    t3_b2: "The constant term is the y-intercept.",
    t3_inst: "Sort the parts of y = -3x + 5.",
    t3_h1: "The x coefficient tells the steepness.",
    t3_h2: "The constant gives the value when x = 0.",
    t3_slope: "slope",
    t3_intercept: "y-intercept",
    t3_i1: "-3",
    t3_i2: "5",
    t3_i3: "coefficient of x",
    t3_i4: "value when x = 0",
    t3_q: "Which equation has slope 2 and y-intercept -1?",
    t3_q_a1: "y = 2x - 1",
    t3_q_a2: "y = -x + 2",
    t3_q_a3: "y = x + 1",
    t3_q_a4: "y = 2 - x",
  },
  de: {
    explorer_title: "Lineare Funktionen",
    t1_title: "Werte aus einer Regel lesen",
    t1_text: "Bei y = 2x + 1 verdoppelst du x und addierst dann 1.",
    t1_b1: "Setze den x-Wert in die Regel ein.",
    t1_b2: "Der Graph einer linearen Funktion ist eine Gerade.",
    t1_inst: "Nutze den Graphen von y = 2x + 1. Tippe den y-Wert bei x = 4.",
    t1_h1: "Verdopple zuerst die 4.",
    t1_h2: "2 * 4 + 1 = 9.",
    t1_q: "Fuer f(x) = 2x + 1: Was ist f(-2)?",
    t1_q_a1: "-3",
    t1_q_a2: "-5",
    t1_q_a3: "3",
    t1_q_a4: "5",
    t2_title: "Steigung bedeutet Aenderung",
    t2_text: "Die Steigung zeigt, wie stark y waechst oder faellt, wenn x um 1 steigt.",
    t2_b1: "Positive Steigung steigt nach rechts.",
    t2_b2: "Negative Steigung faellt nach rechts.",
    t2_inst: "Ordne jedem Veraenderungsmuster die Steigung zu.",
    t2_h1: "Anstieg ist die y-Aenderung, Lauf die x-Aenderung.",
    t2_h2: "Wenn die Linie faellt, ist die Steigung negativ.",
    t2_l1: "hoch 2, rechts 1",
    t2_r1: "Steigung 2",
    t2_l2: "hoch 1, rechts 2",
    t2_r2: "Steigung 1/2",
    t2_l3: "runter 3, rechts 1",
    t2_r3: "Steigung -3",
    t2_l4: "waagerechte Linie",
    t2_r4: "Steigung 0",
    t2_q: "Welche Steigung bedeutet, dass die Linie pro Schritt nach rechts um 2 faellt?",
    t2_q_a1: "-2",
    t2_q_a2: "2",
    t2_q_a3: "1/2",
    t2_q_a4: "0",
    t3_title: "Form y = mx + b",
    t3_text: "In y = mx + b ist m die Steigung und b der y-Achsenabschnitt.",
    t3_b1: "Der Koeffizient von x ist die Steigung.",
    t3_b2: "Der konstante Term ist der y-Achsenabschnitt.",
    t3_inst: "Sortiere die Teile von y = -3x + 5.",
    t3_h1: "Der x-Koeffizient zeigt die Steilheit.",
    t3_h2: "Die Konstante gibt den Wert bei x = 0.",
    t3_slope: "Steigung",
    t3_intercept: "y-Achsenabschnitt",
    t3_i1: "-3",
    t3_i2: "5",
    t3_i3: "Koeffizient von x",
    t3_i4: "Wert bei x = 0",
    t3_q: "Welche Gleichung hat die Steigung 2 und den y-Achsenabschnitt -1?",
    t3_q_a1: "y = 2x - 1",
    t3_q_a2: "y = -x + 2",
    t3_q_a3: "y = x + 1",
    t3_q_a4: "y = 2 - x",
  },
  hu: {
    explorer_title: "Linearis fuggvenyek",
    t1_title: "Ertekek leolvasasa",
    t1_text: "Az y = 2x + 1 szabaly szerint x-et megduplazod, majd 1-et adsz hozza.",
    t1_b1: "Helyettesitsd be az x erteket a szabalyba.",
    t1_b2: "A linearis fuggveny grafikonja egyenes.",
    t1_inst: "Hasznald az y = 2x + 1 grafikont. Koppints a y ertekre, ha x = 4.",
    t1_h1: "Eloszor duplazd meg a 4-et.",
    t1_h2: "2 * 4 + 1 = 9.",
    t1_q: "Ha f(x) = 2x + 1, mennyi f(-2)?",
    t1_q_a1: "-3",
    t1_q_a2: "-5",
    t1_q_a3: "3",
    t1_q_a4: "5",
    t2_title: "A meredekseg valtozast jelent",
    t2_text: "A meredekseg megmutatja, mennyit valtozik y, ha x eggyel no.",
    t2_b1: "A pozitiv meredekseg jobbra felfele megy.",
    t2_b2: "A negativ meredekseg jobbra lefele megy.",
    t2_inst: "Parositsd a valtozasi mintat a meredekseggel.",
    t2_h1: "Az emelkedes a y valtozasa, az elmozdulas az x valtozasa.",
    t2_h2: "Ha az egyenes lefele megy, a meredekseg negativ.",
    t2_l1: "fel 2, jobbra 1",
    t2_r1: "meredekseg 2",
    t2_l2: "fel 1, jobbra 2",
    t2_r2: "meredekseg 1/2",
    t2_l3: "le 3, jobbra 1",
    t2_r3: "meredekseg -3",
    t2_l4: "vizszintes egyenes",
    t2_r4: "meredekseg 0",
    t2_q: "Melyik meredekseg jelenti, hogy az egyenes jobbra egyet lepve 2-t esik?",
    t2_q_a1: "-2",
    t2_q_a2: "2",
    t2_q_a3: "1/2",
    t2_q_a4: "0",
    t3_title: "y = mx + b alak",
    t3_text: "Az y = mx + b alakban m a meredekseg es b az y-tengelymetszet.",
    t3_b1: "Az x egyutthatoja a meredekseg.",
    t3_b2: "Az allando tag az y-tengelymetszet.",
    t3_inst: "Rendezd az y = -3x + 5 reszeit.",
    t3_h1: "Az x egyutthatoja mutatja a lejtest.",
    t3_h2: "Az allando tag az x = 0 helyen ad y-t.",
    t3_slope: "meredekseg",
    t3_intercept: "y-tengelymetszet",
    t3_i1: "-3",
    t3_i2: "5",
    t3_i3: "x egyutthatoja",
    t3_i4: "ertek, ha x = 0",
    t3_q: "Melyik egyenletnek 2 a meredeksege es -1 az y-tengelymetszete?",
    t3_q_a1: "y = 2x - 1",
    t3_q_a2: "y = -x + 2",
    t3_q_a3: "y = x + 1",
    t3_q_a4: "y = 2 - x",
  },
  ro: {
    explorer_title: "Functii liniare",
    t1_title: "Citirea valorilor",
    t1_text: "Pentru y = 2x + 1, dublezi x si apoi aduni 1.",
    t1_b1: "Inlocuieste valoarea lui x in regula.",
    t1_b2: "Graficul unei functii liniare este o dreapta.",
    t1_inst: "Foloseste graficul lui y = 2x + 1. Atinge valoarea lui y cand x = 4.",
    t1_h1: "Dubleză mai intai pe 4.",
    t1_h2: "2 * 4 + 1 = 9.",
    t1_q: "Pentru f(x) = 2x + 1, cat este f(-2)?",
    t1_q_a1: "-3",
    t1_q_a2: "-5",
    t1_q_a3: "3",
    t1_q_a4: "5",
    t2_title: "Panta inseamna schimbare",
    t2_text: "Panta arata cu cat se schimba y cand x creste cu 1.",
    t2_b1: "Panta pozitiva urca spre dreapta.",
    t2_b2: "Panta negativa coboara spre dreapta.",
    t2_inst: "Potriveste modelul de schimbare cu panta lui.",
    t2_h1: "Urcarea este schimbarea lui y, deplasarea este schimbarea lui x.",
    t2_h2: "Daca dreapta coboara, panta este negativa.",
    t2_l1: "urca 2, dreapta 1",
    t2_r1: "panta 2",
    t2_l2: "urca 1, dreapta 2",
    t2_r2: "panta 1/2",
    t2_l3: "coboara 3, dreapta 1",
    t2_r3: "panta -3",
    t2_l4: "dreapta orizontala",
    t2_r4: "panta 0",
    t2_q: "Ce panta inseamna ca dreapta coboara 2 unitati cand x creste cu 1?",
    t2_q_a1: "-2",
    t2_q_a2: "2",
    t2_q_a3: "1/2",
    t2_q_a4: "0",
    t3_title: "Forma y = mx + b",
    t3_text: "In y = mx + b, m este panta si b este intersectia cu axa y.",
    t3_b1: "Coeficientul lui x este panta.",
    t3_b2: "Termenul constant este intersectia cu axa y.",
    t3_inst: "Sorteaza partile lui y = -3x + 5.",
    t3_h1: "Coeficientul lui x arata inclinarea.",
    t3_h2: "Constanta da valoarea cand x = 0.",
    t3_slope: "panta",
    t3_intercept: "intersectie cu axa y",
    t3_i1: "-3",
    t3_i2: "5",
    t3_i3: "coeficientul lui x",
    t3_i4: "valoare cand x = 0",
    t3_q: "Ce ecuatie are panta 2 si intersectia cu axa y egala cu -1?",
    t3_q_a1: "y = 2x - 1",
    t3_q_a2: "y = -x + 2",
    t3_q_a3: "y = x + 1",
    t3_q_a4: "y = 2 - x",
  },
};

const FUNCTIONEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <LessonCard accent="#F59E0B" headline="y = 2x + 1" lines={["x = 4 -> y = 9"]} />,
    bulletKeys: ["t1_b1", "t1_b2"],
    interactive: {
      type: "graph-plotter",
      points: [
        { x: -2, y: -3 },
        { x: -1, y: -1 },
        { x: 0, y: 1 },
        { x: 1, y: 3 },
        { x: 2, y: 5 },
        { x: 3, y: 7 },
        { x: 4, y: 9 },
      ],
      targetX: 4,
      targetY: 9,
      xMin: -3,
      xMax: 5,
      yMin: -4,
      yMax: 10,
      xLabel: "x",
      yLabel: "y",
      chartType: "line",
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"],
      answer: "t1_q_a1",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => <LessonCard accent="#F59E0B" headline="slope = rise / run" lines={["up 2 right 1 -> 2", "down 3 right 1 -> -3"]} />,
    bulletKeys: ["t2_b1", "t2_b2"],
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t2_l1", right: "t2_r1" },
        { left: "t2_l2", right: "t2_r2" },
        { left: "t2_l3", right: "t2_r3" },
        { left: "t2_l4", right: "t2_r4" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"],
      answer: "t2_q_a1",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => <LessonCard accent="#F59E0B" headline="y = -3x + 5" lines={["m = -3", "b = 5"]} />,
    bulletKeys: ["t3_b1", "t3_b2"],
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "slope", label: "t3_slope" },
        { id: "intercept", label: "t3_intercept" },
      ],
      items: [
        { text: "t3_i1", bucketId: "slope" },
        { text: "t3_i2", bucketId: "intercept" },
        { text: "t3_i3", bucketId: "slope" },
        { text: "t3_i4", bucketId: "intercept" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"],
      answer: "t3_q_a1",
    },
  },
];

export const FUNCTIONEXPLORER8_DEF: ExplorerDef = buildDef(
  FUNCTIONEXPLORER8_LABELS,
  "f(x)",
  FUNCTIONEXPLORER8_TOPICS,
);
const PROBABILITYEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Probability",
    t1_title: "Favorable outcomes",
    t1_text: "Probability compares favorable outcomes with all equally likely outcomes.",
    t1_b1: "P(event) = favorable / total.",
    t1_b2: "A fair die has 6 equally likely outcomes.",
    t1_inst: "Sort the die results for the event 'roll an even number'.",
    t1_h1: "Even numbers are divisible by 2.",
    t1_h2: "On a die, 2, 4, and 6 are even.",
    t1_yes: "favorable",
    t1_no: "not favorable",
    t1_i1: "1",
    t1_i2: "2",
    t1_i3: "3",
    t1_i4: "4",
    t1_i5: "5",
    t1_i6: "6",
    t1_q: "What is the probability of rolling a prime number on a fair die?",
    t1_q_a1: "1/2",
    t1_q_a2: "1/3",
    t1_q_a3: "2/3",
    t1_q_a4: "5/6",
    t2_title: "Complement probability",
    t2_text: "The complement of an event is everything that does not happen. Event and complement add up to 1.",
    t2_b1: "P(not A) = 1 - P(A).",
    t2_b2: "If red is 3/8, then not red is 5/8.",
    t2_inst: "Complete: If P(red) = 3/8, then P(not red) = ___.",
    t2_h1: "The whole is 8/8.",
    t2_h2: "8/8 - 3/8 = 5/8.",
    t2_sentence: "If P(red) = 3/8, then P(not red) = ___",
    t2_a1: "5/8",
    t2_a2: "3/5",
    t2_a3: "1/8",
    t2_a4: "6/8",
    t2_q: "If P(rain) = 0.2, what is P(no rain)?",
    t2_q_a1: "0.8",
    t2_q_a2: "0.2",
    t2_q_a3: "1.2",
    t2_q_a4: "0.5",
    t3_title: "Two-step events",
    t3_text: "For independent events, multiply probabilities. Experimental probability uses observed frequency.",
    t3_b1: "Two coin tosses have 4 ordered outcomes: HH, HT, TH, TT.",
    t3_b2: "Experimental probability = successes / trials.",
    t3_inst: "Match each event to its probability.",
    t3_h1: "Count how many coin outcomes match each event.",
    t3_h2: "Exactly one head happens in HT or TH.",
    t3_l1: "two heads in two tosses",
    t3_r1: "1/4",
    t3_l2: "exactly one head in two tosses",
    t3_r2: "1/2",
    t3_l3: "at least one head in two tosses",
    t3_r3: "3/4",
    t3_l4: "two tails in two tosses",
    t3_r4: "1/4",
    t3_q: "Blue appeared 18 times in 60 spins. What is the experimental probability of blue?",
    t3_q_a1: "3/10",
    t3_q_a2: "18/100",
    t3_q_a3: "1/2",
    t3_q_a4: "7/10",
  },
  de: {
    explorer_title: "Wahrscheinlichkeit",
    t1_title: "Guenstige Ergebnisse",
    t1_text: "Wahrscheinlichkeit vergleicht guenstige Ergebnisse mit allen gleich wahrscheinlichen Ergebnissen.",
    t1_b1: "P(Ereignis) = guenstig / insgesamt.",
    t1_b2: "Ein fairer Wuerfel hat 6 gleich wahrscheinliche Ergebnisse.",
    t1_inst: "Sortiere die Wuerfelergebnisse fuer das Ereignis 'gerade Zahl'.",
    t1_h1: "Gerade Zahlen sind durch 2 teilbar.",
    t1_h2: "Beim Wuerfel sind 2, 4 und 6 gerade.",
    t1_yes: "guenstig",
    t1_no: "nicht guenstig",
    t1_i1: "1",
    t1_i2: "2",
    t1_i3: "3",
    t1_i4: "4",
    t1_i5: "5",
    t1_i6: "6",
    t1_q: "Wie gross ist die Wahrscheinlichkeit, bei einem fairen Wuerfel eine Primzahl zu werfen?",
    t1_q_a1: "1/2",
    t1_q_a2: "1/3",
    t1_q_a3: "2/3",
    t1_q_a4: "5/6",
    t2_title: "Gegenwahrscheinlichkeit",
    t2_text: "Das Gegenereignis umfasst alles, was nicht passiert. Ereignis und Gegenereignis ergeben zusammen 1.",
    t2_b1: "P(nicht A) = 1 - P(A).",
    t2_b2: "Wenn rot 3/8 ist, dann ist nicht rot 5/8.",
    t2_inst: "Ergaenze: Wenn P(rot) = 3/8, dann ist P(nicht rot) = ___.",
    t2_h1: "Das Ganze ist 8/8.",
    t2_h2: "8/8 - 3/8 = 5/8.",
    t2_sentence: "Wenn P(rot) = 3/8, dann ist P(nicht rot) = ___",
    t2_a1: "5/8",
    t2_a2: "3/5",
    t2_a3: "1/8",
    t2_a4: "6/8",
    t2_q: "Wenn P(Regen) = 0.2 ist, wie gross ist P(kein Regen)?",
    t2_q_a1: "0.8",
    t2_q_a2: "0.2",
    t2_q_a3: "1.2",
    t2_q_a4: "0.5",
    t3_title: "Zweistufige Ereignisse",
    t3_text: "Bei unabhaengigen Ereignissen multiplizierst du Wahrscheinlichkeiten. Die experimentelle Wahrscheinlichkeit nutzt Haeufigkeiten.",
    t3_b1: "Zwei Muenzwuerfe haben 4 geordnete Ergebnisse: HH, HT, TH, TT.",
    t3_b2: "Experimentelle Wahrscheinlichkeit = Treffer / Versuche.",
    t3_inst: "Ordne jedem Ereignis seine Wahrscheinlichkeit zu.",
    t3_h1: "Zaehle, wie viele Muenzwuerfe zum Ereignis passen.",
    t3_h2: "Genau ein Kopf erscheint in HT oder TH.",
    t3_l1: "zwei Mal Kopf",
    t3_r1: "1/4",
    t3_l2: "genau ein Mal Kopf",
    t3_r2: "1/2",
    t3_l3: "mindestens ein Mal Kopf",
    t3_r3: "3/4",
    t3_l4: "zwei Mal Zahl",
    t3_r4: "1/4",
    t3_q: "Blau kam bei 60 Drehungen 18 Mal vor. Wie gross ist die experimentelle Wahrscheinlichkeit fuer Blau?",
    t3_q_a1: "3/10",
    t3_q_a2: "18/100",
    t3_q_a3: "1/2",
    t3_q_a4: "7/10",
  },
  hu: {
    explorer_title: "Valoszinuseg",
    t1_title: "Kedvezo kimenetelek",
    t1_text: "A valoszinuseg a kedvezo kimeneteleket hasonlitja az osszes azonos eselyu kimenetelhez.",
    t1_b1: "P(esemeny) = kedvezo / osszes.",
    t1_b2: "A szabalyos kockanak 6 egyforma eselyu kimenetele van.",
    t1_inst: "Rendezd a dobokocka eredmenyeit a 'paros szam' esemenyhez.",
    t1_h1: "A paros szam 2-vel oszthato.",
    t1_h2: "A kockan a 2, 4 es 6 paros.",
    t1_yes: "kedvezo",
    t1_no: "nem kedvezo",
    t1_i1: "1",
    t1_i2: "2",
    t1_i3: "3",
    t1_i4: "4",
    t1_i5: "5",
    t1_i6: "6",
    t1_q: "Mennyi a primszam dobasanak valoszinusege egy szabalyos kockaval?",
    t1_q_a1: "1/2",
    t1_q_a2: "1/3",
    t1_q_a3: "2/3",
    t1_q_a4: "5/6",
    t2_title: "Komplementer valoszinuseg",
    t2_text: "A komplementer esemeny mindent tartalmaz, ami nem tortenik meg. Egyutt 1-et adnak.",
    t2_b1: "P(nem A) = 1 - P(A).",
    t2_b2: "Ha piros 3/8, akkor nem piros 5/8.",
    t2_inst: "Egészitsd ki: Ha P(piros) = 3/8, akkor P(nem piros) = ___.",
    t2_h1: "Az egesz 8/8.",
    t2_h2: "8/8 - 3/8 = 5/8.",
    t2_sentence: "Ha P(piros) = 3/8, akkor P(nem piros) = ___",
    t2_a1: "5/8",
    t2_a2: "3/5",
    t2_a3: "1/8",
    t2_a4: "6/8",
    t2_q: "Ha P(eso) = 0.2, mennyi P(nincs eso)?",
    t2_q_a1: "0.8",
    t2_q_a2: "0.2",
    t2_q_a3: "1.2",
    t2_q_a4: "0.5",
    t3_title: "Ketlepeses esemenyek",
    t3_text: "Fuggetlen esemenyeknel szorzod a valoszinusegeket. A kiserleti valoszinuseg megfigyelt gyakorisagbol jon.",
    t3_b1: "Ket penzfeldobas 4 sorrendi kimenetele: HH, HT, TH, TT.",
    t3_b2: "Kiserleti valoszinuseg = sikerek / probak.",
    t3_inst: "Parositsd az esemenyeket a valoszinuseggel.",
    t3_h1: "Szamold meg, hany kimenetel felel meg az esemenynek.",
    t3_h2: "Pontosan egy fej HT vagy TH.",
    t3_l1: "ket fej ket dobasban",
    t3_r1: "1/4",
    t3_l2: "pontosan egy fej ket dobasban",
    t3_r2: "1/2",
    t3_l3: "legalabb egy fej ket dobasban",
    t3_r3: "3/4",
    t3_l4: "ket iras ket dobasban",
    t3_r4: "1/4",
    t3_q: "A kek 60 porgetesbol 18-szor jott ki. Mennyi a kek kiserleti valoszinusege?",
    t3_q_a1: "3/10",
    t3_q_a2: "18/100",
    t3_q_a3: "1/2",
    t3_q_a4: "7/10",
  },
  ro: {
    explorer_title: "Probabilitate",
    t1_title: "Rezultate favorabile",
    t1_text: "Probabilitatea compara rezultatele favorabile cu toate rezultatele la fel de posibile.",
    t1_b1: "P(eveniment) = favorabile / total.",
    t1_b2: "Un zar corect are 6 rezultate la fel de posibile.",
    t1_inst: "Sorteaza rezultatele zarului pentru evenimentul 'numar par'.",
    t1_h1: "Numerele pare se impart la 2.",
    t1_h2: "Pe zar, 2, 4 si 6 sunt pare.",
    t1_yes: "favorabil",
    t1_no: "nefavorabil",
    t1_i1: "1",
    t1_i2: "2",
    t1_i3: "3",
    t1_i4: "4",
    t1_i5: "5",
    t1_i6: "6",
    t1_q: "Care este probabilitatea sa obtii un numar prim la un zar corect?",
    t1_q_a1: "1/2",
    t1_q_a2: "1/3",
    t1_q_a3: "2/3",
    t1_q_a4: "5/6",
    t2_title: "Probabilitatea complementara",
    t2_text: "Complementul unui eveniment este tot ce nu se intampla. Impreuna dau 1.",
    t2_b1: "P(nu A) = 1 - P(A).",
    t2_b2: "Daca rosu este 3/8, atunci non-rosu este 5/8.",
    t2_inst: "Completeaza: Daca P(rosu) = 3/8, atunci P(nu rosu) = ___.",
    t2_h1: "Intregul este 8/8.",
    t2_h2: "8/8 - 3/8 = 5/8.",
    t2_sentence: "Daca P(rosu) = 3/8, atunci P(nu rosu) = ___",
    t2_a1: "5/8",
    t2_a2: "3/5",
    t2_a3: "1/8",
    t2_a4: "6/8",
    t2_q: "Daca P(ploaie) = 0.2, cat este P(fara ploaie)?",
    t2_q_a1: "0.8",
    t2_q_a2: "0.2",
    t2_q_a3: "1.2",
    t2_q_a4: "0.5",
    t3_title: "Evenimente in doi pasi",
    t3_text: "Pentru evenimente independente inmultesti probabilitatile. Probabilitatea experimentala foloseste frecventa observata.",
    t3_b1: "Doua aruncari de moneda au 4 rezultate ordonate: HH, HT, TH, TT.",
    t3_b2: "Probabilitatea experimentala = succese / incercari.",
    t3_inst: "Potriveste fiecare eveniment cu probabilitatea lui.",
    t3_h1: "Numara cate rezultate ale monedei se potrivesc.",
    t3_h2: "Exact un cap apare in HT sau TH.",
    t3_l1: "doua capete in doua aruncari",
    t3_r1: "1/4",
    t3_l2: "exact un cap in doua aruncari",
    t3_r2: "1/2",
    t3_l3: "cel putin un cap in doua aruncari",
    t3_r3: "3/4",
    t3_l4: "doua steme in doua aruncari",
    t3_r4: "1/4",
    t3_q: "Albastru a aparut de 18 ori in 60 de invartiri. Care este probabilitatea experimentala pentru albastru?",
    t3_q_a1: "3/10",
    t3_q_a2: "18/100",
    t3_q_a3: "1/2",
    t3_q_a4: "7/10",
  },
};

const PROBABILITYEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <LessonCard accent="#8B5CF6" headline="P(even) on a die" lines={["2, 4, 6 are favorable", "3 / 6 = 1/2"]} />,
    bulletKeys: ["t1_b1", "t1_b2"],
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "yes", label: "t1_yes" },
        { id: "no", label: "t1_no" },
      ],
      items: [
        { text: "t1_i1", bucketId: "no" },
        { text: "t1_i2", bucketId: "yes" },
        { text: "t1_i3", bucketId: "no" },
        { text: "t1_i4", bucketId: "yes" },
        { text: "t1_i5", bucketId: "no" },
        { text: "t1_i6", bucketId: "yes" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"],
      answer: "t1_q_a1",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => <LessonCard accent="#8B5CF6" headline="P(not A) = 1 - P(A)" lines={["1 - 3/8 = 5/8"]} />,
    bulletKeys: ["t2_b1", "t2_b2"],
    interactive: {
      type: "gap-fill",
      sentence: "t2_sentence",
      choices: ["t2_a1", "t2_a2", "t2_a3", "t2_a4"],
      correctIndex: 0,
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"],
      answer: "t2_q_a1",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => <LessonCard accent="#8B5CF6" headline="HH HT TH TT" lines={["exactly one head -> 2/4", "at least one head -> 3/4"]} />,
    bulletKeys: ["t3_b1", "t3_b2"],
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t3_l1", right: "t3_r1" },
        { left: "t3_l2", right: "t3_r2" },
        { left: "t3_l3", right: "t3_r3" },
        { left: "t3_l4", right: "t3_r4" },
      ],
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"],
      answer: "t3_q_a1",
    },
  },
];

export const PROBABILITYEXPLORER8_DEF: ExplorerDef = buildDef(
  PROBABILITYEXPLORER8_LABELS,
  "P",
  PROBABILITYEXPLORER8_TOPICS,
);
const QUADRATICEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Quadratic equations",
    t1_title: "Simple square equations",
    t1_text: "If x^2 = a, then x can be the positive or negative square root of a.",
    t1_b1: "x^2 = 16 gives x = 4 or x = -4.",
    t1_b2: "Always check both roots.",
    t1_inst: "Match each equation with its solution set.",
    t1_h1: "Think of the positive and negative numbers with that square.",
    t1_h2: "For 49, both 7 and -7 work.",
    t1_l1: "x^2 = 16",
    t1_r1: "x = 4 or x = -4",
    t1_l2: "x^2 = 25",
    t1_r2: "x = 5 or x = -5",
    t1_l3: "x^2 = 49",
    t1_r3: "x = 7 or x = -7",
    t1_l4: "x^2 = 1",
    t1_r4: "x = 1 or x = -1",
    t1_q: "Solve x^2 = 81.",
    t1_q_a1: "x = 9 or x = -9",
    t1_q_a2: "x = 9",
    t1_q_a3: "x = 81",
    t1_q_a4: "x = 8 or x = -8",
    t2_title: "Shifted square form",
    t2_text: "In (x - 3)^2 = 4, first take the square root and then undo the shift.",
    t2_b1: "(x - 3)^2 = 4 leads to x = 1 or x = 5.",
    t2_b2: "Substitute back to check.",
    t2_inst: "Sort the candidate values for (x - 3)^2 = 4.",
    t2_h1: "The solutions are 1 and 5.",
    t2_h2: "3 and 7 do not work.",
    t2_yes: "works",
    t2_no: "does not work",
    t2_i1: "1",
    t2_i2: "3",
    t2_i3: "5",
    t2_i4: "7",
    t2_q: "Solve (x + 4)^2 = 1.",
    t2_q_a1: "x = -3 or x = -5",
    t2_q_a2: "x = -4",
    t2_q_a3: "x = 3 or x = 5",
    t2_q_a4: "x = 1 or x = -1",
    t3_title: "Reading a parabola",
    t3_text: "A quadratic function graphs as a parabola. You can read y-values from the graph.",
    t3_b1: "For y = x^2 - 4, x = 2 gives y = 0.",
    t3_b2: "The graph is symmetric about x = 0.",
    t3_inst: "Use the graph of y = x^2 - 4. Tap the y-value when x = 2.",
    t3_h1: "Square 2 first.",
    t3_h2: "2^2 - 4 = 0.",
    t3_q: "For y = x^2 - 1, what is y when x = 3?",
    t3_q_a1: "8",
    t3_q_a2: "6",
    t3_q_a3: "4",
    t3_q_a4: "10",
  },
  de: {
    explorer_title: "Quadratische Gleichungen",
    t1_title: "Einfache Quadratgleichungen",
    t1_text: "Wenn x^2 = a gilt, dann kann x die positive oder negative Quadratwurzel von a sein.",
    t1_b1: "x^2 = 16 fuehrt zu x = 4 oder x = -4.",
    t1_b2: "Pruefe immer beide Wurzeln.",
    t1_inst: "Ordne jeder Gleichung ihre Loesungsmenge zu.",
    t1_h1: "Suche die positive und negative Zahl mit diesem Quadrat.",
    t1_h2: "Bei 49 funktionieren 7 und -7.",
    t1_l1: "x^2 = 16",
    t1_r1: "x = 4 oder x = -4",
    t1_l2: "x^2 = 25",
    t1_r2: "x = 5 oder x = -5",
    t1_l3: "x^2 = 49",
    t1_r3: "x = 7 oder x = -7",
    t1_l4: "x^2 = 1",
    t1_r4: "x = 1 oder x = -1",
    t1_q: "Loese x^2 = 81.",
    t1_q_a1: "x = 9 oder x = -9",
    t1_q_a2: "x = 9",
    t1_q_a3: "x = 81",
    t1_q_a4: "x = 8 oder x = -8",
    t2_title: "Verschobene Quadratgleichungen",
    t2_text: "Bei (x - 3)^2 = 4 ziehst du zuerst die Wurzel und machst dann die Verschiebung rueckgaengig.",
    t2_b1: "(x - 3)^2 = 4 liefert x = 1 oder x = 5.",
    t2_b2: "Pruefe durch Einsetzen.",
    t2_inst: "Sortiere die Kandidaten fuer (x - 3)^2 = 4.",
    t2_h1: "Die Loesungen sind 1 und 5.",
    t2_h2: "3 und 7 passen nicht.",
    t2_yes: "passt",
    t2_no: "passt nicht",
    t2_i1: "1",
    t2_i2: "3",
    t2_i3: "5",
    t2_i4: "7",
    t2_q: "Loese (x + 4)^2 = 1.",
    t2_q_a1: "x = -3 oder x = -5",
    t2_q_a2: "x = -4",
    t2_q_a3: "x = 3 oder x = 5",
    t2_q_a4: "x = 1 oder x = -1",
    t3_title: "Eine Parabel lesen",
    t3_text: "Eine quadratische Funktion bildet im Graphen eine Parabel. Daraus kannst du y-Werte ablesen.",
    t3_b1: "Bei y = x^2 - 4 gilt fuer x = 2: y = 0.",
    t3_b2: "Der Graph ist zu x = 0 symmetrisch.",
    t3_inst: "Nutze den Graphen von y = x^2 - 4. Tippe den y-Wert bei x = 2.",
    t3_h1: "Quadriere zuerst die 2.",
    t3_h2: "2^2 - 4 = 0.",
    t3_q: "Bei y = x^2 - 1: Wie gross ist y fuer x = 3?",
    t3_q_a1: "8",
    t3_q_a2: "6",
    t3_q_a3: "4",
    t3_q_a4: "10",
  },
  hu: {
    explorer_title: "Masodfoku egyenletek",
    t1_title: "Egyszeru negyzetes egyenletek",
    t1_text: "Ha x^2 = a, akkor x az a pozitiv vagy negativ negyzetgyoke lehet.",
    t1_b1: "x^2 = 16 eseten x = 4 vagy x = -4.",
    t1_b2: "Mindket gyokot ellenorizd.",
    t1_inst: "Parositsd az egyenleteket a megoldashalmazzal.",
    t1_h1: "Keresd a pozitiv es negativ szamot ugyanazzal a negyzettel.",
    t1_h2: "49-hez 7 es -7 tartozik.",
    t1_l1: "x^2 = 16",
    t1_r1: "x = 4 vagy x = -4",
    t1_l2: "x^2 = 25",
    t1_r2: "x = 5 vagy x = -5",
    t1_l3: "x^2 = 49",
    t1_r3: "x = 7 vagy x = -7",
    t1_l4: "x^2 = 1",
    t1_r4: "x = 1 vagy x = -1",
    t1_q: "Oldd meg: x^2 = 81.",
    t1_q_a1: "x = 9 vagy x = -9",
    t1_q_a2: "x = 9",
    t1_q_a3: "x = 81",
    t1_q_a4: "x = 8 vagy x = -8",
    t2_title: "Eltolt negyzetalak",
    t2_text: "A (x - 3)^2 = 4 alaknal eloszor gyokot vonsz, majd visszaforditod az eltolas muveletet.",
    t2_b1: "(x - 3)^2 = 4 megoldasa x = 1 vagy x = 5.",
    t2_b2: "Helyettesitessel ellenorizz.",
    t2_inst: "Rendezd a jelolteket a (x - 3)^2 = 4 egyenlethez.",
    t2_h1: "A megoldasok 1 es 5.",
    t2_h2: "A 3 es a 7 nem jo.",
    t2_yes: "jo",
    t2_no: "nem jo",
    t2_i1: "1",
    t2_i2: "3",
    t2_i3: "5",
    t2_i4: "7",
    t2_q: "Oldd meg: (x + 4)^2 = 1.",
    t2_q_a1: "x = -3 vagy x = -5",
    t2_q_a2: "x = -4",
    t2_q_a3: "x = 3 vagy x = 5",
    t2_q_a4: "x = 1 vagy x = -1",
    t3_title: "Parabola leolvasasa",
    t3_text: "A masodfoku fuggveny grafikonja parabola. Innen leolvashatod a y erteket.",
    t3_b1: "Az y = x^2 - 4 eseten x = 2-nel y = 0.",
    t3_b2: "A grafikon x = 0-ra szimmetrikus.",
    t3_inst: "Hasznald az y = x^2 - 4 grafikont. Koppints a y ertekre, ha x = 2.",
    t3_h1: "Eloszor negyzetre emeld a 2-t.",
    t3_h2: "2^2 - 4 = 0.",
    t3_q: "Az y = x^2 - 1 fuggvenynel mennyi y, ha x = 3?",
    t3_q_a1: "8",
    t3_q_a2: "6",
    t3_q_a3: "4",
    t3_q_a4: "10",
  },
  ro: {
    explorer_title: "Ecuatii patratice",
    t1_title: "Ecuatii simple de forma x^2 = a",
    t1_text: "Daca x^2 = a, atunci x poate fi radacina patrata pozitiva sau negativa a lui a.",
    t1_b1: "x^2 = 16 da x = 4 sau x = -4.",
    t1_b2: "Verifica ambele radacini.",
    t1_inst: "Potriveste fiecare ecuatie cu multimea solutiilor.",
    t1_h1: "Cauta numarul pozitiv si negativ cu acelasi patrat.",
    t1_h2: "Pentru 49 merg 7 si -7.",
    t1_l1: "x^2 = 16",
    t1_r1: "x = 4 sau x = -4",
    t1_l2: "x^2 = 25",
    t1_r2: "x = 5 sau x = -5",
    t1_l3: "x^2 = 49",
    t1_r3: "x = 7 sau x = -7",
    t1_l4: "x^2 = 1",
    t1_r4: "x = 1 sau x = -1",
    t1_q: "Rezolva x^2 = 81.",
    t1_q_a1: "x = 9 sau x = -9",
    t1_q_a2: "x = 9",
    t1_q_a3: "x = 81",
    t1_q_a4: "x = 8 sau x = -8",
    t2_title: "Forma patratica deplasata",
    t2_text: "La (x - 3)^2 = 4, extragi mai intai radacina si apoi anulezi deplasarea.",
    t2_b1: "(x - 3)^2 = 4 are solutiile x = 1 si x = 5.",
    t2_b2: "Verifica prin inlocuire.",
    t2_inst: "Sorteaza valorile candidate pentru (x - 3)^2 = 4.",
    t2_h1: "Solutiile sunt 1 si 5.",
    t2_h2: "3 si 7 nu merg.",
    t2_yes: "merge",
    t2_no: "nu merge",
    t2_i1: "1",
    t2_i2: "3",
    t2_i3: "5",
    t2_i4: "7",
    t2_q: "Rezolva (x + 4)^2 = 1.",
    t2_q_a1: "x = -3 sau x = -5",
    t2_q_a2: "x = -4",
    t2_q_a3: "x = 3 sau x = 5",
    t2_q_a4: "x = 1 sau x = -1",
    t3_title: "Citirea unei parabole",
    t3_text: "Graficul unei functii patratice este o parabola. De aici poti citi valorile lui y.",
    t3_b1: "Pentru y = x^2 - 4, la x = 2 ai y = 0.",
    t3_b2: "Graficul este simetric fata de x = 0.",
    t3_inst: "Foloseste graficul lui y = x^2 - 4. Atinge valoarea lui y cand x = 2.",
    t3_h1: "Ridica pe 2 la patrat.",
    t3_h2: "2^2 - 4 = 0.",
    t3_q: "Pentru y = x^2 - 1, cat este y cand x = 3?",
    t3_q_a1: "8",
    t3_q_a2: "6",
    t3_q_a3: "4",
    t3_q_a4: "10",
  },
};

const QUADRATICEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title",
    infoText: "t1_text",
    svg: () => <LessonCard accent="#6366F1" headline="x^2 = 49" lines={["x = 7", "x = -7"]} />,
    bulletKeys: ["t1_b1", "t1_b2"],
    interactive: {
      type: "match-pairs",
      pairs: [
        { left: "t1_l1", right: "t1_r1" },
        { left: "t1_l2", right: "t1_r2" },
        { left: "t1_l3", right: "t1_r3" },
        { left: "t1_l4", right: "t1_r4" },
      ],
      instruction: "t1_inst",
      hint1: "t1_h1",
      hint2: "t1_h2",
    },
    quiz: {
      question: "t1_q",
      choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"],
      answer: "t1_q_a1",
    },
  },
  {
    infoTitle: "t2_title",
    infoText: "t2_text",
    svg: () => <LessonCard accent="#6366F1" headline="(x - 3)^2 = 4" lines={["x = 1 or 5"]} />,
    bulletKeys: ["t2_b1", "t2_b2"],
    interactive: {
      type: "drag-to-bucket",
      buckets: [
        { id: "yes", label: "t2_yes" },
        { id: "no", label: "t2_no" },
      ],
      items: [
        { text: "t2_i1", bucketId: "yes" },
        { text: "t2_i2", bucketId: "no" },
        { text: "t2_i3", bucketId: "yes" },
        { text: "t2_i4", bucketId: "no" },
      ],
      instruction: "t2_inst",
      hint1: "t2_h1",
      hint2: "t2_h2",
    },
    quiz: {
      question: "t2_q",
      choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"],
      answer: "t2_q_a1",
    },
  },
  {
    infoTitle: "t3_title",
    infoText: "t3_text",
    svg: () => <LessonCard accent="#6366F1" headline="y = x^2 - 4" lines={["x = 2 -> y = 0"]} />,
    bulletKeys: ["t3_b1", "t3_b2"],
    interactive: {
      type: "graph-plotter",
      points: [
        { x: -3, y: 5 },
        { x: -2, y: 0 },
        { x: -1, y: -3 },
        { x: 0, y: -4 },
        { x: 1, y: -3 },
        { x: 2, y: 0 },
        { x: 3, y: 5 },
      ],
      targetX: 2,
      targetY: 0,
      xMin: -4,
      xMax: 4,
      yMin: -5,
      yMax: 6,
      xLabel: "x",
      yLabel: "y",
      chartType: "line",
      instruction: "t3_inst",
      hint1: "t3_h1",
      hint2: "t3_h2",
    },
    quiz: {
      question: "t3_q",
      choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"],
      answer: "t3_q_a1",
    },
  },
];

export const QUADRATICEXPLORER8_DEF: ExplorerDef = buildDef(
  QUADRATICEXPLORER8_LABELS,
  "x^2",
  QUADRATICEXPLORER8_TOPICS,
);
export const SQRTEXPLORER8_DEF: ExplorerDef = {
  labels: SQRTEXPLORER8_LABELS,
  title: "explorer_title",
  icon: "√",
  topics: SQRTEXPLORER8_TOPICS,
  rounds: [],
};
const STATEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Statistics",
    t1_title: "Arithmetic mean",
    t1_text: "The mean is the total of all values divided by the number of values. For 4, 6, 8, 10 the total is 28, so the mean is 7.",
    t1_b1: "Add every value exactly once.", t1_b2: "Divide by how many values there are.",
    t1_inst: "Complete the mean calculation.", t1_h1: "First find 4 + 6 + 8 + 10.", t1_h2: "Divide 28 by 4.",
    t1_sentence: "mean = (4 + 6 + 8 + 10) / 4 = ___", t1_a1: "7", t1_a2: "6", t1_a3: "8", t1_a4: "28",
    t1_q: "What is the mean of 3, 5, 7, 9?", t1_q_a1: "6", t1_q_a2: "5", t1_q_a3: "7", t1_q_a4: "24",
    t2_title: "Median and mode",
    t2_text: "Order the data first. The median is the middle value; the mode is the value occurring most often.",
    t2_b1: "For an even count, average the two middle values.", t2_b2: "A data set can have no mode or more than one mode.",
    t2_inst: "Match each statistic to its value for 2, 3, 3, 5, 8.", t2_h1: "The ordered list already has five values.", t2_h2: "Look at the middle and the repeated value.",
    t2_left1: "median", t2_right1: "3 (middle value)", t2_left2: "mode", t2_right2: "3 (most frequent)", t2_left3: "number of values", t2_right3: "5",
    t2_q: "What is the median of 1, 4, 6, 8?", t2_q_a1: "5", t2_q_a2: "4", t2_q_a3: "6", t2_q_a4: "4.75",
    t3_title: "Range and spread",
    t3_text: "The range measures spread by subtracting the smallest value from the largest value.",
    t3_b1: "range = maximum - minimum", t3_b2: "A larger range usually means more spread.",
    t3_inst: "Sort each data set by its range.", t3_h1: "Use largest minus smallest.", t3_h2: "The ranges are 6 and 10.",
    t3_small: "range 6", t3_large: "range 10", t3_i1: "2, 5, 8", t3_i2: "4, 7, 10", t3_i3: "1, 6, 11", t3_i4: "-2, 3, 8",
    t3_q: "What is the range of -3, 2, 4, 9?", t3_q_a1: "12", t3_q_a2: "6", t3_q_a3: "9", t3_q_a4: "3",
  },
  de: {
    explorer_title: "Statistik",
    t1_title: "Arithmetisches Mittel", t1_text: "Das Mittel ist die Summe aller Werte geteilt durch ihre Anzahl. Bei 4, 6, 8, 10 ist die Summe 28 und das Mittel 7.",
    t1_b1: "Addiere jeden Wert genau einmal.", t1_b2: "Teile durch die Anzahl der Werte.", t1_inst: "Ergaenze die Mittelwertrechnung.", t1_h1: "Berechne zuerst 4 + 6 + 8 + 10.", t1_h2: "Teile 28 durch 4.",
    t1_sentence: "Mittel = (4 + 6 + 8 + 10) / 4 = ___", t1_a1: "7", t1_a2: "6", t1_a3: "8", t1_a4: "28", t1_q: "Wie gross ist das Mittel von 3, 5, 7, 9?", t1_q_a1: "6", t1_q_a2: "5", t1_q_a3: "7", t1_q_a4: "24",
    t2_title: "Median und Modalwert", t2_text: "Ordne zuerst die Daten. Der Median ist der mittlere Wert; der Modalwert kommt am haeufigsten vor.", t2_b1: "Bei gerader Anzahl mittelt man die zwei mittleren Werte.", t2_b2: "Es kann keinen oder mehrere Modalwerte geben.",
    t2_inst: "Ordne der Statistik ihren Wert fuer 2, 3, 3, 5, 8 zu.", t2_h1: "Die geordnete Liste hat fuenf Werte.", t2_h2: "Suche die Mitte und den wiederholten Wert.", t2_left1: "Median", t2_right1: "3 (mittlerer Wert)", t2_left2: "Modalwert", t2_right2: "3 (am haeufigsten)", t2_left3: "Anzahl der Werte", t2_right3: "5",
    t2_q: "Wie gross ist der Median von 1, 4, 6, 8?", t2_q_a1: "5", t2_q_a2: "4", t2_q_a3: "6", t2_q_a4: "4,75",
    t3_title: "Spannweite", t3_text: "Die Spannweite misst die Streuung: groesster Wert minus kleinster Wert.", t3_b1: "Spannweite = Maximum - Minimum", t3_b2: "Eine groessere Spannweite bedeutet meist mehr Streuung.",
    t3_inst: "Sortiere jede Datenreihe nach ihrer Spannweite.", t3_h1: "Rechne groesster minus kleinster Wert.", t3_h2: "Die Spannweiten sind 6 und 10.", t3_small: "Spannweite 6", t3_large: "Spannweite 10", t3_i1: "2, 5, 8", t3_i2: "4, 7, 10", t3_i3: "1, 6, 11", t3_i4: "-2, 3, 8",
    t3_q: "Wie gross ist die Spannweite von -3, 2, 4, 9?", t3_q_a1: "12", t3_q_a2: "6", t3_q_a3: "9", t3_q_a4: "3",
  },
  hu: {
    explorer_title: "Statisztika",
    t1_title: "Szamtani atlag", t1_text: "Az atlag az ertekek osszege osztva az ertekek szamaval. A 4, 6, 8, 10 osszege 28, igy az atlag 7.", t1_b1: "Minden erteket pontosan egyszer adj ossze.", t1_b2: "Oszd az osszeget az ertekek szamaval.",
    t1_inst: "Egeszitsd ki az atlagertek szamitasat.", t1_h1: "Eloszor szamold ki: 4 + 6 + 8 + 10.", t1_h2: "Oszd el 28-at 4-gyel.", t1_sentence: "atlag = (4 + 6 + 8 + 10) / 4 = ___", t1_a1: "7", t1_a2: "6", t1_a3: "8", t1_a4: "28", t1_q: "Mennyi a 3, 5, 7, 9 atlaga?", t1_q_a1: "6", t1_q_a2: "5", t1_q_a3: "7", t1_q_a4: "24",
    t2_title: "Median es modusz", t2_text: "Eloszor rendezd az adatokat. A median a kozepso ertek, a modusz a leggyakoribb ertek.", t2_b1: "Paros elemszamnal a ket kozepso ertek atlaga kell.", t2_b2: "Lehet nulla vagy tobb modusz is.",
    t2_inst: "Parositsd a mutatot az ertekevel a 2, 3, 3, 5, 8 adatsorban.", t2_h1: "A rendezett sorban ot ertek van.", t2_h2: "Keresd a kozepso es a tobbszor szereplo erteket.", t2_left1: "median", t2_right1: "3 (kozepso ertek)", t2_left2: "modusz", t2_right2: "3 (leggyakoribb)", t2_left3: "ertekek szama", t2_right3: "5",
    t2_q: "Mennyi az 1, 4, 6, 8 medianja?", t2_q_a1: "5", t2_q_a2: "4", t2_q_a3: "6", t2_q_a4: "4,75",
    t3_title: "Terjedelem", t3_text: "A terjedelem a legnagyobb es a legkisebb ertek kulonbsege.", t3_b1: "terjedelem = maximum - minimum", t3_b2: "Nagyobb terjedelem altalaban nagyobb szorodast jelez.",
    t3_inst: "Rendezd az adatsorokat a terjedelmuk szerint.", t3_h1: "Vond ki a legkisebbet a legnagyobbol.", t3_h2: "A terjedelmek 6 es 10.", t3_small: "terjedelem 6", t3_large: "terjedelem 10", t3_i1: "2, 5, 8", t3_i2: "4, 7, 10", t3_i3: "1, 6, 11", t3_i4: "-2, 3, 8",
    t3_q: "Mennyi a -3, 2, 4, 9 terjedelme?", t3_q_a1: "12", t3_q_a2: "6", t3_q_a3: "9", t3_q_a4: "3",
  },
  ro: {
    explorer_title: "Statistica",
    t1_title: "Media aritmetica", t1_text: "Media este suma tuturor valorilor impartita la numarul lor. Pentru 4, 6, 8, 10 suma este 28, deci media este 7.", t1_b1: "Aduna fiecare valoare o singura data.", t1_b2: "Imparte la numarul valorilor.",
    t1_inst: "Completeaza calculul mediei.", t1_h1: "Calculeaza mai intai 4 + 6 + 8 + 10.", t1_h2: "Imparte 28 la 4.", t1_sentence: "media = (4 + 6 + 8 + 10) / 4 = ___", t1_a1: "7", t1_a2: "6", t1_a3: "8", t1_a4: "28", t1_q: "Care este media numerelor 3, 5, 7, 9?", t1_q_a1: "6", t1_q_a2: "5", t1_q_a3: "7", t1_q_a4: "24",
    t2_title: "Mediana si modul", t2_text: "Ordoneaza mai intai datele. Mediana este valoarea din mijloc, iar modul apare cel mai des.", t2_b1: "La un numar par de valori, mediaza cele doua valori centrale.", t2_b2: "Un set poate avea zero sau mai multe moduri.",
    t2_inst: "Asociaza indicatorul cu valoarea sa pentru 2, 3, 3, 5, 8.", t2_h1: "Lista ordonata are cinci valori.", t2_h2: "Cauta valoarea centrala si valoarea repetata.", t2_left1: "mediana", t2_right1: "3 (valoarea centrala)", t2_left2: "modul", t2_right2: "3 (cea mai frecventa)", t2_left3: "numarul valorilor", t2_right3: "5",
    t2_q: "Care este mediana numerelor 1, 4, 6, 8?", t2_q_a1: "5", t2_q_a2: "4", t2_q_a3: "6", t2_q_a4: "4,75",
    t3_title: "Amplitudinea", t3_text: "Amplitudinea masoara raspandirea: valoarea maxima minus valoarea minima.", t3_b1: "amplitudine = maxim - minim", t3_b2: "O amplitudine mai mare indica de obicei o raspandire mai mare.",
    t3_inst: "Sorteaza seturile dupa amplitudine.", t3_h1: "Scade minimul din maxim.", t3_h2: "Amplitudinile sunt 6 si 10.", t3_small: "amplitudine 6", t3_large: "amplitudine 10", t3_i1: "2, 5, 8", t3_i2: "4, 7, 10", t3_i3: "1, 6, 11", t3_i4: "-2, 3, 8",
    t3_q: "Care este amplitudinea numerelor -3, 2, 4, 9?", t3_q_a1: "12", t3_q_a2: "6", t3_q_a3: "9", t3_q_a4: "3",
  },
};

const STATEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text", bulletKeys: ["t1_b1", "t1_b2"],
    svg: () => <LessonCard accent="#F59E0B" headline="mean = sum / count" lines={["4 + 6 + 8 + 10 = 28", "28 / 4 = 7"]} />,
    interactive: { type: "gap-fill", sentence: "t1_sentence", choices: ["t1_a1", "t1_a2", "t1_a3", "t1_a4"], correctIndex: 0, instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2" },
    quiz: { question: "t1_q", choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"], answer: "t1_q_a1" },
  },
  {
    infoTitle: "t2_title", infoText: "t2_text", bulletKeys: ["t2_b1", "t2_b2"],
    svg: () => <LessonCard accent="#F59E0B" headline="2, 3, 3, 5, 8" lines={["median = 3", "mode = 3"]} />,
    interactive: { type: "match-pairs", pairs: [{ left: "t2_left1", right: "t2_right1" }, { left: "t2_left2", right: "t2_right2" }, { left: "t2_left3", right: "t2_right3" }], instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2" },
    quiz: { question: "t2_q", choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"], answer: "t2_q_a1" },
  },
  {
    infoTitle: "t3_title", infoText: "t3_text", bulletKeys: ["t3_b1", "t3_b2"],
    svg: () => <LessonCard accent="#F59E0B" headline="range = max - min" lines={["9 - (-3)", "range = 12"]} />,
    interactive: { type: "drag-to-bucket", buckets: [{ id: "small", label: "t3_small" }, { id: "large", label: "t3_large" }], items: [{ text: "t3_i1", bucketId: "small" }, { text: "t3_i2", bucketId: "small" }, { text: "t3_i3", bucketId: "large" }, { text: "t3_i4", bucketId: "large" }], instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2" },
    quiz: { question: "t3_q", choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"], answer: "t3_q_a1" },
  },
];

export const STATEXPLORER8_DEF: ExplorerDef = buildDef(STATEXPLORER8_LABELS, "STAT", STATEXPLORER8_TOPICS);

const SYSTEMEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Systems of equations",
    t1_title: "Elimination", t1_text: "Add equations when opposite terms cancel. From x + y = 9 and x - y = 3, addition gives 2x = 12, so x = 6 and y = 3.", t1_b1: "Perform the same addition on both sides.", t1_b2: "Substitute back to find the second variable.",
    t1_inst: "Solve the system by elimination.", t1_step1: "After adding, 2x = 12. What is x?", t1_step2: "Substitute x = 6 into x + y = 9. What is y?", t1_h1: "The y terms cancel.", t1_h2: "Then 6 + y = 9.",
    t1_q: "For x + y = 7 and x - y = 1, what is x?", t1_q_a1: "4", t1_q_a2: "3", t1_q_a3: "6", t1_q_a4: "8",
    t2_title: "Intersection of two lines", t2_text: "A solution of a system lies on both graphs. It is the intersection point of the two lines.", t2_b1: "The point must satisfy both equations.", t2_b2: "One intersection means one solution.",
    t2_inst: "Select the intersection of y = x + 1 and y = -x + 5.", t2_h1: "Set x + 1 equal to -x + 5.", t2_h2: "The lines meet at (2, 3).",
    t2_q: "Which point solves y = x + 1 and y = -x + 5?", t2_q_a1: "(2, 3)", t2_q_a2: "(3, 2)", t2_q_a3: "(1, 2)", t2_q_a4: "(0, 5)",
    t3_title: "Build a system from a story", t3_text: "Let a be adult tickets and c be child tickets. Eight tickets and a total cost of 52 give a + c = 8 and 8a + 4c = 52.", t3_b1: "One equation counts tickets.", t3_b2: "The other equation counts their cost.",
    t3_inst: "Complete the number of adult tickets.", t3_h1: "Subtract 4(a + c) = 32 from the cost equation.", t3_h2: "4a = 20, so a = 5.", t3_sentence: "a + c = 8 and 8a + 4c = 52, so a = ___", t3_a1: "5", t3_a2: "3", t3_a3: "4", t3_a4: "8",
    t3_q: "If a = 5 and a + c = 8, what is c?", t3_q_a1: "3", t3_q_a2: "5", t3_q_a3: "8", t3_q_a4: "13",
  },
  de: {
    explorer_title: "Lineare Gleichungssysteme",
    t1_title: "Additionsverfahren", t1_text: "Addiere Gleichungen, wenn sich entgegengesetzte Terme aufheben. Aus x + y = 9 und x - y = 3 folgt 2x = 12, also x = 6 und y = 3.", t1_b1: "Addiere auf beiden Seiten gleich.", t1_b2: "Setze zurueck ein, um die zweite Variable zu finden.",
    t1_inst: "Loese das System durch Addition.", t1_step1: "Nach dem Addieren gilt 2x = 12. Was ist x?", t1_step2: "Setze x = 6 in x + y = 9 ein. Was ist y?", t1_h1: "Die y-Terme heben sich auf.", t1_h2: "Dann gilt 6 + y = 9.", t1_q: "Bei x + y = 7 und x - y = 1: Was ist x?", t1_q_a1: "4", t1_q_a2: "3", t1_q_a3: "6", t1_q_a4: "8",
    t2_title: "Schnittpunkt zweier Geraden", t2_text: "Eine Loesung liegt auf beiden Graphen. Sie ist der Schnittpunkt der Geraden.", t2_b1: "Der Punkt muss beide Gleichungen erfuellen.", t2_b2: "Ein Schnittpunkt bedeutet eine Loesung.",
    t2_inst: "Waehle den Schnittpunkt von y = x + 1 und y = -x + 5.", t2_h1: "Setze x + 1 gleich -x + 5.", t2_h2: "Die Geraden treffen sich bei (2, 3).", t2_q: "Welcher Punkt loest y = x + 1 und y = -x + 5?", t2_q_a1: "(2, 3)", t2_q_a2: "(3, 2)", t2_q_a3: "(1, 2)", t2_q_a4: "(0, 5)",
    t3_title: "Ein System aus einer Sachaufgabe", t3_text: "a steht fuer Erwachsenenkarten und c fuer Kinderkarten. Acht Karten fuer 52 ergeben a + c = 8 und 8a + 4c = 52.", t3_b1: "Eine Gleichung zaehlt die Karten.", t3_b2: "Die andere berechnet die Kosten.",
    t3_inst: "Ergaenze die Anzahl der Erwachsenenkarten.", t3_h1: "Ziehe 4(a + c) = 32 von der Kostengleichung ab.", t3_h2: "4a = 20, also a = 5.", t3_sentence: "a + c = 8 und 8a + 4c = 52, also a = ___", t3_a1: "5", t3_a2: "3", t3_a3: "4", t3_a4: "8", t3_q: "Wenn a = 5 und a + c = 8, was ist c?", t3_q_a1: "3", t3_q_a2: "5", t3_q_a3: "8", t3_q_a4: "13",
  },
  hu: {
    explorer_title: "Egyenletrendszerek",
    t1_title: "Kikuszoboles", t1_text: "Add ossze az egyenleteket, ha ellentetes tagok kiesnek. Az x + y = 9 es x - y = 3 osszege 2x = 12, igy x = 6 es y = 3.", t1_b1: "Mindket oldalon ugyanugy adj ossze.", t1_b2: "Visszahelyettesitessel keresd meg a masik valtozot.",
    t1_inst: "Oldd meg a rendszert kikuszobolessel.", t1_step1: "Osszeadas utan 2x = 12. Mennyi x?", t1_step2: "Helyettesitsd x = 6-ot az x + y = 9 egyenletbe. Mennyi y?", t1_h1: "Az y tagok kiesnek.", t1_h2: "Ezutan 6 + y = 9.", t1_q: "Ha x + y = 7 es x - y = 1, mennyi x?", t1_q_a1: "4", t1_q_a2: "3", t1_q_a3: "6", t1_q_a4: "8",
    t2_title: "Ket egyenes metszespontja", t2_text: "A rendszer megoldasa mindket grafikonon rajta van. Ez a ket egyenes metszespontja.", t2_b1: "A pontnak mindket egyenletet teljesitenie kell.", t2_b2: "Egy metszespont egy megoldast jelent.",
    t2_inst: "Jelold ki az y = x + 1 es y = -x + 5 metszespontjat.", t2_h1: "Tedd egyenlove az x + 1 es -x + 5 kifejezeseket.", t2_h2: "Az egyenesek a (2, 3) pontban metszik egymast.", t2_q: "Melyik pont oldja meg az y = x + 1 es y = -x + 5 rendszert?", t2_q_a1: "(2, 3)", t2_q_a2: "(3, 2)", t2_q_a3: "(1, 2)", t2_q_a4: "(0, 5)",
    t3_title: "Egyenletrendszer szovegbol", t3_text: "Legyen a a felnottjegyek, c a gyerekjegyek szama. Nyolc jegy es 52 osszeg eseten a + c = 8 es 8a + 4c = 52.", t3_b1: "Az egyik egyenlet a jegyeket szamolja.", t3_b2: "A masik a teljes arat adja meg.",
    t3_inst: "Egeszitsd ki a felnottjegyek szamat.", t3_h1: "Vond ki a 4(a + c) = 32 egyenletet a koltsegegyenletbol.", t3_h2: "4a = 20, igy a = 5.", t3_sentence: "a + c = 8 es 8a + 4c = 52, igy a = ___", t3_a1: "5", t3_a2: "3", t3_a3: "4", t3_a4: "8", t3_q: "Ha a = 5 es a + c = 8, mennyi c?", t3_q_a1: "3", t3_q_a2: "5", t3_q_a3: "8", t3_q_a4: "13",
  },
  ro: {
    explorer_title: "Sisteme de ecuatii",
    t1_title: "Eliminarea", t1_text: "Aduna ecuatiile cand termenii opusi se anuleaza. Din x + y = 9 si x - y = 3 obtinem 2x = 12, deci x = 6 si y = 3.", t1_b1: "Fa aceeasi adunare in ambele parti.", t1_b2: "Inlocuieste inapoi pentru a afla a doua variabila.",
    t1_inst: "Rezolva sistemul prin eliminare.", t1_step1: "Dupa adunare, 2x = 12. Cat este x?", t1_step2: "Inlocuieste x = 6 in x + y = 9. Cat este y?", t1_h1: "Termenii cu y se anuleaza.", t1_h2: "Apoi 6 + y = 9.", t1_q: "Pentru x + y = 7 si x - y = 1, cat este x?", t1_q_a1: "4", t1_q_a2: "3", t1_q_a3: "6", t1_q_a4: "8",
    t2_title: "Intersectia a doua drepte", t2_text: "Solutia unui sistem se afla pe ambele grafice. Ea este punctul de intersectie al dreptelor.", t2_b1: "Punctul trebuie sa satisfaca ambele ecuatii.", t2_b2: "O intersectie inseamna o solutie.",
    t2_inst: "Selecteaza intersectia pentru y = x + 1 si y = -x + 5.", t2_h1: "Egaleaza x + 1 cu -x + 5.", t2_h2: "Dreptele se intalnesc in (2, 3).", t2_q: "Ce punct rezolva y = x + 1 si y = -x + 5?", t2_q_a1: "(2, 3)", t2_q_a2: "(3, 2)", t2_q_a3: "(1, 2)", t2_q_a4: "(0, 5)",
    t3_title: "Un sistem dintr-o problema", t3_text: "Fie a bilete pentru adulti si c bilete pentru copii. Opt bilete cu pret total 52 dau a + c = 8 si 8a + 4c = 52.", t3_b1: "O ecuatie numara biletele.", t3_b2: "Cealalta ecuatie calculeaza costul.",
    t3_inst: "Completeaza numarul biletelor pentru adulti.", t3_h1: "Scade 4(a + c) = 32 din ecuatia costului.", t3_h2: "4a = 20, deci a = 5.", t3_sentence: "a + c = 8 si 8a + 4c = 52, deci a = ___", t3_a1: "5", t3_a2: "3", t3_a3: "4", t3_a4: "8", t3_q: "Daca a = 5 si a + c = 8, cat este c?", t3_q_a1: "3", t3_q_a2: "5", t3_q_a3: "8", t3_q_a4: "13",
  },
};

const SYSTEMEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text", bulletKeys: ["t1_b1", "t1_b2"],
    svg: () => <LessonCard accent="#06B6D4" headline="x + y = 9; x - y = 3" lines={["2x = 12", "(x, y) = (6, 3)"]} />,
    interactive: { type: "equation-solver", equation: "x + y = 9; x - y = 3", steps: [{ instruction: "t1_step1", choices: [3, 4, 6, 12], answer: 6, equation: "x = 6" }, { instruction: "t1_step2", choices: [1, 2, 3, 6], answer: 3, equation: "y = 3" }], finalAnswer: 3, variable: "y", instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2" },
    quiz: { question: "t1_q", choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"], answer: "t1_q_a1" },
  },
  {
    infoTitle: "t2_title", infoText: "t2_text", bulletKeys: ["t2_b1", "t2_b2"],
    svg: () => <PlaneCard accent="#06B6D4" caption="intersection (2, 3)" points={[{ x: 2, y: 3, label: "S" }]} />,
    interactive: { type: "coordinate-picker", targetX: 2, targetY: 3, range: 5, instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2" },
    quiz: { question: "t2_q", choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"], answer: "t2_q_a1" },
  },
  {
    infoTitle: "t3_title", infoText: "t3_text", bulletKeys: ["t3_b1", "t3_b2"],
    svg: () => <LessonCard accent="#06B6D4" headline="a + c = 8" lines={["8a + 4c = 52", "a = 5, c = 3"]} />,
    interactive: { type: "gap-fill", sentence: "t3_sentence", choices: ["t3_a1", "t3_a2", "t3_a3", "t3_a4"], correctIndex: 0, instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2" },
    quiz: { question: "t3_q", choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"], answer: "t3_q_a1" },
  },
];

export const SYSTEMEXPLORER8_DEF: ExplorerDef = buildDef(SYSTEMEXPLORER8_LABELS, "SYS", SYSTEMEXPLORER8_TOPICS);

const TRANSFORMEXPLORER8_LABELS: Record<string, Record<string, string>> = {
  en: {
    explorer_title: "Geometric transformations",
    t1_title: "Translation", t1_text: "A translation moves every point by the same vector. Adding (4, -2) to A(-1, 3) gives A'(3, 1).", t1_b1: "Add the horizontal change to x.", t1_b2: "Add the vertical change to y.",
    t1_inst: "Plot the image of A(-1, 3) after translation by (4, -2).", t1_h1: "Compute -1 + 4 and 3 - 2.", t1_h2: "The image is (3, 1).", t1_q: "Translate (2, -1) by (-3, 5).", t1_q_a1: "(-1, 4)", t1_q_a2: "(5, -6)", t1_q_a3: "(-5, 6)", t1_q_a4: "(1, 4)",
    t2_title: "Reflection in an axis", t2_text: "Reflection in the x-axis keeps x and changes the sign of y. Reflection in the y-axis changes the sign of x.", t2_b1: "x-axis: (x, y) becomes (x, -y).", t2_b2: "y-axis: (x, y) becomes (-x, y).",
    t2_inst: "Sort each image of P(2, 3) by its reflection axis.", t2_h1: "The coordinate perpendicular to the mirror changes sign.", t2_h2: "Across x: (2, -3); across y: (-2, 3).", t2_x: "reflection in x-axis", t2_y: "reflection in y-axis", t2_i1: "(2, -3)", t2_i2: "x stays 2", t2_i3: "(-2, 3)", t2_i4: "y stays 3",
    t2_q: "Reflect (-4, 1) in the y-axis.", t2_q_a1: "(4, 1)", t2_q_a2: "(-4, -1)", t2_q_a3: "(1, -4)", t2_q_a4: "(4, -1)",
    t3_title: "Rotation about the origin", t3_text: "A 90-degree counterclockwise rotation about the origin maps (x, y) to (-y, x). A 180-degree rotation maps it to (-x, -y).", t3_b1: "Rotations preserve lengths and angles.", t3_b2: "The direction and center must be stated.",
    t3_inst: "Match each point to its 90-degree counterclockwise image.", t3_h1: "Use (x, y) to (-y, x).", t3_h2: "Swap the coordinates, then negate the new x-coordinate.", t3_l1: "(2, 1)", t3_r1: "(-1, 2)", t3_l2: "(-3, 2)", t3_r2: "(-2, -3)", t3_l3: "(0, -4)", t3_r3: "(4, 0)",
    t3_q: "Rotate (3, -2) by 180 degrees about the origin.", t3_q_a1: "(-3, 2)", t3_q_a2: "(2, 3)", t3_q_a3: "(-2, -3)", t3_q_a4: "(3, 2)",
  },
  de: {
    explorer_title: "Geometrische Abbildungen",
    t1_title: "Verschiebung", t1_text: "Eine Verschiebung bewegt jeden Punkt um denselben Vektor. Addiert man (4, -2) zu A(-1, 3), entsteht A'(3, 1).", t1_b1: "Addiere die waagerechte Aenderung zu x.", t1_b2: "Addiere die senkrechte Aenderung zu y.",
    t1_inst: "Zeichne das Bild von A(-1, 3) nach der Verschiebung um (4, -2).", t1_h1: "Berechne -1 + 4 und 3 - 2.", t1_h2: "Der Bildpunkt ist (3, 1).", t1_q: "Verschiebe (2, -1) um (-3, 5).", t1_q_a1: "(-1, 4)", t1_q_a2: "(5, -6)", t1_q_a3: "(-5, 6)", t1_q_a4: "(1, 4)",
    t2_title: "Spiegelung an einer Achse", t2_text: "Bei Spiegelung an der x-Achse bleibt x gleich und y wechselt das Vorzeichen. An der y-Achse wechselt x das Vorzeichen.", t2_b1: "x-Achse: (x, y) wird (x, -y).", t2_b2: "y-Achse: (x, y) wird (-x, y).",
    t2_inst: "Sortiere die Bilder von P(2, 3) nach der Spiegelachse.", t2_h1: "Die Koordinate senkrecht zum Spiegel wechselt das Vorzeichen.", t2_h2: "An x: (2, -3); an y: (-2, 3).", t2_x: "Spiegelung an x-Achse", t2_y: "Spiegelung an y-Achse", t2_i1: "(2, -3)", t2_i2: "x bleibt 2", t2_i3: "(-2, 3)", t2_i4: "y bleibt 3",
    t2_q: "Spiegle (-4, 1) an der y-Achse.", t2_q_a1: "(4, 1)", t2_q_a2: "(-4, -1)", t2_q_a3: "(1, -4)", t2_q_a4: "(4, -1)",
    t3_title: "Drehung um den Ursprung", t3_text: "Eine Drehung um 90 Grad gegen den Uhrzeigersinn bildet (x, y) auf (-y, x) ab. Bei 180 Grad wird daraus (-x, -y).", t3_b1: "Drehungen erhalten Laengen und Winkel.", t3_b2: "Drehrichtung und Zentrum muessen bekannt sein.",
    t3_inst: "Ordne jedem Punkt sein Bild nach 90 Grad gegen den Uhrzeigersinn zu.", t3_h1: "Nutze (x, y) wird (-y, x).", t3_h2: "Vertausche die Koordinaten und negiere das neue x.", t3_l1: "(2, 1)", t3_r1: "(-1, 2)", t3_l2: "(-3, 2)", t3_r2: "(-2, -3)", t3_l3: "(0, -4)", t3_r3: "(4, 0)",
    t3_q: "Drehe (3, -2) um 180 Grad um den Ursprung.", t3_q_a1: "(-3, 2)", t3_q_a2: "(2, 3)", t3_q_a3: "(-2, -3)", t3_q_a4: "(3, 2)",
  },
  hu: {
    explorer_title: "Geometriai transzformaciok",
    t1_title: "Eltolas", t1_text: "Az eltolas minden pontot ugyanazzal a vektorral mozgat. A (4, -2) vektort A(-1, 3)-hoz adva A'(3, 1) lesz.", t1_b1: "A vizszintes valtozast add x-hez.", t1_b2: "A fuggoleges valtozast add y-hoz.",
    t1_inst: "Jelold A(-1, 3) kepet a (4, -2) vektorral valo eltolas utan.", t1_h1: "Szamold ki: -1 + 4 es 3 - 2.", t1_h2: "A keppont (3, 1).", t1_q: "Told el a (2, -1) pontot a (-3, 5) vektorral.", t1_q_a1: "(-1, 4)", t1_q_a2: "(5, -6)", t1_q_a3: "(-5, 6)", t1_q_a4: "(1, 4)",
    t2_title: "Tukrozes tengelyre", t2_text: "Az x tengelyre tukrozes megtartja x-et es megforditja y elojelet. Az y tengelyre tukrozes x elojelet forditja meg.", t2_b1: "x tengely: (x, y) kepe (x, -y).", t2_b2: "y tengely: (x, y) kepe (-x, y).",
    t2_inst: "Rendezd P(2, 3) kepeit a tukrozes tengelye szerint.", t2_h1: "A tukorre meroleges koordinata elojele valtozik.", t2_h2: "x tengelyre: (2, -3); y tengelyre: (-2, 3).", t2_x: "tukrozes x tengelyre", t2_y: "tukrozes y tengelyre", t2_i1: "(2, -3)", t2_i2: "x erteke 2 marad", t2_i3: "(-2, 3)", t2_i4: "y erteke 3 marad",
    t2_q: "Tukrozd a (-4, 1) pontot az y tengelyre.", t2_q_a1: "(4, 1)", t2_q_a2: "(-4, -1)", t2_q_a3: "(1, -4)", t2_q_a4: "(4, -1)",
    t3_title: "Forgatas az origon korul", t3_text: "Az origon koruli 90 fokos pozitiv forgatas (x, y) pontot (-y, x)-be visz. A 180 fokos forgatas kepe (-x, -y).", t3_b1: "A forgatas megtartja a hosszt es a szoget.", t3_b2: "A forgatas iranya es kozeppontja fontos.",
    t3_inst: "Parositsd a pontokat a 90 fokos pozitiv forgatas utani kepukkel.", t3_h1: "Hasznald: (x, y) kepe (-y, x).", t3_h2: "Csereld fel a koordinatakat, majd az uj x elojelet valtoztasd meg.", t3_l1: "(2, 1)", t3_r1: "(-1, 2)", t3_l2: "(-3, 2)", t3_r2: "(-2, -3)", t3_l3: "(0, -4)", t3_r3: "(4, 0)",
    t3_q: "Forgasd a (3, -2) pontot 180 fokkal az origon korul.", t3_q_a1: "(-3, 2)", t3_q_a2: "(2, 3)", t3_q_a3: "(-2, -3)", t3_q_a4: "(3, 2)",
  },
  ro: {
    explorer_title: "Transformari geometrice",
    t1_title: "Translatia", t1_text: "O translatie muta fiecare punct cu acelasi vector. Adaugand (4, -2) la A(-1, 3), obtinem A'(3, 1).", t1_b1: "Aduna schimbarea orizontala la x.", t1_b2: "Aduna schimbarea verticala la y.",
    t1_inst: "Marcheaza imaginea lui A(-1, 3) dupa translatia cu (4, -2).", t1_h1: "Calculeaza -1 + 4 si 3 - 2.", t1_h2: "Imaginea este (3, 1).", t1_q: "Translateaza (2, -1) cu vectorul (-3, 5).", t1_q_a1: "(-1, 4)", t1_q_a2: "(5, -6)", t1_q_a3: "(-5, 6)", t1_q_a4: "(1, 4)",
    t2_title: "Reflexia fata de o axa", t2_text: "Reflexia fata de axa x pastreaza x si schimba semnul lui y. Fata de axa y se schimba semnul lui x.", t2_b1: "axa x: (x, y) devine (x, -y).", t2_b2: "axa y: (x, y) devine (-x, y).",
    t2_inst: "Sorteaza imaginile lui P(2, 3) dupa axa de reflexie.", t2_h1: "Coordonata perpendiculara pe oglinda isi schimba semnul.", t2_h2: "Fata de x: (2, -3); fata de y: (-2, 3).", t2_x: "reflexie fata de axa x", t2_y: "reflexie fata de axa y", t2_i1: "(2, -3)", t2_i2: "x ramane 2", t2_i3: "(-2, 3)", t2_i4: "y ramane 3",
    t2_q: "Reflecta (-4, 1) fata de axa y.", t2_q_a1: "(4, 1)", t2_q_a2: "(-4, -1)", t2_q_a3: "(1, -4)", t2_q_a4: "(4, -1)",
    t3_title: "Rotatia in jurul originii", t3_text: "O rotatie de 90 de grade in sens trigonometric transforma (x, y) in (-y, x). La 180 de grade devine (-x, -y).", t3_b1: "Rotatiile pastreaza lungimile si unghiurile.", t3_b2: "Sensul si centrul rotatiei trebuie precizate.",
    t3_inst: "Asociaza fiecare punct cu imaginea sa dupa 90 de grade in sens trigonometric.", t3_h1: "Foloseste (x, y) devine (-y, x).", t3_h2: "Inverseaza coordonatele, apoi schimba semnul noului x.", t3_l1: "(2, 1)", t3_r1: "(-1, 2)", t3_l2: "(-3, 2)", t3_r2: "(-2, -3)", t3_l3: "(0, -4)", t3_r3: "(4, 0)",
    t3_q: "Roteste (3, -2) cu 180 de grade in jurul originii.", t3_q_a1: "(-3, 2)", t3_q_a2: "(2, 3)", t3_q_a3: "(-2, -3)", t3_q_a4: "(3, 2)",
  },
};

const TRANSFORMEXPLORER8_TOPICS: TopicDef[] = [
  {
    infoTitle: "t1_title", infoText: "t1_text", bulletKeys: ["t1_b1", "t1_b2"],
    svg: () => <PlaneCard accent="#EC4899" caption="translation by (4, -2)" points={[{ x: -1, y: 3, label: "A" }, { x: 3, y: 1, label: "A'" }]} />,
    interactive: { type: "coordinate-picker", targetX: 3, targetY: 1, range: 5, instruction: "t1_inst", hint1: "t1_h1", hint2: "t1_h2" },
    quiz: { question: "t1_q", choices: ["t1_q_a1", "t1_q_a2", "t1_q_a3", "t1_q_a4"], answer: "t1_q_a1" },
  },
  {
    infoTitle: "t2_title", infoText: "t2_text", bulletKeys: ["t2_b1", "t2_b2"],
    svg: () => <PlaneCard accent="#EC4899" caption="reflections of P(2, 3)" points={[{ x: 2, y: 3, label: "P" }, { x: 2, y: -3, label: "Px" }, { x: -2, y: 3, label: "Py" }]} />,
    interactive: { type: "drag-to-bucket", buckets: [{ id: "x", label: "t2_x" }, { id: "y", label: "t2_y" }], items: [{ text: "t2_i1", bucketId: "x" }, { text: "t2_i2", bucketId: "x" }, { text: "t2_i3", bucketId: "y" }, { text: "t2_i4", bucketId: "y" }], instruction: "t2_inst", hint1: "t2_h1", hint2: "t2_h2" },
    quiz: { question: "t2_q", choices: ["t2_q_a1", "t2_q_a2", "t2_q_a3", "t2_q_a4"], answer: "t2_q_a1" },
  },
  {
    infoTitle: "t3_title", infoText: "t3_text", bulletKeys: ["t3_b1", "t3_b2"],
    svg: () => <PlaneCard accent="#EC4899" caption="90 deg counterclockwise" points={[{ x: 2, y: 1, label: "P" }, { x: -1, y: 2, label: "P'" }]} />,
    interactive: { type: "match-pairs", pairs: [{ left: "t3_l1", right: "t3_r1" }, { left: "t3_l2", right: "t3_r2" }, { left: "t3_l3", right: "t3_r3" }], instruction: "t3_inst", hint1: "t3_h1", hint2: "t3_h2" },
    quiz: { question: "t3_q", choices: ["t3_q_a1", "t3_q_a2", "t3_q_a3", "t3_q_a4"], answer: "t3_q_a1" },
  },
];

export const TRANSFORMEXPLORER8_DEF: ExplorerDef = buildDef(TRANSFORMEXPLORER8_LABELS, "MOVE", TRANSFORMEXPLORER8_TOPICS);
