import type { DeutschTheme } from "./types";

// ═══════════════════════════════════════════════════════════════════════════════
// K6 — Satzstrukturen (Klasse 6)
// ═══════════════════════════════════════════════════════════════════════════════

export const K6_SATZSTRUKTUREN: DeutschTheme[] = [
  {
    id: "satzstrukturen_k6",
    name: "Satzstrukturen",
    color: "#10B981",
    icon: "🔗",
    subtopics: [

      // ─── 1. Haupt- & Nebensatz ───────────────────────────────────────────────
      {
        id: "hauptsatz_nebensatz_k6",
        name: "Haupt- & Nebensatz",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Was ist ein Hauptsatz?", options: ["Ein Satz, der von einem anderen abhängt", "Ein Satz, der alleine stehen kann", "Ein Satz ohne Verb", "Ein Satz mit Konjunktion am Anfang"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welches Wort leitet einen Nebensatz ein?", options: ["und", "aber", "weil", "doch"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Ergänze die Konjunktion: 'Ich bleibe zu Hause, ___ ich krank bin.'", answer: ["weil", "da"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Wo steht das konjugierte Verb im Nebensatz?", options: ["An erster Stelle", "An zweiter Stelle", "Am Ende des Satzes", "Vor dem Subjekt"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Setze das Verb richtig: 'Er sagt, dass er morgen ___ (kommen).'", answer: ["kommt"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welchen Unterschied gibt es zwischen 'weil' und 'da'?", options: ["'weil' leitet einen Hauptsatz ein, 'da' einen Nebensatz", "'da' steht immer am Satzanfang, 'weil' nie", "'weil' betont den Grund stärker; 'da' setzt einen bekannten Grund voraus", "Es gibt keinen Unterschied"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welcher Satz ist grammatisch korrekt?", options: ["Ich gehe nicht, weil ich müde bin.", "Ich gehe nicht, weil bin ich müde.", "Ich gehe nicht weil ich bin müde.", "Weil ich bin müde, gehe ich nicht."], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Setze das Komma richtig: 'Sie lacht obwohl sie traurig ist.'", answer: ["Sie lacht, obwohl sie traurig ist."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Was bedeutet 'obwohl' in einem Nebensatz?", options: ["Es drückt einen Grund aus.", "Es drückt einen Gegensatz / Einschränkung aus.", "Es drückt eine Bedingung aus.", "Es drückt eine Folge aus."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Verbinde die Sätze mit 'dass': 'Ich glaube. Er hat recht.' → Ich glaube, ___", answer: ["dass er recht hat."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "In welchem Satz fehlt das Komma?", options: ["Er kommt, weil er Hunger hat.", "Sie schläft, weil sie müde ist.", "Ich lese weil es regnet.", "Du isst, obwohl du satt bist."], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welche Konjunktion leitet einen Kausalsatz ein?", options: ["obwohl", "wenn", "weil", "damit"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Bilde einen Nebensatz mit 'obwohl': Er geht spazieren. Es regnet. → Er geht spazieren, ___", answer: ["obwohl es regnet."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welcher Nebensatz passt zum Hauptsatz 'Ich freue mich, ...'?", options: ["..., weil du kommst.", "..., aber du kommst.", "..., und du kommst.", "..., denn du kommst."], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Ergänze: 'Ich weiß nicht, ___ er kommt.' (ob/dass)", answer: ["ob"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Was ist ein Konsekutivsatz?", options: ["Ein Satz, der einen Grund angibt", "Ein Satz, der eine Folge ausdrückt (sodass)", "Ein Satz, der eine Bedingung nennt", "Ein Satz, der eine Zeit angibt"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welche Konjunktion leitet einen Konzessivsatz ein?", options: ["weil", "wenn", "obwohl", "dass"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Erkläre kurz: Was passiert mit dem Verb im Nebensatz?", answer: ["Es steht am Ende.", "Das Verb steht am Ende des Nebensatzes.", "Es steht am Satzende."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welcher Satz ist ein Objektsatz?", options: ["Als es dunkel wurde, gingen wir nach Hause.", "Er hofft, dass er gewinnt.", "Obwohl es kalt war, schwammen sie.", "Weil es regnete, blieben wir drin."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Schreibe den Satz mit 'da' um: 'Weil alle müde waren, gingen sie früh schlafen.'", answer: ["Da alle müde waren, gingen sie früh schlafen."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "In welchem Satz steht 'dass' korrekt?", options: ["Ich denke, das er recht hat.", "Ich denke, dass er recht hat.", "Ich denke dass, er recht hat.", "Ich denke das er recht, hat."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Ein Temporalsatz gibt … an.", options: ["einen Grund", "eine Zeit", "eine Bedingung", "eine Folge"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welche Konjunktion passt? 'Ich lerne viel, ___ ich gute Noten bekomme.' (Zweck)", answer: ["damit"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welcher Satz enthält einen Finalsatz?", options: ["Er lernt, weil er klug sein will.", "Er lernt, damit er klug wird.", "Er lernt, obwohl er müde ist.", "Er lernt, als er jung war."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Setze das Verb ans Ende: 'Sie sagt, dass sie morgen ___ wird.' (kommen)", answer: ["kommen"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welche Konjunktion drückt eine Bedingung aus?", options: ["obwohl", "weil", "wenn", "dass"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Bilde einen Konditionalsatz: 'Wenn es morgen regnet, ___.'", answer: ["bleiben wir zu Hause.", "gehe ich nicht raus.", "nehme ich einen Schirm mit."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Vor welcher Konjunktion steht kein Komma?", options: ["weil", "obwohl", "dass", "und"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Korrigiere den Fehler: 'Er sagt, dass er gern Fußball spielt wird.'", answer: ["Er sagt, dass er gern Fußball spielen wird."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "hauptsatz_nebensatz_k6", question: "Welcher Nebensatz passt zum Typ 'Kausalsatz'?", options: ["als es Abend wurde", "damit sie schlafen kann", "weil sie müde ist", "obwohl sie müde ist"], correct: 2 },
        ],
      },

      // ─── 2. Satzverbindungen ─────────────────────────────────────────────────
      {
        id: "satzverbindungen_k6",
        name: "Satzverbindungen",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was sind koordinierende Konjunktionen?", options: ["Sie verbinden Haupt- und Nebensatz.", "Sie verbinden zwei gleichrangige Sätze oder Satzglieder.", "Sie stehen immer am Satzende.", "Sie leiten Relativsätze ein."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welche Konjunktion drückt einen Gegensatz aus?", options: ["und", "oder", "aber", "denn"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Verbinde die Sätze mit 'denn': 'Er bleibt zu Hause. Er ist krank.'", answer: ["Er bleibt zu Hause, denn er ist krank."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welche Konjunktion gibt einen Grund an (kein Nebensatz)?", options: ["weil", "denn", "obwohl", "damit"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was ist der Unterschied zwischen 'denn' und 'weil'?", answer: ["'denn' verbindet zwei Hauptsätze, 'weil' leitet einen Nebensatz ein.", "denn verbindet Hauptsätze, weil leitet Nebensätze ein."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was ist ein Konjunktionaladverb?", options: ["Ein Verb mit Konjunktion", "Ein Adverb, das zwei Sätze verbindet (z.B. deshalb, trotzdem)", "Ein Adjektiv im Nebensatz", "Eine Konjunktion im Hauptsatz"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welches Wort ist ein Konjunktionaladverb?", options: ["weil", "obwohl", "deshalb", "dass"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Ergänze das Konjunktionaladverb: 'Es regnete. ___ blieben wir zu Hause.' (Folge)", answer: ["Deshalb", "Daher", "Darum"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was folgt nach einem Konjunktionaladverb am Satzanfang?", options: ["Subjekt, dann Verb", "Verb, dann Subjekt (Inversion)", "Das Objekt", "Ein Nebensatz"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Bilde einen Satz mit 'trotzdem': 'Es regnete. Wir gingen spazieren.'", answer: ["Es regnete. Trotzdem gingen wir spazieren.", "Es regnete, trotzdem gingen wir spazieren."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welcher Satz benutzt 'dann' korrekt?", options: ["Er aß Frühstück, dann er ging in die Schule.", "Er aß Frühstück, dann ging er in die Schule.", "Dann er aß Frühstück und ging in die Schule.", "Er dann aß Frühstück und ging."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Wann steht ein Semikolon zwischen Sätzen?", options: ["Immer statt Komma", "Wenn man zwei inhaltlich eng verwandte Hauptsätze trennt", "Vor jedem 'und'", "Nach jedem Nebensatz"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Verbinde mit 'oder': 'Wir fahren in die Berge. Wir bleiben am Meer.'", answer: ["Wir fahren in die Berge, oder wir bleiben am Meer.", "Wir fahren in die Berge oder wir bleiben am Meer."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welcher Satz enthält 'doch' korrekt als Konjunktion?", options: ["Er wollte kommen, doch er hatte keine Zeit.", "Er wollte doch kommen, hatte keine Zeit.", "Doch er wollte kommen er hatte keine Zeit.", "Er hatte keine Zeit doch, er wollte kommen."], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Erkläre: Was bedeutet 'trotzdem' in einem Satz?", answer: ["Es drückt einen Gegensatz aus.", "Obwohl etwas dagegen spricht, passiert es trotzdem.", "Es zeigt einen Widerspruch."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welches Konjunktionaladverb drückt eine Folge aus?", options: ["trotzdem", "außerdem", "deshalb", "dann"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Schreibe einen Satz mit 'außerdem' als Konjunktionaladverb.", answer: ["Sie ist klug. Außerdem ist sie fleißig.", "Er spielt Fußball. Außerdem schwimmt er gern."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Vor 'aber' zwischen zwei Hauptsätzen steht …?", options: ["ein Semikolon", "kein Satzzeichen", "ein Komma", "ein Punkt"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Schreibe den Satz mit Inversion: 'Ich bin müde. Trotzdem lerne ich weiter.'", answer: ["Ich bin müde. Trotzdem lerne ich weiter."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was ändert sich an der Wortstellung, wenn ein Satz mit 'deshalb' beginnt?", options: ["Das Subjekt steht zuerst", "Das Verb steht an zweiter Stelle (vor dem Subjekt)", "Das Objekt wird ans Ende gestellt", "Nichts ändert sich"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welcher Satz ist grammatisch falsch?", options: ["Er ist krank, deshalb bleibt er zu Hause.", "Er ist krank, daher bleibt er zu Hause.", "Er ist krank, deshalb er bleibt zu Hause.", "Er ist krank; deshalb bleibt er zu Hause."], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Nenne zwei weitere Konjunktionaladverbien außer 'deshalb' und 'trotzdem'.", answer: ["dann, außerdem", "daher, danach", "darum, jedoch"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welches Wort ist KEIN Konjunktionaladverb?", options: ["deshalb", "trotzdem", "dann", "obwohl"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Verbinde mit Semikolon: 'Die Sonne schien hell. Die Vögel sangen fröhlich.'", answer: ["Die Sonne schien hell; die Vögel sangen fröhlich."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Was drückt 'und' zwischen zwei Hauptsätzen aus?", options: ["Gegensatz", "Aufzählung / Anreihung", "Begründung", "Bedingung"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welcher Satz enthält 'doch' richtig als Gegenkonjunktion?", options: ["Doch er kam zu spät.", "Er wollte pünktlich sein, doch er kam zu spät.", "Er doch kam zu spät.", "Er kam doch zu spät er wollte pünktlich sein."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Schreibe den Satz mit 'jedoch' um: 'Er war müde, aber er arbeitete weiter.'", answer: ["Er war müde, jedoch arbeitete er weiter.", "Er war müde; jedoch arbeitete er weiter."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "'Danach' ist ein …?", options: ["koordinierende Konjunktion", "subordinierende Konjunktion", "Konjunktionaladverb", "Relativpronomen"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Ergänze: 'Sie aß Mittag. ___ machte sie einen Spaziergang.'", answer: ["Danach"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzverbindungen_k6", question: "Welcher Satz verwendet 'oder' korrekt?", options: ["Oder du kommst morgen, oder du bleibst.", "Du kommst morgen oder du bleibst zu Hause.", "Du oder kommst morgen oder bleibst.", "Du kommst morgen, oder du bleibst zu Hause."], correct: 3 },
        ],
      },

      // ─── 3. Satzbau ─────────────────────────────────────────────────────────
      {
        id: "satzbau_k6",
        name: "Satzbau",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was versteht man unter der 'Verbklammer'?", options: ["Das Verb steht immer am Anfang.", "Zweiteiliges Prädikat: konjugiertes Verb an 2. Stelle, Verbzusatz am Ende.", "Das Verb steht immer am Ende.", "Verb und Objekt stehen nebeneinander."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Benenne die Verbklammer: 'Sie hat gestern das Buch ___.' Welches Wort fehlt am Ende?", answer: ["gelesen", "gekauft"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welche Stelle nimmt das konjugierte Verb im Aussagesatz ein?", options: ["Erste Stelle", "Zweite Stelle", "Letzte Stelle", "Dritte Stelle"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Schreibe den Satz in der richtigen Reihenfolge: 'gestern / ich / ins Kino / bin / gegangen.'", answer: ["Ich bin gestern ins Kino gegangen."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was ist 'Inversion' im Satzbau?", options: ["Das Objekt steht am Anfang.", "Das Subjekt steht vor dem Verb.", "Subjekt und Verb tauschen die Plätze (z.B. bei Satzglied an erster Stelle).", "Das Verb steht am Ende."], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welcher Satz zeigt Inversion?", options: ["Ich gehe morgen in die Schule.", "Morgen gehe ich in die Schule.", "In die Schule gehe morgen ich.", "Die Schule ich morgen gehe."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Bilde den Satz mit Topikalisierung (Adverb an erster Stelle): 'Er spielt oft Fußball.'", answer: ["Oft spielt er Fußball."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was ist 'Topikalisierung'?", options: ["Ein Satzglied wird ans Ende gestellt.", "Ein Satzglied wird an die erste Stelle gestellt, um es zu betonen.", "Das Subjekt bleibt immer an erster Stelle.", "Das Verb wird an die erste Stelle gestellt."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was steht in einem deutschen Aussagesatz immer an zweiter Stelle?", options: ["Das Subjekt", "Das Objekt", "Das konjugierte Verb", "Das Adverb"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Erkläre: Was ist das Mittelfeld im deutschen Satz?", answer: ["Der Bereich zwischen dem konjugierten Verb und dem Satzende.", "Der Teil zwischen Verb und Verbzusatz."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welcher Satz ist korrekt?", options: ["Heute ich fahre nach Berlin.", "Heute fahre ich nach Berlin.", "Fahre heute ich nach Berlin.", "Ich heute fahre nach Berlin."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Forme um, sodass das Objekt an erster Stelle steht: 'Ich lese das Buch gern.'", answer: ["Das Buch lese ich gern."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "In welcher Stellung steht der Infinitiv im Satz 'Er kann gut schwimmen.'?", options: ["An zweiter Stelle", "An erster Stelle", "Am Satzende", "Vor dem Subjekt"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welches Satzglied wird durch Topikalisierung betont?", options: ["Immer das Verb", "Das Satzglied an erster Stelle", "Das Objekt", "Das Subjekt"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Schreibe den Satz mit Inversion: 'Am Wochenende. Er besucht seine Oma.'", answer: ["Am Wochenende besucht er seine Oma."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was steht im Vorfeld (Position 1) am häufigsten?", options: ["Das Objekt", "Das Subjekt oder ein anderes betontes Satzglied", "Ein Infinitiv", "Ein Komma"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Ordne korrekt: 'Maria / hat / gestern / ein Buch / gelesen.'", answer: ["Maria hat gestern ein Buch gelesen."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was bildet bei trennbaren Verben die Verbklammer?", options: ["Adjektiv + Verb", "Konjugiertes Präfix-Verb (Position 2) + Präfix am Ende", "Subjekt + Verb", "Hauptverb + Modalverb"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Forme um — stelle das Temporaladverb an erste Stelle: 'Sie ruft morgen an.'", answer: ["Morgen ruft sie an."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was ist die typische Satzgliedfolge im deutschen Hauptsatz?", options: ["Objekt – Verb – Subjekt", "Subjekt – Verb – Objekt(e)", "Verb – Subjekt – Objekt", "Objekt – Subjekt – Verb"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welches Satzglied kann NICHT im Vorfeld stehen?", options: ["Temporaladverbiale", "Akkusativobjekt", "Subjekt", "Konjunktion 'weil'"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was ist das 'Nachfeld'?", answer: ["Der Teil nach dem letzten Verb/Verbzusatz.", "Alles, was nach der rechten Verbklammer steht."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Im Fragesatz ohne Fragewort steht das Verb …?", options: ["Am Ende", "An zweiter Stelle", "An erster Stelle", "An dritter Stelle"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Forme um mit Lokaladverb vorne: 'Wir spielen im Park Fußball.'", answer: ["Im Park spielen wir Fußball."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Was versteht man unter 'Ausklammerung'?", options: ["Ein Satzglied wird aus dem Mittelfeld ans Ende gestellt.", "Ein Satzglied wird aus dem Satz gelöscht.", "Das Verb wird ausgeklammert.", "Das Subjekt wird ausgeklammert."], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Zeige Verbklammer: Unterstreiche Anfang und Ende: 'Er hat das Buch gelesen.'", answer: ["'hat' und 'gelesen' bilden die Verbklammer."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welcher Satz zeigt ein Modalverb mit Verbklammer?", options: ["Er liest gern Bücher.", "Er musste das Buch lesen.", "Er hat das Buch.", "Er las das Buch."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welcher Satz ist falsch geordnet?", options: ["Den Hund füttert sie täglich.", "Täglich füttert sie den Hund.", "Sie füttert täglich den Hund.", "Täglich den Hund füttert sie."], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Bilde einen Satz mit Verbklammer (Perfekt): 'wir / das Museum / besuchen (Perfekt)'", answer: ["Wir haben das Museum besucht."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "satzbau_k6", question: "Welche Aussage über die Verbzweitstellung ist richtig?", options: ["Sie gilt nur für Fragen.", "Das Verb steht im Aussagesatz immer an zweiter Position.", "Das Verb steht immer am Anfang.", "Es gibt keine feste Verbstellung."], correct: 1 },
        ],
      },

      // ─── 4. Relativsätze ─────────────────────────────────────────────────────
      {
        id: "erweiterte_relativsaetze_k6",
        name: "Relativsätze",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Was ist ein Relativsatz?", options: ["Ein Satz mit einer Kausalkonjunktion", "Ein Nebensatz, der ein Nomen näher beschreibt", "Ein Satz mit einem Frageadverb", "Ein Satz ohne Verb"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen passt? 'Das Mädchen, ___ hier sitzt, ist meine Schwester.'", options: ["der", "das", "die", "den"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze das Relativpronomen: 'Der Mann, ___ du gestern getroffen hast, heißt Klaus.'", answer: ["den"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen steht im Genitiv Singular Maskulinum?", options: ["der", "dem", "dessen", "deren"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Das ist die Frau, ___ Auto vor der Schule steht.'", answer: ["deren"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Was stimmt über den Relativsatz?", options: ["Er steht vor dem Bezugsnomen.", "Er wird durch Kommata vom Hauptsatz getrennt.", "Das Verb steht an zweiter Stelle.", "Er kann ohne Komma stehen."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen passt? 'Das Buch, ___ ich lese, ist spannend.'", options: ["der", "die", "das", "dem"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Bilde einen Relativsatz: 'Das Fahrrad ist neu. Es gehört mir.' → Das Fahrrad, ___, ist neu.", answer: ["das mir gehört"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen steht im Dativ Plural?", options: ["die", "der", "dem", "denen"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Die Kinder, ___ wir geholfen haben, sind sehr dankbar.'", answer: ["denen"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welcher Satz hat einen korrekten Relativsatz?", options: ["Das Buch das ich lese, ist toll.", "Das Buch, das ich lese, ist toll.", "Das Buch, das lese ich, ist toll.", "Das Buch das lese, ist toll ich."], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Was bestimmt das Genus des Relativpronomens?", options: ["Die Konjunktion", "Das Bezugsnomen im Hauptsatz", "Das Verb des Relativsatzes", "Das Subjekt des Hauptsatzes"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze das Relativpronomen: 'Das Haus, in ___ wir wohnen, ist sehr alt.'", answer: ["dem"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Was ist ein Relativsatz mit Präposition?", options: ["Ein Relativsatz ohne Relativpronomen", "Ein Relativsatz, in dem das Relativpronomen einer Präposition folgt (z.B. 'in dem')", "Ein Relativsatz im Genitiv", "Ein Relativsatz mit 'was'"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Der Verein, ___ ich angehöre, feiert Jubiläum.'", answer: ["dem"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen steht im Nominativ Maskulinum?", options: ["dem", "den", "der", "dessen"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welcher Satz ist falsch?", options: ["Das ist der Lehrer, dem ich vertraue.", "Das ist der Lehrer, der mich unterrichtet.", "Das ist der Lehrer, den ich mag.", "Das ist der Lehrer, die ich mag."], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Der Schüler, ___ Heft ich nehme, ist mein Freund.'", answer: ["dessen"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen ist kein Relativpronomen?", options: ["der", "die", "das", "weil"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Bilde einen Relativsatz: 'Die Stadt ist schön. Ich komme aus ihr.' → Die Stadt, ___", answer: ["aus der ich komme, ist schön."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welches Relativpronomen steht im Akkusativ Maskulinum?", options: ["der", "dem", "den", "dessen"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welcher Satz enthält einen Relativsatz mit Präposition?", options: ["Das ist das Buch, das ich lese.", "Das ist das Buch, über das wir gesprochen haben.", "Das ist das Buch, dessen Autor berühmt ist.", "Das ist das Buch, dem ich gehöre."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Das Konzert, auf ___ ich mich freue, ist morgen.'", answer: ["das"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Wo steht das Verb im Relativsatz?", options: ["An zweiter Stelle", "Am Ende", "An erster Stelle", "Vor dem Relativpronomen"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Forme um: 'Das Mädchen ist freundlich. Sein Vater ist Lehrer.' → Das Mädchen, ___", answer: ["dessen Vater Lehrer ist, ist freundlich."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Was ist der Kasus des Relativpronomens in: 'Der Mann, dem ich helfe, ist alt.'?", options: ["Nominativ", "Akkusativ", "Dativ", "Genitiv"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Welcher Kasus fehlt in der Relativpronomen-Tabelle: Nom./Akk./___/Gen.?", options: ["Ablativ", "Vokativ", "Dativ", "Lokativ"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Ergänze: 'Alles, ___ er sagt, ist wahr.' (was oder das?)", answer: ["was"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Wann benutzt man 'was' als Relativpronomen?", options: ["Bei Personennomen", "Nach Indefinitpronomen (alles, nichts, etwas) oder ganzen Sätzen", "Immer statt 'das'", "Bei Dativobjekten"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "erweiterte_relativsaetze_k6", question: "Bilde den Relativsatz: 'Der Film war gut. Ich habe ihn gestern gesehen.' → Der Film, ___", answer: ["den ich gestern gesehen habe, war gut."] },
        ],
      },

      // ─── 5. Fragewörter & Fragesätze ─────────────────────────────────────────
      {
        id: "fragewörter_k6",
        name: "Fragewörter & Fragesätze",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach einer Person als Subjekt?", options: ["Was", "Wen", "Wer", "Wem"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Mit welchem Fragewort fragt man nach dem Akkusativobjekt (Person)?", options: ["Wer", "Wem", "Wen", "Wessen"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort passt? '___ gehört dieses Buch?' (Dativ, Person)", answer: ["Wem"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Mit welchem Fragewort fragt man nach einem Ort (Ruhelage)?", options: ["Wohin", "Woher", "Wo", "Wann"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Forme eine W-Frage: 'Er geht um 8 Uhr in die Schule.' → ___ geht er in die Schule?", answer: ["Wann"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach einer Richtung?", options: ["Wo", "Woher", "Wohin", "Wann"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Was ist eine Entscheidungsfrage?", options: ["Eine Frage mit Fragewort", "Eine Frage, die mit Ja oder Nein beantwortet wird", "Eine Frage im Nebensatz", "Eine Frage nach dem Subjekt"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Bilde eine Entscheidungsfrage: 'Er kommt morgen.' → ___", answer: ["Kommt er morgen?"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Wo steht das Verb in einer Entscheidungsfrage?", options: ["An zweiter Stelle", "Am Ende", "An erster Stelle", "An dritter Stelle"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Was ist eine indirekte Frage?", options: ["Eine Frage mit Ausrufezeichen", "Eine Frage, die in einen Nebensatz eingebettet ist", "Eine Frage mit Fragewort", "Eine Frage ohne Verb"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Forme in eine indirekte Frage um: 'Wann kommt er?' → Ich frage mich, ___", answer: ["wann er kommt."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Wie endet eine indirekte Frage aus einer Entscheidungsfrage?", options: ["Mit einem Fragewort", "Mit 'ob' + Nebensatz", "Mit einem Komma", "Mit 'dass' + Hauptsatz"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Forme um: 'Hat er die Hausaufgaben gemacht?' → Ich weiß nicht, ___", answer: ["ob er die Hausaufgaben gemacht hat."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach einem Grund?", options: ["Wie", "Was", "Warum", "Welch-"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Forme in eine indirekte Frage: 'Warum bist du traurig?' → Er fragt, ___", answer: ["warum ich traurig bin."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach einer Herkunft?", options: ["Wohin", "Wo", "Woher", "Wann"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Wort leitet eine indirekte Entscheidungsfrage ein?", options: ["dass", "weil", "ob", "wenn"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Bilde eine W-Frage nach dem unterstrichenen Teil: 'Sie fährt nach Berlin.'", answer: ["Wohin fährt sie?"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welcher Satz ist eine korrekte indirekte Frage?", options: ["Ich frage mich, wo er ist.", "Ich frage mich, wo ist er.", "Ich frage mich, wo er ist?", "Wo er ist, ich frage mich."], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort passt? '___ Buch liest du gerade?' (Auswahl unter mehreren)", answer: ["Welches"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach der Art und Weise?", options: ["Wann", "Wo", "Wie", "Was"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Was stimmt über W-Fragen?", options: ["Das Verb steht am Ende.", "Das Fragewort steht an erster Stelle, Verb an zweiter.", "Das Subjekt steht immer am Anfang.", "Das Verb steht an erster Stelle."], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Stelle eine Frage nach dem Besitzer: '___ Tasche ist das?'", answer: ["Wessen"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welcher Satz ist eine korrekte W-Frage?", options: ["Du bist wann gekommen?", "Wann du bist gekommen?", "Wann bist du gekommen?", "Wann gekommen bist du?"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Ergänze die indirekte Frage: 'Ich weiß nicht, ___ er arbeitet.' (Ort)", answer: ["wo"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort ist deklinierbar (verändert seine Form)?", options: ["wo", "wann", "warum", "welch-"], correct: 3 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "In welchem Satz ist die Wortstellung falsch?", options: ["Was liest du?", "Wo bist du gewesen?", "Warum du weinst?", "Wie heißt du?"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Forme um: 'Wie heißt du?' → Sie fragt, ___", answer: ["wie er/sie heißt.", "wie ich heiße."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Welches Fragewort fragt nach einer Sache als Objekt?", options: ["Wer", "Wem", "Wen", "Was"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "fragewörter_k6", question: "Bilde eine Frage: Die Antwort ist 'Er kommt wegen des Wetters nicht.' → ___ kommt er nicht?", answer: ["Warum", "Weshalb", "Weswegen"] },
        ],
      },

      // ─── 6. Imperativsatz ────────────────────────────────────────────────────
      {
        id: "imperativsatz_k6",
        name: "Imperativsatz",
        questions: [
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Was drückt ein Imperativsatz aus?", options: ["Eine Frage", "Eine Aufforderung, Bitte oder ein Befehl", "Eine Verneinung", "Eine Bedingung"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (du) von 'kommen'?", options: ["Kommt!", "Kommen!", "Komm!", "Komme!"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Bilde den Imperativ (du): 'essen'", answer: ["Iss!", "Esse!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (ihr) von 'schreiben'?", options: ["Schreib!", "Schreibt!", "Schreiben!", "Schreibe!"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Bilde den Imperativ (Sie - Höflichkeitsform): 'bitte / nehmen'", answer: ["Nehmen Sie bitte!", "Nehmen Sie Platz, bitte!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (Sie) von 'kommen'?", options: ["Komm Sie!", "Kommen Sie!", "Kommt Sie!", "Komme Sie!"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Was ist höflicher: 'Setz dich!' oder 'Könntest du dich bitte setzen?'", options: ["'Setz dich!' ist höflicher.", "Beide sind gleichwertig.", "'Könntest du dich bitte setzen?' ist höflicher.", "Keine von beiden ist höflich."], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Schreibe die höfliche Bitte: 'Öffne das Fenster!' (Sie-Form)", answer: ["Öffnen Sie bitte das Fenster!", "Würden Sie bitte das Fenster öffnen?"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welches Satzzeichen steht nach einem Befehl?", options: ["Komma", "Punkt oder Ausrufezeichen", "Fragezeichen", "Semikolon"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welcher Imperativ ist falsch?", options: ["Lauf!", "Lauft!", "Laufen Sie!", "Lauft ihr!"], correct: 3 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Bilde den Imperativ (ihr) von 'sein'.", answer: ["Seid!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (du) von 'lesen'?", options: ["Lese!", "Liest!", "Lies!", "Lesen!"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Forme eine höfliche Bitte aus: 'Warten Sie.' → '___ Sie bitte ___.'", answer: ["Warten Sie bitte."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welche Form des Imperativs verwendet man bei Erwachsenen, die man nicht kennt?", options: ["du-Form", "ihr-Form", "Sie-Form", "wir-Form"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (du) von 'helfen'?", options: ["Helfe!", "Hilf!", "Helf!", "Helft!"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Schreibe eine höfliche Aufforderung (Sie-Form): 'ankommen / pünktlich'", answer: ["Kommen Sie bitte pünktlich an!", "Kommen Sie pünktlich an!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wo steht das Verb im Imperativsatz?", options: ["Am Ende", "An zweiter Stelle", "An erster Stelle", "Vor dem Objekt"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Bilde den Imperativ (du): 'aufmachen' (trennbares Verb)", answer: ["Mach auf!", "Mach die Tür auf!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (wir) von 'gehen' (Vorschlag)?", options: ["Geh!", "Geht!", "Gehen wir!", "Gehen Sie!"], correct: 2 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welcher Satz ist eine höfliche Bitte?", options: ["Gib mir das sofort!", "Würden Sie mir bitte helfen?", "Her damit!", "Los, mach schon!"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Forme um (höflicher): 'Sitz ruhig!' → '___ Sie bitte ___.'", answer: ["Sitzen Sie bitte ruhig!", "Setzen Sie sich bitte."] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welcher Imperativ ist für eine Gruppe von Freunden (ihr)?", options: ["Komm schnell!", "Kommen Sie schnell!", "Kommt schnell!", "Kommen wir!"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Ergänze den Imperativ: '___ (sein, ihr) still!'", answer: ["Seid"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welche Verbform benutzt man beim Imperativ (Sie) grundsätzlich?", options: ["Den Infinitiv + Sie", "Die Infinitivform des Verbs steht vor 'Sie'", "Den Infinitiv am Ende", "Den Konjunktiv"], correct: 1 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Forme in Imperativ (du): 'du sollst das Fenster schließen'", answer: ["Schließ das Fenster!", "Mach das Fenster zu!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie macht man einen Imperativ höflicher?", options: ["Durch Großschreibung", "Durch Hinzufügen von 'bitte' oder Modalverben wie 'könnten/würden'", "Durch ein Komma am Ende", "Durch den Konjunktiv II"], correct: 1 },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Welcher Satz verwendet den Imperativ trennbarer Verben korrekt?", options: ["Ruf mich an!", "Anruf mich!", "Rufe mich an!", "Ruf an mich!"], correct: 0 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Bilde den Imperativ (ihr) von 'mitkommen'.", answer: ["Kommt mit!"] },
          { type: "mcq", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Wie lautet der Imperativ (du) von 'nehmen'?", options: ["Nehme!", "Nehmt!", "Nimm!", "Nimmst!"], correct: 2 },
          { type: "typing", topic: "satzstrukturen_k6", subtopic: "imperativsatz_k6", question: "Schreibe eine höfliche Bitte mit Modalverb: 'Würden ___ mir ___ helfen?' (Sie)", answer: ["Würden Sie mir bitte helfen?"] },
        ],
      },
    ],
  },
];
