import type { DeutschTheme } from "./types";

export const K7_VERBEN: DeutschTheme[] = [
  {
    id: "verben_vertieft_k7",
    name: "Verben vertiefen",
    icon: "🔄",
    color: "#3B82F6",
    subtopics: [
      {
        id: "konjunktiv1_vertieft_k7",
        name: "Konjunktiv I vertiefen",
        questions: [
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Er sagt: 'Ich bin muede.' -> Indirekte Rede (3. Person Sg.)?",
            options: ["Er sagt, er sei muede.", "Er sagt, er ist muede.", "Er sagt, er waere muede.", "Er sagt, er sein muede."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Setze in indirekte Rede (Konj. I): Sie sagt: 'Ich habe Zeit.'",
            answer: ["Sie sagt, sie habe Zeit.", "Sie sagt, sie habe Zeit"],
            hint: "habe (Konj. I von haben)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Warum ersetzt man Konjunktiv I manchmal durch Konjunktiv II?",
            options: ["Wenn Konj. I mit Indikativ identisch waere", "Wenn die Aussage unwahr ist", "Wenn das Verb unregelmaessig ist", "Wenn kein Komma gesetzt wird"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte Rede (Konj. I, 1. Pl.): Wir sagen: 'Wir haben keine Zeit.' -> Sie sagen, sie ... keine Zeit.",
            answer: ["haetten", "hätten"],
            hint: "Konj. I von 'haben' (1. Pl.) = haben -> aber identisch mit Indikativ, daher Konj. II: haetten",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Er fragt: 'Kommst du morgen?' -> Indirekte Frage (ja/nein)?",
            options: ["Er fragt, ob sie morgen komme.", "Er fragt, ob sie morgen kommen.", "Er fragt, dass sie morgen komme.", "Er fragt, ob sie morgen kame."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte W-Frage: Sie fragt: 'Wo wohnst du?' -> Sie fragt, ... er wohne.",
            answer: ["wo", "wo"],
            hint: "W-Frage bleibt als Einleitung erhalten",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Konjunktiv I von 'sein' (3. Person Singular)?",
            options: ["sei", "ist", "waere", "seien"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte Rede (Konj. I): Er berichtet: 'Das Wetter wird schoen sein.' -> Er berichtet, das Wetter ... schoen ...",
            answer: ["werde schoen sein", "werde ... sein"],
            hint: "Zukunft in der indirekten Rede: werde + Infinitiv",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Perfekt in der indirekten Rede: 'Ich habe geschlafen.' -> Er sagt, er ...",
            options: ["habe geschlafen", "hatte geschlafen", "hat geschlafen", "haette geschlafen"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Pronomenverschiebung: Ich sage: 'Ich liebe meine Arbeit.' -> Ich sage, ich liebe ... Arbeit.",
            answer: ["meine", "meine"],
            hint: "Bei Ich-Perspektive bleibt 'meine' erhalten, wenn dieselbe Person spricht",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Er sagt: 'Wir gehen ins Kino.' -> Indirekte Rede (Konj. I, 1. Pl.)?",
            options: ["Er sagt, sie gingen ins Kino.", "Er sagt, sie gehen ins Kino.", "Er sagt, sie gehe ins Kino.", "Er sagt, sie sein ins Kino gegangen."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte Rede: Die Lehrerin sagt: 'Die Schueler sind fleissig.' -> Die Lehrerin sagt, die Schueler ... fleissig.",
            answer: ["seien", "seien"],
            hint: "sein (Konj. I, 3. Pl.) = seien",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte Frage mit W-Wort: Er fragt: 'Warum bist du traurig?' -> Indirekte Rede?",
            options: ["Er fragt, warum sie traurig sei.", "Er fragt, ob sie traurig sei.", "Er fragt, dass sie traurig sei.", "Er fragt, warum sie traurig ist."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Konj. I von 'fahren' (3. Person Singular)?",
            answer: ["fahre", "fahre"],
            hint: "Infinitivstamm + e: fahr + e",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Sie sagt: 'Ich werde morgen kommen.' -> Indirekte Rede (Konj. I)?",
            options: ["Sie sagt, sie werde morgen kommen.", "Sie sagt, sie wird morgen kommen.", "Sie sagt, sie kame morgen.", "Sie sagt, sie sei morgen gekommen."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Indirekte Rede (Perfekt, Konj. I): Er sagt: 'Ich bin gereist.' -> Er sagt, er ... gereist.",
            answer: ["sei gereist", "sei ... gereist"],
            hint: "Perfekt mit sein: sei + Partizip II",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Wann benutzt man 'dass' in der indirekten Rede?",
            options: ["Optional, wenn der Nebensatz eingeleitet wird", "Immer nach dem Verb 'sagen'", "Nur bei Fragen", "Nie in der indirekten Rede"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Ergaenze den Konjunktiv I: Der Arzt sagt, der Patient ... (muessen) mehr schlafen.",
            answer: ["muesse", "müsse"],
            hint: "muss (Indikativ) -> muesse (Konj. I)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Konjunktiv I von 'koennen' (3. Person Singular)?",
            options: ["koenne", "koennte", "kann", "koennten"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "konjunktiv1_vertieft_k7",
            question: "Bilde die indirekte Frage: Er fragt: 'Wie alt bist du?' -> Er fragt, wie alt ...",
            answer: ["sie sei.", "er sei.", "sie sei", "er sei"],
            hint: "Konj. I von sein (3. Sg.) = sei; Verb ans Ende des Nebensatzes",
          },
        ],
      },
      {
        id: "plusquamperfekt_k7",
        name: "Plusquamperfekt",
        questions: [
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Wie bildet man das Plusquamperfekt von 'lesen'?",
            options: ["hatte gelesen", "hat gelesen", "war gelesen", "haette gelesen"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Bilde das Plusquamperfekt von 'kommen' (3. Person Singular)?",
            answer: ["war gekommen", "war gekommen"],
            hint: "kommen bildet Perfekt mit 'sein'",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Welcher Satz verwendet das Plusquamperfekt korrekt?",
            options: ["Nachdem er gegessen hatte, ging er schlafen.", "Nachdem er gegessen hat, ging er schlafen.", "Nachdem er aß, hatte er geschlafen.", "Er hatte gegessen, bevor er schlaeft."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Ergaenze: Nachdem wir den Film gesehen ..., gingen wir nach Hause.",
            answer: ["hatten", "hatten"],
            hint: "wir + Plusquamperfekt: hatten + Partizip II",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Was drueckt das Plusquamperfekt aus?",
            options: ["Eine Handlung, die vor einer anderen Vergangenheitshandlung abgeschlossen war", "Eine zukunftige Handlung in der Vergangenheit", "Einen Zustand in der Gegenwart", "Eine wiederholte Handlung in der Vergangenheit"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Plusquamperfekt von 'schreiben' (ich)?",
            answer: ["hatte geschrieben", "hatte geschrieben"],
            hint: "hatte + Partizip II (unregelmaessig: schreiben -> geschrieben)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Ergaenze: Als er ankam, ... seine Freunde schon ... (gehen).",
            options: ["waren ... gegangen", "hatten ... gegangen", "sind ... gegangen", "waren ... gehen"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Bilde einen Satz mit 'nachdem' und Plusquamperfekt: Sie / lernen / schlafen gehen.",
            answer: ["Nachdem sie gelernt hatte, ging sie schlafen.", "Nachdem sie gelernt hatte, ist sie schlafen gegangen."],
            hint: "Plusquamperfekt im Nebensatz, Praeteritum im Hauptsatz",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Welches Hilfsverb verwendet 'reisen' im Plusquamperfekt?",
            options: ["war", "hatte", "ist", "hat"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Plusquamperfekt von 'arbeiten' (er)?",
            answer: ["hatte gearbeitet", "hatte gearbeitet"],
            hint: "regelmaessiges Verb: gearbeitet",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Welche Konjunktion signalisiert oft das Plusquamperfekt im Nebensatz?",
            options: ["nachdem", "waehrend", "weil", "obwohl"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Ergaenze: Bevor der Zug ankam, ... er schon ... (einschlafen).",
            answer: ["war er schon eingeschlafen", "war ... eingeschlafen"],
            hint: "einschlafen -> eingeschlafen, Hilfsverb: war",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Welcher Satz ist grammatikalisch richtig?",
            options: ["Nachdem er aufgeraeumt hatte, kochte er.", "Nachdem er aufgeraeumt hatte, hat er gekocht.", "Nachdem er aufraeumte, hatte er gekocht.", "Nachdem er aufgeraeumt war, kochte er."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Forme in Plusquamperfekt um: Sie lernte. -> Sie ...",
            answer: ["hatte gelernt", "hatte gelernt"],
            hint: "Praeteritum -> Plusquamperfekt: hatte + Partizip II",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Plusquamperfekt von 'fallen' (er)?",
            options: ["war gefallen", "hatte gefallen", "ist gefallen", "hatte gefallt"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Ergaenze die Zeitsequenz: Erst ... er das Buch gelesen ..., dann schaute er den Film. (haben)",
            answer: ["hatte ... gelesen", "hatte er das Buch gelesen"],
            hint: "Plusquamperfekt fuer die frueherer Handlung",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Was ist falsch an: 'Nachdem ich gegessen habe, schlief ich.'?",
            options: ["'habe' sollte 'hatte' sein (Plusquamperfekt noetig)", "'schlief' sollte 'schlafe' sein", "'habe' sollte 'sein' sein", "Der Satz ist korrekt"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Plusquamperfekt: Als das Spiel begann, ... die Zuschauer schon ihre Plaetze ... (einnehmen).",
            answer: ["hatten ... eingenommen", "hatten die Zuschauer schon ihre Plaetze eingenommen"],
            hint: "einnehmen -> eingenommen (unregelmaessig), Hilfsverb: hatten",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Welches Verb bildet Plusquamperfekt mit 'war'?",
            options: ["sterben", "machen", "lesen", "sagen"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "plusquamperfekt_k7",
            question: "Schreibe den Satz im Plusquamperfekt: Er vergisst seine Hausaufgaben.",
            answer: ["Er hatte seine Hausaufgaben vergessen.", "Er hatte seine Hausaufgaben vergessen"],
            hint: "vergessen -> Partizip II: vergessen (unregelmaessig, aber identisch)",
          },
        ],
      },
      {
        id: "verbrektion_k7",
        name: "Verbrektion",
        questions: [
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition steht bei 'warten'?",
            options: ["auf + Akkusativ", "auf + Dativ", "fuer + Akkusativ", "an + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Ich warte ... den Bus. (warten + Praeposition + Akkusativ)",
            answer: ["auf", "auf"],
            hint: "warten auf + Akkusativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welcher Satz ist korrekt?",
            options: ["Sie freut sich ueber das Geschenk.", "Sie freut sich fuer das Geschenk.", "Sie freut sich auf das Geschenk.", "Sie freut sich an das Geschenk."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Praeposition bei 'abhaengen'? Beispiel: Das Ergebnis haengt ... der Arbeit ab.",
            answer: ["von", "von"],
            hint: "abhaengen von + Dativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition und Kasus bei 'teilnehmen'?",
            options: ["an + Dativ", "an + Akkusativ", "bei + Dativ", "in + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Er interessiert sich ... Musik. (sich interessieren + Praeposition)",
            answer: ["fuer", "für"],
            hint: "sich interessieren fuer + Akkusativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Sie denkt oft ... ihren Urlaub. (denken + Praeposition + Akkusativ)",
            options: ["an", "auf", "von", "ueber"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Wir freuen uns ... die Ferien. (sich freuen auf = Zukunft + Akkusativ)",
            answer: ["auf", "auf"],
            hint: "sich freuen auf (Zukunft) + Akkusativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition bei 'sprechen ueber'?",
            options: ["ueber + Akkusativ", "ueber + Dativ", "von + Dativ", "mit + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Bilde einen Satz: sich beschweren + ueber + Akkusativ. Thema: der Laerm.",
            answer: ["Sie beschwert sich ueber den Laerm.", "Er beschwert sich ueber den Laerm.", "Ich beschwere mich ueber den Laerm."],
            hint: "sich beschweren ueber + Akkusativ: den Laerm (Maskulinum, Akk.)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition bei 'sich kuemmern'?",
            options: ["um + Akkusativ", "fuer + Akkusativ", "mit + Dativ", "an + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Praeposition und Kasus: 'bitten'. Beispiel: Ich bitte dich ... Hilfe.",
            answer: ["um", "um"],
            hint: "bitten um + Akkusativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welcher Satz ist richtig?",
            options: ["Er haengt von seinen Eltern ab.", "Er haengt an seinen Eltern ab.", "Er haengt fuer seine Eltern ab.", "Er haengt bei seinen Eltern ab."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Die Studenten nehmen ... dem Seminar teil.",
            answer: ["an", "an"],
            hint: "teilnehmen an + Dativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition bei 'sich erinnern'?",
            options: ["an + Akkusativ", "auf + Akkusativ", "von + Dativ", "zu + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Sie zweifelt ... seiner Ehrlichkeit.",
            answer: ["an", "an"],
            hint: "zweifeln an + Dativ",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition bei 'sich bewerben'?",
            options: ["um + Akkusativ", "fuer + Akkusativ", "auf + Akkusativ", "zu + Dativ"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Welche Praeposition: 'glauben ... jemanden' (jemandem vertrauen)?",
            answer: ["an", "an"],
            hint: "glauben an + Akkusativ (bei Personen/Konzepten)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Ergaenze: Der Lehrer wartet ... die Antwort der Schueler. Welche Praeposition?",
            options: ["auf", "fuer", "von", "nach"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "verbrektion_k7",
            question: "Bilde einen Satz mit 'sich freuen ueber' (Vergangenheit): Er / das Lob.",
            answer: ["Er freute sich ueber das Lob.", "Er hat sich ueber das Lob gefreut.", "Er freute sich ueber das Lob"],
            hint: "sich freuen ueber + Akkusativ: das Lob (Neutrum, Akk. = das Lob)",
          },
        ],
      },
      {
        id: "passivformen_vertieft_k7",
        name: "Passiv: Perfekt und Futur",
        questions: [
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Wie bildet man das Passiv Perfekt?",
            options: ["ist/sind + Partizip II + worden", "hat/haben + Partizip II + geworden", "wird + Partizip II + werden", "wurde + Partizip II"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Bilde Passiv Perfekt: 'Man hat das Auto repariert.' -> Das Auto ...",
            answer: ["ist repariert worden.", "ist repariert worden"],
            hint: "Passiv Perfekt: ist + Partizip II + worden (NICHT geworden!)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Welcher Satz ist Passiv Perfekt (korrekt)?",
            options: ["Das Buch ist geschrieben worden.", "Das Buch ist geschrieben geworden.", "Das Buch wurde geschrieben worden.", "Das Buch hat geschrieben worden."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Futur: 'Man wird das Problem loesen.' -> Das Problem ...",
            answer: ["wird geloest werden.", "wird geloest werden"],
            hint: "Passiv Futur: wird + Partizip II + werden",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Warum heisst es 'worden' und NICHT 'geworden' im Passiv Perfekt?",
            options: ["'worden' ist die Passiv-Partizip-Form von 'werden', 'geworden' gehoert zum Aktiv-Perfekt", "Beide Formen sind korrekt", "'geworden' ist veraltet", "'worden' ist nur im Sueddeutschen korrekt"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Bilde Passiv Perfekt (Plural): 'Man hat die Fenster geputzt.' -> Die Fenster ...",
            answer: ["sind geputzt worden.", "sind geputzt worden"],
            hint: "Plural: sind + Partizip II + worden",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Futur von 'bauen' (das Haus)?",
            options: ["Das Haus wird gebaut werden.", "Das Haus wird gebaut werden haben.", "Das Haus ist gebaut worden werden.", "Das Haus wird bauen werden."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Forme um ins Passiv Perfekt: 'Man hat den Taeter verhaftet.' -> Der Taeter ...",
            answer: ["ist verhaftet worden.", "ist verhaftet worden"],
            hint: "verhaftet worden (NICHT geworden)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Welches Hilfsverb steht im Passiv Perfekt bei Bewegungsverben?",
            options: ["ist/sind + Partizip II + worden", "hat/haben + Partizip II + worden", "wird + Partizip II + worden", "war + Partizip II + worden"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Futur Plural: 'Man wird die Preise erhoehen.' -> Die Preise ...",
            answer: ["werden erhoeht werden.", "werden erhoeht werden"],
            hint: "Passiv Futur Plural: werden + Partizip II + werden",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Welcher Satz ist Passiv Futur (korrekt)?",
            options: ["Die Bruecke wird repariert werden.", "Die Bruecke ist repariert worden.", "Die Bruecke wird repariert worden sein.", "Die Bruecke wurde repariert werden."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Erklaere den Unterschied: 'Das Haus ist gebaut worden.' vs. 'Das Haus ist gebaut geworden.' Welches ist korrekt?",
            answer: ["Das Haus ist gebaut worden.", "worden"],
            hint: "Im Passiv Perfekt immer 'worden', nicht 'geworden'",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Perfekt von 'einladen' (die Gaeste)?",
            options: ["Die Gaeste sind eingeladen worden.", "Die Gaeste haben eingeladen worden.", "Die Gaeste sind eingeladen geworden.", "Die Gaeste wurden eingeladen worden."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Bilde Passiv Futur: 'Man wird das Konzert absagen.' -> Das Konzert ...",
            answer: ["wird abgesagt werden.", "wird abgesagt werden"],
            hint: "abgesagt (Partizip II von absagen) + werden",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Was ist der Unterschied zwischen 'wurde repariert' und 'ist repariert worden'?",
            options: ["'wurde repariert' = Praeteritum Passiv; 'ist repariert worden' = Perfekt Passiv", "Beide bedeuten dasselbe und sind immer austauschbar", "'wurde repariert' ist Perfekt; 'ist repariert worden' ist Praeteritum", "'ist repariert worden' ist veraltet"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Perfekt: 'Man hat den Brief geschrieben.' -> Der Brief ...",
            answer: ["ist geschrieben worden.", "ist geschrieben worden"],
            hint: "schreiben -> geschrieben; Passiv Perfekt: ist + Partizip II + worden",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Futur von 'informieren' (die Buerger)?",
            options: ["Die Buerger werden informiert werden.", "Die Buerger werden informiert worden.", "Die Buerger sind informiert worden.", "Die Buerger werden informiert werden haben."],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Forme um: 'Man hat das Gebaeude renoviert.' -> Passiv Perfekt: Das Gebaeude ...",
            answer: ["ist renoviert worden.", "ist renoviert worden"],
            hint: "renoviert worden (passiv, kein 'geworden'!)",
          },
          {
            type: "mcq",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Welche Form ist im Passiv Perfekt FALSCH?",
            options: ["ist gemacht geworden", "ist gemacht worden", "sind gemacht worden", "war gemacht worden"],
            correct: 0,
          },
          {
            type: "typing",
            topic: "verben_vertieft_k7",
            subtopic: "passivformen_vertieft_k7",
            question: "Passiv Futur: 'Man wird die Ergebnisse veroeffentlichen.' -> Die Ergebnisse ...",
            answer: ["werden veroeffentlicht werden.", "werden veroeffentlicht werden"],
            hint: "veroeffentlicht (Partizip II) + werden am Ende",
          },
        ],
      },
    ],
  },
];
