import { DeutschTheme, DeutschQuestion } from "./types";

const satzperiode_k8: any[] = [
  { type: "mcq", question: "Was ist eine 'Satzperiode'?", options: ["Ein zusammenhängender Satz mit mehreren Haupt- und Nebensätzen, die eine komplexe Gedankenstruktur bilden", "Ein langer Satz ohne Pause", "Ein Satz mit vielen Wörtern", "Ein Satz mit mehreren Themen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode besteht aus mindestens einem _____ und einem _____.", answer: ["Hauptsatz", "Nebensatz"] },
  { type: "mcq", question: "Welche Struktur hat eine klassische Satzperiode?", options: ["Sie steigt in der Komplexität an und endet mit der Hauptaussage (Spannungsbogen)", "Sie beginnt mit der Hauptaussage", "Sie hat keine besondere Struktur", "Sie ist völlig unprediktabel"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode verwendet oft einen _____, um Spannung aufzubauen.", answer: ["Spannungsbogen", "Auf- und Abbau"] },
  { type: "mcq", question: "Was ist der Unterschied zwischen Asyndeton und Polysyndeton in Satzperioden?", options: ["Asyndeton: wenig Konjunktionen; Polysyndeton: viele Konjunktionen", "Asyndeton: kurze Sätze; Polysyndeton: lange Sätze", "Asyndeton: formal; Polysyndeton: informell", "Asyndeton: Alt; Polysyndeton: Neu"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode mit weniger Bindewörtern ist ein _____ Satzbau.", answer: ["asyndeton", "asyndetischer"] },
  { type: "mcq", question: "Welche Funktion erfüllt eine Satzperiode literarisch?", options: ["Sie schafft Spannung und Nachdruck durch Verzögerung der Hauptaussage", "Sie verstärkt die Lesbarkeit", "Sie verkürzt den Text", "Sie ersetzt Synonyme"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Die Analyse einer Satzperiode erfordert das Erkennen der _____ der Haupt- und Nebensätze.", answer: ["Struktur", "Hierarchie", "Abfolge"] },
  { type: "mcq", question: "Was ist die 'rhetorische Periode'?", options: ["Eine Satzperiode, die bewusst gestaltet ist für stilistische/emotionale Wirkung", "Eine wissenschaftliche Periode", "Eine historische Zeitspanne", "Ein grammatisches Phänomen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Beispiel: 'Wenn man die Komplexität einer Satzperiode versteht, die aus mehreren Nebensätzen besteht, die alle auf einen Hauptgedanken hinweisen, dann erkennt man, wie Sprache Spannung aufbaut.' Die Spannung endet mit der _____.", answer: ["Hauptaussage", "Pointe"] },
  { type: "mcq", question: "Welche Reihenfolge folgt eine klassische deutsche Satzperiode oft?", options: ["Vorbereitende Nebensätze → Hauptsatz (Höhepunkt)", "Hauptsatz → Nebensätze", "Nebensätze → Nebensätze → Hauptsatz", "Beliebige Reihenfolge"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode erzeugt durch ihre Struktur eine Art _____.", answer: ["Spannung", "Spannungsbogen", "dramatischer Aufbau"] },
  { type: "mcq", question: "Wie analysiert man die Struktur einer Satzperiode?", options: ["Durch Identifikation der Haupt- und Nebensätze und deren hierarchische Beziehung zueinander", "Durch Zählen der Wörter", "Durch Überprüfung der Titelwahl", "Durch Betrachtung der Schriftart"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Die Analyse von Satzperioden ist oft Teil der _____ Textanalyse.", answer: ["stilistischen", "literarischen"] },
  { type: "mcq", question: "Welche Wirkung hat die Verzögerung der Hauptaussage in einer Satzperiode?", options: ["Erzeugt Spannung und verstärkt die Aufmerksamkeit des Lesers", "Langweilt den Leser", "Verwirrt die Bedeutung", "Hat keine Wirkung"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode ist ein wichtiges Stilmittel in der _____.", answer: ["Literatur", "Rhetorik", "Prosa"] },
  { type: "mcq", question: "Wie viele Sätze kann eine Satzperiode enthalten?", options: ["Eine oder mehr Haupt- und/oder Nebensätze (mindestens 2 Sätze)", "Immer genau zwei", "Immer genau drei", "Unbegrenzt, ohne Minimum"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Eine Satzperiode mit progressiver Struktur baut bis zur _____ hin auf.", answer: ["Pointe", "Klimax", "Hauptaussage"] },
  { type: "mcq", question: "Welche Satzarten können in einer Satzperiode vorkommen?", options: ["Haupt-, Neben- und Infinitivsätze", "Nur Hauptsätze", "Nur Nebensätze", "Nur Fragesätze"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Die Struktur einer Satzperiode folgt oft einem _____ Aufbau.", answer: ["dramatischen", "dramaturgischen", "spannungsgeladenen"] },
  { type: "mcq", question: "Wie beginnt eine Satzperiode typischerweise?", options: ["Mit Nebensätzen oder vorbereitenden Elementen", "Mit der Hauptaussage", "Mit einer Frage", "Mit einer Ausrufung"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzperiode_k8" },
  { type: "typing", question: "Die Analyse einer Satzperiode erfordert das Verstehen der sprachlichen _____.", answer: ["Struktur", "Hierarchie", "Komplexität"] },
];

const konnektoren_k8: any[] = [
  { type: "mcq", question: "Was ist ein 'Konnektor' oder 'Bindewort'?", options: ["Ein Wort, das zwei Sätze oder Satzteile logisch miteinander verbindet", "Ein Wort zwischen Verben", "Ein Wort zwischen Adjektiven", "Ein Wort zwischen Nomen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'folglich' drückt eine _____ aus.", answer: ["Folge", "Konsequenz", "Schlussfolgerung"] },
  { type: "mcq", question: "Welcher Konnektor drückt einen Gegensatz aus?", options: ["obgleich, wenngleich, zwar", "folglich, demnach", "außerdem, fernerhin", "nämlich, dabei"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'demnach' wird verwendet, um eine _____ auszudrücken.", answer: ["Folge", "Schlussfolgerung"] },
  { type: "mcq", question: "Welcher Konnektor drückt Hinzufügung aus?", options: ["außerdem, ferner, hinzu kommt", "zwar, allerdings", "folglich, darum", "indessen, währenddessen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'indessen' wird verwendet, um Gegenstellung oder _____ auszudrücken.", answer: ["Kontrast", "Gegensatz", "Wechsel"] },
  { type: "mcq", question: "Welcher Konnektor drückt Bestätigung aus?", options: ["tatsächlich, in der Tat, wirklich", "allerdings, indes", "folglich, daher", "obgleich, zwar"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'nämlich' wird verwendet, um etwas zu _____ oder zu erklären.", answer: ["präzisieren", "verdeutlichen", "erläutern"] },
  { type: "mcq", question: "Welcher Konnektor drückt Kausalität aus?", options: ["denn, da, weil, schließlich", "außerdem, fernerhin", "obgleich, zwar", "indessen, allerdings"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'davon abgesehen' wird verwendet, um ein _____ oder eine Ausnahme auszudrücken.", answer: ["Zugeständnis", "Einlenken"] },
  { type: "mcq", question: "Welcher Konnektor wird verwendet, um etwas Offensichtliches zu betonen?", options: ["offenbar, anscheinend, augenscheinlich", "übrigens, nebenbei", "jedenfalls, immerhin", "schließlich, nach all"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'kurz gesagt' wird verwendet, um etwas zu _____.", answer: ["zusammenfassen", "resümieren", "verdichten"] },
  { type: "mcq", question: "Welcher Konnektor drückt Bedingung aus?", options: ["falls, sofern, wenn, vorausgesetzt", "folglich, demnach", "obgleich, zwar", "außerdem, ferner"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'einerseits ... andererseits' wird verwendet, um zwei _____ auszudrücken.", answer: ["Aspekte", "Standpunkte", "Seiten"] },
  { type: "mcq", question: "Welcher Konnektor drückt Zeitmäßigkeit aus?", options: ["inzwischen, währenddessen, unterdessen", "folglich, demnach", "obgleich, zwar", "außerdem, hinzu kommt"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'vielmehr' wird verwendet, um etwas zu _____ oder zu korrigieren.", answer: ["präzisieren", "berichtigen", "klarstellen"] },
  { type: "mcq", question: "Welcher Konnektor drückt Verstärkung aus?", options: ["besonders, vor allem, insbesondere", "folglich, demnach", "obgleich, zwar", "allerdings, indessen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'gleichwohl' wird verwendet, um einen _____ oder Gegensatz auszudrücken.", answer: ["Kontrast", "Widerspruch", "Gegensatz"] },
  { type: "mcq", question: "Welcher Konnektor wird verwendet, um eine Ergänzung hinzuzufügen?", options: ["überdies, obendrein, zudem", "folglich, demnach", "obgleich, zwar", "allerdings, indessen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'immerhin' wird verwendet, um etwas _____ oder einzugestehen.", answer: ["zuzugeben", "zu konzedieren", "anzuerkennen"] },
  { type: "mcq", question: "Welcher Konnektor drückt Alternativen aus?", options: ["andernfalls, sonst, anstatt", "außerdem, ferner", "folglich, demnach", "obgleich, zwar"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'hingegen' wird verwendet, um einen _____ auszudrücken.", answer: ["Gegensatz", "Kontrast", "Wechsel"] },
  { type: "mcq", question: "Welcher Konnektor wird verwendet, um Abschluss auszudrücken?", options: ["abschließend, zusammengefasst, letztendlich", "außerdem, ferner", "folglich, demnach", "obgleich, zwar"], correct: 0, topic: "satzstrukturen_k8", subtopic: "konnektoren_k8" },
  { type: "typing", question: "Das Konnektor 'nichtsdestotrotz' wird verwendet, um einen _____ oder Gegensatz auszudrücken.", answer: ["Kontrast", "Gegensatz", "Widerspruch"] },
];

const parenthese_k8: any[] = [
  { type: "mcq", question: "Was ist eine 'Parenthese'?", options: ["Ein Einschub oder Zusatz, der aus dem Redefluss herausgenommen werden kann, ohne den Sinn zu verändern", "Ein zusätzlicher Satz", "Ein Nebensatz", "Ein Bindewort"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Beispiel: 'Der Baum (ein alter Eiche) stand im Garten.' Die Parenthese ist: (ein alter Eiche) oder einfach: _____.", answer: ["Eiche"] },
  { type: "mcq", question: "Was ist eine 'Apposition'?", options: ["Ein gleichsetzendes Attribut, das ein anderes Nomen näher bestimmt (ohne Bindewort)", "Ein Zusatz mit Bindewort", "Ein Nomen im Genitiv", "Ein Adjektiv"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Beispiel: 'Mein Freund Karl kommt morgen.' 'Karl' ist eine _____ zu 'Freund'.", answer: ["Apposition", "Appositive"] },
  { type: "mcq", question: "Wie werden Appositionen typischerweise gekennzeichnet?", options: ["Mit Kommas oder Gedankenstrichen", "Mit Klammern", "Mit Doppelpunkt", "Gar nicht"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Eine Apposition kann mit einem _____ oder einem Gedankenstrich eingeleitet werden.", answer: ["Komma", "Doppelpunkt"] },
  { type: "mcq", question: "Was ist der Unterschied zwischen Parenthese und Apposition?", options: ["Parenthese ist ein beliebiger Einschub; Apposition ist ein nominales Attribut ohne Bindewort", "Parenthese ist kürzer; Apposition ist länger", "Parenthese in Klammern; Apposition mit Kommas", "Sie sind identisch"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Eine Apposition ist immer ein _____ oder eine _____ Konstruktion.", answer: ["Nomen", "nominalistische", "nominale"] },
  { type: "mcq", question: "Welche Funktion erfüllt eine Parenthese im Text?", options: ["Sie liefert zusätzliche Informationen ohne den Hauptgedanken zu unterbrechen", "Sie betont den Hauptgedanken", "Sie ändert die Bedeutung", "Sie verlängert den Satz unnötig"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Ein Beispiel für eine Parenthese: 'Die Stadt (an der Donau gelegen) ist sehr schön.' Die Parenthese ist: _____.", answer: ["an der Donau gelegen"] },
  { type: "mcq", question: "Kann eine Parenthese entfernt werden, ohne dass der Satz unvollständig wird?", options: ["Ja, sie ist ein optionaler Zusatz", "Nein, sie ist notwendig", "Nur manchmal", "Hängt vom Kontext ab"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Eine Parenthese wird oft in _____ oder mit Gedankenstrichen gekennzeichnet.", answer: ["Klammern", "Kommas"] },
  { type: "mcq", question: "Kann eine Apposition ohne Kommas stehen?", options: ["Ja, bei sehr eng verbundenen Nomina (z.B. der König Ludwig)", "Nein, immer mit Kommas", "Nur in modernem Deutsch", "Nur in Nominalisierungen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Beispiel: 'Der Schriftsteller Goethe war sehr produktiv.' 'Goethe' ist eine _____ zu 'Schriftsteller' (ohne Komma).", answer: ["enge Apposition", "Apposition"] },
  { type: "mcq", question: "Welche Stellung kann eine Apposition haben?", options: ["Vor, nach oder innerhalb des Nomens, das sie bestimmt", "Nur danach", "Nur davor", "Nur außerhalb"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Eine Parenthese kann eine vollständige _____ oder eine unvollständige Aussage enthalten.", answer: ["Aussage", "Information"] },
  { type: "mcq", question: "Wie wird eine Parenthese in Klammern geschrieben?", options: ["Wort (zusätzliche Informattion) weiterer Text", "Wort [zusätzliche Information] weiterer Text", "Wort {zusätzliche Information} weiterer Text", "Wort - zusätzliche Information - weiterer Text"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Beispiel: 'Das Auto (ein modernes Modell) fährt schnell.' Die Parenthese ändert den Sinn NICHT, wenn man sie weglässt: 'Das Auto fährt _____'.", answer: ["schnell"] },
  { type: "mcq", question: "Können mehrere Appositionen auf ein Nomen folgen?", options: ["Ja, sie können nebeneinander oder hintereinander stehen", "Nein, nur eine pro Nomen", "Nur bei Titeln", "Nur in formeller Sprache"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
  { type: "typing", question: "Mehrere Appositionen: 'Der König, Friedrich Wilhelm III., der Prussian Monarch, war ...' Die Appositionen sind: Friedrich Wilhelm III. und _____.", answer: ["der Prussian Monarch", "der preußische König"] },
  { type: "mcq", question: "Welche Satzzeichen können bei Parenthesen verwendet werden?", options: ["Kommas, Gedankenstriche oder runde Klammern", "Nur Kommas", "Nur Klammern", "Nur Gedankenstriche"], correct: 0, topic: "satzstrukturen_k8", subtopic: "parenthese_k8" },
];

const satzgliedstellung_k8: any[] = [
  { type: "mcq", question: "Was ist die 'Satzgliedstellung' oder 'Wortstellung'?", options: ["Die Reihenfolge der Satzglieder im Satz, die die Bedeutung und Betonung beeinflussen kann", "Die Reihenfolge der Verben", "Die Anordnung von Adjektiven", "Die Anordnung von Präpositionen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Im Hauptsatz ist die typische Reihenfolge: Subjekt - Verb - Objekt oder _____ Ordnung.", answer: ["SVO", "Subjekt-Verb-Objekt"] },
  { type: "mcq", question: "Welche Inversion ist möglich? 'Das Buch liegt auf dem Tisch.' → '... auf dem Tisch liegt das Buch.'", options: ["Ja, durch Inversion wird das Satzglied vorangestellt", "Nein, das ist ungrammatisch", "Nur in Fragen", "Nur in Nebensätzen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Die Inversion, bei der ein Satzglied vor das Verb tritt, wird verwendet, um _____ zu betonen.", answer: ["das Satzglied", "einen Fokus"] },
  { type: "mcq", question: "Was ist das Typische für die deutsche Satzklammer?", options: ["Das Verb wird in zwei Teile aufgespalten (z.B. 'hat ... gelesen')", "Das Verb steht am Anfang", "Das Verb steht am Ende", "Das Verb wiederholt sich"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "In einem Hauptsatz: 'Der Mann _____ das Buch _____ gelesen.' Die Satzklammer umfasst Hilfsverb und Partizip.", answer: ["hat", ""] },
  { type: "mcq", question: "Wie lautet die typische Satzgliedfolge in einem Nebensatz?", options: ["Subjekt - Objekte/Satzergänzungen - Verb am Ende", "Verb - Subjekt - Objekte", "Objekte - Verb - Subjekt", "Beliebige Reihenfolge"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "In Nebensätzen steht das Verb typically am _____.", answer: ["Ende", "Satzende"] },
  { type: "mcq", question: "Was bewirkt die 'Extraposition' von Satzgliedern?", options: ["Sie ermöglicht das Voranstellen oder Nachstellen von Satzgliedern zur Betonung oder Vorbereitung", "Sie ändert die Grammatik", "Sie verkürzt den Satz", "Sie hat keine Funktion"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Beispiel: 'Ich mag Bücher sehr gerne.' Die typische Reihenfolge ist Subjekt - Verb - Objekt - Adverbial. Die Adverbial-Stellung bestimmt den _____.", answer: ["Fokus", "Fokusbereich"] },
  { type: "mcq", question: "Was ist die 'Topikalisierung'?", options: ["Das Voranstellen eines Satzglieds an die erste Stelle zur Betonung oder Kontrastierung", "Das Verb nach vorne bringen", "Das Nomen nach vorne bringen", "Das Adjektiv nach vorne bringen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Beispiel: 'Diese Buch habe ich bereits gelesen.' 'Diese Buch' wird durch Topikalisierung vorangestellt, um es zu _____.", answer: ["betonen", "hervorheben"] },
  { type: "mcq", question: "Welche Stellung erlaubt die meiste Flexibilität in der deutschen Satzgliedanordnung?", options: ["Mittelfeldstellung (zwischen Verb und Satzende)", "Vorfeld", "Nachfeld", "Präverbale Position"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Das Mittelfeld ist der Bereich _____ dem Verb und dem Satzende (oder der Satzklammer).", answer: ["zwischen", "zw."] },
  { type: "mcq", question: "Was ist die 'Rhema-Thema'-Struktur?", options: ["Thema (Bekanntes) am Anfang, Rhema (Neues) am Ende oder hervorgehoben", "Rhema am Anfang, Thema am Ende", "Rhema und Thema sind identisch", "Sie sind in keiner bestimmten Ordnung"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Nach der Rhema-Thema-Struktur steht das _____ (Bekannte/Gegebene) am Anfang.", answer: ["Thema"] },
  { type: "mcq", question: "Kann die Satzgliedstellung in Fragen anders sein als in Aussagesätzen?", options: ["Ja, das Verb tritt an die zweite Position und das Satzglied kann vorangestellt werden", "Nein, die Stellung ist identisch", "Nur bei Ja-Nein-Fragen", "Nur bei Ergänzungsfragen"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "In einer Frage: 'Was _____ der Mann _____ gelesen?' Das Verb tritt nach dem Fragewort oder an Position ___.", answer: ["2", "zweite"] },
  { type: "mcq", question: "Was bewirkt das Nachfeld in der deutschen Satzgliedstellung?", options: ["Es ermöglicht das Herausziehen von Elementen nach dem Verb zur Betonung oder Entlastung des Mittelfelds", "Es verkürzt den Satz", "Es macht den Satz ungrammatisch", "Es hat keine spezifische Funktion"], correct: 0, topic: "satzstrukturen_k8", subtopic: "satzgliedstellung_k8" },
  { type: "typing", question: "Beispiel für Nachfeld: 'Ich habe gelesen ein sehr interessantes Buch.' Das Nomen wird ins Nachfeld verlagert, um das Mittelfeld zu _____.", answer: ["entlasten", "vereinfachen"] },
];

export const K8_SATZSTRUKTUREN: any[] = [
  {
    id: "satzstrukturen_k8",
    name: { de: "Satzstrukturen", en: "Sentence structures", hu: "Mondat szerkezete", ro: "Structuri de propoziție" },
    icon: "🏗️",
    color: "#0EA5E9",
    subtopics: [
      { id: "satzperiode_k8", name: { de: "Satzperiode", en: "Sentence period", hu: "Mondatperiódus", ro: "Perioadă de propoziție" }, questions: satzperiode_k8 },
      { id: "konnektoren_k8", name: { de: "Konnektoren", en: "Connectors", hu: "Konnektorok", ro: "Conectori" }, questions: konnektoren_k8 },
      { id: "parenthese_k8", name: { de: "Parenthese", en: "Parenthesis", hu: "Parentezis", ro: "Parenteză" }, questions: parenthese_k8 },
      { id: "satzgliedstellung_k8", name: { de: "Satzgliedstellung", en: "Word order", hu: "Szórendiség", ro: "Ordinea cuvintelor" }, questions: satzgliedstellung_k8 },
    ],
  },
];
