import { DeutschTheme, DeutschQuestion } from "./types";

const modalitaet_k8: DeutschQuestion[] = [
  { type: "mcq", text: "Welcher Unterschied besteht zwischen 'müssen' und 'sollen'?", options: ["müssen = Notwendigkeit, sollen = Verpflichtung durch andere", "müssen = Obligation, sollen = Pflicht", "müssen = äußere Zwang, sollen = innere Verpflichtung", "müssen = streng, sollen = weniger streng"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Er _____ (sollen) pünktlich ankommen, aber er ist zu spät gekommen.", answer: ["sollte"] },
  { type: "mcq", text: "Welcher Unterschied besteht zwischen 'dürfte' und 'könnte'?", options: ["dürfte = hohe Wahrscheinlichkeit, könnte = Möglichkeit", "dürfte = Erlaubnis, könnte = Fähigkeit", "dürfte = Vermutung, könnte = Möglichkeit", "dürfte = Erlaubnis, könnte = Wahrscheinlichkeit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "mcq", text: "Was ist der Unterschied zwischen 'will' und 'möchte'?", options: ["will = starker Wunsch/Wille, möchte = höflicher Wunsch", "will = Verhandlung, möchte = Verlangen", "will = aktiv, möchte = passiv", "will = direkt, möchte = indirekt"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Das _____ (können) auch anders sein - es ist nur eine Möglichkeit.", answer: ["kann"] },
  { type: "mcq", text: "Wie unterscheiden sich 'mag' und 'will'?", options: ["mag = Zuneigung/Vorliebe, will = Absicht/Entschlossenheit", "mag = mögen, will = wollen", "mag = Neigung, will = Verlangen", "mag = schwach, will = stark"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Es _____ (sollen) laut Betriebsrat ein neues Pausenkonzept geben.", answer: ["soll"] },
  { type: "mcq", text: "Was ist der Unterschied zwischen 'muss' und 'braucht'?", options: ["muss = zwingend notwendig, braucht = nicht zwingend notwendig (oft mit Negation)", "muss = Obligation, braucht = Wahrscheinlichkeit", "muss = Verpflichtung, braucht = Notwendigkeit", "muss = äußerer Zwang, braucht = innere Notwendigkeit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "mcq", text: "Welcher Modalverb-Nuance wird durch 'würde' ausgedrückt?", options: ["Konjunktiv II: hypothetisch, irrealis, höflich", "Bedingung", "Vermutung", "Möglichkeit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Ich _____ (mögen) nicht, dass er ständig zu spät kommt.", answer: ["mag"] },
  { type: "mcq", text: "Was bedeutet 'sollte' im Konjunktiv II?", options: ["Hypothetischer Ratschlag oder Vermutung", "Subjektive Wahrscheinlichkeit", "Empfehlung", "Erfordernis"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Das Projekt _____ (können) bis Ende des Monats fertiggestellt sein.", answer: ["kann"] },
  { type: "mcq", text: "Welcher Unterschied besteht zwischen 'will' und 'wird'?", options: ["will = Wunsch/Intention, wird = Vorhersage/Futur", "will = aktive Absicht, wird = passive Erwartung", "will = Subjekt entscheidet, wird = Umstände entscheiden", "will = Wille, wird = Geschehen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Er _____ (wollen) nicht zugeben, dass er einen Fehler gemacht hat.", answer: ["will"] },
  { type: "mcq", text: "Welche Bedeutung hat 'mag' statt 'will' bei Aufforderungen?", options: ["Höflichkeit, Indirektheit, Vermeidung von Direktheit", "Freundlichkeit", "Unsicherheit", "Nachgiebigkeit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "mcq", text: "Was ist der Unterschied zwischen 'kann' und 'darf'?", options: ["kann = Fähigkeit/Möglichkeit, darf = Erlaubnis", "kann = Können, darf = Recht", "kann = Vermögen, darf = Gebot", "kann = Potenzial, darf = Berechtigung"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Du _____ (brauchen) dir keine Sorgen zu machen - alles wird gut.", answer: ["brauchst"] },
  { type: "mcq", text: "Welcher Unterschied besteht zwischen 'soll' und 'wird'?", options: ["soll = Verpflichtung, wird = automatisches/unvermeidliches Geschehen", "soll = Befehl, wird = Erwartung", "soll = Auftrag, wird = Verlauf", "soll = Anweisung, wird = Vorhersage"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "mcq", text: "Was ist der Unterschied zwischen 'mag' und 'kann'?", options: ["mag = Vorliebe/Zuneigung, kann = Fähigkeit", "mag = mögen, kann = können", "mag = emotional, kann = kognitiv", "mag = Wunsch, kann = Möglichkeit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Ich _____ (wollen) diesen Film nicht sehen - es ist zu langweilig.", answer: ["will"] },
  { type: "mcq", text: "Was bedeutet 'dürfte' bei einer Vermutung?", options: ["Hohe Wahrscheinlichkeit, Annahme", "Wahrscheinlichkeit", "Vermutung", "Spekulation"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Es _____ (mögen) sein, dass er Recht hat, aber ich bin mir unsicher.", answer: ["mag"] },
  { type: "mcq", text: "Welcher Unterschied besteht zwischen 'muss' und 'kann'?", options: ["muss = Notwendigkeit, kann = Möglichkeit", "muss = zwingend, kann = optional", "muss = Pflicht, kann = Vermögen", "muss = obligatorisch, kann = fakultativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "modalitaet_k8" },
  { type: "typing", text: "Du _____ (sollen) deine Hausaufgaben machen, nicht dein Handy spielen.", answer: ["sollst"] },
];

const funktionsverben_k8: DeutschQuestion[] = [
  { type: "mcq", text: "Was ist eine 'Funktionsverbgefüge'?", options: ["Verb + Nomen kombiniert, um eine Handlung auszudrücken (z.B. 'in Betracht ziehen')", "Ein Verb mit einer Funktion", "Ein Verb, das die Funktion angibt", "Ein Wort mit Funktionswert"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Beispiel: 'eine Entscheidung _____ ' ist ein Funktionsverbgefüge für 'entscheiden'.", answer: ["treffen"] },
  { type: "mcq", text: "Was ist das bedeutungsgleiche einfache Verb zu 'in Betracht ziehen'?", options: ["Berücksichtigen/Erwägen", "Denken", "Überlegen", "Planen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'Kritik _____ ' bedeutet 'kritisieren'.", answer: ["üben"] },
  { type: "mcq", text: "Was bedeutet das Funktionsverbgefüge 'zur Verfügung stellen'?", options: ["Zur Verfügung stellen/Zur Verfügung stellen", "Anbieten/Bereitstellen", "Zugeben", "Abgeben"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'einen Antrag _____ ' bedeutet 'antragen'.", answer: ["stellen"] },
  { type: "mcq", text: "Welches Funktionsverbgefüge bedeutet 'verstehen'?", options: ["Verständnis haben / zeigen", "Sinn erfassen", "Bedeutung erkennen", "Inhalt begreifen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'eine Vereinbarung _____ ' bedeutet 'vereinbaren'.", answer: ["treffen"] },
  { type: "mcq", text: "Was ist das bedeutungsgleiche Verb zu 'Hoffnung hegen'?", options: ["Hoffen", "Erwartung haben", "Träumen", "Wünschen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'Maßnahmen _____ ' bedeutet 'maßnahmen treffen/durchführen'.", answer: ["treffen", "ergreifen"] },
  { type: "mcq", text: "Welches Funktionsverbgefüge bedeutet 'gefallen'?", options: ["Gefallen finden", "Spaß haben", "Vergnügen empfinden", "Freude zeigen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'eine Nachricht _____ ' bedeutet 'mitteilen'.", answer: ["geben"] },
  { type: "mcq", text: "Was bedeutet das Funktionsverbgefüge 'in Kraft treten'?", options: ["In Kraft treten/Gültigkeit erlangen", "Beginnen zu wirken", "Wirksamkeit erreichen", "Gültigkeit haben"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'Schmerz _____ ' bedeutet 'wehtun/schmerzen'.", answer: ["bereiten"] },
  { type: "mcq", text: "Welches Funktionsverbgefüge bedeutet 'anfangen'?", options: ["Den Anfang machen / In Angriff nehmen", "Beginn setzen", "Beginn machen", "Start geben"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'Arbeit _____ ' bedeutet 'arbeiten'.", answer: ["leisten"] },
  { type: "mcq", text: "Was ist das bedeutungsgleiche Verb zu 'Aufmerksamkeit schenken'?", options: ["Beachten", "Bemerken", "Wahrnehmen", "Beobachten"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'Unterricht _____ ' bedeutet 'unterrichten'.", answer: ["erteilen"] },
  { type: "mcq", text: "Welches Funktionsverbgefüge bedeutet 'lachen'?", options: ["In Lachen ausbrechen", "Lacher loswerden", "Lust finden", "Freude zeigen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'eine Beschwerde _____ ' bedeutet 'beschweren'.", answer: ["einreichen"] },
  { type: "mcq", text: "Was bedeutet das Funktionsverbgefüge 'in Erinnerung rufen'?", options: ["Erinnern", "Zurückrufen in die Erinnerung", "Erwecken von Erinnerungen", "Memoria wecken"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'einen Plan _____ ' bedeutet 'planen'.", answer: ["fassen"] },
  { type: "mcq", text: "Welches Funktionsverbgefüge bedeutet 'erkennen'?", options: ["Anerkennung finden / Anerkennung zollen", "Bestätigung geben", "Akzeptanz zeigen", "Geltung geben"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'einen Fehler _____ ' bedeutet 'fehlervoll handeln'.", answer: ["machen"] },
  { type: "mcq", text: "Was ist das bedeutungsgleiche Verb zu 'Vertrauen haben'?", options: ["Vertrauen", "Glauben", "Hoffnung", "Zuversicht"], correct: 0, topic: "verben_vertieft_k8", subtopic: "funktionsverben_k8" },
  { type: "typing", text: "Das Funktionsverbgefüge 'einen Antrag _____ ' bedeutet 'beantragen'.", answer: ["ablehnen", "stellen"] },
];

const verbformen_komplex_k8: DeutschQuestion[] = [
  { type: "mcq", text: "Was ist das Futur II?", options: ["Ein zusammengesetztes Futur, das ausdrückt, dass etwas bis zu einem zukünftigen Zeitpunkt abgeschlossen sein wird", "Das vollendete Futur", "Die fertige Zukunft", "Das vollkommene Futur"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Futur II: 'Ich _____ den Film _____ haben' (schauen)", answer: ["werde", "schauen"] },
  { type: "mcq", text: "Was ist das Plusquamperfekt?", options: ["Die Vorzeitigkeitsform der Vergangenheit (zeitlich vor dem Präteritum/Perfekt)", "Die vollendete Vergangenheit", "Das übergangene Perfect", "Die zweite Vergangenheit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Plusquamperfekt: 'Er _____ schon gegangen, als ich ankam' (sein)", answer: ["war"] },
  { type: "mcq", text: "Wann wird das Plusquamperfekt verwendet?", options: ["Zur Darstellung von Vorzeitigkeit in der Vergangenheit (zeitlich vorher als ein anderes Ereignis)", "Für die Erzählung von Ereignissen", "Für abgeschlossene Handlungen", "Für wiederholte Ereignisse in der Vergangenheit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Konjunktiv II Präteritum: 'Ich _____ lieber zu Hause bleiben' (wollen)", answer: ["würde"] },
  { type: "mcq", text: "Was ist der würde-Konjunktiv?", options: ["Eine moderne Form des Konjunktiv II, gebildet mit 'würde + Infinitiv'", "Eine hypothetische Form", "Eine mögliche Handlung", "Ein irrealis form"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Konjunktiv II Plusquamperfekt: 'Wenn ich gewusst _____, _____ ich mitgekommen' (haben, sein)", answer: ["hätte", "wäre"] },
  { type: "mcq", text: "Was drückt das Konjunktiv II Plusquamperfekt aus?", options: ["Etwas, das in der Vergangenheit möglich hätte sein können, aber nicht geschah (Irrealität)", "Eine Bedingung in der Vergangenheit", "Etwas das hätte passieren können", "Das unerfüllte Potenzial der Vergangenheit"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Passiv Perfekt: 'Das Haus _____ _____ worden' (bauen)", answer: ["ist", "gebaut"] },
  { type: "mcq", text: "Wie wird das Passiv im Perfekt gebildet?", options: ["sein + Partizip Perfekt + worden (z.B. ist gebaut worden)", "haben + Partizip", "sein + worden + Partizip", "werden + sein + Partizip"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Passiv Präteritum: 'Das Projekt _____ vergangene Woche _____ ' (beenden)", answer: ["wurde", "beendet"] },
  { type: "mcq", text: "Was ist die Differenz zwischen 'ist gegangen' (Perfekt) und 'war gegangen' (Plusquamperfekt)?", options: ["ist gegangen = kürzere Vergangenheit, war gegangen = noch weitere Vergangenheit (temporal vorher)", "ist gegangen = näher, war gegangen = ferner", "ist gegangen = aktuell, war gegangen = historisch", "ist gegangen = neulich, war gegangen = früher"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Futur II Passiv: 'Der Bericht _____ _____ worden sein' (schreiben)", answer: ["wird", "geschrieben"] },
  { type: "mcq", text: "Wann wird das Futur II verwendet?", options: ["Zur Aussage über etwas, das bis zu einem bestimmten Zeitpunkt in der Zukunft abgeschlossen sein wird", "Für zukünftige Ereignisse", "Für Vorhersagen", "Für geplante Handlungen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Konjunktiv I Präsens: 'Er sagt, dass er _____ komme' (zur Schule)", answer: [] },
  { type: "mcq", text: "Was ist das Konzept des 'würde-Konjunktiv' versus 'Konjunktiv II'?", options: ["würde-Konjunktiv ist eine alternative Form des Konjunktiv II (moderner)", "Sie sind gleichbedeutend", "würde ist formaler", "Konjunktiv II ist älter"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Passiv Futur: 'Das Auto _____ _____ repariert werden' (in einer Woche)", answer: ["wird"] },
  { type: "mcq", text: "Wie wird das Passiv Futur I gebildet?", options: ["werden + Partizip + werden (z.B. wird repariert werden)", "werden + Partizip", "sein + Partizip + werden", "werden + sein + Partizip"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Konjunktiv II Präsens: 'Wenn ich Zeit _____, würde ich das machen' (haben)", answer: ["hätte"] },
  { type: "mcq", text: "Was unterscheidet Konjunktiv I von Konjunktiv II?", options: ["Konjunktiv I drückt fremde Aussagen aus; Konjunktiv II drückt Hypothetisches/Irreales aus", "Konjunktiv I ist für Zitate", "Konjunktiv II ist für Befehle", "Konjunktiv I ist formal, Konjunktiv II ist informell"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Plusquamperfekt Passive: 'Das Fenster _____ _____ worden' (zerbrechen)", answer: ["war", "zerbrochen"] },
  { type: "mcq", text: "Wann wird das Konjunktiv II verwendet?", options: ["Für hypothetische, irreale oder höfliche Aussagen (wenn-dann Bedingungen, Wünsche, Höflichkeit)", "Für Befehle", "Für Wünsche", "Für Bitten"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbformen_komplex_k8" },
  { type: "typing", text: "Konjunktiv I Präteritum: 'Er _____, er _____ nicht kommen' (sagen, können)", answer: ["sagte", "könne"] },
];

const verbrektion_k8: DeutschQuestion[] = [
  { type: "mcq", text: "Was ist 'Verbrektion' oder 'Valenz' bei Verben?", options: ["Die Fähigkeit eines Verbs, eine bestimmte Anzahl und Art von Ergänzungen zu regieren", "Die Bestimmung des Objekts", "Die Forderung nach bestimmten Fällen", "Die Bindung zu Präpositionen"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'warten' regiert die Präposition '_____ ' mit Akkusativ: warten auf etwas", answer: ["auf"] },
  { type: "mcq", text: "Wie lautet die Präposition und der Kasus für 'sich freuen'?", options: ["über + Akkusativ", "auf + Akkusativ", "zu + Dativ", "in + Dativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'bestehen' regiert die Präposition '_____ ' mit Dativ: bestehen darauf, auf + Akkusativ", answer: ["auf"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'helfen'?", options: ["bei + Dativ", "zu + Dativ", "an + Akkusativ", "über + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'verzeihen' regiert den _____ und einen _____ oder eine Präposition: jemandem etwas verzeihen", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich erinnern'?", options: ["an + Akkusativ", "auf + Akkusativ", "von + Dativ", "über + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'danken' regiert den _____ und optional eine Präposition: jemandem danken", answer: ["Dativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich ärgern'?", options: ["über + Akkusativ", "auf + Akkusativ", "von + Dativ", "mit + Dativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'erzählen' regiert den _____ und den _____: jemandem etwas erzählen", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich einigen'?", options: ["auf + Akkusativ", "über + Akkusativ", "mit + Dativ", "zu + Dativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'versichern' regiert den _____ und den _____: jemandem etwas versichern", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich kümmern'?", options: ["um + Akkusativ", "für + Akkusativ", "nach + Dativ", "von + Dativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'bitten' regiert den _____ und optional: jemandem etwas bitten OR jemandem um etwas bitten", answer: ["Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich beschweren'?", options: ["über + Akkusativ", "bei + Dativ", "für + Akkusativ", "gegen + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'berauben' regiert den _____ und den _____: jemandem etwas berauben (altertümlich)", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'eifern' (nicht 'nacheifern')?", options: ["nach + Dativ", "um + Akkusativ", "gegen + Akkusativ", "für + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'gewähren' regiert den _____ und den _____: jemandem etwas gewähren", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich rühmen'?", options: ["mit + Dativ / von + Dativ", "auf + Akkusativ", "über + Akkusativ", "für + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'zuschreiben' regiert den _____ und den _____: jemandem etwas zuschreiben", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich sehnen'?", options: ["nach + Dativ", "für + Akkusativ", "um + Akkusativ", "auf + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'zeigen' regiert den _____ und den _____: jemandem etwas zeigen", answer: ["Dativ", "Akkusativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'spotten'?", options: ["über + Akkusativ", "mit + Dativ", "auf + Akkusativ", "gegen + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
  { type: "typing", text: "Das Verb 'gefallen' regiert den _____ (nicht Akkusativ!): etwas gefällt mir", answer: ["Dativ"] },
  { type: "mcq", text: "Welche Präposition und welcher Kasus regiert das Verb 'sich einlassen'?", options: ["auf + Akkusativ", "mit + Dativ", "zu + Dativ", "in + Akkusativ"], correct: 0, topic: "verben_vertieft_k8", subtopic: "verbrektion_k8" },
];

export const K8_VERBEN: DeutschTheme[] = [
  {
    id: "verben_vertieft_k8",
    name: { de: "Verben vertieft", en: "Verbs advanced", hu: "Igék haladó", ro: "Verbe avansate" },
    icon: "🔄",
    color: "#3B82F6",
    subtopics: [
      { id: "modalitaet_k8", name: { de: "Modalität", en: "Modality", hu: "Modalitás", ro: "Modalitate" }, questions: modalitaet_k8 },
      { id: "funktionsverben_k8", name: { de: "Funktionsverben", en: "Functional verbs", hu: "Funkcionális igék", ro: "Verbe funcționale" }, questions: funktionsverben_k8 },
      { id: "verbformen_komplex_k8", name: { de: "Verbformen komplex", en: "Complex verb forms", hu: "Összetett igeformák", ro: "Forme verbale complexe" }, questions: verbformen_komplex_k8 },
      { id: "verbrektion_k8", name: { de: "Verbrektion", en: "Verb government", hu: "Igei rekcio", ro: "Regie verbală" }, questions: verbrektion_k8 },
    ],
  },
];
