import { MultilingualVisualLabPool } from "@/lib/visualLab/multilingualTypes";

export const GEOGRAPHY_POOLS: MultilingualVisualLabPool = {
  subject: "Geography",

  // ── MeteorCatch ──────────────────────────────────────────────────────
  meteorCatch: [
    {
      id: "geo-mc-1",
      title: { de: "Kontinente", en: "Continents", hu: "Kontinensek", ro: "Continente" },
      prompt: { de: "Fange nur Kontinente ein.", en: "Catch only continents.", hu: "Csak kontinenseket fogj be.", ro: "Prinde doar continente." },
      goal: 6,
      speed: 5,
      theme: { sky: "#0f172a", glow: "#34d399", accent: "#10b981" },
      correctItems: [
        { id: "europa", label: { de: "Europa", en: "Europe", hu: "Európa", ro: "Europa" }, emoji: "🌍" },
        { id: "asien", label: { de: "Asien", en: "Asia", hu: "Ázsia", ro: "Asia" }, emoji: "🌏" },
        { id: "afrika", label: { de: "Afrika", en: "Africa", hu: "Afrika", ro: "Africa" }, emoji: "🌍" },
        { id: "nordamerika", label: { de: "Nordamerika", en: "North America", hu: "Észak-Amerika", ro: "America de Nord" }, emoji: "🌎" },
        { id: "suedamerika", label: { de: "Südamerika", en: "South America", hu: "Dél-Amerika", ro: "America de Sud" }, emoji: "🌎" },
        { id: "australien", label: { de: "Australien", en: "Australia", hu: "Ausztrália", ro: "Australia" }, emoji: "🦘" },
      ],
      wrongItems: [
        { id: "pazifik", label: { de: "Pazifik", en: "Pacific", hu: "Csendes-óceán", ro: "Pacific" }, emoji: "🌊" },
        { id: "atlantik", label: { de: "Atlantik", en: "Atlantic", hu: "Atlanti-óceán", ro: "Atlantic" }, emoji: "🌊" },
      ],
    },
    {
      id: "geo-mc-2",
      title: { de: "Länder fangen", en: "Catch Countries", hu: "Országok", ro: "Prinde Țări" },
      prompt: { de: "Fange nur echte Länder.", en: "Catch only countries.", hu: "Csak országokat fogj.", ro: "Prinde doar țări." },
      goal: 7,
      speed: 5,
      theme: { sky: "#0f172a", glow: "#a78bfa", accent: "#7c3aed" },
      correctItems: [
        { id: "deutschland", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "frankreich", label: { de: "Frankreich", en: "France", hu: "Franciaország", ro: "Franța" }, emoji: "🇫🇷" },
        { id: "italien", label: { de: "Italien", en: "Italy", hu: "Olaszország", ro: "Italia" }, emoji: "🇮🇹" },
        { id: "spanien", label: { de: "Spanien", en: "Spain", hu: "Spanyolország", ro: "Spania" }, emoji: "🇪🇸" },
        { id: "japan", label: { de: "Japan", en: "Japan", hu: "Japán", ro: "Japonia" }, emoji: "🇯🇵" },
      ],
      wrongItems: [
        { id: "berlin", label: { de: "Berlin", en: "Berlin", hu: "Berlin", ro: "Berlin" }, emoji: "🏛️" },
        { id: "paris", label: { de: "Paris", en: "Paris", hu: "Párizs", ro: "Paris" }, emoji: "🗼" },
      ],
    },
    {
      id: "geo-mc-3",
      title: { de: "Hauptstädte", en: "Capitals", hu: "Fővárosok", ro: "Capitale" },
      prompt: { de: "Fange nur Hauptstädte.", en: "Catch only capitals.", hu: "Csak fővárosokat fogj.", ro: "Prinde doar capitale." },
      goal: 6,
      speed: 5,
      theme: { sky: "#082f49", glow: "#38bdf8", accent: "#0ea5e9" },
      correctItems: [
        { id: "london", label: { de: "London", en: "London", hu: "London", ro: "Londra" }, emoji: "🕰️" },
        { id: "tokio", label: { de: "Tokio", en: "Tokyo", hu: "Tokió", ro: "Tokyo" }, emoji: "🗼" },
        { id: "washington", label: { de: "Washington D.C.", en: "Washington", hu: "Washington", ro: "Washington" }, emoji: "🏛️" },
        { id: "wien", label: { de: "Wien", en: "Vienna", hu: "Bécs", ro: "Viena" }, emoji: "🎻" },
      ],
      wrongItems: [
        { id: "usa", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" }, emoji: "🇺🇸" },
        { id: "china", label: { de: "China", en: "China", hu: "Kína", ro: "China" }, emoji: "🇨🇳" },
      ],
    },
    {
      id: "geo-mc-4",
      title: { de: "Flüsse", en: "Rivers", hu: "Folyók", ro: "Râuri" },
      prompt: { de: "Fange nur Flüsse.", en: "Catch only rivers.", hu: "Csak folyókat fogj.", ro: "Prinde doar râuri." },
      goal: 6,
      speed: 5,
      theme: { sky: "#052e16", glow: "#4ade80", accent: "#16a34a" },
      correctItems: [
        { id: "rhein", label: { de: "Rhein", en: "Rhine", hu: "Rajna", ro: "Rin" }, emoji: "🌊" },
        { id: "donau", label: { de: "Donau", en: "Danube", hu: "Duna", ro: "Dunăre" }, emoji: "💧" },
        { id: "amazonas", label: { de: "Amazonas", en: "Amazon", hu: "Amazonas", ro: "Amazon" }, emoji: "🌿" },
        { id: "nil", label: { de: "Nil", en: "Nile", hu: "Nílus", ro: "Nil" }, emoji: "🐊" },
      ],
      wrongItems: [
        { id: "alpen", label: { de: "Alpen", en: "Alps", hu: "Alpok", ro: "Alpi" }, emoji: "🏔️" },
        { id: "sahara", label: { de: "Sahara", en: "Sahara", hu: "Szahara", ro: "Sahara" }, emoji: "🏜️" },
      ],
    },
    {
      id: "geo-mc-5",
      title: { de: "Berge & Gebirge", en: "Mountains", hu: "Hegyek", ro: "Munți" },
      prompt: { de: "Fange nur Berge.", en: "Catch only mountains.", hu: "Csak hegyeket fogj.", ro: "Prinde doar munți." },
      goal: 5,
      speed: 5,
      theme: { sky: "#1c1917", glow: "#a3e635", accent: "#65a30d" },
      correctItems: [
        { id: "alpen", label: { de: "Alpen", en: "Alps", hu: "Alpok", ro: "Alpi" }, emoji: "🏔️" },
        { id: "himalaya", label: { de: "Himalaya", en: "Himalayas", hu: "Himalája", ro: "Himalaya" }, emoji: "🗻" },
        { id: "montblanc", label: { de: "Mont Blanc", en: "Mont Blanc", hu: "Mont Blanc", ro: "Mont Blanc" }, emoji: "🗻" },
        { id: "everest", label: { de: "Mount Everest", en: "Everest", hu: "Mount Everest", ro: "Everest" }, emoji: "⛰️" },
      ],
      wrongItems: [
        { id: "mittelmeer", label: { de: "Mittelmeer", en: "Med. Sea", hu: "Földközi-tenger", ro: "Marea Mediterană" }, emoji: "⛵" },
      ],
    },
    {
      id: "geo-mc-6",
      title: { de: "Meere & Ozeane", en: "Seas & Oceans", hu: "Tengerek", ro: "Mări" },
      prompt: { de: "Fange nur Meere/Ozeane.", en: "Catch seas/oceans.", hu: "Csak tengereket fogj.", ro: "Prinde mări/oceane." },
      goal: 6,
      speed: 4,
      theme: { sky: "#02113b", glow: "#38bdf8", accent: "#0ea5e9" },
      correctItems: [
        { id: "pazifik", label: { de: "Pazifik", en: "Pacific", hu: "Csendes-óceán", ro: "Pacific" }, emoji: "🌊" },
        { id: "atlantik", label: { de: "Atlantik", en: "Atlantic", hu: "Atlanti-óceán", ro: "Atlantic" }, emoji: "🌊" },
        { id: "mittelmeer", label: { de: "Mittelmeer", en: "Mediterranean", hu: "Földközi-t.", ro: "Mediterană" }, emoji: "⛵" },
        { id: "ostsee", label: { de: "Ostsee", en: "Baltic Sea", hu: "Balti-tenger", ro: "Marea Baltică" }, emoji: "💧" },
      ],
      wrongItems: [
        { id: "rhein", label: { de: "Rhein", en: "Rhine", hu: "Rajna", ro: "Rin" }, emoji: "🌊" },
        { id: "donau", label: { de: "Donau", en: "Danube", hu: "Duna", ro: "Dunăre" }, emoji: "💧" },
      ],
    },
    {
      id: "geo-mc-7",
      title: { de: "Klimazonen", en: "Climate Zones", hu: "Éghajlat", ro: "Zone Climatice" },
      prompt: { de: "Fange Klimazonen.", en: "Catch climate zones.", hu: "Csak éghajlatot fogj.", ro: "Prinde zone climatice." },
      goal: 5,
      speed: 5,
      theme: { sky: "#1a0a2e", glow: "#fb923c", accent: "#f97316" },
      correctItems: [
        { id: "tropen", label: { de: "Tropen", en: "Tropics", hu: "Trópusi", ro: "Tropical" }, emoji: "🌴" },
        { id: "wueste", label: { de: "Wüste", en: "Desert", hu: "Sivatagi", ro: "Deșert" }, emoji: "🏜️" },
        { id: "polar", label: { de: "Polarklima", en: "Polar", hu: "Sarki", ro: "Polar" }, emoji: "🧊" },
        { id: "gemaessigt", label: { de: "Gemäßigt", en: "Temperate", hu: "Mérsékelt", ro: "Temperat" }, emoji: "🌳" },
      ],
      wrongItems: [
        { id: "alpen", label: { de: "Alpen", en: "Alps", hu: "Alpok", ro: "Alpi" }, emoji: "🏔️" },
        { id: "nil", label: { de: "Nil", en: "Nile", hu: "Nílus", ro: "Nil" }, emoji: "🐊" },
      ],
    },
    {
      id: "geo-mc-8",
      title: { de: "Flaggen Europas", en: "Flags", hu: "Zászlók", ro: "Steaguri" },
      prompt: { de: "Fange nur Flaggen.", en: "Catch only flags.", hu: "Csak zászlókat fogj.", ro: "Prinde doar steaguri." },
      goal: 6,
      speed: 5,
      theme: { sky: "#0f172a", glow: "#fbbf24", accent: "#f59e0b" },
      correctItems: [
        { id: "flag-de", label: { de: "Deutschland", en: "Germany", hu: "Német", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "flag-fr", label: { de: "Frankreich", en: "France", hu: "Francia", ro: "Franța" }, emoji: "🇫🇷" },
        { id: "flag-it", label: { de: "Italien", en: "Italy", hu: "Olasz", ro: "Italia" }, emoji: "🇮🇹" },
        { id: "flag-es", label: { de: "Spanien", en: "Spain", hu: "Spanyol", ro: "Spania" }, emoji: "🇪🇸" },
      ],
      wrongItems: [
        { id: "usa", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" }, emoji: "🇺🇸" },
        { id: "china", label: { de: "China", en: "China", hu: "Kína", ro: "China" }, emoji: "🇨🇳" },
      ],
    },
    {
      id: "geo-mc-9",
      title: { de: "Wirtschaftsmächte", en: "Economies", hu: "Gazdaságok", ro: "Economii" },
      prompt: { de: "Fange Wirtschaftsmächte.", en: "Catch top economies.", hu: "Fogj nagy gazdaságokat.", ro: "Prinde economii mari." },
      goal: 5,
      speed: 5,
      theme: { sky: "#052e16", glow: "#4ade80", accent: "#16a34a" },
      correctItems: [
        { id: "wm-usa", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" }, emoji: "🇺🇸" },
        { id: "wm-cn", label: { de: "China", en: "China", hu: "Kína", ro: "China" }, emoji: "🇨🇳" },
        { id: "wm-de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "wm-jp", label: { de: "Japan", en: "Japan", hu: "Japán", ro: "Japonia" }, emoji: "🇯🇵" },
      ],
      wrongItems: [
        { id: "wm-mc", label: { de: "Monaco", en: "Monaco", hu: "Monaco", ro: "Monaco" }, emoji: "🇲🇨" },
      ],
    },
    {
      id: "geo-mc-10",
      title: { de: "Handelsrouten", en: "Trade Routes", hu: "Keresk. útvonalak", ro: "Rute Comerț" },
      prompt: { de: "Fange Handelsrouten.", en: "Catch trade routes.", hu: "Csak kereskedelmi utakat.", ro: "Prinde rute de comerț." },
      goal: 4,
      speed: 5,
      theme: { sky: "#1c1917", glow: "#fbbf24", accent: "#f59e0b" },
      correctItems: [
        { id: "seidenstrasse", label: { de: "Seidenstraße", en: "Silk Road", hu: "Selyemút", ro: "Drumul Mătăsii" }, emoji: "🐪" },
        { id: "suezkanal", label: { de: "Suezkanal", en: "Suez Canal", hu: "Szuezi-csatorna", ro: "Canalul Suez" }, emoji: "🚢" },
        { id: "panamakanal", label: { de: "Panamakanal", en: "Panama Canal", hu: "Panama-csatorna", ro: "Canalul Panama" }, emoji: "⛵" },
      ],
      wrongItems: [
        { id: "autobahn", label: { de: "Autobahn", en: "Highway", hu: "Autópálya", ro: "Autostradă" }, emoji: "🚗" },
      ],
    }
  ],

  // ── OrbitSort ────────────────────────────────────────────────────────
  orbitSort: [
    {
      id: "geo-os-1",
      title: { de: "Kontinente", en: "Continents", hu: "Kontinensek", ro: "Continente" },
      instruction: { de: "Sortiere nach Kontinent.", en: "Sort by continent.", hu: "Rendezd kontinens szerint.", ro: "Sortează după continent." },
      theme: { bg: "#0f172a", orbit: "#10b981", accent: "#34d399" },
      buckets: [
        { id: "europa", label: { de: "Europa", en: "Europe", hu: "Európa", ro: "Europa" }, color: "#3b82f6" },
        { id: "asien", label: { de: "Asien", en: "Asia", hu: "Ázsia", ro: "Asia" }, color: "#ef4444" },
      ],
      items: [
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪", bucketId: "europa" },
        { id: "fr", label: { de: "Frankreich", en: "France", hu: "Franciaország", ro: "Franța" }, emoji: "🇫🇷", bucketId: "europa" },
        { id: "jp", label: { de: "Japan", en: "Japan", hu: "Japán", ro: "Japonia" }, emoji: "🇯🇵", bucketId: "asien" },
        { id: "cn", label: { de: "China", en: "China", hu: "Kína", ro: "China" }, emoji: "🇨🇳", bucketId: "asien" },
      ],
    },
    {
      id: "geo-os-2",
      title: { de: "Klimazonen", en: "Climate Zones", hu: "Éghajlat", ro: "Zone Climatice" },
      instruction: { de: "Welche Klimazone?", en: "Which climate zone?", hu: "Melyik éghajlat?", ro: "Care zonă climatică?" },
      theme: { bg: "#1c1917", orbit: "#fb923c", accent: "#f97316" },
      buckets: [
        { id: "tropisch", label: { de: "Tropisch", en: "Tropical", hu: "Trópusi", ro: "Tropical" }, color: "#22c55e" },
        { id: "polar", label: { de: "Polar", en: "Polar", hu: "Sarki", ro: "Polar" }, color: "#bfdbfe" },
      ],
      items: [
        { id: "brasilien", label: { de: "Brasilien", en: "Brazil", hu: "Brazília", ro: "Brazilia" }, emoji: "🌿", bucketId: "tropisch" },
        { id: "indonesien", label: { de: "Indonesien", en: "Indonesia", hu: "Indonézia", ro: "Indonezia" }, emoji: "🌴", bucketId: "tropisch" },
        { id: "groenland", label: { de: "Grönland", en: "Greenland", hu: "Grönland", ro: "Groenlanda" }, emoji: "🧊", bucketId: "polar" },
        { id: "antarktis", label: { de: "Antarktis", en: "Antarctica", hu: "Antarktisz", ro: "Antarctica" }, emoji: "🐧", bucketId: "polar" },
      ],
    },
    {
      id: "geo-os-3",
      title: { de: "Wirtschaft", en: "Economy Sectors", hu: "Gazdaság", ro: "Sectoare Eco." },
      instruction: { de: "Sortiere nach Sektor.", en: "Sort by sector.", hu: "Rendezd szektor szerint.", ro: "Sortează după sector." },
      theme: { bg: "#0f172a", orbit: "#f59e0b", accent: "#d97706" },
      buckets: [
        { id: "agrar", label: { de: "Landwirtschaft", en: "Agriculture", hu: "Mezőgazdaság", ro: "Agricultură" }, color: "#22c55e" },
        { id: "industrie", label: { de: "Industrie", en: "Industry", hu: "Ipar", ro: "Industrie" }, color: "#3b82f6" },
      ],
      items: [
        { id: "getreide", label: { de: "Getreideanbau", en: "Farming", hu: "Gabona", ro: "Cereale" }, emoji: "🌾", bucketId: "agrar" },
        { id: "vieh", label: { de: "Viehzucht", en: "Livestock", hu: "Állattartás", ro: "Zootehnie" }, emoji: "🐄", bucketId: "agrar" },
        { id: "auto", label: { de: "Autoproduktion", en: "Car Manuf.", hu: "Autógyártás", ro: "Auto" }, emoji: "🏭", bucketId: "industrie" },
        { id: "stahl", label: { de: "Stahlwerk", en: "Steel Mill", hu: "Acélgyártás", ro: "Oțel" }, emoji: "⚙️", bucketId: "industrie" },
      ],
    },
    {
      id: "geo-os-4",
      title: { de: "Sprachfamilien", en: "Languages", hu: "Nyelvcsaládok", ro: "Limbi" },
      instruction: { de: "Sortiere die Sprachen.", en: "Sort the languages.", hu: "Rendezd a nyelveket.", ro: "Sortează limbile." },
      theme: { bg: "#1a0a2e", orbit: "#c084fc", accent: "#9333ea" },
      buckets: [
        { id: "germanisch", label: { de: "Germanisch", en: "Germanic", hu: "Germán", ro: "Germanic" }, color: "#3b82f6" },
        { id: "romanisch", label: { de: "Romanisch", en: "Romance", hu: "Újlatin", ro: "Romanic" }, color: "#ef4444" },
      ],
      items: [
        { id: "deutsch", label: { de: "Deutsch", en: "German", hu: "Német", ro: "Germană" }, emoji: "🇩🇪", bucketId: "germanisch" },
        { id: "englisch", label: { de: "Englisch", en: "English", hu: "Angol", ro: "Engleză" }, emoji: "🇬🇧", bucketId: "germanisch" },
        { id: "spanisch", label: { de: "Spanisch", en: "Spanish", hu: "Spanyol", ro: "Spaniolă" }, emoji: "🇪🇸", bucketId: "romanisch" },
        { id: "franzoesisch", label: { de: "Französisch", en: "French", hu: "Francia", ro: "Franceză" }, emoji: "🇫🇷", bucketId: "romanisch" },
      ],
    },
    {
      id: "geo-os-5",
      title: { de: "Zeitzonen", en: "Time Zones", hu: "Időzónák", ro: "Fus Orar" },
      instruction: { de: "Sortiere nach Zeitzone.", en: "Sort by time zone.", hu: "Rendezd időzóna szerint.", ro: "Sortează fusul." },
      theme: { bg: "#02113b", orbit: "#fbbf24", accent: "#f59e0b" },
      buckets: [
        { id: "mez", label: { de: "MEZ (Europa)", en: "CET (Europe)", hu: "CET (Európa)", ro: "CET (Europa)" }, color: "#3b82f6" },
        { id: "est", label: { de: "EST (Amerika)", en: "EST (America)", hu: "EST (Amerika)", ro: "EST (America)" }, color: "#f59e0b" },
      ],
      items: [
        { id: "berlin", label: { de: "Berlin", en: "Berlin", hu: "Berlin", ro: "Berlin" }, emoji: "🏛️", bucketId: "mez" },
        { id: "rom", label: { de: "Rom", en: "Rome", hu: "Róma", ro: "Roma" }, emoji: "🏟️", bucketId: "mez" },
        { id: "newyork", label: { de: "New York", en: "New York", hu: "New York", ro: "New York" }, emoji: "🗽", bucketId: "est" },
        { id: "toronto", label: { de: "Toronto", en: "Toronto", hu: "Toronto", ro: "Toronto" }, emoji: "🍁", bucketId: "est" },
      ],
    },
    {
      id: "geo-os-6",
      title: { de: "Religionen", en: "Religions", hu: "Vallások", ro: "Religii" },
      instruction: { de: "Sortiere Religionen.", en: "Sort religions.", hu: "Rendezd a vallásokat.", ro: "Sortează religiile." },
      theme: { bg: "#1c1917", orbit: "#22d3ee", accent: "#06b6d4" },
      buckets: [
        { id: "asien", label: { de: "Ursprung Asien", en: "Origin Asia", hu: "Ázsiai eredet", ro: "Origine Asia" }, color: "#f59e0b" },
        { id: "naherosten", label: { de: "Naher Osten", en: "Middle East", hu: "Közel-Kelet", ro: "Orientul Mij." }, color: "#60a5fa" },
      ],
      items: [
        { id: "buddhismus", label: { de: "Buddhismus", en: "Buddhism", hu: "Buddhizmus", ro: "Budism" }, emoji: "☸️", bucketId: "asien" },
        { id: "hinduismus", label: { de: "Hinduismus", en: "Hinduism", hu: "Hinduizmus", ro: "Hinduism" }, emoji: "🕉️", bucketId: "asien" },
        { id: "islam", label: { de: "Islam", en: "Islam", hu: "Iszlám", ro: "Islam" }, emoji: "☪️", bucketId: "naherosten" },
        { id: "christentum", label: { de: "Christentum", en: "Christianity", hu: "Kereszténység", ro: "Creștinism" }, emoji: "✝️", bucketId: "naherosten" },
      ],
    },
    {
      id: "geo-os-7",
      title: { de: "Insel oder Festland?", en: "Island vs Mainland", hu: "Sziget / Szárazf.", ro: "Insulă / Continent" },
      instruction: { de: "Insel oder Festland?", en: "Island or Mainland?", hu: "Sziget vagy szárazföld?", ro: "Insulă sau Continent?" },
      theme: { bg: "#082f49", orbit: "#22d3ee", accent: "#06b6d4" },
      buckets: [
        { id: "insel", label: { de: "Insel", en: "Island", hu: "Sziget", ro: "Insulă" }, color: "#60a5fa" },
        { id: "festland", label: { de: "Festland", en: "Mainland", hu: "Szárazföld", ro: "Continent" }, color: "#f59e0b" },
      ],
      items: [
        { id: "island", label: { de: "Island", en: "Iceland", hu: "Izland", ro: "Islanda" }, emoji: "🇮🇸", bucketId: "insel" },
        { id: "malta", label: { de: "Malta", en: "Malta", hu: "Málta", ro: "Malta" }, emoji: "🇲🇹", bucketId: "insel" },
        { id: "polen", label: { de: "Polen", en: "Poland", hu: "Lengyelország", ro: "Polonia" }, emoji: "🇵🇱", bucketId: "festland" },
        { id: "oesterreich", label: { de: "Österreich", en: "Austria", hu: "Ausztria", ro: "Austria" }, emoji: "🇦🇹", bucketId: "festland" },
      ],
    },
    {
      id: "geo-os-8",
      title: { de: "EU-Mitglied?", en: "EU Member?", hu: "EU-tag?", ro: "Membru UE?" },
      instruction: { de: "Ist das Land in der EU?", en: "Is it in the EU?", hu: "EU-tag az ország?", ro: "E în UE?" },
      theme: { bg: "#02113b", orbit: "#fbbf24", accent: "#f59e0b" },
      buckets: [
        { id: "eu", label: { de: "EU-Mitglied", en: "EU Member", hu: "EU-tag", ro: "Membru UE" }, color: "#3b82f6" },
        { id: "nein", label: { de: "Kein Mitglied", en: "Not Member", hu: "Nem tag", ro: "Nu e membru" }, color: "#6b7280" },
      ],
      items: [
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Német", ro: "Germania" }, emoji: "🇩🇪", bucketId: "eu" },
        { id: "ro", label: { de: "Rumänien", en: "Romania", hu: "Románia", ro: "România" }, emoji: "🇷🇴", bucketId: "eu" },
        { id: "ch", label: { de: "Schweiz", en: "Switzerland", hu: "Svájc", ro: "Elveția" }, emoji: "🇨🇭", bucketId: "nein" },
        { id: "no", label: { de: "Norwegen", en: "Norway", hu: "Norvégia", ro: "Norvegia" }, emoji: "🇳🇴", bucketId: "nein" },
      ],
    },
    {
      id: "geo-os-9",
      title: { de: "Flüsse zuordnen", en: "Rivers", hu: "Folyók", ro: "Râuri" },
      instruction: { de: "Zu welchem Meer?", en: "To which sea?", hu: "Melyik tengerbe?", ro: "În ce mare?" },
      theme: { bg: "#082f49", orbit: "#22d3ee", accent: "#06b6d4" },
      buckets: [
        { id: "nordsee", label: { de: "Nordsee", en: "North Sea", hu: "Északi-tenger", ro: "Marea Nordului" }, color: "#60a5fa" },
        { id: "schwarz", label: { de: "Schwarzes Meer", en: "Black Sea", hu: "Fekete-tenger", ro: "Marea Neagră" }, color: "#1d4ed8" },
      ],
      items: [
        { id: "rhein", label: { de: "Rhein", en: "Rhine", hu: "Rajna", ro: "Rin" }, emoji: "🌊", bucketId: "nordsee" },
        { id: "elbe", label: { de: "Elbe", en: "Elbe", hu: "Elba", ro: "Elba" }, emoji: "💧", bucketId: "nordsee" },
        { id: "donau", label: { de: "Donau", en: "Danube", hu: "Duna", ro: "Dunăre" }, emoji: "🌊", bucketId: "schwarz" },
        { id: "dnjepr", label: { de: "Dnjepr", en: "Dnieper", hu: "Dnyeper", ro: "Nipru" }, emoji: "💦", bucketId: "schwarz" },
      ],
    },
    {
      id: "geo-os-10",
      title: { de: "Ozeane", en: "Oceans", hu: "Óceánok", ro: "Oceane" },
      instruction: { de: "An welchem Ozean?", en: "On which ocean?", hu: "Melyik óceánnál?", ro: "La ce ocean?" },
      theme: { bg: "#1c1917", orbit: "#34d399", accent: "#10b981" },
      buckets: [
        { id: "atlantik", label: { de: "Atlantik", en: "Atlantic", hu: "Atlanti", ro: "Atlantic" }, color: "#60a5fa" },
        { id: "pazifik", label: { de: "Pazifik", en: "Pacific", hu: "Csendes", ro: "Pacific" }, color: "#34d399" },
      ],
      items: [
        { id: "portugal", label: { de: "Portugal", en: "Portugal", hu: "Portugália", ro: "Portugalia" }, emoji: "🇵🇹", bucketId: "atlantik" },
        { id: "brasilien", label: { de: "Brasilien", en: "Brazil", hu: "Brazília", ro: "Brazilia" }, emoji: "🇧🇷", bucketId: "atlantik" },
        { id: "japan", label: { de: "Japan", en: "Japan", hu: "Japán", ro: "Japonia" }, emoji: "🇯🇵", bucketId: "pazifik" },
        { id: "chile", label: { de: "Chile", en: "Chile", hu: "Chile", ro: "Chile" }, emoji: "🇨🇱", bucketId: "pazifik" },
      ],
    },
  ],

  // ── SignalRunner ─────────────────────────────────────────────────────
  signalRunner: [
    {
      id: "geo-sr-1",
      title: { de: "Wahrzeichen", en: "Landmarks", hu: "Nevezetességek", ro: "Repere" },
      instruction: { de: "Wähle die Stadt.", en: "Choose the city.", hu: "Válaszd a várost.", ro: "Alege orașul." },
      scenes: [
        {
          id: "sr-1-s1",
          title: { de: "Eiffelturm", en: "Eiffel Tower", hu: "Eiffel-torony", ro: "Turnul Eiffel" },
          prompt: { de: "Wo steht der Eiffelturm?", en: "Where is the Eiffel Tower?", hu: "Hol van az Eiffel-torony?", ro: "Unde e Turnul Eiffel?" },
          sceneType: "nature",
          visual: { icon: "🗼", bg: "#1e3a5f", accent: "#fbbf24" },
          choices: [
            { id: "a", label: { de: "London", en: "London", hu: "London", ro: "Londra" } },
            { id: "b", label: { de: "Paris", en: "Paris", hu: "Párizs", ro: "Paris" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-2",
      title: { de: "Hauptstädte", en: "Capitals", hu: "Fővárosok", ro: "Capitale" },
      instruction: { de: "Welche Hauptstadt?", en: "Which capital?", hu: "Melyik főváros?", ro: "Care capitală?" },
      scenes: [
        {
          id: "sr-2-s1",
          title: { de: "Österreich", en: "Austria", hu: "Ausztria", ro: "Austria" },
          prompt: { de: "Was ist die Hauptstadt von Österreich?", en: "Capital of Austria?", hu: "Ausztria fővárosa?", ro: "Capitala Austriei?" },
          sceneType: "community",
          visual: { icon: "🇦🇹", bg: "#1a0a0a", accent: "#ef4444" },
          choices: [
            { id: "a", label: { de: "Graz", en: "Graz", hu: "Graz", ro: "Graz" } },
            { id: "b", label: { de: "Wien", en: "Vienna", hu: "Bécs", ro: "Viena" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-3",
      title: { de: "Kontinente", en: "Continents", hu: "Kontinensek", ro: "Continente" },
      instruction: { de: "Welcher Kontinent?", en: "Which continent?", hu: "Melyik kontinens?", ro: "Care continent?" },
      scenes: [
        {
          id: "sr-3-s1",
          title: { de: "Größter", en: "Largest", hu: "Legnagyobb", ro: "Cel mai mare" },
          prompt: { de: "Welcher ist der größte Kontinent?", en: "Largest continent?", hu: "A legnagyobb kontinens?", ro: "Cel mai mare continent?" },
          sceneType: "nature",
          visual: { icon: "🌏", bg: "#0a1a0a", accent: "#22c55e" },
          choices: [
            { id: "a", label: { de: "Afrika", en: "Africa", hu: "Afrika", ro: "Africa" } },
            { id: "b", label: { de: "Asien", en: "Asia", hu: "Ázsia", ro: "Asia" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-4",
      title: { de: "Längster Fluss", en: "Longest River", hu: "Leghosszabb", ro: "Cel mai lung" },
      instruction: { de: "Welcher Fluss?", en: "Which river?", hu: "Melyik folyó?", ro: "Care râu?" },
      scenes: [
        {
          id: "sr-4-s1",
          title: { de: "Welt", en: "World", hu: "Világ", ro: "Lume" },
          prompt: { de: "Welcher Fluss ist der längste der Welt?", en: "Longest river in the world?", hu: "A világ leghosszabb folyója?", ro: "Cel mai lung râu din lume?" },
          sceneType: "nature",
          visual: { icon: "🐊", bg: "#0a1a00", accent: "#4ade80" },
          choices: [
            { id: "a", label: { de: "Amazonas", en: "Amazon", hu: "Amazonas", ro: "Amazon" } },
            { id: "b", label: { de: "Nil", en: "Nile", hu: "Nílus", ro: "Nil" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-5",
      title: { de: "Höchster Berg", en: "Highest Mountain", hu: "Legmagasabb hegy", ro: "Cel mai înalt" },
      instruction: { de: "Welcher Berg?", en: "Which mountain?", hu: "Melyik hegy?", ro: "Care munte?" },
      scenes: [
        {
          id: "sr-5-s1",
          title: { de: "Welt", en: "World", hu: "Világ", ro: "Lume" },
          prompt: { de: "Wie heißt der höchste Berg?", en: "Highest mountain?", hu: "A legmagasabb hegy?", ro: "Cel mai înalt munte?" },
          sceneType: "nature",
          visual: { icon: "🗻", bg: "#0a0010", accent: "#c4b5fd" },
          choices: [
            { id: "a", label: { de: "Mont Blanc", en: "Mont Blanc", hu: "Mont Blanc", ro: "Mont Blanc" } },
            { id: "b", label: { de: "Mount Everest", en: "Everest", hu: "Mount Everest", ro: "Everest" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-6",
      title: { de: "Klimazonen", en: "Climate Zones", hu: "Éghajlat", ro: "Zone Climatice" },
      instruction: { de: "Welche Klimazone?", en: "Which climate zone?", hu: "Melyik éghajlat?", ro: "Care zonă?" },
      scenes: [
        {
          id: "sr-6-s1",
          title: { de: "Wüste", en: "Desert", hu: "Sivatag", ro: "Deșert" },
          prompt: { de: "Heiß und kaum Regen – welche Klimazone?", en: "Hot and no rain – which zone?", hu: "Forró és száraz – mi ez?", ro: "Fierbinte și secetos – care zonă?" },
          sceneType: "nature",
          visual: { icon: "🏜️", bg: "#1a1000", accent: "#fbbf24" },
          choices: [
            { id: "a", label: { de: "Polarklima", en: "Polar", hu: "Sarki", ro: "Polar" } },
            { id: "b", label: { de: "Wüstenklima", en: "Desert", hu: "Sivatagi", ro: "Deșert" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-7",
      title: { de: "Ozeane", en: "Oceans", hu: "Óceánok", ro: "Oceane" },
      instruction: { de: "Welcher Ozean?", en: "Which ocean?", hu: "Melyik óceán?", ro: "Care ocean?" },
      scenes: [
        {
          id: "sr-7-s1",
          title: { de: "Größter", en: "Largest", hu: "Legnagyobb", ro: "Cel mai mare" },
          prompt: { de: "Welcher Ozean ist der größte?", en: "Largest ocean?", hu: "A legnagyobb óceán?", ro: "Cel mai mare ocean?" },
          sceneType: "nature",
          visual: { icon: "🌊", bg: "#001a30", accent: "#38bdf8" },
          choices: [
            { id: "a", label: { de: "Atlantik", en: "Atlantic", hu: "Atlanti", ro: "Atlantic" } },
            { id: "b", label: { de: "Pazifik", en: "Pacific", hu: "Csendes", ro: "Pacific" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-8",
      title: { de: "Wirtschaftsorganisationen", en: "Organizations", hu: "Szervezetek", ro: "Organizații" },
      instruction: { de: "Welche Organisation?", en: "Which organization?", hu: "Melyik szervezet?", ro: "Care organizație?" },
      scenes: [
        {
          id: "sr-8-s1",
          title: { de: "Welthandel", en: "World Trade", hu: "Világkeres.", ro: "Comerț" },
          prompt: { de: "Welche Organisation regelt den Welthandel?", en: "Who regulates world trade?", hu: "Ki szabályozza a világkereskedelmet?", ro: "Cine reglează comerțul?" },
          sceneType: "community",
          visual: { icon: "🌐", bg: "#001a30", accent: "#38bdf8" },
          choices: [
            { id: "a", label: { de: "EU", en: "EU", hu: "EU", ro: "UE" } },
            { id: "b", label: { de: "WTO", en: "WTO", hu: "WTO", ro: "OMC" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-9",
      title: { de: "Bevölkerungsreichste", en: "Most Populous", hu: "Legnépesebb", ro: "Cel mai populat" },
      instruction: { de: "Welches Land?", en: "Which country?", hu: "Melyik ország?", ro: "Care țară?" },
      scenes: [
        {
          id: "sr-9-s1",
          title: { de: "Einwohner", en: "Population", hu: "Lakosság", ro: "Populație" },
          prompt: { de: "Welches Land hat die größte Bevölkerung?", en: "Most populous country?", hu: "A legnépesebb ország?", ro: "Cea mai populată țară?" },
          sceneType: "community",
          visual: { icon: "👥", bg: "#0a1a00", accent: "#4ade80" },
          choices: [
            { id: "a", label: { de: "Indien", en: "India", hu: "India", ro: "India" } },
            { id: "b", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" } },
          ],
          correctChoiceId: "a",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    },
    {
      id: "geo-sr-10",
      title: { de: "EU", en: "EU", hu: "EU", ro: "UE" },
      instruction: { de: "Mitgliedsstaaten", en: "Members", hu: "Tagállamok", ro: "Membrii" },
      scenes: [
        {
          id: "sr-10-s1",
          title: { de: "EU-Gründung", en: "EU Founding", hu: "EU-alapítás", ro: "Fondare UE" },
          prompt: { de: "Welches Land war Gründungsmitglied?", en: "Which was a founding member?", hu: "Melyik volt alapító tag?", ro: "Care a fost membru fondator?" },
          sceneType: "community",
          visual: { icon: "🇪🇺", bg: "#02113b", accent: "#f59e0b" },
          choices: [
            { id: "a", label: { de: "Spanien", en: "Spain", hu: "Spanyolország", ro: "Spania" } },
            { id: "b", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" } },
          ],
          correctChoiceId: "b",
          successFeedback: { de: "Richtig!", en: "Correct!", hu: "Helyes!", ro: "Corect!" },
          failFeedback: { de: "Falsch.", en: "Wrong.", hu: "Helytelen.", ro: "Greșit." },
        },
      ],
    }
  ],

  // ── ConstellationBuilder ─────────────────────────────────────────────
  constellationBuilder: [
    {
      id: "geo-cb-1",
      title: { de: "Kontinente Größe", en: "Continent Size", hu: "Kontinens méret", ro: "Mărime Continente" },
      instruction: { de: "Vom kleinsten zum größten.", en: "Smallest to largest.", hu: "Legkisebbtől a legnagyobbig.", ro: "Cel mai mic la cel mai mare." },
      hint: { de: "Asien ist am größten.", en: "Asia is the largest.", hu: "Ázsia a legnagyobb.", ro: "Asia e cea mai mare." },
      theme: { bg: "#0f172a", accent: "#34d399", card: "#0d3321" },
      parts: [
        { id: "australien", label: { de: "Australien", en: "Australia", hu: "Ausztrália", ro: "Australia" }, emoji: "🦘" },
        { id: "europa", label: { de: "Europa", en: "Europe", hu: "Európa", ro: "Europa" }, emoji: "🌍" },
        { id: "nordamerika", label: { de: "Nordamerika", en: "North America", hu: "Észak-Amerika", ro: "America de Nord" }, emoji: "🌎" },
        { id: "asien", label: { de: "Asien", en: "Asia", hu: "Ázsia", ro: "Asia" }, emoji: "🌏" },
      ],
      slots: [
        { id: "s1", label: { de: "1. Kleinster", en: "1. Smallest", hu: "1. Legkisebb", ro: "1. Cel mai mic" } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4. Größter", en: "4. Largest", hu: "4. Legnagyobb", ro: "4. Cel mai mare" } },
      ],
      solution: ["australien", "europa", "nordamerika", "asien"],
    },
    {
      id: "geo-cb-2",
      title: { de: "Flüsse Länge", en: "River Length", hu: "Folyó hossz", ro: "Lungime Râu" },
      instruction: { de: "Vom kürzesten zum längsten.", en: "Shortest to longest.", hu: "Legrövidebbtől a leghosszabbig.", ro: "Cel mai scurt la cel mai lung." },
      hint: { de: "Nil ist der längste.", en: "Nile is longest.", hu: "Nílus a leghosszabb.", ro: "Nil e cel mai lung." },
      theme: { bg: "#082f49", accent: "#38bdf8", card: "#0c3a5c" },
      parts: [
        { id: "rhein", label: { de: "Rhein", en: "Rhine", hu: "Rajna", ro: "Rin" }, emoji: "🌊" },
        { id: "donau", label: { de: "Donau", en: "Danube", hu: "Duna", ro: "Dunăre" }, emoji: "💧" },
        { id: "amazonas", label: { de: "Amazonas", en: "Amazon", hu: "Amazonas", ro: "Amazon" }, emoji: "🌿" },
        { id: "nil", label: { de: "Nil", en: "Nile", hu: "Nílus", ro: "Nil" }, emoji: "🐊" },
      ],
      slots: [
        { id: "s1", label: { de: "1. Kürzester", en: "1. Shortest", hu: "1. Legrövidebb", ro: "1. Cel mai scurt" } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4. Längster", en: "4. Longest", hu: "4. Leghosszabb", ro: "4. Cel mai lung" } },
      ],
      solution: ["rhein", "donau", "amazonas", "nil"],
    },
    {
      id: "geo-cb-3",
      title: { de: "Berge Höhe", en: "Mountain Height", hu: "Hegy magasság", ro: "Înălțime Munte" },
      instruction: { de: "Vom niedrigsten zum höchsten.", en: "Lowest to highest.", hu: "Legalacsonyabbtól a legmagasabbig.", ro: "De la cel mai jos la cel mai înalt." },
      hint: { de: "Everest ist am höchsten.", en: "Everest is highest.", hu: "Everest a legmagasabb.", ro: "Everest e cel mai înalt." },
      theme: { bg: "#1c1917", accent: "#fb923c", card: "#2c1f10" },
      parts: [
        { id: "brocken", label: { de: "Brocken", en: "Brocken", hu: "Brocken", ro: "Brocken" }, emoji: "⛰️" },
        { id: "zugspitze", label: { de: "Zugspitze", en: "Zugspitze", hu: "Zugspitze", ro: "Zugspitze" }, emoji: "🏔️" },
        { id: "montblanc", label: { de: "Mont Blanc", en: "Mont Blanc", hu: "Mont Blanc", ro: "Mont Blanc" }, emoji: "🗻" },
        { id: "everest", label: { de: "Mount Everest", en: "Everest", hu: "Mount Everest", ro: "Everest" }, emoji: "🗻" },
      ],
      slots: [
        { id: "s1", label: { de: "1. Niedrigster", en: "1. Lowest", hu: "1. Legalacsonyabb", ro: "1. Cel mai jos" } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4. Höchster", en: "4. Highest", hu: "4. Legmagasabb", ro: "4. Cel mai înalt" } },
      ],
      solution: ["brocken", "zugspitze", "montblanc", "everest"],
    },
    {
      id: "geo-cb-4",
      title: { de: "EU Beitritt", en: "EU Accession", hu: "EU-csatlakozás", ro: "Aderare UE" },
      instruction: { de: "Frühester zu spätester Beitritt.", en: "Earliest to latest.", hu: "Legkorábbitól a legkésőbbiig.", ro: "Cea mai devreme la cea mai târzie." },
      hint: { de: "Deutschland war Gründer.", en: "Germany was founder.", hu: "Németország alapító.", ro: "Germania a fost fondator." },
      theme: { bg: "#02113b", accent: "#fbbf24", card: "#0d2566" },
      parts: [
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "gr", label: { de: "Griechenland", en: "Greece", hu: "Görögország", ro: "Grecia" }, emoji: "🇬🇷" },
        { id: "se", label: { de: "Schweden", en: "Sweden", hu: "Svédország", ro: "Suedia" }, emoji: "🇸🇪" },
        { id: "pl", label: { de: "Polen", en: "Poland", hu: "Lengyelország", ro: "Polonia" }, emoji: "🇵🇱" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["de", "gr", "se", "pl"],
    },
    {
      id: "geo-cb-5",
      title: { de: "Nachbarn", en: "Neighbors", hu: "Szomszédok", ro: "Vecini" },
      instruction: { de: "Norden, Osten, Süden, Westen", en: "N, E, S, W", hu: "Észak, Kelet, Dél, Nyugat", ro: "N, E, S, V" },
      hint: { de: "Dänemark ist im Norden.", en: "Denmark is north.", hu: "Dánia északra van.", ro: "Danemarca e în nord." },
      theme: { bg: "#1a1a00", accent: "#facc15", card: "#2a2a00" },
      parts: [
        { id: "n", label: { de: "Dänemark", en: "Denmark", hu: "Dánia", ro: "Danemarca" }, emoji: "🇩🇰" },
        { id: "e", label: { de: "Polen", en: "Poland", hu: "Lengyelország", ro: "Polonia" }, emoji: "🇵🇱" },
        { id: "s", label: { de: "Österreich", en: "Austria", hu: "Ausztria", ro: "Austria" }, emoji: "🇦🇹" },
        { id: "w", label: { de: "Frankreich", en: "France", hu: "Franciaország", ro: "Franța" }, emoji: "🇫🇷" },
      ],
      slots: [
        { id: "n", label: { de: "Norden", en: "North", hu: "Észak", ro: "Nord" } },
        { id: "e", label: { de: "Osten", en: "East", hu: "Kelet", ro: "Est" } },
        { id: "s", label: { de: "Süden", en: "South", hu: "Dél", ro: "Sud" } },
        { id: "w", label: { de: "Westen", en: "West", hu: "Nyugat", ro: "Vest" } },
      ],
      solution: ["n", "e", "s", "w"],
    },
    {
      id: "geo-cb-6",
      title: { de: "BIP-Größe", en: "GDP Size", hu: "GDP méret", ro: "Mărime PIB" },
      instruction: { de: "Vom kleinsten zum größten BIP.", en: "Smallest to largest GDP.", hu: "Legkisebbtől a legnagyobbig.", ro: "Cel mai mic la cel mai mare PIB." },
      hint: { de: "USA ist am größten.", en: "USA is largest.", hu: "USA a legnagyobb.", ro: "SUA e cea mai mare." },
      theme: { bg: "#0f172a", accent: "#f59e0b", card: "#1f1a00" },
      parts: [
        { id: "lu", label: { de: "Luxemburg", en: "Luxembourg", hu: "Luxemburg", ro: "Luxemburg" }, emoji: "🇱🇺" },
        { id: "at", label: { de: "Österreich", en: "Austria", hu: "Ausztria", ro: "Austria" }, emoji: "🇦🇹" },
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "us", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" }, emoji: "🇺🇸" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["lu", "at", "de", "us"],
    },
    {
      id: "geo-cb-7",
      title: { de: "Bevölkerungsdichte", en: "Population Density", hu: "Népsűrűség", ro: "Densitate Populație" },
      instruction: { de: "Von niedrig zu hoch.", en: "Lowest to highest.", hu: "Legalacsonyabbtól a legmagasabbig.", ro: "Cel mai jos la cel mai înalt." },
      hint: { de: "Bangladesch ist sehr dicht.", en: "Bangladesh is dense.", hu: "Banglades nagyon sűrű.", ro: "Bangladesh e dens." },
      theme: { bg: "#1a0a2e", accent: "#a78bfa", card: "#2a1040" },
      parts: [
        { id: "is", label: { de: "Island", en: "Iceland", hu: "Izland", ro: "Islanda" }, emoji: "🇮🇸" },
        { id: "ca", label: { de: "Kanada", en: "Canada", hu: "Kanada", ro: "Canada" }, emoji: "🇨🇦" },
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "bd", label: { de: "Bangladesch", en: "Bangladesh", hu: "Banglades", ro: "Bangladesh" }, emoji: "🇧🇩" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["is", "ca", "de", "bd"],
    },
    {
      id: "geo-cb-8",
      title: { de: "Handelsrouten", en: "Trade Routes", hu: "Keresk. útvonalak", ro: "Rute Comerț" },
      instruction: { de: "Alt zu Neu.", en: "Oldest to newest.", hu: "Legrégebbitől a legújabbig.", ro: "Cea mai veche la cea mai nouă." },
      hint: { de: "Seidenstraße ist am ältesten.", en: "Silk road is oldest.", hu: "A Selyemút a legrégebbi.", ro: "Drumul Mătăsii e cel mai vechi." },
      theme: { bg: "#1c1917", accent: "#fb923c", card: "#2c1a00" },
      parts: [
        { id: "seiden", label: { de: "Seidenstraße", en: "Silk Road", hu: "Selyemút", ro: "Drumul Mătăsii" }, emoji: "🐪" },
        { id: "gewuerz", label: { de: "Gewürzroute", en: "Spice Route", hu: "Fűszerút", ro: "Ruta Mirodeniilor" }, emoji: "🌶️" },
        { id: "suez", label: { de: "Suezkanal", en: "Suez Canal", hu: "Szuezi-csat.", ro: "Canalul Suez" }, emoji: "🚢" },
        { id: "panama", label: { de: "Panamakanal", en: "Panama Canal", hu: "Panama-csat.", ro: "Canalul Panama" }, emoji: "⛵" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["seiden", "gewuerz", "suez", "panama"],
    },
    {
      id: "geo-cb-9",
      title: { de: "Kontinent-Puzzle", en: "Continent Puzzle", hu: "Kontinens Puzzle", ro: "Puzzle Continente" },
      instruction: { de: "Von Nord nach Süd.", en: "North to South.", hu: "Északról délre.", ro: "Nord spre Sud." },
      hint: { de: "Nordamerika oben.", en: "North America top.", hu: "Észak-Amerika fent.", ro: "America de Nord sus." },
      theme: { bg: "#0f172a", accent: "#38bdf8", card: "#1e3a5f" },
      parts: [
        { id: "na", label: { de: "Nordamerika", en: "North America", hu: "Észak-Amerika", ro: "America de Nord" }, emoji: "🌎" },
        { id: "eu", label: { de: "Europa", en: "Europe", hu: "Európa", ro: "Europa" }, emoji: "🌍" },
        { id: "af", label: { de: "Afrika", en: "Africa", hu: "Afrika", ro: "Africa" }, emoji: "🌍" },
        { id: "an", label: { de: "Antarktis", en: "Antarctica", hu: "Antarktisz", ro: "Antarctica" }, emoji: "🐧" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["na", "eu", "af", "an"],
    },
    {
      id: "geo-cb-10",
      title: { de: "Stadt-Puzzle", en: "City Puzzle", hu: "Város Puzzle", ro: "Puzzle Orașe" },
      instruction: { de: "West nach Ost.", en: "West to East.", hu: "Nyugatról keletre.", ro: "Vest spre Est." },
      hint: { de: "London im Westen.", en: "London is west.", hu: "London van nyugatra.", ro: "Londra e la vest." },
      theme: { bg: "#1a1000", accent: "#facc15", card: "#2a2a00" },
      parts: [
        { id: "lo", label: { de: "London", en: "London", hu: "London", ro: "Londra" }, emoji: "🕰️" },
        { id: "pa", label: { de: "Paris", en: "Paris", hu: "Párizs", ro: "Paris" }, emoji: "🗼" },
        { id: "be", label: { de: "Berlin", en: "Berlin", hu: "Berlin", ro: "Berlin" }, emoji: "🏛️" },
        { id: "mo", label: { de: "Moskau", en: "Moscow", hu: "Moszkva", ro: "Moscova" }, emoji: "🏰" },
      ],
      slots: [
        { id: "s1", label: { de: "1.", en: "1.", hu: "1.", ro: "1." } },
        { id: "s2", label: { de: "2.", en: "2.", hu: "2.", ro: "2." } },
        { id: "s3", label: { de: "3.", en: "3.", hu: "3.", ro: "3." } },
        { id: "s4", label: { de: "4.", en: "4.", hu: "4.", ro: "4." } },
      ],
      solution: ["lo", "pa", "be", "mo"],
    }
  ],

  // ── MemoryRadar ──────────────────────────────────────────────────────
  memoryRadar: [
    {
      id: "geo-mr-1",
      title: { de: "Hauptstädte merken", en: "Remember Capitals", hu: "Fővárosok memorizálása", ro: "Reține Capitalele" },
      instruction: { de: "Merke dir die Hauptstädte.", en: "Remember the capitals.", hu: "Jegyezd meg a fővárosokat.", ro: "Reține capitalele." },
      flashDurationMs: 4000,
      selectionLimit: 4,
      theme: { bg: "#0f172a", accent: "#38bdf8", radar: "#1e40af" },
      targetItems: [
        { id: "berlin", label: { de: "Berlin", en: "Berlin", hu: "Berlin", ro: "Berlin" }, emoji: "🏛️" },
        { id: "paris", label: { de: "Paris", en: "Paris", hu: "Párizs", ro: "Paris" }, emoji: "🗼" },
        { id: "rom", label: { de: "Rom", en: "Rome", hu: "Róma", ro: "Roma" }, emoji: "🏟️" },
        { id: "madrid", label: { de: "Madrid", en: "Madrid", hu: "Madrid", ro: "Madrid" }, emoji: "🇪🇸" },
      ],
      decoyItems: [
        { id: "muenchen", label: { de: "München", en: "Munich", hu: "München", ro: "München" }, emoji: "🍺" },
        { id: "barcelona", label: { de: "Barcelona", en: "Barcelona", hu: "Barcelona", ro: "Barcelona" }, emoji: "⛹️" },
      ],
    },
    {
      id: "geo-mr-2",
      title: { de: "Länder Europas", en: "Countries of Europe", hu: "Európa országai", ro: "Țările Europei" },
      instruction: { de: "Welche Länder hast du gesehen?", en: "Which countries did you see?", hu: "Melyik országokat láttad?", ro: "Ce țări ai văzut?" },
      flashDurationMs: 4000,
      selectionLimit: 4,
      theme: { bg: "#1a0a2e", accent: "#a78bfa", radar: "#6d28d9" },
      targetItems: [
        { id: "griechenland", label: { de: "Griechenland", en: "Greece", hu: "Görögország", ro: "Grecia" }, emoji: "🇬🇷" },
        { id: "portugal", label: { de: "Portugal", en: "Portugal", hu: "Portugália", ro: "Portugalia" }, emoji: "🇵🇹" },
        { id: "schweden", label: { de: "Schweden", en: "Sweden", hu: "Svédország", ro: "Suedia" }, emoji: "🇸🇪" },
        { id: "ungarn", label: { de: "Ungarn", en: "Hungary", hu: "Magyarország", ro: "Ungaria" }, emoji: "🇭🇺" },
      ],
      decoyItems: [
        { id: "marokko", label: { de: "Marokko", en: "Morocco", hu: "Marokkó", ro: "Maroc" }, emoji: "🇲🇦" },
        { id: "tunesien", label: { de: "Tunesien", en: "Tunisia", hu: "Tunézia", ro: "Tunisia" }, emoji: "🇹🇳" },
      ],
    },
    {
      id: "geo-mr-3",
      title: { de: "Hauptstadt-Paare", en: "Capital Pairs", hu: "Főváros Párok", ro: "Perechi Capitale" },
      instruction: { de: "Merke dir diese Hauptstädte.", en: "Remember these capitals.", hu: "Jegyezd meg ezeket a fővárosokat.", ro: "Reține aceste capitale." },
      flashDurationMs: 5000,
      selectionLimit: 4,
      theme: { bg: "#052e16", accent: "#4ade80", radar: "#15803d" },
      targetItems: [
        { id: "oslo", label: { de: "Oslo", en: "Oslo", hu: "Oslo", ro: "Oslo" }, emoji: "🇳🇴" },
        { id: "stockholm", label: { de: "Stockholm", en: "Stockholm", hu: "Stockholm", ro: "Stockholm" }, emoji: "🇸🇪" },
        { id: "kopenhagen", label: { de: "Kopenhagen", en: "Copenhagen", hu: "Koppenhága", ro: "Copenhaga" }, emoji: "🇩🇰" },
        { id: "helsinki", label: { de: "Helsinki", en: "Helsinki", hu: "Helsinki", ro: "Helsinki" }, emoji: "🇫🇮" },
      ],
      decoyItems: [
        { id: "bergen", label: { de: "Bergen", en: "Bergen", hu: "Bergen", ro: "Bergen" }, emoji: "🏔️" },
        { id: "malmo", label: { de: "Malmö", en: "Malmö", hu: "Malmö", ro: "Malmö" }, emoji: "🌉" },
      ],
    },
    {
      id: "geo-mr-4",
      title: { de: "EU-Mitgliedstaaten", en: "EU Members", hu: "EU tagállamok", ro: "Membrii UE" },
      instruction: { de: "EU-Länder erkennen.", en: "Recognize EU countries.", hu: "Ismerd fel az EU országokat.", ro: "Recunoaște țările UE." },
      flashDurationMs: 4500,
      selectionLimit: 4,
      theme: { bg: "#02113b", accent: "#fbbf24", radar: "#1e3a8a" },
      targetItems: [
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "fr", label: { de: "Frankreich", en: "France", hu: "Franciaország", ro: "Franța" }, emoji: "🇫🇷" },
        { id: "gr", label: { de: "Griechenland", en: "Greece", hu: "Görögország", ro: "Grecia" }, emoji: "🇬🇷" },
        { id: "hu", label: { de: "Ungarn", en: "Hungary", hu: "Magyarország", ro: "Ungaria" }, emoji: "🇭🇺" },
      ],
      decoyItems: [
        { id: "ch", label: { de: "Schweiz", en: "Switzerland", hu: "Svájc", ro: "Elveția" }, emoji: "🇨🇭" },
        { id: "no", label: { de: "Norwegen", en: "Norway", hu: "Norvégia", ro: "Norvegia" }, emoji: "🇳🇴" },
      ],
    },
    {
      id: "geo-mr-5",
      title: { de: "Gebirge Europas", en: "Mountains of Europe", hu: "Európa hegyei", ro: "Munții Europei" },
      instruction: { de: "Welche Gebirge?", en: "Which mountains?", hu: "Melyik hegyek?", ro: "Care munți?" },
      flashDurationMs: 4000,
      selectionLimit: 4,
      theme: { bg: "#1c1917", accent: "#a3e635", radar: "#365314" },
      targetItems: [
        { id: "alpen", label: { de: "Alpen", en: "Alps", hu: "Alpok", ro: "Alpi" }, emoji: "🏔️" },
        { id: "pyrenaeen", label: { de: "Pyrenäen", en: "Pyrenees", hu: "Pireneusok", ro: "Pirinei" }, emoji: "⛰️" },
        { id: "karpaten", label: { de: "Karpaten", en: "Carpathians", hu: "Kárpátok", ro: "Carpați" }, emoji: "🌲" },
        { id: "ural", label: { de: "Ural", en: "Ural", hu: "Urál", ro: "Ural" }, emoji: "🏞️" },
      ],
      decoyItems: [
        { id: "himalaya", label: { de: "Himalaya", en: "Himalayas", hu: "Himalája", ro: "Himalaya" }, emoji: "🗻" },
        { id: "rocky", label: { de: "Rocky Mountains", en: "Rockies", hu: "Sziklás-h.", ro: "Munții Stâncoși" }, emoji: "🏔️" },
      ],
    },
    {
      id: "geo-mr-6",
      title: { de: "Nachbarn", en: "Neighbors", hu: "Szomszédok", ro: "Vecini" },
      instruction: { de: "Nachbarländer merken.", en: "Remember neighbors.", hu: "Jegyezd meg a szomszédokat.", ro: "Reține vecinii." },
      flashDurationMs: 5000,
      selectionLimit: 4,
      theme: { bg: "#1a1a00", accent: "#facc15", radar: "#713f12" },
      targetItems: [
        { id: "fr", label: { de: "Frankreich", en: "France", hu: "Franciaország", ro: "Franța" }, emoji: "🇫🇷" },
        { id: "at", label: { de: "Österreich", en: "Austria", hu: "Ausztria", ro: "Austria" }, emoji: "🇦🇹" },
        { id: "ch", label: { de: "Schweiz", en: "Switzerland", hu: "Svájc", ro: "Elveția" }, emoji: "🇨🇭" },
        { id: "nl", label: { de: "Niederlande", en: "Netherlands", hu: "Hollandia", ro: "Olanda" }, emoji: "🇳🇱" },
      ],
      decoyItems: [
        { id: "se", label: { de: "Schweden", en: "Sweden", hu: "Svédország", ro: "Suedia" }, emoji: "🇸🇪" },
        { id: "it", label: { de: "Italien", en: "Italy", hu: "Olaszország", ro: "Italia" }, emoji: "🇮🇹" },
      ],
    },
    {
      id: "geo-mr-7",
      title: { de: "Weltmetropolen", en: "World Metropolises", hu: "Világvárosok", ro: "Metropole" },
      instruction: { de: "Finde sie danach.", en: "Find them later.", hu: "Keresd meg utána.", ro: "Găsește-le după." },
      flashDurationMs: 4000,
      selectionLimit: 4,
      theme: { bg: "#1c1917", accent: "#fbbf24", radar: "#92400e" },
      targetItems: [
        { id: "tokio", label: { de: "Tokio", en: "Tokyo", hu: "Tokió", ro: "Tokyo" }, emoji: "🗼" },
        { id: "delhi", label: { de: "Delhi", en: "Delhi", hu: "Újdelhi", ro: "Delhi" }, emoji: "🕌" },
        { id: "saopaulo", label: { de: "São Paulo", en: "São Paulo", hu: "São Paulo", ro: "São Paulo" }, emoji: "🌆" },
        { id: "kairo", label: { de: "Kairo", en: "Cairo", hu: "Kairó", ro: "Cairo" }, emoji: "🐪" },
      ],
      decoyItems: [
        { id: "osaka", label: { de: "Osaka", en: "Osaka", hu: "Oszaka", ro: "Osaka" }, emoji: "🏯" },
        { id: "rio", label: { de: "Rio", en: "Rio", hu: "Rio", ro: "Rio" }, emoji: "🎭" },
      ],
    },
    {
      id: "geo-mr-8",
      title: { de: "Kontinente", en: "Continents", hu: "Kontinensek", ro: "Continente" },
      instruction: { de: "Welche hast du gesehen?", en: "Which did you see?", hu: "Melyiket láttad?", ro: "Pe care le-ai văzut?" },
      flashDurationMs: 3500,
      selectionLimit: 4,
      theme: { bg: "#0f172a", accent: "#34d399", radar: "#065f46" },
      targetItems: [
        { id: "asien", label: { de: "Asien", en: "Asia", hu: "Ázsia", ro: "Asia" }, emoji: "🌏" },
        { id: "afrika", label: { de: "Afrika", en: "Africa", hu: "Afrika", ro: "Africa" }, emoji: "🌍" },
        { id: "antarktis", label: { de: "Antarktis", en: "Antarctica", hu: "Antarktisz", ro: "Antarctica" }, emoji: "🐧" },
        { id: "australien", label: { de: "Australien", en: "Australia", hu: "Ausztrália", ro: "Australia" }, emoji: "🦘" },
      ],
      decoyItems: [
        { id: "atlantis", label: { de: "Atlantis", en: "Atlantis", hu: "Atlantisz", ro: "Atlantida" }, emoji: "🌊" },
        { id: "sibirien", label: { de: "Sibirien", en: "Siberia", hu: "Szibéria", ro: "Siberia" }, emoji: "🌨️" },
      ],
    },
    {
      id: "geo-mr-9",
      title: { de: "Weltflüsse", en: "World Rivers", hu: "Világ folyói", ro: "Râuri Mondiale" },
      instruction: { de: "Merke dir diese Flüsse.", en: "Remember these rivers.", hu: "Jegyezd meg ezeket.", ro: "Reține aceste râuri." },
      flashDurationMs: 4500,
      selectionLimit: 4,
      theme: { bg: "#082f49", accent: "#38bdf8", radar: "#1e3a8a" },
      targetItems: [
        { id: "nil", label: { de: "Nil", en: "Nile", hu: "Nílus", ro: "Nil" }, emoji: "🐊" },
        { id: "amazonas", label: { de: "Amazonas", en: "Amazon", hu: "Amazonas", ro: "Amazon" }, emoji: "🌿" },
        { id: "yangtze", label: { de: "Yangtze", en: "Yangtze", hu: "Jangce", ro: "Yangtze" }, emoji: "🐉" },
        { id: "ganges", label: { de: "Ganges", en: "Ganges", hu: "Gangesz", ro: "Gange" }, emoji: "🕉️" },
      ],
      decoyItems: [
        { id: "hudson", label: { de: "Hudson", en: "Hudson", hu: "Hudson", ro: "Hudson" }, emoji: "🌊" },
        { id: "lena", label: { de: "Lena", en: "Lena", hu: "Léna", ro: "Lena" }, emoji: "🏔️" },
      ],
    },
    {
      id: "geo-mr-10",
      title: { de: "Wirtschaftsmächte", en: "Economies", hu: "Gazdaságok", ro: "Economii" },
      instruction: { de: "Führende Wirtschaftsmächte.", en: "Top economies.", hu: "Vezető gazdaságok.", ro: "Economii de top." },
      flashDurationMs: 4000,
      selectionLimit: 4,
      theme: { bg: "#0f172a", accent: "#f59e0b", radar: "#92400e" },
      targetItems: [
        { id: "us", label: { de: "USA", en: "USA", hu: "USA", ro: "SUA" }, emoji: "🇺🇸" },
        { id: "cn", label: { de: "China", en: "China", hu: "Kína", ro: "China" }, emoji: "🇨🇳" },
        { id: "de", label: { de: "Deutschland", en: "Germany", hu: "Németország", ro: "Germania" }, emoji: "🇩🇪" },
        { id: "jp", label: { de: "Japan", en: "Japan", hu: "Japán", ro: "Japonia" }, emoji: "🇯🇵" },
      ],
      decoyItems: [
        { id: "mc", label: { de: "Monaco", en: "Monaco", hu: "Monaco", ro: "Monaco" }, emoji: "🇲🇨" },
        { id: "sm", label: { de: "San Marino", en: "San Marino", hu: "San Marino", ro: "San Marino" }, emoji: "🇸🇲" },
      ],
    }
  ]
};
