import fs from "node:fs";
import path from "node:path";

const IMG_DIR = path.join(process.cwd(), "public", "poi-images");
const OUT = path.join(process.cwd(), "lib", "visualLab", "data", "poiImageManifest.ts");

const ids = fs
  .readdirSync(IMG_DIR)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.slice(0, -".webp".length))
  .sort();

const lines = [
  "// AUTO-GENERATED by scripts/buildPoiImageManifest.ts — do not edit by hand.",
  `// ${ids.length} entries`,
  "",
  "export const POI_IMAGE_IDS: ReadonlySet<string> = new Set([",
  ...ids.map((id) => `  ${JSON.stringify(id)},`),
  "]);",
  "",
];

fs.writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`wrote ${ids.length} ids -> ${OUT}`);
