import json

faqs = {}

def add_faq(id, de, hu, ro, en):
    faqs[id] = {
        "de": de,
        "hu": hu,
        "ro": ro,
        "en": en
    }

# Batch 5: 41-50
add_faq("historical-diekirch-military-history",
    [{"q": "Was ist das Hauptthema des Militärmuseums in Diekirch?", "a": "Die Ardennenoffensive (Battle of the Bulge) im Winter 1944-1945."},
     {"q": "Gibt es lebensgroße Dioramen im Museum?", "a": "Ja, das Museum ist berühmt für seine sehr realistischen, lebensgroßen Darstellungen von Kriegsszenen."},
     {"q": "Welche schweren Fahrzeuge kann man in Diekirch sehen?", "a": "Es gibt eine beeindruckende Sammlung an Panzern, LKWs und Kanonen aus dem Zweiten Weltkrieg."},
     {"q": "Behandelt das Museum auch die Geschichte der luxemburgischen Armee?", "a": "Ja, es gibt eine eigene Abteilung zur Geschichte und Ausrüstung der heimischen Armee."},
     {"q": "Gibt es persönliche Gegenstände von Soldaten im Museum?", "a": "Ja, viele Exponate stammen von Veteranen, die ihre Ausrüstung dem Museum gespendet haben."}],
    [{"q": "Mi a diekirchi hadtörténeti múzeum fő témája?", "a": "Az ardenneki offenzíva (Battle of the Bulge) az 1944-1945-ös tél folyamán."},
     {"q": "Vannak életnagyságú diorámák a múzeumban?", "a": "Igen, a múzeum híres a háborús jelenetek rendkívül élethű, életnagyságú ábrázolásáról."},
     {"q": "Milyen nehézgépeket láthatunk Diekirchben?", "a": "A második világháborúból származó tankok, teherautók és ágyúk lenyűgöző gyűjteménye található itt."},
     {"q": "Foglalkozik a múzeum a luxemburgi hadsereg történetével is?", "a": "Igen, külön részleg mutatja be a hazai hadsereg történetét és felszerelését."},
     {"q": "Vannak katonák személyes tárgyai a múzeumban?", "a": "Igen, sok kiállítási tárgy veteránoktól származik, akik a múzeumnak adományozták felszerelésüket."}],
    [{"q": "Care este tema principală a Muzeului Militar din Diekirch?", "a": "Ofensiva din Ardeni (Bătălia de la Bulge) din iarna anilor 1944-1945."},
     {"q": "Există diorame în mărime naturală în muzeu?", "a": "Da, muzeul este faimos pentru reprezentările sale foarte realiste, în mărime naturală, ale scenelor de război."},
     {"q": "Ce vehicule grele pot fi văzute la Diekirch?", "a": "Există o colecție impresionantă de tancuri, camioane și tunuri din al Doilea Război Mondial."},
     {"q": "Tratează muzeul și istoria armatei luxemburgheze?", "a": "Da, există o secțiune dedicată istoriei și echipamentului armatei naționale."},
     {"q": "Există obiecte personale ale soldaților în muzeu?", "a": "Da, multe exponate provin de la veterani care și-au donat echipamentul muzeului."}],
    [{"q": "What is the main theme of the military museum in Diekirch?", "a": "The Battle of the Bulge during the winter of 1944-1945."},
     {"q": "Are there life-sized dioramas in the museum?", "a": "Yes, the museum is famous for its very realistic, life-sized depictions of war scenes."},
     {"q": "What heavy vehicles can be seen in Diekirch?", "a": "There is an impressive collection of tanks, trucks, and cannons from WWII."},
     {"q": "Does the museum also cover the history of the Luxembourgish army?", "a": "Yes, there is a dedicated section on the history and equipment of the local army."},
     {"q": "Are there personal items from soldiers in the museum?", "a": "Yes, many exhibits come from veterans who donated their equipment to the museum."}]
)

add_faq("landmark-bourglinster-castle",
    [{"q": "Wofür ist das Schloss Burglinster heute besonders bekannt?", "a": "Es ist ein bedeutendes Gastronomiezentrum mit einem Sternerestaurant."},
     {"q": "Wann wurde das Schloss Burglinster erbaut?", "a": "Die Ursprünge der Burg gehen auf das 11. Jahrhundert zurück."},
     {"q": "Gibt es kulturelle Veranstaltungen auf dem Schloss?", "a": "Ja, es finden regelmäßig Konzerte, Ausstellungen und Kunsthandwerkskurse statt."},
     {"q": "Wie sieht die Architektur des Schlosses aus?", "a": "Es ist eine beeindruckende Mischung aus mittelalterlichen Mauern und späteren Renaissance-Elementen."},
     {"q": "Kann man im Schloss Burglinster heiraten?", "a": "Ja, das Schloss ist ein sehr beliebter Ort für Hochzeiten und festliche Bankette."}],
    [{"q": "Miről különösen ismert ma a bourglinsteri kastély?", "a": "Jelentős gasztronómiai központ, ahol Michelin-csillagos étterem is működik."},
     {"q": "Mikor épült a bourglinsteri kastély?", "a": "A vár eredete a 11. századig nyúlik vissza."},
     {"q": "Vannak kulturális események a kastélyban?", "a": "Igen, rendszeresen tartanak koncerteket, kiállításokat és kézműves foglalkozásokat."},
     {"q": "Milyen a kastély építészeti stílusa?", "a": "A középkori falak és a későbbi reneszánsz elemek lenyűgöző keveréke."},
     {"q": "Lehet esküvőt tartani a bourglinsteri kastélyban?", "a": "Igen, a kastély nagyon népszerű helyszín esküvőkhöz és ünnepi bankettekhez."}],
    [{"q": "Pentru ce este cunoscut astăzi în mod special Castelul Bourglinster?", "a": "Este un centru gastronomic important, având și un restaurant cu stele Michelin."},
     {"q": "Când a fost construit Castelul Bourglinster?", "a": "Originile castelului datează din secolul al XI-lea."},
     {"q": "Există evenimente culturale la castel?", "a": "Da, au loc periodic concerte, expoziții și cursuri de artizanat."},
     {"q": "Cum este arhitectura castelului?", "a": "Este un amestec impresionant de ziduri medievale și elemente ulterioare din perioada Renașterii."},
     {"q": "Se pot organiza nunți la Castelul Bourglinster?", "a": "Da, castelul este o locație foarte populară pentru nunți și banchete festive."}],
    [{"q": "What is Bourglinster Castle particularly known for today?", "a": "It is a major gastronomic center, including a Michelin-starred restaurant."},
     {"q": "When was Bourglinster Castle built?", "a": "The origins of the castle date back to the 11th century."},
     {"q": "Are there cultural events at the castle?", "a": "Yes, concerts, exhibitions, and craft workshops are held regularly."},
     {"q": "What is the architecture of the castle like?", "a": "It is an impressive mix of medieval walls and later Renaissance elements."},
     {"q": "Can you have a wedding at Bourglinster Castle?", "a": "Yes, the castle is a very popular venue for weddings and festive banquets."}]
)

add_faq("historical-roman-villa-echternach",
    [{"q": "Wie groß war die römische Villa in Echternach?", "a": "Es war eine der größten und luxuriösesten Villen nördlich der Alpen."},
     {"q": "Wann wurde die Villa entdeckt?", "a": "Die Überreste wurden 1975 beim Bau des Echternacher Sees freigelegt."},
     {"q": "Was kann man im zugehörigen Museum sehen?", "a": "Man sieht Rekonstruktionen des Alltagslebens, Mosaike und ein Modell der Anlage."},
     {"q": "Hatte die Villa einen Garten?", "a": "Ja, es gab einen rekonstruierten römischen Garten mit typischen Heil- und Zierpflanzen."},
     {"q": "Wozu diente das Hauptgebäude ursprünglich?", "a": "Es war das Zentrum eines riesigen landwirtschaftlichen Betriebs."},
    ],
    [{"q": "Mekkora volt az echternachi római villa?", "a": "Az Alpoktól északra fekvő egyik legnagyobb és legfényűzőbb villa volt."},
     {"q": "Mikor fedezték fel a villát?", "a": "A maradványokat 1975-ben, az Echternachi-tó kialakításakor tárták fel."},
     {"q": "Mit láthatunk a hozzá tartozó múzeumban?", "a": "A mindennapi élet rekonstrukcióit, mozaikokat és a komplexum makettjét láthatjuk."},
     {"q": "Volt kertje a villának?", "a": "Igen, kialakítottak egy rekonstruált római kertet tipikus gyógy- és dísznövényekkel."},
     {"q": "Mire szolgált eredetileg a főépület?", "a": "Egy hatalmas mezőgazdasági birtok központja volt."}],
    [{"q": "Cât de mare era vila romană din Echternach?", "a": "A fost una dintre cele mai mari și luxoase vile de la nord de Alpi."},
     {"q": "Când a fost descoperită vila?", "a": "Rămășițele au fost scoase la iveală în 1975, în timpul amenajării lacului Echternach."},
     {"q": "Ce se poate vedea în muzeul aferent?", "a": "Se pot vedea reconstrucții ale vieții cotidiene, mozaicuri și o machetă a sitului."},
     {"q": "Avea vila o grădină?", "a": "Da, există o grădină romană reconstruită cu plante medicinale și ornamentale tipice."},
     {"q": "Care a fost funcția inițială a clădirii principale?", "a": "Era centrul unei vaste exploatații agricole."}],
    [{"q": "How large was the Roman Villa in Echternach?", "a": "It was one of the largest and most luxurious villas north of the Alps."},
     {"q": "When was the villa discovered?", "a": "The remains were uncovered in 1975 during the construction of Echternach Lake."},
     {"q": "What can you see in the accompanying museum?", "a": "You can see reconstructions of daily life, mosaics, and a model of the site."},
     {"q": "Did the villa have a garden?", "a": "Yes, there is a reconstructed Roman garden with typical medicinal and ornamental plants."},
     {"q": "What was the main building originally used for?", "a": "It was the center of a massive agricultural estate."}]
)

add_faq("landmark-mersch-castle",
    [{"q": "Wofür wird das Schloss Mersch heute genutzt?", "a": "Es beherbergt die Büros der Gemeindeverwaltung von Mersch."},
     {"q": "Ist das Schloss Mersch für Besucher zugänglich?", "a": "Nur der Innenhof und Teile des Gebäudes bei offiziellen Anlässen sind zugänglich."},
     {"q": "Was ist das Besondere am Turm des Schlosses?", "a": "Der quadratische Wohnturm ist der älteste Teil der Anlage aus dem 13. Jahrhundert."},
     {"q": "Gibt es ein Museum in der Nähe des Schlosses?", "a": "Das nationale Literaturzentrum (CNL) befindet sich ganz in der Nähe."},
     {"q": "Liegt das Schloss zentral in Mersch?", "a": "Ja, es liegt mitten im Ortszentrum, unweit der Kirche."}],
    [{"q": "Mire használják ma a merschi kastélyt?", "a": "Mersch község közigazgatási hivatalainak ad otthont."},
     {"q": "Látogatható a merschi kastély?", "a": "Csak a belső udvar és az épület egyes részei látogathatók hivatalos alkalmakkor."},
     {"q": "Mi a különleges a kastély tornyában?", "a": "A négyzet alakú lakótorony az erődítmény legrégebbi, 13. századi része."},
     {"q": "Van múzeum a kastély közelében?", "a": "A nemzeti irodalmi központ (CNL) a közvetlen közelben található."},
     {"q": "Központi helyen fekszik a kastély Merschben?", "a": "Igen, a település központjában, a templom közelében található."}],
    [{"q": "La ce este folosit astăzi Castelul Mersch?", "a": "Găzduiește birourile administrației comunale din Mersch."},
     {"q": "Este Castelul Mersch deschis vizitatorilor?", "a": "Doar curtea interioară și părți ale clădirii sunt accesibile cu ocazii oficiale."},
     {"q": "Ce este special la turnul castelului?", "a": "Turnul locuință pătrat este cea mai veche parte a sitului, datând din secolul al XIII-lea."},
     {"q": "Există vreun muzeu în apropierea castelului?", "a": "Centrul Național de Literatură (CNL) se află foarte aproape."},
     {"q": "Este castelul situat central în Mersch?", "a": "Da, este situat chiar în centrul localității, nu departe de biserică."}],
    [{"q": "What is Mersch Castle used for today?", "a": "It houses the offices of the Mersch municipal administration."},
     {"q": "Is Mersch Castle open to visitors?", "a": "Only the courtyard and parts of the building are accessible during official occasions."},
     {"q": "What is special about the castle's tower?", "a": "The square residential tower is the oldest part of the site, dating back to the 13th century."},
     {"q": "Is there a museum near the castle?", "a": "The National Literature Center (CNL) is located very close by."},
     {"q": "Is the castle centrally located in Mersch?", "a": "Yes, it is in the center of the town, not far from the church."}]
)

add_faq("river-our-river",
    [{"q": "Welche Funktion hat die Our für die Grenze Luxemburgs?", "a": "Sie bildet über weite Strecken die natürliche Grenze zu Deutschland."},
     {"q": "Kann man an der Our angeln?", "a": "Ja, die Our ist ein beliebtes Revier für Fliegenfischer."},
     {"q": "Welche Burg thront über dem Ourtal?", "a": "Die berühmte Burg Vianden überragt das Tal."},
     {"q": "Gibt es Wasserkraftwerke an der Our?", "a": "Ja, das Pumpspeicherwerk Vianden ist eines der größten in Europa."},
     {"q": "Was ist das Naturschutzgebiet 'Our-Tal'?", "a": "Ein geschütztes Gebiet mit seltener Flora und Fauna entlang des Flusses."}],
    [{"q": "Milyen határmenti szerepe van az Our folyónak?", "a": "Hosszú szakaszon ez képezi a természetes határt Németországgal."},
     {"q": "Lehet horgászni az Our folyón?", "a": "Igen, az Our népszerű hely a műlegyező horgászok körében."},
     {"q": "Melyik vár magasodik az Our völgye fölé?", "a": "A híres Viandeni vár emelkedik a völgy fölé."},
     {"q": "Vannak vízerőművek az Our folyón?", "a": "Igen, a viandeni szivattyús-tározós erőmű Európa egyik legnagyobbja."},
     {"q": "Mi az 'Our-völgy' természetvédelmi terület?", "a": "Egy védett terület ritka növény- és állatvilággal a folyó mentén."}],
    [{"q": "Ce rol are râul Our pentru granița Luxemburgului?", "a": "Formează pe porțiuni lungi granița naturală cu Germania."},
     {"q": "Se poate pescui pe râul Our?", "a": "Da, râul Our este o zonă populară pentru pescuitul cu muște."},
     {"q": "Ce castel domină valea râului Our?", "a": "Celebrul Castel Vianden domină valea."},
     {"q": "Există hidrocentrale pe râul Our?", "a": "Da, centrala de acumulare prin pompare de la Vianden este una dintre cele mai mari din Europa."},
     {"q": "Ce este rezervația naturală 'Valea Ourului'?", "a": "O zonă protejată cu floră și faună rare de-a lungul râului."}],
    [{"q": "What function does the Our River have for Luxembourg's border?", "a": "It forms the natural border with Germany over long stretches."},
     {"q": "Can you go fishing on the Our River?", "a": "Yes, the Our is a popular spot for fly fishing."},
     {"q": "Which castle overlooks the Our Valley?", "a": "The famous Vianden Castle towers over the valley."},
     {"q": "Are there hydroelectric power plants on the Our?", "a": "Yes, the Vianden pumped-storage plant is one of the largest in Europe."},
     {"q": "What is the 'Our Valley' nature reserve?", "a": "A protected area with rare flora and fauna along the river."}]
)

add_faq("river-alzette-river",
    [{"q": "Durch welche zwei großen Städte fließt die Alzette?", "a": "Sie fließt durch Esch-sur-Alzette und Luxemburg-Stadt."},
     {"q": "In welchen Fluss mündet die Alzette schließlich?", "a": "Sie mündet bei Ettelbrück in die Sauer."},
     {"q": "Was ist das Besondere an der Alzette in Luxemburg-Stadt?", "a": "Sie hat tiefe Schluchten in den Sandstein gegraben, die das Stadtbild prägen."},
     {"q": "Gibt es Parks entlang der Alzette?", "a": "Ja, zum Beispiel das Pétrusse-Tal und die Gärten im Grund liegen an ihren Ufern."},
     {"q": "Wurde die Alzette früher industriell genutzt?", "a": "Ja, besonders im Süden für die Stahlindustrie war sie lebenswichtig."}],
    [{"q": "Melyik két nagy városon folyik keresztül az Alzette?", "a": "Esch-sur-Alzette-en és Luxemburg városon folyik át."},
     {"q": "Melyik folyóba torkollik végül az Alzette?", "a": "Ettelbrucknél ömlik a Sauer folyóba."},
     {"q": "Mi a különleges az Alzette folyóban Luxemburg városában?", "a": "Mély szurdokokat vájt a homokkőbe, amelyek meghatározzák a városképet."},
     {"q": "Vannak parkok az Alzette mentén?", "a": "Igen, például a Pétrusse-völgy és a Grund kertjei a partján találhatók."},
     {"q": "Használták korábban ipari célokra az Alzette-et?", "a": "Igen, különösen délen, az acélipar számára volt létfontosságú."}],
    [{"q": "Prin care două orașe mari curge râul Alzette?", "a": "Curge prin Esch-sur-Alzette și prin orașul Luxemburg."},
     {"q": "În ce râu se varsă în cele din urmă Alzette?", "a": "Se varsă în râul Sauer, lângă Ettelbruck."},
     {"q": "Ce este special la râul Alzette în orașul Luxemburg?", "a": "A săpat defilee adânci în gresie, care definesc peisajul urban."},
     {"q": "Există parcuri de-a lungul râului Alzette?", "a": "Da, de exemplu valea Pétrusse și grădinile din Grund sunt pe malurile sale."},
     {"q": "A fost râul Alzette folosit industrial în trecut?", "a": "Da, a fost vital în special în sud, pentru industria siderurgică."}],
    [{"q": "Which two major cities does the Alzette flow through?", "a": "It flows through Esch-sur-Alzette and Luxembourg City."},
     {"q": "Into which river does the Alzette finally flow?", "a": "It flows into the Sûre River near Ettelbruck."},
     {"q": "What is special about the Alzette in Luxembourg City?", "a": "It has carved deep gorges into the sandstone, which define the cityscape."},
     {"q": "Are there parks along the Alzette?", "a": "Yes, for example, the Pétrusse Valley and the gardens in the Grund lie on its banks."},
     {"q": "Was the Alzette used industrially in the past?", "a": "Yes, it was vital particularly in the south for the steel industry."}]
)

add_faq("river-clerve-river",
    [{"q": "An welchem bekannten Ort fließt die Clerve vorbei?", "a": "Sie fließt mitten durch die malerische Stadt Clerf (Clervaux)."},
     {"q": "Wo entspringt die Clerve?", "a": "Sie entspringt im Norden Luxemburgs, in der Nähe der belgischen Grenze."},
     {"q": "In welchen Fluss mündet die Clerve?", "a": "Sie ist ein Nebenfluss der Wiltz."},
     {"q": "Ist das Clerve-Tal gut zum Wandern geeignet?", "a": "Ja, es bietet wunderschöne, schattige Wege durch tiefe Wälder."},
     {"q": "Gibt es Burgen im Tal der Clerve?", "a": "Die Burg von Clerf ist die bekannteste Sehenswürdigkeit direkt am Fluss."}],
    [{"q": "Melyik ismert település mellett folyik el a Clerve?", "a": "Közvetlenül a festői Clervaux (Clerf) városán folyik keresztül."},
     {"q": "Hol ered a Clerve folyó?", "a": "Luxemburg északi részén, a belga határ közelében ered."},
     {"q": "Melyik folyóba torkollik a Clerve?", "a": "A Wiltz folyó mellékfolyója."},
     {"q": "Alkalmas a Clerve-völgy a túrázásra?", "a": "Igen, gyönyörű, árnyas utakat kínál a mély erdőkön keresztül."},
     {"q": "Vannak várak a Clerve völgyében?", "a": "A clervaux-i vár a legismertebb látnivaló közvetlenül a folyó partján."}],
    [{"q": "Pe lângă ce localitate cunoscută trece râul Clerve?", "a": "Trece chiar prin mijlocul pitorescului oraș Clervaux (Clerf)."},
     {"q": "Unde izvorăște râul Clerve?", "a": "Izvorăște în nordul Luxemburgului, aproape de granița cu Belgia."},
     {"q": "În ce râu se varsă Clerve?", "a": "Este un afluent al râului Wiltz."},
     {"q": "Este valea râului Clerve potrivită pentru drumeții?", "a": "Da, oferă poteci umbroase și frumoase prin păduri adânci."},
     {"q": "Există castele în valea râului Clerve?", "a": "Castelul din Clervaux este cel mai cunoscut obiectiv turistic situat chiar lângă râu."}],
    [{"q": "Which well-known town does the Clerve flow through?", "a": "It flows right through the picturesque town of Clervaux (Clerf)."},
     {"q": "Where does the Clerve originate?", "a": "It originates in northern Luxembourg, near the Belgian border."},
     {"q": "Into which river does the Clerve flow?", "a": "It is a tributary of the Wiltz River."},
     {"q": "Is the Clerve Valley suitable for hiking?", "a": "Yes, it offers beautiful, shaded paths through deep forests."},
     {"q": "Are there castles in the Clerve Valley?", "a": "The castle of Clervaux is the most famous sight directly on the river."}]
)

add_faq("lake-echternach-lake",
    [{"q": "Wann wurde der Echternacher See angelegt?", "a": "Der künstliche See wurde in den 1970er Jahren zu Erholungszwecken geschaffen."},
     {"q": "Was kann man auf dem See unternehmen?", "a": "Man kann Tretboot fahren, angeln oder den See auf einem 3,5 km langen Weg umrunden."},
     {"q": "Gibt es Sportmöglichkeiten am See?", "a": "Ja, es gibt Plätze für Minigolf, Skaten und ein großes Trampolin."},
     {"q": "Finden am Echternacher See Veranstaltungen statt?", "a": "Ja, zum Beispiel das Open-Air-Kino oder Musikfestivals wie das 'e-Lake'."},
     {"q": "Was ist das 'Adventure Island' am See?", "a": "Ein Bereich mit einem Hochseilgarten und verschiedenen Outdoor-Herausforderungen."}],
    [{"q": "Mikor hozták létre az Echternachi-tavat?", "a": "A mesterséges tavat az 1970-es években alakították ki üdülési célból."},
     {"q": "Milyen tevékenységeket lehet végezni a tavon?", "a": "Lehet vízibiciklizni, horgászni, vagy körbesétálni a tavat egy 3,5 km-es úton."},
     {"q": "Vannak sportolási lehetőségek a tónál?", "a": "Igen, van minigolf, görkorcsolya pálya és egy nagy trambulin is."},
     {"q": "Tartanak rendezvényeket az Echternachi-tónál?", "a": "Igen, például szabadtéri mozit vagy zenei fesztiválokat, mint az 'e-Lake'."},
     {"q": "Mi az 'Adventure Island' a tónál?", "a": "Egy terület kötélpályával és különböző szabadtéri kihívásokkal."}],
    [{"q": "Când a fost amenajat lacul Echternach?", "a": "Lacul artificial a fost creat în anii '70 în scopuri recreative."},
     {"q": "Ce activități se pot practica pe lac?", "a": "Se pot închiria hidrobiciclete, se poate pescui sau se poate face o plimbare de 3,5 km în jurul lacului."},
     {"q": "Există facilități sportive la lac?", "a": "Da, există terenuri de minigolf, patine cu rotile și o trambulină mare."},
     {"q": "Au loc evenimente la lacul Echternach?", "a": "Da, de exemplu cinema în aer liber sau festivaluri de muzică precum 'e-Lake'."},
     {"q": "Ce este 'Adventure Island' de la lac?", "a": "O zonă cu un parcurs de aventură la înălțime și diverse provocări în aer liber."}],
    [{"q": "When was the Echternach Lake created?", "a": "The artificial lake was created in the 1970s for recreational purposes."},
     {"q": "What can you do on the lake?", "a": "You can go pedalo boating, fishing, or walk around the lake on a 3.5 km path."},
     {"q": "Are there sports facilities at the lake?", "a": "Yes, there are spots for minigolf, skating, and a large trampoline."},
     {"q": "Are there events held at the Echternach Lake?", "a": "Yes, such as the open-air cinema or music festivals like 'e-Lake.'"},
     {"q": "What is 'Adventure Island' at the lake?", "a": "An area with a high ropes course and various outdoor challenges."}]
)

add_faq("mountain-berdorf-rocks",
    [{"q": "Darf man an den Berdorfer Felsen klettern?", "a": "Ja, es ist das einzige Gebiet in Luxemburg, in dem Sportklettern offiziell erlaubt ist."},
     {"q": "Was ist die 'Wanterbach'?", "a": "Der zentrale Sektor für Kletterer bei Berdorf."},
     {"q": "Braucht man eine Erlaubnis zum Klettern?", "a": "Ja, Nicht-Luxemburger müssen vorab eine Klettergenehmigung online beantragen."},
     {"q": "Welche Felsformation ist bei Wanderern besonders bekannt?", "a": "Der 'Priedegtstull', ein markanter Fels, der wie eine Kanzel aussieht."},
     {"q": "Wie sind die Felsen entstanden?", "a": "Sie bestehen aus luxemburgischem Sandstein, der vor Millionen von Jahren abgelagert wurde."}],
    [{"q": "Szabad mászni a berdorfi sziklákon?", "a": "Igen, ez az egyetlen terület Luxemburgban, ahol hivatalosan engedélyezett a sziklamászás."},
     {"q": "Mi az a 'Wanterbach'?", "a": "A Berdorf melletti sziklamászók központi szektora."},
     {"q": "Szükség van engedélyre a mászáshoz?", "a": "Igen, a nem luxemburgi lakosoknak előzetesen online mászóengedélyt kell kérniük."},
     {"q": "Melyik sziklaalakzat különösen ismert a túrázók körében?", "a": "A 'Priedegtstull' (Prédikálószék), egy jellegzetes, szószékre emlékeztető szikla."},
     {"q": "Hogyan keletkeztek a sziklák?", "a": "Luxemburgi homokkőből állnak, amely évmilliókkal ezelőtt rakódott le."}],
    [{"q": "Este permis alpinismul pe stâncile de la Berdorf?", "a": "Da, este singura zonă din Luxemburg unde alpinismul sportiv este permis oficial."},
     {"q": "Ce este 'Wanterbach'?", "a": "Sectorul central pentru alpiniști de lângă Berdorf."},
     {"q": "Este nevoie de permis pentru escaladă?", "a": "Da, persoanele care nu sunt rezidenți luxemburghezi trebuie să solicite online un permis de escaladă."},
     {"q": "Ce formațiune stâncoasă este cunoscută în mod special de drumeți?", "a": "'Priedegtstull', o stâncă marcată care arată ca un amvon."},
     {"q": "Cum s-au format aceste stânci?", "a": "Sunt compuse din gresie luxemburgheză, depusă cu milioane de ani în urmă."}],
    [{"q": "Is climbing allowed on the Berdorf rocks?", "a": "Yes, it is the only area in Luxembourg where sport climbing is officially permitted."},
     {"q": "What is the 'Wanterbach'?", "a": "The central sector for climbers near Berdorf."},
     {"q": "Do you need a permit for climbing?", "a": "Yes, non-residents of Luxembourg must apply for a climbing permit online in advance."},
     {"q": "Which rock formation is particularly well-known to hikers?", "a": "The 'Priedegtstull' (Preacher's Chair), a prominent rock that looks like a pulpit."},
     {"q": "How were the rocks formed?", "a": "They consist of Luxembourgish sandstone, deposited millions of years ago."}]
)

add_faq("mountain-gaalgebierg-hill",
    [{"q": "Wo befindet sich der Gaalgebierg?", "a": "Der Hügel liegt im Süden von Esch-sur-Alzette."},
     {"q": "Was kann man im Tierpark auf dem Gaalgebierg sehen?", "a": "Hauptsächlich heimische Wildtiere und Nutztiere wie Hirsche, Ziegen und Kaninchen."},
     {"q": "Gibt es Gärten auf dem Hügel?", "a": "Ja, es gibt wunderschöne Rosengärten und einen französischen Garten."},
     {"q": "Kann man auf dem Gaalgebierg Sport treiben?", "a": "Ja, es gibt Fußballfelder, Tennisplätze und eine Kunsteisbahn."},
     {"q": "Was bedeutet der Name 'Gaalgebierg'?", "a": "Es bedeutet 'Galgenberg', da sich dort im Mittelalter die Hinrichtungsstätte befand."}],
    [{"q": "Hol található a Gaalgebierg?", "a": "A domb Esch-sur-Alzette déli részén fekszik."},
     {"q": "Mit láthatunk a Gaalgebierg állatparkjában?", "a": "Főleg hazai vadon élő állatokat és háziállatokat, például szarvasokat, kecskéket és nyulakat."},
     {"q": "Vannak kertek a dombon?", "a": "Igen, gyönyörű rózsakertek és egy francia kert is található ott."},
     {"q": "Lehet sportolni a Gaalgebierg-en?", "a": "Igen, vannak futballpályák, teniszpályák és egy műjégpálya is."},
     {"q": "Mit jelent a 'Gaalgebierg' név?", "a": "Azt jelenti, 'Akasztófa-hegy', mivel a középkorban ott volt a kivégzőhely."}],
    [{"q": "Unde se află Gaalgebierg?", "a": "Dealul este situat în partea de sud a orașului Esch-sur-Alzette."},
     {"q": "Ce se poate vedea în parcul zoologic de pe Gaalgebierg?", "a": "În principal animale sălbatice locale și animale domestice, cum ar fi cerbi, capre și iepuri."},
     {"q": "Există grădini pe deal?", "a": "Da, există grădini de trandafiri superbe și o grădină franceză."},
     {"q": "Se pot practica sporturi pe Gaalgebierg?", "a": "Da, există terenuri de fotbal, terenuri de tenis și un patinoar artificial."},
     {"q": "Ce înseamnă numele 'Gaalgebierg'?", "a": "Înseamnă 'Dealul Spânzurătorii', deoarece acolo se afla locul de execuție în Evul Mediu."}],
    [{"q": "Where is the Gaalgebierg located?", "a": "The hill is situated in the south of Esch-sur-Alzette."},
     {"q": "What can you see in the animal park on Gaalgebierg?", "a": "Mainly local wildlife and farm animals such as deer, goats, and rabbits."},
     {"q": "Are there gardens on the hill?", "a": "Yes, there are beautiful rose gardens and a French garden."},
     {"q": "Can you do sports on Gaalgebierg?", "a": "Yes, there are football pitches, tennis courts, and an artificial ice rink."},
     {"q": "What does the name 'Gaalgebierg' mean?", "a": "It means 'Gallows Hill,' as the place of execution was located there in the Middle Ages."}]
)

with open('tmp/faqs_5.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
