import json

faqs = {}

def add_faq(id, de, hu, ro, en):
    faqs[id] = {
        "de": de,
        "hu": hu,
        "ro": ro,
        "en": en
    }

# Batch 2: 11-20
add_faq("cult-vianden",
    [{"q": "Wem gehörte die Burg Vianden ursprünglich?", "a": "Sie war der Sitz der mächtigen Grafen von Vianden."},
     {"q": "Ist die Burg Vianden vollständig erhalten?", "a": "Sie wurde nach einer Zeit des Verfalls im 20. Jahrhundert originalgetreu restauriert."},
     {"q": "Was ist die Kapelle der Burg?", "a": "Eine zweistöckige Kapelle, die als architektonisches Juwel gilt."},
     {"q": "Gibt es Führungen auf der Burg?", "a": "Ja, man kann die Burg mit Audioguides oder im Rahmen von Führungen erkunden."},
     {"q": "Welche Aussicht hat man von der Burg?", "a": "Man blickt direkt auf die Stadt Vianden und den Fluss Our."}],
    [{"q": "Kié volt eredetileg a Viandeni vár?", "a": "A hatalmas Vianden grófjainak székhelye volt."},
     {"q": "Teljesen épségben maradt a Viandeni vár?", "a": "A pusztulás időszaka után a 20. században hűen restaurálták."},
     {"q": "Mi a vár kápolnája?", "a": "Egy kétszintes kápolna, amelyet építészeti ékszernek tartanak."},
     {"q": "Vannak vezetett túrák a várban?", "a": "Igen, a vár audioguide-dal vagy vezetett túrák keretében is felfedezhető."},
     {"q": "Milyen kilátás nyílik a várból?", "a": "Közvetlenül Vianden városára és az Our folyóra nyílik kilátás."}],
    [{"q": "Cui a aparținut inițial Castelul Vianden?", "a": "A fost reședința puternicilor conți de Vianden."},
     {"q": "Este Castelul Vianden complet conservat?", "a": "A fost restaurat fidel în secolul al XX-lea, după o perioadă de degradare."},
     {"q": "Ce este capela castelului?", "a": "O capelă pe două niveluri, considerată o bijuterie arhitecturală."},
     {"q": "Există tururi ghidate la castel?", "a": "Da, castelul poate fi explorat cu audioghiduri sau în cadrul tururilor ghidate."},
     {"q": "Ce vedere ai de la castel?", "a": "Ai vedere directă spre orașul Vianden și râul Our."}],
    [{"q": "Who did Vianden Castle originally belong to?", "a": "It was the seat of the powerful Counts of Vianden."},
     {"q": "Is Vianden Castle fully preserved?", "a": "It was faithfully restored in the 20th century after a period of decay."},
     {"q": "What is the castle's chapel?", "a": "A two-story chapel considered an architectural gem."},
     {"q": "Are there guided tours at the castle?", "a": "Yes, you can explore the castle with audio guides or on guided tours."},
     {"q": "What view do you have from the castle?", "a": "You look directly over the town of Vianden and the Our River."}]
)

add_faq("cult-echternach",
    [{"q": "Was ist das Besondere an der Echternacher Buchmalerei?", "a": "Das Skriptorium der Abtei war im Mittelalter berühmt für seine prachtvollen Bibeln."},
     {"q": "Wo liegt der heilige Willibrord begraben?", "a": "Sein Grab befindet sich in der Krypta der St.-Willibrord-Basilika."},
     {"q": "Welches Museum ist im Abteigebäude untergebracht?", "a": "Das Abteimuseum dokumentiert die Geschichte des Klosters."},
     {"q": "Wann findet das Musikfestival in Echternach statt?", "a": "Das Internationale Musikfestival Echternach findet jährlich im Mai und Juni statt."},
     {"q": "Was ist das 'Trifolion'?", "a": "Ein modernes Kultur- und Kongresszentrum in Echternach."}],
    [{"q": "Mi a különleges az echternachi kódexfestészetben?", "a": "Az apátság szkriptóriuma a középkorban híres volt pompás Bibliáiról."},
     {"q": "Hol van eltemetve Szent Willibrord?", "a": "Sírja a Szent Willibrord-bazilika kriptájában található."},
     {"q": "Melyik múzeum kapott helyet az apátság épületében?", "a": "Az Apátsági Múzeum dokumentálja a kolostor történetét."},
     {"q": "Mikor tartják az echternachi zenei fesztivált?", "a": "Az Echternachi Nemzetközi Zenei Fesztivált évente májusban és júniusban rendezik meg."},
     {"q": "Mi az a 'Trifolion'?", "a": "Egy modern kulturális és kongresszusi központ Echternachban."}],
    [{"q": "Ce este special la manuscrisele iluminate din Echternach?", "a": "Scriptoriul abației a fost faimos în Evul Mediu pentru bibliile sale magnifice."},
     {"q": "Unde este înmormântat Sfântul Willibrord?", "a": "Mormântul său se află în cripta Bazilicii Sfântul Willibrord."},
     {"q": "Ce muzeu este găzduit în clădirea abației?", "a": "Muzeul Abației documentează istoria mănăstirii."},
     {"q": "Când are loc festivalul de muzică din Echternach?", "a": "Festivalul Internațional de Muzică Echternach are loc anual în mai și iunie."},
     {"q": "Ce este 'Trifolion'?", "a": "Un centru cultural și de congrese modern din Echternach."}],
    [{"q": "What is special about the Echternach illuminated manuscripts?", "a": "The abbey's scriptorium was famous in the Middle Ages for its magnificent Bibles."},
     {"q": "Where is St. Willibrord buried?", "a": "His tomb is located in the crypt of the St. Willibrord Basilica."},
     {"q": "Which museum is housed in the abbey building?", "a": "The Abbey Museum documents the history of the monastery."},
     {"q": "When does the music festival in Echternach take place?", "a": "The International Music Festival Echternach is held annually in May and June."},
     {"q": "What is the 'Trifolion'?", "a": "A modern cultural and congress center in Echternach."}]
)

add_faq("cult-schengen",
    [{"q": "Wo genau wurde das Schengener Abkommen unterzeichnet?", "a": "An Bord des Schiffes MS Princesse Marie-Astrid auf der Mosel."},
     {"q": "Gibt es Überreste der Berliner Mauer in Schengen?", "a": "Ja, ein Originalabschnitt steht als Denkmal vor dem Europäischen Museum."},
     {"q": "Was symbolisieren die drei Stahlstelen am Flussufer?", "a": "Sie stehen für Luxemburg, Frankreich und Deutschland, die Gründungsmitglieder des Abkommens."},
     {"q": "Gibt es ein Schloss in Schengen?", "a": "Ja, das Schloss Schengen stammt aus dem 19. Jahrhundert und hat einen Barockgarten."},
     {"q": "Welche Rolle spielt der Koch-Brunnen in Schengen?", "a": "Er ist ein Brunnen, der an die Tradition des Weinbaus erinnert."}],
    [{"q": "Pontosan hol írták alá a schengeni egyezményt?", "a": "Az MS Princesse Marie-Astrid hajó fedélzetén a Moselle folyón."},
     {"q": "Vannak a berlini falnak maradványai Schengenben?", "a": "Igen, egy eredeti szakasz áll emlékműként az Európai Múzeum előtt."},
     {"q": "Mit jelképez a folyóparton álló három acélsztélé?", "a": "Luxemburgot, Franciaországot és Németországot, az egyezmény alapító tagjait képviselik."},
     {"q": "Van kastély Schengenben?", "a": "Igen, a schengeni kastély a 19. századból származik, és barokk kertje van."},
     {"q": "Milyen szerepet játszik a Koch-kút Schengenben?", "a": "Ez egy kút, amely a borászati hagyományokra emlékeztet."}],
    [{"q": "Unde anume a fost semnat Acordul Schengen?", "a": "La bordul navei MS Princesse Marie-Astrid pe râul Mosela."},
     {"q": "Există resturi din Zidul Berlinului la Schengen?", "a": "Da, o secțiune originală stă ca monument în fața Muzeului European."},
     {"q": "Ce simbolizează cele trei stele de oțel de pe malul râului?", "a": "Ele reprezintă Luxemburg, Franța și Germania, membrii fondatori ai acordului."},
     {"q": "Există un castel în Schengen?", "a": "Da, Castelul Schengen datează din secolul al XIX-lea și are o grădină barocă."},
     {"q": "Ce rol joacă fântâna Koch în Schengen?", "a": "Este o fântână care amintește de tradiția viticulturii."}],
    [{"q": "Where exactly was the Schengen Agreement signed?", "a": "Aboard the ship MS Princesse Marie-Astrid on the Moselle River."},
     {"q": "Are there remains of the Berlin Wall in Schengen?", "a": "Yes, an original section stands as a monument in front of the European Museum."},
     {"q": "What do the three steel steles on the riverbank symbolize?", "a": "They represent Luxembourg, France, and Germany, the founding members of the agreement."},
     {"q": "Is there a castle in Schengen?", "a": "Yes, Schengen Castle dates from the 19th century and has a baroque garden."},
     {"q": "What role does the Koch fountain play in Schengen?", "a": "It is a fountain that commemorates the tradition of viticulture."}]
)

add_faq("nat-mullerthal",
    [{"q": "Was bedeutet der Name Müllerthal?", "a": "Es bedeutet 'Tal der Müller', da es früher viele Mühlen entlang der Flüsse gab."},
     {"q": "Welches Dorf gilt als Zentrum des Müllerthals?", "a": "Das Dorf Berdorf liegt zentral auf einem Hochplateau in der Region."},
     {"q": "Welche bekannten Felsspalten kann man hier durchwandern?", "a": "Die 'Rittergang' und 'Déiwepëtz' sind sehr schmale, dunkle Felsspalten."},
     {"q": "Wie heißt der Fluss, der den Schiessentümpel-Wasserfall speist?", "a": "Es ist die Schwarze Ernz."},
     {"q": "Gibt es im Müllerthal Möglichkeiten zum Klettern?", "a": "Ja, besonders die Felsen bei Berdorf sind bei Kletterern sehr beliebt."}],
    [{"q": "Mit jelent a Mullerthal név?", "a": "Azt jelenti, hogy 'Molnárok völgye', mivel régen sok malom volt a folyók mentén."},
     {"q": "Melyik falu számít a Mullerthal központjának?", "a": "Berdorf falu központi helyen, egy magas fennsíkon fekszik a régióban."},
     {"q": "Milyen ismert sziklahadakon lehet itt átgyalogolni?", "a": "A 'Rittergang' és a 'Déiwepëtz' nagyon szűk, sötét sziklahasadékok."},
     {"q": "Hogy hívják a Schiessentümpel-vízesést tápláló folyót?", "a": "A Fekete-Ernz folyó az."},
     {"q": "Vannak sziklamászási lehetőségek a Mullerthalban?", "a": "Igen, különösen a Berdorf környéki sziklák nagyon népszerűek a mászók körében."}],
    [{"q": "Ce înseamnă numele Mullerthal?", "a": "Înseamnă 'Valea Morarilor', deoarece existau multe mori de-a lungul râurilor."},
     {"q": "Care sat este considerat centrul regiunii Mullerthal?", "a": "Satul Berdorf este situat central pe un platou înalt în regiune."},
     {"q": "Ce crevase faimoase pot fi parcurse aici?", "a": "'Rittergang' și 'Déiwepëtz' sunt crevase foarte înguste și întunecate."},
     {"q": "Cum se numește râul care alimentează cascada Schiessentümpel?", "a": "Este Ernz Neagră."},
     {"q": "Există posibilități de alpinism în Mullerthal?", "a": "Da, în special stâncile de lângă Berdorf sunt foarte populare printre alpiniști."}],
    [{"q": "What does the name Mullerthal mean?", "a": "It means 'Millers' Valley,' as there used to be many mills along the rivers."},
     {"q": "Which village is considered the center of the Mullerthal?", "a": "The village of Berdorf is centrally located on a high plateau in the region."},
     {"q": "What famous rock crevices can you hike through here?", "a": "The 'Rittergang' and 'Déiwepëtz' are very narrow, dark rock crevices."},
     {"q": "What is the name of the river that feeds the Schiessentümpel waterfall?", "a": "It is the Black Ernz."},
     {"q": "Are there opportunities for rock climbing in Mullerthal?", "a": "Yes, especially the rocks near Berdorf are very popular with climbers."}]
)

add_faq("nat-ardennek-lu",
    [{"q": "Was ist das Ösling?", "a": "Das Ösling ist der lokale Name für das luxemburgische Ardennengebiet."},
     {"q": "Welcher große Stausee befindet sich in den Ardennen?", "a": "Der Obersauer-Stausee, ein wichtiges Trinkwasserreservoir und Erholungsgebiet."},
     {"q": "Wie ist das Klima in den Luxemburger Ardennen?", "a": "Es ist etwas rauer und kühler als im südlichen Gutland."},
     {"q": "Gibt es seltene Tiere in den Ardennen?", "a": "Ja, man kann Schwarzstörche, Rotwild und mit Glück Wildkatzen finden."},
     {"q": "Welche Burg ist das Tor zu den Ardennen im Norden?", "a": "Oft wird die Burg Clerf oder die Burg Wiltz als symbolisches Tor genannt."}],
    [{"q": "Mi az az Ösling?", "a": "Az Ösling a luxemburgi Ardennek területének helyi elnevezése."},
     {"q": "Melyik nagy víztározó tó található az Ardennekben?", "a": "A Felső-Sûre víztározó, amely fontos ivóvízbázis és üdülőhely."},
     {"q": "Milyen az éghajlat a luxemburgi Ardennekben?", "a": "Valamivel zordabb és hűvösebb, mint a déli Gutland régióban."},
     {"q": "Vannak ritka állatok az Ardennekben?", "a": "Igen, fekete gólyák, gímszarvasok és szerencsével vadmacskák is találhatók."},
     {"q": "Melyik vár az Ardennek kapuja északon?", "a": "Gyakran a clervaux-i vagy a wiltzi várat nevezik szimbolikus kapunak."}],
    [{"q": "Ce este Ösling?", "a": "Ösling este numele local pentru regiunea Ardenilor luxemburghezi."},
     {"q": "Ce lac mare de acumulare se află în Ardeni?", "a": "Lacul de acumulare Upper Sûre, un rezervor important de apă potabilă și zonă de recreere."},
     {"q": "Cum este clima în Ardenele luxemburgheze?", "a": "Este ceva mai aspră și mai răcoroasă decât în regiunea Gutland din sud."},
     {"q": "Există animale rare în Ardeni?", "a": "Da, se pot găsi berze negre, cerbi și, cu noroc, pisici sălbatice."},
     {"q": "Care castel este poarta către Ardeni în nord?", "a": "Adesea, castelul Clervaux sau castelul Wiltz sunt numite porți simbolice."}],
    [{"q": "What is the Ösling?", "a": "The Ösling is the local name for the Luxembourgish Ardennes region."},
     {"q": "What large reservoir lake is located in the Ardennes?", "a": "The Upper Sûre Lake, an important drinking water reservoir and recreation area."},
     {"q": "What is the climate like in the Luxembourg Ardennes?", "a": "It is somewhat harsher and cooler than in the southern Gutland region."},
     {"q": "Are there rare animals in the Ardennes?", "a": "Yes, you can find black storks, red deer, and with luck, wildcats."},
     {"q": "Which castle is the gateway to the Ardennes in the north?", "a": "Often Clervaux Castle or Wiltz Castle is called the symbolic gateway."}]
)

add_faq("nat-moselle",
    [{"q": "In welche Richtung fließt die Mosel in Luxemburg?", "a": "Sie fließt von Süden nach Norden entlang der ostluxemburgischen Grenze."},
     {"q": "Welche Weißweinsorte ist typisch für die Luxemburger Mosel?", "a": "Besonders Elbling, Rivaner und Auxerrois sind sehr typisch."},
     {"q": "Was ist die 'Wormer Koeppchen'?", "a": "Eine der berühmtesten und steilsten Weinbergslagen an der Mosel."},
     {"q": "Kann man auf der Mosel Schifffahrten machen?", "a": "Ja, es gibt regelmäßige Panoramafahrten zwischen Grevenmacher und Remich."},
     {"q": "Gibt es Radwege entlang des Flusses?", "a": "Ja, der Mosel-Radweg ist flach und sehr beliebt bei Familien."}],
    [{"q": "Melyik irányba folyik a Moselle Luxemburgban?", "a": "Délről északra folyik a kelet-luxemburgi határ mentén."},
     {"q": "Melyik fehérborfajta jellemző a luxemburgi Moselle-re?", "a": "Különösen az Elbling, a Rivaner és az Auxerrois nagyon jellemző."},
     {"q": "Mi az a 'Wormer Koeppchen'?", "a": "Az egyik leghíresebb és legmeredekebb szőlőültetvény a Moselle mentén."},
     {"q": "Lehet hajókázni a Moselle-en?", "a": "Igen, rendszeres sétahajók járnak Grevenmacher és Remich között."},
     {"q": "Vannak kerékpárutak a folyó mentén?", "a": "Igen, a Moselle-menti kerékpárút sík és nagyon népszerű a családok körében."}],
    [{"q": "În ce direcție curge râul Mosela în Luxemburg?", "a": "Curge de la sud la nord, de-a lungul graniței de est a Luxemburgului."},
     {"q": "Ce soi de vin alb este tipic pentru regiunea Mosela din Luxemburg?", "a": "În special Elbling, Rivaner și Auxerrois sunt foarte tipice."},
     {"q": "Ce este 'Wormer Koeppchen'?", "a": "Una dintre cele mai faimoase și abrupte podgorii de pe malul Moselei."},
     {"q": "Se pot face croaziere pe Mosela?", "a": "Da, există curse regulate între Grevenmacher și Remich."},
     {"q": "Există piste de biciclete de-a lungul râului?", "a": "Da, pista de biciclete de pe malul Moselei este plană și populară printre familii."}],
    [{"q": "In which direction does the Moselle flow in Luxembourg?", "a": "It flows from south to north along the eastern Luxembourgish border."},
     {"q": "Which white wine variety is typical for the Luxembourg Moselle?", "a": "Elbling, Rivaner, and Auxerrois are particularly typical."},
     {"q": "What is the 'Wormer Koeppchen'?", "a": "One of the most famous and steepest vineyard sites on the Moselle."},
     {"q": "Can you take boat trips on the Moselle?", "a": "Yes, there are regular panoramic boat tours between Grevenmacher and Remich."},
     {"q": "Are there cycling paths along the river?", "a": "Yes, the Moselle cycling path is flat and very popular with families."}]
)

add_faq("city-bourscheid",
    [{"q": "Wie hoch liegt die Burg Bourscheid?", "a": "Sie thront auf einem Felsen etwa 150 Meter über der Sauer."},
     {"q": "Kann man die Burg Bourscheid besichtigen?", "a": "Ja, sie ist ganzjährig für Besucher geöffnet."},
     {"q": "Wann wurde die Burg Bourscheid zum ersten Mal erwähnt?", "a": "Die erste urkundliche Erwähnung stammt aus dem Jahr 1095."},
     {"q": "Gibt es in Bourscheid Übernachtungsmöglichkeiten?", "a": "Ja, es gibt mehrere Hotels und Campingplätze mit Blick auf die Burg."},
     {"q": "Was ist der 'Gringlee'?", "a": "Ein bekannter Aussichtspunkt, von dem man einen tollen Blick auf die Burg Bourscheid hat."}],
    [{"q": "Milyen magasan fekszik a bourscheidi vár?", "a": "Egy sziklán trónol, körülbelül 150 méterrel a Sauer folyó felett."},
     {"q": "Látogatható a bourscheidi vár?", "a": "Igen, egész évben nyitva áll a látogatók előtt."},
     {"q": "Mikor említették először a bourscheidi várat?", "a": "Az első írásos említése 1095-ből származik."},
     {"q": "Vannak szálláslehetőségek Bourscheidban?", "a": "Igen, több szálloda és kemping is található, kilátással a várra."},
     {"q": "Mi az a 'Gringlee'?", "a": "Egy ismert kilátópont, ahonnan remek kilátás nyílik a bourscheidi várra."}],
    [{"q": "La ce înălțime se află Castelul Bourscheid?", "a": "Se află pe o stâncă, la aproximativ 150 de metri deasupra râului Sauer."},
     {"q": "Se poate vizita Castelul Bourscheid?", "a": "Da, este deschis vizitatorilor pe tot parcursul anului."},
     {"q": "Când a fost menționat pentru prima dată Castelul Bourscheid?", "a": "Prima mențiune documentară datează din anul 1095."},
     {"q": "Există posibilități de cazare în Bourscheid?", "a": "Da, există mai multe hoteluri și campinguri cu vedere la castel."},
     {"q": "Ce este 'Gringlee'?", "a": "Un punct de belvedere cunoscut, de unde se oferă o vedere superbă asupra Castelului Bourscheid."}],
    [{"q": "How high is Bourscheid Castle located?", "a": "It perches on a rock about 150 meters above the Sûre River."},
     {"q": "Can Bourscheid Castle be visited?", "a": "Yes, it is open to visitors year-round."},
     {"q": "When was Bourscheid Castle first mentioned?", "a": "The first documentary mention dates back to 1095."},
     {"q": "Are there places to stay in Bourscheid?", "a": "Yes, there are several hotels and campsites with views of the castle."},
     {"q": "What is the 'Gringlee'?", "a": "A well-known viewpoint that offers a great view of Bourscheid Castle."}]
)

add_faq("city-berdorf",
    [{"q": "Warum ist Berdorf bei Wanderern so beliebt?", "a": "Es liegt direkt an den spektakulärsten Felsformationen des Müllerthals."},
     {"q": "Was ist der 'Berdorfer Käse'?", "a": "Ein regional bekannter Käse, der direkt im Dorf in einer lokalen Käserei hergestellt wird."},
     {"q": "Wie heißt der hölzerne Aussichtsturm bei Berdorf?", "a": "Der Aquatower bietet eine tolle Aussicht, aber es gibt auch hölzerne Aussichtspunkte wie den 'Priedegtstull'."},
     {"q": "Welche sportliche Aktivität ist in Berdorf weltberühmt?", "a": "Berdorf ist das wichtigste Klettergebiet Luxemburgs."},
     {"q": "Gibt es ein Amphitheater in Berdorf?", "a": "Ja, das 'Breechkaul' ist ein natürliches Fels-Amphitheater, in dem Konzerte stattfinden."}],
    [{"q": "Miért olyan népszerű Berdorf a túrázók körében?", "a": "Közvetlenül a Mullerthal leglátványosabb sziklaalakzatai mellett fekszik."},
     {"q": "Mi az a 'Berdorfer sajt'?", "a": "Egy regionálisan ismert sajt, amelyet közvetlenül a faluban, egy helyi sajtüzemben készítenek."},
     {"q": "Hogy hívják a Berdorf melletti kilátót?", "a": "Az Aquatower remek kilátást nyújt, de vannak fából készült kilátópontok is, mint a 'Priedegtstull'."},
     {"q": "Milyen sporttevékenység világhírű Berdorfban?", "a": "Berdorf Luxemburg legfontosabb sziklamászó helye."},
     {"q": "Van amfiteátrum Berdorfban?", "a": "Igen, a 'Breechkaul' egy természetes szikla-amfiteátrum, ahol koncerteket is tartanak."}],
    [{"q": "De ce este Berdorf atât de popular printre drumeți?", "a": "Este situat direct lângă cele mai spectaculoase formațiuni stâncoase din Mullerthal."},
     {"q": "Ce este 'brânza Berdorfer'?", "a": "O brânză cunoscută la nivel regional, produsă chiar în sat, la o lăptărie locală."},
     {"q": "Cum se numește turnul de belvedere de lângă Berdorf?", "a": "Aquatower oferă o vedere minunată, dar există și puncte de belvedere din lemn, cum ar fi 'Priedegtstull'."},
     {"q": "Ce activitate sportivă este faimoasă în Berdorf?", "a": "Berdorf este cea mai importantă zonă de alpinism din Luxemburg."},
     {"q": "Există un amfiteatru în Berdorf?", "a": "Da, 'Breechkaul' este un amfiteatru natural din stâncă unde au loc concerte."}],
    [{"q": "Why is Berdorf so popular with hikers?", "a": "It is located directly next to the most spectacular rock formations in the Mullerthal."},
     {"q": "What is 'Berdorfer cheese'?", "a": "A regionally famous cheese produced directly in the village at a local dairy."},
     {"q": "What is the name of the observation tower near Berdorf?", "a": "The Aquatower offers a great view, but there are also wooden viewpoints like the 'Priedegtstull.'"},
     {"q": "What sporting activity is world-famous in Berdorf?", "a": "Berdorf is the most important rock-climbing area in Luxembourg."},
     {"q": "Is there an amphitheater in Berdorf?", "a": "Yes, the 'Breechkaul' is a natural rock amphitheater where concerts are held."}]
)

add_faq("city-beaufort",
    [{"q": "Wie viele Burgen gibt es in Befort?", "a": "Es gibt zwei: die Ruine der mittelalterlichen Burg und das Renaissance-Schloss."},
     {"q": "Was ist 'Cassero'?", "a": "Ein schwarzer Johannisbeerlikör, der auf dem Schloss Befort hergestellt wird."},
     {"q": "Kann man das Renaissance-Schloss von innen sehen?", "a": "Ja, es gibt geführte Touren durch die Innenräume des Schlosses."},
     {"q": "Wann wurde die mittelalterliche Burg von Befort erbaut?", "a": "Der Bau begann um das Jahr 1150."},
     {"q": "Gibt es Wanderwege, die in Befort starten?", "a": "Ja, mehrere Schleifen des Müllerthal Trails führen durch Befort."}],
    [{"q": "Hány vár van Beaufortban?", "a": "Kettő: a középkori vár romja és a reneszánsz kastély."},
     {"q": "Mi az a 'Cassero'?", "a": "Egy feketeribizli-likőr, amelyet a beauforti várban készítenek."},
     {"q": "Megtekinthető belülről a reneszánsz kastély?", "a": "Igen, vezetett túrák indulnak a kastély belső termeibe."},
     {"q": "Mikor épült a beauforti középkori vár?", "a": "Az építkezés 1150 körül kezdődött."},
     {"q": "Indulnak túraútvonalak Beaufortból?", "a": "Igen, a Mullerthal Trail több szakasza is áthalad Beauforton."}],
    [{"q": "Câte castele există în Beaufort?", "a": "Există două: ruina castelului medieval și palatul renascentist."},
     {"q": "Ce este 'Cassero'?", "a": "Un lichior de coacăze negre produs la castelul Beaufort."},
     {"q": "Se poate vizita interiorul palatului renascentist?", "a": "Da, există tururi ghidate prin camerele interioare ale palatului."},
     {"q": "Când a fost construit castelul medieval din Beaufort?", "a": "Construcția a început în jurul anului 1150."},
     {"q": "Există trasee de drumeție care pornesc din Beaufort?", "a": "Da, mai multe bucle ale Mullerthal Trail trec prin Beaufort."}],
    [{"q": "How many castles are there in Beaufort?", "a": "There are two: the ruins of the medieval castle and the Renaissance palace."},
     {"q": "What is 'Cassero'?", "a": "A blackcurrant liqueur produced at Beaufort Castle."},
     {"q": "Can you see the inside of the Renaissance palace?", "a": "Yes, there are guided tours of the castle's interior rooms."},
     {"q": "When was the medieval castle of Beaufort built?", "a": "Construction began around the year 1150."},
     {"q": "Are there hiking trails that start in Beaufort?", "a": "Yes, several loops of the Mullerthal Trail pass through Beaufort."}]
)

add_faq("city-clervaux",
    [{"q": "Welche berühmte Fotoausstellung ist in Clerf zu Hause?", "a": "Die Ausstellung 'The Family of Man' von Edward Steichen."},
     {"q": "Wozu dient die Benediktinerabtei in Clerf heute?", "a": "Sie ist ein aktives Kloster, in dem Mönche leben und arbeiten."},
     {"q": "Was zeigt das Museum der Ardennenoffensive in der Burg?", "a": "Es dokumentiert die heftigen Kämpfe im Winter 1944-1945 in der Region."},
     {"q": "Wie heißt die Kirche mit den zwei markanten Türmen in Clerf?", "a": "Die Pfarrkirche St. Cosmas und Damian."},
     {"q": "Gibt es ein Museum für Burgenmodelle in Clerf?", "a": "Ja, in der Burg gibt es eine Ausstellung mit Modellen der wichtigsten Luxemburger Burgen."}],
    [{"q": "Melyik híres fotókiállítás található Clervaux-ban?", "a": "Edward Steichen 'The Family of Man' (Az ember családja) című kiállítása."},
     {"q": "Mire szolgál ma a clervaux-i bencés apátság?", "a": "Aktív kolostor, ahol szerzetesek élnek és dolgoznak."},
     {"q": "Mit mutat be az ardenneki offenzíva múzeuma a várban?", "a": "A régióban 1944-1945 telén zajlott heves harcokat dokumentálja."},
     {"q": "Hogy hívják a két jellegzetes tornyú templomot Clervaux-ban?", "a": "A Szent Kozma és Damján plébániatemplom."},
     {"q": "Van vármaketteket bemutató múzeum Clervaux-ban?", "a": "Igen, a várban található egy kiállítás a legfontosabb luxemburgi várak makettjeiből."}],
    [{"q": "Ce expoziție fotografică celebră se află la Clervaux?", "a": "Expoziția 'The Family of Man' de Edward Steichen."},
     {"q": "La ce servește astăzi abația benedictină din Clervaux?", "a": "Este o mănăstire activă unde călugării trăiesc și lucrează."},
     {"q": "Ce prezintă Muzeul Ofensivei din Ardeni din castel?", "a": "Documentează luptele grele din iarna 1944-1945 din regiune."},
     {"q": "Cum se numește biserica cu cele două turnuri distinctive din Clervaux?", "a": "Biserica parohială Sfinții Cosma și Damian."},
     {"q": "Există un muzeu de machete ale castelelor în Clervaux?", "a": "Da, în castel există o expoziție cu machete ale celor mai importante castele din Luxemburg."}],
    [{"q": "What famous photo exhibition is housed in Clervaux?", "a": "The 'Family of Man' exhibition by Edward Steichen."},
     {"q": "What is the Benedictine Abbey in Clervaux used for today?", "a": "It is an active monastery where monks live and work."},
     {"q": "What does the Battle of the Bulge Museum in the castle show?", "a": "It documents the fierce fighting in the region during the winter of 1944-1945."},
     {"q": "What is the name of the church with the two distinctive towers in Clervaux?", "a": "The Parish Church of St. Cosmas and Damian."},
     {"q": "Is there a museum for castle models in Clervaux?", "a": "Yes, the castle houses an exhibition of models of the most important Luxembourgish castles."}]
)

with open('tmp/faqs_2.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
