import json

faqs = {}

def add_faq(id, de, hu, ro, en):
    faqs[id] = {
        "de": de,
        "hu": hu,
        "ro": ro,
        "en": en
    }

# Batch 4: 31-40
add_faq("city-strassen",
    [{"q": "Was ist das 'Les Thermes' in Strassen?", "a": "Ein großes, futuristisch gestaltetes Wasser- und Wellnesszentrum."},
     {"q": "An welche Stadt grenzt Strassen direkt?", "a": "Es grenzt unmittelbar an den Westen der Hauptstadt Luxemburg."},
     {"q": "Gibt es Parks in Strassen?", "a": "Ja, der Riedgen-Park ist eine grüne Oase in der Gemeinde."},
     {"q": "Welche wichtige Straße führt durch Strassen?", "a": "Die Route d'Arlon (N6) verbindet Strassen mit dem Stadtzentrum."},
     {"q": "Ist Strassen eine internationale Gemeinde?", "a": "Ja, sie hat einen sehr hohen Anteil an ausländischen Mitbürgern aus aller Welt."}],
    [{"q": "Mi az a 'Les Thermes' Strassenben?", "a": "Egy nagy, futurisztikus kialakítású vízi- és wellnessközpont."},
     {"q": "Melyik várossal határos közvetlenül Strassen?", "a": "Közvetlenül a főváros, Luxemburg nyugati részével határos."},
     {"q": "Vannak parkok Strassenben?", "a": "Igen, a Riedgen-park egy zöld oázis a községben."},
     {"q": "Melyik fontos út halad át Strassenen?", "a": "A Route d'Arlon (N6) köti össze Strassent a városközponttal."},
     {"q": "Strassen nemzetközi község?", "a": "Igen, nagyon magas a világ minden tájáról érkező külföldi lakosok aránya."}],
    [{"q": "Ce este 'Les Thermes' din Strassen?", "a": "Un centru mare de wellness și activități acvatice, cu un design futurist."},
     {"q": "Cu ce oraș se învecinează direct Strassen?", "a": "Se învecinează direct cu partea de vest a capitalei Luxemburg."},
     {"q": "Există parcuri în Strassen?", "a": "Da, Parcul Riedgen este o oază de verdeață în comună."},
     {"q": "Ce drum important trece prin Strassen?", "a": "Route d'Arlon (N6) leagă Strassen de centrul orașului."},
     {"q": "Este Strassen o comună internațională?", "a": "Da, are o proporție foarte mare de rezidenți străini din întreaga lume."}],
    [{"q": "What is 'Les Thermes' in Strassen?", "a": "A large, futuristically designed water and wellness center."},
     {"q": "Which city does Strassen border directly?", "a": "It borders the western part of Luxembourg City directly."},
     {"q": "Are there parks in Strassen?", "a": "Yes, Riedgen Park is a green oasis in the municipality."},
     {"q": "Which important road passes through Strassen?", "a": "The Route d'Arlon (N6) connects Strassen with the city center."},
     {"q": "Is Strassen an international municipality?", "a": "Yes, it has a very high proportion of foreign residents from all over the world."}]
)

add_faq("city-mamer",
    [{"q": "Welcher berühmte Olympiasieger wurde in Mamer geboren?", "a": "Josy Barthel, der 1952 Gold über 1500 Meter gewann."},
     {"q": "Was ist das 'Mamer Lycée'?", "a": "Ein moderner Schulcampus am Rande von Mamer."},
     {"q": "Gibt es ein Schloss in Mamer?", "a": "Ja, das Mamer Schloss (Mamer Schlass) beherbergt heute das Rathaus."},
     {"q": "Was ist der 'Parc Brill'?", "a": "Ein beliebter Freizeit- und Erholungspark im Zentrum von Mamer."},
     {"q": "Welches kulturelle Zentrum gibt es in Mamer?", "a": "Das Kulturzentrum 'Kinneksbond'."}],
    [{"q": "Melyik híres olimpiai bajnok született Mamerben?", "a": "Josy Barthel, aki 1952-ben aranyérmet nyert 1500 méteres síkfutásban."},
     {"q": "Mi az a 'Mamer Lycée'?", "a": "Egy modern iskolai campus Mamer szélén."},
     {"q": "Van kastély Mamerben?", "a": "Igen, a mameri kastély (Mamer Schlass) ma a polgármesteri hivatalnak ad otthont."},
     {"q": "Mi az a 'Parc Brill'?", "a": "Egy népszerű szabadidő- és pihenőpark Mamer központjában."},
     {"q": "Milyen kulturális központ található Mamerben?", "a": "A 'Kinneksbond' kulturális központ."}],
    [{"q": "Ce campion olimpic celebru s-a născut în Mamer?", "a": "Josy Barthel, care a câștigat aurul la 1500 de metri în 1952."},
     {"q": "Ce este 'Mamer Lycée'?", "a": "Un campus școlar modern la marginea orașului Mamer."},
     {"q": "Există un castel în Mamer?", "a": "Da, Castelul Mamer (Mamer Schlass) găzduiește astăzi primăria."},
     {"q": "Ce este 'Parc Brill'?", "a": "Un parc popular de recreere și petrecere a timpului liber în centrul orașului Mamer."},
     {"q": "Ce centru cultural există în Mamer?", "a": "Centrul cultural 'Kinneksbond'."}],
    [{"q": "What famous Olympic champion was born in Mamer?", "a": "Josy Barthel, who won gold in the 1500 meters in 1952."},
     {"q": "What is the 'Mamer Lycée'?", "a": "A modern school campus on the outskirts of Mamer."},
     {"q": "Is there a castle in Mamer?", "a": "Yes, Mamer Castle (Mamer Schlass) now houses the town hall."},
     {"q": "What is 'Parc Brill'?", "a": "A popular leisure and recreation park in the center of Mamer."},
     {"q": "Which cultural center is located in Mamer?", "a": "The 'Kinneksbond' cultural center."}]
)

add_faq("city-hesperange",
    [{"q": "Gibt es eine Burgruine in Hesperingen?", "a": "Ja, die Ruine der Burg Hesperingen dominiert den Ortskern."},
     {"q": "Welcher große Park liegt in Hesperingen?", "a": "Der Hesper-Park ist ein weitläufiges Gelände mit Spielplätzen und Wanderwegen."},
     {"q": "Welcher Fluss fließt durch Hesperingen?", "a": "Die Alzette fließt mitten durch die Gemeinde."},
     {"q": "Gibt es ein bekanntes Einkaufszentrum in der Nähe?", "a": "Das Gewerbegebiet Howald gehört zur Gemeinde und bietet viele Geschäfte."},
     {"q": "Welcher Hügel bietet eine gute Aussicht auf die Region?", "a": "Der 'Holleschbierg' beherbergt Sport- und Freizeitanlagen."}],
    [{"q": "Van várrom Hesperange-ban?", "a": "Igen, a hesperange-i vár romjai uralják a település központját."},
     {"q": "Melyik nagy park található Hesperange-ban?", "a": "A Hesper-park egy kiterjedt terület játszóterekkel és sétányokkal."},
     {"q": "Melyik folyó folyik át Hesperange-on?", "a": "Az Alzette folyik át a község közepén."},
     {"q": "Van ismert bevásárlóközpont a közelben?", "a": "A Howald üzleti negyed a községhez tartozik, és számos üzletet kínál."},
     {"q": "Melyik dombról nyílik jó kilátás a régióra?", "a": "A 'Holleschbierg' sport- és szabadidős létesítményeknek ad otthont."}],
    [{"q": "Există o ruină de castel în Hesperange?", "a": "Da, ruinele castelului Hesperange domină centrul localității."},
     {"q": "Ce parc mare se află în Hesperange?", "a": "Parcul Hesper este o zonă vastă cu terenuri de joacă și poteci de plimbare."},
     {"q": "Ce râu trece prin Hesperange?", "a": "Râul Alzette curge chiar prin mijlocul comunei."},
     {"q": "Există vreun centru comercial cunoscut în apropiere?", "a": "Zona comercială Howald aparține de comună și oferă multe magazine."},
     {"q": "Ce deal oferă o vedere bună asupra regiunii?", "a": "Pe 'Holleschbierg' se află facilități sportive și de recreere."}],
    [{"q": "Is there a castle ruin in Hesperange?", "a": "Yes, the ruins of Hesperange Castle dominate the center of the village."},
     {"q": "What large park is located in Hesperange?", "a": "Hesper Park is a vast area with playgrounds and walking paths."},
     {"q": "Which river flows through Hesperange?", "a": "The Alzette flows right through the municipality."},
     {"q": "Is there a well-known shopping area nearby?", "a": "The Howald commercial zone belongs to the municipality and offers many shops."},
     {"q": "Which hill offers a good view of the region?", "a": "The 'Holleschbierg' hosts sports and leisure facilities."}]
)

add_faq("city-betzdorf",
    [{"q": "Welches große Technologieunternehmen hat seinen Sitz in Betzdorf?", "a": "SES, einer der weltweit führenden Satellitenbetreiber."},
     {"q": "Was ist das Schloss Betzdorf heute?", "a": "Es dient als Hauptsitz des Satellitenbetreibers SES."},
     {"q": "Gibt es ein Institut für Astronomie in der Nähe?", "a": "Die Satellitenstation SES Astra ist ein technologisches Highlight."},
     {"q": "Wofür ist die Region um Betzdorf landschaftlich bekannt?", "a": "Für ihre sanften Hügel und landwirtschaftlichen Flächen im Osten des Landes."},
     {"q": "Welche anderen Dörfer gehören zur Gemeinde Betzdorf?", "a": "Dazu gehören Berg, Biwer (teilweise), Mensdorf und Roodt-sur-Syre."}],
    [{"q": "Melyik nagy technológiai vállalat székhelye van Betzdorfban?", "a": "Az SES, a világ egyik vezető műholdüzemeltetője."},
     {"q": "Mi ma a betzdorfi kastély?", "a": "Az SES műholdüzemeltető központjaként szolgál."},
     {"q": "Van csillagászati intézet a közelben?", "a": "Az SES Astra műholdas állomás technológiai fénypont."},
     {"q": "Miről ismert a Betzdorf környéki táj?", "a": "Az ország keleti részén fekvő lankás dombjairól és mezőgazdasági területeiről."},
     {"q": "Mely más falvak tartoznak Betzdorf községhez?", "a": "Ide tartozik Berg, Biwer (részben), Mensdorf és Roodt-sur-Syre."}],
    [{"q": "Ce mare companie tehnologică își are sediul în Betzdorf?", "a": "SES, unul dintre cei mai importanți operatori de sateliți din lume."},
     {"q": "Ce este astăzi Castelul Betzdorf?", "a": "Servește ca sediu central al operatorului de sateliți SES."},
     {"q": "Există vreun institut de astronomie în apropiere?", "a": "Stația de sateliți SES Astra este un reper tehnologic."},
     {"q": "Pentru ce este cunoscut peisajul din jurul Betzdorf?", "a": "Pentru dealurile sale blânde și zonele agricole din estul țării."},
     {"q": "Ce alte sate aparțin de comuna Betzdorf?", "a": "Printre acestea se numără Berg, Biwer (parțial), Mensdorf și Roodt-sur-Syre."}],
    [{"q": "Which major technology company is based in Betzdorf?", "a": "SES, one of the world's leading satellite operators."},
     {"q": "What is Betzdorf Castle today?", "a": "It serves as the headquarters of the satellite operator SES."},
     {"q": "Is there an institute for astronomy nearby?", "a": "The SES Astra satellite station is a technological highlight."},
     {"q": "What is the landscape around Betzdorf known for?", "a": "For its rolling hills and agricultural areas in the east of the country."},
     {"q": "Which other villages belong to the Betzdorf municipality?", "a": "These include Berg, Biwer (partially), Mensdorf, and Roodt-sur-Syre."}]
)

add_faq("city-biwer",
    [{"q": "Wie heißt der Bach, der durch Biwer fließt?", "a": "Die Biwerbach, die später in die Syre mündet."},
     {"q": "Ist Biwer eine ländliche Gemeinde?", "a": "Ja, sie ist geprägt von Landwirtschaft und einer ruhigen Umgebung."},
     {"q": "Welche Bahnstrecke führt durch Biwer?", "a": "Die Strecke Luxemburg-Wasserbillig führt durch das Gemeindegebiet."},
     {"q": "Gibt es Wanderwege in Biwer?", "a": "Ja, es gibt mehrere lokale Wanderwege durch die umliegenden Felder und Wälder."},
     {"q": "Wo befindet sich das Kulturzentrum in Biwer?", "a": "Das 'Centre Culturel' befindet sich im Herzen des Dorfes."}],
    [{"q": "Hogy hívják a Biweren átfolyó patakot?", "a": "A Biwerbach, amely később a Syre folyóba torkollik."},
     {"q": "Biwer egy vidéki község?", "a": "Igen, a mezőgazdaság és a nyugodt környezet jellemzi."},
     {"q": "Melyik vasútvonal halad át Biweren?", "a": "A Luxemburg-Wasserbillig vasútvonal halad át a község területén."},
     {"q": "Vannak túraútvonalak Biwerben?", "a": "Igen, számos helyi túraútvonal vezet át a környező szántóföldeken és erdőkön."},
     {"q": "Hol található a kulturális központ Biwerben?", "a": "A 'Centre Culturel' a falu szívében található."}],
    [{"q": "Cum se numește pârâul care trece prin Biwer?", "a": "Biwerbach, care se varsă ulterior în râul Syre."},
     {"q": "Este Biwer o comună rurală?", "a": "Da, este caracterizată prin agricultură și un mediu liniștit."},
     {"q": "Ce linie de cale ferată trece prin Biwer?", "a": "Linia Luxemburg-Wasserbillig traversează teritoriul comunei."},
     {"q": "Există trasee de drumeție în Biwer?", "a": "Da, există mai multe trasee locale prin câmpurile și pădurile din jur."},
     {"q": "Unde se află centrul cultural din Biwer?", "a": "'Centre Culturel' se află în inima satului."}],
    [{"q": "What is the name of the stream that flows through Biwer?", "a": "The Biwerbach, which later flows into the Syre."},
     {"q": "Is Biwer a rural municipality?", "a": "Yes, it is characterized by agriculture and a peaceful environment."},
     {"q": "Which railway line passes through Biwer?", "a": "The Luxembourg-Wasserbillig line passes through the municipal area."},
     {"q": "Are there hiking trails in Biwer?", "a": "Yes, there are several local trails through the surrounding fields and forests."},
     {"q": "Where is the cultural center located in Biwer?", "a": "The 'Centre Culturel' is located in the heart of the village."}]
)

add_faq("city-petange",
    [{"q": "Warum war Petingen historisch für die Industrie wichtig?", "a": "Es war ein bedeutender Knotenpunkt für den Eisenerztransport per Bahn."},
     {"q": "Was ist der 'Prënzebierg' bei Petingen?", "a": "Ein Naturschutzgebiet und ehemaliges Tagebaugebiet mit tollen Ausblicken."},
     {"q": "Gibt es ein Museum für Züge in der Nähe?", "a": "Ja, der 'Train 1900' verkehrt zwischen Petingen und Fond-de-Gras."},
     {"q": "Welche drei Länder treffen in der Nähe von Petingen zusammen?", "a": "Luxemburg, Belgien und Frankreich (bei Rodange)."},
     {"q": "Was ist das 'Pétange-Athus' Projekt?", "a": "Ein grenzüberschreitendes Logistik- und Industriezentrum."}],
    [{"q": "Miért volt Pétange történelmileg fontos az ipar számára?", "a": "A vasérc vasúti szállításának jelentős csomópontja volt."},
     {"q": "Mi az a 'Prënzebierg' Pétange mellett?", "a": "Természetvédelmi terület és egykori külszíni bányaterület remek kilátással."},
     {"q": "Van vonatokat bemutató múzeum a közelben?", "a": "Igen, a 'Train 1900' közlekedik Pétange és Fond-de-Gras között."},
     {"q": "Melyik három ország találkozik Pétange közelében?", "a": "Luxemburg, Belgium és Franciaország (Rodange-nál)."},
     {"q": "Mi az a 'Pétange-Athus' projekt?", "a": "Egy határokon átnyúló logisztikai és ipari központ."}],
    [{"q": "De ce a fost Pétange important din punct de vedere istoric pentru industrie?", "a": "A fost un nod important pentru transportul feroviar de minereu de fier."},
     {"q": "Ce este 'Prënzebierg' de lângă Pétange?", "a": "O rezervație naturală și fostă zonă minieră de suprafață, cu vederi superbe."},
     {"q": "Există un muzeu al trenurilor în apropiere?", "a": "Da, 'Train 1900' circulă între Pétange și Fond-de-Gras."},
     {"q": "Care trei țări se întâlnesc în apropiere de Pétange?", "a": "Luxemburg, Belgia și Franța (lângă Rodange)."},
     {"q": "Ce este proiectul 'Pétange-Athus'?", "a": "Un centru logistic și industrial transfrontalier."}],
    [{"q": "Why was Pétange historically important for industry?", "a": "It was a major hub for transporting iron ore by rail."},
     {"q": "What is the 'Prënzebierg' near Pétange?", "a": "A nature reserve and former open-cast mining area with great views."},
     {"q": "Is there a museum for trains nearby?", "a": "Yes, the 'Train 1900' operates between Pétange and Fond-de-Gras."},
     {"q": "Which three countries meet near Pétange?", "a": "Luxembourg, Belgium, and France (near Rodange)."},
     {"q": "What is the 'Pétange-Athus' project?", "a": "A cross-border logistics and industrial center."}]
)

add_faq("historical-echternach-basilica",
    [{"q": "Was ist in der Krypta der Basilika zu sehen?", "a": "Das prachtvolle Marmorgrab des heiligen Willibrord."},
     {"q": "Wann wurde die aktuelle Basilika gebaut?", "a": "Die heutige romanische Kirche stammt größtenteils aus dem 11. Jahrhundert."},
     {"q": "Wurde die Basilika im Zweiten Weltkrieg beschädigt?", "a": "Ja, sie wurde 1944 fast vollständig zerstört und danach wieder aufgebaut."},
     {"q": "Was ist das Besondere am 'Evangeliar von Echternach'?", "a": "Es ist ein berühmtes mittelalterliches Manuskript, das in der Abtei entstand."},
     {"q": "Gibt es ein jährliches religiöses Ereignis an der Basilika?", "a": "Ja, die berühmte Springprozession endet traditionell an der Basilika."}],
    [{"q": "Mi látható a bazilika kriptájában?", "a": "Szent Willibrord díszes márványsírja."},
     {"q": "Mikor épült a jelenlegi bazilika?", "a": "A mai román stílusú templom nagyrészt a 11. századból származik."},
     {"q": "Megsérült a bazilika a második világháborúban?", "a": "Igen, 1944-ben szinte teljesen elpusztult, majd újjáépítették."},
     {"q": "Mi a különleges az 'Echternachi Evangéliumban'?", "a": "Egy híres középkori kézirat, amely az apátságban készült."},
     {"q": "Van éves vallási esemény a bazilikánál?", "a": "Igen, a híres szökőkörmenet hagyományosan a bazilikánál ér véget."}],
    [{"q": "Ce se poate vedea în cripta bazilicii?", "a": "Mormântul magnific din marmură al Sfântului Willibrord."},
     {"q": "Când a fost construită actuala bazilică?", "a": "Biserica romanică de astăzi datează în mare parte din secolul al XI-lea."},
     {"q": "A fost bazilica deteriorată în al Doilea Război Mondial?", "a": "Da, a fost distrusă aproape complet în 1944 și reconstruită ulterior."},
     {"q": "Ce este special la 'Evangheliarul din Echternach'?", "a": "Este un manuscris medieval faimos, creat în abație."},
     {"q": "Există un eveniment religios anual la bazilică?", "a": "Da, celebra Procesiune Dansantă se încheie tradițional la bazilică."}],
    [{"q": "What can be seen in the basilica's crypt?", "a": "The magnificent marble tomb of Saint Willibrord."},
     {"q": "When was the current basilica built?", "a": "Today's Romanesque church mostly dates back to the 11th century."},
     {"q": "Was the basilica damaged in WWII?", "a": "Yes, it was almost completely destroyed in 1944 and rebuilt afterwards."},
     {"q": "What is special about the 'Echternach Gospels'?", "a": "It is a famous medieval manuscript created in the abbey."},
     {"q": "Is there an annual religious event at the basilica?", "a": "Yes, the famous Dancing Procession traditionally ends at the basilica."}]
)

add_faq("historical-victor-hugo-house",
    [{"q": "Warum war Victor Hugo in Vianden?", "a": "Er verbrachte dort 1871 mehrere Monate im politischen Exil."},
     {"q": "Was kann man im Victor-Hugo-Haus besichtigen?", "a": "Originale Briefe, Zeichnungen und persönliche Gegenstände des Autors."},
     {"q": "Hatte Victor Hugo eine besondere Beziehung zu Vianden?", "a": "Ja, er zeichnete die Burg und die Stadt oft und lobte ihre Schönheit."},
     {"q": "Wo befindet sich das Museum genau?", "a": "In dem Haus, in dem er damals wohnte, direkt an der Brücke über die Our."},
     {"q": "Wie viele Zeichnungen Hugos sind im Museum?", "a": "Es gibt eine bedeutende Sammlung seiner düsteren und atmosphärischen Zeichnungen."}],
    [{"q": "Miért volt Victor Hugo Viandenben?", "a": "1871-ben több hónapot töltött ott politikai száműzetésben."},
     {"q": "Mi tekinthető meg a Victor Hugo házban?", "a": "Az író eredeti levelei, rajzai és személyes tárgyai."},
     {"q": "Volt Victor Hugónak különleges kapcsolata Viandennel?", "a": "Igen, gyakran rajzolta le a várat és a várost, és dicsérte szépségét."},
     {"q": "Hol található pontosan a múzeum?", "a": "Abban a házban, ahol akkoriban lakott, közvetlenül az Our folyó hídja mellett."},
     {"q": "Hány Hugo-rajz található a múzeumban?", "a": "Jelentős gyűjtemény található sötét és hangulatos rajzaiból."}],
    [{"q": "De ce a fost Victor Hugo la Vianden?", "a": "A petrecut acolo câteva luni în exil politic în anul 1871."},
     {"q": "Ce poate fi vizitat în Casa Victor Hugo?", "a": "Scrisori originale, desene și obiecte personale ale autorului."},
     {"q": "A avut Victor Hugo o relație specială cu Vianden?", "a": "Da, a desenat adesea castelul și orașul și le-a lăudat frumusețea."},
     {"q": "Unde se află exact muzeul?", "a": "În casa în care a locuit atunci, chiar lângă podul peste râul Our."},
     {"q": "Câte desene ale lui Hugo sunt în muzeu?", "a": "Există o colecție semnificativă de desene ale sale, întunecate și pline de atmosferă."}],
    [{"q": "Why was Victor Hugo in Vianden?", "a": "He spent several months there in political exile in 1871."},
     {"q": "What can be visited at the Victor Hugo House?", "a": "Original letters, drawings, and personal belongings of the author."},
     {"q": "Did Victor Hugo have a special relationship with Vianden?", "a": "Yes, he often drew the castle and the town and praised its beauty."},
     {"q": "Where is the museum located exactly?", "a": "In the house where he lived at the time, right by the bridge over the Our."},
     {"q": "How many of Hugo's drawings are in the museum?", "a": "There is a significant collection of his dark and atmospheric drawings."}]
)

add_faq("historical-berg-castle",
    [{"q": "Wer bewohnt das Schloss Berg heute?", "a": "Es ist die offizielle Hauptresidenz des Großherzogs von Luxemburg."},
     {"q": "Kann man das Innere des Schlosses Berg besichtigen?", "a": "Nein, da es privat bewohnt wird, ist es für die Öffentlichkeit nicht zugänglich."},
     {"q": "In welcher Stadt liegt das Schloss Berg?", "a": "Es liegt in Colmar-Berg."},
     {"q": "Wann wurde das heutige Schloss Berg erbaut?", "a": "Das aktuelle Gebäude wurde zwischen 1907 und 1911 errichtet."},
     {"q": "Warum ist das Schloss Berg historisch wichtig?", "a": "Es ist der Geburtsort mehrerer Generationen der großherzoglichen Familie."}],
    [{"q": "Ki lakik ma a Berg kastélyban?", "a": "Ez a luxemburgi nagyherceg hivatalos főrezidenciája."},
     {"q": "Megtekinthető belülről a Berg kastély?", "a": "Nem, mivel magánrezidencia, a nagyközönség számára nem látogatható."},
     {"q": "Melyik városban található a Berg kastély?", "a": "Colmar-Bergben található."},
     {"q": "Mikor épült a mai Berg kastély?", "a": "A jelenlegi épületet 1907 és 1911 között emelték."},
     {"q": "Miért fontos történelmileg a Berg kastély?", "a": "A nagyhercegi család több generációjának születési helye."}],
    [{"q": "Cine locuiește astăzi în Castelul Berg?", "a": "Este reședința principală oficială a Marelui Duce de Luxemburg."},
     {"q": "Se poate vizita interiorul Castelului Berg?", "a": "Nu, deoarece este o reședință privată, nu este deschis publicului."},
     {"q": "În ce oraș se află Castelul Berg?", "a": "Se află în Colmar-Berg."},
     {"q": "Când a fost construit actualul Castel Berg?", "a": "Clădirea actuală a fost construită între anii 1907 și 1911."},
     {"q": "De ce este Castelul Berg important din punct de vedere istoric?", "a": "Este locul de naștere al mai multor generații ale familiei mare-ducale."}],
    [{"q": "Who lives in Berg Castle today?", "a": "It is the official primary residence of the Grand Duke of Luxembourg."},
     {"q": "Can you visit the interior of Berg Castle?", "a": "No, as it is a private residence, it is not open to the public."},
     {"q": "In which town is Berg Castle located?", "a": "It is located in Colmar-Berg."},
     {"q": "When was the current Berg Castle built?", "a": "The current building was constructed between 1907 and 1911."},
     {"q": "Why is Berg Castle historically important?", "a": "It is the birthplace of several generations of the Grand Ducal family."}]
)

add_faq("historical-schengen-monument",
    [{"q": "Was zeigen die drei Kupferstelen am Schengener Denkmal?", "a": "Sie zeigen die Konturen der Gründungsmitglieder des Abkommens."},
     {"q": "Was ist die 'Säule der Nationen'?", "a": "Eine Säule mit den Sternen der EU-Staaten am Moselufer."},
     {"q": "Gibt es ein Schloss in der Nähe des Denkmals?", "a": "Ja, das Schloss Schengen liegt nur wenige Meter entfernt."},
     {"q": "Kann man die Unterschriften des Abkommens sehen?", "a": "Kopien der historischen Dokumente sind im nahen Museum ausgestellt."},
     {"q": "Warum stehen dort Schlösser an einem Gitter?", "a": "Es ist ein Ort für 'Liebesschlösser', die die Verbundenheit symbolisieren."}],
    [{"q": "Mit ábrázol a schengeni emlékmű három rézoszlopa?", "a": "Az egyezményt alapító tagállamok körvonalait ábrázolják."},
     {"q": "Mi az a 'Nemzetek Oszlopa'?", "a": "Egy oszlop az EU-tagállamok csillagaival a Moselle partján."},
     {"q": "Van kastély az emlékmű közelében?", "a": "Igen, a schengeni kastély mindössze néhány méterre található."},
     {"q": "Láthatók az egyezmény aláírásai?", "a": "A történelmi dokumentumok másolatai a közeli múzeumban vannak kiállítva."},
     {"q": "Miért vannak lakatok egy rácson?", "a": "Ez a 'szerelemlakatok' helye, amely az összetartozást szimbolizálja."}],
    [{"q": "Ce reprezintă cele trei stele de cupru de la monumentul Schengen?", "a": "Ele arată contururile statelor membre fondatoare ale acordului."},
     {"q": "Ce este 'Coloana Națiunilor'?", "a": "O coloană cu stelele statelor UE pe malul Moselei."},
     {"q": "Există un castel în apropierea monumentului?", "a": "Da, Castelul Schengen se află la doar câțiva metri distanță."},
     {"q": "Se pot vedea semnăturile de pe acord?", "a": "Copii ale documentelor istorice sunt expuse în muzeul din apropiere."},
     {"q": "De ce sunt lacăte pe un grilaj?", "a": "Este un loc pentru 'lacătele iubirii', care simbolizează unitatea."}],
    [{"q": "What do the three copper steles at the Schengen monument show?", "a": "They show the outlines of the founding members of the agreement."},
     {"q": "What is the 'Column of Nations'?", "a": "A column featuring the stars of the EU states on the banks of the Moselle."},
     {"q": "Is there a castle near the monument?", "a": "Yes, Schengen Castle is located just a few meters away."},
     {"q": "Can you see the signatures of the agreement?", "a": "Copies of the historical documents are exhibited in the nearby museum."},
     {"q": "Why are there padlocks on a grid?", "a": "It is a spot for 'love locks,' symbolizing connection."}]
)

with open('tmp/faqs_4.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
