import json
import os

faqs = {}

def add_faq(id, de, hu, ro, en):
    faqs[id] = {
        "de": de,
        "hu": hu,
        "ro": ro,
        "en": en
    }

# Batch 1: 1-10
add_faq("lu-country", 
    [{"q": "Wann ist der luxemburgische Nationalfeiertag?", "a": "Der Nationalfeiertag wird jedes Jahr am 23. Juni gefeiert."},
     {"q": "Welche Farben hat die luxemburgische Flagge?", "a": "Die Flagge besteht aus drei horizontalen Streifen in Rot, Weiß und Hellblau."},
     {"q": "Welche Währung wird in Luxemburg verwendet?", "a": "Luxemburg verwendet den Euro als offizielle Währung."},
     {"q": "Wer ist das Staatsoberhaupt von Luxemburg?", "a": "Das Staatsoberhaupt ist der Großherzog von Luxemburg."},
     {"q": "An welche Länder grenzt Luxemburg?", "a": "Luxemburg grenzt an Deutschland, Frankreich und Belgien."}],
    [{"q": "Mikor van a luxemburgi nemzeti ünnep?", "a": "A nemzeti ünnepet minden évben június 23-án ünneplik."},
     {"q": "Milyen színei vannak a luxemburgi zászlónak?", "a": "A zászló három vízszintes sávból áll: piros, fehér és világoskék."},
     {"q": "Milyen pénznemet használnak Luxemburgban?", "a": "Luxemburg az eurót használja hivatalos pénznemként."},
     {"q": "Ki Luxemburg államfője?", "a": "Az államfő a luxemburgi nagyherceg."},
     {"q": "Mely országokkal határos Luxemburg?", "a": "Luxemburg Németországgal, Franciaországgal és Belgiummal határos."}],
    [{"q": "Când este ziua națională a Luxemburgului?", "a": "Ziua națională este sărbătorită în fiecare an pe 23 iunie."},
     {"q": "Ce culori are steagul Luxemburgului?", "a": "Steagul este format din trei benzi orizontale: roșu, alb și albastru deschis."},
     {"q": "Ce monedă se folosește în Luxemburg?", "a": "Luxemburg folosește euro ca monedă oficială."},
     {"q": "Cine este șeful statului în Luxemburg?", "a": "Șeful statului este Marele Duce de Luxemburg."},
     {"q": "Cu ce țări se învecinează Luxemburg?", "a": "Luxemburg se învecinează cu Germania, Franța și Belgia."}],
    [{"q": "When is the Luxembourgish National Day?", "a": "The National Day is celebrated every year on June 23rd."},
     {"q": "What are the colors of the Luxembourg flag?", "a": "The flag consists of three horizontal stripes: red, white, and light blue."},
     {"q": "What currency is used in Luxembourg?", "a": "Luxembourg uses the Euro as its official currency."},
     {"q": "Who is the head of state of Luxembourg?", "a": "The head of state is the Grand Duke of Luxembourg."},
     {"q": "Which countries border Luxembourg?", "a": "Luxembourg borders Germany, France, and Belgium."}]
)

add_faq("lu-luxembourg-city",
    [{"q": "Wie heißt der zentrale Platz in der Oberstadt?", "a": "Die Place d'Armes ist das Wohnzimmer der Stadt."},
     {"q": "Wo befindet sich das Denkmal 'Gëlle Fra'?", "a": "Es steht auf der Place de la Constitution."},
     {"q": "Welcher Fluss fließt durch das Tal des Grund?", "a": "Die Alzette fließt durch den malerischen Stadtteil Grund."},
     {"q": "Wie heißt das moderne Viertel mit den EU-Institutionen?", "a": "Das Viertel heißt Kirchberg."},
     {"q": "Wo kann man die Reste der Festung besichtigen?", "a": "In den Bock-Kasematten und am Chemin de la Corniche."}],
    [{"q": "Hogy hívják a felsőváros központi terét?", "a": "A Place d'Armes a város 'nappalija'."},
     {"q": "Hol található a 'Gëlle Fra' emlékmű?", "a": "A Place de la Constitution téren áll."},
     {"q": "Melyik folyó folyik keresztül a Grund völgyén?", "a": "Az Alzette folyik át a festői Grund negyeden."},
     {"q": "Hogy hívják az uniós intézményeknek otthont adó modern negyedet?", "a": "A negyed neve Kirchberg."},
     {"q": "Hol tekinthetők meg az erőd maradványai?", "a": "A Bock-kazamatákban és a Chemin de la Corniche sétányon."}],
    [{"q": "Cum se numește piața centrală din orașul de sus?", "a": "Place d'Armes este considerată 'sufrageria' orașului."},
     {"q": "Unde se află monumentul 'Gëlle Fra'?", "a": "Se află în Place de la Constitution."},
     {"q": "Ce râu curge prin valea Grund?", "a": "Râul Alzette curge prin cartierul pitoresc Grund."},
     {"q": "Cum se numește cartierul modern cu instituțiile UE?", "a": "Cartierul se numește Kirchberg."},
     {"q": "Unde pot fi vizitate rămășițele cetății?", "a": "În Casematele Bock și pe Chemin de la Corniche."}],
    [{"q": "What is the name of the central square in the upper city?", "a": "Place d'Armes is often called the city's 'sitting room.'"},
     {"q": "Where is the 'Gëlle Fra' monument located?", "a": "It stands in Place de la Constitution."},
     {"q": "Which river flows through the Grund valley?", "a": "The Alzette flows through the picturesque Grund district."},
     {"q": "What is the name of the modern district with EU institutions?", "a": "The district is called Kirchberg."},
     {"q": "Where can you see the remains of the fortress?", "a": "In the Bock Casemates and along the Chemin de la Corniche."}]
)

add_faq("lu-vianden",
    [{"q": "Was ist das Wahrzeichen von Vianden?", "a": "Das majestätische Schloss Vianden, eine der größten Burgen Europas."},
     {"q": "Welcher berühmte Schriftsteller lebte in Vianden?", "a": "Victor Hugo lebte 1871 im Exil in Vianden."},
     {"q": "Welches Transportmittel bietet eine tolle Aussicht auf die Burg?", "a": "Der Sessellift von Vianden bietet einen Panoramablick."},
     {"q": "An welchem Fluss liegt Vianden?", "a": "Vianden liegt im Tal des Flusses Our."},
     {"q": "Welches Fest findet jährlich im August auf der Burg statt?", "a": "Das jährliche Mittelalterfest ist eine Hauptattraktion."}],
    [{"q": "Mi Vianden legismertebb jelképe?", "a": "A fenséges Viandeni vár, Európa egyik legnagyobb vára."},
     {"q": "Melyik híres író élt Viandenben?", "a": "Victor Hugo élt Viandenben száműzetésben 1871-ben."},
     {"q": "Melyik közlekedési eszköz kínál remek kilátást a várra?", "a": "A viandeni libegő panorámás kilátást nyújt."},
     {"q": "Melyik folyó partján fekszik Vianden?", "a": "Vianden az Our folyó völgyében fekszik."},
     {"q": "Milyen fesztivált rendeznek évente augusztusban a várban?", "a": "Az évente megrendezett Középkori Fesztivál a fő látványosság."}],
    [{"q": "Care este simbolul orașului Vianden?", "a": "Majestuosul Castel Vianden, unul dintre cele mai mari din Europa."},
     {"q": "Ce scriitor celebru a locuit în Vianden?", "a": "Victor Hugo a locuit în exil la Vianden în 1871."},
     {"q": "Ce mijloc de transport oferă o vedere spectaculoasă asupra castelului?", "a": "Telescaunul din Vianden oferă o vedere panoramică."},
     {"q": "Pe ce râu se află orașul Vianden?", "a": "Vianden este situat pe râul Our."},
     {"q": "Ce festival are loc anual în luna august la castel?", "a": "Festivalul Medieval anual este o atracție principală."}],
    [{"q": "What is the landmark of Vianden?", "a": "The majestic Vianden Castle, one of the largest in Europe."},
     {"q": "Which famous writer lived in Vianden?", "a": "Victor Hugo lived in exile in Vianden in 1871."},
     {"q": "What mode of transport offers a great view of the castle?", "a": "The Vianden Chairlift provides a panoramic view."},
     {"q": "Which river is Vianden located on?", "a": "Vianden is situated in the valley of the Our River."},
     {"q": "What festival is held annually in August at the castle?", "a": "The annual Medieval Festival is a major attraction."}]
)

add_faq("lu-echternach",
    [{"q": "Wie heißt die berühmte UNESCO-Tradition in Echternach?", "a": "Die Echternacher Springprozession am Pfingstdienstag."},
     {"q": "Wer gründete die Stadt Echternach?", "a": "Der heilige Willibrord gründete die Abtei im Jahr 698."},
     {"q": "Was ist das Dënzelt?", "a": "Das Dënzelt ist das ehemalige gotische Rathaus am Marktplatz."},
     {"q": "Welcher Fluss bildet die Grenze bei Echternach?", "a": "Die Sauer bildet hier die Grenze zu Deutschland."},
     {"q": "Was kann man in der Nähe des Echternacher Sees besichtigen?", "a": "Die Überreste einer riesigen römischen Villa."}],
    [{"q": "Hogy hívják Echternach híres UNESCO hagyományát?", "a": "Az echternachi szökőkörmenet, amelyet pünkösdkedden tartanak."},
     {"q": "Ki alapította Echternach városát?", "a": "Szent Willibrord alapította az apátságot 698-ban."},
     {"q": "Mi az a Dënzelt?", "a": "A Dënzelt a piactéren található egykori gótikus városháza."},
     {"q": "Melyik folyó képezi a határt Echternachnál?", "a": "A Sauer folyó alkotja itt a határt Németországgal."},
     {"q": "Mit lehet meglátogatni az Echternachi-tó közelében?", "a": "Egy hatalmas római villa maradványait."}],
    [{"q": "Cum se numește celebra tradiție UNESCO din Echternach?", "a": "Procesiunea Dansantă din Echternach, care are loc în marțea de Rusalii."},
     {"q": "Cine a fondat orașul Echternach?", "a": "Sfântul Willibrord a fondat abația în anul 698."},
     {"q": "Ce este Dënzelt?", "a": "Dënzelt este fosta primărie gotică din piața centrală."},
     {"q": "Ce râu formează granița la Echternach?", "a": "Râul Sauer formează aici granița cu Germania."},
     {"q": "Ce se poate vizita lângă lacul Echternach?", "a": "Rămășițele unei vile romane imense."}],
    [{"q": "What is the famous UNESCO tradition in Echternach?", "a": "The Echternach Dancing Procession held on Whit Tuesday."},
     {"q": "Who founded the town of Echternach?", "a": "St. Willibrord founded the abbey in 698."},
     {"q": "What is the Dënzelt?", "a": "The Dënzelt is the former Gothic town hall on the market square."},
     {"q": "Which river forms the border at Echternach?", "a": "The Sauer River forms the border with Germany here."},
     {"q": "What can you visit near the Echternach Lake?", "a": "The remains of a massive Roman Villa."}]
)

add_faq("lu-mullerthal",
    [{"q": "Wie wird die Region Müllerthal noch genannt?", "a": "Sie ist als 'Kleine Luxemburger Schweiz' bekannt."},
     {"q": "Was ist der Schiessentümpel?", "a": "Ein malerischer Wasserfall mit einer charakteristischen Steinbrücke."},
     {"q": "Wie lang ist der Müllerthal Trail?", "a": "Das Wanderwegenetz umfasst insgesamt etwa 112 Kilometer."},
     {"q": "Welche Gesteinsart prägt die Landschaft?", "a": "Die Region ist berühmt für ihre spektakulären Sandsteinfelsformationen."},
     {"q": "Wie heißt eine bekannte Schlucht im Müllerthal?", "a": "Die Wollefsschlucht (Wolfsschlucht) ist eine der bekanntesten."}],
    [{"q": "Hogy nevezik még a Mullerthal régiót?", "a": "Úgy ismerik, mint a 'Kis Luxemburgi Svájc'."},
     {"q": "Mi az a Schiessentümpel?", "a": "Egy festői vízesés jellegzetes kőhíddal."},
     {"q": "Milyen hosszú a Mullerthal Trail?", "a": "A túraútvonal-hálózat összesen körülbelül 112 kilométer."},
     {"q": "Milyen kőzet jellemzi a tájat?", "a": "A régió a látványos homokkő sziklaalakzatairól híres."},
     {"q": "Hogy hívják a Mullerthal egyik ismert szurdokát?", "a": "A Wollefsschlucht (Farkas-szakadék) az egyik legismertebb."}],
    [{"q": "Cum mai este numită regiunea Mullerthal?", "a": "Este cunoscută sub numele de 'Mica Elveție Luxemburgheză'."},
     {"q": "Ce este Schiessentümpel?", "a": "O cascadă pitorească cu un pod de piatră caracteristic."},
     {"q": "Cât de lung este Mullerthal Trail?", "a": "Rețeaua de trasee măsoară în total aproximativ 112 kilometri."},
     {"q": "Ce tip de rocă domină peisajul?", "a": "Regiunea este faimoasă pentru formațiunile sale spectaculoase de gresie."},
     {"q": "Cum se numește un defileu cunoscut din Mullerthal?", "a": "Wollefsschlucht (Gura Lupului) este unul dintre cele mai faimoase."}],
    [{"q": "What is another name for the Mullerthal region?", "a": "It is known as 'Little Switzerland.'"},
     {"q": "What is the Schiessentümpel?", "a": "A picturesque waterfall with a characteristic stone bridge."},
     {"q": "How long is the Mullerthal Trail?", "a": "The hiking network totals approximately 112 kilometers."},
     {"q": "What type of rock characterizes the landscape?", "a": "The region is famous for its spectacular sandstone rock formations."},
     {"q": "What is the name of a well-known gorge in Mullerthal?", "a": "The Wollefsschlucht (Wolf's Gorge) is one of the most famous."}]
)

add_faq("lu-schengen",
    [{"q": "Warum ist Schengen weltweit bekannt?", "a": "Hier wurde 1985 das Schengener Abkommen für offene Grenzen unterzeichnet."},
     {"q": "An welchem Fluss liegt Schengen?", "a": "Schengen liegt direkt an der Mosel."},
     {"q": "Was kann man im Europäischen Museum Schengen sehen?", "a": "Exponate zur Geschichte der europäischen Integration und offenen Grenzen."},
     {"q": "Was ist das Dreiländereck bei Schengen?", "a": "Der Punkt, an dem Luxemburg, Deutschland und Frankreich aufeinandertreffen."},
     {"q": "Welches Produkt wird in der Region Schengen produziert?", "a": "Die Region ist berühmt für ihren Weinbau, besonders Weißweine."}],
    [{"q": "Miért világhírű Schengen?", "a": "Itt írták alá 1985-ben a nyitott határokról szóló schengeni egyezményt."},
     {"q": "Melyik folyó partján fekszik Schengen?", "a": "Schengen közvetlenül a Moselle partján fekszik."},
     {"q": "Mit láthatunk a schengeni Európai Múzeumban?", "a": "Az európai integráció és a nyitott határok történetét bemutató kiállításokat."},
     {"q": "Mi az a hármashatár Schengenernél?", "a": "Az a pont, ahol Luxemburg, Németország és Franciaország találkozik."},
     {"q": "Milyen terméket állítanak elő a schengeni régióban?", "a": "A régió híres a borászatáról, különösen a fehérborokról."}],
    [{"q": "De ce este Schengen cunoscut în întreaga lume?", "a": "Aici a fost semnat în 1985 Acordul Schengen pentru frontiere deschise."},
     {"q": "Pe ce râu este situat Schengen?", "a": "Schengen se află direct pe malul râului Mosela."},
     {"q": "Ce se poate vedea la Muzeul European Schengen?", "a": "Exponate despre istoria integrării europene și a frontierelor deschise."},
     {"q": "Ce este punctul triplu de la Schengen?", "a": "Locul unde se întâlnesc granițele Luxemburgului, Germaniei și Franței."},
     {"q": "Ce produs se obține în regiunea Schengen?", "a": "Regiunea este faimoasă pentru viticultură, în special pentru vinurile albe."}],
    [{"q": "Why is Schengen world-famous?", "a": "The Schengen Agreement for open borders was signed here in 1985."},
     {"q": "On which river is Schengen located?", "a": "Schengen is situated directly on the Moselle River."},
     {"q": "What can you see at the European Museum Schengen?", "a": "Exhibits on the history of European integration and open borders."},
     {"q": "What is the tripoint near Schengen?", "a": "The point where the borders of Luxembourg, Germany, and France meet."},
     {"q": "What product is produced in the Schengen region?", "a": "The region is famous for its viticulture, especially white wines."}]
)

add_faq("city-luxembourg",
    [{"q": "In wie viele Stadtviertel ist Luxemburg-Stadt unterteilt?", "a": "Die Stadt besteht aus 24 verschiedenen Stadtvierteln."},
     {"q": "Was ist die Philharmonie Luxembourg?", "a": "Ein hochmodernes Konzerthaus auf dem Kirchberg-Plateau."},
     {"q": "Welches Museum ist dem Großherzog Jean gewidmet?", "a": "Das Mudam (Musée d'Art Moderne Grand-Duc Jean)."},
     {"q": "Wo findet man die Kasematten in der Stadt?", "a": "Die bekanntesten sind die Bock-Kasematten und die Pétrusse-Kasematten."},
     {"q": "Wie heißt der Aufzug, der die Oberstadt mit dem Grund verbindet?", "a": "Der Panorama-Aufzug Pfaffenthal."}],
    [{"q": "Hány városrészre oszlik Luxemburg város?", "a": "A város 24 különböző negyedből áll."},
     {"q": "Mi az a Philharmonie Luxembourg?", "a": "Egy ultramodern koncertterem a Kirchberg-fennsíkon."},
     {"q": "Melyik múzeumot szentelték Jean nagyhercegnek?", "a": "A Mudam-ot (Jean Nagyherceg Modern Művészeti Múzeum)."},
     {"q": "Hol találhatók kazamaták a városban?", "a": "A legismertebbek a Bock- és a Pétrusse-kazamaták."},
     {"q": "Hogy hívják a felsővárost Pfaffenthallal összekötő liftet?", "a": "A Pfaffenthal panorámalift."}],
    [{"q": "În câte cartiere este împărțit orașul Luxemburg?", "a": "Orașul este compus din 24 de cartiere diferite."},
     {"q": "Ce este Philharmonie Luxembourg?", "a": "O sală de concerte ultramodernă pe platoul Kirchberg."},
     {"q": "Ce muzeu este dedicat Marelui Duce Jean?", "a": "Mudam (Muzeul de Artă Modernă Marele Duce Jean)."},
     {"q": "Unde se găsesc casemate în oraș?", "a": "Cele mai cunoscute sunt Casematele Bock și Casematele Pétrusse."},
     {"q": "Cum se numește liftul care leagă orașul de sus de cartierul Pfaffenthal?", "a": "Liftul panoramic Pfaffenthal."}],
    [{"q": "How many districts is Luxembourg City divided into?", "a": "The city consists of 24 different districts."},
     {"q": "What is the Philharmonie Luxembourg?", "a": "An ultra-modern concert hall on the Kirchberg plateau."},
     {"q": "Which museum is dedicated to Grand Duke Jean?", "a": "The Mudam (Grand Duke Jean Museum of Modern Art)."},
     {"q": "Where can you find casemates in the city?", "a": "The most famous are the Bock Casemates and the Pétrusse Casemates."},
     {"q": "What is the name of the lift connecting the upper city with Pfaffenthal?", "a": "The Pfaffenthal Panoramic Lift."}]
)

add_faq("city-esch",
    [{"q": "Was war früher die Hauptindustrie in Esch-sur-Alzette?", "a": "Die Eisen- und Stahlindustrie war das Herz der Stadt."},
     {"q": "Wie heißt das neue Universitätsviertel?", "a": "Das Viertel Belval beherbergt den Campus der Universität."},
     {"q": "Welches große Konzerthaus steht in Esch-Belval?", "a": "Die Rockhal ist der bekannteste Veranstaltungsort für Konzerte."},
     {"q": "Was kann man auf dem Gaalgebierg machen?", "a": "Man kann den Tierpark besuchen oder in den Gärten spazieren gehen."},
     {"q": "Wie heißt die Haupteinkaufsstraße von Esch?", "a": "Die Rue de l'Alzette ist die bekannteste Einkaufsmeile."}],
    [{"q": "Mi volt régen a fő iparág Esch-sur-Alzette-ben?", "a": "A vas- és acélipar volt a város szíve."},
     {"q": "Hogy hívják az új egyetemi negyedet?", "a": "A Belval negyed ad otthont az egyetemi campusnak."},
     {"q": "Melyik nagy koncertterem található Esch-Belvalban?", "a": "A Rockhal a legismertebb koncerthelyszín."},
     {"q": "Mit lehet csinálni a Gaalgebierg-en?", "a": "Meg lehet látogatni az állatparkot vagy sétálni a kertekben."},
     {"q": "Hogy hívják Esch fő bevásárlóutcáját?", "a": "A Rue de l'Alzette a legismertebb bevásárlóutca."}],
    [{"q": "Care a fost industria principală în Esch-sur-Alzette?", "a": "Industria fierului și oțelului a fost inima orașului."},
     {"q": "Cum se numește noul cartier universitar?", "a": "Cartierul Belval găzduiește campusul universității."},
     {"q": "Ce sală mare de concerte se află în Esch-Belval?", "a": "Rockhal este cea mai cunoscută locație pentru concerte."},
     {"q": "Ce se poate face pe Gaalgebierg?", "a": "Se poate vizita parcul zoologic sau se poate face o plimbare în grădini."},
     {"q": "Cum se numește strada principală de cumpărături din Esch?", "a": "Rue de l'Alzette este cea mai cunoscută stradă comercială."}],
    [{"q": "What used to be the main industry in Esch-sur-Alzette?", "a": "The iron and steel industry was the heart of the city."},
     {"q": "What is the name of the new university district?", "a": "The Belval district hosts the university campus."},
     {"q": "Which large concert hall is located in Esch-Belval?", "a": "The Rockhal is the most famous concert venue."},
     {"q": "What can you do at Gaalgebierg?", "a": "You can visit the animal park or walk through the gardens."},
     {"q": "What is the name of the main shopping street in Esch?", "a": "Rue de l'Alzette is the most famous shopping street."}]
)

add_faq("city-differdange",
    [{"q": "Was ist das Luxembourg Science Center?", "a": "Ein interaktives Museum in Differdingen, das Wissenschaft erlebbar macht."},
     {"q": "Wer nutzt heute das Schloss Differdingen?", "a": "Es dient als Campus für die Miami University aus den USA."},
     {"q": "Welches Industrieunternehmen ist prägend für Differdingen?", "a": "Das Stahlunternehmen ArcelorMittal betreibt hier ein großes Werk."},
     {"q": "Wie wird Differdingen oft genannt?", "a": "Wegen seiner Industriegeschichte wird es oft 'Eisenstadt' genannt."},
     {"q": "Gibt es Natur in Differdingen?", "a": "Ja, die Stadt ist von großen Waldgebieten wie dem 'Thillenvogtei' umgeben."}],
    [{"q": "Mi az a Luxembourg Science Center?", "a": "Egy interaktív múzeum Differdange-ban, amely élvezetessé teszi a tudományt."},
     {"q": "Ki használja ma a Differdange-i kastélyt?", "a": "Az amerikai Miami Egyetem kampuszaként szolgál."},
     {"q": "Melyik ipari vállalat meghatározó Differdange-ban?", "a": "Az ArcelorMittal acélipari vállalat működtet itt egy nagy gyárat."},
     {"q": "Hogy nevezik gyakran Differdange-ot?", "a": "Ipari múltja miatt gyakran hívják 'vasvárosnak'."},
     {"q": "Van természet Differdange-ban?", "a": "Igen, a várost olyan nagy erdős területek veszik körül, mint a 'Thillenvogtei'."}],
    [{"q": "Ce este Luxembourg Science Center?", "a": "Un muzeu interactiv din Differdange care face știința accesibilă."},
     {"q": "Cine folosește astăzi Castelul Differdange?", "a": "Servește ca campus pentru Universitatea Miami din SUA."},
     {"q": "Ce companie industrială este emblematică pentru Differdange?", "a": "Compania siderurgică ArcelorMittal operează aici o uzină mare."},
     {"q": "Cum este numit adesea orașul Differdange?", "a": "Datorită istoriei sale industriale, este numit adesea 'Orașul Fierului'."},
     {"q": "Există natură în Differdange?", "a": "Da, orașul este înconjurat de zone forestiere mari, precum 'Thillenvogtei'."}],
    [{"q": "What is the Luxembourg Science Center?", "a": "An interactive museum in Differdange that makes science fun and accessible."},
     {"q": "Who uses Differdange Castle today?", "a": "It serves as a campus for Miami University from the USA."},
     {"q": "Which industrial company is prominent in Differdange?", "a": "The steel company ArcelorMittal operates a large plant here."},
     {"q": "What is Differdange often called?", "a": "Because of its industrial history, it is often called the 'Iron City.'"},
     {"q": "Is there nature in Differdange?", "a": "Yes, the city is surrounded by large forested areas like the 'Thillenvogtei.'"}]
)

add_faq("cult-bock",
    [{"q": "Wer gründete die erste Burg auf dem Bock-Felsen?", "a": "Graf Siegfried baute hier im Jahr 963 die Burg Lucilinburhuc."},
     {"q": "Wie lang war das gesamte Tunnelnetz der Kasematten?", "a": "Das Netz erstreckte sich einst über eine Länge von 23 Kilometern."},
     {"q": "Warum wird Luxemburg 'Gibraltar des Nordens' genannt?", "a": "Wegen der gewaltigen Festungsanlagen auf dem Bock und Umgebung."},
     {"q": "Kann man die Kasematten heute noch besuchen?", "a": "Ja, sie sind eine der wichtigsten Touristenattraktionen der Stadt."},
     {"q": "Wofür wurden die Kasematten im Zweiten Weltkrieg genutzt?", "a": "Sie dienten der Bevölkerung als Schutz vor Luftangriffen."}],
    [{"q": "Ki alapította az első várat a Bock-sziklán?", "a": "Szigfrid gróf építette itt 963-ban Lucilinburhuc várát."},
     {"q": "Milyen hosszú volt a kazamaták teljes alagútrendszere?", "a": "A hálózat egykor 23 kilométer hosszan nyúlt el."},
     {"q": "Miért hívják Luxemburgot 'Észak Gibraltárjának'?", "a": "A Bock-sziklán és környékén található hatalmas erődítmények miatt."},
     {"q": "Látogathatók ma is a kazamaták?", "a": "Igen, a város egyik legfontosabb turisztikai látványosságai."},
     {"q": "Mire használták a kazamatákat a második világháborúban?", "a": "Légvédelmi óvóhelyként szolgáltak a lakosság számára."}],
    [{"q": "Cine a fondat primul castel pe stânca Bock?", "a": "Contele Siegfried a construit aici castelul Lucilinburhuc în anul 963."},
     {"q": "Cât de lungă era întreaga rețea de tuneluri a casematelor?", "a": "Rețeaua se întindea odinioară pe o lungime de 23 de kilometri."},
     {"q": "De ce este Luxemburg numit 'Gibraltarul Nordului'?", "a": "Datorită fortificațiilor masive de pe stânca Bock și din împrejurimi."},
     {"q": "Mai pot fi vizitate casematele astăzi?", "a": "Da, sunt una dintre cele mai importante atracții turistice ale orașului."},
     {"q": "Pentru ce au fost folosite casematele în al Doilea Război Mondial?", "a": "Au servit populației ca adăpost împotriva atacurilor aeriene."}],
    [{"q": "Who founded the first castle on the Bock Rock?", "a": "Count Siegfried built the Lucilinburhuc castle here in 963."},
     {"q": "How long was the entire tunnel network of the casemates?", "a": "The network once stretched over a length of 23 kilometers."},
     {"q": "Why is Luxembourg called the 'Gibraltar of the North'?", "a": "Because of the massive fortifications on the Bock and the surrounding area."},
     {"q": "Can the casemates still be visited today?", "a": "Yes, they are one of the most important tourist attractions in the city."},
     {"q": "What were the casemates used for during WWII?", "a": "They served as air-raid shelters for the local population."}]
)

with open('tmp/faqs_1.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
