import json

faqs = {}

def add_faq(id, de, hu, ro, en):
    faqs[id] = {
        "de": de,
        "hu": hu,
        "ro": ro,
        "en": en
    }

# Batch 9: 81-90
add_faq("river-ernz-noire",
    [{"q": "Durch welche Region fließt die Schwarze Ernz?", "a": "Sie fließt mitten durch die Region Müllerthal (Kleine Luxemburger Schweiz)."},
     {"q": "Welches berühmte Naturdenkmal liegt an der Schwarzen Ernz?", "a": "Der Schiessentümpel-Wasserfall."},
     {"q": "In welchen Fluss mündet die Schwarze Ernz?", "a": "Sie mündet bei Grundhof in die Sauer."},
     {"q": "Gibt es Wanderwege entlang des Flusses?", "a": "Ja, der Müllerthal Trail (Route 2) folgt über weite Strecken dem Lauf der Schwarzen Ernz."},
     {"q": "Warum heißt der Fluss 'Schwarze' Ernz?", "a": "Vermutlich aufgrund der dunklen Farbe des Wassers im schattigen, bewaldeten Tal."}],
    [{"q": "Melyik régión folyik keresztül a Fekete-Ernz?", "a": "A Mullerthal régión (Kis Luxemburgi Svájc) folyik keresztül."},
     {"q": "Melyik híres természeti emlékmű található a Fekete-Ernz mentén?", "a": "A Schiessentümpel-vízesés."},
     {"q": "Melyik folyóba torkollik a Fekete-Ernz?", "a": "Grundhofnál ömlik a Sauer folyóba."},
     {"q": "Vannak túraútvonalak a folyó mentén?", "a": "Igen, a Mullerthal Trail (2. útvonal) hosszú szakaszon követi a Fekete-Ernz folyását."},
     {"q": "Miért hívják a folyót 'Fekete'-Ernznek?", "a": "Valószínűleg az árnyas, erdős völgyben sötétnek tűnő vize miatt."}],
    [{"q": "Prin ce regiune trece râul Ernz Neagră?", "a": "Curge chiar prin regiunea Mullerthal (Mica Elveție Luxemburgheză)."},
     {"q": "Ce monument natural faimos se află pe râul Ernz Neagră?", "a": "Cascada Schiessentümpel."},
     {"q": "În ce râu se varsă Ernz Neagră?", "a": "Se varsă în râul Sauer, la Grundhof."},
     {"q": "Există trasee de drumeție de-a lungul râului?", "a": "Da, Mullerthal Trail (Ruta 2) urmărește pe porțiuni lungi cursul râului Ernz Neagră."},
     {"q": "De ce se numește râul Ernz 'Neagră'?", "a": "Probabil din cauza culorii întunecate a apei în valea umbrită și împădurită."}],
    [{"q": "Which region does the Black Ernz flow through?", "a": "It flows right through the Mullerthal region (Little Switzerland)."},
     {"q": "What famous natural monument is located on the Black Ernz?", "a": "The Schiessentümpel waterfall."},
     {"q": "Into which river does the Black Ernz flow?", "a": "It flows into the Sûre River near Grundhof."},
     {"q": "Are there hiking trails along the river?", "a": "Yes, the Mullerthal Trail (Route 2) follows the course of the Black Ernz for long stretches."},
     {"q": "Why is the river called the 'Black' Ernz?", "a": "Presumably due to the dark color of the water in the shaded, forested valley."}]
)

add_faq("agriculture-domaine-vinsmoselle-remerschen",
    [{"q": "Was ist die Domaine Vinsmoselle?", "a": "Die größte Winzergenossenschaft Luxemburgs mit mehreren Standorten an der Mosel."},
     {"q": "Was kann man in der Kellerei in Remerschen besichtigen?", "a": "Die modernen Produktionsanlagen und die großen Weinkeller."},
     {"q": "Welches besondere Gebäude gehört zur Domaine in Remerschen?", "a": "Die Caves du Sud, ein markantes Gebäude für Verkostungen und Verkauf."},
     {"q": "Welche Rebsorten werden hier verarbeitet?", "a": "Die gesamte Palette der Luxemburger Moselweine, von Riesling bis Crémant."},
     {"q": "Gibt es dort eine Vinothek?", "a": "Ja, man kann dort Weine probieren und direkt ab Hof kaufen."}],
    [{"q": "Mi az a Domaine Vinsmoselle?", "a": "Luxemburg legnagyobb borászati szövetkezete, több telephellyel a Moselle mentén."},
     {"q": "Mit lehet meglátogatni a remerscheni borászatban?", "a": "A modern termelőberendezéseket és a nagy borpincéket."},
     {"q": "Milyen különleges épület tartozik a Domaine-hez Remerschenben?", "a": "A Caves du Sud, egy jellegzetes épület kóstolókhoz és értékesítéshez."},
     {"q": "Milyen szőlőfajtákat dolgoznak fel itt?", "a": "A luxemburgi Moselle-borok teljes választékát, a rizlingtől a Crémant-ig."},
     {"q": "Van ott vinotéka?", "a": "Igen, lehet bort kóstolni és közvetlenül a termelőtől vásárolni."}],
    [{"q": "Ce este Domaine Vinsmoselle?", "a": "Cea mai mare cooperativă viticolă din Luxemburg, cu mai multe locații pe Mosela."},
     {"q": "Ce se poate vizita la crama din Remerschen?", "a": "Instalațiile moderne de producție și cramele mari."},
     {"q": "Ce clădire specială aparține de Domaine în Remerschen?", "a": "Caves du Sud, o clădire emblematică pentru degustări și vânzare."},
     {"q": "Ce soiuri de struguri sunt procesate aici?", "a": "Întreaga gamă de vinuri de Mosela din Luxemburg, de la Riesling la Crémant."},
     {"q": "Există o vinotecă acolo?", "a": "Da, se pot degusta vinuri și se pot cumpăra direct de la cramă."}],
    [{"q": "What is Domaine Vinsmoselle?", "a": "Luxembourg's largest winegrowers' cooperative with several locations on the Moselle."},
     {"q": "What can you visit at the winery in Remerschen?", "a": "The modern production facilities and the large wine cellars."},
     {"q": "Which special building belongs to the Domaine in Remerschen?", "a": "The Caves du Sud, a prominent building for tastings and sales."},
     {"q": "Which grape varieties are processed here?", "a": "The entire range of Luxembourg Moselle wines, from Riesling to Crémant."},
     {"q": "Is there a vinotheque there?", "a": "Yes, you can taste wines and buy them directly from the producer."}]
)

add_faq("agriculture-domaine-mathis-bastian-remich",
    [{"q": "Ist die Domaine Mathis Bastian ein Familienbetrieb?", "a": "Ja, es ist ein traditionsreiches Weingut, das heute in Familienbesitz geführt wird."},
     {"q": "Wo liegen die Weinberge der Domaine?", "a": "Auf den sonnigen Hängen rund um Remich."},
     {"q": "Welche Philosophie verfolgt das Weingut?", "a": "Einen naturnahen Weinbau und die Produktion von Charakterweinen."},
     {"q": "Kann man dort Weinproben machen?", "a": "Ja, das Weingut bietet Verkostungen in einem persönlichen Rahmen an."},
     {"q": "Welche Weine sind besonders empfehlenswert?", "a": "Vor allem der Riesling und der Pinot Gris von Mathis Bastian genießen einen sehr guten Ruf."}],
    [{"q": "Családi vállalkozás a Domaine Mathis Bastian?", "a": "Igen, ez egy nagy múltú borászat, amelyet ma is a család vezet."},
     {"q": "Hol találhatók a Domaine szőlőültetvényei?", "a": "A Remich környéki napsütötte lankákon."},
     {"q": "Milyen filozófiát követ a borászat?", "a": "A természetközeli szőlőművelést és karakteres borok készítését."},
     {"q": "Lehet ott borkóstolón részt venni?", "a": "Igen, a borászat személyes hangvételű kóstolókat kínál."},
     {"q": "Mely borok különösen ajánlottak?", "a": "Főleg Mathis Bastian rizlingje és szürkebarátja örvend kiváló hírnévnek."}],
    [{"q": "Este Domaine Mathis Bastian o afacere de familie?", "a": "Da, este un domeniu viticol cu tradiție, administrat și astăzi de familie."},
     {"q": "Unde sunt situate podgoriile domeniului?", "a": "Pe versanții însoriți din jurul localității Remich."},
     {"q": "Ce filozofie urmează crama?", "a": "Viticultura apropiată de natură și producția de vinuri cu caracter."},
     {"q": "Se pot face degustări de vinuri acolo?", "a": "Da, crama oferă degustări într-un cadru personalizat."},
     {"q": "Ce vinuri sunt recomandate în mod deosebit?", "a": "În special Riesling-ul și Pinot Gris-ul de la Mathis Bastian se bucură de o reputație foarte bună."}],
    [{"q": "Is Domaine Mathis Bastian a family business?", "a": "Yes, it is a traditional winery that is still family-owned today."},
     {"q": "Where are the winery's vineyards located?", "a": "On the sunny slopes around Remich."},
     {"q": "What philosophy does the winery follow?", "a": "Nature-oriented viticulture and the production of characterful wines."},
     {"q": "Can you have wine tastings there?", "a": "Yes, the winery offers tastings in a personal setting."},
     {"q": "Which wines are particularly recommended?", "a": "The Riesling and Pinot Gris from Mathis Bastian especially enjoy a very good reputation."}]
)

add_faq("agriculture-clos-mon-vieux-moulin",
    [{"q": "Was bedeutet der Name 'Clos Mon Vieux Moulin'?", "a": "Es bezieht sich auf eine alte Mühle ('Vieux Moulin'), die zum Weingut gehört."},
     {"q": "Welches Weingut betreibt diesen Clos?", "a": "Das Weingut Duhr-Frères aus Ahn."},
     {"q": "Wo befindet sich das Weingut?", "a": "In Ahn, einem malerischen Dorf an der Mosel."},
     {"q": "Was ist das Besondere am Weinbau in Ahn?", "a": "Die Weinberge liegen in einem Talkessel mit einem besonderen Mikroklima."},
     {"q": "Gibt es dort ein Restaurant?", "a": "Ja, die 'Brasserie Mon Vieux Moulin' bietet regionale Küche und eigene Weine."}],
    [{"q": "Mit jelent a 'Clos Mon Vieux Moulin' név?", "a": "Egy régi malomra ('Vieux Moulin') utal, amely a borászathoz tartozik."},
     {"q": "Melyik borászat üzemelteti ezt a területet?", "a": "Az ahni Duhr-Frères borászat."},
     {"q": "Hol található a borászat?", "a": "Ahnban, egy festői faluban a Moselle partján."},
     {"q": "Mi a különleges az ahni szőlőtermesztésben?", "a": "A szőlőültetvények egy völgykatlanban fekszenek, amelynek különleges mikroklímája van."},
     {"q": "Van ott étterem?", "a": "Igen, a 'Brasserie Mon Vieux Moulin' helyi ételeket és saját borokat kínál."}],
    [{"q": "Ce înseamnă numele 'Clos Mon Vieux Moulin'?", "a": "Se referă la o moară veche ('Vieux Moulin') care aparține domeniului viticol."},
     {"q": "Care cramă administrează acest domeniu?", "a": "Crama Duhr-Frères din Ahn."},
     {"q": "Unde se află crama?", "a": "În Ahn, un sat pitoresc de pe malul Moselei."},
     {"q": "Ce este special la viticultura din Ahn?", "a": "Podgoriile sunt situate într-o depresiune cu un microclimat special."},
     {"q": "Există vreun restaurant acolo?", "a": "Da, 'Brasserie Mon Vieux Moulin' oferă bucătărie regională și vinuri proprii."}],
    [{"q": "What does the name 'Clos Mon Vieux Moulin' mean?", "a": "It refers to an old mill ('Vieux Moulin') that belongs to the winery."},
     {"q": "Which winery operates this Clos?", "a": "The Duhr-Frères winery from Ahn."},
     {"q": "Where is the winery located?", "a": "In Ahn, a picturesque village on the Moselle."},
     {"q": "What is special about viticulture in Ahn?", "a": "The vineyards are located in a valley basin with a special microclimate."},
     {"q": "Is there a restaurant there?", "a": "Yes, the 'Brasserie Mon Vieux Moulin' offers regional cuisine and its own wines."}]
)

add_faq("industry-arcelormittal-belval",
    [{"q": "Wozu dienen die alten Hochöfen in Belval heute?", "a": "Sie sind Industriedenkmäler und können im Rahmen von Führungen besichtigt werden."},
     {"q": "Wird in Belval heute noch Stahl produziert?", "a": "Ja, ArcelorMittal betreibt dort ein modernes Elektrostahlwerk."},
     {"q": "Was ist die 'Cité des Sciences'?", "a": "Ein neues Viertel in Belval, das Wissenschaft, Forschung und Kultur vereint."},
     {"q": "Wie hoch sind die Hochöfen?", "a": "Der höchste Punkt, den Besucher besteigen können, liegt auf 40 Metern Höhe."},
     {"q": "Was kann man von der Spitze der Hochöfen sehen?", "a": "Man hat einen fantastischen Blick über das gesamte Belval-Gelände und den Süden Luxemburgs."}],
    [{"q": "Mire szolgálnak ma a régi nagyolvasztók Belvalban?", "a": "Ipari műemlékek, és vezetett túrák keretében látogathatók."},
     {"q": "Gyártanak még ma is acélt Belvalban?", "a": "Igen, az ArcelorMittal egy modern elektromos acélművet működtet ott."},
     {"q": "Mi az a 'Cité des Sciences'?", "a": "Egy új negyed Belvalban, amely a tudományt, a kutatást és a kultúrát ötvözi."},
     {"q": "Milyen magasak a nagyolvasztók?", "a": "A legmagasabb pont, ahová a látogatók felmehetnek, 40 méter magasan van."},
     {"q": "Mit lehet látni a nagyolvasztók tetejéről?", "a": "Fantasztikus kilátás nyílik a teljes Belval-területre és Luxemburg déli részére."}],
    [{"q": "La ce folosesc astăzi vechile furnale din Belval?", "a": "Sunt monumente industriale și pot fi vizitate în cadrul unor tururi ghidate."},
     {"q": "Se mai produce oțel astăzi la Belval?", "a": "Da, ArcelorMittal operează acolo o oțelărie electrică modernă."},
     {"q": "Ce este 'Cité des Sciences'?", "a": "Un cartier nou în Belval, care reunește știința, cercetarea și cultura."},
     {"q": "Cât de înalte sunt furnalele?", "a": "Cel mai înalt punct la care pot urca vizitatorii se află la 40 de metri înălțime."},
     {"q": "Ce se poate vedea din vârful furnalelor?", "a": "Ai o vedere fantastică asupra întregului sit Belval și a sudului Luxemburgului."}],
    [{"q": "What are the old blast furnaces in Belval used for today?", "a": "They are industrial monuments and can be visited on guided tours."},
     {"q": "Is steel still produced in Belval today?", "a": "Yes, ArcelorMittal operates a modern electric steel plant there."},
     {"q": "What is the 'Cité des Sciences'?", "a": "A new district in Belval that combines science, research, and culture."},
     {"q": "How high are the blast furnaces?", "a": "The highest point that visitors can climb to is at an altitude of 40 meters."},
     {"q": "What can you see from the top of the blast furnaces?", "a": "You have a fantastic view over the entire Belval site and the south of Luxembourg."}]
)

add_faq("industry-minett-park-fond-de-gras",
    [{"q": "Was ist der Fond-de-Gras?", "a": "Ein Freilichtmuseum, das die Geschichte des luxemburgischen Bergbaus zeigt."},
     {"q": "Was ist der 'Train 1900'?", "a": "Ein historischer Dampfzug, der Besucher von Petingen zum Fond-de-Gras bringt."},
     {"q": "Kann man dort in eine echte Mine einfahren?", "a": "Ja, die Grube 'Doihl' kann mit einer kleinen Grubenbahn (Minièresbunn) besichtigt werden."},
     {"q": "Gibt es dort historische Gebäude?", "a": "Ja, ein altes Lebensmittelgeschäft, ein Walzwerk und ein Elektrizitätswerk sind erhalten."},
     {"q": "Wann finden Veranstaltungen im Minett Park statt?", "a": "Es gibt regelmäßige Themenwochenenden, wie zum Beispiel das 'Steampunk'-Festival."},
    ],
    [{"q": "Mi az a Fond-de-Gras?", "a": "Egy szabadtéri múzeum, amely a luxemburgi bányászat történetét mutatja be."},
     {"q": "Mi az a 'Train 1900'?", "a": "Egy történelmi gőzmozdonyos vonat, amely Pétange-ból szállítja az utasokat Fond-de-Gras-ba."},
     {"q": "Be lehet menni ott egy igazi bányába?", "a": "Igen, a 'Doihl' bánya egy kis bányavasúttal (Minièresbunn) látogatható."},
     {"q": "Vannak ott történelmi épületek?", "a": "Igen, egy régi élelmiszerüzlet, egy hengermű és egy elektromos központ is fennmaradt."},
     {"q": "Mikor tartanak rendezvényeket a Minett Parkban?", "a": "Rendszeresen vannak tematikus hétvégék, például a 'Steampunk' fesztivál."}],
    [{"q": "Ce este Fond-de-Gras?", "a": "Un muzeu în aer liber care prezintă istoria minieră a Luxemburgului."},
     {"q": "Ce este 'Train 1900'?", "a": "Un tren istoric cu aburi care transportă vizitatorii de la Pétange la Fond-de-Gras."},
     {"q": "Se poate intra într-o mină veritabilă acolo?", "a": "Da, mina 'Doihl' poate fi vizitată cu un trenuleț de mină (Minièresbunn)."},
     {"q": "Există clădiri istorice acolo?", "a": "Da, sunt conservate o veche băcănie, un laminor și o centrală electrică."},
     {"q": "Când au loc evenimente în Minett Park?", "a": "Au loc periodic weekenduri tematice, cum ar fi festivalul 'Steampunk'."}],
    [{"q": "What is Fond-de-Gras?", "a": "An open-air museum showing the history of Luxembourg's mining industry."},
     {"q": "What is the 'Train 1900'?", "a": "A historical steam train that takes visitors from Pétange to Fond-de-Gras."},
     {"q": "Can you enter a real mine there?", "a": "Yes, the 'Doihl' mine can be visited with a small mine train (Minièresbunn)."},
     {"q": "Are there historical buildings there?", "a": "Yes, an old grocery store, a rolling mill, and a power station are preserved."},
     {"q": "When are events held at Minett Park?", "a": "There are regular themed weekends, such as the 'Steampunk' festival."}]
)

add_faq("kid-landmark-paiperleksgaart",
    [{"q": "Wo befindet sich der Schmetterlingsgarten?", "a": "In Grevenmacher an der Mosel."},
     {"q": "Welche Bedingungen herrschen im Schmetterlingshaus?", "a": "Es herrscht ein tropisches Klima mit etwa 27 Grad Celsius und hoher Luftfeuchtigkeit."},
     {"q": "Kann man dort auch andere Tiere sehen?", "a": "Ja, es gibt auch Wachteln, Chamäleons und Bienen."},
     {"q": "Gibt es dort Pflanzen aus den Tropen?", "a": "Ja, der Garten ist voll von exotischen Pflanzen und Blumen, die den Schmetterlingen als Nahrung dienen."},
     {"q": "Darf man im Garten fotografieren?", "a": "Ja, es ist ein Paradies für Makrofotografen, aber man sollte die Tiere nicht berühren."}],
    [{"q": "Hol található a Pillangókert?", "a": "Grevenmacherben, a Moselle partján."},
     {"q": "Milyen körülmények vannak a pillangóházban?", "a": "Trópusi klíma uralkodik, körülbelül 27 Celsius-fokkal és magas páratartalommal."},
     {"q": "Láthatunk ott más állatokat is?", "a": "Igen, fürjek, kaméleonok és méhek is vannak ott."},
     {"q": "Vannak trópusi növények a kertben?", "a": "Igen, a kert tele van egzotikus növényekkel és virágokkal, amelyek a pillangók táplálékául szolgálnak."},
     {"q": "Szabad fotózni a kertben?", "a": "Igen, a makrofotósok paradicsoma, de az állatokat nem szabad megérinteni."}],
    [{"q": "Unde se află Grădina Fluturilor?", "a": "În Grevenmacher, pe malul Moselei."},
     {"q": "Ce condiții sunt în casa fluturilor?", "a": "Există un climat tropical, cu aproximativ 27 de grade Celsius și umiditate ridicată."},
     {"q": "Se pot vedea și alte animale acolo?", "a": "Da, există și prepelițe, cameleoni și albine."},
     {"q": "Există plante tropicale în grădină?", "a": "Da, grădina este plină de plante și flori exotice care servesc drept hrană fluturilor."},
     {"q": "Este permisă fotografierea în grădină?", "a": "Da, este un paradis pentru fotografii macro, dar animalele nu trebuie atinse."}],
    [{"q": "Where is the Butterfly Garden located?", "a": "In Grevenmacher on the Moselle."},
     {"q": "What conditions prevail in the butterfly house?", "a": "There is a tropical climate with about 27 degrees Celsius and high humidity."},
     {"q": "Can you see other animals there too?", "a": "Yes, there are also quails, chameleons, and bees."},
     {"q": "Are there plants from the tropics there?", "a": "Yes, the garden is full of exotic plants and flowers that serve as food for the butterflies."},
     {"q": "Is photography allowed in the garden?", "a": "Yes, it is a paradise for macro photographers, but the animals should not be touched."}]
)

add_faq("kid-landmark-syrdall-schwemm",
    [{"q": "Was ist die Syrdall Schwemm?", "a": "Ein modernes Freizeitbad und Wellnesszentrum in Niederanven."},
     {"q": "Gibt es dort Rutschen für Kinder?", "a": "Ja, es gibt eine große Rutsche und spezielle Kinderbereiche."},
     {"q": "Bietet die Syrdall Schwemm auch Außenbecken?", "a": "Ja, es gibt ein ganzjährig beheiztes Außenbecken."},
     {"q": "Was findet man im Wellnessbereich?", "a": "Verschiedene Saunen, ein Dampfbad und Entspannungszonen."},
     {"q": "Gibt es ein Bistro im Schwimmbad?", "a": "Ja, es gibt eine Gastronomie, in der man Snacks und Getränke bekommt."}],
    [{"q": "Mi az a Syrdall Schwemm?", "a": "Egy modern szabadidős fürdő és wellnessközpont Niederanvenben."},
     {"q": "Vannak csúszdák a gyerekeknek?", "a": "Igen, van egy nagy csúszda és speciális gyermekrészlegek."},
     {"q": "Vannak kültéri medencék a Syrdall Schwemmben?", "a": "Igen, van egy egész évben fűtött kültéri medencéje."},
     {"q": "Mi található a wellness részlegen?", "a": "Különböző szaunák, gőzfürdő és pihenőzónák."},
     {"q": "Van bisztró az uszodában?", "a": "Igen, működik ott vendéglátóhely, ahol snackeket és italokat lehet vásárolni."}],
    [{"q": "Ce este Syrdall Schwemm?", "a": "Un centru modern de agrement și wellness în Niederanven."},
     {"q": "Există tobogane pentru copii acolo?", "a": "Da, există un tobogan mare și zone speciale pentru copii."},
     {"q": "Syrdall Schwemm oferă și bazine exterioare?", "a": "Da, există un bazin exterior încălzit tot timpul anului."},
     {"q": "Ce se găsește în zona de wellness?", "a": "Diverse saune, o baie de aburi și zone de relaxare."},
     {"q": "Există un bistro în incinta piscinei?", "a": "Da, există o zonă de gastronomie unde se pot servi gustări și băuturi."}],
    [{"q": "What is the Syrdall Schwemm?", "a": "A modern leisure pool and wellness center in Niederanven."},
     {"q": "Are there slides for children there?", "a": "Yes, there is a large slide and special children's areas."},
     {"q": "Does the Syrdall Schwemm offer outdoor pools?", "a": "Yes, there is an outdoor pool heated year-round."},
     {"q": "What can you find in the wellness area?", "a": "Various saunas, a steam bath, and relaxation zones."},
     {"q": "Is there a bistro in the swimming pool?", "a": "Yes, there is a catering area where you can get snacks and drinks."}]
)

add_faq("kid-landmark-aquatower-berdorf",
    [{"q": "Was ist der Aquatower Berdorf?", "a": "Ein ehemaliger Wasserturm, der in einen Aussichts- und Erlebnisturm umgewandelt wurde."},
     {"q": "Wie hoch ist der Turm?", "a": "Der Turm ist 55 Meter hoch."},
     {"q": "Was kann man im Turm lernen?", "a": "Es gibt eine interaktive Ausstellung zum Thema Trinkwasser und Geologie."},
     {"q": "Welche Aussicht hat man von oben?", "a": "Einen 360-Grad-Panoramablick über das Müllerthal und bis weit über die Grenze."},
     {"q": "Gibt es dort auch Veranstaltungen?", "a": "Ja, man kann die Aussichtsplattform für private Feiern mieten."}],
    [{"q": "Mi az a berdorfi Aquatower?", "a": "Egy egykori víztorony, amelyet kilátóvá és élménytoronnyá alakítottak át."},
     {"q": "Milyen magas a torony?", "a": "A torony 55 méter magas."},
     {"q": "Mit lehet tanulni a toronyban?", "a": "Egy interaktív kiállítás mutatja be az ivóvíz és a geológia témakörét."},
     {"q": "Milyen kilátás nyílik fentről?", "a": "360 fokos panoráma nyílik a Mullerthalra és messze a határokon túlra."},
     {"q": "Tartanak ott rendezvényeket is?", "a": "Igen, a kilátóteraszt privát ünnepségekre is bérbe lehet venni."}],
    [{"q": "Ce este Aquatower Berdorf?", "a": "Un fost turn de apă transformat în turn de belvedere și experiență."},
     {"q": "Cât de înalt este turnul?", "a": "Turnul are o înălțime de 55 de metri."},
     {"q": "Ce se poate învăța în turn?", "a": "Există o expoziție interactivă despre apa potabilă și geologie."},
     {"q": "Ce vedere ai de sus?", "a": "O panoramă de 360 de grade asupra regiunii Mullerthal și mult dincolo de graniță."},
     {"q": "Au loc și evenimente acolo?", "a": "Da, platforma de belvedere poate fi închiriată pentru evenimente private."}],
    [{"q": "What is the Aquatower Berdorf?", "a": "A former water tower that has been converted into an observation and experience tower."},
     {"q": "How high is the tower?", "a": "The tower is 55 meters high."},
     {"q": "What can you learn in the tower?", "a": "There is an interactive exhibition on the subject of drinking water and geology."},
     {"q": "What view do you have from the top?", "a": "A 360-degree panoramic view over the Mullerthal and far across the border."},
     {"q": "Are there also events held there?", "a": "Yes, the observation platform can be rented for private celebrations."}]
)

add_faq("kid-landmark-vianden-chairlift",
    [{"q": "Wohin bringt einen der Sessellift in Vianden?", "a": "Vom Tal hinauf zu einem Aussichtspunkt auf 440 Metern Höhe."},
     {"q": "Kann man von der Bergstation zur Burg wandern?", "a": "Ja, es gibt einen sehr schönen Fußweg, der bergab direkt zur Burg führt."},
     {"q": "Wann ist der Sessellift in Betrieb?", "a": "Normalerweise von Ostern bis Oktober, sofern das Wetter es zulässt."},
     {"q": "Gibt es an der Bergstation eine Einkehrmöglichkeit?", "a": "Ja, es gibt ein Café mit einer Terrasse, die einen tollen Ausblick bietet."},
     {"q": "Wie viele Personen passen in einen Sessel?", "a": "Die Sessel sind für zwei Personen ausgelegt."}],
    [{"q": "Hová visz fel a viandeni libegő?", "a": "A völgyből egy 440 méter magasan fekvő kilátóponthoz."},
     {"q": "Lehet a felső állomástól a várhoz túrázni?", "a": "Igen, egy nagyon szép gyalogút vezet lefelé közvetlenül a várhoz."},
     {"q": "Mikor üzemel a libegő?", "a": "Általában húsvéttól októberig, az időjárás függvényében."},
     {"q": "Van étkezési lehetőség a felső állomáson?", "a": "Igen, található ott egy kávézó terasszal, ahonnan remek a kilátás."},
     {"q": "Hány személyesek a széékek?", "a": "A székek kétszemélyesek."}],
    [{"q": "Unde te duce telescaunul din Vianden?", "a": "Din vale până la un punct de belvedere situat la o altitudine de 440 de metri."},
     {"q": "Se poate merge pe jos de la stația de sus până la castel?", "a": "Da, există o potecă foarte frumoasă care coboară direct spre castel."},
     {"q": "Când funcționează telescaunul?", "a": "De regulă, de la Paște până în octombrie, dacă vremea permite."},
     {"q": "Există vreo posibilitate de a lua masa la stația de sus?", "a": "Da, există o cafenea cu o terasă care oferă o priveliște superbă."},
     {"q": "Câte persoane încap într-un scaun?", "a": "Scaunele sunt concepute pentru două persoane."}],
    [{"q": "Where does the chairlift in Vianden take you?", "a": "From the valley up to a viewpoint at an altitude of 440 meters."},
     {"q": "Can you hike from the mountain station to the castle?", "a": "Yes, there is a very beautiful path that leads downhill directly to the castle."},
     {"q": "When is the chairlift in operation?", "a": "Usually from Easter to October, weather permitting."},
     {"q": "Is there a place to eat at the mountain station?", "a": "Yes, there is a café with a terrace that offers a great view."},
     {"q": "How many people fit in one chair?", "a": "The chairs are designed for two people."}]
)

with open('tmp/faqs_9.json', 'w', encoding='utf-8') as f:
    json.dump(faqs, f, ensure_ascii=False, indent=2)
